      SUBROUTINE BGNS1 ( DT,     Rho,
     %                   NDIM,   NBSOM,  NBNOVI, XYZNOE,
     %                   NTDLHB, NTDLVP, NDDLNO,
     %                   NUTYEL, NBNOEF, NBDLMX, NBELEM, NUNOEF,
     %                   NBVVEF, NBSFEF, NBLAEF,
     %                   NUVVEF, NUSFEF, NULAEF,
     %                   NUMILI, NUMALI, LTDELI,
     %                   NUMISU, NUMASU, LTDESU,
     %                   NUMIVO, NUMAVO, LTDEVO,
     %                   MOARET, MXARET, MNLARE,
     %                   MOFACE, MXFACE, LFACES,
     %                   UG0,    VITMAX, AEEF,
     %                   UG1,    FG1,    FG2,  NBCHTL, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT: CONSTRUIRE ET ASSEMBLER LE SECOND MEMBRE GLOBAL BG DU PROBLEME
C ---- ( [MG(Rho)] + dt theta [KG(Mhu)] ) {u(tn+1,x)} = {Rho*u(tn,X(tn;tn+1,x))
C                  + dt * theta {fg(tn+1)} + dt * (1-theta) {fg(tn)}
C                  - dt (1-theta) [KG(Mhu)] ) {u(tn)}
C      CALCUL DU SECOND MEMBRE DU SYSTEME LINEAIRE:
C      {Rho*u(tn,X(tn;tn+1,x))   + dt * theta {fg(tn+1)}
C      + dt * (1-theta) {fg(tn)} - dt (1-theta) [KG(Mhu)] ) {u(tn)}

C ENTREES:
C --------
C DT     : PAS CONSTANT DU TEMPS
C Rho    : DENSITE DE MASSE du FLUIDE
C NDIM   : DIMENSION DE L'ESPACE DES COORDONNEES 2 ou 3
C NBSOM  : NOMBRE DE SOMMETS DU MAILLAGE
C NBNOVI : NOMBRE DE NOEUDS VITESSE SOMMETS et MILIEUX DES ARETES DES EF
C NDDLNO  : NUMERO DU DERNIER DL DE CHAQUE NOEUD VITESSE (0:NBNOVI)
C          A UTILISER POUR RETROUVER LES DL PRESSION DES VECTEURS VXYZPN0
C XYZNOE : XYZNOE(3,NBNOVI)  3 COORDONNEES DES NOEUDS DU MAILLAGE
C NTDLHB : NOMBRE TOTAL DE DEGRES DE LIBERTE DE L'OBJET HORS BARYCENTRES
C          (NDIM+1) NBSOM (SANS BARYCENTRES)
C NTDLVP : NOMBRE TOTAL DE DL VITESSE (NDIM*NBNOVI) + PRESSION NBSOM

C NUTYEL : NUMERO DU TYPE D'EF
C          ( 13 TRIANGLE, 19 TETRAEDRE BREZZI-FORTIN,
C            15 TRIANGLE, 20 TETRAEDRE TAYLOR-HOOD)
C NBNOEF : NOMBRE DE NOEUDS D'UN EF DE CE TYPE
C          ( 4 ou 6 POUR LE TRIANGLE, 5 ou 10 POUR LE TETRAEDRE)
C NBDLMX : NOMBRE DE DEGRES DE LIBERTE D'UN EF
C          ( 11 si BF2, 19 si BF3, 15 si TH2, 34 si TH3
C NBELEM : NOMBRE D'EF DU MAILLAGE
C NUNOEF : NUNOEF(NBELEM,NBNOEF) NO DES NOEUDS DES NBELEM EF

C NBVVEF : NOMBRE DE VOLUME  POUR 1 EF DE CE TYPE
C NBSFEF : NOMBRE DE FACES   POUR 1 EF DE CE TYPE
C NBLAEF : NOMBRE D'ARETES   POUR 1 EF DE CE TYPE
C NUVVEF : TABLEAU DU NUMERO DE VOLUME DE CHAQUE ELEMENT FINI
C NUSFEF : TABLEAU DU NUMERO DE SURFACE DES FACES   DE CHAQUE EF
C NULAEF : TABLEAU DU NUMERO DE LIGNE   DES ARETES  DE CHAQUE EF

C NUMILI : NUMERO MINIMAL DES OBJETS LIGNES
C NUMALI : NUMERO MAXIMAL DES OBJETS LIGNES
C LTDELI : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DU FLUIDE
C          DES OBJETS LIGNES

C NUMISU : NUMERO MINIMAL DES OBJETS SURFACES
C NUMASU : NUMERO MAXIMAL DES OBJETS SURFACES
C LTDESU : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DU FLUIDE
C          DES OBJETS SURFACES

C NUMIVO : NUMERO MINIMAL DES OBJETS VOLUMES
C NUMAVO : NUMERO MAXIMAL DES OBJETS VOLUMES
C LTDEVO : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DU FLUIDE
C          DES OBJETS VOLUMES

C MOARET : NOMBRE DE MOTS POUR LES INFO D'UNE ARETE
C MXARET : NOMBRE MAXIMAL D'ARETES DECLAREES
C MNLARE : EN 2D SEULEMENT ADRESSE MCN DU 1-ER MOT DU TABLEAU LARETE

C MOFACE : NOMBRE DE MOTS POUR LES INFO D'UNE FACE
C MXFACE : NOMBRE MAXIMAL D'FACES DECLAREES
C LFACES : TABLEAU DES FACES DU MAILLAGE  (cf hachag.f)
C          LFACES(1,I)= NO DU 1-ER  SOMMET DE LA FACE
C          LFACES(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LFACES(3,I)= NO DU 3-EME SOMMET DE LA FACE
C          LFACES(4,I)= NO DU 4-EME SOMMET DE LA FACE
C                       0 SI TRIANGLE
C          LFACES(5,I)= CHAINAGE HACHAGE SUR FACE SUIVANTE
C                       1 CUBE EST UN TETRA ou PENTA ou HEXAEDRE
C          LFACES(6,I)= NUMERO DU 1-ER  CUBE CONTENANT CETTE FACE
C                       0 SI PAS DE 1-ER  CUBE
C          LFACES(7,I)= NUMERO DU 2-EME CUBE CONTENANT CETTE FACE
C                       ou CHAINAGE SUR LA FACE FRONTALIERE SUIVANTE
C          LFACES(8,I)= NUMERO DE LA FACE A TANGENTE DANS LE TABLEAU NUTGFA
C          LFACES(9,I)= NUMERO DU TYPE DU DERNIER EF DE CETTE FACE

C UG0    : VECTEUR GLOBAL des DL VITESSES-PRESSIONS (1:NTDLVP) au TEMPS tn
C VITMAX : NORME DE LA VITESSE MAXIMALE AU TEMPS PRECEDANT

C SORTIES:
C --------
C UG1    : [-(1-THETA) DT VISCOSITE] UG0 SUR LES 3 DL  du BARYCENTRE SI BF
C FG1    : PREMIER VECTEUR GLOBAL SECOND MEMBRE ASSEMBLE
C FG2    : SECOND  VECTEUR GLOBAL SECOND MEMBRE ASSEMBLE
C NBCHTL : NOMBRE DE REMONTEES DE LA CARACTERISTIQUE TROP LONGUES
C IERR   : 0 PAS DE PROBLEME, >0 PROBLEME RENCONTRE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St Pierre du Perray  Janvier 2013
C23456---------------------------------------------------------------012
      IMPLICIT NONE
      include"./incl/donflu.inc"
      REAL              DT
      DOUBLE PRECISION  Rho, VITMAX,
     %                  UG0(NTDLVP), UG1(NTDLVP),
     %                  FG2(NTDLVP), FG1(NTDLVP),
     %                  AEEF(NBDLMX,NDIM,NBELEM)

      INTEGER           NUNOEF(NBELEM,NBNOEF), NDDLNO(0:NBNOVI)
      INTEGER           NUMILI, NUMALI, LTDELI(1:MXDOFL,NUMILI:NUMALI)
      INTEGER           NUMISU, NUMASU, LTDESU(1:MXDOFL,NUMISU:NUMASU)
      INTEGER           NUMIVO, NUMAVO, LTDEVO(1:MXDOFL,NUMIVO:NUMAVO)
      INTEGER           NUVVEF(NBVVEF,NBELEM), NUSFEF(NBSFEF,NBELEM),
     %                  NULAEF(NBLAEF,NBELEM)

      REAL              XYZNOE(3,NBNOVI)
      INTEGER           NDIM,   NBSOM,  NOBARY, NTDLHB, NTDLVP,
     %                  NBDLMX, NRDLEF, NBNOVI,
     %                  NBVVEF, NBSFEF, NBLAEF,
     %                  NUTYEL, NBELEM, NBNOEF,
     %                  MOARET, MXARET, MNLARE,
     %                  MOFACE, MXFACE, LFACES(MOFACE,MXFACE),
     %                  NBCHTL, IERR

      DOUBLE PRECISION  BE1(34), BE2(34)
      INTEGER           NONOEF(10), NOGLDL(34), NUELEM, N, I
      REAL              COORDP(NBNOEF,3)

C     LA BOUCLE SUR LES ELEMENTS FINIS TAYLOR-HOOD ou BREZZI-FORTIN
C     ICI, UN SEUL TYPE D'ELEMENT FINI
ccc   NTYEF  = 1

C     NOMBRE DE CHEMIN TROP LONG POUR REMONTER LA CARACTERISTIQUE
ccc   NBCHTL = 0

C     NUMERO DU NOEUD BARYCENTRE
      NOBARY = NDIM + 2

      DO 100 NUELEM = 1, NBELEM

C        NO DES NOEUDS DE L'ELEMENT FINI NUELEM
C        INTERPOLATION DU FLUIDE avec F: echapeau->e  P1 ndim
C        COORDONNEES DES POINTS=NOEUDS DE L'ELEMENT FINI
         DO I = 1, NBNOEF
C           NUMERO DU NOEUD
            N = NUNOEF(NUELEM,I)
            NONOEF(I) = N
            COORDP(I,1) = XYZNOE(1,N)
            COORDP(I,2) = XYZNOE(2,N)
            COORDP(I,3) = XYZNOE(3,N)
         ENDDO
C
         IF( NUTYEL .EQ. 13 ) THEN
C
C           TRIANGLE BREZZI-FORTIN P1BULLEP3 EN VITESSE et P1 EN PRESSION
C           -------------------------------------------------------------
C           NO DU BARYCENTRE D'UN EF BREZZI-FORTIN
            NONOEF(NOBARY) = NBSOM + NUELEM
C
C           UG1 = [-(1-THETA) DT VISCOSITE] UG0 SUR LES 2 DL du BARYCENTRE
            CALL GP2P1BP1( NTDLHB, NUELEM, NONOEF, AEEF(1,1,NUELEM),UG0,
     %                     UG1 )
C
C           SECOND MEMBRE ELEMENTAIRE AVEC 4+4+3=11 DEGRES DE LIBERTE DES FORCES
            CALL F2SP1BP1( COORDP,
     %                     NULAEF(1,NUELEM), NUMILI, NUMALI, LTDELI,
     %                     NUSFEF(1,NUELEM), NUMISU, NUMASU, LTDESU,
     %                     BE2 )
C
C           ASSEMBLAGE DES DEGRES DE LIBERTE 4 ET 8 DE SE DANS FG2
C           COMPRESSION DE 11 A 9 DEGRES DE LIBERTE DE SE
            CALL GS2P1BP1( NTDLHB, NUELEM, BE2,  FG2 )
C
C           SECOND MEMBRE ELEMENTAIRE du TRANSPORT pour NAVIER-STOKES
C           avec 4+4+3 COEFFICIENTS (LES 3 DERNIERS SONT NULS)
            CALL F2SNVP1BP1( NUELEM, 1, NBELEM, NUNOEF,
     %                       MOARET, MXARET, MNLARE,
     %                       DT, Rho, XYZNOE, NDDLNO,
     %                       NTDLHB, UG0, VITMAX,
     %                       BE1, IERR )
C
C           ASSEMBLAGE DES DEGRES DE LIBERTE 4 ET 8 DE SE DANS FG1
C           COMPRESSION DE 11 A 9 DEGRES DE LIBERTE DE SE => 3+3+3 COEFFICIENTS
            CALL GS2P1BP1( NTDLHB, NUELEM, BE1,  FG1 )
C
C
         ELSE IF( NUTYEL .EQ. 19 ) THEN
C
C           TETRAEDRE BREZZI-FORTIN P1BULLEP4 EN VITESSE et P1 EN PRESSION
C           --------------------------------------------------------------
C           NO DU BARYCENTRE D'UN EF BREZZI-FORTIN
            NONOEF(NOBARY) = NBSOM + NUELEM
C
C           LE CALCUL DE UG1 EST COMPLETE POUR LES DL 5 10 15 du BARYCENTRE
C           UG1 = [-(1-THETA) DT VISCOSITE] UG0 SUR LES 3 DL  du BARYCENTRE
            CALL GP3P1BP1( NTDLHB, NUELEM, NONOEF, AEEF(1,1,NUELEM),UG0,
     %                     UG1 )
C
C           SECOND MEMBRE ELEMENTAIRE DES FORCES
            CALL F3SP1BP1( COORDP,
     %                     NUSFEF(1,NUELEM), NUMISU, NUMASU, LTDESU,
     %                     NUVVEF(1,NUELEM), NUMIVO, NUMAVO, LTDEVO,
     %                     BE2 )
C
C           ASSEMBLAGE DES DEGRES DE LIBERTE 5 10 15 DE SE DANS FG2
C           COMPRESSION DE 19 A 16 DEGRES DE LIBERTE DE SE
            CALL GS3P1BP1( NTDLHB, NUELEM, BE2,  FG2 )
C
C           SECOND MEMBRE ELEMENTAIRE du TRANSPORT pour NAVIER-STOKES
C           avec 5+5+5+4 COEFFICIENTS (LES 4 DERNIERS SONT NULS)
            CALL F3SNVP1BP1( NUELEM, NBELEM, NUNOEF,
     %                       MOFACE, MXFACE, LFACES,
     %                       DT, Rho, XYZNOE, NDDLNO,
     %                       NTDLHB,  UG0, VITMAX,
     %                       BE1, IERR )
C
C           ASSEMBLAGE DES DEGRES DE LIBERTE 5 10 15 DE SE DANS FG1
C           COMPRESSION DE 19 A 16 DEGRES DE LIBERTE DE SE
            CALL GS3P1BP1( NTDLHB, NUELEM, BE1,  FG1 )
C
         ELSE IF( NUTYEL .EQ. 15 ) THEN
C
C           TRIANGLE TAYLOR-HOOD P2 EN VITESSE et P1 EN PRESSION
C           ----------------------------------------------------
C           SECOND MEMBRE ELEMENTAIRE DES FORCES
            CALL F2SP2P1( COORDP,
     %                    NULAEF(1,NUELEM), NUMILI, NUMALI, LTDELI,
     %                    NUSFEF(1,NUELEM), NUMISU, NUMASU, LTDESU,
     %                    BE2 )
C
C           SECOND MEMBRE ELEMENTAIRE du TRANSPORT pour NAVIER-STOKES
            CALL F2SNVP2P1(NUELEM, 1, NBELEM, NUNOEF,
     %                     MOARET, MXARET, MNLARE,
     %                     DT, Rho, XYZNOE, NDDLNO,
     %                     UG0, VITMAX,
     %                     BE1, IERR )
C
         ELSE IF( NUTYEL .EQ. 20 ) THEN
C
C           TETRAEDRE TAYLOR-HOOD P2 EN VITESSE et P1 EN PRESSION
C           -----------------------------------------------------
C           SECOND MEMBRE ELEMENTAIRE
            CALL F3SP2P1( COORDP,
     %                    NUSFEF(1,NUELEM), NUMISU, NUMASU, LTDESU,
     %                    NUVVEF(1,NUELEM), NUMIVO, NUMAVO, LTDEVO,
     %                    BE2 )
C
C           SECOND MEMBRE ELEMENTAIRE du TRANSPORT pour NAVIER-STOKES
            CALL F3SNVP2P1(NUELEM, NBELEM, NUNOEF,
     %                     MOFACE, MXFACE, LFACES,
     %                     DT, Rho, XYZNOE, NDDLNO,
     %                     UG0, VITMAX,
     %                     BE1, IERR )
C
         ENDIF
         IF( IERR .EQ. 4 ) NBCHTL = NBCHTL + 1
C
C        NOGLDL: NUMERO GLOBAL DES DEGRES DE LIBERTE DE L'ELEMENT FINI
C        -------------------------------------------------------------
         CALL NUGDLE( NDIM,   NUTYEL, NBDLMX, NBNOVI,
     %                NONOEF, NDDLNO,
     %                NRDLEF, NOGLDL, IERR )
C
C        ASSEMBLAGE DU VECTEUR TRANSPORT BE1 DANS LE TABLEAU GLOBAL FG1
C        ASSEMBLAGE DU VECTEUR FORCE     BE2 DANS LE TABLEAU GLOBAL FG2
C        --------------------------------------------------------------
         DO I=1,NRDLEF
C
C           LE NO GLOBAL DU I-EME DEGRE DE LIBERTE LOCAL DANS L'EF
            N = NOGLDL( I )
C
C           ASSEMBLAGE DE LA I-EME COMPOSANTE DE BE DANS BG
            FG1( N ) = FG1( N ) + BE1(I)
            FG2( N ) = FG2( N ) + BE2(I)
C
         ENDDO
C
 100  CONTINUE
C
C     FIN DE LA BOUCLE SUR LES EF POUR LA CONSTRUCTION DE UG1, FG1, FG2
      RETURN
      END
