      SUBROUTINE CONVECBF( tn, tn1, NDIM,  NBSOM,  XYZSOM,
     %                     NBNOEF, NBELEM, NUNOEF, NU1EFN,
     %                     MOARET, MXARET, MNLARE,
     %                     MOFACE, MXFACE, MNLFAC,
     %                     NDDLNO, NTDLHB, VXYZPN0, VITMAX0,
     %                     NBNOVI, VITCON, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCUL DE LA VITESSE ui(tn,X(tn;tn+1,NOSOMT)) CONVECTEE EN LES
C ----- NBSOM SOMMETS DU MAILLAGE DE TRIANGLES ou TETRAEDRES BREZZI-FORTIN
C       PAR REMONTEE DE LA CARACTERISTIQUE en chaque SOMMET sur UN TEMPS DT
C       PROBLEME de NAVIER STOKES sur des EF TAYLOR HOOD
C       INTEGRATION RETROGRADE DES CARACTERISTIQUES cf O. PIRONNEAU
C       POLYNOME P1-LAGRANGE + FONCTION BULLE POUR LA VITESSE
C       POLYNOME LAGRANGE DE DEGRE 1 POUR LA PRESSION
C       TRIANGLE ELEMENT FINI: e ref -> e EST P1 POUR CHAQUE COORDONNEE
C
C ATTENTION: LES VITESSES CONVECTEES AUX BARYCENTRES DES EF NE SONT PAS CALCULEES
C
C ENTREES:
C --------
C tn, tn1: INTERVALLE DE TEMPS tn tn+1  => DT PAS du TEMPS = tn1-tn
C DT     : LE PAS CONSTANT DE TEMPS ENTRE tn ET tn+1
C NBSOM  : NOMBRE DE SOMMETS DU MAILLAGE
C XYZSOM : 3 COORDONNEES DES SOMMETS ET MILIEUX DES ARETES DES EF
C NBNOEF : NOMBRE DE SOMMETS D'UN TRIANGLE = 6 et TETRAEDRE = 10
C NBELEM : NOMBRE DE TETRAEDRES DU MAILLAGE
C NUNOEF : NUMERO DES 3 ou 4 SOMMETS DES EF DU MAILLAGE
C NU1EFN : NUMERO D'UN EF CONTENANT LE SOMMET

C MOFACE : NOMBRE DE MOTS DE CHAQUE FACE DU TABLEAU LFACES
C MXFACE : NOMBRE MAXIMAL D'FACES DU TABLEAU LFACES
C MNLFAC : ADRESSE MCN DU TABLEAU LFACES cf hachag.f

C NDDLNO : TABLEAU DES POINTEURS SUR LE DERNIER DL DE CHAQUE SOMMET FLUIDE
C          CE TABLEAU EST DIMENSIONNE A 1+NBNOEU
C NTDLHB : NOMBRE TOTAL DE DEGRES DE LIBERTE DE L'OBJET HORS BARYCENTRES
C VXYZPN0: VECTEUR GLOBAL des DL VITESSES-PRESSIONS (1:NTDLHB) au TEMPS tn
C          SUIVI DES NDIM VITESSES AU BARYCENTRE DES TETRAEDRES
C VITMAX0: NORME DE LA VITESSE MAXIMALE DE VXYZPN0 AUX SOMMETS
C NBNOVI : NOMBRE DE NOEUDS VITESSE = SOMMETS + BARYCENTRE DES EF BF
C
C SORTIES:
C --------
C VITCON : VITESSE CONVECTEE de DT aux SOMMETS  ui(tn,X(tn;tn+1,NOSOMT))
C IERR   : CODE D'ERREUR 0 PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St Pierre du Perray Decembre 2012
C23456---------------------------------------------------------------012
      IMPLICIT NONE
      REAL               tn, tn1, DT, XYZSOM(3,NBSOM)
      INTEGER            NDIM,   NBSOM, NBNOEF, NBELEM, NTDLHB,
     %                   MOARET, MXARET, MNLARE,
     %                   MOFACE, MXFACE, MNLFAC,
     %                   NUNOEF(NBELEM,NBNOEF), NDDLNO(0:NBSOM),
     %                   NU1EFN(NBSOM), IERR, NBNOVI
      DOUBLE PRECISION   VXYZPN0(1:*), VITMAX0, VITCON(NBNOVI,NDIM)

      DOUBLE PRECISION   V(3)
      INTEGER            NOSOMT

C     PAS DE TEMPS ENTRE tn et tn+1
      DT = tn1 - tn

      IF( NDIM .EQ. 2 ) THEN

C        TRIANGLES BREZZI-FORTIN
         DO NOSOMT = 1, NBSOM

C           VITESSE CONVECTEE DU SOMMET NOSOMT
            CALL CONVECBF2( NOSOMT,  NU1EFN(NOSOMT), NBELEM, NUNOEF,
     %                      MOARET,  MXARET, MNLARE, DT, XYZSOM, NDDLNO,
     %                      NTDLHB,  VXYZPN0, VITMAX0,
     %                      V,       IERR )
            VITCON(NOSOMT,1) = V(1)
            VITCON(NOSOMT,2) = V(2)

         ENDDO
C
      ELSE

C        TETRAEDRES BREZZI-FORTIN
         DO NOSOMT = 1, NBSOM

C           VITESSE CONVECTEE DU SOMMET NOSOMT
            CALL CONVECBF3( NOSOMT,  NU1EFN(NOSOMT), NBELEM, NUNOEF,
     %                      MOFACE,  MXFACE, MNLFAC, DT, XYZSOM, NDDLNO,
     %                      NTDLHB,  VXYZPN0, VITMAX0,
     %                      V,       IERR )
            VITCON(NOSOMT,1) = V(1)
            VITCON(NOSOMT,2) = V(2)
            VITCON(NOSOMT,3) = V(3)

         ENDDO

      ENDIF

ccc      call affvect( 'convecbf.f: VITESSEx',     20,     VITCON )
ccc      call afl1ve(  'convecbf.f: VITESSE ', NBSOM*NDIM, VITCON )

      RETURN
      END
