      SUBROUTINE CONVECTH5( DT,     NDIM,    NBNOVI, XYZPOI,
     %                      NBNOEF, NBELEM,  NUNOEF, NU1EFN,
     %                      MOARET, MXARET,  MNLARE,
     %                      MOFACE, MXFACE,  LFACES,
     %                      NDDLNO, VXYZPN0, VITMAX0,
     %                      VITCON, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCUL DE LA VITESSE ui(tn,X(tn;tn+1,NONOEU)) CONVECTEE EN TOUS
C ----- LES NOEUDS DU MAILLAGE DE TRIANGLES ou TETRAEDRES TAYLOR-HOOD
C       PAR REMONTEE DE LA CARACTERISTIQUE en chaqueNOEUD sur UN TEMPS DT
C       PROBLEME de NAVIER STOKES sur des EF TAYLOR HOOD
C       INTEGRATION RETROGRADE DES CARACTERISTIQUES cf O. PIRONNEAU
C       POLYNOME LAGRANGE DE DEGRE 2 POUR LA VITESSE
C       POLYNOME LAGRANGE DE DEGRE 1 POUR LA PRESSION
C       TRIANGLE ELEMENT FINI: e ref -> e EST P1 POUR CHAQUE COORDONNEE
C
C ENTREES:
C --------
C DT     : LE PAS CONSTANT DE TEMPS ENTRE tn ET tn+1
C NBNOVI : NOMBRE DE NOEUDS DU MAILLAGE
C XYZPOI : 3 COORDONNEES DES SOMMETS ET MILIEUX DES ARETES DES EF
C NBNOEF : NOMBRE DE NOEUDS D'UN TRIANGLE = 6 et TETRAEDRE = 10
C NBELEM : NOMBRE DE TETRAEDRES DU MAILLAGE
C NUNOEF : NUMERO DES 3 ou 4 SOMMETS ET 3 ou 6 MILIEUX DES ARETES DES EF
C NU1EFN : NUMERO D'UN EF CONTENANT LE NOEUD

C MOFACE : NOMBRE DE MOTS DE CHAQUE FACE DU TABLEAU LFACES
C MXFACE : NOMBRE MAXIMAL D'FACES DU TABLEAU LFACES
C LFACES : ADRESSE MCN DU TABLEAU LFACES cf hachag.f

C NDDLNO : TABLEAU DES POINTEURS SUR LE DERNIER DL DE CHAQUE NOEUD FLUIDE
C          CE TABLEAU EST DIMENSIONNE A 1+NBNOVI (VXYZ+PRESSION)
C VXYZPN0: VECTEUR GLOBAL des DL VITESSES-PRESSIONS (1:NTDL) au TEMPS tn
C VITMAX0: NORME DE LA VITESSE MAXIMALE DE VXYZPN0 AUX NOEUDS
C
C SORTIES:
C --------
C VITCON : VITESSE CONVECTEE de DT aux NOEUDS  ui(tn,X(tn;tn+1,NONOEU))
C          ATTENTION LES AUTRES DEGRES DE LIBERTE NE SONT PAS MODIFIES
C IERR   : CODE D'ERREUR 0 PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St Pierre du Perray Decembre 2012
C23456---------------------------------------------------------------012
      IMPLICIT NONE
      REAL               DT, XYZPOI(3,NBNOVI)
      INTEGER            NDIM,   NBNOVI, NBNOEF, NBELEM,
     %                   MOARET, MXARET, MNLARE,
     %                   MOFACE, MXFACE, LFACES(MOFACE,MXFACE),
     %                   NUNOEF(NBELEM,NBNOEF), NDDLNO(0:NBNOVI),
     %                   NU1EFN(NBNOVI), IERR, NDL
      DOUBLE PRECISION   VXYZPN0(1:*), VITMAX0, VITCON(*)

      DOUBLE PRECISION   V(3)
      INTEGER            NONOEU

      IF( NDIM .EQ. 2 ) THEN

C        TRIANGLES TAYLOR-HOOD
         DO NONOEU = 1, NBNOVI

C           VITESSE CONVECTEE DU NOEUD NONOEU
            CALL CONVECTH2( NONOEU,  NU1EFN(NONOEU), NBELEM, NUNOEF,
     %                      MOARET,  MXARET, MNLARE, DT, XYZPOI, NDDLNO,
     %                      VXYZPN0, VITMAX0,
     %                      V,       IERR )
            NDL = NDDLNO( NONOEU - 1 )
            VITCON(NDL+1) = V(1)
            VITCON(NDL+2) = V(2)

         ENDDO
C
      ELSE

C        TETRAEDRES TAYLOR-HOOD
         DO NONOEU = 1, NBNOVI

C           VITESSE CONVECTEE DU NOEUD NONOEU
            CALL CONVECTH3( NONOEU,  NU1EFN(NONOEU), NBELEM, NUNOEF,
     %                      MOFACE,  MXFACE, LFACES, DT, XYZPOI, NDDLNO,
     %                      VXYZPN0, VITMAX0,
     %                      V,       IERR )
            NDL = NDDLNO( NONOEU - 1 )
            VITCON(NDL+1) = V(1)
            VITCON(NDL+2) = V(2)
            VITCON(NDL+3) = V(3)

         ENDDO
C
      ENDIF

ccc      call affvect( 'convecth.f: VITESSEx',     20,      VITCON )
ccc      call afl1ve(  'convecth.f: VITESSE ', NBNOVI*NDIM, VITCON )

      RETURN
      END
