SUBROUTINE DLGABF( NDIM,  NBELEM, NBNOEF, NUNOEF, NBDLAG, AGGAUSS, &
                   NBSOM, NBNOVI, VITESSE )
! ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
! BUT :  CALCUL PAR REMONTEE DE GAUSS DES DEGRES DE LIBERTE VITESSE
! -----  INTERNES AU TRIANGLE ou TETRAEDRE BREZZI-FORTIN
!        A PARTIR DU SECOND MEMBRE STOCKE DANS VITESSE AU DELA DE NBSOM

! ENTREES:
! --------
! NDIM   : 2 ou 3 DIMENSION DE L'ESPACE DU FLUIDE
! NBELEM : NOMBRE DE TETRAEDRES DU MAILLAGE
! NBNOEF : NOMBRE DE NOEUDS D'UN TETRAEDRE (P1B 2d=>4, P1B 3d=>5)
! NUNOEF : NO DES NBNOEF NOEUDS DES NBELEM TRIANGLES ou TETRAEDRES
! NBDLAG : NOMBRE DE COLONNES DE AGGAUSS STOCKEES LORS DE L'ELIMINATION
!          DE GAUSS OU NOMBRE DE DL DE L'INTERPOLATION DE BREZZI-FORTIN
!          NOMBRE DE SOMMETS DE L'EF + 1
! NBELEM : NOMBRE D'EF DU MAILLAGE DU FLUIDE
! AGGAUSS: LIGNE DE AE D'UNE COMPOSANTE DE LA VITESSE ELIMINEE PAR GAUSS
! NBSOM  : NOMBRE DE SOMMETS DU MAILLAGE
! NBNOVI : NOMBRE DE NOEUDS VITESSE (NBSOM+NBELEM)

! MODIFIES:
! --------
! VITESSE: EN ENTREE NDIM VITESSES SOLUTIONS AUX SOMMETS DES EF
!          EN SORTIE IDEM + NDIM VITESSES SOLUTIONS AU BARYCENTRE DES EF
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
! AUTEUR: ALAIN PERRONNET LJLL UPMC Saint Pierre du Perray Decembre 2012
!23456---------------------------------------------------------------012
!$ USE OMP_LIB
      IMPLICIT NONE
      include"./incl/threads.inc"
      DOUBLE PRECISION  AGGAUSS( NBDLAG, NBELEM )
      DOUBLE PRECISION  VITESSE( NBNOVI, NDIM ), S
      INTEGER           NDIM,   NBELEM, NBNOEF, NUNOEF( NBELEM, NBNOEF),&
                        NBDLAG, NBSOM,  NBNOVI
      INTEGER           NUELEM, NUBARY, K, I, NS

!     LA BOUCLE SUR LES ELEMENTS FINIS
!     =================================
!///////////////////////////////////////////////////////////////////////
!$OMP PARALLEL PRIVATE( NUELEM, NUBARY, K, I, NS, S )
!$OMP DO SCHEDULE( STATIC, NBELEM/NBTHREADS )
      DO NUELEM = 1, NBELEM

!        LE NO GLOBAL DU DL A CALCULER ASSOCIE AU BARYCENTRE
         NUBARY = NBSOM + NUELEM

!        REMONTEE DES DL ELIMINES PAR GAUSS
         DO K = NDIM, 1, -1

!           LE SECOND MEMBRE ASSOCIE AU BARYCENTRE COMPOSANTE K
            S = VITESSE( NUBARY, K )

!           REMONTEE DES COEFFICIENTS DE LA LIGNE DE AGGAUSS
            DO I = 1, NBDLAG-1
               NS = NUNOEF( NUELEM, I )
               S = S - AGGAUSS( I, NUELEM ) * VITESSE( NS, K )
            ENDDO

!           LE DL K VITESSE AU BARYCENTRE DE CET EF NUELEM
            VITESSE( NUBARY, K ) = S / AGGAUSS( NBDLAG, NUELEM )

         ENDDO

      ENDDO
!$OMP END DO
!$OMP END PARALLEL
!///////////////////////////////////////////////////////////////////////

!!!      call affvect('Fin dlgabf.f95 VITESSE=', 20, VITESSE )
!!!      call afl1ve( 'Fin dlgabf.f95 VITESSE=', NBNOVI*NDIM, VITESSE )

      RETURN
END SUBROUTINE DLGABF
