      SUBROUTINE DLVBBF( NDIM, MNNPEF, NBDLAG, NBELEM, AGAUSS,
     %                   NTDL, NTDLF, VXYZPN )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL PAR REMONTEE DE GAUSS DES DEGRES DE LIBERTE VITESSE
C -----    INTERNES AU TRIANGLE ou TETRAEDRE BREZZI-FORTIN
C          A PARTIR DU SECOND MEMBRE STOCKE DANS VXYZPN AU DELA DE NTDL
C
C ENTREES:
C --------
C NDIM   : 2 ou 3 DIMENSION DE L'ESPACE DU FLUIDE
C MNNPEF : ADRESSE MCN DU TABLEAU NPEF DU FLUIDE
C NBDLAG : NOMBRE DE COLONNES DE A STOCKEES LORS DE L'ELIMINATION DE GAUSS
C NBELEM : NOMBRE D'EF DU MAILLAGE DU FLUIDE
C AGAUSS : NDIM LIGNES DE AE et BE DES DL VITESSE INTERNES
C NTDL   : NOMBRE DE DL VITESSE PRESSION APRES GAUSS ( NBSOM * (NDIM+1) )
C          ICI CES DL SONT SUPPOSES CALCULES
C NTDLF  : NOMBRE DE DL VITESSES PRESSIONS APRES REMONTEE DE GAUSS
C          ( NBSOM * (NDIM+1) + NDIM * NBELEM )
C
C MODIFIES:
C --------
C VXYZPN : EN ENTREE VITESSE-PRESSIONS SOLUTIONS AUX SOMMETS DES EF
C          EN SORTIE IDEM + VITESSE-PRESSIONS SOLUTIONS AU BARYCENTRE DES EF
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC Saint Pierre du Perray Decembre 2008
C23456---------------------------------------------------------------012
      include"./incl/a___npef.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/ponoel.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
C
      DOUBLE PRECISION  AGAUSS( NBDLAG, NDIM, NBELEM )
      DOUBLE PRECISION  VXYZPN( NTDLF )
C
      INTEGER           NONOEF(4), NOGLDL(19)
      DOUBLE PRECISION  S
C
C     MNELE : ADRESSE DU TABLEAU NPEF"TYPE EF
      MNELE = MCN( MNNPEF )
C
C     NOMBRE DE SOMMETS DE L'EF
      NBSTEF = NDIM + 1
C
C     NO DU DL DU BARYCENTRE DANS L'INTERPOLATION BREZZI-FORTIN
      NODLBA = NBSTEF + 1
C
C     LA BOUCLE SUR LES ELEMENTS FINIS
C     =================================
      DO 80 NUELEM = 1, NBELEM
C
C        NO DES NOEUDS DE L'ELEMENT FINI NUELEM
         CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOEF )
C
C        NO GLOBAL DES DL DE L'EF
         CALL NODLEFBF( NDIM, NTDL, NUELEM, NONOEF, NOGLDL )
C
C        REMONTEE DES DL ELIMINES PAR GAUSS
         DO 50 K = NDIM, 1, -1
C
C           LE NO LOCAL DU DL A CALCULER
            NL = K * NODLBA
C
C           NUMERO GLOBAL DU DL A CALCULER
            NG = NOGLDL( NL )
C
C           LE SECOND MEMBRE NG
            S  = VXYZPN( NG )
C
C           REMONTEE DES COEFFICIENTS DE LA LIGNE
            DO 40 I = 1, NBDLAG
               IF( I .NE. NL ) THEN
                  S = S - AGAUSS( I, K, NUELEM ) * VXYZPN( NOGLDL(I) )
               ENDIF
 40         CONTINUE
C
C           LE DL K VITESSE NG AU BARYCENTRE DE CET EF NUELEM
            VXYZPN( NG ) = S / AGAUSS( NL, K, NUELEM )
C
 50      CONTINUE
C
 80   CONTINUE
C
      RETURN
      END
