      SUBROUTINE ECFIVIPRTE( KNOMOB,  TEMPS, NOVVIPR, NAVSTO, NBPASDT,
     %                       NDIM,    NBNOEVIT, NBNOEPRE, NBNOETEM,
     %                       NTDLVP,  VXYZPN, NTDLTE, TEMPER,
     %                       KNOMFIC, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     CREATION et ECRITURE du VECTEUR VXYZPN + TEMPER
C -----     DANS UN FICHIER NOVVIPR de
C           NTDLVP DEGRES DE LIBERTE DES VITESSES+PRESSION
C           NTDLTE DEGRES DE TEMPERATURE
C           de NUMERO de FICHIER NOVVIPR AU TEMPS TEMPS
C           dans le REPERTOIRE Unix du PROJET Mefisto

C ENTREES:
C --------
C KNOMOB : NOM DE L'OBJET DANS LE LEXIQUE des OBJETS
C TEMPS  : TEMPS ASSOCIE au VECTEUR VITESSE_XYZ+PRESSION+TEMPERATURE A STOCKER
C NOVVIPR: >0 NO DU VECTEUR VITESSE_XYZ+PRESSION+TEMPERATURE
C             SUR LE FICHIER ECRIT dans le REPERTOIRE du PROJET Mefisto

C NAVSTO :-1 POUR RESOUDRE LE PROBLEME DE STOKES   STATIONNAIRE
C          0 POUR RESOUDRE LE PROBLEME DE STOKES INSTATIONNAIRE
C          1 POUR RESOUDRE LE PROBLEME DE NAVIER-STOKES SOUS FORME IMPLICITE
C          2 POUR RESOUDRE LE PROBLEME DE NAVIER-STOKES PAR PAS FRACTIONNAIRES
C          3 POUR RESOUDRE LE PROBLEME DE NAVIER-STOKES + THERMIQUE
C          4 POUR RESOUDRE LE PROBLEME DE NAVIER-STOKES PAR PISO+CARACTERISTIQUE
C          5 POUR RESOUDRE LE PROBLEME DE NAVIER-STOKES PAR PISO+(V.D) V

C NBPASDT:  NOMBRE DE PAS DE TEMPS DEJA CALCULES
C           D'UN FICHIER VITESSE+PRESSION et eventuellement TEMPERATURE

C NDIM    : 2 ou 3 DIMENSION DE L'ESPACE DE TRAVAIL
C NBNOEVIT: NOMBRE DE NOEUDS SUPPORTS DE LA VITESSE
C NBNOEPRE: NOMBRE DE NOEUDS SUPPORTS DE LA PRESSION
C NBNOETEM: NOMBRE DE NOEUDS SUPPORTS DE LA TEMPERATURE

C NTDLVP  : NOMBRE TOTAL DE DEGRES DE LIBERTE EN VITESSE_XYZ+PRESSION
C VXYZPN  : NTDLVP DEGRES DE LIBERTE DU  VECTEUR VITESSE_XYZ+PRESSION
C           AUX NOEUDS DU MAILLAGE POUR LA VITESSE+PRESSION

C NTDLTE  : NOMBRE TOTAL DE DEGRES DE LIBERTE EN TEMPERATURE
C TEMPER  : NTDLTE DEGRES DE LIBERTE DU VECTEUR TEMPERATURE
C           AUX NOEUDS DU MAILLAGE POUR LA TEMPERATURE

C SORTIES:
C --------
C KNOMFIC : NOM du FICHIER SUPPORT du VECTEUR NOVVIPR des VITESSE_XYZ+PRESSION
C IERR    : =0 SI PAS D'ERREUR DETECTEE, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  Saint Pierre du Perray             Aout 2020
C MODIFS : ALAIN PERRONNET  Saint Pierre du Perray            Avril 2021
C MODIFS : ALAIN PERRONNET  Saint Pierre du Perray            Avril 2022
C23456---------------------------------------------------------------012
      include"./incl/langue.inc"
      CHARACTER*(*)     KNOMOB
      CHARACTER*(*)     KNOMFIC
      LOGICAL           LEXIST, LOPEN
      DOUBLE PRECISION  VXYZPN(NTDLVP), TEMPER(NTDLTE)

      IF( NTDLTE .EQ. 0 .AND. NBNOETEM .NE. 0 ) THEN
         PRINT*,'ecfiviprte: INCOHERENCE NTDLTE=',NTDLTE,
     %          ' NBNOETEM=',NBNOETEM,' EST FIXE A ZERO'
         NBNOTE = 0
      ELSE
         NBNOTE = NBNOETEM
      ENDIF

C     LE NOM DU FICHIER du VECTEUR VITESSE-PRESSION
      CALL NMFIVIPRTE( KNOMOB, TEMPS, NOVVIPR,  KNOMFIC, NBK )

C     SI LE FICHIER KNOMFIC(1:NBK) EXISTE ALORS IL EST DETRUIT PUIS RECONSTRUIT
      INQUIRE( FILE=KNOMFIC(1:NBK), EXIST=LEXIST, OPENED=LOPEN )
      IF( LEXIST ) THEN
C        LE FICHIER KNOMFIC(1:NBK) EXISTE
         IF( .NOT. LOPEN ) THEN
C           OUVERTURE DU FICHIER KNOMFIC(1:NBK)
            CALL TRUNIT( NFUNIT )
            OPEN( FILE=KNOMFIC(1:NBK), UNIT=NFUNIT, STATUS='OLD' )
         ENDIF
C        DESTRUCTION DU FICHIER
         CLOSE( NFUNIT, STATUS='DELETE' )
      ENDIF

C     CREATION DU NOUVEAU FICHIER KNOMFIC(1:NBK)
      CALL TRUNIT( NFUNIT )
      OPEN( UNIT=NFUNIT, FILE=KNOMFIC(1:NBK), STATUS='NEW',
     %      ACCESS='SEQUENTIAL', FORM='UNFORMATTED',
     %      IOSTAT=IOERR, ERR=9998 )

C     LE PREMIER ENREGISTREMENT DU FICHIER KNOMFIC(1:NBK)
C     et DERNIER ENREGISTREMENT DU FICHIER KNOMFIC(1:NBK)
C     LES NTDLVP DL DE LA VITESSE ET DE LA PRESSION AUX NOEUDS DU MAILLAGE
C     SONT ECRITS EN BINAIRE DIRECTEMENT SUR LE FICHIER KNOMFIC(1:NBK)
      WRITE(NFUNIT) NAVSTO,   NBPASDT,  NDIM,
     %              NBNOEVIT, NBNOEPRE, NBNOTE,
     %              NTDLVP,   NTDLTE

C     ECRITURE DU VECTEUR VITESSE+PRESSION
      IF( NTDLVP .GT. 0 ) THEN
         WRITE(NFUNIT) (VXYZPN(I),I=1,NTDLVP)
      ENDIF

C     ECRITURE DU VECTEUR TEMPERATURE
      IF( NTDLTE .GT. 0 ) THEN
         WRITE(NFUNIT) (TEMPER(I),I=1,NTDLTE)
      ENDIF

C     FERMETURE DU FICHIER KNOMFIC(1:NBK)
      CLOSE( NFUNIT )

C     AFFICHAGE
      IF( LANGAG .EQ. 0 ) THEN
       PRINT 10011, NAVSTO, NBPASDT, NDIM, NBNOEVIT, NBNOEPRE, NBNOTE,
     %              NTDLVP, NTDLTE,  KNOMFIC(1:NBK)
10011 FORMAT(' ecfiviprte: Ecriture de NAVSTO=',I2,
     %' NbPasTemps=',I8,
     %' DimensionEspace=',I1,
     %' NbNOEUDSVitesse=',I9,' NbNoeudsPression=',I9,
     %' NbNoeudsTemperature=',I9,/,
     %' + NtDLVP=',I10,' reel8 Vitesse+Pression +NtDLTE=',I10,
     %' reel8 Temperature surFICHIER ',A)

      ELSE
       PRINT 20011, NAVSTO, NBPASDT, NDIM, NBNOEVIT, NBNOEPRE, NBNOTE,
     %              NTDLVP, NTDLTE,  KNOMFIC(1:NBK)
20011 FORMAT(' ecfiviprte: WRITING of NAVSTO=',I1,
     %' StepTimeNb=',I8,
     %' SpaceDimension=',I1,
     %' VelocityNodesNb=',I9,' PressureNodesNb=',I9,
     %' TemperatureNodesNb=',I9,/,
     %' + NtDFVP=',I10,' Velocity+Pressure real8 +NtDFTE=',I10,
     %' Temperature real8 onFILE ',A)

      ENDIF

      IERR = 0
      GOTO 9999


C     TRAITEMENT DES ERREURS
 9998 IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'ecfiviprte: Le FICHIER ',KNOMFIC,' UNITE',NFUNIT,
     %       ' NE PEUT PAS ETRE DECLARE  IOSTAT=',IOERR
      ELSE
         PRINT*,'ecfiviprte: FILE ',KNOMFIC,' UNIT',NFUNIT,
     %       ' MAY NOT BE DECLARED  IOSTAT=',IOERR
      ENDIF
      IERR = 1

 9999 RETURN
      END
