      SUBROUTINE FPISONLTH( KNOMOB, NTLXOB, MOREE2, RELMIN, KNOMFIC,
     %                      NDIM,   MNXYZN, NBSOM,  NBNOVI,
     %                      NBTYEL, MNNPEF, NBTTEF, NUTYEL, 
     %                      NUMIOB, NUMAOB, MNDOEL,
     %                      IEFOIN, IEFOCL, IEBLPR,
     %                      NORESO, MNPTDV, MNLPCV, NIVOGC, NBCMVG,
     %                      NBDLFX, MNNDLFX,MNVDLFX,
     %                      DT,     DTSTOC, TPSINI, TPSFIN,
     %                      NBFLUI, MXFLUI, NTDLVP, MNNDDL, MNVXYZP0,
     %                      NTVECT, MNVECT, VITMAX, VITMOY,
     %                      MXPAST, RESULT,
     %                      DFABG,  DFACTO, DVITPR, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCULER LES VITESSES PRESSION DANS UN DOMAINE 3D
C ----- DU PROBLEME DE NAVIER-STOKES INSTATIONNAIRE
C       SELON UNE METHODE PISO SEMI IMPLICITE AVEC PAS DE TEMPS CONSTANT
C       POUR DES TETRAEDRES DE TAYLOR-HOOD AVEC PRISE EN COMPTE DIRECTE
C       DU TERME NON LINEAIRE DE TRANSPORT (V.Grad)V
C
C       DENSITE DE MASSE Rho, VISCOSITE, Mhu SONT INDEPENDANTS DU TEMPS
C       SI FORCE INTERNE DE GRAVITE (-Rho g z) => A ENTRER EN DONNEES
C
C       FORCE EXTERNE SUR LA FRONTIERE
C       BLOCAGE DE LA VITESSE  IMPOSEE
C       BLOCAGE DE LA PRESSION IMPOSEE   PEUVENT DEPENDRE DU TEMPS
C
C***********************************************************************
C       NS Option8: METHODE PISO (Pressure Implicit with Split Operator)
C       AVEC LE TERME NON LINEAIRE DE TRANSPORT (V.Grad)V :
C
C       A L'ETAPE n=0,  V0 = V(t0),  P0 = P(t0)=P0
C
C       A L'ETAPE n+1, LE PROBLEME CONSISTE A TROUVER
C       {V(tn+1), P(tn+1)} = lim {Vm+1, Pm+1} quand m->Infini
C       SOLUTION de
C
C (0)    m=0; Vm=V(tn);  Pm=P(tn);  (calculees juste avant)
C
C       Calcul de la Vitesse 
C (1)   (1/dt - Mhu/Rho Laplacien) {Vm+1,i(X)} = Fg(tn+1)/Rho
C         + 1/dt {V(tn)} - (Vm.Grad) {Vm,i(X)} - 1/Rho Gradi Pm(X)
C       Condition aux limites
C       Vm+1,i(tn+1,X) = Vi(tn+1,X)     avec X sur Gamma
C       -Mhu/Rho dVm+1,i(tn+1,X)/dn = 0   avec X sur Frontiere-Gamma
C       pour  i=1,...,NDIM
C
C       Calcul de la Pression
C (2)   - 1/Rho Laplacien Pm+1(X) =
C       Div { -Fg(tn+1)/Rho + (Vn+1,m+1(X).Grad) Vn+1,m+1(X) }
C                                       X dans le domaine
C       Condition aux limites
C       - 1/Rho dPm+1(Gamma)/dn =
C       n . { -Fg(tn+1)/Rho + (Vn+1,m+1(gamma).Grad) Vn+1,m+1(gamma) }
C       or Pn+1,m+1(Gamma) = P(tn+1,Gamma) pour Gamma sur la frontiere
C
C       Si ||Vi,n+1,m+1 - Vi,n+1,m|| > Eps ||Vi,n+1,m+1||
C       ou ||P  n+1,m+1 - P  n+1,m|| > Eps ||P  n+1,m+1|| aller en (1)
C       Sinon
C          Si T0 + n dt < Tfinal alors n=n+1; tn+1=tn+dt; goto (0)
C
C***************************************************************************
C
C ENTREES:
C --------
C KNOMOB : NOM DE L'OBJET A TRAITER
C NTLXOB : NUMERO DU TMS DU LEXIQUE DE L'OBJET KNOMOB
C MOREE2 : NOMBRE DE MOTS   D'UNE VARIABLE REELLE DOUBLE PRECISION
C RELMIN : PLUS PETIT REEL SERVANT DE MARQUEUR DE NON UTILISATION
C KNOMFIC: NOM DU FICHIER SUPPORT DU VECTEUR VITESSE+PRESSION
C NDIM   : DIMENSION DES COORDONNEES DES POINTS ( 2 OU 3 )
C MNXYZN : ADRESSE MCN DU TABLEAU XYZNOEUD DE L'OBJET KNOMOB
C          XYZ des SOMMETS+BARYCENTRES    DES EF BREZZI-FORTIN
C          XYZ des SOMMETS+MILIEUX ARETES DES EF TAYLOR-HOOD
C NBSOM  : NOMBRE DE SOMMETS DU MAILLAGE
C NBNOVI : NOMBRE DE NOEUDS DU MAILLAGE (SOMMETS ET MILIEUX DES ARETES)
C
C NBTYEL : NOMBRE DE TYPES D'EF DU MAILLAGE DE CET OBJET
C MNNPEF : ADRESSE MCN DU TABLEAU DES ADRESSES MCN DES TMS NPEF"TYPE EF
C NBTTEF : NOMBRE TOTAL D'EF DU MAILLAGE
C
C NUMIOB : NUMERO MINIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C NUMAOB : NUMERO MAXIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C MNDOEL : LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C          TABLEAUX DECRIVANT LES DONNEES DU FLUIDE DE L'OBJET COMPLET
C IEFOCL :=0 SI PAS DE FORCES DONNEES SUR LES FRONTIERES
C         >0 NOMBRE DE TMS FORCE "AUX LIMITES" DES PLS DE L'OBJET RETROUVES
C IEFOCL :=0 SI PAS DE FORCES DONNEES SUR LES FRONTIERES
C         >0 NOMBRE DE TMS FORCE "AUX LIMITES" DES PLS DE L'OBJET RETROUVES
C IEBLPR : NOMBRE DE TMS BLPRESSION       DES PLS DE L'OBJET TROUVE
C
C NORESO : CODE RESOLUTION DES SYSTEMES LINEAIRES
C          1 FACTORISATION COMPLETE DE CHOLESKY ET MATRICE PROFIL
C          2 GRADIENT CONJUGUE SIMPLE ET STOCKAGE MORSE DE LA MATRICE
C          3 GRADIENT CONJUGUE PRECONDITIONNE PAR NIVEAUX ET STOCKAGE MORSE DES
C            NON PROGRAMME
C MNPTDV : ADRESSE MCN DES POINTEURS SUR LES COEFFICIENTS DIAGONAUX DE VG
C MNLPCV : ADRESSE MCN DU NUMERO DE COLONNE DES COEFFICIENTS DE VG MORSE
C NIVOGC : NIVEAU DE FACTORISATION INCOMPLETE DE LA MATRICE DE PRECONDITIONNEMEN
C          A CHOISIR PARMI 0 1 2
C NBCMVG : NOMBRE DE COEFFICIENTS STOCKES D'UNE MATRICE GLOBALE VITESSE  VG
C          NON DIAGONALE
C
C NBDLFX : NOMBRE DE DL VITESSE ET PRESSION FIXES
C MNNDLFX: ADRESSE MCN DU TABLEAU DU NO GLOBAL DE CHAQUE DL FIXE
C MNVDLFX: ADRESSE MCN DU TABLEAU DE LA VALEUR DE CHAQUE DL FIXE
C
C DT     : PAS CONSTANT DU TEMPS
C DTSTOC : PAS CONSTANT DU TEMPS ENTRE 2 STOCKAGES DU VECTEUR"VITESSEPRESSION
C TPSINI : TEMPS INITIAL DU CALCUL
C TPSFIN : TEMPS FINAL   DU CALCUL
C NBFLUI : NUMERO DU DERNIER VECTEUR VITESSEPRESSION STOCKE
C MXFLUI : NOMBRE DE VECTEUR"VITESSEPRESSION A STOCKER
C
C NTDLVP : NOMBRE TOTAL DE DEGRES DE LIBERTE DE L'OBJET AVEC BARYCENTRES SI BF
C          DL VITESSES et PRESSION
C MNNDDL : NUMERO DU DERNIER DL VZ ou Pr DE CHAQUE NOEUD VITESSE (0:NBNOVI)
C          A UTILISER POUR RETROUVER LES DL PRESSION DES VECTEURS VXYZP
C MNVXYZP0: ADRESSE MCN DE VITESSEXYZ+PRESSION AUX NOEUDS A L'INSTANT INITIAL
C
C MODIFIES:
C ---------
C VITMAX : NORME MAXIMALE INITIALE PUIS FINALE DE LA VITESSE AUX NOEUDS
C VITMOY : NORME MOYENNE  INITIALE PUIS FINALE DE LA VITESSE AUX NOEUDS
C
C SORTIES:
C --------
C RESULT : (TEMPS, VitesseMoyenne, VitesseMax,
C           PressionMoyenne, Pression Max-Min,
C           FLUX-, FLUX+) a chaque temps calcule
C NTVECT : NUMERO      DU TMS VECTEUR"VITESSEPRESSION DE L'OBJET
C MNVECT : ADRESSE MCN DU TMS VECTEUR"VITESSEPRESSION DE L'OBJET
C IERR   : 0 SI PAS D'ERREUR D'EXECUTION, NON NUL SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Texas A&M University at QATAR       Mars 2012
C23456---------------------------------------------------------------012
C     VALEUR A METTRE SUR LA DIAGONALE DE LA MATRICE PROFIL
C     POUR TRAITER LES DL FIXES
      DOUBLE PRECISION  TGV
      PARAMETER        (TGV = 1D30)
      PARAMETER        (mIterMax = 16)
C
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/donflu.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a_objet__definition.inc"
      include"./incl/a___arete.inc"
      include"./incl/a___face.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___vecteur.inc"
      include"./incl/a___profil.inc"
      include"./incl/a___morse.inc"
      include"./incl/a___temperinit.inc"
      include"./incl/msvaau.inc"
      include"./incl/ponoel.inc"
      include"./incl/ctemps.inc"
      include"./incl/cthet.inc"
      include"./incl/cnonlin.inc"
      include"./incl/nctyef.inc"
      include"./incl/p2p22d.inc"
      include"./incl/p2p23d.inc"
C
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1), RMCN(1), DMCN(1))
ccc      COMMON / EPSSSS / EPZERO, EPSXYZ
C
      LOGICAL           COMP
      CHARACTER*(*)     KNOMOB, KNOMFIC
      CHARACTER*4       NOMELE(2)
      CHARACTER*12      NMSOLU
      INTEGER           NUMIOB(4), NUMAOB(4), MNDOEL(4)
      INTEGER           NOOBVC(1), NOOBSF(6), NOOBLA(12), NOOBPS(8)
      INTEGER           NOSOEF(4), NONOTE(10)
      REAL              DT, DTSTOC, TPSINI, TPSFIN, XYZEF(30)
      DOUBLE PRECISION  RELMIN, CoBOUS
      DOUBLE PRECISION  DELTAT, Rho, Mhu, UnSRho, UnSdt, MhuSRho, CoGrPr
      DOUBLE PRECISION  AE(55)
      DOUBLE PRECISION  VITMIN, VITMAX, VITMOY, PREMIN, PREMAX, PREMOY,
     %                  FLUNEG, FLUPOS, DIFVIM, NORVIM, NORVIM0,
     %                  DIFPRM, NORPRM, NORPRM0, DIFMAX, VITFXMAX
      DOUBLE PRECISION  RESULT(8,MXPAST),
     %                  VMAXMAX, VMOYMOY, PMXIMXI, PMOYMOY
      DOUBLE PRECISION  STGV, DINFO, DFABG, DFACTO, DVITPR, DMOTSTO
      INTRINSIC         DBLE, ABS
C
      DOUBLE PRECISION, allocatable, dimension(:) :: PG, VG
      INTRINSIC         ALLOCATED
      EXTERNAL          ETTAEL
C
      WRITE(IMPRIM,*) 'Start of PISO+(V.Grad)V IMPLICIT NAVIER-STOKES SO
     %LVER on the OBJECT ',KNOMOB
C
cccC     LAISSE A L'APPRECIATION DE L'UTILISATEUR Option 20; 2; EPZERO
cccC     PROTECTION DE EPZERO INITIAL
ccc      EPZ     = EPZERO
ccc
      NIVMAX  = 10
      MNTPOB  = 0
      MNLPLC  = 0
      MNLPCC  = 0
      MNLPLU  = 0
      MNPGC   = 0
      MNAUX1  = 0
      MNLPCP  = 0
      MNLGMM  = 0
      MNPRE   = 0
      MNBDIR  = 0
      LODIR   = 0
      MNNDPFX = 0
      MNNDVFX = 0
      NBPRFX  = 0
      MNVAPRFX= 0
      MNDLPRFX= 0
      NBVIFX  = 0
      MNDLVIFX= 0
      MNVAVIFX= 0
      MNFVSF  = 0
      MNV3P00 = 0
      MNV3P1  = 0
      MNV3P2  = 0
      IERPGALLOC = 1
      IERVGALLOC = 1
      MNLGAU  = 0
      MOSFOB  = 0
      LOAUX   = 0
      LODIR   = 0
      LOLPCC  = 0
      MOTSGC  = 0
      MOTPRE  = 0
      MNNOSO  = 0
      MNSONO  = 0
      MNPTDP  = 0
      MNP2DP2 = 0
      MNDP2DP2= 0
      NBCMPG  = 0
      NBMXVP0 = 0
      MNPRPR = 0
      MNAUX1 = 0
      MNAUX2 = 0
      MNAUX3 = 0
      MNDIR  = 0
      MNDAD  = 0
      MNBET  = 0
      MNADIR = 0
      MOTSGC = 0
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10000)
      ELSE
         WRITE(IMPRIM,20000)
      ENDIF
10000 FORMAT(/' MASSE VOLUMIQUE, VISCOSITE sont INDEPENDANT du TEMPS et
     %de la VITESSE')
20000 FORMAT(/' DENSITY of MASS, VISCOSITY ARE INDEPENDENT of TIME and
     %VELOCITY')
C
C     STOCKAGE DES RESULTATS
      NBPASDT = 0
      NBPASR  = 1
      RESULT(1,NBPASR) = TEMPS
      RESULT(2,NBPASR) = VITMOY
      RESULT(3,NBPASR) = VITMAX
      RESULT(4,NBPASR) = 0D0
      RESULT(5,NBPASR) = 0D0
      RESULT(6,NBPASR) = 0D0
      RESULT(7,NBPASR) = 0D0
      RESULT(8,NBPASR) = NBPASDT
C
C     LE PAS DE TEMPS EN DOUBLE PRECISION
      DELTAT = DT
      UnSdt = 1D0 / DELTAT
C
C     LE TYPE DES EF DU MAILLAGE EST IL TETRAEDRE TAYLOR-HOOD
C     -------------------------------------------------------
C     MNELE : ADRESSE DU TABLEAU NPEF"TYPE EF (TRIA 2P2C ou TETR 3P2C)
      MNELE  = MCN( MNNPEF )
C
C     NOMBRE D'ELEMENTS FINIS DE CE TYPE
      NBELEM = MCN( MNELE + WBELEM )
C
C     LE NUMERO DU TYPE DE L'ELEMENT FINI (TRIA 2P2C ou TETR 3P2C)
      NUTYEL = MCN( MNELE + WUTYEL )
C
C     MNPGEL ADRESSE MCN DES NUMEROS NOEUDS ET POINTS GEOMETRIQUES DES EF
      MNPGEL = MNELE + WUNDEL
C
C     LES CARACTERISTIQUES DE L'ELEMENT FINI
      CALL ELNUNM( NUTYEL, NOMELE )
      CALL ELTYCA( NUTYEL )
      IF( NUTYEL .EQ. 15 ) THEN
C        TRIANGLE DE TAYLOR-HOOD
         NDIM   = 2
C        NOMBRE DE NO DE SOMMETS D'UN EF DANS NPEF
         NBNOEF = 6
      ELSE IF( NUTYEL .EQ. 20 ) THEN
C        TETRAEDRE DE TAYLOR-HOOD
         NDIM   = 3
C        NOMBRE DE NO DE SOMMETS D'UN EF DANS NPEF
         NBNOEF = 10
      ELSE
C        MAILLAGE D'EF NON TETRAEDRE DE TAYLOR-HOOD
         IERR = 1
         GOTO 9999
      ENDIF
C
C     NOMBRE DE DL DE LA VITESSE
      NTDLVI = NDIM * NBNOVI
C
C     NBSOM EST LE NOMBRE DE DL DE LA PRESSION
C
C     NOMBRE TOTAL DE DL VITESSE+PRESSION
      NTDLVP = NTDLVI + NBSOM
C
C     RECUPERATION DES DONNEES SUPPOSEES CONSTANTES DANS LE FLUIDE
C     SUR LE PREMIER ELEMENT FINI DU MAILLAGE: Rho, Mhu, CoGrPr
C     ------------------------------------------------------------
C     NO DES NOEUDS DE L'ELEMENT FINI 1
      NUELEM = 1
      CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOTE )
C     NO DU BARYCENTRE
      NONOTE(NBNOEF+1) = NBSOM + NUELEM
C
C     NO DES POINTS LIGNES SURFACES VOLUMES DES SOMMETS ARETES FACES VOLUME
      CALL EFPLSV( MNELE , NUELEM,
     %             NOVCEL, NOSFEL, NOLAEL, NOPSEL,
     %             NOOBVC, NOOBSF, NOOBLA, NOOBPS )
C
C     INTERPOLATION DU FLUIDE avec F: echapeau->e  P1 ndim
C     COORDONNEES XYZEF(NBNOEF,3) DES SOMMETS=POINTS DE L'EF
      CALL EFXYZP( NDIM, MNXYZN, NBELEM, NUELEM, MNPGEL, NBNOEF,
     %             XYZEF )
C
C     RECHERCHE DE LA DENSITE DE MASSE Rho, VISCOSITE DYNAMIQUE Mhu,
C     COEFFICIENT DE LA PRESSION CoGrPr AU BARYCENTRE DE L'EF 1
      IF( NDIM .EQ. 2 ) THEN
         CALL REDOFL( NBNOEF, NDIM, XYZEF,
     %                NOOBSF, NUMIOB(3), NUMAOB(3), MCN(MNDOEL(3)),
     %                Rho, Mhu, CoGrPr, CoBOUS )
      ELSE
         CALL REDOFL( NBNOEF, NDIM, XYZEF,
     %                NOOBVC, NUMIOB(4), NUMAOB(4), MCN(MNDOEL(4)),
     %                Rho, Mhu, CoGrPr, CoBOUS )
      ENDIF
C
C     COEFFICIENTS INTERNES A EOL (DIVISION PAR Rho DES EQUATIONS)
C     COEFFICIENT DEVANT LA PRESSION
      UnSRho  = 1D0 / Rho
C     VISCOSITE CINEMATIQUE DU FLUIDE
      MhuSRho = Mhu / Rho
C
C     REMARQUE: CoGrPr n'est pas utilise ici.
C               IMPIVITEMENT IL VAUT 1/Rho
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10010) DELTAT, Rho, Mhu, MhuSRho
      ELSE
         WRITE(IMPRIM,20010) DELTAT, Rho, Mhu, MhuSRho
      ENDIF
10010 FORMAT(/' Pas de TEMPS dt=',G15.7,'  Rho=',G15.7,'  Mhu=',G15.7,
     %'  Mhu/Rho=',G15.7/)
20010 FORMAT(/' Time STEP dt=',G15.7,'  Rho=',G15.7,'  Mhu=',G15.7,
     %'  Mhu/Rho=',G15.7/)
C
C     CONSTRUCTION DU TABLEAU NO SOMMET => NO NOEUD
C     CONSTRUCTION DU TABLEAU NO NOEUD  => NO SOMMET
C     ==============================================
      CALL TNMCDC( 'ENTIER', NBSOM,  MNSONO )
      CALL TNMCDC( 'ENTIER', NBNOVI, MNNOSO )
C
      CALL AZEROI( NBNOVI,  MCN(MNNOSO) )
C     NOMBRE DE SOMMETS DE l'EF
      NBS = NDIM + 1
      DO NUELEM = 1, NBELEM
         CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOTE )
         DO I = 1, NBS
            MCN( MNNOSO-1+NONOTE(I) ) = 1
         ENDDO
      ENDDO
C
C     NUMEROTATION DES SOMMETS DANS L'ORDRE DES NOEUDS (VITESSE)
      NBSOM = 0
      DO I = 1, NBNOVI
         IF( MCN(MNNOSO-1+I ) .GT. 0 ) THEN
            NBSOM = NBSOM + 1
            MCN( MNNOSO-1+I     ) = NBSOM
            MCN( MNSONO-1+NBSOM ) = I
         ENDIF
      ENDDO
C
C     ================================================================
C     CONSTRUCTION DE LA MATRICE GLOBALE DE PRESSION [PG(UnSRho)]
C     UnSRho Integrale grad P1 grad P1 dX avec INTERPOLATION P1
C     ================================================================
C     MATRICE PRESSION SYMETRIQUE NON DIAGONALE
      NCODSP = 1
C
C     CONSTRUCTION DU POINTEUR SUR LA DIAGONALE DE PG
      CALL TNMCDC( 'ENTIER', 1+NBSOM, MNPTDP )
C
      IF( NORESO .EQ. 1 ) THEN
C
C        CHOLESKY PROFIL POUR LA PRESSION
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10001)
         ELSE
            WRITE(IMPRIM,20001)
         ENDIF
C
C        MAX POUR CALCULER LE MIN DES VOISINS D'UN SOMMET
         DO N = 1, NBSOM
            MCN( MNPTDP+N ) = NBSOM
         ENDDO
C
         DO NUELEM = 1, NBELEM
C           LES NUMEROS DES NOEUDS DE L'EF
            CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOTE )
C           RECHERCHE DU NUMERO MINIMAL DES SOMMETS DE l'EF
            NOSOEF(1) = MCN( MNNOSO-1+NONOTE(1) )
            NOMIN     = NOSOEF(1)
            DO I = 2, NBS
C              NUMERO DU SOMMET I
               NOSOEF(I) = MCN( MNNOSO-1+NONOTE(I) )
C              NUMERO MINIMAL DES SOMMETS
               NOMIN = MIN( NOMIN, NOSOEF(I) )
            ENDDO
            DO I = 1, NBS
C              NUMERO DU SOMMET I
               N = NOSOEF(I)
C              NUMERO MINIMUM DES VOISINS DU SOMMET N
               MCN( MNPTDP+N ) = MIN( NOMIN, MCN( MNPTDP+N ) )
            ENDDO
         ENDDO
C
C        POINTEUR SUR LE COEFFICIENT DIAGONAL DE LA MATRICE PRESSION
         MCN( MNPTDP ) = 0
         DO N = 1, NBSOM
            M = MNPTDP+N
C           NPMBRE DE COEFFICIENTS ENTRE LE MIN ET DIAGONAL
            MCN( M ) = MCN( M-1 ) + N - MCN( M ) +1
         ENDDO
C        NOMBRE DE COEFFICIENTS DE LA MATRICE PROFIL DE PRESSION
         NBCMPG = MCN( MNPTDP+NBSOM )
C
      ELSE IF( NORESO .EQ. 2 ) THEN
C
C        GRADIENT CONJUGUE SIMPLE SUR MATRICE MORSE DE LA PRESSION
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10002)
         ELSE
            WRITE(IMPRIM,20002)
         ENDIF
C
cccC        REDUCTION DU SEUIL POUR STOPPER LES ITERATIONS DU GC
ccc         EPZERO = 1E-4
cccC
cccC        CALCUL DES POINTEURS DE LA MATRICE MORSE PRESSION P1 PAR SOMMETS
cccC        ALORS QUE LE MAILLAGE EST P2
ccc         CALL PRGCMCST( NBSOM, MCN(MNNOSO), MNTOPO, MCN(MNNPEF), MNXYZN,
ccc     %                  1, NCODSP, MNPTDP, MNLPCP, IERR )
C
C        CALCUL   DES POINTEURS DE LA MATRICE MORSE PRESSION P1 PAR SOMMETS
C        A PARTIR DES POINTEURS DE LA MATRICE MORSE VITESSE  P2 PAR NOEUDS
         CALL PRGCVP( NBSOM,NBNOVI, MCN(MNNOSO), NCODSP, MNPTDV, MNLPCV,
     %                MNPTDP, MNLPCP, IERR )
         IF( IERR .NE. 0 ) GOTO 9990
C
C        NOMBRE DE COEFFICIENTS DE LA MATRICE MORSE PRESSION AUX SOMMETS
         NBCMPG = MCN( MNPTDP + NBSOM )
C
      ELSE IF( NORESO .EQ. 3 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10003)
         ELSE
            WRITE(IMPRIM,20003)
         ENDIF
C
      ELSE
C        ERREUR SUR NORESO
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10004) NORESO
         ELSE
            WRITE(IMPRIM,20004) NORESO
         ENDIF
         IERR = 1
         GOTO 9999
      ENDIF
10001 FORMAT('CONSTRUCTION de la MATRICE PROFIL [PG] de PRESSION'/
     %'RESOLUTION par FACTORISATION COMPLETE L tL de CHOLESKY')
20001 FORMAT(' CONSTRUCTION of the PRESSURE SKYLINE MATRIX [PG]'/
     %'SOLUTION by COMPLETE CHOLESKY FACTORIZATION L Lt')
10002 FORMAT('CONSTRUCTION de la MATRICE MORSE [PG] de PRESSION'/
     %'RESOLUTION par GRADIENT CONJUGUE SIMPLE')
20002 FORMAT(' CONSTRUCTION of the PRESSURE CONDENSED MATRIX [PG]'/
     %'SOLUTION by CONDENSED MATRIX SIMPLE CONJUGATE GRADIENT')
10003 FORMAT('CONSTRUCTION de la MATRICE MORSE [PG] de PRESSION'/
     %'RESOLUTION par GRADIENT CONJUGUE PRECONDITIONNE')
20003 FORMAT(' CONSTRUCTION of the PRESSURE CONDENSED MATRIX [PG]'/
     %'SOLUTION by CONDENSED MATRIX PRECONDITIONED CONJUGATE GRADIENT')
10004 FORMAT('CODE DE RESOLUTION INCONNU  NORESO=',I5/)
20004 FORMAT('UNKNOWN SOLUTION CODE  NORESO=',I5/)
C
C     MODE DE PRISE EN COMPTE DES CONDITIONS AUX LIMITES DE DIRICHLET
C     SUR LES SYSTEMES LINEAIRES avec LES MATRICES VG PG
C     ---------------------------------------------------------------
      IF( NORESO .EQ. 1 ) THEN
C        MATRICE PROFIL
         STGV = TGV
      ELSE
C        MATRICE MORSE
         STGV = 1D0
      ENDIF
C
C     MATRICE DE PRESSION P1 SYMETRIQUE NON DIAGONALE
C     ===============================================
      NCODSP = 1
C     NBCMPG : NOMBRE DE REELS DOUBLE PRECISION DE LA MATRICE PG
C
C     VERSION ALLOCATION de la MATRICE PG en LANGAGE FORTRAN 90
      WRITE(IMPRIM,*)
      WRITE(IMPRIM,*) 'ALLOCATION DEMAND  of',NBCMPG,
     %                ' DOUBLE PRECISION of the [PG] MATRIX'
      ALLOCATE ( PG(1:NBCMPG), STAT=IERPGALLOC )
      IF( IERPGALLOC .NE. 0 ) THEN
       WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBCMPG,
     %                ' DOUBLE PRECISION of the [PG] MATRIX'
         IERR = IERPGALLOC
         GOTO 9990
      ENDIF
      WRITE(IMPRIM,*) 'ALLOCATION CORRECT of',NBCMPG,
     %                ' DOUBLE PRECISION of the [PG] MATRIX'
      WRITE(IMPRIM,*)
C
C     CONSTRUCTION DES TABLEAUX DES NO ET VALEURS DES PRESSIONS FIXEES
C     ----------------------------------------------------------------
      IF( IEBLPR .GT. 0 ) THEN
         CALL PRESFXST( RELMIN, NBSOM,    NDIM,   MNXYZN, MNNOSO,
     %                  NBTYEL, MNNPEF,   NUMIOB, MNDOEL,
     %                  NBPRFX, MNDLPRFX, MNVAPRFX )
      ELSE
         NBPRFX = 0
      ENDIF
C
      IF( NORESO .EQ. 1 ) THEN
C
C        ASSEMBLAGE PROFIL: 1/Rho ( GRAD p, GRAD q ) INTERPOLATION P1
C        DE LA MATRICE GLOBALE DE LA PRESSION
C        LE COEFFICIENT DE LA MATRICE DE PRESSION est 1/Rho
C        ------------------------------------------------------------
         IF( NUTYEL .EQ. 15 ) THEN
C           TRIANGLE TAYLOR-HOOD
            CALL P12DAGPR( UnSRho, NBSOM,  MCN(MNXYZN+WYZNOE),
     %                     NBNOEF, NBELEM, MCN(MNELE+WUNDEL),
     %                     MCN(MNNOSO), NBCMPG, MCN(MNPTDP), PG )
         ELSE
C           TETRAEDRE TAYLOR-HOOD
            CALL P13DAGPR( UnSRho, NBSOM,  MCN(MNXYZN+WYZNOE),
     %                     NBNOEF, NBELEM, MCN(MNELE+WUNDEL),
     %                     MCN(MNNOSO), NBCMPG, MCN(MNPTDP), PG )
         ENDIF
ccc
ccc         call affvect( 'PG PROFIL ASSEMBLEE avec arrondis', 20, PG )
C
cccC        SUPPRESSION DES COEFFICIENTS D'ERREURS D'ARRONDIS
cccC        et MULTIPLICATION PAR  dt UnSRho
ccc         CALL PRARMU( 1D-4, S, NBCMPG, PG )
ccc         call affvect( 'PG PROFIL ASSEMBLE corrige', 20, PG )
C
C        PRISE EN COMPTE DES CONDITIONS AUX LIMITES DES PRESSIONS FIXEES
         DO I = 1, NBPRFX
C           LE NO GLOBAL DU DL FIXE
            NDL = MCN( MNDLPRFX - 1 + I )
C           LE NO DU COEFFICIENT DIAGONAL NDL
            NDIAG = MCN( MNPTDP + NDL )
C           MODIFICATION DU COEFFICIENT DIAGONAL
C           CETTE VALEUR PEUT SERVIR DE MARQUEUR D'UN DL FIXE POUR PG
            PG( NDIAG ) = STGV
         ENDDO
ccc         call affvect( 'PG PROFIL AVEC CL', 20, PG )
C
C        FACTORISATION COMPLETE DE CHOLESKY  PG = L tL
         CALL CHOLPR( NBSOM, NCODSP, MCN(MNPTDP), PG,  PG, IERR )
ccc         call affvect( 'PG=L tL PROFIL', 20, PG )
C
      ELSE IF( NORESO .EQ. 2 ) THEN
C
C        ASSEMBLAGE MORSE UnSRho ( GRAD p, GRAD q ) INTERPOLATION P1
C        DE LA MATRICE GLOBALE DE LA PRESSION
C        RESOLUTION PAR GRADIENT CONJUGUE SIMPLE SANS PRECONDITIONNEMENT
C        ---------------------------------------------------------------
         IF( NUTYEL .EQ. 15 ) THEN
C           TRIANGLE TAYLOR-HOOD
            CALL P12DAGGC( UnSRho, NBSOM,  MCN(MNXYZN+WYZNOE),
     %                   NBNOEF, NBELEM, MCN(MNELE+WUNDEL), MCN(MNNOSO),
     %                   NBCMPG, MCN(MNPTDP), MCN(MNLPCP), PG )
         ELSE
C           TETRAEDRE TAYLOR-HOOD
            CALL P13DAGGC( UnSRho, NBSOM,  MCN(MNXYZN+WYZNOE),
     %                   NBNOEF, NBELEM, MCN(MNELE+WUNDEL), MCN(MNNOSO),
     %                   NBCMPG, MCN(MNPTDP), MCN(MNLPCP), PG )
         ENDIF
C
C        CONSTRUCTION DU TABLEAU des DL PRESSION FIXES 1 OU NON 0
         CALL TNMCDC( 'ENTIER', NBSOM, MNNDPFX )
C        A PRIORI TOUS LES DL SONT LIBRES => 0
         CALL AZEROI( NBSOM, MCN(MNNDPFX) )
C
C        MISE AU NUMERO DU DL FIXE DANS LES TABLEAUX
C        DES DL FIXES DE LA PRESSION
         DO I = 1, NBPRFX
C           LE NO GLOBAL DU DL PRESSION FIXEE
            NDL = MCN( MNDLPRFX - 1 + I )
C           MISE A I DU DL PRESSION FIXEE NDL
            MCN( MNNDPFX-1 + NDL ) = I
C           MODIFICATION DU COEFFICIENT DIAGONAL
C           LE NO DU COEFFICIENT DIAGONAL NDL
            NDIAG = MCN( MNPTDP + NDL )
C           CETTE VALEUR PEUT SERVIR DE MARQUEUR D'UN DL FIXE POUR PG
            PG( NDIAG ) = STGV
         ENDDO
ccc         call affvect( 'PG MORSE AVEC CL', 20, PG )
C
C        LES 4 TABLEAUX AUXILIAIRES du SOUS PROGRAMME Gcaxb
C        MNAUX1, MNAUX2, MNAUX3 : ADRESSES DE TABLEAUX AUXILIAIRES
         LOAUX = NBNOVI * 4
         CALL TNMCDC( 'REEL2', LOAUX, MNAUX1 )
         IF( MNAUX1 .LE. 0 ) GOTO 9990
         MNAUX2 = MNAUX1 + NBNOVI * MOREE2
         MNAUX3 = MNAUX2 + NBNOVI * MOREE2
         MNPRPR = MNAUX3 + NBNOVI * MOREE2
C
      ELSE IF( NORESO .EQ. 3 ) THEN
C
C        ASSEMBLAGE MORSE UnSRho ( GRAD p, GRAD q ) INTERPOLATION P1
C        RESOLUTION PAR GRADIENT CONJUGUE AVEC PRECONDITIONNEMENT
C        -----------------------------------------------------------
C        TETRAEDRE TAYLOR-HOOD
         CALL P13DAGGC( UnSRho, NBSOM,  MCN(MNXYZN+WYZNOE),
     %                  NBNOEF, NBELEM, MCN(MNELE+WUNDEL), MCN(MNNOSO),
     %                  NBCMPG, MCN(MNPTDP), MCN(MNLPCP), PG )
C
C        CONSTRUCTION DU TABLEAU des DL FIXES OU NON POUR LA PRESSION
         CALL TNMCDC( 'ENTIER', NBSOM, MNNDPFX )
C        A PRIORI TOUS LES DL SONT LIBRES => 0
         CALL AZEROI( NBSOM, MCN(MNNDPFX) )
C        MISE A 1 DES DL FIXES
         DO I = 1, NBPRFX
C           LE NO GLOBAL DU DL PRESSION FIXE
            NDL = MCN( MNDLPRFX - 1 + I )
C           MISE A I DU DL PRESSION FIXE NDL
            MCN( MNNDPFX-1 + NDL ) = I
         ENDDO
C
C        CALCUL DE LA MATRICE DE PRECONDITIONNEMENT DE [PG] STOCKAGE MORSE
         CALL MAPRCRGC( NBSOM,  NIVOGC, MNNDPFX,
     %                  NCODSP, MNPTDP, MNLPCV, PG,
     %                  MNLPLC, MNLPCC, MNLPLU, LOLPCC, MNPGC,
     %                  COMP,   IERR )
         IF( IERR .NE. 0 ) GOTO 9999
C
C        LES TABLEAUX AUXILIAIRES DE GCPRCR
C        MNAUX1, MNAUX2, MNAUX3 : ADRESSES DE TABLEAUX AUXILIAIRES
         LOAUX = NBNOVI * 4
         CALL TNMCDC( 'REEL2', LOAUX, MNAUX1 )
         IF( MNAUX1 .LE. 0 ) GOTO 9990
         MNAUX2 = MNAUX1 + NBNOVI * MOREE2
         MNAUX3 = MNAUX2 + NBNOVI * MOREE2
         MNPRPR = MNAUX3 + NBNOVI * MOREE2
C
C        DECLARATION DES TABLEAUX AUXILIAIRES DES DIRECTIONS DU GC
C        NBDIR  : NOMBRE DE DIRECTIONS >=1 POUR STABILISER LE GC
C        LODIR  : NOMBRE DE MOTS DES TABLEAUX POUR STOCKER LES DIRECTIONS
         NBDIR = 3
C        NOMBRE DE DIRECTIONS >=1 POUR STABILISER LE GC
         LODIR = (NBNOVI+1) * NBDIR * 2
         CALL TNMCDC( 'REEL2', LODIR, MNBDIR )
         IF( MNBDIR .LE. 0 ) GOTO 9990
C        MNBDIR, MNDIR, MNADIR, MNDAD, MNBET: ADRESSES DE TABLEAUX AUXILIAIRES
         MNDIR  = MNBDIR
         MNADIR = MNDIR  + NBNOVI * NBDIR * MOREE2
         MNDAD  = MNADIR + NBNOVI * NBDIR * MOREE2
         MNBET  = MNDAD  + NBDIR * MOREE2
C
C        NOMBRE TOTAL DE MOTS STOCKES POUR LE GC PRECONDITIONNE
         MOTSGC = NBNOVI + NBCMPG + (LOAUX+LODIR) * MOREE2
C
      ENDIF
C
C     ==============================================================
C     DECLARATION DE LA MATRICE VG D'UNE COMPOSANTE P2 DE LA VITESSE
C     MATRICE SYMETRIQUE NON DIAGONALE
C     Integrale 1/dt P2 P2 + Mhu/Rho grad P2 grad P2 dX
C     ==============================================================
      NCODSV = 1
C     NBCMVG : NOMBRE DE REELS DOUBLE PRECISION DE LA MATRICE VG
C     VERSION ALLOCATION de la MATRICE VG en LANGAGE FORTRAN 90
      WRITE(IMPRIM,*)
      WRITE(IMPRIM,*) 'ALLOCATION DEMAND  of',NBCMVG,
     %                ' DOUBLE PRECISION of the [VG] MATRIX'
      ALLOCATE ( VG(1:NBCMVG), STAT=IERVGALLOC )
      IF( IERVGALLOC .NE. 0 ) THEN
       WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBCMVG,
     %                ' DOUBLE PRECISION of the [VG] MATRIX'
         IERR = IERVGALLOC
         GOTO 9990
      ENDIF
      WRITE(IMPRIM,*) 'ALLOCATION CORRECT of',NBCMVG,
     %                ' DOUBLE PRECISION of the [VG] MATRIX'
      WRITE(IMPRIM,*)
C
C     CONSTRUCTION DE LA MATRICE D'UNE COMPOSANTE DE LA VITESSE
C     Integrale  ( 1/dt P2 P2 + Mhu/Rho Grad P2 Grad P2 ) dX
C     avec INTEGRATION EXACTE SUR L'ELEMENT FINI
C     =========================================================
      CALL AZEROD( NBCMVG, VG )
C
C     RECUPERATION DES TABLEAUX POBA NECESSAIRES A LA
C     CONSTRUCTION DES TABLEAUX ELEMENTAIRES
C     RETRIEVE the ARRAYS of BASIS POLYNOMIAL VALUES at
C     NUMERICAL QUADRATURE FORMULA POINTS
      CALL TAPOBA( NBTYEL, MNNPEF, ETTAEL,
     %             MNTPOB, NBDLM0, MOAUX, NBTTEF, NOAXIS, I, IERR )
      IF( IERR .NE. 0 ) GOTO 9990
C
C     RECHERCHE DU TABLEAU DE POBA ET PARTAGE EN P ET DP
      L = MNTPOB
C
C     SAUT DU TABLEAU POUR LES EF 2D DE SURFACE POUR CONDITIONS AUX LIMITES
C     LES VALEURS DES POLYNOMES DE L'EF DE DIMENSION TOTALE C-A-D
C     EN 3D sur le TETRAEDRE DE REFERENCE RECTANGLE UNITE
      L  = L + 1
      IA = MCN( L )
C     DIMENSION DE L ESPACE
C     NDIM   = MCN( IA )
C     NOMBRE DE POLYNOMES D INTERPOLATION
      NBPOLY = MCN( IA + 1 )
C     NOMBRE DE POINTS D INTEGRATION NUMERIQUE
      NPI    = MCN( IA + 2 )
C     ADRESSE DES POIDS DES POINTS DE LA FORMULE D INTEGRATION
      MNPOID = IA + 8
C     ADRESSE DES VALEURS DES POLYNOMES AUX POINTS D INTEGRATION
      MNPOL  = MNPOID + MCN( IA + 3 ) * MOREE2 * NPI
C     ADRESSE DES VALEURS DES DERIVEES DES POLYNOMES AUX POINTS D'INTEGRATION
      MNDPOL = MNPOL + MCN( IA + 4 ) * MOREE2 * NBPOLY * NPI
C
C     CALCUL DE L'INTEGRALE P2 DP2 dx dy dz
C     POUR L'EF de TAYLOR-HOOD en FLUIDE de REFERENCE
      CALL TNMCDC( 'REEL2', 10*3*10, MNP2DP2 )
      CALL INTPDP( NPI, MCN(MNPOID), NDIM, NBPOLY,
     %             MCN(MNPOL), MCN(MNDPOL),  MCN(MNP2DP2))
C
C     CALCUL DE L'INTEGRALE DP2 DP2 dx dy dz
C     POUR L'EF de TAYLOR-HOOD en FLUIDE de REFERENCE
      CALL TNMCDC( 'REEL2', 3*10*3*10, MNDP2DP2 )
      CALL INTDPDP( NPI, MCN(MNPOID), NDIM, NBPOLY, MCN(MNDPOL),
     %              MCN(MNDP2DP2))
C
C     CONSTRUCTION DE LA MATRICE VG D'UNE COMPOSANTE DE LA VITESSE
C     Integrale  ( P2 P2 / dt + Mhu / Rho Grad P2 Grad P2 ) dX
C     avec INTEGRATION EXACTE SUR L'ELEMENT FINI
C     ============================================================
      CALL AGVITTH( UnSdt, MhuSRho, MCN(MNXYZN+WYZNOE),
     %              NUTYEL, NBNOEF, NBELEM, MCN(MNELE+WUNDEL),
     %              NORESO, NBNOVI, NBCMVG, MCN(MNPTDV),MCN(MNLPCV), VG)

C     ==========================================================================
C     PRISE EN COMPTE DES CONDITIONS AUX LIMITES DES VITESSES FIXEES SUR VG
C     ATTENTION: CETTE PROGRAMMATION SUPPOSE QUE TOUS LES DL EN UN NOEUD
C                SONT FIXES ET LES NOEUDS FIXES RESTENT LES MEMES POUR TOUT TEMP
C                MAIS PAS FORCEMENT LA VITESSE A FIXER QUI ELLE DEPEND du TEMPS
C     ==========================================================================
C     LISTE DES DL VITESSES FIXEES EN TOUT TEMPS
      CALL VITEFX( RELMIN, NTDLVI, NDIM,   MNXYZN,
     %             NBTYEL, MNNPEF, NUMIOB, MNDOEL,
     %             NBVCFX, NBVIFX, MNDLVIFX, MNVAVIFX, VITFXMAX )
C
      IF( NORESO .EQ. 2 ) THEN
C
C        CONSTRUCTION DU TABLEAU des DL 1 VITESSE FIXE I OU NON 0
C        --------------------------------------------------------
         CALL TNMCDC( 'ENTIER', NBNOVI, MNNDVFX )
C        A PRIORI TOUS LES DL SONT LIBRES => 0
         CALL AZEROI( NBNOVI, MCN(MNNDVFX) )
C        MISE AU NUMERO DU DL FIXE DANS LES TABLEAUX VIFX
C        DES DL FIXES DE LA 1-ERE COMPOSANTE DE LA VITESSE
         DO I=1, NBVIFX/NDIM
C           LE NO GLOBAL DU DL 1VITESSE FIXEE
            NDL = MCN( MNDLVIFX - 1 + I )
C           MISE A I DU DL 1VITESSE FIXEE NDL
            MCN( MNNDVFX-1 + NDL ) = I
         ENDDO
C
      ENDIF
C
C     PRISE EN COMPTE DE LA VITESSE FIXEE SUR LA MATRICE VG
C     -----------------------------------------------------
      DO I = 1, NBVIFX/NDIM
C        LE NO GLOBAL DU DL FIXE DE LA PREMIERE COMPOSANTE DE LA VITESSE
         NDL = MCN( MNDLVIFX - 1 + I )
C        LE NO DU COEFFICIENT DIAGONAL NDL
         NDIAG = MCN( MNPTDV + NDL )
C        MODIFICATION DU COEFFICIENT DIAGONAL
C        CETTE VALEUR PEUT SERVIR DE MARQUEUR D'UN DL FIXE POUR VG
         VG( NDIAG ) = STGV
      ENDDO
C
      IF( NORESO .EQ. 1 ) THEN
C
C        FACTORISATION COMPLETE DE CHOLESKY  VG = L tL SUR ELLE-MEME
C        -----------------------------------------------------------
         CALL CHOLPR( NBNOVI, NCODSV, MCN(MNPTDV), VG,  VG, IERR )
C
      ENDIF
C
C     TEMPS CALCUL DE FORMATION DES MATRICES GLOBALES ET FACTORISATIONS
      DFACTO = DINFO( 'DELTA CPU' )
C
C     DECLARATIONS DES VECTEURS GLOBAUX
C     =================================
C     DECOMPOSITION DU VECTEUR V3P0 SOLUTION AU TEMPS 0 EN 4 VECTEURS
C     VXYZP0 => VITX0, VITY0, VITZ0, PRES0
C     LE VECTEUR V3P0 SOLUTION AU TEMPS n+1,m (VX,VY,VZ,Pr)
      NBDV3P0 = (NDIM+1) * NBNOVI * 3
      CALL TNMCDC( 'REEL2', NBDV3P0, MNV3P00 )
      MNV3P0  = MNV3P00
      MNVITX0 = MNV3P0
      MNVITY0 = MNVITX0 + MOREE2 * NBNOVI
      MNVITZ0 = MNVITY0 + MOREE2 * NBNOVI
      MNPRES0 = MNVITX0 + MOREE2 * NBNOVI * NDIM
C
C     LE VECTEUR V3P1 SOLUTION AU TEMPS n+1,m+1 (VX,VY,VZ,Pr)
      MNV3P1  = MNV3P0 + MOREE2 * NBNOVI * (NDIM+1)
C
C     LE VECTEUR V3tn SOLUTION AU TEMPS n (VX,VY,VZ,Pr)
      MNV3Ptn = MNV3P1 + MOREE2 * NBNOVI * (NDIM+1)
C
C     MNVXYZP0 = en chaque NOEUD VX,VY,VZ + si MILIEU Pr
C     MNVITX0  = VX(NOEUDS), VY(NOEUDS), VZ(NOEUDS), Pr(SOMMETS)
C     SI TAYLOR-HOOD LA PRESSION AU MILIEU DES ARETES EST CALCULEE
C     EN FAIT DANS V3P1 PUIS SUPPRIME DANS LES INSTRUCTIONS SUIVANTES
C     LE DEBORDEMENT AU DELA DES NTDLVP DL EST AINSI CONTROLE
      CALL VXVYVZPR( NDIM, NUTYEL, NBELEM, NBNOEF, MCN(MNELE+WUNDEL),
     %               MCN(MNNDDL), NTDLVP, 1, MCN(MNVXYZP0),
     %               NBNOVI, MCN(MNVITX0), MCN(MNVITY0), MCN(MNVITZ0),
     %               NBNOVI, MCN(MNV3P1) )
C
C     LA PRESSION0 EST REORDONNEE EN LES SEULS SOMMETS DE 1 A NBSOM
      MNV = ( MNV3P1  - 1 ) / MOREE2
      MNP = ( MNPRES0 - 1 ) / MOREE2
      DO I = 1, NBSOM
C        LE NUMERO N DE NOEUD DU SOMMET I
         N = MCN(MNSONO-1+I)
C        LA PRESSION0 AU NOEUD N EST PLACE AU SOMMET I
         DMCN( MNP + I ) = DMCN( MNV + N )
      ENDDO
C
C     TABLEAU AUXILIAIRE POUR LE GRADIENT CONJUGUE
      IF( NORESO .GT. 1 ) THEN
         CALL TNMCDC( 'REEL2', NTDLVI, MNV3P2 )
         IF( MNV3P2 .LE. 0 ) GOTO 9990
      ENDIF
C
C     L'ADRESSE DE LA VITESSEPRESSION A L'ITERATION 0 DU POINT FIXE
C     NON UTILISE ICI PUISQUE PROBLEME LINEAIRE
C     LA NON LINEARITE EST PRISE EN COMPTE PAR L'INTEGRATION RETROGRADE
C     EN TEMPS LE LONG DES CARACTERISTIQUES
ccc      MNVITI = MNVXYZP0
C
C     FLUX DE LA VITESSE SUR LES SURFACES DE L'OBJET POUR UN TEMPS DONNE
      MOSFOB = NUMAOB(3) - NUMIOB(3) + 1
      CALL TNMCDC( 'REEL2', MOSFOB, MNFVSF )
C
C     BILAN DE L'INSTANT INITIAL
C     ==========================
C     LE PROCHAIN TEMPS POUR STOCKER LE VECTEUR VITESSEPRESSION
      TSTOC  = TPSINI + DTSTOC
      MNFLUI = MNVECT + WECTEU + MOREE2 * NTDLVP * (NBFLUI-1)
      MNTIME = MNVECT + WECTEU + MOREE2 * NTDLVP * MXFLUI - 1
C     LE DEBUT DU VECTEUR VITESSEPRESSION INITIALE
ccc      MNVITI = MNFLUI
C
C     CREATION OU AGMENTATION DU TMS 'VECTEUR"MAXVITESSEPRESS'
C     |VITESSE|Moyen, |VITESSE|Max, Max-MinPression Temps SONT STOCKES
C     A CHAQUE PAS DE TEMPS CALCULE pour TRACE des COURBES(Temps)
C     ----------------------------------------------------------------
      MXPAST = INT( ( TPSFIN - TPSINI ) / DT ) + 2
      NBPAST0= 0
      NBMXVP = 3
      NBPAST = MXPAST
      CALL LXTSOU( NTLXOB, 'VECTEUR"MAXVITESSEPRESS', NTMXVP, MNMXVP )
C
      IF( NTMXVP .GT. 0 ) THEN
C        NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR =? 3 MOYVIT, MAXVIT, MX-MIPRESS
         NBMXVP0 = MCN(MNMXVP+WBCOVE)
C        NOMBRE DE VECTEURS MAX VITESSE PRESSION = NOMBRE DE PAS DE TEMPS CALCUL
         NBPAST0 = MCN(MNMXVP+WBVECT)
         IF( NBMXVP0 .NE. NBMXVP .OR. NBFLUI .LE. 1 ) THEN
C           DESTRUCTION DU TMS
            CALL LXTSDS( NTLXOB, 'VECTEUR"MAXVITESSEPRESS' )
            NBPAST0 = 0
         ELSE
C           CE TABLEAU EST AUGMENTE DE MXPAST VECTEURS
            NBPAST = NBPAST0 + MXPAST
            MOTSVP = WECTEU + MOREE2 * NBMXVP * NBPAST + NBPAST
            CALL TAMSAU( NTMXVP, MOTSVP )
C           IL EST REOUVERT CAR ADRESSE MCN MODIFIEE
            GOTO 13
         ENDIF
      ENDIF
C
C     CONSTRUCTION DU TMS 'VECTEUR"MAXVITESSEPRESS'
      MOTSVP = WECTEU + MOREE2 * NBMXVP * NBPAST + NBPAST
      CALL LXTNDC( NTLXOB, 'VECTEUR"MAXVITESSEPRESS', 'REEL', MOTSVP )
C
 13   CALL LXTSOU( NTLXOB, 'VECTEUR"MAXVITESSEPRESS', NTMXVP, MNMXVP )
C     NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR = 3 MOYVIT, MAXVIT, MX-MIPRESSION
      MCN(MNMXVP+WBCOVE) = NBMXVP
C     NOMBRE DE VECTEURS MAX VITESSE PRESSION = NOMBRE DE PAS DE TEMPS
      MCN(MNMXVP+WBVECT) = NBPAST
C     NOMBRE DE TEMPS A LA FIN DES VECTEURS
      MCN(MNMXVP+WBCPIN) = NBPAST
C     ADRESSE MCN DES 3 VECTEURS
      MNMAXVIT = MNMXVP   + WECTEU
      MNTIMXVP = MNMAXVIT + MOREE2 * NBMXVP * NBPAST
      IF( NBPAST0 .GT. 0 ) THEN
C        LE STOCKAGE DU TEMPS POUR LE TMS VECTEUR"MAXVITESSEPRESS EST DECALE
         MN = MNMXVP + WECTEU + MOREE2 * NBMXVP0 * NBPAST0
         CALL TRTATA( RMCN(MN), RMCN(MNTIMXVP), NBPAST0 )
      ENDIF
C
C     AFFICHAGE DU VECTEUR"VITESSEPRESSION AU TEMPS INITIAL
C     -----------------------------------------------------
      CALL AFVIPR( NUTYEL, NDIM, NBNOVI, MNXYZN, MCN(MNNDDL),
     %             TEMPS,  NTDLVP, MIN(10,NBNOVI), MCN(MNVXYZP0),
     %             VITMIN, VITMAX, VITMOY, PREMIN, PREMAX, PREMOY )
C
C     STOCKAGE EN POSITION NBPAS DE VITMOY, VITMAX, PREMAX-PREMIN, TEMPS
      NBPAS = NBPAST0 + 1
      MN = ( MNMAXVIT - 1 ) / MOREE2 + NBMXVP * (NBPAS-1)
      DMCN( MN+1 ) = VITMOY
      DMCN( MN+2 ) = VITMAX
      DMCN( MN+3 ) = PREMAX-PREMIN
      RMCN( MNTIMXVP-1+NBPAS ) = TEMPS
C
C     TEMPS CPU DE FABRICATION DES VECTEURS GLOBAUX
      DFABG = DINFO( 'DELTA CPU' )
C
C
C     ############################################################
C     ##                                                        ##
C     ##  LA BOUCLE EN TEMPS AVEC UN PAS DE TEMPS CONSTANT = DT ##
C     ##                                                        ##
C     ############################################################
C
C     EF de TAYLOR-HOOD P2 EN VITESSE et P1 EN PRESSION
C     BOUCLE SUR LES ELEMENTS FINIS POUR CONSTRUIRE U(tn+1)
C     VITESSE EN INTEGRATION SEMI IMPLICITE EN TEMPS
C     VG U(tn+1) = (Rho - dt Mhu Laplacien ) U(tn+1) =
C      = Rho U(tn,X(tn+1,x) - dt UnSRho GRAD P(tn) + dt Force(tn+1)
C     -------------------------------------------------------------
C     LES RESULTATS SONT MAINTENANT AU TEMPS + DT
C     .............................................................
 100  TEMPS   = TEMPS   + DT
      NBPASDT = NBPASDT + 1
C
C     mIter NOMBRE D'ITERATIONS DE POINT FIXE POUR TRAITER LE COUPLAGE
C     ET LE TERME NON LINEAIRE DE TRANSPORT
      mIter   = 0
      NORVIM0 = 0
      NORPRM0 = 0
C
C     Vn+1,0 = Vn  dans  MNV3P0 = MNVITX0, MNVITY0, MNVITZ0, MNPRES0
C                                 VITtn+1,m
C
      CALL TRTATD( MCN(MNV3P0), MCN(MNV3Ptn), NBNOVI * (NDIM+1) )
C                  dans  MNV3Ptn = MNVITXtn, MNVITYtn, MNVITZtn, MNPREStn
C     LES ADRESSES MCN INTERMEDIAIRES DES VECTEURS INDEPENDANTS
C     NDIM COMPOSANTES DE LA VITESSE ET PRESSION AU TEMPS tn
      MNVITXtn = MNV3Ptn
      MNVITYtn = MNVITXtn + MOREE2 * NBNOVI
      MNVITZtn = MNVITYtn + MOREE2 * NBNOVI
      MNPREStn = MNVITXtn + MOREE2 * NBNOVI * NDIM
C
C     Les iterations m pour obtenir un point fixe du probleme non lineaire
C     --------------------------------------------------------------------
 111  mIter = mIter + 1
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10111) TEMPS, mIter
      ELSE
         WRITE(IMPRIM,20111) TEMPS, mIter
      ENDIF
10111 FORMAT(/'fpisonlth: CALCUL VITESSE et PRESSION au TEMPS ',G14.6,
     %' m=',I4,'  Methode PISO: ',70('*'))
20111 FORMAT(/'fpisonlth: VELOCITY PRESSURE COMPUTATION at TIME ',G14.6,
     %' m=',I4,'  PISO Method: ',70('*'))
C
C     NDIM COMPOSANTES DE LA VITESSE ET PRESSION AU TEMPS tn+1,m
      MNVITX0 = MNV3P0
      MNVITY0 = MNVITX0 + MOREE2 * NBNOVI
      MNVITZ0 = MNVITY0 + MOREE2 * NBNOVI
      MNPRES0 = MNVITX0 + MOREE2 * NBNOVI * NDIM
C
C     NDIM COMPOSANTES DE LA VITESSE ET PRESSION AU TEMPS tn+1,m+1
      MNVITX1 = MNV3P1
      MNVITY1 = MNVITX1 + MOREE2 * NBNOVI
      MNVITZ1 = MNVITY1 + MOREE2 * NBNOVI
      MNPRES1 = MNVITX1 + MOREE2 * NBNOVI * NDIM
C
C     =====================================================================
C     TETRAEDRE TAYLOR-HOOD EN VITESSE et P1 EN PRESSION
C     BOUCLE SUR LES ELEMENTS FINIS POUR CONSTRUIRE Vm+1
C     VG Vm+1 = (Id/dt - Mhu/Rho Laplacien ) Vm+1
C             =  1/dt V(tn)
C              - (Vm . Grad) Vm
C              + 1/Rho Force(tn+1)
C              - 1/Rho Grad P(tn)
C     C. L.  Vm+1 = V(tn+1) SUR LA FRONTIERE
C
C     => CALCUL de
C     Integrale  tP2 1/dt P2 dX V(tn,Se)
C   - Integrale  tP2 P2 Vem(Se) . Grad P2 Vem(Se) dX
C   + Integrale  tP2 P2 Force(tn+1,Se) dX / Rho
C   - Integrale  tP2 Grad P1 Pm(Se) )  dX / Rho
C     =====================================================================
C     MISE A ZERO DE V3P1
      CALL AZEROD( NTDLVP, DMCN((MNV3P1+1)/MOREE2) )
C
C     BOUCLE SUR LES EF
      DO NUELEM = 1, NBELEM
C
C        NO DES NOEUDS DE L'ELEMENT FINI NUELEM
         CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOTE )
C
C        NO DE  POINTS  LIGNES SURFACES VOLUMES
C           DES SOMMETS ARETES FACES    VOLUME DU TETRAEDRE NUELEM
         CALL EFPLSV( MNELE , NUELEM,
     %                NOVCEL, NOSFEL, NOLAEL, NOPSEL,
     %                NOOBVC, NOOBSF, NOOBLA, NOOBPS )
C
C        INTERPOLATION DU FLUIDE avec F: e reference->e  P1 ndim
C        COORDONNEES DES NBNOEF SOMMETS=POINTS=NOEUDS DE L'EF
         CALL EFXYZP( NDIM, MNXYZN, NBELEM, NUELEM, MNPGEL, NBNOEF,
     %                XYZEF )
C
         IF( NUTYEL .EQ. 15 ) THEN
C
C           TRIANGLE TAYLOR-HOOD
            CALL F2BVETH( UnSdt,  UnSRho, 1D0, 1D0,
     %                    XYZEF,  NONOTE, NBNOVI, NBSOM, MCN(MNNOSO),
     %            NOOBLA, NUMIOB(2), NUMAOB(2), MCN(MNDOEL(2)), IEFOCL,
     %            NOOBSF, NUMIOB(3), NUMAOB(3), MCN(MNDOEL(3)), IEFOIN,
     %                    MCN(MNV3Ptn), MCN(MNV3P0), MCN(MNPRES0),
     %                    AE )
         ELSE
C
C           TETRAEDRE TAYLOR-HOOD
            CALL F3BVETH( UnSdt,  UnSRho, 1D0, 1D0,
     %                    XYZEF,  NONOTE, NBNOVI, NBSOM, MCN(MNNOSO),
     %            NOOBSF, NUMIOB(3), NUMAOB(3), MCN(MNDOEL(3)), IEFOCL,
     %            NOOBVC, NUMIOB(4), NUMAOB(4), MCN(MNDOEL(4)), IEFOIN,
     %                    MCN(MNV3Ptn), MCN(MNV3P0), MCN(MNPRES0),
     %                    AE )
         ENDIF
C
ccc         IF( NUELEM .LE. 3 ) THEN
ccc            call affvect( 'Sortie F23BVETH', 30, AE )
ccc         ENDIF
C
C        ASSEMBLAGE DE AE dans V3P1 = VITX1, VITY1, VITZ1
         CALL ASMEEX1( NDIM, NBNOEF, NONOTE, AE, NBNOVI, MCN(MNV3P1) )
C
      ENDDO
C     FIN DE LA BOUCLE SUR LES EF DE LA CONSTRUCTION DE V3P1
ccc      CALL AFTABLE( 'BG Vitesses ', NBNOVI, 3, MCN(MNV3P1),
ccc     %               NBNOVI-10, NBNOVI, 1, 3 )
C
C     LISTE DES DL VITESSES FIXEES AU TEMPS tn+1,m+1
C     ----------------------------------------------
      CALL VITEFX( RELMIN, NTDLVI, NDIM,   MNXYZN,
     %             NBTYEL, MNNPEF, NUMIOB, MNDOEL,
     %             NBVCFX, NBVIFX, MNDLVIFX, MNVAVIFX, VITFXMAX )
C
C     BLOCAGE DES COMPOSANTES FIXEES DE LA VITESSE AU TEMPS tn+1,m+1 SUR V3P1
      CALL VITEFXVG( NBVIFX, MCN(MNDLVIFX), MCN(MNVAVIFX), STGV,
     %               NDIM, NBNOVI, MCN(MNV3P1) )
ccc      CALL AFTABLE( 'BG Vitesses+CL ', NBNOVI, 3, MCN(MNV3P1),
ccc     %               NBNOVI-10, NBNOVI, 1, 3 )
C
C     RESOLUTION EN VITESSES: i=1,...,NDIM
C     Integrale  1/dt  tP2 P2 + Mhu/Rho tGrad P2 Grad P2 dx  V*i
C   = Integrale  1/dt  tP2 Vi(tn,X(tn;tn+1,bl) dX
C   - Integrale  1/Rho tP2 Grad P(tn) dX
C   + Integrale  1/Rho tP2 Force(tn)  dX
C     =======================================================================
      IF( NORESO .EQ. 1 ) THEN
C
C        DESCENTE et REMONTEE DU PROFIL DE LA MATRICE VITESSE
C        L tL COMPLETE DES NDIM COMPOSANTES DE LA VITESSE U*(tn+1)
         MNV1 = MNV3P1
         DO K = 1, NDIM
            CALL DRCHPR( NBNOVI, NCODSV, MCN(MNPTDV), VG, MCN(MNV1), 3,
     %                   MCN(MNV1) )
ccc            call affvect( 'Apres DRCHPR: VITESSE*i', 30, MCN(MNV1) )
            MNV1 = MNV1 + MOREE2 * NBNOVI
         ENDDO
C
      ELSE IF( NORESO .EQ. 2 ) THEN
C
C        RESOLUTION PAR GC SIMPLE SANS PRECONDITIONNEMENT DES
C        NDIM COMPOSANTES DE LA VITESSE U*(tn+1)
C
C        LE VECTEUR INITIAL DU GC EST LE DERNIER VECTEUR CALCULE
C        PROTECTION CAR B DOIT ETRE DIFFERENT DE X DANS LE GC
         CALL TRTATD( MCN(MNV3P1), MCN(MNV3P2), NDIM*NBNOVI )
         MNVB = MNV3P2
         MNV0 = MNV3P0
         MNV1 = MNV3P1
C        EN SORTIE DE GCAXB LA SOLUTION EST DANS MNV1=MNV3P1
         DO K = 1, NDIM
            CALL GCAXB( NBNOVI,       MCN(MNNDVFX),
     %                   MCN(MNPTDV),  MCN(MNLPCV),  VG,
     %                   MCN(MNVB),    MCN(MNV0),
     %                   MCN(MNAUX1),  MCN(MNAUX2),  MCN(MNAUX3),
     %                   MCN(MNV1),     IERR )
ccc            call affvect( 'Apres GCAXB: VITESSE*i', 30, MCN(MNV1) )
C
C           VERIFICATION DE LA CONVERGENCE DU GC
            IF( IERR .NE. 0 ) THEN
C              IL N'Y A PAS EU CONVERGENCE DU GC
C              LA METHODE DU GC NE CONVERGE PAS => ABANDON DES CALCULS
               WRITE(KERR(MXLGER)(1:10),'(I10)') NBNOVI
               NBLGRC(NRERR) = 3
               IF( LANGAG .EQ. 0 ) THEN
                  KERR(1) = 'NON CONVERGENCE APRES '//KERR(MXLGER)(1:10)
     %                   // ' ITERATIONS DU GC SIMPLE'
                  KERR(2) = 'ABANDON DE LA METHODE DU GRADIENT CONJUGUE'
                  KERR(3) = 'ESSAYER UNE AUTRE METHODE DE RESOLUTION'
               ELSE
                  KERR(1) = 'NO CONVERGENCE after '// KERR(MXLGER)(1:10)
     %                   // ' ITERATIONS of SIMPLE CG'
                  KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
                  KERR(3) = 'TRY an OTHER METHOD'
               ENDIF
               CALL LEREUR
               IERR = 9
               GOTO 9999
            ENDIF
C
ccc            call affvect( 'Apres Gcaxb Vitesse*i=', 30, MCN(MNV1) )
            MNV0 = MNV0 + MOREE2 * NBNOVI
            MNV1 = MNV1 + MOREE2 * NBNOVI
            MNVB = MNVB + MOREE2 * NBNOVI
         ENDDO
C
      ENDIF
ccc      CALL AFTABLE( 'Vitesses ', NBNOVI, 3, MCN(MNV3P1),
ccc     %               NBNOVI-10, NBNOVI, 1, 3 )
C
C     ========================================================================
C     PISO  CALCUL DE LA PRESSION P(tn+1,m+1) PAR LA RESOLUTION DE
C (2) - 1/Rho Laplacien Pm+1(X) = Div { -Fg(tn+1)/Rho
C                                     + Vm+1 . Grad Vm+1 } dans Omega
C     Condition aux limites
C            -1/Rho    dPm+1/dn = n . ( -Fg(tn+1)/Rho
C                                     +  Vm+1 . Grad Vm+1 } sur Gamma
C     or Pn+1,m+1(Gamma) = P(tn+1,Gamma) pour Gamma point sur la frontiere
C
C     REMARQUE: TOUTE LA SURFACE FRONTIERE DOIT FAIRE PARTIE DE L'OBJET
C               POUR PRENDRE EN COMPTE LA NORMALE SUR LE TERME NON LINEAIRE
C     ========================================================================
C     CALCUL DU SECOND MEMBRE BG avec la
C     Version 1 de PISO: Bg avec Div reportee sur la Pression
      IF( NUTYEL .EQ. 15 ) THEN
C        TRIANGLE TAYLOR-HOOD
         CALL F2BPGTH( UnSRho,
     %                 NBSOM,  NBNOVI, MNXYZN, MNPGEL, MCN(MNNOSO),
     %                 MNELE,  NBELEM,
     %                 NOOBLA,
     %                 NOOBSF, NUMIOB(3), NUMAOB(3), MCN(MNDOEL(3)),
     %                 MCN(MNV3P1),  MCN(MNP2DP2),   MCN(MNPRES1) )
      ELSE
C        TETRAEDRE TAYLOR-HOOD
         CALL F3BPGTH( UnSRho,
     %                 NBSOM,  NBNOVI, MNXYZN, MNPGEL, MCN(MNNOSO),
     %                 MNELE,  NBELEM,
     %                 NOOBSF,
     %                 NOOBVC, NUMIOB(4), NUMAOB(4), MCN(MNDOEL(4)),
     %                 MCN(MNV3P1),  MCN(MNP2DP2),   MCN(MNPRES1) )
      ENDIF
C
ccc      call affvect('Sd Membre Pression )',    20, MCN(MNPRES1) )
ccc      call afl1ve( 'Sd Membre Pression )', NBSOM, MCN(MNPRES1) )
C
C     CONSTRUCTION DES TABLEAUX NO ET VALEURS DES PRESSIONS FIXEES a tn+1
C     -------------------------------------------------------------------
      IF( IEBLPR .GT. 0 ) THEN
         CALL PRESFXST( RELMIN, NBSOM,    NDIM,   MNXYZN, MNNOSO,
     %                  NBTYEL, MNNPEF,   NUMIOB, MNDOEL,
     %                  NBPRFX, MNDLPRFX, MNVAPRFX )
      ELSE
         NBPRFX = 0
      ENDIF
C
C     PRISE EN COMPTE DES DEGRES DE LIBERTE PRESSION FIXES P(TN+1)
C     ------------------------------------------------------------
      IF( NORESO .EQ. 1 ) THEN
         MNP1 = ( MNPRES1 - 1 ) / MOREE2
         MM   = MNPRES1
      ELSE
C        COPIE DE MNPRES1 DANS MNPRPR POUR LE GC
         CALL TRTATD( MCN(MNPRES1), MCN(MNPRPR), NBSOM )
         MNP1 = ( MNPRPR - 1 ) / MOREE2
         MM   = MNPRPR
      ENDIF
      MNV = ( MNVAPRFX - 1 ) / MOREE2
      DO I=1, NBPRFX
C        LE NO SOMMET GLOBAL DU DL FIXE
         NDL = MCN( MNDLPRFX - 1 + I )
C        VALEUR FIXEE DE LA PRESSION  P(TN+1)
         DMCN(MNP1+NDL) = STGV * DMCN(MNV+I)
      ENDDO
C
ccc      call affvect( 'Apres CL Pression(tn+1,m+1)=', 20, MCN(mm) )
      IF( NORESO .EQ. 1 ) THEN
C
C        ------------------------------------------------------------------
C        RESOLUTION de P(tn+1,m+1) = [L tL]-1 Div(-FOmega+Rho U.Grad U)
C        PAR DESCENTE REMONTEE DE LA MATRICE FACTORISEE PG = L tL PROFIL
C        ------------------------------------------------------------------
         CALL DRCHPR( NBSOM, NCODSP, MCN(MNPTDP), PG, MCN(MNPRES1), 3,
     %                MCN(MNPRES1) )
ccc         call affvect( 'Apres DRCHPR PR(tn+1,m+1)=',   20, MCN(MNPRES1))
ccc         call afl1ve(  'Apres DRCHPR Pr(tn+1,m+1)=',NBSOM, MCN(MNPRES1))
C
      ELSE IF( NORESO .EQ. 2 ) THEN
C
C        ----------------------------------------------------------------
C        RESOLUTION de P(tn+1,m+1) = [PG]-1 Div(-FOmega+Rho U.Grad U)
C        PAR GRADIENT CONJUGUE SIMPLE AVEC MATRICE SYMETRIQUE MORSE
C        ----------------------------------------------------------------
C        X0 DU GC EST P(tn+1) CALCULE AUPARAVANT
         CALL GCAXB( NBSOM,        MCN(MNNDPFX),
     %                MCN(MNPTDP),  MCN(MNLPCP),  PG,
     %                MCN(MNPRPR),  MCN(MNPRES0),
     %                MCN(MNAUX1),  MCN(MNAUX2),  MCN(MNAUX3),
     %                MCN(MNPRES1), IERR )
ccc         call affvect( 'Apres Gcaxb PR(tn+1,m+1)=',   20, MCN(MNPRES1) )
ccc         call afl1ve(  'Apres Gcaxb Pr(tn+1,m+1)=',NBSOM, MCN(MNPRES1) )
C
C        VERIFICATION DE LA CONVERGENCE DU GC
         IF( IERR .NE. 0 ) THEN
C           IL N'Y A PAS EU CONVERGENCE DU GC
C           LA METHODE DU GC NE CONVERGE PAS => ABANDON DES CALCULS
            WRITE(KERR(MXLGER)(1:10),'(I10)') NBSOM
            NBLGRC(NRERR) = 3
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'NON CONVERGENCE APRES '//KERR(MXLGER)(1:10)
     %                   // ' ITERATIONS DU GC SIMPLE'
               KERR(2) = 'ABANDON DE LA METHODE DU GRADIENT CONJUGUE'
               KERR(3) = 'ESSAYER UNE AUTRE METHODE DE RESOLUTION'
            ELSE
               KERR(1) = 'NO CONVERGENCE after '// KERR(MXLGER)(1:10)
     %                   // ' ITERATIONS of SIMPLE CG'
               KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
               KERR(3) = 'TRY an OTHER METHOD'
            ENDIF
            CALL LEREUR
            IERR = 9
            GOTO 9999
         ENDIF
C
      ELSE IF( NORESO .EQ. 3 ) THEN
C
C        ----------------------------------------------------------------
C        RESOLUTION DU SYSTEME PAR GRADIENT CONJUGUE AVEC CROUT INCOMPLET
C        ----------------------------------------------------------------
C
C        PRISE EN COMPTE DES DEGRES DE LIBERTE PRESSION FIXES SUR BG
C        -----------------------------------------------------------
         CALL PRESFXBG( NBPRFX, MCN(MNDLPRFX), MCN(MNVAPRFX),
     %                  NBSOM, MCN(MNPRES1) )
C
C        MISE A ZERO DU TABLEAU AUXILIAIRE
         CALL AZEROD( LOAUX, DMCN((MNAUX1+1)/MOREE2) )
C        MISE A ZERO DU TABLEAU DES DIRECTIONS
         CALL AZEROD( LODIR, DMCN((MNBDIR+1)/MOREE2) )
C        RESOLUTION GC PRECONDITIONNE PAR CROUT INCOMPLET
C        LE VECTEUR INITIAL DU GC EST LE DERNIER VECTEUR CALCULE
         CALL GCPRCR( NBSOM,       1,           NBDIR,   MCN(MNNDPFX),
     %                MCN(MNPTDP), MCN(MNLPCV), PG,      MCN(MNPRES1),
     %                MCN(MNLPLC), MCN(MNLPCC), MCN(MNPGC),
     %                MCN(MNPRES0),MCN(MNAUX1), MCN(MNAUX2),MCN(MNAUX3),
     %                MCN(MNDIR),  MCN(MNADIR), MCN(MNDAD),  MCN(MNBET),
     %                MCN(MNPRES1), IERR )
ccc         call affvect( 'Apres GCPRCR PRESSION1=', 20, MCN(MNPRES1) )
C
C        VERIFICATION DE LA CONVERGENCE DU GC
         IF( IERR .NE. 0 ) THEN
C           IL N'Y A PAS EU CONVERGENCE DU GC
C           LA METHODE DU GC NE CONVERGE PAS => ABANDON DES CALCULS
            WRITE(KERR(MXLGER)(1:8),'(I8)') NIVOGC
            NBLGRC(NRERR) = 3
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'NON CONVERGENCE AU NIVEAU '//KERR(MXLGER)(1:8)
               KERR(2) = 'ABANDON DE LA METHODE DU GRADIENT CONJUGUE'
               KERR(3) = 'ESSAYER FACTORISATION COMPLETE DE CHOLESKY MAT
     %RICE PROFIL'
            ELSE
               KERR(1) = 'NO CONVERGENCE at LEVEL '// KERR(MXLGER)(1:8)
               KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
          KERR(3)='TRY FULL CHOLESKY FACTORIZATION with SKYLINE STORAGE'
            ENDIF
            CALL LEREUR
            IERR = 9
            GOTO 9999
         ENDIF
C
      ENDIF
C
ccc      call affvect(
ccc     %'Solution PR of -UnSRho LAPLACIEN P = Div(-FOmega+Rho U.Grad U)',
ccc     %              20, MCN(MNPRES1) )
ccc      call afl1ve(
ccc     %'Solution Pr of -UnSRho LAPLACIEN P = Div(-FOmega+Rho U.Grad U)',
ccc     %              NBSOM, MCN(MNPRES1))
C
C     PASSAGE DE VITX,VITY,VITZ,PRESSION(tn+1,m+1) PAR COMPOSANTES
C     A VXYZP(tn+1,m+1) PAR NOEUDS
C     ============================================================
      CALL VXYZPRE(NDIM, NUTYEL, MCN(MNNDDL),
     %             1, NBNOVI, MCN(MNVITX1), MCN(MNVITY1), MCN(MNVITZ1),
     %             NBSOM,  MCN(MNNOSO), MCN(MNPRES1),
     %             NTDLVP, MCN(MNVXYZP0) )
C
C     CONVERGENCE DES ITERATIONS mIter ?
C     ==================================
      CALL NORMDIF( 3*NBNOVI, MCN(MNV3P0), MCN(MNV3P1), DIFVIM, NORVIM )
      CALL NORMDIF( NBSOM,  MCN(MNPRES0), MCN(MNPRES1), DIFPRM, NORPRM )
      IF( NORVIM0 .GT. 0D0 ) THEN
         DIFMAX = DIFVIM / NORVIM0
      ELSE
         DIFMAX  = DIFVIM
         NORVIM0 = NORVIM
      ENDIF
      IF( NORPRM0 .GT. 0D0 ) THEN
         DIFMAX = MAX( DIFMAX, DIFPRM/NORPRM0 )
      ELSE
         DIFMAX  = MAX( DIFMAX, DIFPRM )
         NORPRM0 = NORPRM
      ENDIF
C
      WRITE(IMPRIM,10300) TEMPS, mIter, DIFVIM, NORVIM, DIFPRM, NORPRM,
     %                    DIFMAX
10300 FORMAT(/'TEMPS',G13.5,' Iter m=',I3,
     % ' ||Vn+1,m+1-Vn+1,m||/NbV=',G15.7,' ||Vn+1,m||/NbV=',G15.7,
     %'  ||Pn+1,m+1-Pn+1,m||/NbP=',G15.7,' ||Pn+1,m||/NbP=',G15.7,
     %' Test=',G13.5)
C
      IF( DIFMAX .LT. 1D15 ) THEN
         IF( DIFMAX .GT. 0.001D0 ) THEN
C           UNE ITERATION mIter A FAIRE DE PLUS
            IF( mIter .LE. mIterMax ) THEN
               MN     = MNV3P0
               MNV3P0 = MNV3P1
               MNV3P1 = MN
               GOTO 111
            ELSE
               GOTO 301
            ENDIF
         ENDIF
         GOTO 303
      ENDIF
C
C     DIVERGENCE OU NOMBRE D'ITERATIONS MAX ATTEINT
 301  WRITE(IMPRIM,10301) TEMPS, mIterMax
10301 FORMAT(/'Time',G13.5,' m=Nb Iteration MAX=',I3,
     %        ' ATTAINED => DETECTED DIVERGENCE. STOP'//)
      IERR = 10
      GOTO 305
C
C     ICI CONVERGENCE DES ITERATIONS mIter de POINT FIXE
C     --------------------------------------------------
 303  WRITE(IMPRIM,10303) TEMPS, mIter
10303 FORMAT('+++++ TEMPS',G13.5,' Iteration m=',I3,' => CONVERGENCE')
C
C     AFFICHAGE DU VECTEUR"VITESSEPRESSION(tn+1,m+1) NBFLUI AU TEMPS
C     --------------------------------------------------------------
 305  CALL AFVIPR( NUTYEL, NDIM, NBNOVI, MNXYZN, MCN(MNNDDL),
     %             TEMPS,  NTDLVP, MIN(10,NBNOVI), MCN(MNVXYZP0),
     %             VITMIN, VITMAX, VITMOY, PREMIN, PREMAX, PREMOY )
C
C     STOCKAGE EN POSITION NBPAS DE VITMOY, VITMAX, PREMAX-PREMIN, TEMPS
      NBPAS = NBPAS + 1
      MN    = ( MNMAXVIT - 1 ) / MOREE2 + NBMXVP * (NBPAS-1)
      DMCN( MN+1 ) = VITMOY
      DMCN( MN+2 ) = VITMAX
      DMCN( MN+3 ) = PREMAX-PREMIN
      RMCN( MNTIMXVP-1+NBPAS ) = TEMPS
C
C     FLUX DE LA VITESSE A TRAVERS LES FACES DES SURFACES DE L'OBJET
C     --------------------------------------------------------------
C     MNELE=MCN( MNNPEF ): ADRESSE DU TABLEAU NPEF"TYPE EF
      CALL FLUVITSF( MNXYZN, MCN(MNNPEF), MCN(MNNDDL), MCN(MNVXYZP0),
     %               NUMIOB(3), NUMAOB(3),
     %               FLUNEG, FLUPOS, MCN(MNFVSF) )
C
C     STOCKAGE DES RESULTATS AU NBPASR
      NBPASR = NBPASR + 1
      RESULT(1,NBPASR) = TEMPS
      RESULT(2,NBPASR) = VITMOY
      RESULT(3,NBPASR) = VITMAX
      RESULT(4,NBPASR) = PREMOY
      RESULT(5,NBPASR) = PREMAX - PREMIN
      RESULT(6,NBPASR) = FLUNEG
      RESULT(7,NBPASR) = FLUPOS
      RESULT(8,NBPASR) = NBPASDT
C
C     STOCKAGE OU PAS DU VECTEUR SOLUTION?
      IF( TEMPS .GE. TSTOC*0.9999 ) THEN
C        STOCKAGE DE LA VITESSEPRESSION A CET INSTANT TEMPS
         MNFLUI = MNVECT + WECTEU + MOREE2 * NTDLVP * NBFLUI
C        LE NOMBRE DE VECTEURS VITESSEPRESSION STOCKES
         NBFLUI = NBFLUI + 1
         CALL TRTATD( MCN(MNVXYZP0), MCN(MNFLUI), NTDLVP )

C        STOCKAGE DE LA VITESSEPRESSION NBFLUI A CET INSTANT TEMPS
C        SUR FICHIER DU REPERTOIRE DU PROJET
         NAVIER = 3
         CALL ECFIVIPR( KNOMOB, TEMPS,  NBFLUI,
     %                  NAVIER, NORESO, NIVOGC, NBPASDT,
     %                  NBNOVI, NBSOM,
     %                  NTDLVP, MCN(MNVXYZP0),
     %                  KNOMFIC, IERR )

C        LE TEMPS DE STOCKAGE
         MNTIME = MNVECT + WECTEU + MOREE2 * NTDLVP * MXFLUI - 1
         RMCN(MNTIME+NBFLUI) = TEMPS
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10350) TEMPS, NTDLVP, NBFLUI
         ELSE
            WRITE(IMPRIM,20350) TEMPS, NTDLVP, NBFLUI
         ENDIF
C        LE PROCHAIN TEMPS DE STOCKAGE
         TSTOC = TSTOC + DTSTOC
      ENDIF
C
10350 FORMAT(' Au TEMPS',G14.6,' STOCKAGE de',I7,' VITESSEPRESSION',
     %   ' en COLONNE',I5,' du TMS VECTEUR"VITESSEPRESSION')
20350 FORMAT(' At TIME',G14.6,' STORAGE of',I7,' VELOCITY PRESSURE',
     %   ' in COLUMN',I5,' of TMS VECTEUR"VITESSEPRESSION')
C
C     PERMUTATION DE MNV3P0 (tn+1,m) ET MNV3P1 (tn+1,m+1)
C     ---------------------------------------------------
      MN     = MNV3P0
      MNV3P0 = MNV3P1
      MNV3P1 = MN
      IF( IERR .NE. 0 ) GOTO 360
C
      IF( TEMPS + DT .LT. TPSFIN*1.00001 ) GOTO 100
C
C    ##############################################################
C    ##                                                          ##
C    ##                FIN DE LA BOUCLE EN TEMPS                 ##
C    ##                                                          ##
C    ##############################################################
C
C
 360  IF( RMCN(MNTIME+NBFLUI) .NE. TEMPS ) THEN
C        STOCKAGE DES VITESSEPRESSION A CET INSTANT
         MNFLUI = MNVECT + WECTEU + MOREE2 * NTDLVP * NBFLUI
         CALL TRTATD( MCN(MNVXYZP0), MCN(MNFLUI), NTDLVP )
C        LE NOMBRE DE VECTEURS VITESSEPRESSION STOCKES
         NBFLUI = NBFLUI + 1
C        LE TEMPS DE STOCKAGE
         MNTIME = MNVECT + WECTEU + MOREE2 * NTDLVP * MXFLUI - 1
         RMCN(MNTIME+NBFLUI) = TEMPS
         WRITE(IMPRIM,10350) TEMPS, NTDLVP, NBFLUI
      ENDIF
C
C     MISE A JOUR DU TMS 'VECTEUR"VITESSEPRESSION'
C     ============================================
      MCN( MNVECT + WBCOVE ) = NTDLVP
      MCN( MNVECT + WBVECT ) = NBFLUI
      MCN( MNVECT + WBCPIN ) = NBFLUI
      IF( NBFLUI .LT. MXFLUI ) THEN
C        LE TMS EST RACOURCI
         L  = MNVECT + WECTEU + NTDLVP * MXFLUI * MOREE2 - 1
         L1 = MNVECT + WECTEU + NTDLVP * NBFLUI * MOREE2 - 1
         DO 200 I=1,NBFLUI
            RMCN(L1+I) = RMCN(L+I)
 200     CONTINUE
         CALL TAMSRA( NTVECT, WECTEU+NTDLVP*NBFLUI*MOREE2+NBFLUI )
      ENDIF
C     LA DATE
      CALL ECDATE( MCN(MNVECT) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVECT + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
C     L'ADRESSE-1 DU PREMIER TEMPS STOCKE DERRRIERE LES MXFLUI
C     VECTEURS VITESSEPRESSION
      MNTIME = MNVECT + WECTEU + NTDLVP * MXFLUI * MOREE2 -1
C
C     AFFICHAGE DU TABLEAU DES RESULTATS GLOBAUX sur V(t,r)
C     =====================================================
      WRITE(IMPRIM,*)
      WRITE(IMPRIM,19991)
      WRITE(IMPRIM,*)
     %'ARRAY of V(t,r) RESULT at every TIME STEP during the INTERVAL of
     %TIME (',TPSINI, TPSFIN,' )'
      WRITE(IMPRIM,19991)
19991 FORMAT(180('='))
      VMOYMOY = 0D0
      VMAXMAX = RESULT(3,1)
      PMOYMOY = 0D0
      PMXIMXI = RESULT(5,1)
      DO K=1,NBPASR
         WRITE(IMPRIM,19990) (RESULT(I,K),I=1,7),RESULT(6,K)+RESULT(7,K)
         VMOYMOY = VMOYMOY + RESULT(2,K)
         IF( RESULT(3,K) .GT. VMAXMAX ) VMAXMAX = RESULT(3,K)
         PMOYMOY = PMOYMOY + RESULT(4,K)
         IF( RESULT(5,K) .GT. PMXIMXI ) PMXIMXI = RESULT(5,K)
      ENDDO
19990 FORMAT('Time=',G12.5,' VelocityMean=',G14.6,' VelocityMax=',G14.6,
     %' PressureMean=',G14.6,' PressMax-Min=',G14.6,
     %' Flux-=',G14.6,' Flux+=',G14.6,' Flux-+ =',G14.6)
C
C     TOTAUX
      VMOYMOY = VMOYMOY / NBPASR
      PMOYMOY = PMOYMOY / NBPASR
      WRITE(IMPRIM,19991)
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*)
     %'Vitesse MOYENNE MAXIMA, PRESSION Max-Min sur l''INTERVALLE de TEM
     %PS [',TPSINI, TPSFIN,' ]'
      ELSE
         WRITE(IMPRIM,*)
     %'MEANS and MAXIMA of Velocity during the INTERVAL of TIME (',
     %TPSINI, TPSFIN,' )'
      ENDIF
      WRITE(IMPRIM,19990) RESULT(1,NBPASR),VMOYMOY, VMAXMAX,
     %                    PMOYMOY, PMXIMXI
      WRITE(IMPRIM,19991)
C
C     AFFICHAGE DU VECTEUR"VITESSEPRESSION V(NBFLUI) AU TEMPS FINAL
C     -------------------------------------------------------------
      MN = MNVECT+WECTEU + MOREE2 * (NBFLUI-1) * NTDLVP
      CALL AFVIPR( NUTYEL, NDIM,   NBNOVI, MNXYZN, MCN(MNNDDL),
     %             TEMPS,  NTDLVP, MIN(32,NBNOVI), MCN(MN),
     %             VITMIN, VITMAX, VITMOY, PREMIN, PREMAX, PREMOY )
C
C     STOCKAGE EN POSITION NBPAS DE VITMOY, VITMAX, PREMAX-PREMIN, TEMPS
ccc      NBPAS = NBPAS + 1
      MN    = ( MNMAXVIT - 1 ) / MOREE2 + NBMXVP * (NBPAS-1)
      DMCN( MN+1 ) = VITMOY
      DMCN( MN+2 ) = VITMAX
      DMCN( MN+3 ) = PREMAX-PREMIN
      RMCN( MNTIMXVP-1+NBPAS ) = TEMPS
C
C     MISE A JOUR TMS VECTEUR"MAXVITESSEPRESS
C    (NBPAS PEUT ETRE DIFFERENT DE NBPAST)
C     ---------------------------------------
C     NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR = 3 MOYVIT, MAXVIT, MX-MIPRESSION
      MCN(MNMXVP+WBCOVE) = NBMXVP
C     NOMBRE DE VECTEURS MAX VITESSE PRESSION = NOMBRE DE PAS DE TEMPS CALCULES
      MCN(MNMXVP+WBVECT) = NBPAS
C     NOMBRE DE TEMPS A LA FIN DES VECTEURS
      MCN(MNMXVP+WBCPIN) = NBPAS
C     LE STOCKAGE DU TEMPS POUR LE TMS VECTEUR"MAXVITESSEPRESS
      MN = MNMXVP + WECTEU + MOREE2 * NBMXVP * NBPAS
      CALL TRTATA( RMCN(MNTIMXVP), RMCN(MN), NBPAS )
C
C     LA DATE DU TMS VECTEUR"MAXVITESSEPRESS
      CALL ECDATE( MCN(MNMXVP) )
C
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNMXVP + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
      MOTSVP1 = WECTEU + NBMXVP * NBPAS * MOREE2 + NBPAS
      IF( MOTSVP1 .LT. MOTSVP ) CALL TAMSRA( NTMXVP, MOTSVP1 )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     LA DATE
      CALL ECDATE( MCN(MNVECT) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVECT + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
C     FLUX DE LA VITESSE FINALE A TRAVERS LES FACES DES SURFACES DE L'OBJET
C     ---------------------------------------------------------------------
      MNFLUI = MNVECT + WECTEU + MOREE2 * NTDLVP *(NBFLUI-1)
      CALL FLUVITSF( MNXYZN, MNELE, MCN(MNNDDL), MCN(MNFLUI),
     %               NUMIOB(3), NUMAOB(3),
     %               FLUNEG, FLUPOS, MCN(MNFVSF) )
C
C     EXTRACTION DES PRESSIONS AUX NOEUDS DU MAILLAGE
C     --------------------------------------------------------------------
C     RECHERCHE DU TABLEAU DEFINITION DE L'OBJET
      CALL LXTSOU( NTLXOB, 'DEFINITION', NTDFOB, MNDFOB )
C     INTERPOLATION de la PRESSION = P1 POUR BREZZI-FORTIN
C                                  = P2 POUR TAYLOR-YOUNG
C     INTERPP et NBNOPR
      INTERPP = 2
      NBNOPR  = NBNOVI
C
C     ADRESSE MCN des NBFLUI VECTEUR PRESSIONS AUX SOMMETS DU MAILLAGE
      CALL TNMCDC( 'REEL2', NBFLUI*NBNOPR, MNPRES )
      IF( MNPRES .EQ. 0 ) GOTO 9990
C
C     EXTRACTION DES PRESSIONS AUX NOEUDS DU MAILLAGE
      CALL VECPRES( NDIM,   NUTYEL, NBELEM, NBNOEF, MCN(MNELE+WUNDEL),
     %              NBNOVI, MCN(MNNDDL), NTDLVP, NBFLUI, MCN(MNFLUI),
     %              NBNOPR, MCN(MNPRES) )
C
C     CALCUL DE L'INTEGRALE DE LA PRESSION d'INTERPOLATION P1 SUR TOUTES
C     LES SURFACES DE L'OBJET POUR TOUS LES VECTEURS STOCKES 1 A NBFLUI
C     et AUSSI CALCUL DU COUPLE EXERCE TOUTES LES SURFACES
C     ------------------------------------------------------------------
      WRITE(IMPRIM,*)
      WRITE(IMPRIM,*)'PRESSURE INTEGRAL OVER ALL OBJECT SURFACES:'
      WRITE(IMPRIM,19991)
      IF( LANGAG .EQ. 0 ) THEN
         NMSOLU = 'PRESSION '
      ELSE
         NMSOLU = 'PRESSURE '
      ENDIF
C     A METTRE A JOUR.....
      NCAS0 = 1
      NCAS1 = 1
      CALL INSOSF( 0,     INTERPP, NTLXOB, MNDFOB,
     %             NCAS0, NCAS1, MCN(MNPRES), NMSOLU,
     %             RMCN(MNTIME+1)  )
C
      CALL TNMCDS( 'REEL2', NBFLUI*NBNOPR, MNPRES )
C
      GOTO 9999
C
C
C     PLACE MEMOIRE INSUFFISANTE
C     **************************
 9990 NBLGRC(NRERR) = 2
      IF( LANGAG .EQ. 0 ) THEN
         KERR(1) = 'ERREUR: PLACE MEMOIRE INSUFFISANTE'
         KERR(2) = 'REDUIRE LE MAILLAGE'
      ELSE
         KERR(1) = 'ERROR: NOT ENOUGH LARGE MEMORY'
         KERR(2) = 'REDUCE the MESH'
      ENDIF
      CALL LEREUR
      IERR = 20
C
C     DESTRUCTION DES TMC DEVENUS INUTILES
C     ====================================
C     FREE MEMORY USED BY ARRAYS PG VG
 9999 IF( IERVGALLOC .EQ. 0 ) DEALLOCATE( VG )
      IF( IERPGALLOC .EQ. 0 ) DEALLOCATE( PG )
      IF( MNDP2DP2 .GT. 0 ) CALL TNMCDS( 'REEL2', 3*10*3*10, MNDP2DP2)
      IF( MNP2DP2  .GT. 0 ) CALL TNMCDS( 'REEL2', 10*3*10,   MNP2DP2 )
      IF( MNPTDV   .GT. 0 ) CALL TNMCDS( 'ENTIER', NBNOVI+1, MNPTDV  )
      IF( MNV3P2   .GT. 0 ) CALL TNMCDS( 'REEL2',  NTDLVI,   MNV3P2  )
      IF( MNV3P00  .GT. 0 ) CALL TNMCDS( 'REEL2',  NBDV3P0,  MNV3P00 )
      IF( NBPRFX   .GT. 0 ) CALL TNMCDS( 'ENTIER', NBPRFX,   MNDLPRFX)
      IF( NBPRFX   .GT. 0 ) CALL TNMCDS( 'REEL2',  NBPRFX,   MNVAPRFX)
      IF( NBVIFX   .GT. 0 ) CALL TNMCDS( 'ENTIER', NBVIFX,   MNDLVIFX)
      IF( NBVIFX   .GT. 0 ) CALL TNMCDS( 'REEL2',  NBVIFX,   MNVAVIFX)
      IF( MNNDLFX  .GT. 0 ) CALL TNMCDS( 'ENTIER', NBDLFX,   MNNDLFX )
      IF( MNVDLFX  .GT. 0 ) CALL TNMCDS( 'REEL2',  NBDLFX,   MNVDLFX )
      IF( MNFVSF   .GT. 0 ) CALL TNMCDS( 'REEL2',  MOSFOB,   MNFVSF  )
      IF( MNNDPFX  .GT. 0 ) CALL TNMCDS( 'ENTIER', NBSOM,    MNNDPFX )
      IF( MNNDVFX  .GT. 0 ) CALL TNMCDS( 'ENTIER', NBNOVI,   MNNDVFX )
      IF( MNSONO   .GT. 0 ) CALL TNMCDS( 'ENTIER', NBSOM,    MNSONO  )
      IF( MNNOSO   .GT. 0 ) CALL TNMCDS( 'ENTIER', NBNOVI,   MNNOSO  )
      IF( MNPTDP   .GT. 0 ) CALL TNMCDS( 'ENTIER', 1+NBSOM,  MNPTDP  )
C
      DMOTSTO = 901.D0+NBNOVI*2+NBPRFX+NBVIFX+NBDLFX+NBSOM*3
     %        + MOREE2*( NBNOVI+NTDLVI+NTDLVP*3
     %                  +NBPRFX+NBVIFX+NBDLFX+ MOSFOB+NBCMVG+NBCMPG )
     %        + NBFLUI + MOREE2 *NTDLVP*NBFLUI
C
      IF( NORESO .GE. 2 ) THEN
C        GRADIENT CONJUGUE STOCKAGE MORSE
C        DESTRUCTION DES TABLEAUX AUXILIAIRES
         IF( MNAUX1 .GT. 0 ) CALL TNMCDS( 'REEL2',  LOAUX,   MNAUX1 )
         IF( MNBDIR .GT. 0 ) CALL TNMCDS( 'REEL2',  LODIR,   MNBDIR )
         IF( MNLPCV .GT. 0 ) CALL TNMCDS( 'ENTIER', NBCMVG,  MNLPCV )
         IF( MNLPLC .GT. 0 ) CALL TNMCDS( 'ENTIER', NBNOVI+1,MNLPLC )
         IF( MNLPCC .GT. 0 ) CALL TNMCDS( 'ENTIER', LOLPCC,  MNLPCC )
         IF( MNPGC  .GT. 0 ) CALL TNMCDS( 'REEL2',  LOLPCC,  MNPGC  )
         IF( MNLPCP .GT. 0 ) CALL TNMCDS( 'ENTIER', NBCMPG,  MNLPCP )
         DMOTSTO = DMOTSTO + NBNOVI+1+LOLPCC+NBCMPG+NBCMVG
     %           + MOREE2*(LOAUX+LODIR+LOLPCC)
      ENDIF
C
C     BILAN SUR LA PLACE MEMOIRE CENTRALE OCCUPEE
C     ===========================================
      IF( NORESO .EQ. 1 ) THEN
C
C        FACTORISATION COMPLETE CHOLESKY STOCKAGE PROFIL
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,19002) DMOTSTO
         ELSE
            WRITE(IMPRIM,29002) DMOTSTO
         ENDIF
19002 FORMAT(/'STOCKAGE PROFIL des MATRICES et VECTEURS=',G25.17,
     %' MOTS MEMOIRE'/)
29002 FORMAT(/'SKYLINE STORAGE of MATRICES and VECTORS=', G25.17,
     %' MEMORY WORDS'/)
C
      ELSE IF( NORESO .GE. 3 ) THEN
C
C        GRADIENT CONJUGUE PRECONDITIONNE PAR CROUT INCOMPLET STOCKAGE MORSE
         MOTPRE  = 1 + NBNOVI + LOLPCC * (1+MOREE2)
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,19004) DMOTSTO, DBLE(MOTPRE), DBLE(MOTSGC),
     %                          DMOTSTO+MOTPRE+MOTSGC
         ELSE
            WRITE(IMPRIM,29004) DMOTSTO, DBLE(MOTPRE), DBLE(MOTSGC),
     %                          DMOTSTO+MOTPRE+MOTSGC
         ENDIF
19004    FORMAT(/' MATRICES MORSE GC ',         T30,G25.17,' MOTS'/
     %           ' MATRICE PRECONDITIONNEMENT', T30,G25.17,' MOTS'/
     %           ' TABLEAUX SUPPLEMENTAIRES GC',T30,G25.17,' MOTS'/
     %           ' AU TOTAL LE GC DEMANDE',     T30,G25.17,' MOTS'/)
C
29004    FORMAT(/' CG CONDENSED MATRICES',      T30,G25.17,' WORDS'/
     %           ' PRECONDITIONED MATRIX',      T30,G25.17,' WORDS'/
     %           ' AUXILIARY ARRAYS',           T30,G25.17,' WORDS'/
     %           ' TOTAL for the CG',           T30,G25.17,' WORDS'/)
      ENDIF
C
C     TOTAL DES MOTS NECESSAIRES A LA RESOLUTION
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,19005) DMOTSTO
      ELSE
         WRITE(IMPRIM,29005) DMOTSTO
      ENDIF
19005 FORMAT(/'STOCKAGE TOTAL des MATRICES et VECTEURS=',G25.17,
     %' MOTS MEMOIRE'/)
29005 FORMAT(/'TOTAL STORAGE of MATRICES and VECTORS=', G25.17,
     %' MEMORY WORDS'/)
C
cccC     RESTAURATION DE EPZERO INITIAL
cccC     ------------------------------
ccc      EPZERO = EPZ
C
C     COUT CALCUL DES VITESSES PRESSIONS
C     ==================================
      DVITPR = DINFO( 'DELTA CPU' )
C
      RETURN
      END
