      SUBROUTINE GAS2P1BP1( NBSOM, NUEF, BE, NBNOVI, BG )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ASSEMBLAGE DES DEGRES DE LIBERTE VITESSE 4 et 8 DANS BG
C -----    (VITESSE1 et 2 au BARYCENTRE de l'EF)
C          INTERNES ATTACHES AU TRIANGLE BREZZI-FORTIN
C          COMPRESSION DU SECOND MEMBRE ELEMENTAIRE BE
C
C ENTREES:
C --------
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION
C NUEF   : NUMERO DE L'EF BREZZI-FORTIN A TRAITER
C
C MODIFIE:
C --------
C BE     : EN ENTREE SECOND MEMBRE ELEMENTAIRE (8 D.L.)
C          EN SORTIE SECOND MEMBRE ELEMENTAIRE (6 D.L.) REDUIT
C BG     : VECTEUR GLOBAL SECOND MEMBRE APRES ASSEMBLAGE DES DL BARYCENTRES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC Saint Pierre du Perray Decembre 2008
C23456---------------------------------------------------------------012
      DOUBLE PRECISION  BE(8), BG(NBNOVI,2)
C
C     LE DEGRE DE LIBERTE 4 DE BE ELIMINE ENSUITE PAR GAUSS SUR [AG]
C     EST ASSEMBLE DANS BG POUR CHACUNE DES 2 COMPOSANTES
      N = NBSOM + NUEF
      BG( N, 1 ) = BG( N, 1 ) + BE(4)
C
C     LE DEGRE DE LIBERTE 8 DE BE ELIMINE ENSUITE PAR GAUSS SUR [AG]
C     EST ASSEMBLE DANS BG
      BG( N, 2 ) = BG( N, 2 ) + BE(8)
C
C     RECONSTRUCTION DANS BE AVEC SEULEMENT 6 DEGRES DE LIBERTE FINAUX
C     BE(4) EST ECRASE PAR BE(5), BE(5) PAR BE(6), BE(6) PAR BE(7)
C     REDUCTION DES DL VITESSE 4 8
      BE(4) = BE(5)
      BE(5) = BE(6)
      BE(6) = BE(7)
C
      RETURN
      END
