      SUBROUTINE GAS3P1BP1( NBSOM, NUEF, BE, NBNOVI, BG )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ASSEMBLAGE DES DEGRES DE LIBERTE VITESSE 5 10 15 DANS BG
C -----    (VITESSE1 2 3 au BARYCENTRE de l'EF)
C          INTERNES ATTACHES AU TETRAEDRE BREZZI-FORTIN
C          COMPRESSION DU SECOND MEMBRE ELEMENTAIRE BE
C
C ENTREES:
C --------
C NBSOM  : NOMBRE DE SOMMETS DE LA TETRAEDRISATION
C NUEF   : NUMERO DE L'EF BREZZI-FORTIN A TRAITER
C
C MODIFIE:
C --------
C BE     : EN ENTREE SECOND MEMBRE ELEMENTAIRE (15 D.L.)
C          EN SORTIE SECOND MEMBRE ELEMENTAIRE (12 D.L.) REDUIT
C BG     : VECTEUR GLOBAL SECOND MEMBRE APRES ASSEMBLAGE DES DL BARYCENTRES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC Saint Pierre du Perray Decembre 2010
C23456---------------------------------------------------------------012
      DOUBLE PRECISION  BE(15), BG(NBNOVI,3)
C
C     LE DEGRE DE LIBERTE 5 DE BE ELIMINE ENSUITE PAR GAUSS SUR [AG]
C     EST ASSEMBLE DANS BG POUR CHACUNE DES 3 COMPOSANTES
      N = NBSOM + NUEF
      BG( N, 1 ) = BG( N, 1 ) + BE(5)
C
C     LE DEGRE DE LIBERTE 10 DE BE ELIMINE ENSUITE PAR GAUSS SUR [AG]
C     EST ASSEMBLE DANS BG
      BG( N, 2 ) = BG( N, 2 ) + BE(10)
C
C     LE DEGRE DE LIBERTE 15 DE BE ELIMINE ENSUITE PAR GAUSS SUR [AG]
C     EST ASSEMBLE DANS BG
      BG( N, 3 ) = BG( N, 3 ) + BE(15)
C
C     RECONSTRUCTION DE BE AVEC SEULEMENT 12 DEGRES DE LIBERTE
C     REDUCTION DU DL VITESSE 5
      BE(5) = BE(6)
      BE(6) = BE(7)
      BE(7) = BE(8)
      BE(8) = BE(9)
C
C     REDUCTION DU DL VITESSE 10
      BE( 9) = BE(11)
      BE(10) = BE(12)
      BE(11) = BE(13)
      BE(12) = BE(14)
C
      RETURN
      END
