      SUBROUTINE GP3P1BP1( NTDL, NUELEM, NONOEF, AE, U, V )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DU VECTEUR V PRODUIT MATRICE AE PAR LE VECTEUR U
C -----    POUR LES DL BARYCENTRES DES TETRAEDRES BREZZI-FORTIN
C
C ENTREES:
C --------
C NTDL   : NOMBRE DE DEGRES DE LIBERTE SANS LES BARYCENTRES DES EF
C NUELEM : NUMERO DU TETRAEDRE BREZZI-FORTIN A TRAITER
C NONOEF : NO DES NOEUDS DU TETRAEDRE C'EST A DIRE DES 4 SOMMETS
C AE     : LES 3 LIGNES DE AE DES DEGRES DE LIBERTE 5 10 15 DU BARYCENTRE
C U      : VECTEUR A MULTIPLIER PAR AE
C
C SORTIE :
C --------
C V      : VECTEUR PRODUIT DE AE * U
C          EN FAIT, SEULEMENT LES 3 COMPOSANTES ASSOCIEES AU BARYCENTRE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC Saint Pierre du Perray  Janvier 2009
C23456---------------------------------------------------------------012
      DOUBLE PRECISION  AE(19,3), U(*), V(*), S
      INTEGER           NONOEF(5), NOGLDL(19)
C
C     NO GLOBAL DES DL DE L'ELEMENT FINI BREZZI-FORTIN
      CALL NODLEFBF( 3, NTDL, NUELEM, NONOEF, NOGLDL )
C
C     NUMERO DU DERNIER DL AVANT CEUX DU BARYCENTRE
      NBADL = NTDL + 3*NUELEM - 3
C
C     PRODUIT D'UNE LIGNE 5 10 15 PAR LE VECTEUR U
      DO 30 K=1,3
C
C        PRODUIT DE LA LIGNE DU DL BARYCENTRE PAR LE VECTEUR U
         S = 0D0
         DO 10 I=1,19
            S = S + AE(I,K) * U( NOGLDL(I) )
 10      CONTINUE
         V( NBADL + K ) = S
C
C        BLOC AU DESSUS DE LA DIAGONALE OBTENU PAR TRANSPOSITION
         S = U( NBADL + K )
         DO 20 I=1,19
            IF( I .NE. 5 .AND. I .NE. 10 .AND. I .NE. 15  ) THEN
               NP = NOGLDL( I )
               V(NP) = V(NP) + AE(I,K) * S
            ENDIF
 20      CONTINUE
C
 30   CONTINUE
C
      RETURN
      END
