      SUBROUTINE GV3EP1BP1( AE, AS, AGAUSS )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ELIMINATION PAR GAUSS DES DEGRES DE LIBERTE VITESSE 5 10 15
C -----    (VITESSE1 2 3 en moyenne sur e)
C          INTERNES ATTACHES AU TETRAEDRE BREZZI-FORTIN
C
C MODIFIES:
C --------
C AE     : MATRICE DE VISCOSITE (19,19) STOCKEE PLEINE
C
C SORTIES:
C --------
C AS     : MATRICE DE VISCOSITE (16,16) STOCKEE PLEINE
C AGAUSS : LES 3 LIGNES DE AE DES DEGRES DE LIBERTE ELIMINES
C          POUR LES CALCULER APRES RESOLUTION
C
C REMARQUE : A L'APPEL AE et AS PEUVENT AVOIR MEME ADRESSE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC Saint Pierre du Perray   Avril 2010
C23456---------------------------------------------------------------012
      IMPLICIT NONE
      DOUBLE PRECISION AE(19,19), AS(16,16), AGAUSS(19,3)
      DOUBLE PRECISION PIVOT, S
      INTEGER          I, I4, J, J4
C
C     LA LIGNE DE A DU DL 5 ELIMINE PAR GAUSS
C     POUR PERMETTRE LE CALCUL DES VITESSES MOYENNES APRES RESOLUTION
      DO 50 J=1,19
         AGAUSS(J,1) = AE(5,J)
 50   CONTINUE
C
C     TRIANGULATION DE GAUSS SUR LA LIGNE 5
      PIVOT = AE(5,5)
      DO 55 I=1,19
         IF( I .NE. 5 ) THEN
            S = AE(I,5) / PIVOT
            DO 52 J=1,19
ccc               IF( J .NE. 5 ) THEN
               AE(I,J) = AE(I,J) - S * AE(5,J)
ccc               ENDIF
 52         CONTINUE
         ENDIF
 55   CONTINUE
C
C     LA LIGNE DE A DU DL 10 ELIMINE PAR GAUSS
C     POUR PERMETTRE LE CALCUL DES VITESSES MOYENNES APRES RESOLUTION
      DO 100 J=1,19
         AGAUSS(J,2) = AE(10,J)
 100  CONTINUE
C     EN FAIT AE(10,5)=0 SUITE A GAUSS MAIS VALEUR EXACTE IMPOSEE
      AGAUSS(5,2) = 0D0
C
C     TRIANGULATION DE GAUSS SUR LA LIGNE 10
      PIVOT = AE(10,10)
      DO 105 I=1,19
         IF( I .NE. 5 .AND. I .NE. 10 ) THEN
            S = AE(I,10) / PIVOT
            DO 102 J=1,19
ccc               IF( J .NE. 5 .AND. J .NE. 10 ) THEN
               AE(I,J) = AE(I,J) - S * AE(10,J)
ccc               ENDIF
 102        CONTINUE
         ENDIF
 105  CONTINUE
C
C     LA LIGNE DE A DU DL 15 ELIMINE PAR GAUSS
C     POUR PERMETTRE LE CALCUL DES VITESSES MOYENNES APRES RESOLUTION
      DO 150 J=1,19
         AGAUSS(J,3) = AE(15,J)
 150  CONTINUE
C     EN FAIT AE(15,5)=0  SUITE A GAUSS MAIS VALEUR EXACTE IMPOSEE
      AGAUSS(5,3) = 0D0
C     EN FAIT AE(15,10)=0 SUITE A GAUSS MAIS VALEUR EXACTE IMPOSEE
      AGAUSS(10,3) = 0D0
C
C     TRIANGULATION DE GAUSS SUR LA LIGNE 15
      PIVOT = AE(15,15)
      DO 155 I=1,19
         IF( I .NE. 5 .AND. I .NE. 10 .AND. I .NE. 15 ) THEN
            S = AE(I,15) / PIVOT
            DO 152 J=1,19
ccc               IF( J .NE. 5 .AND. J .NE. 10 .AND. J .NE. 15 ) THEN
               AE(I,J) = AE(I,J) - S * AE(15,J)
ccc               ENDIF
 152        CONTINUE
         ENDIF
 155   CONTINUE
C
C     RECONSTRUCTION DANS AS(16,16) AVEC SEULEMENT 16 DEGRES DE LIBERTE
C     REDUCTION DES DL VITESSE 5 10 15
      J4 = 0
      DO 200 J = 1, 16
         I4 = 0
         DO 190 I = 1, 16
            AS(I,J) = AE(I+I4,J+J4)
            I4 = I / 4
 190     CONTINUE
         J4 = J / 4
 200  CONTINUE
C
      RETURN
      END
