      SUBROUTINE NMFIVIPRTE( KNOMOB, TEMPS, NOVVIPR,  KNOMFIC, NBK )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CONSTRUIRE LE NOM KNOMFIC DE FICHIER DU VECTEUR VITESSE+PRESSION
C ----- DE NUMERO NOVVVIPR A L'INSTANT TEMPS

C ENTREES:
C --------
C KNOMOB  : NOM DE L'OBJET DANS LE LEXIQUE des OBJETS
C TEMPS   : TEMPS  DU VECTEUR VITESSE_XYZ+PRESSION A STOCKER
C NOVVIPR : NUMERO DU VECTEUR VITESSE_XYZ+PRESSION DANS LE REPERTOIRE
C           DU PROJET

C SORTIE  :
C ---------
C KNOMFIC : NOM DU FICHIER SUPPORT DU VECTEUR VITESSE+PRESSION
C NBK     : NOMBRE DE CARACTERES NON BLANCS DE KNOMFIC
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  Saint Pierre du Perray             Aout 2020
C MODIFS : ALAIN PERRONNET  Saint Pierre du Perray            Avril 2022
C23456---------------------------------------------------------------012
      CHARACTER*(*) KNOMOB
      REAL          TEMPS
      INTEGER       NOVVIPR
      CHARACTER*(*) KNOMFIC

      NBCKNOM = NUDCNB( KNOMOB )
      KNOMFIC = KNOMOB(1:NBCKNOM)//'_VitPrTe_N=     _T=                '

      WRITE( KNOMFIC(NBCKNOM+12:NBCKNOM+16), '(I5)'    ) 10000 + NOVVIPR
      KNOMFIC(NBCKNOM+12:NBCKNOM+12) = '0'
      WRITE( KNOMFIC(NBCKNOM+20:NBCKNOM+34), '(E15.7)' ) TEMPS

C     SUPPRESSION DES CARACTERES BLANCS et CARACTERES BLANCS AU DELA
      CALL SANSBL( KNOMFIC, NBK )

C     COMPLETION PAR DES BLANCS AU DELA DE NBK EST DEJA FAITE
ccc      PRINT*,'nmfivipr: KNOMFIC= ',KNOMFIC(1:NBK)

      RETURN
      END
