      SUBROUTINE PRESFXBG( NBRDLX, NDLX, PREFIX, NBSOM,  BG )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    PRISE EN COMPTE SUR LE VECTEUR GLOBAL DES NDIM COMPOSANTES
C -----    DE LA PRESSION DES DL FIXES
C
C ENTREES:
C --------
C NBRDLX : NOMBRE DE DL PRESSION FIXES
C          ERREUR SI NBRDLX=0 CAR PAS DE CONDITION AUX LIMITES!
C NDLX   : TABLEAU MC DES NUMEROS DES DL FIXES
C PREFIX : TABLEAU MC DES VALEURS DES PRESSIONS FIXEES
C
C NBSOM  : NOMBRE DE SOMMETS SUPPORT DE LA PRESSION
C
C MODIFIE:
C --------
C BG     : VALEUR DES COEFFICIENTS DU VECTEUR GLOBAL PRESSION
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2010
C23456---------------------------------------------------------------012
      INTEGER           NDLX(NBRDLX)
      DOUBLE PRECISION  PREFIX(NBRDLX), BG(NBSOM)
C
      DO K=1,NBRDLX
C
C        NUMERO DU DL FIXE DE 1 A NBSOM
         NDL = NDLX( K )
C
C        VALEUR FIXEE DE LA PRESSION
         BG( NDL ) =  PREFIX(K)
C
      ENDDO
C
      RETURN
      END
