      SUBROUTINE PTDLFLUI( NDIM,   NBSOM, NBNOVI, NBELEM, MNELE, NUTYEL, 
     %                     NDDLNO, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     GENERER LE POINTEUR SUR LE DERNIER DEGRE DE LIBERTE
C -----     DE CHAQUE NOEUD DU MAILLAGE D'UN FLUIDE

C ENTREES :
C ---------
C NDIM    : DIMENSION DE L'ESPACE DU FLUIDE
C NBSOM   : NOMBRE DE SOMMETS DU MAILLAGE
C NBNOVI  : NOMBRE DE NOEUDS SUPPORT DE LA VITESSE
C           SI BREZZI-FORTIN : NOMBRE DE SOMMETS + BARYCENTRES
C           SI TAYLOR-YOUNG  : NOMBRE DE SOMMETS + MILIEUX DES ARETES
C NBELEM  : NOMBRE TOTAL D'ELEMENTS FINIS
C MNELE   : ADRESSE DU TABLEAU DES TYPES D'ELEMENTS FINIS
C NUTYEL  : NUMERO DU TYPE D'EF UTILISE
C           BREZZI FORTIN 13: TRIA 2P1D ou 19: TETR 3P1D
C           TAYLOR HOOD   15: TRIA 2P2D ou 20: TRIA 2P2C

C SORTIES :
C ---------
C NDDLNO  : TABLEAU DES POINTEURS SUR LE DERNIER DL DE CHAQUE NOEUD
C           NDDLNO(I)= NO DERNIER DL DU NOEUD
C                      (SOMMET ou MILIEU ou BARYCENTRE)
C           CE TABLEAU EST DIMENSIONNE A 1+NBNOVI  cf plus bas
C IERR    : 0 SI PAS D'ERREUR
C           1 SI UN TABLEAU 'NPEF"TYPE_EF' EST INCONNU
C           2 SI NOMBRE DE SOMMETS RETROUVES INCOHERENT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  Saint Pierre du Perray          Fevrier 2021
C23456---------------------------------------------------------------012
      INTEGER   NDDLNO(0:NBNOVI)
      INTEGER   NONOEF(27)

      IERR   = 0

C     DETERMINATION DE LA NATURE DES NOEUDS :
C     1 : SI VITESSE + PRESSION
C     2 : SI VITESSE SEULE

      DO NUELEM = 1, NBELEM

C        LES NOEUDS DE L'ELEMENT FINI NUELEM
         CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOEF )

C        LES SOMMETS SONT MARQUES PAR 1, LES AUTRES NOEUDS PAR 2
         DO I=1,NDIM+1
C           SOMMET
            NDDLNO( NONOEF(I) ) = 1
         ENDDO

         IF( NUTYEL .EQ. 13 .OR. NUTYEL .EQ. 19 ) THEN

C           BARYCENTRE DE L'EF NUELEM BREZZI-FORTIN
            NDDLNO( NBSOM + NUELEM ) = 2

         ELSE IF( NUTYEL .EQ. 15 .OR. NUTYEL .EQ. 20 ) THEN

C           MILIEU D'ARETE DU TRIANGLE ou DU TETRAEDRE TAYLOR HOOD
            DO I=NDIM+2,NBNOEF
               NDDLNO( NONOEF(I) ) = 2
            ENDDO

         ENDIF

      ENDDO

C     CONSTRUCTION DU TABLEAU NDDLNO(0:NBNOVI)
C     NO DU DERNIER DL DE CHAQUE NOEUD et
C     VERIFICATION DU NOMBRE DE SOMMETS DU MAILLAGE
      NBSOMF = 0
C     SOMMATION POUR POINTER SUR LE DERNIER DL DE CHAQUE NOEUD
      NDDLNO(0) = 0
      DO I = 1, NBNOVI
         IF( NDDLNO(I) .EQ. 1 ) THEN
C           SOMMET => NDIM + 1  DL: V1 V2 ... Vndim Pression
            NDDLNO(I) = NDDLNO(I-1) + NDIM + 1
C           NOMBRE DE SOMMETS DU MAILLAGE
            NBSOMF = NBSOMF + 1
         ELSE IF( NDDLNO(I) .EQ. 2 ) THEN
C           MILIEU D'UN COTE ou BARYCENTRE => NDIM DL: V1 V2 ... Vndim
            NDDLNO(I) = NDDLNO(I-1) + NDIM
         ELSE
            PRINT*,'ptdlflui: NDDLNO(',I,')=',NDDLNO(I),' => IERR=1'
            IERR = 1
         ENDIF
      ENDDO

      IF( NBSOM .NE. NBSOMF ) THEN
         PRINT*,'ptdlflui: NOMBRE de SOMMETS INITIAL NBSOM=',NBSOM,
     %          ' FINAL NBSOMF=',NBSOMF,' ???... A CORRIGER'
         IERR = 2
      ENDIF

      RETURN
      END
