      SUBROUTINE SPTP2P13D( DT,      XYZPOI, 
     %                      NUEF,    NBEF,    NUNOTE, NDDLNO,
     %                      VITMAX,  VXYZPN,
     %                      VMXNUEF, NBSSPATE, DDT )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE NOMBRE NBSSPATE DE SOUS PAS DE TEMPS DDT
C -----    DANS LE PAS DE TEMPS DT POUR LE TETRAEDRE NUEF TAYLOR-HOOD
C
C ENTREES:
C --------
C DT     : LE PAS CONSTANT DE TEMPS ENTRE tn ET tn+1
C XYZPOI : 3 COORDONNEES DES SOMMETS ET MILIEUX DES ARETES DES TETRAEDRES
C NUEF   : NUMERO DE L'EF A TRAITER
C NBEF   : NOMBRE DE TETRAEDRES DU MAILLAGE
C NUNOTE : NUMERO DES 4 SOMMETS ET 6 MILIEUX DES ARETES DES TETRAEDRES
C NDDLNO : TABLEAU DES POINTEURS SUR LE DERNIER DL DE CHAQUE NOEUD FLUIDE
C          CE TABLEAU EST DIMENSIONNE A 1+NBNOEU DU MAILLAGE
C VITMAX : NORME DE LA VITESSE MAXIMALE GLOBALE SUR LE MAILLAGE
C VXYZPN : VECTEUR GLOBAL des DL VITESSES-PRESSIONS (1:NTDL) au TEMPS tn
C
C SORTIES :
C ---------
C VMXNUEF : LA VITESSE MAXIMALE EN L'UN DES 10 NOEUDS DU TETRAEDRE NUEF
C NBSSPATE: LE NOMBRE NBSSPATE DE SOUS PAS DE TEMPS DDT
C DDT     : LA VALEUR DU SOUS PAS DE TEMPS DANS LE PAS DE TEMPS DT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St Pierre du Perray     AOUT 2012
C23456---------------------------------------------------------------012
      IMPLICIT  NONE
      REAL               DT, XYZPOI(3,*)
      DOUBLE PRECISION   VXYZPN(1:*), VITMAX, VMXNUEF,
     %                   S, ARETMX, DDT
      INTEGER            NUEF, NBEF, NUNOTE(NBEF,10), NDDLNO(0:*),
     %                   NBSSPATE, NDL, I, NS1, NS2
C
C     NO DES 2 SOMMETS DE CHAQUE ARETE DANS L'ORDRE DE 
      INTEGER            NOSOAR(2,6)
      DATA               NOSOAR / 1,2,  2,3,  3,1,  1,4,  2,4,  3,4 /
C
C     CALCUL DE LA LONGUEUR MAXIMALE DES 6 ARETES DU TETRAEDRE
      ARETMX = 0D0
      DO I=1,6
         NS1 = NUNOTE( NUEF, NOSOAR(1,I) )
         NS2 = NUNOTE( NUEF, NOSOAR(2,I) )
         S = ( XYZPOI(1,NS2) - XYZPOI(1,NS1) ) ** 2
     %     + ( XYZPOI(2,NS2) - XYZPOI(2,NS1) ) ** 2
     %     + ( XYZPOI(3,NS2) - XYZPOI(3,NS1) ) ** 2
         IF( S .GT. ARETMX ) ARETMX = S
      ENDDO
      ARETMX = SQRT( ARETMX )
C
C     VITESSE MAXIMALE AUX 10 NOEUDS DU TETRAEDRE NUEF
      VMXNUEF = 0D0
      DO I=1,10
C        NUMERO DU NOEUD I DU TETRAEDRE NUEF
         NS1 = NUNOTE(NUEF,I)
C        NO DU DL I DANS L'EF NUEF DE LA VITESSE
         NDL = NDDLNO( NS1 - 1 )
C        CARRE DE LA VITESSE AU NOEUD I
         S = VXYZPN(NDL+1)**2 + VXYZPN(NDL+2)**2 + VXYZPN(NDL+3)**2
         IF( S .GT. VMXNUEF ) VMXNUEF = S
      ENDDO
      VMXNUEF = SQRT( VMXNUEF )
C
      IF( VMXNUEF .LE. VITMAX*1D-3 ) THEN
C        VITESSE TROP FAIBLE . SOUS PAS NUL d'INTEGRATION en TEMPS
         NBSSPATE = 0
         DDT      = 0D0
         GOTO 9999
      ENDIF
C
C     LE NOMBRE NBSSPATE DE SOUS PAS DE TEMPS DANS LE PAS DE TEMPS DT
C     16 SOUS PAS DE TEMPS SI L'EF EST A LA VITESSE MAXIMALE GLOBALE
      NBSSPATE = NINT( 16 * VMXNUEF / VITMAX )
C
C     16 SOUS PAS DE TEMPS POUR PARCOURIR L'ARETE MAXIMALE A
C     LA VITESSE VMXNUEF DURANT LE TEMPS DT
      NBSSPATE = MAX( NBSSPATE, NINT( 16 * VMXNUEF * DT / ARETMX ) )
C
C     ECRETAGE DU NOMBRE DE SOUS PAS DE TEMPS DDT DANS LE PAS DE TEMPS DT
      NBSSPATE = MAX( NBSSPATE,  6 )
      NBSSPATE = MIN( NBSSPATE, 16 )
C
C     SOUS PAS DE TEMPS ENTRE T-DT et T
      DDT = DT / NBSSPATE
C
 9999 RETURN
      END
