      SUBROUTINE TMSL2VP( KNOMOB, NTVEL2, MNVEL2,
     %                    NTVIEX, MNVIEX, NTPREX, MNPREX, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CONSTRUIRE LE TMS 'VECTEUR"L2VITESSEPRESS'
C -----    ET SI VITESSE_EXACTE(t,x,y,z,nc) EXISTE
C                CONSTRUIRE LE TMS 'VECTEUR"VITESSEEXACTE'
C          ET SI PRESSION_EXACTE(t,x,y,z) EXISTE
C                CONSTRUIRE LE TMS 'VECTEUR"PRESSIONEXACTE'
C
C ENTREE :
C --------
C KNOMOB : NOM DE L'OBJET A TRAITER
C
C SORTIES:
C --------
C NTVEL2 : NUMERO       DU TMS 'VECTEUR"L2VITESSEPRESS'
C MNVEL2 : ADRESSE MCN  DU TMS 'VECTEUR"L2VITESSEPRESS'
C NTVIEX : NUMERO       DU TMS 'VECTEUR"VITESSEEXACTE'
C MNVIEX : ADRESSE MCN  DU TMS 'VECTEUR"VITESSEEXACTE'
C NTPREX : NUMERO       DU TMS 'VECTEUR"PRESSIONEXACTE'
C MNPREX : ADRESSE MCN  DU TMS 'VECTEUR"PRESSIONEXACTE'
C IERR   : =0 SI PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET TEXAS A & M UNIVERSITY at QATAR   Fevrier 2012
C23456---------------------------------------------------------------012
      PARAMETER      (MXTYEL=7)
      include"./incl/ntmnlt.inc"
      include"./incl/langue.inc"
      include"./incl/donflu.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___vecteur.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/ponoel.inc"
      include"./incl/gsmenu.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      INTEGER           NUMIOB(4),NUMAOB(4),MNDOEL(4),MXDOEL(4)
      LOGICAL           AVANT
      CHARACTER*(*)     KNOMOB
      CHARACTER*4       NOMELE(2)
      DOUBLE PRECISION  VOLUME
      INTRINSIC         REAL
C
      IERR   = 0
C     LE NOMBRE DE MOTS D'UNE VARIABLE REEL2
      MOREE2 = MOTVAR(6)
      NTVEL2 = 0
      MNVEL2 = 0
      NTVIEX = 0
      MNVIEX = 0
      NTPREX = 0
      MNPREX = 0
      MNX    = 0
      MNPREEXA = 0
      MNVITEXA = 0
C
C     RECHERCHE DU NOM DE L'OBJET DANS LE LEXIQUE DES OBJETS
      CALL LXLXOU( NTOBJE, KNOMOB, NTLXOB, MNLXOB )
C     S'IL N'EXISTE PAS RETOUR A LA DEMANDE DU NOM DE L'OBJET
      IF( NTLXOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OBJET INCONNU ' // KNOMOB
         ELSE
            KERR(1) = 'ERROR: UNKNOWN OBJECT ' // KNOMOB
         ENDIF
         CALL LEREUR
         CALL LXIM( NTOBJE )
         IERR = 1
         RETURN
      ENDIF
C
C     RECHERCHE DU TMS  VECTEUR"VITESSEPRESSION DE L'OBJET
      CALL LXTSOU( NTLXOB, 'VECTEUR"VITESSEPRESSION', NTVECT, MNVECT )
C     LES DL SONT PAR NOEUDS: VX,VY,VZ, evt PRESSION (aux sommets seulement)
C     ET TEMPS APRES TEMPS
      IF( NTVECT .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OBJET ' // KNOMOB
            KERR(2) = 'VITESSE PRESSION NON CALCULEES'
         ELSE
            KERR(1) = 'ERROR: OBJECT ' // KNOMOB
            KERR(2) = 'VELOCITY PRESSURE NOT COMPUTED'
         ENDIF
         CALL LEREUR
         IERR = 3
         GOTO 9999
      ENDIF
C
C     LES NORMES L2 DES NBVECT PRESSION, |VITESSE|, VOLUME SONT ELLES
C     DEJA CALCULEES A PARTIR DU TMS  VECTEUR"VITESSEPRESSION?
      CALL LXTSOU( NTLXOB, 'VECTEUR"L2VITESSEPRESS', NTVEL2, MNVEL2 )
      IF( NTVEL2 .GT. 0 ) THEN
         IF( AVANT( MCN(MNVECT), MCN(MNVEL2) ) ) THEN
C           L2VITESSES-PRESSIONS ANTERIEURES AUX VITESSES-PRESSIONS
C           SONT DEJA CALCULEES ET NE SONT PAS RECALCULEES
C
C           OUVERTURE DU TMS 'VECTEUR"VITESSEEXACTE'
            CALL LXTSOU( NTLXOB,'VECTEUR"VITESSEEXACTE', NTVIEX, MNVIEX)
C
C           OUVERTURE DU TMS 'VECTEUR"PRESSIONEXACTE'
            CALL LXTSOU( NTLXOB,'VECTEUR"PRESSIONEXACTE',NTPREX, MNPREX)
C
            GOTO 9999
C
         ENDIF
C        CE TABLEAU EST DETRUIT POUR ETRE RECALCULE CAR NON A JOUR
         CALL LXTSDS( NTLXOB, 'VECTEUR"L2VITESSEPRESS' )
      ENDIF
C
C     NOMBRE TOTAL DE VECTEURS VITESSEPRESSION
      NBVECT = MCN( MNVECT + WBVECT )
      IF( NBVECT .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: PAS DE VECTEUR"VITESSEPRESSION STOCKE'
         ELSE
            KERR(1) = 'ERROR: NO VECTEUR"VITESSEPRESSION STORED'
         ENDIF
         CALL LEREUR
         IERR = 1
         GOTO 9999
      ENDIF
C
C     NOMBRE DE DL D'UN VECTEUR de VECTEUR"VITESSEPRESSION
      NTDLVP = MCN( MNVECT + WBCOVE )
      IF( NTDLVP .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1)='ERREUR: NOMBRE COMPOSANTES INCORRECT D''1 VECTEUR'
         ELSE
            KERR(1)='ERROR: INCORRECT NUMBER OF COMPONENTS of A VECTOR'
         ENDIF
         CALL LEREUR
         IERR = 1
         GOTO 9999
      ENDIF
C
C     CONSTRUCTION DU TABLEAU LESTEMPS A L'ADRESSE MCN MNTIMES
C     NBVECT NOMBRE DE VECTEUR"VITESSEPRESSION STOCKES
      CALL LESTEMPS( KNOMOB, MNVECT, NBVECT, MNTIMES, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     CALCUL DES CARACTERISTIQUES DU MAILLAGE ET DES EF FLUIDE
C     RECHERCHE DES TABLEAUX XYZSOMMET XYZNOEUD XYZPOINT NPEF"
C     ASSOCIES A L'OBJET
      CALL MIMAOB( 1,      NTLXOB, MXDOFL, NTTOPO, MNTOPO,
     %             NTXYZP, MNXYZP, NTXYZN, MNXYZN,
     %             MXTYEL, NBTYEL, MTNPEF, MNNPEF,
     %             NUMIOB, NUMAOB,
     %             NDPGST, NBOBIN, MNOBIN, NBOBCL, MNOBCL,
     %             MXDOEL, MNDOEL, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C     NTTOPO : NUMERO      DU TMS 'TOPOLOGIE' DE L'OBJET
C     MNTOPO : ADRESSE MCN DU TMS 'TOPOLOGIE' DE L'OBJET
C     NTXYZP : NUMERO      DU TMS 'XYZPOINT'  DE L'OBJET
C     MNXYZP : ADRESSE MCN DU TMS 'XYZPOINT'  DE L'OBJET
C     NTXYZN : NUMERO      DU TMS 'XYZNOEUD'  DE L'OBJET
C     MNXYZN : ADRESSE MCN DU TMS 'XYZNOEUD'  DE L'OBJET
C     NBTYEL : NOMBRE DE TYPES D'ELEMENTS FINIS DU MAILLAGE
C     NTELEM : NUMERO      DU TMS DES NBTYEL TYPES D'ELEMENTS FINIS
C     MNNPEF : ADRESSE MCN DU TMS DES NBTYEL TYPES D'ELEMENTS FINIS
C     NUMIOB : LES 4 NUMEROS MINIMA DES OBJETS
C     NUMAOB : LES 4 NUMEROS MAXIMA DES OBJETS
C     MNOBIN : ADRESSE MCN DU TMS DES OBJETS INTERNES
C     MNOBCL : ADRESSE MCN DU TMS DES OBJETS AUX LIMITES
C     MNDOEL : LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C              TABLEAUX DECRIVANT LE FLUIDE DE L'OBJET COMPLET
C
C     INITIALISATIONS DE VARIABLES ET AFFICHAGES
C     ==========================================
C     LES POINTS SONT IDENTIQUES AUX NOEUDS
      MNXYZP = MNXYZN
C
C     NOMBRE DE NOEUDS SUPPORT DE LA VITESSE DU MAILLAGE
      NBNOEU = MCN(MNXYZN+WNBNOE)
C
C     NDIM DIMENSION EFFECTIVE DE L'ESPACE DES COORDONNEES
      CALL DIMCOO( NBNOEU, MCN(MNXYZN+WYZNOE), NDIM )
      NDIMLI = NDIM
C
C     ICI UN SEUL TYPE D'EF DANS LE MAILLAGE
C     MNELE : ADRESSE DU TABLEAU NPEF"TYPE EF (P1D ou P2C)
      MNELE  = MCN( MNNPEF )
C
C     NOMBRE D'ELEMENTS FINIS DE CE TYPE
      NBELEM = MCN( MNELE + WBELEM )
C
C     LE NOMBRE DE NOEUDS DE L'ELEMENT FINI
      NBNOEF = MCN( MNELE + WBNDEL )
C
C     LE NUMERO DU SEUL TYPE DE L'ELEMENT FINI
C     (TRIA 2P1D ou TRIA 2P2C ou TETR 3P1D ou TETR 3P2C)
      NUTYEL = MCN( MNELE + WUTYEL )
C
C     NDPGST : CODE TRAITEMENT DES XYZ DES SOMMETS POINTS NOEUDS DU MAILLAGE
C              0 : NOEUDS=POINTS=SOMMETS
C              1 : NOEUDS=POINTS#SOMMETS
C              2 : NOEUDS#POINTS=SOMMETS
C              3 : NOEUDS#POINTS#SOMMETS
      NDPGST = MCN( MNTOPO + WDPGST )
C
C     LES CARACTERISTIQUES DE L'ELEMENT FINI
      CALL ELNUNM( NUTYEL, NOMELE )
C
C     LES CARACTERISTIQUES DE L'ELEMENT FINI
      CALL ELTYCA( NUTYEL )
C
      IF( NUTYEL .NE. 13 .AND. NUTYEL .NE. 19 .AND.
     %    NUTYEL .NE. 15 .AND. NUTYEL .NE. 20 ) THEN
          NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) ='ERREUR: ELEMENT FINI FLUIDE INCONNU ' // NOMELE(1)
     %             // NOMELE(2)
         ELSE
            KERR(1) ='ERROR: UNKNOWN FLUID FINITE ELEMENT ' // NOMELE(1)
     %             // NOMELE(2)
         ENDIF
         CALL LEREUR
         IERR = 4
         GOTO 9999
      ENDIF
C
      IF( NUTYEL .EQ. 13 .OR. NUTYEL .EQ. 19 ) THEN
C        EF BREZZI-FORTIN
C        NOMBRE DE SOMMETS DU MAILLAGE
         IF( NBNOEU .GT. NBELEM ) THEN
            NBSOMT = NBNOEU - NBELEM
         ELSE
            NBSOMT = NBNOEU
         ENDIF
C        NOMBRE DE NOEUDS=SOMMETS SUPPORT DE LA PRESSION
         NBNOPR = NBSOMT
C        NOMBRE DE NOEUDS SUPPORTANT LA VITESSE LES BARYCENTRES EN PLUS
         NBNOVI = NBSOMT + NBELEM
C        INTERPOLATION DE LA VITESSE EN P1+BULLE
         INTERPV = 3
C        INTERPOLATION P1 DE LA PRESSION
         INTERPP = 1
      ELSE IF( NUTYEL .EQ. 15 .OR. NUTYEL .EQ. 20 ) THEN
C        EF TAYLOR-HOOD
C        NOMBRE DE NOEUDS (SOMMETS et MILIEUX ARETES) SUPPORT DE LA PRESSION
C        LA PRESSION AU MILIEU D'UNE ARETE EST LA MOYENNE DE CELLES AUX EXTREMIT
         NBNOPR = NBNOEU
C        NOMBRE DE NOEUDS SUPPORTANT LA VITESSE
         NBNOVI = NBNOEU
C        INTERPOLATION P2 DE LA VITESSE
         INTERPV = 2
C        INTERPOLATION P1 DE LA PRESSION
         INTERPP = 1
      ENDIF
C
C     RECONSTRUCTION DU TABLEAU NDDLNO(0:NBNOEU)
C     POINTEUR SUR LE DERNIER DL DE CHAQUE NOEUD VITESSE DU FLUIDE
C     ------------------------------------------------------------
      MNNDDL = 0
      CALL TNMCDC( 'ENTIER', 1+NBNOVI, MNNDDL )
      CALL AZEROI( 1+NBNOVI, MCN(MNNDDL) )
      CALL PTDLFL( MNELE,  NDIM, NBELEM, NBNOEU, NUTYEL,
     %             NBSOMT, NBNOVI, MCN(MNNDDL), IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10210) NDIM, NBVECT, NTDLVP, NBNOVI, NBNOPR,
     %                       INTERPV, INTERPP
      ELSE
         WRITE(IMPRIM,20210) NDIM, NBVECT, NTDLVP, NBNOVI, NBNOPR,
     %                       INTERPV, INTERPP
      ENDIF
10210 FORMAT(/' DIMENSION 2 OU 3 DE L''ESPACE',T42,'=',I9/
     %        ' NOMBRE DE VECTEURS SOLUTIONS',T42,'=',I9/
     %        ' NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR',T42,'=',I9/
     %        ' NOMBRE DE NOEUDS SUPPORT DES VITESSES',T42,'=',I9/
     %        ' NOMBRE DE NOEUDS SUPPORT DES PRESSIONS',T42,'=',I9/
     %        ' NUMERO DU TYPE EF',T42,'=',I9/
     %        ' NUMERO D''INTERPOLATION DES VITESSES',T42,'=',I9/
     %        ' NUMERO D''INTERPOLATION DE LA PRESSION',T42,'=',I9/)
C
20210 FORMAT(/' SPACE DIMENSION (2 or 3)',T40,'=',I9/
     %        ' NUMBER of SOLUTION VECTORS',   T40,'=',I9/
     %        ' NUMBER of COMPONENTS of each VECTOR',T40,'=',I9/
     %        ' NUMBER of NODES SUPPORT of VELOCITY',T40,'=',I9/
     %        ' NUMBER of NODES SUPPORT of PRESSURE',T40,'=',I9/
     %        ' INTERPOLATION NUMBER of VELOCITIES',T40,'=',I9/
     %        ' INTERPOLATION NUMBER of P1 PRESSURE',T40,'=',I9/)
C
C     LE TABLEAU DES 3 COORDONNEES DES NBDLMX NOEUDS D'UN ELEMENT FINI
      CALL TNMCDC( 'REEL', NBNOE*3, MNX )
C
C     LES NORMES L2 DES NBVECT PRESSION, |VITESSE|, VOLUME
C     ====================================================
C     NOMBRE DE NORMES L2 A CALCULER
C     (1:||VITESSE||L2, 2:||PRESSION||L2)
      NBCOL2 = 2
C
C     NUMERO DE LA FONCTIONS UTILISATEUR POUR DONNER LA
C     VITESSE_EXACTE(t,x,y,z,nocomp)  => NORME L2 de |VITESSE EXACTE|
      NOFOVI = NOFOVITE()
      IF( NOFOVI .GT. 0 ) NBCOL2 = NBCOL2 + 1
C     => CALCUL DU TMS 'VECTEUR"VITESSEEXACTE' A FAIRE
C
C     PRESSION_EXACTE(t,x,y,z) => NORME L2 de la PRESSION EXACTE
      NOFOPR = NOFOPRES()
      IF( NOFOPR .GT. 0 ) NBCOL2 = NBCOL2 + 1
C     => CALCUL DU TMS 'VECTEUR"PRESSIONEXACTE' A FAIRE
C
C     CONSTRUCTION DU TMS 'VECTEUR"L2VITESSEPRESS'
C     --------------------------------------------
      L = WECTEU + NBVECT * NBCOL2 * MOREE2 + NBVECT+1
      CALL LXTNDC( NTLXOB, 'VECTEUR"L2VITESSEPRESS', 'REEL', L )
      CALL LXTSOU( NTLXOB, 'VECTEUR"L2VITESSEPRESS', NTVEL2, MNVEL2 )
C     NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR = NOMBRE DE VECTEURS STOCKES
      MCN(MNVEL2+WBCOVE) = NBVECT
C     NOMBRE DE VECTEURS NORME L2 MOYENNE
      MCN(MNVEL2+WBVECT) = NBCOL2
C     NOMBRE DE TEMPS A LA FIN DES VECTEURS
      MCN(MNVEL2+WBCPIN) = NBVECT+1
C
C     TABLEAU NORMES L2 DU MODULE DE LA VITESSE  1-ER VECTEUR
      MNINTVIT = MNVEL2 + WECTEU
C     TABLEAU NORMES L2 DE LA PRESSION           2-EME VECTEUR
      MNINTPRE = MNINTVIT + MOREE2 * NBVECT
C
      IF( NOFOVI .GT. 0 ) THEN
C        TABLEAU NORMES L2 DE L'ERREUR SUR LE MODULE DE LA VITESSE 3EME VECTEUR
         MNINTVER = MNINTPRE + MOREE2 * NBVECT
      ELSE
         MNINTVER = MNINTPRE
      ENDIF
C
      IF( NOFOPR .GT. 0 ) THEN
C        TABLEAU NORMES L2 DE L'ERREUR SUR LA PRESSION 3EME ou 4EME VECTEUR
         MNINTPER = MNINTVER + MOREE2 * NBVECT
      ELSE
         MNINTPER = MNINTVER
      ENDIF
C
C     MISE A ZERO DES TABLEAUX DES NORMES L2
      CALL AZEROD( NBCOL2*NBVECT, MCN(MNINTVIT) )
C
C     SI VITESSE_EXACTE(t,x,y,z,nocomp) alors CALCUL de VITESSEk(NOEUDS)
C     ==================================================================
      IF( NOFOVI .GT. 0 ) THEN
C
C        CONSTRUCTION DU TMS 'VECTEUR"VITESSEEXACTE'
         CALL LXTSOU( NTLXOB, 'VECTEUR"VITESSEEXACTE', NTVIEX, MNVIEX )
         IF( NTVIEX .GT. 0 ) THEN
            IF( AVANT( MCN(MNVECT), MCN(MNVIEX) ) ) THEN
C              VITESSES EXACTES POSTERIEURES AUX VITESSES-PRESSIONS
C              DEJA CALCULEES => ELLES NE SONT PAS RECALCULEES
               GOTO 100
            ENDIF
         ENDIF
C
         IF(NTVIEX.GT.0) CALL LXTSDS(NTLXOB, 'VECTEUR"VITESSEEXACTE')
         L = WECTEU + NDIM * NBNOVI * NBVECT * MOREE2 + NBVECT
         CALL LXTNDC( NTLXOB, 'VECTEUR"VITESSEEXACTE', 'REEL', L )
         CALL LXTSOU( NTLXOB, 'VECTEUR"VITESSEEXACTE', NTVIEX, MNVIEX )
C        NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR
         MCN(MNVIEX+WBCOVE) = NBNOVI
C        NOMBRE DE VECTEURS = NB CAS * NOMBRE DE COMPOSANTES DE LA VITESSE
         MCN(MNVIEX+WBVECT) = NBVECT * NDIM
C        NOMBRE DE TEMPS A LA FIN DES VECTEURS
         MCN(MNVIEX+WBCPIN) = NBVECT
C
C        ADRESSE DU TABLEAU VITEXA(NBNOVI, NBVECT, NDIM )
         MNVITEXA = MNVIEX + WECTEU
C
C        CALCUL DE LA VITESSE EXACTE EN TOUS LES NOEUDS DU MAILLAGE
         CALL VITEXACT( NOFOVI, NDIM, NBNOVI, NBVECT, MCN(MNTIMES),
     %                  MCN(MNXYZN+WYZNOE),   MCN(MNVITEXA) )
C
C        LE STOCKAGE DU TEMPS POUR LE TMS 'VECTEUR"L2VITESSEPRESS'
         MNTIMEVE = MNVIEX + WECTEU + MOREE2 * NBNOVI*NBVECT*NDIM
         CALL TRTATA( RMCN(MNTIMES), RMCN(MNTIMEVE), NBVECT )
C
C        LA DATE DU TMS VECTEUR"L2VITESSEPRESS
         CALL ECDATE( MCN(MNVIEX) )
C
C        LE NUMERO DU TABLEAU DESCRIPTEUR
         MCN( MNVIEX + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
      ENDIF
C
C     SI PRESSION_EXACTE(t,x,y,z) alors CALCUL de PRESSION(NOEUDS)
C     ============================================================
 100  IF( NOFOPR .GT. 0 ) THEN
C
C        CONSTRUCTION DU TMS 'VECTEUR"PRESSIONEXACTE'
         CALL LXTSOU( NTLXOB, 'VECTEUR"PRESSIONEXACTE', NTPREX,MNPREX)
         IF( NTPREX .GT. 0 ) THEN
            IF( AVANT( MCN(MNVECT), MCN(MNPREX) ) ) THEN
C              PRESSIONS EXACTES POSTERIEURES AUX VITESSES-PRESSIONS
C              DEJA CALCULEES => ELLES NE SONT PAS RECALCULEES
               GOTO 200
            ENDIF
         ENDIF
         IF(NTPREX.GT.0) CALL LXTSDS(NTLXOB, 'VECTEUR"PRESSIONEXACTE')
         L = WECTEU + NBNOPR * NBVECT * MOREE2 + NBVECT
         CALL LXTNDC( NTLXOB, 'VECTEUR"PRESSIONEXACTE', 'REEL', L )
         CALL LXTSOU( NTLXOB, 'VECTEUR"PRESSIONEXACTE', NTPREX,MNPREX)
C        NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR
         MCN(MNPREX+WBCOVE) = NBNOPR
C        NOMBRE DE VECTEURS = NOMBRE DE COMPOSANTES DE LA PRESSION
         MCN(MNPREX+WBVECT) = NBVECT
C        NOMBRE DE TEMPS A LA FIN DES VECTEURS
         MCN(MNPREX+WBCPIN) = NBVECT
C
C        ADRESSE DU TABLEAU PREX( NBNOPR, NBVECT )
         MNPREEXA = MNPREX + WECTEU
C
C        CALCUL DE LA PRESSION EXACTE EN TOUS LES NOEUDS DU MAILLAGE
         CALL PREEXACT( NOFOPR, NBNOPR, NBVECT, MCN(MNTIMES),
     %                  MCN(MNXYZN+WYZNOE), MCN(MNPREEXA) )
C
C        LE STOCKAGE DU TEMPS POUR LE TMS 'VECTEUR"PRESSIONEXACTE'
         MNTIMEPE = MNVIEX + WECTEU + MOREE2 * NBNOPR*NBVECT*NDIM
         CALL TRTATA( RMCN(MNTIMES), RMCN(MNTIMEPE), NBVECT )
C
C        LA DATE DU TMS VECTEUR"L2VITESSEPRESS
         CALL ECDATE( MCN(MNPREX) )
C
C        LE NUMERO DU TABLEAU DESCRIPTEUR
         MCN( MNPREX + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
      ENDIF
C
C     CALCUL DU VOLUME DU DOMAINE ET POUR CHAQUE PAS DE TEMPS CALCUL
C     DE LA NORME L2 DU MODULE DE LA VITESSE ET DE LA PRESSION
C     EVENTUELLEMENT DE LA NORME L2 DE L'ERREUR SUR LE MODULE DE LA VITESSE
C     EVENTUELLEMENT DE LA NORME L2 DE L'ERREUR SUR LA PRESSION
C     =====================================================================
 200  MNVXYZP = MNVECT+WECTEU
      CALL TMSL2VP1( NDIM,   NTDLVP, NBVECT,
     %               NUTYEL, NBELEM, NBNOE,  MCN(MNELE+WUNDEL),
     %               NBNOPR, NBNOVI, MCN(MNNDDL),
     %               MCN(MNXYZN+WYZNOE), MCN(MNX),
     %               MCN(MNVXYZP), MCN(MNVITEXA), MCN(MNPREEXA),
     %               VOLUME, MCN(MNINTVIT), MCN(MNINTPRE),
     %               NOFOVI, MCN(MNINTVER), NOFOPR, MCN(MNINTPER), IERR)
C
C     LE STOCKAGE DU TEMPS POUR LE TMS VECTEUR"L2VITESSEPRESS
      MNTIMEL2 = MNVEL2 + WECTEU + MOREE2 * NBVECT * NBCOL2
      CALL TRTATA( RMCN(MNTIMES), RMCN(MNTIMEL2), NBVECT )
C
C     LE VOLUME REEL SIMPLE PRECISION EST AJOUTE APRES TOUS LES TEMPS
      RMCN(MNTIMEL2+NBVECT) = REAL( VOLUME )
C
C     LA DATE DU TMS VECTEUR"L2VITESSEPRESS
      CALL ECDATE( MCN(MNVEL2) )
C
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVEL2 + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
C     SUPPRESSION DU TABLEAU DEVENU INUTILE
 9999 IF( MNX .GT. 0 ) CALL TNMCDS( 'REEL', NBNOE*3, MNX )
C
      RETURN
      END
