      SUBROUTINE VEVITE( NCAS0,  NCAS1,  NCAS,
     %                   CMVITE, vitx,   vity,   vitz,
     %                   NBPOI,  XYZPOI, NBNV,   NOPTEF,
     %                   NBFLEC, MXFLEC, XYZDFL, CMMXFL,
     %                   NBAREF, MXAREF, NOAREF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    LISTER LES VECTEURS VITESSES AUX NOEUDS VITESSE DE L'EF 3D
C -----    AYANT UNE INTERSECTION AVEC LE PLAN NOAXE

C ENTREES :
C ---------
C NCAS0:NCAS1 : NOMBRE DE VECTEURS VITESSE STOCKES  (=NCAS1-NCAS0+1)
C NCAS0  : NUMERO DU PREMIER CAS RETROUVE PARMI LES VECTEURS DES FICHIERS
C NCAS1  : NUMERO DU DERNIER CAS RETROUVE PARMI LES VECTEURS DES FICHIERS
C NCAS   : NUMERO DU VECTEUR VITESSE A TRACER

C CMVITE : NOMBRE DE CM POUR L'UNITE DE VITESSE
C VITX   : COMPOSANTE X DE LA VITESSE EN CHAQUE POINT DES TETRAEDRES
C VITY   : COMPOSANTE Y DE LA VITESSE EN CHAQUE POINT DES TETRAEDRES
C VITZ   : COMPOSANTE Z DE LA VITESSE EN CHAQUE POINT DES TETRAEDRES
C NBNV   : NOMBRE DE NOEUDS ELEMENTAIRES SUPPORT D'UNE VITESSE
C          (5 pour TETRAEDRE BREZZI-FORTIN, 10 pour TETRA TAYLOR-HOOD)
C NOPTEF : NO DES POINTS DU TETRAEDRE SECTIONNE
C
C MODIFIE:
C --------
C CMMXFL : CM DE LA FLECHE MAXIMALE
C
C SORTIES :
C ---------
C NBFLEC : NOMBRE DE FLECHES VITESSES
C MXFLEC : NOMBRE MAXIMAL DE FLECHES VITESSES DECLARABLES DANS XYZDFL
C XYZDFL : 1:3 XYZ DU POINT DE DEPART DE LA FLECHE
C          4:6 XYZ DE LA DIRECTION DE LA FLECHE
C          7   DIMENSION EN CM DU TRACE
C              SON SIGNE DETERMINE LE SENS DU TRIANGLE DE LA FLECHE
C NBAREF : NOMBRE D'ARETES DES EF SECTIONNES
C MXAREF : MAXIMUM D'ARETES DES EF SECTIONNES A DECLARER DANS NOAREF
C NOAREF : NO DES 2 SOMMETS DES ARETES DES EF SECTIONNES
C IERR   : 1 SI TABLEAU XYZDFL SATURE, 0 SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Laboratoire JL LIONS UPMC Paris  Fevrier 2007
C MODIFS : ALAIN PERRONNET Saint PIERRE du PERRAY           Fevrier 2022
C....................................................................012
      include"./incl/ponoel.inc"

      type typ_dptab
         DOUBLE PRECISION, dimension(:), pointer :: dptab
      end type typ_dptab
      type( typ_dptab ), dimension(NCAS0:NCAS1) :: vitx, vity, vitz

      REAL              XYZPOI(3,NBPOI)
      REAL              XYZDFL(7,MXFLEC )
      INTEGER           NOAREF(2,MXAREF), NOPTEF(NBNV)
      INTRINSIC         SQRT, MAX, REAL

      IERR = 0

C     LISTAGE DES VECTEURS VITESSES AUX NBNV NOEUDS DU TETRAEDRE
      DO 10 L=1,NBNV

C        CONSTRUCTION DU VECTEUR VITESSE
         IF( NBFLEC .GE. MXFLEC ) THEN
            IERR = 1
            RETURN
         ENDIF
         NBFLEC = NBFLEC + 1
C
C        XYZ DU DEBUT DE LA FLECHE
         NS = NOPTEF(L)
         XYZDFL(1,NBFLEC) = XYZPOI(1,NS)
         XYZDFL(2,NBFLEC) = XYZPOI(2,NS)
         XYZDFL(3,NBFLEC) = XYZPOI(3,NS)
C
C        LONGUEUR CM DU CORPS DE LA FLECHE
         CONXCM = REAL( vitx(NCAS)%dptab(NS) * CMVITE )
         CONYCM = REAL( vity(NCAS)%dptab(NS) * CMVITE )
         CONZCM = REAL( vitz(NCAS)%dptab(NS) * CMVITE )
         XYZDFL(7,NBFLEC) = SQRT( CONXCM**2 + CONYCM**2 + CONZCM**2 )
         CMMXFL = MAX( CMMXFL, XYZDFL(7,NBFLEC) )
C
C        DIRECTION DE LA FLECHE
         XYZDFL(4,NBFLEC) = CONXCM
         XYZDFL(5,NBFLEC) = CONYCM
         XYZDFL(6,NBFLEC) = CONZCM
 10   CONTINUE
C
C     AJOUT DES ARETES DE L'EF SECTIONNE
      IF( NBAREF+NARET .GT. MXAREF ) THEN
         IERR = 2
         RETURN
      ENDIF
      DO 20 K=1,NARET
         NBAREF = NBAREF + 1
C        LE NO DES 2 SOMMETS DE L'ARETE K DE L'EF
         NOAREF(1,NBAREF) = NOPTEF( NOSOAR(1,K) )
         NOAREF(2,NBAREF) = NOPTEF( NOSOAR(2,K) )
 20   CONTINUE
C
      RETURN
      END
