      PROGRAM PPINIT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CREER LA MEMOIRE SECONDAIRE
C -----       LE LEXIQUE ADAM 'A'  ( NOTRE PERE A TOUS |)
C             LE NOM 'POINTS       ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C             LE NOM 'LIGNES       ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C             LE NOM 'SURFACES     ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C             LE NOM 'VOLUMES      ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C             LE NOM 'OBJETS       ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C             LE NOM 'FONCTIONS    ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C             LE NOM 'TRANSFO      ' DANS LE LEXIQUE ADAM ( LEXIQUE )
C       FERMER LA MEMOIRE SECONDAIRE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     JUILLET 1989
C2345X7..............................................................012
      IMPLICIT INTEGER (I-N)
      IMPLICIT REAL    (A-H,O-Z)
      include"./incl/ppmck.inc"
      include"./incl/langue.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/msvaau.inc"
      include"./incl/trvari.inc"
      include"./incl/xyzext.inc"
      include"./incl/td.inc"
C
C     MXNMAD NOMBRE DE NOMS DU LEXIQUE ADAM
      INTEGER           MXNMAD
      PARAMETER        (MXNMAD=16)
C
C     MX.... NOMBRE MAXIMAL DE ....
      INTEGER           MXPOIN, MXLIGN, MXSURF, MXVOLU, MXOBJE, MXFONC,
     %                  MXTRAN, MXTTRA
      PARAMETER        (MXPOIN= 256, MXLIGN=128,
     %                  MXSURF=  64, MXVOLU= 32, MXOBJE=16,
     %                  MXFONC=  64, MXTRAN= 32, MXTTRA= 4  )
C
      include"./incl/pp.inc"
      REAL              RMCN(MOTMCN)
      COMMON             MCN(MOTMCN)
      EQUIVALENCE       (MCN(1),RMCN(1))
C
      COMMON / UNITES /  LECTEU, IMPRIM, NUNITE(30)
      COMMON / MSSFTA /  MSSF(28),NTADAM
      COMMON / FONNT  /  NTI,NTR,NTL(7),NTCOMM

C     LES ARGUMENTS A L'APPEL DU LOAD MODULE ppinit ET AUXILIAIRES
      INTEGER          EXISTNF,  NBARGS
      CHARACTER*128    NMFILEDO, ARGUMENT
C
C     RECONNAISSANCE DE LA LANGUE DES DONNEES DE Mefisto
      CALL LANGUE
C
C     NOM DU REPERTOIRE DE TRAVAIL
      WRITE(IMPRIM,*)
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*)'Nom du REPERTOIRE de TRAVAIL :'
      ELSE
         WRITE(IMPRIM,*)'WORKING DIRECTORY NAME :'
      ENDIF
      CALL SYSTEM( 'echo `pwd` ' )
      WRITE(IMPRIM,*)
C
C     NOMBRE DES ARGUMENTS DE LA COMMANDE D'EXECUTION DU LOAD-MODULE
C     ==============================================================
      NBARGS = IARGC()
      IF( LANGAG .EQ. 0 ) THEN
        WRITE(IMPRIM,*)'Mefisto-INITIER: NOMBRE DES ARGUMENTS=',NBARGS+1
      ELSE
         WRITE(IMPRIM,*)'Mefisto-INITIER: ARGUMENT NUMBER=',NBARGS+1
      ENDIF
      DO N=0,NBARGS
C        EXPLORATION DES ARGUMENTS
         CALL GETARG( N, ARGUMENT )
         WRITE(IMPRIM,*)'Mefisto-INITIER: ARGUMENT',N,' = ',ARGUMENT
      ENDDO
C     RECHERCHE D'UN EVENTUEL NOM DE FICHIERS DE DONNEES POUR Mefisto
      CALL NMFIDOCO( 'ppinit', EXISTNF, NMFILEDO )
C
C     LE FORMAT LIBRE, LE NUMERO DES UNITES ....
      CALL INITIA( .FALSE. )
C
C     AFFICHAGE DE LA TAILLE DU SUPER-TABLEAU NUMERIQUE
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10010) MOTMCN
      ELSE
         WRITE(IMPRIM,20010) MOTMCN
      ENDIF
10010 FORMAT('SUPER-TABLEAU MCN DE',I12,' MOTS-MEMOIRE')
20010 FORMAT('SUPER-ARRAY MCN WITH',I12,' WORDS of MEMORY')
C
C     DECLARATION DE LA MEMOIRE SECONDAIRE ET OUVERTURE
C     NOMBRE DE MOTS D'UNE PAGE DU SUPER-FICHIER MOPASF
      MOPASF = 128
      CALL MSIN( MOTMCN, MOPASF )
C
C     LA DECLARATION DU LEXIQUE ADAM
      CALL LXDC( 24, MXNMAD, NTADAM )
C
C     LE LEXIQUE POINTS A MXPOIN NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'POINT', 24, MXPOIN )
C
C     LE LEXIQUE LIGNES A MXLIGN NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'LIGNE', 24, MXLIGN )
C
C     LE LEXIQUE SURFACES A MXSURF NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'SURFACE', 24, MXSURF )
C
C     LE LEXIQUE VOLUMES A MXVOLU NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'VOLUME', 24, MXVOLU )
C
C     LE LEXIQUE OBJETS A MXOBJE NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'OBJET', 24, MXOBJE )
C
C     LE LEXIQUE FONCTIONS A MXFONC NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'FONCTION', 24, MXFONC )
C
C     LE LEXIQUE TRANSFORMATIONS A MXTRAN NOMS DE 24 CARACTERES AU PLUS
      CALL LXLXDC( NTADAM, 'TRANSFO', 24, MXTRAN )
      CALL LXLXOU( NTADAM, 'TRANSFO', NTTRAN, MNTRAN )
C     CREATION DE LA TRANSFORMATION 'I' IDENTITE AVEC LE NUMERO 1
      CALL LXLXDC( NTTRAN, 'I', 24, MXTTRA )
C
C     LE TMS DES COORDONNEES EXTREMALES
C     LES COORDONNEES DU CADRE INITIAL AVEC L'ORIGINE
      INIEXT = 0
      MOAXYZ = 0
      XYZAMPLI(1) = 1
      XYZAMPLI(2) = 1
      XYZAMPLI(3) = 1
      XYZAMPLI(4) = 1
      COOEXT(1,1) = -1.0
      COOEXT(1,2) =  1.0
      COOEXT(2,1) = -0.6
      COOEXT(2,2) =  0.6
      DO 10 I=3,6
         COOEXT(I,1) = 0
         COOEXT(I,2) = 0
 10   CONTINUE
      CALL LXTNDC( NTADAM, 'MIN_MAX_SOMMETS', 'REEL', 6*2+2+4 )
C
C     DECLARATION DES TABLES DU LANGAGE UTILISATEUR LU
      CALL LUINIT
C
C     SAUVEGARDE DES VARIABLES DU LANGAGE UTILISATEUR
      CALL LUFE
C
C     SAUVEGARDE DE LA MEMOIRE SECONDAIRE ET ARRET
      CALL MSFE
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) 'FIN CORRECTE INITIER'
      ELSE
         WRITE(IMPRIM,*) 'END of INITIER'
      ENDIF

      STOP
      END
