      SUBROUTINE ASFONOEUD( NBDLNO, NBNOEUD, NDSM,
     %                      NBFNFX, NODLFN,  VADLFN, RELMIN,
     %                      B )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT:     AJOUTER LES FORCES NODALES AUX SECONDS MEMBRES DEJA ASSEMBLES
C ----
C ENTREES:
C --------
C NBDLNO : NOMBRE DE DL EN UN NOEUD
C NBNOEUD: NOMBRE DE NOEUDS DU MAILLAGE
C NDSM   : NOMBRE DE CAS OU SECONDS MEMBRES
C NBFNFX : NOMBRE DE FORCES NODALES A ASSEMBLER
C NODLFN : LE NUMERO DES DL DES NBFNFX FORCES NODALES (NBNOEUD,NBDLNO)
C VADLFN : LA VALEUR DES NBFNFX FORCES NODALES
C RELMIN : LA VALEUR TEST DE NON INITIALISATION D UNE FORCE NODALE
C
C MODIFIE:
C --------
C B      : TABLEAU(NBDLNO,NBNOEUD,NDSM) AVANT ET APRES ASSEMBLAGE DES FORCES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: A.PERRONNET LJLL UPMC PARIS & St PIERRE DU PERRAY JANVIER 2014
C2345X7..............................................................012
      DOUBLE PRECISION B(NBDLNO,NBNOEUD,NDSM)
      DOUBLE PRECISION VADLFN(NDSM,NBFNFX), RELMIN, FN
      INTEGER          NODLFN(NBFNFX)
C
C     LA BOUCLE SUR LES FORCES NODALES
      DO J=1,NBFNFX
C
C        LE NUMERO DU DL EN NUMEROTATION (NBNOEUD,NBDLNO)
         NODLNO = NODLFN( J ) / NBNOEUD
C        NUMERO DU NOEUD
         NONOEU = NODLFN( J ) - NODLNO * NBNOEUD
C        NUMERO DU DL EN CE NOEUD
         NODLNO = NODLNO + 1
C
         DO I = 1, NDSM
C
C           SI    LA VALEUR DE LA FORCE NODALE N A PAS ETE INITIALISEE
C           ALORS ELLE EST RAMENEE A 0
            FN = VADLFN( I , J )
            IF( FN .EQ. RELMIN ) FN = 0.D0
C
C           AJOUT DE LA FORCE NODALE FN
            B( NODLNO, NONOEU, I ) = B( NODLNO, NONOEU, I ) + FN

         ENDDO
C
      ENDDO

      RETURN
      END
