      SUBROUTINE ASVEVG ( NTDL, NBDLIB, NBDL, NODL, NODLIB, VE,
     %                    VG )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ASSEMBLER LE SECOND MEMBRE ELEMENTAIRE DANS LE VECTEUR GLOBAL
C -----    AVEC CERTAINS DES DEGRES DE LIBERTE FIXES A ZERO
C
C ENTREES:
C --------
C NTDL   : NOMBRE TOTAL DE DEGRES DE LIBERTE DU MAILLAGE FIXES OU NON
C NBDLIB : NOMBRE TOTAL DE DEGRES DE LIBERTE NON FIXES
C NBDL   : NOMBRE DE   DEGRES DE LIBERTE DE L ELEMENT FINI
C NODL   : NO DES NBDL DEGRES DE LIBERTE DE L ELEMENT FINI
C NODLIB : NODLIB(I) = NUMERO DU DEGRE DE LIBERTE S'IL EST LIBRE
C                     -INDICE DANS LA LISTE DES DL BLOQUES S'IL EST BLOQUE
C          I DE 1 A NTDL NOMBRE TOTAL DE DL DU MAILLAGE
C VE     : SECOND MEMBRE ELEMENTAIRE  (NBDL)
C
C SORTIES:
C --------
C VG     : VECTEUR SECOND MEMBRE GLOBAL (NBDLIB)
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET St PIERRE DU PERRAY & LJLL UPMC  JANVIER 2010
C23456---------------------------------------------------------------012
      INTEGER           NODL(NBDL), NODLIB(NTDL)
      DOUBLE PRECISION  VE(NBDL), VG(NBDLIB)
C
      DO 20 K=1,NBDL
C
C        LE NO GLOBAL DU I-EME DEGRE DE LIBERTE LOCAL DANS LE MAILLAGE
         NDL = NODL(K)
C
C        NUMERO DU DL DANS LA NUMEROTATION DES DEGRES DE LIBERTE NON FIXES
C        ATTENTION: LES AUTRES DL FIXES SONT SUPPOSES NULS
         NDLL = NODLIB( NDL )
C
         IF( NDLL .GT. 0 ) THEN
C           ASSEMBLAGE DE LA K-EME COMPOSANTE DE VE DANS VG
            VG( NDLL ) = VG( NDLL ) + VE( K )
         ENDIF
C
 20   CONTINUE
C
      RETURN
      END
