      SUBROUTINE DEPLT1( MOREE2, MNXYZN, NDPGST, MXDONN, LPVIIN, MNVIIN,
     %                   NBCODE, NBTYEL, MNNPEF, NUMIOB, MNDOEL,
     %                   DT,     MNUG0,  MNUG1 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    A PARTIR DU VECTEUR DEPLACEMENT UG1 A L'INSTANT T0+DT
C -----    DEJA CALCULE SUR L'OBJET REMPLACER LES VALEURS
C          DEFINIES A PARTIR DU TMS VITESSEINIT DEFINI SUR LES PLSV
C          PAR LA MEME FORMULE UG1 = UG0 + DT VO
C          IL EST SUPPOSE QU'AU MOINS UN PLSV SUPPORTE UN TMS 'VITESSEINIT'
C
C ENTREES:
C --------
C MOREE2 : NOMBRE DE MOTS   D'UNE VARIABLE REELLE DOUBLE PRECISION
C MNXYZN : ADRESSE MCN DU TABLEAU XYZNOEUD DE L'OBJET KNOMOB
C NDPGST : CODE D'IDENTIFICATION DES SOMMETS POINTS NOEUDS
C MXDONN : NOMBRE MAXIMAL DE TABLEAUX DE DONNEES
C          cf $MEFISTO/incl/donele.inc et donthe.inc
C LPVIIN : NUMERO DU TABLEAU DE DONNEE 'VITESSEINIT'
C MNVIIN : ADRESSE MCN DU TMS 'VITESSEINIT'
C
C NBCODE : NOMBRE DE COMPOSANTES DU DEPLACEMENT EN TOUT NOEUD
C NBTYEL : NOMBRE DE TYPES D'EF DU MAILLAGE DE CET OBJET
C MNNPEF : ADRESSE MCN DU TABLEAU DES ADRESSES MCN DES TMS NPEF"TYPE EF
C NUMIOB : NUMERO MINIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C MNDOEL : LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C          TABLEAUX DECRIVANT LES DONNEES (ELASTICITE,THERMIQUE,...)
C          DE L'OBJET COMPLET
C
C DT     : PAS DE TEMPS
C MNUG0  : ADRESSE MCN DU VECTEUR DEPLACEMENT A L'INSTANT INITIAL
C          CE TABLEAU DOIT ETRE INITIALISE
C MNUG1  : ADRESSE MCN DU VECTEUR DEPLACEMENT A L'INSTANT INITIAL + DT
C          CE TABLEAU VA ETRE INITIALISE DANS CE SP
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS        JUIN 1999
C23456---------------------------------------------------------------012
      include"./incl/donele.inc"
      include"./incl/a___vitesseinit.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___vecteur.inc"
      include"./incl/ponoel.inc"
C
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/pp.inc"
      COMMON             MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE       (MCN(1), RMCN(1), DMCN(1))
C
      INTEGER           NOOBVC, NOOBSF(6), NOOBLA(12), NOOBPS(8)
      INTEGER           NUMIOB(4), MNDOEL(4)
      INTEGER           NOTYOB(3,MXNOEL)
      DOUBLE PRECISION  DT
      DOUBLE PRECISION  XPOIN,  YPOIN, ZPOIN
      DOUBLE PRECISION  VITES0(3)
C     AU MOINS UN PLSV SUPPORTE UN TMS 'VITESSEINIT'
C
C     LA BOUCLE SUR LES TYPES D'ELEMENTS FINIS DU MAILLAGE DE L'OBJET
      MM  = MNXYZN + WYZNOE - 3
      MN0 = (MNUG0-1) / MOREE2 - NBCODE
      MN1 = (MNUG1-1) / MOREE2 - NBCODE
      DO 90 NOTYEL = 1, NBTYEL
C
C        L'ADRESSE DU TABLEAU NPEF"No TYPE EF
         MNELE = MCN( MNNPEF - 1 + NOTYEL )
C        LE NUMERO DU TYPE DE L'ELEMENT FINI
         NUTYEL = MCN( MNELE + WUTYEL )
C        LE NOMBRE D'ELEMENTS DE CE TYPE
         NBELEM = MCN( MNELE + WBELEM )
C
C        L'ADRESSE MCN DES NOEUDS ET POINTS GEOMETRIQUES DES EF
         MNNDEL = MNELE + WUNDEL
         MNPGEL = MNNDEL
         IF( NDPGST .GE. 2 ) THEN
            MNPGEL = MNPGEL + NBELEM * MCN(MNELE+WBNDEL)
         ENDIF
C
C        LES CARACTERISTIQUES DE L'ELEMENT FINI
C        ON TROUVE: NBPOE, NBNOE, NARET
         CALL ELTYCA( NUTYEL )
C
C        LA BOUCLE SUR LES ELEMENTS FINIS DE CE TYPE NUTYEL
         DO 80 NUELEM = 1, NBELEM
C
C           LES NOEUDS DE L'ELEMENT FINI
C           LE NUMERO DE VOLUME  DE L'EF
C           LE NUMERO DE SURFACE DES FACES   DE L'EF
C           LE NUMERO DE LIGNE   DES ARETES  DE L'EF
C           LE NUMERO DE POINT   DES SOMMETS DE L'EF
            CALL EFPLSV( MNELE , NUELEM,
     %                   NOVCEL, NOSFEL, NOLAEL, NOPSEL,
     %                   NOOBVC, NOOBSF, NOOBLA, NOOBPS )
C
C           LE CALCUL DU TYPE OBJET DE CHAQUE NOEUD DE L'ELEMENT FINI
C           EN COMMENCANT PAR LE VOLUME, PUIS LES FACES, PUIS LES ARETES
C           PUIS LES SOMMETS CE QUI ASSURE LA PRIORITE DES POINTS SUR
C           LES LIGNES, SURFACES ET VOLUMES
            CALL EFTNND( NOOBVC, NOOBSF, NOOBLA, NOOBPS,
     %                   NUMIOB, MNDOEL,
     %                  'VITESSEINIT', MXDONN, LPVIIN,
     %                   NOTYOB )
C
C           LE RECENSEMENT DE LA VITESSE INITIALE
C           AUX NBNOE NOEUDS DE CET ELEMENT FINI
            DO 70 J=1,NBNOE
C
C              LE NUMERO DU NOEUD DANS LE MAILLAGE DE L'OBJET
               NONOE = MCN( MNNDEL-1 + NUELEM + NBELEM*(J-1) )
C
C              L'ADRESSE MCN DU TABLEAU VITESSEINIT
               MN2 = NOTYOB(3,J)
C
C              EXISTE-T-IL UN "VITESSEINIT" EN CE NOEUD ?
               IF( MN2 .GT. 0 ) THEN
C
C                 CALCUL DU DEPLACEMENT INITIAL EN CE NOEUD
C                 LE TYPE OBJET DU NOEUD J DE L'EF
                  NTYOB = NOTYOB(1,J)
                  NOOB  = NOTYOB(2,J)
                  N     = MM + 3 * NONOE
                  XPOIN = RMCN(N)
                  YPOIN = RMCN(N+1)
                  ZPOIN = RMCN(N+2)
                  CALL REVIIN( NTYOB,NOOB,NBCODE,XPOIN,YPOIN,ZPOIN,
     %                         MNVIIN, VITES0 )
C                 LE VECTEUR UG1 EST INITIALISE EN CE NOEUD
                  L  = MN0 + NBCODE*NONOE
                  LL = MN1 + NBCODE*NONOE
                  DO 69 K=1,NBCODE
C                    LE VECTEUR UG1 AU TEMPS T0+DT EST INITIALISE
                     DMCN(LL+K) = DMCN(L+K) + DT * VITES0(K)
 69               CONTINUE
C
               ENDIF
C
 70         CONTINUE
 80      CONTINUE
 90   CONTINUE
C
C     ICI LE VECTEUR MNUG1 EST INITIALISE DEFINITIVEMENT
      RETURN
      END
