      SUBROUTINE INITVV0( NUINVP, N, V0, RC, V1, NBVP, VECPR, MGVECPR,
     %                    NCODSM, NBRDMG, MUMG, MG,  V, W, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TROUVER UN VECTEUR MG-ORTHOGONAL AUX NB VECTEURS PROPRES VECPR
C -----    EN FONCTION DU NUMERO NUINVP
C
C ENTREES:
C --------
C NUINVP : NUMERO DU CHOIX D'INITIALISATION
C N      : NOMBRE DE COMPOSANTES DES VECTEURS
C V0 V1  : 2 VECTEURS ( V0=DIAGONALE(A) V1=DIAGONALE(B) )
C RC     : UN REEL DOUBLE PRECISION
C NBVP   : NOMBRE DE VECTEURS PROPRES DEJA CALCULES
C VECPR  : NBVP VECTEURS MG-ORTHOGONAUX
C MGVECPR: NBVP MG * VECPR OU MG EST LA MATRICE DE MASSE
C
C NCODSM : CODE DE STOCKAGE DE LA MATRICE GLOBALE DE CAPACITE MG
C          0 SI MATRICE DIAGONALE
C          1 SI MATRICE SYMETRIQUE
C         -1 SI MATRICE NON SYMETRIQUE
C NBRDMG : NOMBRE DE REELS DOUBLE PRECISION DE LA MATRICE GLOBALE MG
C          = NBRDKG SI MATRICE NON DIAGONALE, =NTDL SI MATRICE DIAGONALE
C MUMG   : POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE MG
C MG     : MATRICE PROFIL GLOBALE DE CAPACITE CALCULEE
C
C SORTIES:
C --------
C V      : LE VECTEUR MG-ORTHONORMAL AUX NBVP VECPR et tV MG V = 1
C W      : LE VECTEUR MG V  MG-ORTHONORMAL
C IERR   : = 0 SI PAS D'ERREUR RENCONTREE
C            1 SI APRES 9 TENTATIVES, AUCUN VECTEUR MG-ORTHOGONAL
C              N'A PU ETRE TROUVE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET UPMC ANALYSE NUMERIQUE PARIS     DECEMBRE 1998
C2345X7..............................................................012
      DOUBLE PRECISION  V(N), W(N), V0(N), V1(N), VECPR(N,NBVP),
     %                  MGVECPR(N,NBVP), MG(NBRDMG)
      INTEGER           MUMG(0:N)
      DOUBLE PRECISION  RC, XX, tVMGV
      INTRINSIC         SQRT
C
      NBINIT = 0
C
C     INITIALISATION DU VECTEUR PROPRE POUR L'ITERATION INVERSE
C     ---------------------------------------------------------
      IF( NUINVP .LE. 0 ) GOTO 100
C     LE VECTEUR V INITIAL EST PRIS DIRECTEMENT ET ORTHONORMALISE
C
 5    NBINIT = NBINIT + 1
      GOTO( 10, 20, 30, 40, 50, 60, 70, 80, 90 ) , NUINVP
C
C     CAS STANDARD
 10   DO 11 I=1,N
         XX = ABS( V0(I) - RC * V1(I) )
         IF( XX .LT. 1.D-20 ) XX = 1D0
         V(I) = V1(I) / XX
 11   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 20   DO 21 I=1,N
         V(I) = V1(I)
 21   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 30   DO 31 I=1,N
         V(I) = V0(I)
 31   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 40   DO 41 I=1,N
         V(I) = 1D0
 41   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 50   CALL ALEAD( 5, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 60   CALL ALEAD( 7, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 70   CALL ALEAD( 11, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 80   CALL ALEAD( 13, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 90   CALL ALEAD( 3, N, V )
C
C     B-ORTHONORMALISATION DU VECTEUR PAR RAPPORT AUX NBVP VECTEURS VECPR
 100  CALL BORTHO( N, NBVP, VECPR, MGVECPR, V )
C
C     VERIFICATION QUE LE VECTEUR V N'EST PAS LE VECTEUR ZERO
C     -------------------------------------------------------
C     Wk = MG Vk
      CALL MAPRVE( 0, 1D0, N, NCODSM, MUMG, MG, V,  W )
C
      tVMGV = 0D0
      DO I=1,N
         tVMGV = tVMGV + V(I) * W(I)
      ENDDO
C
      IF( ABS( tVMGV ) .LT. 1D-3 ) THEN
C
C        V VECTEUR NUL => ESSAI D'UNE AUTRE INITIALISATION
         IF( NBINIT .GE. 9 ) THEN
C
C           TOUTES LES 9 POSSIBILITES ONT ETE UTILISES => EN TROUVER UNE AUTRE
            IERR = 1
            GOTO 9999
         ENDIF
C
C        RECHERCHE D'UN AUTRE VECTEUR V ORTHOGONAL A CEUX CALCULES
         NUINVP = MOD( NUINVP, 9 ) + 1
         GOTO 5
C
      ENDIF
C
C     MG-ORTHONORMALISATION DE V ET W
C     -------------------------------
      tVMGV = SQRT( tVMGV )
      DO I=1,N
         V(I) = V(I) / tVMGV
         W(I) = W(I) / tVMGV
      ENDDO
      IERR = 0
C
 9999 RETURN
      END
