      SUBROUTINE INITIN( NUINVP, N, V0, RC, V1, NBVP, VECPR, BVECPR,
     %                   V )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TROUVER UN VECTEUR B-ORTHOGONAL AUX NB VECTEURS PROPRES VECPR
C -----    EN FONCTION DU NUMERO NUINVP
C
C ENTREES:
C --------
C NUINVP : NUMERO DU CHOIX D'INITIALISATION
C N      : NOMBRE DE COMPOSANTES DES VECTEURS
C V0 V1  : 2 VECTEURS ( V0=DIAGONALE(A) V1=DIAGONALE(B) )
C RC     : UN REEL DOUBLE PRECISION
C NBVP   : NOMBRE DE VECTEURS PROPRES DEJA CALCULES
C VECPR  : NBVP VECTEURS B-ORTHOGONAUX
C BVECPR : NBVP B * VECPR OU B EST LA MATRICE DE MASSE
C
C SORTIE :
C --------
C V      : LE VECTEUR B-ORTHOGONAL AUX NBVP VECPR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET UPMC ANALYSE NUMERIQUE PARIS     DECEMBRE 1998
C2345X7..............................................................012
      DOUBLE PRECISION V(N), V0(N), V1(N), VECPR(N,NBVP), BVECPR(N,NBVP)
      DOUBLE PRECISION RC, XX
C
C     INITIALISATION DU VECTEUR PROPRE POUR L'ITERATION INVERSE
C     ---------------------------------------------------------
      IF( NUINVP .LE. 0 ) GOTO 100
C     LE VECTEUR V INITIAL EST PRIS DIRECTEMENT ET ORTHONORMALISE
C
      GOTO( 10, 20, 30, 40, 50, 60, 70, 80, 90 ) , NUINVP
C
C     CAS STANDARD
 10   DO 11 I=1,N
         XX = ABS( V0(I) - RC * V1(I) )
         IF( XX .LT. 1.D-20 ) XX = 1D0
         V(I) = V1(I) / XX
 11   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 20   DO 21 I=1,N
         V(I) = V1(I)
 21   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 30   DO 31 I=1,N
         V(I) = V0(I)
 31   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 40   DO 41 I=1,N
         V(I) = 1D0
 41   CONTINUE
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 50   CALL ALEAD( 5, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 60   CALL ALEAD( 7, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 70   CALL ALEAD( 11, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 80   CALL ALEAD( 13, N, V )
      GOTO 100
C
C     REPRISE CAR OUBLI DE VALEURS PROPRES
 90   CALL ALEAD( 3, N, V )
C
C     B-ORTHONORMALISATION DU VECTEUR PAR RAPPORT AUX NBVP VECTEURS VECPR
 100  CALL BORTHO( N, NBVP, VECPR, BVECPR, V )
C
      RETURN
      END
