      SUBROUTINE ITEIN2( N,  NC, NURAC,  NUINVP,
     %                   NCODSA, MUA, A, DIAGA, MOTSRG, RG,
     %                   NCODSB, MUB, B, DIAGB,
     %                   NINVMX, NINV,
     %                   R0,     R1,    NBHR1, DETR1, NBVIR1, NOVR1,
     %                   VALPR,  VECPR, BVECPR,
     %                   R2,     V, W )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ITERATIONS INVERSES POUR AFFINER LA VALEUR PROPRE R1
C -----    ET CALCULER LE VECTEUR PROPRE ASSOCIE
C
C ENTREES:
C --------
C N      : NOMBRE DE DEGRES DE LIBER2E
C NC     : NOMBRE MAXIMAL DE VALEURS ET VECTEURS PROPRES A CALCULER
C NURAC  : NUMERO DE LA VALEUR PROPRE A CALCULER
C NUINVP : NUMERO D'INITIALISATION DU VECTEUR DE 1 A 9
C
C NCODSA : CODE DE STOCKAGE DE LA MATRICE PROFIL A
C MUA    : TABLEAU POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE A
C A      : MATRICE A - R1 B FACTORISEE = L D tL
C DIAGA  : DIAGONALE DE LA MATRICE PROFIL A
C MOTSRG : NOMBRE DE MOTS DE LA MATRICE PROFIL A
C RG     : SAUVEGARDE DE LA MATRICE A AVANT L D tL
C
C NCODSB : CODE DE STOCKAGE DE LA MATRICE PROFIL B
C MUB    : TABLEAU POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE B
C B      : MATRICE PROFIL DE MASSE
C DIAGB  : DIAGONALE DE LA MATRICE PROFIL B
C NINVMX : NOMBRE MAXIMAL D'ITERATIONS INVERSES
C
C MODIFIES:
C ---------
C NINV   : NOMBRE D'ITERATIONS INVERSES
C R0     : PLUS GRANDE VALEUR SANS VALEUR PROPRE OUBLIEE
C R1     : VALEUR PROPRE INITIALE A AFFINER PUIS MODIFIEE
C NBHR1  : NOMBRE D'HOMOTHETIES DE SCALE DU DETERMINANT DE A - R1 B
C DETR1  : DETERMINANT DE A - R1 B  * SCALE ** NBHR1
C NBVIR1 : NOMBRE DE VALEURS PROPRES INFERIEURES A R1
C NOVR1  : NOMBRE DE VALEURS PROPRES OUBLIEES DANS VALPR AVANT R1
C VALPR  : NURAC-1 VALEURS PROPRES DEJA CALCULEES
C VECPR  : VECTEURS PROPRES DEJA CALCULES
C BVECPR : B * VECTEURS PROPRES DEJA CALCULES
C
C SORTIES:
C --------
C R2     : VALEUR PROPRE CALCULEE PAR ITERATIONS INVERSES = R1 + QR
C          QR EST LA TRANSLATION PAR RAPPORT A R1
C V      : VECTEUR PROPRE ASSOCIE A LA VALEUR PROPRE R2
C W      : PRODUIT DE B AVEC V
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET UPMC ANALYSE NUMERIQUE PARIS     DECEMBRE 1998
C2345X7..............................................................012
      PARAMETER        ( NINVT=8 )
C     NINVT  NOMBRE D ITERATIONS INVERSES SANS TEST DE CONVERGENCE
C
      PARAMETER        ( SCINV=5E-5, SCLINV=1E-2)
C     SCINV  SEUIL DE CONVERGENCE       DE L ITERATION INVERSE
C     SCLINV SEUIL DE CONVERGENCE LENTE DE L ITERATION INVERSE
C
      include"./incl/langue.inc"
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      INTEGER           NINV(NC)
      DOUBLE PRECISION  A(*), RG(*), B(*)
      DOUBLE PRECISION  V(N), W(N), DIAGA(N), DIAGB(N)
      DOUBLE PRECISION  VALPR(NC), VECPR(N,NC), BVECPR(N,NC)
      DOUBLE PRECISION  R0, R1, DETR1, R2
      DOUBLE PRECISION  QR1, QR, RN, RD
C
      NBRECL = 0
      NINVTE = NINVT
C
C     R2  = R1 + QR EST LA VALEUR PROPRE CALCULEE PAR ITERATION INVERSE
      R2  = R1
      QR  = 0D0
C
C     INITIALISATION DU VECTEUR PROPRE POUR L'ITERATION INVERSE
C     ---------------------------------------------------------
 10   CALL INITIN( NUINVP, N, DIAGA, R1, DIAGB, NURAC-1, VECPR, BVECPR,
     %             V )
C
CCC      WRITE(IMPRIM,10010) NUINVP
CCC10010 FORMAT(/' INITIALISATION',I2,' DU VECTEUR ITERATION INVERSE')
C
C     Wk = B Vk
 12   CALL MAPRVE( 0,      1D0, N,
     %             NCODSB, MUB, B,  V,  W )
C
C     UNE ITERATION INVERSE DE PLUS
C     -----------------------------
      NINV(NURAC) = NINV(NURAC) + 1
C
C     Vk+1 = (A - R1 B)-1 Wk = (L D tL)-1 Wk
      CALL DRCRPR( N, NCODSA, MUA, A, W, 3,  V, IERR )
C
C     LE NUMERATEUR DU QUOTIENT DE RAYLEIGHT: RN = tVk+1 (A - R1 B) Vk+1
      RN = 0D0
      DO 20 I=1,N
         RN = RN + W(I) * V(I)
 20   CONTINUE
C
C     Wk+1 = B Vk+1
      CALL MAPRVE( 0, 1D0, N, NCODSB, MUB, B, V,  W )
C
C     LE DENOMINATEUR DU QUOTIENT DE RAYLEIGHT: RD = tVk+1 B Vk+1
      RD = 0D0
      DO 25 I=1,N
         RD = RD + W(I) * V(I)
 25   CONTINUE
C
C     QR QUOTIENT DE RAYLEIGH AVANT TRANSLATION
      QR1 = QR
      QR  = RN / RD
C
C     R2 QUOTIENT DE RAYLEIGH APRES TRANSLATION
      R2 = R1 + QR
C
CCC      WRITE(IMPRIM,10025) NINV(NURAC),R1,R2,QR
CCC10025 FORMAT(' ITERATION INVERSE',I4,' R1=',G15.7,' R2=',G15.7,
CCC     %' QR RAYLEIGHT=',G15.7)
C
      IF( ABS(QR-QR1) .LE. ABS(QR*SCINV) ) THEN
C
C        CONVERGENCE DES ITERATIONS INVERSES
C        -----------------------------------
C        LE QUOTIENT DE RAYLEIGHT EST IL GRAND?
         IF( ABS(QR) .GT. ABS(R2*0.1D0) ) THEN
C           IL ES PLUS PRUDENT DE REFAIRE UNE TRANSLATION
C           SINON RISQUE D'IMPRECISION SUR R2 FINAL!
            GOTO 40
         ELSE
C           CONVERGENCE ASSUREE DES ITERATIONS INVERSES
            GOTO 9000
         ENDIF
      ENDIF
C
C     TEST DE CONVERGENCE LENTE DE L ITERATION INVERSE
      IF( NINV(NURAC) .LT. NINVTE ) GOTO 50
      IF( ABS(QR-QR1) .GT. ABS(QR*SCLINV) ) GOTO 50
C
C     REPRISE DES CONVERGENCES LENTES DE L ITERATION INVERSE
C     ------------------------------------------------------
 40   NUINVP = MOD( NUINVP, 9 ) + 1
      NBRECL = NBRECL + 1
      NINVTE = NINV(NURAC) + NINVT
C
C     NOMBRE DE VALEURS PROPRES OUBLIEES AVANT R2
      R1 = R2
      CALL NBVAOU( R1,     N,     NURAC-1, VALPR,
     %             NCODSA, MUA,   A,       MOTSRG, RG,
     %             NCODSB, MUB,   B,
     %             NBHR1,  DETR1, NBVIR1,  NOVR1 )
C     R0 EST LA PLUS GRANDE VALEUR CALCULEE AVEC 0 VALEUR OUBLIEE
      IF( NOVR1 .EQ. 0 .AND. R1 .GT. R0 ) R0 = R1
      GOTO 10
C
C     PASSAGE A L'ITERATION INVERSE SUIVANTE
C     --------------------------------------
 50   IF( NINV(NURAC) .LE. NINVMX ) THEN
C        MAX DES ITERATIONS INVERSES NON ATTEINT => RETOUR EN ITERATION INVERSE
C        B-ORTHOGONALISATION DE V AUX VECTEURS PROPRES
         CALL BORTHO( N, NURAC-1, VECPR, BVECPR, V)
C
C        B-ORTHONORMALISATION DE V TOUTES LES ITERATIONS
C        POUR REDUIRE LES RISQUES D'UNDERFLOW!
CCC NE marche PAS pour vvpt3d.iteinv  IF( MOD(NINV(NURAC),2) .EQ. 0 ) THEN
C        Wk+1 = B Vk+1
         CALL MAPRVE( 0, 1D0, N, NCODSB, MUB, B, V,  W )
C        B-ORTHONORMALISATION DE V
         RD = 0D0
         DO 60 I=1,N
            RD = RD + V(I) * W(I)
 60      CONTINUE
C        Vk+1 = Vk+1 / (tVk+1 B Vk+1) ** 1/2
         RD = SQRT( ABS(RD) )
         DO 70 I=1,N
            V(I) = V(I) / RD
 70      CONTINUE
         GOTO 12
      ENDIF
C
C     SORTIE APRES CONVERGENCE OU MAX ITERATIONS ATTEINTES
 9000 IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,19000) NURAC, R2, NINV(NURAC)
      ELSE
         WRITE(IMPRIM,29000) NURAC, R2, NINV(NURAC)
      ENDIF
19000 FORMAT('VALEUR PROPRE',I4,' =',G15.7,
     %' APRES',I4,' ITERATIONS INVERSES')
29000 FORMAT('CONVERGED EIGENVALUE',I4,' =',G15.7,
     %' after',I4,' INVERSE ITERATIONS')
C
      RETURN
      END
