      SUBROUTINE ITEINV( NOMPB,  NTLXOB, NTDL,  INIDONN, NBROOT, EIGMAX,
     %                   NBDLFX, MNVDLX, NBDLIB, MNDLIB,
     %                   NCODSK, MNMUKG, KG,
     %                   NCODSM, MNMUMG, MG,
     %                   TETA,   MOTSRG, RG,
     %                   NTVVPR, MNVVPR, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LES VALEURS EIGV ET VECTEURS PROPRES VP TELS QUE
C -----    ( K + EIGV M ) VP = 0   ET   tM VP M = Id
C          PAR LA METHODE DES ITERATIONS INVERSES AVEC TRANSLATION
C
C ENTREES:
C --------
C NOMPB  : NOM EN 4 CARACTERES DE LA CLASSE DU PROBLEME TRAITE
C          'THER' ou 'ELAS' ou 'FLUI'
C NTLXOB : NUMERO DU TMS LEXIQUE DE L'OBJET
C NTDL   : NOMBRE DE LIGNES ET COLONNES DES MATRICES K ET M EN ENTREE
C          NOMBRE TOTAL DE DL BLOQUES+LIBRES
C
C INIDONN: =0 DONNEES A DEFINIR PAR LECTURE DES DONNEES DE L'UTILISATEUR
C          =1 NBROOT et EIGMAX SONT DEJA INITIALISEES
C NBROOT : >0 NOMBRE DES PLUS PETITES VALEURS PROPRES A CALCULER
C NBROOT : =0 EIGMAX BORNE SUPERIEURE DES VALEURS PROPRES A CALCULER
C
C EIGMAX : BORNE SUPERIEURE DES VALEURS PROPRES A CALCULER
C NBDLFX : NOMBRE DE DEGRES DE LIBERTE BLOQUES
C MNVDLX : ADRESSE MCN DES VALEURS DES NODLFX DEGRES FIXES
C NBDLIB : NOMBRE DE DEGRES DE LIBERTE LIBRES
C MNDLIB : MCN(MNDLIB-1+I) = NUMERO DE 1 A NBDLIB DU DL I (1 A NTDL) LIBRE
C                          -(INDICE DANS NODLFX) SI LE DL I EST BLOQUE
C          0  SI PAS DE DL BLOQUES
C
C NCODSK : CODE DE STOCKAGE DE LA MATRICE PROFIL K
C          =0 SI DIAGONALE
C          >0 SI PROFIL SYMETRIQUE
c          <0 SI PROFIL NON SYMETRIQUE
C MNMUK  : ADRESSE MCN DU POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE K
C KG     : MATRICE PROFIL REELLE DOUBLE PRECISION
C
C NCODSM : CODE DE STOCKAGE DE LA MATRICE PROFIL M
C          =0 SI DIAGONALE
C          >0 SI PROFIL SYMETRIQUE
C          <0 SI PROFIL NON SYMETRIQUE
C MNMUM  : ADRESSE MCN DU POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE M
C MG     : MATRICE PROFIL REELLE DOUBLE PRECISION
C TETA   : COEFFICIENT DE TRANSLATION TETA TEL QUE K <-- K + TETA M
C MOTSRG : NOMBRE DE MOTS DE LA MATRICE KG et MG et RG
C RG     : MATRICE DE SAUVEGARDE DE LA MATRICE KG
C
C SORTIES:
C --------
C NTVVPR : NUMERO      DU TMS DES VALEURS ET VECTEURS PROPRES
C MNVVPR : ADRESSE MCN DU TMS DES VALEURS ET VECTEURS PROPRES
C IERR   : 0 SI PAS D'ERREUR D'EXECUTION, NON NUL SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET      ANALYSE NUMERIQUE UPMC PARIS    AOUT 1998
C23456---------------------------------------------------------------012
      include"./incl/a___vecteur.inc"
      include"./incl/epsvvp.inc"
      include"./incl/langue.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
C
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      DOUBLE PRECISION  EIGMAX, TETA, DTETA, DET1
      CHARACTER*(*)     NOMPB
      CHARACTER*20      NOMVEC
      INTRINSIC         REAL
C
C     SEUILS INDEPENDANTS DE LA METHODE CHOISIE
C     -----------------------------------------
C     SCALE BASE POUR L EVALUATION DU DETERMINANT POUR LES HOMOTHETIES
      SCALE = 1.D70
C     PRECIS : SEUIL AU DESSOUS DUQUEL LA NORME D UN VECTEUR EST SUPPOSE NUL
C              LORS D'UNE M-ORTHONORMALISATION AUX VP PRECEDENTS
      PRECIS = 1D-10
C     FAST FACTEUR PAR LEQUEL ON TRANSLATE LEGEREMENT MU POUR PRESERVER LA FACTO
      FAST  = 5.E-5
C     SEUIL DES FACTORISATIONS CORRECTES L D tL DES MATRICES PROFIL
      EPS   = 1.E-12
C
C     LE NOMBRE DE MOTS D'UNE VARIABLE REEL2
      MOREE2 = MOTVAR(6)
C
      IF( INIDONN .GT. 0 ) GOTO 1
C
C     LECTURE DU NOMBRE DE MODES PROPRES A CALCULER
C     ---------------------------------------------
      EIGMAX = 0D0
C     NBROOT: > 0 CALCUL DES NBROOT PLUS PETITES VALEURS ET VECTEURS PROPRES
C             = 0 CALCUL DES VALEURS PROPRES POSITIVES INFERIEURES A D
C                 EN SORTIE NBROOT NOMBRE EFFECTIVEMENT CALCULE
C     EIGMAX: BORNE DES VALEURS PROPRES A DONNER LORSQUE NBROOT = 0
      CALL INVITE( 68 )
      NCVALS = 0
      CALL LIRENT( NCVALS, NBROOT )
      IF( NCVALS .LT. 0 ) THEN
C        ABANDON DE LA LECTURE DES DONNEES
         IERR = 2
         RETURN
      ENDIF
C
 1    IF( NBROOT .GT. 0 ) THEN
C
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12000) NBROOT
         ELSE
            WRITE(IMPRIM,22000) NBROOT
         ENDIF
12000    FORMAT(/'NOMBRE DE MODES PROPRES A CALCULER',T37,'=',I6)
22000    FORMAT(/'NUMBER of EIGENSOLUTIONS to COMPUTE',T37,'=',I6)
C
      ELSE
C
         IF( INIDONN .GT. 0 ) GOTO 2
C
C        ENTREE DE LA BORNE SUPERIEURE DES VALEURS PROPRES A CALCULER
C        ------------------------------------------------------------
         CALL INVITE( 7 )
         NCVALS = 0
         CALL LIRRDP( NCVALS, EIGMAX )
         IF( NCVALS .LT. 0 ) THEN
C           ABANDON DE LA LECTURE DES DONNEES
            IERR = 2
            RETURN
         ENDIF
C
 2       NBROOT = 0
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12010) EIGMAX
         ELSE
            WRITE(IMPRIM,22010) EIGMAX
         ENDIF
C
      ENDIF
12010 FORMAT(/'BORNE SUPERIEURE DES VALEURS PROPRES A CALCULER =',G15.7)
22010 FORMAT(/'SUPERIOR BOUNDARY of EIGENVALUES =',G15.7)
C
      IF( NBROOT .LE. 0 ) THEN
C
C        RECHERCHE DU NOMBRE NBROOT DE VALEURS PROPRES INFERIEURES A EIGMAX
C        ------------------------------------------------------------------
         ISC   = 1000
         DTETA = EIGMAX
C
C        COMBINAISON LINEAIRE DES 2 MATRICES PROFILS K=K-DTETA M
 2100    CALL MUA2PD( NBDLIB,   1D0, NCODSK, MCN(MNMUKG), KG,
     %                       -DTETA, NCODSM, MCN(MNMUMG), MG,
     %                                       MCN(MNMUKG), KG )
C
C        FACTORISATION DE GAUSS SYMETRIQUE: A - DTETA B = L D tL
         CALL CRMC1D( MCN(MNMUKG), KG, NBDLIB, EPS, 0,  KG, NRETOU )
         IF( NRETOU .EQ. 0 ) THEN
C           CALCUL DU DETERMINANT DE LA MATRICE
            CALL DETETD( KG, MCN(MNMUKG), NBDLIB,  NBROOT, ISC, DET1 )
         ELSE
            CALL TRTATA( RG, KG, MOTSRG )
            DTETA = DTETA*1.01D0
            GOTO 2100
         ENDIF
C
         IF( LANGAG .EQ. 0 ) THEN
            WRITE (IMPRIM,10170) NBROOT, DTETA
         ELSE
            WRITE (IMPRIM,20170) NBROOT, DTETA
         ENDIF
         IF ( NBROOT .LE. 0 ) THEN
            IF( LANGAG .EQ. 0 ) THEN
               WRITE (IMPRIM,10180) DTETA
            ELSE
               WRITE (IMPRIM,20180) DTETA
            ENDIF
            RETURN
         ENDIF
      ENDIF
10170 FORMAT('Il y a ',I6,' VALEURS PROPRES entre 0. et ',G15.7/)
20170 FORMAT('There are ',I6,' EIGENVALUES from 0. to ',G15.7/)
10180 FORMAT('ATTENTION ITEINV: 0 VALEUR PROPRE en DESSOUS de',G15.7/)
20180 FORMAT('ATTENTION ITEINV: 0 EIGENVALUE under ',G15.7/)
C
C     MXROOT: MAJORANT DU NOMBRE DE VALEURS PROPRES >NBROOT A CAUSE DES
C             VALEURS MULTIPLES OU DES VALEURS SUPERIEURES A CELLES CHERCHEES
      MXROOT = MIN( 2*NBROOT, NBROOT+8, NBDLIB/2 )
C
C     CREATION DES TABLEAUX DE TRAVAIL ET DE RESULTAT
C     -----------------------------------------------
C     LES VECTEURS PROPRES ET AUXILIAIRES
      MNV  = 0
      CALL TNMCDC( 'REEL2', NBDLIB * ( 4 + MXROOT*2 ), MNV )
      MNV0 = MNV  + MOREE2 * NBDLIB
      MNV1 = MNV0 + MOREE2 * NBDLIB
      MNW  = MNV1 + MOREE2 * NBDLIB
      MNWW = MNW  + MOREE2 * NBDLIB
      MNVV = MNWW + MOREE2 * NBDLIB * MXROOT
C
C     LES VALEURS PROPRES ET BORNES D'ERREUR
      MNEIGV = 0
      CALL TNMCDC( 'REEL2', MXROOT+2, MNEIGV )
C
C     LE NOMBRE D'ITERATIONS INVERSES  POUR CHAQUE VALEUR PROPRE
      MNNINV = 0
      CALL TNMCDC( 'ENTIER', MXROOT, MNNINV )
C
C     METHODE DES ITERATIONS INVERSES AVEC TRANSLATION
C     ------------------------------------------------
      CALL ITEIN1( NBROOT,      MXROOT,    NBDLIB,
     %             MCN(MNMUKG), KG, NCODSK,
     %             MCN(MNMUMG), MG, NCODSM,
     %             MCN(MNV0),   MCN(MNV1), MCN(MNV), MCN(MNW),
     %             MCN(MNVV),   MCN(MNWW), MCN(MNEIGV),
     %             MCN(MNNINV), MOTSRG, RG,
     %             IERR )
C
C     ====================================================
C     ADRESSAGE INITIALISATION DU TMS VECTEUR"VALEURPROPRE
C     ====================================================
      IF( NOMPB(1:4) .EQ. 'THER' ) THEN
         NOMVEC = 'VECTEUR"VALEURPROPRE'
      ELSE IF( NOMPB(1:4) .EQ. 'ELAS' ) THEN
         NOMVEC = 'VECTEUR"MODEPROPRE'
      ENDIF
      CALL LXTSOU( NTLXOB, NOMVEC, NTVVPR, MNVVPR )
      IF( NTVVPR .GT. 0 ) THEN
C        LE VECTEUR EST DETRUIT POUR ETRE REDECLARE
         CALL LXTSDS( NTLXOB, NOMVEC )
      ENDIF
      L =  WECTEU + NBROOT * NTDL * MOREE2 + NBROOT
      CALL LXTNDC( NTLXOB, NOMVEC, 'MOTS', L )
      CALL LXTSOU( NTLXOB, NOMVEC, NTVVPR, MNVVPR )
C     NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR PROPRE
      MCN( MNVVPR + WBCOVE ) = NTDL
C     NOMBRE DE VECTEURS
      MCN( MNVVPR + WBVECT ) = NBROOT
C     NOMBRE DE VALEURS PROPRES REELLE SIMPLE PRECISION
      MCN( MNVVPR + WBCPIN ) = NBROOT
C
C     AJOUT DES DEGRES DE LIBERTE FIXES A ZERO S'IL EN EXISTE
C     DANS LES VECTEURS PROPRES CALCULES
      IF( MNDLIB .LE. 0 ) THEN
         MNDLB = 1
      ELSE
         MNDLB = MNDLIB
      ENDIF
      CALL CPSIVV( NBROOT, NTDL, NBDLIB, MCN(MNDLB),
     %             NBDLFX, MCN(MNVDLX),
     %             MCN(MNVV), MCN(MNVVPR+WECTEU) )
C
C     COPIE DES MXROOT VALEURS PROPRES EN SIMPLE PRECISION
      MNR = MNVVPR + WECTEU + MOREE2*NTDL*NBROOT
      MND = (MNEIGV+1) / MOREE2
      DO 799 I=1,NBROOT
C        TRANSLATION INVERSE DES VALEURS PROPRES
         RMCN(MNR) = REAL( DMCN(MND) - TETA )
         MNR = MNR + 1
         MND = MND + 1
 799  CONTINUE
C     LA DATE
      CALL ECDATE( MCN(MNVVPR) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVVPR + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
C     DESTRUCTION DES TABLEAUX MC INUTILES
      CALL TNMCDS( 'REEL2',  NBDLIB * ( 4 + MXROOT*2 ), MNV )
      CALL TNMCDS( 'REEL2',  MXROOT+2, MNEIGV )
      CALL TNMCDS( 'ENTIER', MXROOT,   MNNINV )
C
      RETURN
      END
