      SUBROUTINE MAPRCRGC( NTDL,   NIVEAU, MNNDFX,
     %                     NCODSV, MNPTDG, MNLPCO, AG,
     %                     MNLPLC, MNLPCC, MNLPLU, LOLPCC, MNAGC,
     %                     COMP,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT:     CALCUL DE LA MATRICE DE PRECONDITIONNEMENT FACTORISATION
C ----     INCOMPLETE DE CROUT DE LA MATRICE [AG] EN STOCKAGE MORSE
C
C
C ENTREES:
C --------
C NTDL   : NOMBRE DE LIGNES ET COLONNES DE LA MATRICE AG(NTDL,NTDL)
C NIVEAU : PARAMETRE DE FACTORISATION INCOMPLETE
C MNNDFX : ADRESSE MCN DU TABLEAU NDFX(I)=0 SI I DL LIBRE, 1 SI I DL FIXE
C NCODSV : MODE DE STOCKAGE DE LA MATRICE
C          1 SI SYMETRIQUE NON DIAGONALE
C         -1 SI NON SYMETRIQUE
C MNPTDG : ADRESSE MCN DU POINTEUR LPLIGN sur AG
C MNLPCO : ADRESSE MCN DU POINTEUR LPCOLO sur AG
C AG     : COEFFICIENTS NON NULS DE LA MATRICE
C
C SORTIES:
C --------
C MNLPLC : ADRESSE MCN DU POINTEUR LPLIGN sur AGC
C MNLPCC : ADRESSE MCN DU POINTEUR LPCOLO sur AGC
C MNLPLU : ADRESSE MCN DU POINTEUR LPDILU sur AGC
C          =0 SI MATRICE SYMETRIQUE
C          >0 SI MATRICE NON SYMETRIQUE
C LOLPCC : NOMBRE DE COEFFICIENTS DE LA MATRICE DE PRECONDITIONNEMENT
C MNAGC  : ADRESSE MCN DE LA MATRICE DE PRECONDITIONNEMENT
C COMP   : LOGIQUE INDICATEUR DE FACTORISATION INCOMPLETE CORRECT OU NON
C IERR   : CODE D'ERREUR >0 SI ERREUR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2010
C23456---------------------------------------------------------------012
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1), RMCN(1), DMCN(1))
      DOUBLE PRECISION  AG(1:*)
      LOGICAL           COMP
C
C     CALCUL DU SQUELETTE (POINTEURS DIAGONALE ET COLONNES)
C     DE LA MATRICE DE PRECONDITIONNEMENT DU GRADIENT CONJUGUE
      CALL CALPNT( NTDL,   NIVEAU, NCODSV, MNPTDG, MNLPCO,
     %             MNLPLC, MNLPCC, MNLPLU, COMP,   IERR )
C
C     VERIFICATION DE LA FACTORISATION
      LOLPCC = MCN( MNLPLC + NTDL )
      IF( IERR .NE. 0 ) THEN
         NBLGRC(NRERR) = 2
         IF( LANGAG .EQ. 0 ) THEN
           KERR(1)='PROBLEME dans la FACTORISATION INCOMPLETE de NIVEAU'
     %             // KERR(MXLGER)(1:2)
           KERR(2) = 'ABANDON de la METHODE du GRADIENT CONJUGUE'
         ELSE
           KERR(1)='PROBLEM of INCOMPLETE FACTORIZATION of LEVEL '
     %               // KERR(MXLGER)(1:2)
           KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
         ENDIF
         CALL LEREUR
         IERR = 2
         GOTO 9999
      ENDIF
C
C     DECLARATION INITIALISATION DE LA MATRICE MORSE DE CONDITIONNEMENT
C     TEST DE LA PLACE MEMOIRE DISPONIBLE
      CALL TNMCMX( 'REEL2', MAXVAR )
      IF( MAXVAR .LT. LOLPCC ) THEN
C        PLACE MEMOIRE INSUFFISANTE
         NBLGRC(NRERR) = 2
         WRITE(KERR(MXLGER)(1:2),'(I2)') NIVEAU
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'MAPRCRGC: PLACE MEMOIRE INSUFFISANTE'
            KERR(2) = 'DIMINUEZ la VALEUR du NIVEAU'
     %              // KERR(MXLGER)(1:2)
         ELSE
            KERR(1) = 'MAPRCRGC: NOT ENOUGH MEMORY'
            KERR(2) = 'DIMINISH the LEVEL VALUE'
     %              // KERR(MXLGER)(1:2)
         ENDIF
         CALL LEREUR
         IERR = 2
         GOTO 9999
      ENDIF
C
C     DECLARATION DE LA MATRICE DE PRECONDITIONNEMENT
      CALL TNMCDC( 'REEL2', LOLPCC, MNAGC )
      IF( MNAGC .LE. 0 ) GOTO 9999
C
C     AFFICHAGE
      NBLGRC(NRERR) = 1
      WRITE(KERR(MXLGER)(1:2),'(I2)') NIVEAU
      IF( LANGAG .EQ. 0 ) THEN
         KERR(1) = 'CROUT FACTORISATION INCOMPLETE AVEC'
     %          // KERR(MXLGER)(1:2) // ' NIVEAUX'
      ELSE
         KERR(1) = 'INCOMPLETE CROUT FACTORIZATION by'
     %          // KERR(MXLGER)(1:2) // ' LEVELS'
      ENDIF
      CALL LERESU
C
C     CONSTRUCTION DE LA MATRICE DE PRECONDITIONNEMENT AGC
      CALL INCRCO( NTDL,        MCN(MNNDFX),
     &             MCN(MNPTDG), MCN(MNLPCO), AG,
     &             MCN(MNLPLC), MCN(MNLPCC), MCN(MNAGC),
     &             IERR )
C
C     FACTORISATION INCOMPLETE DE CROUT L D tL
      CALL INCRFA( NTDL, MCN(MNLPLC), MCN(MNLPCC), MCN(MNAGC), IERR )
C
C     VERIFICATION DE LA STABILITE DE LA FACTORISATION INCOMPLETE
      IF( IERR .GT. 0 ) THEN
C        LA FACTORISATION EST INSTABLE : ABANDON DES CALCULS
         WRITE(KERR(MXLGER)(1:2),'(I2)') NIVEAU
         NBLGRC(NRERR) = 2
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'FACTORISATION INSTABLE AU NIVEAU '
     &           // KERR(MXLGER)(1:2)
            KERR(2) = 'ABANDON DE LA METHODE DU GRADIENT CONJUGUE'
         ELSE
            KERR(1)='UNSTABLE INCOMPLETE FACTORIZATION at LEVEL '
     %           // KERR(MXLGER)(1:2)
            KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
         ENDIF
         CALL LEREUR
         IERR = 2
         GO TO 9999
      ENDIF
C
 9999 RETURN
      END
