      SUBROUTINE REDLIB( NBDLFX, NODLFX, NTDL,   NBDLIB, MNDLIB )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RENUMEROTER LES DEGRES DE LIBERTE LIBRES DE 1 A NBDLIB
C -----    DLIB(I) = NUMERO DU DL LIBRE
C                  -(INDICE DANS NODLFX) SI LE DL EST BLOQUE
C
C ENTREES:
C --------
C NBDLFX : NOMBRE DE DEGRES DE LIBERTE BLOQUES
C NODLFX : NUMERO DE 1 A NTDL DES NODLFX DEGRES DE LIBERTE BLOQUES
C NTDL   : NOMBRE TOTAL DE DL BLOQUES+LIBRES
C
C SORTIES:
C --------
C NBDLIB : NOMBRE DE DEGRES DE LIBERTE LIBRES
C MNDLIB : ADRESSE MCN DU TABLEAU NODLIB(1:NBDLFX)
C          MCN(MNDLIB-1+I) = NUMERO DE 1 A NBDLIB DU DL LIBRE I (1 A NTDL)
C                          -(INDICE DANS NODLFX) DU DL I BLOQUE
C          =0 ADRESSE SI NBDLFX=0 C-A-D PAS DE DL BLOQUES et NTDL=NBDLIB
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS        AOUT 1998
C2345X7..............................................................012
      include"./incl/langue.inc"
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      INTEGER           NODLFX(1:NBDLFX)
C
C     VERIFICATION
      MNDLIB = 0
      IF( NBDLFX .LE. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,*) 'REDLIB: PAS DE DEGRE DE LIBERTE FIXE'
         ELSE
            WRITE(IMPRIM,*) 'REDLIB: NO IMPOSED DEGREE OF FREEDOM'
         ENDIF
         NBDLIB = NTDL
         RETURN
      ENDIF
C
C     ADRESSAGE MCN DU TABLEAU DLIB
      CALL TNMCDC( 'ENTIER', NTDL, MNDLIB )
      CALL AZEROI( NTDL, MCN(MNDLIB) )
C
C     BOUCLE SUR LES DEGRES DE LIBERTE BLOQUES RANGES DANS NODLFX
      DO 10 I=1,NBDLFX
         N = NODLFX(I)
         MCN( MNDLIB-1+N) = -I
 10   CONTINUE
C
C     RENUMEROTATION DES DL LIBRES
      NBDLIB = 0
      DO 20 I=1,NTDL
         IF( MCN( MNDLIB-1+I ) .EQ. 0 ) THEN
C           UN DL LIBRE DE PLUS
            NBDLIB = NBDLIB + 1
            MCN( MNDLIB-1+I ) = NBDLIB
         ENDIF
 20   CONTINUE
C
CCC      WRITE(IMPRIM,*) 'REDLIB: NOMBRE TOTAL DE DL  =', NTDL
CCC      WRITE(IMPRIM,*) 'REDLIB: NOMBRE DE DL FIXES  =', NBDLFX
CCC      WRITE(IMPRIM,*) 'REDLIB: NOMBRE DE DL LIBRES =', NBDLIB
C
      RETURN
      END
