      SUBROUTINE SDRES5(TABLE,TRACE,NBNOIN,
     &                  NBNOSD,NUNOIN,NUNOSD,NBOBNO,NBINCO)
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : GESTION DU TABLEAU TABLE SUR L'INTERFACE : MOYENNE DES
C ----- VALEURS DE PART ET D'AUTRE DE L'INTERFACE

C ENTREES :
C ---------
C NBNOIN : NOMBRE TOTAL DE NOEUDS DE L'INTERFACE
C NBNOSD : NOMBRE DE NOEUDS DE L'INTERFACE
C NUNOIN : LES NUMEROS DE CES NOEUDS DANS L'INTERFACE
C NUNOSD : LES NUMEROS DE CES NOEUDS DANS LE SOUS-DOMAINE
C NBOBNO : LE NOMBRE DE SOUS-DOMAINES CONTENANT CE NOEUD
C NBINCO : LE  NOMBRE D'INCONNUES EN CHAQUE NOEUD
C TABLE  : LE TABLEAU A PONDERER SUR L'INTERFACE
C
C SORTIES :
C ---------
C TRACE  : LA TRACE PONDEREE DU  TABLEAU TABLE SUR L'INTERFACE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PASCAL JOLY     ANALYSE NUMERIQUE UPMC PARIS  MAI 1990
C23456---------------------------------------------------------------012
      DIMENSION NUNOIN(NBNOSD),NUNOSD(NBNOSD),NBOBNO(NBNOIN)
      DOUBLE PRECISION TABLE(NTDL,NDSM),TRACE(NBNOIN*NBINCO,NDSM)
      COMMON / SOUSDO / NORESO,NTDL,NDSM,NDIM,NPIMAX

C     LE TRANSFERT
C     ============
      DO NB = 1 , NBNOSD
         NUNOK = NBINCO * ( NUNOSD(NB) - 1 )
         NBK   = NBINCO * ( NUNOIN(NB) - 1 )
         DO K  = 1 , NBINCO
            DO NS = 1 , NDSM
               TRACE(NBK+K,NS) = TRACE(NBK+K,NS)
     &                         + TABLE(NUNOK+K,NS) / NBOBNO(NUNOIN(NB))
            ENDDO
         ENDDO
      ENDDO

      RETURN
      END
