      SUBROUTINE SDRES4(TRACE,TABLE,NBNOIN,
     &                  NBNOSD,NUNOIN,NUNOSD,NBINCO)
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : RELEVEMENT DU TABLEAU TABLE SUR LE SOUS-DOMAINE
C ----- A PARTIR DE SA TRACE TRACE SUR L'INTERFACE

C ENTREES :
C ---------
C NBNOIN : NOMBRE TOTAL DE NOEUDS DE L'INTERFACE
C NBNOSD : NOMBRE DE NOEUDS DU SOUS-DOMAINE SUR L'INTERFACE
C NUNOIN : LES NUMEROS DE CES NOEUDS DANS L'INTERFACE
C NUNOSD : LES NUMEROS DE CES NOEUDS DANS LE SOUS-DOMAINE
C NBINCO : LE  NOMBRE D'INCONNUES EN CHAQUE NOEUD
C TRACE  : LA TRACE DU TABLEAU TABLE SUR L'INTERFACE

C SORTIES :
C ---------
C TABLE  : LE TABLEAU TABLE DANS LE SOUS-DOMAINE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PASCAL JOLY     ANALYSE NUMERIQUE UPMC PARIS  MAI 1990
C23456---------------------------------------------------------------012
      DIMENSION NUNOIN(NBNOSD),NUNOSD(NBNOSD)
      DOUBLE PRECISION  TRACE(NBNOIN*NBINCO,NDSM),TABLE(NTDL,NDSM)
      COMMON / SOUSDO / NORESO,NTDL,NDSM,NDIM,NPIMAX

C     LE TRANSFERT
C     ============
      DO NB = 1 , NBNOSD
         NUNOK = NBINCO * ( NUNOSD(NB) - 1 )
         NBK   = NBINCO * ( NUNOIN(NB) - 1 )
         DO K  = 1 , NBINCO
            DO NS = 1 , NDSM
               TABLE(NUNOK+K,NS) = TRACE(NBK+K,NS)
            ENDDO
         ENDDO
      ENDDO

      RETURN
      END
