      SUBROUTINE SSPAC2( NBREPRI, NBDLIB, NROO, EIGMIN, EIGMAX,
     %                   MOTSRG, RG,
     %                   NCODSA, MUA,  A,
     %                   NCODSB, MUB,  B,
     %                   NCVALP, NBVALP, VALPR, VALPES,
     %                   NBVAOU, IFACTO, TETATO )
C +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C  BUT :   LOCALISER ENTRE EIGMIN EIGMAX LES VALEURS PROPRES OUBLIEES
C  -----
C          CF LE RAPPORT SUR LE CALCUL DES VALEURS VECTEURS PROPRES
C
C ENTREES:
C --------
C NBREPRI: NOMBRE D'APPELS DE SSPAC2
C NBDLIB : NOMBRE DE COMPOSANTES DE CHACUN DES VECTEURS PROPRES
C          NOMBRE DE LIGNES ET COLONNES DES MATRICES A ET B
C NCVALP : NOMBRE DE VALEURS PROPRES DECLAREES EN ENTREE
C NBVALP : NOMBRE DE VALEURS PROPRES CALCULEES EN ENTREE
C NROO   : NROO(1) NOMBRE DE VALEURS PROPRES INFERIEURES A EIGMAX
C          NROO(2) NOMBRE DE VALEURS PROPRES INFERIEURES A EIGMIN
C EIGMIN : BORNE MINIMALE DES VALEURS PROPRES A CALCULER
C EIGMAX : BORNE MAXIMALE DES VALEURS PROPRES A CALCULER
C EPS    : SEUIL DE PRECISION DES FACTORISATIONS DE A OU B
C
C MOTSRG : NOMBRE DE MOTS DE LA MATRICE RG
C RG     : MATRICE SAUVEGARDE RG NON FACTORISEE
C NCODSA : CODE DE STOCKAGE DE LA MATRICE PROFIL A
C MUA    : POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE A
C NCODSB : CODE DE STOCKAGE DE LA MATRICE PROFIL B
C MUB    : POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE B
C B      : MATRICE PROFIL REELLE DOUBLE PRECISION
C
C VALPR  : LES NBVALP VALEURS PROPRES DEJA CALCULEES
C
C MODIFIES:
C ---------
C VALPES : ESTIMATION DE LA VALEUR PROPRE SUIVANT LA DERNIERE CONVERGEE
C NBVAOU : NOMBRE DE VALEURS PROPRES OUBLIEES A CALCULER
C IFACTO : 0 LA FACTORISATION DE A EST A FAIRE.1 SINON
C TETATO : TRANSLATION EFFECTUEE ( A => A - TETATO * B )
C A      : MATRICE PROFIL REELLE DOUBLE PRECISION
C          EN ENTREE FACTORISEE PRECEDENTE DE A
C          EN SORTIE FACTORISEE DE A - TETATO * B
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL ANALYSE NUMERIQUE UPMC PARIS    AOUT 2003
C23456---------------------------------------------------------------012
      include"./incl/langue.inc"
      include"./incl/epsvvp.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      DOUBLE PRECISION  RG(*),A(*),B(*),VALPR(NCVALP)
      DOUBLE PRECISION  EIGMIN,EIGMAX,V,DETA,TETATO,VALPES
      INTEGER           NROO(2),MUB(*),MUA(*)
C
C     LE NOMBRE DE TRANSLATIONS DE LA MATRICE B
      NBTRANSL = 0
C
C     LA NOUVELLE TRANSLATION DE A - TETATO B
ccc 5    TETATO = ( TETATO + EIGMAX )/2
ccc      essai acceleration de la reprise avec valpes   le 30 juin 2008
C
 5    NBTRANSL = NBTRANSL + 1
      IF( NBTRANSL .GT. 4 ) GOTO 9000
C     4 TRANSLATIONS AU PLUS SONT PERMISES CAR LE COUT EST TRES IMPORTANT
C
      IF( NBTRANSL .EQ. 1 .AND. VALPES .LT. EIGMAX ) THEN
         TETATO = VALPES
      ELSE
         TETATO = ( TETATO + EIGMAX ) / 2
      ENDIF
      TETATO = MIN( TETATO, EIGMAX )
      IF( NBTRANSL .EQ. 4 ) TETATO = EIGMAX
      WRITE(IMPRIM,*) 'sspac2: TETATO avant',TETATI,' apres',TETATO,
     %   ' EIGMAX=',EIGMAX
      VALPES = TETATO
C
C     CALCUL DU NOMBRE NVALPI DE VALEURS PROPRES INFERIEURES A TETATO
C     METHODE DU RECENSEMENT DES COEFFICIENTS DIAGONAUX NEGATIFS
      CALL NVALPD( NBDLIB, TETATO, EPS, 1.01D0,
     +             MOTSRG, RG,
     +             NCODSA, MUA, A, NCODSB, MUB, B,
     +             N1, NBHOMO, DETA )
C     N1=NOMBRE DE VALEURS PROPRES AVANT TETATO
      IFACTO = 1
C
C     NBVAOU NOMBRE DE VALEURS PROPRES ENTRE EIGMIN ET TETATO
      NBVAOU = 0
      DO 10 I=1,NBVALP
         V = VALPR(I)
         IF( EIGMIN .LE. V .AND. V .LE. TETATO ) NBVAOU=NBVAOU+1
 10   CONTINUE
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) NBVAOU,' VALEURS PROPRES CONVERGEES ENTRE',
     %                   EIGMIN,' ET',TETATO
      ELSE
         WRITE(IMPRIM,*) NBVAOU,' CONVERGED EIGENVALUES from',EIGMIN,
     %' to',TETATO
      ENDIF
C
C     NBVAOU NOMBRE DE VALEURS PROPRES OUBLIEES ENTRE EIGMIN ET TETATO
      NBVAOU = N1 - ( NROO(2) + NBVAOU )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) NBVAOU,' VALEURS PROPRES OUBLIEES  ENTRE',
     %                   EIGMIN,' ET',TETATO
      ELSE
         WRITE(IMPRIM,*) NBVAOU,' FORGOTTEN EIGENVALUES from',
     %                   EIGMIN,' to',TETATO
      ENDIF
C
      IF( NBVAOU .EQ. 0 ) GOTO 5
C
C     UNE REPRISE DE PLUS
 9000 NBREPRI = NBREPRI + 1
      RETURN
      END
