      SUBROUTINE TAPOBA( NBTYEL, MNNPEF, SPTAEL,
     %                   MNTPOB, NBDLMX, MOAUX,  NBTTEF, NOAXIS, NCODMG,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LES TABLEAUX POBA NECESSAIRES A LA CONSTRUCTION
C -----    DES TABLEAUX ELEMENTAIRES DU PROBLEME THERMIQUE OU ELASTICITE
C
C ENTREES:
C --------
C NBTYEL : NOMBRE ACTUEL DE TYPES D'EF DU MAILLAGE    DE L'OBJET
C MNNPEF : ADRESSE MCN DES ADRESSES MCN DES TMS NPEF" DE L'OBJET
C SPTAEL : NOM DU SOUS-PROGRAMME DE CALCUL DES CARACTERISTIQUES
C          DES TABLEAUX ELEMENTAIRES
C          EN THERMIQUE  : ETTAEL
C          EN ELASTICITE : EETAEL
C
C SORTIES :
C ---------
C MNTPOB : ADRESSE MCN DU TABLEAU POINTEUR SUR LES TABLEAUX POBA DES EF
C NBDLMX : NOMBRE MAXIMAL DE DL D'UN EF EN THERMIQUE ou ELASTICITE ou ...
C MOAUX  : NOMBRE MAXIMAL DE MOTS POUR LES TABLEAUX AUXILIAIRES DES EF
C NBTTEF : NOMBRE TOTAL DES EF DU MAILLAGE DE L'OBJET
C NOAXIS : 0 SI PROBLEME AVEC EF NON AXISYMETRIQUE
C          1 SI PROBLEME AVEC EF     AXISYMETRIQUE
C NCODMG : 1 SI MATRICE GLOBALE DE MASSE SYMETRIQUE
C          0 SI MATRICE GLOBALE DE MASSE DIAGONALE
C         -1 SI MATRICE GLOBALE DE MASSE NON SYMETRIQUE
C IERR   : 0 SI PAS D'ERREUR D'EXECUTION, NON NUL SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE UPMC PARIS    FEVRIER 1999
C2345X7..............................................................012
      PARAMETER     (MOPAGE=512)
      include"./incl/homdir.inc"
      include"./incl/msvaau.inc"
      include"./incl/donthe.inc"
      include"./incl/ponoel.inc"
      include"./incl/gsmenu.inc"
      include"./incl/a___npef.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / ELFINI / NELFI(512)
      EXTERNAL          SPTAEL
      INTEGER           NOMTAB(5)
      CHARACTER*4       NOMELE(2)
      CHARACTER*160     KNOM
C
      IERR   = 0
      NBDLMX = 0
      MOAUX  = 1
      NOAXIS = 0
      NBTTEF = 0
      NCODMG = -10
C
C     LES TABLEAUX POBA NECESSAIRES AUX TABLEAUX ELEMENTAIRES
C     =======================================================
C     OUVERTURE DU FICHIER DIRECT POBA SUPPORT DE TABLEAUX ELEMENTAIRES
      CALL TRUNIT( NFPOBA )
      KNOM = HOMDIR // '/pp/pxyz'
      OPEN( UNIT=NFPOBA, ERR=9999, STATUS='OLD',
     %      FILE=KNOM, ACCESS='DIRECT', FORM='UNFORMATTED',
     %      RECL=MOPAGE*NBCHMO )
C     LECTURE DE LA PREMIERE PAGE
      READ (UNIT=NFPOBA,REC=1) NELFI
C
C     DECLARATION DU TMC DES ADRESSES MCN DES TABLEAUX POBA DES TYPES D'EF
      MNTPOB = 0
      CALL TNMCDC( 'ENTIER', NBTYEL*MXPOBA, MNTPOB )
C
C     MISE DANS MCN DES TABLEAUX POBA NECESSAIRES EN THERMIQUE
      DO 20 NOTYEL=1,NBTYEL
C
C        L'ADRESSE DU TABLEAU NPEF"NOTYEL
         MNELE  = MCN( MNNPEF - 1 + NOTYEL )
C        LE NUMERO DU TYPE DE L'ELEMENT FINI
         NUTYEL = MCN( MNELE + WUTYEL )
C
C        LE NOMBRE D'ELEMENTS FINIS DE CE TYPE
         NBELEM = MCN( MNELE + WBELEM )
C        LE NOMBRE TOTAL D'EF DE L'OBJET
         NBTTEF = NBTTEF + NBELEM
C
         IF( NUTYEL .LE. 4 ) THEN
C           EF AXISYMETRIQUE
            NOAXIS = 1
         ENDIF
C
C        LES CARACTERISTIQUES GEOMETRIQUES DE L'ELEMENT FINI
         CALL ELNUNM( NUTYEL, NOMELE )
         CALL ELTYCA( NUTYEL )
C
C        LES CARACTERISTIQUES DES TABLEAUX DE L'ELEMENT FINI
         CALL SPTAEL( NUTYEL, 1,
     %                NBDL,   NCODEM, NTPOBA, NOMTAB, MOTAUX )
C
C        NBDL      : NOMBRE DE DL DE L ELEMENT FINI OU NOMBRE DE POLYNOMES
C        NTPOBA    : NOMBRE DE TABLEAUX A LIRE SUR LE FICHIER POBA
C        NOMTAB(J) : NOM DU J-EME TABLEAU DE POBA A LIRE 1<=J<=NTPOBA
C        MOTAUX    : NOMBRE DE MOTS AUXILIAIRES NECESSAIRES A L ELEMENT
C
C        CODE DE STOCKAGE DE LA MATRICE GLOBALE DE MASSE
         NCODMG = MAX( NCODMG, NCODEM )
C
C        DECLARATION ET LECTURE DES TABLEAUX DE POBA DE CE TYPE D'EF
         IF( NTPOBA .GT. 0 ) THEN
            DO 10 J=1,NTPOBA
               CALL FINDEL(NOMTAB(J),MCN(MNTPOB-1+(NOTYEL-1)*MXPOBA+J),
     &                     NFPOBA,MOPAGE)
 10         CONTINUE
         ENDIF
C
C        BILAN DES TABLEAUX AUXILIAIRES ET ELEMENTAIRES
         IF( MOAUX  .LT. MOTAUX ) MOAUX  = MOTAUX
         IF( NBDLMX .LT. NBDL   ) NBDLMX = NBDL
 20   CONTINUE
C
C     FERMETURE DU FICHIER POBA
      CLOSE( UNIT=NFPOBA )
      RETURN
C
C     ERREUR A L'OUVERTURE DU FICHIER POBA
 9999 NBLGRC(NRERR) = 2
      KERR(1) = 'OUVERTURE IMPOSSIBLE DU FICHIER POBA: '
      KERR(2) = KNOM( 1:NUDCNB(KNOM) )
      CALL LEREUR
      IERR = 1
C
      RETURN
      END
