      SUBROUTINE AFCHAI( NLD , NCD , NLF , NCF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : AFFICHER UNE CHAINE DE CARACTERES DEBUTANT EN (NLD,NCD)
C ----- ET FINISSANT EN (NLF,NCF) DU TABLEAU KTD
C
C ENTREES :
C ---------
C NLD, NCD: POSITION DANS KTD DE LA PREMIERE ' DE LA CHAINE
C NLF, NCF: POSITION DANS KTD DE LA DERNIERE ' DE LA CHAINE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS   SEPTEMBRE 1988
C23456---------------------------------------------------------------012
      include"./incl/td.inc"
C
C     LA LIGNE EST BUFFERISEE A L'AIDE DU POINTEUR LCLIGN DERNIER
C     CARACTERE ENTRE DANS LA LIGNE
      IF( IMPRES*NOMUET .LE. 0 ) RETURN
C
      IF( NLD .LE. 0 ) RETURN
C
      IF( NLD .EQ. NLF ) THEN
C        TOUTE LA CHAINE EST SUR LA MEME LIGNE DE KTD
         NBCA = NCF - NCD + 2
         IF( NBCA .LE. 1 ) RETURN
C        LE NOMBRE DE CARACTERES RESTANT DANS LA LIGNE D'AFFICHAGE
         NBCL = NCLIGN - LCLIGN
         IF( NBCL .LT. NBCA ) THEN
C           ON AFFICHE LA LIGNE
            CALL AFLIGN
         ENDIF
C        STOCKAGE DANS KLIGNE DES NBCA CARACTERES
         KLIGNE(LCLIGN+1:LCLIGN+NBCA) = ' ' // KTD(NLD)(NCD:NCF)
         LCLIGN = LCLIGN + NBCA
         RETURN
      ENDIF
C
C     LA CHAINE S'ETEND SUR PLUS D'UNE LIGNE DE KTD
C     LE NOMBRE DE CARACTERES DE LA CHAINE
C     LES ' INITIAL ET FINAL NE SONT PAS DECOMPTES
      NBCA = NCF + ( NLF - NLD ) * NCKTD - NCD + 1
      NBCL = NCLIGN - LCLIGN
      IF( NBCL .GE. NBCA ) THEN
C        TOUTE LA CHAINE TIENT SUR LA KLIGNE
         KLIGNE(LCLIGN+1:LCLIGN+NBCA) = ' ' //
     %      KTD(NLD)(NCD:NCKTD) // KTD(NLD+1)(1:NCF)
         LCLIGN = LCLIGN + NBCA
         RETURN
      ENDIF
C
C     IL FAUT PLUS D'UNE KLIGNE . PASSAGE AU DEBUT D'UNE KLIGNE
      CALL AFLIGN
C
C     REMPLISSAGE DES LIGNES
      NBL = NBCA / NCLIGN
      NL0 = NLD
      NC0 = NCD
      DO 10 I=1,NBL
         KLIGNE(1:NCLIGN) = KTD(NL0)(NC0:NCKTD)
         NL0 = NL0 + 1
         IF( NC0 .GT. 1 ) THEN
            KLIGNE(NCLIGN+2-NC0:NCLIGN) = KTD(NL0)(1:NC0-1)
         ENDIF
         LCLIGN = NCLIGN
         CALL AFLIGN
 10   CONTINUE
C
C     NOMBRE DE CARACTERES RESTANT
      NBCA = NBCA - NCKTD * NBL
      IF( NBCA .GT. 0 ) THEN
         IF( NL0 .EQ. NLF ) THEN
            KLIGNE(1:NCLIGN) = KTD(NL0)(NC0:NCF)
         ELSE
            KLIGNE(1:NCLIGN) = KTD(NL0)(NC0:NCKTD)
            KLIGNE(NCLIGN+2-NC0:NBCA) = KTD(NLF)(1:NCF)
         ENDIF
         LCLIGN = NBCA
      ENDIF
      END
