      SUBROUTINE AJARCH( NS1,    NS2,    L1ARCH,
     %                   MXARCH, NBARCH, N1ARCH, NSARCH, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUTER UNE NOUVELLE ARETE DE SOMMETS NS1 NS2 EN TETE DE
C -----    LA LISTE DES ARETES CHAINEES A PARTIR DE L1ARCH DANS NSARCH
C
C ENTREES:
C --------
C NS1,NS2: NUMEROS DANS XYZST DES 2 SOMMETS DE L'ARETE
C L1ARCH : NUMERO DANS NSARCH DE LA PREMIERE ARETE DU CHAINAGE
C MXARCH : NOMBRE MAXIMAL D'ARETES DECLARABLES DANS NSARCH
C
C MODIFIES :
C ----------
C L1ARCH : NUMERO DANS NSARCH DE LA PREMIERE ARETE DU CHAINAGE OU
C          CETTE NOUVELLE ARETE DOIT ETRE CHAINEE
C NBARCH : NOMBRE D'ARETES CHAINEES DANS NSARCH
C N1ARCH : NUMERO DANS NSARCH DE LA PREMIERE ARETE VIDE
C IERR   : 0 SI PAS D'ERREUR DETECTEE
C          1 SATURATION DU TABLEAU NSARCH
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS     JANVIER 1995
C2345X7..............................................................012
      include"./incl/gsmenu.inc"
      INTEGER        NSARCH(4,MXARCH)
C
C     PAS D'ARETE SI LES 2 SOMMETS SONT IDENTIQUES
      IF( NS1 .EQ. NS2 ) RETURN
C
C     CHAINAGE SIMPLE DE CETTE ARETE DANS SA LIGNE
      IF( N1ARCH .LE. 0 ) THEN
C        SATURATION DU TABLEAU NSARCH
         NBLGRC(NRERR) = 1
         KERR(1) = 'AJARCH: SATURATION DU TABLEAU NSARCH'
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C     LA NOUVELLE ARETE
      NA = N1ARCH
C     LA NOUVELLE ARETE VIDE
      N1ARCH = NSARCH(4,N1ARCH)
C
C     LA NOUVELLE ARETE DEVIENT TETE DE CHAINAGE DE SA LIGNE
      NBARCH = NBARCH + 1
C
C     LE NUMERO DES 2 SOMMETS DANS XYZST
      NSARCH(1,NA) = NS1
      NSARCH(2,NA) = NS2
C
C     PAS D'ARETE PRECEDENTE
      NSARCH(3,NA) = 0
c
C     L'ARETE SUIVANTE EST L'ANCIENNE TETE
      L = L1ARCH
      IF( L .GT. 0 ) THEN
C        IL EXISTE UNE ARETE DANS LA LISTE ELLE EST CHAINEE A LA NOUVELLE
         NSARCH(3,L) = NA
      ENDIF
      NSARCH(4,NA) = L
C
C     LA NOUVELLE TETE DE LISTE DE CETTE LIGNE
      L1ARCH = NA
      END
