      SUBROUTINE AJNVTR( NS1,    NS2,    NS3,    NOSURF,
     %                   MXNVTR, NBNVTR, NSNVTR, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUTER UN NOUVEAU TRIANGLE DE SOMMETS NS1 NS2 NS3
C -----    DANS LE TABLEAU NSNVTR
C
C ENTREES:
C --------
C NS1,NS2,NS3: NUMEROS DANS XYZST DES 3 SOMMETS DU TRIANGLE
C NOSURF : NUMERO DE SURFACE DU TRIANGLE
C MXNVTR : NOMBRE MAXIMAL DE TRIANGLES DECLARABLES
C
C MODIFIES :
C ----------
C NBNVTR : NOMBRE D'ARETES CHAINEES DANS NSNVTR
C NSNVTR : NUMERO DES 3 SOMMETS DU TRIANGLE, NO DE SURFACE
C IERR   : 0 SI PAS D'ERREUR DETECTEE
C          3 SATURATION DU TABLEAU NSNVTR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS     JANVIER 1995
C2345X7..............................................................012
      include"./incl/gsmenu.inc"
      INTEGER        NSNVTR(4,MXNVTR)
C
C     PAS DE TRIANGLE SI 2 SOMMETS SONT IDENTIQUES
      IF( NS1 .EQ. NS2 .OR. NS2 .EQ. NS3 .OR. NS3 .EQ. NS1 ) RETURN
C
C     CHAINAGE SIMPLE DE CETTE ARETE DANS SA LIGNE
      IF( NBNVTR .GE. MXNVTR ) THEN
C        SATURATION DU TABLEAU NSNVTR
         NBLGRC(NRERR) = 1
         KERR(1) = 'AJNVTR: SATURATION DU TABLEAU NSNVTR'
         CALL LEREUR
         IERR = 3
         RETURN
      ENDIF
C
C     LE NOUVEAU TRIANGLE EST EMPILE
      NBNVTR = NBNVTR + 1
C
C     LE NUMERO DES 2 SOMMETS DANS XYZST
      NSNVTR(1,NBNVTR) = NS1
      NSNVTR(2,NBNVTR) = NS2
      NSNVTR(3,NBNVTR) = NS3
C
C     LE NUMERO DE SURFACE DU TRIANGLE
      NSNVTR(4,NBNVTR) = NOSURF
      END
