      SUBROUTINE ANG2TR3R( P1, P2, P3, P4, ANGLE, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCULER L'ANGLE ENTRE LES PLANS DES 2 TRIANGLES P1P2P3 et P1P2P4
C ----- POUR L'ARETE COMMUNE P1P2   VERSION REAL SIMPLE PRECISION

C ENTREES:
C --------
C P1     : XYZ DU SOMMET 1 DU 1-ER  TRIANGLE
C P2     : XYZ DU SOMMET 2 DU 1-ER  TRIANGLE
C P3     : XYZ DU SOMMET 3 DU 1-ER  TRIANGLE
C P4     : XYZ DU SOMMET 4 DU 2-EME TRIANGLE

C SORTIES:
C --------
C ANGLE  : ANGLE ENTRE LES PLANS DES 2 TRIANGLES P1P2P3 et P1P2P4
C          DANS L'INTERVALLE [0, 2Pi] RADIANS
C IERR   : =0 CALCUL CORRECT
C          =1 AU MOINS UN DES 2 TRIANGLES EST DEGENERE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY  Octobre 2017
C23456---------------------------------------------------------------012
      REAL              P1(3), P2(3), P3(3), P4(3)
      DOUBLE PRECISION  ANGLE, VN1(3), VN2(3)
      INTRINSIC         ACOS

C     LE VECTOR NORMAL UNITAIRE A L'ARETE P1 P2 DIRIGE VERS P3
      CALL NORARTRR( P1, P2, P3, VN1, IERR )
      IF( IERR .NE. 0 ) RETURN

C     LE VECTOR NORMAL UNITAIRE A L'ARETE P1 P2 DIRIGE VERS P4
      CALL NORARTRR( P1, P2, P4, VN2, IERR )
      IF( IERR .NE. 0 ) RETURN

C     COSINUS DE L'ANGLE
      ANGLE = VN1(1)*VN2(1) + VN1(2)*VN2(2) + VN1(3)*VN2(3)

C     ANGLE ENTRE [0, PI] RADIANS
      ANGLE = ACOS( ANGLE )

C     P4 EST IL AU DESSUS OU AU DESSOUS DU TRIANGLE ORIENTE P1P2P3?
C     LE VECTOR NORMAL UNITAIRE AU TRIANGLE ORIENTE P1P2P3 FAIT IL
C     UN ANGLE DE PLUS DE 90 DEGRES AVEC LE VECTEUR (P1+P2)/2 P4?
      DO I=1,3
         VN1(I) = P4(I) - ( P1(I) + P2(I) ) / 2
      ENDDO

C     ANGLE ENTRE [-Pi, Pi]
      ANGLE = ANGLE * INVTRIAR( P1, P2, P3, VN1 )
C     INVTRIAR: = 1 SI VN et NORMALE A S1S2S3 ONT UN ANGLE <=90 DEGRES
C               =-1 SI VN et NORMALE A S1S2S3 ONT UN ANGLE > 90 DEGRES

C     ANGLE ENTRE [0, 2Pi]
      IF( ANGLE .LT. 0. ) THEN
         ANGLE = ATAN( 1.0 ) * 8D0 + ANGLE
      ENDIF

      RETURN
      END
