      SUBROUTINE ANGLDIED( XYZ1AR, XYZ2AR, XYZ3TR1, XYZ3TR2,
     %                     ANGDIE, IERR1, IERR2 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER L'ANGLE DIEDRE DES 2 TRIANGLES DEFINIS PAR
C -----    LES XYZ DES 2 SOMMETS DE LEUR ARETE COMMUNE
C          LES XYZ DU 3-EME SOMMET DE CHACUN DES 2 TRIANGLES

C          REMARQUE: LE MOT 'TRIANGLE' PEUT ETRE REMPLACE PAR 'PLAN'

C ENTREES:
C --------
C XYZ1AR : XYZ DU 1-ER  SOMMET DE L'ARETE COMMUNE
C XYZ2AR : XYZ DU 2-EME SOMMET DE L'ARETE COMMUNE
C XYZ3TR1: XYZ DU 3-EME SOMMET DU TRIANGLE 1
C XYZ3TR2: XYZ DU 3-EME SOMMET DU TRIANGLE 2

C SORTIES:
C --------
C ANGDIE : >=0 ANGLE DIEDRE EN DEGRES COMPRIS ENTRE 0. et 180. DEGRES
C          =-777. SI IERR1 ou IERR2 NON NUL
C                 VALEUR POUR ATTIRER L'ATTENTION
C IERR1  : =0 SI NORMALE AU TRIANGLE 1 A ETE CORRECTEMENT CALCULEE
C          =2 SI TRIANGLE 1 REDUIT A UNE ARETE
C IERR2  : =0 SI NORMALE AU TRIANGLE 2 A ETE CORRECTEMENT CALCULEE
C          =2 SI TRIANGLE 2 REDUIT A UNE ARETE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN  Saint Pierre du Perray             Mars 2020
C23456...............................................................012
      REAL   XYZ1AR(3), XYZ2AR(3), XYZ3TR1(3), XYZ3TR2(3), ANGDIE

C     LE COSINUS COMPRIS ENTRE -1. et 1. de l'ANGLE des NORMALES
C     AUX TRIANGLES 1  et 2
      CALL COS2TR( XYZ1AR, XYZ2AR, XYZ3TR1,
     %             XYZ2AR, XYZ1AR, XYZ3TR2,
     %             COS2PL, IERR1, IERR2 )

      IF( IERR1 .NE. 0 ) THEN
         PRINT *,'angldied: ATTENTION: TRIANGLE 1 INCORRECT: IERR1=',
     %           IERR1,' -> ANGLE DIEDRE=-777.0 Pourquoi pas!'
         ANGDIE=-777.0
         GOTO 9999
      ENDIF

      IF( IERR2 .NE. 0 ) THEN
         PRINT *,'angldied: ATTENTION: TRIANGLE 2 INCORRECT: IERR2=',
     %           IERR2,' -> ANGLE DIEDRE=-777.0 Pourquoi pas!'
         ANGDIE=-777.0
         GOTO 9999
      ENDIF

C     ANGLE EN RADIANS ENTRE 0. et Pi
      ANGDIE = ACOS( COS2PL )

C     CONVERSION EN DEGRES
      ANGDIE =  REAL( ANGDIE * 45D0 / ATAN( 1D0 ) )

 9999 RETURN
      END
