      SUBROUTINE CEBOQU( QTEMIN, NOSOTE, PTXYZD, CENTRE, VOLUTE, QUALTE)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DES 3 COORDONNEES DU CENTRE DE LA BOULE CIRCONSCRITE
C -----    AU TETRAEDRE NOSOTE(1:4) ET DU CARRE DE SON RAYON
C          CALCUL DU VOLUME ORIENTE DU TETRAEDRE

C ENTREES:
C --------
C QTEMIN : QUALITE MINIMALE AU DESSOUS DE LAQUELLE UN TETRAEDRE EST JUGE
C          DEGENERE
C NOSOTE : NUMERO DANS PTXYZD DES 4 SOMMETS DU TETRAEDRE
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS

C SORTIE :
C --------
C CENTRE : 3 COORDONNEES DU CENTRE ET CARRE DU RAYON DE LA BOULE CIRCONSCRITE
C          0,0,0,-1 SI TETRAEDRE INCORRECT
C VOLUTE : LE VOLUME DU TETRAEDRE (>0 SI ORIENTE COMME UN REPERE
C                                  =0 SI TETRAEDRE DEGENERE
C                                  <0 SI NON ORIENTE COMME UN REPERE)
C QUALTE : >=0 QUALITE DU TETRAEDRE
C              ALFA * RAYON INSCRIT / LONGUEUR DE LA PLUS LONGUE ARETE
C          <0  SI TETRAEDRE DEGENERE OU MAL ORIENTE a VOLUME NEGATIF
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LABORATOIRE ANALYSE NUMERIQUE PARIS  MAI 1991
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Decembre 2016
C2345X7..............................................................012
      REAL              QTEMIN, QUALTE
      INTEGER           NOSOTE(4)
      DOUBLE PRECISION  PTXYZD(1:4,1:*)
      DOUBLE PRECISION  CENTRE(4), VOLUTE

      DOUBLE PRECISION  ARMIN, ARMAX, SURFTR(4)

C     LE TETRAEDRE EST IL ACTIF DANS NOTETR?
      IF( NOSOTE(1) .LE. 0 ) THEN
         PRINT *,'ceboqu: TETRAEDRE INACTIF de SOMMETS:',NOSOTE
         QUALTE = -1
         VOLUTE = 0D0
         GOTO 9000
      ENDIF

C     CALCUL DE LA LONGUEUR DES ARETES MIN ET MAX,
C     LA SURFACE DES 4 FACES, LE VOLUME,
C     LA QUALITE: ALFA RAYON INSCRIT / H LONGUEUR DE LA PLUS LONGUE ARETE
C     OU    ALFA = 4/(SIN(ARCOS(1/SQRT(3)))
C     (RAPPEL : RAYON INSCRIT = 3 VOLUME TETRA / SURFACE DES 4 FACES)
C     ===================================================================
      CALL QUATETD( PTXYZD( 1, NOSOTE(1) ),
     %              PTXYZD( 1, NOSOTE(2) ),
     %              PTXYZD( 1, NOSOTE(3) ),
     %              PTXYZD( 1, NOSOTE(4) ),
     %              ARMIN, ARMAX, SURFTR, VOLUTE, QUALTE )

 9000 IF( QUALTE .LE. QTEMIN ) THEN

C        VALEURS IMPOSEES POUR UN TETRAEDRE DEGENERE
C        CENTRE XYZ NULS et CARRE DU RAYON =-1 POUR EVITER DIVISION/R=0D0
         CENTRE(1) = 0D0
         CENTRE(2) = 0D0
         CENTRE(3) = 0D0
         CENTRE(4) =-1D0
         RETURN

      ENDIF

C     CALCUL DU CENTRE ET RAYON DE LA BOULE CIRCONSCRITE AU TETRAEDRE
C     ===============================================================
      CALL CERABOCI( PTXYZD( 1, NOSOTE(1) ),
     %               PTXYZD( 1, NOSOTE(2) ),
     %               PTXYZD( 1, NOSOTE(3) ),
     %               PTXYZD( 1, NOSOTE(4) ),
     %               CENTRE, VOLUTE, IERR )
      IF( IERR .NE. 0 ) THEN
         QUALTE = -1
      ENDIF

      RETURN
      END
