      SUBROUTINE CRHAFAVO( NBSOTE, MXTETR, NSTETR, NUDTETR,
     %                     MOFACE, MXFACE, LFACES, NBFAPB, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CREER SI CE N'EST DEJA FAIT LE TMS DES FACES D'UN VOLUME
C -----    ET CHAINER LES FACES FRONTALIERES
C             CHAINER LES FACES INTERFACES ENTRE 2 MATERIAUX
C          cf ~/td/d/a___face
C
C ENTREES:
C --------
C MXTETR : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES DANS NSTETR
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE
C          NSTETR(1,*)=0 => TAETRAEDRE VIDE et NSTETR(2,*) EST LE
C          TETRAEDRE NSTETR SUIVANT
C
C SORTIES:
C --------
C NBTETR : NOMBRE DE TETRAEDRES ACTIFS DANS NSTETR
C NUDTETR: NUMERO NSTETR DU DERNIER TETRAEDRE ACTIF PARMI MXTETR
C NBFAPB : NOMBRE DE FACES DES TETRAEDRES A PROBLEME APPARTENANT A
C          PLUS DE 2 TETRAEDRES
C LFACES : LFACES(1,I)= NO DU 1-ER  SOMMET DE LA FACE
C          LFACES(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LFACES(3,I)= NO DU 3-EME SOMMET DE LA FACE
C          LFACES(4,I)= CHAINAGE HACHAGE SUR FACE SUIVANTE
C          SI SOMMET 2 < DERNIER SOMMET  => FACE   DIRECTE DANS L'ELEMENT FINI
C                      >                 => FACE INDIRECTE
C          UNE FACE DIRECTE EST VUE DE L EXTERIEUR DE L'ELEMENT FINI
C          SOUS LA FORME DIRECTE

C          LFACES(5,I)= NUMERO DU 1-ER ELEMENT FINI CONTENANT CETTE FACE
C                       >0 SI FACE   DIRECTE DANS CET ELEMENT FINI
C                       <0 SI FACE INDIRECTE DANS CET ELEMENT FINI
C          SI LA FACE APPARTIENT A 2 ELEMENTS FINIS ALORS
C          LFACES(6,I)= NUMERO DU 2-EME ELEMENT FINI CONTENANT CETTE FACE
C                       >0 SI FACE   DIRECTE DANS CET ELEMENT FINI
C                       <0 SI FACE INDIRECTE DANS CET ELEMENT FINI
C          SINON
C          LFACES(7,I)= NUMERO DU 3-EME ELEMENT FINI CONTENANT CETTE FACE
C                       0 SI C'EST LA DERNIERE
C NBFAPB : NOMBRE DE FACES APPARTENANT A AU MOINS 3 TETRAEDRES
C IERR   : =0  SI PAS D'ERREUR
C          =1  SI MXFACE DEMANDE A ETRE AUGMENTE
C          =12 SI AU MOINS UNE FACE DANS 3 TETRAEDRES
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN LJLL UPMC ET St PIERRE DU PERRAY   Avril 2017
C2345X7..............................................................012
      PARAMETER (MXFAPB=1024)
      INTEGER  NSTETR(NBSOTE,MXTETR), LFACES(MOFACE,MXFACE)
      INTEGER  NOSOTR1(3), NOSOTR2(3), NOFAPB(MXFAPB)
      INTEGER  NOSOFATE(3,4)
      DATA     NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /

C     MISE A ZERO DU TABLEAU LFACES
      CALL AZEROI( MOFACE*MXFACE, LFACES )

C     LA 1-ERE FACE LIBRE
      LIBREF = MXFACE

C     LA BOUCLE SUR LES TETRAEDRES DE NSTER
      NBFAPB = 0

      DO 100 NTE=1,MXTETR

         IF( NSTETR(1,NTE) .LE. 0 ) GOTO 100

C        NUMERO NSTETR DU DERNIER TETRAEDRE ACTIF
         NUDTETR = NTE

         DO 90 NF = 1, 4

C           LE NUMERO DES 3 SOMMETS DE LA FACE NF DU TETRAEDRE NTE
            DO NS = 1, 3
               NOSOTR1( NS ) = NSTETR( NOSOFATE(NS,NF), NTE )
            ENDDO
C
C           PRESENTATION DES NUMEROS DES SOMMETS POUR LE HACHAGE
C           LE PLUS PETIT NUMERO DE SOMMET EST MIS EN PREMIERE POSITION DE NUSTF
C           PUIS LE PLUS PETIT SOMMET PARMI LE SECOND ET LE 3-EME
            CALL NSFAHA( 3, NOSOTR1, LESENS, NOSOTR2, MINNUS )
C
C           RECHERCHE OU ADJONCTION DE LA FACE DANS LFACES
            CALL HACHAG( 3, NOSOTR2, MOFACE, MXFACE, LFACES, 4,
     &                   LIBREF, NOFAC )
C           NOFAC : NO DANS LFACES DE LA FACE RETROUVEE
C                   =0 SI SATURATION DU TABLEAU LFACES
C                   >0 SI LA FACE NOSOTR2   A     ETE RETROUVEE
C                   <0 SI LA FACE NOSOTR2 N'A PAS ETE RETROUVEE MAIS AJOUTEE
            IF( NOFAC .EQ. 0 ) THEN
C              LISTE SATUREE CAR MXFACE SOUS-ESTIMEE
               PRINT*,'crhafavo: MXFACE de LFACES A AUGMENTER'
               IERR=1
               RETURN
            ELSE IF( NOFAC .LT. 0 ) THEN
C              FACE AJOUTEE
               NOFAC = -NOFAC
            ELSE
C              FACE RETROUVEE DANS LFACES
               IF( ABS(LFACES(5,NOFAC)) .EQ. NTE ) GOTO 90
               IF( ABS(LFACES(6,NOFAC)) .EQ. NTE ) GOTO 90
               IF( ABS(LFACES(7,NOFAC)) .EQ. NTE ) GOTO 90
C              NTE NON DEJA STOCKE
            ENDIF

C           STOCKAGE DU NO NSTETR DU TETRAEDRE DANS LFACES(5:7,NOFAC)
            K = 4
 10         K = K + 1
            IF( K .LE. 6 ) THEN
C
C              RECHERCHE D'UN NUMERO NUL D'ELEMENT FINI PARMI LES 2 POSSIBLES
               NTESTK = LFACES( K, NOFAC )
               IF( NTESTK .NE. 0 ) THEN
                  GOTO 10
               ENDIF
C
C              NO ELEMENT FINI > 0 SI LA FACE EST   DIRECTE DANS L'ELEMENT FINI
C                              < 0 SI LA FACE EST INDIRECTE DANS L'ELEMENT FINI
               LFACES( K, NOFAC ) = NTE * LESENS

            ELSE

C              ERREUR: PLUS DE 2 TETRAEDRES CONTIENNENT CETTE FACE
C              UNE FACE A PB DE PLUS
               NBFAPB = NBFAPB + 1
               IF( NBFAPB .LE. MXFAPB ) THEN
                  NOFAPB( NBFAPB ) = NOFAC
               ENDIF

C              STOCKAGE DU 3-EME TETRAEDRE
               LFACES( 7, NOFAC ) = NTE

C              NUMERO NSTETR DU TETRAEDRE 1 DE CETTE FACE
               NTE1 = ABS( LFACES( 5, NOFAC) )
C              NUMERO NSTETR DU TETRAEDRE 2 DE CETTE FACE
               NTE2 = ABS( LFACES( 6, NOFAC) )

               PRINT *
               PRINT *,'crhafavo: FACE TRIPLE',NBFAPB,' LFACES(',NOFAC,
     %                 ')=',(LFACES(L,NOFAC),L=1,7),
     %                 ' DANS AU MOINS 3 TETRAEDRES'

C              IMPRESSION DES NO ET XYZ DES SOMMETS DE LA FACE A PB
               PRINT 10050, NTE,  (NSTETR(L,NTE ),L=1,4)
               PRINT 10050, NTE1, (NSTETR(L,NTE1),L=1,4)
               PRINT 10050, NTE2, (NSTETR(L,NTE2),L=1,4)
10050          FORMAT(' crhafavo: NSTETR(',I8,') de SOMMETS:',T40,4I8)

               IERR = 12

            ENDIF

 90      ENDDO

 100  ENDDO

      IF( NBFAPB .GT. 0 ) THEN
         PRINT *,'crhafavo:',NBFAPB,' FACES dans 3 TETRAEDRES'
         PRINT *,'crhafavo:',NUDTETR,' NO DERNIER TETRAEDRE ACTIF PARMI'
     %                      ,MXTETR,' TETRAEDRES DECLARES'
      ENDIF

      RETURN
      END
