      SUBROUTINE DETETD( A, MU, N,   NBCDNE, NBHOMO, DET )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCUL DU DETERMINANT DE LA MATRICE A PROFIL FACTORISEE (TL*D*L)
C ----- DU NOMBRE DE PIVOTS NEGATIFS(NBCDNE) ET DES
C       HOMOTHETIES POUR EVITER LES OVERFLOW DU MOT MEMOIRE(SCALE)
C
C ENTREES:
C --------
C A      : MATRICE FACTORISEE
C MU     : POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE A PROFIL MU(1)=0
C N      : ORDRE DE A
C
C SORTIES:
C --------
C NBCDNE : NOMBRE DE COEFFICIENTS DIAGONAUX NEGATIFS DE LA MATRICE A
C NBHOMO : NOMBRE D HOMOTHETIES EFFECTUEES C-A-D LE NOMBRE DE FOIS OU
C          LE DETERMINANT EST MULTIPLIE PAR LE FACTEUR SCALE
C          CE NOMBRE PEUT ETRE NEGATIF
C DET    : DETERMINANT DE LA MATRICE A=TL*D*L (PRODUIT DE LA TRACE DE D)
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEURS: PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS        AOUT 1998
C ......................................................................
      include"./incl/epsvvp.inc"
CCC      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      DOUBLE PRECISION  A(*), X, DET, SCALE1
      INTEGER           MU(0:N)
C
C     L'INVERSE DU FACTEUR D'HOMOTHETIE
      SCALE1 = 1D0 / SCALE
C
      NBCDNE = 0
      NBHOMO = 0
      DET    = 1D0
C
      DO 30 J=1,N
C
C        LE COEFFICIENT DIAGONAL J DE LA MATRICE PROFIL A
         X = A( MU(J) )
C
C        NBCDNE NOMBRE DE COEFFICIENTS DIAGONAUX STRICTEMENT NEGATIFS
         IF( X .LT. 0D0 ) THEN
            NBCDNE = NBCDNE + 1
         ENDIF
C
C        LE DETERMINANT DE LA MATRICE A
         DET = DET * X
C
C        L HOMOTHETIE DU DETERMINANT EST ELLE NECESSAIRE?
 10      IF( ABS(DET) .LT. SCALE1 ) THEN
             DET    = DET * SCALE
             NBHOMO = NBHOMO + 1
             GOTO 10
         ENDIF
C
 20      IF( ABS(DET) .GE. SCALE ) THEN
             DET    = DET * SCALE1
             NBHOMO = NBHOMO - 1
             GOTO 20
         ENDIF
C
 30   CONTINUE
C
CCC      WRITE(IMPRIM,10000) DET,SCALE,-NBHOMO
CCC10000 FORMAT('DETERMINANT DE LA MATRICE =',G24.16,
CCC     %       ' * (',G10.2,' **',I5,' )')

      RETURN
      END
