      SUBROUTINE EFPOGE( MNNPEF , NUELEM ,
     %                   NBPGEF , NOPGEF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   RETROUVER LE NUMERO DES POINT GEOMETRIQUES DE L'ELEMENT NUELEM
C -----
C
C ENTREES :
C ---------
C MNNPEF : ADRESSE MCN DU TABLEAU 'NPEF"NOM_ELEMENT_FINI'
C NUELEM : NUMERO DE L'ELEMENT
C
C SORTIES :
C ---------
C NBPGEF : NOMBRE EFFECTIF DE   POINTS GEOMETRIQUES DE L'ELEMENT FINI
C NOPGEF : LE NUMERO DES NBPGEF POINTS GEOMETRIQUES DE L'ELEMENT FINI
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1989
C23456---------------------------------------------------------------012
      IMPLICIT          INTEGER (W)
      include"./incl/a___npef.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      INTEGER           NOPGEF(1:NBPGEF)
C
C     L'ADRESSE DU 1-ER NOEUD DE L'ELEMENT NUELEM
      MN = MNNPEF - 1 + WUNDEL + NUELEM
C
C     LE NOMBRE DE POINTS DE L'ELEMENT
      NBPGEF = MCN( MNNPEF + WBPGEL )
C
C     LE NOMBRE DE NOEUDS DE L'ELEMENT
      NBNDEL = MCN( MNNPEF + WBNDEL )
C
C     LE NOMBRE D'ELEMENTS
      NBELEM = MCN( MNNPEF + WBELEM )
C
      IF( NBPGEF .GT. 0 ) THEN
C        POINTS#NOEUDS
         NBPGEF = MCN( MNNPEF + WBPGEL )
         MN     = MNNPEF + NBNDEL * NBELEM
      ELSE
C        POINTS=NOEUDS
         NBPGEF = NBNDEL
      ENDIF
C
C     COPIE DU NUMERO DES POINTS GEOMETRIQUES
      DO 10 I=0,NBPGEF-1
C        LE NUMERO DU I+1-EME POINT GEOMETRIQUE
         NOPGEF(I+1) = MCN(MN)
C        L'ADRESSE MCN DU NUMERO DE POINT GEOMETRIQUE SUIVANT
         MN = MN + NBELEM
 10   CONTINUE
      END
