      SUBROUTINE EFTGEF( MNNPEF, NUELEM,
     %                   NBTGEL, NOTGEL )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE NOMBRE ET LES NUMEROS EVENTUELS
C -----    DES TANGENTES DE L'EF
C
C ENTREES:
C --------
C MNNPEF : ADRESSE MCN DU TABLEAU  'NPEF"NOM_ELEMENT_FINI'
C NUELEM : NUMERO DE L'ELEMENT FINI DANS L'ENSEMBLE DES EF DE CE TYPE
C
C SORTIES:
C --------
C NBTGEL : =0 SI L'EF N'A PAS DE TANGENTE
C          >0 SI L'EF A NBTGEL TANGENTES
C NOTGEL : +-NUMERO DES NBTGEL TANGENTES DE L'EF NUELEM
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    DECEMBRE 1996
C23456---------------------------------------------------------------012
      IMPLICIT          INTEGER (W)
      include"./incl/a___npef.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      INTEGER           NOTGEL(1:NBTGEL)
C
C     LE NOMBRE DE TG PAR EF A TG
      NBTGEL = MCN( MNNPEF + WBTGEL )
      IF( NBTGEL .LE. 0 ) GOTO 9999
C
C     LE NOMBRE D'EF A TG
      NBELTG = MCN( MNNPEF + WBELTG )
      IF( NBELTG .LE. 0 ) GOTO 9999
C
C     LE NOMBRE D'ELEMENTS FINIS DE CE TYPE
      NBELEM = MCN( MNNPEF + WBELEM )
C
C     LE NOMBRE DE NOEUDS DE L'ELEMENT
      NBNDEL = MCN( MNNPEF + WBNDEL )
C
C     LE NOMBRE DE POINTS GEOMETRIQUES DE L'ELEMENT
      NBPGEL = MCN( MNNPEF + WBPGEL )
C
C     NBPSEL   NOMBRE DE POINTS UTILISATEUR SOMMET D UN ELEMENT
C     MOPSEL   NOMBRE DE VARIABLES DES TABLEAUX NLPSEL ET NEPSEL
C     NBLAEL   NOMBRE DE LIGNES UTILISATEUR ARETE D UN ELEMENT
C     MOLAEL   NOMBRE DE VARIABLES DES TABLEAUX NLLAEL ET NELAEL
C     NBSFEL   NOMBRE DE SURFACES UTILISATEUR FACE D UN ELEMENT
C     MOSFEL   NOMBRE DE VARIABLES DES TABLEAUX NLSFEL ET NESFEL
C     NBVCEL   NOMBRE DE VOLUMES UTILISATEUR CUBE D UN ELEMENT
C     MOVCEL   NOMBRE DE VARIABLES DES TABLEAUX NLVCEL ET NEVCEL
C
      NBPSEL = MCN( MNNPEF + WBPSEL )
      MOPSEL = MCN( MNNPEF + WOPSEL )
      NBLAEL = MCN( MNNPEF + WBLAEL )
      MOLAEL = MCN( MNNPEF + WOLAEL )
      NBSFEL = MCN( MNNPEF + WBSFEL )
      MOSFEL = MCN( MNNPEF + WOSFEL )
      NBVCEL = MCN( MNNPEF + WBVCEL )
      MOVCEL = MCN( MNNPEF + WOVCEL )
C
C     LES ADRESSES MCN DU DEBUT DES TABLEAUX
      MNNDEL = MNNPEF  + WUNDEL
      IF( NBPGEL .GT. 0 ) THEN
C        NOEUDS#POINTS
         MNPGEL = MNNDEL + NBELEM * NBNDEL
         MNPSEL = MNPGEL + NBELEM * NBPGEL
      ELSE
C        NOEUDS=POINTS
         MNPGEL = MNNDEL
         MNPSEL = MNPGEL + NBELEM * NBNDEL
      ENDIF
C
      MNLAEL = MNPSEL + NBPSEL + MOPSEL + MOPSEL
      MNSFEL = MNLAEL + NBLAEL + MOLAEL + MOLAEL
      MNVCEL = MNSFEL + NBSFEL + MOSFEL + MOSFEL
      MNELTG = MNVCEL + NBVCEL + MOVCEL + MOVCEL
C
      NUELTG = MCN( MNELTG - 1 + NUELEM )
      IF( NUELTG .LE. 0 ) GOTO 9999
C
C     LES NUMEROS DES TANGENTES DE CET EF A TG
      MNNUTG = MNELTG + MCN(MNNPEF+WBELAP) - NBELTG + NUELTG - 1
      DO 10 I=1,NBTGEL
         NOTGEL( I ) = MCN( MNNUTG + I * NBELTG )
 10   CONTINUE
      RETURN
C
C     PAS DE TG
 9999 NBTGEL = 0
      END
