      SUBROUTINE FIMOLE( NOFISY , NOPAGE , MOPAGE , NBMOTS , PAGE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : LIRE SUR LE FICHIER NOFISY LES NBMOTS DE LA PAGE NOPAGE
C ----- ET LES RANGER DANS LES NBMOTS PREMIERS MOTS DU TABLEAU PAGE
C
C ENTREES :
C ---------
C NOFISY : NUMERO SYSTEME DU FICHIER D ACCES DIRECT
C NOPAGE : NUMERO DE LA PAGE A LIRE SUR CE FICHIER
C MOPAGE : NOMBRE DE MOTS PAR PAGE DE CE FICHIER
C NBMOTS : NOMBRE DE MOTS DE LA PAGE A LIRE
C
C SORTIE :
C --------
C PAGE   : TABLEAU RECEVANT LES NBMOTS MOTS LUS SUR LE FICHIER
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  NOVEMBRE 1989
C.......................................................................
      INTEGER PAGE(MOPAGE)
C
C     LECTURE SUR LE FICHIER NOFISY DE LA PAGE NOPAGE
      READ( UNIT=NOFISY,REC=NOPAGE) (PAGE(I),I=1,NBMOTS)
C
      RETURN
      END
