      SUBROUTINE FIPALE( NOFISY , NOPAGE , MOPAGE , PAGE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : LIRE SUR LE FICHIER NOFISY LA PAGE NOPAGE ET LES RANGER DANS
C ----- LES MOPAGE PREMIERS MOTS DU TABLEAU PAGE
C
C ENTREES :
C ---------
C NOFISY : NUMERO SYSTEME DU FICHIER D ACCES DIRECT
C NOPAGE : NUMERO DE LA PAGE A LIRE SUR CE FICHIER
C MOPAGE : NOMBRE DE MOTS PAR PAGE DE CE FICHIER
C
C SORTIE :
C --------
C PAGE   : TABLEAU RECEVANT LES MOPAGE MOTS LUS SUR LE FICHIER
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  DECEMBRE 1983
C.......................................................................
      INTEGER PAGE(MOPAGE)
C
C     LECTURE SUR LE FICHIER NOFISY DE LA PAGE NOPAGE
      READ( UNIT=NOFISY,REC=NOPAGE) PAGE
C
      RETURN
      END
