      SUBROUTINE HACHAR( NVALEU, VALEUR, L1, L2, LISTE, LIEN,
     %                   NOCOLO )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : RECHERCHER LES NVALEU ENTIERS DU TABLEAU VALEUR PARMI
C ----- LES NVALEU-ERES VALEURS DES COLONNES DU TABLEAU LISTE
C       LA METHODE EMPLOYEE ICI EST CELLE DU HACHAGE
C       ADRESSAGE SUR LA SOMME DES VALEURS MODULO L2
C
C PARAMETRES D ENTREE :
C ---------------------
C NVALEU : NOMBRE DES VALEURS A IDENTIFIER OU AJOUTER
C VALEUR : TABLEAU DE NVALEU ENTIERS DES VALEURS A RETROUVER OU AJOUTER
C L1     : NOMBRE DE LIGNES DU TABLEAU LISTE (>NVALEU)
C L2     : NOMBRE DE COLONNES DU TABLEAU LISTE
C LISTE  : TABLEAU CONTENANT LES VALEURS DEJA AJOUTEES
C LIEN   : NUMERO DE LA LIGNE CONTENANT LE CHAINAGE SUR LE SUIVANT
C          ET SANS SUIVANT OU LIGNE NON UTILISEE  : LA VALEUR 0
C
C PARAMETRE RESULTAT :
C --------------------
C NOCOLO : NO DE LA COLONNE DU TABLEAU VALEUR RETROUVEE
C          > 0 SI LE TABLEAU VALEUR A ETE RETROUVE
C          =<0 SI LE TABLEAU VALEUR N'A PAS ETE RETROUVE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE UPMC PARIS      AVRIL 1989
C ......................................................................
      INTEGER  VALEUR(NVALEU) , LISTE(L1,L2)
C
C     LA FONCTION D ADRESSAGE
C     =======================
      GOTO( 101 , 102 , 103 , 104 , 105 , 106 , 107 , 108 ) , NVALEU
C
C     CAS NVALEU NEGATIF OU SUPERIEUR A 8
      NOCOLO = 0
      DO 100 I=1,NVALEU
         NOCOLO = NOCOLO + ABS( VALEUR(I) )
 100  CONTINUE
      GOTO 200
C
 101  NOCOLO = VALEUR(1)
      GOTO 200
C
 102  NOCOLO = VALEUR(1) + VALEUR(2)
      GOTO 200
C
 103  NOCOLO = VALEUR(1) + VALEUR(2) + VALEUR(3)
      GOTO 200
C
 104  NOCOLO = VALEUR(1) + VALEUR(2) + VALEUR(3) + VALEUR(4)
      GOTO 200
C
 105  NOCOLO = VALEUR(1) + VALEUR(2) + VALEUR(3) + VALEUR(4) +
     %         VALEUR(5)
      GOTO 200
C
 106  NOCOLO = VALEUR(1) + VALEUR(2) + VALEUR(3) + VALEUR(4) +
     %         VALEUR(5) + VALEUR(6)
      GOTO 200
C
 107  NOCOLO = VALEUR(1) + VALEUR(2) + VALEUR(3) + VALEUR(4) +
     %         VALEUR(5) + VALEUR(6) + VALEUR(7)
      GOTO 200
C
 108  NOCOLO = VALEUR(1) + VALEUR(2) + VALEUR(3) + VALEUR(4) +
     %         VALEUR(5) + VALEUR(6) + VALEUR(7) + VALEUR(8)
C
 200  NOCOLO = MOD( ABS(NOCOLO) , L2 )
      IF( NOCOLO .EQ. 0 ) NOCOLO = L2
C
C     LA RECHERCHE DU TABLEAU
C     -----------------------
 210  DO 220 I=1,NVALEU
         IF( VALEUR(I) .NE. LISTE(I,NOCOLO) ) GOTO 230
 220  CONTINUE
C
C     LE TABLEAU EST RETROUVE
C     -----------------------
      RETURN
C
C     TABLEAU VALEUR RECHERCHE PARMI LES COLONNES CHAINEES A NOCOLO
C     -------------------------------------------------------------
 230  NOCOLO = LISTE( LIEN , NOCOLO )
      IF( NOCOLO .GT. 0 ) GOTO 210

      RETURN
      END
