      SUBROUTINE HACHAF( NMOBJT, NBMOTS, NTFAOB, MNFAOB,
     %                   NTARFR, MNARFR, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CREER SI CE N'EST DEJA FAIT LE TABLEAU DES ARETES FRONTALIERES
C -----    A PARTIR DES FACES FRONTALIERES D'UN OBJET 3D
C
C ENTREES:
C --------
C NMOBJT : NOM DE L'OBJET
C NBMOTS : NOMBRE DE MOTS D'INFORMATIONS A STOCKER EN PLUS PAR FACE(>1)
C NTFAOB : NUMERO DU TMS DES FACES DU VOLUME
C          0 SI NON CREE PAR CAUSE D'ERREUR
C MNFAOB : ADRESSE MCN DU TABLEAU DES FACES DU VOLUME
C          cf ~/td/d/a___face
C
C SORTIES:
C --------
C NTARFR : NUMERO DU TMS DES ARETES FRONTALIERES DE L'OBJET 3D
C          0 SI NON CREE PAR CAUSE D'ERREUR
C MNARFR : ADRESSE MCN DU TABLEAU DES  ARETES FRONTALIERES DE L'OBJET 3D
C          cf ~/td/d/a___aretefr
C IERR   : =0 SI PAS D'ERREUR
C          =1 SI OBJET INCONNU
C          =2 SI OBJET CONNU MAIS PAS D'INTERPOLATION
C          =3 SI OBJET CONNU MAIS PAS DE TABLEAU FACE
C          =4 SI OBJET CONNU MAIS PAS DE MCN POUR DECLARER ARETFR
C          >0 SI ERREUR
C
C EN SORTIE  LE TABLEAU LAREFR CONTIENT :
C MOARFR  NOMBRE DE MOTS PAR ARETE FRONTALIERE DU TABLEAU NFACE DES FACES
C MXARFR  NOMBRE MAXIMAL D'ARETES FRONTALIERES DECLARABLES
C L1ARFR  NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
C NBARFR  NOMBRE D'ARETES FRONTALIERES DANS LE CHAINAGE
C         LAREFR(1,I)= NO DU 1-ER  SOMMET DE L'ARETE FRONTALIERE
C         LAREFR(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C         LAREFR(3,I)= 0 OU NUMERO DE L'ARETE FRONTALIERE SUIVANTE
C                      DANS LE HACHAGE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1994
C ...................................................................012
      IMPLICIT INTEGER (W)
      include"./incl/gsmenu.inc"
      include"./incl/a___face.inc"
      include"./incl/a___aretefr.inc"
      include"./incl/ntmnlt.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
      CHARACTER*(*)     NMOBJT
      INTEGER           NOSOEL(4),NS(2)
      LOGICAL           AVANT
C
      IERR   = 0
      NBARFR = 0
C
C     L'OBJET EST RECHERCHE
C     =====================
C     LE TABLEAU LEXIQUE DE CET OBJET
      CALL LXLXOU( NTOBJE, NMOBJT, NTLXOB, MN )
      IF( NTLXOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) = NMOBJT
         KERR(2) = 'OBJET INCONNU'
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     LE TABLEAU 'TOPOLOGIE' DE CET OBJET
      CALL LXTSOU( NTLXOB, 'TOPOLOGIE', NTTOPO, MNTOPO )
      IF( NTTOPO .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) = 'OBJET: ' // NMOBJT
         KERR(2) = 'INTERPOLATION NON DEFINIE'
         CALL LEREUR
         IERR = 2
         RETURN
      ENDIF
C
C     LE TABLEAU 'FACE' DE CET OBJET
      CALL LXTSOU( NTLXOB, 'FACE', NTFAOB, MNFAOB )
      IF( NTFAOB .GT. 0 ) THEN
C        LES FACES SONT ELLES ANTERIEURES A LA TOPOLOGIE DE L'OBJET?
         IF( .NOT. AVANT( MCN(MNTOPO), MCN(MNFAOB) ) ) THEN
C           LES FACES SONT ANTERIEURES A LA TOPOLOGIE
            GOTO 9999
         ENDIF
      ELSE
         GOTO 9999
      ENDIF
C
C     LE TABLEAU 'ARETEFR' DE CET OBJET
      CALL LXTSOU( NTLXOB, 'ARETEFR', NTARFR, MNARFR )
      IF( NTARFR .GT. 0 ) THEN
C        LES ARETES FRONTALIERES SONT ELLES ANTERIEURES AU TABLEAU FACE
         IF( AVANT( MCN(MNFAOB), MCN(MNARFR) ) ) THEN
C           LES SOMMETS SONT ANTERIEURS AUX FACES
C           LE TABLEAU ARETEFR EST ACCEPTE  => RETOUR SANS RECALCUL
            NBARFR = MCN( MNARFR + WBARFR )
            RETURN
         ENDIF
C        LE TABLEAU 'ARETEFR' EST DETRUIT POUR ETRE ENSUITE REGENERE
         CALL LXTSDS( NTLXOB, 'ARETEFR' )
         NTARFR = 0
         MNARFR = 0
      ENDIF
C
C     NOMBRE D'ARETES FRONTALIERES DECLARABLES
      MOFACE = MCN( MNFAOB + WOFACE )
      MXFACE = MCN( MNFAOB + WXFACE )
      NBFAFR = MCN( MNFAOB + WBFAFR )
C     SURFACE FERMEE A PRIORI + QUELQUES ARETES POUR LES ERREURS
      MXARFR = 2 * NBFAFR + 64
C     NOMBRE DE MOTS PAR ARETE FRONTALIERE
      MOARFR = 3 + NBMOTS
C
C     ADRESSAGE ET OUVERTURE DU TABLEAU ARETEFR
C     -----------------------------------------
      CALL LXTNDC( NTLXOB, 'ARETEFR', 'ENTIER', WAREFR + MOARFR*MXARFR)
      CALL LXTSOU( NTLXOB, 'ARETEFR', NTARFR, MNARFR )
      IF( NTARFR .LE. 0 ) THEN
         NBLGRC(NRERR) = 3
         KERR(1) = 'OBJET ' // NMOBJT
         KERR(2) = 'PAS ASSEZ DE PLACE POUR DECLARER ARETEFR'
         KERR(3) = 'REDUIRE LE NOMBRE DES ELEMENTS FINIS'
         CALL LEREUR
         IERR   = 4
         NTARFR = 0
         MNARFR = 0
         RETURN
      ENDIF
C
C     LE TABLEAU DES ARETES FRONTALIERES EST INITIALISE A ZERO
      MNAREF = MNARFR + WAREFR
      CALL AZEROI( MOARFR*MXARFR, MCN(MNAREF) )
C
C     LA 1-ERE ARETE FRONTALIERE LIBRE
      LIBREF = MXARFR
C
C     LA BOUCLE SUR LES ARETES FRONTALIERES
      MNFACE = MNFAOB + WFACES - MOFACE - 1
      NUFAFR = MCN( MNFAOB + W1FAFR )
      DO 100 NA=1,NBFAFR
         IF( NUFAFR .LE. 0 ) GOTO 100
C
C        ADRESSE MCN DE LA FACE NUFAFR DANS LFACES
         MNF = MNFACE + NUFAFR * MOFACE
         IF( MCN( MNF + 4 ) .EQ. 0 ) THEN
            NBS = 3
         ELSE
            NBS = 4
         ENDIF
C
C        LE NUMERO DES SOMMETS DE LA FACE
         DO 10 I=1,NBS
            NOSOEL(I) = MCN( MNF + I )
 10      CONTINUE
C
C        SENS DIRECT OU NON DU STOCKAGE DE LA FACE
         IF( MCN(MNF+6) .LT. 0 ) THEN
C           PERMUTATION DU SOMMET 2 ET NBS
            I           = NOSOEL(2)
            NOSOEL(2)   = NOSOEL(NBS)
            NOSOEL(NBS) = I
         ENDIF
C
C        LA BOUCLE SUR LES NBS ARETES DE LA FACE
         NS1 = MCN( MNF + NBS )
         DO 50 I=1,NBS
            NS2 = MCN( MNF + I )
C           NS1 NS2 NUMEROS DES 2 SOMMETS DE L'ARETE I DE LA FACE NUFAFR
            IF( NS1 .LT. NS2 ) THEN
               NS(1) = NS1
               NS(2) = NS2
            ELSE
               NS(1) = NS2
               NS(2) = NS1
            ENDIF
C
C           RECHERCHE OU ADJONCTION DE L'ARETE FRONTALIERE
            CALL HACHAG( 2, NS, MOARFR, MXARFR, MCN(MNAREF), 3,
     &                   LIBREF, NOARE )
            IF( NOARE .EQ. 0 ) THEN
               CALL LXTSDS( NTLXOB, 'ARETEFR' )
               IERR = 4
               RETURN
            ENDIF
C
C           PASSAGE A L'ARETE SUIVANTE DE LA FACE
            NS1 = NS2
 50      CONTINUE
C
C        PASSAGE A LA FACE FRONTALIERE SUIVANTE
         NUFAFR = MCN( MNF + 7 )
 100  CONTINUE
C
C     CALCUL DU NOMBRE D'ARETES FRONTALIERES
      MNF    = MNAREF
      L1ARFR = 0
      DO 200 I=1,MXARFR
         IF( MCN(MNF) .GT. 0 ) THEN
C           UNE ARETE FRONTALIERE DE PLUS
            NBARFR = NBARFR + 1
C           CETTE ARETE EST MISE EN TETE DU CHAINAGE DES ARETES FRONTIERE
            MCN(MNF+2) = L1ARFR
            L1ARFR = I
         ENDIF
         MNF = MNF + MOARFR
 200  CONTINUE
C
C     LE TABLEAU 'ARETEFR' EST COMPLETE
C     LE NOMBRE D'ENTIERS PAR ARETE FRONTALIERE
      MCN( MNARFR + WOARFR ) = MOARFR
C     LA MAJORATION DU NOMBRE D'ARETES FRONTALIERES
      MCN( MNARFR + WXARFR ) = MXARFR
C     LE NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
      MCN( MNARFR + W1ARFR ) = L1ARFR
C     LE NOMBRE D'ARETES FRONTALIERES DANS LE CHAINAGE
      MCN( MNARFR + WBARFR ) = NBARFR
C     LE NOMBRE TOTAL DE SOMMETS DES ARETES (ICI NUL PAS DE STOCKAGE)
      MCN( MNARFR + WBTSAF ) = 0
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MNARFR) )
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNARFR + MOTVAR(6) ) = NONMTD( '~>>>ARETEFR' )
      RETURN
C
C     ERREUR DETECTEE
 9999 NBLGRC(NRERR) = 2
      KERR(1) = 'OBJET: ' // NMOBJT
      KERR(2) = 'SANS TABLEAU FACE dans HACHAF'
      CALL LEREUR
      IERR = 3
      RETURN
      END
