      SUBROUTINE INARTRR( S1, S2, P1, P2, P3,  LINTER, PTR, CBT )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LES 3 COORDONNEES DU POINT PT, INTERSECTION DU
C -----    SEGMENT S1-S2 ET DU TRIANGLE DEFINI PAR SES SOMMETS P1, P2, P3

C          SP DIFFERENT de INARTR1 PAR LA POSITION du POINT PT SUR S1S2...

C ENTREES:
C --------
C S1,S2   : LES 2 POINTS QUI DEFINISSENT L'ARETE
C P1,P2,P3: LES 3 POINTS QUI DEFINISSENT LE TRIANGLE

C SORTIES:
C --------
C LINTER : -2 SI S1=S2 PAS DE CALCUL DE PT
C          -1 SI S1-S2 PARALLELE AU PLAN DU TRIANGLE
C           0 SI S1-S2 N'INTERSECTE PAS LE TRIANGLE ENTRE CES 3 SOMMETS
C                      ET ENTRE S1-S2
C           1 SI S1-S2   INTERSECTE     LE TRIANGLE ENTRE CES 3 SOMMETS
C                      ET ENTRE S1-S2   ...S1...PT...S2...>
C           PT EST DANS LE TRIANGLE OU SUR UNE DE SES 3 ARETES
C PTR    : LES 3 COORDONNEES DU POINT D'INTERSECTION SI LINTER=1
C CBT    : LES 3 COORDONNEES BARYCENTRIQUES DE PT DANS LE TRIANGLE P1P2P3
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY   JUILLET 2009
C MODIFS: ALAIN PERRONNET LJLL UPMC & VEULETTES SUR MER   SEPTEMBRE 2014
C MODIFS: ALAIN PERRONNET Saint Pierre du Perray           Novembre 2019
C MODIFS: ALAIN PERRONNET Saint Pierre du Perray            Octobre 2020
C23456...............................................................012
      IMPLICIT  NONE
      REAL              S1(3), S2(3), P1(3), P2(3), P3(3), PTR(3)
      DOUBLE PRECISION  CBT(3), PTI(3), CBA(3), CBAPTI, S1S2, S1PTI
      INTEGER           LINTER, K, N

      CALL INTARTRR0( S1, S2, P1, P2, P3, LINTER, PTI, CBT )

C LINTER : -2 SI S1=S2 PAS DE CALCUL DE PTI
C          -1 SI S1-S2 PARALLELE AU PLAN DU TRIANGLE
C           0 SI S1-S2 N'INTERSECTE PAS LE TRIANGLE ENTRE CES 3 SOMMETS
C           1 SI S1-S2   INTERSECTE     LE TRIANGLE ENTRE CES 3 SOMMETS
C             C-A-D  PTI EST INTERNE AU TRIANGLE OU SUR UNE DE SES 3 ARETES
C PTI     : LES 3 COORDONNEES DU POINT D'INTERSECTION SI LINTER=1
C CBT    : LES 3 COORDONNEES BARYCENTRIQUES DE PTI DANS LE TRIANGLE P1P2P3

      IF( LINTER .GE. 0 ) THEN
C        PT DOUBLE PRECISION => PTR SIMPLE PRECISION
         DO K=1,3
            PTR(K) = REAL( PTI(K) )
         ENDDO
      ENDIF

      IF( LINTER .NE. 1 ) GOTO 9999

C     COORDONNEE BARYCENTRIQUE DE PTI SUR L'ARETE S1-S2
C     CALCULEE PAR LA MOYENNE SUR SES 3 COORDONNES XYZ
C     AJOUT 29/09/2014 DU TEST SUR PTI INTERIEUR A S1-S2
      N = 0
      S1S2 = 0D0
      S1PTI = 0D0
      DO K=1,3
         S1S2 = S1S2 + ( S2(K) - S1(K) ) ** 2
         S1PTI = S1PTI + ( PTI(K) - S1(K) ) ** 2
         IF( S2(K) .NE. S1(K) ) THEN
            CBA(K) = ( PTI(K) - S1(K) ) / ( S2(K) - S1(K) )
            N = N + 1
         ELSE
            CBA(K) = 0D0
         ENDIF
      ENDDO
      CBAPTI = ( CBA(1) + CBA(2) + CBA(3) ) / N

      IF( S1PTI .EQ. 0D0 ) THEN
C        PTI=S1
         CBAPTI = 0D0
         LINTER = 1
         GOTO 9999
      ENDIF

      IF( S1S2 .EQ. 0D0 ) THEN
C        S1=S2  NON PTI  => NON DANS L'INTERVALLE S1 S2
         LINTER = 0
         GOTO 9999
      ENDIF

      IF( CBAPTI .LT. 0D0 ) THEN
         CBAPTI = -SQRT( S1PTI / S1S2 )
      ELSE
         CBAPTI =  SQRT( S1PTI / S1S2 )
      ENDIF

      IF( 0D0 .LE. CBAPTI .AND. CBAPTI .LE. 1D0 ) THEN
C        LE POINT EST DANS LE TRIANGLE OU SUR UNE DE SES 3 ARETES
C        ENTRE LES SOMMETS S1-S2
         LINTER = 1
         GOTO 9999
      ENDIF

C     La DROITE S1-S2 N'INTERSECTE PAS LE TRIANGLE ENTRE CES 3 SOMMETS
C     ou BIEN LE POINT D'INTERSECTION N'EST PAS ENTRE LES SOMMETS S1-S2
      LINTER = 0

 9999 RETURN
      END
