      SUBROUTINE INT1SD( NS1, NS2, NS3, NS4, PXYD, LINTER, X0, Y0 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    EXISTENCE OU NON  D'UNE INTERSECTION A L'INTERIEUR
C -----    DES 2 ARETES NS1-NS2 ET NS3-NS4
C          ATTENTION LES INTERSECTIONS AU SOMMET SONT COMPTEES
C
C ENTREES:
C --------
C NS1,...NS4 : NUMERO PXYD DES 4 SOMMETS
C PXYD   : LES COORDONNEES DES SOMMETS
C
C SORTIE :
C --------
C LINTER : -1 SI NS3-NS4 PARALLELE A NS1 NS2
C           0 SI NS3-NS4 N'INTERSECTE PAS NS1-NS2 ENTRE LES ARETES
C           1 SI NS3-NS4   INTERSECTE     NS1-NS2 ENTRE LES ARETES
C           2 SI LE POINT D'INTERSECTION EST NS1  ENTRE NS3-NS4
C           3 SI LE POINT D'INTERSECTION EST NS3  ENTRE NS1-NS2
C           4 SI LE POINT D'INTERSECTION EST NS4  ENTRE NS1-NS2
C X0,Y0  :  2 COORDONNEES DU POINT D'INTERSECTION S'IL EXISTE(LINTER>=1)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    FEVRIER 1992
C2345X7..............................................................012
      DOUBLE PRECISION  PXYD(3,*)
      DOUBLE PRECISION  X0, Y0, X1, Y1, X2, Y2, X3, Y3, X4, Y4
C
      X1  = PXYD(1,NS1)
      Y1  = PXYD(2,NS1)
C
      X2  = PXYD(1,NS2)
      Y2  = PXYD(2,NS2)
C
      X3  = PXYD(1,NS3)
      Y3  = PXYD(2,NS3)
C
      X4  = PXYD(1,NS4)
      Y4  = PXYD(2,NS4)
C
      CALL INTARAR( X1, Y1, X2, Y2, X3, Y3, X4, Y4,
     %              LINTER, X0, Y0 )
C
      RETURN
      END
