      SUBROUTINE LAR1FST( L1ARFA, L2ARFA, NARFA, NBAR1F, NUAR1F,
     %                    MXSA1F, NBSA1F, NUSA1F )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    A PARTIR DU TABLEAU ARFA DES ARETES DES FACES D'UNE SURFACE
C -----    CONSTRUIRE LE TABLEAU DES SOMMETS DES ARETES SIMPLES CAD
C          DES ARETES APPARTENANT A UNE SEULE FACE (QUADRANGLE ou TRIANGLE)

C ENTREES:
C --------
C L1ARFA : NOMBRE DE MOTS PAR ARFA DU TABLEAU NARFA
C L2ARFA : NOMBRE DE FACES DU TABLEAU NARFA
C NARFA  : NARFA(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          NARFA(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          NARFA(3,I)= CHAINAGE HACHAGE SUR L'ARETE SUIVANTE
C          NARFA(4:L1ARFA,I)= NO DANS NOSOFA DE LA FACE CONTENANT L'ARETE I
C          SI UNE ARETE APPARTIENT A PLUS DE L1ARFA-3 FACES, 
C          LE NUMERO DE FACE L1ARFA EST RENDU NEGATIF POUR INDIQUER
C          QUE LA LISTE DES FACES EST INCOMPLETE

C NBAR1F : NOMBRE D'ARETES SIMPLES 
C NUAR1F : NUMERO NARFA DES NBAR1F ARETES SIMPLES
C MXSA1F : NOMBRE MAXIMAL DE SOMMETS DES ARETES SIMPLES DANS NUSA1F

C SORTIES:
C --------
C NBSA1F : NOMBRE         DE SOMMETS DES ARETES SIMPLES DANS NUSA1F
C NUSA1F : NUMERO XYZSOM DES SOMMETS DES ARETES SIMPLES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2015
C23456---------------------------------------------------------------012
      INTEGER  NARFA(L1ARFA,L2ARFA), NUAR1F( NBAR1F ), NUSA1F( MXSA1F )

C     MISE A ZERO DE NUSA1F
      CALL AZEROI( MXSA1F, NUSA1F )

C     RECHERCHE DES ARETES APPARTENANT A UNE SEULE FACE=QT
      DO NA = 1, NBAR1F

C        NUMERO DE L'ARETE SIMPLE NA DANS NARFA
         NA1F = NUAR1F( NA )

C        LES 2 SOMMETS DE L'ARETE SIMPLE
         NS1 = NARFA(1,NA1F)
         NS2 = NARFA(2,NA1F)

C        LES 2 SOMMETS DE L'ARETE NA SONT EMPILES DANS SA1F
         NUSA1F( NS1 ) = NUSA1F( NS1 ) + 1
         NUSA1F( NS2 ) = NUSA1F( NS2 ) + 1

      ENDDO

C     CONTRACTION DU TABLEAU NUSA1F DES SOMMETS DES ARETES SIMPLES
      NBSA1F = 0
      DO NS1 = 1, MXSA1F
         IF( NUSA1F( NS1 ) .GT. 0 ) THEN
C           UN SOMMET DE PLUS DES ARETES SIMPLES
            NBSA1F = NBSA1F + 1
            NUSA1F( NBSA1F ) = NS1
         ENDIF
      ENDDO

      RETURN
      END
