      SUBROUTINE LIEXPD( NLD   , NCD   , NLMAX , NCMAX,
     %                   NCODEV, DBLVAL, NRETOU )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     LIRE ET RETOURNER UNE VALEUR DONNEE PAR L'UTILISATEUR
C -----     CETTE VALEUR EST UNE EXPRESSION DOUBLE PRECISION
C
C           CF ~LU/GRAMMAIRE DE DEFINITION DU LANGAGE UTILISATEUR
C
C ENTREES :
C ---------
C NLD,NCD : POSITION DANS KLG DU PREMIER CARACTERE A TRAITER
C
C MODIFIES:
C ---------
C NLMAX,NCMAX : POSITION DANS KLG DU DERNIER CARACTERE A TRAITER
C
C SORTIES :
C ---------
C NLD,NCD : POSITION DANS KLG DU DERNIER CARACTERE
C           EFFECTIVEMENT TRAITE
C NCODEV  : 0 DBLVAL N'EST PAS INITIALISEE
C           1 DBLVAL EST INITIALISEE
C DBLVAL  : VALEUR REELLE DOUBLE PRECISION
C NRETOU  :  0 SI PAS D'ERREUR
C           >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN  ANALYSE NUMERIQUE UPMC PARIS    OCTOBRE 1988
C23456---------------------------------------------------------------012
      include"./incl/lu.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      DOUBLE PRECISION  DBLVAL

C    3 ETAPES : 1: ANALYSE LEXICALE ( LIRE ET CHAINER LES OPERATIONS )
C    ========   2: GENERATION DE L'ARBORESCENCE
C               3: CALCUL DE LA VALEUR DE L'EXPRESSION
C                               REELLE DOUBLE PRECISION
      NCODEV = 0

C     SAUVEGARDE DE LA VALEUR D'ENTREE DU NOMBRE DE CONSTANTES STOCKEES
C     26/11/2015
      NBCTE0 = NBCTE

C     1: ANALYSE LEXICALE ( LIRE ET CHAINER LES OPERATIONS )
      NBVAR0 = NBVARU
      NBVAR1 = NBVARU
      CALL ALEXPD( NLD   , NCD   , NLMAX , NCMAX,
     %             NCODEV, DBLVAL, NRETOU )
      IF( NCODEV .GT. 0 .OR. NRETOU .NE. 0 ) RETURN

C     2: GENERATION DE L'ARBORESCENCE
      CALL AREXPD( NRETOU )
      IF( NRETOU .NE. 0 ) RETURN

C     3: CALCUL DE LA VALEUR DE L'EXPRESSION REELLE DOUBLE PRECISION
      CALL VAEXPD( NCODEV, DBLVAL )

      RETURN
      END
