      SUBROUTINE LISTQTAR( L1ARFA,   L2ARFA, NARFA,
     %                     NS1, NS2, NOARET, NBQTAR, NOQTAR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : ETABLIR LA LISTE DES QT ADJACENTS PAR L'ARETE DE SOMMETS NS1-NS2
C -----

C ENTREES:
C --------
C L1ARFA : NOMBRE DE MOTS PAR ARFA DU TABLEAU NARFA
C L2ARFA : NOMBRE DE FACES DU TABLEAU NARFA
C NARFA  : NARFA(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          NARFA(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          NARFA(3,I)= CHAINAGE HACHAGE SUR L'ARETE SUIVANTE
C          NARFA(4:L1ARFA,I)= NO DANS NOSOFA DE LA FACE CONTENANT L'ARETE I
C          SI UNE ARETE APPARTIENT A PLUS DE L1ARFA-3 FACES, 
C          LE NUMERO DE FACE L1ARFA EST RENDU NEGATIF POUR INDIQUER
C          QUE LA LISTE DES FACES EST INCOMPLETE
C NS1 NS2: LES NUMEROS DES 2 SOMMETS DE L'ARETE

C SORTIES:
C --------
C NOARET : NUMERO NARFA DE L'ARETE DE SOMMETS NS1 NS2
C NBQTAR : >0 NOMBRE DE QT  DE  L'ARETE NS1-NS2
C          =0 ARETE NS1-NS2 INEXISTANTE DANS NARFA ou AUCUN QT
C NOQTAR : NUMERO >0 DANS NOSTQT DES NBQTAR QT D'ARETE NS1-NS2
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Saint Pierre du Perray             Avril 2020
C23456---------------------------------------------------------------012
      INTEGER        NARFA(L1ARFA,L2ARFA), NOQTAR(16), NS(2)

      IF( NS1 .LE. NS2 ) THEN
         NS(1) = NS1
         NS(2) = NS2
      ELSE
         NS(1) = NS2
         NS(2) = NS1
      ENDIF

C     NS(1) < NS(2)
C     ADJONCTION DE L'ARETE SI ELLE N'EXISTE PAS DEJA
      CALL HACHAR( 2, NS, L1ARFA, L2ARFA, NARFA, 3, NOARET )

C     AJOUT DU NUMERO DU QTANGLE DE CETTE ARETE
C     NOARET = 0 SI LE TABLEAU NARFA EST SATURE
      IF( NOARET .LE. 0 ) THEN
         NOARET = 0
         NBQTAR = 0
         GOTO 9999
      ENDIF

C     QUEL EST LE NOMBRE DE QT CONTENANT CETTE ARETE?
      NBQTAR = 0
      DO K = 4, L1ARFA
         NOQT = ABS( NARFA(K,NOARET) )
         IF( NOQT .NE. 0 ) THEN
            NBQTAR = NBQTAR + 1
            NOQTAR( NBQTAR ) = NOQT
         ENDIF
      ENDDO

 9999 RETURN
      END


