      SUBROUTINE LXNMNU( NTLX , KNOM , NONOM0 , NONOM1 , MNLX )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : RETROUVER LE NUMERO NONOM1 D'UN NOM KNOM DANS LE LEXIQUE NTLX
C -----
C
C ENTREES :
C ---------
C NTLX   : NUMERO DU TABLEAU MS CONTENANT LE LEXIQUE
C KNOM   : CHAINE DE CARACTERES NOM A RETROUVER DANS LE LEXIQUE
C
C SORTIE  :
C ---------
C NONOM0 : NUMERO DU NOM QUI PRECEDE KNOM DANS LE CHAINAGE DU HACHAGE
C          =0 S'IL N'EXISTE PAS DE NOM PRECEDENT NONOM1
C NONOM1 : NUMERO DU NOM KNOM DANS LE LEXIQUE S'IL A ETE RETROUVE
C          =0 S'IL N'A PAS ETE RETROUVE
C MNLX   : ADRESSE MCN DU LEXIQUE NTLX
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : ALAIN PERRONNET ANALYSE NUMERIQUE PARIS   OCTOBRE 1984
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      INTEGER           INOM(18)
      CHARACTER*(*)     KNOM
C
C     OUVERTURE DU TABLEAU MS = LEXIQUE NTLX
      CALL TAMSOU( NTLX , MNLX )
C
C     MNLX   : ADRESSE MCN DU LEXIQUE
C     NBENNM : NOMBRE D'ENTIERS POUR STOCKER LES CARACTERES D'UN NOM
      NBENNM = MCN( MNLX + 2 )
C
C     CONVERSION DE KNOM EN ENTIERS DE INOM
      CALL NOMENT( NBENNM , KNOM , INOM )
C
C     DEBUT DU CHAINAGE DES NOMS OCCUPES
      NONOM0 = 0
      NONOM1 = MCN( MNLX + 5 )
C
C     LA BOUCLE SUR LES NOMS OCCUPES
 10   IF( NONOM1 .GT. 0 ) THEN
C        IL EXISTE ENCORE UN NOM.EST IL KNOM ?
         MN = MNLX + MCN( MNLX ) * NONOM1
C        TENTATIVE D'ACCELERATION PAR NON PASSAGE FREQUENT
C        SUR LA BOUCLE
         IF( INOM(1) .NE. MCN( MN ) ) GOTO 30
         DO 20 N=2,NBENNM
            IF( INOM(N) .NE. MCN( MN + N - 1) ) GOTO 30
 20      CONTINUE
C        C'EST LE NOM
         RETURN
C
C        CE N'EST PAS LE NOM KNOM
 30      NONOM0 = NONOM1
         NONOM1 = MCN( MN + NBENNM )
         GOTO 10
      ENDIF
C
C     IL N'EXISTE PLUS DE NOMS. NONOM1=0 EN RETOUR
      RETURN
      END
