      SUBROUTINE LXRLOU( NTLX , KNOM , NTRELA , MNRELA )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : OUVRIR LE NOM KNOM RELATION DU LEXIQUE NTLX
C -----
C
C ENTREES :
C ---------
C NTLX   : NUMERO DU TABLEAU MS CONTENANT LE LEXIQUE
C KNOM   : CHAINE DE CARACTERES NOM A RETROUVER DANS LE LEXIQUE
C
C SORTIES :
C ---------
C NTRELA : NUMERO DE CE TABLEAU MS CONTENANT LA RELATION
C          0 SI KNOM N'A PAS ETE RETROUVE DANS LE LEXIQUE ET RETOUR
C          ==> NECESSITE DE FAIRE UN TEST EN RETOUR
C MNRELA : ADRESSE EN MEMOIRE CENTRALE MCN OU MCK DE CETTE RELATION
C          0 SI KNOM N'A PAS ETE RETROUVE DANS LE LEXIQUE ET RETOUR
C          ==> NECESSITE DE FAIRE UN TEST EN RETOUR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : ALAIN PERRONNET ANALYSE NUMERIQUE PARIS   OCTOBRE 1985
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      CHARACTER*(*) KNOM
      CHARACTER*4   KTYPE
C
C     OUVERTURE DU TABLEAU MS DE NOM KNOM
      CALL LXNMOU( NTLX , KNOM , KTYPE , NTRELA , MNRELA )
C
C     VERIFICATION : LE TYPE RECUPERE EST-IL UNE RELA ?
      IF( KTYPE .NE. 'RELA' .AND. MNRELA .GT. 0 ) THEN
         NBLGRC(NRERR) = 1
         KERR(1) = KNOM
         KERR(2) ='NOM DE TYPE '//KTYPE//' AU LIEU DE RELA'
         CALL LEREUR
         CALL ARRET(100)
      ENDIF
      END
