      SUBROUTINE MIMAOB( NBJEUX, NTLXOB, MXDONN,
     %                   NTTOPO, MNTOPO, NTXYZP, MNXYZP, NTXYZN, MNXYZN,
     %                   MXTYEL, NBTYEL, MTNPEF, MNNPEF, NUMIOB, NUMAOB,
     %                   NDPGST, NBOBIN, MNOBIN, NBOBCL, MNOBCL,
     %                   MXDOEL, MNDOEL, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE NUMERO ET ADRESSE DES TMS
C -----    XYZPOINT XYZNOEUD NPEF D'UNE TOPOLOGIE D'UN OBJET
C          RECHERCHE DU MIN ET MAX DES NUMEROS DES OBJETS IMPLIQUES

C ENTREES:
C --------
C NBJEUX : NOMBRE DE JEUX DE DONNEES D'ENTREES
C          = 1 en STANDARD ou PAR DEFAUT
C          = DEGRE+1 DU POLYNOME P(Lambda)=0 des VALEURS PROPRES
C NTLXOB : NUMERO DU TMS LEXIQUE DE L'OBJET
C MXDONN : NOMBRE MAXIMAL DE DONNEES PAR PLSV SELON LE TYPE DE PB TRAITE
C          cf en thermique  ./incl/donthe.inc
C          cf en elasticite ./incl/donela.inc
C          cf en fluide     ./incl/donflu.inc

C SORTIES :
C ---------
C NTTOPO : NUMERO      DU TMS 'TOPOLOGIE' DE L'OBJET
C MNTOPO : ADRESSE MCN DU TMS 'TOPOLOGIE' DE L'OBJET
C NTXYZP : NUMERO      DU TMS 'XYZPOINT'  DE L'OBJET
C MNXYZP : ADRESSE MCN DU TMS 'XYZPOINT'  DE L'OBJET
C NTXYZN : NUMERO      DU TMS 'XYZNOEUD'  DE L'OBJET
C MNXYZN : ADRESSE MCN DU TMS 'XYZNOEUD'  DE L'OBJET
C MXTYEL : NOMBRE MAXIMAL DECLARABLE DE TYPES D'EF DU MAILLAGE
C NBTYEL : NOMBRE ACTUEL DE TYPES D'EF DU MAILLAGE DE L'OBJET
C MTNPEF : ADRESSE MCN DU TMC(NBTYEL) DU NUMERO        DU TMS 'NPEF' DES NBTYEL
C MNNPEF : ADRESSE MCN DU TMC(NBTYEL) DE L'ADRESSE MCN DU TMS 'NPEF' DES NBTYEL
C NUMIOB : NUMERO MINIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C NUMAOB : NUMERO MAXIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C NDPGST : COMPARAISON DES NOEUDS POINTS GEOMETRIQUES ET SOMMETS
C          0: noeuds = points = sommets seul le tms XYZSOMMET de l''objet existe
C          1: noeuds = points # sommets les tms XYZSOMMET XYZNOEUD existent
C          2: noeuds # points = sommets les tms XYZSOMMET XYZNOEUD existent
C          3: noeuds # points # sommets les tms XYZSOMMET XYZNOEUD XYZPOINT exis
C NBOBIN : NOMBRE DE VOLUMES en 3D, SURFACES en 2D DE L'OBJET
C MNOBIN : ADRESSE MCN DU DEBUT DU TABLEAU NUOBIN (PARTIE DE TOPOLOGIE)
C NBOBCL : NOMBRE DE PLS en 3D, PL en 2D DE L'OBJET
C MNOBCL : ADRESSE MCN DU DEBUT DU TABLEAU NUOBCL (PARTIE DE TOPOLOGIE)
C MXDOEL : NOMBRE DE MOTS DECLARES DU TABLEAU DES DONNEES DES PLSV
C MNDOEL : LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C          TABLEAUX DECRIVANT LES DONNEES (ELASTICITE,THERMIQUE,...)
C          DE L'OBJET COMPLET
C IERR   : 0 SI PAS D'ERREUR, >0 SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE UPMC PARIS    FEVRIER 1999
C2345X7..............................................................012
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      INTEGER           NUMIOB(4), NUMAOB(4), MNDOEL(4), MXDOEL(4)

C     ADRESSAGE DES ADRESSES DES TABLEAUX NPEF"... DE CET OBJET
      MNNPEF = 0
      CALL TNMCDC( 'ENTIER', 2*MXTYEL, MNNPEF )
      MTNPEF = MNNPEF + MXTYEL

C     RECHERCHE DES TABLEAUX XYZSOMMET XYZNOEUD XYZPOINT ASSOCIES A L'OBJET
      CALL NDPGEL( NTLXOB, NTTOPO, MNTOPO,
     %             NTXYZP, MNXYZP, NTXYZN, MNXYZN,
     %             NBTYEL, MCN(MTNPEF), MCN(MNNPEF), IERR )
      IF( IERR .NE. 0 ) RETURN

C     NBCOOR : NOMBRE DE COORDONNEES DES NOEUDS=POINTS (3 ou 6)
      NBCOOR = MCN( MNXYZP + WBCOOP )
ccc      IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,*) 'Chaque NOEUD=POINT a ',NBCOOR,
ccc     %                   ' COORDONNEES STOCKEES'
ccc      ELSE
ccc         WRITE(IMPRIM,*) 'Each NODE=POINT has ',NBCOOR,
ccc     %                   ' STORED COORDINATES'
ccc      ENDIF

      NDPGST = MCN( MNTOPO + WDPGST )
      NBOBIN = MCN( MNTOPO + WBOBIN )
      NBOBCL = MCN( MNTOPO + WBOBCL )

C     RECHERCHE DU MIN ET MAX DES NUMEROS DES OBJETS IMPLIQUES
C     ========================================================
C     DANS L'OBJET ( POINTS, LIGNES, SURFACES, VOLUMES )
C     LES 4 MINIMA D'ABORD, LES 4 MAXIMA ENSUITE
      JGRAND = IINFO( 'GRAND' )
      K      = - JGRAND
      DO I=1,4
         NUMIOB(I) = JGRAND
         NUMAOB(I) = K
      ENDDO

C     L'ADRESSE MCN DU DEBUT DU TABLEAU NUOBIN
      MNOBIN = MNTOPO + WMTYEL + NBTYEL
      MN     = MNOBIN - 2
      DO I=1,NBOBIN
C        LE TYPE DE L'OBJET INTERNE
         MN   = MN + 2
         NYOB = MCN( MN )
         NUOB = MCN( MN + 1 )
C        LE MINIMUM DES NUMEROS D'OBJETS
         NUMIOB( NYOB ) = MIN( NUMIOB(NYOB), NUOB )
C        LE MAXIMUM DES NUMEROS D'OBJETS
         NUMAOB( NYOB ) = MAX( NUMAOB(NYOB), NUOB )
      ENDDO

C     L'ADRESSE MCN DU DEBUT DU TABLEAU NUOBCL
      MNOBCL = MNOBIN + MOTVAR(13) * NBOBIN
      MN     = MNOBCL - 2
      DO I=1,NBOBCL
C        LE TYPE DE L'OBJET AUX LIMITES
         MN   = MN + 2
         NYOB = MCN( MN )
         NUOB = MCN( MN + 1 )
C        LE MINIMUM DES NUMEROS D'OBJETS
         NUMIOB( NYOB ) = MIN( NUMIOB(NYOB), NUOB )
C        LE MAXIMUM DES NUMEROS D'OBJETS
         NUMAOB( NYOB ) = MAX( NUMAOB(NYOB), NUOB )
      ENDDO

C     DECLARATION DES TABLEAUX DES DONNEES DES PLSV
      DO I=1,4
C        NOMBRE DE VARIABLES DES TABLEAUX
         IF( NUMIOB(I) .EQ. JGRAND ) THEN
C           PLSV NON REPERTORIE DANS L'OBJET
            NUMIOB(I) = 0
            NUMAOB(I) = 0
            MNDOEL(I) = 0
         ELSE
C           TABLEAU MNDOEL( MXDONN, NBJEUX, NUMIOB(I):NUMAOB(I) )
            MXDOEL(I) = MXDONN * NBJEUX * (NUMAOB(I) - NUMIOB(I) + 1)
            CALL TNMCDC( 'ENTIER', MXDOEL(I), MNDOEL(I) )
            CALL AZEROI( MXDOEL(I), MCN( MNDOEL(I) ) )
         ENDIF
      ENDDO

C     ICI NUMIOB CONTIENT LES 4 NUMEROS MINIMA DES PLSV
C         NUMAOB          LES 4 NUMEROS MAXIMA DES PLSV
C     MNDOEL LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C     TABLEAUX DECRIVANT LES DONNEES DE L'OBJET COMPLET

      RETURN
      END
