      SUBROUTINE MSIN( MOTMCN, MOPASF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : DECLARER LA MEMOIRE SECONDAIRE
C ----- DECLARER ET INITIALISER LE SUPER-FICHIER(10) DE GESTION DE LA MS
C       DECLARER LES FICHIERS DECRITS PAR LE TABLEAU LDFIMS
C
C ENTREES :
C ---------
C MOTMCN : NOMBRE DE MOTS DU SUPER TABLEAU MCN
C MXFIMS : NOMBRE MAXIMAL DE FICHIERS DE LA MS
C MXTAMS : NOMBRE MAXIMAL DE TABLEAUX DECLARABLES DANS LA MS
C NBFIMS : NOMBRE DE FICHIERS INITIAUX DE LA MS ( >1)
C          LE SUPER-FICHIER EST OBLIGATOIREMENT LE PREMIER D ENTRE EUX
C          LE NUMERO SYSTEME ATTRIBUE EST 10 POUR LE SUPER-FICHIER(S.F.)
C           9 + I POUR LE I-1 EME FICHIER SUPPORT DES TABLEAUX
C           NUMERIQUES ET CARACTERES DE LA MS
C LDFIMS : LES DESCRIPTEURS DES FICHIERS DE LA MS
C          LDFIMS(1,N)=NOMBRE DE PAGES DU N-EME FICHIER
C          LDFIMS(2,N)=NOMBRE DE MOTS DE CHAQUE PAGE DU N-EME FICHIER
C          N VARIE DE 1 (SF) A NBFIMS (=<MXFIMS)
C          ATTENTION : LDFIMS(2,1) DOIT ETRE SUPERIEUR A 29.
C          ---------
C NMPROJ : NOM DU PROJET NECESSITANT CETTE MS ( 72 CARACTERES )
C
C SORTIE :
C --------
C          LE SUPER-FICHIER=1-ER FICHIER DECLARE EST INITIALISE
C          CF LA BROCHURE DESCRIPTION DU SUPER-FICHIER
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC  PARIS    OCTOBRE 1988
C.......................................................................
      PARAMETER ( MXFIMS=10 , NBFIMS=6 , MXTAMS=16384 )
      include"./incl/nmproj.inc"
C
C     MXFIMS : NOMBRE MAXIMUM DE FICHIERS DECLARABLES DE
C              LA MEMOIRE SECONDAIRE
C     NBFIMS : NOMBRE INITIAL DE FICHIERS SUPER-FICHIER COMPRIS
C     MXTAMS : NOMBRE MAXIMUM DE TABLEAUX MS DECLARABLES
C
      INTEGER  LDFIMS(2,NBFIMS)
C
C     LES CARACTERISTIQUES DES FICHIERS
C
C     DECLARATION DES FICHIERS DE LA MEMOIRE SECONDAIRE
C     -------------------------------------------------
C     LE SUPER-FICHIER DE 2048 PAGES DE MOPASF MOTS
      LDFIMS(1,1) = 2048
      LDFIMS(2,1) = MOPASF
C     LE 1-ER FICHIER NUMERIQUE DE 16384 PAGES DE 128 MOTS
      LDFIMS(1,2) = 16384
      LDFIMS(2,2) = 128
C     LE 2-ME FICHIER NUMERIQUE DE 16384 PAGES DE 1024 MOTS
      LDFIMS(1,3) = 16384
      LDFIMS(2,3) = 1024
C     LE 3-ME FICHIER NUMERIQUE DE 16384 PAGES DE 8192 MOTS
      LDFIMS(1,4) = 16384
      LDFIMS(2,4) =  8192
C     LE 4-ME FICHIER NUMERIQUE DE 16384 PAGES DE 32768 MOTS
      LDFIMS(1,5) = 16384
      LDFIMS(2,5) = 32768
C     LE 5-ME FICHIER NUMERIQUE DE 32768 PAGES DE 131072 MOTS
      LDFIMS(1,6) = 32768
C     LE NOMBRE MAXIMAL DE MOTS D'UNE PAGE DES FICHIERS DE LA MS
      MXPAFI      = 131072
      LDFIMS(2,6) = MXPAFI
      CALL MSDC( MXFIMS , MXTAMS , NBFIMS , LDFIMS , NMPROJ )
C
C     OUVERTURE DE LA MEMOIRE SECONDAIRE
C     ----------------------------------
      M2ZLMG = 128
      M2ZLMK =  64
      M2ZLMN = 256
      CALL MSOU( MOPASF , M2ZLMG , M2ZLMK , M2ZLMN , MOTMCN )
C
      RETURN
      END
