      SUBROUTINE NMPLSV( NTYOBJ, NUMOBJ,
     %                   KTYOBJ, NOMOBJ, NOMTMS, L1 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETOURNER LE NOM DU TYPE ET LE NOM D'UN PLSVO DEFINI
C -----    PAR SON NUMERO DE TYPE ET NUMERO
C          CONSTRUIRE LE NOM NOMTMS DU TMS SANS LE SUFFIXE
C          EXEMPLE: NOMTMS=~>SURFACE>BASE>
C
C ENTREES:
C --------
C NTYOBJ : NUMERO DU TYPE DU PLSVO DE 1 A 5
C NUMOBJ : NUMERO DU PLSVO DANS SON TYPE
C
C SORTIES:
C --------
C KTYOBJ : NOM DU TYPE DE PLSVO
C NOMOBJ : NOM DU PLSVO
C NOMTMS : NOM DU TABLEAU DANS LES LEXIQUES MEFISTO
C L1     : NUMERO DU CARACTERE DERRIERE LE DERNIER >
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     MARS 1999
C2345X7...........................................................012
      CHARACTER*80   NOMOBJ, NOMTMS
      CHARACTER*10   NMTYOB, KTYOBJ
C
C     LE NOM DU TYPE DE PLSVO
      KTYOBJ = NMTYOB( NTYOBJ )
C
C     RECUPERATION DANS NOMOBJ DU NOM DU PLSV DE TYPE KTYOBJ ET DE NO NUMOBJ
      CALL NMOBNU( KTYOBJ, NUMOBJ, NOMOBJ )
C
C     RECHERCHE DU 1-ER BLANC LE NOM KTYOBJ
      L1 = INDEX( KTYOBJ , ' ' )
      IF( L1 .GT. 0 ) THEN
         L1 = L1 - 1
      ELSE
         L1 = LEN( KTYOBJ )
      ENDIF
C
C     RECHERCHE DU 1-ER BLANC LE NOM NOMOBJ
      L2 = INDEX( NOMOBJ , ' ' )
      IF( L2 .GT. 0 ) THEN
         L2 = L2 - 1
      ELSE
         L2 = LEN( NOMOBJ )
      ENDIF
C
C     LE PREFIXE "PLSV>NOM>"
      NOMTMS = '~>' // KTYOBJ(1:L1) // '>' // NOMOBJ(1:L2) // '> '
C
C     NUMERO DU CARACTERE APRES LE DERNIER >
      L1 = INDEX( NOMTMS, ' ' )
      RETURN
      END
