      SUBROUTINE NU8TGF( NF, NCOGEL, MINNUS, LESENS, NBTF, NUTGFA )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    FOURNIR LES NUMEROS DES NBTF TANGENTES DE LA FACE NF DE
C -----    L'EF VOLUMIQUE DE TYPE NCOGEL AVEC LE SOMMET MINIMAL EN POSITION
C          MINNUS DES SOMMETS DE LA FACE ET UNE EVENTUELLE PERMUTATION
C          DES SOMMETS 2 ET NBSF SELON LA VALEUR DE LESENS
C
C  LE PLUS PETIT NUMERO DE SOMMET EST MIS EN PREMIERE POSITION DE NUSTFA1
C  PUIS LE PLUS PETIT SOMMET PARMI LE SECOND ET LE NBSF-EME

C ENTREES:
C --------
C NF     : NUMERO DE LA FACE DE L'EF VOLUMIQUE DE TYPE NCOGEL
C NCOGEL : CODE GEOMETRIQUE DE L ELEMENT
C          1:POINT 2:SEGMENT 3:TRIANGLE 4:QUADRANGLE
C          5:TETRAEDRE 6:PENTAEDRE 7:HEXAEDRE >7:ERREUR
C MINNUS : INDICE DANS NUSTFA0 DU PLUS PETIT NUMERO DE SOMMET
C LESENS : SI SOMMET 2 < SOMMET NBSF ALORS FACE AVEC LESENS=+1
C          SI SOMMET 2 > SOMMET NBSF ALORS FACE AVEC LESENS=-1
C          ET PERMUTATION POUR QUE NUSTFA(2)<NUSTFA(NBSF)

C SORTIES:
C --------
C NBTF   : NOMBRE DE TANGENTES DE CETTE FACE (6 OU 8)
C NUTGFA : NUMERO DES NBTF TANGENTES DE LA FACE DANS LES TANGENTES
C          DE L'EF VOLUMIQUE ET COMPTE TENU DE MINNUS ET LESENS
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS    DECEMBRE 1996
C2345X7..............................................................012
      include"./incl/sotgfc.inc"
      INTEGER        NUTGFA(NBTF), NUTGF1(8)

C     LE NOMBRE DE SOMMETS DE LA FACE
      NBSF = NBSTFA( NF, NCOGEL )

C     NOMBRE DE TANGENTES DE LA FACE NF DE L'EF DE TYPE NCOGEL
      NBTF = NBTGFA( NF, NCOGEL )

      DO I=1,NBTF
C        NUMERO DE LA TG DANS L'EF VOLUMIQUE
         NUTGFA(I) = NOTGFA( I, NF, NCOGEL )
      ENDDO

C     PERMUTATION DES TANGENTES SUIVANT CELLE DES SOMMETS
C     POUR AMENER LE PLUS PETIT NO DE SOMMET DE LA FACE
C     EN PREMIERE POSITION DE NUTGF1
      NBSF2 = NBSF * 2
      L     = MINNUS * 2
      DO I=2,NBSF2,2
         NUTGF1(I-1) = NUTGFA(L-1)
         NUTGF1(I  ) = NUTGFA(L  )
         L = L + 2
         IF( L .GT. NBSF2 ) L = 2
      ENDDO

      IF( LESENS .LT. 0 ) THEN
C        IL FAUT PERMUTER LES SOMMETS 2 ET NBSF AU NIVEAU DES TGS
         IF( NBSF .EQ. 3 ) THEN
            NUTGFA( 1 ) = NUTGF1( 2 )
            NUTGFA( 2 ) = NUTGF1( 1 )
            NUTGFA( 3 ) = NUTGF1( 6 )
            NUTGFA( 4 ) = NUTGF1( 5 )
            NUTGFA( 5 ) = NUTGF1( 4 )
            NUTGFA( 6 ) = NUTGF1( 3 )
         ELSE
            NUTGFA( 1 ) = NUTGF1( 2 )
            NUTGFA( 2 ) = NUTGF1( 1 )
            NUTGFA( 3 ) = NUTGF1( 8 )
            NUTGFA( 4 ) = NUTGF1( 7 )
            NUTGFA( 5 ) = NUTGF1( 6 )
            NUTGFA( 6 ) = NUTGF1( 5 )
            NUTGFA( 7 ) = NUTGF1( 4 )
            NUTGFA( 8 ) = NUTGF1( 3 )
         ENDIF
      ELSE
C        SIMPLE RECOPIE DANS NUTGFA
         DO I=1,NBSF2
            NUTGFA(I) = NUTGF1(I)
         ENDDO
      ENDIF

      RETURN
      END
