      SUBROUTINE NUPACH( CHAINE , NOPACH )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : RETROUVER LE NUMERO DE LA CONSTANTE CHAINE DE CARACTERES
C ----- ET SINON AJOUT DANS LA TABLE DES CONSTANTES CHAINES
C
C       CF ~LU/GRAMMAIRE DE DEFINITION DU LANGAGE UTILISATEUR
C
C ENTREES :
C ---------
C CHAINE : LA CHAINE DE CARACTERES  PARAMETRE D'UNE FONCTION
C
C SORTIES :
C ---------
C NOPACH : NUMERO DANS LA TABLE DE LA CONSTANTE CHAINE
C          0 SI LA TABLE DES CONSTANTES CHAINES EST SATUREE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN  ANALYSE NUMERIQUE UPMC PARIS    FEVRIER 1990
C23456---------------------------------------------------------------012
      include"./incl/lu.inc"
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      CHARACTER*(*)    CHAINE
C
C     RECHERCHE DE CETTE CONSTANTE DANS LA TABLE
      DO 10 NOPACH=1,NBPACH
         IF( CHAINE .EQ. KPACH(NOPACH) ) THEN
C           CONSTANTE RETROUVEE
            RETURN
         ENDIF
 10   CONTINUE
C
C     AJOUT DE LA CONSTANTE DANS LA TABLE
      IF( NBPACH .GE. MXPACH ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) ='LU: TABLE DES CONSTANTES SATUREE'
         KERR(2) ='LU: AUGMENTER MXPACH DANS LU.INC'
         CALL LEREUR
         NOPACH = 0
         RETURN
      ENDIF
C
C     IL RESTE DE LA PLACE
      NBPACH = NBPACH + 1
      NOPACH = NBPACH
      KPACH( NBPACH ) = CHAINE
      END
