      SUBROUTINE PTFACLIC( NDIM, XYZSOM, NOFACE, NOSOEF,  XYZPT, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETOURNER LES COORDONNEES CARTESIENNES XYZ d'un POINT
C -----    CLIQUE sur LA FACE NOFACE du TABLEAU NOSOEF

C ENTREES:
C --------
C NDIM   : DIMENSION (2 ou 3) DE L'ESPACE DE LA SURFACE
C NBSOM  : NOMBRE DE SOMMETS DU MAILLAGE
C XYZSOM : XYZ 3 COORDONNEES CARTESIENNES DES SOMMETS DU MAILLAGE
C NBFACE : NOMBRE DE TRIANGLES OU QUADRANGLES DU MAILLAGE
C NOFACE : >0 NUMERO DE LA FACE NOSOEF TRIANGLE ou QUADRANGLE DEFINISSANT
C             LE PLAN DE PROJECTION DU POINT CLIQUE
C NOSOEF : NO DES 4 SOMMETS DES TRIANGLES ET/OU QUADRANGLES DU MAILLAGE
C
C SORTIES:
C --------
C XYZPT  : 3 COORDONNEES CARTESIENNES XYZ DU POINT CLIQUE DANS LE PLAN
C          DE LA FACE NOFACE
C IERR   : =0 XYZPT LES XYZ DU POINT CLIQUE DANS LA FACE NOFACE
C          =1 ABANDON DEMANDE. XYZPT N'EST PAS MODIFIE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : Alain PERRONNET Saint PIERRE du PERRAY             Avril 2020
C2345X7..............................................................012
      include"./incl/langue.inc"
      REAL         XYZSOM(3,*)
      INTEGER      NOSOEF(4,*)
      REAL         XYZAX(3,4), XYZAPT(3), XYZPT(3)
      EQUIVALENCE (XYZAX(1,1),X1),(XYZAX(2,1),Y1),
     %            (XYZAX(1,2),X2),(XYZAX(2,2),Y2),
     %            (XYZAX(1,3),X3),(XYZAX(2,3),Y3),
     %            (XYZAX(1,4),X4),(XYZAX(2,4),Y4)
      EQUIVALENCE (XYZAPT(1),XAPT), (XYZAPT(2),YAPT), (XYZAPT(3),ZAPT)

      IF( NOFACE .LE. 0 ) RETURN

C     CLIC d'UNE POSITION NOUVELLE d'UN POINT DANS LA FACE NOFACE
C     -----------------------------------------------------------
      CALL SAIPTC( NOTYEV,  NX, NY, NOCHAR )
      IF( NOTYEV .LE. 0 ) THEN
C         -1 => CARACTERE TAPE AU CLAVIER AVEC NOCHAR
C          0 => ABANDON
         IERR = 1
         GOTO 9999
      ENDIF
      IERR = 0

C     COORDONNEES AXONOMETRIQUES DU POINT CLIQUE EN NX NY PIXELS
C     PAS D'INFORMATION DE LA 3-EME COORDONNEE DANS LA DIRECTION DE VISEE
      XAPT = XOB2PX( NX )
      YAPT = YOB2PX( NY )

C     LE POINT CLIQUE EST SUPPOSE DANS LA FACE NOFACE
C     ou PAS TROP LOIN dans SON PLAN
C     -----------------------------------------------
      IF( NOSOEF(4,NOFACE) .EQ. 0 ) THEN
C        NOFACE EST UN TRIANGLE
         NBS = 3
      ELSE
C        NOFACE EST UN QUADRANGLE
         NBS = 4
      ENDIF
C
C     LES COORDONNEES AXONO DES NBS SOMMETS DE LA FACE NOFACE
      DO NS=1,NBS
C        NUMERO DU SOMMET NS DU TQ NOFACE
         NUST = NOSOEF(NS,NOFACE)
         IF( NDIM .EQ. 2 ) THEN
C           CALCUL DES 3 COORDONNEES DU SOMMET NS
C           A PARTIR DES 3 COORDONNEES XYZSOM DU SOMMET N
            XYZAX(1,NS) = XYZSOM(1,NUST)
            XYZAX(2,NS) = XYZSOM(2,NUST)
            XYZAX(3,NS) = XYZSOM(3,NUST)
          ELSE
C           CALCUL DES 3 COORDONNEES AXONOMETRIQUES XYZAX
C           A PARTIR DES 3 COORDONNEES XYZSOM DU SOMMET NUST
            CALL XYZAXO( XYZSOM(1,NUST), XYZAX(1,NS) )
         ENDIF
      ENDDO

C     CALCUL DES 3 COORDONNEES BARYCENTRIQUES DU POINT (XAPT,YAPT)
C     DANS LE TRIANGLE NOFACE ou LE TRIANGLE 123 DU QUADRANGLE NOFACE
      D   =    (X2-X1 )*(Y3-Y1 )  -  (X3-X1 )*(Y2-Y1)
      CB1 = ( (X2-XAPT)*(Y3-YAPT) - (X3-XAPT)*(Y2-YAPT) ) / D
      CB2 = ( (X3-XAPT)*(Y1-YAPT) - (X1-XAPT)*(Y3-YAPT) ) / D
      CB3 = ( (X1-XAPT)*(Y2-YAPT) - (X2-XAPT)*(Y1-YAPT) ) / D

      IF( NBS .EQ. 3 ) THEN

C        NOFACE EST UN TRIANGLE
C        3-EME COORDONNEE AXONOMETRIQUE DU POINT CLIQUE DANS L'EF
         ZAPT = CB1 * XYZAX(3,1) + CB2 * XYZAX(3,2) + CB3 * XYZAX(3,3)

      ELSE

C        NOFACE EST UN QUADRANGLE
         IF( CB1 .LT. 0.0 .OR. CB1 .GT. 1.0 .OR.
     %       CB2 .LT. 0.0 .OR. CB2 .GT. 1.0 .OR.
     %       CB3 .LT. 0.0 .OR. CB3 .GT. 1.0 ) THEN
C           LE POINT (XAPT,YAPT) N'EST PAS DANS LE TRIANGLE 123
C           du QUADRANGLE NOFACE
C           CALCUL DES 3 COORDONNEES BARYCENTRIQUES DU POINT (XAPT,YAPT)
C           DANS LE TRIANGLE 1 3 4 DU QUADRANGLE NOFACE
            D   =    (X3-X1 )*(Y4-Y1)   -  (X4-X1 )*(Y3-Y1)
            CB1 = ( (X3-XAPT)*(Y4-YAPT) - (X4-XAPT)*(Y3-YAPT) ) / D
            CB2 = ( (X4-XAPT)*(Y1-YAPT) - (X1-XAPT)*(Y4-YAPT) ) / D
            CB3 = ( (X1-XAPT)*(Y3-YAPT) - (X3-XAPT)*(Y1-YAPT) ) / D
C
C           3-EME COORDONNEE AXONOMETRIQUE DU POINT CLIQUE DANS L'EF
            ZAPT = CB1*XYZAX(3,1) + CB2*XYZAX(3,3) + CB3*XYZAX(3,4)
C
         ENDIF
C
      ENDIF
C
C     3 COORDONNEES CARTESIENNES DU POINT CLIQUE DANS LE TRIANGLE OU QUADRANGLE
      IF( NDIM .EQ. 2 ) THEN
         XYZPT(1) = XAPT
         XYZPT(2) = YAPT
         XYZPT(3) = 0
      ELSE
         CALL AXOXYZ( XYZAPT, XYZPT )
      ENDIF


 9999 IF( IERR .EQ. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'ptfaclic: dans la FACE', NOFACE,
     %          ' les XYZ du POINT CLIQUE=', XYZPT
         ELSE
            PRINT*,'ptfaclic: in FACE', NOFACE,
     %             ' the CLICKED POINT XYZ=', XYZPT
         ENDIF
      ENDIF

      RETURN
      END
