      SUBROUTINE QUATRID( NOSOEL, XYZSOM,  QUALIT )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   CALCUL DE LA QUALITE D'UN TRIANGLE DANS R**3 (DOUBLE PRECISION)
C -----   QUALITE: 2 RACINE(3) x RAYON CERCLE INSCRIT
C                / H LONGUEUR DE LA PLUS LONGUE ARETE

C         VERSION AVEC REELS DOUBLE PRECISION

C ENTREES:
C --------
C NOSOEL : NUMERO DES 3 SOMMETS DANS XYZSOM DES SOMMETS DU TRIANGLE
C XYZSOM : 3 COORDONNEES DES SOMMETS DU MAILLAGE

C SORTIE :
C --------
C QUALIT : QUALITE DU TRIANGLE (VALEUR COMPRISE ENTRE 0 ET 1)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE PARIS UPMC       AVRIL 1998
C2345X7..............................................................012
      INTEGER           NOSOEL(1:3)
      DOUBLE PRECISION  XYZSOM(3,*), QUALIT
      DOUBLE PRECISION  XYZS1(3), XYZS2(3), XYZS3(3)

C     LES 3 COORDONNEES DES 3 SOMMETS DU TRIANGLE
      NS1 = NOSOEL(1)
      NS2 = NOSOEL(2)
      NS3 = NOSOEL(3)

      DO K=1,3
         XYZS1(K) = XYZSOM(K,NS1)
         XYZS2(K) = XYZSOM(K,NS2)
         XYZS3(K) = XYZSOM(K,NS3)
      ENDDO

C     CALCUL DE LA QUALITE DU TRIANGLE
      CALL QUATRID3S( XYZS1, XYZS2, XYZS3,  QUALIT )

      RETURN
      END
