       SUBROUTINE RLATAU( NTRL1 , MNRL1 , NAPLUS , MOPLUS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : AUGMENTER LA RELATION NTRL1 AFIN QU'ELLE AIT EN SORTIE
C ----- NAPLUS ATTRIBUTS ET MOPLUS POUR STOCKER LES VALEURS
C***********************************************************************
C ATTENTION : SOUS-PROGRAMME DEPENDANT MACHINE PAR LA DECLARATION DE
C =========== MCK ET MCG
C***********************************************************************
C ENTREE :
C --------
C NTRL1  : NUMERO DU TABLEAU MS DE LA RELATION A AUGMENTER
C          CE NUMERO EST LE MEME EN ENTREE ET SORTIE
C          LE TABLEAU EST OUVERT EN SORTIE
C
C ENTREE ET SORTIE :
C ------------------
C MNRL1  : ADRESSE AVANT ET APRES AUGMENTATION
C
C ENTREE :
C --------
C NAPLUS : NOMBRE D'ATTRIBUTS A AJOUTER
C MOPLUS : NOMBRE DE MOTS A AJOUTER AUX VALEURS DES ATTRIBUTS
C
C ATTENTION : EN SORTIE LE TABLEAU DE NBVAR2 VARIABLES N'EST PAS OUVERT.
C =========== AFIN D' OBTENIR SON ADRESSE EN MC FAIRE
C             CALL TAMSOU( NTRL1 , MNRL1 )
C
C ATTENTION : LES 2 TABLEAUX AVANT ET APRES DOIVENT TENIR SIMULTANEMENT
C =========== DANS MCN OU MCK
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS SEPTEMBRE 1986
C.......................................................................
      include"./incl/ppmck.inc"
      include"./incl/motmcg.inc"
      include"./incl/msvaau.inc"
      include"./incl/pp.inc"
      COMMON             MCN(MOTMCN)
      COMMON / MSSFTA /  MSV1(10),M1TAMS,NSV2(13),MGZLMN,NSV3(4)
      COMMON / UNITES /  LECTEU,IMPRIM,NUNITE(30)
      COMMON / MSIMTA /  NOIMPR
C
      IF( NAPLUS + MOPLUS .LE. 0 ) RETURN
C
C     OUVERTURE DU TABLEAU DE LA RELATION AVANT AUGMENTATION
C     ======================================================
      CALL TAMSOU( NTRL1 , MNRL1 )
C
C     M1RL1   NOMBRE DE MOTS PAR NOM OU ATTRIBUT
      M1RL1  = MCN( MNRL1 )
C     M2RL1   NOMBRE MAXIMAL DE NOMS DE LA RELATION
      M2RL1  = MCN( MNRL1 + 1 )
C     NBENNM  NOMBRE D'ENTIERS POUR STOCKER UN NOM
      NBENNM = MCN( MNRL1 + 2 )
C     ADRESSE DU SOUS TABLEAU DES ATTRIBUTS
      MNAT1  = MNRL1 + M1RL1 * ( 1 + M2RL1 )
C     MXATR1  NOMBRE D'ATTRIBUTS AVANT AUGMENTATION
      MXATR1 = MCN( MNAT1 + 1 )
C     MOATR1  NOMBRE DE MOTS DES VALEURS DES ATTRIBUTS AVANT AUGMENTATIO
      MOATR1 = MCN( MNAT1 + 4 )
C
C     DECLARATION DU TABLEAU AUGMENTE
C     ===============================
      M1RL2  = M1RL1  + MOPLUS
      MXATR2 = MXATR1 + NAPLUS
      MOATR2 = MOATR1 + MOPLUS
      CALL TNMSDC( 'ENTIER' , M1RL2*(2+M2RL1+MXATR2) , NTRL2 )
C
C     OUVERTURE DU TABLEAU AUGMENTE
      CALL TAMSOU( NTRL2 , MNRL2 )
C
C     COPIE DU 1-ER TABLEAU DANS LE SECOND
C     ====================================
      MN1 = MNRL1 - 1
      MN2 = MNRL2 - 1
C
C     LES NOMS
C     --------
      DO 40 I=1,M2RL1 + 1
         DO 20 J=1,M1RL1
            MCN( MN2 + J ) = MCN( MN1 + J )
 20      CONTINUE
         MN1 = MN1 + M1RL1
         MN2 = MN2 + M1RL2
 40   CONTINUE
C
C     LES ATTRIBUTS DECALES
C     ---------------------
      DO 80 I=1,MXATR1+1
         DO 50 J=1,M1RL1
            MCN( MN2 + J ) = MCN( MN1 + J )
 50      CONTINUE
C        LES MOTS AJOUTES DE L'ATTRIBUT
         DO 60 J=M1RL1+1,M1RL2
            MCN( MN2 + J ) = 0
 60      CONTINUE
         MN1 = MN1 + M1RL1
         MN2 = MN2 + M1RL2
 80   CONTINUE
C
C     LES NOUVEAUX ATTRIBUTS
C     ----------------------
      MN2 = MN2 + NBENNM
      DO 100 I=1,NAPLUS
C        LE CHAINAGE SUR LE SUIVANT
         MCN( MN2 ) = I+1
         DO 90 J=1,MOATR2
            MCN( MN2 + J ) = 0
 90      CONTINUE
         MN2 = MN2 + M1RL2
 100  CONTINUE
C
C     LE DERNIER EST CHAINE AVEC LE 1-ER ANCIEN
      MCN( MN2 - M1RL2 ) = MCN( MNAT1 + 6 )
C
C     LE NOUVEAU 1-ER EST LE 1-ER VIDE AJOUTE
      MNAT2 = MNRL2 + M1RL2 * ( 1 + M2RL1 )
      MCN( MNAT2 + 6 ) = MXATR1 + 1
C
C     MISE A JOUR DES VARIABLES MODIFIEES
      MCN( MNRL2     ) = M1RL2
      MCN( MNAT2     ) = M1RL2
      MCN( MNAT2 + 1 ) = MXATR2
      MCN( MNAT2 + 4 ) = MOATR2
C
C     PERMUTATION DES DESCRIPTEURS DES 2 TABLEAUX TAMS
C     PERMISE CAR ILS SONT TOUS LES 2 OUVERTS
C     ================================================
C     DECLARATION OUVERTURE D'UN TABLEAU MC POUR LA PERMUTATION
C     CAR L'ADRESSE DU MG.. PEUT VARIER ENTRE 2 APPELS DE TAMSRE
      CALL TNMCDC( 'ENTIER' , M1TAMS , MNTAMC )
C
C     L'ADRESSE DU DESCRIPTEUR DU TABLEAU NTRL1
      CALL TAMSRE( NTRL1 , MGTAM1 )
C
C     COPIE DE CE DESCRIPTEUR DANS LE TABLEAU AUXILIAIRE
      CALL TRTATA( MCG(MGTAM1) , MCN(MNTAMC) , M1TAMS )
C
C     L'ADRESSE DU DESCRIPTEUR DU TABLEAU NTRL2
      CALL TAMSRE( NTRL2 , MGTAM2 )
C
C     PERMUTATION DU DESCRIPTEUR DU 2ME TABLEAU ET
C     DE LA COPIE DU DESCRIPTEUR DU 1-ER TABLEAU
      DO 10 I=0 , M1TAMS-1
         MN = MCN( MNTAMC + I)
         MCN( MNTAMC + I ) = MCG( MGTAM2 + I )
         MCG( MGTAM2 + I ) = MN
 10   CONTINUE
C
C     L'ADRESSE DU DESCRIPTEUR DU TABLEAU NTRL1
      CALL TAMSRE( NTRL1 , MGTAM1 )
C
C     LA COPIE DU DESCRIPTEUR DU NOUVEAU DANS L'ANCIEN
      CALL TRTATA( MCN(MNTAMC) , MCG(MGTAM1) , M1TAMS )
C
C     DESTRUCTION DU TABLEAU MC AUXILIAIRE
      CALL TAMCDS( 'ENTIER' , M1TAMS , MCG(MGZLMN) , MNTAMC )
C
C     DESTRUCTION DE L'ANCIEN TABLEAU MS EN POSITION NTRL2
      CALL TAMSDS( NTRL2 )
C
C     FERMETURE DU TABLEAU NTRL1
      CALL TAMSFE( NTRL1)
C
      IF( NOIMPR .NE. 0 ) WRITE(IMPRIM,19900) NTRL1,NAPLUS,
     %                    MNRL1,MNRL2
19900 FORMAT(' SP RLATAU:LA RELATION',I9,
     %' PASSE A',I9,' VARIABLES ENTIERES'/
     %' SON ADRESSE',I8,' DEVIENT',I8/)
C
C     LA NOUVELLE ADRESSE DU TABLEAU AUGMENTE
      CALL TAMSOU( NTRL1 , MNRL1 )
C
      END
