      SUBROUTINE SEARCLIC( XYZSOM, L1ARET, L2ARET, LARETE,  NUARPRCL )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    A PARTIR DES ITEMS ARETES VISIBLES SUR L'ECRAN GRAPHIQUE
C -----    SELECTIONNER A L'AIDE D'UN CLIC SOURIS UN ARETE DU MAILLAGE
C          PRESENT DANS LA FENETRE GRAPHIQUE C-A-D
C          RETOURNER LE NUMERO NUARPRCL DE L'ARETE VISIBLE LA PLUS PROCHE
C          DU POINT CLIQUE DANS UN MAILLAGE 3D

C ENTREES:
C --------
C XYZSOM : XYZ les 3 COORDONNEES CARTESIENNES DES ARETES DU MAILLAGE
C L1ARET : NOMBRE DE MOTS PAR ARET DU TABLEAU LARETE
C L2ARET : NOMBRE DE FACES DU TABLEAU LARETE
C LARETE : LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR L'ARETE SUIVANTE
C          LARETE(4:3+MXFAAR,I)= NO NOSOFA DE LA FACE CONTENANT L'ARETE
C          SI UNE ARETE APPARTIENT A PLUS DE MXFAAR FACES, 
C          LE NUMERO DE FACE MXFAAR EST RENDU NEGATIF POUR INDIQUER
C          QUE LA LISTE DES FACES EST INCOMPLETE

C SORTIES:
C --------
C NUARPRCL: >0 NUMERO DE L'ARETE VISIBLE LA PLUS PROCHE DU POINT CLIQUE
C              NUARPRCL=MCN(MNITEMS+MCN(MNITEMS)*ITARPRCL+3)
C              EST L'INDICE DANS LE TABLEAU LARETE
C           =0 SI PAS D'ITEM ARETE PROCHE OU ABANDON DEMANDE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : Alain PERRONNET  Saint PIERRE du PERRAY          Janvier 2021
C2345X7..............................................................012
      include"./incl/langue.inc"
      include"./incl/trvari.inc"
      include"./incl/mecoit.inc"
      include"./incl/pp.inc"
      REAL          RMCN(MOTMCN)
      COMMON         MCN(MOTMCN)
      EQUIVALENCE  (RMCN(1),MCN(1))

      COMMON /LECLXQ/LECLEX
      INTEGER        LARETE(L1ARET,L2ARET)
      REAL           XYZSOM(3,*)
      CHARACTER*20   KTITRE

C     LES ITEMS ARETES VISIBLES SONT SUR L'ECRAN
      LECLEX = 6

      ITARPRCL= 0
      NXCL    = -1
      NYCL    = -1
      NUARPRCL0= 0
      NUARPRCL = 0
      DISTMI  = 1E28

C     POUR INVITE le TRACE DU MAILLAGE + LES ITEMS ARETES VISIBLES
      IF( LANGAG .EQ. 0 ) THEN
         KTITRE='CLIQUER une ARETE'
      ELSE
         KTITRE='CLICK an EDGE'
      ENDIF
      CALL SANSBL( KTITRE, NBC )
      CALL TRFINS( KTITRE(1:NBC) )

C     ACTIVATION DE LA SAISIE A LA SOURIS ou FRAPPE AU CLAVIER
C     SAISIE D'UN CLIC (NX,NY) DE LA SOURIS 
C     ou UN DEPLACEMENT du POINTEUR de la SOURIS
C     ou d'UN CARACTERE AU CLAVIER
C     --------------------------------------------------------
 10   CALL XVSOURIS( NOTYEV, NOBOCA, NX, NY )
C     RETOURNE NOTYEV QUI VAUT
C     = 0 Si ABANDON demande par clic du bouton 2 de la souris
C         ou par frappe de la touche Echappement ou @
C     = 1 Si CLIC ENFONCE et RELACHE D'UN BOUTON DE LA SOURIS
C         => NX, NY et NOBOCA=NUMERO DU BOUTON ENFONCE RELACHE
C     =-1 Si CLIC SEULEMENT ENFONCE  D'UN BOUTON DE LA SOURIS
C         => NX, NY et NOBOCA=NUMERO DU BOUTON ENFONCE
C     =-2 Si le POINTEUR de la SOURIS A BOUGE SANS BOUTON ENFONCE
C         => NX, NY
C     = 2 Si FRAPPE D'UN CARACTERE AU CLAVIER
C         => NOBOCA=NUMERO DU CARACTERE DANS LA TABLE ASCII

      IF( NOTYEV .EQ. 2 ) THEN
C        CARACTERE de NUMERO ASCII NOBOCA TAPE AU CLAVIER
         IF( NOBOCA .EQ. 27 ) THEN
cccC        LE CARACTERE 'ECHAPPEMENT' DEVIENT LE CARACTERE '@'
ccc         NOBOCA = 64
            NOTYEV = 0
            GOTO 12
         ELSE
            GOTO 10
         ENDIF
      ENDIF

 12   IF( NOTYEV .EQ. 0 ) THEN
C        ABANDON DE LA RECHERCHE DE L'ARETE CLIQUE
         ITARPRCL = 0
         NUARPRCL = 0
         NXCL = -1
         NYCL = -1
         GOTO 9999
      ENDIF

C     Ici: NOTYEV=1 ou -1 ou -2
C     LE CLIC DANS L'ECRAN GRAPHIQUE (NX,NY) EN PIXELS
C     RECHERCHE DE LA PLUS PROCHE ARETE DU CLIC PARMI LES ITEM ARETES
C     ---------------------------------------------------------------
      CALL SETACLIC( XYZSOM, L1ARET, L2ARET, LARETE,
     %               NX,     NY,     NUARPRCL )
      IF( NUARPRCL .EQ. 0 ) GOTO 10

C     L'ARETE LA PLUS PROCHE DU POINT CLIQUE EST NUARPRCL
C     ---------------------------------------------------
      IF( NUARPRCL0 .GT. 0 .AND. NUARPRCL0 .NE. NUARPRCL ) THEN
C        RESTAURATION DES PIXELS DE LA FENETRE PIXELS MEFISTO
C        SAUVEGARDEE JUSTE AVANT LES MODIFICATIONS
         CALL RESTAUREMEMPX
         CALL MEMPXFENETRE
         CALL XVVOIR
      ENDIF

C     TRACE DE L'ITEM ARETE 'NOST1' 'NOST2'
C     -------------------------------------
C     LES 2 SOMMETS DE L'ARETE NUARPRCL
      NOST1 = LARETE(1,NUARPRCL)
      NOST2 = LARETE(2,NUARPRCL)
      CALL XVEPAISSEUR( 4 )
      CALL TRARET3D( NCROUG, -1, NOST1, NOST2, XYZSOM )
      CALL TRFINS( KTITRE(1:NBC) )
      NUARPRCL0 = NUARPRCL

      IF( NOTYEV .LT. 0 ) THEN
         GOTO 10
      ENDIF


C     Ici: NOTYEV = 1  NOBOCA EST LE BOUTON CLIQUE et RELACHE
C                 =>   l'ARETE NUARPRCL CLIQUEE EST SELECTIONNEE
C     ==========================================================
cccC     ADRESSE PIXELS NXCL NYCL SUR L'ECRAN DE L'ARETE NUARPRCL CLIQUEE
cccC     L'ADRESSE MCN DE L'ITEMAR ITARPRCL
ccc      MNIT = MNITAR + MCN(MNITAR) * ITARPRCL

      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'searclic: ARETE CLIQUE: NoAr=',NUARPRCL,
     %          ' X=',XYZSOM(1,NUARPRCL),' Y=',XYZSOM(2,NUARPRCL),
     %          ' Z=',XYZSOM(3,NUARPRCL)
      ELSE
         PRINT*,'searclic: CLICKED EDGE: NoAr=',NUARPRCL,
     %          ' X=',XYZSOM(1,NUARPRCL),' Y=',XYZSOM(2,NUARPRCL),
     %          ' Z=',XYZSOM(3,NUARPRCL)
      ENDIF

 9999 RETURN
      END
