      SUBROUTINE SSARCH( NS,     L1ARCH,
     %                   NBARCH, N1ARCH, NSARCH, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SUPPRIMER UN SOMMET ET DONC UNE ARETE DANS LE CHAINAGE DES
C -----    ARETES . ATTENTION CE SOMMET DOIT APPARTENIR A 2 ARETES
C
C ENTREES:
C --------
C NS     : NUMERO DANS XYZST DU SOMMET A SUPPRIMER
C
C MODIFIES :
C ----------
C L1ARCH : NUMERO DANS NSARCH DE LA PREMIERE ARETE DU CHAINAGE
C NBARCH : NOMBRE D'ARETES CHAINEES DANS NSARCH
C N1ARCH : NUMERO DANS NSARCH DE LA PREMIERE ARETE VIDE
C NSARCH : NUMERO DES 2 SOMMETS DE L'ARETE, ARETE PRECEDENTE ET SUIVANTE
C IERR   : 0 SI PAS D'ERREUR DETECTEE
C          1 LE SOMMET N'APPARTIENT PAS A 2 ARETES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS     FEVRIER 1995
C2345X7..............................................................012
      include"./incl/gsmenu.inc"
      INTEGER        NSARCH(4,*)
C
C     DEBUT DU CHAINAGE
      L = L1ARCH
 10   IF( L .GT. 0 ) THEN
         IF( NS .EQ. NSARCH(1,L) ) THEN
            NA1 = L
            NS1 = NSARCH(2,L)
            GOTO 20
         ELSE IF( NS .EQ. NSARCH(2,L) ) THEN
            NA1 = L
            NS1 = NSARCH(1,L)
            GOTO 20
         ENDIF
C        PASSAGE A L'ARETE SUIVANTE
         L = NSARCH(4,L)
         GOTO 10
      ENDIF
      GOTO 9900
C
C     RECHERCHE DE LA SECONDE ARETE DE SOMMET NS
 20   L = NSARCH(4,L)
C
 25   IF( L .GT. 0 ) THEN
         IF( NS .EQ. NSARCH(1,L) ) THEN
            NA2 = L
            NS2 = NSARCH(2,L)
            GOTO 30
         ELSE IF( NS .EQ. NSARCH(2,L) ) THEN
            NA2 = L
            NS2 = NSARCH(1,L)
            GOTO 30
         ENDIF
C        PASSAGE A L'ARETE SUIVANTE
         L = NSARCH(4,L)
         GOTO 25
      ENDIF
      GOTO 9900
C
C     LE SOMMET APPARTIENT A 2 ARETES  DE SOMMETS NS1 NS2
C     LA SECONDE ARETE EST SUPPRIMEE
 30   NAVANT = NSARCH(3,NA2)
      NAPRES = NSARCH(4,NA2)
C     IL Y A TOUJOURS UNE ARETE AVANT NA2 D'APRES SA DECOUVERTE
      NSARCH(4,NAVANT) = NAPRES
      IF( NAPRES .GT. 0 ) NSARCH(3,NAPRES) = NAVANT
C     TEMOIN DE SUPPRESSION DE L'ARETE NA2
      NSARCH(1,NA2) = 0
C     REMARQUE: NA2 NE PEUT ETRE L1ARCH CAR C'EST LA SECONDE ARETE
C               RETROUVEE DANS NSARCH
C     LA PREMIERE ARETE A POUR SOMMETS NS1 NS2
      NSARCH(1,NA1) = NS1
      NSARCH(2,NA1) = NS2
C     LES CHAINAGES DE NA1 RESTENT INCHANGES
C
C     L'ARETE NA2 EST CHAINEE AUX ARETES VIDES DE NSARCH
      NSARCH(4,NA2) = N1ARCH
      N1ARCH = NA2
      NBARCH = NBARCH - 1
      RETURN
C
C     LE SOMMET N'APPARTIENT PAS A 2 ARETES
 9900 IERR = 1
      RETURN
      END
