      SUBROUTINE TAMCMX( KTYPE , REZLMC , MAXVAR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : RETOURNER EN FONCTION DU TYPE LE NOMBRE MAXIMAL DE VARIABLES
C ----- CONTIGUES DE LA PLUS GRANDE ZONE LIBRE DU SUPER-TABLEAU
C
C ENTREE :
C --------
C KTYPE  : NOM DU TYPE DES VARIABLES DU TABLEAU SELON
C          LOGIQUE  CARACTERE  ENTIER/2  ENTIER  REEL  REEL2  REEL4
C          COMPLEXE  COMPLEXE2
C REZLMC : TABLEAU REPERTOIRE DES ZONES LIBRES DANS MC
C          REZLMC(1,0)=VALEUR MAXIMALE DU 2-EME INDICE DU TABLEAU REZLMC
C                      OU NOMBRE MAXIMAL DE ZONES LIBRES PERMISES
C                      DANS LE SUPER-TABLEAU
C          REZLMC(2,0)=VALEUR DU 2-EME INDICE DE REZLMC DESIGNANT LA
C                      1-ERE ZONE LIBRE.DEPART DU CHAINAGE ZONES LIBRES
C          REZLMC(3,0)=NUMERO DE LA 1-ERE COLONNE DE REZLMC NON OCCUPEE
C                      PAR UNE ZONE LIBRE.CHAINAGE DES COLONNES NON
C                      OCCUPEES DE REZLMC
C          POUR N COMPRIS ENTRE 1 ET REZLMC(1,0)
C          REZLMC(1,N)=ADRESSE MOT         DE LA N-EME ZONE LIBRE DE MC
C          REZLMC(2,N)=NOMBRE  DE MOTS     DE LA N-EME ZONE LIBRE DE MC
C          REZLMC(3,N)=CHAINAGE SUCCESSEUR DE LA N-EME ZONE LIBRE DE MC
C
C SORTIE :
C --------
C MAXVAR : NOMBRE DE VARIABLES DE TYPE KTYPE CONTIGUES DANS LA PLUS
C          GRANDE ZONE LIBRE DU SUPER-TABLEAU
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  NOVEMBRE 1983
C.......................................................................
      CHARACTER*(*)     KTYPE
      INTEGER           REZLMC(3,0:*)
C
C     CHAINAGE SUR LES ZONES LIBRES DU SUPER-TABLEAU
      MCLIBR = 0
      MAXVAR = 0
      NZONE  = REZLMC(2,0)
C
C     LA BOUCLE SUR LES ZONES LIBRES
C     ==============================
C
 10   IF( NZONE .NE. 0 ) THEN
C
C        NZONE EST UNE ZONE LIBRE
         IF( MAXVAR .LT. REZLMC(2,NZONE) ) THEN
C
C           CETTE ZONE LIBRE EST LE MAXIMUM ACTUEL
            MCLIBR = REZLMC(1,NZONE)
            MAXVAR = REZLMC(2,NZONE)
         ENDIF
C
C     PASSAGE A LA ZONE LIBRE SUIVANTE
      NZONE = REZLMC(3,NZONE)
      GOTO 10
C
C     FIN DE LA BOUCLE SUR LES ZONES LIBRES
C     =====================================
C
      ELSE
C
C        MCLIBR EST ELLE UNE BONNE FRONTIERE DE MOT POUR LE TYPE KTYPE
         NUMTYV = NUMTYP( KTYPE )
         MAXVAR = MAXVAR - MODECA( NUMTYV , MCLIBR )
         IF( MAXVAR .LT. 0 ) MAXVAR = 0
      ENDIF
C
C     TRANSFORMATION DU NOMBRE DE MOTS EN NOMBRE DE VARIABLES
      MAXVAR = INT( MAXVAR * VAR1MO( NUMTYV ) )
C
      RETURN
      END
