      SUBROUTINE TAMCLE( NOFISY , N1PAGE , MOPAFI , MOTABL , NTABL )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : LECTURE D'UN TABLEAU NTABL A PARTIR DE LA PAGE N1PAGE
C ----- DU FICHIER NOFISY D'ACCES DIRECT
C
C ENTREES :
C ---------
C NOFISY : NUMERO LOGIQUE DU FICHIER A LIRE
C MOPAFI : NOMBRE DE MOTS DE CHAQUE PAGE DU FICHIER NOFISY
C MOTABL : NOMBRE DE MOTS DU TABLEAU NTABL A LIRE
C
C SORTIE :
C -------
C NTABL  : LE TABLEAU A LIRE SUR LE FICHIER
C
C ENTREE ET SORTIE :
C ------------------
C N1PAGE : EN ENTREE NUMERO DE LA 1-RE PAGE DU TABLEAU
C          EN SORTIE NUMERO DE LA DERNIERE PAGE DU TABLEAU
C          LES PAGES DU TABLEAU SONT SUPPOSEES SEQUENTIELLES SUR
C          LE FICHIER NOFISY
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  DECEMBRE 1983
C.......................................................................
      INTEGER NTABL(MOTABL)
C
C     LE NOMBRE DE PAGES DU TABLEAU NTABL ET LE NOMBRE MOPERD DE
C     MOTS PERDUS DANS LA DERNIERE PAGE
      CALL NBPATA( MOTABL , MOPAFI , NBPAGE , MOPERD )
C
C     L'ADRESSE DANS NTABL DU 1-ER MOT LU DE LA 1-RE PAGE
      MCT = 1
C
C     PROTECTION DE MOPAFI
      MOPAFS = MOPAFI
C
C     LA BOUCLE SUR LES PAGES A LIRE
      DO 10 I=1,NBPAGE
C
C        LES MOPERD MOTS PERDUS DE LA DERNIERE PAGE NE SONT PAS LUS
         IF( I .EQ. NBPAGE ) MOPAFS = MOPAFS - MOPERD
C
C        LECTURE DE LA PAGE I DU TABLEAU
         CALL FIPALE( NOFISY , N1PAGE , MOPAFS , NTABL( MCT ) )
C
C        L'ADRESSE DE LA PAGE SUIVANTE DU TABLEAU NTABL
         MCT = MCT + MOPAFS
C
C        LE NUMERO DE LA PAGE SUIVANTE DU TABLEAU SUR LE FICHIER
         N1PAGE = N1PAGE + 1
 10   CONTINUE
C
      RETURN
      END
