      SUBROUTINE TAMSEC( RETAMS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : ECRITURE DU TABLEAU MS DECRIT PAR LES 6 ENTIERS DU TABLEAU
C ----- RETAMS A PARTIR DU SUPER-TABLEAU MCN OU MCK
C
C ENTREES :
C ---------
C RETAMS : LE DESCRIPTEUR DU TABLEAU MS A ECRIRE
C RETAMS(1)=NTTAMS NO DU TYPE DU TABLEAU MS
C                  0 SI LE TABLEAU N EST PAS DECLARE
C RETAMS(2)=NVTAMS NOMBRE DE VARIABLES DU TABLEAU MS
C RETAMS(3)=NFTAMS NUMERO DU FICHIER MS (1 A M2FIMS) DU TABLEAU MS
C                  0 SI NON DECLARE
C RETAMS(4)=N1TAMS NUMERO DE LA PREMIERE PAGE DU TABLEAU SUR
C                  LE FICHIER NFTAMS QUI LE SAUVEGARDE
C RETAMS(5)=MCTAMS ADRESSE MC DU PREMIER MOT DU TABLEAU MS
C                  >0 LE TABLEAU EST OUVERT( VERROUILLE ) EN MC
C                     IL EST PRET A ETRE UTILISE
C                     IL NE PEUT ETRE SAUVEGARDE SUR SON FICHIER
C                     TANT QU IL N EST PAS FERME
C                  =0 LE TABLEAU N EST PAS EN MC
C                     IL EST DECLARE MAIS PAS OUVERT
C                  <0 LE TABLEAU EST FERME,SUSCEPTIBLE
C                     D ETRE SAUVEGARDE SUR SON FICHIER MS
C                     IL EST UTILISABLE SEULEMENT S IL EST REOUVERT
C RETAMS(6)=LSTAMS CHAINAGE AVAL DES TABLEAUX MS LIBRES OU FERMES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  DECEMBRE 1983
C.......................................................................
      include"./incl/motmcg.inc"
      include"./incl/msvaau.inc"
      include"./incl/ppmck.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      INTEGER           RETAMS(6)
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      COMMON / MSSFTA / NOFISF,NBPASF,MOPASF,MGBUSF,NSFLIB,
     %                  M1FIMS,M2FIMS,MGFIMS,NSFIMS,LPFIMS,
     %                  M1TAMS,M2TAMS,MGBUTA,NBBUTA,NPTAMS,NATAMS,
     %                  NBCTMS,LLTAMS,LFTAMS,MGNPSF,NSFNPS,NPSNPS,
     %                  MGZLMG,MGZLMK,MGZLMN,MOTSMG,MOTSMK,MOTSMN,NTADAM
C
C     LE NOMBRE DE MOTS DU TABLEAU
      MOTABL = MOTTAB( RETAMS(1) , RETAMS(2) )
C
C     LE NUMERO DU FICHIER MS
      NFTAMS = RETAMS(3)
C
C     LE NOMBRE DE MOTS D'UNE PAGE DE CE FICHIER
      IGF    = MGFIMS + M1FIMS * ( NFTAMS - 1 )
      MOPAFI = MCG( IGF + 2 )
C
C     LE NOMBRE DE PAGES ET DE MOTS PERDUS DE LA DERNIERE PAGE
C     DU TABLEAU A ECRIRE
      CALL NBPATA( MOTABL , MOPAFI , NBPAGE , MOPERD )
C
C     LE NUMERO DE LA PREMIERE PAGE
      NOPAGE = RETAMS(4)
C
C     L'ADRESSE MC DU PREMIER MOT DU TABLEAU
      MCT    = ABS( RETAMS(5) )
C
C     LA BOUCLE SUR LES PAGES A ECRIRE
      DO 10 I=1,NBPAGE
C
C        LES MOPERD MOTS PERDUS DE LA DERNIERE PAGE NE SONT PAS ECRITS
         IF( I .EQ. NBPAGE ) MOPAFI = MOPAFI - MOPERD
C
C        ECRITURE DE LA PAGE I DU TABLEAU
C        SELON LE TYPE DU TABLEAU
         IF( RETAMS(1) .EQ. NOTYPK) THEN
C           TABLEAU DE CARACTERES
            CALL FIPAEK( MCG( IGF ) , NOPAGE , MOPAFI , MCK( MCT ) )
         ELSE
            CALL FIPAEC( MCG( IGF ) , NOPAGE , MOPAFI , MCN( MCT ) )
         ENDIF
C
C        L'ADRESSE MC DE LA PAGE SUIVANTE DU TABLEAU EN MC
         MCT = MCT + MOPAFI
C
C        LE NUMERO DE LA PAGE SUIVANTE DU TABLEAU SUR LE FICHIER
         CALL FIPASU( NOPAGE , MCG(IGF) , NOPAGE )
         NOPAGE = MCG( NOPAGE )
 10   CONTINUE
C
      RETURN
      END
