      SUBROUTINE TAMSRE( NOTAMS , MGTAMS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : RETROUVER LE TABLEAU NOTAMS DANS LE REPERTOIRE PAGINE RETAMS
C ----- PLUS PRECISEMENT L'ADRESSE MCG DU 1-ER MOT DU DESCRIPTEUR
C       RETAMS(1..6,NOTAMS)
C
C ENTREE :
C --------
C NOTAMS : NO DU TABLEAU DANS LE TABLEAU RETAMS ( NO COLONNE RETAMS )
C
C SORTIES :
C ---------
C MGTAMS : ADRESSE MCG DU PREMIER MOT DES DESCRIPTEURS DU TABLEAU MS
C          NOTAMS ( RETAMS(1..6,NOTAMS) AVEC LA PAGINATION )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  NOVEMBRE 1983
C.......................................................................
      include"./incl/motmcg.inc"
      include"./incl/ppmck.inc"
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / MSSFTA / NOFISF,NBPASF,MOPASF,MGBUSF,NSFLIB,
     %                  M1FIMS,M2FIMS,MGFIMS,NSFIMS,LPFIMS,
     %                  M1TAMS,M2TAMS,MGBUTA,NBBUTA,NPTAMS,NATAMS,
     %                  NBCTMS,LLTAMS,LFTAMS,MGNPSF,NSFNPS,NPSNPS,
     %                  MGZLMG,MGZLMK,MGZLMN,MOTSMG,MOTSMK,MOTSMN,NTADAM
      SAVE              NOBUFF
      CHARACTER*16      ERREUR
      DATA              ERREUR / 'ERREUR TAMSRE :' /
      DATA              NOBUFF / 1 /
C
C     LE NUMERO DU TABLEAU NOTAMS EST-IL COMPRIS ENTRE 1 ET M2TAMS
      IF( NOTAMS .LE. 0 .OR. NOTAMS .GT. M2TAMS ) THEN
C
C             ERREUR
         WRITE(IMPRIM,10000) ERREUR,NOTAMS,M2TAMS
         CALL ARRET(100)
10000 FORMAT(A16,' NUMERO DE TABLEAU MS=',I12,' NON COMPRIS ENTRE 1 ET'
     %,I12/)
      ENDIF
C
C     LE NUMERO DE LA PAGE RETAMS DU TABLEAU MS NOTAMS
      NOPAG  = NOTAMS / NBCTMS
C
C     LE DECALAGE DANS LA PAGE
      NBCDEC = NOTAMS - NOPAG * NBCTMS
C
C     LA CORRECTION SI NOTAMS EST UN MULTIPLE DE NBCTMS OU NON
      IF( NBCDEC .EQ. 0 ) THEN
         NBCDEC = NBCTMS
      ELSE
         NOPAG  = NOPAG + 1
      ENDIF
C
C     LA PAGE EST-ELLE DANS UN DES BUFFERS PRESENTS DANS MG?
C     ======================================================
C
      IGB = MGBUTA + 3 * NOBUFF - 3
      DO 10 I=1,NBBUTA
         IF( MCG(IGB+1) .EQ. NOPAG ) GOTO 40
         NOBUFF = NOBUFF + 1
         IF( NOBUFF .GT. NBBUTA ) THEN
C           LE BUFFER SUIVANT EST LE PREMIER (STRUCTURE DE TORE)
            NOBUFF = 1
            IGB    = MGBUTA
         ELSE
C           LE BUFFER SUIVANT
            IGB    = IGB + 3
         ENDIF
 10   CONTINUE
C
C     ICI LA PAGE N'A PAS ETE RETROUVEE
C     LA PAGE DE PLUS PETIT NUMERO D APPEL EST SAUVEGARDEE SUR SF
      MINI = NATAMS
      IGB  = MGBUTA
      DO 20 I=1,NBBUTA
C        LE BUFFER I A-T-IL DEJA ETE UTILISE ?
         IF( MCG(IGB+1) .LE. 0 ) THEN
C           NON:CE BUFFER RECOIT LA PAGE A LIRE SUR LE SUPER-FICHIER
            NOBUFF = I
            GOTO 30
         ENDIF
C        OUI:CE BUFFER A-T-IL LE PLUS PETIT NUMERO D'APPEL ?
         IF( MCG( IGB + 2 ) .LT. MINI ) THEN
            MINI   = MCG( IGB + 2 )
            NOBUFF = I
         ENDIF
      IGB = IGB + 3
 20   CONTINUE
C
C     SAUVEGARDE DU BUFFER NOBUFF SUR LE SUPER-FICHIER
      IGB = MGBUTA + 3 * NOBUFF - 3
      CALL FIPAEC( NOFISF , MCG(MGNPSF+MCG(IGB+1)-1) , MOPASF ,
     %             MCG( MCG(IGB) )    )
C
C     RESTAURATION DE LA PAGE NOPAG DANS LE BUFFER NOBUFF
 30   CALL FIPALE( NOFISF , MCG(MGNPSF+NOPAG-1) , MOPASF ,
     %             MCG( MCG(IGB) )    )
C
C     MISE A JOUR DU NUMERO DE PAGE DANS LE BUFFER
      MCG( IGB + 1 ) = NOPAG
C
C     MISE A JOUR DU NUMERO D APPEL TOTAL A RETAMS
 40   NATAMS = NATAMS + 1
C
C     MISE A JOUR DU NUMERO D APPEL DU BUFFER NOBUFF
      MCG( IGB + 2 ) = NATAMS
C
C     L ADRESSE MCG DU 1-ER MOT DU TABLEAU RETAMS(NOTAMS)
      MGTAMS = MCG(IGB) + M1TAMS * ( NBCDEC - 1 )
      RETURN
      END
