      SUBROUTINE TNMCDC( KTYPE , NBVARI , MNTABL )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : DECLARER UN TABLEAU MC DE NBVARI VARIABLES DE TYPE KTYPE
C -----
C
C ENTREES :
C ---------
C KTYPE  : NOM DU TYPE DES VARIABLES DU TABLEAU
C          LOGIQUE  ENTIER/2  ENTIER  REEL REEL2 REEL4  COMPLEXE
C          COMPLEXE2
C NBVARI : NOMBRE DE VARIABLES DU TABLEAU MC A DECLARER
C
C ENTREE ET SORTIE :
C ------------------
C MNTABL : 0   EN ENTREE => ARRET SI PAS ASSEZ DE PLACE OU DE ZONE LIBRE
C          /=0           => RETOUR AU PROGRAMME APPELANT EN CAS D ERREUR
C          > 0 EN SORTIE => ADRESSE MCN DU 1-ER MOT DU TABLEAU NUMERIQUE
C          =<0           => PAS ASSEZ DE PLACE OU DE ZONES LIBRES MCN
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PERRONNET ALAIN ANALYSE NUMERIQUE PARIS  DECEMBRE 1983
C.......................................................................
      include"./incl/motmcg.inc"
      CHARACTER*(*)     KTYPE
      COMMON / MSSFTA / NOFISF,NBPASF,MOPASF,MGBUSF,NSFLIB,
     %                  M1FIMS,M2FIMS,MGFIMS,NSFIMS,LPFIMS,
     %                  M1TAMS,M2TAMS,MGBUTA,NBBUTA,NPTAMS,NATAMS,
     %                  NBCTMS,LLTAMS,LFTAMS,MGNPSF,NSFNPS,NPSNPS,
     %                  MGZLMG,MGZLMK,MGZLMN,MOTSMG,MOTSMK,MOTSMN,NTADAM
C
C     LA DECLARATION PROPREMENT DITE DU TABLEAU
      CALL TAMCDC( KTYPE , NBVARI , MCG(MGZLMN) , MNTABL )
C
      RETURN
      END
