      SUBROUTINE TRCOPL( COSMAXPL, XYZSOM, NA, NTR, M1TRIA, NOTRIA,
     %                   L1ARET, L2ARET, LARETE, NTRADJ )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE NUMERO DU TRIANGLE ADJACENT NTRADJ A
C -----    L'ARETE NA DU TRIANGLE NTR S'IL Y EST COPLANAIRE
C          ET SINON ZERO
C ENTREES:
C --------
C COSMAXPL:COSINUS DE L'ANGLE DIEDRE ENTRE LES 2 PLANS DES TRIANGLES
C          AU DESSOUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES NON-COPLANAIRES
C XYZSOM : XYZ DES SOMMETS DE LA TRIANGULATION
C NA     : NUMERO 1 A 3 DE L'ARETE DU TRIANGLE NTR
C NTR    : NUMERO DU TRIANGLE DANS LE TABLEAU NOTRIA
C M1TRIA : =4 NOTRIA= NoSommet1  NoSommet2  NoSommet3 0 POUR CHAQUE TRIANGLE
C          =6 NOTRIA= NoSommet1  NoSommet2  NoSommet3 +
C                     NoTriaAd1  NoTriaAd2  NoTriaAd3   POUR CHAQUE TRIANGLE
C NOTRIA : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES TRIANGLES

C Les 3 PARAMETRES CI-DESSOUS N'ONT PAS A ETRE INITIALISES SI M1TRIA=6
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU NARET
C L2ARET : NOMBRE DE ARETES DU TABLEAU NARET
C LARETE : TABLEAU DES ARETES DU MAILLAGE
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE

C SORTIE :
C --------
C NTRADJ : > 0 NUMERO DANS NOTRIA DU TRIANGLE COPLANAIRE ADJACENT
C              A L'ARETE NA DE NTR
C          = 0 SI PAS DE TRIANGLE ADJACENT ou PAS COPLANAIRE
C          =-1 SI M1TRIA NE VAUT PAS 4 ou 6
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET  Saint Pierre du Perray              Mars 2020
C....................................................................012
      INTEGER  NOTRIA(M1TRIA,*), LARETE(L1ARET,L2ARET)
      REAL     XYZSOM(3,*)

      NTRADJ = 0

C     NUMERO DU SOMMET NA DU TRIANGLE NTR
      NST = NOTRIA( NA, NTR )

      IF( NST .LE. 0 ) GOTO 9999

C     LES 2 TRIANGLES ADJACENTS D'ARETE NA DE NTR SONT ILS COPLANAIRES?
      IF( M1TRIA .EQ. 6 ) THEN

C        NO NOTRIA DU TRIAGLE ADJACENT A L'ARETE NA DE NTR
         NTRADJ = NOTRIA( 3+NA, NTR )

      ELSE IF( M1TRIA .EQ. 4 ) THEN

C        RECHERCHE DU TRIANGLE AJACENT A NTR PAR L'ARETE NA
         CALL NUQTADAR( NA,  NTR, NOTRIA, L1ARET, L2ARET, LARETE,
     %                  NAR, NTRADJ )
         IF( NTRADJ .EQ. 0 ) THEN
C           ARETE SANS ou TROP DE TRIANGLES ADJACENTS
            GOTO 9999
         ENDIF

      ELSE

C        PAR DEFAUT
         NTRADJ = 0
         GOTO 9999

      ENDIF

C     LE NUMERO DES SOMMETS DE NTR EN PARTANT DE SON ARETE NA
      IF( NA .EQ. 3 ) THEN
         N2 = 1
      ELSE
         N2 = NA+1
      ENDIF
      IF( N2 .EQ. 3 ) THEN
         N3 = 1
      ELSE
         N3 = N2+1
      ENDIF
      NS1 = NOTRIA( NA, NTR )
      NS2 = NOTRIA( N2, NTR )
      NS3 = NOTRIA( N3, NTR )

C     RECHERCHE DU NO NS4 DU SOMMET DE NTRADJ NON SOMMET DE NTR
      DO K=1,3

         NS4 = NOTRIA( K, NTRADJ )
         IF( NS4.NE.NS1 .AND. NS4.NE.NS2 .AND. NS4.NE.NS3 ) THEN

C           LE COSINUS DE L'ANGLE DES NORMALES AUX
C           TRIANGLES NTR NTRADJ D'ARETE COMMUNE NS1-NS2
            CALL COS2TR( XYZSOM( 1, NS1 ),
     %                   XYZSOM( 1, NS2 ),
     %                   XYZSOM( 1, NS3 ),
     %                   XYZSOM( 1, NS2 ),
     %                   XYZSOM( 1, NS1 ),
     %                   XYZSOM( 1, NS4 ),
     %                   COS2PL, IERR1, IERR2 )

            IF( IERR1 .NE. 0 .OR. IERR2 .NE. 0 ) THEN
C              SI UN TRIANGLE EST SANS NORMALE
C              ALORS LA COPLANEARITE EST FAVORISEE
               GOTO 9999
            ENDIF

            IF( COS2PL .LT. COSMAXPL ) THEN
C              LES 2 TRIANGLES NE SONT PAS COPLANAIRES
               NTRADJ = 0
            ENDIF

            GOTO 9999
         ENDIF
      ENDDO

 9999 RETURN
      END
