      SUBROUTINE AXONOMETRIE( AXPTV, AXEIL, AXLAR, AXHAU, AXARR, AXAVA )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  CONSTRUCTION DE LA MATRICE DE LA PROJECTION AXONOMETRIQUE
C -----  A PARTIR DES 3 COORDONNEES DU POINT VISE PTV
C                 DES 3 COORDONNEES POSITION DE L'OEIL
C                 DE LA LARGEUR ET HAUTEUR DE LA FENETRE ECRAN
C                 DE LA PROFONDEUR ET AVANCE DANS LA DIRECTION DE VISEE
C
C ENTREES:
C --------
C AXLAR  : LARGEUR/2 VUE SUR L'ECRAN  (EN VALEUR ABSOLUE )
C AXHAU  : HAUTEUR/2 VUE SUR L'ECRAN
C AXARR  : DISTANCE A PTV DU PLAN ARRIERE DE SECTION
C AXAVA  : DISTANCE A PTV DU PLAN AVANT   DE SECTION
C AXPTV  : XYZ DU POINT VISE
C AXEIL  : XYZ DE L'OEIL
C
C SORTIES:  dans le common / trvar4 / de ~/incl/trvari.inc
C --------
C NDIMLI : 1 VARIABLE  ENTIERE AUXILIAIRE 2=>2D 3=>3D
C NOTYVI : NUMERO DU TYPE DE LA VISEE
C          0 SI NON INITIALISE
C          1 SI INITIALISE EN 2D
C         11 SI AXONOMETRIE PAR PTV OEIL AXOARR ET AXOAVA
C AXOLAR : LARGEUR/2 VUE SUR L'ECRAN  (EN VALEUR ABSOLUE )
C AXOHAU : HAUTEUR/2 VUE SUR L'ECRAN
C AXOARR : DISTANCE A PTV DU PLAN ARRIERE DE SECTION
C AXOAVA : DISTANCE A PTV DU PLAN AVANT   DE SECTION
C AXOPTV : XYZ DU POINT VISE
C AXOEIL : XYZ DE L'OEIL
C AXOMAT : MATRICE DE LA TRANSFORMATION (XYZAXO = AXOMAT * (xyz - PTV))
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS   SEPTEMBRE 1994
C2345X789............................................................012
      include"./incl/trvari.inc"
      REAL    AXPTV(3), AXEIL(3)
C
C     INITIALISATION DES VARIABLES DU COMMON / TRVAR4 /
      NDIMLI = 3
      NOTYVI = 11
      AXOLAR = AXLAR
      AXOHAU = AXHAU
      AXOARR = AXARR
      AXOAVA = AXAVA
      DO 10 I=1,3
         AXOPTV(I) = AXPTV(I)
         AXOEIL(I) = AXEIL(I)
 10   CONTINUE
C
C     CALCUL DE LA MATRICE AXOMAT
      CALL MATAXO
C
C     DEFINITION DE LA FENETRE EN LARGEUR ET HAUTEUR
      CALL ISOFENETRE( -AXOLAR, AXOLAR, -AXOHAU, AXOHAU )
      END
