      DOUBLE PRECISION FUNCTION DINFO(MOTCLE)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETOURNER UNE INFORMATION DE TYPE DOUBLE PRECISION
C -----    *** VERSION HP 700 ***
C
C ENTREE :
C --------
C MOTCLE : NATURE DE L'INFORMATION A RETOURNER, EN CLAIR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C PROGRAMMEUR : PATRICK LAUG  INRIA (3) 954 90 20 POSTE 3508
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      DOUBLE PRECISION  CPUOLD, CPUNEW, D
      COMMON / TEMCPU / CPUOLD
      CHARACTER*(*)     MOTCLE
      DOUBLE PRECISION  TOLD,   TNEW
      INTEGER           COUNT
      DOUBLE PRECISION  PETIT,  GRAND
      INTEGER           NEXT1(0:1)
C
      SAVE TOLD,COUNT
C
      DATA PETIT  /2.3D-308/
      DATA GRAND  /1.7D+308/
      DATA COUNT  /0/
      DATA NEXT1  /1,0/
      DATA CPUOLD /0.D0/
C
C     PLUS PETIT REEL POSITIF
      IF (MOTCLE .EQ. 'PETIT') THEN
         DINFO = PETIT
C
C     PLUS GRAND REEL
      ELSE IF (MOTCLE .EQ. 'GRAND') THEN
         DINFO = GRAND
C
C     TEMPS HORLOGE A PARTIR D'UN INSTANT FIXE
      ELSE IF (MOTCLE .EQ. 'HORLOGE') THEN
         CALL SECONDES1970( D )
         DINFO=D
         TOLD=TNEW
C
C     ACCROISSEMENT DU TEMPS HORLOGE
C     - AU PREMIER APPEL, RETOURNE LA MEME VALEUR QUE DINFO('HORLOGE')
C     - ENSUITE, RETOURNE LA DIFFERENCE ENTRE LA VALEUR COURANTE DE
C                L'HORLOGE ET LA VALEUR QU'ELLE AVAIT A L'APPEL PRECEDENT
C     REMARQUE : POUR QUE LE RESULTAT AIT UN SENS, L'UTILISATEUR DOIT
C                BIEN LOCALISER TOUS LES APPELS A DINFO('DELTA HORLOGE')
      ELSE IF (MOTCLE .EQ. 'DELTA HORLOGE') THEN
ccc         CALL TEMPSCPU( TNEW )
          CALL CPU_TIME( TNEW )
         IF( MOD(COUNT,2).EQ.0 )THEN
           DINFO=TNEW
         ELSE
           DINFO=TNEW-TOLD
         ENDIF
         COUNT=NEXT1(COUNT)
         TOLD=TNEW
C
C     TEMPS CPU A PARTIR D'UN INSTANT FIXE
      ELSE IF (MOTCLE .EQ. 'CPU') THEN
ccc          CALL TEMPSCPU( CPUNEW )
          CALL CPU_TIME( CPUNEW )
          DINFO=CPUNEW
          CPUOLD = CPUNEW
C
C     ACCROISSEMENT DU TEMPS CPU
C     - AU PREMIER APPEL, RETOURNE LA MEME VALEUR QUE DINFO('CPU')
C     - ENSUITE, RETOURNE LA DIFFERENCE ENTRE LA VALEUR COURANTE DU
C                TEMPS CPU ET LA VALEUR QU'IL AVAIT A L'APPEL PRECEDENT
C     REMARQUE : POUR QUE LE RESULTAT AIT UN SENS, L'UTILISATEUR DOIT
C                BIEN LOCALISER TOUS LES APPELS A DINFO('DELTA CPU')
      ELSE IF (MOTCLE .EQ. 'DELTA CPU') THEN
ccc         CALL TEMPSCPU( CPUNEW )
         CALL CPU_TIME( CPUNEW )
         DINFO  = CPUNEW - CPUOLD
         CPUOLD = CPUNEW
C
C     NOMBRE DE CHIFFRES D'UN REEL DOUBLE PRECISION
      ELSE IF (MOTCLE .EQ. 'PRECISION') THEN
C        ATTENTION SUR DEC-ALPHA: 1D-14
         DINFO = 1D-16
C
C     ERREUR
      ELSE
         WRITE (IINFO('I'),*) 'DINFO: MOT-CLE INCONNU: ', MOTCLE
         DINFO = 0D0
      END IF
      END
