      SUBROUTINE ENTIER2D( NC, X, Y, ENTIER )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  TRACE LES CARACTERES DE L'ENTIER AVEC LA COULEUR NC
C -----  A PARTIR DU POINT (X,Y) EN COORDONNEES OBJET 2D
C        LA TRANSFORMATION EN PIXELS EST ASSUREE DANS CE SP
C        LES AUTRES CARACTERISTIQUES DU TRACE SONT CELLES ACTUELLES
C
C        VERSION xvue
C
C ENTREE :
C --------
C NC     : NUMERO DE LA COULEUR DES CARACTERES DE L'ENTIER
C X      : ABSCISSE OBJET DES CARACTERES DE LA VALEUR DE L'ENTIER
C Y      : ORDONNEE OBJET DES CARACTERES DE LA VALEUR DE L'ENTIER
C ENTIER : L'ENTIER DONT LA VALEUR DOIT ETRE TRACEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC  PARIS  SEPTEMBRE 1994
C2345X7..............................................................012
      include"./incl/minint.inc"
      include"./incl/trvari.inc"
      INTEGER       ENTIER
      CHARACTER*11  KTXT
      CHARACTER*12  KENT
C
C     SI COULEUR NEGATIVE ALORS AUCUN TRACE
      IF( NC .LT. 0 ) RETURN
C
C     TRANSFORMATION EN PIXELS DANS LA FENETRE XV
      NX = NUPXEX( X )
      NY = NUPXEY( Y )
      IF( NX .EQ. MININT .OR. NY .EQ. MININT ) RETURN
C
C     TRANSLATION POUR CENTRER LE .
      NX = NX - NPLACA/2
      NY = NY + 2
C
C     TRACE EFFECTIF
      CALL XVCOULEUR( NC )
C
C     LE NOMBRE DE CARACTERES DE L'ENTIER
      WRITE( KTXT, '(I11)') ENTIER
      DO 10 I=1,11
         IF( KTXT(I:I) .NE. ' ' ) GOTO 20
 10   CONTINUE
C
 20   KENT = '.' // KTXT(I:11)
      L    = 13 - I
C     LE TRACE XV DE LA CHAINE DES L CARACTERES
      CALL XVTEXTE( KENT(1:L), L, NX, NY )
      END
