      SUBROUTINE ENTIERPX( NC, NX, NY, ENTIER )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  TRACE LES CARACTERES DE L'ENTIER AVEC LA COULEUR NC
C -----  A PARTIR DU POINT (NX,NY) EN COORDONNEES PIXELS
C        SANS DECALAGE NI AJOUT DE .
C
C ENTREE :
C --------
C NC     : NUMERO DE LA COULEUR DES CARACTERES DE L'ENTIER
C NX     : ABSCISSE PX DES CARACTERES DE LA VALEUR DE L'ENTIER
C NY     : ORDONNEE PX DES CARACTERES DE LA VALEUR DE L'ENTIER
C ENTIER : L'ENTIER DONT LA VALEUR DOIT ETRE TRACEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC  PARIS  SEPTEMBRE 1994
C2345X7..............................................................012
      include"./incl/trvari.inc"
      INTEGER       ENTIER
      CHARACTER*11  KTXT
C
C     SI COULEUR NEGATIVE ALORS AUCUN TRACE
      IF( NC .LT. 0 ) RETURN
C
C     TRACE EFFECTIF
      CALL XVCOULEUR( NC )
C
C     LE NOMBRE DE CARACTERES DE L'ENTIER
      WRITE( KTXT, '(I11)') ENTIER
      DO 10 I=1,11
         IF( KTXT(I:I) .NE. ' ' ) GOTO 20
 10   CONTINUE
C
C     LE TRACE XV DE LA CHAINE DES L CARACTERES
 20   CALL XVTEXTE( KTXT(I:11), 12-I, NX, NY )
      END
