      SUBROUTINE EVMENU
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  SAISIR UN TEXTE POUR KLG A L'AIDE DE
C -----  LA SOURIS OU LE CLAVIER PHYSIQUE
C        TRACE LE NOM DE L'OBJET, LE MENU ET L'INVITE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR:ALAIN PERRONNET ANALYSE NUMERIQUE LJLL UPMC PARIS     MARS 1996
C AUTEUR:ALAIN PERRONNET ANALYSE NUMERIQUE LJLL UPMC PARIS NOVEMBRE 2003
C23456---------------------------------------------------------------012
      include"./incl/gsmenu.inc"

C     SAUVEGARDE DES PIXELS DE LA FENETRE GRAPHIQUE MEFISTO
      CALL SAUVEMEMPX

C     TRACE DES RECTANGLES HISTO, MENU, INVIT, LIGSAI, LIGLUE, LERESU
      CALL LESREC

C     LECTURE AU CLAVIER OU DANS UN MENU OU CLIC PLSVO
      CALL SACLAV

C     L'INVITE EST EFFACEE
      CALL RECTEF( NRINVI )

C     LES LIGNES LUES SONT EFFACEES
      CALL RECTEF( NRLGLU )

C     LA LIGNE DE SAISIE EST EFFACEE
      CALL RECTEF( NRLGSA )

C     RESTAURATION DES PIXELS SOUS LE RECTANGLE MENU
      CALL RESTAUREMEMPX
      CALL MEMPXFENETRE

      RETURN
      END
