      SUBROUTINE FACE3D( NCF, NCA, NBS, XYZ )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACE LA FACE 3D DE NBS SOMMETS XYZ AVEC LES COULEURS
C -----    NCF POUR LA FACE ET NCA POUR LES ARETES
C
C          ATTENTION (X,Y,Z) EN COORDONNEES OBJET 3D
C          LA TRANSFORMATION EN PIXELS EST ASSUREE DANS CE SP
C          LES AUTRES CARACTERISTIQUES DU TRACE SONT CELLES ACTUELLES
C
C ENTREE :
C --------
C NCF    : NUMERO DE LA COULEUR DE REMPLISSAGE DE LA FACE A TRACER
C NCA    : NUMERO DE LA COULEUR DU CONTOUR     DE LA FACE A TRACER
C          <0 PAS DE TRACE DES ARETES DU CONTOUR DE LA FACE
C NBS    : NOMBRE DE SOMMETS DE LA FACE A TRACER
C XYZ    : ABSCISSE, ORDONNEE, COTE DES NBS SOMMETS DE LA FACE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC  PARIS        MAI 1994
C2345X7..............................................................012
      include"./incl/trvari.inc"
      include"./incl/minint.inc"
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      INTRINSIC         INT2
C
      PARAMETER        (MXPOIN=512)
      INTEGER*2         XYPX(2,MXPOIN)
      COMMON / COXYPX / XYPX
C
      REAL              XYZ(3,NBS), AXYZ(3)
C
C     SI COULEUR NEGATIVE => RETOUR
      IF( NCF .LT. 0 .AND. NCA .LT. 0 ) GOTO 9999
C
C     VERIFICATION
      IF( NBS .LE. 2 ) GOTO 9999
      IF( NBS .GE. MXPOIN ) THEN
         WRITE(IMPRIM,*) 'AUGMENTER MXPOIN dans SP face3d'
         GOTO 9999
      ENDIF

C     AXONOMETRIE DE L'OEIL POUR CALCULER LA DISTANCE A L'OEIL
      CALL XYZAXO( AXOEIL, AXOOEIL )

      DO NBSP=1,NBS
C        TRANSFORMATION DE XYZ EN COORDONNEES AXONOMETRIQUES AXYZ
         CALL XYZAXO( XYZ(1,NBSP), AXYZ )
C        SI UN POINT EST EXTERIEUR AUX 2 PLANS DE SECTION
C        ALORS LA FACE N'EST PAS TRACEE
         IF( AXOARR .NE. 0 .OR. AXOAVA .NE. 0 ) THEN
C           AXOARR ET AXOAVA SONT ACTIFS
            IF( AXOOEIL(3) - AXYZ(3) .LT. AXOARR ) GOTO 9999
            IF( AXOOEIL(3) - AXYZ(3) .GT. AXOAVA ) GOTO 9999
         ENDIF

C        TRANSFORMATION EN PIXELS DANS LA FENETRE XV
         NX = NUPXEX( AXYZ(1) )
         IF( NX .LE. MININT .OR. NX .GE. MAXINT ) GOTO 9999
C        SI LE NUMERO PIXEL EST INCORRECT ABANDON DU TRACE DE LA FACE
         NY = NUPXEY( AXYZ(2) )
         IF( NY .LE. MININT .OR. NY .GE. MAXINT ) GOTO 9999
         XYPX(1,NBSP) = INT2( NX )
         XYPX(2,NBSP) = INT2( NY )
      ENDDO
C
C     FERMETURE DES ARETES DU POLYGONE DE LA FACE
      IF( XYPX(1,NBS).NE.XYPX(1,1) .OR. XYPX(2,NBS).NE.XYPX(2,1) ) THEN
C        FERMETURE DU POLYGONE
         NBSP = NBS + 1
         XYPX(1,NBSP) = XYPX(1,1)
         XYPX(2,NBSP) = XYPX(2,1)
      ELSE
C        POLYGONE DEJA FERME
         NBSP = NBS
      ENDIF
C
      IF( NCF .GE. 0 .AND. NCA .LT. 0 ) THEN
C        TRACE EFFECTIF DU REMPLISSAGE DE LA FACE SANS LES ARETES
         CALL XVCOULEUR( NCF )
         CALL XVFACE( NBSP, XYPX )
         GOTO 9999
      ENDIF

      IF( NCF .LT. 0 .AND. NCA .GE. 0 ) THEN
C        TRACE DES ARETES DE LA FACE SANS REMPLISSAGE DE LA FACE
         CALL XVCOULEUR( NCA )
         CALL XVTRAITS( NBSP, XYPX )
         GOTO 9999
      ENDIF

C     TRACE DES ARETES DU CONTOUR ET DU REMPLISSAGE DE LA FACE
      CALL XVFACETRAITS( NCF, NCA, NBSP, XYPX )

 9999 RETURN
      END
