      SUBROUTINE GRADUA( AMPLI,   RMIN0, RMAX0,
     %                   PREMIER, PAS,   NBPAS, NBDFOR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCULER LA GRADUATION A TRACER ENTRE RMIN ET RMAX
C ----- POUR OBTENIR UNE LECTURE AISEE (PEU DE DECIMALES TRACEES)
C       A PEU PRES 10 NOMBRES REELS SONT A TRACER
C
C ENTREES :
C --------
C AMPLI   : COEFFICIENT DE REDUCTION DE LA COORDONNEE
C RMIN0   : LE REEL MINIMAL A TRACER
C RMAX0   : LE REEL MAXIMAL A TRACER
C
C SORTIES :
C --------
C PREMIER : REEL A TRACER
C PAS     : ENTRE 2 NOMBRES A TRACER
C NBPAS   : LE NOMBRE DE PAS A PARTIR DE ZERO
C NBDFOR  : LE NOMBRE DE DECIMALES A TRACER DANS LE FORMAT QUI SERA
C           G NBDFOR+8.NBDFOR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC  PARIS       AOUT 1997
C MODIFS : PERRONNET ALAIN LJLL UPMC PARIS St Pierre du Perray JUIN 2009
C2345X7..............................................................012
CCC      CHARACTER*10 KFORM
      INTRINSIC    MAX
C
C     AMPLIFICATION OU NON SELON LE COEFFICIENT AMPLI
      RMIN = RMIN0 / AMPLI
      RMAX = RMAX0 / AMPLI
C
C     10 NOMBRES A PEU PRES SONT A TRACER
      PAS = ( RMAX - RMIN ) / 10
C
C     EXPOSANT DE 10 DU PAS
      NBE = NBCHIR( PAS )
C
C     LA PUISSANCE DE 10 DE PAS
      DIXNBE = 10.0 ** NBE
C
C     LE PREMIER CHIFFRE SIGNIFICATIF DE PAS
      N1 = INT( PAS / DIXNBE )
C
C     LE SECOND CHIFFRE SIGNIFICATIF DE PAS SOUS LA FORME 0.N2
      R = ( PAS - N1 * DIXNBE ) / DIXNBE
C
C     LE NOMBRE N1.N2
      R = N1 + R
C
C     LE VRAI PAS
      N1 = NINT(R)
C     VALEUR PLUS LISIBLE
      IF( N1 .GE. 3 .AND. N1 .LE. 7 ) N1 = 5
      IF( N1 .GE. 8 ) N1 = 10
      PAS = N1 * DIXNBE
C
C     LE PLUS GRAND MULTIPLE DE PAS < RMIN
      PREMIER = INT( ABS(RMIN) / PAS ) * PAS
      IF( RMIN .LT. 0 ) PREMIER = -PREMIER
C
C     TENTATIVE POUR EVITER +-1E-7 A LA PLACE DE ZERO
      IF( ABS(PREMIER) .LT. 1E-3 * PAS ) PREMIER = 0
C
      RMIN = PREMIER
C
C     LE NOMBRE DE PAS
      NBPAS = NINT( (RMAX-RMIN) / PAS ) + 1
C
C     LE NOMBRE DE DECIMALES A TRACER POUR CHAQUE REEL
      NBCMI = ABS( NBCHIR(RMIN) )
      NBCMX = ABS( NBCHIR(RMAX) )
      NBCPA = ABS( NBCHIR(PAS)  )
      NBDFOR = MAX( NBCMI, NBCMX ) + NBCPA + 1
      IF( NBDFOR .GT. 6 ) NBDFOR = 6
C
C     RETOUR AUX COORDONNEES INITIALES
      PREMIER = PREMIER * AMPLI
      PAS     = PAS     * AMPLI
C
CCC      WRITE( KFORM,10010 ) NBDFOR+8,NBDFOR
CCC10010 FORMAT('''(G',I2,'.',I1,')''',1X)
CCC      WRITE(*,*) 'RMIN=',RMIN,' RMAX=',RMAX,' PREMIER=',PREMIER,
CCC     %      ' PAS=',PAS, ' NBPAS=',NBPAS,' NBDFOR=',NBDFOR,
CCC     %      ' KFORM=',KFORM
CCC      DO 10 i=0,NBPAS
CCC         WRITE(*,KNORM) PREMIER + i * pas  KFORM => PB SOUS LINUX
CCC         WRITE(*,'(G13.5)') PREMIER + i * pas
CCC 10   CONTINUE
C
      RETURN
      END
