      SUBROUTINE LEMENU
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : TRACER SUR L'ECRAN GRAPHIQUE LE MENU
C ----- VERSION XVUE sans Motif
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS         MAI 1994
C23456---------------------------------------------------------------012
      include"./incl/gsmenu.inc"
      include"./incl/trvari.inc"
      include"./incl/langue.inc"
      include"./incl/epombr.inc"
      INTRINSIC  INT
C
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
C
      IF( INTERA .LE. 1 ) RETURN
C
      IF( MDLGRC(NRMENU) .EQ. 0 ) NBLGRC(NRMENU) = NBLGRC(NRMENU) - 1
      IF( NBLGRC(NRMENU) .LE. 0 ) RETURN
C
C     AJOUT DANS LE MENU DE LA LIGNE ABANDON ET DOCUMENTATION
      IF( NAMENU(NBLGRC(NRMENU)) .NE. INMENU+1 ) THEN
C
C        AJOUT DE LA LIGNE DE DEMANDE D'ABANDON
         NBLGRC(NRMENU) = NBLGRC(NRMENU) + 1
         IF( LANGAG .EQ. 0 ) THEN
            KMENU (NBLGRC(NRMENU)) = 'ABANDON ...'
         ELSE
            KMENU (NBLGRC(NRMENU)) = 'ESCAPE ...'
         ENDIF
         NAMENU(NBLGRC(NRMENU)) =  INMENU - 1
C
C        AJOUT DE LA LIGNE DE DEMANDE DE DOCUMENTATION
         NBLGRC(NRMENU) = NBLGRC(NRMENU) + 1
         KMENU (NBLGRC(NRMENU)) = 'DOCUMENTATION'
         NAMENU(NBLGRC(NRMENU)) =  INMENU + 1
      ENDIF
C
C     LE NUMERO MAXIMAL DU DERNIER CARACTERE NON BLANC DE KMENU
      MDRECT(NRMENU) = 5 + MXCANB( NBLGRC(NRMENU) , KMENU )
C
C     LE COIN SUPERIEUR GAUCHE LARGEUR ET HAUTEUR
CCC      DXRECT(NRMENU) = MAX( DXRECT(NRERR),
CCC     %  ECARLR(NRMENU) * 2 + LAPXMENU( NBLGRC(NRMENU) , KMENU ) )
      DXRECT(NRMENU)=ECARLR(NRMENU)*2+LAPXMENU(NBLGRC(NRMENU),KMENU)+20
      XRECT (NRMENU)=LAPXFE - 2*ECARRC - DXRECT(NRMENU)
C
C     LE RECTANGLE MENU EN HAUT A GAUCHE AU DESSOUS DU RECTANGLE RESULTAT
      DYRECT(NRMENU) = DYLGRC(NRMENU) * NBLGRC(NRMENU)
      IF( DYRECT(NRERR) .GT. 0 ) THEN
         YRECT(NRMENU) = INT(YRECT(NRERR) + DYRECT(NRERR) + 1.5*ECARRC)
      ELSE
         YRECT (NRMENU) = ECARRC
      ENDIF
C
C     LE TRACE DU MENU
      CALL RECTTX( NRMENU, KMENU, 2, NAMENU )
      END
