      SUBROUTINE SANSDBL( KNOM, NBCAR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SUPPRIME LES DOUBLES BLANCS D'UNE CHAINE DE CARACTERES KNOM
C -----    ET LES BLANCS INITIAUX EN CADRANT A GAUCHE

C MODIFIE:
C --------
C KNOM   : CHAINE DE CARACTERES AVANT ET APRES

C SORTIE :
C --------
C NBCAR  : NUMERO DU DERNIER CARACTERE NON BLANC DE KNOM EN SORTIE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS         MAI 1999
C2345X7..............................................................012
      CHARACTER*(*) KNOM

C     LE NOMBRE DE CARACTERES DECLARES DE KNOM
      NBCKNOM = LEN( KNOM )

C     COPIE DANS LA CHAINE DE CARACTERES AUXILIAIRE
      KNOM = KNOM(1:NBCKNOM)

C     RECHERCHE DU PREMIER CARACTERE NON BLANC
      DO I = 1,NBCKNOM
         IF( KNOM(I:I) .NE. ' ' ) GOTO 20
      ENDDO
C     KNOM  = ' '
      NBCAR = 0
      GOTO 9999

C     SUPPRESSION DES BLANCS EN TETE
 20   KNOM = KNOM(I:NBCKNOM)

C     POSITION DU DERNIER CARACTERE NON BLANC
      NBCAR = NUDCNB( KNOM )
C     POSITION DU PREMIER CARACTERE NON BLANC
      I0 = 1

C     RECHERCHE DE 2 BLANCS CONSECUTIFS
 30   N = INDEX( KNOM(I0:NBCAR), '  ' )
      IF( N .EQ. 0 ) GOTO 9999

C     2 BLANCS EXISTENT EN POSITION I0-1+N
C     LE PREMIER BLANC EST ECRASE
      KNOM(I0-1+N:NBCAR) = KNOM(I0+N:NBCAR) // ' '

C     LE PREMIER CARACTERE A EXAMINER EST LE PREMIER BLANC ECRASE
      I0 = I0 - 1 + N

C     UN CARACTERE DE MOINS
      NBCAR = NBCAR - 1
      GOTO 30

 9999 RETURN
      END
