      SUBROUTINE SYMBOLE3D( NC, XYZ, TEXTE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  TRACE LE SYMBOLE DE NUMERO NOSYMB AVEC LA COULEUR NC
C -----  A PARTIR DU POINT (X,Y,Z) EN COORDONNEES OBJET 3D
C        LA TRANSFORMATION EN PIXELS EST ASSUREE DANS CE SP
C        LES AUTRES CARACTERISTIQUES DU TRACE SONT CELLES ACTUELLES
C        LA CHAINE EST DECALE D'UN DEMI CARACTERE VERS LE BAS ET A GAUCHE
C
C ENTREE :
C --------
C NC     : NUMERO DE LA COULEUR DU SYMBOLE A TRACER
C XYZ    : ABSCISSE ORDONNEE COTE DU SYMBOLE
C TEXTE  : LA CHAINE DE CARACTERES SERVANT DE SYMBOLE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC  PARIS        MAI 1994
C2345X7..............................................................012
      include"./incl/trvari.inc"
      include"./incl/minint.inc"
      REAL           XYZ(3), AXYZ(3)
      CHARACTER*(*)  TEXTE
C
C     SI COULEUR NEGATIVE ALORS AUCUN TRACE
      IF( NC .LT. 0 ) RETURN
C
C     TRANSFORMATION EN COORDONNEES AXONOMETRIQUES
      CALL XYZAXO( XYZ, AXYZ )
C
C     SI LE POINT EST EXTERIEUR AUX 2 PLANS LE TEXTE N'EST PAS TRACE
      IF( AXOARR .NE. 0 .OR. AXOAVA .NE. 0 ) THEN
C        AXOARR ET AXOAVA SONT ACTIFS
         IF( AXYZ(3) .LT. AXOARR ) RETURN
         IF( AXYZ(3) .GT. AXOAVA ) RETURN
      ENDIF
C
C     TRANSFORMATION EN PIXELS DANS LA FENETRE XV
      NX = NUPXEX( AXYZ(1) )
      NY = NUPXEY( AXYZ(2) )
      IF( NX .EQ. MININT .OR. NY .EQ. MININT ) RETURN
C
C     TRANSLATION POUR CENTRER LE SYMBOLE EN FONCTION DE LA FONTE
      NX = NX - NPLACA/2 + 1
      NY = NY + NPHACA/2 - 2
C
C     TRACE EFFECTIF
      CALL XVCOULEUR( NC )
C
C     LE NOMBRE DE CARACTERES DE TEXTE
      L = NUDCNB( TEXTE )
      CALL XVTEXTE( TEXTE(1:L), L, NX, NY )

      RETURN
      END
