      SUBROUTINE TRARET3D( NCOULAR, NCOULST, NOST1, NOST2, XYZSOM )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     en 3D TRACE de l'ARETE et des CARACTERES '*NOST'
C -----     DES 2 SOMMETS NOST1 et NOST2 de XYZSOM

C ENTREES:
C --------
C NCOULAR : NUMERO DE LA COULEUR DE TRACE DE L'ARETE 3D
C NCOULST : NUMERO DE LA COULEUR DE TRACE DES 2 SOMMETS
C NOST1   : NUMERO XYZSOM du SOMMET NOST1
C NOST2   : NUMERO XYZSOM du SOMMET NOST2
C XYZSOM  : XYZ DES SOMMETS DU MAILLAGE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : Alain PERRONNET  Saint PIERRE du PERRAY          Janvier 2021
C2345X7..............................................................012
      REAL           XYZSOM(3,*), XYZA(3)
      CHARACTER*12   CARSYM

C     SI COULEUR NEGATIVE PAS DE TRACE
      IF( NCOULAR .LT. 0 ) RETURN

C     TRACE DE L'ARETE 3D DE SOMMETS NOST1-NOST2
      CALL TRAIT3D( NCOULAR, XYZSOM(1,NOST1), XYZSOM(1,NOST2) )

      IF( NCOULST .LT. 0 ) RETURN

C     CONSTRUCTION DU MOT '*NOST1'
      CARSYM = '* '
      WRITE( CARSYM(2:11),'(I9)') NOST1
C     SUPPRESSION DES BLANCS
      CALL SANSBL( CARSYM, NBC )
C     COORDONNEES AXONOMETRIQUES DU SOMMET NOST1
      CALL XYZAXO( XYZSOM(1,NOST1), XYZA )
C     TRACE en NCOULST du MOT '*Nost1'
      CALL SYMBOLE2D( NCOULST, XYZA(1), XYZA(2), CARSYM(1:NBC) )

C     CONSTRUCTION DU MOT '*NOST2'
      CARSYM = '* '
      WRITE( CARSYM(2:11),'(I9)') NOST2
C     SUPPRESSION DES BLANCS
      CALL SANSBL( CARSYM, NBC )
C     TRACE en NCOULST du MOT '*Nost2'
      CALL SYMBOLE2D( NCOULST, XYZA(1), XYZA(2), CARSYM(1:NBC) )

      RETURN
      END
