      SUBROUTINE TRFA3D( NCF, NCA, POREDF, MNS, MNTG,
     %                   NBS, NOSOEL, NUEFTG,
     %                   X, Y, Z )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACER EN COULEURS DE LA FACE 3D DEFINIE PAR SON CODE,
C -----    SES NUMEROS DE SOMMETS ET TANGENTES
C
C ENTREES:
C --------
C NCF    : NUMERO DE LA COULEUR DE REMPLISSAGE DE LA FACE A TRACER
C          <0 PAS DE TRACE DE L'INTERIEUR DE LA FACE
C NCA    : NUMERO DE LA COULEUR DU CONTOUR     DE LA FACE A TRACER
C          <0 PAS DE TRACE DES ARETES DU CONTOUR DE LA FACE
C POREDF : POURCENTAGE DE REDUCTION DE LA FACE ( 0<=POREDF<100 )
C MNS    : ADRESSE MCN -3 DE LA PREMIERE COORDONNEE DU PREMIER SOMMET
C MNTG   : ADRESSE MCN -3 DE LA PREMIERE COORDONNEE DE LA PREMIERE TG
C NBS    : NOMBRE DE SOMMETS ( 3 ou 4 ) DE LA FACE A TRACER
C NOSOEL : NUMERO DES NBSOEF SOMMETS
C          SUIVI EVENTUELLEMENT DES NBTGEF TANGENTES DE L'EF NUELEM
C
C          SI PAS DE TANGENTES (NBTGEF=0):
C             TRIANGLE  : NO SOMMET1 , NS2 , NS3, 0
C             QUADRANGLE: NO SOMMET1 , NS2 , NS3, NS4
C
C          S'IL EXISTE DES TANGENTES (NBTGEF>0) ELLES SONT RANGEES PAR SOMMET:
C             TRIANGLE  : NO  SOMMET1, NS2 , NS3, 0,
C                         NO TANGENTE1(S1S2), NT2(S1S3),   NT3(S2S3), NT4(S2S1),
C                         NO TANGENTE5(S3S1), NT6(S3S2),   0,         0
C             QUADRANGLE: NO  SOMMET1, NS2 , NS3, NS4,
C                         NO TANGENTE1(S1S2), NT2(S1S3),   NT3(S2S3), NT4(S2S1),
C                         NO TANGENTE5(S3S4), NT6(S3S2),   NT7(S4S1), NT8(S4S3)
C          CE CHOIX PERMET UNE BOUCLE SUR LES TANGENTES PAR LES SOMMETS
C
C NUEFTG : NUMERO DE L'EF A TG ET SINON 0
C
C SORTIES:
C --------
C X      : ABSCISSE OBJET DES NBS SOMMETS ET TANGENTES DE LA FACE
C Y      : ORDONNEE OBJET DES NBS SOMMETS ET TANGENTES DE LA FACE
C Z      : COTE     OBJET DES NBS SOMMETS ET TANGENTES DE LA FACE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1996
C2345X...............................................................012
      INTEGER        NOSOEL(1:12),NOSTEF(1:12)
      REAL           X(12), Y(12), Z(12)
C
C     CALCUL DES COORDONNEES DES SOMMETS ET DES TANGENTES DE L'EF
      CALL XYZSTG( MNS, MNTG, NBS, NOSOEL, NUEFTG,
     %             X, Y, Z )
C
      IF( NUEFTG .GT. 0 ) THEN
C
C        EF AVEC DES TANGENTES (POLYNOMES DE DEGRE 3)
C        CONSTRUCTION DU TABLEAU NOSTEF (NOSOEL COMPRESSE POUR LE TRIANGLE)
         IF( NBS .EQ. 4 ) THEN

C           QUADRANGLE
            DO J=1,12
               NOSTEF(J) = NOSOEL(J)
            ENDDO

         ELSE

C           TRIANGLE
            NOSTEF(1) = NOSOEL(1)
            NOSTEF(2) = NOSOEL(2)
            NOSTEF(3) = NOSOEL(3)
            NOSTEF(4) = NOSOEL(5)
            NOSTEF(5) = NOSOEL(6)
            NOSTEF(6) = NOSOEL(7)
            NOSTEF(7) = NOSOEL(8)
            NOSTEF(8) = NOSOEL(9)
            NOSTEF(9) = NOSOEL(10)

         ENDIF
C
C        LE TRACE DE L'EF A TG (POLYNOMES DE DEGRE 3)
         CALL FAP33D( NCF, NCA, POREDF, NBS, X, Y, Z, NOSTEF,NOSTEF )
C
      ELSE
C
C        TRACE DE L'EF SANS TG (POLYNOMES DE DEGRE 1)
         CALL FAP13D( NCF, NCA, POREDF, NBS, X, Y, Z )

      ENDIF

      RETURN
      END
