      SUBROUTINE TRIACOU3DBORD( XYZ1,  XYZ2,  XYZ3,
     %                          COUL1, COUL2, COUL3,
     %                          NC, NF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACE LE TRIANGLE DE SOMMETS XYZi ET DE COULEURS COULi
C -----    SELON LES COULEURS INTERMEDIAIRES  (PALETTE 11 RECOMMANDEE)
C          AINSI QUE LES ARETES DU TRIANGLE SELON LA COULEUR NC
C          ATTENTION (X,Y,Z) EN COORDONNEES OBJETS 3D
C
C ENTREES:
C --------
C XYZi   : 3 COORDONNEES DU SOMMET i
C COULi  : NUMERO REEL DE LA COULEUR AUX 3 SOMMETS DU TRIANGLE
C          REEL DE VALEURS COMPRISES ENTRE N1COUL ET NDCOUL
C          (cf ~/incl/trvari.inc)
C NC     : COULEUR DE TRACE DES 3 ARETES
C          SI NC<0 PAS DE TRACE DU BORD
C NF     : SI NF>=0 TRACE DE LA FACE
C          SI NF<0 PAS DE TRACE DE LA FACE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR :PERRONNET ALAIN ANALYSE NUMERIQUE UPMC LJLL PARIS OCTOBRE 2003
C2345X7..............................................................012
      include"./incl/trvari.inc"
      include"./incl/minint.inc"
      REAL           XYZ1(3), XYZ2(3), XYZ3(3)
      REAL           COUL1, COUL2, COUL3, COUL(3)
      REAL           AXYZ(3)
      INTEGER*2      XYPX(2,4)
C
C     TRANSFORMATION EN COORDONNEES AXONOMETRIQUES
      CALL XYZAXO( XYZ1, AXYZ )
C     SI UN POINT EST EXTERIEUR AUX 2 PLANS LA FACE N'EST PAS TRACEE
      IF( AXOARR .NE. 0 .OR. AXOAVA .NE. 0 ) THEN
C         AXOARR ET AXOAVA SONT ACTIFS
          IF( AXYZ(3) .LT. AXOARR ) RETURN
          IF( AXYZ(3) .GT. AXOAVA ) RETURN
      ENDIF
C     TRANSFORMATION EN PIXELS DANS LA FENETRE XV
      NX = NUPXEX( AXYZ(1) )
      NY = NUPXEY( AXYZ(2) )
C     SI LE NUMERO PIXEL EST INCORRECT ABANDON DU TRACE DE LA FACE
      IF( NX .EQ. MININT .OR. NY .EQ. MININT ) RETURN
      XYPX(1,1) = INT2( NX )
      XYPX(2,1) = INT2( NY )
C
C
C     TRANSFORMATION EN COORDONNEES AXONOMETRIQUES
      CALL XYZAXO( XYZ2, AXYZ )
C     SI UN POINT EST EXTERIEUR AUX 2 PLANS LA FACE N'EST PAS TRACEE
      IF( AXOARR .NE. 0 .OR. AXOAVA .NE. 0 ) THEN
C         AXOARR ET AXOAVA SONT ACTIFS
          IF( AXYZ(3) .LT. AXOARR ) RETURN
          IF( AXYZ(3) .GT. AXOAVA ) RETURN
      ENDIF
C     TRANSFORMATION EN PIXELS DANS LA FENETRE XV
      NX = NUPXEX( AXYZ(1) )
      NY = NUPXEY( AXYZ(2) )
C     SI LE NUMERO PIXEL EST INCORRECT ABANDON DU TRACE DE LA FACE
      IF( NX .EQ. MININT .OR. NY .EQ. MININT ) RETURN
      XYPX(1,2) = INT2( NX )
      XYPX(2,2) = INT2( NY )
C
C
C     TRANSFORMATION EN COORDONNEES AXONOMETRIQUES
      CALL XYZAXO( XYZ3, AXYZ )
C     SI UN POINT EST EXTERIEUR AUX 2 PLANS LA FACE N'EST PAS TRACEE
      IF( AXOARR .NE. 0 .OR. AXOAVA .NE. 0 ) THEN
C         AXOARR ET AXOAVA SONT ACTIFS
          IF( AXYZ(3) .LT. AXOARR ) RETURN
          IF( AXYZ(3) .GT. AXOAVA ) RETURN
      ENDIF
C     TRANSFORMATION EN PIXELS DANS LA FENETRE XV
      NX = NUPXEX( AXYZ(1) )
      NY = NUPXEY( AXYZ(2) )
C     SI LE NUMERO PIXEL EST INCORRECT ABANDON DU TRACE DE LA FACE
      IF( NX .EQ. MININT .OR. NY .EQ. MININT ) RETURN
      XYPX(1,3) = INT2( NX )
      XYPX(2,3) = INT2( NY )
C
C     TRACE EFFECTIF DU REMPLISSAGE DU TRIANGLE SELON DES COULEURS INTERMEDIAIRE
      IF( NF .GE. 0 ) THEN
         COUL(1) = COUL1
         COUL(2) = COUL2
         COUL(3) = COUL3
         CALL TRIACOUL( XYPX, COUL )
      ENDIF
C
C     TRACE SELON LA COULEUR NC DES 3 ARETES DU TRIANGLE
      IF( NC .GE. 0 ) THEN
         CALL XVCOULEUR( NC )
         XYPX(1,4) = XYPX(1,1)
         XYPX(2,4) = XYPX(2,1)
         I = 4
         CALL XVTRAITS( I, XYPX )
      ENDIF
      RETURN
      END
