C/home/ap/mefisto/incl/homdir1.inc
CThe Mefisto source directory NAME
      CHARACTER* HOMDIR
      PARAMETER (HOMDIR=
     %'/home/ap/mefisto'
     %)


C    Autre exemple avec un nom de homdir > 65  => 2 lignes por le definir


C/Network/Servers/ldap.ann.jussieu.fr/Volumes/DATA/users/ljll/peronet/mefisto/incl/homdir.inc
CThe Mefisto source directory
      CHARACTER*76 HOMDIR
      PARAMETER (HOMDIR=
     %'/Network/Servers/ldap.ann.jussieu.fr/Volumes/DATA/users/ljll/pero
     %net/mefisto'
     %)
