#!/bin/bash
#  Shell script appelsp   Alain Perronnet juin 1998
#
echo Recherche des SP appeles et n\'appartenant pas a un repertoire
echo Nom du repertoire?
read repe
if test ! -d $ef/$repe
then
  echo Repertoire $ef/$repe inconnu
  exit
fi
echo Recherche dans le repertoire $repe
cd $ef/$repe
rm fsubr fcall
grep -i SUBROUTINE *.f >fsubr
#cat fsubr

grep -i CALL *.f >fcall

vi fcall <<@
\:1,\$s/.*CALL //
\:1,\$s/.*call //
\:1,\$s/(.*//
\:1,\$s/ //g              #il ne reste plus que le nom du sp appel
\:w fcall
\:q
@
#cat fcall
rm f0 f1 2>>poubelle

for j in `cat fcall`
do
  grep -i $j fsubr >ficaux
  set `wc ficaux`; nb=`expr $1 == 0`  #nb=1 si sp pas appele
  nb=f$nb
  >$nb                   # creation du fichier vide f1 si sp pas dans repe
  if test -f f1
  then
    echo $j appele et non dans le repertoire $repe
  fi
  rm f0 f1 ficaux 2>>poubelle
done
