#!/bin/bash
#
#  compilation et edition de liens de ppbrezfort2d
#  Alain Perronnet
# 
echo     
echo ===========================================================
echo MEFISTO-LINUX: Compilation Edition de liens de ppbrezfort2d
echo ===========================================================
cd $MEFISTO

#Creation du repertoire pp s'il n'existe pas
if test -d pp
then
   echo pp existe
else 
   mkdir pp
fi
#  
# compilation conditionnelle de xvuelc.c 
if test -f xvue/xvuelc.o
then
   echo "xvue/xvuelc.o NON recompile"
else 
   bin/ccxvue
fi

nompp=pp/ppbrezfort2d
if test -f $nompp
then
  rm $nompp
fi
 
echo "Un peu de patience: Compilation ppbrezfort2d et Edition de liens en cours ..."

gfortran -O -I. prpr/ppbrezfort2d.f mail/lib util/lib xvue/lib xvue/xvuelc.o \
     -L/usr/X11R6/lib -lXt -lX11 -o $nompp

rm ppbrezfort2d.o
if test -f $nompp
then 
   chmod 755 $nompp
   ls -l $MEFISTO/pp 
   echo "$MEFISTO/$nompp est PRET a l'emploi" 
else
   echo "$MEFISTO/$nompp est INCORRECT"
fi  
