#!/bin/bash
#
# compilation et edition de liens de ppflui.f 
# Alain Perronnet  Octobre 2012 Version LINUX 64bits

cd $MEFISTO
#Creation du repertoire pp s'il n'existe pas
if !(test -d pp)
then
  mkdir pp
fi

if test -f $MEFISTO/td/m/anglais
then
  LANGAGE=1
  LANGUE=ANGLAISE
  echo
  echo ====================================================================
  echo MEFISTO-LINUX 64bits: Compilation f+OpenMP + Link Editor of ppflui.f
  echo ====================================================================
else
  LANGAGE=0
  LANGUE=FRANCAISE
  echo
  echo =========================================================================
  echo MEFISTO-LINUX 64bits: Compilation f+OpenMP + Edition de liens de ppflui.f
  echo =========================================================================
fi

#  
# compilation de xvuelc.c
if !(test -f xvue/xvuelc.o)
then
  bin/ccxvue
fi

nompp=pp/ppflui
if test -f $nompp
then
  rm $nompp
fi

### g77 -g -I.  prpr/ppflui.f flui/lib util/lib xvue/lib xvue/xvuelc.o \
###     -lXt -lX11 -lXext -o $nompp

echo "gfortran -m64 -Wall -mcmodel=large -fPIC -O -fopenmp -I. $MEFISTO/prpr/ppflui.f -o $nompp"
gfortran -m64 -Wall -mcmodel=large -fPIC -O -fopenmp -I. prpr/ppflui.f \
          flui/lib ther/lib elas/lib reso/lib mail/lib \
          util/lib xvue/lib xvue/xvuelc.o \
          -lgfortran -L/usr/X11R6/lib64 -lX11 -o $nompp

if test -f ppflui.o
then
  rm ppflui.o
fi

if test -f $nompp
then 
  chmod 755 $nompp
  ls -l $MEFISTO/pp
  echo
  if [ $LANGAGE = 0 ]
  then
    echo "$MEFISTO/$nompp est CORRECT pour executer FLUIDER"
  else
    echo "$MEFISTO/$nompp is CORRECT to execute FLUIDER"
  fi
else
  if [ $LANGAGE = 0 ]
  then
    echo "$MEFISTO/$nompp est INCORRECT. FLUIDER est NON EXECUTABLE"
  else
    echo "$MEFISTO/$nompp is INCORRECT. FLUIDER is NOT EXECUTABLE"
  fi
fi
