#!/bin/bash
#
# compilation et edition de liens de ppelas.f 
# Alain Perronnet   Version LINUX 64bits  Octobre 2012

cd $MEFISTO
#Creation du repertoire pp s'il n'existe pas
if !(test -d pp)
then
  mkdir pp
fi

if test -f $MEFISTO/td/m/anglais
then
  LANGAGE=1
  LANGUE=ANGLAISE
  echo
  echo ======================================================================
  echo MEFISTO-LINUX 64bits: Compilation f95+OpenMP + Link Editor of ppelas.f
  echo ======================================================================
else
  LANGAGE=0
  LANGUE=FRANCAISE
  echo
  echo ===========================================================================
  echo MEFISTO-LINUX 64bits: Compilation f95+OpenMP + Edition de liens de ppelas.f
  echo ===========================================================================
fi

#  
# compilation de xvuelc.c
if !(test -f xvue/xvuelc.o)
then
  bin/ccgxvue
fi

nompp=pp/ppelas
if test -f $nompp
then
  rm $nompp
fi

### g77 -g -I.  prpr/ppelas.f elas/lib util/lib xvue/lib xvue/xvuelc.o \
###     -lXt -lX11 -lXext -o $nompp

echo "gfortran -m64 -mcmodel=large -fPIC -g -fopenmp -I. $MEFISTO/prpr/ppelas.f -o $nompp"
gfortran -m64 -mcmodel=large -fPIC -g -fopenmp -I. prpr/ppelas.f elas/lib reso/lib mail/lib \
                util/lib xvue/lib xvue/xvuelc.o \
    -lgfortran -L/usr/X11R6/lib64 -lX11 -o $nompp

if test -f ppelas.o
then
  rm ppelas.o
fi

if test -f $nompp
then 
  chmod 755 $nompp
  ls -l $MEFISTO/pp
  echo
  if [ $LANGAGE = 0 ]
  then
    echo "$MEFISTO/$nompp est CORRECT pour executer ELASTICER"
  else
    echo "$MEFISTO/$nompp is CORRECT to execute ELASTICER"
  fi
else
  if [ $LANGAGE = 0 ]
  then
    echo "$MEFISTO/$nompp est INCORRECT. ELASTICER est NON EXECUTABLE"
  else
    echo "$MEFISTO/$nompp is INCORRECT. ELASTICER is NOT EXECUTABLE"
  fi
fi
