#!/bin/bash
#
# compilation et edition de liens de ppnlse.f 
# Alain Perronnet   Version LINUX 64bits   Octobre 2012

cd $MEFISTO
#Creation du repertoire pp s'il n'existe pas
if !(test -d pp)
then
  mkdir pp
fi

if test -f $MEFISTO/td/m/anglais
then
  LANGAGE=1
  LANGUE=ANGLAISE
  echo
  echo ======================================================================
  echo MEFISTO-LINUX 64bits: Compilation f95+OpenMP + Link Editor of ppnlse.f
  echo ======================================================================
else
  LANGAGE=0
  LANGUE=FRANCAISE
  echo
  echo ===========================================================================
  echo MEFISTO-LINUX 64bits: Compilation f95+OpenMP + Edition de liens de ppnlse.f
  echo ===========================================================================
fi

#  
# compilation de xvuelc.c
if !(test -f xvue/xvuelc.o)
then
  bin/ccgxvue
fi

nompp=pp/ppnlse
if test -f $nompp
then
  rm $nompp
fi

echo "gfortran -m64 -fPIC -fopenmp -g -I. $MEFISTO/prpr/ppnlse.f -o $nompp"
gfortran -m64 -fPIC -g -fopenmp -I. prpr/ppnlse.f ther/lib elas/lib reso/lib mail/lib \
         util/lib xvue/lib xvue/xvuelc.o \
         -lgfortran -L/usr/X11R6/lib64 -lX11 -o $nompp

if test -f ppnlse.o
then
  rm ppnlse.o
fi

if test -f $nompp
then 
  chmod 755 $nompp
  ls -l $MEFISTO/pp
  echo
  if [ $LANGAGE = 0 ]
  then
    echo "$MEFISTO/$nompp est CORRECT pour executer NLSER"
  else
    echo "$MEFISTO/$nompp is CORRECT to execute NLSER"
  fi
else
  if [ $LANGAGE = 0 ]
  then
    echo "$MEFISTO/$nompp est INCORRECT. NLSER est NON EXECUTABLE"
  else
    echo "$MEFISTO/$nompp is INCORRECT. NLSER is NOT EXECUTABLE"
  fi
fi
echo
