#!/bin/bash
#  execution de ppmail avec debogueur ddd
#  Alain Perronnet    Novembre 2003  Version LINUX
#   
#  mise sous le directory 
echo
echo MEFISTO-MAILLAGE: nom du projet \?
read nomproj

direxec=$MEFISTOX/$nomproj
echo Execution MEFISTO MAILLAGE dans $direxec

if test -d $direxec
then
   cd  $direxec 
   ddd $MEFISTO/pp/ppmail
else  
   echo Commande INITIER non prealablement executee
   echo avec ce nom de projet $nomproj
fi
