#!/bin/bash
#  execution du MAILLEUR de Mefisto par MAILLER_OMP ou MESHER_OMP
#  Alain Perronnet  Octobre 2012   Version LINUX 64 bits
#   
if test -f $MEFISTO/td/m/anglais
then
  LANGAGE=1
  LANGUE=ANGLAISE
  echo
  echo '======================================================'
  echo 'MEFISTO-MESHER_OMP: MESH an OBJECT under LINUX 64 bits'
  echo '======================================================'
  echo 'Project (low case) name' \?
else
  LANGAGE=0
  LANGUE=FRANCAISE
  echo
  echo '============================================================='
  echo 'MEFISTO-MAILLEUR_OMP: MAILLER un OBJET sur sous LINUX 64 bits'
  echo '============================================================='
  echo 'nom (en minuscules) du projet' \?
fi
read nomproj

direxec=$MEFISTOX/$nomproj
echo
if [ $LANGAGE = 0 ]
then
  echo "Execution MEFISTO MAILLER_OMP dans le repertoire $direxec"
else
  echo "Execution MEFISTO MESHER_OMP in directory $direxec"
fi

if test -d $direxec
then
  cd  $direxec
  export OMP_NUM_THREADS=8
  echo "OMP_NUM_THREADS="$OMP_NUM_THREADS
  time $MEFISTO/pp/ppmail
else  
  if [ $LANGAGE = 0 ]
  then
    echo Commande INITIER non prealablement executee
    echo "avec ce nom de projet $nomproj"
    echo Executer INITIER
  else
    echo Command INITIER NOT EXECUTED BEFORE
    echo "with this project name $nomproj"
    echo Execute INITIER
  fi
fi
