      SUBROUTINE EC3P1D( NUELEM, NBELEM, NUNDEL, NDSM, NDSMCI,
     %                   DELTA,  DP, F,
     %                   NOOBVC, NUMIVO, NUMAVO, LTDEVO,
     %                   MNTEMP, NTDLT,  TEMPER, NTDLE, DEPLAC,
     %                   ELAS,   STRELT, CONINI,
     %                   COOPTC, STRESS )
C +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DU TENSEUR DES CONTRAINTES ELASTIQUES AU BARYCENTRE
C -----    D'UN EF DE TYPE TETRAEDRE LAGRANGE DE DEGRE 1
C
C ENTREES :
C ---------
C NUELEM : NUMERO DE L'ELEMENT FINI POUR CE TYPE D'ELEMENT FINI
C NBELEM : NOMBRE TOTAL D'ELEMENTS FINIS DE CE TYPE
C NUNDEL : NUMERO DES 4 NOEUDS DES ELEMENTS FINIS
C NDSM   : NOMBRE DE CAS DE CHARGE OU SECONDS MEMBRES DU SYSTEME
C NDSMCI : NOMBRE DE JEUX DE CONTRAINTES INITIALES = 0 OU 1 OU NDSM
C DELTA  : JACOBIEN DU TETRAEDRE
C F      : 3 COORDONNEES DOUBLE PRECISION DU BARYCENTRE DU TETRAEDRE
C DP     : GRADIENT DES FONCTIONS DE BASE AUX POINTS D INTEGRATION
C
C NOOBVC : NUMERO DE VOLUME DE CE TETRAEDRE
C NUMIVO : NUMERO MINIMAL DES VOLUMES
C NUMAVO : NUMERO MAXIMAL DES VOLUMES
C LTDEVO : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES D'ELASTICITE
C          DES VOLUMES
C
C MNTEMP : >0 INDICATEUR DE CONTRAINTES THERMIQUES
C          =0 SI PAS DE  DE CONTRAINTES THERMIQUES
C NTDLT  : NOMBRE TOTAL DE DL EN TEMPERATURE DU MAILLAGE
C TEMPER : TEMPERATURES (NTDLT,NDSM)
C NTDLE  : NOMBRE TOTAL DE DL EN DEPLACEMENTS DU MAILLAGE
C DEPLAC : DEPLACEMENTS (NTDLE,NDSM)
C
C TABLEAUX AUXILIAIRES :
C ----------------------
C ELAS   : TENSEUR DE L ELASTICITE SYMETRIQUE CALCULE DANS CE SP
C STRELT : TABLEAU AUXILIAIRE (6,3*4)
C CONINI : TABLEAU AUXILIAIRE (NDSM,6)
C
C SORTIES:
C --------
C COOPTC : LES COORDONNEES DU POINT DE CALCUL DES CONTRAINTES=BARYCENTRE
C STRESS : LES CONTRAINTES AU BARYCENTRE ET POUR CHAQUE CAS DE CHARGE
C          STRESS ( 6, NDSM )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS       AVRIL 1998
C23456...............................................................012
      include"./incl/donela.inc"
      DOUBLE PRECISION DP(3,4),
     %                 STRELT(6,3*4),
     %                 TEMPER(NTDLT,NDSM),
     %                 DEPLAC(NTDLE,NDSM),
     %                 DILATA,
     %                 STRESS(6,NDSM)
      REAL             COOPTC(NBELEM,3)
      INTEGER          NUNDEL(NBELEM,4)
      INTEGER          LTDEVO(1:MXDOEL,NUMIVO:NUMAVO)
      DOUBLE PRECISION ELAS(21),CONINI(NDSM,6),D,DD,TEMPIN
      DOUBLE PRECISION DELTA,F(3),TEMPBA
      INTRINSIC        REAL
C
C     LE TABLEAU COOPTC COORDONNEES DES POINTS DE CALCUL
C     --------------------------------------------------
      COOPTC(NUELEM,1) = REAL( F(1) )
      COOPTC(NUELEM,2) = REAL( F(2) )
      COOPTC(NUELEM,3) = REAL( F(3) )
C
C     LE TENSEUR SYMETRIQUE DE L'ELASTICITE AU BARYCENTRE DU TETRAEDRE
C     ----------------------------------------------------------------
      CALL REELAS( 4, NOOBVC, 3, F(1), F(2), F(3),
     %             LTDEVO(LPYOUN,NOOBVC),
     %             ELAS )
C
C     CALCUL DES CONTRAINTES ELASTIQUES
C     ---------------------------------
      DO 5 J=1,4
C     ED11 * DP
      STRELT(1,J)=ELAS( 1)*DP(1,J) + ELAS( 7)*DP(2,J) + ELAS(16)*DP(3,J)
      STRELT(2,J)=ELAS( 2)*DP(1,J) + ELAS( 8)*DP(2,J) + ELAS(17)*DP(3,J)
      STRELT(3,J)=ELAS( 4)*DP(1,J) + ELAS( 9)*DP(2,J) + ELAS(18)*DP(3,J)
      STRELT(4,J)=ELAS( 7)*DP(1,J) + ELAS(10)*DP(2,J) + ELAS(19)*DP(3,J)
      STRELT(5,J)=ELAS(11)*DP(1,J) + ELAS(14)*DP(2,J) + ELAS(20)*DP(3,J)
      STRELT(6,J)=ELAS(16)*DP(1,J) + ELAS(19)*DP(2,J) + ELAS(21)*DP(3,J)
C
C     ED2 * DP
      STRELT(1,J+4)=ELAS( 7)*DP(1,J) +ELAS( 2)*DP(2,J) +ELAS(11)*DP(3,J)
      STRELT(2,J+4)=ELAS( 8)*DP(1,J) +ELAS( 3)*DP(2,J) +ELAS(12)*DP(3,J)
      STRELT(3,J+4)=ELAS( 9)*DP(1,J) +ELAS( 5)*DP(2,J) +ELAS(13)*DP(3,J)
      STRELT(4,J+4)=ELAS(10)*DP(1,J) +ELAS( 8)*DP(2,J) +ELAS(14)*DP(3,J)
      STRELT(5,J+4)=ELAS(14)*DP(1,J) +ELAS(12)*DP(2,J) +ELAS(15)*DP(3,J)
      STRELT(6,J+4)=ELAS(19)*DP(1,J) +ELAS(17)*DP(2,J) +ELAS(20)*DP(3,J)
C
C     ED3 * DP
      STRELT(1,J+8)=ELAS(16)*DP(1,J) +ELAS(11)*DP(2,J) +ELAS( 4)*DP(3,J)
      STRELT(2,J+8)=ELAS(17)*DP(1,J) +ELAS(12)*DP(2,J) +ELAS( 5)*DP(3,J)
      STRELT(3,J+8)=ELAS(18)*DP(1,J) +ELAS(13)*DP(2,J) +ELAS( 6)*DP(3,J)
      STRELT(4,J+8)=ELAS(19)*DP(1,J) +ELAS(14)*DP(2,J) +ELAS( 9)*DP(3,J)
      STRELT(5,J+8)=ELAS(20)*DP(1,J) +ELAS(15)*DP(2,J) +ELAS(13)*DP(3,J)
      STRELT(6,J+8)=ELAS(21)*DP(1,J) +ELAS(20)*DP(2,J) +ELAS(18)*DP(3,J)
C
 5    CONTINUE
C
C     CONTRIBUTION DES DEPLACEMENTS AU TENSEUR DES CONTRAINTES
      N1 = 3 * NUNDEL( NUELEM, 1 )
      N2 = 3 * NUNDEL( NUELEM, 2 )
      N3 = 3 * NUNDEL( NUELEM, 3 )
      N4 = 3 * NUNDEL( NUELEM, 4 )
C
      DO 9 M=1,NDSM
         DO 7 K=1,6
      STRESS(K,M)=STRELT(K,1)*DEPLAC(N1-2,M) +STRELT(K,2)*DEPLAC(N2-2,M)
     %           +STRELT(K,3)*DEPLAC(N3-2,M) +STRELT(K,4)*DEPLAC(N4-2,M)
     %           +STRELT(K,5)*DEPLAC(N1-1,M) +STRELT(K,6)*DEPLAC(N2-1,M)
     %           +STRELT(K,7)*DEPLAC(N3-1,M) +STRELT(K,8)*DEPLAC(N4-1,M)
     %           +STRELT(K,9)*DEPLAC(N1  ,M) +STRELT(K,10)*DEPLAC(N2 ,M)
     %           +STRELT(K,11)*DEPLAC(N3 ,M) +STRELT(K,12)*DEPLAC(N4 ,M)
 7       CONTINUE
 9    CONTINUE
C
C     CALCUL DES CONTRAINTES THERMIQUES
C     ---------------------------------
      IF( MNTEMP .GT. 0 ) THEN
         IF( LTDEVO(LPDILA,NOOBVC) .GT. 0 ) THEN
C           CALCUL DE -(E)*(DILATA(NDSDE))=(ED3)
C           LE COEFFICIENT DE DILATATION THERMIQUE
            CALL REDILA( 4, NOOBVC, F(1), F(2), F(3),
     %                   LTDEVO(LPDILA,NOOBVC),
     %                   DILATA , TEMPIN )
C           CONTRIBUTION = - (E) (DILATA) [1/4,1/4,1/4,1/4] DELTA (TEMP -TEMPIN)
C           POUR UN MATERIAU HOMOGENE ISOTROPE
            D = - DILATA * DELTA / 4D0
            DO 19 M=1,NDSM
C              LA TEMPERATURE AU BARYCENTRE DU TETRAEDRE
               TEMPBA = TEMPER( NUNDEL(NUELEM,1), M )
     %                + TEMPER( NUNDEL(NUELEM,2), M )
     %                + TEMPER( NUNDEL(NUELEM,3), M )
     %                + TEMPER( NUNDEL(NUELEM,4), M )
               DD = D * ( TEMPBA / 4D0 - TEMPIN )
               STRESS(1,M) = STRESS(1,M) + D * (ELAS(1)+ELAS(2)+ELAS(4))
               STRESS(2,M) = STRESS(2,M) + D * (ELAS(2)+ELAS(3)+ELAS(5))
               STRESS(3,M) = STRESS(3,M) + D * (ELAS(4)+ELAS(5)+ELAS(6))
               STRESS(4,M) = STRESS(4,M) + D * (ELAS(7)+ELAS(8)+ELAS(9))
               STRESS(5,M) = STRESS(5,M) +D*(ELAS(11)+ELAS(12)+ELAS(13))
               STRESS(6,M) = STRESS(6,M) +D*(ELAS(16)+ELAS(17)+ELAS(18))
   19       CONTINUE
         ENDIF
      ENDIF
C
C     CALCUL DES CONTRAINTES INITIALES
C     --------------------------------
      IF( NDSMCI .GT. 0 .AND. LTDEVO(LPCOIN,NOOBVC) .GT. 0 ) THEN
C        LA VALEUR DES CONTRAINTES INITIALES EN CE POINT
         CALL RECOIN( 4, NOOBVC, 6, F(1), F(2), F(3),
     %                LTDEVO(LPCOIN,NOOBVC), CONINI )
         DO 29 M=1,NDSM
            IF( NDSMCI .EQ. 1 ) THEN
               MM = 1
            ELSE
               MM = M
            ENDIF
            DO 27 K=1,6
               STRESS(K,M) = STRESS(K,M) + CONINI(MM,K)
  27        CONTINUE
  29     CONTINUE
      ENDIF
C
      RETURN
      END
