      SUBROUTINE ELAILC( KNOMOB, MOREE2, D2PI,
     %                   NDIM,   NDPGST, MNXYZP, MNXYZN,
     %                   NBCODE, NBTYEL, MNNPEF,
     %                   MNTPOB, MNTAUX,
     %                   NUMIOB, NUMAOB,
     %                   MNDOEL, PENALI, RELMIN, AMORTM, AMORTK,
     %                   MNELAS, MNFORC, MNTAEL, MNX,
     %                   MNIP,   MNNODL,
     %                   NORESO, MNLPLK, MNLPCK, NIVEAU, NBRDKG,
     %                   NCODMG, NBRDMG,
     %                   TPSINI, TPSFIN, DT,     NBDEPL, TESTDE, DTSTDE,
     %                   NTVEDE, MNVEDE, NTDLDE, MNUG0,
     %                   NOTHEL, MNVETE, NBTEMP, NTDLTE, MNTEM0,
     %                   NPIMAX, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LES DEPLACEMENTS EN 2D OU 3D OU AXISYMETRIQUE
C -----    EN ELASTICITE LINEAIRE INSTATIONNAIRE AVEC DES
C          ELEMENTS FINIS LAGRANGE DE DEGRE 1 OU 2
C          AVEC UN SCHEMA EN TEMPS DE NEWMARK A PAS CONSTANT
C
C   (a2 + dt g2 amortM) [M] + dt (g2 amortK + dt b2) [K] =
C
C   Somme dt**2 bi {F(tn+i)}
C   i=0,2
C
C - Somme ( (ai + dt gi amortM) [M] + dt (gi amortK + dt bi) [K] ) {un+i}
C   i=0,1
C
C cf Edwige GODLEWSKI  &  Annie PUECH-RAOULT
C    Equations d'evolutions lineaires du 2-eme ordre et methodes multipas
C    RAIRO Analyse Numerique Vol 13 n4 1979  pages 329 a 353
C
C ENTREES:
C --------
C KNOMOB : NOM DE L'OBJET D'ELASTICITE INSTATIONNAIRE A TRAITER
C MOREE2 : NOMBRE DE MOTS   D'UNE VARIABLE REELLE DOUBLE PRECISION
C D2PI   : NOMBRE 2 x PI DANS UNE VARIABLE REELLE DOUBLE PRECISION
C NOAXIS : 1 SI PB AXISYMETRIQUE, 0 SINON
C
C NTLXOB : NUMERO DU TMS DU LEXIQUE DE L'OBJET KNOMOB
C MNTOPO : NUMERO DU TMS TOPOLOGIE  DE L'OBJET KNOMOB
C NDIM   : DIMENSION DES COORDONNEES DES POINTS ( 2 OU 3 )
C NDPGST : CODE D'IDENTIFICATION DES SOMMETS POINTS NOEUDS
C MNXYZP : ADRESSE MCN DU TABLEAU XYZPOINT DE L'OBJET KNOMOB
C MNXYZN : ADRESSE MCN DU TABLEAU XYZNOEUD DE L'OBJET KNOMOB
C
C NBCODE : NOMBRE DE COMPOSANTES EN UN NOEUD DU VECTEUR DEPLACEMENT
C NBTYEL : NOMBRE DE TYPES D'EF DU MAILLAGE DE CET OBJET
C MNNPEF : ADRESSE MCN DU TABLEAU DES ADRESSES MCN DES TMS NPEF"TYPE EF
C NBTTEF : NOMBRE TOTAL D'EF DU MAILLAGE
C
C MNTPOB : ADRESSE MCN DU TABLEAU POINTEUR SUR LES TABLEAUX POBA DES EF
C NBDLMX : NOMBRE MAXIMAL DE DEGRES DE LIBERTE (TEMPERATURES) D'UN EF
C MOAUX  : NOMBRE DE OTS AUXILIAIRES NECESSAIRES AU CALCUL DES EF
C MNTAUX : ADRESSE MCN DU TABLEAU AUXILIAIRE POUR LES EF
C
C NUMIOB : NUMERO MINIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C NUMAOB : NUMERO MAXIMAL DU PLSV DANS LA DEFINITION DE L'OBJET
C NBOBIN : NOMBRE DE VOLUMES en 3D, SURFACES en 2D DE L'OBJET
C MNOBIN : ADRESSE MCN DU DEBUT DU TABLEAU NUOBIN (PARTIE DE TOPOLOGIE)
C NBOBCL : NOMBRE DE PLS en 3D, PL en 2D DE L'OBJET
C MNOBCL : ADRESSE MCN DU DEBUT DU TABLEAU NUOBCL (PARTIE DE TOPOLOGIE)
C
C MNDOEL : LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C          TABLEAUX DECRIVANT LES DONNEES ELASTICITE DE L'OBJET COMPLET
C
C IEMASS : NOMBRE DE TMS MASSE            DES SV DE L'OBJET RETROUVES
C IEYOUN : NOMBRE DE TMS YOUNG (+POISSON) DES SV DE L'OBJET RETROUVES
C IEDILA : NOMBRE DE TMS DILATATION       DES SV DE L'OBJET RETROUVES
C
C PENALI : PENALISATION DE LA CONDITION DE DEPLACEMENT IMPOSE
C          SA VALEUR DOIT ICI ETRE TRES GRANDE CAR ELLE VAUT 1/EPSILON
C RELMIN : PLUS PETIT REEL SERVANT DE MARQUEUR DE NON UTILISATION
C AMORTM : COEFFICIENT D'AMORTISSEMENT DE LA MATRICE DE MASSE
C AMORTK : COEFFICIENT D'AMORTISSEMENT DE LA MATRICE DE RAIDEUR
C
C MNELAS : 27 REELS DOUBLE PRECISION POUR LE COEFFICIENT DE YOUNG AUX PT INTEGR
C MNFORC : ADRESSE MCN DU TABLEAU DES FORCES EXERCEES EN UN POINT
C MOTAEL : NOMBRE DE MOTS DECLARES DU TABLEAU DES TABLEAUX ELEMENTAIRES
C MNTAEL : ADRESSE MCN DES TABLEAUX ELEMENTAIRES
C MNX    : ADRESSE MCN DU TABLEAU DES 3 COORDONNEES DES NOEUDS=POINTS DE L'EF
C MNIP   : NUMERO DES DL PAR COMPOSANTES A PAR NOEUDS
C MNNODL : ADRESSE MCN DU TABLEAU DES NUMEROS DES NOEUDS DE L'EF COURANT
C
C NORESO : CODE RESOLUTION DES SYSTEMES LINEAIRES
C          1 FACTORISATION DE CHOLESKY ET MATRICES PROFILS
C          2 GRADIENT CONJUGUE PRECONDITIONNE PAR NIVEAUX ET MATRICES MORSES
C MNLPLK : ADRESSE MCN DES POINTEURS SUR LES COEFFICIENTS DIAGONAUX DE LA MATRIC
C MNLPCK : ADRESSE MCN DU NUMERO DE COLONNE DES COEFFICIENTS DE LA MATRICE MORSE
C NIVEAU : NIVEAU DE FACTORISATION INCOMPLETE DE LA MATRICE DE PRECONDITIONNEMEN
C          A CHOISIR PARMI 0 1 2
C NBRDKG : NOMBRE DE REELS DOUBLE PRECISION DE LA MATRICE KG DE RAIDEUR
C NCODMG : 1 SI MATRICE DE MASSE SYMETRIQUE
C          0 SI MATRICE DE MASSE DIAGONALE
C         -1 SI MATRICE DE MASSE NON SYMETRIQUE
C NBRDMG : NOMBRE DE REELS DOUBLE PRECISION DE LA MATRICE MG DE MASSE
C
C TPSINI : TEMPS INITIAL DU CALCUL
C TPSFIN : TEMPS FINAL   DU CALCUL
C DT     : PAS CONSTANT DU TEMPS
C NBDEPL : NUMERO DU DERNIER VECTEUR TEMPERATURE STOCKE = VECTEUR A TPSINI
C TESTDE : TEMPS DU PROCHAIN VECTEUR"DEPLACEMENT A STOCKER
C DTSTDE : PAS CONSTANT DU TEMPS ENTRE 2 STOCKAGES DU VECTEUR"DEPLACT
C
C NTVEDE : NUMERO      DU TMS VECTEUR"DEPLACT DE L'OBJET
C MNVEDE : ADRESSE MCN DU TMS VECTEUR"DEPLACT DE L'OBJET
C NTDLDE : NOMBRE TOTAL DE DEGRES DE LIBERTE DES DEPLACEMENTS DE L'OBJET
C MNUG0  : ADRESSE MCN DES 3 TMS DES VECTEURS DEPLACEMENT AUX TEMPS n-1 n n+1
C          A L'INSTANT INITIAL ET SUIVANT
C
C NOTHEL : 1  POUR LA RESOLUTION DE L'ELASTICITE SEULE
C          2  POUR LA RESOLUTION DE LA THERMO-ELASTICITE
C EN THERMO-ELASTICITE NOTHEL=2 LES VARIABLES SUIVANTES SONT >0 ET =0 SINON
C
C NTVETE : NUMERO      DU TMS DES VECTEUR"TEMPERATURE
C MNVETE : ADRESSE MCN DU TMS DES VECTEUR"TEMPERATURE
C NBTEMP : NUMERO      DU VECTEUR"TEMPERATURE UTILISE AU TEMPS TPSINI
C NTDLTE : NOMBRE DE D.L. EN TEMPERATURE
C MNTEM0 : ADRESSE MCN DU VECTEUR TEMPERATURE CALCULE AU TEMPS TPSINI
C          CE VECTEUR TEMPERATURE EST UNE INTERPOLATION LINEAIRE ENTRE
C          LES TEMPERATURES AUX 2 TEMPS QUI ENCADRENT LE TEMPS TPSINI
C          =0 SI PAS DE THERMO-ELASTICITE
C
C SORTIES:
C --------
C NPIMAX : NOMBRE MAXIMAL DE POINTS D'INTEGRATION D'UN EF DU MAILLAGE
C IERR   : 0 SI PAS D'ERREUR D'EXECUTION
C          NON NUL SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: FERNANDES-VARELA DEA ANALYSE NUMERIQUE UPMC PARIS JANVIER 1998
C MODIFS: ALAIN PERRONNET      ANALYSE NUMERIQUE UPMC PARIS MARS    1999
C23456---------------------------------------------------------------012
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/donela.inc"
      include"./incl/donele.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a_objet__definition.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___young.inc"
      include"./incl/a___dilatation.inc"
      include"./incl/a___force.inc"
      include"./incl/a___fixation.inc"
      include"./incl/a___vecteur.inc"
      include"./incl/a___profil.inc"
      include"./incl/a___contrainte.inc"
      include"./incl/a___contrinit.inc"
      include"./incl/a___deplactinit.inc"
      include"./incl/a___vitesseinit.inc"
      include"./incl/a___tableau1r.inc"
      include"./incl/msvaau.inc"
      include"./incl/ponoel.inc"
      include"./incl/ctemps.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
C
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
C
      CHARACTER*(*)     KNOMOB
      DOUBLE PRECISION  PENALI,RELMIN,D2PI
      DOUBLE PRECISION  AMORTM,AMORTK
      DOUBLE PRECISION  DT,DTDT,ALPHA0,ALPHA1,D(1)
      INTEGER           NUMIOB(4),NUMAOB(4),MNDOEL(4)
C
C     ADRESSES DES VECTEURS GLOBAUX U0,U1,B0,B1,B2
      INTEGER           MNUG(0:2),MNBG(0:2)
C
C     3 MATRICES GLOBALES
      DOUBLE PRECISION, allocatable, dimension(:) :: MG
      DOUBLE PRECISION, allocatable, dimension(:) :: KG
      DOUBLE PRECISION, allocatable, dimension(:) :: KM
      INTEGER           IERMGALLOC, IERKGALLOC, IERKMALLOC
      INTRINSIC         ALLOCATED, REAL
C
C     PARAMETRES DU SCHEMA DE NEWMARK
      DOUBLE PRECISION  ALP(0:2),BET(0:2),GAM(0:2)
      DATA              ALP/  1.D0  ,-2.D0,  1.D0   /
      DATA              BET/  0.25D0, 0.5D0, 0.25D0 /
      DATA              GAM/ -0.5D0 , 0.D0 , 0.5D0  /
C
      IERR = 0
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10000) KNOMOB
      ELSE
         WRITE(IMPRIM,20000) KNOMOB
      ENDIF
10000 FORMAT(/' CALCUL DE L''ELASTICITE INSTATIONNAIRE DE L''OBJET ',A)
20000 FORMAT(/' COMPUTATION of the UNSTEADY ELASTICITY of OBJECT ',A)
C
C     PROTECTION DES ADRESSES POUR EVITER DES PROBLEMES LORS
C     DE LA DESTRUCTION DES TABLEAUX
      IERMGALLOC = 1
      IERKGALLOC = 1
      IERKMALLOC = 1
      MNBG0  = 0
      MNLPLC = 0
      MNLPCC = 0
      MNAGC  = 0
      MNAUGC = 0
      MNDIGC = 0
      MNDIR  = 0
      MNDAD  = 0
      MNBET  = 0
      MNAUX1 = 0
      MNAUX2 = 0
      MNAUX3 = 0
      MNAUX4 = 0
      MNADIR = 0
      TEMPT0 = 0
      TEMPT1 = 0
C
C     LE TEMPS INITIAL DE L'ETUDE DES DEPLACEMENTS
C     ============================================
      TEMPS = TPSINI
      DTDT  = DT * DT
C
C     LE NOMBRE DE PAS DE TEMPS EN ELASTICITE
      NBPAS = NINT( ( TPSFIN - TPSINI ) / DT )
C
C     LE NOMBRE TOTAL DE VECTEUR"DEPLACT A STOCKER
      MXDEPL = MCN( MNVEDE + WBVECT )
C
C     LE NOMBRE DE CAS DE CHARGE A CHAQUE TEMPS
      NDSM   = 1
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10001)AMORTM,AMORTK,PENALI,TPSINI,TPSFIN,DT,NBPAS,
     %                      MXDEPL,NTDLDE
      ELSE
         WRITE(IMPRIM,20001)AMORTM,AMORTK,PENALI,TPSINI,TPSFIN,DT,NBPAS,
     %                      MXDEPL,NTDLDE
      ENDIF
10001 FORMAT(/
     %' AMORTISSEMENT EN MASSE      AMORTM       =',G15.7/
     %' AMORTISSEMENT EN RIGIDITE   AMORTK       =',G15.7/
     %' PENALISATION                PENALI       =',G15.7/
     %' TEMPS INITIAL               TPSINI       =',G15.7/
     %' TEMPS FINAL                 TPSFIN       =',G15.7/
     %' PAS DE TEMPS                DT           =',G15.7/
     %' NOMBRE DE PAS DE TEMPS A CALCULER        =',I8/
     %' NOMBRE DE VECTEURS DEPLACEMENT A STOCKER =',I8/
     %' NOMBRE DE DEGRES DE LIBERTE DEPLACEMENT  =',I8/)
20001 FORMAT(/
     %' MASS DUMPING       AMORTM =',G15.7/
     %' STIFFNESS DUMPING  AMORTK =',G15.7/
     %' PENALISATION       PENALI =',G15.7/
     %' INITIAL  TIME      TPSINI =',G15.7/
     %' FINAL    TIME      TPSFIN =',G15.7/
     %' STEP of TIME       DT     =',G15.7/
     %' NUMBER of STEP of TIME to be COMPUTED       =',I8/
     %' NUMBER of DISPLACEMENT VECTORS to be STORED =',I8/
     %' NUMBER of DISPLACEMENT DoF For each VECTOR  =',I8/)
C
C     DECLARATION DES MATRICES SYMETRIQUES GLOBALES [M] [K] ET [KM]
C     =============================================================
C     ALLOCATION DYNAMIQUE EN FORTRAN 90 DES MATRICES PROFIL M K KM
      WRITE(IMPRIM,*)
      WRITE(IMPRIM,*) 'ALLOCATION DEMAND  of',NBRDKG,
     %                ' DOUBLE PRECISION of the [MG] [KG] [KM] MATRICES'
      ALLOCATE ( MG(1:NBRDKG), STAT=IERMGALLOC )
      IF( IERMGALLOC .NE. 0 ) THEN
       WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBRDKG,
     %                ' DOUBLE PRECISION of the [MG] MATRIX'
         IERR = IERMGALLOC
         GOTO 9999
      ENDIF
C
      ALLOCATE ( KG(1:NBRDKG), STAT=IERKGALLOC )
      IF( IERKGALLOC .NE. 0 ) THEN
       WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBRDKG,
     %                ' DOUBLE PRECISION of the [KG] MATRIX'
         IERR = IERKGALLOC
         GOTO 9999
      ENDIF
      WRITE(IMPRIM,*) 'ALLOCATION CORRECT of',NBRDKG,
     %                ' DOUBLE PRECISION of the [MG] and [KG] MATRICES'
C
      ALLOCATE ( KM(1:NBRDKG), STAT=IERKMALLOC )
      IF( IERKMALLOC .NE. 0 ) THEN
       WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBRDKG,
     %                ' DOUBLE PRECISION of the [KM] MATRIX'
         IERR = IERKMALLOC
         GOTO 9999
      ENDIF
      WRITE(IMPRIM,*) 'ALLOCATION CORRECT of',NBRDKG,
     %                ' DOUBLE PRECISION of the [MG] [KG] [KM] MATRICES'
      WRITE(IMPRIM,*)
C
      IF( NOTHEL .EQ. 2 ) THEN
C
C        THERMO-ELASTICITE. RECUPERATION DES CARTES DE TEMPERATURES
C        ==========================================================
C        LE NOMBRE DE DL EN TEMPERATURE
         NTDLTE = MCN( MNVETE + WBCOVE )
C        LE NOMBRE DE VECTEUR"TEMPERATURE STOCKES
         MXTEMP = MCN( MNVETE + WBVECT )
C
C        LE VECTEUR"TEMPERATURE UTILISE AU TEMPS TPSINI
         MNTEMP = MNVETE + WECTEU + MOREE2 * NTDLTE * (NBTEMP-1)
C
C        ADRESSE DU DEBUT DES TEMPS DE STOCKAGE DE VECTEUR"TEMPERATURE
         MNTETE = MNVETE + WECTEU + MOREE2 * NTDLTE * MXTEMP - 1
C
C        LE TEMPS DU VECTEUR"TEMPERATURE STOCKE PROCHE DE TPSINI
         TEMPT0 = RMCN(MNTETE+NBTEMP)
         TEMPT1 = RMCN(MNTETE+NBTEMP+1)
C
      ELSE
C
C        PAS DE THERMO-ELASTICITE => PAS DE TEMPERATURES
         NTDLTE = 0
         MNTEMP = 0
         MNTETE = 0
         MXTEMP = 0
C
      ENDIF
C
C     CALCUL DES MATRICES DE MASSE ET RAIDEUR SUPPOSES INDEPENDANTES
C     DU TEMPS ET DES DEPLACEMENTS
      CALL ELAMKB( 1,      1,      0,
     %             PENALI, D2PI,   NDIM,
     %             NBTYEL, MNNPEF, NDPGST,
     %             MNTPOB, MXPOBA, MNTAUX,
     %             MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %             MNELAS, MNFORC, MNTAEL, MNX,    MNIP,   MNNODL,
     %             MNTEM0, NTDLTE,
     %             NORESO, MNLPLK, MNLPCK,
     %             NBRDMG, MG,     NBRDKG, KG,   NTDLDE, 0,
     %             NCODMG, NCODKG, NPIMAX )
C
C     CALCUL DE LA MATRICE DU SYSTEME [KM]
      ALPHA0 = ALP(2) + DT * GAM(2) * AMORTM
      ALPHA1 = DTDT*BET(2)+DT*GAM(2)* AMORTK
      CALL MUA2PD( NTDLDE, ALPHA0, NCODMG, MCN(MNLPLK), MG,
     %                     ALPHA1, NCODKG, MCN(MNLPLK), KG,
     %                                     MCN(MNLPLK), KM )
C
      IF( NORESO .EQ. 1 ) THEN
C
C        FACTORISATION DE CHOLESKY DE LA MATRICE PROFIL [KM] DU SYSTEME
C        ==============================================================
         IF( LANGAG .EQ. 0 ) THEN
           WRITE(IMPRIM,*)'DEBUT FACTORISATION DE LA MATRICE DU SYSTEME'
         ELSE
           WRITE(IMPRIM,*)'SYSTEM MATRIX L tL FACTORIZATION'
         ENDIF
         CALL CHOLPR( NTDLDE, NCODKG, MCN(MNLPLK), KM,
     %                KM, IERR )
         IF( IERR .NE. 0 ) THEN
            NBLGRC(NRERR) = 2
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'MATRICE NON INVERSIBLE'
               KERR(2) = 'REVOYEZ LES CONDITIONS AUX LIMITES'
            ELSE
               KERR(1) = 'NOT INVERSIBLE MATRIX'
               KERR(2) = 'CORRECT the BOUNDARY CONDITIONS'
            ENDIF
            CALL LEREUR
            IERR = 7
            GOTO 9999
         ENDIF
C
      ELSE
C
C        CALCUL DE LA MATRICE DE PRECONDITIONNEMENT POUR LE GC STOCKAGE MORSE
C        ====================================================================
C        CALCUL DU SQUELETTE DE LA MATRICE DE PRECONDITIONNEMENT
         CALL CALPNT( NTDLDE,NIVEAU,NCODKG,MNLPLK,MNLPCK,
     %                MNLPLC,MNLPCC,MNLPLU,COMP,IERR )
         LOLPCC = MCN(MNLPLC+NTDLDE)
C        VERIFICATION DE LA FACTORISATION
         IF( IERR .NE. 0 ) THEN
            WRITE(KERR(MXLGER)(1:4),'(I4)') NIVEAU
            NBLGRC(NRERR) = 3
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1)= 'PROBLEME de FACTORISATION INCOMPLETE de NIVEAU'
     %               // KERR(MXLGER)(1:4)
               KERR(2)= 'ABANDON de la METHODE du GRADIENT CONJUGUE'
               KERR(3)= '=> AUGMENTER NIVEAU ou CHOISIR CHOLESKY'
            ELSE
               KERR(1)='PROBLEM of INCOMPLETE FACTORIZATION of LEVEL'
     %               // KERR(MXLGER)(1:4)
               KERR(2)= 'EXIT of the CONJUGATE GRADIENT METHOD'
               KERR(3)= '=> AUGMENT LEVEL or CHOOSE CHOLESKY'
            ENDIF
            CALL LEREUR
            GOTO 9998
         ENDIF
C
C        DECLARATION INITIALISATION DE LA MATRICE MORSE DE CONDITIONNEMENT
C        TEST DE LA PLACE MEMOIRE DISPONIBLE
         CALL TNMCMX( 'REEL2', MAXVAR )
         IF( MAXVAR .LT. LOLPCC ) THEN
C            PLACE MEMOIRE INSUFFISANTE
             WRITE(KERR(MXLGER)(1:2),'(I2)') NIVEAU
             NBLGRC(NRERR) = 2
             IF( LANGAG .EQ. 0 ) THEN
            KERR(1)='PLACE MEMOIRE INSUFFISANTE'
            KERR(2)='DIMINUEZ LA VALEUR DU NIVEAU DU PRECONDITIONNEMENT'
     %             // KERR(MXLGER)(1:2)
             ELSE
            KERR(1)='NOT ENOUGH MEMORY'
            KERR(2)='DIMINISH the LEVEL' // KERR(MXLGER)(1:2)
             ENDIF
             CALL LEREUR
             GOTO 9998
         ENDIF
C
C        DECLARATION DE LA MATRICE DE PRECONDITIONNEMENT DE KM
         MNAGC = 0
         CALL TNMCDC( 'REEL2', LOLPCC, MNAGC )
C
         NBLGRC(NRERR) = 1
         WRITE(KERR(2)(1:2),'(I2)') NIVEAU
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'FACTORISATION INCOMPLETE de NIVEAU' //
     %                 KERR(2)(1:2)
         ELSE
            KERR(1) = 'INCOMPLETE CHOLESKY FACTORIZATION of LEVEL' //
     &                 KERR(2)(1:2)
         ENDIF
         CALL LERESU
         CALL INCHGC( NTDLDE,
     %                MCN(MNLPLK),MCN(MNLPCK),KM,
     %                MCN(MNLPLC),MCN(MNLPCC),MCN(MNAGC), IERR )
C        VERIFICATION DE LA STABILITE
         IF( IERR .NE. 0 ) THEN
C           LA FACTORISATION EST INSTABLE : ABANDON DES CALCULS
            WRITE(KERR(MXLGER)(1:4),'(I4)') NIVEAU
            NBLGRC(NRERR) = 3
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'FACTORISATION INSTABLE au NIVEAU '
     %              // KERR(MXLGER)(1:4)
               KERR(2) = 'ABANDON de la METHODE du GRADIENT CONJUGUE'
               KERR(3) = '=> AUGMENTER NIVEAU ou CHOISIR CHOLESKY'
            ELSE
               KERR(1)='UNSTABLE INCOMPLETE FACTORIZATION at LEVEL '
     %              // KERR(MXLGER)(1:4)
               KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
               KERR(3) = '=> AUGMENT LEVEL or CHOOSE CHOLESKY'
            ENDIF
            CALL LEREUR
            GOTO 9998
         ENDIF
C
C        LES TABLEAUX AUXILIAIRES DE GCPRCH
         LOAUGC = NTDLDE * NDSM * 3
         CALL TNMCDC( 'REEL2' , LOAUGC , MNAUGC )
         MNAUX2 = MNAUGC
         MNAUX3 = MNAUX2 + NTDLDE * NDSM * MOREE2
         MNAUX4 = MNAUX3 + NTDLDE * NDSM * MOREE2
C
C        NBDIR  = NOMBRE DE DIRECTIONS CONSERVEES POUR STABILISER
         LODIR  = 0
         NBDIR  = 5
         LODIGC = (NTDLDE+1) * NBDIR * 2
         CALL TNMCDC( 'REEL2', LODIGC, MNDIGC )
         MNDIR   = MNDIGC
         MNADIR  = MNDIGC + NTDLDE * NBDIR * MOREE2
         MNDAD   = MNADIR + NTDLDE * NBDIR * MOREE2
         MNBET   = MNDAD  + NBDIR * MOREE2
      ENDIF
C
C     LES VECTEURS SECONDS MEMBRES GLOBAUX
C     ====================================
C     DEUX VECTEURS DEPLACEMENTS ONT DEJA ETE DECLARES
C     LE DEPLACEMENT A L'INSTANT Tn-1
      MNUG(0) = MNUG0
C     LE DEPLACEMENT A L'INSTANT Tn
      MNUG(1) = MNUG0 + MOREE2 * NTDLDE
C     LE DEPLACEMENT A L'INSTANT Tn+1
      MNUG(2) = MNUG(1) + MOREE2 * NTDLDE
C
C     ADRESSE DU VECTEUR"DEPLACT DERNIER STOCKE
      MNDEPL = MNVEDE + WECTEU + MOREE2 * NTDLDE * (NBDEPL-1)
C     MNTEM0 EST LE VECTEUR TEMPERATURE INTERPOLE A L'INSTANT TPSINI
C     ADRESSE DU TEMPS DU DERNIER STOCKAGE DU VECTEUR"DEPLACT
      MNTEDE = MNVEDE + WECTEU + MOREE2 * NTDLDE * MXDEPL + NBDEPL - 1
C
C     DECLARATION DES 3 TABLEAUX SECONDS MEMBRES AUXILIAIRES
      CALL TNMCDC( 'REEL2', NTDLDE*3, MNBG0 )
      MNBG(0) = MNBG0
      MNBG(1) = MNBG(0) + MOREE2 * NTDLDE
      MNBG(2) = MNBG(1) + MOREE2 * NTDLDE
C
C     CALCUL DU SECOND MEMBRE AU TEMPS INITIAL TPSINI
C     ===============================================
      N = 0
      CALL ELAMKB( 0,      0,      1,
     %             PENALI, D2PI,   NDIM,
     %             NBTYEL, MNNPEF, NDPGST,
     %             MNTPOB, MXPOBA, MNTAUX,
     %             MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %             MNELAS, MNFORC, MNTAEL, MNX,  MNIP, MNNODL,
     %             MNTEM0, NTDLTE,
     %             N,      N,      N,
     %             N,      D,      N,      D, NTDLDE,  MNBG(0),
     %             N,      N,      NPIMAX )
C
C     CONSTRUCTION DES TABLEAUX DES NUMEROS ET VALEURS DES FORCES NODALES
C     ===================================================================
      CALL ELFNFX( NTDLDE, NBCODE, NBTYEL, MNNPEF, NDPGST,
     %             MNXYZN, NUMIOB, MNDOEL, RELMIN,
     %             NBRFNX, MONFNX, MNNFNX, MNVFNX,
     %             IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     ASSEMBLAGE DES FORCES NODALES
      CALL ASFONO( NTDLDE,NDSM,NBRFNX,MCN(MNNFNX),MCN(MNVFNX),RELMIN,
     %             MCN(MNBG(0)) )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) 'Le VECTEUR B0 est CALCULE au TEMPS',TEMPS
      ELSE
         WRITE(IMPRIM,*) 'The VECTOR B0 is COMPUTED at TIME',TEMPS
      ENDIF
C
C     CALCUL DU SECOND MEMBRE AU TEMPS T1 = TPSINI + DT
C     =================================================
      TEMPS = REAL( TPSINI + DT )
C
      IF( NOTHEL .EQ. 2 ) THEN
C
C        THERMO-ELASTICITE: IL EXISTE DES TEMPERATURES STOCKEES
         IF( TEMPS .GE. TEMPT1*0.9999 ) THEN
C
C           PASSAGE AU TEMPS THERMIQUE DE STOCKAGE SUIVANT
            NBTEMP = NBTEMP + 1
            TEMPT0 = RMCN(MNTETE+NBTEMP)
            TEMPT1 = RMCN(MNTETE+NBTEMP+1)
            MNTEMP = MNTEMP + MOREE2 * NTDLTE
C
         ENDIF
C
C        CALCUL DES NTDLTE TEMPERATURES AUX NOEUDS A L'INSTANT TPSINI + DT
C        INTERPOLATION LINEAIRE ENTRE TEMP0 ET TEMP1 A L'INSTANT TEMPS
         ALPHA0 = ( TEMPT1 - TEMPS  ) / ( TEMPT1 - TEMPT0 )
         ALPHA1 = ( TEMPS  - TEMPT0 ) / ( TEMPT1 - TEMPT0 )
         CALL CL2VED( NTDLTE, ALPHA0, MCN(MNTEMP),
     %                        ALPHA1, MCN(MNTEMP+MOREE2*NTDLTE),
     %                MCN(MNTEM0) )
C
      ENDIF
C
C     CONSTRUCTION DU SECOND MEMBRE GLOBAL AU TEMPS T1 = TPSINI + DT
      N = 0
      CALL ELAMKB( 0,      0,      1,
     %             PENALI, D2PI,   NDIM,
     %             NBTYEL, MNNPEF, NDPGST,
     %             MNTPOB, MXPOBA, MNTAUX,
     %             MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %             MNELAS, MNFORC, MNTAEL, MNX,    MNIP,   MNNODL,
     %             MNTEM0, NTDLTE,
     %             N,      N,      N,
     %             N,      D,      N,      D, NTDLDE,  MNBG(1),
     %             N,      N,      NPIMAX )
C
C     ASSEMBLAGE DES FORCES NODALES AU TEMPS T1 = TPSINI + DT
      CALL ASFONO( NTDLDE,NDSM,NBRFNX,MCN(MNNFNX),MCN(MNVFNX),RELMIN,
     %             MCN(MNBG(1)) )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) 'Le VECTEUR B1 est CALCULE au TEMPS',TEMPS
         WRITE(IMPRIM,10009)
      ELSE
         WRITE(IMPRIM,*) 'The VECTOR B1 is COMPUTED at TIME',TEMPS
         WRITE(IMPRIM,20009)
      ENDIF
C
10009 FORMAT(/'-------------------------------'/
     %        'DEMARRAGE DE LA BOUCLE EN TEMPS'/
     %        '-------------------------------')
20009 FORMAT(/'-------------------------'/
     %        'START OF THE LOOP OF TIME'/
     %        '-------------------------')
C
      DO 90 ITEMPS=0,NBPAS-2
C
C        L'INSTANT COURANT Tn+2
C        ----------------------
         TEMPS = REAL( TEMPS + DT )
C
         IF( NOTHEL .EQ. 2 .AND. TEMPS .LE. TPSFIN ) THEN
C
            IF( TEMPS .GE. 0.9999*TEMPT1 ) THEN
               IF( NBTEMP .LT. MXTEMP-1 ) THEN
C                 PASSAGE AU TEMPS THERMIQUE SUIVANT
                  NBTEMP = NBTEMP + 1
                  TEMPT0 = RMCN(MNTETE+NBTEMP)
                  TEMPT1 = RMCN(MNTETE+NBTEMP+1)
                  MNTEMP = MNTEMP + MOREE2 * NTDLTE
               ELSE
C                 NBTEMP=MXTEMP-1 => RMCN(MNTETE+NBTEMP+2) ILLICITE
C                 LE VECTEUR DES TEMPERATURES RESTE INCHANGE POUR PERMETTRE
C                 L'UTILISATION DU SUIVANT QUI EST LE DERNIER
                  TEMPT0 = RMCN(MNTETE+NBTEMP)
                  TEMPT1 = RMCN(MNTETE+NBTEMP+1)
               ENDIF
            ENDIF
C
C           CALCUL DES NTDLTE TEMPERATURES AUX NOEUDS A L'INSTANT TEMPS Tn+2
C           INTERPOLATION LINEAIRE ENTRE TEMP0 ET TEMP1 A L'INSTANT TEMPS
            ALPHA0 = ( TEMPT1 - TEMPS  ) / ( TEMPT1 - TEMPT0 )
            ALPHA1 = ( TEMPS  - TEMPT0 ) / ( TEMPT1 - TEMPT0 )
            CALL CL2VED( NTDLTE, ALPHA0, MCN(MNTEMP),
     %                           ALPHA1, MCN(MNTEMP+MOREE2*NTDLTE),
     %                   MCN(MNTEM0) )
         ENDIF
C
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10010) TEMPS
         ELSE
            WRITE(IMPRIM,20010) TEMPS
         ENDIF
10010    FORMAT(/' TEMPS=',G14.6)
20010    FORMAT(/' TIME=' ,G14.6)
C
C        CALCUL DU SECOND MEMBRE A L'INSTANT TEMPS Tn+2
         N = 0
         CALL ELAMKB( 0,      0,      1,
     %                PENALI, D2PI,   NDIM,
     %                NBTYEL, MNNPEF, NDPGST,
     %                MNTPOB, MXPOBA, MNTAUX,
     %                MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %                MNELAS, MNFORC, MNTAEL, MNX,    MNIP,   MNNODL,
     %                MNTEM0, NTDLTE,
     %                N,      N,      N,
     %                N,      D,      N,      D, NTDLDE,   MNBG(2),
     %                N,      N,      NPIMAX )
C
C        ASSEMBLAGE DES FORCES NODALES A L'INSTANT TEMPS Tn+2
         CALL ASFONO( NTDLDE,NDSM,NBRFNX,MCN(MNNFNX),MCN(MNVFNX),RELMIN,
     %                MCN(MNBG(2)) )
C
C        CALCUL DU SECOND MEMBRE C DU SYSTEME A RESOUDRE AU TEMPS Tn+2
         CALL NEWMBG( NTDLDE, ALP,BET,GAM,  AMORTM,AMORTK, DT,
     %                NORESO, MCN(MNLPLK),  MCN(MNLPCK),
     %                NCODMG, MG,   NCODKG, KG,
     %                MCN(MNUG(0)), MCN(MNUG(1)),
     %                MCN(MNBG(0)), MCN(MNBG(1)), MCN(MNBG(2)),
     %                MCN(MNUG(2)) )
C
         IF( NORESO .EQ. 1 ) THEN
C
C           RESOLUTION DU SYSTEME FACTORISE AU TEMPS Tn+2
            CALL DRCH1D( NTDLDE, NCODKG, MCN(MNLPLK), KM,
     %                   NDSM,   MCN(MNUG(2)), 2,
     %                   MCN(MNUG(2)) )
C
         ELSE
C
C           RESOLUTION DU SYSTEME PAR GRADIENT CONJUGUE
C           LE VECTEUR INITIAL DU GC EST LE DERNIER VECTEUR CALCULE
C           MISE A ZERO DU TABLEAU DES DIRECTIONS
            CALL AZEROD( LODIR, MCN(MNDIGC) )
            CALL GCPRCH( NTDLDE,  1,           NBDIR,
     %              MCN(MNLPLK),  MCN(MNLPCK), KM,         MCN(MNUG(2)),
     %              MCN(MNLPLC),  MCN(MNLPCC), MCN(MNAGC),
     %              MCN(MNUG(1)), MCN(MNAUX2), MCN(MNAUX3),
     %              MCN(MNAUX4),  MCN(MNDIR),  MCN(MNADIR),
     %              MCN(MNDAD),   MCN(MNBET),  MCN(MNUG(2)), IERR )
C
C           VERIFICATION DE LA CONVERGENCE DU GC
            IF( IERR .NE. 0 ) THEN
C
C              LA METHODE DU GC NE CONVERGE PAS => ABANDON DES CALCULS
               WRITE(KERR(MXLGER)(1:8),'(I8)') NIVEAU
               NBLGRC(NRERR) = 3
               IF( LANGAG .EQ. 0 ) THEN
                  KERR(1)='NON CONVERGENCE DU GC AU NIVEAU '
     %                 // KERR(MXLGER)(1:8)
                  KERR(2)='ABANDON DE LA METHODE DU GRADIENT CONJUGUE'
                KERR(3)='=> AUGMENTER NIVEAU ou CHOISIR CHOLESKY PROFIL'
               ELSE
                  KERR(1)='NO CONVERGENCE of CG at LEVEL '
     %                 // KERR(MXLGER)(1:8)
                  KERR(2) = 'EXIT of the CONJUGATE GRADIENT METHOD'
                  KERR(3) = '=> AUGMENT LEVEL or CHOOSE CHOLESKY'
               ENDIF
               IERR = 9
               GOTO 9998
            ENDIF
C
         ENDIF
C
         IF( TEMPS .GE. TESTDE*0.9999 ) THEN
C           OUI: LE TEMPS DU STOCKAGE DU VECTEUR"DEPLACT
            MNTEDE = MNTEDE + 1
            RMCN(MNTEDE) = TEMPS
C           LE TEMPS DU PROCHAIN STOCKAGE
            TESTDE = TEMPS + DTSTDE
C           TRANSFERT DU TABLEAU MNUG(2)
            MNDEPL = MNDEPL + NTDLDE * MOREE2
            CALL TRTATD( MCN(MNUG(2)), MCN(MNDEPL), NTDLDE )
            NBDEPL = NBDEPL + 1
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,10090) TEMPS,NTDLDE,NBDEPL,MXDEPL
            ELSE
               WRITE(IMPRIM,20090) TEMPS,NTDLDE,NBDEPL,MXDEPL
            ENDIF
         ENDIF
C
10090 FORMAT(' Au TEMPS',G14.6,' STOCKAGE de',I7,' DEPLACEMENTS',
     %       ' en COLONNE',I5,'/',I5,' du TMS VECTEUR"DEPLACT')
20090 FORMAT(' At TIME',G14.6,' STORAGE of',I7,' DEPLACEMENTS',
     %       ' in COLUMN',I5,'/',I5,' of TMS VECTEUR"DEPLACT')
C
C        PERMUTATION DES TABLEAUX POUR LE PAS DE TEMPS SUIVANT Tn+3
         MN      = MNUG(0)
         MNUG(0) = MNUG(1)
         MNUG(1) = MNUG(2)
         MNUG(2) = MN
C
         MN      = MNBG(0)
         MNBG(0) = MNBG(1)
         MNBG(1) = MNBG(2)
         MNBG(2) = MN
C
 90   CONTINUE
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10091)
      ELSE
         WRITE(IMPRIM,20091)
      ENDIF
10091 FORMAT(/'---------------------------------------'/
     %        'FIN de la BOUCLE de RESOLUTION en TEMPS'/
     %        '---------------------------------------')
20091 FORMAT(/'-------------------------'/
     %        'END of LOOP of TIME STEPS'/
     %        '-------------------------')
C
C     MISE A JOUR DU TMS 'VECTEUR"DEPLACT'
C     ====================================
      IF( ABS(RMCN(MNTEDE)-TEMPS) .GT. 1.E-4*ABS(TEMPS) ) THEN
C        OUI: LE TEMPS DU STOCKAGE DU VECTEUR"DEPLACT
         MNTEDE = MNTEDE + 1
         RMCN(MNTEDE) = TEMPS
C        TRANSFERT DU TABLEAU MNUG(1) LE DERNIER CALCULE
         MNDEPL = MNDEPL + NTDLDE * MOREE2
         CALL TRTATD( MCN(MNUG(1)), MCN(MNDEPL), NTDLDE )
         NBDEPL = NBDEPL + 1
         WRITE(IMPRIM,10090) TEMPS, NTDLDE, NBDEPL
      ENDIF
C
C     MISE A JOUR DU TMS VECTEUR"DEPLACT
      MCN( MNVEDE + WBCOVE ) = NTDLDE
      MCN( MNVEDE + WBVECT ) = NBDEPL
      MCN( MNVEDE + WBCPIN ) = NBDEPL
C     LA DATE
      CALL ECDATE( MCN(MNVEDE) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVEDE + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
      IF( MXDEPL .LT. NBDEPL ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,*) 'TROP DE VECTEUR"DEPLACT STOCKES'
         ELSE
            WRITE(IMPRIM,*) 'TOO MANY VECTEUR"DEPLACT STORED'
         ENDIF
         IERR = 10
         GOTO 9999
      ELSE IF( MXDEPL .GT. NBDEPL ) THEN
C        LE TABLEAU EST REDUIT
         L  = MNVEDE + WECTEU + NTDLDE * MXDEPL * MOREE2 - 1
         L1 = MNVEDE + WECTEU + NTDLDE * NBDEPL * MOREE2 - 1
         DO 95 I=1,NBDEPL
            RMCN(L1+I) = RMCN(L+I)
 95      CONTINUE
         CALL TAMSRA( NTVEDE, WECTEU+NTDLDE*NBDEPL*MOREE2+NBDEPL )
      ENDIF
C
C     LE NOMBRE DE MOTS DES MATRICES
      MN = NTDLDE + MOREE2 * (NBRDMG + 2 * NBRDKG)
      IF( NORESO .EQ. 2 ) THEN
         MN = MN+NBRDKG+NTDLDE+LOLPCC*(1+MOREE2)+MOREE2*(LOAUGC+LODIGC)
      ENDIF
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,19999) MN
      ELSE
         WRITE(IMPRIM,29999) MN
      ENDIF
19999 FORMAT('Les 3 MATRICES OCCUPENT',I10,' MOTS MEMOIRE' )
29999 FORMAT('The 3 MATRICES OCCUPY',I10,' MEMORY WORDS' )
C
      IF( NORESO .EQ. 1 ) GOTO 9999
C
C     ERREUR LORS DU GRADIENT CONJUGUE
C     ================================
 9998 IF( MNLPCK .GT. 0 ) CALL TNMCDS( 'ENTIER', NBRDKG,   MNLPCK )
      IF( MNLPLC .GT. 0 ) CALL TNMCDS( 'ENTIER', NTDLDE+1, MNLPLC )
      IF( MNLPCC .GT. 0 ) CALL TNMCDS( 'ENTIER', LOLPCC,   MNLPCC )
      IF( MNAGC  .GT. 0 ) CALL TNMCDS( 'REEL2',  LOLPCC,   MNAGC  )
      IF( MNAUGC .GT. 0 ) CALL TNMCDS( 'REEL2',  LOAUGC,   MNAUGC )
      IF( MNDIGC .GT. 0 ) CALL TNMCDS( 'REEL2',  LODIGC,   MNDIGC )
C
C     FERMETURE DE LA MATRICE POUR REDONNER DE LA PLACE EN MC
C     =======================================================
9999  IF( MNLPLK .GT. 0 ) CALL TNMCDS( 'ENTIER', NTDLDE+1, MNLPLK )
      IF( MNBG0  .GT. 0 ) CALL TNMCDS( 'REEL2',  NTDLDE*3, MNBG0  )
      IF( MNNFNX .GT. 0 ) CALL TNMCDS( 'ENTIER', MONFNX,   MNNFNX )
      IF( MNVFNX .GT. 0 ) CALL TNMCDS( 'REEL2',  MONFNX,   MNVFNX )
C     LES 3 MATRICES GLOBALES
      IF( IERKMALLOC .EQ. 0 ) DEALLOCATE( KM )
      IF( IERKGALLOC .EQ. 0 ) DEALLOCATE( KG )
      IF( IERMGALLOC .EQ. 0 ) DEALLOCATE( MG )
C
      RETURN
      END
