      SUBROUTINE EM2P1D( X,      NOOBSF, NUMISU, NUMASU, LTDESU,
     %                   NCODSM, MASSEF)
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DE LA MATRICE DE MASSE (DIAGONALE)
C -----    POUR UN TRIANGLE 2D DE TYPE TRIA 2P1D
C
C ENTREES:
C --------
C X      : LES 2 COORDONNEES DES 3 SOMMETS DU TRIANGLE
C NOOBSF : NUMERO DE LA SURFACE DE CE TRIANGLE
C NUMISU : NUMERO MINIMAL DES SURFACES DE L'OBJET
C NUMASU : NUMERO MAXIMAL DES SURFACES DE L'OBJET
C LTDESU : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES MASSE
C          DES SURFACES DE L'OBJET
C
C SORTIES:
C --------
C NCODSM : CODE DE STOCKAGE DE LA MATRICE ELEMENTAIRE DE MASSE
C          0 DIAGONALE
C MASSEF : MATRICE DE MASSE DIAGONALE (1,1) (2,2) ... (6,6)
C          RANGEE PAR NOEUDS ( U1S1,U2S1, U1S2,U2S2, U1S3,U2S3 )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS         MAI 1998
C23456---------------------------------------------------------------012
      include"./incl/donela.inc"
      DOUBLE PRECISION  MASSEF(6), RHO
      REAL              X(3, 2)
      INTEGER           LTDESU( 1:MXDOEL, NUMISU:NUMASU )
C
      DOUBLE PRECISION  DELTA, XYZPI(3)
C
C     CONTRIBUTION DE LA SURFACE
C     ==========================
C     JACOBIEN * POIDS
      DELTA = ABS(  (X(2,1) - X(1,1)) * (X(3,2) - X(1,2))
     %            - (X(3,1) - X(1,1)) * (X(2,2) - X(1,2)) ) / 6D0
C
C     CALCUL DES COEFFICIENTS DIAGONAUX DE LA MASSE ELEMENTAIRE
      NC = 1
      DO 10 L=1,3
C
C        RECHERCHE DE LA DENSITE SURFACIQUE DE MASSE
C        AU POINT D'INTEGRATION L = SOMMET L DU TRIANGLE
         XYZPI(1) = X(L,1)
         XYZPI(2) = X(L,2)
         XYZPI(3) = 0D0
         CALL REMASS( 3, NOOBSF, 3, XYZPI,
     %                LTDESU(LPMASS,NOOBSF), RHO )
C
C        MASSE = MASSE * POIDS * DELTA
         MASSEF(NC  ) = RHO * DELTA
         MASSEF(NC+1) = MASSEF(NC)
         NC = NC + 2
C
 10   CONTINUE
C
C     CODE MATRICE ELEMENTAIRE DE MASSE DIAGONALE
      NCODSM = 0
      RETURN
      END
