      SUBROUTINE ER2LAG( D2PI,   PENALI, NBSOMT, NBCOTE,
     &                   NOOBPS, NUMIPO, NUMAPO, LTDEPO,
     &                   NOOBLA, NUMILI, NUMALI, LTDELI,
     &                   NOOBSF, NUMISU, NUMASU, LTDESU,
     &                   NBPOLA, NBPOLY, NPI,    POLY,
     &                   IP,     F1,     F2,     POIDEL, DP,
     &                   G1,     G2,     G3,
     &                   ELAS,   AE )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DE LA MATRICE DE RAIDEUR DES EF 2D SAUF TRIA 2P1D
C -----    LAGRANGE ISOPARAMETRIQUES
C
C ENTREES:
C --------
C D2PI   : 2 FOIS PI
C PENALI : 1/EPSILON DE LA PENALISATION DU DEPLACEMENT IMPOSE
C NBSOMT : NOMBRE DE SOMMETS DE L ELEMENT FINI
C NBCOTE : NOMBRE DES COTES  DE L ELEMENT FINI
C
C NOOBPS : NUMERO DE POINT DES SOMMETS
C NUMIPO : NUMERO MINIMAL  DES OBJETS POINTS
C NUMAPO : NUMERO MAXIMAL  DES OBJETS POINTS
C LTDEPO : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES D'ELASTICITE
C          DES POINTS DE L'OBJET
C
C NOOBLA : NOUMERO DES OBJETS LIGNES DES ARETES DE L'ELEMENT FINI
C NUMILI : NUMERO MINIMAL DES LIGNES DE L'OBJET
C NUMALI : NUMERO MAXIMAL DES LIGNES DE L'OBJET
C LTDELI : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES D'ELASTICITE
C          DES LIGNES DE L'OBJET
C
C NOOBSF : NUMERO DE L'OBJET SURFACE DE CET ELEMENT FINI
C NUMISU : NUMERO MINIMAL DES SURFACES DE L'OBJET
C NUMASU : NUMERO MAXIMAL DES SURFACES DE L'OBJET
C LTDESU : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES D'ELASTICITE
C
C NBPOLA : NOMBRE DE POLYNOMES DE BASE SUR UN COTE DE L'ELEMENT FINI
C NPIA   : NOMBRE DE POINTS D INTEGRATION SUR UN COTE
C POIDSA : POIDS DES POINTS D INTEGRATION SUR UN COTE
C POLYA  : VALEUR DES POLYNOMES DE BASE AUX POINTS D'INTEGRATION COTE
C DPOLYA : VALEUR DU GRADIENT DE CES MEMES POLYNOMES AUX POINTS ...
C
C NBPOLY : NOMBRE DE POLYNOMES DE L'ELEMENT FINI COMPLET
C NPI    : NOMBRE DE POINTS D INTEGRATION NUMERIQUE
C POIDS  : LES NPI POIDS DE LA FORMULE D INTEGRATION
C POLY   : VALEUR DES POLYNOMES DE BASE AUX POINTS D'INTEGRATION
C          POLY(I,  L)= P(I) (XL)
C DPOLY  : IDEM POUR LES DERIVEES DE CES POLYNOMES
C          DPOLY(I,J,L)=DP(J)/DX(I) (XL)
C
C IP     : IP(J) = POSITION DI J-EME D.L. COMPOSANTE PAR COMPOSANTE
C          DANS LA NUMEROTATION PAR NOEUDS
C F1     : COORDONNEES XX DES NPI POINTS D INTEGRATION DE L ELEMENT
C F2     : COORDONNEES YY DES NPI POINTS D INTEGRATION DE L ELEMENT
C POIDEL : DELTA * POIDS(NPI) DES NPI POINTS D INTEGRATION
C DP     : GRADIENT DES POLYNOMES DE BASE SUR L ELEMENT COURANT
C G1,G2,G3 : TABLEAUX AUXILIAIRES
C
C SORTIES:
C --------
C ELAS   : TENSEUR SYMETRIQUE DE L ELASTICITE
C AE     : LA MATRICE DE RAIDEUR SYMETRIQUE PLEINE
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET        ANALYSE NUMERIQUE UPMC   NOVEMBRE 1990
C MODIF  : M. A. FERNANDEZ VARELA ANALYSE NUMERIQUE UPMC    JANVIER 1998
C MODIF  : ALAIN PERRONNET        ANALYSE NUMERIQUE UPMC       MARS 1999
C23456---------------------------------------------------------------012
      include"./incl/donela.inc"
      include"./incl/a___fixation.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
C
      DOUBLE PRECISION  PENALI
      DOUBLE PRECISION  D2PI
      DOUBLE PRECISION  POLY(NBPOLY,NPI),
     %                  F1(NPI),F2(NPI),
     %                  POIDEL(NPI),
     %                  DP(2,NBPOLY,NPI),
     %                  G1(NBPOLY*(NBPOLY+1)/2),
     %                  G2(NBPOLY,2),
     %                  G3(NBPOLY,NBPOLY),
     %                  ELAS(6),
     %                  COEFDE(2,9),
     %                  AE(*)
C
      INTEGER           NOOBPS(NBSOMT), NOOBLA(NBCOTE), NOOBSF
      INTEGER           LTDEPO(1:MXDOEL,NUMIPO:NUMAPO)
      INTEGER           LTDELI(1:MXDOEL,NUMILI:NUMALI)
      INTEGER           LTDESU(1:MXDOEL,NUMISU:NUMASU)
C
      DOUBLE PRECISION  AUX, A11(3), A12(2,2)
      INTEGER           IP(*), NOPOAR(3)
C
C     INITIALISATION DE AE
C     --------------------
      CALL AZEROD( NBPOLY*(2*NBPOLY+1) , AE )
C
C     CONTRIBUTION DE LA SURFACE A LA MATRICE DE RAIDEUR
C     ==================================================
      DO 10 L=1,NPI
C
C        RECHERCHE DU TENSEUR SYMETRIQUE DE L'ELASTICITE AU POINT
C        D'INTEGRATION L
         CALL REELAS( 3,NOOBSF,2,F1(L),F2(L),0D0,
     %                LTDESU(LPYOUN,NOOBSF),ELAS)
C
C
C        CONSTRUCTION DES MATRICES   ( A11   A12 )
C        -------------------------   (       A22 )
         AUX = POIDEL(L)
C
C        LE BLOC 11
         A11(1)=AUX*ELAS(1)
         A11(2)=AUX*ELAS(4)
         A11(3)=AUX*ELAS(6)
C        CALCUL DE LA MATRICE AE11
C        CALCUL DU PRODUIT  G1(NBPOLY,NBPOLY) = DP*(NBPOLY,2) * A11(2,2) * DP(2,
         CALL TABA8D(NBPOLY,2,DP(1,1,L),A11,G1,G2)
C        TRANSFERT DANS LA MATRICE AE11
         CALL PLONAD(1,NBPOLY,NBPOLY,1,1,IP,G1,G1,AE)
C
C        LE BLOC 12
         A12(1,1)=AUX*ELAS(4)
         A12(1,2)=AUX*ELAS(2)
         A12(2,1)=AUX*ELAS(6)
         A12(2,2)=AUX*ELAS(5)
C        CALCUL DE LA MATRICE AE12
C        CALCUL DU PRODUIT   G2(NBPOLY,2) = DP**T(2,NBPOLY) * A12(2,2)
         CALL TAB0D(NBPOLY,2,2,DP(1,1,L),A12,G2)
C        CALCUL DU PRODUIT   G3(NBPOLY,NBPOLY) = G2(NBPOLY,2) * DP(2,NBPOLY)
         CALL AB0D(NBPOLY,2,NBPOLY,G2,DP(1,1,L),G3)
C        ON PLONGE G3 DANS AE12
         CALL PLONAD(-1,NBPOLY,NBPOLY,1,2,IP,G3,G3,AE)
C
C        LE BLOC 22
         A11(1)=AUX*ELAS(6)
         A11(2)=AUX*ELAS(5)
         A11(3)=AUX*ELAS(3)
C        CALCUL DE LA MATRICE AE22
C        CALCUL DU PRODUIT  G1(NBPOLY,NBPOLY) = DP**T(NBPOLY,2) * A22(2,2) * DP(
         CALL TABA8D(NBPOLY,2,DP(1,1,L),A11,G1,G2)
C        TRANSFERT DANS LA MATRICE AE22
         CALL PLONAD(1,NBPOLY,NBPOLY,2,2,IP,G1,G1,AE)
C
 10   CONTINUE
C
C     CONTRIBUTION DU COEFFICIENT DU DEPLACEMENT SUR LA SURFACE
C     SOUS LA FORME DE COEFFICIENTS DIAGONAUX DU TYPE DE LA MASSE
C     ===========================================================
C     LA SURFACE SUPPORTE T ELLE UN COEFFICIENT DU DEPLACEMENT?
C     ADRESSE MCN DU COEFFICIENT DU DEPLACEMENT
      MN = LTDESU(LPCOED,NOOBSF)
      IF( MN .GT. 0 ) THEN
         CALL EN2LAG( D2PI,   0,
     &                NOOBSF, NUMISU, NUMASU, LTDESU,
     &                NBPOLY, NPI,    POLY,
     &                F1, F2, POIDEL, COEFDE,
     &                AE )
      ENDIF
C
C     CONTRIBUTION DE LA PENALISATION DES DEPLACEMENTS IMPOSES
C     ========================================================
      IF( PENALI .EQ. 0D0 ) RETURN
C
C     CONTRIBUTION DES ARETES
C     -----------------------
      DO 400 K=1,NBCOTE
C
         IF( NOOBLA(K) .GT. 0 ) THEN
C
            MN = LTDELI( LPFIXA, NOOBLA(K) )
            IF( MN .GT. 0 ) THEN
C
C              LE NOMBRE DE COMPOSANTES FIXEES DU DEPLACEMENT SUR LE COTE K
               NBCOFI = MCN( MN + WBCOFI )
C
C              LE NUMERO DES POINTS DU COTE K
               NOPOAR(1) = K
               IF( K .NE. NBCOTE ) THEN
                  NOPOAR(2) = K+1
               ELSE
                  NOPOAR(2) = 1
               ENDIF
C              LE NUMERO DU POINT MILIEU
               NOPOAR(3) = K + NBCOTE
C
C              CALCUL DES FIXATIONS PENALISEES SUR LE COTE K
               DO 360 I=1,NBPOLA
C
C                 LE NUMERO DU NOEUD I DE L'ARETE K
                  II = NOPOAR(I)
C
                  DO 350 J=1,NBCOFI
C
C                    LE NUMERO DE LA COMPOSANTE FIXEE
                     L = MCN( MN + WUCOFI - 1 + J )
C
C                    LE NUMERO DU DL FIXE
                     L = II * 2 - 2 + L
C
C                    LE NUMERO DU COEFFICIENT DIAGONAL L
                     M = L * ( L + 1 ) / 2
                     AE(M) = AE(M) + PENALI
C
 350              CONTINUE
 360           CONTINUE
            ENDIF
         ENDIF
C
 400  CONTINUE
C
C     CONTRIBUTION DES SOMMETS A LA PENALISATION DES DEPLACEMENTS IMPOSES
C     -------------------------------------------------------------------
      DO 450 K=1,NBSOMT
C
C        NUMERO DE POINT DU SOMMET K
         N = NOOBPS(K)
         IF( N .GT. 0 ) THEN
C
C           LE SOMMET K EST UN POINT. EST IL SUPPORT D'UNE FIXATION?
            MN = LTDEPO( LPFIXA, N )
            IF( MN .GT. 0 ) THEN
C
C              OUI: LE NOMBRE DE COMPOSANTES FIXEES
               NBCOFI = MCN( MN + WBCOFI )
C
               DO 440 J=1,NBCOFI
C
C                 LE NUMERO DE LA COMPOSANTE FIXEE
                  L = MCN( MN + WUCOFI - 1 + J )
C
C                 LES SOMMETS SONT NUMEROTES AVANT LES MILIEUX DES COTES
C                 LE NUMERO DU DL FIXE
                  L = K * 2 - 2 + L
C
C                 LE NUMERO DU COEFFICIENT DIAGONAL L
                  M = L * ( L + 1 ) / 2
                  AE(M) = AE(M) + PENALI
C
 440           CONTINUE
C
            ENDIF
         ENDIF
 450  CONTINUE
C
      RETURN
      END
