      SUBROUTINE MIMXDE( NDIM,   NBPOIN, XYZPOI,
     %                   AMPLID, NTDL,   NBVECT, NCAS, DEPLAC,
     %                   COIN )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    METTRE LE MINIMUM ET MAXIMUM DES COORDONNEES DES POINTS
C -----    DANS LE TABLEAU COIN EN TENANT COMPTE DES DEPLACEMENTS AMPLIFIES
C
C
C ENTREES :
C ---------
C NDIM   : DIMENSION DE L'ESPACE DE L'OBJET (2 OU 3)
C NBPOIN : NOMBRE DE POINTS DU MAILLAGE DE L'OBJET
C XYZPOI : LES 3 COORDONNEES DES NBPOIN POINTS=NOEUDS
C NTDL   : NOMBRE TOTAL DE COMPOSANTES DES DEPLACEMENTS (=NDIM*NBPOIN)
C NBVECT : NOMBRE TOTAL DE VECTEURS DEPLACEMENTS
C NCAS   : NUMERO DU VECTEUR A TRAITER (PARMI 1 A NBVECT)
C AMPLID : FACTEUR D'AMPLIFICATION DES DEPLACEMENTS
C DEPLAC : LES COMPOSANTES DES DEPLACEMENTS
C
C SORTIE :
C --------
C COIN   : COIN(.,1) MIN DES COORDONNEES DES POINTS
C          COIN(.,2) MAX DES COORDONNEES DES POINTS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE  UPMC PARIS       MARS 1997
C.......................................................................
      REAL              COIN(6,2), XYZPOI(3,NBPOIN)
      DOUBLE PRECISION  DEPLAC(NTDL,NBVECT)
      INTRINSIC         REAL
C
C     UNE MARGE DE 1%
      AMPLI2 = AMPLID * 1.01
C
C     L'INITIALISATION
      S = REAL( XYZPOI(1,1) + AMPLI2 * DEPLAC(1,NCAS) )
      COIN(1,1) = MIN( XYZPOI(1,1), S )
      COIN(1,2) = MAX( XYZPOI(1,1), S )
C
      S = REAL( XYZPOI(2,1) + AMPLI2 * DEPLAC(2,NCAS) )
      COIN(2,1) = MIN( XYZPOI(2,1), S )
      COIN(2,2) = MAX( XYZPOI(2,1), S )
C
      IF( NDIM .EQ. 3 ) THEN
         S = REAL( XYZPOI(3,1) + AMPLI2 * DEPLAC(3,NCAS) )
         COIN(3,1) = MIN( XYZPOI(3,1), S )
         COIN(3,2) = MAX( XYZPOI(3,1), S )
      ELSE
         COIN(3,1) = 0
         COIN(3,2) = 0
      ENDIF
C
C     LE MIN ET MAX DES POINTS + AMPLI2 * DEPLACEMENT NCAS
      ND = 0
      DO 20 J=2,NBPOIN
         ND = ND + NDIM
         DO 10 I=1,NDIM
C           LE DEPLACEMENT AMPLIFIE
            S = REAL( XYZPOI(I,J) + AMPLI2 * DEPLAC(ND+I,NCAS) )
            COIN(I,1) = MIN( COIN(I,1), XYZPOI(I,J), S )
            COIN(I,2) = MAX( COIN(I,2), XYZPOI(I,J), S )
 10      CONTINUE
 20   CONTINUE
C
      RETURN
      END
