      SUBROUTINE TRCOEFSE( KNOMOB, NTLXOB,
     %                     NBCOOR, NBPOI,  XYZPOI, NOFORE,
     %                     MODECO, NCAS, NOPT, CONTMX, CMFLEC, CMPCON )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACE DES CONTRAINTES PRINCIPALES DES EF SECTIONNES PAR UN
C -----    PLAN A X OU Y OU Z = CONSTANTE  OU UN PLAN QUELCONQUE
C          SUR UN OBJET 3D
C
C ENTREES:
C --------
C KNOMOB : NOM DE L'OBJET
C NTLXOB : NO LEXIQUE DE L'OBJET
C NBTYEL : LE NOMBRE DE TYPES D'ELEMENTS FINIS DANS CETTE TOPOLOGIE
C MNTOPO : ADRESSE MCN DU TABLEAU TOPOLOGIE
C MNELEM : ADRESSE MCN DES TABLEAUX ELEMENTS FINIS DE CETTE TOPOLOGIE
C NDPGST : CODE TRAITEMENT DES SOMMETS POINTS NOEUDS DU MAILLAGE
C          0 : NOEUDS=POINTS=SOMMETS
C          1 : NOEUDS=POINTS#SOMMETS
C          2 : NOEUDS#POINTS=SOMMETS
C          3 : NOEUDS#POINTS#SOMMETS
C NBCOOR : NOMBRE DE COORDONNEES D'UN POINT
C NBPOI  : NOMBRE DE POINTS
C XYZPOI : NBCOOR COORDONNEES DES NBPOI POINTS
C NOFORE : 0 SI PAS DE FONCTION UTILISATEUR 'REGION', >0 SINON
C MODECO : MODE DE TRACE DES VECTEURS DU TMS D'ADRESSE MNDEPL
C          =1 CE SONT DEPLACEMENTS
C          =2 CE SONT DES MODES PROPRES
C NCAS   : NUMERO DU CAS A TRAITER
C NOPT   : NUMERO DE L'OPTION DE TRAITEMENT
C CONTMX : MAXIMUM EN VALEUR ABSOLUE DES CONTRAINTES
C CMFLEC : NOMBRE DE CM DU DE LA FLECHE MAXIMALE
C CMPCON : NOMBRE DE CM POUR L'UNITE DE CONTRAINTE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Laboratoire JL LIONS UPMC Paris Decembre 2006
C23456...............................................................012
      PARAMETER   (MXTYEL=7)
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___vecteur.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___face.inc"
      include"./incl/a___aretefr.inc"
      include"./incl/a___contrainte.inc"
      include"./incl/ponoel.inc"
      include"./incl/donele.inc"
      include"./incl/trvari.inc"
      include"./incl/mecoit.inc"
      include"./incl/xyzext.inc"
      include"./incl/ctemps.inc"
C
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      include"./incl/pp.inc"
      COMMON             MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (RMCN(1),MCN(1))
      CHARACTER*(*)     KNOMOB
      CHARACTER*90      KNOM
      REAL              XYZPOI(NBCOOR,NBPOI)
C
C     VARIABLES PERSO
      REAL              NORM
      REAL              VNORMAL(3)
      REAL              PTPLAN(3), APTPLAN(3)
      REAL              XYZ0(3), XYZ(3)
      REAL              COPLAN, COPLANMIN, COPLANMAX, PROSCR
      REAL              XYZPLAN(3,4)
      INTEGER           NOPTEF(64)
      CHARACTER*4       NOMELE(2)
C
      MOREE2 = MOTVAR(6)
      MNELEM = 0
      MNXYZF = 0
      MNBARY = 0
      MNBAFR = 0
      MNNOBA = 0
      MNNBFR = 0
      MNAREF = 0
      NBCOUL = NDCOUL - N1COUL + 1
C
C     MISE A JOUR DE L'ECHELLE DU TRACE DES CONTRAINTES
      IF( NOPT .EQ. 1 ) THEN
         CMPCON = CMFLEC / CONTMX
      ELSE IF( NOPT .EQ. 2 ) THEN
         CMPCON = 1. / CONTMX
      ENDIF
C
C     RECHERCHE DES TABLEAUX SOMMETS NOEUDS POINTS ASSOCIES A L'OBJET
C     ===============================================================
C     ADRESSAGE DES ADRESSES DES TABLEAUX ELEMENTS DE CET OBJET
      CALL TNMCDC( 'ENTIER', 2*MXTYEL, MNELEM )
      MNTELE = MNELEM + MXTYEL
      CALL NDPGEL( NTLXOB, NTTOPO, MNTOPO,
     %             NTPOGE, MNPOGE, NTNOEU, MNNOEU,
     %             NBTYEL, MCN(MNTELE), MCN(MNELEM), IERR )
C     NTTOPO : NUMERO      DU TMS 'TOPOLOGIE' DE L'OBJET
C     MNTOPO : ADRESSE MCN DU TMS 'TOPOLOGIE' DE L'OBJET
C     NTPOGE : NUMERO      DU TMS 'XYZPOINT'  DE L'OBJET
C     MNPOGE : ADRESSE MCN DU TMS 'XYZPOINT'  DE L'OBJET
C     NTNOEU : NUMERO      DU TMS 'XYZNOEUD'  DE L'OBJET
C     MNNOEU : ADRESSE MCN DU TMS 'XYZNOEUD'  DE L'OBJET
C     NBTYEL : NOMBRE DE TYPES D'ELEMENTS FINIS DU MAILLAGE
C     NTELEM : NUMERO      DU TMS DES NBTYEL TYPES D'ELEMENTS FINIS
C     MNELEM : ADRESSE MCN DU TMS DES NBTYEL TYPES D'ELEMENTS FINIS
      IF( IERR .NE. 0 ) GOTO 9000
C
C     NDPGST : CODE TRAITEMENT DES XYZ DES SOMMETS POINTS NOEUDS DU MAILLAGE
C              0 : NOEUDS=POINTS=SOMMETS
C              1 : NOEUDS=POINTS#SOMMETS
C              2 : NOEUDS#POINTS=SOMMETS
C              3 : NOEUDS#POINTS#SOMMETS
      NDPGST = MCN( MNTOPO + WDPGST )
C
C     CONSTRUCTION DES FACES FRONTALIERES ET DE LEURS BARYCENTRES
C     ===========================================================
C     CREATION OU REDECOUVERTE DU TMS OBJET>>>FACE
      CALL HACHOB( KNOMOB, 4, NTFAOB, MNFAOB, IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     CREATION DU HACHAGE DES ARETES DES FACES FRONTALIERES DE L'OBJET
      CALL HACHAF( KNOMOB, 0, NTFAOB, MNFAOB,
     %             NTAFOB, MNAFOB, I )
C
C     LE NOMBRE D'ENTIERS PAR ARETE FRONTALIERE
      MOARFR = MCN( MNAFOB + WOARFR )
C     LA MAJORATION DU NOMBRE DES ARETES FRONTALIERES
      MXARFR = MCN( MNAFOB + WXARFR )
C     LE NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
      L1ARFR = MCN( MNAFOB + W1ARFR )
C     LE NOMBRE D'ARETES FRONTALIERES DANS LE CHAINAGE
      NBARFR = MCN( MNAFOB + WBARFR )
C
C     RESERVATION DES TABLEAUX NO XYZ POUR LE TRI
      CALL TNMCDC( 'ENTIER',  NBARFR, MNNBFR )
      CALL TNMCDC( 'REEL'  ,3*NBARFR, MNBAFR )
C
C     CALCULER LE BARYCENTRE DE CHAQUE FACE FRONTALIERE
C              LE NUMERO DE LA FACE POUR LE TRI PAR TAS ULTERIEUR
      CALL TRIARFR( MOARFR, L1ARFR, MCN(MNAFOB+WAREFR), XYZPOI,
     %              NBARFR, MCN(MNNBFR), RMCN(MNBAFR) )
C
C     TABLEAU DES XYZ DIRECTION + LONGUEUR DES FLECHES CONTRAINTES
      MXFLEC = 15 * NBELFIN( NBTYEL, MNELEM ) + 1024
      CALL TNMCDC( 'REEL', MXFLEC*15, MNXYZF )
      MXAREF = 10 * NBARFR + 1024
      CALL TNMCDC( 'ENTIER', MXAREF*2, MNAREF )
C
C     LECTURE DES DONNEES DE DEFINITION DU PLAN DE SECTION
C     ----------------------------------------------------
 100  CALL LIMTCL( 'sectvopl', NOAXE )
      IF( NOAXE .LE. 0 ) GOTO 9000
      IF( NOAXE .EQ. 4 ) THEN
C
C        COUPE SELON UN PLAN DE VECTEUR NORMAL A DEFINIR
C        ENTREE X DU VECTEUR NORMAL
         CALL INVITE( 135 )
         NCVALS = 0
         CALL LIRRSP( NCVALS, VNORMAL(1) )
         IF (NCVALS .LE. 0) GOTO 100
C
C        ENTREE Y DU VECTEUR NORMAL
         CALL INVITE( 136 )
         NCVALS = 0
         CALL LIRRSP( NCVALS, VNORMAL(2) )
         IF (NCVALS .LE. 0) GOTO 100
C
C        ENTREE Z DU VECTEUR NORMAL
         CALL INVITE( 137 )
         NCVALS = 0
         CALL LIRRSP( NCVALS, VNORMAL(3) )
         IF (NCVALS .LE. 0) GOTO 100
C
C        NORMALISATION DU VECTEUR VNORMAL
         NORM = SQRT( VNORMAL(1)**2 + VNORMAL(2)**2 + VNORMAL(3)**2 )
C
         IF (NORM .LT. 1E-8) THEN
            NBLGRC(NRERR) = 2
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'TRCOEFSE: VECTEUR NORMAL AU PLAN NUL'
               KERR(2) = '          VEUILLEZ RECOMMENCER'
            ELSE
               KERR(1) = 'TRCOEFSE: NULL NORMAL VECTOR'
               KERR(2) = '          GIVE IT AGAIN'
            ENDIF
            CALL LEREUR
            GOTO 100
         ENDIF
C
         DO 110 I=1,3
            VNORMAL(I) = VNORMAL(I) / NORM
 110     CONTINUE
C
C        ICI VNORMAL EST LE VECTEUR NORMAL UNITE DU PLAN DE SECTION
      ENDIF
C
C     -----------------------------------------------------------
C     OPTIONS DE LA VISEE POUR VOIR L'OBJET ET LE PLAN DE SECTION
C     -----------------------------------------------------------
 150  CALL VISE3D( NMTCL )
      IF( NMTCL .LT. 0 ) GOTO 100
C
C     LES COORDONNEES EXTREMES SONT CELLES DE CET OBJET
      CALL MIMXPT( NBCOOR, NBPOI, XYZPOI, COOEXT )
C     CADRE AVEC 20% EN PLUS
      DO 160 I=1,NBCOOR
         EC = ( COOEXT(I,2) - COOEXT(I,1) ) * 1.2 / 2
         CM = ( COOEXT(I,1) + COOEXT(I,2) ) / 2
         COOEXT(I,1) = CM - EC
         COOEXT(I,2) = CM + EC
 160  CONTINUE
C
C     DEFINITION DE LA VISEE AXONOMETRIQUE POUR DEFINIR LE PLAN DE SECTION
C     --------------------------------------------------------------------
C     POINT VU LE CENTRE DE L'HEXAEDRE ENGLOBANT
      AXOPTV(1) = ( COOEXT(1,1) + COOEXT(1,2) ) * 0.5
      AXOPTV(2) = ( COOEXT(2,1) + COOEXT(2,2) ) * 0.5
      AXOPTV(3) = ( COOEXT(3,1) + COOEXT(3,2) ) * 0.5
C     POSITION DE L'OEIL
      AXOEIL(1) = AXOPTV(1) + 4.0 * ( COOEXT(1,2) - COOEXT(1,1) )
      AXOEIL(2) = AXOPTV(2) + 3.0 * ( COOEXT(2,2) - COOEXT(2,1) )
      AXOEIL(3) = AXOPTV(3) + 3.5 * ( COOEXT(3,2) - COOEXT(3,1) )
C     LARGEUR/2 et HAUTEUR/2 de la FENETRE
      AXOLAR = (COOEXT(1,2)-COOEXT(1,1) + COOEXT(2,2)-COOEXT(2,1))*0.45
      AXOHAU = ( COOEXT(3,2) - COOEXT(3,1) ) * 0.85
C     PAS DE PLAN ARRIERE ET AVANT
      AXOARR = 0
      AXOAVA = 0
      CALL AXONOMETRIE( AXOPTV, AXOEIL, AXOLAR, AXOHAU, AXOARR, AXOAVA )
C
C     LE BARYCENTRE DE L'HEXAEDRE ENGLOBANT SERT DE POSITION
C     DE DEPART DU PLAN DE SECTION DES EF
      PTPLAN(1) = AXOPTV(1)
      PTPLAN(2) = AXOPTV(2)
      PTPLAN(3) = AXOPTV(3)
C     LES COORDONNEES AXONOMETRIQUES DU POINT DU PLAN
      CALL XYZAXO( PTPLAN, APTPLAN )
C
C     COORDONNEE MINIMALE ET MAXIMALE DU PLAN DE SECTION
      IF( NOAXE .LE. 3 ) THEN
C        COORDONNEE SELON L'AXE NOAXE
         COPLANMIN = COOEXT(NOAXE,1)
         COPLANMAX = COOEXT(NOAXE,2)
      ELSE
C        LA COORDONNEE SELON LA DIRECTION NORMALE
         COPLAN0   = PROSCR( PTPLAN,      VNORMAL, 3 )
         COPLANMIN = PROSCR( COOEXT(1,1), VNORMAL, 3 )
         COPLANMAX = PROSCR( COOEXT(1,2), VNORMAL, 3 )
      ENDIF
      IF( COPLANMIN .GT. COPLANMAX ) THEN
         C         = COPLANMIN
         COPLANMIN = COPLANMAX
         COPLANMAX = C
      ENDIF
C
C     ECART MAXIMAL MIN-MAX = DIAGONALE DE L'HEXAEDRE
      ECMX = SQRT( (COOEXT(1,2)-COOEXT(1,1))**2 +
     %             (COOEXT(2,2)-COOEXT(2,1))**2 +
     %             (COOEXT(3,2)-COOEXT(3,1))**2 )
C
C     INITIALISATION DU TRACE INTERACTIF SELON LE DEPLACEMENT DE LA SOURIS
      CALL ORBITE0( NOTYEV )
      IF( NOTYEV .EQ. 0 ) GOTO 9000
      NOPX0 = LAPXFE / 2
      NOPY0 = LHPXFE / 2
C     LE POINTEUR DE LA SOURIS EST CENTRE DANS LA FENETRE
      CALL DEPLSOURIS( NOPX0, NOPY0 )
C
C     MISE A JOUR DU DEPLACEMENT DE LA SOURIS POUR POSITIONNER LE PLAN
C     ----------------------------------------------------------------
 200  CALL ORBITE2( NOTYEV )
      IF( NOTYEV .EQ.  0 ) GOTO 150
      IF( NOTYEV .EQ. -3 ) THEN
C
C        DEPLACEMENT EN COORDONNEE AXONOMETRIQUE
C        PAR RAPPORT A CELUI EN PIXELS
         APTPLAN(1) = APTPLAN(1) + ECMX*2 * FLOAT( NOPX1 - NOPX0 )
     %                           / FLOAT(LAPXFE)
         APTPLAN(2) = APTPLAN(2) + ECMX*2 * FLOAT( NOPY0 - NOPY1 )
     %                           / FLOAT(LHPXFE)
C        PASSAGE AUX COORDONNEES CARTESIENNES
         CALL AXOXYZ( APTPLAN, PTPLAN )
C
C        SELON NOAXE CALCUL DE COPLAN SELON LA NORMALE AU PLAN
C        ET DES 4 SOMMETS DU CARRE DE VISUALISATION DU PLAN
         CALL SCTPLN( NOAXE,  VNORMAL,
     %                PTPLAN, COPLAN0, COPLANMIN, COPLANMAX,
     %                COPLAN, XYZPLAN )
C
C        MISE A JOUR DU PIXEL INITIAL DE LA SOURIS
         NOPX0 = NOPX1
         NOPY0 = NOPY1
      ENDIF
C
C     CONSTRUCTION DES VECTEURS CONTRAINTES
C     BOUCLE SUR LES DIFFERENTS TYPES D'ELEMENTS FINIS DU MAILLAGE
C     ============================================================
      NBFLEC = 0
      NBAREF = 0
      DO 250 I = 0, NBTYEL-1
C
C        L'ADRESSE MCN DU DEBUT DU TABLEAU NPEF DE CE TYPE D'EF
         MNELE = MCN( MNELEM + I )
C
C        LE NUMERO DU TYPE DES ELEMENTS FINIS
         NUTYEL = MCN( MNELE + WUTYEL )
         IF( NUTYEL .EQ. 30 ) GOTO 250
C        PAS DE TRACE DES 6CUBES, SEULEMENT DES 3Q1C EXTRAITS
C
C        LE NOMBRE DE TELS ELEMENTS FINIS
         NBELEM = MCN(MNELE + WBELEM )
C
C        LES CARACTERISTIQUES DE L'ELEMENT FINI
         CALL ELNUNM( NUTYEL, NOMELE )
         CALL ELTYCA( NUTYEL )
C
C        L'ADRESSE MCN DU TABLEAU 'NPEF' POUR CE TYPE D'EF
         MNPGEL = MNELE + WUNDEL
         IF( NDPGST .GE. 2 ) THEN
            MNPGEL = MNPGEL + MCN(MNELE+WBELEM) * MCN(MNELE+WBNDEL)
         ENDIF
C
C        TRACE DES CONTRAINTES DANS LES EF SECTIONNES
C        ------------------------------------------
         KNOM = 'CONTRAINTE"' // NOMELE(2)
C        OUVERTURE DU TABLEAU
         CALL LXTSOU( NTLXOB, KNOM, NTCONT, MNCONT )
         IF( NTCONT .LE. 0 ) THEN
            NBLGRC(NRERR) = 1
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,*) 'OBJET SANS CONTRAINTES CALCULEES'
            ELSE
               WRITE(IMPRIM,*) 'OBJECT WITHOUT COMPUTED STRESSES'
            ENDIF
            CALL LEREUR
            GOTO 9000
         ENDIF
C
C        LES DIFFERENTS TABLEAUX ET VARIABLES DE 'CONTRAINTE'
C        AFIN DE BENEFICIER DES INDICES FORTRAN EN CLAIR
         NBELFI = MCN(MNCONT+WBELFI)
         NBPIEF = MCN(MNCONT+WBPIEF)
         NBJECA = MCN(MNCONT+WBJECA)
         NDIMES = MCN(MNCONT+WDIMES)
         LDCOPR = MCN(MNCONT+WDCOPR)
         MNDIPR = MNCONT+LDCOPR+NBELFI*NBPIEF*NDIMES*NBJECA*MOREE2
         MNPGEL = MNELE + WUNDEL
         IF( NDPGST .GE. 2 ) THEN
            MNPGEL = MNPGEL + MCN(MNELE+WBELEM) * MCN(MNELE+WBNDEL)
         ENDIF
cc         LDDTEM = MCN(MNCONT+WDDTEM)
cc         MNCOPG = MNCONT + LDDTEM + MOREE2*NBELFI*NDIMES*NBPIEF*NBJECA
C
C        LA BOUCLE SUR LES ELEMENTS FINIS DE CE TYPE NUTYEL
C        ==================================================
         DO 240 NEF = 1, NBELFI
C
C           LES NBPGEF POINTS DE L'ELEMENT FINI NUELEM
            CALL EFPOGE( MNELE, NEF, NBPGEF, NOPTEF )
C
C           NBNSOM SOMMETS PLACES EN PREMIER DANS LES NO DE POINTS
C           RECHERCHE DE LA COORDONNEE NOAXE MIN MAX DES SOMMETS DE L'EF
C           POUR SAVOIR SI LA COORDONNEE DU PLAN EST ENTRE CES VALEURS
            IF( NOAXE .LE. 3 ) THEN
C
C              PLAN A COORDONNEE NOAXE=Constante
               CMIN = XYZPOI( NOAXE, NOPTEF(1) )
               CMAX = CMIN
               DO 220 NF = 1, NFACE
                  DO 215 NS = 1,NBSOFA(NF)
C                    LE NO DU SOMMET NS DE LA FACE NF DANS L'EF NEF
                     NOST = NOPTEF( NOSOFA( NS, NF ) )
                     C = XYZPOI( NOAXE, NOST )
                     IF( C .LT. CMIN ) CMIN = C
                     IF( C .GT. CMAX ) CMAX = C
 215              CONTINUE
 220           CONTINUE
C
            ELSE
C
C              PLAN DEFINI PAR LE VECTEUR NORMAL
C              COORDONNEE SELON LA DIRECTION NORMALE PAR PRODUIT SCALAIRE
               CMIN = PROSCR( XYZPOI(1,NOPTEF(1)), VNORMAL, 3 )
               CMAX = CMIN
               DO 230 NF = 1, NFACE
                  DO 225 NS = 1,NBSOFA(NF)
C                    LE NO DU SOMMET NS DE LA FACE NF DANS L'EF NEF
                     NOST = NOPTEF( NOSOFA( NS, NF ) )
                     C = PROSCR( XYZPOI( 1, NOST ), VNORMAL, 3 )
                     IF( C .LT. CMIN ) CMIN = C
                     IF( C .GT. CMAX ) CMAX = C
 225              CONTINUE
 230           CONTINUE
C
            ENDIF
C
            IF( COPLAN .LT. CMIN .OR. COPLAN .GT. CMAX ) GOTO 240
C
C           L'EF NEF A UNE INTERSECTION AVEC LE PLAN NOAXE
C           LISTAGE DES VECTEURS CONTRAINTES
            CALL VECONT( NOFORE, NEF, NBELFI, NBPIEF, NDIMES, NBJECA,
     %                   MCN(MNCONT+WOPIEF), MCN(MNCONT+LDCOPR),
     %                   MCN(MNDIPR), NCAS,  CMPCON,
     %                   NBFLEC, MXFLEC, RMCN(MNXYZF),
     %                   NBAREF, MXAREF, MCN(MNAREF), NOPTEF, IERR )
            IF( IERR .NE. 0 ) THEN
               IF( LANGAG .EQ. 0 ) THEN
                  IF( IERR .EQ. 1 ) THEN
                  WRITE(IMPRIM,*)'TRCOEFSE: AUGMENTER MXFLEC=',MXFLEC
                  ELSE
                  WRITE(IMPRIM,*)'TRCOEFSE: AUGMENTER MXAREF=',MXAREF
                  ENDIF
               ELSE
                  IF( IERR .EQ. 1 ) THEN
                  WRITE(IMPRIM,*)'TRCOEFSE: AUGMENT MXFLEC=',MXFLEC
                  ELSE
                  WRITE(IMPRIM,*)'TRCOEFSE: AUGMENT MXAREF=',MXAREF
                  ENDIF
               ENDIF
               GOTO 300
            ENDIF
 240      CONTINUE
C
 250  CONTINUE
C
C     RESERVATION DES TABLEAUX NO BARYCENTRES POUR LE TRI
 300  IF( MNBARY .GT. 0 ) CALL TNMCDS( 'REEL',  MXBARY, MNBARY )
      IF( MNNOBA .GT. 0 ) CALL TNMCDS( 'ENTIER',MXBARY, MNNOBA )
      MXBARY = NBARFR + NBFLEC + NBAREF + 4
      CALL TNMCDC( 'ENTIER', MXBARY, MNNOBA )
      CALL TNMCDC( 'REEL',   MXBARY, MNBARY )
C
C     LES ARETES DE LA FRONTIERE SONT EN PREMIER
      MNBA = MNBAFR
      DO 305 NF = 0, NBARFR-1
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( RMCN(MNBA), XYZ )
         RMCN(MNBARY+NF) = XYZ(3)
C        NO>0 DE L'ARETE DANS LAREFR
         MCN(MNNOBA+NF) = MCN(MNNBFR+NF)
         MNBA = MNBA + 3
 305  CONTINUE
C
C     LES FLECHES DES EF SECTIONNES SONT AJOUTEES
      MNBA = MNXYZF
      DO 310 NF = 0, NBFLEC-1
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( RMCN(MNBA), XYZ )
         RMCN(MNBARY+NBARFR+NF) = XYZ(3)
C        NO<POUR SAVOIR QUE C'EST UNE FLECHE
         MCN(MNNOBA+NBARFR+NF) = -(1+NF)
         MNBA = MNBA + 15
 310  CONTINUE
      NBBARY = NBARFR + NBFLEC
C
C     LES ARETES DES EF SECTIONNES SONT AJOUTEES
      MNBA = MNAREF
      DO 315 NF = 0, NBAREF-1
C        LE BARYCENTRE DE L'ARETE
         NS1 = MCN(MNBA)
         NS2 = MCN(MNBA+1)
         XYZ(1) = ( XYZPOI( 1, NS1 ) + XYZPOI( 1, NS2 ) ) * 0.5
         XYZ(2) = ( XYZPOI( 2, NS1 ) + XYZPOI( 2, NS2 ) ) * 0.5
         XYZ(3) = ( XYZPOI( 3, NS1 ) + XYZPOI( 3, NS2 ) ) * 0.5
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         RMCN(MNBARY+NBBARY+NF) = XYZ(3)
C        NO<POUR SAVOIR QUE C'EST UNE FLECHE
         MCN(MNNOBA+NBBARY+NF) = -(1+NF+NBFLEC)
         MNBA = MNBA + 2
 315  CONTINUE
      NBBARY = NBBARY + NBAREF
C
C     LES 4 ARETES DU RECTANGLE DU PLAN DE SECTION
      NF0 = 4
      DO 320 NF = 1, 4
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         XYZ0(1) = (XYZPLAN(1,NF0) + XYZPLAN(1,NF)) * 0.5
         XYZ0(2) = (XYZPLAN(2,NF0) + XYZPLAN(2,NF)) * 0.5
         XYZ0(3) = (XYZPLAN(3,NF0) + XYZPLAN(3,NF)) * 0.5
         CALL XYZAXO( XYZ0, XYZ )
         RMCN(MNBARY+NBBARY+NF-1) = XYZ(3)
C        NO>NBFLEC POUR SAVOIR QUE C'EST UNE ARETE DU RECTANGLE DU PLAN
         MCN(MNNOBA+NBBARY+NF-1) = -(NBFLEC+NBAREF + NF)
         NF0 = NF
 320  CONTINUE
C
C     NOMBRE TOTAL DE TRACES A TRIER
      NBBARY = NBBARY + 4
C
C     LE TRI PAR TAS DE CETTE DISTANCE
C     LA FACE LA PLUS PROCHE EST LA PREMIERE
      CALL TRITRP( NBBARY, RMCN(MNBARY), MCN(MNNOBA) )
C
C     LA MEMOIRE PIXELS EST EFFACEE
      CALL EFFACEMEMPX
C
C     TRACE EFFECTIF DES AXES, ARETES FRONTALIERES ET DES FLECHES
C     ===========================================================
      CALL TRCOEFSE2( NBCOOR, NBPOI,  XYZPOI,
     %                MOARFR, MXARFR, MCN(MNAFOB+WAREFR),
     %                NBBARY, MCN(MNNOBA),
     %                NBFLEC, RMCN(MNXYZF),
     %                NBAREF, MCN(MNAREF), XYZPLAN )
C
      IF( MNBARY .GT. 0 ) CALL TNMCDS( 'REEL',  MXBARY, MNBARY )
      IF( MNNOBA .GT. 0 ) CALL TNMCDS( 'ENTIER',MXBARY, MNNOBA )
C
C     LE TRACE DU TITRE FINAL
C     =======================
      CALL XVCOULEUR( NCNOIR )
      IF( LANGAG .EQ. 0 ) THEN
         KNOM = 'OBJET: ' // KNOMOB
      ELSE
         KNOM = 'OBJECT: ' // KNOMOB
      ENDIF
      I = NUDCNB( KNOM )
      IF( MODECO .EQ. 1 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            KNOM(I+1:I+9) = ' au TEMPS'
         ELSE
            KNOM(I+1:I+9) = ' at TIME'
         ENDIF
         WRITE( KNOM(I+10:I+23), '(G14.6)' ) TEMPS
      ELSE
         IF( LANGAG .EQ. 0 ) THEN
            KNOM(I+1:I+12) = '  FREQUENCE '
         ELSE
            KNOM(I+1:I+12) = '  FREQUENCY '
         ENDIF
         WRITE( KNOM(I+13:I+26), '(G14.6)' ) TEMPS
         KNOM(I+27:I+30) = ' Hz '
      ENDIF
      I = NUDCNB( KNOM )
      CALL XVTEXTE( KNOM(1:I), I, 50, 60 )
C
      IF( LANGAG .EQ. 0 ) THEN
         KNOM = '1CM DE FLECHE= '
         WRITE( KNOM(15:27),'(G13.5)') 1.0/CMPCON
         KNOM(29:51)='UNITES DE CONTRAINTES'
      ELSE
         KNOM = '1CM of ARROW= '
         WRITE( KNOM(15:27),'(G13.5)') 1.0/CMPCON
         KNOM(29:51)='UNITIES of STRESS'
      ENDIF
      I = NUDCNB( KNOM )
      CALL XVTEXTE( KNOM(1:I), I, 50, 75 )
C
C     FIN DU TRACE
      IAVTIT = 1
      IF( LANGAG .EQ. 0 ) THEN
         CALL TRFINS( 'Les CONTRAINTES et DIRECTIONS PRINCIPALES' )
      ELSE
         CALL TRFINS( 'The MAIN STRESSES and DIRECTIONS' )
      ENDIF
C
C     RETOUR POUR UNE NOUVELLE VISEE
      GOTO 200
C
C     SORTIE DU TRACE DES PLANS DE SECTION
C     ====================================
 9000 IF( MNBARY .GT. 0 ) CALL TNMCDS( 'REEL',  MXBARY,   MNBARY )
      IF( MNNOBA .GT. 0 ) CALL TNMCDS( 'ENTIER',MXBARY,   MNNOBA )
      IF( MNBAFR .GT. 0 ) CALL TNMCDS( 'REEL',  NBARFR*3, MNBAFR )
      IF( MNNBFR .GT. 0 ) CALL TNMCDS( 'ENTIER',NBARFR,   MNNBFR )
      IF( MNAREF .GT. 0 ) CALL TNMCDS( 'ENTIER',MXAREF*2, MNAREF )
      IF( MNXYZF .GT. 0 ) CALL TNMCDS( 'REEL',  MXFLEC*15,MNXYZF )
      IF( MNELEM .GT. 0 ) CALL TNMCDS( 'ENTIER',MXTYEL*2, MNELEM )
      END
