      SUBROUTINE TRDE31( MOFACE, MXFACE, LFACES,
     %                   L1FAFR, NBFAFR, NBCOOR, XYZPOI,
     %                   NOVUE,  AMPLID, NTDL,   NCAS,   DEPLAC,
     %                   NOFAFR, DIFAFR, NBFATR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE BARYCENTRE DE CHAQUE FACE FRONTALIERE AVEC
C -----    UNE DEFORMATION AMPLIFIEE DES DEPLACEMENTS
C          CALCULER LA COTE AXONOMETRIQUE DE CES BARYCENTRES
C          ATTENTION: NOEUDS ET POINTS DES EF DOIVENT ETRE CONFONDUS
C
C ENTREES:
C --------
C MOFACE : NOMBRE DE MOTS PAR FACE DU TABLEAU NFACE DES FACES
C MXFACE : NOMBRE DE FACES DU TABLEAU NFACE
C LFACES : TABLEAU NUMERO DES FACES, LIEN, NO DES CUBES
C          LFACES(1,I)= NO DU 1-ER  SOMMET DE LA FACE
C          LFACES(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LFACES(3,I)= NO DU 3-EME SOMMET DE LA FACE
C          LFACES(4,I)= NO DU 4-EME SOMMET DE LA FACE
C                      0 SI TRIANGLE
C          LFACES(5,I)= + ou - CHAINAGE HACHAGE SUR FACE SUIVANTE
C                      >0 FACE INTERNE
C                      <0 FACE FRONTALIERE
C          SI SOMMET 2 < DERNIER SOMMET  => FACE   DIRECTE
C                      <                 => FACE INDIRECTE
C          UNE FACE DIRECTE EST VUE DE L EXTERIEUR AU CUBE
C          SOUS LA FORME DIRECTE
C          LFACES(6,I)= NUMERO DU 1-ER  CUBE CONTENANT CETTE FACE
C                      >0 SI FACE   DIRECTE DANS CE CUBE
C                      <0 SI FACE INDIRECTE DANS CE CUBE
C          SI LA FACE APPARTIENT A 2 CUBES ALORS
C          LFACES(7,I)= NUMERO DU 2-EME CUBE CONTENANT CETTE FACE
C                      >0 SI FACE   DIRECTE DANS CE CUBE
C                      <0 SI FACE INDIRECTE DANS CE CUBE
C          SINON
C          LFACES(7,I)= NUMERO DE LA FACE FRONTALIERE SUIVANTE
C                      0 SI C'EST LA DERNIERE
C L1FAFR : NUMERO DE LA PREMIERE FACE FRONTALIERE
C NBFAFR : NOMBRE DE FACES FRONTALIERES
C NBCOOR : NOMBRE DE COORDONNEES D'UN POINT
C XYZPOI : 3 COORDONNEES DES POINTS=NOEUDS DE L'OBJET
C NOVUE  : NUMERO DE LA VUE A TRACER . NOVUE DEMARRE A ZERO
C AMPLID : FACTEUR D'AMPLIFICATION DES DEPLACEMENTS
C NTDL   : NOMBRE TOTAL DE DEGRES DE LIBERTE
C NCAS   : NUMERO DU CAS A TRACER
C DEPLAC : LES COMPOSANTES DES DEPLACEMENTS
C
C SORTIES:
C --------
C NOFAFR : NOFAFR(I)=NUMERO DE LA FACE FRONTALIERE I DANS LFACES
C DIFAFR : COTE AXONOMETRIQUE DU BARYCENTRE DES FACES FRONTALIERES
C          AVEC UNE DEFORMATION AMPLIFIEE
C
C MODIFIE:
C --------
C NBFATR : EN ENTREE NOMBRE DE FACES A TRACER DEJA CALCULEES
C          EN SORTIE NOMBRE DE FACES A TRACER
C      IDEE: AJOUTER LES NOUVELLES FACES DANS LES TABLEAUX NOFAFR DIFAFR
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS         MARS 1997
C AUTEUR: PERRONNET ALAIN LJLL UPMC Paris & VEULETTES sur MER AVRIL 2009
C ...................................................................012
      include"./incl/trvari.inc"
      INTEGER           LFACES(1:MOFACE,1:MXFACE)
      REAL              XYZPOI(1:NBCOOR,1:*)
      DOUBLE PRECISION  DEPLAC(1:NTDL,1:*)
      INTEGER           NOFAFR(1:NBFAFR)
      REAL              DIFAFR(1:NBFAFR),
     %                  XYZ(3)
      INTRINSIC         REAL
C
C     BOUCLE SUR LES FACES FRONTALIERES
      N = L1FAFR
 1    IF( N .NE. 0 ) THEN
C
C        LA FACE N DE LFACES EST TRAITEE CAR FRONTALIERE
         NBFATR = NBFATR + 1
C        DECALAGE DE MXFACE+1 POUR RECUPERER NOVUE ENSUITE
C        ATTENTION: MXFACE NE CONVIENT PAS DANS LE CALCUL DU RESTE!
         NOFAFR( NBFATR ) = N + (MXFACE+1) * NOVUE
C
C        LE NOMBRE DE SOMMETS DE LA FACE
         IF( LFACES(4,N) .EQ. 0 ) THEN
            NBS = 3
         ELSE
            NBS = 4
         ENDIF
C
C        LES 3 COORDONNEES DU BARYCENTRE DE LA FACE FRONTALIERE DEFORMEE
         XYZ(1) = 0.0
         XYZ(2) = 0.0
         XYZ(3) = 0.0
         DO 20 J=1,NBS
C           LE NUMERO DU SOMMET
            NS = LFACES( J , N )
            ND = 3 * NS - 3
            DO 10 K=1,3
               XYZ(K) = REAL( XYZ(K)+XYZPOI(K,NS)
     %                     + DEPLAC(ND+K,NCAS) * AMPLID )
 10         CONTINUE
 20      CONTINUE
         XYZ(1) = XYZ(1) / NBS
         XYZ(2) = XYZ(2) / NBS
         XYZ(3) = XYZ(3) / NBS
C
C        COTE Z AXONOMETRIQUE DU BARYCENTRE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         DIFAFR( NBFATR ) = XYZ(3)
C
C        PASSAGE A LA FACE FRONTALIERE SUIVANTE
         N = LFACES(7,N)
         GOTO 1
      ENDIF
C
      RETURN
      END
