      SUBROUTINE TRFRP3( PI,   NBVUES, AMPLID, KNOMOB, MNNOEU,
     %                   NCAS, NTDL,   NBVECT, DEPLAC )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACER LES ARETES FRONTALIERES NON DEFORMEES DE L'OBJET
C -----    TRACER LES FACES FRONTALIERES DEFORMEES PAR LES DEPLACEMENTS
C          AMPLIFIES DU COEFFICIENT MUTILIPLICATIF AMPLID
C          ET UN MOUVEMENT SELON LA FREQUENCE PROPRE DE L'OBJET
C
C          ATTENTION: POINTS ET NOEUDS DES EF DOIVENT ETRE IDENTIQUES
C
C ENTREES:
C --------
C PI     : 3.14159...
C NBVUES : NOMBRE DE VUES POUR VOIR LA VIBRATION EN FREQUENCE PROPRE
C AMPLID : FACTEUR D'AMPLIFICATION DES DEPLACEMENTS
C KNOMOB : NOM DE L'OBJET
C MNNOEU : ADRESSE MCN DU TABLEAU XYZNOEUD DES POINTS=NOEUDS DE L'OBJET
C NCAS   : NUMERO DU CAS A TRACER
C NTDL   : NOMBRE TOTAL DE DEGRES DE LIBERTE
C NBVECT : NOMBRE TOTAL DE VECTEURS DEPLACEMENTS
C DEPLAC : LES COMPOSANTES DES DEPLACEMENTS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC Paris & VEULETTES sur MER AVRIL 2009
C23456---------------------------------------------------------------012
      PARAMETER (LIGCON=0, LIGTIR=1 )
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ponoel.inc"
      include"./incl/trvari.inc"
      include"./incl/mecoit.inc"
      include"./incl/a___face.inc"
      include"./incl/a___aretefr.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/ctemps.inc"
      include"./incl/xyzext.inc"
C
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
      CHARACTER*(*)     KNOMOB
      CHARACTER*80      KNOM, KTITRE
      DOUBLE PRECISION  DEPLAC(NTDL,NBVECT), PI
      INTRINSIC         REAL
C
C     TITRE DU TRACE
      IF( LANGAG .EQ. 0 ) THEN
         KTITRE = 'OBJET DEFORME CAS '
      ELSE
         KTITRE = 'DEFORMED OBJECT CASE '
      ENDIF
      I = NUDCNB( KTITRE )
      WRITE( KTITRE(I+1:I+2), '(I2)' ) NCAS
C
      I = NUDCNB( KTITRE )
      IF( LANGAG .EQ. 0 ) THEN
         KTITRE(I+1:I+12) = '  FREQUENCE '
      ELSE
         KTITRE(I+1:I+12) = '  FREQUENCY '
      ENDIF
      I = NUDCNB( KTITRE )
      WRITE( KTITRE(I+1:I+14), '(G14.6)' ) TEMPS
      I = NUDCNB( KTITRE )
      KTITRE(I+1:I+4) = ' Hz '
C
      MNNUFA = 0
      MNBARY = 0
C
C     CREATION OU REDECOUVERTE DU TMS >>>face cf ~/td/d/a___face
      CALL HACHOB( KNOMOB, 4, NTFAOB, MNFAOB, IERR )
C     LE NOMBRE D'ENTIERS STOCKES PAR FACE(>=8)
      MOFACE = MCN( MNFAOB + WOFACE )
C     LE NOMBRE MAXIMAL DE FACES
      MXFACE = MCN( MNFAOB + WXFACE )
C     NUMERO DE LA 1-ERE FACE FRONTALIERE
      L1FAFR = MCN( MNFAOB + W1FAFR )
C     LE NOMBRE DE FACES FRONTALIERES
      NBFAFR = MCN( MNFAOB + WBFAFR )
ccc      print *,'trfrp3: NBFAFR=',nbfafr
C
C     CREATION DU HACHAGE DES ARETES DES FACES FRONTALIERES DE L'OBJET
C     CF ~/td/d/a___aretefr
      CALL HACHAF( KNOMOB, 0, NTFAOB, MNFAOB,
     %             NTAFOB, MNAFOB, I )
C     EN SORTIE  LE TABLEAU LAREFR (ADRESSE MCN MNAFOB) CONTIENT :
C     LE NOMBRE D'ENTIERS PAR ARETE FRONTALIERE
      MOARFR = MCN( MNAFOB + WOARFR )
C     LA MAJORATION DU NOMBRE DES ARETES FRONTALIERES
      MXARFR = MCN( MNAFOB + WXARFR )
C     LE NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
      L1ARFR = MCN( MNAFOB + W1ARFR )
C     LE NOMBRE D'ARETES FRONTALIERES DANS LE CHAINAGE
      NBARFR = MCN( MNAFOB + WBARFR )
      print *,'trfrp3: NBARFR=',nbarfr
C     LAREFR(1,I)= NO DU 1-ER  SOMMET DE L'ARETE FRONTALIERE
C     LAREFR(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C     LAREFR(3,I)= 0 OU NUMERO DE L'ARETE FRONTALIERE SUIVANTE DANS LE HACHAGE
C
C     NOMBRE TOTAL DE FACES ET ARETES A TRACER SIMULTANEMENT
      NBTFA  = NBFAFR + NBARFR
      IF( MNBARY .EQ. 0 ) CALL TNMCDC( 'REEL',   NBTFA, MNBARY )
      IF( MNNUFA .EQ. 0 ) CALL TNMCDC( 'ENTIER', NBTFA, MNNUFA )
C
C     OPTIONS DE LA VISEE POUR VOIR L'OBJET ET SA DEFORMEE
C     ----------------------------------------------------
 10   CALL VISE3D( NMTCL )
      IF( NMTCL .LT. 0 ) GOTO 9000
C
C     INITIALISATION DE L'ORBITE ZOOM DEPLACEMENT
      IF( LORBITE .NE. 0 ) THEN
         CALL ORBITE0( NOTYEV )
         IF( NOTYEV .EQ. 0 ) GOTO 10
         CALL EFFACE
      ENDIF
C
 50   IF( LORBITE .NE. 0 ) THEN
C        ORBITE OU ZOOM OU TRANSLATION ACTIFS
         CALL ORBITE1( NOTYEV )
         IF( NOTYEV .EQ. 0 ) GOTO 10
      ENDIF
C
C     FORMATION DES TABLEAUX NUMERO DES FACES ET DISTANCE AXONOMETRIQUE
C     POUR LES FACES DEFORMEES PAR LES DEPLACEMENTS ET L'AMPLIFICATION
C     POUR LE TRACE DES NBVUES DE LA VIBRATION EN FREQUENCE PROPRE
C     -----------------------------------------------------------------
      DO 60 NOVUE = 0, 2*NBVUES
C
C
C        LA MEMOIRE PIXELS EST EFFACEE POUR EVITER LA SUPERPOSITION DES VUES
         CALL EFFACEMEMPX
C
C        TRACE DES AXES 3D
C        -----------------
         CALL TRAXE3
C
C        FORMATION DES TABLEAUX NUMERO DES FACES ET DISTANCE AXONOMETRIQUE
C        POUR LES ARETES FRONTALIERES NON DEFORMEES DE L'OBJET
C        RECALCUL POUR LE TRI
C        -----------------------------------------------------------------
         CALL TRBARF( MOARFR, MXARFR, L1ARFR, MCN(MNAFOB+WAREFR),
     %                MCN(MNNOEU+WBCOON), RMCN(MNNOEU+WYZNOE),
     %                0, MCN(MNNUFA), RMCN(MNBARY))
C
C        FORMATIONS DES FACES FRONTALIERES DEFORMEES
C        -------------------------------------------
C        FACTEUR DE DEFORMATION POUR LA FREQUENCE PROPRE DE CETTE VUE
         AMPLDE = REAL( AMPLID * COS( ( PI * NOVUE ) / NBVUES ) )
         NBFAT = 0
         CALL TRDE31( MOFACE, MXFACE, MCN(MNFAOB+WFACES),
     %                L1FAFR, NBFAFR,
     %                MCN(MNNOEU+WBCOON), RMCN(MNNOEU+WYZNOE),
     %                NOVUE, AMPLDE, NTDL, NCAS, DEPLAC,
     %                MCN(MNNUFA+NBARFR), RMCN(MNBARY+NBARFR), NBFAT )
C
C        LE TRI PAR TAS DES DISTANCES A L'OEIL
C        LA FACE OU L'ARETE LA PLUS PROCHE DE L'OEIL EST LA PREMIERE
         NBFA = NBARFR + NBFAFR
         CALL TRITRP( NBFA, RMCN(MNBARY), MCN(MNNUFA) )
         CALL TRDE32( MOFACE, MXFACE, MCN(MNFAOB+WFACES), NBFAFR,NBFAFR,
     %                MOARFR, MXARFR, MCN(MNAFOB+WAREFR), NBARFR,
     %                MCN(MNNUFA), RMCN(MNNOEU+WYZNOE),
     %                NCAS, NTDL, NBVECT, DEPLAC, AMPLDE )
C        TRACE FORCE DU TITRE
         IAVTIT = 1
         CALL TRFINS( KTITRE )
C
 60   CONTINUE
C
C     EFFACEMENT DE LA LEGENDE SUR POSTSCRIPT
      IF ( LASOPS .NE. 0 ) THEN
         IF ( LASOPS .EQ. 1 ) THEN
            LASOPS = -11
         ELSE
            IF ( LASOPS .EQ. 2 ) THEN
               LASOPS = -12
            ELSE
               LASOPS = 0
               NBLGRC(NRERR) = 2
               IF( LANGAG .EQ. 0 ) THEN
                  KERR(1) = 'TRFRP3: MAUVAISE VALEUR de LASOPS'
                  KERR(2) = '        ARRET du TRACE POSTSCRIPT'
               ELSE
                  KERR(1) = 'TRFRP3: BAD VALUE of LASOPS'
                  KERR(2) = '        STOP of POSTSCRIPT DRAWING'
               ENDIF
               CALL LEREUR
            ENDIF
         ENDIF
         CALL XVPOSTSCRIPT(LASOPS)
         LASOPS = - LASOPS
         CALL XVPOSTSCRIPT(LASOPS)
      ENDIF
C
C     LE TRACE DU TITRE FINAL
C     -----------------------
C     LE TYPE DES CARACTERES
      IF( LANGAG .EQ. 0 ) THEN
         KNOM = 'OBJET: ' // KNOMOB
      ELSE
         KNOM = 'OBJECT: ' // KNOMOB
      ENDIF
      I = NUDCNB( KNOM )
      CALL XVCOULEUR( NCROUG )
      CALL XVTEXTE( KNOM(1:I), I, 50, 30 )
C
      IF( LANGAG .EQ. 0 ) THEN
         KNOM = 'AMPLIFICATION des DEPLACEMENTS= '
      ELSE
         KNOM = 'AMPLIFICATION of DISPLACEMENTS= '
      ENDIF
      WRITE( KNOM(32:44), '(G13.5)' ) AMPLID
      CALL XVTEXTE( KNOM(1:44), 44, 50, 60 )
C
C     RETOUR AU TRACE NORMAL POUR POSTSCRIPT
      IF ( LASOPS.NE.0 ) THEN
         LASOPS = LASOPS -10
         CALL XVPOSTSCRIPT(LASOPS)
      ENDIF
C
C     RETOUR AUX PARAMETRES INITIAUX
      CALL XVEPAISSEUR( 1 )
      CALL XVTYPETRAIT( LIGCON )
C
C     TRACE FORCE DU TITRE
      IAVTIT = 1
      CALL TRFINS( KTITRE )
C
      IF( LORBITE .NE. 0 ) THEN
C        ORBITE OU ZOOM OU TRANSLATION ACTIFS
         CALL ORBITE1( NOTYEV )
         IF( NOTYEV .EQ. 0 ) GOTO 10
         GOTO 50
      ENDIF
      CALL CLICSO
      GOTO 10
C
C     SORTIE DU TRACE DES ARETES ET FACES FRONTALIERES DEFORMEES
C     SUPPRESSION DES TABLEAUX INUTILES
 9000 IF( MNNUFA .GT. 0 ) CALL TNMCDS( 'ENTIER', NBTFA, MNNUFA )
      IF( MNBARY .GT. 0 ) CALL TNMCDS( 'REEL',   NBTFA, MNBARY )
C
      RETURN
      END
