      SUBROUTINE VECONT( NOFORE, NEF,    NBELFI, NBPIEF, NDIMES, NBCAS,
     %                   COPIEF, CONPRI, DIRPRI, NCAS,   CMPCON,
     %                   NBFLEC, MXFLEC, XYZDFL,
     %                   NBAREF, MXAREF, NOAREF, NOPTEF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    LISTER LES VECTEURS CONTRAINTES PRINCIPALES DE L'EF 3D NEF
C -----
C
C ENTREES :
C ---------
C NOFORE : 0 SI PAS DE FONCTION UTILISATEUR 'REGION', >0 SINON
C NEF    : NO DE L'EF
C NBELFI : NOMBRE D'ELEMENTS FINIS DE CE TYPE
C NBPIEF : NOMBRE DE POINTS DE CALCUL DES CONTRAINTES PAR ELEMENT
C NDIMES : ESPACE DE TRAVAIL 2 OU 3
C NBCAS  : NOMBRE DE CAS TRAITES
C COPIEF : LES NDIMES COORDONNEES DES POINTS DE CALCUL DES CONTRAINTES
C CONPRI : LES NDIMES CONTRAINTES PRINCIPALES
C DIRPRI : LES NDIMES DIRECTIONS PRINCIPALES
C NCAS   : NUMERO DU CAS A TRAITER
C CMPCON : NOMBRE DE CM POUR L'UNITE DE CONTRAINTE
C
C SORTIES :
C ---------
C NBFLEC : NOMBRE DE FLECHES CONTRAINTES
C MXFLEC : NOMBRE MAXIMAL DE FLECHES CONTRAINTES DECLARABLES DANS XYZDFL
C XYZDFL : 1:3 XYZ DU POINT DE DEPART DE LA FLECHE
C          4:6 XYZ DE LA DIRECTION DE LA FLECHE
C          7   DIMENSION EN CM DU TRACE
C              SON SIGNE DETERMINE LE SENS DU TRIANGLE DE LA FLECHE
C NBAREF : NOMBRE D'ARETES DES EF SECTIONNES
C MXAREF : MAXIMUM D4ARETES DES EF SECTIONNES A DECLARER DANS NOAREF
C NOAREF : NO DES 2 SOMMETS DES ARETES DES EF SECTIONNES
C NOPTEF : NO DES POINTS DE L'EF
C IERR   : 1 SI TABLEAU XYZDFL SATURE, 0 SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Laboratoire JL LIONS UPMC Paris Decembre 2006
C....................................................................012
      include"./incl/ponoel.inc"
      include"./incl/ctemps.inc"
      REAL              COPIEF(1:NBELFI,1:NBPIEF,1:NDIMES)
      DOUBLE PRECISION  CONPRI(1:NBELFI,1:NBPIEF,1:NDIMES,1:NBCAS)
      REAL     DIRPRI(1:NBELFI,1:NBPIEF,1:NDIMES,1:NDIMES,1:NBCAS)
      REAL              XYZDFL(15,MXFLEC)
      INTEGER           NOAREF(2,MXAREF), NOPTEF(64)
      DOUBLE PRECISION  VMAX,A(4)
      INTRINSIC         REAL
C
      IERR   = 0
C
      DO 10 L=1,NBPIEF
C
C        IMPRESSION REDUITE DES CONTRAINTES
         IF( NOFORE .GT. 0 ) THEN
C
C           LES 4 PARAMETRES D'APPEL DE LA FONCTION 'CHOIX'
C           LE TEMPS EN 1-ER PARAMETRE
            A(1) = TEMPS
C           PUIS LES 3 COORDONNEES X Y Z DU POINT D'INTEGRATION
            A(2) = COPIEF(NEF,L,1)
            A(3) = COPIEF(NEF,L,2)
            A(4) = COPIEF(NEF,L,3)
C           FONCTION CHOIX(TEMPS,X,Y,Z)
            CALL FONVAL( NOFORE, 4, A, NCODEV, VMAX )
            IF( NINT(VMAX) .NE. 0 ) THEN
               J=1
            ELSE
               J=0
            ENDIF
         ELSE
            J=1
         ENDIF
         IF( J .EQ. 0 ) GOTO 10
C
C        CONSTRUCTION DES VECTEURS CONTRAINTES PRINCIPALES
         IF( NBFLEC .GE. MXFLEC ) THEN
            IERR = 1
            RETURN
         ENDIF
         NBFLEC = NBFLEC + 1
C
C        COORDONNEES DU POINT CENTRE DES CONTRAINTES A TRACER
         XYZDFL(1,NBFLEC) = COPIEF(NEF,L,1)
         XYZDFL(2,NBFLEC) = COPIEF(NEF,L,2)
         XYZDFL(3,NBFLEC) = COPIEF(NEF,L,3)
C
C        LA PREMIERE CONTRAINTE PRINCIPALE
         VP1 = REAL( CONPRI(NEF,L,1,NCAS) )
C        SA DIRECTION PRINCIPALE
         XV1=DIRPRI(NEF,L,1,1,NCAS)
         YV1=DIRPRI(NEF,L,2,1,NCAS)
         ZV1=DIRPRI(NEF,L,3,1,NCAS)
C        LONGUEUR CM DE LA FLECHE DE VP1
         CXCM  = VP1*XV1*CMPCON
         CYCM  = VP1*YV1*CMPCON
         CZCM  = VP1*ZV1*CMPCON
         CONCM = SQRT( CXCM**2 + CYCM**2 + CZCM**2 )
C        LA FLECHE DE LA 1-ERE CONTRAINTE PRINCIPALE
C        LE SIGNE DE CONCM DONNE LE SENS DE LA FLECHE
         IF (VP1 .LT. 0.D0 ) CONCM=-CONCM
         XYZDFL(4,NBFLEC) = CXCM
         XYZDFL(5,NBFLEC) = CYCM
         XYZDFL(6,NBFLEC) = CZCM
         XYZDFL(7,NBFLEC) = CONCM
C
C        LA DEUXIEME CONTRAINTE PRINCIPALE
         VP2 = REAL( CONPRI(NEF,L,2,NCAS) )
C        SA DIRECTION PRINCIPLALE
         XV1=DIRPRI(NEF,L,1,2,NCAS)
         YV1=DIRPRI(NEF,L,2,2,NCAS)
         ZV1=DIRPRI(NEF,L,3,2,NCAS)
C        LONGUEUR CM DE LA FLECHE DE VP2
         CXCM  = VP2*XV1*CMPCON
         CYCM  = VP2*YV1*CMPCON
         CZCM  = VP2*ZV1*CMPCON
         CONCM = SQRT( CXCM**2 + CYCM**2 + CZCM**2 )
C        LES 3 FLECHES DE LA 2-ERE CONTRAINTE PRINCIPALE
C        LE SIGNE DE CONCM DONNE LE SENS DE LA FLECHE
         IF (VP2 .LT. 0.D0 ) CONCM=-CONCM
         XYZDFL( 8,NBFLEC) = CXCM
         XYZDFL( 9,NBFLEC) = CYCM
         XYZDFL(10,NBFLEC) = CZCM
         XYZDFL(11,NBFLEC) = CONCM
C
C        LA TROISIEME CONTRAINTE PRINCIPALE
         VP3 = REAL( CONPRI(NEF,L,3,NCAS) )
C        SA DIRECTION PRINCIPLALE
         XV1=DIRPRI(NEF,L,1,3,NCAS)
         YV1=DIRPRI(NEF,L,2,3,NCAS)
         ZV1=DIRPRI(NEF,L,3,3,NCAS)
C        LONGUEUR CM DE LA FLECHE DE VP3
         CXCM  = VP3*XV1*CMPCON
         CYCM  = VP3*YV1*CMPCON
         CZCM  = VP3*ZV1*CMPCON
         CONCM = SQRT( CXCM**2 + CYCM**2 + CZCM**2 )
C        LES 3 FLECHES DE LA 3-ERE CONTRAINTE PRINCIPALE
C        LE SIGNE DE CONCM DONNE LE SENS DE LA FLECHE
         IF (VP3 .LT. 0.D0 ) CONCM=-CONCM
         XYZDFL(12,NBFLEC) = CXCM
         XYZDFL(13,NBFLEC) = CYCM
         XYZDFL(14,NBFLEC) = CZCM
         XYZDFL(15,NBFLEC) = CONCM
C
 10   CONTINUE
C
C     AJOUT DES ARETES DE L'EF SECTIONNE
      IF( NBAREF+NARET .GT. MXAREF ) THEN
         IERR = 2
         RETURN
      ENDIF
      DO 20 K=1,NARET
         NBAREF = NBAREF + 1
C        LE NO DES 2 SOMMETS DE L'ARETE K DE L'EF
         NOAREF(1,NBAREF) = NOPTEF( NOSOAR(1,K) )
         NOAREF(2,NBAREF) = NOPTEF( NOSOAR(2,K) )
 20   CONTINUE
C
      RETURN
      END
