      SUBROUTINE AISOAR( MOSOAR, MXSOAR, NOSOAR, NA1 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CHAINER EN COLONNE LCHAIN LES ARETES NON VIDES ET
C -----    NON FRONTALIERES DU TABLEAU NOSOAR
C
C ENTREES:
C --------
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DANS LE TABLEAU NOSOAR
C MXSOAR : NOMBRE MAXIMAL D'ARETES FRONTALIERES DECLARABLES
C
C MODIFIES :
C ----------
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES, CHAINAGES EN +
C          NOSOAR(LCHAIN,I)=ARETE INTERNE SUIVANTE
C
C SORTIE :
C --------
C NA1    : NUMERO DANS NOSOAR DE LA PREMIERE ARETE INTERNE
C          LES SUIVANTES SONT NOSOAR(LCHAIN,NA1), ...
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1997
C....................................................................012
      PARAMETER (LCHAIN=6)
      INTEGER    NOSOAR(MOSOAR,MXSOAR)
C
C     FORMATION DU CHAINAGE DES ARETES INTERNES A ECHANGER EVENTUELLEMENT
C     RECHERCHE DE LA PREMIERE ARETE NON VIDE ET NON FRONTALIERE
      DO 10 NA1=1,MXSOAR
         IF( NOSOAR(1,NA1) .GT. 0 .AND. NOSOAR(3,NA1) .LE. 0 ) GOTO 15
 10   CONTINUE
C
C     PROTECTION DE LA PREMIERE ARETE NON VIDE ET NON FRONTALIERE
 15   NA0 = NA1
      DO 20 NA=NA1+1,MXSOAR
         IF( NOSOAR(1,NA) .GT. 0 .AND. NOSOAR(3,NA) .LE. 0 ) THEN
C           ARETE INTERNE => ELLE EST CHAINEE A PARTIR DE LA PRECEDENTE
            NOSOAR(LCHAIN,NA0) = NA
            NA0 = NA
         ENDIF
 20   CONTINUE
C
C     LA DERNIERE ARETE INTERNE N'A PAS DE SUIVANTE
      NOSOAR(LCHAIN,NA0) = 0
      END
