      SUBROUTINE AJBATECF( MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                     HEXAPAVE, NBIPAV, ECHPAV, N1SPAVE, NOPTSUIV,
     %                     N1TETS, MXTETR, NOTETR,
     %                     NBSTCF, NOSTCF, MXTE1S, NOTE1S,
     %                     MXSMIN, NOSMIN, NODSNO, DISTMIN, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUT DU BARYCENTRE D'UN SUR 2 TETRAEDRES DES SOMMETS DU CF
C -----

C ENTREES:
C --------
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C NBSOMM : NOMBRE DE SOMMETS INITIAUX
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C NPSOFR : =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C              LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE PT OU FACE
C          = -1 SI LE POINT EST SOMMET D'OT TROP PROCHE PT OU FACE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT DEPLACE SUR LA SURFACE
C            DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE

C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES

C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C MXTETR : NOMBRE DE TETRAEDRES DECLARABLES DANS NOTETR
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE DE NUMEROTATION
C          1: 123      2: 234      3: 341      4: 412

C NBSTCF : NOMBRE DE SOMMETS PDU CF DES NBTRCF FACES PERDUES
C NOSTCF : TABLEAU DU NUMERO DANS PTXYZD DES SOMMETS DU CF
C MXTE1S : NOMBRE MAXIMAL D'ENTIERS DU TABLEAU NOTE1S
C NOTE1S : TABLEAU 1:MXTE1S AUXILIAIRE D'ENTIERS
C          GENERALEMENT LES NO DES TETRAEDRES D'UN SOMMET

C MXSMIN : NOMBRE D'ENTIERS DES TABLEAUX AUXILIAIRES NOSMIN, NODSNO
C NOSMIN : TABLEAU 1:MXSMIN D'ENTIERS
C NODSNO : TABLEAU 1:MXSMIN D'ENTIERS
C DISTMIN: TABLEAU 1:MXSMIN DOUBLE PRECISION

C SORTIES:
C --------
C NBSOMM : NOMBRE DE SOMMETS FINAUX
C IERR   : 0 SI PAS D'ERREUR
C          1 SATURATION DES SOMMETS
C          2 PROBLEME LORS DU CALCUL DE LA FONCTION TAILLE_IDEALE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET St Pierre du Perray              Janvier 2020
C....................................................................012
      PARAMETER       ( QUAMED=0.005 )
      INTEGER           NOTETR(8,MXTETR), N1TETS(MXSOMM),
     %                  NPSOFR(MXSOMM), NOTE1S(MXTE1S),
     %                  NOSTCF(NBSTCF)
      INTEGER           NBIPAV(3), N1SPAVE(0:*), NOPTSUIV(1:*),
     %                  NOSMIN(MXSMIN), NODSNO(MXSMIN)
      DOUBLE PRECISION  PTXYZD(1:4,1:MXSOMM)
      DOUBLE PRECISION  ARMIN, ARMAX, SURFTR(4), VOLUTE
      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3), DISTMIN(MXSMIN)
      DOUBLE PRECISION  XYZBATE(4), D
      INTRINSIC         SQRT

      NBSOM0 = NBSOMM

C     EXISTENCE OU NON DE LA FONCTION TAILLE_IDEALE(X,Y,Z)
      NOFOTI = NOFOTIEL()

C     CONSTRUCTION DE LA LISTE DES TETRAEDRES AYANT UN SOMMET DU CF
C     -------------------------------------------------------------
      NBTECF = 0
      DO N = 1, NBSTCF, 2
         NSTCF = NOSTCF( N )
C        LISTE DES TETRAEDRES DE SOMMET NSTCF
         CALL TETR1S( NSTCF,  N1TETS, NOTETR,
     %                NBTE1S, MXTE1S, NOTE1S(NBTECF+1), IERR )
         NBTECF = NBTECF + NBTE1S
         CALL UNITABL( NOTE1S, NBTECF )
      ENDDO

C     UN PAS DE 2 POUR NE PAS TROP GENERER DE BARYCENTRES
      DO 50 N = 1, NBTECF, 2

         NTE = NOTE1S( N )

C        VOLUME et QUALITE du TETRAEDRE NTE
         CALL QUATETD( PTXYZD(1,NOTETR(1,NTE)),
     %                 PTXYZD(1,NOTETR(2,NTE)),
     %                 PTXYZD(1,NOTETR(3,NTE)),
     %                 PTXYZD(1,NOTETR(4,NTE)),
     %                 ARMIN, ARMAX, SURFTR, VOLUTE, QUALTE )

         IF( QUALTE .LE. QUAMED ) GOTO 50

C        CALCUL DES XYZD DU BARYCENTRE DU TETRAEDRE NTE
C        ----------------------------------------------
         DO I=1,4
            XYZBATE(I) = 0D0
            DO J=1,4
               XYZBATE(I) = XYZBATE(I) + PTXYZD( I, NOTETR( J, NTE ) )
            ENDDO
            XYZBATE(I) = XYZBATE(I) / 4
         ENDDO

         IF( NOFOTI .GT. 0 ) THEN
C           CALCUL DE LA DISTANCE SOUHAITEE AU BARYCENTRE de NTE
C           PAR APPEL DE LA FONCTION 'TAILLE_IDEALE'
            CALL FONVAL( NOFOTI, 3, XYZBATE, NCODEV, XYZBATE(4) )
            IF( NCODEV .LE. 0 ) THEN
               IERR = 2
               GOTO 9999
            ENDIF
         ENDIF

C        EXISTE-T-IL UN SOMMET PTXYZD TRES PROCHE DU BARYCENTRE?
C        RETROUVER LES PLUS PROCHES SOMMETS TETRAEDRISES DU POINT NPt
C        A UNE DISTANCE D'UN PAVE RANGES DANS LES PAVES DE L'HEXAEDRE
C        -------------------------------------------------------------
         CALL DMINSTPAV( HEXAPAVE, NBIPAV,ECHPAV,N1SPAVE,NOPTSUIV,
     %                   XYZBATE, PTXYZD,
     %                   MXSMIN, NBSMIN, NOSMIN, NODSNO, DISTMIN )

C        DISTANCE DU SOMMET LE PLUS PROCHE DU BARYCENTRE
         NSDMIN = NOSMIN( NODSNO(1) )
         D      = SQRT( DISTMIN( 1 ) )

         IF( D .LT. PTXYZD(4,NSDMIN) * 1D-2 ) THEN
C           LE BARYCENTRE de NTE TROP PROCHE DU POINT NSDMIN EST ABANDONNE
            PRINT*,'ajbatecf: ABANDON du BARYCENTRE',XYZBATE,
     %             ' du TETRAEDRE',NTE
            PRINT*,'ajbatecf: TROP PROCHE de',(PTXYZD(K,NSDMIN),K=1,4)
            GOTO 50
         ENDIF

C        CREATION DU POINT NBSOMM BARYCENTRE DU TETRAEDRE NTE
C        ----------------------------------------------------
         IF( NBSOMM .GE. MXSOMM ) THEN
            PRINT*,'ajbatecf: TABLEAU PTXYZD SATURE MXSOMM=',MXSOMM
            IERR = 1
            GOTO 9999
         ENDIF
         NBSOMM = NBSOMM + 1
         NPSOFR( NBSOMM ) = 0
         N1TETS( NBSOMM ) = 0
         DO I=1,4
            PTXYZD(I,NBSOMM  ) = XYZBATE(I)
         ENDDO

 50   ENDDO

      IERR = 0

 9999 PRINT*
      PRINT*, 'ajbatecf: Ajout des BARYCENTRES de',NBSOM0+1,' a',NBSOMM

      RETURN
      END
