      SUBROUTINE AJFAET2( NOTET1, NFT,    NOTETR,
     %                    N1FEOC, N1FEVI, NFETOI,
     %                    NFS,    NBFASU, NBFAAJ )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SI LA FACE NFT DU TETRAEDRE NOTET1 N'EST PAS DANS NFETOI
C -----    ALORS ELLE EST AJOUTEE ET NFS EST SA PLACE DANS NFETOI
C          SINON ELLE EST RETIREE de l'ETOILE et NFS=0

C ENTREES:
C --------
C NOTET1 : NUMERO DU TETRAEDRE
C NFT    : NUMERO DE LA FACE DU TETRAEDRE NOTET1
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412

C ENTREES ET SORTIES:
C -------------------
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C N1FEVI : POINTEUR SUR LA PREMIERE FACE VIDE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C NFETOI : EN VERSION 2
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST LA NORMALE DIRIGEE VERS L'INTERIEUR
C             DE L'ETOILE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C SORTIES:
C --------
C NFS    : >0 NUMERO NFETOI DE CETTE FACE NFT DE NOTET1 AJOUTEE DANS NFETOI
C          =0 RETRAIT DE LA FACE NFT DE NOTET1 DE L'ETOILE
C NBFASU : NOMBRE CUMULE DE FACES SUPPRIMEES DE L'ETOILE
C NBFAAJ : NOMBRE CUMULE DE FACES AJOUTEES   A  L'ETOILE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY  Octobre 2014
C23456...............................................................012
      INTEGER  NOTETR(8,*), NFETOI(5,*), NOSOTR0(3), NOSOTR(3)
      INTEGER  NOSOFATE(3,4)
      DATA     NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /
C     => LA NORMALE A LA FACE EST ORIENTEE VERS L'EXTERIEUR DU TETRAEDRE

C     LE NUMERO CROISSANT DES 3 SOMMETS DE LA FACE I DU TETRAEDRE NOTET1
      DO K=1,3
         NOSOTR0(K) = NOTETR( NOSOFATE(K,NFT), NOTET1 )
      ENDDO

C     TRI POUR UNE COMPARAISON RAPIDE
      CALL TRI3NO( NOSOTR0, NOSOTR0 )

C     LE DEBUT DU CHAINAGE DES FACES DE L'ETOILE
      NF0 = 0
      NFS = N1FEOC

C     BOUCLE SUR LES FACES DE L'ETOILE
C     ================================
 10   IF( NFS .GT. 0 ) THEN

C        LE NUMERO DES 3 SOMMETS DE LA FACE SIMPLE NFS DE L'ETOILE
         DO K=1,3
            NOSOTR(K) = ABS( NFETOI(1+K,NFS) )
         ENDDO
         CALL TRI3NO( NOSOTR, NOSOTR )

         IF( NOSOTR0(1) .EQ. NOSOTR(1) .AND.
     %       NOSOTR0(2) .EQ. NOSOTR(2) .AND.
     %       NOSOTR0(3) .EQ. NOSOTR(3) ) THEN

C           LA FACE NFT DU TETRAEDRE NOTET1 EST IDENTIQUE A LA FACE NFS
C           -----------------------------------------------------------
C           LE TETRAEDRE OPPOSE A LA FACE NFT DU TETRAEDRE NOTET1
            NTEOP = NFETOI(1,NFS)
            NOTETR(4+NFT,NOTET1) = NTEOP

            IF( NTEOP .GT. 0 .AND. NOTETR(1,NTEOP) .GT. 0 ) THEN
C              NO FACE DANS NTEOP
               CALL NO1F1T( NOSOTR, NOTETR(1,NTEOP), K )
               IF( K .GT. 0 ) THEN
                  NOTETR(4+K,NTEOP) = NOTET1
               ENDIF
            ENDIF

C           RETRAIT DE LA FACE NFS DE L'ETOILE NFETOI
C           =========================================
            NBFASU = NBFASU + 1
ccc            print *,'ajfaet2: RETRAIT de la face:',(NFETOI(L,NFS),L=1,5)

            IF( NF0 .NE. 0 ) THEN
C              LA FACE NFS,PRECEDEE DE NF0,N'EST PAS LA
C              PREMIERE DE L'ETOILE
               NFETOI(5,NF0) = NFETOI(5,NFS)
C              LA FACE NFS DEVIENT LA PREMIERE VIDE DE L'ETOILE
               NFETOI(5,NFS) = N1FEVI
               N1FEVI = NFS
            ELSE
C              LA FACE NFS=N1FEOC EST LA 1-ERE DE L'ETOILE
               NF0    = NFETOI(5,NFS)
               NFETOI(5,NFS) = N1FEVI
               N1FEVI = NFS
               N1FEOC = NF0
            ENDIF
            NFS = 0
            GOTO 9999

         ELSE

C           LA FACE NFS DE L'ETOILE EST DIFFERENTE. PASSAGE A LA SUIVANTE
C           -------------------------------------------------------------
            NF0 = NFS
            NFS = NFETOI(5,NFS)
            GOTO 10

         ENDIF
      ENDIF

C     LA FACE NFT DE NOTET1 N'EST PAS RETROUVEE DANS L'ETOILE
C     ELLE EST AJOUTEE A LA FIN DES FACES OCCUPEES DE L'ETOILE POUR
C     FAVORISER LE TRAITEMENT DES FACES INITIALES DE L'ETOILE
C     =============================================================
      NBFAAJ = NBFAAJ + 1

C     RECHERCHE D'UNE FACE VIDE
      NFS    = N1FEVI
      N1FEVI = NFETOI( 5, N1FEVI )

C     NOTET1 EST LE TETRAEDRE OPPOSE A CELUI QUI SERA
C     AJOUTE DE L'AUTRE COTE
      NFETOI( 1, NFS ) = NOTET1

C     NOSOFATE(3,I) LE NUMERO DES 3 SOMMETS DE LA FACE NFT DE NOTET1
C     AVEC UN ORDRE QUI DONNE UNE NORMALE 12x13 DIRIGEE VERS L'EXTERIEUR
C     DU TETRAEDRE NOTET1 C-A-D LA DIRECTION DE L'INTERIEUR DE L'ETOILE
      NFETOI( 2, NFS ) = NOTETR( NOSOFATE(1,NFT), NOTET1 )
      NFETOI( 3, NFS ) = NOTETR( NOSOFATE(2,NFT), NOTET1 )
      NFETOI( 4, NFS ) = NOTETR( NOSOFATE(3,NFT), NOTET1 )

C     NFS EST PLACEE EN DERNIERE FACE DE L'ETOILE
      NF0 = 0
      NF1 = N1FEOC
 20   IF( NF1 .GT. 0 ) THEN
         NF0 = NF1
         NF1 = NFETOI( 5, NF1 )
         GOTO 20
      ENDIF
C     NF0 EST LA DERNIERE FACE OCCUPEE DE L'ETOILE

C     MISE A JOUR DU CHAINAGE: NFS VIENT APRES NF0
      IF( NF0 .GT. 0 ) THEN
C        IL EXISTE UNE FACE DANS L'ETOILE
         NFETOI( 5, NF0 ) = NFS
      ELSE
C        NF1 EST LA SEULE FACE DE L'ETOILE
         N1FEOC = NFS
      ENDIF
C     NFS EST LA DERNIERE FACE DE L'ETOILE NFETOI
      NFETOI( 5, NFS ) = 0

ccc      print *,'ajfaet2: AJOUT   de la face:',(NFETOI(L,NFS),L=1,5)

 9999 RETURN
      END
