      SUBROUTINE AJFACE( NOAJRE, NOTET0, NF0,    NBSOTE, NSTETR,
     %                   N1FEOC, N1FEVI, NFETOI,
     %                   NF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     AJOUT OU RETRAIT DE LA FACE I DU TETRAEDRE NOTET0 DE NSTETR
C -----     IDEM VDFAET MAIS GESTION D'UNE QUEUE
C           TOUT AJOUT SE FAIT PAR LA FIN

C ENTREES :
C ---------
C NOAJRE : 1 SI AJOUT   D'UN TETRAEDRE A  L'ETOILE
C          0 SI RETRAIT D'UN TETRAEDRE DE L'ETOILE
C          SEULE L'ORIENTATION DES FACES CREES CHANGE
C          AJOUT   SENS   DIRECT DE LA FACE
C          RETRAIT SENS INDIRECT DE LA FACE
C NOTET0 : NUMERO DU TETRAEDRE DANS LE TABLEAU NSTETR
C NF0    : NUMERO DE LA FACE DU TETRAEDRE NOTET0
C NBSOTE : VALEUR MAXIMALE DE DECLARATION DU PREMIER INDICE DE NSTETR(>3)
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE

C ENTREES ET SORTIES :
C --------------------
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C N1FEVI : POINTEUR SUR LA PREMIERE FACE VIDE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C NFETOI : 1,2,3: NUMERO DES SOMMETS DE LA FACE
C                 DANS LE SENS DIRECT VU DE L'INTERIEUR
C          4: NUMERO DU TETRAEDRE DE CETTE FACE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C SORTIE :
C --------
C NF     : >0  NUMERO DE LA FACE DANS NFETOI SI ELLE A ETE AJOUTEE
C          =0  SI ELLE A ETE SUPPRIMEE
C          =-1 SI SATURATION DES FACES DE NFETOI
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    DECEMBRE 1991
C23456...............................................................012
      include"./incl/gsmenu.inc"
      INTEGER           NSTETR(NBSOTE,*),
     %                  NFETOI(5,*),
     %                  NSF(1:3), NSFT(1:3), NSFE(1:3)

      INTEGER           NOSOFATE(1:3,1:4)
      DATA              NOSOFATE/ 1,2,3, 2,4,3, 3,4,1, 4,2,1 /
C     NO DES SOMMETS DES FACES POUR QUE VU DU SOMMET OPPOSE
C     LES SOMMETS SOIENT VUS DANS LE SENS DIRECT

C     LES 3 SOMMETS DE LA FACE NF0 DU TETRAEDRE VUS DANS LE SENS DIRECT
C     OU ENCORE DE NORMALE DIRIGEE VERS L'INTERIEUR DU TETRAEDRE
      NSF(1) = NSTETR( NOSOFATE(1,NF0), NOTET0 )
      NSF(2) = NSTETR( NOSOFATE(2,NF0), NOTET0 )
      NSF(3) = NSTETR( NOSOFATE(3,NF0), NOTET0 )

C     LES 3 SOMMETS PAR ORDRE CROISSANT
      CALL TRI3NO( NSF, NSFT )

C     LE DEBUT DU CHAINAGE DES FACES DE L'ETOILE
C     ET BOUCLE SUR LES FACES ACTUELLES DE L'ETOILE
      NF1 = 0
      NF2 = N1FEOC

 10   IF( NF2 .GT. 0 ) THEN

C        TRI CROISSANT DES SOMMETS DE LA FACE
         NSFE( 1 ) = ABS( NFETOI(1,NF2) )
         NSFE( 2 ) =      NFETOI(2,NF2)
         NSFE( 3 ) =      NFETOI(3,NF2)
         CALL TRI3NO( NSFE, NSFE )

         IF( NSFE(1) .EQ. NSFT(1) ) THEN
            IF( NSFE(2) .EQ. NSFT(2) ) THEN
               IF( NSFE(3) .EQ. NSFT(3) ) THEN

C                 LA FACE NF2 EST DEJA DANS L'ETOILE
C                 DESTRUCTION DE LA FACE DE L'ETOILE
                  IF( NF1 .NE. 0 ) THEN
C                 LA FACE NF2,PRECEDEE DE NF1,N'EST PAS LA
C                 PREMIERE DE L'ETOILE
                     NFETOI(5,NF1) = NFETOI(5,NF2)
C                    LA FACE NF2 DEVIENT LA PREMIERE VIDE DE L'ETOILE
                     NFETOI(5,NF2) = N1FEVI
                     N1FEVI = NF2
                  ELSE
C                    LA FACE NF2=N1FEOC EST LA 1-ERE DE L'ETOILE
                     NF1    = NFETOI(5,N1FEOC)
                     NFETOI(5,N1FEOC) = N1FEVI
                     N1FEVI = N1FEOC
                     N1FEOC = NF1
                  ENDIF
                  NF = 0
                  RETURN

               ENDIF
            ENDIF
         ENDIF

C        LA FACE EST DIFFERENTE.PASSAGE A LA SUIVANTE
         NF1 = NF2
         NF2 = NFETOI(5,NF2)
         GOTO 10
      ENDIF

C     RESERVATION D'UNE FACE DE NFETOI A PARTIR DES FACES VIDES
      IF( N1FEVI .LE. 0 ) THEN
C        SATURATION DES FACES DE L'ETOILE
         NBLGRC(NRERR) = 2
         KERR(1) = 'AJFACE: SATURATION DES FACES DE L''ETOILE'
         KERR(2) = 'N1FEVI=       N1FEOC=      '
         WRITE(KERR(2)( 8:13),'(I6)') N1FEVI
         WRITE(KERR(2)(22:27),'(I6)') N1FEOC
         CALL LEREUR
         NF = -1
         RETURN
      ENDIF

C     ICI NF1 EST LA DERNIERE FACE TRAITEE DE L'ETOILE
C     LA FACE EST AJOUTEE A L'ETOILE A LA FIN DES FACES OCCUPEES
      NF     = N1FEVI
      N1FEVI = NFETOI(5,N1FEVI)

C     LES 3 SOMMETS DANS LE SENS DIRECT VU DE L'INTERIEUR
      NFETOI(1,NF) = NSF(1)
      IF( NOAJRE .EQ. 0 ) THEN
C        RETRAIT D'UN TETRAEDRE DE L'ETOILE
         NFETOI(2,NF) = NSF(3)
         NFETOI(3,NF) = NSF(2)
      ELSE
C        AJOUT D'UN TETRAEDRE A L'ETOILE
         NFETOI(2,NF) = NSF(2)
         NFETOI(3,NF) = NSF(3)
      ENDIF

C     LE TETRAEDRE DE CETTE FACE
      NFETOI(4,NF) = NOTET0

C     NF EST ELLE LA PREMIERE FACE DE L'ETOILE ?
      IF( N1FEOC .EQ. 0 ) N1FEOC = NF

C     CHAINAGE DES FACES . NF EST LA DERNIERE DE L'ETOILE
      IF( NF1 .GT. 0 ) NFETOI(5,NF1)= NF
      NFETOI(5,NF) = 0

      RETURN
      END
