      SUBROUTINE AJFAET1( NOTET1, NFTE,   NOTETR,
     %                    N1FEOC, N1FEVI, NFETOI, NFS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SI LA FACE I DU TETRAEDRE NOTET1 N'EST PAS DANS NFETOI
C -----    ALORS ELLE EST AJOUTEE ET NFS EST SA PLACE DANS NFETOI
C          SINON ELLE EST SUPPRIMEE et NFS=0

C ENTREES :
C ---------
C NOTET1 : NUMERO NOTETR DU TETRAEDRE
C NFTE   : NUMERO DE LA FACE DU TETRAEDRE NOTET1
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412

C ENTREES ET SORTIES :
C --------------------
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C N1FEVI : POINTEUR SUR LA PREMIERE FACE VIDE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C          =-1 SI SATURATION DU TABLEAU NFETOI
C NFETOI : EN VERSION 1
C          1: NUMERO DU TETRAEDRE DANS NOTETR DE LA FACE DE L'ETOILE
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3: NON UTILISE ICI
C          4: NON UTILISE ICI
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C SORTIE :
C --------
C NFS    : >0 NUMERO DANS NFETOI DE LA FACE AJOUTEE
C          =0 SUPPRESSION DE LA FACE DU TABLEAU NFETOI
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC PARIS & LJUBLJANA     Novembre 2014
C23456...............................................................012
      INTEGER  NOTETR(8,*), NFETOI(5,*), NOSOTR(3), NOSOFATE(3,4)
      DATA     NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /
C     => LA NORMALE A LA FACE EST ORIENTEE VERS L'EXTERIEUR DU TETRAEDRE

      IF( NOTETR(1,NOTET1) .EQ. 0 ) THEN
C        TETRAEDRE INACTIF
         NFS = 0
         GOTO 9999
      ENDIF

C     LE NUMERO NOTEOP DU TETRAEDRE DE L'AUTRE COTE DE LA FACE NFTE
      NOTEOP = NOTETR( 4+NFTE, NOTET1 )
      IF( NOTEOP .LE. 0 ) THEN
C        LE TETRAEDRE DE L'AUTRE COTE N'EXISTE PAS
         GOTO 20
      ENDIF

C     NFOP LE NUMERO LOCAL DE LA FACE CONCERNEE DANS LE TETRAEDRE OPPOSE
C     LES 3 SOMMETS DE LA FACE I DE NOTET1
      DO K=1,3
         NOSOTR(K) = NOTETR( NOSOFATE(K,NFTE), NOTET1 )
      ENDDO
      CALL TRI3NO( NOSOTR, NOSOTR )

C     LA FACE NFTE DE NOTET1 NOSOTR EST ELLE UNE FACE DE NOTEOP?
      CALL NUFATRTE( NOSOTR, NOTETR(1,NOTEOP), NFOP )
      IF( NFOP .GT. 0 ) THEN
C        LA FACE NFTE DU TETRAEDRE NOTET1  EST 
C        LA FACE NFOP DU TETRAEDRE NOTEOP
         NOTETR(4+NFTE,NOTET1 ) = NOTEOP
         NOTETR(4+NFOP,NOTEOP ) = NOTET1
      ENDIF

C     LE DEBUT DU CHAINAGE DES FACES DE L'ETOILE
C     ET BOUCLE SUR LES FACES DE L'ETOILE
C     ==========================================
      NF1 = 0
      NFS = N1FEOC

 10   IF( NFS .GT. 0 ) THEN
         IF(     NFETOI(1,NFS)  .EQ. NOTEOP .AND.
     %       ABS(NFETOI(2,NFS)) .EQ. NFOP ) THEN

C           LA FACE NFOP DU TETRAEDRE NOTEOP EST IDENTIQUE A NFS
C           DESTRUCTION DE LA FACE NFS DOUBLE DE L'ETOILE NFETOI
C           ====================================================
            IF( NF1 .NE. 0 ) THEN
C              LA FACE NFS,PRECEDEE DE NF1,N'EST PAS LA
C              PREMIERE DE L'ETOILE
               NFETOI(5,NF1) = NFETOI(5,NFS)
C              LA FACE NFS DEVIENT LA PREMIERE VIDE DE L'ETOILE
               NFETOI(5,NFS) = N1FEVI
               N1FEVI = NFS
            ELSE
C              LA FACE NFS=N1FEOC EST LA 1-ERE DE L'ETOILE
               NF1    = NFETOI(5,N1FEOC)
               NFETOI(5,N1FEOC) = N1FEVI
               N1FEVI = N1FEOC
               N1FEOC = NF1
            ENDIF
            NFS = 0
            GOTO 9999

         ELSE

C            LA FACE EST DIFFERENTE.PASSAGE A LA SUIVANTE DE NFETOI
             NF1 = NFS
             NFS = NFETOI(5,NFS)
             GOTO 10

          ENDIF
      ENDIF

C     LA FACE NFOP N'EST PAS RETROUVEE. LA FACE NFS EST SIMPLE et
C     EST AJOUTEE A L'ETOILE A LA FIN DES FACES OCCUPEES POUR
C     FAVORISER LE TRAITEMENT DES FACES INITIALES DE L'ETOILE
C     ===========================================================
 20   NF1 = 0
      NFS = N1FEOC
 30   IF( NFS .GT. 0 ) THEN
         NF1 = NFS
         NFS = NFETOI(5,NFS)
         GOTO 30
      ENDIF
C     NF1 EST LA DERNIERE FACE DE L'ETOILE

C     RECHERCHE D'UNE FACE VIDE
      IF( N1FEVI .LE. 0 ) THEN
         PRINT *,'ajfaet1: N1FEVI=',N1FEVI,
     %   ' SATURATION DU TABLEAU NFETOI. A AUGMENTER'
         N1FEVI = -1
         GOTO 9999
      ENDIF
      NFS    = N1FEVI
      N1FEVI = NFETOI(5,N1FEVI)

C     MISE A JOUR DU CHAINAGE : NFS VIENT APRES NF1
      IF( NF1 .GT. 0 ) THEN
C        IL EXISTE UNE FACE DANS L'ETOILE
         NFETOI( 5, NF1 ) = NFS
      ELSE
C        NFS EST LA SEULE FACE DE L'ETOILE
         N1FEOC = NFS
      ENDIF

C     INTIALISATION DE LA FACE SIMPLE EN DERNIERE POSITION DE L'ETOILE
C     ----------------------------------------------------------------
      NFETOI(1,NFS) = NOTET1
      NFETOI(2,NFS) = NFTE
      NFETOI(3,NFS) = 0
      NFETOI(4,NFS) = 0
      NFETOI(5,NFS) = 0

 9999 RETURN
      END
