      SUBROUTINE AJSOAR( NS1,    NS2,    NT1,    NOLIGN,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %                   NOAR,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUTER L'ARETE DE SOMMET NS1-NS2 DANS LE HACHAGE DU TABLEAU
C -----    NOSOAR DES ARETES DE LA TRIANGULATION SI ELLE N'EXISTE PAS
C          METTRE A JOUR LES DONNEES DANS TOUS LES CAS
C
C ENTREES:
C --------
C NS1 NS2: NUMERO DES 2 SOMMETS DE L'ARETE
C NT1    : NUMERO DU TRIANGLE AUQUEL APPARTIENT L'ARETE
C          NT1=-1 SI NUMERO INCONNU
C NOLIGN : NUMERO DE LA LIGNE DE L'ARETE
C          =0 SI L'ARETE N'EST PAS UNE ARETE DE LIGNE
C          CE NUMERO EST AJOUTE SEULEMENT SI L'ARETE EST CREEE
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOSOAR
C MXSOAR : NOMBRE MAXIMAL D'ARETES STOCKABLES DANS LE TABLEAU NOSOAR
C
C MODIFIES:
C ---------
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C          UNE ARETE I DE NOSOAR EST VIDE  <=>  NOSOAR(1,I)=0
C          CHAINAGE DES ARETES VIDES AMONT ET AVAL
C          L'ARETE VIDE QUI PRECEDE=NOSOAR(4,I)
C          L'ARETE VIDE QUI SUIT   =NOSOAR(5,I)
C NOSOAR : NUMERO DES 2 SOMMETS, NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE MOMENTAN'E D'ARETES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = MIN( NOSOAR(1), NOSOAR(2) )
C NOARST : NOARST(NP) NUMERO D'UNE ARETE DU SOMMET NP
C
C SORTIES:
C --------
C NOAR   : >0 NUMERO DE L'ARETE RETROUVEE OU AJOUTEE
C IERR   : =0 SI PAS D'ERREUR
C          =1 SI LE TABLEAU NOSOAR EST SATURE
C          =2 SI ARETE A CREER ET APPARTENANT A 2 TRIANGLES DISTINCTS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       AOUT 1998
C2345X7..............................................................012
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      INTEGER           NOSOAR(MOSOAR,MXSOAR), NOARST(*)
      INTEGER           NU2SAR(2)
C
C     AJOUT EVENTUEL DE L'ARETE S1 S2 DANS NOSOAR
      NU2SAR(1) = NS1
      NU2SAR(2) = NS2
C
C     HACHAGE DE L'ARETE DE SOMMETS NU2SAR
      CALL HASOAR( MOSOAR, MXSOAR, N1SOAR, NOSOAR, NU2SAR, NOAR )
C     EN SORTIE: NOAR>0 => NO ARETE RETROUVEE
C                    <0 => NO ARETE AJOUTEE
C                    =0 => SATURATION DU TABLEAU NOSOAR
C
      IF( NOAR .EQ. 0 ) THEN
C
C        SATURATION DU TABLEAU NOSOAR
         WRITE(IMPRIM,*) 'AJSOAR: TABLEAU NOSOAR SATURE'
         IERR = 1
         RETURN
C
      ELSE IF( NOAR .LT. 0 ) THEN
C
C        L'ARETE A ETE AJOUTEE. INITIALISATION DES AUTRES INFORMATIONS
         NOAR = -NOAR
C        LE NUMERO DE LA LIGNE DE L'ARETE
         NOSOAR(3,NOAR) = NOLIGN
C        LE TRIANGLE 1 DE L'ARETE => LE TRIANGLE NT1
         NOSOAR(4,NOAR) = NT1
C        LE TRIANGLE 2 DE L'ARETE => PAS DE TRIANGLE
         NOSOAR(5,NOAR) = -1
C
C        LE SOMMET APPARTIENT A L'ARETE NOAR
         NOARST( NU2SAR(1) ) = NOAR
         NOARST( NU2SAR(2) ) = NOAR
C
      ELSE
C
C        L'ARETE A ETE RETROUVEE.
C        SI ELLE APPARTIENT A PLUS DE 2 TRIANGLES
C        ALORS IL Y A UNE ERREUR
         IF( NOSOAR(5,NOAR) .GT. 0 ) THEN
C           ARETE APPARTENANT A PLUS DE 2 TRIANGLES => ERREUR
            WRITE(IMPRIM,*) 'ERREUR AJSOAR: ARETE ',NOAR,
     %              ' DANS PLUS DE 2 TRIANGLES'
            IERR = 2
            RETURN
         ENDIF
         NOSOAR(5,NOAR) = NT1
C
      ENDIF
C
C     PAS D'ERREUR
      IERR = 0
      END
