      SUBROUTINE AJTE2ACF( KTITRE, PTXYZD, LEFACO, NO0FAR,
     %                     NBTRCF, NOTRCF, NBSTCF, NOSTCF, 
     %                     NOTETR, N1TETS, MXTE1S, NOTE1S,
     %                     MXTECF, NBTECF, NOTECF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUT A L'ETOILE NOTECF DES TETRAEDRES DES TETRAEDRES 
C -----    AYANT 2 ARETES CONSECUTIVES DU CF

C ENTREES:
C --------
C KTITRE : TITRE D'UN TRACE
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE

C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES D'OC
C NO0FAR : NUMERO DES 3 SOMMETS DES FACES AJOUTEES AU CF

C NBTRCF : NOMBRE DE FACES DE NOTRCF
C NOTRCF : >0 NUMERO DANS LEFACO DES TRIANGLES PERDUS  DU CF
C          <0 NUMERO DANS NO0FAR DES TRIANGLES AJOUTES AU CF
C NBSTCF : NOMBRE DE SOMMETS DES ARETES PERIPHERIQUES DU CF
C NOSTCF : NUMERO PTXYZD DES NBSTCF SOMMETS DES ARETES PERIPHERIQUES

C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C N1TETS : N1TETS(NS) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET NS
C MXTE1S : NOMBRE D'ENTIERS DU TABLEAU AUXILIAIRE NOTE1S
C NOTE1S : TABLEAU 1:MXTE1S D'ENTIERS (No DE TETRAEDRE DE CERTAINS SOMMETS)

C SORTIES:
C --------
C NBTECF : NOMBRE DE TETRAEDRES DE L'ETOILE
C NOTECF : NUMERO NOTETR DES NBTECF TETRAEDRES DE L'ETOILE
C IERR   : =0  SI PAS D'ERREUR DETECTEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Veulettes sur mer               Decembre 2019
C2345X7..............................................................012
      CHARACTER*(*)     KTITRE
      DOUBLE PRECISION  PTXYZD(4,*)
      INTEGER           NOTETR(8,*), N1TETS(*),
     %                  LEFACO(11,0:*), NO0FAR(3,*), NOTE1S(MXTE1S),
     %                  NOTRCF(NBTRCF), NOSTCF(NBSTCF), NOTECF(MXTECF),
     %                  NFETOIL(5)

      IERR   = 0

C     ----------------------------------------------------------------
C     AJOUT DES EVENTUELS TETRAEDRES AYANT 2 ARETES CONSECUTIVES DU CF
C     ----------------------------------------------------------------
      NBTECF0 = NBTECF

C     NUMERO DES SOMMETS DU CF RENDU PERIODIQUE
      NOSTCF( NBSTCF+1 ) = NOSTCF( 1  )
      DO 10 N = 1, NBSTCF-1

C        TOUTES LES ARETES POSSIBLES DU CF ISSUES DE NS1 SONT ENVISAGEES
         NS1 = NOSTCF( N )
         NS2 = NOSTCF( N+1 )
         NS3 = NOSTCF( N+2 )

C        LES NBTEA1 TETRAEDRES D'ARETE NS1 NS2
         CALL TETR1A( NS1,    NS2,    N1TETS, NOTETR,
     %                NBTEA1, MXTE1S, NOTE1S, IERR )
         IF( IERR .NE. 0 ) GOTO 9999
         IF( NBTEA1 .EQ. 0 ) GOTO 10

C        LES NBTEA2 TETRAEDRES D'ARETE NS2 NS3
         CALL TETR1A( NS2,    NS3,   N1TETS, NOTETR,
     %                NBTEA2, MXTE1S-NBTEA1, NOTE1S(NBTEA1+1), IERR )
         IF( IERR .NE. 0 ) GOTO 9999
         IF( NBTEA2 .EQ. 0 ) GOTO 10

C        RECHERCHE DES TETRAEDRES COMMUNS AUX 2 LISTES
         DO I1 = 1, NBTEA1

C           LE TETRAEDRE D'ARETE NS1-NS2
            NTE1 = NOTE1S( I1 )

            DO I2 = 1, NBTEA2

C              LE TETRAEDRE D'ARETE NS2-NS3
               NTE2 = NOTE1S( NBTEA1+I2 )

               IF( NTE1 .EQ. NTE2 ) THEN

C                 NTE1 ET NTE2 ONT LES ARETES NS1-NS2 et NS2-NS3
C                 AJOUT S'ILS NE SONT PAS DEJA DANS NOTECF
                  DO K=1,NBTECF
                     IF( NOTECF(K) .EQ. NTE1 ) GOTO 10
                  ENDDO

C                 AJOUT DE NTE1 AU TABLEAU NOTECF
                  NBTECF = NBTECF + 1
                  NOTECF( NBTECF ) = NTE1
                  PRINT*,'ajte2acf: Ajout du TETRAEDRE(',NTE1,'):',
     %                   (NOTETR(k,NTE1),k=1,8),' d''ARETES',
     %                    NS1,'-',NS2,' et',NS2,'-',NS3
                  GOTO 10

               ENDIF

            ENDDO

         ENDDO

 10   ENDDO

C     UNICITE DES NBTECF TETRAEDRES DU TABLEAU NOTECF
      CALL UNITABL( NOTECF, NBTECF )

      IF( NBTECF0 .NE. NBTECF ) THEN
C        TRACE DES TETRAEDRES, TRIANGLES, ARETES DU CF
         KTITRE='ajte2acf: AJOUT de         TETRAEDRES AYANT 2 ARETES C
     %ONSECUTIVES du CF'
         WRITE(KTITRE(19:24),'(I6)') NBTECF-NBTECF0
         CALL SANSDBL( KTITRE, L )
         PRINT*, KTITRE(1:L)
         CALL TRFETO4( KTITRE(1:L), PTXYZD, 0, NFETOIL,
     %                 NBTRCF, NOTRCF, LEFACO, NO0FAR,
     %                 NBTECF, NOTECF, NOTETR )
      ENDIF

 9999 RETURN
      END
