      SUBROUTINE AMQALLTE( QTEAME,  MXTETR, N1TEVI, NOTETR, N1TETS,
     %                     MXSOMM,  NBSOMM, PTXYZD, NPSOFR,
     %                     INFACO,  MXFACO, LEFACO, IVOLTE, NVOLTE,
     %                     MXTEET,  NOTEET, MXFEET, NOFEET,
     %                     MXTECR,  NOTECR,
     %                     NUDTETR, VOLMOY, MODIFT, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TENTATIVE D'AMELIORER LA QUALITE DE TOUS LES TETRAEDRES
C -----    DE QUALITE MEDIOCRE<QTEAME PAR DIFFERENTES TECHNIQUES SELON
C          LE TYPE DE DEGENERESCENCE en TETRAEDRE PLAT de
C          TYPE TRIANGLE ou QUADRANGLE

C ENTREES:
C --------
C QTEAME : QUALITE AU DESSOUS DE LAQUELLE UN TETRAEDRE EST AMELIORE
C MXTETR : NOMBRE MAXIMAL DE TETRAEDRES DU TABLEAU NOTETR
C N1TEVI : NO DU PREMIER TETRAEDRE VIDE DANS NOTETR
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C MXSOMM : NOMBRE MAXIMAL DE POINTS DU TABLEAU PTXYZD
C NBSOMM : NOMBRE         DE POINTS DU TABLEAU PTXYZD
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C NPSOFR : =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C              LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE PT OU FACE
C          = -1 SI LE POINT EST SOMMET D'OT TROP PROCHE PT OU FACE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT DEPLACE SUR LA SURFACE
C            DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE

C NBSTCF : NOMBRE DE SOMMETS DU CF DES FACES PERDUES CONTIGUES
C NOSTCF : NUMERO PTXYZD DES NBSTCF SOMMETS DU CF

C INFACO : = 0 PAS DE TABLEAU LEFACO NI DE CONSERVATION DES FACES FRONTIERE
C          = 1 EXISTENCE TABLEAU LEFACO ET CONSERVATION DES FACES FRONTIERE
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES D'OC
C IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL (VOLUME MONO-MATERIAU)
C          1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C NVOLTE : NUMERO DU VOLUME (1 A NBVOPA) DE CHAQUE TETRAEDRE
C          -1 SI VOLUME INCONNU
C NUDTETR: NUMERO DU DERNIER TETRAEDRE ACTIF DANS NOTETR

C AUXILIAIRES:
C ------------
C MXTEET : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES DANS LE TABLEAU NOTEET
C NOTEET : NO NOTETR DES TETRAEDRES DES SOMMETS D'UN TETRAEDRE MEDIOCRE
C MXFEET : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LE CHAINAGE NFETOI
C NOFEET : au debut VERSION1 FACES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR AYANT CETTE FACE
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3: NON UTILISE ICI
C          4: NUMERO DE CETTE FACE DANS LEFACO, 0 SI PAS DANS LEFACO
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES
C          ensuite VERSION2
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST DIRIGE VERS L'INTERIEUR DE L'ETOILE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C MXTECR : NOMBRE MAXIMAL DE NO NOTETR DES TETRAEDRES CREES
C NOTECR : NO NOTETR DES TETRAEDRES CREES DANS L'ETOILE D'UN TETRAEDRE NTEQM

C SORTIES:
C --------
C NBSOMM : NOMBRE DE POINTS DU TABLEAU PTXYZD
C NUDTETR: NUMERO DU DERNIER TETRAEDRE ACTIF DANS NOTETR
C VOLMOY : VOLUME MOYEN DES TETRAEDRES
C          A UTILISER POUR DETECTER UN VOLUME QUASI NUL
C MODIFT : = 0 AUCUNE MODIFICATION DE TETRAEDRES
C          > 0 NOMBRE DE FOIS OU DES TETRAEDRES ONT ETE MODIFIES
C IERR   : = 0 PAS D'ERREUR
C          = 1 SATURATION DES SOMMETS    du TABLEAU PTXYZD
C          = 2 SATURATION DE MCN
C          = 3 SATURATION DES TETRAEDRES du TABLEAU NOTETR
C          =11 TETRAEDRE NTEQM AVEC 0 POUR PREMIER SOMMET
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET VEULETTES & St PIERRE du PERRAY      Mai 2018
C2345X7..............................................................012
      PARAMETER        (QUAMED=0.005)
      include"./incl/langue.inc"
      include"./incl/pp.inc"
      COMMON          MCN(MOTMCN)
      REAL           RMCN(MOTMCN)
      EQUIVALENCE   (RMCN(1),MCN(1))

      DOUBLE PRECISION  PTXYZD(4,MXSOMM)
      INTEGER           NOTETR(8,MXTETR), N1TETS(*), NPSOFR(*),
     %                  LEFACO(1:11,0:MXFACO), NVOLTE(*),
     %                  NOTEET(MXTEET), NOFEET(5,MXFEET), NOTECR(MXTECR)

      DOUBLE PRECISION  ARMIN, ARMAX, SURFTR(4), V, VOLTOT, VOLMOY

      COMMON / TRTETR / STOPTE,TRACTE
      LOGICAL           STOPTE,TRACTE,TRACTE0

      TRACTE0= TRACTE
      VOLTOT = 0D0
      VOLMOY = 0D0
      QTEMIN = 2
      NBTETR = 0
      MODIFT = 0
      IERR   = 0

      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
      PRINT*,'amqallte: AMELIORATION de la QUALITE des TETRAEDRES de QUA
     %LITE MEDIOCRE <',QTEAME
      ELSE
      PRINT*,'amqallte: TETRAHEDRA QUALITY IMPROVEMENT from QUALITY<',
     %        QTEAME
      ENDIF

C     RESERVATION DES TABLEAUX DE LA QUALITE DES TETRAEDRES MEDIOCRES
C     ET DE LEUR NUMERO DANS NOTETR
      MNQUTE = 0
      MNANTE = 0
      IF( NUDTETR .GT. 0 ) THEN
         MXTRI = NUDTETR
      ELSE
         MXTRI = MXTETR
      ENDIF
      CALL TNMCDC( 'REEL',   MXTRI, MNQUTE )
      CALL TNMCDC( 'ENTIER', MXTRI, MNANTE )
      IF( MNQUTE .EQ. 0 .OR. MNANTE .EQ. 0 ) THEN
C        SATURATION DE MCN
         PRINT*,'amqallte: SATURATION de MCN MOTMCN=',MOTMCN
         IERR = 2
         GOTO 9999
      ENDIF

C     CALCUL DE LA QUALITE DES TETRAEDRES
C     RECENSEMENT DES NTEQM TETRAEDRES MEDIOCRES
C     ------------------------------------------
      NUDTETR = 0
      NBTEQM  = 0
      DO NTE = 1, MXTETR

         IF( NOTETR(1,NTE) .GT. 0 ) THEN

C           MISE A JOUR DU NO DU DERNIER TETRAEDRE ACTIF DANS NOTETR
            IF( NUDTETR .LT. NTE ) NUDTETR = NTE

C           VOLUME ET QUALITE DU TETRAEDRE NTE
            CALL QUATETD( PTXYZD(1,NOTETR(1,NTE)),
     %                    PTXYZD(1,NOTETR(2,NTE)),
     %                    PTXYZD(1,NOTETR(3,NTE)),
     %                    PTXYZD(1,NOTETR(4,NTE)),
     %                    ARMIN, ARMAX, SURFTR, V, Q )

C           UN TETRAEDRE ACTIF DE PLUS
            NBTETR = NBTETR + 1
C           VOLUME TOTAL DES NBTETR TETRAEDRES
            VOLTOT = VOLTOT + ABS( V )

            IF( Q .LT. QTEMIN ) QTEMIN = Q

            IF( Q .LT. QTEAME .AND. NBTEQM .LT. MXTRI ) THEN

C              STOCKAGE DE LA QUALITE DU TETRAEDRE MEDIOCRE NBTEQM
               RMCN( MNQUTE + NBTEQM ) = Q
C              ANCIEN NUMERO DU TETRAEDRE MEDIOCRE DANS NOTETR
                MCN( MNANTE + NBTEQM ) = NTE
               NBTEQM = NBTEQM + 1

            ENDIF

         ENDIF

      ENDDO

C     VOLUME MOYEN DES NBTETR TETRAEDRES ACTIFS
      VOLMOY = VOLTOT / NBTETR

      IF( LANGAG .EQ. 0 ) THEN
         PRINT *,'amqallte: Parmi',NBTETR,' TETRAEDRES',
     %            NBTEQM,' TETRAEDRES DE QUALITE<',QTEAME,
     %           ' et de QUALITE MIN=',QTEMIN
      ELSE
         PRINT *,'amqallte: Among',NBTETR,' TETRAHEDRA',
     %            NBTEQM,' TETRAHEDRA of QUALITY<',QTEAME,
     %           ' and MIN QUALITY=',QTEMIN
      ENDIF


C     TRI SELON LA QUALITE CROISSANTE DES NBTEQM TETRAEDRES DE QUALITE MEDIOCRE
C     -------------------------------------------------------------------------
      CALL TRITRP( NBTEQM, RMCN(MNQUTE), MCN(MNANTE) )


C     TENTATIVE D'AMELIORATION DES NTEQM TETRAEDRES
C     ---------------------------------------------
      DO 50 NT = 1, NBTEQM

C        ANCIEN NUMERO NOTETR DU TETRAEDRE MEDIOCRE NT
         NTE = MCN( MNANTE -1 + NT )

C        QUALITE DU TETRAEDRE NTE
         Q = RMCN( MNQUTE-1+NT )

         IF( Q .LT. QUAMED ) THEN
C           TENTATIVE D'AMELIORER LA QUALITE ET CELLE DES VOISINS DE NTE
C           EN RETETRAEDRISANT LES TETRAEDRES DE SES SOMMETS
            CALL A1TEQMMM( QTEAME, NTE,
     %                     MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                     INFACO, MXFACO, LEFACO, IVOLTE, NVOLTE,
     %                     MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %                     MXTEET, NOTEET, MXFEET, NOFEET,
     %                     MXTECR, NBTECR, NOTECR, MODIF,  IERR )
            GOTO 50
         ENDIF

C        TENTATIVE D'AMELIORER LA QUALITE ET CELLE DES VOISINS DE NTE
         CALL A1TEQM( QTEAME, NTE,    MXSOMM, PTXYZD, NPSOFR,
     %                INFACO, MXFACO, LEFACO, IVOLTE, NVOLTE,
     %                MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %                MODIF,  IERR )
         IF( MODIF .GT. 0 ) THEN
            MODIFT = MODIFT + 1
         ENDIF

 50   ENDDO


C     CI-DESSOUS A SUPPRIMER SI NBELIM EST TOUJOURS NUL
      NBELIM = 0
      IF( IVOLTE .NE. 0 ) THEN
C        EXISTENCE DE TETRAEDRES SE TROUVANT DANS AUCUN VOLUME:  UTILE?...
         DO NTE = 1, NUDTETR
            IF( NOTETR(1,NTE) .NE. 0 .AND. NVOLTE(NTE) .LT. 0 ) THEN
               NBELIM = NBELIM + 1
               PRINT*,'amqallte: NOTETR(',NTE,')=',(NOTETR(K,NTE),K=1,8)
     %               ,' MAIS VOLUME=',NVOLTE(NTE)
            ENDIF
         ENDDO
      ENDIF


      IF( LANGAG .EQ. 0 ) THEN
      PRINT *,'amqallte:',MODIFT,' MODIFICATIONS de TETRAEDRES parmi',
     %         NBTETR,' TETRAEDRES, No DERNIER TETRAEDRE',NUDTETR,
     %        ' et',NBELIM,' TETRAEDRES dans AUCUN VOLUME'
      ELSE
      PRINT *,'amqallte:',MODIFT,' MODIFICATIONS of TETRAHEDRA among',
     %         NBTETR,' TETRAHEDRA, LAST TETRAHEDRON NUMBER',NUDTETR,
     %        ' and',NBELIM,' TETRAHEDRA in ZERO VOLUME'
      ENDIF

 9999 IF( MNQUTE .GT. 0 ) CALL TNMCDS( 'REEL',   MXTRI, MNQUTE )
      IF( MNANTE .GT. 0 ) CALL TNMCDS( 'ENTIER', MXTRI, MNANTE )

      TRACTE = TRACTE0
      RETURN
      END
