      SUBROUTINE AMQGRTE( QTEAME, MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                    INFACO, MXFACO, LEFACO, IVOLTE, NVOLTE,
     %                    MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %                    MXTEET, NBTEET, NOTEET,
     %                    MODIFTET, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AMELIORATION DE LA QUALITE D'UN GROUPE DE TETRAEDRES NOTETR EN
C -----    TRAITANT PAR DECOMPOSITION LES TETRAEDRES DE QUALITE MEDIOCRE

C ENTREES:
C --------
C QTEAME : QUALITE DES TETRAEDRES AU DESSOUS DE LAQUELLE UNE
C          AMELIORATION DES TETRAEDRES EST DEMANDEE
C MXSOMM : NOMBRE DE SOMMETS DECLARABLES DANS PTXYZD
C NBSOMM : NOMBRE DE SOMMETS ACTUELS DANS PTXYZD
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C NPSOFR : NUMERO DES POINTS INITIAUX
C          LE SIGNE DEVIENT NEGATIF SI LE SOMMET EST DEPLACE
C          =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C                    LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -1 SI LE POINT EST SOMMET RECONNU TROP PROCHE
C          = -4 SI LE POINT EST SOMMET DE LA GRILLE REGULIERE ELIMINABLE
C          = -3 SI LE POINT EST SOMMET REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT I DEPLACE SUR LA SURFACE
C             DANS LEUR SURFACE FERMEE INITIALE OU NO DE POINT INTERNE

C INFACO : = 0 PAS DE TABLEAU LEFACO NI CONTROLE DE FACE FRONTIERE
C          = 1 EXISTENCE DU TABLEAU LEFACO ET CONTROLE DE FACE FRONTIERE
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES D'OC
C IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL
C          1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C NVOLTE : >0 NUMERO DU VOLUME DE 1 A NBVOPA DE CHAQUE TETRAEDRE
C          -1 SI TETRAEDRE INACTIF ou SUPPRIME

C MXTETR : NOMBRE DE TETRAEDRES DECLARABLES DANS NOTETR
C MXTEET : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES DANS NOTEET

C MODIFIES:
C ---------
C N1TEVI : NO DU PREMIER TETRAEDRE VIDE DANS NOTETR
C N1TETS : N1TETS(NS) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET NS
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C NUDTETR: NUMERO NOTETR DU DERNIER TETRAEDRE ACTIF DANS NOTETR

C SORTIES :
C ---------
C NBSOMM : NOMBRE DE SOMMETS FINAL DANS PTXYZD
C NBTEET : NOMBRE DE  TETRAEDRES DE NOTETR DANS NOTEET
C NOTEET : NUMERO DES TETRAEDRES DE NOTETR CONTENANT AU MOINS
C          1 DES 4 SOMMETS DU TETRAEDRE PLAT
C MODIFTET:= 0 AUCUNE MODIFICATION DE TETRAEDRES
C          > 0 NOMBRE DE TETRAEDRES MODIFIES
C IERR   : = 0 PAS D'ERREUR
C          = 1 SATURATION DU TABLEAU NOTETR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY  Janvier 2017
C2345X7..............................................................012
      PARAMETER       ( QUAMED=0.005, MXTEQM=2048 )
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE
ccc      LOGICAL                          TRACTE0
      DOUBLE PRECISION  PTXYZD(4,MXSOMM)
      INTEGER           NPSOFR(1:MXSOMM)
      INTEGER           NOTETR(8,MXTETR), N1TETS(MXSOMM),NOTEET(MXTEET),
     %                  NOTEQM(MXTEQM), NOFEET(5,MXTEQM),NOTECR(MXTEQM),
     %                  LEFACO(1:11,0:MXFACO), NVOLTE(*)
      DOUBLE PRECISION  ARMIN, ARMAX, SURFTR(4)
      DOUBLE PRECISION  VOLUTE, VOMITE, VOLUE0, VOLMOY, VMIN, VOLMIN, V

ccc      CHARACTER*80      KTITRE
ccc      TRACTE0 = TRACTE

C     CALCUL DES VOLUMES et QUALITES avant TRAITEMENT
C     RECHERCHE DU TETRAEDRE DE PLUS PETIT VOLUME
C     COMPRESSION DU TABLEAU NOTEET
      MODIFTET = 0
      IERR = 0

      IF( NBTEET .LE. 1 ) GOTO 9999

      VOMITE = 0D0
      VOLUE0 = 0D0
      QUAMOY = 0.0
      QUAMIN = 2.0
      NTQMIN = 0
      NTVMIN = 0
      VOLMIN = 1D123
      VMIN   = 1D123
      NBTEQM = 0
      NBT    = 0

C     RECENSEMENT DES TETRAEDRES DE QUALITE MEDIOCRE
      DO K = 1, NBTEET

C        TETRAEDRE
         NTE = NOTEET( K )

         IF( NTE .GT. 0 .AND. NOTETR(1,NTE ) .GT. 0 ) THEN

C           SON VOLUME ET SA QUALITE
            CALL QUATETD( PTXYZD(1,NOTETR(1,NTE)),
     %                    PTXYZD(1,NOTETR(2,NTE)),
     %                    PTXYZD(1,NOTETR(3,NTE)),
     %                    PTXYZD(1,NOTETR(4,NTE)),
     %                    ARMIN, ARMAX, SURFTR, VOLUTE, QUALTE )

            V = ABS( VOLUTE )
            VOLUE0 = VOLUE0 + V
            QUAMOY = QUAMOY + QUALTE

            IF( QUALTE .LT. QUAMIN ) THEN
               QUAMIN = QUALTE
               VMIN   = VOLUTE
               NTQMIN = NTE
            ELSE IF( QUALTE .EQ. QUAMIN ) THEN
               IF( V .LT. VMIN ) THEN
                  VMIN   = VOLUTE
                  NTQMIN = NTE
               ENDIF
            ENDIF

            IF( QUALTE .LT. QTEAME ) THEN
C              STOCKAGE DU NO DE TETRAEDRE DE QUALITE MEDIOCRE
               NBTEQM = NBTEQM + 1
               NOTEQM( NBTEQM ) = NTE
            ENDIF

            IF( VOLUTE .LT. VOLMIN ) THEN
               VOLMIN = VOLUTE
               NTVMIN = NTE
            ENDIF

ccc            PRINT *,'amqgrte : avant NOTETR(',NTE,')='
ccc     %             ,(NOTETR(I,NTE),I=1,8)
ccc     %             ,' QUALITE=',QUALTE,' V=',VOLUTE

            NBT = NBT + 1
            NOTEET( NBT ) = NTE

C           LES SOMMETS DES TETRAEDRES OPPOSES DEVIENNENT LEUR 1-ER TETRAEDRE

            DO NF = 1, 4
               NTOP = NOTETR( 4+NF, NTE )
               IF( NTOP .GT. 0 .AND. NOTETR(1,NTOP) .GT. 0 ) THEN
C                 LES SOMMETS DE NTOP APPARTIENNENT A NTOP ET NON PLUS A NTE
C                 POUR EVITER DE PERDRE LEUR ATTACHEMENT SUITE AUX 
                  DO L=1,4
                     N1TETS( NOTETR(L,NTOP) ) = NTOP
                  ENDDO
               ENDIF
            ENDDO

         ENDIF

      ENDDO

      NBTEET = NBT
      VOLMOY = VOLUE0 / NBT
      QUAMOY = QUAMOY / NBT

      IF( NBTEQM .LE. 0 ) THEN

ccc      IF( NBTEQM .LE. 0 .AND. NTQMIN .GT. 0 ) THEN
ccc         NBTEQM = 1
ccc         NOTEQM( 1 ) = NTQMIN
ccc         PRINT *,'amqgrte: MODIF du TETRA',NTQMIN,
ccc     %           ' de QMIN=',QUAMIN,' QMOY=',QUAMOY,
ccc     %           NBTEET,' TETRAEDRES de Volume=',VOLUE0,
ccc     %           ' VMoyen=',VOLMOY,' VMin=',VOLMIN
         GOTO 9999

      ENDIF

      IF( NBTEQM .GT. 0 ) THEN

ccc         PRINT*
ccc         PRINT*,'amqgrte: Vol MIN Tetraedres=',VOLMIN,
ccc     %          ' NOTETR(',NTVMIN,')=',(NOTETR(K,NTVMIN),K=1,8)

         DO K=1,NBTEQM

C           TRAITEMENT DU TETRAEDRE NTE DE VOLUME<=0 ou QUALITE<0.01
            NTE = NOTEQM( K )

C           CONTROLE POUR SAVOIR SI NTE N'A PAS ETE DETRUIT DEPUIS
            IF( NTE .GT. 0 .AND. NOTETR(1,NTE ) .GT. 0 ) THEN

C              SON VOLUME ET SA QUALITE
               CALL QUATETD( PTXYZD(1,NOTETR(1,NTE)),
     %                       PTXYZD(1,NOTETR(2,NTE)),
     %                       PTXYZD(1,NOTETR(3,NTE)),
     %                       PTXYZD(1,NOTETR(4,NTE)),
     %                       ARMIN, ARMAX, SURFTR, VOLUTE, QUALTE )

               IF( QUALTE .LT. QUAMED ) THEN

C                 TENTATIVE D'AMELIORER LA QUALITE ET CELLE DES VOISINS DE NTE
C                 EN RETETRAEDRISANT LES TETRAEDRES DE SES SOMMETS
                  CALL A1TEQMMM( QTEAME, NTE,
     %                           MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                           INFACO, MXFACO, LEFACO, IVOLTE, NVOLTE,
     %                           MXTETR, N1TEVI, N1TETS, NOTETR,NUDTETR,
     %                           MXTEQM, NOTEQM, MXTEQM, NOFEET,
     %                           MXTEQM, NBTECR, NOTECR, MODIFT,  IERR )

               ELSE

C                 AMELIORER LE TETRAEDRE NTE ET LES TETRAEDRES VOISINS DE NTE
                  CALL A1TEQM( QTEAME, NTE,    MXSOMM, PTXYZD, NPSOFR,
     %                         INFACO, MXFACO, LEFACO, IVOLTE, NVOLTE,
     %                         MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %                         MODIFT, IERR )

               ENDIF

C              S'IL Y A EU MODIFICATION DES TETRAEDRES ALORS MODIFTET+1
C              NECESSAIRE POUR TERMINER LES ITERATIONS SUR amqgrte.f
               MODIFTET = MODIFTET + MODIFT

            ENDIF

         ENDDO

C        MISE A JOUR DE N1TETS POUR CAUSE DE RETRAIT DE TETRAEDRES
         IF( MODIFTET .GT. 0 ) THEN
            DO K = 1, NBTEET
C              TETRAEDRE
               NTE = NOTEET( K )
               IF( NTE .GT. 0 .AND. NOTETR(1,NTE) .GT. 0 ) THEN
                  DO L=1,4
                     N1TETS( NOTETR(L,NTE) ) = NTE
                  ENDDO
               ENDIF
            ENDDO
         ENDIF

      ENDIF

ccc      TRACTE = TRACTE0

 9999 RETURN
      END
