      SUBROUTINE BAFAFR( MOFACE, MXFACE, LFACES, XYZSOM,
     %                   NBFISO, L1FAFR, NBFAFR, L1FA2M, NBFA2M,
     %                   NOFAFR, BARFAC )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE BARYCENTRE DE CHAQUE FACE FRONTALIERE
C -----             LE NUMERO DE LA FACE POUR LE TRI PAR TAS ULTERIEUR
C
C ENTREES:
C --------
C MOFACE : NOMBRE DE MOTS PAR FACE DU TABLEAU LFACES DES FACES
C MXFACE : NOMBRE DE FACES DU TABLEAU LFACES
C LFACES : TABLEAU NUMERO DES FACES, LIEN, NO DES CUBES
C          LFACES(1,I)= NO DU 1-ER  SOMMET DE LA FACE
C          LFACES(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LFACES(3,I)= NO DU 3-EME SOMMET DE LA FACE
C          LFACES(4,I)= NO DU 4-EME SOMMET DE LA FACE
C                      0 SI TRIANGLE
C          LFACES(5,I)= + ou - CHAINAGE HACHAGE SUR FACE SUIVANTE
C                      >0 FACE INTERNE
C                      <0 FACE FRONTALIERE
C          SI SOMMET 2 < DERNIER SOMMET  => FACE   DIRECTE
C                      <                 => FACE INDIRECTE
C          UNE FACE DIRECTE EST VUE DE L EXTERIEUR AU CUBE
C          SOUS LA FORME DIRECTE
C          LFACES(6,I)= NUMERO DU 1-ER  CUBE CONTENANT CETTE FACE
C                      >0 SI FACE   DIRECTE DANS CE CUBE
C                      <0 SI FACE INDIRECTE DANS CE CUBE
C          SI LA FACE APPARTIENT A 2 CUBES ALORS
C          LFACES(7,I)= NUMERO DU 2-EME CUBE CONTENANT CETTE FACE
C                      >0 SI FACE   DIRECTE DANS CE CUBE
C                      <0 SI FACE INDIRECTE DANS CE CUBE
C          SINON
C          LFACES(7,I)= NUMERO DE LA FACE FRONTALIERE SUIVANTE
C                       0 SI C'EST LA DERNIERE
C NBFISO : NOMBRE DE FACES ISOVALEURS
C L1FAFR : NUMERO DE LA PREMIERE FACE FRONTALIERE
C NBFAFR : NOMBRE DE FACES FRONTALIERES
C L1FA2M : NUMERO DE LA PREMIERE FACE INTERFACE
C NBFA2M : NOMBRE DE FACES INTERFACES
C
C SORTIES:
C --------
C ATTENTION : LES VALEURS CALCULEES ICI DEBUTENT EN POSITION NBFISO+1
C NOFAFR : NUMERO DE LA FACE FRONTALIERE DANS LFACES
C BARFAC : XYZ DU BARYCENTRE DES FACES
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR:PERRONNET ALAIN ANALYSE NUMERIQUE LJLL UPMC PARIS NOVEMBRE 2003
C AUTEUR : ALAIN PERRONNET LJLL UPMC et St Pierre du Perray     Mai 2008
C2345X7..............................................................012
      include"./incl/trvari.inc"
      INTEGER   LFACES(1:MOFACE,1:MXFACE)
      REAL      XYZSOM(1:3,1:*)
      INTEGER   NOFAFR(1:NBFAFR+NBFA2M)
      REAL      BARFAC(1:3,1:NBFAFR+NBFA2M),
     %          XYZ(3)
C
C     BOUCLE SUR LES FACES FRONTALIERES
      I = NBFISO
      N = L1FAFR
      LS = 7
C
 1    IF( N .NE. 0 ) THEN
C
C        LA FACE N DE LFACES EST TRAITEE
         I = I + 1
         NOFAFR(I) = NBFISO + N
C
C        LES COORDONNEES DU BARYCENTRE DE LA FACE N
         XYZ(1) = 0.0
         XYZ(2) = 0.0
         XYZ(3) = 0.0
         IF( LFACES(4,N) .EQ. 0 ) THEN
            NBS = 3
         ELSE
            NBS = 4
         ENDIF
         DO 20 J=1,NBS
C           LE NUMERO DU SOMMET
            NS = LFACES( J , N )
            DO 10 K=1,3
               XYZ(K) = XYZ(K) + XYZSOM(K,NS)
 10         CONTINUE
 20      CONTINUE
         BARFAC(1,I) = XYZ(1) / NBS
         BARFAC(2,I) = XYZ(2) / NBS
         BARFAC(3,I) = XYZ(3) / NBS
C
C        PASSAGE A LA FACE FRONTALIERE SUIVANTE
         N = LFACES(LS,N)
         GOTO 1
C
      ENDIF
      IF( LS .EQ. 7 .AND. NBFA2M . GT. 0 ) THEN
C        TRAITEMENT DES FACES INTERFACES ENTRE 2 MATERIAUX
         N  = L1FA2M
         LS = 8
         GOTO 1
      ENDIF
C
      RETURN
      END
