      SUBROUTINE BAST1TR4( COSMAXPL, QUALMN, NBSOM,  XYZSOM,
     %                     L1ARET,   L2ARET, MNARET,
     %                     N3, NTR,  M1TRIA, NBTRIA, NOTRIA,
     %                     MXTRPV,   NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV,
     %                     QUAMIN0,  QUAMIN1, MODIF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    BARYCENTRAGE DU SOMMET N3 du TRIANGLE NTR 
C -----    SI TOUS LES TRIANGLES DE CE SOMMET SONT COPLANAIRES et
C          SI LE MINIMUM DES QUALITES DES TRIANGLES EST AUGMENTEE
C          ESSAI D'ECHANGER LES DIAGONALES DES QUADRANGLES NTR+NTRADJ

C ENTREES:
C --------
C COSMAXPL:COSINUS DE L'ANGLE DIEDRE ENTRE LES 2 PLANS DES TRIANGLES AU
C          DESSOUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES NON-COPLANAIRES
C QUALMN : QUALITE AU DESSOUS DE LAQUELLE LA QUALITE D'UN TRIANGLE
C          EST A AMELIORER
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION
C XYZSOM : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU LARETE
C L2ARET : NOMBRE DE ARETES         DU TABLEAU LARETE
C MNARET : ADRESSE MCN DU TABLEAU LARETE DES ARETES DU MAILLAGE
C N3     : NUMERO DE 1 A 3 DU SOMMET DE NTR A BARYCENTRER
C NTR    : NUMERO NOTRIA DU TRIANGLE A TRAITER
C M1TRIA : NOMBRE D'ENTIERS DU PREMIER INDICE DU TABLEAU NOTRIA
C          =4 POUR STOCKER PAR TRIANGLE LE NO DE SES 3 SOMMETS + 0
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C MXTRPV : NOMBRE MAXIMAL DE NO DE TRIANGLES DU TABLEAU NOTRPV

C MODIFIES:
C ---------
C LARETE :=MCN(MNARET) TABLEAU DES ARETES DU MAILLAGE
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE
C NOTRIA : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES NBTRIA TRIANGLES

C SORTIES:
C --------
C NBTRPV : NOMBRE DE TRIANGLES DE SOMMET NS3=NOTRIA(N3,NTR)
C NBTRPVV: NOMBRE DE TRIANGLES DE NOTRPV INITIAUX + ADJACENTS
C NBTRPVVV:NOMBRE DE TRIANGLES DE NOTRPV INITIAUX + ADJACENTS + ADJACENTS
C NOTRPV : NUMERO NOTRIA DES TRIANGLES DE SOMMET NS3=NOTRIA(N3,NTR)
C QUAMIN0: QUALITE INITIALE MINIMALE DES NBTRPV TRIANGLES 
C QUAMIN1: QUALITE FINALE   MINIMALE DES NBTRPV TRIANGLES
C MODIF  : =0  SI PAS DE MODIFICATION DES XYZ DU SOMMET N3 DE NTR
C          =1  SI        MODIFICATION DES XYZ DU SOMMET N3 DE NTR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET  Saint Pierre du Perray              Mars 2020
C....................................................................012
      include"./incl/langue.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0
      REAL              XYZSOM(3,NBSOM), XYZ(3), XYZBAR(3)
      INTEGER           NOTRIA(M1TRIA,NBTRIA), NOTRPV(MXTRPV)

      TRACTE0 = TRACTE
      MODIF   = 0
C     MXTRAR  = L1ARET-3 NOMBRE MAXIMUM DE TRIANGLES ADJACENTS A UNE ARETE
      MXTRAR  = L1ARET - 3
      QUAMIN0 =-3
      QUAMIN1 =-3

      IF( N3  .LE. 0 .OR. N3 .GT. 3 ) GOTO 9999
      IF( NTR .LE. 0 .OR. NOTRIA(1,NTR) .EQ. 0 ) GOTO 9999

C     LE TRIANGLE NTR EST ACTIF
      NS3 = NOTRIA( N3, NTR )
      IF( N3 .EQ. 3 ) THEN
         N1 = 1
      ELSE
         N1 = N3+1
      ENDIF
      NS1 = NOTRIA( N1, NTR )

      IF( N1 .EQ. 3 ) THEN
         N2 = 1
      ELSE
         N2 = N1+1
      ENDIF
      NS2 = NOTRIA( N2, NTR )

C     INITIALISATION DE LA PILE DES COUPLES DE TRIANGLES ADJACENTS
      NBTRPV = 1
      NOTRPV( NBTRPV ) = NTR
 
C     RECHERCHE DU TRIANGLE ADJACENT A NTR PAR L'ARETE NS2 NS3
      CALL NUQTADAR( N2,    NTR, NOTRIA, L1ARET, L2ARET, MCN(MNARET),
     %               NAR23, NTRAD23 )
      IF( NTRAD23 .LE. 0 ) THEN
C        ARETE SANS ou TROP DE TRIANGLES ADJACENTS. PAS DE BARYCENTRAGE
         GOTO 9999
      ENDIF
      NBTRPV = NBTRPV + 1
      NOTRPV( NBTRPV ) = NTRAD23

C     RECHERCHE DU TRIANGLE AJACENT A NTR PAR L'ARETE NS3 NS1
      CALL NUQTADAR( N3,    NTR, NOTRIA, L1ARET, L2ARET, MCN(MNARET),
     %               NAR31, NTRAD31 )
      IF( NAR31 .LE. 0 ) THEN
C        ARETE SANS ou TROP DE TRIANGLES ADJACENTS. PAS DE BARYCENTRAGE
         GOTO 9999
      ENDIF
      NBTRPV = NBTRPV + 1
      NOTRPV( NBTRPV ) = NTRAD31

C     BOUCLE SUR LES TRIANGLES DE SOMMET NS3
      DO 30 N = 2, NBTRPV

C        LE N-EME TRIANGLE DE SOMMET NS3
         NTRNS3 = NOTRPV( N )

C        RECHERCHE DES ARETES DE SOMMET NS3
         DO NA=1,3
            NST = NOTRIA( NA, NTRNS3 )
            IF( NST .EQ. NS3 ) GOTO 10
         ENDDO

C        LE TRIANGLE ADJACENT NTRAD A L'ARETE NA DE NTRNS3 ET NTRNS3
C        SONT ILS COPLANAIRES?
 10      CALL TRCOPL( COSMAXPL, XYZSOM, NA, NTRNS3, 4, NOTRIA,
     %                L1ARET,   L2ARET, MCN(MNARET), NTRAD )
         IF( NTRAD .GT. 0 ) THEN
C           OUI: NTRAD EST IL DEJA TRAITE?
            DO K=1,NBTRPV
               IF( NTRAD .EQ. NOTRPV(K) ) GOTO 20
            ENDDO
            IF( NBTRPV .GE. MXTRPV ) THEN
               PRINT*,'bast1tr4: AUGMENTER MXTRPV=',MXTRPV
               GOTO 9999
            ENDIF
            NBTRPV = NBTRPV + 1
            NOTRPV( NBTRPV ) = NTRAD
         ELSE
C           LES TRIANGLES NTRNS3 et NTRAD NE SONT PAS COPLANAIRES
            GOTO 9999
         ENDIF

C        L'ARETE PRECEDENTE DE NA DE SOMMET NS3
 20      IF( NA .EQ. 1 ) THEN
            N1 = 3
         ELSE
            N1 = NA-1
         ENDIF

C        LE TRIANGLE ADJACENT NTRAD A L'ARETE N1 DE NTRNS3 ET NTRNS3
C        SONT ILS COPLANAIRES?
         CALL TRCOPL( COSMAXPL, XYZSOM, N1, NTRNS3, 4, NOTRIA,
     %                L1ARET,   L2ARET, MCN(MNARET), NTRAD )
         IF( NTRAD .GT. 0 ) THEN
C           OUI: NTRAD EST IL DEJA TRAITE?
            DO K=1,NBTRPV
               IF( NTRAD .EQ. NOTRPV(K) ) GOTO 30
            ENDDO
            IF( NBTRPV .GE. MXTRPV ) THEN
               PRINT*,'bast1tr4: AUGMENTER MXTRPV=',MXTRPV
               GOTO 9999
            ENDIF
            NBTRPV = NBTRPV + 1
            NOTRPV( NBTRPV ) = NTRAD
         ELSE
C           LES TRIANGLES NTRNS3 et NTRAD NE SONT PAS COPLANAIRES
            GOTO 9999
         ENDIF

 30   ENDDO

C     CALCUL DES QUALITES MOYENNE ET MINIMALE DU GROUPE DES
C     NBTRPV TRIANGLES DU TABLEAU NOTRIA
      CALL QUMYMITR( NBTRPV, NOTRPV, M1TRIA,  NOTRIA,  XYZSOM,
     %               QUALMN, NBTRQI, QUAMOY0, QUAMIN0, NTRMIN0 )

ccc      PRINT*,'bast1tr4 0: Les',NBTRPV,' TRIANGLES ont une QUALITE MOYENN
ccc     %E=',QUAMOY0,' MINIMALE=',QUAMIN0

C     ICI NBTRPV TRIANGLES DE SOMMET NS3 SONT COPLANAIRES
C     TRACE DES TRIANGLES NTR DE SOMMET NS3
      CALL TRTRIAR( 'bast1tr4 0', XYZSOM,
     %               MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %               MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )

C     BARYCENTRAGE DU SOMMET NS3
C     CALCUL DU BARYCENTRE DES NBTRPV TRIANGLES (DONT NTR)
      DO K=1,3
         XYZBAR(K) = 0D0
      ENDDO

      NBS = 0
      DO NT=1,NBTRPV
         NTRIA = NOTRPV( NT )
         DO I=1,3
            NS2 = NOTRIA( I, NTRIA )
            IF( NS2 .NE. NS3 ) THEN
               NBS = NBS + 1
               DO K=1,3
                  XYZBAR(K) = XYZBAR(K) + XYZSOM(K,NS2)
               ENDDO
            ENDIF
         ENDDO
      ENDDO

C     LE SOMMET NS3 EST DEPLACE AU BARYCENTRE DES NBTRPV TRIANGLES
C     AVEC SAUVEGARDE DANS XYZ DE SES COORDONNEES
      DO K=1,3
         XYZ(K )       = XYZSOM(K,NS3)
C        PONDERATION ( 1/4 ANCIEN + 3/4 NOUVEAU ) DU DEPLACEMENT
         XYZSOM(K,NS3) = XYZSOM(K,NS3)*0.25 + (XYZBAR(K)/NBS) * 0.75
      ENDDO

C     CALCUL DES QUALITES MOYENNE ET MINIMALE DU GROUPE DES
C     NBTRPV TRIANGLES DU TABLEAU NOTRIA
      CALL QUMYMITR( NBTRPV, NOTRPV, M1TRIA,  NOTRIA,  XYZSOM,
     %               QUALMN, NBTRQI, QUAMOY1, QUAMIN1, NTRMIN1 )

      IF( QUAMIN0 .GT. QUAMIN1 ) THEN
 
C        PERTE DE QUALITE MINIMUM => RETOUR AUX XYZ INITIAUX DE NS3
C        ----------------------------------------------------------
         MODIF = 0
         DO K=1,3
            XYZSOM(K,NS3) = XYZ(K)
         ENDDO
         QUAMOY1 = QUAMOY0
         QUAMIN1 = QUAMIN0

ccc      PRINT*,'bast1tr4 1: Le SOMMET',NS3,
ccc     %       ' N''EST PAS DEPLACE au BARYCENTRE de',NBTRPV,' TRIANGLES'
ccc      PRINT*,'bast1tr4 1: Les',NBTRPV,
ccc     %       ' TRIANGLES ont une QUALITE MOYENNE=',QUAMOY1,
ccc     %       ' MINIMALE=',QUAMIN1

         GOTO 9999

      ENDIF

C     BARYCENTRAGE DE NS3 AVEC UN GAIN EN QUALITE MINIMUM
C     ---------------------------------------------------
      MODIF = 1

ccc      PRINT*,'bast1tr4 1: Le SOMMET',NS3,
ccc     %       ' EST DEPLACE au BARYCENTRE des',NBTRPV,' TRIANGLES',
ccc     %       (NOTRPV(K),K=1,NBTRPV)
ccc      PRINT*,'bast1tr4 1: Les',NBTRPV,
ccc     %       ' TRIANGLES ont une QUALITE MOYENNE=',QUAMOY1,
ccc     %       ' MINIMALE=',QUAMIN1

cccC     SI POSSIBLE ECHANGER L'ARETE COMMUNE A 2 TRIANGLES PAR L'AUTRE
cccC     DIAGONALE SI L'ANGLE DU DIEDRE EST INFERIEUR A ANGL2P POUR
cccC     TOUTES LES ARETES DU GROUPE DE TRIANGLES DEFINI PAR NOTRPV
cccC     --------------------------------------------------------------
ccc      CALL EC2DGTR( COSMAXPL, XYZSOM, M1TRIA, NOTRIA,
ccc     %              MXTRPV,   NBTRPV, NOTRPV,
ccc     %              L1ARET,   L2ARET, MNARET, NBDIAG )

C     TRACE DES TRIANGLES DE SOMMET NS3
      CALL TRTRIAR( 'bast1tr4 F', XYZSOM,
     %               MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %               MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )

 9999 TRACTE = TRACTE0
      RETURN
      END
