      SUBROUTINE BASTTTR4( COSMAXPL, QUALMN, NBSOM,  XYZSOM,
     %                     MXTRAR,   L1ARET, L2ARET, MNARET,
     %                     M1TRIA,   NBTRIA, NOTRIA, MXTRPV, NOTRPV,
     %                     MODIFS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    BARYCENTRAGE DE TOUS LES SOMMETS DES NBTRIA TRIANGLES
C -----    SI TOUS LES TRIANGLES DE CE SOMMET SONT COPLANAIRES et
C          SI LE MINIMUM DES QUALITES DES TRIANGLES EST AUGMENTEE

C ENTREES:
C --------
C COSMAXPL:COSINUS DE L'ANGLE DIEDRE ENTRE LES 2 PLANS DES TRIANGLES AU
C          DESSOUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES NON-COPLANAIRES
C QUALMN : QUALITE AU DESSOUS DE LAQUELLE LA QUALITE D'UN TRIANGLE
C          EST A AMELIORER
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION
C XYZSOM : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C MXTRAR : NOMBRE MAXIMUM DE TRIANGLES ADJACENTS A UNE ARETE
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU LARETE
C L2ARET : NOMBRE DE ARETES         DU TABLEAU LARETE
C MNARET : ADRESSE MCN DU TABLEAU LARETE DES ARETES DU MAILLAGE
C N3     : NUMERO DE 1 A 3 DU SOMMET DE NTR A BARYCENTRER
C NTR    : NUMERO NOTRIA DU TRIANGLE A TRAITER
C M1TRIA : NOMBRE D'ENTIERS DU PREMIER INDICE DU TABLEAU NOTRIA
C          =4 POUR STOCKER PAR TRIANGLE LE NO DE SES 3 SOMMETS + 0
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C MXTRPV : NOMBRE MAXIMAL DE NO DE TRIANGLES DU TABLEAU NOTRPV

C MODIFIES:
C ---------
C LARETE : =MCN(MNARET) TABLEAU DES ARETES DU MAILLAGE
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE
C NOTRIA : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES NBTRIA TRIANGLES
C NOTRPV : NUMERO NOTRIA DE TRIANGLES (TABLEAU AUXILIAIRE)

C SORTIES:
C --------

C MODIFS : NOMBRE DE MODIFICATIONS DES XYZ DES SOMMETS DES TRIANGLES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET  Saint Pierre du Perray             Avril 2020
C....................................................................012
      REAL        XYZSOM(3,NBSOM)
      INTEGER     NOTRIA(M1TRIA,NBTRIA), NOTRPV(MXTRPV)

C     CONSTRUCTION DU TABLEAU LARETE DES ARETES DU MAILLAGE A PARTIR DE NOTRIA
C     ------------------------------------------------------------------------
C     EVENTUELLE DESTRUCTION DU TABLEAU DES ARETES DU MAILLAGE
      IF( MNARET .GT. 0 ) CALL TNMCDS( 'ENTIER', L1ARET*L2ARET, MNARET )

C     CONSTRUCTION DU TABLEAU DES ARETES DE LA TRIANGULATION
      CALL GEARSU( 4,      NBTRIA, NOTRIA, MXTRAR,
     %             L1ARET, L2ARET, MNARET, IERR )
C     ARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C     ARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C     ARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C     ARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                 0 SI PAS DE 1-ER  TRIANGLE
C     ARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                 0 SI PAS DE 2-EME TRIANGLE
C     ARETE(3+MXTRAR,I)= NO DU MXTRAR-EME TRIANGLE CONTENANT CETTE ARETE
C                        0 SI PAS DE MXTRAR-EME TRIANGLE

C     BARYCENTRAGE DES SOMMETS DES NBTRIA TRIANGLES
      MODIFS = 0
      DO NTR = 1, NBTRIA
         IF( NOTRIA(1,NTR) .GT. 0 ) THEN
            DO N=1,3
               NS3 = NOTRIA( N, NTR ) 
               CALL BAST1TR4( COSMAXPL,QUALMN, NBSOM, XYZSOM,
     %                        L1ARET, L2ARET, MNARET,
     %                        N, NTR, M1TRIA, NBTRIA, NOTRIA,
     %                        MXTRPV, NBTRPV, NBTRPVV,NBTRPVVV, NOTRPV,
     %                        QUAMIN0,QUAMIN1, MODIF )
               MODIFS = MODIFS + MODIF
            ENDDO
         ENDIF
      ENDDO

      RETURN
      END
