      SUBROUTINE BASTTETR( NBITERBA, NBSOMM, PTXYZD, NPSOFR,
     %                     MXTETR,   NOTETR, N1TETS, MXTE1S, NOTE1S )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    BARYCENTRAGE DES SOMMETS INTERNES D'UNE TETRAEDRISATION
C -----    EXCEPTES LES SOMMETS DE NPSOFR NON NUL ET SEULEMENT
C          SI LA QUALITE MINIMALE EST MAXIMISEE

C ENTREES:
C --------
C NBITERBA:NOMBRE D'ITERATIONS DE BARYCENTRAGE DEMANDE
C NBSOMM : NOMBRE DE SOMMETS PTXYZD DE LA TETRAEDRISATION
C NPSOFR : =  0 SI LE POINT AJOUTE N'EST PAS SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C              LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE PT OU FACE
C          = -1 SI LE POINT EST SOMMET D'OT TROP PROCHE PT OU FACE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT DEPLACE SUR LA SURFACE
C             DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE
C MXTETR : NOMBRE D'EF DU MAILLAGE
C NOTETR : NUMERO DE 1 A NBSOMM DES SOMMETS DES TETRAEDRES
C           ou =0 SI PAS DE SOMMET
C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C MXTE1S : NOMBRE MAXIMAL D'ENTIERS DU TABLEAU NOTE1S
C NOTE1S : TABLEAU AUXILIAIRE DES NO DE TETRAEDRES D'UN SOMMET

C MODIFIE:
C --------
C PTXYZD: EN ENTREE XYZD DES NBSOMM SOMMETS      DE LA TETRAEDRISATION
C         EN SORTIE XYZD DES SOMMETS BARYCENTRES DE LA TETRAEDRISATION
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN  Veulettes sur mer              Decembre 2019
C23456...............................................................012
      PARAMETER       (QUAMED=0.005, MXSTBA=256)
      INTEGER          NPSOFR(NBSOMM), NOTETR(8,MXTETR), NOTE1S(MXTE1S),
     %                 N1TETS(NBSOMM), NOSTBA(MXSTBA)
      DOUBLE PRECISION PTXYZD(4,NBSOMM), XYZDBAR(4), XYZD0(4)

      QUAMITER = -2
      DO NOITER = 1, NBITERBA

         QUAMINT = 2
         NBBAR   = 0

         DO 20 NST = 1, NBSOMM

            IF( N1TETS( NST ) .LE. 0 ) GOTO 20

C           NST APPARTIENT A AU MOINS UN TETRAEDRE
            IF( NPSOFR(NST).LT.-4  .OR.  NPSOFR(NST).GT.0 ) GOTO 20

C           NST N'EST PAS SUR LA FRONTIERE
C           NST EST UN SOMMET INTERNE DEPLACE AU BARYCENTRE DE SES VOISINS
            XYZDBAR( 1 ) = 0D0
            XYZDBAR( 2 ) = 0D0
            XYZDBAR( 3 ) = 0D0
            XYZDBAR( 4 ) = 0D0
            NBSTBA = 0

C           RECHERCHE DES TETRAEDRES DE SOMMET NST
            CALL TETR1S( NST,    N1TETS, NOTETR,
     %                   NBTE1S, MXTE1S, NOTE1S, IERR )
            IF( IERR .NE. 0 ) GOTO 20

C           CALCUL DE LA QUALITE MINIMALE DES NBTE1S TETRAEDRES
            CALL QUVOTETD( QUAMED,   PTXYZD,  NBTE1S, NOTE1S, NOTETR,
     %                     QUAMINS0, QUAMOY0, NBTEQM )

C           RECHERCHE DES SOMMETS DES NBTE1S TETRAEDRES DE SOMMET NST
            DO N = 1, NBTE1S

C              NO NOTETR DU TETRAEDRE N DE SOMMET NST
               NTE = NOTE1S( N )

               DO 10 I=1,4
                  NSTI = NOTETR( I, NTE )
                  DO M=1, NBSTBA
                     IF( NSTI .EQ. NST .OR. NSTI .EQ. NOSTBA(M) )GOTO 10
                  ENDDO
                  IF( NBSTBA .GE. MXSTBA ) GOTO 20
                  NBSTBA = NBSTBA + 1
                  NOSTBA( NBSTBA ) = NSTI
 10            ENDDO

C              PASSAGE AU TETRAEDRE SUIVANT DE SOMMET NST
            ENDDO

            DO I = 1, NBSTBA

C              NUMERO DU SOMMET I
               NSTI = NOSTBA( I )

C              AJOUT AU BARYCENTRE DES COORDONNEES DU SOMMET NSTI
C              (NON COMPRIS LE SOMMET NST LUI-MEME)
               DO K=1,4
                  XYZDBAR(K) = XYZDBAR(K) + PTXYZD( K, NSTI )
               ENDDO

            ENDDO

C           NST EST PLACE AU BARYCENTRE DE SES VOISINS
            DO K=1,4
               XYZD0( K ) = PTXYZD( K, NST )
               PTXYZD( K, NST ) = XYZDBAR( K ) / NBSTBA
            ENDDO

C           CALCUL DE LA QUALITE MINIMALE DES NBTE1S TETRAEDRES
            CALL QUVOTETD( QUAMED,   PTXYZD,  NBTE1S, NOTE1S, NOTETR,
     %                     QUAMINS1, QUAMOY1, NBTEQM )

            IF( QUAMINS0 .GT. QUAMINS1 ) THEN
C              RETOUR AU XYZD(NST) INITIALES
               DO K=1,4
                  PTXYZD( K, NST ) = XYZD0( K )
               ENDDO
               QUAMINT = MIN( QUAMINT, QUAMINS0 )
            ELSE
C              NOMBRE DE SOMMETS BARYCENTRES
               NBBAR = NBBAR + 1
               QUAMINT = MIN( QUAMINT, QUAMINS1 )
            ENDIF

 20      ENDDO

        IF( NBBAR .EQ. 0 ) GOTO 9999

         PRINT*,'basttetr: ITERATION',NOITER,' BARYCENTRAGE de',NBBAR,
     %' SOMMETS INTERNES. Qualite MINIMALE rencontree durant l''ITERATIO
     %N=',QUAMINT

         IF( QUAMINT .LE. QUAMITER ) THEN
C           LA QUALITE SE DETERIORE OU STAGNE
            GOTO 9999
         ENDIF

C        LA QUALITE MIN DE L'ITERATION
         QUAMITER = QUAMINT

      ENDDO

 9999 RETURN
      END
