      SUBROUTINE BATRGRAN( COSMAXPL, MXSOMM, NBSOMM, XYZSOM,
     %                     MXTRIA,   NBTRIA, NOTRIA, SFMOYTR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUT DU BARYCENTRE DES TRIANGLES DE SURFACE SUPERIEURE A
C -----    3 FOIS LA SURFACE MOYENNE SI TAILLE_IDEALE N'EST PAS FOURNIE

C ENTREES:
C --------
C COSMAXPL:COSINUS DE L'ANGLE DIEDRE ENTRE LES 2 PLANS DES TRIANGLES
C          AU DESSOUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES NON-COPLANAIRES
C MXSOMM : NOMBRE MAXIMUM DE SOMMETS   DU TABLEAU XYZSOM
C MXTRIA : NOMBRE MAXIMUM DE TRIANGLES DU TABLEAU NOTRIA

C MODIFIES:
C ---------
C NBSOMM : NOMBRE DE SOMMETS DE LA TRIANGULATION
C XYZSOM : XYZ DES NBSOMM SOMMETS DE LA TRIANGULATION
C NBTRIA : NOMBRE DE TRIANGLES DU TABLEAU NOTRIA
C NOTRIA : NUMERO DE 1 A NBSOMM DES SOMMETS DES TRIANGLES DE LA TRIANGULATION
C          1 2 3 LE NO XYZSOM DES 3 SOMMETS DU TRIANGLE
C          4 5 6 LE NO DU TRIANGLE ADJACENT PAR L'ARETE 1 2 3
C SFMOYTR: SURFACE MOYENNE DES NBTRIA TRIANGLES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN  Saint Pierre du Perray             Mars 2020
C23456...............................................................012
      PARAMETER       ( MXTRAJ=256 )
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      INTEGER  NOTRIA(6,MXTRIA), NOTRAJ(MXTRAJ)
      REAL     XYZSOM(3,MXSOMM), XYZBAR(3), SFMOYTR

      TRACTE0 = TRACTE

C     SI FONCTION 'TAILLE_IDEALE' ou 'EDGE_LENGTH'  EXISTE  ->  SORTIE
      NOFOTI = NOFOPIEX()
      IF( NOFOTI .NE. 0 ) GOTO 9999

C     CALCUL DE LA SURFACE MOYENNE DES TRIANGLES
      SFMOYTR = 0.
      NBTR    = 0
      DO 10 NTR = 1, NBTRIA
C        NOMBRE DE TRIANGLES DE SOMMET NST
         IF( NOTRIA( 1, NTR ) .LE. 0 ) GOTO 10
C        SURFACE DU TRIANGLE NTR
         STR = SURTRR( XYZSOM( 1, NOTRIA(1,NTR) ),
     %                 XYZSOM( 1, NOTRIA(2,NTR) ),
     %                 XYZSOM( 1, NOTRIA(3,NTR) ) )
         NBTR = NBTR + 1
         SFMOYTR = SFMOYTR + STR
 10   ENDDO
      SFMOYTR = SFMOYTR / NBTR
      PRINT*,'batrgran: SURFACE MOYENNE des',NBTR,' TRIANGLES=',SFMOYTR

C     NOMBRE DE BARYCENTRES AJOUTES
      NBAJBA = 0
      NB2DIA = 0

      NBTRIA0 = NBTRIA
      DO 100 NTR = 1, NBTRIA0

C        NOMBRE DE TRIANGLES DE SOMMET NST
         IF( NOTRIA( 1, NTR ) .LE. 0 ) GOTO 100

C        SURFACE DU TRIANGLE NTR
         STR = SURTRR( XYZSOM( 1, NOTRIA(1,NTR) ),
     %                 XYZSOM( 1, NOTRIA(2,NTR) ),
     %                 XYZSOM( 1, NOTRIA(3,NTR) ) )

         IF( STR .LT. 3 * SFMOYTR ) GOTO 100

         IF( NBSOMM   .GE. MXSOMM ) GOTO 9999
         IF( NBTRIA+2 .GT. MXTRIA ) GOTO 9999

C        NTR LE TRIANGLE DE PLUS PETITE ARETE ou GRANDE AIRE
C        EST DECOUPE EN 3 SOUS-TRIANGLES A PARTIR DE SON BARYCENTRE
         DO K=1,3
            XYZBAR( K ) = 0.
         ENDDO
         DO K=1,3
            NS = NOTRIA( K, NTR )
            DO I=1,3
               XYZBAR(I) = XYZBAR(I) + XYZSOM(I,NS)
            ENDDO
         ENDDO

C        AJOUT DU BARYCENTRE DU TRIANGLE NTR
         NBAJBA = NBAJBA + 1
         NBSOMM = NBSOMM + 1

         DO K=1,3
            XYZSOM( K, NBSOMM ) = XYZBAR( K ) / 3
         ENDDO

C        LES 3 SOMMETS DE NTR
         NS1 = NOTRIA( 1, NTR )
         NS2 = NOTRIA( 2, NTR )
         NS3 = NOTRIA( 3, NTR )

C        LES 3 TRIANGLES ADJACENTS DE NTR PAR LES ARETES
         NTR1AD = NOTRIA( 4, NTR )
         NTR2AD = NOTRIA( 5, NTR )
         NTR3AD = NOTRIA( 6, NTR )

C        DECOUPAGE EN 3 SOUS-TRIANGLES DU TRIANGLE NTR
         NTR1 = NTR
C        LES 2 TRIANGLES CREES DE SOMMET NBSOMM
         NTR2 = NBTRIA + 1
         NTR3 = NBTRIA + 2
         NBTRIA = NTR3

C        CONSTRUCTION DU TRIANGLE NTR1: NS1-NS2-NBSOMM
         NOTRIA( 1, NTR1 ) = NS1
         NOTRIA( 2, NTR1 ) = NS2
         NOTRIA( 3, NTR1 ) = NBSOMM

C        LES TRIANGLES ADJACENTS DE NTR1
         NOTRIA( 4, NTR1 ) = NTR1AD
         IF( NTR1AD .GT. 0 .AND. NOTRIA(1,NTR1AD) .GT. 0 ) THEN
            CALL NUAR2STR( NS1, NS2, NOTRIA(1,NTR1AD), NATA )
            NOTRIA( 3+NATA, NTR1AD ) = NTR1
         ENDIF
         NOTRIA( 5, NTR1 ) = NTR2
         NOTRIA( 6, NTR1 ) = NTR3

C        CONSTRUCTION DU TRIANGLE NTR2: NS2-NS3-NBSOMM
         NOTRIA( 1, NTR2 ) = NS2
         NOTRIA( 2, NTR2 ) = NS3
         NOTRIA( 3, NTR2 ) = NBSOMM

C        LES TRIANGLES ADJACENTS DE NTR2
         NOTRIA( 4, NTR2 ) = NTR2AD
         IF( NTR2AD .GT. 0 .AND. NOTRIA(1,NTR2AD) .GT. 0 ) THEN
            CALL NUAR2STR( NS2, NS3, NOTRIA(1,NTR2AD), NATA )
            NOTRIA( 3+NATA, NTR2AD ) = NTR2
         ENDIF
         NOTRIA( 5, NTR2 ) = NTR3
         NOTRIA( 6, NTR2 ) = NTR1

C        CONSTRUCTION DU TRIANGLE NTR3: NS3-NS1-NBSOMM
         NOTRIA( 1, NTR3 ) = NS3
         NOTRIA( 2, NTR3 ) = NS1
         NOTRIA( 3, NTR3 ) = NBSOMM

C        LES TRIANGLES ADJACENTS DE NTR3
         NOTRIA( 4, NTR3 ) = NTR3AD
         IF( NTR3AD .GT. 0 .AND. NOTRIA(1,NTR3AD) .GT. 0 ) THEN
            CALL NUAR2STR( NS3, NS1, NOTRIA(1,NTR3AD), NATA )
            NOTRIA( 3+NATA, NTR3AD ) = NTR3
         ENDIF
         NOTRIA( 5, NTR3 ) = NTR1
         NOTRIA( 6, NTR3 ) = NTR2

C        TENTATIVE D'ECHANGE DES DIAGONALES DES ARETES D'ADJACENCE
C        DES TRIANGLES DE SOMMET NSt + NBSOMM
         NBTRAJ = 3
         NOTRAJ( 1 ) = NTR1
         NOTRAJ( 2 ) = NTR2
         NOTRAJ( 3 ) = NTR3

         DO N = 1, NBTRAJ
            NT = NOTRAJ( N )
            DO K = 1, 3
              CALL EC2DIA(COSMAXPL, NT, K, NOTRIA, NBSOM, XYZSOM, NT0)
              IF( NT0 .GT. 0 ) THEN
                 NB2DIA = NB2DIA + 1
              ENDIF
            ENDDO
         ENDDO

C        TRACE DES TRIANGLES NOTRAJ(1:NBTNEW) DE NOTRIA, LEURS VOISINS et
C        LEURS VOISINS DE VOISINS POUR VOIR LEUR ENVIRONNEMENT
ccc         tracte = .true.
         CALL TRTRIAN( 'batrgran 1', XYZSOM, 6, MXTRAJ, NBTRAJ, NOTRAJ,
     %                  NOTRIA )
ccc         tracte = tracte0

 100  ENDDO

      PRINT*,'batrgran:',NBAJBA,' BARYCENTRES AJOUTES DANS LES GRANDS TR
     %IANGLES. NBTRIA=',NBTRIA,' NBSOMM=',NBSOMM,' NB2DIA=',NB2DIA

 9999 TRACTE = TRACTE0
      RETURN
      END
