      SUBROUTINE CH3F3F( N1ARCF, NOARCF, NOSTC,  NOTRCF0,
ccc     %                   PTXYZD,
     %                   MXFACO, LEFACO, N1FASC,  NOTRCF1, NONOUI )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ECHANGE DU PENTAGONE FORME PAR 3 TRIANGLES LEFACO
C -----    AVEC 3 NOUVEAUX TRIANGLES LEFACO SI LE PENTAGONE RESTE CONVEXE
C
C ENTREES:
C --------
C N1ARCF : NUMERO DANS NOARCF DE LA PREMIERE ARETE DU CF
C NOARCF : NO SOMMET, NO SUIVANT DANS NOARCF, NO FACE LEFACO OPPOSEE
C NOTRCF0: NUMERO LEFACO DES 3 FACES PERDUES
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C
C MODIFIES:
C ---------
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO
C LEFACO : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES
C N1FASC : N1FASC(NS) = NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS
C
C SORTIES:
C --------
C NOTRCF1: NUMERO LEFACO DES 3 FACES GENEREES, 0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 2005
C....................................................................012
      include"./incl/trvari.inc"
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
ccc      DOUBLE PRECISION  PTXYZD(1:4,1:*)
      INTEGER           LEFACO(11,0:MXFACO),
     %                  N1FASC(*)
      INTEGER           NOTRCF0(3), NOTRCF1(3), NOARCF(3,*)
C
      NONOUI = 0
C
C     LE PREMIER TRIANGLE DU CF
      NF0 = NOTRCF0(1)
C     LES VOLUMES DE LA FACE NF0
      NV1 = LEFACO(4,NF0)
      NV2 = LEFACO(5,NF0)
C
      DO 5 N = 2, 3
C        VERIFICATION DES VOLUMES ET NO DE FACEOC
         NF1 = NOTRCF0( N )
         NW1 = LEFACO(4,NF1)
         NW2 = LEFACO(5,NF1)
         IF( (NV1 .NE. NW1 .AND. NV1 .NE. NW2) .OR.
     %       (NV2 .NE. NW1 .AND. NV2 .NE. NW2) ) RETURN
 5    CONTINUE
C
C     NO DANS NOARCF DU SOMMET NOSTC
C     PARCOURS DES 5 ARETES DU PENTAGONE
      NA0 = N1ARCF
      DO 10 N=1,5
         IF( NOSTC .EQ. NOARCF(1,NA0) ) GOTO 15
         NA0 = NOARCF(2,NA0)
 10   CONTINUE
C
C     LE PREMIER TRIANGLE DU CF
 15   NF0 = NOTRCF0(1)
C
C     SUPPRESSION DES 3 TRIANGLES PERDUS DE LEFACO
      DO 30 N=1,3
CCC
CCCC     TRACE DE LA FACE INITIALE DE LEFACO
CCC      CALL TRFATR( NCBLAN, NCVERT, LEFACO(1,NOTRCF0(I)), PTXYZD )
C
C        DESTRUCTION DE LA FACE INITIALE DE LEFACO
         CALL VDDSFA( NOTRCF0(N), MXFACO, LEFACO, NBFACO, N1FASC )
 30   CONTINUE
C
C     AJOUT DANS LEFACO DU TRIANGLE NA0 NA0+1 NA0+2
      NA1 = NA0
C
C     LES 3 ARETES ET LES 3 SOMMETS DU NOUVEAU TRIANGLE 1 DE LEFACO
      NS1 = NOARCF(1,NA1)
C     L'ARETE SUIVANTE
      NA2 = NOARCF(2,NA1)
      NS2 = NOARCF(1,NA2)
C     L'ARETE SUIVANTE
      NA3 = NOARCF(2,NA2)
      NS3 = NOARCF(1,NA3)
C
C     AJOUT DE LA FACE NOTRCF1(1)  DANS LEFACO
      CALL VDAJFA( NS1,NS2,NS3,  NV1,NV2,
     %             NOARCF(3,NA1),NOARCF(3,NA2),-1,
     %             MXFACO, LEFACO, NBFACO, N1FASC, NOTRCF1(1) )
C
C     LES 3 ARETES ET LES 3 SOMMETS DU NOUVEAU TRIANGLE 2 DE LEFACO
C     L'ARETE SUIVANTE
      NA4 = NOARCF(2,NA3)
      NS4 = NOARCF(1,NA4)
C
C     AJOUT DE LA FACE NOTRCF1(2)  DANS LEFACO
      CALL VDAJFA( NS1,NS3,NS4,  NV1,NV2,
     %             NOTRCF1(1),NOARCF(3,NA3),-1,
     %             MXFACO, LEFACO, NBFACO, N1FASC, NOTRCF1(2) )
C
C     MISE A JOUR DE NOTRCF(1) DANS LA FACE NOTRCF1(2) DE LEFACO
      DO 70 N=6,8
         IF( LEFACO(N,NOTRCF1(1)) .EQ. -1 ) THEN
            LEFACO(N,NOTRCF1(1)) = NOTRCF1(2)
            GOTO 75
         ENDIF
 70   CONTINUE
C
C     LES 3 ARETES ET LES 3 SOMMETS DU NOUVEAU TRIANGLE 3 DE LEFACO
C     L'ARETE SUIVANTE
 75   NA5 = NOARCF(2,NA4)
      NS5 = NOARCF(1,NA5)
C
C     AJOUT DE LA FACE NOTRCF1(3)  DANS LEFACO
      CALL VDAJFA( NS1,NS4,NS5, NV1,NV2,
     %             NOTRCF1(2),NOARCF(3,NA4),NOARCF(3,NA5),
     %             MXFACO, LEFACO, NBFACO, N1FASC, NOTRCF1(3) )
C
C     MISE A JOUR DE NOTRCF(2) DANS LA FACE NOTRCF1(3) DE LEFACO
      DO 80 N=6,8
         IF( LEFACO(N,NOTRCF1(2)) .EQ. -1 ) THEN
            LEFACO(N,NOTRCF1(2)) = NOTRCF1(3)
            GOTO 85
         ENDIF
 80   CONTINUE
C
CCC      DO 90 N=1,3
CCCC     TRACE DE LA FACE FINALE DE LEFACO
CCC      CALL TRFATR( NCMAGE, NCBLEU, LEFACO(1,NOTRCF1(N)), PTXYZD )
CCC 90   CONTINUE
C
 85   NONOUI = 1
      RETURN
      END
