      SUBROUTINE CH3T2T( INFACO, MXFACO, LEFACO, MXQUAL, IVOLTE, NVOLTE,
     %                   NTE,    NAR,    PTXYZD,
     %                   N1TETS, NOTETR, N1TEVI, NUDTETR,
     %                   NTEOLD, NTENEW, Q5TE,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    EVENTUEL CHANGEMENT DE 3 TETRAEDRES AYANT UNE ARETE COMMUNE
C -----    EN 2 TETRAEDRES => L'ARETE NAR EST ECHANGEE EN UNE FACE

C ENTREES:
C --------
C INFACO : =1 PAS DE 3T->2T SI L'UNE DES 3 FACES QUI DISPARAITRAIENT
C             DANS 3T->2T EST DANS LEFACO
C          =0 SI PAS DE CONTROLE SUR LA FACE COMMUNE ET SON APPARTENANCE
C             A LEFACO
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES D'OC

C MXQUAL :  0 CHANGEMENT 3T -> 2T SI VOLUMES 3T et 2T EGAUX seulement
C           1 SI VOLUMES 3T et 2T EGAUX et CHANGEMENT SI et SEULEMENT SI
C             MIN( QUALITE 3T INITIAUX ) < MIN( QUALITE DES 2T )

C IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL
C          1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C NVOLTE : NUMERO DU VOLUME (1 A NBVOPA) DE CHAQUE TETRAEDRE
C          -1 SI VOLUME INCONNU

C NTE    : NUMERO NOTETR DU PREMIER TETRAEDRE
C NAR    : NUMERO DE 1 A 6 DE L'ARETE COMMUNE DES 3 TETRAEDRES DANS NTE
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS

C MODIFIES:
C ---------
C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C N1TEVI : NUMERO DU 1 PREMIER TETRAEDRE VIDE DANS LE TABLEAU NOTETR
C          LE CHAINAGE DES TETRAEDRES VIDES SE FAIT SUR NOTETR(5,.)
C NUDTETR: PLUS GRAND NUMERO DANS NOTETR DE TETRAEDRE OCCUPE

C SORTIES:
C --------
C NTEOLD : NUMERO NOTETR DES 3 TETRAEDRES QUI SONT REMPLACES
C NTENEW : NUMERO NOTETR DES 2 TETRAEDRES QUI REMPLACENT NTEOLD
C Q5TE   : QUALITE 1:3 DES 3T et 4:5 DES 2T SI MXQUAL=1 et IERR=0
C IERR   : 0 SI PAS D'ERREUR ET 3T -> 2T REALISE
C          1 SI PAS 3 ET SEULEMENT 3 TETRAEDRES D'ARETE COMMUNE NAR
C            => PAS DE TRANSFORMATION 3T=>2T
C          2 SI SATURATION DU TABLEAU NOTETR
C            => PAS DE TRANSFORMATION 3T=>2T
C          3 SI LE VOLUME 2T et 3T SONT DIFFERENTS
C            OU SI UN DES 3 TETRAEDRES EST DE VOLUME NUL OU NEGATIF
C            => PAS DE TRANSFORMATION 3T=>2T
C          4 SI MIN( QUALITE 3T INITIAUX ) >= MIN( QUALITE DES 2T )
C            => PAS DE TRANSFORMATION 3T=>2T
C          5 SI L'UNE DES 3 FACES APPELEES A DISPARAITRE APPARTIENT
C            A LEFACO ET PAS DE 3T->2T
C          6 SI NOTETR(1,NTE)<=0
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC  &  St PIERRE DU PERRAY Mai     2017
C MODIFS: ALAIN PERRONNET               St PIERRE DU PERRAY Fevrier 2018
C....................................................................012
      PARAMETER        (MXTE1A=16384)
      include"./incl/gsmenu.inc"
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE
ccc      LOGICAL                          TRACTE0
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      DOUBLE PRECISION  PTXYZD(1:4,1:*),VOLU2T, VOLU3T, VOLTET, V,
     %                  V3451, V4352
      DOUBLE PRECISION  ARMIN, ARMAX, SURFTR(4)
      REAL              Q5TE(5), QTE
      INTEGER           LEFACO(1:11,0:MXFACO)
      INTEGER           NOTETR(8,*), N1TETS(*), NTEOLD(3), NTENEW(2)
      INTEGER           NSF(3), NOSOTR(3), NOTE1A(MXTE1A), NVOLTE(*)
      CHARACTER*80      KTITRE

C     NO DES 2 SOMMETS EXTREMITES DES ARETES DU TETRAEDRE
      INTEGER           NOSOARTE(2,6)
      DATA              NOSOARTE / 1,2, 2,3, 3,1, 4,1, 4,2, 4,3 /
      INTEGER           NOSOFATE(3,4)
      DATA              NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /

      IF( NOTETR(1,NTE) .LE. 0 ) THEN
         IERR = 6
         RETURN
      ENDIF

C     NUMERO PTXYZD DES 2 SOMMETS DE L'ARETE NAR
      NS1 = NOTETR( NOSOARTE( 1, NAR ), NTE )
      NS2 = NOTETR( NOSOARTE( 2, NAR ), NTE )

C     L'ARETE NS1-NS2 PERFORE LA FACE COMMUNE AUX 2 TETRAEDRES
C     2 TETRAEDRES => 3 TETRAEDRES D'ARETE COMMUNE NS1-NS2
      CALL TETR1A( NS1,    NS2,    N1TETS, NOTETR,
     %             NBTE1A, MXTE1A, NOTE1A, IERR )
      IF( IERR .NE. 0 ) RETURN

      IF( NBTE1A .GE. MXTE1A ) THEN
C        TRACE DES TETRAEDRES DU DEBORDEMENT DU TABLEAU NOTE1A
ccc         TRACTE0 = TRACTE
ccc         TRACTE = .TRUE.
         KTITRE ='ch3t2t: DEBORDEMENT DU TABLEAU NOTE1A POURQUOI ???'
         CALL TRFETO13( KTITRE, PTXYZD, NBTE1A, NOTE1A, NOTETR )
ccc         TRACTE = TRACTE0
      ENDIF

      IF( NBTE1A .NE. 3 ) THEN
         IERR = 1
         GOTO 9000
      ENDIF

C     SI LE NO DE VOLUME DES TETRAEDRES (TABLEAU NVOLTE) EST PRESENT
C     ALORS TOUS LES TETRAEDRES DOIVENT ETRE DANS UN MEME VOLUME
      NOVOLU = 0
      IF( IVOLTE .NE. 0 ) THEN
         NOVOLU = NVOLTE( NOTE1A(1) )
         DO M = 2, NBTE1A
            IF( NVOLTE( NOTE1A(M) ) .NE. NOVOLU ) THEN
               IERR = 1
               GOTO 9000
            ENDIF
         ENDDO
      ENDIF

C     RECHERCHE DE NTE DANS NOTE1A
      DO N = 1, 3
         IF( NTE .EQ. NOTE1A( N ) ) GOTO 5
      ENDDO
      IERR = 1
      GOTO 9000

C     NTE EST MIS EN PREMIERE POSITION DE NOTE1A
 5    IF( N .NE. 1 ) THEN
         M           = NOTE1A( 1 )
         NOTE1A( 1 ) = NOTE1A( N )
         NOTE1A( N ) = M
      ENDIF

C     RECHERCHE DES 2 SOMMETS NS3 NS4 DE NTE NON SUR L'ARETE NAR
      DO N3 = 1,4
         NS3 = NOTETR( N3, NTE )
         IF( NS3 .NE. NS1 .AND. NS3 .NE. NS2 ) GOTO 10
      ENDDO

 10   DO N4 = N3+1,4
         NS4 = NOTETR( N4, NTE )
         IF( NS4 .NE. NS1 .AND. NS4 .NE. NS2 ) GOTO 15
      ENDDO
      IERR = 1
      GOTO 9000

C     RECHERCHE DANS NOTE1A(2) DU SOMMET NS5 NON SOMMET DE NTE
 15   NTE2 = NOTE1A( 2 )
      DO N5 = 1, 4
         NS5 = NOTETR( N5, NTE2 )
         IF( NS5 .NE. NS1 .AND. NS5 .NE. NS2 .AND.
     %       NS5 .NE. NS3 .AND. NS5 .NE. NS4 ) GOTO 20
      ENDDO
      IERR = 1
      GOTO 9000

C     LES 3 TETRAEDRES S'ENROULENT ILS AUTOUR DE NS1-NS2?
 20   NTE3 = NOTE1A( 3 )
      DO N6 = 1, 4
         NS6 = NOTETR( N6, NTE3 )
         IF( NS6 .NE. NS1 .AND. NS6 .NE. NS2 .AND.
     %       NS6 .NE. NS3 .AND. NS6 .NE. NS4 .AND.
     %       NS6 .NE. NS5 ) THEN
C           NTE3 N'A PAS 2 FACES COMMUNES AVEC NTE1 ou NTE2
C           PAS D'ECHANGE 3T -> 2T
            IERR = 1
            GOTO 9000
         ENDIF
      ENDDO

C     NTE1+NTE2+NTE3 S'ENROULENT SANS TROU SUR L'AXE NS1-NS2
      IF( INFACO .NE. 0 ) THEN

C        PROTECTION DES FACES DE LEFACO QUI DISPARAITRAIENT DANS 3T->2T
C        FACE NS1-NS2-NS3
C        LA FACE DE SOMMETS NOSOTR(1:3) EXISTE-T-ELLE DEJA DANS LEFACO?
C        HACHAGE DANS LEFACO AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
         NOSOTR(1) = NS1
         NOSOTR(2) = NS2
         NOSOTR(3) = NS3
         CALL NULETR( NOSOTR, MXFACO, LEFACO,  NFLEFA )
         IF( NFLEFA .GT. 0 ) THEN
C           OUI: FACE DANS LEFACO -> POUR LA CONSERVER PAS D'ECHANGE
            IERR = 5
            GOTO 9000
         ENDIF

C        FACE NS1-NS2-NS4
         NOSOTR(1) = NS1
         NOSOTR(2) = NS2
         NOSOTR(3) = NS4
         CALL NULETR( NOSOTR, MXFACO, LEFACO,  NFLEFA )
         IF( NFLEFA .GT. 0 ) THEN
C           OUI: FACE DANS LEFACO -> POUR LA CONSERVER PAS D'ECHANGE
            IERR = 5
            GOTO 9000
         ENDIF

C        FACE NS1-NS2-NS5
         NOSOTR(1) = NS1
         NOSOTR(2) = NS2
         NOSOTR(3) = NS5
         CALL NULETR( NOSOTR, MXFACO, LEFACO,  NFLEFA )
         IF( NFLEFA .GT. 0 ) THEN
C           OUI: FACE DANS LEFACO -> POUR LA CONSERVER PAS D'ECHANGE
            IERR = 5
            GOTO 9000
         ENDIF

      ENDIF

C     VOLUME DU 1-ER TETRAEDRE REMPLACANT
      V3451 = VOLTET( PTXYZD(1,NS3), PTXYZD(1,NS4),
     %                PTXYZD(1,NS5), PTXYZD(1,NS1) )
      IF( V3451 .LE. 0D0 ) THEN
C        PERMUTATION DE NS3 et NS4
         M     = NS3
         NS3   = NS4
         NS4   = M
C        LE VOLUME DEVIENT POSITIF
         V3451 = -V3451
      ENDIF

C     NUMERO DES 3 SOMMETS DE LA FACE COMMUNE NS345
      NSF(1) = NS3
      NSF(2) = NS4
      NSF(3) = NS5

C     VERIFICATION : COMPARAISON DES 2 VOLUMES 3T ET 2T
      VOLU3T = 0D0
      DO N = 1, 3
         NT = NOTE1A( N )
         VOLU3T = VOLU3T + ABS( VOLTET( PTXYZD(1,NOTETR(1,NT)),
     %                                  PTXYZD(1,NOTETR(2,NT)),
     %                                  PTXYZD(1,NOTETR(3,NT)),
     %                                  PTXYZD(1,NOTETR(4,NT)) ) )
      ENDDO

      V4352 = VOLTET( PTXYZD(1,NS4), PTXYZD(1,NS3),
     %                PTXYZD(1,NS5), PTXYZD(1,NS2) )
      IF( V4352 .LE. 0D0 ) THEN
         IERR = 3
C        RETOUR SANS MODIFICATION
         GOTO 9000
      ENDIF

      VOLU2T = V3451 + V4352

C     COMPARAISON DU VOLUME DE 3T et 2T
      IF( ABS(VOLU2T-VOLU3T) .GT. VOLU2T*1D-8 ) THEN
CCC         WRITE(IMPRIM,10010) VOLU2T,VOLU3T
CCC10010 FORMAT(' ch3t2t: VOLUME 3T AVANT',G25.16,' NON EGAL A 2T',G25.16)
         IERR = 3
C        RETOUR SANS MODIFICATION
         GOTO 9000
      ENDIF

C     RECHERCHE ON NON DU MAXIMUM DES QUALITES 3T ou 2T?
      IF( MXQUAL .GT. 0 ) THEN

C        OUI: CALCUL DES QUALITES DES 3 TETRAEDRES ACTUELS
         DO N = 1, 3
            NT = NOTE1A( N )
            CALL QUATETD( PTXYZD(1,NOTETR(1,NT)),
     %                    PTXYZD(1,NOTETR(2,NT)),
     %                    PTXYZD(1,NOTETR(3,NT)),
     %                    PTXYZD(1,NOTETR(4,NT)),
     %                    ARMIN, ARMAX, SURFTR, V, Q5TE(N) )
         ENDDO

C        OUI: CALCUL DES QUALITES DES TETRAEDRES 3451  4352
         CALL QUATETD( PTXYZD(1,NS3),
     %                 PTXYZD(1,NS4),
     %                 PTXYZD(1,NS5),
     %                 PTXYZD(1,NS1),
     %                 ARMIN, ARMAX, SURFTR, V3451, Q3451 )

         CALL QUATETD( PTXYZD(1,NS4),
     %                 PTXYZD(1,NS3),
     %                 PTXYZD(1,NS5),
     %                 PTXYZD(1,NS2),
     %                 ARMIN, ARMAX, SURFTR, V4352, Q4352 )

         IF( MIN(Q5TE(1),Q5TE(2),Q5TE(3)) .GE. MIN( Q3451,Q4352 ) ) THEN
            IERR = 4
C           RETOUR SANS MODIFICATION
            GOTO 9000
         ENDIF

      ENDIF

C     RECHERCHE DE 2 TETRAEDRES VIDES POUR LES TETRAEDRES 3451 et 4352
      DO LL=1,2

         IF( N1TEVI .LE. 0 ) THEN
C           SATURATION DES TETRAEDRES NOTETR
            NBLGRC(NRERR) = 1
            KERR(1) = 'SATURATION DES TETRAEDRES N1TEVI='
            L = NUDCNB( KERR(1) )
            WRITE(KERR(1)(L+1:L+10),'(I10)') N1TEVI
            CALL LEREUR
            IERR = 2
            GOTO 9000
         ENDIF
C        NUMERO NOTETR DU NOUVEAU TETRAEDRE
         NT = N1TEVI
C        MISE A JOUR DU 1-ER TETRAEDRE VIDE
         N1TEVI = NOTETR(5,N1TEVI)

         NTENEW(LL) = NT
         IF( IVOLTE .NE. 0 ) THEN
C           NUMERO DE VOLUME DES SOUS-TETRAEDRES
            NVOLTE( NT ) = NOVOLU
         ENDIF
C        MISE A JOUR DU DERNIER TETRAEDRE OCCUPE
         NUDTETR = MAX( NUDTETR, NT )

      ENDDO

C     LE TETRAEDRE 3451 EST CONSTRUIT
      NTE1 = NTENEW( 1 )
      NOTETR(1,NTE1) = NS3
      NOTETR(2,NTE1) = NS4
      NOTETR(3,NTE1) = NS5
      NOTETR(4,NTE1) = NS1

C     LE TETRAEDRE 4352 EST CONSTRUIT
      NTE2 = NTENEW( 2 )
      NOTETR(1,NTE2) = NS4
      NOTETR(2,NTE2) = NS3
      NOTETR(3,NTE2) = NS5
      NOTETR(4,NTE2) = NS2

C     RECHERCHE DES COUPLES DE TETRAEDRES OPPOSES PAR UNE FACE
      NOTETR(5,NTE1) = NTE2
      NOTETR(5,NTE2) = NTE1

C     POUR TESTER. ENSUITE SUPPRIMER LES 6 LIGNES SUIVANTES
      NOTETR(6,NTE1) = -1
      NOTETR(7,NTE1) = -1
      NOTETR(8,NTE1) = -1

      NOTETR(6,NTE2) = -1
      NOTETR(7,NTE2) = -1
      NOTETR(8,NTE2) = -1

      DO M = 1, 2

C        NOUVEAU TETRAEDRE DE TETRAEDRES OPPOSES A COMPLETER
         NTEN = NTENEW( M )

         DO 30 NF=2,4

C           FACE NF DE NTEN
            DO K = 1, 3
               NOSOTR( K ) = NOTETR( NOSOFATE(K,NF), NTEN )
            ENDDO

            DO N = 1, 3

               NT = NOTE1A( N )
               CALL NUFATRTE( NOSOTR, NOTETR(1,NT), NFNT )
               IF( NFNT .GT. 0 ) THEN

C                 LA FACE NFNT DE NT EST LA FACE NF DE NTEN
C                 D'OU SON TETRAEDRE OPPOSE NTEOP PAR CETTE FACE
                  NTEOP = NOTETR( 4+NFNT, NT )
                  NOTETR( 4+NF, NTEN ) = NTEOP

                  IF( NTEOP .GT. 0 ) THEN
                     CALL NUFATRTE( NOSOTR, NOTETR(1,NTEOP), NFTEOP )
                     IF( NFTEOP .GT. 0 ) THEN
                        NOTETR( 4+NFTEOP, NTEOP ) = NTEN
                     ENDIF
                  ENDIF

                  GOTO 30

               ENDIF
            ENDDO

C           ANOMALIE SI PASSAGE ICI
            PRINT*,'ch3t2t: ANOMALIE NOSOTR=',NOSOTR,' du TETRAEDRE',
     %              NTEN,' NON RETROUVE DANS LES 3 TETRAEDRES',
     %             (NOTE1A(N),N=1,3)
            DO N = 1,3
               NT = NOTE1A( N )
               PRINT*,'NOTETR(',NT,')=',(NOTETR(K,NT),K=1,8)
            ENDDO
            PRINT*,'NOTETR(',NTEN,')=',(NOTETR(K,NTEN),K=1,8)

 30      ENDDO

C        QUALITE ET VOLUME DU TETRAEDRE NTEN
         CALL QUATETD( PTXYZD(1,NOTETR(1,NTEN)),
     %                 PTXYZD(1,NOTETR(2,NTEN)),
     %                 PTXYZD(1,NOTETR(3,NTEN)),
     %                 PTXYZD(1,NOTETR(4,NTEN)),
     %                 ARMIN, ARMAX, SURFTR, V, QTE )
         Q5TE(3+M) = QTE
         IF( QTE .LE. 0.0 ) THEN
C           TETRAEDRE NTEN DEGENERE
            WRITE(IMPRIM,10030) NTEN,QTE,(NOTETR(KL,NTEN),KL=1,4)
10030       FORMAT(' ch3t2t: TETRAEDRE DEGENERE',I8,' QUALITE',G13.6,
     %             ' DE SOMMETS ',4I8)
         ENDIF

      ENDDO

C     MISE A JOUR D'UN TETRAEDRE CONTENANT CHAQUE SOMMET
      N1TETS(NS3) = NTE1
      N1TETS(NS4) = NTE1
      N1TETS(NS5) = NTE1
      N1TETS(NS1) = NTE1
      N1TETS(NS2) = NTE2

C     DESTRUCTION DES 3 TETRAEDRES NOTE1A
C     ILS REDEVIENNENT VIDES DANS NOTETR
      DO N = 1, 3
         NT = NOTE1A( N )
         NTEOLD( N )  = NT
         NOTETR(1,NT) = 0
         NOTETR(5,NT) = N1TEVI
         N1TEVI       = NT
         IF( IVOLTE .NE. 0 ) THEN
C           NUMERO INCONNU DE VOLUME DU TETRAEDRE INACTIF
            NVOLTE( NT ) = -1
         ENDIF
      ENDDO

      IERR = 0

 9000 RETURN
      END
