      SUBROUTINE CRFETOI1( NBTEET, NOTEET, NOTETR,
     %                     MXFETO, N1FEOC, N1FEVI, NFETOI )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CONSTRUCTION DE L'ETOILE DES FACES SIMPLES DES TETRAEDRES
C -----    LES FACES VUES 2 FOIS SONT ELIMINEES
C          LES FACES VUES UNE FOIS SONT AJOUTEES
C          VERSION 1 DU TABLEAU NFETOI DES FACES SIMPLES DE L'ETOILE

C ENTREES:
C --------
C NBTEET : NOMBRE DE TETRAEDRES DE L'ETOILE
C NOTEET : NUMERO NOTETR DES TETRAEDRES DE L'ETOILE
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C MXFETO : NOMBRE MAXIMAL DE FACES DU TABLEAU NFETOI

C SORTIES:
C --------
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C N1FEVI : POINTEUR SUR LA PREMIERE FACE VIDE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C          =-1 SI SATURATION DU TABLEAU NFETOI
C NFETOI : VERSION 1
C          1: NUMERO DU TETRAEDRE DANS NOTETR DE LA FACE DE L'ETOILE
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3: NON UTILISE ICI
C          4: NON UTILISE ICI
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY Novembre 2014
C23456...............................................................012
      INTEGER  NOTEET(NBTEET), NOTETR(8,*), NFETOI(5,MXFETO)

C        REINITIALISATION A VIDE DES FACES DE NFETOI
         CALL ETOIVIDE( MXFETO, N1FEOC, N1FEVI, NFETOI )
C        N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C                 CHAINAGE SUIVANT DANS NFETOI(5,*)
C        N1FEVI : POINTEUR SUR LA PREMIERE FACE VIDE DE L'ETOILE
C                 CHAINAGE SUIVANT DANS NFETOI(5,*)
C        NFETOI : 1: NUMERO DU TETRAEDRE DANS NOTETR AYANT CETTE FACE
C                 2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C                    UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C                 3: NON UTILISE ICI
C                 4: NUMERO DE CETTE FACE DANS LEFACO, 0 SI PAS DANS LEFACO
C                 5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

         DO N=1,NBTEET
C           LE TETRAEDRE N DE L'ETOILE
            NTE = NOTEET( N )
            IF( NTE .GT. 0 .AND. NOTETR(1,NTE) .GT. 0 ) THEN
               DO NFTE=1,4
C                 LA FACE NFTE DU TETRAEDRE NTE EST AJOUTEE AUX
C                 FACES DE L'ETOILE
                  CALL AJFAET1( NTE, NFTE, NOTETR,
     %                          N1FEOC, N1FEVI, NFETOI, NFS )
                  IF( N1FEVI .EQ. -1 ) GOTO 9999
               ENDDO
            ENDIF
         ENDDO

C        RENDRE POSITIF NFETOI(2,*) DE L'ETOILE
         NF1 = N1FEOC
 20      IF( NF1 .GT. 0 ) THEN

C           NUMERO DE LA FACE SIMPLE DANS LE TETRAEDRE
C           LA FACE EST REINITIALISEE NON TRAITEE
            NFETOI(2,NF1) = ABS( NFETOI(2,NF1) )

C           LA FACE SUIVANTE
            NF1 = NFETOI(5,NF1)
            GOTO 20

         ENDIF

 9999    RETURN
         END
