       SUBROUTINE CRSFTRCL( KNOMSF1, MNXYZS1, MNNSEF1 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     RETIRER et CREER UNE SURFACE de TRIANGLES CLIQUES
C -----
C ENTREES:
C --------
C KNOMSF1 : NOM DE LA SURFACE A PARTITIONNER
C MNXYZS1 : ADRESSE DU TABLEAU XYZSOMMET DE LA SURFACE
C MNNSEF1 : ADRESSE DU TABLEAU NSEF      DE LA SURFACE
C
C SORTIES:
C --------
C LES TRIANGLES CLIQUES FORMENT S2 ET ONT ETE RETIRES DE S1
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : Alain PERRONNET Saint PIERRE du PERRAY           Janvier 2021
C2345X7..............................................................012
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/trvari.inc"
      include"./incl/a_surface__definition.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/pp.inc"
      COMMON         MCN(MOTMCN)
      REAL          RMCN(1)
      EQUIVALENCE  (RMCN(1),MCN(1))
      INTEGER       NOSOTQ(4)
      CHARACTER*24  KNOMSF1, KNOMSF2
      CHARACTER*48  KTITRE

      NBTQCL = 0
      NOTQCL = 0
      NBSAUV = 0
      MNNEWX = 0

      NBCOOR = MCN(MNXYZS1+WBCOOR)
      NBSOM1 = MCN(MNXYZS1+WNBSOM)
      MNXYZ1 = MNXYZS1 + WYZSOM

      NBTQSF1 = MCN( MNNSEF1+WBEFOB )
      MNSOEF1 = MNNSEF1 + WUSOEF

      PRINT*,'crsftrcl: PARTITIONNER a partir de TRIANGLES CLIQUES la SU
     %RFACE ',KNOMSF1,' de',NBSOM1,' SOMMETS et',NBTQSF1,' EF'

C     LECTURE DU MENU POUR CLIQUER LES TRIANGLES
C     ------------------------------------------
 10   CALL LIMTCL( 'pasftrcl', NOMTCL )
      IF( NOMTCL .LT. 0  ) THEN

C        FIN DE L'OPTION?
C        VERIFICATION DE LA SAUVEGARDE DES TRIANGLES CLIQUES de S2
         IF( NBTQCL .LE. 0 .OR. NBSAUV .GT. 0 ) GOTO 9999

C        DES TRIANGLES ONT ETE CLIQUES SANS ETRE SAUVEGARDES DANS S2
         NBLGRC(NRERR)=2
         IF( LANGAG .EQ. 0 ) THEN
          KERR(1)='           TRIANGLES CLIQUES NON SAUVEGARDES'
          KERR(2)='REINTEGRES A LA TRIANGULATION DE S1'
         ELSE
          KERR(1)='           CLICKED TRIANGLES CLIQUES NOT SAVED'
          KERR(2)='REINTEGRATED to THE S1 TRIANGULATION'
         ENDIF
         WRITE(KERR(1)(1:5),'(I5)') NBTQCL
         CALL LERESU

         NBTQSF1 = NBTQSF1 + NBTQCL
         MCN( MNNSEF1+WBEFOB ) = NBTQSF1
         CALL ECDATE( MCN(MNNSEF1) )
         MCN( MNNSEF1+MOTVAR(6) ) = NONMTD( '~>>>NSEF' )

C        PLUS AUCUN TRIANGLE CLIQUE
         NBTQCL = 0
         GOTO 10

      ENDIF

      GOTO( 100, 200, 300, 400, 10 ), NOMTCL


C     DONNER un NOM de la SURFACE S2 des TRIANGLES CLIQUES
C     ====================================================
 100  CALL INVITE( 43 )
      NCVALS = 0
      CALL LIRCAR( NCVALS, KNOMSF2 )
      IF( NCVALS .EQ. -1 ) RETURN
      NBTQCL = 0
      NBSAUV = 0
      GOTO 10


C     CLIC DANS QUEL TRIANGLE ou QUADRANGLE?
C     ======================================
 200  NBTQSF1 = MCN(MNNSEF1+WBEFOB)

C     SELECTIONNER A L'AIDE D'UN CLIC SOURIS UNE FACE DU MAILLAGE
C     PRESENTE DANS LA FENETRE GRAPHIQUE C-A-D
C     RETOURNER LE NUMERO NOTQCL DE LA FACE VISIBLE DONT LE CLIC
C     EST INTERNE POUR UN MAILLAGE d'une SURFACE 3D
C     -----------------------------------------------------------
      NBNOST = 0
      NOSOTQ(1) = 0
      CALL SEFACLIC( RMCN(MNXYZ1), NCJAUN, NBNOST, NOSOTQ,
     %               MCN(MNSOEF1), NOTQCL )

      IF( NOTQCL .LE. 0 ) THEN
         NBLGRC(NRERR)=2
         IF( LANGAG .EQ. 0 ) THEN
          KERR(1)='POINT EXTERNE aux TRIANGLES ou QUADRANGLES VISIBLES'
          KERR(2)='CLIQUER un POINT a L''INTERIEUR d''un TRIANGLE'
         ELSE
            KERR(1)='POINT OUTSIDE TRIANGLES or QUADRANGLES'
            KERR(2)='CLICK a POINT INSIDE a TRIANGLE or QUADRANGLE'
         ENDIF
         CALL LERESU
         GOTO 10
      ENDIF

C     LE TRIANGLE ou QUADRANGLE NOTQCL EST PERMUTE AVEC
C     LE DERNIER TRIANGLE DE S1 QUI DEVIENT TRIANGLE de S2
C     ----------------------------------------------------
      MN  = MNSOEF1 + 4 * NBTQSF1 - 5
      MN1 = MNSOEF1 + 4 * NOTQCL - 5
      PRINT*,'crsftrcl: MISE dans S2 du TQANGLE',NOTQCL,' St:',
     %       (MCN(MN1+K),K=1,4)

      DO K=1,4
C        PERMUTATION DU NO DE SOMMET DES TRIANGLES NOTQCL et NBTQSF1
         NS         = MCN(MN1+K)
         MCN(MN1+K) = MCN(MN +K)
         MCN(MN +K) = NS
      ENDDO

C     UN EF DE PLUS DANS S2
      NBTQCL = NBTQCL + 1

C     UN EF DE MOINS DANS S1
      NBTQSF1 = NBTQSF1 - 1
      MCN( MNNSEF1+WBEFOB ) = NBTQSF1
      CALL ECDATE( MCN(MNNSEF1) )
      MCN( MNNSEF1+MOTVAR(6) ) = NONMTD( '~>>>NSEF' )

C     TRACE EN ROUGE du TRIANGLE CLIQUE de S2
      IF( LANGAG .EQ. 0 ) THEN
         KTITRE='En ROUGE le NOUVEAU TRIANGLE CLIQUE'
      ELSE
         KTITRE='in RED the NEW CLICKED TRIANGLE'
      ENDIF

C     RESTAURATION DES PIXELS DE LA FENETRE PIXELS MEFISTO
C     SAUVEGARDEE JUSTE AVANT LES MODIFICATIONS
      CALL RESTAUREMEMPX
      CALL MEMPXFENETRE
      CALL XVVOIR

C     TRACE EN ROUGE DE L'ITEM FACE CLIQUE
      CALL TIFACE3D( NCROUG, NCROSE, -1, -1,
     %               NBTQSF1+1, MCN(MNSOEF1), RMCN(MNXYZ1) )
      CALL SANSBL( KTITRE, NBC )
      CALL TRFINS( KTITRE(1:NBC) )

      GOTO 10


C     REGENERER dans S1 le DERNIER TRIANGLE CLIQUE de S2
C     C'EST LE TRIANGLE NBTQSF1+1
C     ==================================================
 300  IF( NBTQCL .LE. 0 ) GOTO 10
C     UN EF DE PLUS DANS S1 QUI EST NBTQSF1+1
      NBTQSF1 = NBTQSF1 +1
      MCN( MNNSEF1+WBEFOB ) = NBTQSF1
      CALL ECDATE( MCN(MNNSEF1) )
      MCN( MNNSEF1+MOTVAR(6) ) = NONMTD( '~>>>NSEF' )

C     RESTAURATION DES PIXELS DE LA FENETRE PIXELS MEFISTO
C     SAUVEGARDEE JUSTE AVANT LES MODIFICATIONS
      CALL RESTAUREMEMPX
      CALL MEMPXFENETRE
      CALL XVVOIR

C     TRACE EN VERT DE L'ITEM REGENERE
      CALL TIFACE3D( NCVERT, NCTURQ, -1, -1,
     %               NBTQSF1, MCN(MNSOEF1), RMCN(MNXYZ1) )
      CALL SANSBL( KTITRE, NBC )
      CALL TRFINS( KTITRE(1:NBC) )

C     UN TRIANGLE DE MOINS CLIQUE DE S2 REMIS DANS S1
      NBTQCL = NBTQCL - 1
      GOTO 10


C     RETIRER les TRIANGLES S2 de S1 et CREER la SURFACE S2
C     =====================================================
 400  CALL LXLXDC( NTSURF, KNOMSF2, 24, 8 )
      CALL LXLXOU( NTSURF, KNOMSF2, NTLXS2, MNLXS2 )
      IF( NTLXS2 .LE. 0 ) GOTO 10

C     GENERATION DU TABLEAU 'XYZSOMMET' DE S2
      CALL LXTSOU( NTLXS2, 'XYZSOMMET', NTXYZS2, MNXYZS2 )
      IF( NTXYZS2 .GT. 0 ) THEN
         CALL LXTSDS( NTLXS2, 'XYZSOMMET' )
      ENDIF

      NBSOM2 = NBSOM1
      NBMOTS = WYZSOM + NBCOOR * NBSOM1
      CALL LXTNDC( NTLXS2, 'XYZSOMMET','MOTS',   NBMOTS )
      CALL LXTSOU( NTLXS2, 'XYZSOMMET', NTXYZS2, MNXYZS2 )
      MNXYZ2 = MNXYZS2 + WYZSOM

C     COPIE DE XYZ DE S1 DANS S2
      CALL TRTATA( MCN(MNXYZ1), MCN(MNXYZ2), 3*NBSOM1 )

C     GENERATION DU TABLEAU 'NSEF' DE S2
      CALL LXTSOU( NTLXS2, 'NSEF', NTNSEF2, MNNSEF2 )
      IF( NTNSEF2 .GT. 0 ) THEN
         CALL LXTSDS( NTLXS2, 'NSEF' )
      ENDIF
      NBMOTS = WUSOEF + 4 * NBTQCL
      CALL LXTNDC( NTLXS2, 'NSEF','MOTS',   NBMOTS )
      CALL LXTSOU( NTLXS2, 'NSEF', NTNSEF2, MNNSEF2 )

C     COPIE DES NBTQCL TRIANGLES CLIQUES DE S2
      MN      = MNSOEF1 + 4 * NBTQSF1
      MNSOEF2 = MNNSEF2 + WUSOEF
      CALL TRTATA( MCN(MN), MCN(MNSOEF2), 4*NBTQCL )

C     TABLEAU DE RENUMEROTATION DES SOMMETS DE S2
      CALL TNMCDC( 'ENTIER', 1+NBSOM1, MNNEWX )

C     RENUMEROTATION DES SOMMETS ET DES TRIANGLES DE S2
      NBTQSF2 = NBTQCL
      CALL MAJXYZNSE( NBSOM2, RMCN(MNXYZ2), MCN(MNNEWX),
     %                4, NBTQSF2, MCN(MNSOEF2) )

      CALL TNMCDS( 'ENTIER', 1+NBSOM1, MNNEWX )

C     LES VARAIABLES du TMS 'XYZSOMMET' de la SURFACE S2
C     LE NOMBRE DE SOMMETS INITIAL de S2
      MCN( MNXYZS2 + WNBSOM ) = NBSOM2
C     LE NOMBRE DE TANGENTES
      MCN( MNXYZS2 + WNBTGS ) = 0
C     LE NOMBRE DE COORDONNEES D'UN SOMMET
      MCN( MNXYZS2 + WBCOOR ) = NBCOOR

C     LE TMS XYZSOMMET EST RACCOURCI A SA VALEUR EXACTE
      CALL TAMSRA( NTXYZS2, WYZSOM + NBSOM2 * NBCOOR )

C     LES VARAIABLES du TMS 'NSEF' de la SURFACE S2
      MCN( MNNSEF2 + WUTYOB ) = 3
      MCN( MNNSEF2 + WUTFMA ) = -1
      MCN( MNNSEF2 + WBSOEF ) = 4
      MCN( MNNSEF2 + WBTGEF ) = 0
      MCN( MNNSEF2 + WBEFOB ) = NBTQSF2
      MCN( MNNSEF2 + WBEFTG ) = 0
      MCN( MNNSEF2 + WBEFAP ) = 0
      MCN( MNNSEF2 + WUTYMA ) = 0

C     LE TMS DEFINITION DE LA SURFACE S2
      CALL LXTSOU( NTLXS2, 'DEFINITION', NTDEFI, MNDEFI )
      IF( NTDEFI .GT. 0 ) THEN
         CALL LXTSDS( NTLXS2, 'DEFINITION' )
      ENDIF

C     A PARTIR DES TMS XYZSOMMET et NSEF
C     10: 'DONNEE DIRECTE DES TMS XYZSOMMET ET NSEF'
      CALL LXTNDC( NTLXS2, 'DEFINITION', 'MOTS', WUTSSS+1 )
      CALL LXTSOU( NTLXS2, 'DEFINITION', NTDEFI, MNDEFI )
C     TRANSFORMATION (I pour IDENTITE)
      MCN( MNDEFI + WTYTRS ) = 1

C     10: 'DONNEE DIRECTE DES TMS XYZSOMMET ET NSEF'
      MCN( MNDEFI + WUTYSU ) = 10

C     NUTSOV 'tableau MS xyzsommet' tms ~>>>XYZSOMMET
      MCN( MNDEFI + WUTSOS ) = NTXYZS2

C     NUTSSV 'tableau MS no des sommets des EF' tms ~>>>NSEF
      MCN( MNDEFI + WUTSSS ) = NTNSEF2

C     AJOUT DE LA DATE du TMS 'DEFINITION'
      CALL ECDATE( MCN(MNDEFI) )

C     AJOUT DE LA DATE du TMS 'XYZSOMMET' POSTERIEURE a la DEFINITION
      CALL ECDATE( MCN(MNXYZS2) )
      MCN( MNXYZS2+MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )

C     AJOUT DE LA DATE du TMS 'NSEF' DE S2 POSTERIEURE a la DEFINITION
      CALL ECDATE( MCN(MNNSEF2) )
      MCN( MNNSEF2+MOTVAR(6) ) = NONMTD( '~>>>NSEF' )

      IF( LANGAG .EQ. 0 ) THEN
         PRINT *,'Creation CORRECTE de la SURFACE ',KNOMSF2,
     %           ' de',NBSOM2,' SOMMETS et',NBTQSF2,' QTRIANGLES'
      ELSE
         PRINT *,'CORRECT CREATION of SURFACE ',KNOMSF2,
     %           ' of',NBSOM2,' VERTICES and',NBTQSF2,' QTRIANGLES'
      ENDIF

C     QUALITE DE LA TRIANGULATION DE LA SURFACE EXTRAITE S2
      CALL IMPQUA( 3, KNOMSF2, MNNSEF2, MNXYZS2, NBEFMQ2, QUAMIN2,
     %             SURVOLEF )

C     QUALITE DE LA TRIANGULATION DE LA SURFACE RESTANTE S1
      CALL IMPQUA( 3, KNOMSF1, MNNSEF1, MNXYZS1, NBEFMQ1, QUAMIN1,
     %             SURVOLEF )

      NBSAUV = 1
      GOTO 10

 9999 RETURN
      END
