      SUBROUTINE CRSTCF2( NBTRCF, NOTRCF, LEFACO, NO0FAR,
     %                    MXSTCF, NBSTCF, NOSTCF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CONSTRUCTION DU TABLEAU DES NBSTCF NUMEROS DES SOMMETS DU CF
C -----    A PARTIR DE LA LISTE NOTRCF DES TRIANGLES DU CF
C ENTREES:
C --------
C NBTRCF : NOMBRE DE TRIANGLES DU TABLEAU NOTRCF SUR LEFACO
C          C-A-D DU POLYGONE ENCORE DIT ENSUITE ETOILE
C NOTRCF : >0 NUMERO DANS LEFACO DU TRIANGLE DE L'ETOILE
C          <0 NUMERO DANS NO0FAR DU TRIANGLE AJOUTE A L'ETOILE
C LEFACO : ENSEMBLE DES FACES=TRIANGLES DE LA PEAU OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          123: NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          45 : NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1, VOLUME2 DE LA FACE
C          678: NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C               ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C                          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          9  : LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C               HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C               LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C               NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C               SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C               NF  = LEFACO( 9, NF )  ...
C          10 : LEFACO(10,*) PREMIERE FACE DANS LE HACHAGE
C          11 : LEFACO(11,.) = NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE, 0 SINON
cccC          12 : LEFACO(12,.) = NO FACEOC DE 1 A NBFACES D'OC
C NO0FAR : NUMERO DES 3 SOMMETS DE LA FACE AJOUTEE AU CF
C MXSTCF : NOMBRE MAXIMAL DE SOMMETS DU CF DECLARABLES DANS NOSTCF

C SORTIES:
C --------
C NBSTCF : NOMBRE DE SOMMETS DU CF
C NOSTCF : NUMERO PTXYZD DES NBSTCF SOMMETS PERIPHERIQUES DU CF
C IERR   : =5 NBSTCF>MXSTCF => TROP DE SOMMETS DU CF
C          =0 SI PAS D'ERREUR RENCONTREE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET VEULETTES & St PIERRE du PERRAY  Janvier 2018
C2345X7..............................................................012
      INTEGER   NOTRCF(NBTRCF), LEFACO(11,0:*), NO0FAR(3,*),
     %          NOSTCF(MXSTCF)

      IERR   = 0
      NBSTCF = 0

      DO N = 1, NBTRCF

         NT = NOTRCF( N )

         DO 10 M=1,3

C           NO DU SOMMET N DU TRIANGLE N
            IF( NT .GT. 0 ) THEN
               NS = LEFACO(M,NT)
            ELSE
               NS = NO0FAR(M,-NT)
            ENDIF

C           NS EST IL DEJA STOCKE DANS NOSTCF?
            DO K=1,NBSTCF
               IF( NS .EQ. NOSTCF(K) ) GOTO 10
            ENDDO

C           NON : IL EST AJOUTE DANS NOSTCF
            IF( NBSTCF .GE. MXSTCF ) THEN
               PRINT*,'crstcf2: NOSTCF SATURE. AUGMENTER MXSTCF='
     %                ,MXSTCF
               IERR = 5
               RETURN
            ENDIF

            NBSTCF = NBSTCF + 1
            NOSTCF( NBSTCF ) = NS

 10      ENDDO

      ENDDO

      RETURN
      END
