      SUBROUTINE CYLCONE( NBES,   NBEH, XYZB, XYZH, RI, RS, QH, QS, ANG,
     %                    XYZSOM, NOEUDS, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT:      GENERER UN SECTEUR ANGULAIRE DE LA SURFACE D'UN CYLINDRE
C -----     OU D'UN TRONC DE CONE
C ENTREES :
C ---------
C NBEH    : NOMBRE D'ELEMENTS SUR LA HAUTEUR
C NBES    : NOMBRE D'ELEMENTS SUR LA SECTION ANGULAIRE
C XYZB    : XYZ DU CENTRE DU CERCLE INFERIEUR
C XYZH    : XYZ DU CENTRE DU CERCLE SUPERIEUR
C RI      : RAYON DU CERCLE INFERIEUR
C RS      : RAYON DU CERCLE SUPERIEUR
C QH      : RAISON GEOMETRIQUE DE CONCENTRATION SUR LA HAUTEUR
C QS      : RAISON GEOMETRIQUE DE CONCENTRATION SUR L'ANGLE
C ANG     : ANGLE DU SECTEUR ANGULAIRE
C
C CONTRAINTES SUR LES ENTREES :
C ----------------------------
C NBEH >= 2
C NBES >= 2
C Z DIFFERENT DE 0
C RS > 0
C RI > 0
C QH > 0 ( 1 - MAILLAGE HOMOGENE )
C QS > 0 ( 1 - MAILLAGE HOMOGENE )
C 0 < ANG <= 2*PI     SI ANG > PI ALORS NBES>=3
C
C VARIABLES UTILISEES :
C --------------------
C NBEF  : NOMBRE TOTAL D'ELEMENTS (quadrangle)
C NBSH  : NOMBRE DE SOMMETS SUR LA HAUTEUR
C NBSS  : NOMBRS DE SOMMETS SUR LA SECTION
C NUMEF : NUMERO D'ELEMENT
C NUMS  : NUMERO DU SOMMET
C
C SORTIES :
C --------
C XYZSOM : TABLEAU DES COORDONNEES DES NOEUDS
C NOEUDS : TABLEAU D'AFFECTATION DES SOMMETS AUX ELEMENTS
C IERR   : 0 SI PAS D'ERREUR
C          > 0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : BATOUCHE_EMMEL MARS DEA D'ANALYSE NUMERIQUE     Fevrier  1991
C MODIFS : ALAIN PERRONNET LJLL UPMC & St Pierre du Perray Novembre 2011
C2345X7..............................................................012
      REAL              XYZSOM(3,*), XYZB(3), XYZH(3)
      REAL              XYZ3PI(3,3), XYZ3PF(3,3), XYZ(3)
      INTEGER           NOEUDS(4,*)
      DOUBLE PRECISION  DMATRI(3,4)
      INTRINSIC         SQRT
C
C     LE VECTEUR AXE DU CYLINDRE
      X = XYZH(1) - XYZB(1)
      Y = XYZH(2) - XYZB(2)
      Z = XYZH(3) - XYZB(3)
C
C     LONGUEUR DE L'AXE DU CYLINDRE
      H = SQRT( X*X + Y*Y + Z*Z )
C
C     CONSTRUIRE LA MATRICE DE TRANSFORMATION DES COORDONNEES POUR
C     PASSER D'UN REPERE DEFINI PAR 3 POINTS INITIAUX NON ALIGNES
C                               A   3 POINTS FINAUX   NON ALIGNES
C     LE REPERE INITIAL
      XYZ3PI(1,1) = 0.
      XYZ3PI(2,1) = 0.
      XYZ3PI(3,1) = 0.
C
      XYZ3PI(1,2) = H
      XYZ3PI(2,2) = 0.
      XYZ3PI(3,2) = 0.
C
      XYZ3PI(1,3) = 0.
      XYZ3PI(2,3) = H
      XYZ3PI(3,3) = 0.
C
C     LE REPERE FINAL
      XYZ3PF(1,1) = XYZB(1)
      XYZ3PF(2,1) = XYZB(2)
      XYZ3PF(3,1) = XYZB(3)
C
      IF( SQRT(X*X + Y*Y)/H .LE. 1E-3 ) THEN
C
C        AXES X et Y
         XYZ3PF(1,2) = XYZB(1) + H
         XYZ3PF(2,2) = XYZB(2)
         XYZ3PF(3,2) = XYZB(3)
C
         XYZ3PF(1,3) = XYZB(1)
         XYZ3PF(2,3) = XYZB(2) + H
         XYZ3PF(3,3) = XYZB(3)
C
      ELSE
C
C        RECHERCHE DE 2 DIRECTIONS ORTHOGONALES A L'AXE DU CYLINDRE
         XYZ3PF(1,2) = XYZB(1) - Y
         XYZ3PF(2,2) = XYZB(2) + X
         XYZ3PF(3,2) = XYZB(3)
C
         XYZ3PF(1,3) = XYZB(1) - X * Z
         XYZ3PF(2,3) = XYZB(2) - Y * Z
         XYZ3PF(3,3) = XYZB(3) + X * X + Y * Y
C
      ENDIF
C
C     CONSTRUCTION DE LA MATRICE DE TRANSFORMATION QUI ENVOIE
C     LES 3 POINTS INITIAUX SUR LES 3 POINTS FINAUX
      CALL TR3P3P( XYZ3PI, XYZ3PF, DMATRI, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     CALCUL DES XYZ DANS LE REPERE PROPRE
      NBSH  = NBEH+1
      NBSS  = NBES+1
      NBEF  = NBES * NBEH
      IF( ANG .EQ. 360.0 ) THEN
         NTEST=1
      ELSE
         NTEST=0
      ENDIF
      ANG = ANG * ATAN(1.) * 4. / 180.
C
C     CALCUL DES COORDONNEES DES NS SOMMETS
      NUMS=0
      DO I=1,NBSS
         WI = ANG * DIVISN( QS, I, NBSS )
         DO J=1,NBSH
C
            NUMS = NUMS+1
            DV   = DIVISN( QH, J, NBSH )
            RJ   = RI + (RS-RI) * DV
C
C           XYZ DANS LE REPERE PROPRE DU CONE (AXE Z)
            XYZ(1) = RJ*COS(WI)
            XYZ(2) = RJ*SIN(WI)
            XYZ(3) = DV*H
C
C           LE SOMMET APRES TRANSFORMATION
C           PASSAGE DU REPERE PROPRE DU CYLINDRE AU REPERE GENERAL
            CALL ISOMVA( DMATRI, XYZ, XYZSOM(1,NUMS) )
C
         ENDDO
      ENDDO
C
C     NUMEROTATION DES SOMMETS DES ELEMENTS FINIS
      DO NUMEF=1,NBEF
         NOEUDS(1,NUMEF) = NUMEF+(NUMEF-1)/NBEH
         NOEUDS(2,NUMEF) = NOEUDS(1,NUMEF)+NBSH
         NOEUDS(3,NUMEF) = NOEUDS(2,NUMEF)+1
         NOEUDS(4,NUMEF) = NOEUDS(1,NUMEF)+1
      ENDDO
C
C     RACCORD SI ANG=2*PI
      IF( NTEST .EQ. 1 ) THEN
         NN=NBEF-NBEH
         DO K=1,NBEH
            NOEUDS(2,NN+K)=NOEUDS(1,K)
            NOEUDS(3,NN+K)=NOEUDS(4,K)
         ENDDO
      ENDIF
C
 9999 RETURN
      END
