      SUBROUTINE DFTOPO
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : DEFINIR LES RECOUVREMENTS ENTRE POINTS LIGNES SURFACES VOLUMES
C ----- D'UN OBJET  EN TERMES DE SOMMETS SEULEMENT
C       PRENDRE EN COMPTE L'INTERPOLATION CHOISIE EN CREEANT
C       LES NOEUDS ET LES POINTS A PARTIR DES SOMMETS DES EF
C       RENUMEROTER EVENTUELLEMNET LES NOEUDS DE L'OBJET
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE UPMC PARIS       MARS 2004
C2345X7..............................................................012
      COMMON / UNITES /  LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/pilect.inc"
      CHARACTER*24  KNOMOB

 10   IERR = 0

C     NOM_DE_L'OBJET  LE CARACTERE @ POUR FINIR
      CALL INVITE( 46 )
      NCVALS = 0
      CALL LIRCAR( NCVALS, KNOMOB )
C     SI ECHAPPEMENT DEMANDE
      IF( NCVALS .EQ. -1 ) GOTO 9999

C     CONSTRUCTION DE LA TOPOLOGIE DE L'OBJET
      CALL DFTOP0( KNOMOB, IERR )
      IF( IERR .EQ. 0 ) THEN
ccc         IF( INTERA .GE. 1 .AND. LHLECT .EQ. 1 ) CALL T1OBJE( KNOMOB )
        IF( INTERA .GE. 1 ) CALL T1OBJE( KNOMOB )
      ENDIF
      GOTO 10

C     SORTIE
 9999 RETURN
      END
