      SUBROUTINE DMINTETRAPAV( HEXAPAVE, NBIPAV, ECHPAV,
     %                         N1SPAVE, NOPTSUIV, XYZ, PTXYZD,
     %                         MXSMIN, NBSMIN, NOSMIN, NODSNO, DISTMIN,
     %                         N1TETS, NBTETD, MINTET )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     RETROUVER LES PLUS PROCHES TETRAEDRES DU POINT XYZ RANGES
C -----     DANS LES PAVES
C ENTREES :
C ---------
C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES
C XYZ     : LES 3 COORDONNEES DU POINT A TRAITER
C PTXYZD  : X Y Z DISTANCE SOUHAITEE DES POINTS
C MXSMIN  : NOMBRE MAXIMAL DE SOMMETS VOISINS DE XYZ
C N1TETS  : NO NOTETR D'UN TETRAEDRE D'UN SOMMET
C
C SORTIES :
C ---------
C NBSMIN  : NOMBRE DE SOMMETS PROCHES
C NOSMIN  : NO DANS PTXYZD DES NBSMIN PLUS PROCHES POINT DE XYZ
C           0 SI PAS DE POINT PROCHE DANS LE PAVAGE
C NODSNO  : NODSNO(1)=NO DANS NOSMIN DU PLUS PROCHE POINT DE PTXYZD
C           APRES TRI CROISSANT DES DISTANCES A XYZ
C DISTMIN : DISTANCE AU CARRE DU POINT DU PAVAGE LE PLUS PROCHE DE XYZ
C NBTETD  : NOMBRE DE TETRAEDRES A DISTANCE CROISSANTE
C MINTET  : NO DES TETRAEDRES A DISTANCE CROISSANTE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 2005
C2345X7..............................................................012
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      INTEGER           NOSMIN(MXSMIN), NODSNO(MXSMIN)
      INTEGER           N1TETS(*),MINTET(*)
      DOUBLE PRECISION  DISTMIN(MXSMIN)
      INTEGER           NBIPAV(3), N1SPAVE(0:*), NOPTSUIV(*)
      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3)
      DOUBLE PRECISION  XYZ(3), PTXYZD(4,*)
C
C     RECHERCHE DES SOMMETS LES PLUS PROCHES A UNE DISTANCE D'UN PAVE
      CALL DMINSTPAV( HEXAPAVE, NBIPAV, ECHPAV, N1SPAVE, NOPTSUIV,
     %                XYZ, PTXYZD,
     %                MXSMIN, NBSMIN, NOSMIN, NODSNO, DISTMIN )
C
C     PASSAGE AUX TETRAEDRES POINTES PAR CES SOMMETS
      NBTETD = 0
      DO 10 NS=1,NBSMIN
C
C        LE TETRAEDRE
         NT = N1TETS( NOSMIN( NODSNO(NS) ) )
         IF( NT .LE. 0 ) GOTO 10
         DO N=1,NBTETD
            IF( NT .EQ. MINTET(N) ) GOTO 10
         ENDDO
C
C        CE TETRAEDRE NOUVEAU EST A AJOUTER A LA LISTE
         NBTETD = NBTETD + 1
         MINTET( NBTETD ) = NT
C
 10   CONTINUE
C
      RETURN
      END
