      SUBROUTINE DSTETO( NS,     NBSOTE, N1TEVI, NSTETR, NBDM, NUDMEF,
     %                   NO1TSO, N1TESO, NOTESO, QUALIT, NUMATE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    DETRUIRE LES TETRAEDRES DE SOMMET NS
C -----
C
C ENTREES:
C --------
C NS     : NUMERO DANS XYZSOM DU POINT D'ETOILE A TRAITER
C NBSOTE : VALEUR MAXIMALE DE DECLARATION DU PREMIER INDICE DE NSTETR(>3)
C N1TEVI : NUMERO 1-ER TETRAEDRE VIDE DE NSTETR
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE
C NBDM   : 0 SI 1 MATERIAU=VOLUME, SINON NOMBRE DE MATERIAUX DU VOLUME
C NUDMEF : NUMERO DE MATERIAU DE CHAQUE TETRAEDRE DU MAILLAGE
C          ATTENTION: CE TABLEAU EXISTE SEULEMENT SI NBDM>0
C NO1TSO : NUMERO DU 1-ER TETRAEDRE DANS NOTESO DE CHAQUE SOMMET
C N1TESO : NUMERO 1-ER TETRAEDRE VIDE DANS NOTESO
C NOTESO : NOTESO(1,*) NUMERO DANS NSTETR DU TETRAEDRE
C          NOTESO(2,*) NUMERO DANS NOTESO DU TETRAEDRE SUIVANT
C                      0 SI C'EST LE DERNIER
C
C SORTIE :
C --------
C NUMATE : -2 SI LES TETRAEDRES NE SONT PAS DANS UN SEUL MATERIAU
C           0 SI PAS DE MATERIAUX
C          >0 NUMERO DE L'UNIQUE MATERIAU DES TETRAEDRES DE SOMMET NS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 1991
C MODIFS : ALAIN PERRONNET LJLL UPMC et St Pierre du Perray    Juin 2008
C2345X7..............................................................012
      INTEGER           NSTETR(NBSOTE,*),
     %                  NUDMEF(*),
     %                  NO1TSO(*),
     %                  NOTESO(2,*)
      REAL              QUALIT(*)
C
C     TOUS LES TETRAEDRES DE SOMMET NS DOIVENT ETRE DANS LE MEME MATERIAU
      NUMATE = 0
      IF( NBDM .GT. 0 ) THEN
C
C        POSITION DANS NOTESO DU 1-ER TETRAEDRE DE SOMMET NS
         NDT  = NO1TSO( NS )
C
C        NO DU MATERIAU DU 1-ER TETRAEDRE
         NUMATE = NUDMEF( NOTESO(1,NDT) )
C
C        TANT QU'IL EXISTE UN TETRAEDRE DE SOMMET NS FAIRE
 10      IF( NDT .GT. 0 ) THEN
C
C           LE NUMERO DU TETRAEDRE DANS NSTETR
            NT = NOTESO(1,NDT)
C
            IF( NUMATE .NE. NUDMEF(NT) ) THEN
               NUMATE = -2
               RETURN
            ENDIF
C
C           LE TETRAEDRE SUIVANT  ( VALEUR ECRASEE PAR DS1TET )
            NDT = NOTESO(2,NDT)
C
            GOTO 10
         ENDIF
      ENDIF
C
C     ICI TOUS LES TETRAEDRES SONT DANS UN SEUL MATERIAU
      GRAND = RINFO( 'GRAND' )
C
C     POSITION DANS NOTESO DU 1-ER TETRAEDRE DE SOMMET NS
      NDT  = NO1TSO( NS )
C
C     TANT QU'IL EXISTE UN TETRAEDRE DE SOMMET NS FAIRE
 20   IF( NDT .GT. 0 ) THEN
C
C        LE NUMERO DU TETRAEDRE DANS NSTETR
         NT = NOTESO(1,NDT)
C
C        LE TETRAEDRE SUIVANT  ( VALEUR ECRASEE PAR DS1TET )
         NDT  = NOTESO(2,NDT)
C
C        LE CHAINAGE DE NT EST SUPPRIME DES TETRAEDRES DE SES 4 SOMMETS
         CALL DS1TET( NT,     NBSOTE, N1TEVI, NSTETR,
     %                NO1TSO, N1TESO, NOTESO )
C
C        MISE A JOUR QUALITE
         QUALIT( NT ) = GRAND
C
C        EVENTUEL NUMERO DU MATERIAU
         IF( NBDM .GT. 0 ) NUDMEF( NT ) = 0
         GOTO 20
      ENDIF
C
C     ICI NO1TSO(NS)=0  DE PAR LES DESTRUCTIONS DES TETRAEDRES
      RETURN
      END
