      SUBROUTINE DV2D3D( X2DY2D, ORIGIN, D2D3, XMIN, YMIN, XYMXMI,
     %                   XYZ )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : TRANSFORME (X2D,Y2D) COORDONNEES 2D DANS LE PLAN APRES
C ----- MISE A L'ECHELLE [0,2**20] EN LES COORDONNES 3D DANS LE REPERE
C       INITIAL
C
C ENTREES:
C --------
C X2DY2D : LES 2 COORDONNEES DANS LE REPERE LIE AU PLAN APRES
C          MISE A L'ECHELLE EN X ET Y
C ORIGIN : LES 3 COORDONNEES DU POINT ORIGINE DU REPERE DANS LE PLAN
C D2D3   : MATRICE DE CHANGEMENT DU REPERE XYZ EN CELUI LIE AU PLAN
C XMIN   : VAUT ZERO APRES MISE A L'ECHELLE EN X DANS LE PLAN XY
C YMIN   : VAUT ZERO APRES MISE A L'ECHELLE EN Y DANS LE PLAN XY
C XYMXMI : XMIN + XYMXMI VAUT 2**20 APRES TRANSFORMATION
C
C SORTIES:
C --------
C XYZ    : LES 3 COORDONNES DU POINT 3D
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS        MARS 1995
C2345X7..............................................................012
      REAL              X2DY2D(2), ORIGIN(3), XYZ(3), XY(2)
      DOUBLE PRECISION  D2D3(3,3)
C
C     INVERSION DE LA MISE A L'ECHELLE EN X ET Y ENTRE [0,2**20]
      XY(1) = ECHMIS( X2DY2D(1), XMIN, XYMXMI )
      XY(2) = ECHMIS( X2DY2D(2), YMIN, XYMXMI )
C
C     LES COORDONNEES 3D DU POINT XY DANS LE REPERE INITIAL
      CALL CH2D3D( ORIGIN, D2D3, XY, XYZ )
      END
