      SUBROUTINE EC2DIAGRTR( COSMAXPL, NBSOM,  XYZSOM, NBTRQM, NOTRQM,
     %                       NBTRIA, NOTRIA, NBCHGT )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETRIANGULATION POUR ECHANGER LA DIAGONALE DE 2 TRIANGLES
C -----    AYANT UNE ARETE COMMUNE DES TRIANGLES DU TABLEAU NOTRQM
C
C ENTREES:
C --------
C COSMAXPL: COSINUS DE L'ANGLE DES NORMALES AUX 2 PLANS DES TRIANGLES
C           AU DESSUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES COPLANAIRES
C           COSMAXPL = COS( ANGL2P ) AVEC
C ANGL2P : ANGLE MAXIMAL EN RADIANS ENTRE LES PLANS DE 2 TRIANGLES
C          POUR LES CONSIDERER COPLANAIRES
C NBSOM  : NOMBRE DE SOMMETS DU MAILLAGE
C XYZSOM : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C NBTRQM : NOMBRE DE TRIANGLES A TRAITER
C NOTRQM : NUMERO DANS NOTRIA DES TRIANGLES A TRAITER
C
C MODIFIES :
C ----------
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C NOTRIA : LISTE CHAINEE DES TRIANGLES
C                 ------- ------- ------- -------- -------- --------
C  PAR TRIANGLE : SOMMET1 SOMMET2 SOMMET3 TR_VOIS1 TR_VOIS2 TR_VOIS3
C                 ------- ------- ------- -------- -------- --------
C                 SOMMET    EST LE NUMERO DU SOMMET
C                 TR_VOIS i EST LE NUMERO DANS NOTRIA DU TRIANGLE
C                                  ADJACENT PAR L'ARETE i
C SORTIES:
C --------
C NBCHGT : NOMBRE DE CHANGEMENT DE DIAGONALE POUR 2 TRIANGLES ADJACENTS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    OCTOBRE 1993
C....................................................................012
      REAL      XYZSOM(3,NBSOM)
      INTEGER   NOTRQM(NBTRQM), NOTRIA(6,NBTRIA)

C     NOMBRE DE CHANGEMENTS DE DIAGONALE DE 2 TRIANGLES
      NBCHGT = 0
      DO NT=1,NBTRQM
C
C        LE NUMERO DU TRIANGLE DANS NOTRIA
         NT1 = NOTRQM( NT )
C
C        PARCOURS DES 3 ARETES DU TRIANGLE NT1
         DO I=1,3
C           ECHANGE EVENTUEL DE LA DIAGONALE ARETE I DE NT1
C           AVEC LE TRIANGLE OPPOSE S'IL EXISTE
            CALL EC2DIA( COSMAXPL, NT1, I, NOTRIA, NBSOM, XYZSOM,
     %                   NT2 )
            IF( NT2 .GT. 0 ) NBCHGT = NBCHGT + 1
         ENDDO

      ENDDO

      RETURN
      END
