      SUBROUTINE EC2DGTR( COSMAXPL, XYZSOM, M1TRIA4, NOTRIA,
     %                    MXGRTR,   NBGRTR, NOGRTR,
     %                    L1ARET,   L2ARET, MNARET, NBDIAG )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SI POSSIBLE ECHANGER L'ARETE COMMUNE A 2 TRIANGLES PAR L'AUTRE
C -----    DIAGONALE SI L'ANGLE DU DIEDRE EST INFERIEUR A ANGL2P POUR
C          TOUTES LES ARETES DU GROUPE DE TRIANGLES DEFINI PAR NOGRTR

C          ATTENTION: DANS R3 LES 4 SOMMETS DES 2 TRIANGLES
C                     FORMENT UN TETRAEDRE QUI DISPARAIT OU
C                     APPARAIT SELON LE CHANGEMENT DE DIAGONALE
C                     D'OU LE CONTROLE DE COPLANEARITE EFFECTUE
C ENTREES:
C --------
C COSMAXPL: COSINUS DE L'ANGLE DES NORMALES AUX 2 PLANS DES TRIANGLES
C           AU DESSUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES COPLANAIRES
C           COSMAXPL = COS( ANGL2P ) AVEC
C           ANGL2P = ANGLE MAXIMAL EN RADIANS ENTRE LES PLANS DE 2 TRIANGLES
C           POUR LES CONSIDERER COPLANAIRES
C XYZSOM  : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C M1TRIA4 : =4 NOMBRE DE NUMEROS D'UN TRIANGLE DU TABLEAU NOTRIA
C NOTRIA  : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES TRIANGLES
C MXGRTR  : NOMBRE MAXIMAL DE NUMERO NOTRIA DE TRIANGLES DU TABLEAU NOGRTR
C NBGRTR  : NOMBRE DE NUMEROS   DANS NOTRIA DE TRIANGLES DU TABLEAU NOGRTR

C MODIFIES:
C ---------
C NOTRIA  : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES NBGRTR TRIANGLES
C NOGRTR  : NUMERO NOTRIA DES TRIANGLES DU GROUPE

C SORTIES:
C --------
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU LARETE (=3+MXTRAR)
C L2ARET : NOMBRE MAXIMUM D'ARETES  DU TABLEAU LARETE
C MNARET : ADRESSE MCN DU TABLEAU LARETE=MCN(MNARET) DES ARETES DU MAILLAGE
C  ATTENTION: IL EST SUPPOSE A JOUR. IL N'EST PAS RECALCULE ICI
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE I
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER  TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE
C          LARETE(4:L1ARET,I)= NUMERO DU EME TRIANGLE CONTENANT CETTE ARETE

C NBDIAG : NOMBRE D'ECHANGES DE DIAGONALES ENTRE 2 TRIANGLES ADJACENTS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET Saint Pierre du Perray               Mars 2020
C....................................................................012
      include"./incl/langue.inc"
      include"./incl/pp.inc"
      COMMON   MCN(MOTMCN)
      INTEGER  NOTRIA(M1TRIA4,*), NOGRTR(MXGRTR)
      REAL     XYZSOM(3,*)

      NBDIAG = 0
      IF( NBGRTR .LE. 0 ) GOTO 9999

      LIBREA = L2ARET

      DO 50 NT = 1, NBGRTR

         NTR = NOGRTR( NT )
         IF( NOTRIA(1,NTR) .LE. 0 ) GOTO 50

         DO 20 NA = 1, 3

C           RECHERCHE DU TRIANGLE AJACENT A NTR PAR L'ARETE NA
            CALL NUQTADAR( NA,  NTR, NOTRIA, L1ARET,L2ARET, MCN(MNARET),
     %                     NAR, NTRAD )
            IF( NAR .LE. 0 .OR. NTRAD .LE. 0 ) THEN
C              ARETE SANS ou TROP DE TRIANGLES ADJACENTS. PAS D'ECHANGE
               GOTO 20
            ENDIF

C           TENTATIVE D'ECHANGE DES DIAGONALES DU QUADRANGLE NTR+NTRAD
C           SUR LUI-MEME
            CALL EC2D2TR( COSMAXPL, XYZSOM, NTR,    NTRAD,  NOTRIA,
     %                    LIBREA,   L1ARET, L2ARET, MCN(MNARET),
     %                    MODIF )
            NBDIAG = NBDIAG + MODIF

 20      ENDDO

 50   ENDDO

      IF( NBDIAG .GT. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            PRINT*,'ec2dgtr:',NBDIAG,' ECHANGES DES DIAGONALES DE 2 TRIA
     %NGLES ADJACENTS'
         ELSE
            PRINT*,'ec2dgtr:',NBDIAG,' DIAGONAL SWAPS of 2 ADJACENT TRIA
     %NGLES'
         ENDIF
      ENDIF

 9999 RETURN
      END
