      SUBROUTINE EC2DTTR( COSMAXPL, XYZSOM, M1TRIA4, NBTRIA, NOTRIA,
     %                    MXTRAR,   L1ARET, L2ARET,  MNARET,
     %                    NBDIAG,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SI POSSIBLE ECHANGER L'ARETE COMMUNE A 2 TRIANGLES PAR L'AUTRE
C -----    DIAGONALE SI L'ANGLE DU DIEDRE EST INFERIEUR A ANGL2P

C          ATTENTION: DANS R3 LES 4 SOMMETS DES 2 TRIANGLES
C                     FORMENT UN TETRAEDRE QUI DISPARAIT OU
C                     APPARAIT SELON LE CHANGEMENT DE DIAGONALE
C ENTREES:
C --------
C COSMAXPL: COSINUS DE L'ANGLE DES NORMALES AUX 2 PLANS DES TRIANGLES
C           AU DESSUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES COPLANAIRES
C           COSMAXPL = COS( ANGL2P ) AVEC
C           ANGL2P = ANGLE MAXIMAL EN RADIANS ENTRE LES PLANS DE 2 TRIANGLES
C           POUR LES CONSIDERER COPLANAIRES
C XYZSOM  : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C M1TRIA4 : =4 NOMBRE DE NUMEROS D'UN TRIANGLE DU TABLEAU NOTRIA
C NOTRIA  : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES NBTRIA TRIANGLES
C MXTRAR  : NOMBRE MAXIMAL DE TRIANGLES ADJACENTS PAR UNE ARETE DANS LARETE()

C SORTIES:
C --------
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU LARETE (=3+MXTRAR)
C L2ARET : NOMBRE MAXIMUM D'ARETES  DU TABLEAU LARETE
C MNARET : ADRESSE MCN DU TABLEAU LARETE DES ARETES DU MAILLAGE
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE I
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER  TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE
C          LARETE(4:3+MXTRAR,I)= NUMERO DU EME TRIANGLE CONTENANT CETTE ARETE

C NBDIAG : NOMBRE D'ECHANGES DE DIAGONALES ENTRE 2 TRIANGLES ADJACENTS
C IERR   : =0 PAS D'ERREUR DETECTEE
C          =5 TROP d'EF POUR UNE ARETE . PAS D'ECHANGE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET Veulettes sur mer                   Avril 2017
C MODIFS: ALAIN PERRONNET Saint Pierre du Perray               Mars 2020
C....................................................................012
      include"./incl/langue.inc"
      include"./incl/pp.inc"
      COMMON   MCN(MOTMCN)
      INTEGER  NOTRIA(M1TRIA4,*)
      REAL     XYZSOM(3,*)

C     EVENTUELLE DESTRUCTION DU TABLEAU DES ARETES DU MAILLAGE
      IF( MNARET .GT. 0 ) CALL TNMCDS( 'ENTIER', L1ARET*L2ARET, MNARET )

C     CONSTRUCTION DU TABLEAU DES ARETES DE LA TRIANGULATION
      CALL GEARSU( M1TRIA4, NBTRIA, NOTRIA, MXTRAR,
     %             L1ARET, L2ARET, MNARET, IERR )
C     ARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C     ARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C     ARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C     ARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                 0 SI PAS DE 1-ER  TRIANGLE
C     ARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                 0 SI PAS DE 2-EME TRIANGLE
C     ARETE(3+MXTRAR,I)= NO DU MXTRAR-EME TRIANGLE CONTENANT CETTE ARETE
C                        0 SI PAS DE MXTRAR-EME TRIANGLE
C     puis
C     ARETE(6,I)= NOMBRE DE POINTS AJOUTES SUR L'ARETE I POUR TAILLE_IDEALE
C     ARETE(7,I)= NUMERO XYZSOM DU DERNIER POINT AJOUTE SUR L'ARETE I

      IF( IERR .NE. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            PRINT*,'ec2dttr: 1 ARETE EST PARTAGEE PAR >',MXTRAR,' EF'
            PRINT*,'ec2dttr: OPTION 30 IMPOSSIBLE DANS CE CAS'
            PRINT*,'ec2dttr: AUGMENTER MXTRAR=',MXTRAR
         ELSE
            PRINT*,'ec2dttr: ONE EDGE IS SHARED BY >',MXTRAR,' FE'
            PRINT*,'ec2dttr: OPTION 30 is IMPOSSIBLE IN THIS CASE'
            PRINT*,'ec2dttr: AUGMENT MXTRAR=',MXTRAR
         ENDIF
         IF( MNARET .GT. 0 ) THEN
C           DESTRUCTION DU TABLEAU DES ARETES
            CALL TNMCDS( 'ENTIER', L1ARET*L2ARET, MNARET )
         ENDIF
         IERR = 5
         GOTO 9999
      ENDIF

      NBDIAG = 0
      NBARET = 0
      LIBREA = L2ARET
      MNAR   = MNARET - L1ARET

      DO NAR = 1, L2ARET

C        L'ARETE NAR
         MNAR = MNAR + L1ARET
         IF( MCN( MNAR ) .GT. 0 ) THEN

C           UNE ARETE ACTIVE DE PLUS
            NBARET = NBARET + 1

C           L'EVENTUEL SECOND TRIANGLE AVEC CETTE ARETE
            NT2  = ABS( MCN( MNAR+4 ) )
            IF( NT2 .GT. 0 ) THEN

C              LE PREMIER TRIANGLE AVEC CETTE ARETE
               NT1 = ABS( MCN( MNAR+3 ) )

C              TENTATIVE D'ECHANGE DES DIAGONALES DU QUADRANGLE NT1+NT2
C              SUR LUI-MEME
               CALL EC2D2TR( COSMAXPL, XYZSOM, NT1,    NT2,  NOTRIA,
     %                       LIBREA,   L1ARET, L2ARET, MCN(MNARET)
     %                      ,MODIF )
               NBDIAG = NBDIAG + MODIF

            ENDIF

         ENDIF

      ENDDO

      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'ec2dttr:',NBDIAG,' ECHANGES DES DIAGONALES DE 2 TRIANGL
     %ES ADJACENTS parmi',NBARET,' ARETES'
      ELSE
         PRINT*,'ec2dttr:',NBDIAG,' DIAGONAL SWAPS of 2 ADJACENT TRIANGL
     %ES among',NBARET,' EDGES'
      ENDIF

 9999 RETURN
      END
