       SUBROUTINE ECHDIAP3( MNXYZS,  MNNSEF, L1ARET, L2ARET, LARETE,
     %                      NUARPRCL, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ECHANGER UNE ARETE DIAGONALE COMMUNE A 2 TRIANGLES DE R3
C -----    L'ARETE DIAGONALE EST DESIGNEE A LA SOURIS DANS R3

C ENTREES:
C --------
C MNXYZS : ADRESSE DU TABLEAU XYZSOMMET DE LA SURFACE
C MNNSEF : ADRESSE DU TABLEAU NSEF      DE LA SURFACE
C L1ARET : NOMBRE DE MOTS PAR ARET DU TABLEAU LARETE
C L2ARET : NOMBRE DE FACES DU TABLEAU LARETE
C LARETE : LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR L'ARETE SUIVANTE
C          LARETE(4:3+MXFAAR,I)= NO NOSOFA DU TRIANGLE CONTENANT L'ARETE
C          SI UNE ARETE APPARTIENT A PLUS DE MXFAAR FACES, 
C          LE NUMERO DE FACE MXFAAR EST RENDU NEGATIF POUR INDIQUER
C          QUE LA LISTE DES FACES EST INCOMPLETE

C SORTIES:
C --------
C NUARPRCL: >0 NUMERO DE L'ARETE VISIBLE LA PLUS PROCHE DU POINT CLIQUE
C              DANS LE TABLEAU LARETE
C           =0 SI PAS D'ITEM ARETE PROCHE OU ABANDON DEMANDE
C IERR    : =0 SI PAS D'ERREUR
C            1 SI ECHANGE REFUSE POUR QUADRANGLE NON CONVEXE OU DEGENERE
C            2 SI POINT DANS UN QUADRANGLE ou EF ADJACENT QUADRANGLE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : Alain PERRONNET Saint PIERRE du PERRAY           Janvier 2021
C2345X7..............................................................012
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/pp.inc"
      COMMON         MCN(MOTMCN)
      REAL          RMCN(1)
      EQUIVALENCE  (RMCN(1),MCN(1))
      INTEGER        LARETE(L1ARET,L2ARET)

      IERR = 0

C     CLIQUER SUR UNE ARETE ADJACENTE A 2 TRIANGLES
C     =============================================
      CALL SEARCLIC( RMCN(MNXYZS+WYZSOM), L1ARET, L2ARET, LARETE,
     %               NUARPRCL )
      IF( NUARPRCL .LE. 0 ) GOTO 9999

C     LES 2 SOMMETS DE L'ARETE COMMUNE
      NOSDI1 = LARETE(1,NUARPRCL)
      NOSDI2 = LARETE(2,NUARPRCL)

C     LES 2 TRIANGLES ADJACENTS A CETTE ARETE
      NOTRIA1 = LARETE(4,NUARPRCL)
      NOTRIA2 = LARETE(5,NUARPRCL)

C     ADRESSE MCN DU TABLEAU NUSOEF NO DES 4 SOMMETS DES NBTQ EF ACTUELS
      MNSOEL = MNNSEF + WUSOEF
      IF( MCN(MNSOEL+4*NOTRIA1-1) .GT. 0 .OR.
     %    MCN(MNSOEL+4*NOTRIA2-1) .GT. 0 ) THEN
         NBLGRC(NRERR)=1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1)='ARETE D''UN QUADRANGLE NON TRAITE'
         ELSE
            KERR(1)='EDGE of a QUADRANGLE NOT TREATED'
         ENDIF
         CALL LEREUR
         IERR=2
         GOTO 9999
      ENDIF

C     ICI L'ARETE NOSDI1 NOSDI2 EST UNE ARETE DES TRIANGLES NOTRIA1 et NOTRIA2
C     RECHERCHE DU NO DE SOMMET DU TRIANGLE 1 NON SUR L'ARETE COMMUNE
      MN1 = MNSOEL + 4*NOTRIA1 - 5
      DO I=1,3
         NOSTR1 = MCN(MN1+I)
         IF( NOSTR1 .NE. NOSDI1 .AND. NOSTR1 .NE. NOSDI2 ) GOTO 20
      ENDDO

C     RECHERCHE DU NO DE SOMMET DU TRIANGLE 1 NON SUR L'ARETE COMMUNE
 20   MN2 = MNSOEL + 4*NOTRIA2 - 5
      DO I=1,3
         NOSTR2 = MCN(MN2+I)
         IF( NOSTR2 .NE. NOSDI1 .AND. NOSTR2 .NE. NOSDI2 ) GOTO 40
      ENDDO

C     LE QUADRANGLE FORME DES 2 TRIANGLES EST IL ECHANGEABLE?
 40   CALL ECHDIA( NDIM,    NOSDI1,  NOSDI2, NOSTR1, NOSTR2,
     %             NOTRIA1, NOTRIA2, MNXYZS, MNNSEF, IERR )
C
 9999 RETURN
      END
