      SUBROUTINE F0PTVPSI( QUAMINEX, XYZPT,  PTXYZD, N1FEOC, NFETOI,
     %                     MXVPSI,   NBVPSI, NFVPSI, NBFETO,
     %                     VETXYZ,   QUAMIN )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C  BUT :   DETERMINER L'ENSEMBLE DES FACES DE L'ETOILE FORMANT
C ------   AVEC LE POINT XYZPT DES TETRAEDRES DE VOLUMES>0
C          SANS INTERSECTION AVEC LES FACES DE L'ETOILE

C ENTREES:
C --------
C QUAMINEX:QUALITE MINIMALE EXIGEE POUR CREER UN TETRAEDRE
C XYZPT  : COORDONNEES XYZ DU POINT A TESTER COMME CENTRE DE TETRAEDRISATION
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C NFETOI : LES FACES TRIANGULAIRES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE >0 EN SORTIE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C          S1S2 x S1S3 VERS L'INTERIEUR DE L'ETOILE
C MXVPSI : NOMBRE MAXIMAL DE FACES DU TABLEAU NFVPSI

C SORTIES:
C --------
C NBVPSI : NOMBRE DE TETRAEDRES DE VOLUME>0 SANS INTERSECTION
C          AVEC LES FACES DE L'ETOILE
C          = -MXVPSI SI NBVPSI>MXVPSI
C NFVPSI : NUMERO NFETOI DES NBVPSI FACES DONNANT AVEC XYZPT UN VOLUME>0
C          ET SANS INTERSECTION AVEC LES FACES DE L'ETOILE
C NBFETO : NOMBRE DE FACES DE L'ETOILE NFETOI A PARTIR DE N1FEOC
C VETXYZ : VOLUME DE L'ETOILE DE CENTRE XYZPT DES TETRAEDRES ACCEPTES
C QUAMIN : MINIMUM DES QUALITES DES TETRAEDRES NFVPSI-XYZPT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY     Aout 2015
C2345X7..............................................................012
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE
ccc      LOGICAL                   TRACTE0

      DOUBLE PRECISION  PTXYZD(4,*), XYZPT(3)
      INTEGER           NFETOI(5,*), NFVPSI(MXVPSI)

      DOUBLE PRECISION  V, VETXYZ, SURFTR(4), ARMIN, ARMAX
ccc      CHARACTER*72      KTITRE

C     PARCOURS DES FACES DE L'ETOILE
      NBFETO = 0
      NBVPSI = 0
      VETXYZ = 0D0
      QUAMIN = 2.0
      NF1    = N1FEOC

 3    IF( NF1 .GT. 0 ) THEN

C        LE VOLUME DU TETRAEDRE FACE NF1 + XYZPT EST-IL STRICTEMENT POSITIF
C        SANS INTERSECTION AVEC LES AUTRES FACES?
C        ------------------------------------------------------------------
C        LE NO DES 3 SOMMETS DE LA FACE
C        S1S2xS1S3 EST LA NORMALE DIRIGEE VERS L'INTERIEUR DE L'ETOILE
         NBFETO = NBFETO + 1
         NS1 = NFETOI(2,NF1)
         NS2 = NFETOI(3,NF1)
         NS3 = NFETOI(4,NF1)

C        QUALITE DU TETRAEDRE NF1-XYZPT
         CALL QUATETD( PTXYZD(1,NS1 ), PTXYZD(1,NS2 ),
     %                 PTXYZD(1,NS3 ), XYZPT,
     %                 ARMIN, ARMAX, SURFTR, V, QUALIT )

C        LA QUALITE DU TETRAEDRE NF1-XYZPT DOIT ETRE >QUAMINEX
         IF( QUALIT .GT. QUAMINEX ) THEN

C           LE TETRAEDRE NFETOI(NF1)-XYZPT A UN VOLUME>0
C           INTERSECTE T IL UNE FACE DE L'ETOILE?
            NF2 = N1FEOC
 5          IF( NF2 .GT. 0 ) THEN
               IF( NF2 .NE. NF1 ) THEN

C                 INTERSECTION TRIANGLE-TETRAEDRE?
                  CALL INTRITET( PTXYZD(1,NFETOI(2,NF2)),
     %                           PTXYZD(1,NFETOI(3,NF2)),
     %                           PTXYZD(1,NFETOI(4,NF2)),
     %                           PTXYZD(1,NS1),
     %                           PTXYZD(1,NS2),
     %                           PTXYZD(1,NS3),
     %                           XYZPT,   LINTER )
                  IF( LINTER  .NE. 0 ) THEN
C                    OUI: UN POINT D'INTERSECTION=>ABANDON DE CETTE FACE
                     GOTO 8
                  ENDIF

               ENDIF

C              PASSAGE A LA FACE SUIVANTE DE L'ETOILE
               NF2 = NFETOI(5,NF2)
               GOTO 5
            ENDIF

C           NF1-XYZPT FORME UN TETRAEDRE DE VOLUME>0 ET
C           INTERSECTE AUCUNE FACE DE L'ETOILE
            IF( NBVPSI .GE. MXVPSI ) THEN
            PRINT*,'PB f0ptvpsi: MXVPSI=',MXVPSI,' ATTEINT. A AUGMENTER'
               NBVPSI = -NBVPSI
               GOTO 9999
            ENDIF

C           UN TETRAEDRE DE VOLUME>0 SANS INTERSECTION DE PLUS
            NBVPSI = NBVPSI + 1
            NFVPSI( NBVPSI ) = NF1

C           TETRAEDRE ACCEPTE: QUALITE MINIMUM DES TETRAEDRES ACCEPTES
            QUAMIN = MIN( QUAMIN, QUALIT )

C           VOLUME DE L'ETOILE DE CENTRE XYZPT DES TETRAEDRES ACCEPTES
            VETXYZ = VETXYZ + ABS( V )

         ENDIF

C        PASSAGE A LA FACE SUIVANTE DE L'ETOILE
 8       NF1 = NFETOI(5,NF1)
         GOTO 3

      ENDIF

C     ICI IL EXISTE NBVPSI TETRAEDRES DE VOLUME POSITIF
C     SANS INTERSECTION AVEC LES FACES DE L'ETOILE A CREER

ccc 9999 IF( NBVPSI .NE. NBFETO ) THEN
ccc         TRACTE0 = TRACTE
ccc         TRACTE  = .TRUE.
ccc         KTITRE = 'En sortie de f0ptvpsi: NBVPSI=       NBFETO=       QU
ccc     %AMIN=       '
ccc         WRITE(KTITRE(31:36), '(I6)'   ) NBVPSI
ccc         WRITE(KTITRE(45:50), '(I6)'   ) NBFETO
ccc         WRITE(KTITRE(59:66), '(F8.3)' ) QUAMIN
ccc         CALL SANSDBL( KTITRE, L )
ccc         PRINT*, KTITRE(1:L)
ccc         CALL TRFETO3( KTITRE(1:L), XYZPT,  XYZPT,  PTXYZD,
ccc     %                 N1FEOC, NFETOI, NBVPSI, NFVPSI )
ccc         TRACTE = TRACTE0
ccc      ENDIF

 9999 RETURN
      END
