      SUBROUTINE F0TRTE( LETREE, PXYD,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   NOARST,
     %                   NBTR,   NUTR,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    FORMER LE OU LES TRIANGLES DU TRIANGLE EQUILATERAL LETREE
C -----    LES POINTS INTERNES AU TE DEVIENNENT DES SOMMETS DES
C          SOUS-TRIANGLES DU TE
C
C ENTREES:
C --------
C LETREE : ARBRE-4 DES TRIANGLES EQUILATERAUX (TE) FOND DE LA TRIANGULATION
C          SI LETREE(0)>0 ALORS
C             LETREE(0:3) : NO (>0) LETREE DES 4 SOUS-TRIANGLES DU TRIANGLE J
C          SINON
C             LETREE(0:3) :-NO PXYD DES 1 A 4 POINTS INTERNES AU TRIANGLE J
C                           0  SI PAS DE POINT
C                         ( LE TE EST UNE FEUILLE DE L'ARBRE )
C          LETREE(4) : NO LETREE DU SUR-TRIANGLE DU TRIANGLE J
C          LETREE(5) : 0 1 2 3 NO DU SOUS-TRIANGLE J POUR SON SUR-TRIANGLE
C          LETREE(6:8) : NO PXYD DES 3 SOMMETS DU TRIANGLE J
C PXYD   : TABLEAU DES X  Y  DISTANCE_SOUHAITEE DE CHAQUE SOMMET
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOSOAR
C MXSOAR : NOMBRE MAXIMAL D'ARETES STOCKABLES DANS LE TABLEAU NOSOAR
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXARTR : NOMBRE MAXIMAL DE TRIANGLES STOCKABLES DANS LE TABLEAU NOARTR
C
C MODIFIES:
C ---------
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C          UNE ARETE I DE NOSOAR EST VIDE  <=>  NOSOAR(1,I)=0
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = (NOSOAR(1)+NOSOAR(2)) MODULO MXSOAR
C          SOMMET 1 = 0 SI ARETE VIDE => SOMMET 2 = ARETE VIDE SUIVANTE
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C NOARST : NOARST(I) NUMERO D'UNE ARETE DE SOMMET I
C
C SORTIES:
C --------
C NBTR   : NOMBRE DE SOUS-TRIANGLES DU TE, TRIANGULATION DU TE
C NUTR   : NUMERO DES NBTR SOUS-TRIANGLES DU TE DANS LE TABLEAU NOARTR
C IERR   : =0 SI PAS D'ERREUR
C          =1 SI LE TABLEAU NOSOAR EST SATURE
C          =2 SI LE TABLEAU NOARTR EST SATURE
C          =3 SI AUCUN DES TRIANGLES NE CONTIENT L'UN DES POINTS INTERNES AU TE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1997
C....................................................................012
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      DOUBLE PRECISION  PXYD(3,*)
      INTEGER           LETREE(0:8),
     %                  NOSOAR(MOSOAR,MXSOAR),
     %                  NOARTR(MOARTR,MXARTR),
     %                  NOARST(*),
     %                  NUTR(1:NBTR)
      INTEGER           NUARCO(3)
C
C     LE NUMERO NT DU TRIANGLE DANS LE TABLEAU NOARTR
      IF( N1ARTR .LE. 0 ) THEN
C        TABLEAU NOARTR SATURE
         WRITE(IMPRIM,*) 'F0TRTE: TABLEAU NOARTR SATURE'
         IERR = 2
         RETURN
      ENDIF
      NT = N1ARTR
C     LE NUMERO DU NOUVEAU PREMIER TRIANGLE LIBRE DANS NOARTR
      N1ARTR = NOARTR( 2, N1ARTR )
C
C     FORMATION DU TRIANGLE = LE TRIANGLE EQUILATERAL LETREE
      DO 10 I=1,3
         IF( I .NE. 3 ) THEN
            I1 = I + 1
         ELSE
            I1 = 1
         ENDIF
C        AJOUT EVENTUEL DE L'ARETE SI SI+1 DANS LE TABLEAU NOSOAR
         CALL FASOAR( LETREE(5+I), LETREE(5+I1), NT, -1, 0,
     %                MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %                NUARCO(I), IERR )
         IF( IERR .NE. 0 ) RETURN
 10   CONTINUE
C
C     LE TRIANGLE NT EST FORME DANS LE TABLEAU NOARTR
      DO 20 I=1,3
C        LETREE(5+I) EST LE NUMERO DU SOMMET 1 DE L'ARETE I DU TE
         IF( LETREE(5+I) .EQ. NOSOAR(1,NUARCO(I)) ) THEN
            LESIGN =  1
         ELSE
            LESIGN = -1
         ENDIF
C        L'ARETE NS1-NS2 DANS NOSOAR EST CELLE DU COTE DU TE
         NOARTR( I, NT ) = LESIGN * NUARCO(I)
 20   CONTINUE
C
C     TRIANGULATION DU TE=TRIANGLE NT PAR AJOUT DES POINTS INTERNES DU TE
      NBTR    = 1
      NUTR(1) = NT
      CALL TRPITE( LETREE, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             NBTR,   NUTR,   IERR )
      END
