      SUBROUTINE F2TRTE( LETREE, PXYD,   MILIEU,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   NOARST,
     %                   NBTR,   NUTR,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    FORMER LES TRIANGLES DU TRIANGLE EQUILATERAL LETREE
C -----    A PARTIR DE 2 MILIEUX DES COTES DU TE
C          ET DES POINTS INTERNES AU TE
C          ILS DEVIENNENT TOUS DES SOMMETS DES SOUS-TRIANGLES DU TE
C
C ENTREES:
C --------
C LETREE : ARBRE-4 DES TRIANGLES EQUILATERAUX (TE) FOND DE LA TRIANGULATION
C          SI LETREE(0)>0 ALORS
C             LETREE(0:3) : NO (>0) LETREE DES 4 SOUS-TRIANGLES DU TRIANGLE J
C          SINON
C             LETREE(0:3) :-NO PXYD DES 1 A 4 POINTS INTERNES AU TRIANGLE J
C                           0  SI PAS DE POINT
C                         ( LE TE EST UNE FEUILLE DE L'ARBRE )
C          LETREE(4) : NO LETREE DU SUR-TRIANGLE DU TRIANGLE J
C          LETREE(5) : 0 1 2 3 NO DU SOUS-TRIANGLE J POUR SON SUR-TRIANGLE
C          LETREE(6:8) : NO PXYD DES 3 SOMMETS DU TRIANGLE J
C PXYD   : TABLEAU DES X  Y  DISTANCE_SOUHAITEE DE CHAQUE SOMMET
C MILIEU : MILIEU(I) NUMERO DANS PXYD DU MILIEU DE L'ARETE I DU TE
C                    0 SI PAS DE MILIEU DU COTE I A AJOUTER
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOSOAR
C MXSOAR : NOMBRE MAXIMAL D'ARETES STOCKABLES DANS LE TABLEAU NOSOAR
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXARTR : NOMBRE MAXIMAL DE TRIANGLES STOCKABLES DANS LE TABLEAU NOARTR
C
C MODIFIES:
C ---------
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C          UNE ARETE I DE NOSOAR EST VIDE  <=>  NOSOAR(1,I)=0
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = (NOSOAR(1)+NOSOAR(2)) MODULO MXSOAR
C          SOMMET 1 = 0 SI ARETE VIDE => SOMMET 2 = ARETE VIDE SUIVANTE
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C NOARST : NOARST(NP) NUMERO D'UNE ARETE DU SOMMET NP
C
C SORTIES:
C --------
C NBTR   : NOMBRE DE SOUS-TRIANGLES DU TE, TRIANGULATION DU TE
C NUTR   : NUMERO DES NBTR SOUS-TRIANGLES DU TE DANS LE TABLEAU NOARTR
C IERR   : =0 SI PAS D'ERREUR
C          =1 SI LE TABLEAU NOSOAR EST SATURE
C          =2 SI LE TABLEAU NOARTR EST SATURE
C          =3 SI AUCUN DES TRIANGLES NE CONTIENT L'UN DES POINTS INTERNES AU TE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1997
C....................................................................012
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      DOUBLE PRECISION  PXYD(3,*)
      INTEGER           LETREE(0:8),
     %                  MILIEU(3),
     %                  NOSOAR(MOSOAR,MXSOAR),
     %                  NOARTR(MOARTR,MXARTR),
     %                  NOARST(*),
     %                  NUTR(1:NBTR)
C
      INTEGER           NOSOTR(3), NUARCO(7)
C
C     LE NUMERO DES 3 TRIANGLES A CREER DANS LE TABLEAU NOARTR
      DO 5 NBTR=1,3
         IF( N1ARTR .LE. 0 ) THEN
C           TABLEAU NOARTR SATURE
            IERR = 2
            RETURN
         ENDIF
         NUTR(NBTR) = N1ARTR
C        LE NOUVEAU PREMIER TRIANGLE LIBRE DANS NOARTR
         N1ARTR = NOARTR(2,N1ARTR)
 5    CONTINUE
      NBTR = 3
C
C     RECHERCHE DU PREMIER MILIEU A CREER
      DO 7 I=1,3
         IF( MILIEU(I) .NE. 0 ) GOTO 9
 7    CONTINUE
C
C     ON SE RAMENE AU SEUL CAS I=2 C-A-D LE COTE 1 N'A PAS DE MILIEU
 9    IF( I .EQ. 2 ) THEN
C        PAS DE MILIEU SUR LE COTE 1
         NOSOTR(1) = LETREE(6)
         NOSOTR(2) = LETREE(7)
         NOSOTR(3) = LETREE(8)
C        LE NUMERO PXYD DU MILIEU DU COTE 2
         NM2 = MILIEU( 2 )
C        LE NUMERO PXYD DU MILIEU DU COTE 3
         NM3 = MILIEU( 3 )
      ELSE IF( MILIEU(2) .NE. 0 ) THEN
C        PAS DE MILIEU SUR LE COTE 3
         NOSOTR(1) = LETREE(8)
         NOSOTR(2) = LETREE(6)
         NOSOTR(3) = LETREE(7)
C        LE NUMERO PXYD DU MILIEU DU COTE 2
         NM2 = MILIEU( 1 )
C        LE NUMERO PXYD DU MILIEU DU COTE 3
         NM3 = MILIEU( 2 )
      ELSE
C        PAS DE MILIEU SUR LE COTE 2
         NOSOTR(1) = LETREE(7)
         NOSOTR(2) = LETREE(8)
         NOSOTR(3) = LETREE(6)
C        LE NUMERO PXYD DU MILIEU DU COTE 2
         NM2 = MILIEU( 3 )
C        LE NUMERO PXYD DU MILIEU DU COTE 3
         NM3 = MILIEU( 1 )
      ENDIF
C
C     ICI SEUL LE COTE 1 N'A PAS DE MILIEU
C     NM2 EST LE MILIEU DU COTE 2
C     NM3 EST LE MILIEU DU COTE 3
C
C     AJOUT EVENTUEL DE L'ARETE S1 S2 DANS NOSOAR
      CALL FASOAR( NOSOTR(1), NOSOTR(2), NUTR(1), -1, 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(1), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     AJOUT EVENTUEL DE L'ARETE S1 S2 DANS NOSOAR
      CALL FASOAR( NOSOTR(2), NM2, NUTR(1), -1, 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(2), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     AJOUT EVENTUEL DE L'ARETE S1 NM2 DANS NOSOAR
      CALL FASOAR( NOSOTR(1), NM2, NUTR(1), NUTR(2), 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(3), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     AJOUT EVENTUEL DE L'ARETE NM2 NM3 DANS NOSOAR
      CALL FASOAR( NM3, NM2, NUTR(2), NUTR(3), 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(4), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     AJOUT EVENTUEL DE L'ARETE S1 NM3 DANS NOSOAR
      CALL FASOAR( NOSOTR(1), NM3, NUTR(2), -1, 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(5), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     AJOUT EVENTUEL DE L'ARETE NM2 S3 DANS NOSOAR
      CALL FASOAR( NM2, NOSOTR(3), NUTR(3), -1, 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(6), IERR )
C
C     AJOUT EVENTUEL DE L'ARETE NM3 S3 DANS NOSOAR
      CALL FASOAR( NOSOTR(3), NM3, NUTR(3), -1, 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(7), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     LE TRIANGLE S1 S2 NM2  OU ARETE1 ARETE2 ARETE3
      DO 20 I=1,2
C        NOSOTR(I) EST LE NUMERO DU SOMMET 1 DE L'ARETE I DU TE
         IF( NOSOTR(I) .EQ. NOSOAR(1,NUARCO(I)) ) THEN
            LESIGN = 1
         ELSE
            LESIGN = -1
         ENDIF
C        L'ARETE NS1-NS2 DANS NOSOAR EST CELLE DU COTE DU TE
         NOARTR( I, NUTR(1) ) = LESIGN * NUARCO(I)
 20   CONTINUE
      IF( NM2 .EQ. NOSOAR(1,NUARCO(3)) ) THEN
         LESIGN =  1
      ELSE
         LESIGN = -1
      ENDIF
      NOARTR( 3, NUTR(1) ) = LESIGN * NUARCO(3)
C
C     LE TRIANGLE S1 NM2 NM3
      NOARTR( 1, NUTR(2) ) = -LESIGN * NUARCO(3)
      IF( NM2 .EQ. NOSOAR(1,NUARCO(4)) ) THEN
         LESIGN =  1
      ELSE
         LESIGN = -1
      ENDIF
      NOARTR( 2, NUTR(2) ) =  LESIGN * NUARCO(4)
      NOARTR( 1, NUTR(3) ) = -LESIGN * NUARCO(4)
      IF( NM3 .EQ. NOSOAR(1,NUARCO(5)) ) THEN
         LESIGN =  1
      ELSE
         LESIGN = -1
      ENDIF
      NOARTR( 3, NUTR(2) ) = LESIGN * NUARCO(5)
C
C     LE TRIANGLE NM2 NM3 S3
      IF( NM2 .EQ. NOSOAR(1,NUARCO(6)) ) THEN
         LESIGN =  1
      ELSE
         LESIGN = -1
      ENDIF
      NOARTR( 2, NUTR(3) ) =  LESIGN * NUARCO(6)
      IF( NM3 .EQ. NOSOAR(1,NUARCO(7)) ) THEN
         LESIGN = -1
      ELSE
         LESIGN =  1
      ENDIF
      NOARTR( 3, NUTR(3) ) = LESIGN * NUARCO(7)
C
C     TRIANGULATION DES 3 SOUS-TE PAR AJOUT DES POINTS INTERNES DU TE
      CALL TRPITE( LETREE, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             NBTR,   NUTR,   IERR )
      END
