      SUBROUTINE F3TRTE( LETREE, PXYD,   MILIEU,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   NOARST,
     %                   NBTR,   NUTR,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    FORMER LES TRIANGLES DU TRIANGLE EQUILATERAL LETREE
C -----    A PARTIR DE 3 MILIEUX DES COTES DU TE
C          ET DES POINTS INTERNES AU TE
C          ILS DEVIENNENT TOUS DES SOMMETS DES SOUS-TRIANGLES DU TE
C
C ENTREES:
C --------
C LETREE : ARBRE-4 DES TRIANGLES EQUILATERAUX (TE) FOND DE LA TRIANGULATION
C          SI LETREE(0)>0 ALORS
C             LETREE(0:3) : NO (>0) LETREE DES 4 SOUS-TRIANGLES DU TRIANGLE J
C          SINON
C             LETREE(0:3) :-NO PXYD DES 1 A 4 POINTS INTERNES AU TRIANGLE J
C                           0  SI PAS DE POINT
C                         ( LE TE EST UNE FEUILLE DE L'ARBRE )
C          LETREE(4) : NO LETREE DU SUR-TRIANGLE DU TRIANGLE J
C          LETREE(5) : 0 1 2 3 NO DU SOUS-TRIANGLE J POUR SON SUR-TRIANGLE
C          LETREE(6:8) : NO PXYD DES 3 SOMMETS DU TRIANGLE J
C PXYD   : TABLEAU DES X  Y  DISTANCE_SOUHAITEE DE CHAQUE SOMMET
C MILIEU : MILIEU(I) NUMERO DANS PXYD DU MILIEU DE L'ARETE I DU TE
C                    0 SI PAS DE MILIEU DU COTE I A AJOUTER
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOSOAR
C MXSOAR : NOMBRE MAXIMAL D'ARETES STOCKABLES DANS LE TABLEAU NOSOAR
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXARTR : NOMBRE MAXIMAL DE TRIANGLES STOCKABLES DANS LE TABLEAU NOARTR
C
C MODIFIES:
C ---------
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C          UNE ARETE I DE NOSOAR EST VIDE  <=>  NOSOAR(1,I)=0
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = (NOSOAR(1)+NOSOAR(2)) MODULO MXSOAR
C          SOMMET 1 = 0 SI ARETE VIDE => SOMMET 2 = ARETE VIDE SUIVANTE
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C NOARST : NOARST(NP) NUMERO D'UNE ARETE DU SOMMET NP
C
C SORTIES:
C --------
C NBTR   : NOMBRE DE SOUS-TRIANGLES DU TE, TRIANGULATION DU TE
C NUTR   : NUMERO DES NBTR SOUS-TRIANGLES DU TE DANS LE TABLEAU NOARTR
C IERR   : =0 SI PAS D'ERREUR
C          =1 SI LE TABLEAU NOSOAR EST SATURE
C          =2 SI LE TABLEAU NOARTR EST SATURE
C          =3 SI AUCUN DES TRIANGLES NE CONTIENT L'UN DES POINTS INTERNES AU TE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1997
C....................................................................012
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      DOUBLE PRECISION  PXYD(3,*)
      INTEGER           LETREE(0:8),
     %                  MILIEU(3),
     %                  NOSOAR(MOSOAR,MXSOAR),
     %                  NOARTR(MOARTR,MXARTR),
     %                  NOARST(*),
     %                  NUTR(1:NBTR)
C
      INTEGER           NUARCO(9)
C
C     LE NUMERO DES 4 TRIANGLES A CREER DANS LE TABLEAU NOARTR
      DO 5 NBTR=1,4
         IF( N1ARTR .LE. 0 ) THEN
C           TABLEAU NOARTR SATURE
            IERR = 2
            RETURN
         ENDIF
         NUTR(NBTR) = N1ARTR
C        LE NOUVEAU PREMIER TRIANGLE LIBRE DANS NOARTR
         N1ARTR = NOARTR(2,N1ARTR)
 5    CONTINUE
      NBTR = 4
C
      DO 10 I=1,3
C        LE SOMMET SUIVANT
         IF( I .NE. 3 ) THEN
            I1 = I + 1
         ELSE
            I1 = 1
         ENDIF
C        LE SOMMET PRECEDANT
         IF( I .NE. 1 ) THEN
            I0 = I - 1
         ELSE
            I0 = 3
         ENDIF
         I3 = 3 * I
C
C        AJOUT EVENTUEL DE L'ARETE SI MI DANS NOSOAR
         CALL FASOAR( LETREE(5+I), MILIEU(I), NUTR(I), -1, 0,
     %                MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %                NUARCO(I3-2), IERR )
         IF( IERR .NE. 0 ) RETURN
C
C        AJOUT EVENTUEL DE L'ARETE MI MI-1 DANS NOSOAR
         CALL FASOAR( MILIEU(I), MILIEU(I0), NUTR(I), NUTR(4), 0,
     %                MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %                NUARCO(I3-1), IERR )
         IF( IERR .NE. 0 ) RETURN
C
C        AJOUT EVENTUEL DE L'ARETE M I-1  SI DANS NOSOAR
         CALL FASOAR( MILIEU(I0), LETREE(5+I), NUTR(I), -1, 0,
     %                MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %                NUARCO(I3), IERR )
         IF( IERR .NE. 0 ) RETURN
C
 10   CONTINUE
C
C     LES 3 SOUS-TRIANGLES PRES DES SOMMETS
      DO 20 I=1,3
C        LE SOMMET SUIVANT
         IF( I .NE. 3 ) THEN
            I1 = I + 1
         ELSE
            I1 = 1
         ENDIF
C        LE SOMMET PRECEDANT
         IF( I .NE. 1 ) THEN
            I0 = I - 1
         ELSE
            I0 = 3
         ENDIF
         I3 = 3 * I
C
C        AJOUT DU TRIANGLE  ARETE3I-2 ARETE3I-1 ARETE3I
         IF( LETREE(5+I) .EQ. NOSOAR(1,NUARCO(I3-2)) ) THEN
            LESIGN =  1
         ELSE
            LESIGN = -1
         ENDIF
         NOARTR( 1, NUTR(I) ) = LESIGN * NUARCO(I3-2)
C
         IF( MILIEU(I) .EQ. NOSOAR(1,NUARCO(I3-1)) ) THEN
            LESIGN =  1
         ELSE
            LESIGN = -1
         ENDIF
         NOARTR( 2, NUTR(I) ) = LESIGN * NUARCO(I3-1)
C
         IF( MILIEU(I0) .EQ. NOSOAR(1,NUARCO(I3)) ) THEN
            LESIGN =  1
         ELSE
            LESIGN = -1
         ENDIF
         NOARTR( 3, NUTR(I) ) = LESIGN * NUARCO(I3)
C
 20   CONTINUE
C
C     LE SOUS TRIANGLE CENTRAL
      I3 = -1
      DO 30 I=1,3
         I3 = I3 + 3
         IF( MILIEU(I) .EQ. NOSOAR(1,NUARCO(I3)) ) THEN
            LESIGN = -1
         ELSE
            LESIGN =  1
         ENDIF
         NOARTR( I, NUTR(4) ) = LESIGN * NUARCO(I3)
 30   CONTINUE
C
C     TRIANGULATION DES 3 SOUS-TE PAR AJOUT DES POINTS INTERNES DU TE
      CALL TRPITE( LETREE, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             NBTR,   NUTR,   IERR )
      END
