      SUBROUTINE GETETO( NS,     XYZSOM, N1FEOC, N1FEVI, NFETOI,
     %                   NUMATE, NUDMEF,
     %                   NBSOTE, N1TEVI, NSTETR,
     %                   NO1TSO, N1TESO, NOTESO,
     %                   MXTETA, VOLUMT, QUALIT,
     %                   QUALNS, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   GENERER LES TETRAEDRES DE L'ETOILE FORMEE DES FACES DE NFETOI
C -----   A PARTIR DU SOMMET NS, UN DES SOMMETS DES FACES
C
C ENTREES:
C --------
C NS     : LE POINT EN COURS DE TRAITEMENT
C N1FEOC : NUMERO DE LA PREMIERE FACE DE NFETOI
C NFETOI : LES 3 SOMMETS DE CHAQUE FACE ET FACE SUIVANTE DE L'ETOILE
C NUMATE : =0 SI PAS DE MATERIAUX
C          >0 NUMERO DE L'UNIQUE MATERIAU DES TETRAEDRES DE SOMMET NS
C NBSOTE : NOMBRE D'ENTIERS PAR TETRAEDRE DANS NSTETR
C
C MODIFIES :
C ----------
C NUDMEF : NUMERO DE MATERIAU DE CHAQUE TETRAEDRE DU MAILLAGE
C          ATTENTION: CE TABLEAU EXISTE SEULEMENT SI NUMATE>0
C N1TEVI : NUMERO 1-ER TETRAEDRE VIDE DE NSTETR
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE
C NO1TSO : NUMERO DU 1-ER TETRAEDRE DANS NOTESO DE CHAQUE SOMMET
C N1TESO : NUMERO 1-ER TETRAEDRE VIDE DANS NOTESO
C NOTESO : NOTESO(1,*) NUMERO DANS NSTETR DU TETRAEDRE
C          NOTESO(2,*) NUMERO DANS NOTESO DU TETRAEDRE SUIVANT
C                      0 SI C'EST LE DERNIER
C MXTETA : NUMERO MAXIMAL D'UN TETRAEDRE ACTUEL
C VOLUMT : VOLUME DES TETRAEDRES
C QUALIT : QUALITE DES TETRAEDRES
C
C SORTIES:
C --------
C QUALNS : QUALITE MINIMALES DES TETRAEDRES DE SOMMET NS
C IERR   : =0 SI PAS D'ERREUR
C          >0 SINON ( SATURATION DES TETRAEDRES NSTETR OU NOTESO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 1991
C....................................................................012
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      INTEGER           NFETOI(5,*),
     %                  NUDMEF(*),
     %                  NSTETR(NBSOTE,MXTETA),
     %                  NO1TSO(*),
     %                  NOTESO(2,*)
      REAL              XYZSOM(3,*),
     %                  QUALIT(*),
     %                  VOLUMT(*)
      REAL              ARMIN,ARMAX,SURFTR(4)
C
C     POSITION DANS NFETOI DE LA 1-ERE FACE DE L'ETOILE
      QUALNS = 10.0
      NF  = N1FEOC
C
C     TANT QU'IL EXISTE UNE FACE DE L'ETOILE FAIRE
 10   IF( NF .GT. 0 ) THEN
C
C        CETTE FACE CONTIENT ELLE LE SOMMET NS ?
         DO 20 I=1,3
            IF( ABS(NFETOI(I,NF)) .EQ. NS ) GOTO 90
 20      CONTINUE
C
C        RECHERCHE D'UN TETRAEDRE VIDE
         IF( N1TEVI .LE. 0 ) THEN
            NBLGRC(NRERR) = 1
            KERR(1) = 'SATURATION DES TETRAEDRES'
            CALL LEREUR
            IERR = 1
            GOTO 9999
         ENDIF
C        LE PREMIER TETRAEDRE VIDE
         NT = N1TEVI
C        EST MIS A JOUR
         N1TEVI = NSTETR( 2, N1TEVI )
C
C        FORMATION DU TETRAEDRE DE SOMMET NS ET DE FACE OPPOSEE NF
         NSTETR(1,NT) = ABS( NFETOI(1,NF) )
         NSTETR(2,NT) = NFETOI(2,NF)
         NSTETR(3,NT) = NFETOI(3,NF)
         NSTETR(4,NT) = NS
C
C        EVENTUEL NUMERO DE MATERIAU DU TETRAEDRE
         IF( NUMATE .GT. 0 ) NUDMEF(NT) = NUMATE
C
C        AJOUT DE CE TETRAEDRE DANS LE CHAINAGE DES TETRAEDRES
C        DE SES 4 SOMMETS
         DO 80 I=1,4
C           LE SOMMET I
            N   = NSTETR(I,NT)
C           UNE PLACE LIBRE DANS NOTESO
            IF( N1TESO .LE. 0 ) THEN
               NBLGRC(NRERR) = 1
               KERR(1) = 'SATURATION DES TETRAEDRES DE 1 SOMMET'
               CALL LEREUR
               IERR = 2
               GOTO 9999
            ENDIF
C           GESTION DES PLACES LIBRES DE NOTESO
            NTS    = N1TESO
            N1TESO = NOTESO( 2, N1TESO )
C           LE TETRAEDRE NT EST CHAINE A L'ANCIEN PREMIER
            NOTESO( 1, NTS ) = NT
            NOTESO( 2, NTS ) = NO1TSO( N )
C           NT DEVIENT LE PREMIER
            NO1TSO(N) = NTS
 80      CONTINUE
C
C        QUALITE ET VOLUME DU TETRAEDRE
         CALL QUATET( XYZSOM(1,NSTETR(1,NT)),
     %                XYZSOM(1,NSTETR(2,NT)),
     %                XYZSOM(1,NSTETR(3,NT)),
     %                XYZSOM(1,NSTETR(4,NT)),
     %                ARMIN, ARMAX, SURFTR, VOLUMT(NT), QUALIT(NT) )
C        QUALITE MINIMALE DES TETRAEDRES DE SOMMET NS
         QUALNS = MIN( QUALNS, QUALIT(NT) )
C
C        LA FACE SUIVANTE
 90      NF  = NFETOI(5,NF)
         GOTO 10
      ENDIF
C
C     LES FACES OCCUPEES DE NFETOI DEVIENNENT VIDES
 9999 CALL ETOIOCVI( N1FEOC, N1FEVI, NFETOI )
C
      RETURN
      END
