      SUBROUTINE IDETGS( NBOBUN, MNXYOB, MNSOMM, NBTGUN,
     %                   MNDETG, MNNUTG, NBFITG )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  IDENTIFIER LES TANGENTES D'UNE UNION DE PLSV C'EST A DIRE
C -----  D'OBJETS PREMIERS (VALABLE AUSSI POUR DES OBJETS DE MEME TYPE)
C        L'IDENTIFICATION PEUT ETRE FAITE SI LES TANGENTES SONT OPPOSEES
C
C ENTREES:
C --------
C NBOBUN : NOMBRE D'OBJETS PREMIERS DE L'UNION
C MNXYOB : ADRESSE MCN DU TABLEAU DES ADRESSES MCN DES TMS XYZSOMMET
C          DES NBOBUN OBJETS DE L'UNION
C MNSOMM : ADRESSE MCN DU TMS XYZSOMMET AVANT ET APRES IDENTIFICATION
C          DES TANGENTES
C NBTGUN : NOMBRE INITIAL DE TANGENTES DE L'UNION
C MNDETG : ADRESSE MCN DU TMC DES NUMEROS DE LA DERNIERE TANGENTE
C          DE CHAQUE OBJET DE L'UNION
C MNNUTG : ADRESSE MCN DU TMC DES NUMEROS DE CHAQUE TANGENTE
C          MCN(MNNUTG+I) = NOUVEAU NUMERO DE LA TG INITIALE I
C
C SORTIES:
C --------
C NBFITG : NOMBRE FINAL DE TANGENTES DE L'UNION
C LES TABLEAUX MCN(MNDETG+J) ET MCN(MNNUTG+I) SONT REMPLIS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS        JUIN 1997
C23456---------------------------------------------------------------012
      include"./incl/a___xyzsommet.inc"
      COMMON / EPSSSS / EPZERO, EPSXYZ
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
C
      NBFITG = 0
      IF( NBTGUN .LE. 0 ) RETURN
C
C     CONSTRUCTION DU TABLEAU DES CARRES DES NORMES DES TANGENTES
C     ===========================================================
C     DECLARATION DU TMC DU CARRE DES NORMES DES TANGENTES
C     LES TABLEAUX DES NBTGUN CARRES DES NORMES DES TANGENTES
      CALL TNMCDC( 'REEL'  , NBTGUN,   MNCATG )
      CALL TNMCDC( 'ENTIER', NBTGUN*2, MNNCTG )
C     LE TABLEAU DES ADRESSES MCN DE CHAQUE TG DE L'UNION
      MNMNTG = MNNCTG + NBTGUN
C     ADRESSES POUR ECONOMISER QUELQUES SOUSTRACTIONS
      MNCAT1 = MNCATG - 1
      MNNCT1 = MNNCTG - 1
      MNMNT1 = MNMNTG - 1
      MNNUT1 = MNNUTG - 1
C
C     LE POINTEUR AVANT LA PREMIERE TG
      NBTOTG = 0
      MCN(MNDETG) = 0
C
C     RECENSEMENT DE TOUTES LES TANGENTES
      DO 20 J=1,NBOBUN
C
C        ADRESSE DU TABLEAU 'XYZSOMMET' DE L'OBJET J
         MN  = MCN( MNXYOB - 1 + J )
C
C        LE NOMBRE DE TANGENTES DU PLSV J
         NBT = MCN( MN + WNBTGS )
         IF( NBT .GT. 0 ) THEN
C
C           ADRESSE DE LA 1-ERE COMPOSANTE DE LA 1-ERE TANGENTE
            MNT = MN + WYZSOM + 3 * MCN(MN+WNBSOM) - 3
C
C           BOUCLE SUR LES TANGENTES DE L'UNION
            DO 10 N=1,NBT
C              LE NUMERO DE LA TG DANS L'UNION
               NBTOTG = NBTOTG + 1
C              ADRESSE MCN DE LA PREMIERE COMPOSANTE DE LA TG NBTOTG
               MNT = MNT + 3
               MCN ( MNMNT1+NBTOTG ) = MNT
C              LE CARRE DE LA NORME DE LA TANGENTE NBTOTG
               RMCN( MNCAT1+NBTOTG ) = RMCN(MNT  ) ** 2
     %                               + RMCN(MNT+1) ** 2
     %                               + RMCN(MNT+2) ** 2
 10         CONTINUE
         ENDIF
C
C        LE NUMERO DE LA DERNIERE TANGENTE INITIALE DE L'OBJET J
         MCN( MNDETG + J ) = NBTOTG
C
 20   CONTINUE
C
C     LE TRI CROISSANT SELON LE CARRE DE LA NORME DES TANGENTES
C     =========================================================
      DO 25 I=1,NBTOTG
         MCN( MNNCT1+I ) = I
 25   CONTINUE
      CALL TRITRP( NBTOTG, RMCN(MNCATG), MCN(MNNCTG) )
C
C     IDENTIFICATION DES TANGENTES TRIEES SELON LE CARRE DE LEUR NORME
C     ================================================================
C     ADRESSE MCN DU DEBUT DES COMPOSANTES DES TANGENTES DANS
C     LE TMS XYZSOMMET DE L'UNION
      MNXYTU = MNSOMM + WYZSOM + 3*MCN(MNSOMM+WNBSOM) - 3
C
C     MISE A ZERO DU TABLEAU MNNUTG
      CALL AZEROI( NBTGUN, MCN(MNNUTG) )
C
C     PARCOURS DES TANGENTES DE L'UNION SELON LA VALEUR
C     DU CARRE DE LEUR NORME DANS LE SENS CROISSANT
      DO 100 J=1,NBTOTG
C
C        LE NUMERO AVANT LE TRI DE LA TG J PAR NORME CROISSANTE
         NUAVTG = MCN( MNNCT1 + J )
C
C        EST ELLE DEJA IDENTIFIEE?
         IF( MCN(MNNUT1+NUAVTG) .EQ. 0 ) THEN
C
C           NON : LA TG NUAVTG N'EST PAS ENCORE IDENTIFIEE
C           L'ADRESSE MCN DES 3 COMPOSANTES DE LA TG NUAVTG
            MNT = MCN( MNMNT1 + NUAVTG )
C
C           BOUCLE SUR LES TGS DE CARRE DE NORME PROCHE
C           ===========================================
            DO 30 I=MAX(1,J-8), MIN(NBTGUN,J+8)
C
C              LE NUMERO DE LA TG I AVANT LE TRI
               NUAVTI = MCN( MNNCT1 + I )
C
C              EST ELLE DEJA IDENTIFIEE?
C              SON NUMERO DE TG DANS LES TGS FINALES DE L'UNION
               NFTGI = MCN( MNNUT1 + NUAVTI )
               IF( NFTGI .EQ. 0 ) GOTO 30
C
C              TANGENTE AYANT UN NUMERO DE TANGENTE FINALE
C              L'ADRESSE MCN DES 3 COMPOSANTES DE LA TG
               NFTGIA = ABS( NFTGI )
               MNTI   = MNXYTU + 3 * NFTGIA
C
C              IDENTIFICATION POSSIBLE DE LA TANGENTE NUAVTG AVEC NUAVTI
               CALL TGSIDE( RMCN(MNT), RMCN(MNTI), LSIGNE )
               IF( LSIGNE .NE. 0 ) THEN
C
C                 LA TANGENTE NUAVTG EST IDENTIFIEE A LA TG NFTGI FINALE
C                 ------------------------------------------------------
                  MCN( MNNUT1 + NUAVTG ) = LSIGNE * NFTGIA
                  GOTO 100
               ENDIF
 30         CONTINUE
C
C           TG NON IDENTIFIEE => UNE TG FINALE DE PLUS
C           ------------------------------------------
            NBFITG = NBFITG + 1
C           LE NUMERO FINAL DE LA TG NUAVTG DANS LES TG FINALES
            MCN( MNNUT1 + NUAVTG ) = NBFITG
C           STOCKAGE DES 3 COMPOSANTES DE CETTE TANGENTE FINALE
            MNTI = MNXYTU + 3 * NBFITG
            DO 40 I=0,2
               RMCN(MNTI+I) = RMCN(MNT+I)
 40         CONTINUE
         ENDIF
C
 100  CONTINUE
C
C     DESTRUCTION DU TMC DU CARRE DES NORMES DES TANGENTES
      CALL TNMCDS( 'REEL',   NBTGUN,   MNCATG )
      CALL TNMCDS( 'ENTIER', NBTGUN*2, MNNCTG )
      RETURN
      END
