      SUBROUTINE LIEX20( NULGEX, NTLXLI, LADEFI,
     %                   NTNSEF, MNNSEF, NTXYZS, MNXYZS, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    GENERER LES ARETES DE L'UNION DES LIGNES EXTRUDEES
C -----    D'UN POLYGONE DEFINI PAR SES SOMMETS ET LES 2 POINTS
C          DE DEFINITION DU VECTEUR TRANSLATION
C
C ENTREES:
C --------
C NULGEX : NUMERO DE LA LIGNE DANS SON LEXIQUE
C NTLXLI : NUMERO DU TABLEAU TMS DU LEXIQUE DE LA LIGNE
C LADEFI : TABLEAU ENTIER DES DONNEES DE LA DEFINITION DE LA LIGNE
C          CF ~/td/d/a_ligne__definition
C
C SORTIES:
C --------
C NTNSEF : NUMERO      DU TMS 'NSEF' DES NUMEROS DES ARETES DES LIGNES
C MNNSEF : ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES ARETES DES LIGNES
C          CF ~/td/d/a___nsef
C NTXYZS : NUMERO      DU TMS 'XYZSOMMET' DE LA LIGNE UNION DES LIGNES
C MNXYZS : ADRESSE MCN DU TMS 'XYZSOMMET' DE LA LIGNE UNION DES LIGNES
C          CF ~/td/d/a___xyzsommet
C IERR   : 0 SI PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY  JANVIER 2010
C2345X7..............................................................012
      include"./incl/a_ligne__definition.inc"
C
C     LE SUPER-TABLEAU OU TOUS LES TMC ET TMS OUVERTS SONT STOCKES
C     ICI LE TABLEAU DMCN REEL DOUBLE PRECISION N'EST PAS UTILE
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL             RMCN(1)
      DOUBLE PRECISION DMCN(1)
      EQUIVALENCE     ( MCN(1), RMCN(1), DMCN(1) )
C
C     LE NUMERO D'UNITE DU CLAVIER, FENETRE DES AFFICHAGES ET
C     LE PARAMETRE DE NIVEAU D'INTERACTIVITE
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
C
C     LE TABLEAU DES DONNEES DE LA DEFINITION DE LA LIGNE
C     VU SOUS FORME D'UN TABLEAU D'ENTIERS
      INTEGER           LADEFI(0:*)
C
      CHARACTER*24      NMLGEX
C
      IERR   = 0
      MNNULG = 0
C
C     LE NOM DE LA LIGNE, UNION DE TOUTES LES LIGNES
      CALL NMOBNU( 'LIGNE', NULGEX, NMLGEX )
C
C     RECUPERATION DES 3 COORDONNEES DES NBPTEX POINTS DU POLYGONE INITIAL
C     TRANSLATION  DES 3 COORDONNEES DES NBPTEX POINTS DU POLYGONE FINAL
C     CONSTRUCTION DES NBPTEX LIGNES DU POLYGONE INITIAL
C     POUR FERMER LE POLYGONE, LE DERNIER POINT EST LE MEME QUE LE PREMIER
C     CONSTRUCTION DES NBPTEX LIGNES DU POLYGONE FINAL
C     CONSTRUCTION DES NBPTEX LIGNES EXTRUDEES DES SOMMETS DU POLYGONE
C     --------------------------------------------------------------------
      NBPTEX = LADEFI(WBPTEX)
      CALL CRLI20( NMLGEX, LADEFI(WUPTVT), LADEFI(WUFEEX),
     %             NBPTEX, LADEFI(WUPTEX),
     %             NBLG, MNNULG, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     UNION DES NBLG LIGNES EXTRUDEES ET DES 2 POLYGONES
C     --------------------------------------------------
C     MODIFICATION DU TMS DEFINITION DE LA LIGNE
C     NECESSAIRE POUR LE RE-MAILLAGE AUTOMATIQUE
      CALL LXTSOU( NTLXLI, 'DEFINITION', NT1LDE, MN1LDE )
      IF( NT1LDE .GT. 0 ) CALL LXTSDS( NTLXLI, 'DEFINITION' )
C     LA LIGNE A UN TMS DEFINITION DE LIGNE UNION DE LIGNES
      CALL LXTNDC( NTLXLI, 'DEFINITION', 'MOTS', WULIUN+NBLG )
      CALL LXTSOU( NTLXLI, 'DEFINITION', NT1LDE, MN1LDE )
C     TRANSFORMATION (I pour IDENTITE)
      MCN( MN1LDE + WTYTRL ) = 1
C     TYPE DE LA LIGNE
      MCN( MN1LDE + WUTYLI ) = 51
C     NOMBRE DE LIGNES DE LA LIGNE UNION
      MCN( MN1LDE + WBLIUN ) = NBLG
C     LES NBLGP NUMEROS DES LIGNES DANS LE LEXIQUE LIGNE
      DO K = 1, NBLG
         MCN( MN1LDE+WULIUN-1+K ) = MCN( MNNULG-1+K )
      ENDDO
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MN1LDE + MOTVAR(6) ) = NONMTD( '~>LIGNE>>DEFINITION' )
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MN1LDE) )
C
C     CREATION DU MAILLAGE UNION DES LIGNES
      CALL UNPLSV( 51,  2, NULGEX, NBLG, MCN(MNNULG),
     %             NTNSEF, MNNSEF, NTXYZS, MNXYZS,
     %             NTUNIO, MNUNIO, IERR   )
C
C     DESTRUCTION DES TABLEAUX MC DEVENUS INUTILES
 9999 IF( MNNULG .GT. 0 ) CALL TNMCDS( 'ENTIER', 3*NBPTEX, MNNULG )
C
      RETURN
      END
