      SUBROUTINE LIEX06( NTLXLI, LADEFI,
     %                   NTARLI,  MNARLI, NTSOLI, MNSOLI, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    GENERER LES ARETES DE LA LIGNE DEFINIE PAR UNE LISTE DE NOMS
C -----    DE POINTS UTILISATEUR ( 1 ARETE ENTRE 2 POINTS SUCCESSIFS )
C
C ENTREES:
C --------
C NTLXLI : NUMERO DU TABLEAU TS DU LEXIQUE DE LA LIGNE
C LADEFI : TABLEAU ENTIER DE DEFINITION DE LA LIGNE
C          CF ~td/d/a_ligne__definition
C
C SORTIES:
C --------
C NTARLI : NUMERO      DU TMS 'NSEF' DES NUMEROS DES ARETES DE LA LIGNE
C MNARLI : ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES ARETES DE LA LIGNE
C          CF ~TD/D/A___NSEF
C NTSOLI : NUMERO      DU TMS 'XYZSOMMET' DE LA LIGNE
C MNSOLI : ADRESSE MCN DU TMS 'XYZSOMMET' DE LA LIGNE
C          CF ~TD/D/A___XYZSOMMET
C IERR   : 0 SI PAS D'ERREUR
C          >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC  PARIS   NOVEMBRE 1988
C MODIFS : ALAIN PERRONNET TEXAS A & M UNIVERSITY at QATAR     MARS 2012
C234567.................................................................
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/a_ligne__definition.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/ntmnlt.inc"
      COMMON / EPSSSS / EPZERO,EPSXYZ
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
      INTEGER           LADEFI(0:*)
C
C     LE NOMBRE DE POINTS DE LA LIGNE
      NBPOLI = LADEFI( WBPOLI )
C
C     DONNEES CORRECTES?
      IF( NBPOLI .LE. 1 ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER)(1:10),'(I10)') NBPOLI
         KERR(1) ='NOMBRE INCORRECT DE POINTS' // KERR(MXLGER)(1:10)
         CALL LEREUR
         IERR = 2
         GOTO 9999
      ENDIF
C
C     CONSTRUCTION DU TABLEAU 'XYZSOMMET'
C     -----------------------------------
      CALL LXTNDC( NTLXLI, 'XYZSOMMET', 'MOTS', WYZSOM + 3*NBPOLI )
      CALL LXTSOU( NTLXLI, 'XYZSOMMET',  NTSOLI , MNSOLI )
C
C     LE NOMBRE DE SOMMETS
      MCN( MNSOLI + WNBSOM ) = NBPOLI
C
C     ADRESSE DU DEBUT DES COORDONNEES DU 1-ER SOMMET DE LA LIGNE
      MNS = MNSOLI + WYZSOM
C
C     GENERATION DES NBPOLI POINTS DANS SOMMETS
      DO 20 I=1,NBPOLI
C
C        COORDONNEES DU POINT I
         CALL LXNLOU( NTPOIN, LADEFI( WUPOLI - 1 + I ), NTPOI, MN )
         IF( NTPOI .LE. 0 ) THEN
            NBLGRC(NRERR) = 1
            WRITE(KERR(MXLGER)(1:10),'(I10)')  LADEFI( WUPOLI - 1 + I )
            KERR(1) = 'LIEX06: POINT INEXISTANT' // KERR(MXLGER)(1:10)
            CALL LEREUR
            IERR = 3
            GOTO 9999
         ENDIF
C
         CALL LXTSOU( NTPOI , 'XYZSOMMET',  NTSOM, MNSOM )
         MN = MNSOM + WYZSOM
         RMCN( MNS     ) = RMCN( MN     )
         RMCN( MNS + 1 ) = RMCN( MN + 1 )
         RMCN( MNS + 2 ) = RMCN( MN + 2 )
         MNS = MNS + 3
 20   CONTINUE
C
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MNSOLI) )
C
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNSOLI + WNBTGS ) = 0
      MCN( MNSOLI + WBCOOR ) = 3
      MCN( MNSOLI + MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )
C
C     NOMBRE D'ARETES DE LA LIGNE
      NBARLI = NBPOLI - 1
C
C     LA LIGNE EST ELLE UNE COURBE FERMEE: 1-ER SOMMET=DERNIER SOMMET?
C     ----------------------------------------------------------------
      CALL XYZIDE( MCN(MNSOLI+WYZSOM), MCN(MNSOLI+WYZSOM+3*NBPOLI-3),
     %             IDENTQ )
      IF( IDENTQ .EQ. 0 ) THEN
C
C     CONSTRUCTION DU TABLEAU 'NSEF' LIGNE STRUCTURE OUVERTE
C     ------------------------------------------------------
      CALL LXTNDC( NTLXLI, 'NSEF', 'MOTS', 1 + WBARSE )
      CALL LXTSOU( NTLXLI, 'NSEF',  NTARLI , MNARLI )
C
C     LE TYPE DE L'OBJET : ICI LIGNE
      MCN( MNARLI + WUTYOB ) = 2
C     LE TYPE DU MAILLAGE : ICI SEGMENT STRUCTURE
      MCN( MNARLI + WUTYMA ) = 2
C     LE NOMBRE DE SOMMETS ET TANGENTES PAR ARETE
      MCN( MNARLI + WBSOEF ) = 2
      MCN( MNARLI + WBTGEF ) = 0
C     PAS D'EF A TG
      MCN( MNARLI + WBEFTG ) = 0
      MCN( MNARLI + WBEFAP ) = 0
C     LE NOMBRE D'ARETES DU SEGMENT STRUCTURE
      MCN( MNARLI + WBEFOB ) = NBARLI
C     LE NOMBRE D'ARETES DU SEGMENT STRUCTURE
      MCN( MNARLI + WBARSE ) = NBARLI
C     LE TYPE NON-FERME DU MAILLAGE
      MCN( MNARLI + WUTFMA ) = 0
C
      ELSE
C
C     CONSTRUCTION DU TABLEAU 'NSEF' LIGNE NON STRUCTURE FERMEE
C     ---------------------------------------------------------
      CALL LXTNDC( NTLXLI, 'NSEF', 'ENTIER',
     S             WUSOEF + 2 * NBARLI )
      CALL LXTSOU( NTLXLI, 'NSEF', NTARLI, MNARLI )
C
C     LE TYPE DE L'OBJET : ICI LIGNE
      MCN( MNARLI + WUTYOB ) = 2
C     LE TYPE DU MAILLAGE : ICI SEGMENT NON STRUCTURE
      MCN( MNARLI + WUTYMA ) = 0
C     LE NOMBRE DE SOMMETS PAR SOUS-OBJET
      MCN( MNARLI + WBSOEF ) = 2
C     LE NOMBRE DE NSEF
      MCN( MNARLI + WBEFOB ) = NBARLI
C
      IA = MNARLI + WUSOEF - 1
      DO I=1,NBARLI
         MCN( IA + 1 ) = I
         MCN( IA + 2 ) = I + 1
         IA = IA + 2
      ENDDO
C
C     LE SOMMET DE LA DERNIERE ARETE EST LE PREMIER
      MCN( IA ) = 1
C     LE TYPE FERME DE LA LIGNE
      MCN( MNARLI + WUTFMA ) = 1
C     PAS DE TANGENTES STOCKEES
      MCN( MNARLI + WBTGEF ) = 0
      MCN( MNARLI + WBEFTG ) = 0
      MCN( MNARLI + WBEFAP ) = 0
C
      ENDIF
C
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MNARLI) )
C
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNARLI + MOTVAR(6) ) = NONMTD( '~>>>NSEF' )
C
      IERR = 0
C
C     ERREUR
C     ======
 9999 RETURN
      END
