      SUBROUTINE LIEX26( NTLXLI, LADEFI, RADEFI,
     %                   NTNSEF, MNNSEF, NTXYZS, MNXYZS, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    GENERER LES ARETES DE LA LIGNE INTERSECTION DE 2 TRONCS DE CONES
C -----
C
C ENTREES:
C --------
C LADEFI : TABLEAU ENTIER DE DEFINITION DE LA LIGNE
C          CF ~/td/d/a_ligne__definition
C RADEFI : TABLEAU REEL   DE DEFINITION DE LA LIGNE
C          CES 2 TABLEAUX LADEFI ET RADEFI ONT MEME ADRESSE A L'APPEL
C NTLXLI : NUMERO DU TABLEAU TS DU LEXIQUE DE LA LIGNE
C
C SORTIES:
C --------
C NTNSEF : NUMERO      DU TMS 'NSEF' DES NUMEROS DES ARETES DE LA LIGNE
C MNNSEF : ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES ARETES DE LA LIGNE
C NTXYZS : NUMERO      DU TMS 'XYZSOMMET' DE LA LIGNE
C MNXYZS : ADRESSE MCN DU TMS 'XYZSOMMET' DE LA LIGNE
C IERR   : 0 SI PAS D'ERREUR
C          1 SI NOMBRE DE SOMMETS INCORRECT <2
C          2 POINT INITIAL OU FINAL NON INITIALISE
C          3 POINT INITIAL ET FINAL CONFONDUS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 1997
C....................................................................012
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/a_ligne__definition.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/gsmenu.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
C
      INTEGER           LADEFI(0:*)
      REAL              RADEFI(0:*)
C
      DOUBLE PRECISION  RYCONE(2,2),PTAXCO(3,2,2),
     %                  HAUTCO(2),RPCONE(3,3,2)
C
      INTEGER           LAPERM(2)
C
C     EN CAS D'ERREUR RENCONTREE
      IERR   = 0
      NTXYZS = 0
      MNXYZS = 0
      NTNSEF = 0
      MNNSEF = 0
      MNBRAC = 0
      MNRACI = 0
      MNSUIV = 0
      MNRPIN = 0
      MNLONG = 0
C
C     EXISTENCE OU NON DE LA FONCTION 'TAILLE_IDEALE(XYZ)' DES ARETES
C     ===============================================================
C     LE NOMBRE D'ARETES ET DE SOMMETS DE LA LIGNE
      NBARLI = LADEFI( WBARLI )
C
C     ICI LA CARTE EST SUPPOSEE ISOTROPE
      NOFOTI = NOFOTIEL()
C     NOFOTI>0 SI CETTE FONCTION EXISTE
      IF( NOFOTI .GT. 0 ) THEN
C        LA FONCTION 'TAILLE_IDEALE(X,Y,Z)' EXISTE
C        LE NOMBRE D'ARETES DE LA LIGNE EST INACTIF
         IF( NBARLI .LE. 0 ) NBARLI = 10
         GOTO 3
      ENDIF
      IF( NBARLI .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         KERR(1) = 'NOMBRE INCORRECT D''ARETES'
         CALL LEREUR
         IERR = 10
         GOTO 9999
      ENDIF
C
C     RECHERCHE DU RAYON MAXIMAL => CE SERA LE CONE 2 (CAS PLUS SIMPLE!)
C     PAS TOUJOURS FIABLE POUR 2 VRAIS CONES (ET NON DES CYLINDRES)!
 3    R1 = MAX( RADEFI(WYCON1), RADEFI(WYCON1+1) )
      R2 = MAX( RADEFI(WYCON2), RADEFI(WYCON2+1) )
      IF( R2 .GE. R1 ) THEN
         LAPERM(1) = 1
         LAPERM(2) = 2
      ELSE
         LAPERM(1) = 2
         LAPERM(2) = 1
      ENDIF
C
C     LES 2 RAYONS DES 2 PLANS ORTHOGONAUX AUX CONES
      RYCONE(1,LAPERM(1)) = RADEFI(WYCON1)
      RYCONE(2,LAPERM(1)) = RADEFI(WYCON1+1)
      RYCONE(1,LAPERM(2)) = RADEFI(WYCON2)
      RYCONE(2,LAPERM(2)) = RADEFI(WYCON2+1)
C
C     RAYONS CORRECTS ?
      DO 10 J=1,2
         DO 5 I=1,2
            IF( RYCONE(I,J) .LE. 0 ) THEN
               NBLGRC(NRERR) = 1
               WRITE(KERR(3),'(I1)') I
               WRITE(KERR(4),'(I1)') LAPERM(J)
               KERR(1) = 'RAYON <0 AU POINT ' // KERR(3)(1:1)
     %                   // ' DU CONE ' // KERR(4)(1:1)
               CALL LEREUR
               IERR = 11
               GOTO 9999
            ENDIF
 5       CONTINUE
 10   CONTINUE
C
      IF( RYCONE(1,1) .EQ. RYCONE(2,1) .AND.
     %    RYCONE(1,2) .EQ. RYCONE(2,2) .AND.
     %    RYCONE(2,1) .EQ. RYCONE(1,2)       ) THEN
C        CAS PARTICULIER DES 2 CYLINDRES AVEC MEMES RAYONS =>
C        2 SOLUTIONS SONT POSSIBLES MAIS DIFFERENTES
C        ON OBLIGE LE RESULTAT A ETRE SYMETRIQUE EN
C        MODIFIANT LE RAYON DE L'UN DES CONES AU DESSOUS DU SEUIL
C        DE PRECISION DES REELS SIMPLE PRECISION
         RYCONE(1,1) = RYCONE(1,1) * 0.9999999D0
         RYCONE(2,1) = RYCONE(2,1) * 0.9999999D0
      ENDIF
C
C     RECUPERATION DES 3 COORDONNEES DES 2 POINTS DE L'AXE DES 2 CONES
      DO 20 J=1,2
         LJ = LAPERM(J)
         IF( LJ .EQ. 1 ) THEN
            K = WAXCN1
         ELSE
            K = WAXCN2
         ENDIF
         DO 15 I=1,2
            NUPT = LADEFI(K-1+I)
            IF( NUPT .LE. 0 ) GOTO 12
C           RECUPERATION DES 3 COORDONNEES DU POINT
            CALL LXNLOU( NTPOIN, NUPT, NTPOI, MN )
            CALL LXTSOU( NTPOI, 'XYZSOMMET', NTSOM, MNSOM )
            IF( NTSOM .LE. 0 ) GOTO 12
            MN = MNSOM + WYZSOM
            PTAXCO( 1, I, J ) = RMCN( MN   )
            PTAXCO( 2, I, J ) = RMCN( MN+1 )
            PTAXCO( 3, I, J ) = RMCN( MN+2 )
            GOTO 15
C
C           ERREUR: POINT INCORRECT
 12         NBLGRC(NRERR) = 1
            WRITE(KERR(3),'(I1)') I
            WRITE(KERR(4),'(I1)') LJ
            KERR(1) = 'POINT '// KERR(3)(1:1) //
     %                ' INCORRECT DE L''AXE DU CONE ' // KERR(4)(1:1)
            CALL LEREUR
            IERR = 12
            GOTO 9999
 15      CONTINUE
 20   CONTINUE
C
C     CALCUL DES INTERVALLES DE POINTS D'INTERSECTION DES 2 TRONCS DE CONES
C     PARMI 1+MXGENE GENERATRICES DU CONE 1 AVEC AU MINIMUM, UN SEGMENT P3
C     PAR DIXIEME DE DEGRE. CHAINAGE DES POINTS D'INTERSECTION
C     =====================================================================
      MXGENE = MAX( 3600, 3*NBARLI )
      CALL TNMCDC( 'ENTIER', 1+MXGENE,    MNBRAC )
      CALL TNMCDC( 'REEL2',  2+2*MXGENE,  MNRACI )
      CALL TNMCDC( 'REEL2', 64, MNLONG )
      MXPINT = 6 * MXGENE + 1
      CALL TNMCDC( 'ENTIER', 2*MXPINT+65, MNSUIV )
      MNTPIN = MNSUIV + MXPINT
      MN1COU = MNTPIN + MXPINT
      CALL TNMCDC( 'REEL2', 3*MXPINT,  MNRPIN )
C
      CALL CONEIN( MXGENE, MXPINT,
     %         PTAXCO(1,1,1), RYCONE(1,1), PTAXCO(1,2,1), RYCONE(2,1),
     %         PTAXCO(1,1,2), RYCONE(1,2), PTAXCO(1,2,2), RYCONE(2,2),
     %         HAUTCO(1), RPCONE(1,1,1), HAUTCO(2), RPCONE(1,1,2),
     %         MCN(MNBRAC), MCN(MNRACI),
     %         MCN(MNSUIV), MCN(MNTPIN), MCN(MNRPIN),
     %         NBIP1, NBIP2, MCN(MN1COU), MCN(MNLONG), IERR )
      CALL TNMCDS( 'ENTIER', 1+MXGENE,   MNBRAC )
      CALL TNMCDS( 'REEL2',  2+2*MXGENE, MNRACI )
      IF( IERR .GT.  0 ) GOTO 9998
      IF( IERR .EQ. -2 ) THEN
C        ERREUR: CONE 2 INCORRECT
         NBLGRC(NRERR) = 1
         WRITE(KERR(3)(1:1),'(I1)') LAPERM(2)
         KERR(1) = 'CONE' // KERR(3)(1:1) // ' AVEC DONNEES INCORRECTES'
         CALL LEREUR
         IERR = 13
         GOTO 9998
      ENDIF
      IF( IERR .EQ. -1 ) THEN
C        L'INTERSECTION EST UN SEGMENT DE DROITE RPINT(1)-RPINT(2)
C        DANS LE REPERE GLOBAL INITIAL
C        LES COORDONNEES DOUBLE PRECISION REDEVIENNENT SIMPLE PRECISION
         MN = ( MNRPIN + 1 ) / 2
C        CONSTRUCTION DU SEGMENT DE DROITE D'EXTREMITES XYZ1 XYZ2
         CALL SEGDRO( NTLXLI, DMCN(MN), DMCN(MN+3), NBARLI, 1D0,
     %                NTNSEF, MNNSEF, NTXYZS, MNXYZS, IERR )
         GOTO 9998
      ENDIF
C
C     CONSTRUCTION DU CHAINAGE DES SOMMETS DES ARETES DES INTERVALLES
C     DE POINTS D'INTERSECTION
C     ================================================================
      CALL CONEAR( NOFOTI, MXPINT,
     %             PTAXCO(1,1,1), RYCONE(1,1), RYCONE(2,1),
     %             PTAXCO(1,1,2), RYCONE(1,2), RYCONE(2,2),
     %             HAUTCO(1), RPCONE(1,1,1), HAUTCO(2), RPCONE(1,1,2),
     %             MCN(MNSUIV),   MCN(MNTPIN), MCN(MNRPIN),
     %             NBIP1,  NBIP2, MCN(MN1COU), MCN(MNLONG),
     %             NBARLI, NBSOML, IERR )
      IF( IERR .GT. 0 ) GOTO 9998
      CALL TNMCDS( 'REEL2', 64, MNLONG )
C
      IF( NBARLI .LT. 1 ) THEN
         NBLGRC(NRERR) = 1
         KERR(1) = 'NOMBRE INCORRECT D''ARETES'
         CALL LEREUR
         IERR = 12
         GOTO 9998
      ENDIF
C
C     CONSTRUCTION DU TABLEAU 'XYZSOMMET'
C     -----------------------------------
C     LES 2 TANGENTES PAR ARETE SONT STOCKEES
      NBTGS = 2 * NBARLI
      CALL LXTNDC( NTLXLI, 'XYZSOMMET', 'ENTIER',
     %             WYZSOM + 3*(NBSOML+NBTGS) )
      CALL LXTSOU( NTLXLI, 'XYZSOMMET',  NTXYZS , MNXYZS )
C
C     ADRESSE DU DEBUT DES COORDONNEES DU 1-ER SOMMET DE LA LIGNE
      MNS  = MNXYZS + WYZSOM
      MNT  = MNS    + 3 * NBSOML
C
C     CONSTRUCTION DU TABLEAU 'NSEF' LIGNE STRUCTURE
C     ----------------------------------------------
      CALL LXTNDC( NTLXLI, 'NSEF', 'ENTIER', WUSOEF + 6*NBARLI )
      CALL LXTSOU( NTLXLI, 'NSEF',  NTNSEF , MNNSEF )
C
C     ADRESSE DU DEBUT DES TABLEAUX NUSOAR, LPEFTG, NGEFTG, NUTGAR
      MNSOAR = MNNSEF + WUSOEF
      MNLPEF = MNSOAR + NBARLI*2
      MNNGEF = MNLPEF + NBARLI
      MNTGAR = MNNGEF + NBARLI
C
      CALL CONETG( MXPINT,
     %         PTAXCO(1,1,1), RYCONE(1,1), RYCONE(2,1),
     %         PTAXCO(1,1,2), RYCONE(1,2), RYCONE(2,2),
     %         HAUTCO(1), RPCONE(1,1,1), HAUTCO(2), RPCONE(1,1,2),
     %         MCN(MNSUIV), MCN(MNTPIN), MCN(MNRPIN),
     %         NBIP1, NBIP2, MCN(MN1COU),
     %         NBARLI, NBSOML,
     %         NBARL,  NBSOM, NBTGS,
     %         MCN(MNS), MCN(MNT),
     %         MCN(MNSOAR), MCN(MNLPEF), MCN(MNNGEF), MCN(MNTGAR) )
C
C     MISE A JOUR DU TMS XYZSOMMET
C     LE NOMBRE DE SOMMETS
      MCN( MNXYZS + WNBSOM ) = NBSOM
C     LE NOMBRE DE TANGENTES STOCKEES
      MCN( MNXYZS + WNBTGS ) = NBTGS
      IF( NBSOM .LT. NBSOML ) THEN
C        TRANSLATION DES TANGENTES
         MNS = MNXYZS + WYZSOM + 3 * NBSOML
         MNT = MNXYZS + WYZSOM + 3 * NBSOM
         CALL TRTATA( RMCN(MNS), RMCN(MNT), 3*NBTGS )
C        LE TMS EST RACOURCI
         CALL TAMSRA( NTXYZS, WYZSOM + 3*(NBSOM+NBTGS) )
      ENDIF
C     AJOUT DE LA DATE POUR LE TMS XYZSOMMET
      CALL ECDATE( MCN(MNXYZS) )
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNXYZS + WBCOOR ) = 3
      MCN( MNXYZS + MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )
C
C     MISE A JOUR DU TMS NSEF
C     LE TYPE DE L'OBJET : ICI LIGNE
      MCN( MNNSEF + WUTYOB ) = 2
C     LE TYPE DE FERMETURE DU MAILLAGE : ICI INCONNU
      MCN( MNNSEF + WUTFMA ) = -1
C     LE NOMBRE DE SOMMETS PAR EF=ARETE
      MCN( MNNSEF + WBSOEF ) = 2
C     LE NOMBRE DE TANGENTES PAR EF
      MCN( MNNSEF + WBTGEF ) = 2
C     LE NOMBRE D'ARETES DE LA LIGNE
      MCN( MNNSEF + WBEFOB ) = NBARL
C     NOMBRE D'EF AVEC TG
      MCN( MNNSEF + WBEFTG ) = NBARL
C     NOMBRE DES EF AVEC POINTEUR SUR EF A TG
      MCN( MNNSEF + WBEFAP ) = NBARL
C     NUMERO DU TYPE DE MAILLAGE: ICI NON STRUCTURE
      MCN( MNNSEF + WUTYMA ) = 0
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MNNSEF) )
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNNSEF + MOTVAR(6) ) = NONMTD( '~>>>NSEF' )
C
 9998 IF( MNSUIV .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXPINT+65, MNSUIV )
      IF( MNRPIN .GT. 0 ) CALL TNMCDS( 'REEL2',  3*MXPINT,    MNRPIN )
      IF( MNLONG .GT. 0 ) CALL TNMCDS( 'REEL2',  64,          MNLONG )
      IF( MNBRAC .GT. 0 ) CALL TNMCDS( 'ENTIER', 1+MXGENE,    MNBRAC )
      IF( MNRACI .GT. 0 ) CALL TNMCDS( 'REEL2',  2+2*MXGENE,  MNRACI )
C
C     ERREUR
C     ======
 9999 RETURN
      END
