      SUBROUTINE MOD1TRQM( COSMAXPL, QUALMN, MXSOM,  NBSOM,  XYZSOM,
     %                     MXTRAR,   L1ARET, L2ARET, MNARET,
     %                     NTR0,     M1TRIA, MXTRIA, NBTRIA, NOTRIA,
     %                     MXTRPV,   NOTRPV, MODIFS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ESSAIS POUR AMELIORER LA QUALITE DU TRIANGLE NTR0 et
C -----    SON ENVIRONNEMENT

C ENTREES:
C --------
C COSMAXPL:COSINUS DE L'ANGLE DIEDRE ENTRE LES 2 PLANS DES TRIANGLES AU DESSOUS
C          DUQUEL LES 2 TRIANGLES SONT CONSIDERES NON-COPLANAIRES
C QUALMN : QUALITE AU DESSOUS DE LAQUELLE LA QUALITE D'UN TRIANGLE
C          EST A AMELIORER
C MXSOM  : NOMBRE MAXIMUM DE SOMMETS XYZSOM DE LA TRIANGULATION
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION
C XYZSOM : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C MXTRAR : NOMBRE MAXIMUM DE TRIANGLES ADJACENTS A UNE ARETE
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU LARETE
C L2ARET : NOMBRE DE ARETES         DU TABLEAU LARETE
C MNARET : ADRESSE MCN DU TABLEAU LARETE DES ARETES DU MAILLAGE
C NTR0   : NUMERO NOTRIA DU TRIANGLE A TRAITER
C M1TRIA : NOMBRE D'ENTIERS DU PREMIER INDICE DU TABLEAU NOTRIA
C          =4 POUR STOCKER PAR TRIANGLE LE NO DES 3 SOMMETS + 0
C MXTRIA : NOMBRE MAXIMUM DE TRIANGLES DE LA TRIANGULATION
C MXTRPV : NOMBRE MAXIMAL DE NO DE TRIANGLES DU TABLEAU NOTRPV

C MODIFIES:
C ---------
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION
C LARETE : TABLEAU DES ARETES DU MAILLAGE  (=MCN(MNARET))
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C NOTRIA : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES NBTRIA TRIANGLES
C NOTRPV : NUMERO NOTRIA DES TRIANGLES + TRIANGLES VOISINS A TRACER

C SORTIE :
C --------
C MODIFS : =0  SI PAS DE MODIFICATION DU TRIANGLE NTR
C          >0  NOMBRE D'ECHANGE DES DIAGONALES A ETE EFFECTUE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET  Saint Pierre du Perray              Mars 2020
C....................................................................012
      PARAMETER        (MXPILE=256)
      include"./incl/langue.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0
      REAL              XYZSOM(3,MXSOM), LGARET, LGAMAX, LGAMIN
      INTEGER           NOTRIA(M1TRIA,MXTRIA), NOTRPV(MXTRPV),
     %                  LAPILE(MXPILE), NOQTAR(16)

      TRACTE0 = TRACTE
      MODIFS  = 0

      NTR = NTR0
      IF( NOTRIA(1,NTR) .EQ. 0 ) GOTO 9999
C     LE TRIANGLE NTR EST ACTIF

C     CALCUL DE LA QUALITE DU TRIANGLE NTR
      CALL QUATRI( NOTRIA(1,NTR), XYZSOM, QTR0 )
      IF( QTR0 .GE. QUALMN ) GOTO 9999

ccc      if( QTR0 .LT. 0.01 ) then
ccc         tracte = .true.
ccc      endif

      PRINT*
      PRINT*,'mod1trqm 0: Au debut le TRIANGLE NTR0=',NTR0,' St:',
     %       (NOTRIA(K,NTR0),K=1,3),' de QUALITE=',QTR0

C     CONSTRUCTION DU TABLEAU LARETE DES ARETES DU MAILLAGE A PARTIR DE NOTRIA
C     ------------------------------------------------------------------------
C     EVENTUELLE DESTRUCTION DU TABLEAU DES ARETES DU MAILLAGE
      IF( MNARET .GT. 0 ) CALL TNMCDS( 'ENTIER', L1ARET*L2ARET, MNARET )

C     CONSTRUCTION DU TABLEAU DES ARETES DE LA TRIANGULATION
      CALL GEARSU( 4,      NBTRIA, NOTRIA, MXTRAR,
     %             L1ARET, L2ARET, MNARET, IERR )
C     ARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C     ARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C     ARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C     ARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                 0 SI PAS DE 1-ER  TRIANGLE
C     ARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                 0 SI PAS DE 2-EME TRIANGLE
C     ARETE(3+MXTRAR,I)= NO DU MXTRAR-EME TRIANGLE CONTENANT CETTE ARETE
C                        0 SI PAS DE MXTRAR-EME TRIANGLE

C     TRACE DU TRIANGLE INITIAL NTR et SES VOISINS et VOISINS DE VOISINS
      NBTRPV = 1
      NOTRPV(1) = NTR
      CALL TRTRIAR( 'mod1trqm 0', XYZSOM,
     %               MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %               MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )


C     INITIALISATION DE LA PILE DES TRIANGLES A TRAITER
C     =================================================
      LHPILE = 1
      LAPILE( LHPILE ) = NTR

 5    IF( LHPILE .LE. 0 ) THEN
         GOTO 15
      ENDIF

C     1) ESSAI D'ECHANGER LES DIAGONALES DES QUADRANGLES NTR+NTRAD
C        D'ARETE D'ADJACENCE LA PLUS LONGUE DES ARETES DE NTR
C     ------------------------------------------------------------
      NTR = LAPILE( LHPILE )
      LHPILE = LHPILE -1

      LGAMAX = 0.0
      DO NA = 1, 3

C        TRIANGLE NTR d'ARETE NA DE SOMMETS NS1 NS2
         NS1 = NOTRIA( NA, NTR )
         IF( NA .EQ. 3 ) THEN
            N2 = 1
         ELSE
            N2 = NA+1
         ENDIF
         NS2 = NOTRIA( N2, NTR )
         LGARET = ( XYZSOM(1,NS2) - XYZSOM(1,NS1) ) ** 2
     %          + ( XYZSOM(2,NS2) - XYZSOM(2,NS1) ) ** 2
     %          + ( XYZSOM(3,NS2) - XYZSOM(3,NS1) ) ** 2
         LGARET = SQRT( LGARET )
         IF( LGARET .GT. LGAMAX ) THEN
            LGAMAX = LGARET
            NAMAX  = NA
         ENDIF
      ENDDO

C     RECHERCHE DU TRIANGLE ADJACENT NTRAD DE NTR PAR L'ARETE NAMAX
      CALL NUQTADAR( NAMAX, NTR, NOTRIA, L1ARET, L2ARET, MCN(MNARET),
     %               NAR,   NTRAD )
C     NTRAD:    SI L'ARETE APPARTIENT A 2 TRIANGLES ALORS
C            >0 NUMERO DANS NOTRIA DU TRIANGLE ADJACENT A NTR PAR L'ARETE NAMAX
C            =0 SI L'ARETE N'EST PAS RETROUVEE ou
C               SI L'ARETE APPARTIENT A UN SEUL TRIANGLE ou a >2 QTANGLES

      IF( NTRAD .GT. 0 ) THEN

C        IL EXISTE UN TRIANGLE ADJACENT NTRAD
C        QUALITE DU TRIANGLE NTRAD INITIAL
         CALL QUATRI( NOTRIA(1,NTRAD), XYZSOM, QTRAD0 )

C        LE QUADRANGLE NTR+NTRAD12 ECHANGE SES 2 DIAGONALES?
C        ---------------------------------------------------
         LIBREF = L2ARET
         CALL EC2D2TR( COSMAX, XYZSOM, NTR,    NTRAD,  NOTRIA,
     %                 LIBREF, L1ARET, L2ARET, MCN(MNARET),
     %                 MODIF )

         IF( MODIF .EQ. 1  ) THEN

C           L'ECHANGE A EU LIEU SUR LES 2 MEMES TRIANGLES NTR et NTRAD
C           ----------------------------------------------------------
C           QUALITE DU TRIANGLE NTR FINAL
            CALL QUATRI( NOTRIA(1,NTR), XYZSOM, QTR1 )

C           QUALITE DU TRIANGLE NTRAD FINAL
            CALL QUATRI( NOTRIA(1,NTRAD), XYZSOM, QTRAD1 )
            QUAMIN1 = MIN( QTR1, QTRAD1 )

            PRINT*,'mod1trqm 1: le TRIANGLE',NTR,': Qualite0',QTR0,
     %             ' MODIFIE avec SOMMETS',(NOTRIA(K,NTR),K=1,3),
     %             ' -> Qualite1',QTR1

            PRINT*,'mod1trqm 1: le TRIANGLE',NTRAD,': Qualite0',QTRAD0,
     %             ' MODIFIE avec SOMMETS',(NOTRIA(K,NTRAD),K=1,3),
     %             ' -> Qualite1',QTRAD1

C           TRACE DES TRIANGLES FINAUX NTR NTRAD et VOISINS
            NBTRPV = 2
            NOTRPV(1) = NTR
            NOTRPV(2) = NTRAD
            CALL TRTRIAR( 'mod1trqm 1', XYZSOM,
     %                   MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %                   MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )
            MODIFS = MODIFS + MODIF

            IF( QUAMIN1 .GE. QUALMN ) GOTO 1000

C           ESSAI AVEC LE NOUVEAU TRIANGLE NTR?
            IF( QTR1 .LT. QUALMN ) THEN
               LHPILE = LHPILE + 1
               LAPILE( LHPILE ) = NTR
            ENDIF

C           ESSAI AVEC LE NOUVEAU TRIANGLE NTRAD?
            IF( QTRAD1 .LT. QUALMN ) THEN
               LHPILE = LHPILE + 1
               LAPILE( LHPILE ) = NTRAD
            ENDIF

            GOTO 5

         ENDIF

      ENDIF


C     2) BARYCENTRAGE DU SOMMET OPPOSE A LA PLUS GRANDE ARETE DE NTR
C        SI TOUS LES TRIANGLES DE CE SOMMET SONT COPLANAIRES et
C        SI LE MINIMUM DES QUALITES DES TRIANGLES EST AUGMENTEE
C        ESSAI D'ECHANGER LES DIAGONALES DES QUADRANGLES NTR+NTRADJ
C     --------------------------------------------------------------
C     NTR EST MODIFIE -> RETOUR AU TRIANGLE NTR0 INITIAL
 15   NTR = NTR0

C     RECHERCHE DE LA PLUS LONGUE ARETE DE NTR EST NAMAX
      LGAMAX = 0.0
      DO NA = 1, 3
C        TRIANGLE NTR d'ARETE NA DE SOMMETS NS1 NS2
         NS1 = NOTRIA( NA, NTR )
         IF( NA .EQ. 3 ) THEN
            N2 = 1
         ELSE
            N2 = NA+1
         ENDIF
         NS2 = NOTRIA( N2, NTR )
         LGARET = ( XYZSOM(1,NS2) - XYZSOM(1,NS1) ) ** 2
     %             + ( XYZSOM(2,NS2) - XYZSOM(2,NS1) ) ** 2
     %             + ( XYZSOM(3,NS2) - XYZSOM(3,NS1) ) ** 2
         LGARET = SQRT( LGARET )
         IF( LGARET .GT. LGAMAX ) THEN
            LGAMAX = LGARET
            NAMAX  = NA
         ENDIF
      ENDDO

C     LA PLUS LONGUE ARETE DE NTR EST NAMAX
C     LE SOMMET OPPOSE EST N3 SUR L'ARETE QUI PRECEDE NAMAX
      IF( NAMAX .EQ. 1 ) THEN
         N3 = 3
      ELSE
         N3 = NAMAX - 1
      ENDIF

C     BARYCENTRAGE DU SOMMET N3 du TRIANGLE NTR 
C     SI TOUS LES TRIANGLES DE CE SOMMET SONT COPLANAIRES et
C     SI LE MINIMUM DES QUALITES DES TRIANGLES EST AUGMENTEE
      CALL BAST1TR4( COSMAXPL, QUALMN, NBSOM,  XYZSOM,
     %               L1ARET,   L2ARET, MNARET,
     %               N3,       NTR,    M1TRIA, NBTRIA, NOTRIA,
     %               MXTRPV,   NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV,
     %               QUAMIN0, QUAMIN1, MODIF )
      MODIFS = MODIFS + MODIF


C     EXTENSION DES TRAITEMENTS SUIVANTS AUX TRIANGLES ADJACENTS 1:NBTRPVV
C     --------------------------------------------------------------------
      NBTRPV = NBTRPVV

C     TENTATIVE D'AMELIORATION DE LA QUALITE PAR ECHANGE DES DIAGONALES
C     DES QUADRANGLES DE 2 TRIANGLES ADJACENTS PAR UNE ARETE DES 
C     TRIANGLES NOTRPV VENANT D'ETRE MODIFIES
C     ------------------------------------------------------------------
      CALL EC2DGTR( COSMAXPL, XYZSOM, M1TRIA, NOTRIA,
     %              MXTRPV,   NBTRPV, NOTRPV,
     %              L1ARET,   L2ARET, MNARET, NBDIAG )
      MODIFS = MODIFS + NBDIAG

C     CALCUL DES QUALITES MOYENNE ET MINIMALE DU GROUPE DES
C     NBTRPV TRIANGLES DU TABLEAU NOTRIA
      CALL QUMYMITR( NBTRPV, NOTRPV, M1TRIA, NOTRIA,
     %               XYZSOM, QUALMN, NBTRQI, QUAMOY2, QUAMIN2, NTRMIN2 )

      PRINT*,'mod1trqm 2: Les',NBTRPV,' TRIANGLES ont une QUALITE MOYENN
     %E=',QUAMOY2,' MINIMALE=',QUAMIN2

      CALL TRTRIAR( 'mod1trqm 2', XYZSOM,
     %               MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %               MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )

      IF( QUAMIN2 .GE. QUALMN ) GOTO 1000


C     RECHERCHE DU SOMMET NS3 OPPOSE A LA PLUS GRANDE ARETE NS1-NS2
C     DU TRIANGLE NTRMIN2 DE PLUS PETITE QUALITE
C     -------------------------------------------------------------
      NTR    = NTRMIN2
      LGAMIN = 1E27
      LGAMAX = 0.0
      PERIME = 0.0
      DO NA = 1, 3

C        TRIANGLE NTR d'ARETE NA DE SOMMETS NS1 NS2
         NS1 = NOTRIA( NA, NTR )
         IF( NA .EQ. 3 ) THEN
            N2 = 1
         ELSE
            N2 = NA+1
         ENDIF
         NS2 = NOTRIA( N2, NTR )

         LGARET = ( XYZSOM(1,NS2) - XYZSOM(1,NS1) ) ** 2
     %          + ( XYZSOM(2,NS2) - XYZSOM(2,NS1) ) ** 2
     %          + ( XYZSOM(3,NS2) - XYZSOM(3,NS1) ) ** 2
         LGARET = SQRT( LGARET )
         PERIME = PERIME + LGARET

         IF( LGARET .LT. LGAMIN ) THEN
            LGAMIN = LGARET
            NAMIN  = NA
         ENDIF

         IF( LGARET .GT. LGAMAX ) THEN
            LGAMAX = LGARET
            NAMAX  = NA
         ENDIF

      ENDDO

      ARPE = LGAMIN / PERIME
      IF( ARPE .LE. 0.028 ) THEN

C        LE TRIANGLE NTR A UNE ARETE NAMIN TRES PETITE PAR RAPPORT
C        AUX 2 AUTRES ARETES, LE SOMMET NS3 EST OPPOSE A LA PLUS
C        LONGUE ARETE NAMAX DE SOMMETS
C        NS1-NS2 VA ETRE IDENTIFIE AU SOMMET NS1 ou NS2 LE PLUS PROCHE
C        TOUS LES TRIANGLES D'ARETE NS1-NS2 SERONT DETRUITS
C        -------------------------------------------------------------
C        LA PLUS LONGUE ARETE DE NTR EST NAMAX ET DE SOMMETS NS1-NS2
         NS1 = NOTRIA( NAMAX, NTR )
         IF( NAMAX .EQ. 3 ) THEN
            N2 = 1
         ELSE
            N2 = NAMAX + 1
         ENDIF
         NS2 = NOTRIA( N2, NTR )
         IF( N2 .EQ. 3 ) THEN
            N3 = 1
         ELSE
            N3 = N2 + 1
         ENDIF
         NS3 = NOTRIA( N3, NTR )

C        TENTATIVE D'IDENTIFICATION DE NS3 A UN AUTRE SOMMET PROCHE
         NOSOM1 = NS3
         NOSOM2 = NS3
         CALL SE30ISA4( NBSOM,  XYZSOM, NOSOM1, NOSOM2,
     %                  MXTRAR, L1ARET, L2ARET, MNARET,
     %                  NBTRIA, NOTRIA, NBSTID )

         IF( NBSTID .LE. 0 ) GOTO 600
         MODIFS = MODIFS + NBSTID

C        CALCUL DES QUALITES MOYENNE ET MINIMALE DU GROUPE DES
C        NBTRPV TRIANGLES DU TABLEAU NOTRIA
         CALL LISTTRQM( QUALMN, M1TRIA, NBTRIA, NOTRIA,
     %                  MXTRPV, NBTRPV, NOTRPV,
     %                  NBSOM,  XYZSOM, QUAMOY3, QUAMIN3 )
         PRINT*,'mod1trqm 3: Les',NBTRIA,' TRIANGLES ont une QUALITE MOY
     %ENNE=',QUAMOY3,' MINIMALE=',QUAMIN3

         CALL TRTRIAR( 'mod1trqm 3', XYZSOM,
     %                  MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %                  MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )

         IF( QUAMIN3 .GE. QUALMN ) GOTO 1000

      ENDIF


C     AJOUT DU POINT PROJETE NBSOM du SOMMET NS3 OPPOSE A LA PLUS
C     LONGUE ARETE NAMAX DE NTR et NTR+NTRAD12 DEVIENNENT 4 TRIANGLES
C     ---------------------------------------------------------------
 600  NS1 = NOTRIA( NAMAX, NTR )
      IF( NAMAX .EQ. 3 ) THEN
         N2 = 1
      ELSE
         N2 = NAMAX + 1
      ENDIF
      NS2 = NOTRIA( N2, NTR )
      IF( N2 .EQ. 3 ) THEN
         N3 = 1
      ELSE
         N3 = N2 + 1
      ENDIF
      NS3 = NOTRIA( N3, NTR )

C     ETABLIR LA LISTE DES NBQTAR QT ADJACENTS PAR L'ARETE DE SOMMETS NS1-NS2
      LIBREF = L2ARET
      CALL LISTQTAR( L1ARET,   L2ARET, MCN(MNARET),
     %               NS1, NS2, NAR12, NBQTAR, NOQTAR )

      IF( NBQTAR .LE. 1 ) THEN
C        ARETE SANS ou TROP DE TRIANGLES ADJACENTS
C        => PAS DE MODIFICATION
         GOTO 1000
      ENDIF

C     RECHERCHE DE NTR DANS CETTE LISTE
      DO K=1, NBQTAR
         IF( NOQTAR(K) .EQ. NTR ) GOTO 610
      ENDDO

C     NTR DEVIENT LE PREMIER DE LA LISTE
 610  IF( K .NE. 1 ) THEN
         NOQTAR(K) = NOQTAR(1)
         NOQTAR(1) = NTR
      ENDIF

C     NBQTAR TRIANGLES PEUVENT ILS ETRE AJOUTES A NOTRIA?
      IF( NBTRIA+NBQTAR .GT. MXTRIA ) THEN
         PRINT*,'mod1trqm : AUGMENTER MXTRIA=',MXTRIA
         GOTO 1000
      ENDIF

C     CONSTRUCTION DU POINT NBSOM PROJECTION DE NS3 SUR NS1-NS2
      IF( NBSOM .GE. MXSOM ) THEN
         PRINT*,'mod1trqm: AUGMENTER MXSOM=',MXSOM
         GOTO 1000
      ENDIF
      NBSOM = NBSOM + 1
      CALL PTPRDR( XYZSOM(1,NS3), XYZSOM(1,NS1), XYZSOM(1,NS2),
     %             XYZSOM(1,NBSOM) )
C     NBSOMM EST AMENE AU MILIEU DE NBSOM-MILIEU NS1-NS2
      DO K=1,3
         XYZSOM(K,NBSOM) = ( XYZSOM(K,NBSOM)
     %                   + ( XYZSOM(K,NS1) + XYZSOM(K,NS2) ) /2 ) /2
      ENDDO

      NBTRPV = 0
      DO K = 1, NBQTAR

C        LE K-EME TRIANGLE ADJACENT NTRAD12 DE L'ARETE NS1-NS2
         NTRAD12 = NOQTAR( K )

C        NS3 LE 3-EME SOMMET DU TRIANGLE NTRAD12
         DO N3 = 1, 3
            NS3 = NOTRIA( N3, NTRAD12 )
            IF( NS3 .NE. NS1 .AND. NS3 .NE. NS2 ) GOTO 620
         ENDDO

C        SUPPRESSION DES 3 ARETES DE NTRAD12 DU TABLEAU LARETE
 620     CALL SU3ANARF( L1ARET,L2ARET,MCN(MNARET), NTRAD12,NOTRIA, IERR)

ccc         IF( IERR .NE. 0 ) THEN
cccC           TRAITEMENT DE L'ERREUR
ccc            NBTRPV = NBTRPV + 1
ccc            NOTRPV( NBTRPV ) = NTRAD12
ccc            NBTRPV = NBTRPV + 1
ccc            NOTRPV( NBTRPV ) = NBTRIA
ccc         ENDIF

C        CONSTRUCTION DES 2 SOUS-TRIANGLES DE NTRAD12
         NOTRIA( 1, NTRAD12 ) = NBSOM
         NOTRIA( 2, NTRAD12 ) = NS2
         NOTRIA( 3, NTRAD12 ) = NS3
         NOTRIA( 4, NTRAD12 ) = 0

C        AJOUT DES 3 ARETES DU TRIANGLE NT DANS LE TABLEAU LARETE
         CALL AJ3ANARF( LIBREF, L1ARET, L2ARET, MCN(MNARET),
     %                  NT,     NOTRIA, IERR )

         NBTRIA = NBTRIA + 1
         NOTRIA( 1, NBTRIA ) = NBSOM
         NOTRIA( 2, NBTRIA ) = NS3
         NOTRIA( 3, NBTRIA ) = NS1
         NOTRIA( 4, NBTRIA ) = 0

C        AJOUT DES 3 ARETES DU TRIANGLE NT DANS LE TABLEAU LARETE
         CALL AJ3ANARF( LIBREF, L1ARET, L2ARET, MCN(MNARET),
     %                  NT,     NOTRIA, IERR )

C        LES 2 SOUS-TRIANGLES SONT AJOUTES A NOTRPV
         NBTRPV = NBTRPV + 1
         NOTRPV( NBTRPV ) = NTRAD12
         NBTRPV = NBTRPV + 1
         NOTRPV( NBTRPV ) = NBTRIA

      ENDDO

      MODIFS = MODIFS + 1
ccc   GOTO 1000


C     BARYCENTRAGE DES SOMMETS DES NBTRPV TRIANGLES NOTRPV
C     ----------------------------------------------------
 1000 DO N = 1, NBTRPV
         NT = NOTRPV( N )
         DO N3 = 1,3
C           BARYCENTRAGE DU SOMMET N3 du TRIANGLE NT 
C           SI TOUS LES TRIANGLES DE CE SOMMET SONT COPLANAIRES et
C           SI LE MINIMUM DES QUALITES DES TRIANGLES EST AUGMENTEE
            CALL BAST1TR4( COSMAXPL, QUALMN,  NBSOM,  XYZSOM,
     %                     L1ARET,   L2ARET,  MNARET,
     %                     N3,       NT,      M1TRIA, NBTRIA, NOTRIA,
     %                     MXTRPV,   NBTRPV,  NBTRPVV, NBTRPVVV, NOTRPV,
     %                     QUAMIN0,  QUAMIN1, MODIF )
            MODIFS = MODIFS + MODIF
         ENDDO
      ENDDO

C     SI POSSIBLE ECHANGER L'ARETE COMMUNE A 2 TRIANGLES PAR L'AUTRE
C     DIAGONALE SI L'ANGLE DU DIEDRE EST INFERIEUR A ANGL2P POUR
C     TOUTES LES ARETES DU GROUPE DE NBTRPVV TRIANGLES NOTRPV
C     --------------------------------------------------------------
      NBTRPV = NBTRPVV
      CALL EC2DGTR( COSMAXPL, XYZSOM, M1TRIA, NOTRIA,
     %              MXTRPV,   NBTRPV, NOTRPV,
     %              L1ARET,   L2ARET, MNARET, NBDIAG )

C     TRACE DES TRIANGLES DE NOTRPV ET VOISINS et VOISINS DES VOISINS
      CALL TRTRIAR( 'mod1trqm 4', XYZSOM,
     %               MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %               MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )


C     AJOUT DE NTR0 A LA LISTE NOTRPV SI CE N'EST PAS DEJA LE CAS
      IF( NOTRIA(1,NTR0) .LE. 0 ) GOTO 9990
      NBTRVP = NBTRPVVV
      DO N=1,NBTRPV
         NT = NOTRPV( N )
         IF( NT .EQ. NTR0 ) GOTO 9990
      ENDDO
      NBTRPV = NBTRPV + 1
      NOTRPV( NBTRPV ) = NTR0


C     CALCUL DES QUALITES MOYENNE ET MINIMALE DU GROUPE DES
C     NBTRPV TRIANGLES NOTRPV
 9990 CALL QUMYMITR( NBTRPV, NOTRPV, M1TRIA, NOTRIA,
     %               XYZSOM, QUALMN, NBTRQI, QUAMOYF, QUAMINF, NTRMINF )

ccc      PRINT*,'mod1trqm Fin: AU DEPART Traitement du triangle NTR0=',NTR0
ccc     %      ,' de QUALITE0=',QTR0

      PRINT*,'mod1trqm Fin: Les',NBTRPV,' TRIANGLES ont une QUALITE MOYE
     %NNE=',QUAMOYF,' MINIMALE=',QUAMINF,' pour le TRIANGLE',NTRMINF,
     %' St:',(NOTRIA(K,NTRMINF),K=1,3)

      CALL TRTRIAR( 'mod1trqm F', XYZSOM,
     %               MXTRAR, L1ARET, L2ARET, MNARET, NBTRIA, NOTRIA,
     %               MXTRPV, NBTRPV, NBTRPVV, NBTRPVVV, NOTRPV )

 9999 TRACTE = TRACTE0
      RETURN
      END
