      SUBROUTINE MODGTRQM( COSMAXPL, QUALMN, MXSOM, NBSOM, XYZSOM,
     %                     MXTRAR, L1ARET, L2ARET, MNARET,
     %                     M1TRIA, MXTRIA, NBTRIA, NOTRIA,
     %                     MXTRQM, NBTRQM, NOTRQM,
     %                     MXTRPV, NOTRPV, MODIFS )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ESSAIS D'AMELIORATION DE LA QUALITE DES NBTRQM TRIANGLES
C -----    DE QUALITE INFERIEURE A QUALMN DE NUMERO NOTRQM

C ENTREES:
C --------
C COSMAXPL:COSINUS DE L'ANGLE DIEDRE ENTRE LES 2 PLANS DES TRIANGLES AU
C          DESSOUS DUQUEL LES 2 TRIANGLES SONT CONSIDERES NON-COPLANAIRES
C QUALMN : QUALITE AU DESSOUS DE LAQUELLE LA QUALITE D'UN TRIANGLE
C          EST A AMELIORER
C MXSOM  : NOMBRE MAXIMUM DE SOMMETS XYZSOM DE LA TRIANGULATION
C XYZSOM : X Y Z LES 3 COORDONNEES DES SOMMETS DE LA TRIANGULATION
C MXTRAR : NOMBRE MAXIMUM DE TRIANGLES ADJACENTS A UNE ARETE
C L1ARET : NOMBRE DE MOTS PAR ARETE DU TABLEAU LARETE
C L2ARET : NOMBRE DE ARETES DU TABLEAU LARETE
C M1TRIA : NOMBRE MD'ENTIERS DU PREMIER INDICE DU TABLEAU NOTRIA
C          =4 POUR STOCKER PAR TRIANGLE LE NO DES 3 SOMMETS + 0
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C MXTRQM : NOMBRE MAXIMAL DE NUMERO NOTRIA DE TRIANGLES DU TABLEAU NOTRQM
C NBTRQM : NOMBRE DE NUMEROS DANS NOTRIA DE TRIANGLES DU TABLEAU NOTRQM
C MXTRPV : NOMBRE MAXIMAL DE NUMERO NOTRIA DE TRIANGLES DU TABLEAU NOTRPV
C          DES TRIANGLES ET LEURS VOISINS A TRACER
C MNARET : ADRESSE MCN DU TABLEAU LARETE=MCN(MNARET)

C MODIFIES:
C ---------
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION
C LARETE : =MCN(MNARET) TABLEAU DES ARETES DU MAILLAGE
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 1-ER  TRIANGLE
C          LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                       0 SI PAS DE 2-EME TRIANGLE
C NOTRIA : NUMERO XYZSOM DES 3 SOMMETS ET 0 POUR CHACUN DES NBTRIA TRIANGLES
C NOTRQM : NUMERO NOTRIA DES TRIANGLES DE QUALITE INFERIEURE A QUALMN
C NOTRPV : NUMERO NOTRIA DES TRIANGLES + TRIANGLES VOISINS A TRACER

C SORTIE :
C --------
C MODIFS : NOMBRE DE TRIANGLES MODIFIES POUR AMELIORER LEUR QUALITE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET  Saint Pierre du Perray              Mars 2020
C....................................................................012
      include"./incl/langue.inc"
      REAL           XYZSOM(3,MXSOM)
      INTEGER        NOTRIA(M1TRIA,MXTRIA),
     %               NOTRQM(MXTRQM), NOTRPV(MXTRPV)

      MODIFS = 0
      IF( NBTRQM .LE. 0 ) GOTO 9999

C     RECONSTRUCTION DU TABLEAU DES ARETES DE LA TRIANGULATION
C     --------------------------------------------------------
C     EVENTUELLE DESTRUCTION DU TABLEAU DES ARETES DU MAILLAGE
      IF( MNARET .GT. 0 ) CALL TNMCDS( 'ENTIER', L1ARET*L2ARET, MNARET )

      CALL GEARSU( M1TRIA, NBTRIA, NOTRIA,
     %             MXTRAR, L1ARET, L2ARET, MNARET, IERR )
C     LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C     LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C     LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C     LARETE(4,I)= NUMERO DU 1-ER TRIANGLE CONTENANT CETTE ARETE
C                  0 SI PAS DE 1-ER  TRIANGLE
C     LARETE(5,I)= NUMERO DU 2-EME TRIANGLE CONTENANT CETTE ARETE
C                  0 SI PAS DE 2-EME TRIANGLE
C     LARETE(3+MXTRAR,I)= NO DU MXTRAR-EME TRIANGLE CONTENANT CETTE ARETE
C                         0 SI PAS DE MXTRAR-EME TRIANGLE
      IF( IERR .NE. 0 ) GOTO 9999

C     MODIFICATION DES NBTRQM TRIANGLES DE QUALITE < QUALMN
C     -----------------------------------------------------
      DO 10 NT = NBTRQM, 1, -1

         NTR = NOTRQM( NT )
         IF( NOTRIA(1,NTR) .EQ. 0 ) GOTO 10

C        LE TRIANGLE NTR EST ACTIF
         CALL MOD1TRQM( COSMAXPL, QUALMN, MXSOM, NBSOM, XYZSOM,
     %                  MXTRAR, L1ARET, L2ARET, MNARET,
     %                  NTR,    M1TRIA, MXTRIA, NBTRIA, NOTRIA,
     %                  MXTRPV, NOTRPV, MODIF )
         IF( MODIF .EQ. -1 ) GOTO 9999
         MODIFS = MODIFS + MODIF

 10   ENDDO

      PRINT*,'modgtrqm:',MODIFS,' MODIFICATIONS POUR AMELIORER LA QUALIT
     %E des',NBTRQM,' TRIANGLES du GROUPE'


 9999 RETURN
      END
