      SUBROUTINE MQ2F2F( I, NF0, NF1, LEFACO, PTXYZD, NONOUI )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    L'ECHANGE DU QUADRILATERE COPLANAIRE FORME PAR 2 TRIANGLES
C -----    AVEC LES 2 AUTRES TRIANGLES OFFRE T IL UNE MEILLEURE
C          QUALITE MINMALE ?
C ENTREES :
C ---------
C I      : NUMERO DE L'ARETE DE LA FACE NF0
C NF0    : NUMERO LEFACO DE LA FACE
C NF1    : NUMERO LEFACO DE LA FACE ADJACENTE A NF0 PAR SON ARETE I
C LEFACO : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C
C SORTIE :
C --------
C NONOUI : 1 SI L'ECHANGE OFFRE UNE MEILLEURE QUALITE MINIMALE
C          0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1993
C....................................................................012
      DOUBLE PRECISION  PTXYZD(1:4,1:*)
      INTEGER           LEFACO(11,0:*)
C
C     NF0 NF1 FORMENT UN QUADRANGLE
C     LES 2 SOMMETS DE L'ARETE I DE NF0
      IF( I .EQ. 3 ) THEN
         K = 1
      ELSE
         K = I + 1
      ENDIF
      NS1 = LEFACO(I,NF0)
      NS2 = LEFACO(K,NF0)
C
C     NS3 LE SOMMET RESTANT DE NF0
      IF( I .EQ. 1 ) THEN
         L = 3
      ELSE
         L = I - 1
      ENDIF
      NS3 = LEFACO(L,NF0)
C
C     NS4 LE SOMMET RESTANT DE NF1
      DO 10 K=1,3
         NS4 = LEFACO(K,NF1)
         IF( NS4 .NE. NS1 .AND. NS4 .NE. NS2 ) GOTO 20
 10   CONTINUE
C
C     LES 2 SURFACES SONT ELLES EGALES ?
 20   CALL QUADCXD( PTXYZD(1,NS1), PTXYZD(1,NS3),
     %              PTXYZD(1,NS2), PTXYZD(1,NS4), NONOUI )
      IF( NONOUI .EQ. 0 ) GOTO 9000
C
C     LES QUALITES DES TRIANGLES EN JEUX
      CALL QUTRTE( PTXYZD(1,NS1), PTXYZD(1,NS2),
     %             PTXYZD(1,NS3), Q1 )
      CALL QUTRTE( PTXYZD(1,NS1), PTXYZD(1,NS2),
     %             PTXYZD(1,NS4), Q2 )
      Q0 = MIN( Q1, Q2 )
      CALL QUTRTE( PTXYZD(1,NS3), PTXYZD(1,NS4),
     %             PTXYZD(1,NS1), Q1 )
      CALL QUTRTE( PTXYZD(1,NS3), PTXYZD(1,NS4),
     %             PTXYZD(1,NS2), Q2 )
      Q1 = MIN( Q1, Q2 )
C
      IF( Q1 .GT. Q0 ) THEN
C        ECHANGE POSSIBLE ET DE MEILLEURE QUALITE
         NONOUI = 1
      ELSE
C        ECHANGE NON POSSIBLE OU DE MOINS BONNE QUALITE MINIMALE
         NONOUI = 0
      ENDIF
C
 9000 RETURN
      END
