      SUBROUTINE N12TVT( NT, LETREE, N12TRV )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE NUMERO LETREE DES 12 TE VOISINS DU TE NT
C -----    DE MEMES NIVEAUX
C
C     ATTENTION : LE 13-EME EST A DECLARER BIEN QUE EGAL AU PREMIER
C
C ENTREES:
C --------
C NT     : NUMERO LETREE DU TE DE TE VOISINS A CALCULER
C LETREE : ARBRE-4 DES TRIANGLES EQUILATERAUX (TE) FOND DE LA TRIANGULATION
C      LETREE(0,0)  NO DU 1-ER TE VIDE DANS LETREE
C      LETREE(0,1) : MAXIMUM DU 1-ER INDICE DE LETREE (ICI 8)
C      LETREE(0,2) : MAXIMUM DECLARE DU 2-EME INDICE DE LETREE (ICI MXTREE)
C      LETREE(0:8,1) : RACINE DE L'ARBRE  (TRIANGLE SANS SUR TRIANGLE)
C      SI LETREE(0,.)>0 ALORS
C         LETREE(0:3,J) : NO (>0) LETREE DES 4 SOUS-TRIANGLES DU TRIANGLE J
C      SINON
C         LETREE(0:3,J) :-NO PXYD DES 1 … 4 POINTS INTERNES AU TRIANGLE J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C      LETREE(4,J) : NO LETREE DU SUR-TRIANGLE DU TRIANGLE J
C      LETREE(5,J) : 0 1 2 3 NO DU SOUS-TRIANGLE J POUR SON SUR-TRIANGLE
C      LETREE(6:8,J) : NO PXYD DES 3 SOMMETS DU TRIANGLE J
C
C SORTIES :
C ---------
C N12TRV  : NUMERO LETREE DES 12 TE VOISINS PAR UNE ARETE OU SOMMET
C           DANS L'ORDRE SOMMET 1 SOMMET 2 SOMMET 3
C           ET POUR LE SENS DIRECT
C           0 SI PAS DE TE VOISIN (RACINE , ... )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    FEVRIER 1992
C2345X7..............................................................012
      INTEGER           LETREE(0:8,0:*),N12TRV(13)
C
C     ESSAI DANS LE SENS DIRECT AUTOUR DES 3 SOMMETS
      DO 10 NST=1,3
         CALL N5TRVS( NT, NST, LETREE, N12TRV(4*NST-3) )
C        ATTENTION : LE 13-EME EST A DECLARER CAR CALCULE ICI
 10   CONTINUE
      END
