      SUBROUTINE NOFQPF( NAR, NF, LEFACO, NF0, NA0 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE NUMERO DANS LEFACO DE LA FACE QUI PRECEDE
C -----    DANS LE CHAINAGE CIRCULAIRE LA FACE OPPOSEE A L'ARETE NAR
C          DE NF DE LEFACO
C
C ENTREES:
C --------
C NAR    : NUMERO DE L'ARETE DE LA FACE NF DE LEFACO
C NF     : NUMERO DANS LEFACO DE LA FACE A DETRUIRE
C LEFACO : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES
C
C SORTIES:
C --------
C NF0    : NUMERO DE LA FACE PRECEDANT NF DANS LE CHAINAGE CIRCULAIRE
C          0 SI LA FACE ADJACENTE EST ELLE MEME OU N'EXISTE PAS
C NA0    : NUMERO DE 1 A 3 DE L'ARETE DANS NF0 IDENTIQUE A NAR DE NF
C          0 SI LA FACE ADJACENTE EST ELLE MEME OU N'EXISTE PAS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    OCTOBRE 1991
C2345X7..............................................................012
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      INTEGER  LEFACO(1:11,0:*)
C
C     LES 2 SOMMETS DE L'ARETE NAR DE NF
      NS1 = LEFACO( NAR, NF )
      NS2 = LEFACO( MOD(NAR,3)+1, NF )
C
C     PARCOURS DES FACES ADJACENTES A PARTIR DE NF ( ARETE NAR )
      NA0 = 0
      NF0 = 0
      NF1 = LEFACO( 5+NAR, NF )
      IF( NF1 .LE. 0 ) RETURN
C
 10   IF( NF1 .NE. NF ) THEN
C        PASSAGE A LA FACE SUIVANTE DANS LE CHAINAGE CIRCULAIRE
         NF0 = NF1
         CALL NO1A1F( NS1, NS2, LEFACO(1,NF0), NA0 )
         IF( NA0 .LE. 0 ) THEN
            WRITE(IMPRIM,*) 'NOFQPF: ANOMALIE NA0=0'
            WRITE(IMPRIM,10010) NF0,(LEFACO(I,NF0),I=1,10)
10010       FORMAT(' LEFACO(',I6,')=',10I7)
            NF0 = 0
            RETURN
         ENDIF
         NF1 = LEFACO( 5+NA0, NF0 )
         IF( NF1 .GT. 0 ) GOTO 10
         NA0 = 0
         NF0 = 0
      ENDIF
      END
