      SUBROUTINE NOPOMODULEF
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : SORTIR SUR UN FICHIER nopomodulef.NomObjet SELON LA DIMENSION
C ----- DE L'ESPACE DE L'OBJET
C       si NDIM=2 LES VERTICES, TRIANGLES, QUADRANGLES ET
C                 ARETES de la FRONTIERE
C       si NDIM=3 LES VERTICES, LES ELEMENTS FINIS ET
C                 FACES de la FRONTIERE
C       D'UN OBJET MAILLE PAR MEFISTO C-A-D A PARTIR DE SES
C       NUMEROS DE NOEUDS DES EF, DES VOLUMES SURFACES LIGNES POINTS
C       ET CELA POUR UNE UTILISATION ULTERIEURE DE LA SD NOPO DE MODULEF
C
C ATTENTION: SOMMETS et NOEUDS et POINTS SONT ICI SUPPOSES IDENTIQUES!
C       i.e. INTERPOLATION LAGRANGE DE DEGRE 1 SUR LES ELEMENTS FINIS
C
C SORTIE :
C --------
C LE FICHIER nopomodulef.NomObjet DANS LE REPERTOIRE DU PROJET
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET LJLL UPMC PARIS & St PIERRE DU PERRAY MAI 2011
C23456---------------------------------------------------------------012
      PARAMETER         (MXTYEL=7)
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a_objet__definition.inc"
      include"./incl/a_ligne__definition.inc"
      include"./incl/a_transfo__definition.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___texte.inc"
      include"./incl/msvaau.inc"
      include"./incl/ponoel.inc"
      include"./incl/pp.inc"
      COMMON             MCN(MOTMCN)
      REAL               RMCN(1)
      EQUIVALENCE       (MCN(1),RMCN(1))
      COMMON / UNITES /  LECTEU, IMPRIM, INTERA, NUNITE(29)
      COMMON / TRAVA1 /  MTITRE(20), NDATE(2), NOMCRE(6)
      CHARACTER*4        NOMELE(2)
      CHARACTER*10       NMTYOB,KNM,KNMS
      CHARACTER*24       KNOMOB,KNOM
      CHARACTER*80       KINFO
      CHARACTER*32       KNMFIC
      LOGICAL            LEXIST,LOPEN
      INTEGER            NBPLSV(4)
      INTEGER            NOOBVC, NOOBSF(6), NOOBLA(12), NOOBPS(8)
      INTEGER            NONOEF(20)
C
C     NOM DE L'OBJET A TRAITER
C     ------------------------
 10   CALL INVITE( 45 )
      IERR   = 0
      NCVALS = 0
      CALL LIRCAR( NCVALS, KNOMOB )
      IF( NCVALS .EQ. -1 ) RETURN
C
      MNELEM = 0
      IANOP0 = 0
      IANOP2 = 0
      IANOP5 = 0
C
C     RECHERCHE DU NOM DE L'OBJET DANS LE LEXIQUE DES OBJETS
      CALL LXLXOU( NTOBJE, KNOMOB, NTLXOB, MNLXOB )
C     S'IL N'EXISTE PAS RETOUR A LA DEMANDE DU NOM DE L'OBJET
      IF( NTLXOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) = KNOMOB
         IF( LANGAG .EQ. 0 ) THEN
            KERR(2) = 'OBJET INCONNU'
         ELSE
            KERR(2) = 'UNKNOWN OBJECT'
         ENDIF
         CALL LEREUR
         CALL LXIM( NTOBJE )
         GOTO 10
      ENDIF
C
C     TRACE DE L'OBJET
      NBLGRC(NRHIST) = 1
      KHIST(1) = 'OBJET: ' // KNOMOB
      CALL LHISTO
      IF( INTERA .GE. 1 ) THEN
C        TRACE DE L'OBJET SI CONSOLE GRAPHIQUE INTERACTIVE
         CALL T1OBJE( KNOMOB )
      ENDIF
C
C     RECHERCHE DU TABLEAU DEFINITION DE L'OBJET
      CALL LXTSOU( NTLXOB, 'DEFINITION', NTDFOB, MNDFOB )
C     S'IL N'EXISTE PAS RETOUR A LA DEMANDE DU NOM DE L'OBJET
      IF( NTDFOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) = KNOMOB
         IF( LANGAG .EQ. 0 ) THEN
            KERR(2) = 'OBJET SANS TMS de DEFINITION'
         ELSE
            KERR(2) = 'OBJECT WITHOUT the TMS DEFINITION'
         ENDIF
         CALL LEREUR
         GOTO 10
      ENDIF
C
C     ADRESSAGE DES ADRESSES DES TABLEAUX NPEF"xxxx DE CET OBJET
      MNELEM = 0
      CALL TNMCDC( 'ENTIER', 2*MXTYEL, MNELEM )
      MNTELE = MNELEM + MXTYEL
C
C     RECHERCHE DES TABLEAUX XYZSOMMET XYZNOEUD XYZPOINT ASSOCIES A L'OBJET
      CALL NDPGEL( NTLXOB, NTTOPO, MNTOPO ,
     %             NTXYZP, MNXYZP, NTXYZN, MNXYZN ,
     %             NBTYEL, MCN(MNTELE), MCN(MNELEM), IERR )
      IF( IERR .NE. 0 ) GOTO 9900
C
C     LE TYPE DE MAILLAGE ET LES OBJETS INTERNES ET AUX LIMITES DE L'OBJET
      NDPGST = MCN( MNTOPO + WDPGST )
      NBOBIN = MCN( MNTOPO + WBOBIN )
      NBOBCL = MCN( MNTOPO + WBOBCL )
C
C     LA VALEUR DE Z DES POINTS DU MAILLAGE DE L'OBJET DEFINIT
C     NDIM LA DIMENSION 2 OU 3 DE L'ESPACE DES COORDONNEES
C     ATTENTION: CETTE PROGRAMMATION SOUS ENTEND NOEUDS=POINTS
      NBNOEU = MCN(MNXYZP+WNBPOI)
      CALL DIMCOO( NBNOEU, MCN(MNXYZP+WYZPOI), NDIM )
C
      WRITE(IMPRIM,*)
      IF( LANGAG .EQ. 0 ) THEN
      WRITE(IMPRIM,10059) KNOMOB
10059 FORMAT(A24, ' NOM de l''OBJET pour nopomodulef')
      WRITE(IMPRIM,10210) NDIM,NBNOEU,NBOBIN,NBOBCL,NBTYEL
10210 FORMAT(' DIMENSION 2 OU 3 DE L''ESPACE',T30,'=',I10/
     %' NOMBRE DE NOEUDS'                    ,T30,'=',I10/
     %' NOMBRE D''OBJETS INTERNES'           ,T30,'=',I10/
     %' NOMBRE D''OBJETS AUX LIMITES'        ,T30,'=',I10/
     %' NOMBRE DE TYPES D''EF'               ,T30,'=',I10)
      ELSE
      WRITE(IMPRIM,11059) KNOMOB
11059 FORMAT(A24, ' NAME of the OBJECT for nopomodulef')
      WRITE(IMPRIM,11210) NDIM,NBNOEU,NBOBIN,NBOBCL,NBTYEL
11210 FORMAT(' SPACE''s DIMENSION (2 or 3)',T30,'=',I10/
     %' NUMBER of NODES'                   ,T30,'=',I10/
     %' NUMBER of MATERIALS'               ,T30,'=',I10/
     %' NUMBER of PL(S) at the BOUNDARY'   ,T30,'=',I10/
     %' NUMBER of TYPES of FE'             ,T30,'=',I10)
      ENDIF
C
C     BOUCLE SUR LES OBJETS "INTERNES": calcul du nombre d'EF de nopomodulef
C     ======================================================================
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,14100) NBOBIN
      ELSE
         WRITE(IMPRIM,13100) NBOBIN
      ENDIF
14100 FORMAT(/,I10,' NBOBIN NOMBRE DE MATERIAUX' )
13100 FORMAT(/,I10,' NBOBIN NUMBER of MATERIALS' )
C
C     L'ADRESSE MCN DU DEBUT DU TABLEAU NUOBIN
      MNOBIN = MNTOPO + WMTYEL + NBTYEL
      MN     = MNOBIN - 2
      NDSD   = 0
      DO 100 I=1,NBOBIN
C        LE TYPE DE L'OBJET
         MN   = MN + 2
         NYOB = MCN( MN )
         NUOB = MCN( MN + 1 )
C        OUVERTURE DE L'OBJET
         CALL LXNLOU( NTMN(NYOB), NUOB, NTOB, MNOB )
         KNM = NMTYOB( NYOB )
         CALL NMOBNU( KNM, NUOB, KNOM )
         IF( NTOB .LE. 0 ) THEN
            NBLGRC(NRERR) = 2
            KERR(1) = KNOM
            IF( LANGAG .EQ. 0 ) THEN
               KERR(2) = 'MATERIAU INCONNU'
            ELSE
               KERR(2) = 'UNKNOWN MATERIAL'
            ENDIF
            CALL LEREUR
            IERR = IERR + 1
            GOTO 100
         ENDIF
C        ECRITURE DU NOM DE L'OBJET INTERNE ou MATERIAU I
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10102) NUOB, KNM, KNOM
         ELSE
            WRITE(IMPRIM,11102) NUOB, KNM, KNOM
         ENDIF
 100  CONTINUE
      NDSD = MAX( NDSD, NUOB )
10102 FORMAT( I10,' est le NUMERO dans ',A10,' de  ', A24 )
11102 FORMAT( I10,' is the NUMBER in ',A10,' of  ', A24 )
      IF( IERR .NE. 0 ) GOTO 9900
      NBPLSV(NDIM+1) = NBOBIN
C
C     BOUCLE SUR LES OBJETS AUX LIMITES DE L'OBJET
C     RECHERCHE DU NOMBRE DE POINTS LIGNES SURFACES DE L'OBJET
C     ========================================================
C     RECENSEMENT DU NOMBRE DE POINTS, LIGNES, ... DE L'OBJET
C     BOUCLE SUR LES SURFACES(SI NDIM=3) LIGNES ET POINTS
C     L'ADRESSE MCN DU DEBUT DU TABLEAU NUOBCL
      NDSR = 0
      MNOBCL = MNOBIN + MOTVAR(13) * NBOBIN
      DO 130 L=NDIM,1,-1
         NBPLSV(L) = 0
         KNM = NMTYOB( L )
         MN  = MNOBCL - 2
         DO 120 I=1,NBOBCL
C           LE TYPE DE L'OBJET
            MN   = MN + 2
            NYOB = MCN( MN )
            IF( NYOB .NE. L ) GOTO 120
            NUOB = MCN( MN + 1 )
C           OUVERTURE DE L'OBJET
            CALL LXNLOU( NTMN(NYOB), NUOB, NTOB, MNOB )
            CALL NMOBNU( KNM, NUOB, KNOM )
            IF( NTOB .LE. 0 ) THEN
               NBLGRC(NRERR) = 1
               IF( LANGAG .EQ. 0 ) THEN
                  KERR(1) = KNM // ':' // KNOM // ' INCONNU'
               ELSE
                  KERR(1) = KNM // ': UNKNOWN ' // KNOM
               ENDIF
               CALL LEREUR
               IERR = IERR + 1
               GOTO 120
            ENDIF
C           UN PLS DE TYPE L DE PLUS
            NBPLSV(L) = NBPLSV(L) + 1
            NDSR = MAX( NDSR, NUOB )
 120     CONTINUE
 130  CONTINUE
C
C     BOUCLE SUR LES SURFACES(SI NDIM=3) LIGNES ET POINTS AUX LIMITES
      DO 150 L=NDIM,1,-1
C        ECRITURE DU NOMBRE D'OBJETS AUX LIMITES DE TYPE L
         KNM = NMTYOB( L )
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10140) NBPLSV(L),KNM
         ELSE
            WRITE(IMPRIM,11140) NBPLSV(L),KNM
         ENDIF
10140    FORMAT(/, I10,' NOMBRE de ',A10 )
11140    FORMAT(/, I10,' NUMBER of ',A10 )
         MN  = MNOBCL - 2
         DO 140 I=1,NBOBCL
C           LE TYPE DE L'OBJET
            MN   = MN + 2
            NYOB = MCN( MN )
            IF( NYOB .NE. L ) GOTO 140
            NUOB = MCN( MN + 1 )
C           OUVERTURE DE L'OBJET
            CALL LXNLOU( NTMN(NYOB), NUOB, NTOB, MNOB )
            CALL NMOBNU( KNM, NUOB, KNOM )
            IF( NTOB .LE. 0 ) THEN
               NBLGRC(NRERR) = 1
               IF( LANGAG .EQ. 0 ) THEN
                  KERR(1) = KNM // ':' // KNOM // ' INCONNU'
               ELSE
                  KERR(1) = KNM // ': UNKNOWN ' // KNOM
               ENDIF
               CALL LEREUR
               GOTO 140
            ENDIF
C           ECRITURE DU NOM DE L'OBJET AUX LIMITES
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,10102) NUOB, KNM, KNOM
            ELSE
               WRITE(IMPRIM,11102) NUOB, KNM, KNOM
            ENDIF
 140     CONTINUE
 150  CONTINUE
      IF( IERR .GT. 0 ) GOTO 9900
C
C     LA BOUCLE SUR LES DIFFERENTS TYPES D'EF (TABLEAUX NPEF"xxxx)
C     CALCUL DU NOMBRE D'EF POUR nopomodulef
C     ============================================================
C     ECRITURE DU NOMBRE DE TYPE D'EF
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10390) NBTYEL
      ELSE
         WRITE(IMPRIM,11390) NBTYEL
      ENDIF
10390 FORMAT(/, I10,' NBTYEL NOMBRE DE TYPES D''EF de l''OBJET' )
11390 FORMAT(/, I10,' NBTYEL NUMBER of TYPES of FE of the OBJECT' )
C
      NBEF   = 0
      NBPOEF = 0
      NBSEGM = 0
      NBTRIA = 0
      NBQUAD = 0
      NBTETR = 0
      NBPENT = 0
      NBPYRA = 0
      NBHEXA = 0
      DO NOTYEL = 1, NBTYEL
C
C        L'ADRESSE DU TABLEAU NPEF"xxxx
         MNELE = MCN( MNELEM - 1 + NOTYEL )
C
C        LE NUMERO DU TYPE DE L'ELEMENT FINI
         NUTYEL = MCN( MNELE + WUTYEL )
C
C        NCOGEL LE CODE GEOMETRIQUE DE L'ELEMENT FINI EST CALCULE
         CALL ELNUCG( NUTYEL, NCOGEL )
C
C        LE NOMBRE D'ELEMENTS FINIS DE CE TYPE
         NBELEM = MCN( MNELE + WBELEM )
C
C        NOMBRE TOTAL D'EF
         NBEF = NBEF + NBELEM
C
         IF( NCOGEL .EQ. 1 ) THEN
C           NB POINTS EF
            NBPOEF = NBPOEF + NBEF
         ELSE IF( NCOGEL .EQ. 2 ) THEN
C           NB SEGMENTS EF
            NBSEGM = NBSEGM + NBEF
         ELSE IF( NCOGEL .EQ. 3 ) THEN
C           NB TRIANGLES EF
            NBTRIA = NBTRIA + NBEF
         ELSE IF( NCOGEL .EQ. 4 ) THEN
C           NB QUADRANGLES EF
            NBQUAD = NBQUAD + NBEF
         ELSE IF( NCOGEL .EQ. 5 ) THEN
C           NB TETRAEDRES EF
            NBTETR = NBTETR + NBEF
         ELSE IF( NCOGEL .EQ. 6 ) THEN
C           NB PENTAEDRES EF
            NBPENT = NBPENT + NBEF
         ELSE IF( NCOGEL .EQ. 7 ) THEN
C           NB HEXAEDRES EF
            NBHEXA = NBHEXA + NBEF
         ENDIF
C
      ENDDO
C
C     CALCUL DE LPGDN, LNOP5
C     ======================
C     BOUCLE SUR LES TYPES D'EF
      LNOP5 = 0
      LPGDN = 0
      NBNOA = 0
      DO NOTYEL = 1, NBTYEL
C
C        L'ADRESSE DU TABLEAU NPEF"xxxx
         MNELE = MCN( MNELEM - 1 + NOTYEL )
C
C        LE NUMERO DU TYPE DE L'ELEMENT FINI
         NUTYEL = MCN( MNELE + WUTYEL )
C
C        NCOGEL LE CODE GEOMETRIQUE DE L'ELEMENT FINI EST CALCULE
         CALL ELNUCG( NUTYEL, NCOGEL )
C
C        NOMBRE DE SOMMETS DE CE TYPE D'EF
         NBS = NBSOME ( NCOGEL )
C
C        LE NOMBRE D'ELEMENTS FINIS DE CE TYPE
         NBELEM = MCN( MNELE + WBELEM )
C
C        L'ADRESSE MCN DES NOEUDS ET POINTS GEOMETRIQUES DES ELEMENTS FINIS
         MNNDEL = MNELE + WUNDEL
         MNPGEL = MNNDEL
         IF( NDPGST .GE. 2 ) THEN
            MNPGEL = MNPGEL + NBELEM * MCN(MNELE+WBNDEL)
         ENDIF
C
C        LES CARACTERISTIQUES DE L'ELEMENT FINI
         CALL ELNUNM( NUTYEL, NOMELE )
         CALL ELTYCA( NUTYEL )
C
         DO NUELEM = 1, NBELEM
C
C           NO DES NOEUDS DE L'ELEMENT FINI NUELEM
            CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOEF )
C
C           NOMBRE DE NOEUDS INTERNES A UNE ARETE
            IF( NBS .NE. NBNOEF ) THEN
C              UN MILIEU D'ARETE
               NBNOA = 1
            ENDIF
C
C           MIN ET MAX DES NOEUDS DE L'EF
            MINNO = NONOEF(1)
            MAXNO = MINNO
            DO N=1,NBNOEF
               MINNO = MIN( MINNO, NONOEF(N) )
               MAXNO = MAX( MINNO, NONOEF(N) )
            ENDDO
            LPGDN = MAX( LPGDN, MAXNO-MINNO )
C
C           NO DES POINTS  LIGNES SURFACES VOLUMES DES
C                  SOMMETS ARETES FACES    VOLUME DE L'EF
            CALL EFPLSV( MNELE , NUELEM,
     %                   NOVCEL, NOSFEL, NOLAEL, NOPSEL,
     %                   NOOBVC, NOOBSF, NOOBLA, NOOBPS )
C
C           NDSDE NUMERO DE SOUS-DOMAINE DE L'EF
            IF( NDIM .EQ. 2 ) THEN
               NDSDE = NOOBSF(1)
            ELSE
               NDSDE = NOOBVC
            ENDIF
C
C           NMAE  NOMBRE DE MOTS POUR STOCKER LES REFERENCES
C           NOMBRE DE NON ZERO DANS NOOBPS
            NBNZPS = 0
            DO N=1,NBNSOM
               IF( NOOBPS(N) .NE. 0 ) NBNZPS = NBNSOM
            ENDDO
C           NOMBRE DE NON ZERO DANS NOOBLA
            NBNZLA = 0
            DO N=1,NARET
               IF( NOOBLA(N) .NE. 0 ) NBNZLA = NARET
            ENDDO
C           NOMBRE DE NON ZERO DANS NOOBSF
            NBNZSF = 0
            IF( NDIM .EQ. 3 ) THEN
               DO N=1,NFACE
                  IF( NOOBSF(N) .NE. 0 ) NBNZSF = NFACE
               ENDDO
            ENDIF
            NMAE  = NBNZSF + NBNZLA + NBNZPS
            INING = 0
            IF( NBNZPS .GT. 0 ) INING = 3
            IF( NBNZLA .GT. 0 ) INING = 2
            IF( NBNZSF .GT. 0 ) INING = 1
            IF( INING  .GT. 0 ) NMAE  = NMAE + 1
C
            LNOP5 = LNOP5 + 4 + NBNOEF + NMAE
         ENDDO
      ENDDO
C
C     DECLARATION OUVERTURE DU FICHIER nopomodulef.NOM_OBJET
C     ======================================================
C     LE NOM DU FICHIER
      I = NUDCNB( KNOMOB )
      KNMFIC = 'nopomodulef' // '.' // KNOMOB(1:I)
C
C     SI LE FICHIER KNMFIC EXISTE ALORS IL EST DETRUIT PUIS RECONSTRUIT
      INQUIRE( FILE=KNMFIC, EXIST=LEXIST, OPENED=LOPEN )
      IF( LEXIST ) THEN
C        LE FICHIER KNMFIC EXISTE
         IF( .NOT. LOPEN ) THEN
C           OUVERTURE DU FICHIER KNMFIC
            CALL TRUNIT( NOFILE )
            OPEN( FILE=KNMFIC, UNIT=NOFILE, STATUS='OLD' )
         ENDIF
C        DESTRUCTION DU FICHIER
         CLOSE( NOFILE, STATUS='DELETE' )
      ENDIF
C
C     CREATION DU FICHIER KNMFIC
      CALL TRUNIT( NOFILE )
      OPEN( UNIT=NOFILE, ERR=9999, STATUS='NEW',
     %      FILE=KNMFIC, ACCESS='SEQUENTIAL', FORM='FORMATTED' )
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10001) KNMFIC
10001 FORMAT(/' CREATION du FICHIER ',A)
      ELSE
         WRITE(IMPRIM,10002) KNMFIC
10002 FORMAT(/' CREATION of the FILE ',A)
      ENDIF
C
C     ***********************************************************
C     ECRITURE DES DONNEES DU MAILLAGE SUR LE FICHIER nopomodulef
C     ***********************************************************
C
C     TABLEAU NOP0  DECLARATION, INITIALISATION
C     ============
      CALL TNMCDC( 'ENTIER', 32, IANOP0 )
C
C     TITRE, DATE, NOM CREATEUR
      CALL TRTATA( MTITRE, MCN(IANOP0), 20+2+6 )
C
C     NOM DE LA SD
      MCN(IANOP0+28) = ICHARX('NOPO')
C
C     NIVEAU
      MCN(IANOP0+29) = 0
C
C     ETAT
      MCN(IANOP0+30) = 0
C
C     NTACM  NOMBRE DE TABLEAUX ASSOCIES A CETTE SD
      MCN(IANOP0+31) = 0
C
C     ECRITURE SUR LE FICHIER DU TABLEAU NOP0
      WRITE(NOFILE,'(A)'  ) KNMFIC
      WRITE(NOFILE,'(A8)' ) KINFO('DATE')
      WRITE(NOFILE,'(A24)') KINFO('UTILISATEUR')
      WRITE(NOFILE,'(A4)' ) 'NOPO'
      WRITE(NOFILE,12000) (MCN(IANOP0+K),K=29,31)
12000 FORMAT( I10 )
      IF( LANGAG .EQ. 0 ) THEN
      WRITE(IMPRIM,*) 'TABLEAU NOP0',32,' MOTS ecrit sur ',KNMFIC
      ELSE
      WRITE(IMPRIM,*) 'ARRAY NOP0',32,' WORDS on ',KNMFIC
      ENDIF
C
C     DESTRUCTION DU TABLEAU NOP0
      CALL TNMCDS( 'ENTIER', 32, IANOP0 )
C
C     PAS DE TABLEAU NOP1 (TABLEAUX ASSOCIES A CETTE SD)
C     ==================================================
C
C     TABLEAU NOP2  DECLARATION, INITIALISATION
C     ============
      CALL TNMCDC( 'ENTIER', 27, IANOP2 )
C
C     DIMENSION DE L'ESPACE DE TRAVAIL
      MCN(IANOP2) = NDIM
C
C     MAXIMUM DES NUMEROS DE REFERENCE
      MCN(IANOP2+1) = NDSR
C
C     MAXIMUM DES NUMEROS DE SOUS-DOMAINES
      MCN(IANOP2+2) = NDSD
C
C     NOEUDS=POINTS=SOMMETS
      MCN(IANOP2+3) = 1
C
C     NOMBRE D'EF
      MCN(IANOP2+4) = NBEF
C
C     NOMBRE D'EF REDUITS A UN POINT
      MCN(IANOP2+5) = NBPOEF
C
C     NOMBRE D'EF SEGMENTS
      MCN(IANOP2+6) = NBSEGM
C
C     NOMBRE D'EF TRIANGLES
      MCN(IANOP2+7) = NBTRIA
C
C     NOMBRE D'EF QUADRANGLES
      MCN(IANOP2+8) = NBQUAD
C
C     NOMBRE D'EF TETRAEDRES
      MCN(IANOP2+9) = NBTETR
C
C     NOMBRE D'EF PENTAEDRES
      MCN(IANOP2+10) = NBPENT
C
C     NOMBRE D'EF HEXAEDRES
      MCN(IANOP2+11) = NBHEXA
C
C     NOMBRE D'EF SUPER-ELEMENTS
      MCN(IANOP2+12) = 0
C
C     NOMBRE D'EF FRONTALIERS  (EN FAIT NON CALCULE CAR INUTILE?)
      MCN(IANOP2+13) = 1
C
C     NOMBRE DE NOEUDS=POINTS=SOMMETS
      MCN(IANOP2+14) = NBNOEU
C
C     NOMBRE DE NOEUDS SUR UN SEGMENT EXTREMITES EXCLUES
      MCN(IANOP2+15) = NBNOA
C
C     NOMBRE DE NOEUDS INTERNES A UN TRIANGLE
      MCN(IANOP2+16) = 0
C
C     NOMBRE DE NOEUDS INTERNES A UN QUADRANGLE
      MCN(IANOP2+17) = 0
C
C     NOMBRE DE NOEUDS INTERNES A UN TETRAEDRE
      MCN(IANOP2+18) = 0
C
C     NOMBRE DE NOEUDS INTERNES A UN PENTAEDRE
      MCN(IANOP2+19) = 0
C
C     NOMBRE DE NOEUDS INTERNES A UN HEXAEDRE
      MCN(IANOP2+20) = 0
C
C     NOMBRE DE POINTS=NOEUDS=SOMMETS
      MCN(IANOP2+21) = NBNOEU
C
C     TYPE DES VALEURS DES COORDONNEES 2 REEL SIMPLE PRECISION
      MCN(IANOP2+22) = 2
C
C     LA PLUS GRANDE DIFFERENCE ENTRE 2 SOMMETS D'UN MEME EF +1
      MCN(IANOP2+23) = LPGDN+1
C
C     NOMBRE D'EF GROSSIERS
      MCN(IANOP2+24) = 0
C
C     NOMBRE DE MOTS DU TABLEAU NOP5
      MCN(IANOP2+25) = LNOP5
C
C     AXES COORDONNEES CARTESIENNES
      MCN(IANOP2+26) = 1
C
C     ECRITURE SUR LE FICHIER DU TABLEAU NOP0
      WRITE(NOFILE,12000) (MCN(IANOP2+K),K=0,26)
      CALL TNMCDS( 'ENTIER', 27, IANOP2 )
      IF( LANGAG .EQ. 0 ) THEN
      WRITE(IMPRIM,*) 'TABLEAU NOP2',27,' MOTS ecrit sur ',KNMFIC
      ELSE
      WRITE(IMPRIM,*) 'ARRAY NOP2',27,' WORDS on ',KNMFIC
      ENDIF
C
C     PAS DE TABLEAU NOP3 (TABLEAUX DES EF GROSSIERS)
C     ===============================================
C
C     TABLEAU NOP4  MISE SUR LE FICHIER DES XYZ DES SOMMETS
C     ============
12004 FORMAT( 3E16.7 )
      MN = MNXYZN + WYZNOE - 1
      DO N=1,NBNOEU
         WRITE(NOFILE,12004) (RMCN(MN+K),K=1,NDIM)
         MN = MN + 3
      ENDDO
      IF( LANGAG .EQ. 0 ) THEN
      WRITE(IMPRIM,*) 'TABLEAU NOP4',NDIM*NBNOEU,' MOTS ecrit sur ',
     %                 KNMFIC
      ELSE
      WRITE(IMPRIM,*) 'ARRAY NOP4',NDIM*NBNOEU,' WORDS on ',KNMFIC
      ENDIF
C
C     TABLEAU NOP5  DECLARATION, INITIALISATION
C     ============
      CALL TNMCDC( 'ENTIER', LNOP5, IANOP5 )
C
C     BOUCLE SUR LES TYPES D'EF
      DO NOTYEL = 1, NBTYEL
C
C        L'ADRESSE DU TABLEAU NPEF"xxxx
         MNELE = MCN( MNELEM - 1 + NOTYEL )
C
C        LE NUMERO DU TYPE DE L'ELEMENT FINI
         NUTYEL = MCN( MNELE + WUTYEL )
C
C        NCOGEL LE CODE GEOMETRIQUE DE L'ELEMENT FINI EST CALCULE
         CALL ELNUCG( NUTYEL, NCOGEL )
C
C        LE NOMBRE D'ELEMENTS FINIS DE CE TYPE
         NBELEM = MCN( MNELE + WBELEM )
C
C        L'ADRESSE MCN DES NOEUDS ET POINTS GEOMETRIQUES DES ELEMENTS FINIS
         MNNDEL = MNELE + WUNDEL
         MNPGEL = MNNDEL
         IF( NDPGST .GE. 2 ) THEN
            MNPGEL = MNPGEL + NBELEM * MCN(MNELE+WBNDEL)
         ENDIF
C
C        LES CARACTERISTIQUES DE L'ELEMENT FINI
         CALL ELNUNM( NUTYEL, NOMELE )
         CALL ELTYCA( NUTYEL )
C
         DO NUELEM = 1, NBELEM
C
C           NO DES NOEUDS DE L'ELEMENT FINI NUELEM
            CALL EFNOEU( MNELE, NUELEM, NBNOEF, NONOEF )
C
C           NO DES POINTS LIGNES SURFACES VOLUMES DES SOMMETS ARETES FACES VOLUM
            CALL EFPLSV( MNELE , NUELEM,
     %                   NOVCEL, NOSFEL, NOLAEL, NOPSEL,
     %                   NOOBVC, NOOBSF, NOOBLA, NOOBPS )
C
C           NDSDE NUMERO DE SOUS-DOMAINE DE L'EF
            IF( NDIM .EQ. 2 ) THEN
               NDSDE = NOOBSF(1)
            ELSE
               NDSDE = NOOBVC
            ENDIF
C
C           NMAE  NOMBRE DE MOTS POUR STOCKER LES REFERENCES
C           NOMBRE DE NON ZERO DANS NOOBPS
            NBNZPS = 0
            DO N=1,NBNSOM
               IF( NOOBPS(N) .NE. 0 ) NBNZPS = NBNSOM
            ENDDO
C           NOMBRE DE NON ZERO DANS NOOBLA
            NBNZLA = 0
            DO N=1,NARET
               IF( NOOBLA(N) .NE. 0 ) NBNZLA = NARET
            ENDDO
C           NOMBRE DE NON ZERO DANS NOOBSF
            NBNZSF = 0
            IF( NDIM .EQ. 3 ) THEN
               DO N=1,NFACE
                  IF( NOOBSF(N) .NE. 0 ) NBNZSF = NFACE
               ENDDO
            ENDIF
            NMAE  = NBNZSF + NBNZLA + NBNZPS
            INING = 0
            IF( NBNZPS .GT. 0 ) INING = 3
            IF( NBNZLA .GT. 0 ) INING = 2
            IF( NBNZSF .GT. 0 ) INING = 1
            IF( INING  .GT. 0 ) NMAE  = NMAE + 1
C
C           ECRITURE SUR LE FICHIER nopomefisto des DONNEES de l'EF
            WRITE(NOFILE,12010) NCOGEL, NMAE, NDSDE, NBNOEF
C           NBNOEF NUMEROS DES NOEUDS DE L'EF
            WRITE(NOFILE,12010) (NONOEF(K),K=1,NBNOEF)
C           NMAE INFORMATIONS SUR LA FRONTIERE de l'EF
            IF( NMAE .GT. 0 ) THEN
               WRITE(NOFILE,12010) INING,
     %                            (NOOBSF(K),K=1,NBNZSF),
     %                            (NOOBLA(K),K=1,NBNZLA),
     %                            (NOOBPS(K),K=1,NBNZPS)
            ENDIF
         ENDDO
      ENDDO
12010 FORMAT( 10I10 )
      IF( LANGAG .EQ. 0 ) THEN
      WRITE(IMPRIM,*) 'TABLEAU NOP5',LNOP5,' MOTS ecrit sur ',KNMFIC
      ELSE
      WRITE(IMPRIM,*) 'ARRAY NOP5',LNOP5,' WORDS on ',KNMFIC
      ENDIF
C
      CALL TNMCDS( 'ENTIER', LNOP5, IANOP5 )
C
C     ECRITURE DU NOMBRE D'OBJETS INTERNES OU MATERIAUX
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(NOFILE,14100) NBOBIN
      ELSE
         WRITE(NOFILE,13100) NBOBIN
      ENDIF
C
C     CORRESPONDANCE NO DE SOUS-DOMAINE<=> NOM de MATERIAU
C     L'ADRESSE MCN DU DEBUT DU TABLEAU NUOBIN
      MNOBIN = MNTOPO + WMTYEL + NBTYEL
      MN     = MNOBIN - 2
      DO 600 I=1,NBOBIN
C        LE TYPE DE L'OBJET
         MN   = MN + 2
         NYOB = MCN( MN )
         NUOB = MCN( MN + 1 )
C        OUVERTURE DE L'OBJET
         CALL LXNLOU( NTMN(NYOB), NUOB, NTOB, MNOB )
         KNM = NMTYOB( NYOB )
         CALL NMOBNU( KNM, NUOB, KNOM )
C        ECRITURE DU NOM DE L'OBJET INTERNE I
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(NOFILE,14602) NUOB, KNM, KNOM
         ELSE
            WRITE(NOFILE,13602) NUOB, KNM, KNOM
         ENDIF
 600  CONTINUE
14602 FORMAT( I10,' est le NUMERO dans ',A10,' de  ',A )
13602 FORMAT( I10,' is the NUMBER in ',A10,' of  ',A )
C
C     ECRITURE DU NOMBRE D'OBJETS AUX LIMITES DE L'OBJET
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(NOFILE,14620) NBOBCL
      ELSE
         WRITE(NOFILE,13620) NBOBCL
      ENDIF
14620 FORMAT( I10,' NBOBCL NOMBRE D''OBJETS AUX LIMITES' )
13620 FORMAT( I10,' NBOBCL NUMBER of PL(S) on the BOUNDARY' )
C
C     BOUCLE SUR LES SURFACES(SI NDIM=3) LIGNES ET POINTS
      DO 650 L=NDIM,1,-1
C        ECRITURE DU NOMBRE D'OBJETS AUX LIMITES DE TYPE L
         KNM = NMTYOB( L )
         M   = NUDCNB(KNM)
         KNMS = KNM(1:M) // 'S'
         WRITE(NOFILE,13640) NBPLSV(L),KNMS(1:M+1)
13640    FORMAT( I10,' ',A )
         MN  = MNOBCL - 2
         DO 640 I=1,NBOBCL
C           LE TYPE DE L'OBJET
            MN   = MN + 2
            NYOB = MCN( MN )
            IF( NYOB .NE. L ) GOTO 640
            NUOB = MCN( MN + 1 )
C           OUVERTURE DE L'OBJET
            CALL LXNLOU( NTMN(NYOB), NUOB, NTOB, MNOB )
            CALL NMOBNU( KNM, NUOB, KNOM )
C           ECRITURE DU NOM DE L'OBJET AUX LIMITES
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(NOFILE,10102) NUOB, KNM, KNOM
            ELSE
               WRITE(NOFILE,11102) NUOB, KNM, KNOM
            ENDIF
 640     CONTINUE
 650  CONTINUE
C
C     ECRITURE DU NOMBRE D'EF
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(NOFILE,16000) NBEF,   KNOMOB
         WRITE(IMPRIM,16000) NBEF,   KNOMOB
         WRITE(NOFILE,16001) NBNOEU, KNOMOB
         WRITE(IMPRIM,16001) NBNOEU, KNOMOB
      ELSE
         WRITE(NOFILE,26000) NBEF,   KNOMOB
         WRITE(IMPRIM,26000) NBEF,   KNOMOB
         WRITE(NOFILE,26001) NBNOEU, KNOMOB
         WRITE(IMPRIM,26001) NBNOEU, KNOMOB
      ENDIF
16000 FORMAT( I10,' NOMBRE TOTAL d''EF      de l''OBJET ',A )
16001 FORMAT( I10,' NOMBRE TOTAL de NOEUDS de l''OBJET ',A )
26000 FORMAT( I10,' TOTAL NUMBER of FE    of the OBJECT ',A )
26001 FORMAT( I10,' TOTAL NUMBER of NODES of the OBJECT ',A )
C
C     FERMETURE DU FICHIER nopomodulef
      CLOSE( NOFILE )
C
C     DESTRUCTION DES TABLEAUX AUXILIAIRES
 9900 IF( MNELEM .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXTYEL, MNELEM )
      RETURN
C
C     PB A L'OUVERTURE DU FICHIER
 9999 NBLGRC(NRERR) = 1
      IF( LANGAG .EQ. 0 ) THEN
         KERR(1) = 'IMPOSSIBLE OUVERTURE DU FICHIER nopomodulef'
      ELSE
         KERR(1) = 'FILE nopomodulef CAN NOT BE OPENED'
      ENDIF
      CALL LEREUR
      GOTO 10
C
      END
