      SUBROUTINE NUFATRTE( NOSOTR, NOSOTE, NUFACTET )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE NUMERO LOCAL NUFACTET DE LA FACE DE SOMMETS
C -----    NOSOTR PARMI LES 4 SOMMETS NOSOTE D'UN TETRAEDRE

C ENTREE :
C --------
C NOSOTR : NO DES 3 SOMMETS DE LA FACE TRIANGULAIRE
C NOSOTE : NO DES 4 SOMMETS DU TETRAEDRE

C MODIFIE:
C --------
C NOSOTR : NO DES 3 SOMMETS DE LA FACE TRIANGULAIRE
C          EN SORTIE LES 3 NO DE SOMMETS SONT CROISSANTS

C SORTIE :
C --------
C NUFACTET: NUMERO DE 1 A 4 DE LA FACE NOSOTR DANS LE TETRAEDRE NOSOTE
C           FACE1: 1 2 3,  FACE2: 2,3,4,  FACE3: 3,4,1  FACE4: 4,1,2
C           =0 SI NON RETROUVEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2016
C2345X7..............................................................012
      INTEGER   NOSOTR(3), NOSOTE(4)
      INTEGER   NOSOTR2(3),
     %          NOSOFATE(3,4)
C               NUMERO LOCAL DES 3 SOMMETS DES 4 FACES DU TETRAEDRE
      DATA      NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /
C     => LA NORMALE A LA FACE EST ORIENTEE VERS L'EXTERIEUR DU TETRAEDRE

C     RENUMEROTATION CROISSANTE DE NOSOTR
      CALL TRI3NO( NOSOTR, NOSOTR )

      DO NUFACTET = 1, 4

C        3 SOMMETS DE LA FACE NUFACTET
         DO K=1,3
            NOSOTR2(K) = NOSOTE( NOSOFATE(K,NUFACTET) )
         ENDDO

C        RENUMEROTATION CROISSANTE DE NOSOTR2
         CALL TRI3NO( NOSOTR2, NOSOTR2 )

         IF( NOSOTR(1) .EQ. NOSOTR2(1) .AND.
     %       NOSOTR(2) .EQ. NOSOTR2(2) .AND.
     %       NOSOTR(3) .EQ. NOSOTR2(3) ) GOTO 9999

      ENDDO

C     FACE NON RETROUVEE
      NUFACTET = 0

 9999 RETURN
      END
