      SUBROUTINE NULETR( NOSOTR, MXFACO, LEFACO,  NFLEFA )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE NUMERO NFLEFA DANS LE TABLEAU LEFACO DU
C -----    TRIANGLE DE SOMMETS NOSOTR

C ENTREES :
C ---------
C NOSOTR : NUMEROS DES 3 SOMMETS DU TRIANGLE
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1 < SOMMET 2 < SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3

C          9: CHAINAGE DU HACHAGE DES FACES ISSUES DE LA FONCTION DE HACHAGE
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)

C          10: NUMERO DE LA PREMIERE FACE ISSUE DE LA FONCTION DE HACHAGE
C              LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOTR(1)+NOSOTR(2)+NOSOTR(3), MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. 
C              PASSAGE A LA SUIVANTE PAR NF = LEFACO( 9, NF )  ...

C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
CCCC       LEFACO(12,*) NO de FACE OpenCascade

C SORTIES :
C ---------
C NFLEFA  : >0 NUMERO LEFACO DE LA FACE NOSOTR SI ELLE EST RETROUVEE
C           =0 SI LA FACE N'EST PAS RETROUVEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE PARIS UPMC        Juin 1991
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2016
C23456...............................................................012
      INTEGER    LEFACO(1:11,0:MXFACO), NOSOTR(3)

C     TRI CROISSANT DES 3 NUMEROS DES SOMMETS DU TRIANGLE NOSOTR
      CALL TRI3NO( NOSOTR, NOSOTR )

C     LA FACE DE SOMMETS NOSOTR(1:3) EXISTE-T-ELLE DEJA DANS LEFACO?
C     HACHAGE DANS LEFACO AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
      LF = MOD( NOSOTR(1) + NOSOTR(2) + NOSOTR(3), MXFACO ) + 1

C     LE NO DE LA 1-ERE FACE DANS LEFACO ISSUE DE LA FORMULE DE HACHAGE
      NFLEFA = LEFACO( 10, LF )

 10   IF( NFLEFA .GT. 0 ) THEN

C        EST CE LA MEME FACE QUE NOSOTR?
         IF(       NOSOTR(1) .EQ. LEFACO(1,NFLEFA) ) THEN
            IF(    NOSOTR(2) .EQ. LEFACO(2,NFLEFA) ) THEN
               IF( NOSOTR(3) .EQ. LEFACO(3,NFLEFA) ) GOTO 9999
            ENDIF
         ENDIF

C        NON: LA FACE N'EST PAS RETROUVEE
C             PASSAGE A LA SUIVANTE DANS LE CHAINAGE DU HACHAGE
         NFLEFA = LEFACO( 9, NFLEFA )
         GOTO 10

      ENDIF

 9999 RETURN
      END
