      SUBROUTINE OPLOR3( NUOPER,  NTLXSU,
     %                   MCNSEF1, MCXYZS1, MCNSEF2, MCXYZS2,
     %                   NTNSEFF, MCNSEFF, NTXYZSF, MCXYZSF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DE L'INTERSECTION, DE LA DIFFERENCE OU DE L'UNION DE
C -----    DEUX MAILLAGES DE SURFACES FERMEES (D'UN VOLUME ou SOLIDE)
C          (TOUTE ARETE APPARTIENT A 2 et SEULEMENT 2 EF)
C ENTREES:
C --------
C NUOPER : NUMERO DE L'OPERATEUR LOGIQUE A TRAITER
C        ( 1: 'intersection' , 2: 'addition' , 3: 'soustraction' )
C NUSURF : NUMERO DE LA SURFACE DANS LE LEXIQUE DES SURFACES
C NTLXSU : NUMERO DU TABLEAU TMS DU LEXIQUE DE LA SURFACE FINALE
C
C NTSURF1: NUMERO       DU TMS-LEXIQUE   de la SURFACE1
C MCSURF1: ADRESSE MCN  DU TMS-LEXIQUE   de la SURFACE1
C NTNSEF1: NUMERO       DU TMS NSEF      de la SURFACE1
C MCNSEF1: ADRESSE MCN  DU TMS NSEF      de la SURFACE1
C NTXYZS1: NUMERO       DU TMS XYZSOMMET de la SURFACE1
C MCXYZS1: ADRESSE MCN  DU TMS XYZSOMMET de la SURFACE1
C
C NTSURF2: NUMERO       DU TMS-LEXIQUE   de la SURFACE2
C MCSURF2: ADRESSE MCN  DU TMS-LEXIQUE   de la SURFACE2
C NTNSEF2: NUMERO       DU TMS NSEF      de la SURFACE2
C MCNSEF2: ADRESSE MCN  DU TMS NSEF      de la SURFACE2
C NTXYZS2: NUMERO       DU TMS XYZSOMMET de la SURFACE2
C MCXYZS2: ADRESSE MCN  DU TMS XYZSOMMET de la SURFACE2
C
C SORTIES:
C --------
C NTNSEFF: NUMERO      DU TMS 'NSEF' DES NUMEROS DES FACES DE LA SURFACE
C MCNSEFF: ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES FACES DE LA SURFACE
C          CF ~td/d/a___nsef
C NTXYZSF: NUMERO      DU TMS 'XYZSOMMET' DE LA SURFACE
C MCXYZSF: ADRESSE MCN DU TMS 'XYZSOMMET' DE LA SURFACE
C          CF ~td/d/a___xyzsommet
C IERR   : =0 SI PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC& St Pierre du Perray SEPTEMBRE 2011
C2345X7..............................................................012
      INCLUDE "./incl/ntmnlt.inc"
      INCLUDE "./incl/a_surface__definition.inc"
      INCLUDE "./incl/a___xyzsommet.inc"
      INCLUDE "./incl/a___nsef.inc"
      INCLUDE "./incl/gsmenu.inc"
      INCLUDE "./incl/langue.inc"
C
      include"./incl/pp.inc"
      COMMON             MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE (MCN(1), RMCN(1), DMCN(1))
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      LOGICAL           TRATRI
      COMMON / DV2DCO / TRATRI
C
      INTEGER  NTNSEFF, MCNSEFF,  NTXYZSF, MCXYZSF
CCC      CHARACTER*24 NOMSUR
C
      IERR    = 0
C
C     TRACE DES SOUS-TRIANGLES EN CONSTRUCTION
ccc      TRATRI  = .FALSE.
      TRATRI  = .TRUE.
C
      NTNSEFF = 0
      MCNSEFF = 0
      NTXYZSF = 0
      MCXYZSF = 0
C
      MC1ARET = 0
      MCARET  = 0
      MCSSGI  = 0
      MCTRA   = 0
      MCSTAR  = 0
C
      MCXYZD1 = 0
      MCXYZD2 = 0
      MCPTA   = 0
      MCPSGI1 = 0
      MCPSGI2 = 0
      MCSGI   = 0
      MCCHSGI = 0
      MCCHSTA = 0
      MCPHSTA = 0
      MNARET1 = 0
      MNARET2 = 0
      MCQUA1  = 0
      MCQUA2  = 0
      MCQUAT  = 0
      MCQUAN  = 0
      MCQUAS  = 0
      MCDEFI = 0
C
C     DONNEES DES SURFACE 1 et SURFACE 2
C     Surface Fermee ou NON-Fermee?
      IF( MCN( MCNSEF1 + WUTFMA ) .NE. 1 .OR.
     %    MCN( MCNSEF2 + WUTFMA ) .NE. 1 ) THEN
         NBLGRC(NRERR) = 2
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'SURFACE 1 ou 2 NON FERMEE'
            KERR(2) = 'N''EST PAS CELLE d''UN SOLIDE'
         ELSE
            KERR(1) = 'SURFACE 1 or 2 is NOT a CLOSED SURFACE'
            KERR(2) = 'is NOT a CLOSED SURFACE of A SOLID'
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     NOMBRE D'EF DE LA SURFACE
      NBEFSU1 = MCN( MCNSEF1 + WBEFOB )
      NBEFSU2 = MCN( MCNSEF2 + WBEFOB )
C
C     variable NUTYMA 'Numero de type du maillage' entier
C     ( 0 : 'non structure' ,
C       1 : 'noeudsommet structure' , 2 : 'segment    structure' ,
C       3 : 'triangle    structure' , 4 : 'quadrangle structure' ,
C       5 : 'tetraedre   structure' , 6 : 'pentaedre  structure' ,
C       7 : 'hexaedre    structure' , 8 : '6-cube     structure' ) ;
      NUTYMA1 = MCN( MCNSEF1 + WUTYMA )
      NUTYMA2 = MCN( MCNSEF2 + WUTYMA )
C
C     SI LE MAILLAGE EST STRUCTURE
C     ALORS IL N'EST PAS LE MAILLAGE D'UNE SURFACE FERMEE
      IF( NUTYMA1 .GT. 0 .OR. NUTYMA2 .GT. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'AU MOINS UNE SURFACE STRUCTUREE => NON FERMEE'
         ELSE
            KERR(1) = 'At LEAST ONE STRUCTURED SURFACE => NOT CLOSED'
         ENDIF
         CALL LEREUR
         IERR = 2
         RETURN
      ENDIF
C
C     NOMBRE DE MOTS POUR UN REEL DOUBLE PRECISION
      MOREE2 = MOTVAR(6)
C
C     ADRESSE MCN DU TABLEAU NUSOEF1(4,NBEFSU1)
      MCNUSO1 = MCNSEF1 + WUSOEF
C     ADRESSE MCN DU TABLEAU NUSOEF2(4,NBEFSU2)
      MCNUSO2 = MCNSEF2 + WUSOEF
C
C     EXISTE-T-IL DES QUADRANGLES DANS SURFACE 1
      CALL QUA2TRI( NBEFSU1, MCNUSO1, NBQT1, MCQUA1 )
      IF( NBQT1 .GT. 0 ) THEN
C        ADRESSE MCN DU TABLEAU NUSOEF1(4,NBEFSU1)
         MCNUSO1 = MCQUA1
C        NOMBRE DE TRIANGLES APRES DECOUPAGE EN 2 DES QUADRANGLES
         NBEFSU1 = NBQT1
      ENDIF
C
C     EXISTE-T-IL DES QUADRANGLES DANS SURFACE 2
      CALL QUA2TRI( NBEFSU2, MCNUSO2, NBQT2, MCQUA2 )
      IF( NBQT2 .GT. 0 ) THEN
C        ADRESSE MCN DU TABLEAU NUSOEF2(4,NBEFSU2)
         MCNUSO2 = MCQUA2
C        NOMBRE DE TRIANGLES APRES DECOUPAGE EN 2 DES QUADRANGLES
         NBEFSU2 = NBQT2
      ENDIF
C
C     ICI SURFACE 1 ET SURFACE 2 SONT TRIANGULEES
C     -------------------------------------------
C
C     NOMBRE DE SOMMETS DU MAILLAGE
      NBSOM1 = MCN( MCXYZS1 + WNBSOM )
      NBSOM2 = MCN( MCXYZS2 + WNBSOM )
C
C     ADRESSE MCN DU TABLEAU XYZSOM(3,NBSOM) TRANSFORME EN DOUBLE PRECISION
      MCXYZ1 = MCXYZS1 + WYZSOM
      CALL TNMCDC( 'REEL2', 3*NBSOM1, MCXYZD1 )
      CALL REELREEL2( 3*NBSOM1, RMCN(MCXYZ1), RMCN(MCXYZD1) )
ccc      print *
ccc      MN = ( MCXYZD1 - 1 ) / MOREE2
ccc      DO N=1,NBSOM1
ccc         print *,'XYZSF1 ',N,' =',(DMCN(MN+3*(N-1)+K),K=1,3)
ccc      ENDDO
C
      MCXYZ2 = MCXYZS2 + WYZSOM
      CALL TNMCDC( 'REEL2', 3*NBSOM2, MCXYZD2 )
      CALL REELREEL2( 3*NBSOM2, RMCN(MCXYZ2), RMCN(MCXYZD2) )
ccc      print *
ccc      MN = ( MCXYZD2 - 1 ) / MOREE2
ccc      DO N=1,NBSOM2
ccc         print *,'XYZSF2 ',N,' =',(DMCN(MN+3*(N-1)+K),K=1,3)
ccc      ENDDO
C
C     TABLEAU DES XYZPTA DES NOUVEAUX POINTS AJOUTES
      MXPTA = 2 * (NBSOM1 + NBSOM2)
      IF( MXPTA .LT. 1024 ) MXPTA=1024
      CALL TNMCDC( 'REEL2', 3*MXPTA, MCPTA )
C
C     TABLEAU PSGISF1 POINTEUR SUR 1-ER SEGMENT INTERSECTION DE CHAQUE
C     TRIANGLE DE LA SURFACE 1
      MXPSGI1 = NBEFSU1
      CALL TNMCDC( 'ENTIER', MXPSGI1, MCPSGI1 )
C
C     TABLEAU PSGISF2 POINTEUR SUR 1-ER SEGMENT INTERSECTION DE CHAQUE
C     TRIANGLE DE LA SURFACE 2
      MXPSGI2 = NBEFSU2
      CALL TNMCDC( 'ENTIER', MXPSGI2, MCPSGI2 )
C
C     TABLEAU NSTSGI(2,*) NUMERO DES 2 SOMMETS DES SGI
C     SEGMENTS D'INTERSECTION
C     1: NUMERO DANS XYZPTA DU SOMMET 1 DU SGI
C     2: NUMERO DANS XYZPTA DU SOMMET 2 DU SGI
C     3: NUMERO DU TRIANGLE DANS NUSTS1
C     4: NUMERO DU TRIANGLE DANS NUSTS2
      MXSGI = 2 * MXPTA
      CALL TNMCDC( 'ENTIER', 4*MXSGI, MCSGI )
      CALL AZEROI( 4*MXSGI, MCN(MCSGI) )
C
C     TABLEAU LCHSGI(2,*) NUMERO DU SGI et CHAINAGE SUR LE SUIVANT
      MXCHSGI = 2*(NBEFSU1+NBEFSU2)
      CALL TNMCDC( 'ENTIER', 2*MXCHSGI, MCCHSGI )
C
C     CALCUL DES ARETES D'INTERSECTION ENTRE LES TRIANGLES DE SURFACE1
C     ET LES TRIANGLES DE SURFACE2 (un SIMPLE SOMMET est OUBLIE CAR INUTILE)
C     ----------------------------------------------------------------------
      CALL TRTR3SGI( NBSOM1,  MCN(MCXYZD1), NBEFSU1, MCN(MCNUSO1),
     %               MCN(MCPSGI1),
     %               NBSOM2,  MCN(MCXYZD2), NBEFSU2, MCN(MCNUSO2),
     %               MCN(MCPSGI2),
     %               MXSGI,   NBSGI,   MCN(MCSGI),
     %               MXCHSGI, NBCHSGI, MCN(MCCHSGI),
     %               MXPTA,   NBPTA,   MCN(MCPTA),  IERR )
      IF( IERR  .NE. 0 ) GOTO 9000
C
      IF( NBSGI .LE. 0 ) THEN
C        SURFACE1 intersection SURFACE2 = ENSEMBLE VIDE
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'SURFACE1 SURFACE2 SANS INTERSECTION'
         ELSE
            KERR(1) = 'SURFACE1 SURFACE2 WITHOUT INTERSECTION'
         ENDIF
         IF( NUOPER .EQ. 2 ) THEN
C           SURFACE1 + SURFACE2 = SURFACE1 ou SURFACE2
            NBLGRC(NRERR) = 2
            IF( LANGAG .EQ. 0 ) THEN
               KERR(2)='CHOISIR L''OPTION 51 POUR AVOIR SURF1 +- SURF2'
            ELSE
               KERR(2)='CHOOSE the OPTION 51 to HAVE SURF1 +- SURF2'
            ENDIF
         ENDIF
         IF( NUOPER .EQ. 3 ) THEN
C           SURFACE1 - SURFACE2 = SURFACE1 union SURFACE2
            NBLGRC(NRERR) = 2
            IF( LANGAG .EQ. 0 ) THEN
             KERR(2)='CHOISIR L''OPTION 51 POUR AVOIR SURFACE1-SURFACE2'
            ELSE
               KERR(2)='CHOOSE the OPTION 51 to HAVE SURFACE1-SURFACE2'
            ENDIF
         ENDIF
         CALL LEREUR
         IERR = 3
         GOTO 9000
      ENDIF
C
C     NOMBRE DE POINTS SOMMETS DES SGI
      NBPTSG = NBPTA
C
C     SOUS-TRIANGULATION DES TRIANGLES INTERSECTES DE LA SURFACE 1
C     et DE LA SURFACE 2 SELON L'OPERATEUR NUOPER
C     ( 1: 'intersection' , 2: 'addition' , 3: 'soustraction' )
C     ------------------------------------------------------------
C     SIGNE DU DETERMINANT POUR LA SURFACE 1 SELON NUOPER POUR SAVOIR
C     QUEL EST LE CF A TRIANGULER PARMI LES 2 CF POSSIBLES
      IF( NUOPER .EQ. 1 ) THEN
C        INTERSECTION SF1 et SF2
C        SOUS-TRIANGLE DE SF1 AU DESSOUS DU PLAN DU TRIANGLE DE SF2
         LSIGNS1 = -1
      ELSE
C        ADDITION SF1 + SF2 ou  SOUSTRACTION SF1 - SF2
C        SOUS-TRIANGLE DE SF1 AU DESSUS DU PLAN DU TRIANGLE DE SF2
         LSIGNS1 =  1
      ENDIF
C
C     SIGNE DU DETERMINANT POUR LA SURFACE 2 SELON NUOPER POUR SAVOIR
C     QUEL EST LE CF A TRIANGULER PARMI LES 2 CF POSSIBLES
      IF( NUOPER .EQ. 2 ) THEN
C        ADDITION SF1 + SF2
C        SOUS-TRIANGLE DE SF2 AU DESSUS DU PLAN DU TRIANGLE DE SF1
         LSIGNS2 =  1
      ELSE
C        INTERSECTION SF1 et SF2  ou  SOUSTRACTION SF1 - SF2
C        SOUS-TRIANGLE DE SF2 AU DESSOUS DU PLAN DU TRIANGLE DE SF1
         LSIGNS2 = -1
      ENDIF
C
C     LES TABLEAUX AUXILIAIRES DE LA SOUS-TRIANGULATION
      MX1ARET = MXSGI
      CALL TNMCDC( 'ENTIER', MX1ARET, MC1ARET )
C
      MXARET = MXSGI * 3
      CALL TNMCDC( 'ENTIER', 3*MXARET, MCARET )
C
      CALL TNMCDC( 'ENTIER', MXPTA, MCSSGI )
C
      MXTRA = MAX( 4*MXSGI, 2*(NBEFSU1+NBEFSU2) )
      CALL TNMCDC( 'ENTIER', 3*MXTRA, MCTRA )
C
      MXSTAR = MXTRA
      CALL TNMCDC( 'ENTIER', 2*MXSTAR, MCSTAR )
C
      CALL TRTR3RET( LSIGNS1, LSIGNS2,
     %               NBSOM1,  MCN(MCXYZD1), NBEFSU1, MCN(MCNUSO1),
     %               MCN(MCPSGI1),
     %               NBSOM2,  MCN(MCXYZD2), NBEFSU2, MCN(MCNUSO2),
     %               MCN(MCPSGI2),
     %               MXSGI,   MCN(MCSGI),   MXCHSGI, MCN(MCCHSGI),
     %               MXARET,  NBARET,MCN(MCARET), MX1ARET,MCN(MC1ARET),
     %               MXPTA,   NBPTA,   MCN(MCPTA), MCN(MCSSGI),
     %               MXTRA,   NBTRA,   MCN(MCTRA), IERR )
      IF( IERR .NE. 0 ) GOTO 9000
C     NOMBRE DE SOMMETS DES SOUS-TRIANGLES AVEC DES ARETES SGI
      NBPTA2 = NBPTA
C     NOMBRE DE SOUS-TRIANGLES AVEC DES ARETES SGI
      NBTRSG = NBTRA
C
C     CONSTRUCTION DU HACHAGE DES ARETES DE LA SURFACE 1
C     PAR ARETE STOCKAGE EN PLUS DE EF1 EF2 POINTEUR SUR POINTS DE L'ARETE
      MXMOAR = 3
      CALL GEARSU( 4, NBEFSU1, MCN(MCNUSO1), MXMOAR,
     %                L1ARET1, L2ARET1, MNARET1, IERR )
C
C     CONSTRUCTION DU HACHAGE DES ARETES DE LA SURFACE 2
      CALL GEARSU( 4, NBEFSU2, MCN(MCNUSO2), MXMOAR,
     %                L1ARET2, L2ARET2, MNARET2, IERR )
C
      MXCHSTA = MXSGI
      CALL TNMCDC( 'ENTIER', 3*MXCHSTA, MCCHSTA )
      CALL TNMCDC( 'ENTIER', MAX(NBEFSU1,NBEFSU2), MCPHSTA )
C
C     TRIANGLES DE LA SURFACE1 DE (SURFACE1 OPER SURFACE2)
C     ----------------------------------------------------
      CALL TRTR3S1P( NBSOM1,  MCN(MCXYZD1), NBEFSU1, MCN(MCNUSO1),
     %               MCN(MCPSGI1), L1ARET1, L2ARET1, MCN(MNARET1),
     %               MXCHSTA, MCN(MCCHSTA), MCN(MCPHSTA),
     %               MXSGI,   MCN(MCSGI),   MXCHSGI, MCN(MCCHSGI),
     %               MXARET,  NBARET,MCN(MCARET), MX1ARET,MCN(MC1ARET),
     %               MXSTAR,  MCN(MCSTAR),
     %               MXPTA,   NBPTA, MCN(MCPTA),
     %               MXTRA,   NBTRA, MCN(MCTRA),
     %               IERR )
C
C     TRIANGLES DE LA SURFACE2 DE (SURFACE1 OPER SURFACE2)
C     ----------------------------------------------------
      CALL TRTR3S1P( NBSOM2,  MCN(MCXYZD2), NBEFSU2, MCN(MCNUSO2),
     %               MCN(MCPSGI2), L1ARET2, L2ARET2, MCN(MNARET2),
     %               MXCHSTA, MCN(MCCHSTA), MCN(MCPHSTA),
     %               MXSGI,   MCN(MCSGI),   MXCHSGI, MCN(MCCHSGI),
     %               MXARET,  NBARET,MCN(MCARET), MX1ARET,MCN(MC1ARET),
     %               MXSTAR,  MCN(MCSTAR),
     %               MXPTA,   NBPTA, MCN(MCPTA),
     %               MXTRA,   NBTRA, MCN(MCTRA),
     %               IERR )
C
C     SUPPRESSION DES COUPLES DE TRIANGLES TRES ALLONGES ADJACENTS PAR
C     UNE COURTE ARETE
C     ----------------------------------------------------------------
      CALL TNMCDC( 'REEL2',  MXTRA, MCQUAT )
      CALL TNMCDC( 'ENTIER', MXTRA, MCQUAN )
      CALL TNMCDC( 'ENTIER', NBPTA, MCQUAS )
      CALL TRTR3S2T( NBPTSG, NBPTA, MCN(MCPTA),
     %               NBTRSG, NBTRA, MCN(MCTRA),
     %               MXSGI,  MCN(MCSGI), MXCHSGI, MCN(MCCHSGI),
     %               MCN(MCQUAT), MCN(MCQUAN), MCN(MCQUAS),
     %               NODEST, NODETR )
      WRITE(IMPRIM,*) 'APRES SUPPRESSIONS MAUVAIS TRIANGLES NODEST=',
     %                 NODEST,' NODETR=',NODETR
      IF( IERR .NE. 0 ) GOTO 9000
      NBPTA = NODEST
      NBTRA = NODETR
C
C     CONSTRUCTION DES TMS XYZSOMMET ET NSEF DE SURFACE1 OPER SURFACE2
C     A PARTIR DES SOUS-TRIANGLES DE NUSTRA et XYZPTA
C     ----------------------------------------------------------------
      IF( NBPTA .GT. 0 .AND. NBTRA .GT. 0 ) THEN
cccC
cccC        LE NOM DE LA SURFACE RETROUVEE
ccc         CALL NMOBNU( 'SURFACE', NUSURF, NOMSUF )
cccC        MODIFICATION DU NOM
ccc         N = NUDCNB( NOMSUR )
ccc         N = MIN(N,22)
ccc         NOMSUR = NOMSUR(1:N) // '_0'
cccC        CONSTRUCTION DU LEXIQUE DU SURFACE
ccc         CALL LXLXDC( NTSURF, NOMSUR, 24, 8 )
ccc         CALL LXLXOU( NTSURF, NOMSUR, NTLXSU0, MNLXSU0 )
cccC        NUMERO DU SURFACE DANS LE LX DES SURFACES
ccc         CALL NUOBNM( 'SURFACE', NOMSUR, NUSURF0 )
ccc         CALL CRTRIA( NTLXSU0, MXPTA,  NBPTA,  MCN(MCPTA),
ccc     %                         MXTRA,  NBTRA,  MCN(MCTRA),
ccc     %                NTNSEF0, MCNSEF0, NTXYZS0, MCXYZS0, IERR )
C
         CALL CRTRIA( NTLXSU,  MXPTA,   NBPTA,   MCN(MCPTA),
     %                         MXTRA,   NBTRA,   MCN(MCTRA),
     %                NTNSEFF, MCNSEFF, NTXYZSF, MCXYZSF, IERR )
      ELSE
         IERR = 23
         GOTO 9000
      ENDIF
C
cccC     AMELIORATION DE LA QUALITE DES TRIANGLES
cccC     ----------------------------------------
ccc      CALL TNMCDC( 'ENTIER', WNGL2P+1, MCDEFI )
cccC     variable NUSUQU 'nom de la triangulation a ameliorer' ^~>SURFACE
ccc      MCN( MCDEFI + WUSUQU ) = NUSURF0
cccC     variable QUALMN 'qualite au dessous de laquelle ameliorer' reel
ccc      RMCN( MCDEFI + WUALMN ) = 0.1
cccC     variable ANGL2P 'degres du petit angle de coplanearite' reel
ccc      RMCN( MCDEFI + WNGL2P ) = 0.
ccc      CALL SUEX30( NUSURF,  NTLXSU,  MCN(MCDEFI), RMCN(MCDEFI),
ccc     %             NTNSEFF, MCNSEFF, NTXYZSF, MCXYZSF, IERR )
ccc      CALL TNMCDS( 'ENTIER', WNGL2P+1, MCDEFI )
cccC     DESTRUCTION DE LA SURFACE INTERMEDIAIRE
ccc      CALL LXLXDS ( NTSURF, NOMSUR )
C
C     MISE A JOUR DES COORDONNEES EXTREMES DU MAILLAGE
      IF( MCXYZSF .GT. 0 ) CALL MAJEXT( MCN(MCXYZSF) )
C
C     NETTOYAGE DES TABLEAUX DEVENUS INUTILES
C     ---------------------------------------
 9000 IF( MCQUAS .GT.0 ) CALL TNMCDS( 'ENTIER', NBPTA, MCQUAS )
      IF( MCQUAN .GT.0 ) CALL TNMCDS( 'ENTIER', MXTRA, MCQUAN )
      IF( MCQUAT .GT.0 ) CALL TNMCDS( 'REEL2',  MXTRA, MCQUAT )
      IF( MCPHSTA.GT.0 ) CALL TNMCDS( 'ENTIER', MAX(NBEFSU1,NBEFSU2),
     %                                 MCPHSTA )
      IF( MCCHSTA.GT.0) CALL TNMCDS( 'ENTIER', 3*MXCHSTA, MCCHSTA )
      IF( MNARET2.GT.0) CALL TNMCDS( 'ENTIER', L1ARET2*L2ARET2, MNARET2)
      IF( MNARET1.GT.0) CALL TNMCDS( 'ENTIER', L1ARET1*L2ARET1, MNARET1)
      IF( MC1ARET .GT. 0 ) CALL TNMCDS( 'ENTIER', MX1ARET,  MC1ARET )
      IF( MCARET  .GT. 0 ) CALL TNMCDS( 'ENTIER', 3*MXARET, MCARET  )
      IF( MCSSGI  .GT. 0 ) CALL TNMCDS( 'ENTIER', MXPTA,    MCSSGI  )
      IF( MCTRA   .GT. 0 ) CALL TNMCDS( 'ENTIER', 3*MXTRA,  MCTRA   )
      IF( MCSTAR  .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXSTAR, MCSTAR  )
C
      IF( MCXYZD1 .GT. 0 ) CALL TNMCDS( 'REEL2', 3*NBSOM1,  MCXYZD1 )
      IF( MCXYZD2 .GT. 0 ) CALL TNMCDS( 'REEL2', 3*NBSOM2,  MCXYZD2 )
      IF( MCPTA   .GT. 0 ) CALL TNMCDS( 'REEL2', 3*MXPTA,   MCPTA   )
      IF( MCPSGI1 .GT. 0 ) CALL TNMCDS( 'ENTIER', MXPSGI1,  MCPSGI1 )
      IF( MCPSGI2 .GT. 0 ) CALL TNMCDS( 'ENTIER', MXPSGI2,  MCPSGI2 )
      IF( MCSGI   .GT. 0 ) CALL TNMCDS( 'ENTIER', 4*MXSGI,  MCSGI   )
      IF( MCCHSGI .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXCHSGI,MCCHSGI )
C
C     PROTECTION POUR LES TRIANGULATIONS A VENIR
      TRATRI = .FALSE.
C
      RETURN
      END
