      SUBROUTINE OT4TET( PTXYZD, MXTETR,  N1TEVI, NOTETR,
     %                   N1TETS, NUDTETR, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    GENERATION DES 4 PREMIERS TETRAEDRES DANS L'OCTAEDRE A PARTIR
C -----    DE SES 6 SOMMETS et INITIALISATION DES TETRAEDRES VIDES

C ENTREE :
C --------
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C MXTETR : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES

C SORTIES:
C --------
C N1TEVI : NUMERO DU PREMIER TETRAEDRE VIDE DANS LE CHAINAGE NOTETR(5,*)
C NOTETR : LISTE DES TETRAEDRES OCCUPES POINTEE PAR N1TETS
C                               VIDES   POINTEE PAR N1TEVI
C
C          SOMMET1   < SOMMET2    SOMMET3     SOMMET4
C          ORDRE CLASSIQUE 1 2 3 DIRECT EN BAS ET 4 EN HAUT
C          LE SOMMET 1 EST LE PLUS PETIT
C          LE VOLUME EST POSITIF => UN ORDRE
C
C          TETRAEDRE1  TETREDRE2  TETRAEDRE3  TETREDRE4  VOISINS PAR LA
C          FACE1       FACE2D      FACE3       FACE4
C
C N1TETS : NUMERO D'UN TETRAEDRE AYANT CE SOMMET
C NUDTETR: NUMERO NOTETR DU DERNIER TETRAEDRE CREE
C IERR   : 0 SI PAS D'ERREUR
C          1 TOUS LES POINTS SONT COPLANAIRES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1992
C2345X7..............................................................012
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      DOUBLE PRECISION  PTXYZD(1:4,1:*)
      INTEGER           NOTETR(8,*),
     %                  N1TETS(*)
      DOUBLE PRECISION  CENTRE(4), VOLUTE

C     TETRAEDRE 1 : 1 2 4 3
      NOTETR(1,1) = 1
      NOTETR(2,1) = 2
      NOTETR(3,1) = 4
      NOTETR(4,1) = 3
      NOTETR(5,1) = 2
      NOTETR(6,1) = 3
      NOTETR(7,1) = 0
      NOTETR(8,1) = 0
C     CALCUL DU CENTRE DE LA BOULE CIRCONSCRITE ET DU CARRE DU RAYON
      CALL CERABOCI( PTXYZD(1,1),PTXYZD(1,2),PTXYZD(1,4),PTXYZD(1,3),
     %               CENTRE, VOLUTE, IERR )
C     IERR   : =0 SI CALCUL CORRECT SANS PROBLEME RENCONTRE
C              =1 SI TETRAEDRE PLAT (4 SOMMETS DANS UN PLAN)
C              =2 SI TETRAEDRE MAL ORIENTE DE VOLUME STRICTEMENT NEGATIF
C              =3 SI RAYON**2 DE LA BOULE CIRCONSCRITE PAR LA FORMULE est <0
C              =4 SI TROP GRANDE DIFFERENCE SUR LE CALCUL DU RAYON AUX 4 SOMMETS
C                    SOUVENT DU A UN VOLUME TROP FAIBLE
      IF( IERR .NE. 0 ) RETURN

C     TETRAEDRE 2 : 1 2 5 4
      NOTETR(1,2) = 1
      NOTETR(2,2) = 2
      NOTETR(3,2) = 5
      NOTETR(4,2) = 4
      NOTETR(5,2) = 0
      NOTETR(6,2) = 4
      NOTETR(7,2) = 0
      NOTETR(8,2) = 1
C     CALCUL DU CENTRE DE LA BOULE CIRCONSCRITE ET DU CARRE DU RAYON
      CALL CERABOCI( PTXYZD(1,1),PTXYZD(1,2),PTXYZD(1,5),PTXYZD(1,4),
     %               CENTRE, VOLUTE, IERR )

C     TETRAEDRE 3 : 2 3 6 4
      NOTETR(1,3) = 2
      NOTETR(2,3) = 3
      NOTETR(3,3) = 6
      NOTETR(4,3) = 4
      NOTETR(5,3) = 0
      NOTETR(6,3) = 0
      NOTETR(7,3) = 4
      NOTETR(8,3) = 1
C     CALCUL DU CENTRE DE LA BOULE CIRCONSCRITE ET DU CARRE DU RAYON
      CALL CERABOCI( PTXYZD(1,2),PTXYZD(1,3),PTXYZD(1,6),PTXYZD(1,4),
     %               CENTRE, VOLUTE, IERR )

C     TETRAEDRE 4 : 2 4 6 5
      NOTETR(1,4) = 2
      NOTETR(2,4) = 4
      NOTETR(3,4) = 6
      NOTETR(4,4) = 5
      NOTETR(5,4) = 3
      NOTETR(6,4) = 0
      NOTETR(7,4) = 0
      NOTETR(8,4) = 2
C     CALCUL DU CENTRE DE LA BOULE CIRCONSCRITE ET DU CARRE DU RAYON
      CALL CERABOCI( PTXYZD(1,2),PTXYZD(1,4),PTXYZD(1,6),PTXYZD(1,5),
     %               CENTRE, VOLUTE, IERR )

C     NUMERO NOTETR DU DERNIER TETRAEDRE CREE
      NUDTETR = 4

C     DEBUT DES CHAINAGES DES TETRAEDRES OCCUPES ET VIDES
      N1TEVI = 5

C     CHAINAGE DES TETRAEDRES VIDES SUIVANTS
      DO 10 I=N1TEVI , MXTETR
C        LE NUMERO DU PREMIER SOMMET
         NOTETR(1,I) = 0
C        LE TETRAEDRE SUIVANT
         NOTETR(5,I) = I + 1
 10   CONTINUE
C     LA FIN DU CHAINAGE DES SUIVANTS VIDES
      NOTETR(5,MXTETR) = 0

C     UN NUMERO DE TETRAEDRE POUR CHACUN DES 6 SOMMETS DE L'OCTAEDRE
      N1TETS(1) = 1
      N1TETS(2) = 1
      N1TETS(3) = 1
      N1TETS(4) = 1
      N1TETS(5) = 2
      N1TETS(6) = 3

      RETURN
      END
