      SUBROUTINE OTAJPI( HEXA,   NBPTIN, NOPTIN, DISTSO ,
     %                   NBSOMM, MXSOMM, PTXYZD, NPSOFR,
     %                   MXARBO, LARBRO, MXARBT, LARBRT, NUOTPT,
     %                   LAVIDE, MXARET, LARETE,
     %                   IERR  )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUTER LES POINTS INTERNES DANS LE TABLEAU PTXYZD
C -----    METTRE A JOUR NPSOFR COMME NUMERO DE POINT INTERNE
C          1 000 000 + NUMERO DU POINT INTERNE DES POINTS AJOUTES

C ENTREES:
C --------
C HEXA   : MIN ET MAX DES 3 COORDONNEES D'UN HEXAEDRE ENGLOBANT
C          LES POINTS DE L'OBJET A MAILLER
C NBPTIN : NOMBRE DE POINTS INTERNES A AJOUTER
C NOPTIN : NUMEROS DES POINTS INTERNES
C DISTSO : DISTANCE SOUHAITEE AUTOUR DES POINTS INTERNES
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS UTILISABLES DANS PTXYZD
C MXARBO : NOMBRE MAXIMAL D'OCTAEDRES DANS LARBRO
C MXARBT : NOMBRE MAXIMAL DE TETRAEDRES DANS LARBRT
C MXARET : NOMBRE MAXIMAL D'ARETES DES OT

C ENTREES ET SORTIES:
C -------------------
C NBSOMM : NOMBRE ACTUEL DE POINTS DECLARES DANS PTXYZD
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C NPSOFR : 1 000 000  + NUMERO DU POINT INTERNE DES POINTS AJOUTES
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(0,0) : NO DU 1-ER OCTAEDRE VIDE DANS LARBRO
C      LARBRO(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRO (ICI -1:20)
C      LARBRO(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRO
C                    (ICI = MXARBO)

C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )

C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT

C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 0 A 4 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)

C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT

C NUOTPT : NUMERO D'OT (>0 SI LARBRO, <0 SI LARBRT) DE CHAQUE POINT PTXYZD

C LAVIDE : PREMIERE ADRESSE LARETE A EXPLORER POUR TROUVER UNE ARETE VIDE
C LARETE : TABLEAU DE HACHAGE DES ARETES DES OT
C          LARETE(1,J) = SOMMET 1 DANS PTXYZD
C          LARETE(2,J) = SOMMET 2 DANS PTXYZD
C          LARETE(3,J) = NUMERO DANS LARETE DE L'ARETE SUIVANTE
C          LARETE(4,J) = MILIEU DE L'ARETE DANS PTXYZD
C          HACHAGE(NS1,NS2) = (NS1 + NS2) MODULO MXARET + 1

C SORTIES:
C --------
C IERR   : 0 SI PAS D'ERREUR
C          1 UN POINT INCONNU OU INCORRECT
C          5 SI TABLEAU PTXYZD SATURE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1992
C2345X7..............................................................012
      include"./incl/langue.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/gsmenu.inc"
      include"./incl/a___xyzsommet.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))

      REAL              HEXA(6,2)
      INTEGER           NOPTIN(1:NBPTIN),
     &                  LARBRO(-1:20,0:MXARBO),
     &                  LARBRT(-1:9 ,0:MXARBT),
     &                  NUOTPT(1:MXSOMM),
     &                  NPSOFR(1:MXSOMM),
     &                  LARETE(1:4 ,1:MXARET)
      REAL              DISTSO(1:NBPTIN)
      DOUBLE PRECISION  PTXYZD(4,MXSOMM)

      IERR = 0
      IF( NBPTIN .LE. 0 ) GOTO 9999

C     DECLARATION DU TABLEAU OTFL
      MNOTFL = 0
      MXOTFL = 128
      CALL TNMCDC( 'ENTIER', MXOTFL, MNOTFL )
C
      DO 90 I=1,NBPTIN

C        LE NUMERO DU I-EME POINT IMPOSE
         NP = NOPTIN(I)

C        LE SOMMET NP EXISTE-T-IL?
         CALL LXNLOU( NTPOIN , NP , NTPO , MNPO )
         IF( NTPO .LE. 0 ) THEN
C           NON
            NBLGRC(NRERR) = 1
            WRITE(KERR(MXLGER)(1:10),'(I10)') NP
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'otajpi: POINT INCONNU ' // KERR(MXLGER)(1:10)
            ELSE
               KERR(1) = 'otajpi: UNKNOWN POINT ' // KERR(MXLGER)(1:10)
            ENDIF
            CALL LEREUR
            IERR = 1
         ELSE
C           OUI
            CALL LXTSOU( NTPO , 'XYZSOMMET' , NTSO , MNSO )
            MNSO = MNSO + WYZSOM
C           RECHERCHE DU PLUS PROCHE POINT DE NP
            PTXYZD(1,MXSOMM) = RMCN(MNSO)
            PTXYZD(2,MXSOMM) = RMCN(MNSO+1)
            PTXYZD(3,MXSOMM) = RMCN(MNSO+2)

C           RETROUVER LE PLUS PROCHE POINT NS DANS PTXYZD
C          (SOMMET OU NON D'UN OT) DU POINT PTXYZD(1,MXSOMM)
C           ET CHERCHER A L'IDENTIFIER SELON EPSXYZ OU EPZERO
            CALL OTPLPRPT( PTXYZD(1,MXSOMM), PTXYZD,
     %                     LARBRO, LARBRT, MXOTFL, MNOTFL,
     %                     NS,     DISMIN )

            IF( NS .GT. 0 .AND. DISMIN .EQ. 0 ) GOTO 80

C           LE POINT NP NON IDENTIFIE DEVIENT LE POINT NBSOMM
            IF( NBSOMM .GE. MXSOMM ) THEN
               NBLGRC(NRERR) = 1
               IF( LANGAG .EQ. 0 ) THEN
                  KERR(1) = 'SP otajpi: TABLEAU PTXYZD SATURE'
               ELSE
                  KERR(1) = 'SP otajpi: ARRAY PTXYZD SATURATED'
               ENDIF
               CALL LEREUR
               IERR = 2
               RETURN
            ENDIF

C           STOCKAGE DU NUMERO DU POINT INTERNE DANS LE LEXIQUE DES POINTS
            NBSOMM = NBSOMM + 1
            PTXYZD(1,NBSOMM) = DBLE( RMCN( MNSO     ) )
            PTXYZD(2,NBSOMM) = DBLE( RMCN( MNSO + 1 ) )
            PTXYZD(3,NBSOMM) = DBLE( RMCN( MNSO + 2 ) )
            NS = NBSOMM
C           STOCKAGE DU POINT DANS SON OT
            CALL OTRGPT( HEXA,   NBSOMM, MXSOMM, PTXYZD,
     &                   MXARBO, LARBRO, MXARBT, LARBRT, NUOTPT,
     &                   LAVIDE, MXARET, LARETE,
     &                   NUOTFE, IERR  )
            IF( IERR .NE. 0 ) GOTO 9990

C           LA DISTANCE SOUHAITEE DES DISTANCES AUX VOISINS DE NBSOMM
 80         PTXYZD(4,NS) = MAX( DBLE(DISTSO(I)) , PTXYZD(4,NS) )

C           LE NUMERO DE POINT DANS LE LEXIQUE DES POINTS
            NPSOFR( NS ) = 1 000 000 + NP
         ENDIF
 90   CONTINUE

C     DESTRUCTION DU TABLEAU OTFL
 9990 CALL TNMCDS( 'ENTIER', MXOTFL, MNOTFL )

      PRINT*,'otajpi:',NBPTIN,' POINTS INTERNES A TETRAEDRISER'

 9999 RETURN
      END
