      SUBROUTINE OTPLPRPT( PT,     PTXYZD, LARBRO, LARBRT,
     %                     MXOTFL, MNOTFL, NPMIN,  DISMI2 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LE PLUS PROCHE POINT NPMIN DANS PTXYZD
C -----   (SOMMET OU NON D'UN OT) DU POINT DE COORDONNEES PT ET
C          CHERCHER A L'IDENTIFIER SELON EPSXYZ OU EPZERO

C ENTREES:
C --------
C PT     : X Y Z DU POINT
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT

C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 0 A 4 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C
C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT

C MODIFIES:
C ---------
C MXOTFL : NOMBRE D'ENTIERS DU TABLEAU OTFL
C MNOTFL : ADRESSE MCN DU TABLEAU OTFL
C          LE TABLEAU OTFL A DU ETRE DECLARE AU PREALABLE

C SORTIES:
C --------
C NPMIN  : NUMERO PTXYZD DU POINT (NON SOMMET D'OT) LE PLUS PROCHE
C          =0 S'IL N'EN EXISTE PAS
C DISMI2 : CARRE DE LA DISTANCE DE NPMIN AU POINT PT SI NPMIN>0
C          =0 SI PT A ETE IDENTIFIE AU POINT NPMIN>0 DE PTXYZD
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1992
C2345X7..............................................................012
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      COMMON / EPSSSS / EPZERO, EPSXYZ
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      DOUBLE PRECISION  PT(4), PTXYZD(4,*)
      INTEGER           LARBRO(-1:20,0:*),
     &                  LARBRT(-1:9,0:*)
      INTEGER           NUOTVO(1:16)

C     INITIALISATION DE LA DISTANCE MINIMALE
      DISMI2 = 1E28
      NPMIN  = 0

C     L'OT FEUILLE NUOTFE CONTENANT LE POINT PT A PARTIR DE LA RACINE
      NUOTRA = 1
      CALL NOTFPT( PT, PTXYZD, NUOTRA, LARBRO, LARBRT, NUOTFE )
      IF( NUOTFE .EQ. 0 ) THEN
         PRINT*,'otplprpt: PROBLEME: le POINT',(PT(K),K=1,3),
     %          ' N''EST PAS DANS L''OT RACINE',NUOTRA
         GOTO 9999
      ENDIF

C     RECHERCHE DU SOMMET OU POINT LE PLUS PROCHE DANS L'OT NUOTFE
C     ------------------------------------------------------------
      CALL XYZDOT( PT,    PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             NPMIN, DISMI2 )
C     NPMIN  : NUMERO PTXYZD DU POINT (SOMMET OU NON DE L'OT) LE PLUS PROCHE
C              =0 S'IL N'EN EXISTE PAS
C     DISMI2 : CARRE DE LA DISTANCE DE NPMIN AU POINT PT SI NPMIN>0
C              =0 SI LE PT A ETE IDENTIFIE AU POINT NPMIN>0 DE PTXYZD
      IF( NPMIN .GT. 0 .AND. DISMI2 .EQ. 0 ) THEN
         GOTO 9999
      ENDIF

C     DISTANCE D'IDENTIFICATION AU POINT PT ( CF XYZIDD )
      DISTAN = REAL( SQRT( PT(1) ** 2 + PT(2) ** 2 + PT(3) ** 2 ) )
      IF( DISTAN .LT. EPZERO ) THEN
C        POINT VOISIN DE L'ORIGINE
         DISTAN = EPZERO
      ELSE
C        POINT DISTANT DE L'ORIGINE
         DISTAN = DISTAN * EPSXYZ
      ENDIF

C     RECHERCHE SELECTIVE DES OT VOISINS SELON LA DISTANCE
C     DU POINT PT AVEC LES SOMMETS DE L'OT NUOTFE
C     ----------------------------------------------------
      CALL DPTSOT( PT,     PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             DISTMI, NUMINI )
      IF( DISTMI .LT. DISTAN ) THEN
C        LA BOULE DE RAYON DISTAN CONTIENT LE SOMMET DE L'OT
C        RECHERCHE DES OT VOISINS PAR LE SOMMET NUMINI
         CALL OTVOST( NUOTFE, NUMINI, LARBRO, LARBRT, PTXYZD,
     %                NBOTVO, NUOTVO )
         GOTO 30
      ENDIF

C     RECHERCHE SELECTIVE DES OT VOISINS SELON LA DISTANCE
C     DU POINT PT AVEC LES ARETES DE L'OT NUOTFE
C     ----------------------------------------------------
      CALL DPTAOT( PT,     PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             DISTMI, NUMINI )
      IF( DISTMI .LT. DISTAN ) THEN
C        LA BOULE DE RAYON DISTAN INTERSECTE L'ARETE NUMINI DE L'OT
C        RECHERCHE DES OT VOISINS PAR L'ARETE NUMINI
         CALL OTVOAT( NUOTFE, NUMINI, LARBRO, LARBRT, NBOTVO, NUOTVO )
         GOTO 30
      ENDIF

C     RECHERCHE SELECTIVE DES OT VOISINS SELON LA DISTANCE
C     DU POINT PT AVEC LES FACES DE L'OT NUOTFE
C     ----------------------------------------------------
      CALL DPTFOT( PT,     PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             DISTMI, NUMINI )
      IF( DISTMI .LT. DISTAN ) THEN
C        LA BOULE DE RAYON DISTAN INTERSECTE LA FACE NUMINI DE L'OT
C        RECHERCHE DES OT VOISINS PAR LA FACE NUMINI
         CALL OTVOFA( NUOTFE, NUMINI, LARBRO, LARBRT, NUOTVO, NBOTVO )
         NBOTVO = 1
         GOTO 30
      ENDIF

C     LA BOULE N'A PAS D'INTERSECTION AVEC D'AUTRES OT => RETOUR
      GOTO 9999

C     A PARTIR DE LA LISTE DES OT VOISINS DU POINT PT
C     RECHERCHE DES SOMMETS OU POINTS DES OT VOISINS
C     ===============================================
 30   MNFILS = 0
      MXFILS = 128
      CALL TNMCDC( 'ENTIER', MXFILS, MNFILS )

      DO 100 I=1,NBOTVO
C        LE NUMERO D'OT VOISIN
         NUOT = NUOTVO( I )
         IF( NUOT .NE. 0 ) THEN
C           RECHERCHE DU SOMMET OU POINT LE PLUS PROCHE DANS L'OT NUOT
            CALL XYZDOT( PT,    PTXYZD, NUOT, LARBRO, LARBRT,
     %                   NPMIN, DISMI2 )
            IF( NPMIN .GT. 0 .AND. DISMI2 .LE. 0 ) GOTO 9999
C           RECHERCHE DES OT FEUILLES DE L'OT NUOT POUR ATTEINDRE LES POINTS
            CALL OTFEOT( NUOT, LARBRO, LARBRT, MXFILS, MNFILS,
     %                   MXOTFL, NBOTFL, MNOTFL )
            DO 90 J=1,NBOTFL
               NUOTFE = MCN( MNOTFL - 1 + J )
               CALL XYZDOT( PT,    PTXYZD, NUOTFE, LARBRO, LARBRT,
     %                      NPMIN, DISMI2 )
               IF( NPMIN .GT. 0 .AND. DISMI2 .LE. 0 ) GOTO 9000
 90         CONTINUE
         ENDIF
 100  CONTINUE

C     DESTRUCTION DE LA PILE
 9000 IF( MNFILS .GT. 0 ) CALL TNMCDS('ENTIER', MXFILS, MNFILS )

 9999 RETURN
      END
