      SUBROUTINE OTTAID( NOFOTI, ARETOCG, HEXA, XYZ,
     %                   DTAILL, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     CALCUL LA TAILLE IDEALE AU POINT XYZ A PARTIR DE LA
C -----     FONCTION TAILLE_IDEALE(X,Y,Z) FOURNIE PAR L'UTILISATEUR
C           TOUT POINT EXTERIEUR A L'HEXAEDRE ENGLOBANT RETOURNE ARETOCG
C ENTREES:
C --------
C NOFOTI : NUMERO DE LA FONCTION TAILLE_IDEALE(X,Y,Z)
C          >0 SI ELLE EXISTE, 0 SINON
C ARETOCG: DISTANCE SOUHAITEE des SOMMETS DE L'OCTAEDRE ENGLOBANT
C HEXA   : MIN ET MAX DES 3 COORDONNEES D'UN HEXAEDRE ENGLOBANT
C          LES POINTS DE L'OBJET A MAILLER
C XYZ    : LES 3 COORDONNEES REELLES DOUBLE PRECISION DU POINT
C
C SORTIES:
C --------
C DTAILL : LA TAILLE_IDEALE DE L'ARETE SOUHAITEE AUTOUR DU POINT XYZ
C IERR   : 0 SI PAS D'ERREUR, <>0 SINON
C          1 CALCUL INCORRECT DE TAILLE_IDEALE(X,Y,Z)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE PARIS UPMC        JUIN 1997
C MODIFS : ALAIN PERRONNET LJLL UPMC & Saint PIERRE DU PERRAY  MARS 2016
C MODIFS : ALAIN PERRONNET Saint Pierre du Perray              JUIN 2020
C2345X7..............................................................012
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      DOUBLE PRECISION  XYZ(3),  DTAILL
      REAL              ARETOCG, HEXA(6,2)

C     LE POINT XYZ EST IL EN DEHORS DE L'HEXAEDRE ENGLOBANT LES POINTS?
      IF( XYZ(1) .LT. HEXA(1,1) .OR. XYZ(1) .GT. HEXA(1,2) .OR.
     %    XYZ(2) .LT. HEXA(2,1) .OR. XYZ(2) .GT. HEXA(2,2) .OR.
     %    XYZ(3) .LT. HEXA(3,1) .OR. XYZ(3) .GT. HEXA(3,2) ) THEN
          DTAILL = ARETOCG
          IERR   = 0
          RETURN
      ENDIF

C     CALCUL DE TAILLE_IDEALE( XYZ )
      CALL TAILIDEA( NOFOTI, XYZ, NCODEV, DTAILL )
      IERR = 1 - NCODEV

      RETURN
      END
