      SUBROUTINE OTVADP( NP,     DISTAN, PTXYZD,
     %                   LARBRO, LARBRT, NUOTPT,
     %                   NBOTVO, NUOTVO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LES OT VOISINS D'UN POINT PT DONT UN SOMMET
C -----    EST A DISTANCE INFERIEURE A DISTAN
C
C ENTREES:
C --------
C NP     : NUMERO DU POINT DANS PTXYZD
C DISTAN : LA DISTANCE MINIMALE AUTOUR DU POINT NP
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(0,0) : NO DU 1-ER OCTAEDRE VIDE DANS LARBRO
C      LARBRO(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRO (ICI -1:20)
C      LARBRO(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRO
C                    (ICI = MXARBO)
C
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT
C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 0 A 4 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C
C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT
C
C NUOTPT : NUMERO D'OT (>0 SI LARBRO, <0 SI LARBRT) DE CHAQUE POINT PTXYZD
C          SI SOMMET D'OT, C'EST LE NUMERO D'OT DU PERE
C          SI POINT INTERNE OU FRONTALIER, C'EST LE NUMERO D'OT LE CONTENANT
C
C SORTIES:
C --------
C NBOTVO : NOMBRE D'OT VOISINS DE DISTANCE INFERIEURE
C NUOTVO : NUMERO DANS LARBRO( >0) OU LARBRT (<0) DES OT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    DECEMBRE 1992
C2345X7..............................................................012
      DOUBLE PRECISION  PTXYZD(4,*)
      INTEGER           LARBRO(-1:20,0:*),
     &                  LARBRT(-1:9,0:*),
     &                  NUOTPT(1:*),
     &                  NUOTVO(1:*)
C
C     NUOT SON NUMERO D'OT LE CONTENANT
      NUOT = NUOTPT( NP )
C
C     L'OT FEUILLE NUOTFE CONTENANT LE POINT PT A PARTIR DE L'OT NUOT
      CALL NOTFPT( PTXYZD(1,NP), PTXYZD, NUOT, LARBRO, LARBRT, NUOTFE )
      NBOTVO = 1
      NUOTVO( 1 ) = NUOTFE
C
C     RECHERCHE SELECTIVE DES OT VOISINS SELON LA DISTANCE
C     DU POINT PT AVEC LES SOMMETS DE L'OT NUOTFE
      CALL DPTSOT( PTXYZD(1,NP), PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             DISTMI, NUMINI )
      IF( DISTMI .LT. DISTAN ) THEN
C        LA BOULE DE RAYON DISTAN CONTIENT LE SOMMET DE L'OT
C        RECHERCHE DES OT VOISINS PAR LE SOMMET NUMINI
         CALL OTVOST( NUOTFE, NUMINI, LARBRO, LARBRT, PTXYZD,
     %                NBOTV,  NUOTVO(2) )
C        AJOUT SANS DUPLICATION DES NBOTV OT VOISINS
         CALL AJPESR( NBOTV, NUOTVO(2), NBOTVO, NUOTVO )
         RETURN
      ENDIF
C
C     RECHERCHE SELECTIVE DES OT VOISINS SELON LA DISTANCE
C     DU POINT PT AVEC LES ARETES DE L'OT NUOTFE
      CALL DPTAOT( PTXYZD(1,NP), PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             DISTMI, NUMINI )
      IF( DISTMI .LT. DISTAN ) THEN
C        LA BOULE DE RAYON DISTAN INTERSECTE L'ARETE NUMINI DE L'OT
C        RECHERCHE DES OT VOISINS PAR L'ARETE NUMINI
         CALL OTVOAT( NUOTFE, NUMINI, LARBRO, LARBRT,
     %                NBOTV,  NUOTVO(2) )
C        AJOUT SANS DUPLICATION DES NBOTV OT VOISINS
         CALL AJPESR( NBOTV, NUOTVO(2), NBOTVO, NUOTVO )
         RETURN
      ENDIF
C
C     RECHERCHE SELECTIVE DES OT VOISINS SELON LA DISTANCE
C     DU POINT PT AVEC LES FACES DE L'OT NUOTFE
      CALL DPTFOT( PTXYZD(1,NP), PTXYZD, NUOTFE, LARBRO, LARBRT,
     %             DISTMI, NUMINI )
      IF( DISTMI .LT. DISTAN ) THEN
C        LA BOULE DE RAYON DISTAN INTERSECTE LA FACE NUMINI DE L'OT
C        RECHERCHE DE L'OT VOISIN PAR LA FACE NUMINI
         CALL OTVOFA( NUOTFE, NUMINI, LARBRO, LARBRT, NUOT, NBOTV )
         IF( NUOT .NE. 0 ) THEN
            NUOTVO(2) = NUOT
            NBOTVO = 2
         ENDIF
      ENDIF

      RETURN
      END
