      SUBROUTINE OTVOIS( NUOT, LARBRO, LARBRT, PTXYZD, NBOTVO, NUOTVO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER LES OT VOISINS PAR UN SOMMET OU UNE ARETE OU UNE
C -----    FACE DE L'OT NUOT ( NUOT N'EST PAS ICI UN DE SES VOISINS )
C
C ENTREES:
C --------
C NUOT   : NUMERO DE L'OT, >0 SI DANS LARBRO,  <0 SI DANS LARBRT
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0 OU <0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C         REMARQUE : TOUT FILS 1 EST UN OCTAEDRE => NO OT >0 DANS LARBRO
C                    DONC <0 => UNE FEUILLE
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT
C
C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 1 A 5 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C
C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0 OU <0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C         REMARQUE : TOUT FILS 1 EST UN OCTAEDRE => NO OT >0 DANS LARBRO
C                    DONC <0 => UNE FEUILLE
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT
C
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C
C ENTREE ET SORTIE:
C -----------------
C NBOTVO : NOMBRE D'OT VOISINS ACTUELS DEJA RECENSES ( 0 SI AUCUN )
C          ET DEJA STOCKES DANS LE TABLEAU NUOTVO
C          (57 AU PLUS POUR LES OT VOISINS D'UN OT)
C NUOTVO : NUMEROS DES OT VOISINS AVANT ET APRES SANS REPETITION
C
C ATTENTION : LES OT VOISINS SONT CUMULES SANS REPETITION
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1992
C2345X7..............................................................012
      INTEGER           LARBRO(-1:20,0:*),
     &                  LARBRT(-1:9 ,0:*) ,
     &                  NUOTVO(1:*),
     &                  NUOTV(1:16)
      DOUBLE PRECISION  PTXYZD(4,*)
C
C     LES OT VOISINS PAR TOUS LES SOMMETS DE L'OT
      IF( NUOT .GT. 0 )  THEN
C        OCTAEDRE
         NBST = 6
      ELSE
C        TETRAEDRE
         NBST = 4
      ENDIF
      DO 20 NS=1,NBST
         CALL OTVOST( NUOT, NS, LARBRO, LARBRT, PTXYZD, NBOTV, NUOTV )
         DO 10 I=1,NBOTV
            NUOTVV = NUOTV( I )
            IF( NUOTVV .NE. 0 ) THEN
C              AJOUT DE L'OT VOISIN
               CALL AJ1ESR( NUOTVV, NBOTVO, NUOTVO )
            ENDIF
 10      CONTINUE
 20   CONTINUE
      END
