      SUBROUTINE OTVOAT( NUOT, NOARET, LARBRO, LARBRT, NBOTVO, NUOTVO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  RETROUVER LES 3 OT OPPOSES PAR L'ARETE NOARET DE L'OT NUOT
C -----
C
C ENTREES:
C --------
C NUOT   : NUMERO DE L'OT, >0 SI DANS LARBRO,  <0 SI DANS LARBRT
C NOARET : 1 A 6  POUR UN TETRAEDRE ( NUOT<0 )
C          1 A 12 POUR UN OCTAEDRE  ( NUOT>0 )
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0 OU <0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C         REMARQUE : TOUT FILS 1 EST UN OCTAEDRE => NO OT >0 DANS LARBRO
C                    DONC <0 => UNE FEUILLE
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT
C
C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 1 A 5 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C
C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0 OU <0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C         REMARQUE : TOUT FILS 1 EST UN OCTAEDRE => NO OT >0 DANS LARBRO
C                    DONC <0 => UNE FEUILLE
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT
C
C NUOTPT : NUMERO D'OT (>0 SI LARBRO, <0 SI LARBRT) DE CHAQUE POINT PTXYZD
C          SI SOMMET D'OT, C'EST LE NUMERO D'OT DU PERE
C          SI POINT INTERNE OU FRONTALIER, C'EST LE NUMERO D'OT LE CONTENANT
C
C SORTIES:
C --------
C NBOTVO : NOMBRE D'OT VOISIN PAR L'ARETE NOARET DE L'OT NUOT
C NUOTVO : NUMEROS DES OT VOISINS PAR L'ARETE NOARET
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1992
C2345X7..............................................................012
      INTEGER           LARBRO(-1:20,0:*),
     &                  LARBRT(-1:9,0:*),
     &                  NUOTVO(3)
C
C     RECHERCHE DU NUMERO DES 2 FACES D'ARETE NOARET
      CALL NUFAOT( NUOT, NOARET, NUFAC1, NUFAC2 )
C
C     RECHERCHE DE L'OT VOISIN PAR LA 1-ERE FACE DE L'ARETE NOARET
      NBOTVO = 0
      CALL OTVOFA( NUOT, NUFAC1, LARBRO, LARBRT, NUOTVO(1), NB )
      IF( NUOTVO(1) .NE. 0 ) NBOTVO = 1
C
C     RECHERCHE DE L'OT OPPOSE PAR L'ARETE NOARET
      CALL OTVOAR( NUOT, NOARET, LARBRO, LARBRT, NUOTVO(NBOTVO+1), NB )
      IF( NUOTVO(NBOTVO+1) .NE. 0 ) NBOTVO = NBOTVO + 1
C
C     RECHERCHE DE L'OT VOISIN PAR LA 1-ERE FACE DE L'ARETE NOARET
      CALL OTVOFA( NUOT, NUFAC2, LARBRO, LARBRT, NUOTVO(NBOTVO+1), NB )
      IF( NUOTVO(NBOTVO+1) .NE. 0 ) NBOTVO = NBOTVO + 1
      END
