      SUBROUTINE PLCN1T( PAX1CN, RAY1CN, RAY2CN,
     %                   RPCONE, HAUTCN, VNPLAN, PTCONE,
     %                   PGCONE, TG, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DU VECTEUR UNITAIRE DE LA TG AU TRONC DE CONE ET
C -----    DANS LE PLAN DEFINI PAR SON VECTEUR NORMAL VNPLAN AU POINT PTCONE
C
C ENTREES:
C --------
C PAX1CN : POINT 1 DE BASE DE L'AXE DU TRONC DE CONE
C RAY1CN : RAYON DU CERCLE AU POINT PAX1CN (PLAN ORTHOGONAL A L'AXE DU CONE )
C PAX2CN : POINT 2 DE L'AXE DU TRONC DE CONE
C RAY2CN : RAYON DU CERCLE AU POINT PAX2CN (PLAN ORTHOGONAL A L'AXE DU CONE )
C RPCONE : REPERE PROPRE ORTHONORME DU CONE D'ORIGINE AU POINT PAX1CN
C HAUTCN : HAUTEUR DU TRONC DE CONE
C VNPLAN : VECTEUR NORMAL UNITAIRE AU PLAN DES 3 POINTS
C PTCONE : POINT D'INTERSECTION DANS LE REPERE PROPRE AU CONE
C
C SORTIES:
C --------
C PGCONE : MEME POINT DU CONE MAIS DANS LE REPERE GLOBAL
C TG     : VECTEUR UNITAIRE DANS LE REPERE GLOBAL DE LA TG AU TRONC
C          DE CONE ET DANS LE PLAN DE NORMALE VN AU POINT GLOBAL PGCONE
C IERR   : 0 SI AUCUNE ERREUR DETECTEE
C          1 SI VECTEUR TG NUL
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN UPMC ANALYSE NUMERIQUE PARIS     JANVIER 1998
C2345X7..............................................................012
      DOUBLE PRECISION  PAX1CN(3)
      DOUBLE PRECISION  RPCONE(3,3), VNPLAN(3)
      DOUBLE PRECISION  RAY1CN, RAY2CN, HAUTCN
      DOUBLE PRECISION  PTCONE(3), PGCONE(3), PTGENE(3), PGGENE(3),
     %                  V1(3),  V2(3), V3(3), VNCONE(3),
     %                  PTAXEC(3), PGAXEC(3), TG(3)
      DOUBLE PRECISION  ANGLED, ANGLE
C
C     PASSAGE AUX COORDONNEES GLOBALES DU POINT PTCONE
      CALL AC3D3D( PAX1CN, RPCONE, PTCONE, PGCONE )
C
C     PTAXEC EST LE POINT DE L'AXE DU CONE DE MEME COTE Z QUE PTCONE
C     LES COORDONNEES SONT CELLES DU REPERE PROPRE AU CONE
      PTAXEC(1) = 0D0
      PTAXEC(2) = 0D0
      PTAXEC(3) = PTCONE(3)
C     PASSAGE AUX COORDONNEES GLOBALES
      CALL AC3D3D( PAX1CN, RPCONE, PTAXEC, PGAXEC )
C
C     CALCUL D'UN POINT PTGENE DE LA GENERATRICE DU CONE PASSANT PAR PTCONE
C     ANGLE DE LA GENERATRICE DU CONE PASSANT PAR PTCONE
      PTGENE(1) = 1D0
      PTGENE(2) = 0D0
      ANGLE = ANGLED( PTAXEC, PTGENE, PTCONE )
      IF( ABS(PTCONE(3)) .LE. 1D-12*HAUTCN ) THEN
C        LE POINT CHOISI DE LA GENERATRICE DU CONE A POUR COTE Z HAUTCN
         PTGENE(1) = RAY2CN * COS( ANGLE )
         PTGENE(2) = RAY2CN * SIN( ANGLE )
         PTGENE(3) = HAUTCN
      ELSE
C        LE POINT CHOISI DE LA GENERATRICE DU CONE A POUR COTE Z 0D0
         PTGENE(1) = RAY1CN * COS( ANGLE )
         PTGENE(2) = RAY1CN * SIN( ANGLE )
         PTGENE(3) = 0D0
      ENDIF
C     PASSAGE AUX COORDONNEES GLOBALES
      CALL AC3D3D( PAX1CN, RPCONE, PTGENE, PGGENE )
C
C     VECTEUR NORMAL QUI AVEC PTCONE PTGENE DEFINIT LE PLAN TG AU CONE
C     AU POINT PTCONE=PGCONE
      V1(1) = PGAXEC(1) - PGCONE(1)
      V1(2) = PGAXEC(2) - PGCONE(2)
      V1(3) = PGAXEC(3) - PGCONE(3)
      CALL NORME1( 3, V1, IERR )
      V2(1) = PGGENE(1)  - PGCONE(1)
      V2(2) = PGGENE(2)  - PGCONE(2)
      V2(3) = PGGENE(3)  - PGCONE(3)
      CALL NORME1( 3, V2, IERR )
      CALL PROVEC( V1, V2, V3 )
C
C     LE VECTEUR NORMAL VNCONE AU PLAN TG DU CONE AU POINT PGCONE
      CALL PROVEC( V3, V2, VNCONE )
C
C     LE VECTEUR UNITAIRE TANGENT AU POINT PGCONE AU TRONC DE CONE ET DANS LE PL
      CALL PROVEC( VNPLAN, VNCONE, TG )
      CALL NORME1( 3, TG, IERR )
C
      RETURN
      END
