      SUBROUTINE PLCNDI( PARAME, ANGLE1, ANGLE2,
     %                   RAY1CN, RAY2CN, HAUTCN, XYZ1PL, VN,
     %                   ANGLE,  P, Q,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DU PARAMETRE DU POINT D'INTERSECTION DE LA GENERATRICE
C -----    DU CONE AVEC LE PLAN DEFINI PAR LES 3 POINTS XYZ1PL
C
C ENTREES:
C --------
C PARAME : PARAMETRE A PARTIR DE P SUR LA DROITE PQ DU POINT D'INTERSECTION
C          AVEC LE PLAN QUI DOIT VALOIR 0 OU 1 EN SORTIE
C ANGLE1 : DE LA GENERATRICE AVEC OX DANS LE REPERE PROPRE AU CONE
C          TEL QUE LE PARAME CORRESPONDANT SOIT EXTERIEUR A [0,1]
C ANGLE2 : DE LA GENERATRICE AVEC OX DANS LE REPERE PROPRE AU CONE
C          TEL QUE LE PARAME CORRESPONDANT SOIT INTERIEUR A [0,1]
C RAY1CN : RAYON DU CERCLE AU POINT PAX1CN (PLAN ORTHOGONAL A L'AXE DU CONE )
C RAY2CN : RAYON DU CERCLE AU POINT PAX2CN (PLAN ORTHOGONAL A L'AXE DU CONE )
C HAUTCN : HAUTEUR DU TRONC DE CONE
C XYZ1PL : 3 COORDONNEES DANS LE REPERE DU CONE DES 1-ER POINT DE DEFINITION DU
C VN     : VECTEUR NORMAL UNITAIRE AU PLAN DES 3 POINTS
C
C SORTIES:
C --------
C PARAME : PARAMETRE A PARTIR DE P SUR LA DROITE PQ DU POINT D'INTERSECTION
C          AVEC LE PLAN
C ANGLE  : L'ANGLE DE LA GENERATRICE REALISANT PARAME=0 OU 1
C P,Q    : 3 COORDONNEES DANS LE REPERE PROPRE DU CONE DES 2 EXTREMITES DE
C          DE LA GENERATRICE D'ANGLE AVEC OX
C IERR   :=0 PAS D'ERREUR DETECTEE
C         =2 LE PLAN EST TANGENT AU CONE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET UPMC ANALYSE NUMERIQUE  PARIS    JANVIER 1998
C2345X7..............................................................012
      DOUBLE PRECISION  PARAME, ANGLE1, ANGLE2,
     %                  RAY1CN, RAY2CN, HAUTCN, XYZ1PL(3), VN(3),
     %                  ANGLE,  P(3), Q(3)
C
      IF( PARAME .LE. 0.5D0 ) THEN
C
C        RECHERCHE DE PARAME=0
C        =====================
C        DICHOTOMIE SUR L'ANGLE POUR ATTEINDRE PARAME=0 OU 1
 10      ANGLE = ( ANGLE1 + ANGLE2 ) * 0.5D0
         CALL PLCNAN( ANGLE,  RAY1CN, RAY2CN, HAUTCN, XYZ1PL, VN,
     %                PARAME, P, Q,   IERR )
         IF( IERR .NE. 0 ) GOTO 9000
         IF( ABS( PARAME ) .LE. 1D-12  .OR.
     %       ABS( ANGLE2 - ANGLE1 ) .LE. 1D-12 ) GOTO 9000
C
         IF( PARAME .LT. 0 ) THEN
            ANGLE1 = ANGLE
         ELSE
            ANGLE2 = ANGLE
         ENDIF
         GOTO 10
C
      ELSE
C
C        RECHERCHE DE PARAME=1
C        =====================
C        DICHOTOMIE SUR L'ANGLE POUR ATTEINDRE PARAME=0 OU 1
 20      ANGLE = ( ANGLE1 + ANGLE2 ) * 0.5D0
         CALL PLCNAN( ANGLE,  RAY1CN, RAY2CN, HAUTCN, XYZ1PL, VN,
     %                PARAME, P, Q,   IERR )
         IF( IERR .NE. 0 ) GOTO 9000
         IF( ABS(    1D0 - PARAME ) .LE. 1D-12 .OR.
     %       ABS( ANGLE2 - ANGLE1 ) .LE. 1D-12 ) GOTO 9000
C
         IF( PARAME .GT. 1D0 ) THEN
            ANGLE1 = ANGLE
            GOTO 20
         ELSE
            ANGLE2 = ANGLE
            GOTO 20
         ENDIF
      ENDIF
C
 9000 RETURN
      END
