      SUBROUTINE PPVTR1( P, HH, PXYD, NT, LETREE, NOLESO, NS, DMIN )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE PLUS PROCHE POINT NS DE P DE DISTANCE < H
C -----    RENDRE NEGATIF NOLESO(N) DE TOUT SOMMET N DU TE NT
C          TROP PROCHE DU POINT P ( DISTANCE < H )
C
C ATTENTION : P N'EST PAS DANS LETREE NI AJOUTE DANS CE SP (CF AJPTR2)
C
C ENTREES:
C --------
C P      : 2 COORDONNEES DU POINT P
C HH     : DISTANCE **2 AU DESSOUS DE LAQUELLE CHERCHER LES SOMMETS DE TE
C PXYD   : X Y DISTANCE DES POINTS
C NT     : NUMERO LETREE DU TE MINIMAL CONTENANT LE POINT P
C LETREE : ARBRE-4 DES TRIANGLES EQUILATERAUX (TE) FOND DE LA TRIANGULATION
C      LETREE(0,0)  NO DU 1-ER TE VIDE DANS LETREE
C      LETREE(0,1) : MAXIMUM DU 1-ER INDICE DE LETREE (ICI 8)
C      LETREE(0,2) : MAXIMUM DECLARE DU 2-EME INDICE DE LETREE (ICI MXTREE)
C      LETREE(0:8,1) : RACINE DE L'ARBRE  (TRIANGLE SANS SUR TRIANGLE)
C      SI LETREE(0,.)>0 ALORS
C         LETREE(0:3,J) : NO (>0) LETREE DES 4 SOUS-TRIANGLES DU TRIANGLE J
C      SINON
C         LETREE(0:3,J) :-NO PXYD DES 1 … 4 POINTS INTERNES AU TRIANGLE J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C      LETREE(4,J) : NO LETREE DU SUR-TRIANGLE DU TRIANGLE J
C      LETREE(5,J) : 0 1 2 3 NO DU SOUS-TRIANGLE J POUR SON SUR-TRIANGLE
C      LETREE(6:8,J) : NO PXYD DES 3 SOMMETS DU TRIANGLE J
C NOLESO : TABLEAU DU NUMERO DANS LETREE D'UN SOMMET DE TE
C      >0 +NO LETREE DU TRIANGLE DU SOMMET ET SOMMET DE LA TRIANGULATION
C      <0 -NO LETREE DU TRIANGLE DU SOMMET ELIMINE   DE LA TRIANGULATION
C      =0 SI SOMMET N'APPARTENANT PAS AUX SOMMETS DE LETREE
C
C SORTIES :
C ---------
C NS      : NUMERO PXYD DU PLUS PROCHE SOMMET DE LA TRIANGULATION ACTUELLE
C           ET DISTANT DE MOINS DE SQRT( HH )
C DMIN    : DISTANCE MINIMALE DE P A PXYD(NS)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    FEVRIER 1992
C2345X7..............................................................012
      PARAMETER        (MXPILE=256)
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      DOUBLE PRECISION  P(2), PXYD(3,*)
      INTEGER           LETREE(0:8,0:*), NOLESO(*)
      INTEGER           LAPILE(MXPILE)
C
C     RECHERCHE DES POINTS INTERNES AU TRIANGLE NT
      LHPILE = 1
      LAPILE( LHPILE ) = NT
C
C     TANT QUE LE TRIANGLE N'EST PAS UN SOUS-TRIANGLE
C              EMPILER LES SOUS-TRIANGLES
 10   NTR = LAPILE( LHPILE )
C     LE TRIANGLE EST DEPILE
      LHPILE = LHPILE - 1
C
C     NTR CONTIENT 3 SOMMETS DE TE. SONT-ILS TROP PROCHES DE P?
      DO 15 I=6,8
         NS1 = LETREE(I,NTR)
         IF( NOLESO(NS1) .GT. 0 ) THEN
C           DISTANCE DU POINT P AU SOMMET DU SOUS-TRIANGLE
            D = REAL( (P(1)-PXYD(1,NS1)) **2 + (P(2)-PXYD(2,NS1)) **2 )
            IF( D .LT. HH ) THEN
C              SOMMET TROP PROCHE
               NOLESO( NS1 ) = - NOLESO( NS1 )
            ENDIF
         ENDIF
 15   CONTINUE
C
      IF( LETREE(0,NTR) .GT. 0 ) THEN
C
C        IL EXISTE 4 SOUS-TRIANGLES A EMPILER
         IF( MXPILE .LT. LHPILE + 4 ) THEN
C           SATURATION DE LA PILE
            WRITE(IMPRIM,*) 'PPVTR1:SATURATION DE LA PILE'
            CALL XVPAUSE
            GOTO 10
         ENDIF
C
C        LES 4 SOUS-TRIANGLES SONT EMPILES
         LHPILE = LHPILE + 4
         DO 20 I=0,3
            LAPILE( LHPILE - I ) = LETREE( I, NTR )
 20      CONTINUE
         GOTO 10
C
      ELSE
C
C        NTR CONTIENT 0 A 4 POINTS DE DISTANCE MINIMALE A P?
         DO 30 I=0,3
            NS1 = -LETREE(I,NTR)
            IF( NS1 .GT. 0 ) THEN
C              DISTANCE DU POINT P AU POINT DU SOUS-TRIANGLE
               D = REAL( (P(1)-PXYD(1,NS1))**2 +(P(2)-PXYD(2,NS1))**2 )
               IF( D .LT. DMIN ) THEN
                  DMIN = D
                  NS   = NS1
               ENDIF
            ENDIF
 30      CONTINUE
C
         IF( LHPILE .GT. 0 ) GOTO 10
C
      ENDIF
      END
