      SUBROUTINE QTEN4T( NBSOMM, MXSOMM, XYZSOM, NBDM,   NUDMEF,
     %                   NT,     NBSOTE, N1TEVI, NSTETR,
     %                   NO1TSO, N1TESO, NOTESO,
     %                   N1FEOC, N1FEVI, NFETOI, VOETOI, QUETOI,
     %                   MXTETA, VOLUMT, QUALIT, NOTEDS,
     %                   VOLET0, QUAET0, VOLET1, QUAET1, IERR  )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CONSTRUIRE L'ETOILE DES TETRAEDRES D'ARETE LA PLUS LONGUE
C -----    ARETE DU TETRAEDRE NT
C          CHERCHER LE MEILLEUR BARYCENTRE DE CES TETRAEDRES
C          CREER CETTE TETRAEDRISATION SI VOLUME RESPECTE ET
C          QUALITE AMELIOREE DE L'ETOILE
C
C ENTREES:
C --------
C NT     : NUMERO DU TETRAEDRE DEGENERE DE TYPE QUADRANGLE
C          AVEC DES TETRAEDRES OPPOSES
C NBSOTE : VALEUR MAXIMALE DE DECLARATION DU PREMIER INDICE DE NSTETR(>3)
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS DECLARABLES DANS XYZSOM
C XYZSOM : COORDONNEES X Y Z DES NBSOMM SOMMETS DES TETRAEDRES
C NBDM   : 0 SI 1 MATERIAU=VOLUME, SINON NOMBRE DE MATERIAUX DU VOLUME
C
C MODIFIES:
C ---------
C NBSOMM : NOMBRE DE SOMMETS AVANT ET APRES
C NUDMEF : NUMERO DE MATERIAU DE CHAQUE TETRAEDRE DU MAILLAGE
C          ATTENTION: CE TABLEAU EXISTE SEULEMENT SI NBDM>0
C N1TEVI : NUMERO DU PREMIER TETRAEDRE VIDE DANS NSTETR
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE
C NO1TSO : NUMERO DU 1-ER TETRAEDRE DANS NOTESO DE CHAQUE SOMMET
C N1TESO : NUMERO DU PREMIER TETRAEDRE NON UTILISE DANS NOTESO
C          CHAINAGE DES PLACES VIDES DANS NOTESO(2,*)
C NOTESO : NOTESO(1,*) NUMERO DANS NSTETR DU TETRAEDRE
C          NOTESO(2,*) NUMERO DANS NOTESO DU TETRAEDRE SUIVANT
C                      0 SI C'EST LE DERNIER
C MXTETA : NUMERO MAXIMAL DES TETRAEDRES ACTUELS
C VOLUMT : VOLUME  DES TETRAEDRES DE LA TETRAEDRISATION
C QUALIT : QUALITE DES TETRAEDRES DE LA TETRAEDRISATION
C
C TABLEAUX AUXILIAIRES :
C ----------------------
C NFETOI(5,MXFAET)  DES ENTIERS
C NOSOET(MXTETR)    DES ENTIERS
C VOETOI(MXFAET)    DES REELS
C QUETOI(MXFAET)    DES REELS
C NOTEDS : NUMERO DANS NSTETR DES TETRAEDRES A DETRUIRE
C
C SORTIES:
C --------
C VOLET0 : VOLUME  DE L'ETOILE INITIALE
C QUAET0 : QUALITE DE L'ETOILE INITIALE
C VOLET1 : VOLUME  DE LA DERNIERE ETOILE CALCULEE
C QUAET1 : QUALITE DE LA DERNIERE ETOILE CALCULEE
C IERR   : = 0 SI PAS D'ERREUR ET PAS DE MODIFICATION
C          =-1 SI MODIFICATION EFFECTUEE
C          > 0 EN CAS DE SATURATION D'UN TABLEAU
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 1993
C MODIFS : ALAIN PERRONNET LJLL UPMC et St Pierre du Perray Fevrier 2016
C....................................................................012
      INTEGER           NSTETR(NBSOTE,*),
     %                  NUDMEF(*),
     %                  NO1TSO(*),
     %                  NOTESO(2,*),
     %                  NOTEDS(*),
     %                  NFETOI(5,*)
      REAL              VOETOI(*), QUETOI(*)
      REAL              XYZSOM(3,MXSOMM), VOLUMT(*), QUALIT(*)
      REAL              LONARE(6), P(3), PP(3)

      INTEGER           NOSOARTE(2,6)
      DATA              NOSOARTE / 1,2, 2,3, 3,1, 4,1, 4,2, 4,3 /

C     ICI PAS DE SOMMET DOUBLE DES TETRAEDRES OPPOSES AUX FACES DE NT

C     RECHERCHE DES 2 DIAGONALES DU QUADRANGLE=TETRAEDRE DEGENERE
C     LONGUEUR DES 6 ARETES DU TETRAEDRE NT
      CALL LON6AR( XYZSOM(1,NSTETR(1,NT)),
     %             XYZSOM(1,NSTETR(2,NT)),
     %             XYZSOM(1,NSTETR(3,NT)),
     %             XYZSOM(1,NSTETR(4,NT)), LONARE )
      IMAX  = 0
      ARMAX = 0
      DO I=1,6
         IF( LONARE(I) .GT. ARMAX ) THEN
            IMAX  = I
            ARMAX = LONARE(I)
         ENDIF
      ENDDO
      NPAS = 0

C     QUALITE MINIMALE DE L'ETOILE A TESTER
 20   QUALM0 = QUALIT( NT )

C     LES 2 SOMMETS DE LA PLUS LONGUE ARETE DU TETRAEDRE NT
      NS1 = NSTETR( NOSOARTE( 1, IMAX ), NT )
      NS3 = NSTETR( NOSOARTE( 2, IMAX ), NT )

C     LA PLUS LONGUE ARETE EST LA DIAGONALE DU QUADRANGLE
C     RECHERCHE DES TETRAEDRES QUI S'ENROULENT AUTOUR DE NS1 NS3
      CALL NOTEAR( NS1,    NS3,
     %             NBSOTE, NSTETR, NO1TSO, NOTESO,
     %             NBTEDS, NOTEDS )

C     ESSAI DE TETRAEDRISER L'ETOILE A PARTIR DU BARYCENTRE DE CHACUN
C     DES TETRAEDRES D'ARETE LA DIAGONALE NS1-NS3
      MEILEUR = 0
      DO 50 I=1,NBTEDS

         NT1 = NOTEDS(I)
         IF( NT1 .LE. 0 ) GOTO 50

C        LE BARYCENTRE DU TETRAEDRE NT1
         DO J=1,3
            P( J ) = 0
            DO K=1,4
               P( J ) = P( J ) + XYZSOM( J, NSTETR(K,NT1) )
            ENDDO
            P( J ) = P( J ) / 4
         ENDDO

C        SIMULATION DE TETRAEDRISATION ETOILEE PAR CE BARYCENTRE
         CALL SIPITE( P,      XYZSOM, NBTEDS, NOTEDS, NBSOTE, NSTETR,
     %                QUALIT, N1FEOC, N1FEVI, NFETOI, VOETOI, QUETOI,
     %                VOLET0, QUAET0, VOLET1, QUAET1 )

         IF( QUAET1 .LE. 0 ) GOTO 50
         IF( QUAET1 .GT. QUALM0 .AND.
     %       ABS(VOLET1-VOLET0) .LT. VOLET0*0.001 ) THEN

C           PROTECTION DU POINT DONNANT LA MEILLEURE QUALITE
            PP(1) = P(1)
            PP(2) = P(2)
            PP(3) = P(3)
            MEILEUR = NT1
            QUALM0 = QUAET1

         ENDIF

 50   CONTINUE
C
      IF( MEILEUR .NE. 0 ) THEN

C        SIMULATION DE TETRAEDRISATION ETOILEE PAR CE BARYCENTRE
C        ET CONSTRUCTION DES FACES DE L'ETOILE
         CALL SIPITE( PP,     XYZSOM, NBTEDS, NOTEDS, NBSOTE, NSTETR,
     %                QUALIT, N1FEOC, N1FEVI, NFETOI, VOETOI, QUETOI,
     %                VOLET0, QUAET0, VOLET1, QUAET1 )

C        GENERATION EFFECTIVE DE CETTE TETRAEDRISATION ETOILEE
         CALL GETEPT( PP,     NBSOMM, MXSOMM, XYZSOM, NBDM, NUDMEF,
     %                NBSOTE, N1TEVI, NSTETR,
     %                NO1TSO, N1TESO, NOTESO,
     %                N1FEOC, N1FEVI, NFETOI, NBTEDS, NOTEDS,
     %                MXTETA, VOLUMT, QUALIT,
     %                VOLET0, QUAET0, VOLET1, QUAET1, IERR )
         IF( IERR .EQ. 0 ) IERR = -1

      ELSE

C        ESSAI DE L'AUTRE DIAGONALE. L'ARETE OPPOSEE
         IF( NPAS .EQ. 0 ) THEN
            NPAS = 1
            IF( IMAX .EQ. 1 ) THEN
               IMAX = 6
            ELSE IF( IMAX .EQ. 2 ) THEN
               IMAX = 4
            ELSE IF( IMAX .EQ. 3 ) THEN
               IMAX = 5
            ELSE IF( IMAX .EQ. 4 ) THEN
               IMAX = 2
            ELSE IF( IMAX .EQ. 5 ) THEN
               IMAX = 3
            ELSE
               IMAX = 1
            ENDIF
            GOTO 20
         ENDIF

      ENDIF
C
      RETURN
      END
