      SUBROUTINE QU2T2T( NS4,    NS5,
     %                   XYZSOM, NBSOTE, N1TEVI, NSTETR, NBDM, NUDMEF,
     %                   NO1TSO, N1TESO, NOTESO,
     %                   NBTEDS, NOTEDS,
     %                   MXTETA, VOLUMT, QUALIT, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   TRANSFORMER LES EVENTUELS 2 TETRAEDRES AYANT EN COMMUN
C -----   L'ARETE NS4 NS5 EN ECHANGEANT LA DIAGONALE
C         (LES 2 FACES CONTENANT NS4-NS5 SONT COPLANAIRES)
C ENTREES :
C ---------
C NS4,NS5: NUMERO XYZSOM DES 2 SOMMETS DE L'ARETE
C XYZSOM : COORDONNEES X Y Z DES NBSOMM SOMMETS DES TETRAEDRES
C NBSOTE : VALEUR MAXIMALE DE DECLARATION DU PREMIER INDICE DE NSTETR(>3)
C NBDM   : 0 SI 1 MATERIAU=VOLUME, SINON NOMBRE DE MATERIAUX DU VOLUME
C
C MODIFIES :
C ----------
C N1TEVI : NUMERO DU PREMIER TETRAEDRE VIDE DANS NSTETR
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE
C NO1TSO : NUMERO DU 1-ER TETRAEDRE DANS NOTESO DE CHAQUE SOMMET
C N1TESO : NUMERO DU PREMIER TETRAEDRE NON UTILISE DANS NOTESO
C          CHAINAGE DES PLACES VIDES DANS NOTESO(2,*)
C NOTESO : NOTESO(1,*) NUMERO DANS NSTETR DU TETRAEDRE
C          NOTESO(2,*) NUMERO DANS NOTESO DU TETRAEDRE SUIVANT
C                      0 SI C'EST LE DERNIER
C NBTEDS : NOMBRE DE  TETRAEDRES D'ARETE IAR
C NOTEDS : NUMERO DES TETRAEDRES D'ARETE IAR
C MXTETA : NUMERO MAXIMAL DES TETRAEDRES ACTUELS
C VOLUMT : VOLUME  DES TETRAEDRES DE LA TETRAEDRISATION
C QUALIT : QUALITE DES TETRAEDRES DE LA TETRAEDRISATION
C IERR   : =-1 SI ECHANGE FAIT SANS ERREUR
C          = 0 SI PAS D'ERREUR MAIS PAS D'ECHANGE
C          > 0 EN CAS DE SATURATION D'UN TABLEAU
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    JANVIER 1992
C....................................................................012
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      INTEGER           NSTETR(NBSOTE,*),
     %                  NUDMEF(*),
     %                  NO1TSO(*),
     %                  NOTESO(2,*),
     %                  NOTEDS(*)
      REAL              XYZSOM(3,*),VOLUMT(*),QUALIT(*)
      REAL              ARMIN,ARMAX,SURFTR(4)
      INTEGER           NSF(4)
C
      GRAND = RINFO( 'GRAND' )
C
C     NBTEDS TETRAEDRES ONT L'ARETE NS4-NS5 COMMUNE
      CALL NOTEAR( NS4,    NS5,
     %             NBSOTE, NSTETR, NO1TSO, NOTESO,
     %             NBTEDS, NOTEDS )
      IF( NBTEDS .NE. 2 ) RETURN
      NT1 = NOTEDS(1)
      NT2 = NOTEDS(2)
C
      NUMATE = 0
      IF( NBDM .GT. 0 ) THEN
C        PAS DE MODIFICATION SI LES 2 TRIANGLES NE SONT PAS
C        DANS LE MEME VOLUME
         NUMATE = NUDMEF(NT1)
         IF( NUMATE .NE. NUDMEF(NT2) ) RETURN
      ENDIF
C
C     LE SOMMET COMMUN AUX 2 TETRAEDRES ET DIFFERENTS DE NS4-NS5
      L = 0
      DO 2 I=1,4
         NS1 = NSTETR(I,NT1)
         IF( NS1 .NE. NS4 .AND. NS1 .NE. NS5 ) THEN
            L = L + 1
            NSF(L) = NS1
         ENDIF
 2    CONTINUE
      DO 3 I=1,4
         NS1 = NSTETR(I,NT2)
         IF( NS1 .NE. NS4 .AND. NS1 .NE. NS5 ) THEN
            L = L + 1
            NSF(L) = NS1
         ENDIF
 3    CONTINUE
      DO 5 I=1,2
         NS3 = NSF(I)
         DO 4 J=3,4
            IF( NS3 .EQ. NSF(J) ) GOTO 7
 4       CONTINUE
 5    CONTINUE
      RETURN
C
C     NS3 EST LE SOMMET COMMUN AUX 2 TETRAEDRES DIFFERENTS DE NS4-NS5
 7    IF( J .EQ. 3 ) THEN
         NS2 = NSF(4)
      ELSE
         NS2 = NSF(3)
      ENDIF
      IF( I .EQ. 1 ) THEN
         NS1 = NSF(2)
      ELSE
         NS1 = NSF(1)
      ENDIF
C
C     REMISE EN VOLUME POSITIF DU TETRAEDRE NSF - NS4
      CALL QUATET( XYZSOM(1,NS1), XYZSOM(1,NS2),
     %             XYZSOM(1,NS3), XYZSOM(1,NS4),
     %             ARMIN, ARMAX, SURFTR, V, Q2 )
      IF( V .LT. 0 ) THEN
         K   = NS2
         NS2 = NS3
         NS3 = K
      ENDIF
C
C     QUALITE DES 2 TETRAEDRES INITIAUX
      Q1 = MIN( QUALIT(NT1), QUALIT(NT2) )
      V1 = ABS( VOLUMT(NT1) ) + ABS( VOLUMT(NT2) )
C
C     QUALITE ET VOLUME DES TETRAEDRES 1234 ET 1325
      CALL QUATET( XYZSOM(1,NS1), XYZSOM(1,NS2),
     %             XYZSOM(1,NS3), XYZSOM(1,NS4),
     %             ARMIN, ARMAX, SURFTR, V2, Q2 )
      CALL QUATET( XYZSOM(1,NS1), XYZSOM(1,NS3),
     %             XYZSOM(1,NS2), XYZSOM(1,NS5),
     %             ARMIN, ARMAX, SURFTR, V, Q3 )
C
C     COMPARAISON DES VOLUMES
      V2 = ABS(V2) + ABS(V)
      IF( ABS( V1 - V2 ) .LE. 1E-3*V1 ) THEN
C
C        VOLUMES CONSIDERES EGAUX. COMPARAISON DES QUALITES
         IF( MIN(Q2,Q3) .GT. Q1 ) THEN
C
C           QUALITE AMELIOREE PAR 2T =>2T
            DO 50 I=1,2
C              SUPPRESSION DU TETRAEDRE
               NT1 = NOTEDS(I)
               CALL DS1TET( NT1, NBSOTE, N1TEVI, NSTETR,
     %                      NO1TSO, N1TESO, NOTESO )
               QUALIT( NT1 ) = GRAND
               IF( NBDM .GT. 0 ) NUDMEF( NT1 ) = 0
 50         CONTINUE
C
C           CREATION DES TETRAEDRES 5231 3241
            CALL Q05S2T( NS5, NS4, NS1, NS2, NS3, NUMATE, NUDMEF,
     %                   XYZSOM, NBSOTE, N1TEVI, NSTETR,
     %                   NO1TSO, N1TESO, NOTESO,
     %                   MXTETA, VOLUMT, QUALIT, IERR )
            IF( IERR .EQ. 0 ) IERR = -1
         ENDIF
      ENDIF
      END
