      SUBROUTINE REAJSTPAV( HEXAPAVE, NBIPAV, ECHPAV, N1SPAVE, NOPTSUIV,
     %                      XYZ, ARETMX, NBSOM, MXSOMM, PTXYZD, NUCENTR,
     %                      NOSOMM )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     RETROUVER OU AJOUTER LE POINT XYZ AUX NBSOM POINTS
C -----     DE COORDONNEES STOCKEES DANS PTXYZD
C           LE PAVAGE DE CHAINAGE DES POINTS ACCELERE LA RECHERCHE
C           DU POINT LE PLUS PROCHE
C           IDENTIFICATION EVENTUELLE DU CENTRE DE L'ICOSAEDRE AVEC XYZ
C
C ENTREES :
C ---------
C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES
C XYZ     : LE POINT A TRAITER
C ARETMX  : DISTANCE SOUHAITEE AUTOUR DU POINT XYZ
C MXSOMM  : NOMBRE MAXIMAL DECLARABLE DE POINTS DANS PTXYZD
C PTXYZD  : X Y Z DISTANCE SOUHAITEE DES POINTS
C NUCENTR : NUMERO PTXYZD CENTRE DE L'ICOSAEDRE (=13)
C           OU DU POINT CENTRE DE LA PREMIERE SURFACE ENGLOBANTE
C              QUI L'ETOILE (=1)
C
C MODIFIE :
C ---------
C NBSOM   : NO DANS PTXYZD DU DERNIER POINT DE PTXYZD (AVANT ET APRES)
C
C SORTIES :
C ---------
C NOSOMM  : NO DANS PTXYZD DU POINT XYZ (RETROUVE DANS PTXYZD OU AJOUTE)
C           0 SI SATURATION DU TABLEAU PTXYZD
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     JANVIER 2006
C MODIFS : ALAIN PERRONNET LJLL UPMC ET ST PIERRE DU PERRAY   AVRIL 2008
C MODIFS : ALAIN PERRONNET LJLL UPMC ET ST PIERRE DU PERRAY    AOUT 2014
C2345X7..............................................................012
      COMMON / EPSSSS / EPZERO, EPSXYZ
C PRECISON ABSOLUE  POUR IDENTIFIER 2 POINTS DE R3 DANS LE VOISINAGE DE ZERO
C PRECISON RELATIVE POUR IDENTIFIER 2 POINTS DE R3 HORS LE VOISINAGE DE ZERO
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      INTEGER           NBIPAV(3), N1SPAVE(0:*), NOPTSUIV(MXSOMM)
      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3)
      DOUBLE PRECISION  XYZ(3), PTXYZD(4,MXSOMM)
      DOUBLE PRECISION  D, DMIN, ARETMX
      INTEGER           NPAV(3), N1PAV(3), N2PAV(3)
C
C     TEMOIN D'IDENTIFICATION DU CENTRE DE L'ICOSAEDRE AVEC UN AUTRE SOMMET
      INTEGER           MODIF13
      DATA              MODIF13 / 0 /
      SAVE              MODIF13
C
C     LE NUMERO EN X Y Z DES PAVES SUSCEPTIBLES DE CONTENIR CE POINT XYZ
      DO K=1,3
C        RECHERCHE DES INDICES DU PAVAGE POUVANT CONTENIR LE SOMMET
         INDICE = INT( ( XYZ(K) - HEXAPAVE(K,1) ) * ECHPAV(K) )
         NBI    =  NBIPAV(K)-1
         IF( INDICE .LE. 0 ) THEN
            NPAV(K)  = 0
            N1PAV(K) = 0
            N2PAV(K) = MIN( 1, NBI )
         ELSE IF( INDICE .GE. NBI ) THEN
            N1PAV(K) = MAX( NBI, NBIPAV(K)-2 )
            N2PAV(K) = NBI
            NPAV(K)  = N2PAV(K)
         ELSE
            N1PAV(K) = INDICE - 1
            NPAV(K)  = INDICE
            N2PAV(K) = INDICE + 1
         ENDIF
      ENDDO
C
C     PARCOURS DES PAVES POSSIBLES
      NSMIN = 0
      DMIN  = 1D111
      DO NZ = N1PAV(3), N2PAV(3)
         MZ = NZ * NBIPAV(2)
         DO NY = N1PAV(2), N2PAV(2)
            MY = ( NY + MZ ) * NBIPAV(1)
            DO NX = N1PAV(1), N2PAV(1)
C
C              LE NO DU PAVE >=0
               NUPAVE = NX + MY
C
C              LE PREMIER SOMMET DU PAVE NUPAVE
               NOSOMM = N1SPAVE( NUPAVE )
C
 10            IF( NOSOMM .GT. 0 ) THEN
C                 LE SOMMET NOSOMM EXISTE : RECHERCHE DU SOMMET LE PLUS PROCHE
                  D = ( PTXYZD(1,NOSOMM)-XYZ(1) ) ** 2
     %              + ( PTXYZD(2,NOSOMM)-XYZ(2) ) ** 2
     %              + ( PTXYZD(3,NOSOMM)-XYZ(3) ) ** 2
                  IF( D .LT. DMIN ) THEN
                     DMIN  = D
                     NSMIN = NOSOMM
                  ENDIF
C                 PASSAGE AU SOMMET SUIVANT DU PAVE
                  NOSOMM = NOPTSUIV( NOSOMM )
                  GOTO 10
               ENDIF
C
            ENDDO
         ENDDO
      ENDDO
C
      IF( NSMIN .GT. 0 ) THEN
C
C        NSMIN EST LE SOMMET LE PLUS PROCHE DE XYZ
C        EST IL ASSEZ PROCHE DE XYZ POUR L'IDENTIFIER?
         NOSOMM = NSMIN
         IF( NOSOMM .NE. NUCENTR .OR. MODIF13 .NE. 0 ) THEN
C
C           NOSOMM N'EST PAS LE CENTRE DE L'ICOSAEDRE ENGLOBANT ELARGI
            CALL XYZIDED( XYZ, PTXYZD(1,NOSOMM), IDENTQ )
            IF( IDENTQ .EQ. 0 ) GOTO 30
C
         ELSE
C
C           NOSOMM EST LE CENTRE DE L'ICOSAEDRE ENGLOBANT ELARGI
C           CRITERES D'IDENTIFICATION BEAUCOUP PLUS LACHE POUR
C           QUE CE CENTRE DEVIENNE LE POINT
            D = 0D0
            DO K=1,3
               D = D + ( PTXYZD(K,NUCENTR) - XYZ( K ) ) **2
            ENDDO
            IF ( D .GT. ARETMX**2 ) GOTO 30
C
C           LE CENTRE DE L'ICOSAEDRE (SOMMET NUCENTR de PTXYZD)
C           DEVIENT LE POINT XYZ
            WRITE(IMPRIM,*) 'LE CENTRE DE L''ICOSAEDRE',
     %                      (PTXYZD(K,NUCENTR),K=1,3)
            WRITE(IMPRIM,*) ' DEVIENT LE POINT',(XYZ(K),K=1,3)
            MODIF13 = 1
            DO K=1,3
               PTXYZD(K,NUCENTR) = XYZ(K)
            ENDDO
            PTXYZD(4,NUCENTR) = ARETMX
            NOSOMM = NUCENTR
C
         ENDIF
C
C        LES 2 SOMMETS NOSOMM ET XYZ SONT IDENTIQUES
CCCC       AFFICHAGE SI LE 4-EME CHIFFRE SIGNIFICATIF EST DIFFERENT
CCC        IF( ABS(PTXYZD(1,NOSOMM)-XYZ(1)).GT.1D-4*ABS(XYZ(1)) .OR.
CCC     %      ABS(PTXYZD(2,NOSOMM)-XYZ(2)).GT.1D-4*ABS(XYZ(2)) .OR.
CCC     %      ABS(PTXYZD(3,NOSOMM)-XYZ(3)).GT.1D-4*ABS(XYZ(3)))THEN
CCC
            WRITE(IMPRIM,10030) (PTXYZD(K,NOSOMM),K=1,3),
     %                          (XYZ(K),K=1,3),NOSOMM
10030 FORMAT(' REMARQUE  :  SOMMET=',3G15.7/
     %       ' IDENTIFIE AU SOMMET=',3G15.7,' NUMERO:',I8/)
CCC
CCC        ENDIF
         GOTO 9900
      ENDIF
C
C     SOMMET NON IDENTIFIE. AJOUT DE CE SOMMET DANS PTXYZD
 30   NBSOM = NBSOM + 1
      IF( NBSOM .GT. MXSOMM ) THEN
C        PAS ASSEZ DE SOMMETS DECLARES DANS PTXYZD
         NOSOMM = 0
         GOTO 9900
      ELSE
         NOSOMM = NBSOM
      ENDIF
C
C     CHAINAGE DU NOUVEAU SOMMET EN DEBUT DE PAVE
      NUPAVE = NPAV(1) + NBIPAV(1) * ( NPAV(2) + NBIPAV(2) * NPAV(3) )
      NOPTSUIV( NOSOMM ) = N1SPAVE( NUPAVE )
      N1SPAVE( NUPAVE ) = NOSOMM
C
C     LES 3 COORDONNEES SONT AJOUTEES DANS PTXYZD(1:4,NOSOMM)
      PTXYZD(1,NOSOMM) = XYZ( 1 )
      PTXYZD(2,NOSOMM) = XYZ( 2 )
      PTXYZD(3,NOSOMM) = XYZ( 3 )
C     LONGUEUR DE L'ARETE MAX ALENTOUR
      PTXYZD(4,NOSOMM) = ARETMX
C
 9900 RETURN
      END
