      SUBROUTINE RSTETO( PTXYZD, NBTERST, NOTERST, NBTESUP, NOTESUP,
     %                   MXTETR, N1TEVI,  NOTETR,  NUDTETR, N1TETS,
     %                   NBFANR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   SUPPRIMER LES NBTESUP TETRAEDRES de NUMERO NOTETR dans NOTESUP
C -----   RESTAURER LES NBTERST TETRAEDRES de NUMERO NOTETR dans NOTERST
C         METTRE A JOUR LES TABLEAUX N1TEVI, NOTETR, N1TETS

C ENTREES:
C --------
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C NBTERST: NOMBRE DE TETRAEDRES A RESTAURER
C NOTERST: NUMERO NOTETR DES NBTERST TETRAEDRES A RESTAURER
C NBTESUP: NOMBRE DE TETRAEDRES A DETRUIRE
C NOTESUP: NUMERO NOTETR DES NBTESUP TETRAEDRES A DETRUIRE
C MXTETR : NOMBRE DE TETRAEDRES DECLARABLES DANS NOTETR
C NUDTETR: PLUS GRAND NUMERO DANS NOTETR DE TETRAEDRE OCCUPE

C MODIFIES:
C ---------
C N1TEVI : NUMERO NOTETR DU PREMIER TETRAEDRE VIDE
C          CHAINGE DES TETRAEDRES VIDE DANS NOTETR(5,*)
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C           1: 123      2: 234      3: 341      4: 412
C N1TETS : N1TETS(I) NUMERO NOTETR D'UN TETRAEDRE AYANT POUR SOMMET I

C SORTIE :
C --------
C NBFANR : NOMBRE DE FACES DE TETRAEDRE OPPOSE NON RETROUVE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & ST PIERRE DU PERRAY  Fevrier 2015
C2345X7..............................................................012
      DOUBLE PRECISION  PTXYZD(4,*)
      INTEGER           NOTERST(NBTERST), NOTESUP(NBTESUP),
     %                  NOTETR(8,MXTETR), N1TETS(*)
      INTEGER           NOSOFA(3,4), NOSOTR(3)
      DATA              NOSOFA / 1,3,2,  2,3,4, 3,1,4, 4,1,2 /

C     SUPPRESSION DES NBTESUP TETRAEDRES NOTESUP
      print*,'rsteto: SUPPRESSION des',NBTESUP,' TETRAEDRES'
      print 10000,(NOTESUP(K),K=1,NBTESUP)
      DO K = NBTESUP, 1, -1
         NT = ABS( NOTESUP( K ) )
         DO M=1,8
            NOTETR(M,NT) = 0
         ENDDO
C        NT DEVIENT LE PREMIER TETRAEDRE VIDE
         NOTETR(5,NT) = N1TEVI
         N1TEVI = NT
      ENDDO

C     RESTAURATION DE N1TETS ET DE LA FACE OPPOSEE DANS NOTETR
C     DES NBTERST TETRAEDRES DU TABLEAU NOTERST
      print*,'rsteto: RESTAURATION des',NBTERST,' TETRAEDRES'
      print 10000,(NOTERST(K),K=1,NBTERST)
10000 FORMAT( 20(I7) )

      DO K = 1, NBTERST

C        NUMERO NOTETR DU TETRAEDRE K A RESTAURER
         NT = ABS( NOTERST( K ) )
         IF( NT .GT. 0 ) THEN

            IF( NOTETR(1,NT) .LT. 0 ) THEN
C              1-ER SOMMET REACTIVE
               NOTETR(1,NT) = - NOTETR(1,NT)
            ENDIF

            IF( NOTETR(1,NT) .GT. 0 ) THEN
               DO L=1,4

C                 MISE A JOUR DE N1TETS DU SOMMET L
                  N1TETS( NOTETR(L,NT) ) = NT

C                 RETROUVER LE NO LOCAL LOP DE LA FACE DANS LE TETRAEDRE
C                 OPPOSE NTOP A LA FACE L DU TETRAEDRE NT
                  NTOP = NOTETR( 4+L, NT )

                  IF( NTOP .GT. 0 ) THEN

C                    LES 3 SOMMETS DE LA FACE L DU TETRAEDRE NT
                     DO M=1,3
                        NOSOTR(M) = NOTETR( NOSOFA(M,L), NT )
                     ENDDO

C                    TRI CROISSANT DES 3 SOMMETS DE LA FACE L
                     CALL TRI3NO( NOSOTR, NOSOTR )

C                    RECHERCHE DE LA FACE NOSOTR DANS CE TETRAEDRE NTOP
                     CALL NO1F1T( NOSOTR, NOTETR(1,NTOP), LOP )

                     IF( LOP .GT. 0 ) THEN
C                       LE TETRAEDRE OPPOSE A LA FACE LOP DE NTOP EST NT
                        NOTETR( 4+LOP, NTOP ) = NT
                     ENDIF

                  ENDIF

               ENDDO
            ENDIF

         ENDIF

      ENDDO


C     MISE A JOUR DES TETRAEDRES OPPOSES DANS UNE LISTE DE TETRAEDRES
      CALL MJOPTE( NBTERST, NOTERST, N1TETS, NOTETR, NUDTETR,
     %             N1TEVI,  PTXYZD, NBFANR )

      IF( NBFANR .GT. 0 ) THEN
         PRINT*,'rsteto: RESTAURATION des',NBTERST,' TETRAEDRES avec',
     %           NBFANR,' TETRAEDRES de FACE OPPOSEE NON RETROUVES'
      ENDIF

C     VERIFIER L'ABSENCE DE TETRAEDRE OPPOSE NEGATIF (INCONNU)
C     VERIFIER L'ABSENCE DE TETRAEDRES OPPOSES DOUBLES
C     VERIFIER L'ABSENCE DE FACE COMMUNE A AU MOINS 3 TETRAEDRES
C     VERIFIER L'OPPOSITION DES TETRAEDRES 
C     DANS UNE LISTE DE NBTETRA TETRAEDRES
      CALL VEOPTE( NBTERST, NOTERST, NOTETR, PTXYZD, NBFANR )

      IF( NBFANR .GT. 0 ) THEN
         PRINT*,'rsteto: Probleme: La VERIFICATION des',NBTERST,
     %          ' TETRAEDRES RESTAURES a TROUVE',
     %           NBFANR,' TETRAEDRES de FACE OPPOSEE NON RETROUVES'
      ENDIF

      RETURN
      END
