      SUBROUTINE SBOT( INHEXA, HEXA,   NUOT,
     %                 MXARBO, LARBRO, MXARBT, LARBRT, NUOTPT,
     %                 NBSOMM, MXSOMM, PTXYZD,
     %                 LAVIDE, MXARET, LARETE,
     %                 IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SUBDIVISION D'UN OT EN 14 OU 5 FILS SELON SON TYPE
C -----    OCTAEDRE OU TETRAEDRE
C
C ENTREES:
C --------
C INHEXA : =0 SUBDIVISER SYSTEMATIQUEMENT L'OCTAEDRE OU TETRAEDRE
C          =1 SUBDIVISER SEULEMENT SI TOUS LES MILIEUX DES ARETES
C             SONT INTERNES A L'HEXAEDRE ENGLOBANT LES POINTS INITIAUX
C HEXA   : MIN ET MAX DES 3 COORDONNEES D'UN HEXAEDRE ENGLOBANT
C          LES POINTS DE L'OBJET A MAILLER
C NUOT   : NUMERO DE L'OCTAEDRE A DECOMPOSER
C MXARBO : NOMBRE MAXIMAL D'OCTAEDRES DANS LARBRO
C MXARBT : NOMBRE MAXIMAL DE TETRAEDRES DANS LARBRT
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C MXARET : NOMBRE MAXIMAL D'ARETES DES OT
C
C ENTREES ET SORTIES:
C -------------------
C NBSOMM : NOMBRE ACTUEL DE POINTS DECLARES DANS PTXYZD
C LAVIDE : PREMIERE ARETE VIDE POSSIBLE DANS LARETE
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(0,0) : NO DU 1-ER OCTAEDRE VIDE DANS LARBRO
C      LARBRO(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRO (ICI -1:20)
C      LARBRO(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRO
C                    (ICI = MXARBO)
C
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT
C
C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 0 A 4 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C
C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT
C NUOTPT : NUMERO D'OT (>0 SI LARBRO, <0 SI LARBRT) DE CHAQUE POINT PTXYZD
C
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C NBSOMM : LE DERNIER POINT AJOUTE DANS PTXYZD
C LAVIDE : PREMIERE ADRESSE LARETE A EXPLORER POUR TROUVER UNE ARETE VIDE
C LARETE : TABLEAU DE HACHAGE DES ARETES DES OT
C          LARETE(1,J) = SOMMET 1 DANS PTXYZD
C          LARETE(2,J) = SOMMET 2 DANS PTXYZD
C          LARETE(3,J) = NUMERO DANS LARETE DE L'ARETE SUIVANTE
C          LARETE(4,J) = MILIEU DE L'ARETE DANS PTXYZD
C          HACHAGE(NS1,NS2) = (NS1 + NS2) MODULO MXARET + 1
C
C SORTIES:
C --------
C IERR   : 0  SI PAS D'ERREUR,  >0 SI ERREUR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   NOVEMBRE 1992
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY     MARS 2016
C2345X7..............................................................012
      REAL              HEXA(6,2)
      INTEGER           LARBRO(-1:20,0:MXARBO),
     %                  LARBRT(-1:9 ,0:MXARBT),
     %                  NUOTPT(1:MXSOMM),
     %                  LARETE(1:4 ,1:MXARET)
      DOUBLE PRECISION  PTXYZD(4,MXSOMM)
C
      IF( NUOT .GT. 0 ) THEN
C        OCTAEDRE
         CALL SBOCTA( INHEXA, HEXA,   NUOT,
     %                MXARBO, LARBRO, MXARBT, LARBRT, NUOTPT,
     %                NBSOMM, MXSOMM, PTXYZD,
     %                LAVIDE, MXARET, LARETE,
     %                IERR )
      ELSE
C        TETRAEDRE
         NTYOT = LARBRT( 0, -NUOT )  / 100
         CALL SBTETR( INHEXA, HEXA,   NTYOT,  NUOT,
     %                MXARBO, LARBRO, MXARBT, LARBRT, NUOTPT,
     %                NBSOMM, MXSOMM, PTXYZD,
     %                LAVIDE, MXARET, LARETE,
     %                IERR )
      ENDIF

      RETURN
      END
