      SUBROUTINE SBTETR( INHEXA, HEXA,   NOTYTE, NUMTET,
     %                   MXARBO, LARBRO, MXARBT, LARBRT, NUOTPT,
     %                   NBSOMM, MXSOMM, PTXYZD,
     %                   LAVIDE, MXARET, LARETE, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   CREATION DE L'OCTAEDRE ET DES 4 TETRAEDRES DU TETRAEDRE NUMTET
C -----   REARRANGEMENT DES POINTS STOCKES DANS LE TETRAEDRE
C
C ENTREES:
C --------
C INHEXA : =0 SUBDIVISER SYSTEMATIQUEMENT LE TETRAEDRE
C          =1 SUBDIVISER SEULEMENT SI TOUS LES MILIEUX DES ARETES
C             SONT INTERNES A L'HEXAEDRE ENGLOBANT LES POINTS INITIAUX
C HEXA   : MIN ET MAX DES 3 COORDONNEES D'UN HEXAEDRE ENGLOBANT
C          LES POINTS DE L'OBJET A MAILLER
C NOTYTE : NUMERO DU TYPE DU TETRAEDRE A SUBDIVISER (1 OU 2)
C NUMTET : NUMERO (<0) LARBRT DU TETRAEDRE A DECOMPOSER
C MXARBO : NOMBRE MAXIMAL D'OCTAEDRES DANS LARBRO
C MXARBT : NOMBRE MAXIMAL DE TETRAEDRES DANS LARBRT
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C MXARET : NOMBRE MAXIMAL D'ARETES DES OT
C
C ENTREES ET SORTIES:
C -------------------
C NBSOMM : NOMBRE ACTUEL DE POINTS DECLARES DANS PTXYZD
C LAVIDE : PREMIERE ARETE VIDE POSSIBLE DANS LARETE
C
C ATTENTION : EN SORTIE LES NUMEROS DES POINTS DU TETRAEDRE SONT
C             REDISTRIBUES DANS LES FILS
C
C LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(0,0) : NO DU 1-ER OCTAEDRE VIDE DANS LARBRO
C      LARBRO(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRO (ICI -1:20)
C      LARBRO(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRO
C                    (ICI = MXARBO)
C
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C   SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (<0 LARBRT, >0 LARBRO) DES 14 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C   SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT
C
C LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 0 A 4 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C
C   SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (<0 LARBRT, >0 LARBRO) DES 5 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C   SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT
C NUOTPT : NUMERO D'OT (>0 SI LARBRO, <0 SI LARBRT) DE CHAQUE POINT PTXYZD
C
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C NBSOMM : LE DERNIER POINT AJOUTE DANS PTXYZD
C
C AUXILIAIRES:
C ------------
C LARETE : TABLEAU DE HACHAGE DES ARETES DES OT
C          LARETE(1,J) = SOMMET 1 DANS PTXYZD
C          LARETE(2,J) = SOMMET 2 DANS PTXYZD
C          LARETE(3,J) = NUMERO DANS LARETE DE L'ARETE SUIVANTE
C          LARETE(4,J) = MILIEU DE L'ARETE DANS PTXYZD
C          HACHAGE(NS1,NS2) = (NS1 + NS2) MODULO MXARET + 1
C LAVIDE : PREMIERE ADRESSE LARETE A EXPLORER POUR TROUVER UNE ARETE VIDE
C
C SORTIES:
C --------
C IERR   : 0  SI PAS D'ERREUR,  >0 SI ERREUR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   NOVEMBRE 1992
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY     MARS 2016
C2345X7..............................................................012
      include"./incl/gsmenu.inc"
      REAL              HEXA(6,2)
      INTEGER           LARBRO(-1:20,0:MXARBO),
     %                  LARBRT(-1:9 ,0:MXARBT),
     %                  NUOTPT(1:MXSOMM),
     %                  LARETE(1:4 ,1:MXARET)
      DOUBLE PRECISION  PTXYZD(4,MXSOMM), PTM(3)
      INTEGER           NS(2),NOPOIN(10),NOPTIN(5)
      EQUIVALENCE      (NS(1),NS1),(NS(2),NS2)

      INTEGER           NOSOARTE(2,6)
      DATA              NOSOARTE / 1,2, 2,3, 3,1, 1,4, 2,4, 3,4 /

      NUMTE = ABS( NUMTET )

      IF( INHEXA .EQ. 0 ) GOTO 100

C     LE MILIEU DES 6 ARETES DU TETRAEDRE SONT ELLES INTERNES
C     A L'HEXAEDRE ENGLOBANT?
      DO I=1,6

C        LES NUMEROS PTXYZD DES 2 SOMMETS DE L'ARETE I
         NS1 = LARBRT( 5+NOSOARTE(1,I), NUMTE )
         NS2 = LARBRT( 5+NOSOARTE(2,I), NUMTE )

C        XYZ DU POINT MILIEU DE L'ARETE I
         DO J=1,3
            PTM(J) = (PTXYZD(J,NS1) + PTXYZD(J,NS2)) * 0.5D0
         ENDDO

C        EST IL EN DEHORS DE L'HEXAEDRE ENGLOBANT LES POINTS?
         IF( PTM(1) .LT. HEXA(1,1) .OR. PTM(1) .GT. HEXA(1,2) .OR.
     %       PTM(2) .LT. HEXA(2,1) .OR. PTM(2) .GT. HEXA(2,2) .OR.
     %       PTM(3) .LT. HEXA(3,1) .OR. PTM(3) .GT. HEXA(3,2) ) THEN
C           OUI: PAS DE SUBDIVISION
            RETURN
         ENDIF

      ENDDO

C     PROTECTION DES EVENTUELS 5 POINTS INTERNES AU TETRAEDRE
 100  IF( LARBRT(1,NUMTE) .LT. 0 ) THEN
         DO I=1,5
            NOPTIN( I ) = ABS( LARBRT( I, NUMTE ) )
         ENDDO
      ELSE
         DO I=1,5
            NOPTIN( I ) = 0
         ENDDO
      ENDIF

C     GENERATION DU MILIEU DES 6 ARETES DU TETRAEDRE
      DO I=1,6

C        LES NUMEROS PTXYZD DES 2 SOMMETS DE L'ARETE I
         NS1 = LARBRT( 5+NOSOARTE(1,I), NUMTE )
         NS2 = LARBRT( 5+NOSOARTE(2,I), NUMTE )

         IF( NS1 .GT. NS2 ) THEN
            NOAR = NS1
            NS1  = NS2
            NS2  = NOAR
         ENDIF

C        HACHAGE DE L'ARETE POUR LA RETROUVER
         CALL HACHAG( 2, NS, 4, MXARET, LARETE, 3,  LAVIDE, NOAR )
C
         IF( NOAR .EQ. 0 )  THEN
C           SATURATION DES ARETES DE LARETE
            NBLGRC(NRERR) = 1
            KERR(1) ='SP sbtetr: TABLEAU LARETE SATURE'
            CALL LEREUR
            IERR = 3
            RETURN
         ENDIF
C
         IF( NOAR .LT. 0 ) THEN
C           L'ARETE EST CREEE . CREATION DU POINT PTXYZD MILIEU
            IF( NBSOMM .GT. MXSOMM ) THEN
C              SATURATION DES POINTS DE PTXYZD
               NBLGRC(NRERR) = 1
               KERR(1) ='SP sbtetr: TABLEAU PTXYZD SATURE NBSOMM=      '
               WRITE(KERR(1)(41:52),'(I12)') NBSOMM
               CALL LEREUR
               IERR = 2
               RETURN
            ENDIF
            NBSOMM = NBSOMM + 1
C           LE NUMERO D'UN OT CONTENANT CE MILIEU
            NUOTPT( NBSOMM ) = -NUMTE
            DO J=1,3
               PTXYZD(J,NBSOMM) = (PTXYZD(J,NS1) + PTXYZD(J,NS2)) *0.5D0
            ENDDO
C           AJOUT DU MILIEU DANS LARETE
            LARETE(4,-NOAR) = NBSOMM
            NOPOIN(4+I) = NBSOMM
         ELSE
C           ARETE ET MILIEU EXISTENT
            NOPOIN(4+I) = LARETE(4,NOAR)
         ENDIF
      ENDDO
C
C     LES 4 SOMMETS
      DO I=1,4
         NOPOIN(I) = LARBRT(5+I,NUMTE)
      ENDDO
C
C     CREATION DE L'OCTAEDRE FILS
C     ---------------------------
      IF( NOTYTE .EQ. 1 ) THEN
         CALL CROCTA( NOPOIN(10), NOPOIN(7), NOPOIN(8), NOPOIN(9),
     %                NOPOIN( 6), NOPOIN(5),
     %               -NUMTE, 1, LARBRO, NUOTCR, IERR )
      ELSE
         CALL CROCTA( NOPOIN(10), NOPOIN(6), NOPOIN(7), NOPOIN(8),
     %                NOPOIN( 9), NOPOIN(5),
     %               -NUMTE, 1, LARBRO, NUOTCR, IERR )
      ENDIF
      IF( IERR .NE. 0 ) RETURN
      LARBRT(1,NUMTE) = NUOTCR
C
C     LES 4 FILS TETRAEDRES DE TYPE NOTYTE
C     ------------------------------------
      CALL CRTETR( NOPOIN(1), NOPOIN(5), NOPOIN(7), NOPOIN(8),
     %            -NUMTE, 2, NOTYTE, LARBRT, NUOTCR, IERR )
      IF( IERR .NE. 0 ) RETURN
      LARBRT(2,NUMTE) = NUOTCR
C
      CALL CRTETR( NOPOIN(5), NOPOIN(2), NOPOIN(6), NOPOIN(9),
     %            -NUMTE, 3, NOTYTE, LARBRT, NUOTCR, IERR )
      IF( IERR .NE. 0 ) RETURN
      LARBRT(3,NUMTE) = NUOTCR
C
      CALL CRTETR( NOPOIN(7), NOPOIN(6), NOPOIN(3), NOPOIN(10),
     %            -NUMTE, 4, NOTYTE, LARBRT, NUOTCR, IERR )
      IF( IERR .NE. 0 ) RETURN
      LARBRT(4,NUMTE) = NUOTCR
C
      CALL CRTETR( NOPOIN(8), NOPOIN(9), NOPOIN(10), NOPOIN(4),
     %            -NUMTE, 5, NOTYTE, LARBRT, NUOTCR, IERR )
      IF( IERR .NE. 0 ) RETURN
      LARBRT(5,NUMTE) = NUOTCR
C
C     REDISTRIBUTION DES POINTS INTERNES INITIAUX DANS LES FILS
C     ---------------------------------------------------------
      DO 200 N=1,5
         NP = NOPTIN( N )
         IF( NP .LE. 0 ) RETURN
C        RECHERCHE DE L'OT FEUILLE CONTENANT LE POINT NP
C        A PARTIR DU TETRAEDRE PERE
         CALL NOTFPT( PTXYZD(1,NP), PTXYZD, -NUMTE, LARBRO, LARBRT,
     %                NUOTFE )
         IF( NUOTFE .GT. 0 ) THEN
C           OCTAEDRE
            DO I=1,14
               IF( LARBRO(I,NUOTFE) .EQ. 0 ) THEN
C                 NON : AJOUT DU POINT
                  LARBRO(I,NUOTFE) = -NP
                  NUOTPT(NP) = NUOTFE
                  GOTO 200
               ENDIF
            ENDDO
         ELSE
C           TETRAEDRE
            DO I=1,5
               IF( LARBRT(I,-NUOTFE) .EQ. 0 ) THEN
C                 AJOUT DU POINT
                  LARBRT(I,-NUOTFE) = -NP
                  NUOTPT(NP) = NUOTFE
                  GOTO 200
               ENDIF
            ENDDO
         ENDIF
 200  CONTINUE

      RETURN
      END
