      SUBROUTINE SGIARET( LP1SGI, LCHSGI, MXSGI,   NSTSGI,
     %                    MXARET, NBARET, LCHARET  )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  CONSTRUIRE A PARTIR DES SGI LE DEBUT D'UN CONTOUR FERME D'ARETES
C -----
C ENTREES:
C --------
C LP1SGI : POINTEUR SUR LE 1-ER SEGMENT INTERSECTION (SGI)
C LCHSGI : NUMERO DU SGI et CHAINAGE SUR LE SUIVANT
C          LCHSGI(2,K) = SUIVANT DE K DANS LCHSGI
C MXSGI  : NOMBRE MAXIMAL DE SGI DECLARABLES DANS NSTSGI
C NSTSGI : NUMERO DANS XYZPTA DES 2 POINTS EXTREMITES DU SGI
C          NUMERO DU TRIANGLE DANS NUSTS1 ET DANS NUSTS2
C MXARET : NOMBRE MAXIMAL D'ARETES DECLARABLES DANS LCHARET
C
C MODIFIES:
C----------
C NBARET : NOMBRE D'ARETES D'UN CF ET DERNIERE ARETE CHAINEE DANS LCHARET
C          LE CONTROLE DE DEBORDEMENT DE NBARET DOIT ETRE FAIT
C          AVANT APPEL DU SP SGIARET
C LCHARET: (3,MXARET) NUMERO DANS XYZST DU SOMMET 1 ET 2 DU SEGMENT,
C          CHAINAGE SUR LE SUIVANT
C          TABLEAU CLONE DU CF POUR SA TRIANGULATION
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC & St Pierre du Perray  Octobre 2011
C2345X7..............................................................012
      INTEGER  LP1SGI, LCHSGI(2,*), NSTSGI(4,MXSGI), LCHARET(3,MXARET)
C
C     LA PREMIERE ARETE EST CELLE DU SGI
      LCH = LP1SGI
C     NUMERO DANS LCHSGI DU SGI
 10   NSGI = LCHSGI( 1, LCH )
C     NSG1 NUMERO DU SOMMET 1 DU SGI DANS XYZPTA
      NSG1 = NSTSGI( 1, NSGI )
C     NSG2 NUMERO DU SOMMET 2 DU SGI DANS XYZPTA
      NSG2 = NSTSGI( 2, NSGI )
C
C     AJOUT DE L'ARETE DANS LE MEME ORDRE QUE LES SGI
C     LE CONTROLE DE DEBORDEMENT DE NBARET DOIT ETRE FAIT AVANT APPEL DU SP
      NBARET = NBARET + 1
C     NUMERO XYZPTA SOMMET 1 DE L'ARETE
      LCHARET(1,NBARET) = NSG1
C     NUMERO XYZPTA SOMMET 2 DE L'ARETE
      LCHARET(2,NBARET) = NSG2
C     CHAINAGE LCHARET SUR L'ARETE SUIVANTE
      LCHARET(3,NBARET) = NBARET + 1
C
C     NUMERO DANS LCHSGI DU SGI SUIVANT
      LCH = LCHSGI( 2, LCH )
      IF( LCH .GT. 0 ) GOTO 10
C
      RETURN
      END
