      SUBROUTINE SGICONT( MXCHSGI, LCHSGI, MXSGI, NSTSGI,
     %                    L1CHSGI, NUSU,   LCH0 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    REORDONNER LES SGI CHAINES POUR EN FAIRE UNE SUITE
C -----    CONTINUE D'ARETES A PARTIR DU SOMMET NUSU(1) (SIMPLE OU NON)
C
C ENTREES:
C --------
C MXCHSGI: NOMBRE MAXIMAL DE SGI DECLARABLES DANS LCHSGI
C MXSGI  : NOMBRE MAXIMAL DE SGI DECLARABLES DANS NSTSGI
C
C MODIFIES:
C----------
C LCHSGI : NUMERO DU SGI et CHAINAGE SUR LE SUIVANT
C NSTSGI : NUMERO DANS XYZPTA DES 2 POINTS EXTREMITES DU SEGMENT INTERSECTION
C          NUMERO DU TRIANGLE DANS NUSTS1 ET DANS NUSTS2
C L1CHSGI: POINTEUR SUR 1-ER SEGMENT INTERSECTION DU CHAINAGE
C
C SORTIE :
C --------
C NUSU   : NUMERO DES 2 SOMMETS EXTREMITES DE LA LIGNE CONTINUE DES SGI
C LCH0   : NUMERO DANS LCHSGI DU DERNIER SGI (DE SOMMET FINAL NUSU(2))
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC& St Pierre du Perray SEPTEMBRE 2011
C2345X7..............................................................012
      INTEGER   NSTSGI(4,MXSGI), LCHSGI(2,MXCHSGI)
      INTEGER   NUSU(2)
C               NUMERO DES SOMMETS UNIQUES DES SGI D'UN TRIANGLE
C              (CAS GENERAL=2, SI >2 NON TRAITE ICI... A FAIRE)
C
C     LES SGI SONT REORDONNES POUR FORMER UNE SUITE CONTINUE D'ARETES
C     RECHERCHE DU SGI DE SOMMET NUSU(1) NUMERO DU 1-ER SOMMET DES SGI
      NSG0 = NUSU(1)
C
      LCH0 = 0
      LCH  = L1CHSGI
C
C     NUMERO DANS LCHSGI DU SGI
 10   NSGI = LCHSGI( 1, LCH )
C     NSG1 NUMERO DU SOMMET 1 DU SGI DANS XYZPTA
      NSG1 = NSTSGI( 1, NSGI )
C     NSG2 NUMERO DU SOMMET 2 DU SGI DANS XYZPTA
      NSG2 = NSTSGI( 2, NSGI )
C
      IF( NSG1 .NE. NSG0 .AND. NSG2 .NE. NSG0 ) THEN
C        NSG1 et NSG2 DIFFERENTS DE NSG0
         LCH0 = LCH
         LCH  = LCHSGI( 2, LCH )
         IF( LCH .GT. 0 ) GOTO 10
C        IMPOSSIBLE D'ARRIVER APRES LE IF CAR NUSU(1) EXISTE DANS LES SGI
      ENDIF
C
      IF( NSG2 .EQ. NSG0 ) THEN
C        NSG2=NSG0  => PERMUTATION NSG1 ET NSG2 SOMMETS DU SGI
         NSTSGI( 1, NSGI ) = NSG2
         NSTSGI( 2, NSGI ) = NSG1
         N    = NSG1
         NSG1 = NSG2
         NSG2 = N
      ENDIF
C
C     SI LE PREMIER SGI  CONTIENT NUSU(1) => RIEN A FAIRE
      IF( LCH0 .EQ. 0 ) GOTO 20
C
C     NUSU(1) EST SUR UN SGI QUI N'EST PAS LE PREMIER
      LCH1 = LCH
C
C     RECHERCHE DU DERNIER SGI ACTUEL
 15   LCHDER = LCH1
      LCH1   = LCHSGI( 2, LCH1 )
      IF( LCH1 .GT. 0 ) GOTO 15
C
C     LE DERNIER A POUR SUIVANT LE PREMIER ACTUEL
      LCHSGI( 2, LCHDER ) = L1CHSGI
C
C     LE PRECEDENT DU PREMIER SGI DEVIENT LE DERNIER SGI
      LCHSGI( 2, LCH0 ) = 0
C
C     LE SGI DE SOMMET 1 NUSU(1) EST LCH ET DEVIENT LE PREMIER DES SGI
      L1CHSGI = LCH
C
C     ICI, LE SGI DE SOMMET 1 NUSU(1) EST EN TETE DES SGI
C     CHAINAGE DES SGI EN CONTINU A PARTIR DE CE SOMMET NSG1=NUSU(1)
C     RECHERCHE DE NSG2 LE SECOND SOMMET DU SGI PARMI LES AUTRES SGI
 20   LCH00 = LCH
      NSG00 = NSG2
C
C     PARCOURS DES SGI RESTANTS POUR TROUVER NSG00
      LCH0 = LCH
      LCH  = LCHSGI( 2, LCH )
C
 30   IF( LCH .GT. 0 ) THEN
C        NUMERO DANS LCHSGI DU SGI
         NSGI = LCHSGI( 1, LCH )
C        NSG1 NUMERO DU SOMMET 1 DU SGI DANS XYZPTA
         NSG1 = NSTSGI( 1, NSGI )
C        NSG2 NUMERO DU SOMMET 2 DU SGI DANS XYZPTA
         NSG2 = NSTSGI( 2, NSGI )
C
         IF( NSG1 .NE. NSG00 .AND. NSG2 .NE. NSG00 ) THEN
C           NSG1 et NSG2 DIFFERENTS DE NSG00
            LCH0 = LCH
            LCH  = LCHSGI( 2, LCH )
            GOTO 30
         ENDIF
C
         IF( NSG2 .EQ. NSG00 ) THEN
C           NSG2=NSG0
C           PERMUTATION NSG1 ET NSG2 SOMMETS DU SGI
            NSTSGI( 1, NSGI ) = NSG2
            NSTSGI( 2, NSGI ) = NSG1
            N    = NSG1
            NSG1 = NSG2
            NSG2 = N
         ENDIF
C
C        ICI NSG1=NSG00 DE LCH  CHAINAGE A LA SUITE DE LCH00
         IF( LCHSGI( 2, LCH00 ) .EQ. LCH ) GOTO 20
C
         LC1 = LCHSGI( 2, LCH00 )
         LC2 = LCHSGI( 2, LCH )
         LCHSGI( 2, LCH00 ) = LCH
         LCHSGI( 2, LCH   ) = LC1
         LCHSGI( 2, LC1   ) = LC2
         IF( LC1 .GT. 0 ) THEN
C           ENCORE UN SGI A TRAITER
            GOTO 20
         ENDIF
      ENDIF
C
C     ICI TOUS LES SGI SONT ORDONNES CONTINUS DE NUSU(1) A NUSU(2)
C     (LC=0 et NSG2=NUSU(2))
      NSGI = LCHSGI( 1, LCH0 )
      NUSU(2) = NSTSGI( 2, NSGI )
C
C     AFFICHAGE DES SGI CONTINUS
      print *
      print *,'sgicont: NUSU(1)=',NUSU(1),'  NUSU(2)=',NUSU(2)
      CALL SGIIMPR( L1CHSGI, LCHSGI, NSTSGI )
C
      RETURN
      END
