      SUBROUTINE SGICONT0( MXCHSGI, LCHSGI, MXSGI, NSTSGI,
     %                     L1CHSGI, NUSU,   LCH0 )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    REORDONNER LES SGI CHAINES POUR EN FAIRE UNE SUITE
C -----    CONTINUE D'ARETES A PARTIR D'UN SOMMET APPARTENANT A UN SEUL SGI
C
C ENTREES:
C --------
C MXCHSGI: NOMBRE MAXIMAL DE SGI DECLARABLES DANS LCHSGI
C MXSGI  : NOMBRE MAXIMAL DE SGI DECLARABLES DANS NSTSGI
C
C MODIFIES:
C----------
C LCHSGI : NUMERO DU SGI et CHAINAGE SUR LE SUIVANT
C NSTSGI : NUMERO DANS XYZPTA DES 2 POINTS EXTREMITES DU SEGMENT INTERSECTION
C          NUMERO DU TRIANGLE DANS NUSTS1 ET DANS NUSTS2
C L1CHSGI: POINTEUR SUR 1-ER SEGMENT INTERSECTION DU CHAINAGE
C
C SORTIE :
C --------
C NUSU   : NUMERO DES 2 SOMMETS EXTREMITES DE LA LIGNE CONTINUE DES SGI
C LCH0   : NUMERO DANS LCHSGI DU DERNIER SGI (DE SOMMET FINAL NUSU(2))
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC & St Pierre du Perray  Octobre 2011
C2345X7..............................................................012
      INTEGER   NSTSGI(4,MXSGI), LCHSGI(2,MXCHSGI)
      INTEGER   NUSU(2)
C               NUMERO DES SOMMETS UNIQUES DES SGI D'UN TRIANGLE
C              (CAS GENERAL=2, SI >2 NON TRAITE ICI... A FAIRE)
C
C     RECHERCHE D'UN SOMMET APPARTENANT A UN SEUL SGI
      LCH0  = L1CHSGI
 1    NSGI0 = LCHSGI( 1, LCH0 )
      K = 0
C     NSG1 NUMERO DU SOMMET 1 DU SGI DANS XYZPTA
 5    IF( K .GE. 2 ) THEN
C        PASSAGE AU SGI SUIVANT
         LCH0 = LCHSGI( 2, LCH0 )
         IF( LCH0 .GT. 0 ) GOTO 1
         print*,'PB sgicont0: PAS DE SOMMET UNIQUE POUR LES SGI CHAINES'
      ELSE
         K = K + 1
C        NSG0 NUMERO DU SOMMET K DU SGI DANS XYZPTA
         NSG0 = NSTSGI( K, NSGI0 )
      ENDIF
C
C     PARCOURS DES SOMMETS DES SGI POUR COMPTER LE NOMBRE DE NSG0
      NB  = 0
      LCH = L1CHSGI
C
 8    NSGI = LCHSGI( 1, LCH )
C     NSG1 NUMERO DU SOMMET 1 DU SGI DANS XYZPTA
      NSG1 = NSTSGI( 1, NSGI )
C     NSG2 NUMERO DU SOMMET 2 DU SGI DANS XYZPTA
      NSG2 = NSTSGI( 2, NSGI )
      IF( NSG0 .EQ. NSG1 .OR. NSG0 .EQ. NSG2 ) THEN
         IF( NB .EQ. 1 ) GOTO 5
         NB = NB + 1
      ENDIF
C     LE SUIVANT
      LCH  = LCHSGI( 2, LCH )
      IF( LCH .GT. 0 ) GOTO 8
C
C     NSG0 EST UN SOMMET UNIQUE => NUMERO DU 1-ER SOMMET DES SGI
      NUSU(1) = NSG0
      print *,'sgicont0: 1-ER SOMMET UNIQUE NUSU(1)=',NUSU(1),
     %        ' NSGI0=',NSGI0
C
C     REORDONNER LES SGI EN CONTINUE A PARTIR DU SOMMET NUSU(1)
      CALL SGIIMPR( L1CHSGI, LCHSGI, NSTSGI )
      CALL SGICONT( MXCHSGI, LCHSGI, MXSGI, NSTSGI,
     %              L1CHSGI, NUSU,   LCH0 )
C
      RETURN
      END
