      SUBROUTINE SGICOURB2( NT1,    NUSTS1, XYZS1,   XYZPTA,
     %                      LCHSGI, NSTSGI,
     %                      NBFCB,  L1COURB, NUSUCB, NUARCB )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    DECOUPER EN PLUSIEURS COURBES CHAQUE COURBE AYANT AU MOINS
C -----    UN SOMMET DOUBLE SUR DES ARETES DU TRIANGLE
C
C ENTREES:
C --------
C NT1    : NUMERO DU TRIANGLE
C NUSTS1 : (4,NBTRS1) NUMERO DANS XYZS1 DES 3 SOMMETS + 0 EN POSITION 4
C XYZS1  : 3 XYZ DES NBS1 SOMMETS DE LA SURFACE 1
C XYZPTA : 3 XYZ DES SOMMETS AJOUTES PAR LES SGI
C
C MODIFIES:
C----------
C LCHSGI : LCHSGI(1,.) NUMERO DU SGI DANS NSTSGI
C          LCHSGI(2,.) CHAINAGE SUR LE SGI SUIVANT DANS LCHSGI
C NSTSGI : NSTSGI(1,.) NUMERO DANS XYZPTA DU PREMIER POINT DU SGI
C          NSTSGI(2,.) NUMERO DANS XYZPTA DU SECOND  POINT DU SGI
C          NSTSGI(3,.) NUMERO DU TRIANGLE DANS LA TRIANGULATION NUSTS1
C          NSTSGI(4,.) NUMERO DU TRIANGLE DANS LA TRIANGULATION NUSTS2
C
C SORTIES:
C --------
C NBFCB  : NOMBRE FINAL DE COURBES DE SGI
C L1COURB: L1COURB(k) NUMERO DANS LCHSGI DU PREMIER SGI DE LA COURBE k
C          DE SOMMET INITIAL NUSUCB(1,k) et FINAL NUSUCB(2,k)
C NUSUCB : NUSUCB(1:2,k) NO DU PREMIER ET DERNIER SOMMET DANS XYZPTA
C          DE LA COURBE k
C NUARCB : NUARCB(L,M) NUMERO DE L'ARETE NT1 DU SU L DE LA COURBE M
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC & St Pierre du Perray  Octobre 2011
C2345X7..............................................................012
      INTEGER  NUSTS1(4,*), LCHSGI(2,*), NSTSGI(4,*),
     %         L1COURB(0:NBFCB), NUSUCB(2,0:NBFCB), NUARCB(2,0:NBFCB)
      DOUBLE PRECISION  XYZS1(3,*), XYZPTA(3,*), CBPTTRA(3)
C
C     NUMERO DES 3 SOMMETS DU TRIANGLE NT1 CONTENANT AU MOINS 1 SGI
      NS1T1 = NUSTS1(1,NT1)
      NS2T1 = NUSTS1(2,NT1)
      NS3T1 = NUSTS1(3,NT1)
C
C     PARCOURS DES NBFCB COURBES ACTUELLES
      NUCB = 0
C
 10   NUCB = NUCB + 1
      IF( NUCB .GT. NBFCB ) GOTO 50
C
C     COURBE NUCB A TRAITER
C     PARCOURS DES SOMMETS DOUBLES DE LA COURBE
      LCH0 = L1COURB(NUCB)
C
C     NUMERO DANS LCHSGI DU SGI
 15   NSGI = LCHSGI( 1, LCH0 )
C     NSG2 NUMERO DU SOMMET 2 DU SGI DANS XYZPTA
      NSG2 = NSTSGI( 2, NSGI )
C
C     SGI SUIVANT
      LCH = LCHSGI( 2, LCH0 )
      IF( LCH .LE. 0 ) GOTO 10
C
C     NSG2 EST UN SOMMET DOUBLE DE LA COURBE
C     EST IL SUR DES 3 ARETES DU TRIANGLE?
C     COORDONNEES BARYCENTRIQUES DU POINT NSG2
      CALL CBPTTR( XYZS1(1,NS1T1), XYZS1(1,NS2T1),
     %             XYZS1(1,NS3T1), XYZPTA(1,NSG2),
     %             CBPTTRA )
C     NSG2 EST SUR L'ARETE K SI CBPTTRA(K-1)=0
      DO K=1,3
         IF( K .GT. 1 ) THEN
            K2 = K-1
         ELSE
            K2 = 3
         ENDIF
         IF( ABS(CBPTTRA(K2)) .LE. 1D-4 ) THEN
C           NUSU(M) EST INTERNE A L'ARETE K DE NT1
ccc            print *,'Triangle',NT1,' ST DOUBLE',NSG2,
ccc     %              ' est sur arete',K
            GOTO 20
         ENDIF
      ENDDO
C
C     NSG2 EST SUR AUCUNE ARETE. PASSAGE AU SOMMET DOUBLE SUIVANT
      LCH0 = LCH
      GOTO 15
C
C     NSG2 EST SUR L'ARETE K DU TRIANGLE NT1
C     NSG2 DEVIENT UN DOUBLE SOMMET UNIQUE
C     SOMMET FINAL DE LA 1-ERE COURBE ET INITIAL DE LA SECOND COURBE
C     DECOUPAGE EN 2 COURBES DE LA COURBE NUCB
C     FERMETURE DE LA PREMIERE COURBE
 20   LCHSGI( 2, LCH0 ) = - LCHSGI( 2, LCH0 )
C
C     UNE COURBE DE PLUS
      NBFCB = NBFCB + 1
      L1COURB(NBFCB) = LCH
C
C     PROTECTIONS
      NSF = NUSUCB( 2, NUCB )
      NAF = NUARCB( 2, NUCB )
C
C     2 SOMMETS NSG2 UNIQUES DE PLUS
C     DERNIER SOMMET UNIQUE DE LA COURBE NUCB
      NUSUCB( 2, NUCB ) = NSG2
C     NUMERO ARETE NT1 DU DERNIER SOMMET UNIQUE DE LA COURBE NUCB
      NUARCB( 2, NUCB ) = K
C
C     NUMERO DU PREMIER SOMMET UNIQUE DE LA COURBE NBFCB
      NUSUCB( 1, NBFCB ) = NSG2
C     NUMERO ARETE NT1 DU PREMIER SOMMET UNIQUE DE LA COURBE NBFCB
      NUARCB( 1, NBFCB ) = K
C
C     NUMERO DU DERNIER SOMMET UNIQUE DE LA COURBE NBFCB
      NUSUCB( 2, NBFCB ) = NSF
C     NUMERO ARETE NT1 DU DERNIER SOMMET UNIQUE DE LA COURBE NBFCB
      NUARCB( 2, NBFCB ) = NAF
C
C     PASSAGE A LA COURBE SUIVANTE
      GOTO 10
C
C     TOUS LES SOMMETS DOUBLES DES COURBES ONT ETE TRAITES
C     AFFICHAGE DES NBFCB COURBES DE SGI
ccc 50   print *
ccc      DO M=1,NBFCB
ccc         print *,'SGICOURB2:  NUSUCB(1,',M,')=',NUSUCB(1,M),
ccc     %                      ' NUSUCB(2,',M,')=',NUSUCB(2,M)
ccc         print *,'SGICOURB2:  NUARCB(1,',M,')=',NUARCB(1,M),
ccc     %                      ' NUARCB(2,',M,')=',NUARCB(2,M)
ccc      ENDDO
ccc   CALL SGIIMPR( L1COURB(1), LCHSGI, NSTSGI )
C
 50   RETURN
      END
