      SUBROUTINE SGIRENV( L1CHSGI, LCHSGI, NSTSGI )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RENVERSER L'ORDRE DES CHAINAGES D'UNE LISTE L1CHSGI, LCHSGI
C -----
C MODIFIES:
C----------
C L1CHSGI: POINTEUR SUR LE 1-ER SEGMENT INTERSECTION (SGI)
C LCHSGI : NUMERO DU SGI et CHAINAGE SUR LE SUIVANT
C          LCHSGI(2,K) = SUIVANT DE K DANS LCHSGI
C NSTSGI : NUMERO DANS XYZPTA DES 2 POINTS EXTREMITES DU SGI
C          NUMERO DU TRIANGLE DANS NUSTS1 ET DANS NUSTS2
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC & St Pierre du Perray  Octobre 2011
C2345X7..............................................................012
      INTEGER  L1CHSGI, LCHSGI(2,*), NSTSGI(4,*)
C
C     LE PREMIER SGI
      LCH = L1CHSGI
      IF( LCH .LE. 0 ) GOTO 9999
C
C     LE SUIVANT
      LCHS = LCHSGI( 2, LCH  )
      IF( LCHS .LE. 0 ) GOTO 9999
C
C     LE SUIVANT DU SUIVANT
 10   LCHSS = LCHSGI( 2, LCHS )
C
C     L'ANCIEN SUIVANT DEVIENT LE NOUVEAU PRECEDENT
      LCHSGI( 2, LCHS ) = LCH
C
C     PERMUTATION DU NUMERO DES 2 SOMMETS DU SGI
C     NUMERO DANS LCHSGI DU SGI
      NSGI = LCHSGI( 1, LCH )
C     NS1 NUMERO DU SOMMET 1 DU SGI LCH DANS XYZPTA
      NS1  = NSTSGI( 1, NSGI )
C     NS2 NUMERO DU SOMMET 2 DU SGI LCH DANS XYZPTA
      NS2  = NSTSGI( 2, NSGI )
      NSTSGI( 1, NSGI ) = NS2
      NSTSGI( 2, NSGI ) = NS1
C
C     PROGRESSION D'UN SGI
      LCH  = LCHS
      LCHS = LCHSS
      IF( LCHSS .GT. 0 ) GOTO 10
C
C     LE PREMIER DEVIENT LE DERNIER: SON POINTEUR DEVIENT 0
      LCHSGI( 2, L1CHSGI ) = 0
C
C     POINTEUR DU NOUVEAU PREMIER
      L1CHSGI = LCH
C
C     PERMUTATION DU NUMERO DES 2 SOMMETS DU NOUVEAU PREMIER SGI
C     NUMERO DANS LCHSGI DU SGI
      NSGI = LCHSGI( 1, LCH )
C     NS1 NUMERO DU SOMMET 1 DU SGI LCH DANS XYZPTA
      NS1  = NSTSGI( 1, NSGI )
C     NS2 NUMERO DU SOMMET 2 DU SGI LCH DANS XYZPTA
      NS2  = NSTSGI( 2, NSGI )
      NSTSGI( 1, NSGI ) = NS2
      NSTSGI( 2, NSGI ) = NS1
C
C     AFFICHAGE DES SGI RENVERSES
 9999 print *,'sgirenv:'
      CALL SGIIMPR( L1CHSGI, LCHSGI, NSTSGI )
C
      RETURN
      END
