      SUBROUTINE SIPITE( Pt,     XYZSOM, NBTEDS, NOTEDS, NBSOTE, NSTETR,
     %                   QUALIT, N1FEOC, N1FEVI, NFETOI, VOETOI, QUETOI,
     %                   VOLET0, QUAET0, VOLET1, QUAET1  )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SIMULATION DE LA TETRAEDRISATION ETOILEE PAR LE POINT P
C -----    DES NBTEDS TETRAEDRES NOTEDS DANS NSTETR
C
C ENTREES:
C --------
C Pt     : XYZ DU POINT ETOILANT ?
C XYZSOM : LES 3 COORDONNEES DES SOMMETS DES TETRAEDRES
C NBTEDS : NOMBRE DE TETRAEDRES DE L'ETOILE DE P
C NOTEDS : NUMERO DANS NSTETR DES TETRAEDRES DE L'ETOILE
C NBSOTE : VALEUR MAXIMALE DE DECLARATION DU PREMIER INDICE DE NSTETR(>3)
C NSTETR : NUMERO DES 4 SOMMETS DE CHAQUE TETRAEDRE

C MODIFIES :
C ----------
C QUALIT : QUALITE DES TETRAEDRES ACTUELS
C N1FEVI : NUMERO DANS NFETOI DE LA PREMIERE FACE VIDE
C N1FEOC : NUMERO DANS NFETOI DE LA PREMIERE FACE OCCUPEE
C NFETOI : NUMERO DES 3 SOMMETS, TETRAEDRE ET SUIVANTE DES FACES
C          VUES UNE FOIS DE L'ETOILE CHAINEES N1FEOC PUIS NFETOI(5,*)
C VOETOI : VOLUME  DU TETRAEDRE INITIAL ASSOCIE A LA FACE
C QUETOI : QUALITE DU TETRAEDRE INITIAL ASSOCIE A LA FACE

C SORTIES:
C --------
C VOLTE0 : VOLUME  INITIAL  DE LA TETRAEDRISATION ETOILEE PAR Pt
C QUAET0 : QUALITE INITIALE DE LA TETRAEDRISATION ETOILEE PAR Pt
C VOLTE1 : VOLUME  FINAL    DE LA TETRAEDRISATION ETOILEE PAR Pt
C QUAET1 : QUALITE FINALE   DE LA TETRAEDRISATION ETOILEE PAR Pt
C          -2 INDIQUE UNE IMPOSSIBLITE D'OBTENIR UNE ETOILE POUR Pt
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 1991
C MODIFS : ALAIN PERRONNET LJLL UPMC et St Pierre du Perray Fevrier 2016
C....................................................................012
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      INTEGER           NSTETR(NBSOTE,*), NFETOI(5,*), NOTEDS(*)
      REAL              Pt(3), XYZSOM(3,*)
      REAL              VOETOI(*), QUETOI(*), QUALIT(*)
      REAL              ARMIN, ARMAX, SURFTR(4),
     %                  VOLET0, VOLET1, QUAET0, QUAET1

C     REINITIALISATION A VIDE DES FACES ETOILANT LE POINT
C     ---------------------------------------------------
      CALL ETOIOCVI( N1FEOC, N1FEVI, NFETOI )

C     L'ETOILE DES FACES SIMPLES DES TETRAEDRES NOTEDS
C     ------------------------------------------------
      GRAND  = RINFO( 'GRAND' )
      QUAET0 = GRAND
      QUAET1 = GRAND
      VOLET0 = 0
      VOLET1 = 0

      DO J=1,NBTEDS

C        NUMERO NSTETR DU TETRAEDRE
         NT = NOTEDS(J)

C        CALCUL DU VOLUME ET QUALITE DU TETRAEDRE NT
         CALL QUATET( XYZSOM(1,NSTETR(1,NT)),
     %                XYZSOM(1,NSTETR(2,NT)),
     %                XYZSOM(1,NSTETR(3,NT)),
     %                XYZSOM(1,NSTETR(4,NT)),
     %                ARMIN, ARMAX, SURFTR, V, Q )
         QUALIT( NT ) = Q

C        VOLUME INITIAL
         VOLET0 = VOLET0 + ABS( V )

C        QUALITE INITIALE
         QUAET0 = MIN( QUAET0, Q )

C        FORMATION DES FACES DE L'ETOILE DES TETRAEDRES NOTEDS AJOUTES
         DO I=1,4
C           SI    ( LA FACE I DU TETRAEDRE NOTET0 N'APPARTIENT PAS
C                   AUX FACES DE L'ETOILE NFETOI )
C           ALORS ELLE EST AJOUTEE A L'ETOILE DANS NFETOI
C           SINON ELLE EST EMPILEE DANS NPILE POUR ETRE DETRUITE ENSUITE
C                 ELLE EST SUPPRIMEE DE L'ETOILE NFETOI
            CALL AJFACE( 1, NT, I, NBSOTE, NSTETR,
     %                   N1FEOC, N1FEVI, NFETOI,
     %                   NF  )
            IF( NF .LT. 0 ) THEN
C              SATURATION DES FACES DE L'ETOILE
               QUAET1 = -2
               VOLET1 = 0
               GOTO 9999
            ENDIF
         ENDDO

      ENDDO

C     ICI, L'ETOILE EST COMPLETE: CALCUL DE SA QUALITE
C     ------------------------------------------------
      NF = N1FEOC
 90   IF( NF .GT. 0 ) THEN

C        CALCUL DU VOLUME ET QUALITE DU TETRAEDRE DU A LA FACE
         CALL QUATET( XYZSOM(1,NFETOI(1,NF)),
     %                XYZSOM(1,NFETOI(2,NF)),
     %                XYZSOM(1,NFETOI(3,NF)),
     %                Pt,
     %                ARMIN, ARMAX, SURFTR, VOETOI(NF), QUETOI(NF) )

C        VOLUME FINAL
         VOLET1 = VOLET1 + ABS( VOETOI( NF ) )

C        QUALITE INITIALE
         IF( QUETOI(NF) .LT. QUAET1 ) THEN
            QUAET1 = QUETOI(NF)
         ENDIF

C        PASSAGE A LA FACE SUIVANTE
         NF = NFETOI(5,NF)
         GOTO 90

      ENDIF
C
C     RECTIFICATION EN CAS D'ETOILE VIDE
      IF( QUAET1 .EQ. GRAND ) QUAET1 = 0
C
 9999 RETURN
      END
