      SUBROUTINE SIPTGRBA( KTITRE, PTXYZD, N1FEOC, NFETOI,
     %                     NBFETO, XYZMAX, MXVPSI, NBVPSI, NFVPSI,
     %                     QUAMIMX, RAVEVM )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SIMULER LA TETRAEDRISATION DES FACES SIMPLES DE L'ETOILE
C -----    NFETOI ISSUES DE N1FEOC A PARTIR D'UN POINT XYZ CALCULE
C          SUR UNE GRILLE 3D CENTRE AU BARYCENTRE DES FACES DE L'ETOILE
C          POUR MAXIMISER LE NOMBRE DE TETRAEDRES FACE+XYZ DE VOLUMES
C          POSITIFS ET SANS INTERSECTION AVEC LES FACES

C ENTREES:
C --------
C KTITRE : TITRE DU TRACE
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C NFETOI : LES FACES TRIANGULAIRES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST LA NORMALE DIRIGEE VERS L'INTERIEUR
C             DE L'ETOILE
C          5: CHAINAGE SUR LA FACE SUIVANTE OCCUPEE OU VIDE
C MXVPSI : NOMBRE MAXIMAL DE FACES DU TABLEAU NFVPSI et NFVPSI0

C SORTIES:
C --------
C NBFETO : NOMBRE ACTUEL  DE FACES DE L'ETOILE ISSUE DE N1FEOC
C XYZMAX : POINT CHOISI POUR FORMER AVEC DES FACES DE L'ETOILE DES TETRAEDRES
C          MAXIMISANT LE NOMBRE DE TETRAEDRES FACE+XYZMAx A V>0
C NBVPSI : NOMBRE DE FACES DES TETRAEDRES DE VOLUME>0 SANS INTERSECTION
C          AVEC LES FACES
C NFVPSI : NUMERO NFETOI DES NBVPSI FACES DONNANT AVEC XYZMAX UN VOLUME>0
C          ET SANS INTERSECTION AVEC LES FACES DE L'ETOILE
C QUAMIMX: QUALITE MINIMALE DES NBVPSI FUTURS TETRAEDRES A VOLUME>0
C RAVEVM : RAPPORT DU VOLUME DE L'ETOILE ACTUELLE AU VOLUME DE
C          NBFETO FOIS LE VOLUME DU TETRAEDRE REGULIER D'ARETE MOYENNE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & VEULETTES SUR MER   DECEMBRE 2014
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY OCTOBRE  2017
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY MAI      2018
C MODIFS : ALAIN PERRONNET             St PIERRE DU PERRAY JANVIER  2020
C2345X7..............................................................012
ccc      include"./incl/darete.inc"
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      DOUBLE PRECISION  PTXYZD(4,*), XYZ(3), XYZBE(3), XYZPAS(3),
     %                  XYZMAX(3), XYZMIX(3,2),
     %                  AREMOY, VTETREG, COEFQP, V, RAVEVM

      INTEGER           NFETOI(5,*), NFVPSI(MXVPSI)
      REAL              QUAMIN, QUAMIMX
      CHARACTER*(*)     KTITRE

      TRACTE0 = TRACTE
      LORBITE = 1

      NFVPSIMAX = 0
      QUAMIMX   = -2.0

C     CHOIX: XYZ UN SOMMET D'UNE GRILLE CUBIQUE AUTOUR DU
C            BARYCENTRE XYZBE DE TOUTES LES FACES DE L'ETOILE
C     -------------------------------------------------------
C     CALCUL DES COORDONNEES EXTREMES ET DU POINT XYZBE DU BARYCENTRE
C     DES FACES N1FEOC A 0 DE L'ETOILE DEFINIE DANS NFETOI
      CALL XYZBF10( PTXYZD, N1FEOC, 0, NFETOI, NBFETO, XYZMIX, XYZBE )

C     TRACE DES FACES DE L'ETOILE ET DU POINT XYZ
      KTITRE='Entree siptgrba:        FACES de NFETOI'
      WRITE(KTITRE(17:21),'(I5)') NBFETO
      CALL SANSDBL( KTITRE, L )
      CALL TRFETO3( KTITRE(1:L), XYZBE, XYZBE, PTXYZD, N1FEOC, NFETOI,
     %              0, NFVPSI )

C     CALCUL DU VOLUME DES TETRAEDRES FACES+XYZBE POUR SAVOIR
C     SI L'ETOILE EST QUASI-PLANE (RAVEVM<=1D-2)
      CALL VOTEET( PTXYZD, XYZBE, N1FEOC, NFETOI, NBFETO, V )

C     LA LONGUEUR DE L'ARETE MOYENNE DES FACES DE L'ETOILE
      CALL ARMYFAET( PTXYZD, N1FEOC, NFETOI, NBFETO, AREMOY )

C     VOLUME DU TETRAEDRE REGULIER D'ARETE AREMOY
      VTETREG = AREMOY **3 / ( 6D0 * SQRT( 2D0 ) )
C     VOLUME DE L'ETOILE REGULIERE DE NBFETO FACES = VTETREG * NBFETO

C     RAPPORT DU VOLUME V DE L'ETOILE FACES+XYZBE AU VOLUME DE
C     NBFETO VOLUME D'UN TETRAEDRE REGULIER D'ARETE AREMOY
C     CE RAPPORT MESURE L'ECRASEMENT DE L'ETOILE / TETRAEDRES REGULIERS
      RAVEVM = V / ( VTETREG * NBFETO )

      IF( RAVEVM .LT. 1D-2 ) THEN
C        COEFFICIENT REDUCTEUR POUR UNE ETOILE QUASI-PLANE
         COEFQP = 0.6D0
      ELSE
C        COEFFICIENT REDUCTEUR POUR UNE ETOILE CORRECTEMENT VOLUMINEUSE
         COEFQP = 1D0
      ENDIF

C     GRILLE DE POINTS AUTOUR DU BARYCENTRE DES NBFETO FACES NFETOI
C     =============================================================
C     LES PAS XYZPAS ENTRE SOMMETS DE LA GRILLE
      NBSUB = 2
      DO N=1,3
         XYZPAS(N)=(XYZMIX(N,2)-XYZMIX(N,1)) / (2.15 * NBSUB) * COEFQP
      ENDDO

C     METHODE DU MAXIMUM DE FACE+XYZ DE VOLUME>0 SANS INTERSECTION ET DE
C     MAXIMUM DU MINIMUM DES QUALITES DES TETRAEDRES NF+XYZ
C     ------------------------------------------------------------------
      MXFPVP = 0
      DO N = -NBSUB, NBSUB, 1
         XYZ(3) = XYZBE(3) + N * XYZPAS(3)
         DO M = -NBSUB, NBSUB, 1
            XYZ(2) = XYZBE(2) + M * XYZPAS(2)
            DO L = -NBSUB, NBSUB, 1
               XYZ(1) = XYZBE(1) + L * XYZPAS(1)

C              DETERMINER LE NOMBRE MAXIMAL DE TETRAEDRES XYZ+FACES
C              SIMPLES DE VOLUME POSITIF et SANS INTERSECTION AVEC
C              LES AUTRES FACES SIMPLES DE L'ETOILE
               CALL FAPTVPSI( XYZ,    PTXYZD, N1FEOC, NFETOI,
     %                        MXVPSI, NBVPSI, NFVPSI,
     %                        NBFETO, NBVPIN, QUAMIN )

               IF( NBVPSI .GT. MXFPVP ) THEN
                  MXFPVP    = NBVPSI
                  QUAMIMX   = QUAMIN
                  XYZMAX(1) = XYZ(1)
                  XYZMAX(2) = XYZ(2)
                  XYZMAX(3) = XYZ(3)
                  NFVPSIMAX = NFVPSI(1)
               ELSE IF( NBVPSI.EQ.MXFPVP .AND. QUAMIN.GT.QUAMIMX ) THEN
                  QUAMIMX   = QUAMIN
                  XYZMAX(1) = XYZ(1)
                  XYZMAX(2) = XYZ(2)
                  XYZMAX(3) = XYZ(3)
                  NFVPSIMAX = NFVPSI(1)
               ENDIF

            ENDDO
         ENDDO
      ENDDO

C     LE MEILLEUR RESULTAT AVEC LE MAXIMUM DE FACES+XYZMAX A V>0
      NBVPSI = MXFPVP

C     RECALCULER LE TABLEAU NFVPSI POUR LE POINT XYZMAX CAR LE
C     TABLEAU A PEUT ETRE ETE ECRASE PAR LES POINTS SUIVANTS de XYZMAX
      CALL FAPTVPSI( XYZMAX, PTXYZD, N1FEOC, NFETOI,
     %               MXVPSI, NBVPSI, NFVPSI,
     %               NBFETO, NBVPIN, QUAMIMX )

      IF( NBVPSI .EQ. NBFETO ) THEN

C        XYZMAX TETRAEDRISE TOUTES LES FACES DE NFETOI
C        =============================================
       KTITRE='siptgrba:  TOUTES LES        FACES+XYZMAX -> TETRAEDRES V
     %>0'
         WRITE(KTITRE(23:27), '(I5)' ) NBFETO

      ELSE

       KTITRE='siptgrba: PARMI les       FACES seules       FACES+XYZMAX
     % -> TETRAEDRES V>0'
         WRITE(KTITRE(20:24), '(I5)' ) NBFETO
         WRITE(KTITRE(39:43), '(I5)' ) NBVPSI

      ENDIF

C     TRACE DES FACES DE L'ETOILE ET DU POINT XYZ
      CALL SANSDBL( KTITRE, L )
ccc      PRINT*, KTITRE(1:L)
      CALL TRFETO3( KTITRE(1:L), XYZMAX, XYZMAX, PTXYZD,
     %              N1FEOC, NFETOI, NBVPSI, NFVPSI )

      TRACTE = TRACTE0
      RETURN
      END
