        SUBROUTINE SUEX16( NTLXSU, LADEFI, RADEFI,
     %                     NTFASF, MNFASF, NTSOSF, MNSOSF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  GENERER LA QUADRANGULATION D'UNE SURFACE
C -----  OBTENUE PAR DES COUCHES LIMITES SELON LA NORMALE AUX ARETES
C        D'UNE LIGNE FERMEE par exemple un NACA
C        REMARQUE: LA DONNEE de EPAISSEUR 1ER COUCHE<0
C                  DONNE L'EXTRUSION DANS L'AUTRE SENS DE LA NORMALE!
C
C        ATTENTION: SI LA LIGNE N'EST PAS CONVEXE LES QUADRANGLES
C                   PEUVENT SE CHEVAUCHER
C                   TRACER POUR VERIFIER SI LE RESULTAT EST CORRECT
C ENTREES:
C --------
C NTLXSU : NUMERO DU TABLEAU TS DU LEXIQUE DE LA SURFACE A CREER
C LADEFI : TABLEAU ENTIER DE DEFINITION DE LA SURFACE
C RADEFI : TABLEAU REEL   DE DEFINITION DE LA SURFACE
C          CF '~/td/d/a_surface__definition'
C
C SORTIES:
C --------
C NTFASF : NUMERO      DU TMS 'NSEF' DES NUMEROS DES FACES
C MNFASF : ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES FACES
C          CF '~/td/d/a___nsef'
C NTSOSF : NUMERO      DU TMS 'XYZSOMMET' DE LA SURFACE
C MNSOSF : ADRESSE MCN DU TMS 'XYZSOMMET' DE LA SURFACE
C          CF '~/td/d/a___xyzsommet'
C IERR   : = 0 SI PAS D'ERREUR
C          <>0 SI ERREUR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR:ALAIN PERRONNET NCTS Tsing Hua University HSINCHU TAIWAN 9/2006
C23456...............................................................012
      IMPLICIT INTEGER (W)
      REAL        VALTEM
      PARAMETER  (VALTEM=1.23E37)
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/a_surface__definition.inc"
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
      INTEGER           LADEFI(0:*), NOSOEL(4)
      REAL              RADEFI(0:*)
      CHARACTER*24      KNOMLG
      LOGICAL           SENSDIREC
C
      IERR   = 0
      MNSOLG = 0
C
C     A PRIORI LA LIGNE EST DANS LE SENS DIRECT
      SENSDIREC = .TRUE.
C
C     VERIFICATION DES DONNEES
C     NOMBRE DES PREMIERES COUCHES LIMITES
      NBCOLI = LADEFI( WBCOLI )
      IF( NBCOLI .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER),'(I12)') NBCOLI
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'NOMBRE INCORRECT de PREMIERES COUCHES LIMITES='
     %                 //KERR(MXLGER)(1:12)
         ELSE
            KERR(1) = 'INCORRECT NUMBER of FIRST BOUNDARY LAYERS='
     %                 //KERR(MXLGER)(1:12)
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     EPAISSEUR D'UNE DES PREMIERES COUCHES LIMITES
      EPCOLI = RADEFI( WPCOLI )
      IF( EPCOLI .EQ. 0.0 ) THEN
C        L'EPAISSEUR PEUT ETRE POSITIVE OU NEGATIVE
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER),'(G15.7)') EPCOLI
         IF( LANGAG .EQ. 0 ) THEN
           KERR(1)='EPAISSEUR INCORRECTE des PREMIERES COUCHES LIMITES='
     %              //KERR(MXLGER)(1:15)
         ELSE
           KERR(1)='INCORRECT THICKNESS of FIRST BOUNDARY LAYERS='
     %              //KERR(MXLGER)(1:15)
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     NOMBRE DES DERNIERES COUCHES LIMITES
      NBDECO = LADEFI( WBDECO )
      IF( NBDECO .LT. 0 ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER),'(I12)') NBDECO
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'NOMBRE INCORRECT de DERNIERES COUCHES='
     %                 //KERR(MXLGER)(1:12)
         ELSE
            KERR(1) = 'INCORRECT NUMBER of LAST LAYERS='
     %                 //KERR(MXLGER)(1:12)
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     EPAISSEUR DE LA DERNIERE COUCHE LIMITE
      EPDECO = RADEFI( WPDECO )
      IF( NBDECO .GT. 0 .AND. EPDECO .EQ. 0.0 ) THEN
C        L'EPAISSEUR PEUT ETRE POSITIVE OU NEGATIVE
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER),'(G15.7)') EPDECO
         IF( LANGAG .EQ. 0 ) THEN
           KERR(1)='EPAISSEUR INCORRECTE des DERNIERES COUCHES='
     %              //KERR(MXLGER)(1:15)
         ELSE
           KERR(1)='INCORRECT THICKNESS of FIRST BOUNDARY LAYERS='
     %              //KERR(MXLGER)(1:15)
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     LES 2 EPAISSEURS DOIVENT AVOIR LE MEME SIGNE
      IF( EPCOLI * EPDECO .LT. 0 ) THEN
          EPDECO = - ABS( EPDECO )
          EPCOLI = - ABS( EPCOLI )
       ENDIF
C
C     RESTAURATION DU MAILLAGE DE LA LIGNE
C     ------------------------------------
      NULFAG = LADEFI( WULFAG )
      IF( NULFAG .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'NOM INCORRECT de la LIGNE A GROSSIR'
         ELSE
            KERR(1) = 'UNKNOWN NAME of the LINE TO BE MAGNIFY'
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     OUVERTURE DE LA LIGNE NULFAG
      CALL LXNLOU( NTLIGN, NULFAG, NT, MN )
      IF( NT .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'NOM INCORRECT de la LIGNE A GROSSIR'
         ELSE
            KERR(1) = 'UNKNOWN NAME of the LINE TO BE MAGNIFY'
         ENDIF
         IERR = 1
         RETURN
      ENDIF
C
C     LE NOM KNOMLG  DE LA LIGNE
      CALL NMOBNU( 'LIGNE', NULFAG, KNOMLG )
C
C     RESTAURATION DU TABLEAU XYZSOMMET
      CALL LXTSOU( NT, 'XYZSOMMET', NTSOLG, MNSOLG )
      IF( NTSOLG .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) = KNOMLG
         IF( LANGAG .EQ. 0 ) THEN
            KERR(2) = 'LIGNE SANS XYZSOMMET'
         ELSE
            KERR(2) = 'LINE WITHOUT XYZSOMMET'
         ENDIF
         IERR = 2
         RETURN
      ENDIF
C     LE NOMBRE DE SES SOMMETS ET TANGENTES
      NBSOLG = MCN( MNSOLG+WNBSOM )
      NBTGLG = MCN( MNSOLG+WNBTGS )
C     VERIFICATION: TOUS LES POINTS ONT MEME Z
      MN = MNSOLG + WYZSOM + 2
      R  = RMCN(MN)
      DO 5 I=2,NBSOLG
         MN = MN + 3
         IF( RMCN(MN) .NE. R ) THEN
            NBLGRC(NRERR) = 2
            KERR(1) = KNOMLG
            IF( LANGAG .EQ. 0 ) THEN
               KERR(2) = 'LIGNE dans R3 INTERDITE. 2D SEULEMENT'
            ELSE
               KERR(2) = '3D LINE FORBIDDEN. 2D ONLY'
            ENDIF
            IERR = 4
            RETURN
         ENDIF
 5    CONTINUE
C
C     RESTAURATION DU TABLEAU NSEF
      CALL LXTSOU( NT, 'NSEF', NTARLG, MNARLG )
      IF( NTARLG .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         KERR(1) = KNOMLG
         IF( LANGAG .EQ. 0 ) THEN
            KERR(2) = 'LIGNE SANS NSEF'
         ELSE
            KERR(2) = 'LINE WITHOUT NSEF'
         ENDIF
         IERR = 3
         RETURN
      ENDIF
C
C     TENTATIVE DE STRUCTURER UNE LIGNE DEFINIE PAR
C     SES 2 TMS XYZSOMMET ET NSEF
C     SI LA LIGNE EST FERMEE DONC NON STRUCTURABLE SES TMS SONT
C     NEANMOINS REMIS DANS UN SENS DE PARCOURS FAVORABLE
      CALL LIGSTR( NT, NTARLG, MNARLG, NTSOLG, MNSOLG, IERR )
C
C     LES PARAMETRES DES NO SOMMET DE LA LIGNE A DEPLACER
      CALL NSEFPA( MCN(MNARLG),
     %             NUTYLG, NBSOEL, NBSOEF, NBTGEL,
     %             LDAPEF, LDNGEF, LDTGEF, NBARLG,
     %             NX  , NY  , NZ  ,
     %             IERR   )
      IF( IERR .NE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'LIGNE A GROSSIR INCORRECTE'
         ELSE
            KERR(1) = 'INCORRECT LINE to MAGNIFY'
         ENDIF
         CALL LEREUR
         IERR = 7
         RETURN
      ENDIF
C
C     NOMBRE D'ARETES A TG DE LA LIGNE
      NBARTG = MCN( MNARLG + WBEFTG )
C
C     ADRESSE AVANT 1-ER NO DE SOMMET DE LA LIGNE
      MNEFLG = MNARLG + WUSOEF - 1
C
C     ADRESSE AVANT 1-ER POINTEUR SUR EF A TG
      MNEFAPLG = MNARLG + LDAPEF -1
C     ADRESSE AVANT 1-ER CODE GEOMETRIQUE DES EF A TG
      MNEFCGLG = MNARLG + LDTGEF -1
C     ADRESSE AVANT NO DE TG DES ARETES A TG
      MNEFLGTG = MNARLG + LDTGEF -1
C
C     LE TYPE DU MAILLAGE DE LA SURFACE
C     LE MAILLAGE DE LA SURFACE EST NON STRUCTURE
      NUTYSF = 0
C
C     LE NOMBRE DE SOMMETS DE LA SURFACE MAILLEE
      NBSOSF = NBSOLG * ( 1 + NBCOLI + NBDECO )
C     LE NOMBRE DE TANGENTES DE LA SURFACE EST CELUI DE LA LIGNE INITIALE
      NBTGSF = NBTGLG
C
C     CONSTRUCTION DU TABLEAU 'XYZSOMMET' DE CETTE SURFACE
C     ----------------------------------------------------
      CALL LXTNDC( NTLXSU, 'XYZSOMMET', 'MOTS',
     %             WYZSOM + 3 * ( NBSOSF + NBTGSF ) )
      CALL LXTSOU( NTLXSU, 'XYZSOMMET',  NTSOSF, MNSOSF )
C     MISE A VALEUR TEMOIN DE NON UTILISATION DES X DES SOMMETS DE LA SURFACE
      MN = MNSOSF + WYZSOM
      DO 2 I=1, NBSOSF
         RMCN( MN ) = VALTEM
         MN = MN + 3
 2    CONTINUE
C
C     CONSTRUCTION DU TABLEAU 'NSEF' DE CETTE SURFACE
C     -----------------------------------------------
C     LE NOMBRE D'EF QUADRANGLES DE LA SURFACE MAILLEE
      NBFASF = NBARLG * ( NBCOLI + NBDECO )
C
C     DECLARATION DES NO DE SOMMETS DES QUADRANGLES DE LA SURFACE
C     LE NOMBRE DE QUADRANGLES A TG
      IF( NBTGLG .GT. 0 ) THEN
         NBTGEF = 8
C        MEME STRUCTURE DE LA SURFACE QUE CELLE DE LA LIGNE
         NBEFTG = NBARTG
         NBEFAP = NBFASF
      ELSE
         NBTGEF = 0
         NBEFTG = 0
         NBEFAP = 0
      ENDIF
      CALL LXTNDC( NTLXSU, 'NSEF', 'ENTIER',
     %             WUSOEF + 4*NBFASF + NBEFAP + NBEFTG * (1+NBTGEF) )
      CALL LXTSOU( NTLXSU, 'NSEF',  NTFASF, MNFASF )
C
C     LA PREMIERE LIGNE DE QUADRANGLES=PREMIERE COUCHE LIMITE
C     LES COORDONNEES DES SOMMETS ET TANGENTES DES QUADRANGLES
      MNSTSF = MNSOSF + WYZSOM - 1
C
C     LA PREMIERE LIGNE DE SOMMET EST LA LIGNE INITIALE
      MN = MNSOLG + WYZSOM - 1
      DO 10 I = 1, 3*NBSOLG
         RMCN( MNSTSF + I ) = RMCN( MN + I )
 10   CONTINUE
C
C     LA SEULE LIGNE A TANGENTES DES QUADRANGLES EST LA LIGNE INITIALE
      MNSFTG = MNSOSF + WYZSOM + 3 * NBSOSF - 1
      MN     = MN + 3 * NBSOLG
      DO 20 I = 1, 3*NBTGLG
         RMCN( MNSFTG + I ) = RMCN( MN + I )
 20   CONTINUE
C
C     LES ADRESSAGES DANS MCN DANS LE TMS NSEF
      MNEFSF   = MNFASF + WUSOEF - 1
      MNEFAPSF = MNEFSF + 4*NBFASF
      MNEFSFTG = MNEFAPSF + NBEFAP + NBEFTG
C
C     TRAITEMENT DES QUADRANGLES A TG = CEUX DE LA PREMIERE COUCHE
      IF( NBTGLG .GT. 0 ) THEN
C        POINTEUR SUR LES PREMIERS QUADRANGLES A TG
         DO 25 I=1,NBARTG
            MCN(MNEFAPSF+I) = MCN(MNEFAPLG+I)
 25      CONTINUE
C        POINTEUR NUL SUR LES QUADRANGLES DES COUCHES 2 3 ...
         CALL AZEROI( NBEFAP-NBARTG, MCN(MNEFAPSF+1+NBARLG) )
C
C        CODE GEOMETRIQUE C1 Degre 3
         CALL AZEROI( NBEFTG,   MCN(MNEFAPSF+1+NBEFAP) )
C        MISE A ZERO DU NUMERO DES TANGENTES
         CALL AZEROI( NBTGEF*NBEFTG, MCN(MNEFSFTG+1) )
      ENDIF
C
C     CONSTRUCTION DES QUADRANGLES ET DES SOMMETS DE LA COUCHE 1
      MNSTSF = MNSOSF + WYZSOM - 4
      DO 30 I=1,NBARLG
         II = I
C
C        LE NUMERO DES 2 SOMMETS ET DES 2 TANGENTES DE L'ARETE I
         CALL NSEFNS( I    ,  NUTYLG, NBSOEF, NBTGEL,
     %                LDAPEF, LDNGEF, LDTGEF,
     %                MNARLG, NX, NY, NZ,
     %                NCOGEL, NUGEEF, NUEFTG, NOSOEL, IERR )
C
C        NCOGEL: NUMERO DU CODE GEOMETRIQUE DE L'EF NUELEM
C                2:SEGMENT
C        NUGEEF: >=0 NUMERO DE DEFINITION GEOMETRIQUE DE L'EF
C        NUEFTG: >0  NUMERO DE CET EF NUELEM PARMI LES EF A TG
C                =0  SI L'EF I N'A PAS DE TG
C        NOSOEL:  NUMERO DES 2 SOMMETS
C                 SUIVI EVENTUELLEMENT DES NBTGEF +-TANGENTES
C        LE - INDIQUE QUE LES COMPOSANTES DE LA TANGENTES SONT A INVERSER
C        SI PAS DE TANGENTES (NBTGEF=0):
C           ARETE: NO SOMMET1 , NS2
C        S'IL EXISTE DES TANGENTES (NBTGEF>0) ELLES SONT RANGEES PAR SOMMET:
C           ARETE: NO SOMMET1, NS2,
C                  NO TANGENTE1(S1S2), NT2(S2S1)
C
C        LES 2 NUMEROS DES SOMMETS DE L'ARETE I
 28      IF( SENSDIREC ) THEN
            NST1 = NOSOEL(2)
            NST2 = NOSOEL(1)
         ELSE
            NST1 = NOSOEL(1)
            NST2 = NOSOEL(2)
         ENDIF
C
C        LE NO DES 4 SOMMETS DU QUADRANGLE I
         NST3 = NST2 + NBSOLG
         NST4 = NST1 + NBSOLG
         MCN( MNEFSF + 1 ) = NST1
         MCN( MNEFSF + 2 ) = NST2
         MCN( MNEFSF + 3 ) = NST3
         MCN( MNEFSF + 4 ) = NST4
         MNEFSF = MNEFSF + 4
C
C        LES 2 EVENTUELLES TANGENTES
         NTG1 = 0
         NTG2 = 0
         IF( NBTGLG .GT. 0 ) THEN
C
            IF( NUEFTG .GT. 0 ) THEN
C              ARETE A TG
               IF( SENSDIREC ) THEN
                  NTG1 = NOSOEL(4)
                  NTG2 = NOSOEL(3)
               ELSE
                  NTG1 = NOSOEL(3)
                  NTG2 = NOSOEL(4)
               ENDIF
            ENDIF
C
C           LES 2 TANGENTES DE LA PREMIERE ARETE DU QUADRANGLE
C           ORDRE DES TG DU QUADRANGLE:
C           T1:S1S2 T2:S1S4  T3:S2S3 T4:S2S1  T5:S3S4 T6:S3S2  T7:S4S1 T8:S4S3
            MCN( MNEFSFTG + 1 ) = NTG1
            MCN( MNEFSFTG + 2 ) = 0
            MCN( MNEFSFTG + 3 ) = 0
            MCN( MNEFSFTG + 4 ) = NTG2
            MCN( MNEFSFTG + 5 ) = 0
            MCN( MNEFSFTG + 6 ) = 0
            MCN( MNEFSFTG + 7 ) = 0
            MCN( MNEFSFTG + 8 ) = 0
            MNEFSFTG = MNEFSFTG + 8
         ENDIF
C
C        CALCUL DES 2 COMPOSANTES DU VECTEUR NORMAL A L'ARETE I DE LA LIGNE
C        DE SOMMETS NST1 et NST2
         MNST1 = MNSTSF + 3 * NST1
         MNST2 = MNSTSF + 3 * NST2
C        LE VECTEUR NORMAL UNITE AU VECTEUR ST1 -> ST2 (+90 DEGRES)
         VN1 = RMCN( MNST1 + 2 ) - RMCN( MNST2 + 2 )
         VN2 = RMCN( MNST2 + 1 ) - RMCN( MNST1 + 1 )
C        NORMALISATION EN LONGUEUR SELON L'EPAISSEUR
C        REMARQUE: EPCOLI<0 DONNE L'AUTRE SENS DU VECTEUR NORMAL!
         R = EPCOLI / SQRT( VN1*VN1 + VN2*VN2 )
         VN1 = VN1 * R
         VN2 = VN2 * R
C
C        CALCUL DES COORDONNEES DES SOMMETS SUR LA NORMALE A UNE EPAISSEUR
C        DEPLACEMENT DANS LA DIRECTION NORMALE DE ST1 -> ST4
         MNST4 = MNSTSF + 3 * NST4
         IF( RMCN(MNST4+1) .EQ. VALTEM ) THEN
C           SOMMET VU POUR LA PREMIERE FOIS. DEPLACEMENT NORMAL
            RMCN( MNST4 + 1 ) = RMCN( MNST1 + 1 ) + VN1
            RMCN( MNST4 + 2 ) = RMCN( MNST1 + 2 ) + VN2
            IF( SURTR2(RMCN(MNST1+1),RMCN(MNST2+1),RMCN(MNST4+1)).LE.0)
     %      THEN
               IF( II .EQ. 1 ) THEN
C                 TRIANGLE DANS LE MAUVAIS SENS => SENS DIRECT INVERSE
                  SENSDIREC = .FALSE.
                  MNEFSF = MNEFSF - 4
                  MNEFSFTG = MNEFSFTG - 8
                  RMCN(MNST4+1) = VALTEM
                  EPCOLI = - EPCOLI
                  EPDECO = - EPDECO
                  II = II + 1
                  GOTO 28
ccc               ELSE
cccC                 ERREUR AU MOINS 2 QUADRANGLES DANS DES SENS OPPOSES
ccc                  NBLGRC(NRERR) = 2
ccc                  KERR(1) = KNOMLG
ccc                  IF( LANGAG .EQ. 0 ) THEN
ccc                     KERR(2) = 'LIGNE AVEC DES ARETES NON TOUTES DANS LE
ccc     % MEME SENS'
ccc                  ELSE
ccc                     KERR(2) ='LINE WITH EDGES NOT ALL IN THE SAME SENS'
ccc                  ENDIF
ccc                  IERR = 5
ccc                  RETURN
               ENDIF
            ENDIF
         ELSE
C           SOMMET VU POUR LA DEUXIEME FOIS. DEPLACEMENT NORMAL DE LA MOYENNE
            RMCN( MNST4+1 ) = (RMCN(MNST4+1) + RMCN(MNST1+1)+VN1) * 0.5
            RMCN( MNST4+2 ) = (RMCN(MNST4+2) + RMCN(MNST1+2)+VN2) * 0.5
         ENDIF
         RMCN( MNST4+3 ) =  RMCN( MNST1 + 3 )
C
C        DEPLACEMENT DANS LA DIRECTION NORMALE DE ST2 -> ST3
         MNST3 = MNSTSF + 3 * NST3
         IF( RMCN(MNST3+1) .EQ. VALTEM ) THEN
C           SOMMET VU POUR LA PREMIERE FOIS. DEPLACEMENT NORMAL
            RMCN( MNST3 + 1 ) = RMCN( MNST2 + 1 ) + VN1
            RMCN( MNST3 + 2 ) = RMCN( MNST2 + 2 ) + VN2
         ELSE
C           SOMMET VU POUR LA DEUXIEME FOIS. DEPLACEMENT NORMAL DE LA MOYENNE
            RMCN( MNST3+1 ) = (RMCN(MNST3+1) + RMCN(MNST2+1)+VN1) * 0.5
            RMCN( MNST3+2 ) = (RMCN(MNST3+2) + RMCN(MNST2+2)+VN2) * 0.5
         ENDIF
         RMCN( MNST3+3 ) =  RMCN( MNST2+3 )
 30   CONTINUE
C
C     QUADRANGULATION DES COUCHES LIMITES 2 a NBCOLI
      MNEFSF0 = MNFASF + WUSOEF - 1
      DO 50 NC = 2, NBCOLI
         DO 40 I = 1, NBARLG
C           LES NUMEROS DES SOMMETS 1 ET 2 DU NOUVEAU QUADRANGLE
C           SONT LES SOMMETS 4 ET 3 DU QUADRANGLE DE LA COUCHE PRECEDENTE
            NST1 = MCN( MNEFSF0 + 4 )
            NST2 = MCN( MNEFSF0 + 3 )
            MNEFSF0 = MNEFSF0 + 4
C
C           LE NO DES 4 SOMMETS DU NOUVEAU QUADRANGLE I
            NST3 = NST2 + NBSOLG
            NST4 = NST1 + NBSOLG
            MCN( MNEFSF + 1 ) = NST1
            MCN( MNEFSF + 2 ) = NST2
            MCN( MNEFSF + 3 ) = NST3
            MCN( MNEFSF + 4 ) = NST4
            MNEFSF = MNEFSF + 4
C
C           CALCUL DES 2 COMPOSANTES DU VECTEUR NORMAL A L'ARETE I DE LA LIGNE
C           DE SOMMETS NST1 et NST2
            MNST1 = MNSTSF + 3 * NST1
            MNST2 = MNSTSF + 3 * NST2
C           LE VECTEUR NORMAL UNITE AU VECTEUR ST1 -> ST2 (+90 DEGRES)
            VN1 = RMCN( MNST1 + 2 ) - RMCN( MNST2 + 2 )
            VN2 = RMCN( MNST2 + 1 ) - RMCN( MNST1 + 1 )
C           NORMALISATION EN LONGUEUR SELON L'EPAISSEUR
            R = EPCOLI / SQRT( VN1*VN1 + VN2*VN2 )
            VN1 = VN1 * R
            VN2 = VN2 * R
C
C           CALCUL DES COORDONNEES DES SOMMETS SUR LA NORMALE A UNE EPAISSEUR
C           DEPLACEMENT DANS LA DIRECTION NORMALE DE ST1 -> ST4
            MNST4 = MNSTSF + 3 * NST4
            IF( RMCN(MNST4+1) .EQ. VALTEM ) THEN
C              SOMMET VU POUR LA PREMIERE FOIS. DEPLACEMENT NORMAL
               RMCN( MNST4 + 1 ) = RMCN( MNST1 + 1 ) + VN1
               RMCN( MNST4 + 2 ) = RMCN( MNST1 + 2 ) + VN2
            ELSE
C              SOMMET VU POUR LA DEUXIEME FOIS. DEPLACEMENT NORMAL DE LA MOYENNE
               RMCN(MNST4+1) = (RMCN(MNST4+1) + RMCN(MNST1+1)+VN1) * 0.5
               RMCN(MNST4+2) = (RMCN(MNST4+2) + RMCN(MNST1+2)+VN2) * 0.5
            ENDIF
            RMCN( MNST4+3 ) =  RMCN( MNST1 + 3 )
C
C           DEPLACEMENT DANS LA DIRECTION NORMALE DE ST2 -> ST3
            MNST3 = MNSTSF + 3 * NST3
            IF( RMCN(MNST3+1) .EQ. VALTEM ) THEN
C              SOMMET VU POUR LA PREMIERE FOIS. DEPLACEMENT NORMAL
               RMCN( MNST3 + 1 ) = RMCN( MNST2 + 1 ) + VN1
               RMCN( MNST3 + 2 ) = RMCN( MNST2 + 2 ) + VN2
            ELSE
C              SOMMET VU POUR LA DEUXIEME FOIS. DEPLACEMENT NORMAL DE LA MOYENNE
               RMCN(MNST3+1) = (RMCN(MNST3+1) + RMCN(MNST2+1)+VN1) * 0.5
               RMCN(MNST3+2) = (RMCN(MNST3+2) + RMCN(MNST2+2)+VN2) * 0.5
            ENDIF
            RMCN( MNST3+3 ) =  RMCN( MNST2+3 )
 40      CONTINUE
 50   CONTINUE
C
C     QUADRANGULATION DES DERNIERES COUCHES 1 a NBDECO
      DO 70 NC = 1, NBDECO
C        EPAISSEUR DE LA COUCHE  VARIATION LINEAIRE ENTRE EPCOLI ET EPDECO
         EPAIS = ( EPCOLI * (NBDECO-NC) + EPDECO * NC )/ NBDECO
         DO 60 I = 1, NBARLG
C           LES NUMEROS DES SOMMETS 1 ET 2 DU NOUVEAU QUADRANGLE
C           SONT LES SOMMETS 4 ET 3 DU QUADRANGLE DE LA COUCHE PRECEDENTE
            NST1 = MCN( MNEFSF0 + 4 )
            NST2 = MCN( MNEFSF0 + 3 )
            MNEFSF0 = MNEFSF0 + 4
C
C           LE NO DES 4 SOMMETS DU NOUVEAU QUADRANGLE I
            NST3 = NST2 + NBSOLG
            NST4 = NST1 + NBSOLG
            MCN( MNEFSF + 1 ) = NST1
            MCN( MNEFSF + 2 ) = NST2
            MCN( MNEFSF + 3 ) = NST3
            MCN( MNEFSF + 4 ) = NST4
            MNEFSF = MNEFSF + 4
C
C           CALCUL DES 2 COMPOSANTES DU VECTEUR NORMAL A L'ARETE I DE LA LIGNE
C           DE SOMMETS NST1 et NST2
            MNST1 = MNSTSF + 3 * NST1
            MNST2 = MNSTSF + 3 * NST2
C           LE VECTEUR NORMAL UNITE AU VECTEUR ST1 -> ST2 (+90 DEGRES)
            VN1 = RMCN( MNST1 + 2 ) - RMCN( MNST2 + 2 )
            VN2 = RMCN( MNST2 + 1 ) - RMCN( MNST1 + 1 )
C           NORMALISATION EN LONGUEUR SELON L'EPAISSEUR
            R = EPAIS / SQRT( VN1*VN1 + VN2*VN2 )
            VN1 = VN1 * R
            VN2 = VN2 * R
C
C           CALCUL DES COORDONNEES DES SOMMETS SUR LA NORMALE A UNE EPAISSEUR
C           DEPLACEMENT DANS LA DIRECTION NORMALE DE ST1 -> ST4
            MNST4 = MNSTSF + 3 * NST4
            IF( RMCN(MNST4+1) .EQ. VALTEM ) THEN
C              SOMMET VU POUR LA PREMIERE FOIS. DEPLACEMENT NORMAL
               RMCN( MNST4 + 1 ) = RMCN( MNST1 + 1 ) + VN1
               RMCN( MNST4 + 2 ) = RMCN( MNST1 + 2 ) + VN2
            ELSE
C              SOMMET VU POUR LA DEUXIEME FOIS. DEPLACEMENT NORMAL DE LA MOYENNE
               RMCN(MNST4+1) = (RMCN(MNST4+1) + RMCN(MNST1+1)+VN1) * 0.5
               RMCN(MNST4+2) = (RMCN(MNST4+2) + RMCN(MNST1+2)+VN2) * 0.5
            ENDIF
            RMCN( MNST4+3 ) =  RMCN( MNST1 + 3 )
C
C           DEPLACEMENT DANS LA DIRECTION NORMALE DE ST2 -> ST3
            MNST3 = MNSTSF + 3 * NST3
            IF( RMCN(MNST3+1) .EQ. VALTEM ) THEN
C              SOMMET VU POUR LA PREMIERE FOIS. DEPLACEMENT NORMAL
               RMCN( MNST3 + 1 ) = RMCN( MNST2 + 1 ) + VN1
               RMCN( MNST3 + 2 ) = RMCN( MNST2 + 2 ) + VN2
            ELSE
C              SOMMET VU POUR LA DEUXIEME FOIS. DEPLACEMENT NORMAL DE LA MOYENNE
               RMCN(MNST3+1) = (RMCN(MNST3+1) + RMCN(MNST2+1)+VN1) * 0.5
               RMCN(MNST3+2) = (RMCN(MNST3+2) + RMCN(MNST2+2)+VN2) * 0.5
            ENDIF
            RMCN( MNST3+3 ) =  RMCN( MNST2+3 )
 60      CONTINUE
 70   CONTINUE
C
C     MISE A JOUR DU TABLEAU 'XYZSOMMET'
C     ----------------------------------
C     LE NOMBRE DE COORDONNEES PAR SOMMET
      MCN( MNSOSF + WBCOOR ) = 3
C     LE NOMBRE DE SOMMETS
      MCN( MNSOSF + WNBSOM ) = NBSOSF
C     LE NOMBRE DE TANGENTES
      MCN( MNSOSF + WNBTGS ) = NBTGSF
C     LA DATE DE CREATION
      CALL ECDATE( MCN(MNSOSF) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNSOSF + MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )
C
C     MISE A JOUR DU TABLEAU 'NSEF'
C     -----------------------------
C     SURFACE QUADRANGULEE NON STRUCTUREE
      MCN( MNFASF + WUTYOB ) = 3
      MCN( MNFASF + WUTYMA ) = NUTYSF
C     NOMBRE DE SOMMETS PAR EF
      MCN( MNFASF + WBSOEF ) = 4
C     NOMBRE D'EF DU MAILLAGE
      MCN( MNFASF + WBEFOB ) = NBFASF
C     LE TYPE INCONNU DE FERMETURE DU MAILLAGE
      MCN( MNFASF + WUTFMA ) = -1
C     LES TANGENTES STOCKEES
      MCN( MNFASF + WBTGEF ) = NBTGEF
      MCN( MNFASF + WBEFAP ) = NBEFAP
      MCN( MNFASF + WBEFTG ) = NBEFTG
C     LA DATE DE CREATION
      CALL ECDATE( MCN(MNFASF) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNFASF + MOTVAR(6) ) = NONMTD( '~>>>NSEF' )
C
      RETURN
      END
