      SUBROUTINE SUTELEFA( NTE, NOTETR, INFACO, MXFACO, LEFACO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    SUPPRIMER LE NUMERO NOTETR DU TETRAEDRE NTE DE L'UNE
C -----    DES FACES DU TABLEAU LEFACO EN POSITION 11

C ENTREES:
C --------
C NTE    : NUMERO DU TETRAEDRE DANS NOTETR
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C INFACO : = 0 PAS DE TABLEAU LEFACO NI DE CONSERVATION DES
C              FACES FRONTIERE ( NO DE VOLUME CONNU PAR NVOLTE )
C          = 1 EXISTENCE DU TABLEAU LEFACO ET CONSERVATION DES
C              FACES DE LA FRONTIERE
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO

C MODIFIE:
C --------
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3

C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)

C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...

C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
CCCC       LEFACO(12,*) NO DE FACE OpenCascade
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2016
C MODIF  : ALAIN PERRONNET Veulettes sur mer               Decembre 2019
C2345X7..............................................................012
      INTEGER    NOTETR(8,*), LEFACO(1:11,0:*)

C     DESTRUCTION EVENTUELLE DES 4 FACES DE NTE DANS LEFACO
      IF( INFACO .NE. 0 ) THEN
         DO NF=1,4

            CALL NULEFT( NF, NTE, NOTETR, MXFACO, LEFACO,  NFLEFA )
C           NFLEFA: >0 NO LEFACO DE LA FACE NF DE NTE SI ELLE EST RETROUVEE
C                   =0 SI LA FACE N'EST PAS RETROUVEE

            IF( NFLEFA .GT. 0 .AND. LEFACO(11,NFLEFA) .EQ. NTE ) THEN
C              LE NO DE TETRAEDRE NTE EST RETIRE DE CETTE FACE DE LEFACO
               LEFACO(11,NFLEFA) = 0
            ENDIF

         ENDDO
      ENDIF

      RETURN
      END
