      SUBROUTINE TBAFAS( NBCOOR, NBPOMA, XYZPOI,
     %                   NBSO,   NSPSOM, NBAR,   NSLARE, NBFA, NSSFAC,
     %                   MOARFR, MXARFR, L1ARFR, LAREFR,
     %                   NBBARY, NOBARY, DIBARY,
     %                   NUMXPO, NUMXLI, NUMXSU )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE BARYCENTRE DE CHAQUE ARETE FRONTALIERE,
C -----    CHAQUE FACE, CHAQUE ARETE ET CHAQUE SOMMET
C          CALCULER LA COTE AXONOMETRIQUE DE CES BARYCENTRES
C ENTREES:
C --------
C NBCOOR : NOMBRE DE COORDONNEES D'UN POINT OU NOEUD (3 ou 6)
C NBPOMA : NOMBRE TOTAL DE POINTS DU MAILLAGE
C XYZPOI : XYZ DES POINTS DES EF DU MAILLAGE
C NBSO   : NOMBRE DE SOMMETS IDENTIQUES A DES POINTS DE L'UTILISATEUR
C NSPSOM : NUMERO XYZPOI DU SOMMET ET NO DU POINT
C NBAR   : NOMBRE D' ARETES SUR UNE LIGNE UTILISATEUR
C NSLARE : NUMERO XYZPOI DES 2 SOMMETS ET NO DE LA LIGNE
C NBFA   : NOMBRE DE FACES  SUR UNE SURFACE UTILISATEUR
C NSSFAC : NUMERO XYZPOI DES 3 OU 4 SOMMETS ET NO DE LA SURFACE
C MOARFR : NOMBRE DE MOTS PAR ARETE FRONTALIERE DU TABLEAU LAREFR
C MXARFR : NOMBRE DE FACES DU TABLEAU LAREFR
C L1ARFR : NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
C LAREFR : TABLEAU NUMERO DES 2 SOMMETS ET LIEN
C          LAREFR(1,I)= NO DU 1-ER  SOMMET DE L'ARETE FRONTALIERE
C          LAREFR(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LAREFR(3,I)= 0 OU NUMERO DE L'ARETE FRONTALIERE SUIVANTE
C
C SORTIES:
C --------
C NBBARY : NOMBRE DE BARYCENTRES A TRIER
C NOBARY : NOBARY(I)=I I=1,...,NBSO+NBAR+NBFA ET PUIS NO ARETE DANS ARFR
C DIBARY : COTE AXONOMETRIQUE DES BARYCENTRES
C NUMXPO : NUMERO MAXIMAL DES POINTS   DE L'OBJET
C NUMXLI : NUMERO MAXIMAL DES LIGNES   DE L'OBJET
C NUMXSU : NUMERO MAXIMAL DES SURFACES DE L'OBJET
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1994
C ...................................................................012
      REAL       XYZPOI(1:NBCOOR,1:NBPOMA)
      INTEGER    NSPSOM(2,NBSO)
      INTEGER    NSLARE(3,NBAR)
      INTEGER    NSSFAC(5,NBFA)
      INTEGER    LAREFR(1:MOARFR,1:MXARFR)
      INTEGER    NOBARY(1:*)
      REAL       DIBARY(1:*)
      REAL       XYZ(3)
C
C     LE NUMERO AVANT TRI
      NBSAF = NBSO + NBAR + NBFA
      DO 10 I=1,NBSAF
         NOBARY( I ) = I
 10   CONTINUE
C
C     LE NUMERO MAXIMAL DES POINTS LIGNES SURFACES DE CET OBJET
      NUMXPO = 0
      NUMXLI = 0
      NUMXSU = 0
C
C     LES SOMMETS
      DO 20 I=1,NBSO
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZPOI(1,NSPSOM(1,I)), XYZ )
         DIBARY(I) = XYZ(3)
C
C        LE NUMERO MAXIMAL DES POINTS DE L'OBJET
         NUMXPO = MAX( NUMXPO, NSPSOM(2,I) )
 20   CONTINUE
C
C     LES ARETES
      DO 40 I=1,NBAR
C
C        LES COORDONNEES DU BARYCENTRE DE L'ARETE
         DO 30 K=1,3
C           NSLARE(J,I) NUMERO DU SOMMET J DE L'ARETE I
            XYZ(K)= (XYZPOI(K,NSLARE(1,I)) + XYZPOI(K,NSLARE(2,I)) )*0.5
 30      CONTINUE
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         DIBARY(NBSO+I) = XYZ(3)
C
C        LE NUMERO MAXIMAL DES LIGNES DE L'OBJET
         NUMXLI = MAX( NUMXLI, NSLARE(3,I) )
 40   CONTINUE
C
C     LES FACES
      DO 70 I=1,NBFA
C
C        LES COORDONNEES DU BARYCENTRE DE LA FACE
         IF( NSSFAC(4,I) .EQ. 0 ) THEN
            N = 3
         ELSE
            N = 4
         ENDIF
         XYZ(1) = 0
         XYZ(2) = 0
         XYZ(3) = 0
         DO 60 L=1,N
C           NSSFAC(L,I) NUMERO DU SOMMET L DE LA FACE I
            NS = NSSFAC(L,I)
            DO 50 K=1,3
               XYZ(K)= XYZ(K) + XYZPOI(K,NS)
 50         CONTINUE
 60      CONTINUE
         XYZ(1) = XYZ(1) / N
         XYZ(2) = XYZ(2) / N
         XYZ(3) = XYZ(3) / N
C
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         DIBARY(NBSO+NBAR+I) = XYZ(3)
C
C        LE NUMERO MAXIMAL DES SURFACES DE L'OBJET
         NUMXSU = MAX( NUMXSU, NSSFAC(5,I) )
 70   CONTINUE
C
C     BOUCLE SUR LES ARETES FRONTALIERES
      NBBARY = NBSAF
      N      = L1ARFR
C
 80   IF( N .GT. 0 ) THEN
C
C        L'ARETE N DE LAREFR EST FRONTALIERE
         NBBARY = NBBARY + 1
         NOBARY( NBBARY ) = NBSAF + N
C
C        LES COORDONNEES DU BARYCENTRE DE L'ARETE
         DO 90 K=1,3
C           LAREFR(J,N) NUMERO DU SOMMET J DE L'ARETE FRONTALIERE N
            XYZ(K)= (XYZPOI(K,LAREFR(1,N)) + XYZPOI(K,LAREFR(2,N)) )*0.5
 90      CONTINUE
C
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         DIBARY( NBBARY ) = XYZ(3)
C
C        PASSAGE A L'ARETE FRONTALIERE SUIVANTE
         N = LAREFR(3,N)
         GOTO 80
      ENDIF
      END
