      SUBROUTINE TE2PFACF( NUVOLU, KNMVOLU, QUAMINEX, QTEAME, NOFOTI,
     %                     MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                     HEXAPAVE,NBIPAV,ECHPAV, N1SPAVE, NOPTSUIV,
     %                     NFP,    NBFAPE, NOFAPE,
     %                     N1FASC, INFACO, MXFACO ,LEFACO, NO0FAR,
     %                     IVOLTE, NVOLTE,
     %                     MXTETR, N1TEVI, NOTETR, N1TETS, NUDTETR,
     %                     NBTRCF, NOTRCF,
     %                     MXETOI, NFETOI, NTETOI, LISPOI, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUT DE 2 POINTS SUR LES NORMALES DE CHAQUE FACE DU CF
C -----    ISSUES DE LEUR BARYCENTRE

C ENTREES:
C --------
C NUVOLU : NUMERO DANS LE LEXIQUE DES VOLUMES DU VOLUME A TETRAEDRISER
C KNMVOLU: NOM DU VOLUME A TETRAEDRISER
C QUAMINEX: QUALITE MINIMALE EXIGEE POUR CREER UN TETRAEDRE
C QTEAME : QUALITE DES TETRAEDRES AU DESSOUS DE LAQUELLE UNE
C          AMELIORATION DE LA QUALITE DES TETRAEDRES EST DEMANDEE
C NOFOTI : =1       EXISTENCE DE LA FONCTION UTILISATEUR 'TAILLE_IDEALE'
C          =0 PAS D'EXISTENCE DE LA FONCTION UTILISATEUR 'TAILLE_IDEALE'
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C NPSOFR : =  0  SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C              LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE PT OU FACE
C          = -1 SI LE POINT EST SOMMET D'OT TROP PROCHE PT OU FACE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT DEPLACE SUR LA SURFACE
C             DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE
C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES

C NFP    : NUMERO NOFAPE DE LA FACE PERDUE LEFACO A TRAITER
C NBFAPE : NOMBRE DE FACES PERDUES DE LEFACO
C NOFAPE : NUMERO DES NBFAPE FACES PERDUES
C INFACO : = 0 PAS DE TABLEAU LEFACO NI DE CONSERVATION DES
C              FACES FRONTIERE ( NO DE VOLUME CONNU PAR NVOLTE )
C          = 1 EXISTENCE DU TABLEAU LEFACO ET CONSERVATION DES
C              FACES DE LA FRONTIERE
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES D'OC
C NO0FAR : NUMERO DES 3 SOMMETS DES FACES AJOUTEES AU CF
C IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL
C          1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C NVOLTE : >0 NUMERO DU VOLUME DE 1 A NBVOPA DE CHAQUE TETRAEDRE
C          -1 SI TETRAEDRE INACTIF ou SUPPRIME

C MXTETR : NOMBRE DE TETRAEDRES DECLARABLES DANS NOTETR
C N1TEVI : NO DU PREMIER TETRAEDRE VIDE DANS NOTETR
C N1TETS : N1TETS(NS) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET NS
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C NUDTETR: NU NOTETR DU DERNIER TETRAEDRE ACTIF

C NBTRCF : NOMBRE DE FACES DE NOTRCF
C NOTRCF : >0 NUMERO DANS LEFACO DES TRIANGLES PERDUS  DU CF
C          <0 NUMERO DANS NO0FAR DES TRIANGLES AJOUTES AU CF
C NBSTCF : NOMBRE DE SOMMETS DU CF DES FACES PERDUES
C NOSTCF : NUMERO PTXYZD DES NBSTCF SOMMETS DU CF

C MXETOI : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LE CHAINAGE NFETOI
C NFETOI : VERSION1  FACES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR AYANT CETTE FACE
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3: NON UTILISE ICI
C          4: NUMERO DE CETTE FACE DANS LEFACO, 0 SI PAS DANS LEFACO
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES
C          ou VERSION2
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST DIRIGE VERS L'INTERIEUR DE L'ETOILE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES
C NTETOI : ENTIER (1:MXETOI)
C LISPOI : LISPOI(I)=I ou 0 EN ENTREE POUR PERMETTRE LA PERMUTATION
C          DES POINTS LORSQUE DES TETRAEDRES DEGENERES SONT RENCONTRES

C SORTIES:
C --------
C NBSOMM : NO PTXYZD DU DERNIER SOMMET TETRAEDRISE (AVANT et APRES)
C IERR   : =0  SI PAS D'ERREUR DETECTEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  Saint PIERRE du PERRAY         Novembre 2018
C2345X7..............................................................012
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      CHARACTER*24      KNMVOLU
      DOUBLE PRECISION  PTXYZD(4,*)
      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3)
      INTEGER           NBIPAV(3), N1SPAVE(0:*), NOPTSUIV(1:*)
      INTEGER           NOTETR(8,*), N1TETS(*), NOFAPE(NBFAPE),
     %                  N1FASC(MXSOMM), LEFACO(11,0:MXFACO),NO0FAR(3,*),
     %                  NVOLTE(*), NOTRCF(NBTRCF),
     %                  NFETOI(5,MXETOI), NTETOI(MXETOI),
     %                  LISPOI(0:MXSOMM), NPSOFR(MXSOMM)
      DOUBLE PRECISION  PROSCD, XYZNONF(3), XYZBANF(4), V(3,2), D, C
      INTRINSIC         SQRT

 
      TRACTE0= TRACTE
      IERR   = 0
      INFACO = 1
      NFLPER = NOFAPE( NFP )
      print*,'te2pfacf: NFP=',NFP,' NOFAPE=',NFLPER
      NBPTSUP= 0

C     CALCUL DU BARYCENTRE ET VECTEUR NORMAL AUX NBTRCF FACES NOTRCF
C     --------------------------------------------------------------
      NBSOM0 = NBSOMM
      DO 100 NFCF = 1, NBTRCF

         NF = NOTRCF( NFCF )

C        SOMMET 1 DU TRIANGLE NF DE LEFACO ou NO0FAR
         IF( NF .GT. 0 ) THEN
C           FACE LEFACO
            NS = LEFACO( 1, NF )
         ELSE
C           FACE NO0FAR
            NS = NO0FAR( 1, -NF )
         ENDIF

         IF( NS .LE. 0 ) GOTO 100

C        LA FACE EXISTE: CALCUL DU VECTEUR NORMAL UNITE A LA FACE NF
         DO J=1,2

C           SOMMET 1+J DU TRIANGLE NF DE LEFACO ou NO0FAR
            IF( NF .GT. 0 ) THEN
C              FACE LEFACO
               NSJ = LEFACO( J+1, NF )
            ELSE
C              FACE NO0FAR
               NSJ = NO0FAR( J+1, -NF )
            ENDIF

            DO I=1,3
               V(I,J) = PTXYZD( I, NSJ ) - PTXYZD( I, NS )
            ENDDO

         ENDDO

C        LE VECTEUR NORMAL UNITE A LA FACE NF
         CALL PROVEC( V(1,1) , V(1,2) , XYZNONF )
         D = SQRT( PROSCD( XYZNONF, XYZNONF, 3 ) )
         DO I=1,3
            XYZNONF(I) = XYZNONF(I)  / D
         ENDDO

C        CALCUL DU BARYCENTRE DE LA FACE NF
         DO I=1,4
            XYZBANF(I) = 0D0
            DO J=1,3
C              SOMMET J DU TRIANGLE NF DE LEFACO ou NO0FAR
               IF( NF .GT. 0 ) THEN
C                 FACE LEFACO
                  NSJ = LEFACO( J, NF )
               ELSE
C                 FACE NO0FAR
                  NSJ = NO0FAR( J, -NF )
               ENDIF
               XYZBANF(I) = XYZBANF(I) + PTXYZD(I,NSJ)
            ENDDO
            XYZBANF(I) = XYZBANF(I) / 3D0
         ENDDO

         IF( NOFOTI .GT. 0 ) THEN
C           CALCUL DE LA DISTANCE SOUHAITEE AU  BARYCENTRE DE NF
C           LES 3 PARAMETRES D'APPEL DE LA FONCTION 'TAILLE_IDEALE'
C           EN CE SOMMET XYZ DU REPERE R**3 "NATUREL"
            CALL FONVAL( NOFOTI, 3, XYZBANF, NCODEV, XYZBANF(4) )
            IF( NCODEV .LE. 0 ) THEN
               IERR = 2
               GOTO 9999
            ENDIF
         ENDIF

C        CREATION DE 2 POINTS (UN DE CHAQUE COTE DE LA NORMALE)
C        SUR LA NORMALE MOYENNE DES FACES DU CF
         IF( NBSOMM+2 .GT. MXSOMM ) THEN
            PRINT*,'te2pfacf: PTXYZD SATURE. AUGMENTER MXSOMM=',MXSOMM
            IERR = 1
            GOTO 9999
         ENDIF

C        DISTANCE A LA FACE
         C = XYZBANF(4) / 2

         NBSOMM = NBSOMM + 1
         NPSOFR( NBSOMM ) = 0
         LISPOI( NBSOMM ) = NBSOMM

         DO I=1,3
            D = C * XYZNONF(I)
            PTXYZD(I,NBSOMM  ) = XYZBANF(I) + D
            PTXYZD(I,NBSOMM+1) = XYZBANF(I) - D
         ENDDO

         PTXYZD(4,NBSOMM) = XYZBANF(4)
         IF( NOFOTI .GT. 0 ) THEN
C           CALCUL DE LA DISTANCE SOUHAITEE AU  BARYCENTRE DE NF
C           LES 3 PARAMETRES D'APPEL DE LA FONCTION 'TAILLE_IDEALE'
C           EN CE SOMMET XYZ DU REPERE R**3 "NATUREL"
            CALL FONVAL( NOFOTI, 3, PTXYZD(1,NBSOMM), NCODEV,
     %                   PTXYZD(4,NBSOMM) )
            IF( NCODEV .LE. 0 ) THEN
               IERR = 2
               GOTO 9999
            ENDIF
         ENDIF

         NBSOMM = NBSOMM + 1
         NPSOFR( NBSOMM ) = 0
         LISPOI( NBSOMM ) = NBSOMM
         PTXYZD(4,NBSOMM) = XYZBANF(4)
         IF( NOFOTI .GT. 0 ) THEN
C           CALCUL DE LA DISTANCE SOUHAITEE AU  BARYCENTRE DE NF
C           LES 3 PARAMETRES D'APPEL DE LA FONCTION 'TAILLE_IDEALE'
C           EN CE SOMMET XYZ DU REPERE R**3 "NATUREL"
            CALL FONVAL( NOFOTI, 3, PTXYZD(1,NBSOMM), NCODEV,
     %                   PTXYZD(4,NBSOMM) )
            IF( NCODEV .LE. 0 ) THEN
               IERR = 2
               GOTO 9999
            ENDIF
         ENDIF

 100  ENDDO

C     TETREDRISATION DES POINTS CONTRAINTS NOSOM1 A NOSOM2
C     DU TABLEAU PTXYZD A PARTIR DE LEUR ETOILE
      NDERPt = NBSOM0
 101  NTE0   = N1TETS( NDERPt )
      IF( NTE0 .LE. 0 ) THEN
         NDERPT = NDERPt - 1
         GOTO 101
      ENDIF

      NOSOM1 = NBSOM0 + 1
      NOSOM2 = NBSOMM
      CALL TETRAPTS( NUVOLU, KNMVOLU, QUAMINEX, QTEAME, NOSOM1, NOSOM2,
     %               NTE0,   MXSOMM,  NBSOMM, PTXYZD,   NPSOFR,
     %               HEXAPAVE,NBIPAV,ECHPAV, N1SPAVE,NOPTSUIV,
     %               INFACO, MXFACO, LEFACO, N1FASC,
     %               IVOLTE, NVOLTE,
     %               MXTETR, N1TEVI, NOTETR, N1TETS,
     %               MXETOI, NFETOI, NTETOI, LISPOI,
     %               NUDTETR,NBPTSUP,IERR )

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, NOFAPE, N1TEVI, NUDTETR )

 9999 TRACTE = TRACTE0
      RETURN
      END
