      SUBROUTINE TE3TE2( NOFACO, LEFACO, N1FASC, NOTECF,
     %                   PTXYZD, N1TETS, NOTETR, N1TEVI, NUDTETR,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CHANGEMENT DE 3 TETRAEDRES AYANT UNE ARETE COMMUNE EN
C -----    2 TETRAEDRES AYANT UNE FACE COMMUNE
C          ATTENTION: PAS DE CONTROLE QUE L'ARETE PERCE LA FACE COMMUNE!
C
C ENTREES:
C --------
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO
C LEFACO : FACE=TRIANGLE DE LA PEAU OU DES INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1, VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          LEFACO(10,*) PREMIERE FACE DANS LE HACHAGE
C          LEFACO(11,.) = NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE, 0 SINON
CCCC          LEFACO(12,.) = NO FACEOC DE 1 A NBFACES D'OC
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS
C NOTECF : LES 3 NO NOTETR DES TETRAEDRES AYANT UNE ARETE COMMUNE
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C
C MODIFIES:
C ---------
C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C N1TEVI : NUMERO DU 1 PREMIER TETRAEDRE VIDE DANS LE TABLEAU NOTETR
C          LE CHAINAGE DES TETRAEDRES VIDES SE FAIT SUR NOTETR(5,.)
C NUDTETR: PLUS GRAND NUMERO DANS NOTETR DE TETRAEDRE OCCUPE
C
C SORTIE :
C --------
C IERR   : 0 SI PAS D'ERREUR
C          1 SI SATURATION DU TABLEAU NOTETR => PAS DE CHANGEMENT 3TE=>2TE
C          2 SI PAS D'ARETE COMMUNE AUX 3 TETRAEDRES => PAS DE CHGT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 2005
C....................................................................012
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      INTEGER           LEFACO(11,0:*),
     %                  N1FASC(*),
     %                  NOTECF(3)
      DOUBLE PRECISION  PTXYZD(4,*)
      DOUBLE PRECISION  VOLTET, V
      INTEGER           NOTETR(8,*),
     %                  N1TETS(*),
     %                  NTNEW(2)
      INTEGER           NSF(3), NSA(2), NOSOTR(3), NOSOFATE(3,4)
C     NO DES SOMMETS DES FACES POUR QUE VU DU SOMMET MANQUANT
C     LES SOMMETS SOIENT VUS DANS LE SENS DIRECT
      DATA              NOSOFATE/ 1,2,3, 2,4,3, 3,4,1, 4,2,1 /
C
C     L'ARETE NS1-NS2 DES 3 TETRAEDRES PERFORE T ELLE LA FACE COMMUNE AUX 2 TETR
C     3 TETRAEDRES => 2 TETRAEDRES AVEC UNE FACE LEFACO COMMUNE
C
C     LES 3 SOMMETS DE LA FACE LEFACO
      NSF(1) = LEFACO(1,NOFACO)
      NSF(2) = LEFACO(2,NOFACO)
      NSF(3) = LEFACO(3,NOFACO)
CCC      PRINT *,'TE3TE2: LEFACO(',NOFACO,')=',NSF
CCC            PRINT *,'TE3TE2: NOTETR(',NOTECF(1),')=',
CCC     %                     (NOTETR(KKK,NOTECF(1)),KKK=1,8)
CCC            PRINT *,'TE3TE2: NOTETR(',NOTECF(2),')=',
CCC     %                     (NOTETR(KKK,NOTECF(2)),KKK=1,8)
CCC            PRINT *,'TE3TE2: NOTETR(',NOTECF(3),')=',
CCC     %                     (NOTETR(KKK,NOTECF(3)),KKK=1,8)
      DO 5 M=1,3
C        LE NO DU M-EME SOMMET DE LA FACE PERDUE
C        IL DOIT APPARTENIR A 2 DES 3 TETRAEDRES
         NS  = NSF(M)
         NBS = 0
         DO 2 K=1,3
            NTE = NOTECF(K)
            DO 1 I=1,4
               NSTE = NOTETR(I,NTE)
               IF( NSTE .EQ. NS ) THEN
                  NBS = NBS + 1
                  GOTO 2
               ENDIF
 1          CONTINUE
 2       CONTINUE
         IF( NBS .NE. 2 ) THEN
CCC            PRINT *,'TE3TE2: 1 SOMMET FACE PERDUE NON DANS 2 TETRAEDRES'
            IERR = 2
            RETURN
         ENDIF
 5    CONTINUE
C
C     RECHERCHE DES 2 SOMMETS DE L'ARETE INTERSECTANTE ET COMMUNE AUX 3 TETRAEDR
      N  = 0
      NT = NOTECF(1)
      DO 20 M=1,4
         NS = NOTETR(M,NT)
         IF( NS.NE.NSF(1) .AND. NS.NE.NSF(2) .AND. NS.NE.NSF(3) ) THEN
            IF( N .EQ. 0 ) THEN
C              LE 1-ER SOMMET DE L'ARETE COMMUNE
               NSA(1) = NS
               N = 1
            ELSE
C              LE SECOND SOMMET DE L'ARETE COMMUNE
               NSA(2) = NS
               GOTO 22
            ENDIF
         ENDIF
 20   CONTINUE
C
C     VERIFICATION NSA(1:2) 2 SOMMETS DES 2 AUTRES TETRAEDRES
 22   NS1 = 0
      NS2 = 0
      DO 28 K=2,3
         NT = NOTECF(K)
         DO 26 M=1,4
            NS = NOTETR(M,NT)
            IF( NS .EQ. NSA(1) ) NS1 = NS1 + 1
            IF( NS .EQ. NSA(2) ) NS2 = NS2 + 1
 26      CONTINUE
 28   CONTINUE
      IF( NS1 .NE. 2 .OR. NS2 .NE. 2 ) THEN
         PRINT *,'TE3TE2:ANOMALIE PAS D ARETE COMMUNE AUX 3 TETRAEDRES'
         IERR = 2
         RETURN
      ENDIF
C
C     LES 2 NOUVEAUX TETRAEDRES SONT CONSTRUITS
C     RECHERCHE DE 2 TETRAEDRES VIDES
      DO 10 N=1,2
         IF( N1TEVI .LE. 0 ) THEN
C           SATURATION DES TETRAEDRES
            NBLGRC(NRERR) = 1
            KERR(1) = 'SATURATION DES TETRAEDRES'
            CALL LEREUR
            IERR = 1
            RETURN
         ENDIF
C        MISE A JOUR DU DERNIER TETRAEDRE OCCUPE
         NUDTETR = MAX( NUDTETR, N1TEVI )
C        MISE A JOUR DU 1-ER TETRAEDRE VIDE
         NTNEW(N) = N1TEVI
         N1TEVI   = NOTETR(5,N1TEVI)
 10   CONTINUE
C
      DO 90 K=1,2
C
C        LES 4 SOMMETS DU TETRAEDRE K
         V = VOLTET( PTXYZD(1,NSF(1)), PTXYZD(1,NSF(2)),
     %               PTXYZD(1,NSF(3)), PTXYZD(1,NSA(K)) )
         IF( V .LT. 0 ) THEN
C           ECHANGE DES SOMMETS 2 ET 3 POUR RENDRE LE VOLUME>0
            N      = NSF(2)
            NSF(2) = NSF(3)
            NSF(3) = N
         ENDIF
C
C        LES 4 SOMMETS DU NOUVEAU TETRAEDRE
         NTK = NTNEW(K)
         NOTETR(1,NTK) = NSF(1)
         NOTETR(2,NTK) = NSF(2)
         NOTETR(3,NTK) = NSF(3)
         NOTETR(4,NTK) = NSA(K)
C
C        LE NO DES 4 TETRAEDRES OPPOSES PAR LES FACES A NTK
C        LA FACE 1 EST CELLE DE LEFACO ET LE TETRA OPPOSE EST DANS NTNEW
         NOTETR( 5, NTK ) = NTNEW( MOD(K,2) + 1 )
         NOTETR( 6, NTK ) = 0
         NOTETR( 7, NTK ) = 0
         NOTETR( 8, NTK ) = 0
CCC         PRINT *,'TE3TE2: NSF=',(NSF(KKK),KKK=1,3),' NSA=',NSA
CCC         PRINT *,'NOTETR(',NTK,')=',(NOTETR(KKK,NTK),KKK=1,8)
C
C        LES 3 AUTRES FACES
         DO 50 NF=2,4
C           LES 3 SOMMETS DE LA FACE NF DE NTK
            NOSOTR(1) = NOTETR( NOSOFATE(1,NF), NTK )
            NOSOTR(2) = NOTETR( NOSOFATE(2,NF), NTK )
            NOSOTR(3) = NOTETR( NOSOFATE(3,NF), NTK )
            CALL TRI3NO( NOSOTR, NOSOTR )
            DO 30 N=1,3
               NT1 = NOTECF(N)
               CALL NO1F1T( NOSOTR, NOTETR(1,NT1), NF1 )
               IF( NF1 .GT. 0 ) GOTO 40
 30         CONTINUE
            PRINT *,'TE3TE2: ANOMALIE 30'
            PRINT *,'NSF=',(NSF(KKK),KKK=1,3),' NSA=',NSA
            PRINT *,'NOSOTR=',(NOSOTR(KKK),KKK=1,3)
CCC            CALL CLICSO
            IERR = 2
            RETURN
C
C           LA FACE NF DE NTK EST LA FACE NF1 DE NT1
C           LE NO NOTETR DU TETRAEDRE OPPOSE
 40         NTOP = NOTETR( 4+NF1, NT1 )
            NOTETR( 4+NF, NTK ) = NTOP
C           LA RECIPROQUE POUR NTOP S'IL EXISTE
            IF( NTOP .GT. 0 ) THEN
               CALL NO1F1T( NOSOTR, NOTETR(1,NTOP), NF2 )
               IF( NF2 .GT. 0 ) THEN
                  NOTETR( 4+NF2, NTOP ) = NTK
               ELSE
                  PRINT *,'TE3TE2: ANOMALIE 50'
            PRINT *,'NOTETR(',NTK, ')=',(NOTETR(KKK,NTK),KKK=1,8)
            PRINT *,'NOTETR(',NTOP,')=',(NOTETR(KKK,NTOP),KKK=1,8)
CCC            CALL CLICSO
               ENDIF
            ENDIF
 50      CONTINUE
C
C        MISE A JOUR D'UN TETRAEDRE CONTENANT CHAQUE SOMMET
         N1TETS( NSA(K) ) = NTK
C
C        LES COORDONNEES DU CENTRE DE LA BOULE CIRCONSCRITE
C        AU TETRAEDRE NTK ET CARRE DE SON RAYON
         CALL QV1TET( PTXYZD, NOTETR(1,NTK), V, Q )
CCC         WRITE(IMPRIM,*)'TE3TE2: QUALITE DU TETRAEDRE',NTK,' = ',Q
         IF( Q .LE. 0 ) THEN
C          TETRAEDRE DEGENERE
           WRITE(IMPRIM,10090) NTK,(NOTETR(KL,NTK),KL=1,4)
10090 FORMAT('TE3TE2: TETRAEDRE DEGENERE ',I8,' DE SOMMETS ',4I8)
         ENDIF
C
 90   CONTINUE
C
C     AUTRES MISES A JOUR
      N1TETS( NOTETR(1,NTK) ) = NTK
      N1TETS( NOTETR(2,NTK) ) = NTK
      N1TETS( NOTETR(3,NTK) ) = NTK
C     UN NO DE TETRAEDRE POUR LA FACE LEFACO
      LEFACO( 11, NOFACO ) = NTK
C     UN NO DE FACE LEFACO POUR LES 3 SOMMETS DE LA FACE LEFACO
      N1FASC( NOTETR(1,NTK) ) = NOFACO
      N1FASC( NOTETR(2,NTK) ) = NOFACO
      N1FASC( NOTETR(3,NTK) ) = NOFACO
C
C     DESTRUCTION DES 3 TETRAEDRES DE NOTECF
C     ILS REDEVIENNENT VIDES DANS NOTETR
      DO 150 N=1,3
         NT = NOTECF( N )
         NOTETR(1,NT) = 0
         NOTETR(5,NT) = N1TEVI
         N1TEVI       = NT
 150  CONTINUE
C
      RETURN
      END
