      SUBROUTINE TEABR4( NOFOTI, NUTYSU, ARETMX, PERMT2, MXSOMM,
     %                   NBLFTR, NULFTR, NDARLF,
     %                   NBSOIN, NOSOIN, DISOIN, NBARFR,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   PXYD  , NOARST, NSLIGN,
     %                   NBSOMM, NBSOM,  NBTRIA, NDTRIA,
     %                   ORIGIN, D2D3, XMIN, YMIN, XYMXMI,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRIANGULATION D'UNE SURFACE PLANE DELIMITEE PAR DES ARETES
C -----    FORMANT LA FRONTIERE ET DES POINTS INTERNES IMPOSES,
C          CONSTRUCTION D'UN ARBRE 4 DE TRIANGLES EQUILATERAUX RECOUVRANT
C          SUBDIVISION DES TRIANGLES EQUILATERAUX A PARTIR DES 3 SOMMETS
C          ET DES EVENTUELS POINTS FRONTALIERS OU INTERNES IMPOSES
C          DE LEUR INTERIEUR, REGENERATION DES ARETES FRONTALIERES NON
C          ARETES DE LA TRIANGULATION PUIS AMELIORATION DE LA QUALITE
C          GEOMETRIQUE DES TRIANGLES
C          PRISE EN COMPTE SI ELLE EXISTE DE LA FONCTION
C          TAILLE_IDEALE(X,Y,Z) ENTRE LES 2 SOMMETS DE CHAQUE ARETE
C
C ENTREES:
C --------
C NOFOTI : NUMERO DE LA FONCTION UTILISATEUR TAILLE_IDEALE(x,y,z)
C          0 SI LA FONCTION N'A PAS ETE DONNEE PAR L'UTILISATEUR
C NUTYSU : NUMERO D'OPTION DE GENERATION DU MAILLAGE DE CETTE SURFACE
C          9 APPEL DIRECT A PARTIR DU SP SUEX09
C          1 APPEL PAR LE SP SUEX01-QUNSAL (QUADRANGLE ALGEBRIQUE)
C          3 APPEL PAR LE SP SUEX03        (B-SPLINE POLYNOMIALE )
C          6 APPEL PAR LE SP SUEX06-TRNSAL (TRIANGLE   ALGEBRIQUE)
C         23 APPEL PAR LE SP SUEX23        (TORE AVEC TAILLE_IDEALE)
C ARETMX : LONGUEUR MAXIMALE DES ARETES DES TRIANGLES EQUILATERAUX
C PERMT2 : PERIMETRE DE LA LIGNE ENVELOPPE DANS LE PLAN
C          AVANT MISE A L'ECHELLE A 2**20
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TRIANGULATION
C NBLFTR : NOMBRE DE  LIGNES FERMEES LIMITANT LA SURFACE A TRIANGULER
C NULFTR : NUMERO DES LIGNES FERMEES LIMITANT LA SURFACE A TRIANGULER
C NDARLF : NUMERO DE LA PREMIERE ARETE DE CHAQUE LIGNE FERMEE DANS
C          LE TABLEAU NOSOAR
C NBARFR : NOMBRE D'ARETES  DE LA FRONTIERE OU CONTOUR DU DOMAINE =
C          NOMBRE DE POINTS DE LA FRONTIERE OU CONTOUR DU DOMAINE
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE ET
C          INDICE DANS NOSOAR DE L'ARETE SUIVANTE DANS LE HACHAGE
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXSOAR : NOMBRE MAXIMAL D'ARETES FRONTALIERES DECLARABLES
C
C
C ENTREES ET SORTIES :
C --------------------
C NBSOIN : NOMBRE DE POINTS INTERNES A LA SURFACE FUTUR SOMMET DE LA
C          TRIANGULATION (REMIS A JOUR SI POINTS DOUBLES)
C NOSOIN : NOSOIN(I) NUMERO DANS LE LEXIQUE POINTS DU I-EME POINT
C          INTERNE
C DISOIN : DISOIN(I) DISTANCE SOUHAITEE AVEC LES VOISINS DU POINT
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C          UNE ARETE I DE NOSOAR EST VIDE  <=>  NOSOAR(1,I)=0
C NOSOAR : NUMERO DES 2 SOMMETS DE CHAQUE ARETE ET
C          POINTEUR SUR L'ARETE SUIVANTE
C
C    ATTENTION: UNE ARETE DOIT ETRE LA SUIVANTE DE LA PRECEDENTE
C    ---------- OU LA PREMIERE D'UNE COMPOSANTE CONNEXE DE LA
C               FRONTIERE  OU LA DERNIERE
C
C SORTIES:
C --------
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C
C PXYD   : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  DISTANCE_SOUHAITEE
C          TABLEAU REEL2(3,MXSOMM)
C
C NOARST : NOARST(I) NUMERO NOSOAR D'UNE ARETE DU SOMMET I
C
C NSLIGN : TABLEAU DU NUMERO DE SOMMET DANS SA LIGNE POUR CHAQUE
C          SOMMET FRONTALIER
C          NUMERO DU POINT DANS LE LEXIQUE POINT SI INTERNE IMPOSE
C          0 SI LE POINT EST INTERNE NON IMPOSE PAR L'UTILISATEUR
C         -1 SI LE SOMMET EST EXTERNE AU DOMAINE
C
C NBSOMM : NOMBRE DE SOMMETS INTERNES + EXTERNES APRES TRIANGULATION
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C NDTRIA : NUMERO MAXIMAL DANS NOARTR D'UN TRIANGLE INTERNE
C ORIGIN : POINT ORIGINE DANS LE PLAN DE MAILLAGE
C D2D3   : MATRICE DE PASSAGE DES COORDONNEES 3D EN COORDONNEES 2D
C XMIN   : ABSCISSE MINIMALE APRES TRANSFORMATION 3D->2D
C YMIN   : ORDONNEE MINIMALE APRES TRANSFORMATION 3D->2D
C XYMXMI : ECART MAXIMAL ENTRE XMAX-XMIN ET YMAX-YMIN
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION FINALE
C IERR   :  0 SI PAS D'ERREUR
C          51 SATURATION DU TABLEAU LETREE
C          52 SATURATION DES SOMMETS DANS LE TABLEAU PXYD
C           2 SATURATION DES ARETES
C           3 SATURATION DES TRIANGLES
C           4 PILE SATUREE DES ARETES FRONTALIERES NON RETROUVEES
C           5 PILE SATUREE DES ARETES EXTERIEURES AU DOMAINE
C           6 EXISTENCE D'ARETES PERDUES STOCKEES DANS NTETOI (CF LETREE)
C           7 TOUS LES POINTS SONT ALIGNES
C           8 AUCUN CERCLE CIRCONSCRIT AUX TRIANGLES ACTUELS NE CONTIENT
C             LE POINT COURANT
C           9 TABLEAU NOSOAR DE TAILLE INSUFFISANTE CAR TROP D'ARETES
C             PERDUES
C          10 LIGNE ENVELOPPE INCORRECTE
C          11 2 EXTREMITES CONFONDUES POUR UNE ARETE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC        MAI 1997
C....................................................................012
      IMPLICIT INTEGER (W)
      include"./incl/a___xyzsommet.inc"
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/trvari.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
C     LA LONGUEUR DES ARETES DE LA LIGNE ENVELOPPE DANS R**3
      COMMON / PEL1R3 / PERMT3
      LOGICAL           TRATRI
      COMMON / DV2DCO / TRATRI
C     TRACE OU NON DES TRIANGLES GENERES DANS LA TRIANGULATION
C
C     LES PARAMETRES D'ENTREE ET SORTIE
      INTEGER           NOSOAR(MOSOAR,MXSOAR),
     %                  NSLIGN(MXSOMM),
     %                  NULFTR(1:NBLFTR),
     %                  NDARLF(1:NBLFTR),
     %                  NOARST(MXSOMM),
     %                  NOSOIN(NBSOIN)
      REAL              DISOIN(NBSOIN)
      DOUBLE PRECISION  DINFO, TCPU, D, RAP2P3
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
C
C     LES PARAMETRES RESULTATS
      INTEGER           NOARTR(MOARTR,MXARTR)
      DOUBLE PRECISION  PXYD(3,MXSOMM)
      REAL              COMXMI(3,2),
     %                  ORIGIN(3)
      DOUBLE PRECISION  D2D3(3,3)
C
      INTEGER           NOSOTR(3)
      EQUIVALENCE      (NOSOTR(1),NS1), (NOSOTR(2),NS2),
     %                 (NOSOTR(3),NS3)

cccC     TRACE OU NON DES TRIANGLES GENERES
ccc      TRATRI = .TRUE.
ccc      TRATRI = .FALSE.

C     AU DEBUT PAS D'ERREUR
      IERR = 0
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10000)
      ELSE
         WRITE(IMPRIM,20000)
      ENDIF
10000 FORMAT(' TRIANGULATION d''ARBRE-4 de TE dans un PLAN de R3')
20000 FORMAT(' TRIANGULATION of REGULAR TRIANGLE QUADTREE in a PLANE of 
     %R3')
C
C     INITIALISATIONS DES POINTS INTERNES ET DES ARETES FRONTALIERES
C     VALEUR DE LA TAILLE SOUHAITEE AUTOUR DES FUTURS SOMMETS
C     RENUMEROTATION GLOBALE DES SOMMETS POUR LA TRIANGULATION
C     ==============================================================
      CALL TEQINI( NOFOTI, MXSOMM, NBLFTR, NDARLF,
     %             NBARFR, NSLIGN,
     %             NBSOIN, NOSOIN, DISOIN,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             PXYD  , NBARPI,
     %             ORIGIN, D2D3  , COMXMI, AREMIN, AREMAX,
     %             XMIN  , YMIN  , XYMXMI, ARETMX, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C     ICI LE TABLEAU PXYD N'A PAS DE SOMMETS IDENTIQUES

      IF( TRATRI ) THEN
C        LES TRACES SONT DEMANDES
         CALL EFFACE
C        LE CADRE OBJET GLOBAL APRES MISE A L'ECHELLE EN 2D
         XE = ( COMXMI(1,2) - COMXMI(1,1) ) / 18
         YE = ( COMXMI(2,2) - COMXMI(2,1) ) / 18
         CALL ISOFENETRE( COMXMI(1,1)-XE, COMXMI(1,2)+XE,
     %                    COMXMI(2,1)-YE, COMXMI(2,2)+YE )
      ENDIF

      D    = DINFO('DELTA CPU')
      TCPU = D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10002) TCPU
      ELSE
         WRITE(IMPRIM,20002) TCPU
      ENDIF
10002 FORMAT(/' TEMPS COHERENCE des DONNEES',T60,':',F11.2,' SECONDES')
20002 FORMAT(/' TIME for INPUT COHERENCE',T60,':',F11.2,' SECONDS')
C
C     CREATION DE L'ARBRE-4 DES TE (TABLEAU LETREE)
C     AJOUT DANS LES TE DES SOMMETS DES LIGNES ET DES POINTS INTERNES IMPOSES
C     =======================================================================
C     PREMIERE ESTIMATION DE MXTREE
      MXTREE = 3 * MXSOMM
C
 5    MNTREE = 0
C     REINITIALISATION EN CAS D'AUGMENTATION DE MXTREE
      NBSOMM = NBARPI
      CALL TNMCDC( 'ENTIER', 9*(1+MXTREE), MNTREE )
      CALL TEAJTE( MXSOMM, NBSOMM, PXYD, COMXMI,
     %             ARETMX, MXTREE, MCN(MNTREE),
     %             IERR )
      IF( IERR .EQ. 51 ) THEN
C        SATURATION DE LETREE => SA TAILLE EST AUGMENTEE
C        DESTRUCTION DES 2 TABLEAUX AUXILIAIRES
         CALL TNMCDS( 'ENTIER', 9*(1+MXTREE), MNTREE )
         MXTREE = MXTREE * 2
         IERR   = 0
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,*) 'NOUVELLE VALEUR DE MXTREE =',MXTREE
         ELSE
            WRITE(IMPRIM,*) 'NEW VALUE of MXTREE =',MXTREE
         ENDIF
         GOTO 5
      ENDIF
C
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10005) D
      ELSE
         WRITE(IMPRIM,20005) D
      ENDIF
10005 FORMAT(' TEMPS AJOUT ARBRE-4 DES TRIANGLES EQUILATERAUX',
     %         T60,':',F11.2,' SECONDES' )
20005 FORMAT(' TIME to ADD QUADTREE of REGULAR TRIANGLES',
     %         T60,':',F11.2,' SECONDS' )
      IF( IERR .NE. 0 ) GOTO 9999
C     ICI LE TABLEAU PXYD CONTIENT LES SOMMETS DES TE ET
C     LES POINTS FRONTALIERS ET INTERNES
C
C     HOMOGENEISATION DE L'ARBRE DES TE A UN SAUT DE TAILLE AU PLUS
C     PRISE EN COMPTE DES DISTANCES SOUHAITEES AUTOUR DES SOMMETS INITIAUX
C     ====================================================================
C     RESERVATION DE LA QUEUE POUR PARCOURIR LES TE DE L'ARBRE
      CALL TNMCMX( 'ENTIER', MXQUEU )
      MXQUEU = NINT( MXQUEU * 0.75 )
      MXQUEU = MIN( MXTREE, MXQUEU )
      CALL TNMCDC( 'ENTIER', MXQUEU, MNQUEU )

C     RAPPORT DES PERIMETRES DES ARETES DE LA LIGNE ENVELOPPE DE R2 SUR R3
      IF( NOFOTI .LE. 0 .OR. NUTYSU .EQ. 9 .OR. NUTYSU .EQ. 23 ) THEN
         RAP2P3 = 1D0
      ELSE
C        LE PERIMETRE DE LA LIGNE ENVELOPPE EST CALCULEE DANS SUEX01 03 06
         RAP2P3 = PERMT2 / PERMT3
      ENDIF

      CALL TEHOTE( NOFOTI, NUTYSU, RAP2P3,
     %             NBARPI, MXSOMM, NBSOMM, PXYD,
     %             ORIGIN, D2D3, XMIN, YMIN, XYMXMI,
     %             COMXMI, ARETMX,
     %             MCN(MNTREE), MXQUEU, MCN(MNQUEU),
     %             IERR )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10006) D
      ELSE
         WRITE(IMPRIM,20006) D
      ENDIF
10006 FORMAT(' TEMPS ADAPTATION ET HOMOGENEISATION ARBRE-4 DES TE',
     %         T60,':',F11.2,' SECONDES' )
20006 FORMAT(' TIME ADAPTATION  and HOMOGENEIZATION of QUADTREE',
     %         T60,':',F11.2,' SECONDS' )

      IF( IERR .NE. 0 ) THEN
C        DESTRUCTION DU TABLEAU AUXILIAIRE ET DE L'ARBRE
         CALL TNMCDS( 'ENTIER', MXQUEU, MNQUEU )
         CALL TNMCDS( 'ENTIER', 9*(1+MXTREE), MNTREE )
         IF( IERR .EQ. 51 ) THEN
C           LETREE SATURE
            MXTREE = MXTREE * 2
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,*) 'NOUVELLE VALEUR DE MXTREE =',MXTREE
            ELSE
               WRITE(IMPRIM,*) 'NEW VALUE of MXTREE =',MXTREE
            ENDIF
            IERR = 0
            GOTO 5
         ELSE
            GOTO 9999
         ENDIF
      ENDIF
C
C     TRIANGULER LES TRIANGLES EQUILATERAUX FEUILLES A PARTIR DE LEURS 3 SOMMETS
C     ET DES POINTS DE LA FRONTIERE, DES POINTS INTERNES IMPOSES INTERIEURS
C     ==========================================================================
      CALL TETRTE( COMXMI, ARETMX, NBARPI, MXSOMM, PXYD,
     %             MXQUEU, MCN(MNQUEU),    MCN(MNTREE),
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             IERR  )
C     DESTRUCTION DE LA QUEUE ET DE L'ARBRE DEVENUS INUTILES
      CALL TNMCDS( 'ENTIER', MXQUEU, MNQUEU )
      CALL TNMCDS( 'ENTIER', 9*(1+MXTREE), MNTREE )
C     IERR =0 SI PAS D'ERREUR
C          =1 SI LE TABLEAU NOSOAR EST SATURE
C          =2 SI LE TABLEAU NOARTR EST SATURE
C          =3 SI AUCUN DES TRIANGLES NE CONTIENT L'UN DES POINTS INTERNES D'UN T
C          =5 SI SATURATION DE LA QUEUE DE PARCOURS DE L'ARBRE DES TE
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10007) D
      ELSE
         WRITE(IMPRIM,20007) D
      ENDIF
10007 FORMAT(' TEMPS TRIANGULATION DES TE',T60,':',F11.2,' SECONDES' )
20007 FORMAT(' TIME TRIANGULATION of REGULAR TRIANGLES',T60,':',F11.2,
     %' SECONDS' )
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCNOIR, NCBLAN,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     BOUCLE SUR LES ARETES INTERNES (NON SUR UNE LIGNE DE LA FRONTIERE)
C     AVEC ECHANGE DES 2 DIAGONALES AFIN DE RENDRE LA TRIANGULATION DELAUNAY
C     ======================================================================
C     FORMATION DU CHAINAGE 6 DES ARETES INTERNES A ECHANGER EVENTUELLEMENT
      CALL AISOAR( MOSOAR, MXSOAR, NOSOAR, NA )
      CALL TEDELA( PXYD,   NOARST,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NA,
     %             MOARTR, MXARTR, NOARTR, MODIFS )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) 'NOMBRE ECHANGES DIAGONALES =',MODIFS
         WRITE(IMPRIM,10011) D
      ELSE
         WRITE(IMPRIM,*) 'SWAPPING DIAGONAL NUMBER =',MODIFS
         WRITE(IMPRIM,20011) D
      ENDIF
10011 FORMAT(' TEMPS DELAUNAY DES DIAGONALES INTERNES',T60,':',F11.2,
     %       ' SECONDES' )
20011 FORMAT(' TIME DELAUNAY SWAPPING INTERNAL DIAGONALS',T60,':',F11.2,
     %       ' SECONDS' )
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCBLAN, NCBLEU,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     DETECTION DES ARETES FRONTALIERES INITIALES PERDUES
C     TRIANGULATION FRONTALE POUR LES RESTAURER
C     ===================================================
      MXARCF = MXSOMM / 5
      MNARCF = 0
      CALL TNMCDC( 'ENTIER', MXARCF*6+1, MNARCF )
      CALL TEREFR( NBARPI, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             MXARCF, MCN(MNARCF+MXARCF*5), MCN(MNARCF+MXARCF*2),
     %             MCN(MNARCF), MCN(MNARCF+MXARCF),
     %             NBARPE, IERR )
      CALL TNMCDS( 'ENTIER', MXARCF*6+1, MNARCF)
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10040) NBARPE
      ELSE
         WRITE(IMPRIM,20040) NBARPE
      ENDIF
10040 FORMAT(' RESTAURATION de',I7,' ARETES PERDUES DE LA FRONTIERE' )
20040 FORMAT(' RECOVERING of',I7,' LOST EDGES of the BOUNDARY' )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10045) D
      ELSE
         WRITE(IMPRIM,20045) D
      ENDIF
10045 FORMAT(' TEMPS RECUPERATION DES ARETES PERDUES DE LA FRONTIERE',
     %         T60,':',F11.2,' SECONDES')
20045 FORMAT(' TIME RECUPERATION of LOST EDGES of the BOUNDARY',
     %         T60,':',F11.2,' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCBLEU, NCCYAN,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C     FIN DE LA TRIANGULATION AVEC RESPECT DES ARETES INITIALES FRONTALIERES
C
C     SUPPRESSION DES TRIANGLES EXTERNES AU DOMAINE
C     =============================================
CCC      WRITE(IMPRIM,10050)
CCC10050 FORMAT(' SUPPRESSION DES TRIANGLES EXTERNES')
C     RECHERCHE DU DERNIER TRIANGLE UTILISE
      DO NDTRIA=MXARTR,1,-1
         IF( NOARTR(1,NDTRIA) .NE. 0 ) GOTO 58
      ENDDO

 58   MNTRSU = 0
      CALL TNMCDC( 'ENTIER', NDTRIA, MNTRSU )
      CALL TESUEX( NBLFTR, NULFTR,
     %             NDTRIA, NBSOMM, PXYD,   NSLIGN,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             NBTRIA, MCN(MNTRSU), IERR )
      CALL TNMCDS( 'ENTIER', NDTRIA, MNTRSU )

      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10060) D
      ELSE
         WRITE(IMPRIM,20060) D
      ENDIF
10060 FORMAT(' TEMPS SUPPRESSION DES TRIANGLES EXTERNES',
     %         T60,':',F11.2,' SECONDES')
20060 FORMAT(' TIME SUPPRESSION of EXTERNAL TRIANGLES',
     %         T60,':',F11.2,' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCBEIG, NCMAGE,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     AMELIORATION DE LA QUALITE DE LA TRIANGULATION PAR
C     BARYCENTRAGE DES SOMMETS INTERNES A LA TRIANGULATION
C     SUPPRESSION DES ARETES TROP LONGUES OU TROP COURTES
C     MODIFICATION DE LA TOPOLOGIE DES GROUPES DE TRIANGLES
C     MISE EN DELAUNAY DE LA TRIANGULATION
C     =====================================================
CCC      WRITE(IMPRIM,*)
CCC      WRITE(IMPRIM,*) 'DEBUT DE L''AMELIORATION DE LA QUALITE'
      MXARCF = MXSOMM / 10
      MNARCF = 0
      CALL TNMCDC( 'ENTIER', 7*MXARCF+1, MNARCF )
      CALL TEAMQT( NOFOTI, NUTYSU, RAP2P3,
     %             NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR,
     %             MXARCF, MCN(MNARCF), MCN(MNARCF+MXARCF),
     %             MCN(MNARCF+6*MXARCF), MCN(MNARCF+3*MXARCF),
     %             MCN(MNARCF+2*MXARCF),
     %             ORIGIN, D2D3,   XMIN,   YMIN,  XYMXMI,
     %             NBARFR, NBARPI, NBSOMM, MXSOMM,
     %             PXYD, NSLIGN, IERR )
      CALL TNMCDS( 'ENTIER', 7*MXARCF+1, MNARCF )
C
      IF( IERR .EQ.  -13 ) IERR=0
C     MODIF 6/10/2006 ARRET DE L'AMELIORATION APRES BOUCLE INFINIE DANS CAETOI
C
      IF( IERR .NE. 0 ) GOTO 9999
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10065) D
      ELSE
         WRITE(IMPRIM,20065) D
      ENDIF
10065 FORMAT(' TEMPS AMELIORATION DE LA QUALITE DE LA TRIANGULATION',
     %         T60,':',F11.2,' SECONDES')
20065 FORMAT(' TIME IMPROVEMENT of TRIANGULATION QUALITY',
     %         T60,':',F11.2,' SECONDS')
C
C     TRACE DE LA TRIANGULATION FINALE
      CALL TETRMA( NCCYAN, NCBLEU,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     =======================
C     FIN DE LA TRIANGULATION
C     =======================
C
C     RENUMEROTATION DES SOMMETS INTERNES: NOARST(I)=NUMERO FINAL DU SOMMET
C     ===================================
      DO I=1,NBSOMM
         NOARST(I) = 0
      ENDDO

      NBTRIA = 0
      DO NT=1,MXARTR
         IF( NOARTR(1,NT) .NE. 0 ) THEN
            NBTRIA = NBTRIA + 1
            NDTRIA = NT
C           LE NUMERO DES 3 SOMMETS DU TRIANGLE NT
            CALL NUSOTR( NT, MOSOAR, NOSOAR, MOARTR, NOARTR,
     %                   NOSOTR )
C           LES 3 SOMMETS DU TRIANGLE SONT ACTIFS
            DO I=1,3
               NOARST( NOSOTR(I) ) = 1
            ENDDO
         ENDIF
      ENDDO

      NBSOM = 0
      DO I=1,NBSOMM
         IF( NOARST(I) .GT. 0 ) THEN
            NBSOM = NBSOM + 1
            NOARST(I) = NBSOM
         ENDIF
      ENDDO
C
C     IMPRESSION DU NOMBRE DE SOMMETS ET TRIANGLES
C     ============================================
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10093) TCPU, NBSOM, NBTRIA
      ELSE
         WRITE(IMPRIM,20093) TCPU, NBSOM, NBTRIA
      ENDIF
10093 FORMAT(' TEMPS TOTAL DE LA TRIANGULATION',T60,':',F11.2,
     %       ' SECONDES'/
     %       ' NOMBRE FINAL DE SOMMETS  =',I10/
     %       ' NOMBRE FINAL DE TRIANGLES=',I10 )
20093 FORMAT(' TRIANGULATION TOTAL TIME',T60,':',F11.2,
     %       ' SECONDS'/
     %       ' FINAL VERTICES  NUMBER=',I10/
     %       ' FINAL TRIANGLES NUMBER=',I10 )
C
 9999 RETURN
      END
