      SUBROUTINE TEAMQT( NOFOTI, NUTYSU, RAP2P3,
     %                   NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   MXARCF, NOTRCF, NOSTBO,
     %                   N1ARCF, NOARCF, LARMIN,
     %                   ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
     %                   NBDPFR, NBDPII, NBSOMM, MXSOMM,
     %                   PXYD,   NSLIGN,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AMELIORATION DE LA QUALITE DE LA TRIANGULATION
C -----    ISSUE de TEABR4 ou de TRLFPI
C
C ENTREES:
C --------
C NOFOTI : NUMERO DANS LE LX DES FONCTIONS DE LA FONCTION TAILLE_IDEALE(X,Y,Z)
C          >0 SI ELLE EXISTE ET 0 SINON
C NUTYSU : NUMERO D'OPTION DE GENERATION DU MAILLAGE DE CETTE SURFACE
C          9 APPEL DIRECT A PARTIR DU SP SUEX09
C         19 APPEL DIRECT A PARTIR DU SP SUEX19
C          1 APPEL PAR LE SP SUEX01-QUNSAL (QUADRANGLE ALGEBRIQUE)
C          3 APPEL PAR LE SP SUEX03        (B-SPLINE POLYNOMIALE )
C          6 APPEL PAR LE SP SUEX06-TRNSAL (TRIANGLE   ALGEBRIQUE)
C RAP2P3 : RAPPORT DU PERIMETRE DE L'ENVELOPPE DU DOMAINE PLAN SUR
C                  LE PERIMETRE DE L'ENVELOPPE DU DOMAINE DE R**3
C          APPROXIMATION POUR CALCULER RAPIDEMENT LA TAILLE DE L'ARETE
C          DANS LE PLAN CONNAISSANT SA TAILLE DANS R**3
C NOARST : NOARST(I) NUMERO D'UNE ARETE DE SOMMET I
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE ET
C          INDICE DANS NOSOAR DE L'ARETE SUIVANTE DANS LE HACHAGE
C MXSOAR : NOMBRE MAXIMAL D'ARETES FRONTALIERES DECLARABLES
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXARTR : NOMBRE MAXIMAL DE TRIANGLES DECLARABLES DANS NOARTR
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C MXARCF : NOMBRE MAXIMAL DE TRIANGLES EMPILABLES
C NBDPFR : NUMERO DU DERNIER SOMMET FRONTALIER
C NBDPII : NUMERO DU DERNIER INTERNE IMPOSE
C          =NBDPFR SI PAS DE POINT INTERNE IMPOSE
C NSLIGN : TABLEAU DU NUMERO DE SOMMET DANS SA LIGNE POUR CHAQUE
C          SOMMET FRONTALIER
C          NUMERO DU POINT DANS LE LEXIQUE POINT SI INTERNE IMPOSE
C          0 SI LE POINT EST INTERNE NON IMPOSE PAR L'UTILISATEUR
C         -1 SI LE SOMMET EST EXTERNE AU DOMAINE
C
C MODIFIES :
C ----------
C NBSOMM : NOMBRE ACTUEL DE SOMMETS DE LA TRIANGULATION
C          (CERTAINS SOMMETS INTERNES ONT ETE DESACTIVES OU AJOUTES)
C PXYD   : TABLEAU DES COORDONNEES 2D DES POINTS
C
C AUXILIAIRES:
C ------------
C NOTRCF : TABLEAU ( MXARCF ) AUXILIAIRE D'ENTIERS
C          NUMERO DANS NOARTR DES TRIANGLES DE SOMMET NS
C NOSTBO : TABLEAU ( MXARCF ) AUXILIAIRE D'ENTIERS
C          NUMERO DANS PXYD DES SOMMETS DES ARETES SIMPLES DE LA BOULE
C N1ARCF : TABLEAU (0:MXARCF) AUXILIAIRE D'ENTIERS
C NOARCF : TABLEAU (3,MXARCF) AUXILIAIRE D'ENTIERS
C LARMIN : TABLEAU ( MXARCF ) AUXILIAIRE D'ENTIERS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE UPMC PARIS       JUIN 1997
C MODIFS : ALAIN PERRONNET  LJLL UPMC & St PIERRE DU PERRAY    MARS 2008
C....................................................................012
C     PARAMETER       ( QUAMAL=0.3 ) => OK
C     PARAMETER       ( QUAMAL=0.4 ) => PB POUR LE TEST OCEAN
C     PARAMETER       ( QUAMAL=0.5 ) => PB POUR LE TEST OCEAN
      PARAMETER       ( QUAMAL=0.2 )
C     QUAMAL=0.2 EST CHOISI POUR NE PAS TROP DETRUIRE DE SOMMETS
C     SEUIL DE QUALITE D'UN TRIANGLE AU DESSOUS DUQUEL UN DE SES SOMMETS
C     PEUT ETRE DETRUIT
C
      include"./incl/trvari.inc"
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
C
      DOUBLE PRECISION  PXYD(3,*), RAP2P3, D2D3(3,3)
      REAL              ORIGIN(3)
ccc      DOUBLE PRECISION  DINFO, TCPU, D
      INTEGER           NOARTR(MOARTR,*),
     %                  NOSOAR(MOSOAR,*),
     %                  NOARST(*),
     %                  NOTRCF(MXARCF),
     %                  NSLIGN(*),
     %                  NOSTBO(MXARCF),
     %                  N1ARCF(0:MXARCF),
     %                  NOARCF(3,MXARCF),
     %                  LARMIN(MXARCF)
C
      IERR = 0
ccc      D    = DINFO('DELTA CPU')
ccc      TCPU = 0D0
C
C     SUPPRIMER DE LA TRIANGULATION LES TRIANGLES DE QUALITE
C     INFERIEURE A QUAMAL
C     ======================================================
      CALL TESUQM( QUAMAL, NBDPII, PXYD,   NOARST,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR,
     %             MXARCF, N1ARCF, NOARCF,
     %             LARMIN, NOTRCF, NOSTBO,
     %             QUAMIN )
ccc      D    = DINFO('DELTA CPU')
ccc      TCPU = TCPU + D
ccc      print *,'Sortie tesuqm:',D,' secondes cpu'
C
C     SUPPRESSION DES SOMMETS DE TRIANGLES TROP PROCHES
C     D'UN SOMMET FRONTALIER OU D'UN POINT INTERNE IMPOSE PAR
C     TRIANGULATION FRONTALE DE L'ETOILE ET MISE EN DELAUNAY
C     =======================================================
      IF( QUAMIN .LT. QUAMAL ) THEN
         CALL TESUSP( QUAMAL, NBDPFR, NBDPII, PXYD,   NOARST,
     %                MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                MOARTR, MXARTR, N1ARTR, NOARTR,
     %                MXARCF, N1ARCF, NOARCF,
     %                LARMIN, NOTRCF, NOSTBO,
     %                IERR )
ccc         D    = DINFO('DELTA CPU')
ccc         TCPU = TCPU + D
ccc         print *,'Sortie tesusp:',D,' secondes cpu'
         IF( IERR .NE. 0 ) GOTO 9999
      ENDIF
C
C     AJUSTAGE DES TAILLES MOYENNES DES ARETES AVEC AMPLI=1.34D0 ENTRE
C     AMPLI/2 x TAILLE_SOUHAITEE ET AMPLI x TAILLE_SOUHAITEE
C     + BARYCENTRAGE DES SOMMETS ET MISE EN TRIANGULATION DELAUNAY
C     ================================================================
C     TABLEAU DE LA QUALITE MINIMALE DES TRIANGLES DE CHAQUE SOMMET
      MCQMST = 0
      CALL TNMCDC( 'REEL',   MXSOMM, MCQMST )
      MCNOAN = 0
      CALL TNMCDC( 'ENTIER', MXSOMM, MCNOAN )
      CALL TEAMQST(NOFOTI, NUTYSU, RAP2P3,
     %             NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR,
     %             MXARCF, NOTRCF, NOSTBO,
     %             N1ARCF, NOARCF, LARMIN,
     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
     %             NBDPFR, NBDPII, NBSOMM, MXSOMM, PXYD, NSLIGN,
     %             RMCN(MCQMST), MCN(MCNOAN),
     %             IERR )
      CALL TNMCDS( 'REEL',   MXSOMM, MCQMST )
      CALL TNMCDS( 'ENTIER', MXSOMM, MCNOAN )
ccc         D    = DINFO('DELTA CPU')
ccc         TCPU = TCPU + D
ccc         print *,'Sortie teamqst:',D,' secondes cpu'
      IF( IERR .NE. 0 ) GOTO 9999
C
cccC     AJUSTAGE DES TAILLES MOYENNES DES ARETES AVEC AMPLI=1.34D0 ENTRE
cccC     AMPLI/2 x TAILLE_SOUHAITEE ET AMPLI x TAILLE_SOUHAITEE
cccC     + BARYCENTRAGE DES SOMMETS ET MISE EN TRIANGULATION DELAUNAY
cccC     ================================================================
ccc      CALL TEAMQA( NOFOTI, NUTYSU, RAP2P3,
ccc     %             NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
ccc     %             MOARTR, MXARTR, N1ARTR, NOARTR,
ccc     %             MXARCF, NOTRCF, NOSTBO,
ccc     %             N1ARCF, NOARCF, LARMIN,
ccc     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
ccc     %             NBDPFR, NBDPII, NBSOMM, MXSOMM, PXYD, NSLIGN,
ccc     %             IERR )
ccc      D    = DINFO('DELTA CPU')
ccc      TCPU = TCPU + D
ccc      print *,'Sortie teamqa:',D,' secondes cpu'
ccc      IF( IERR .NE. 0 ) GOTO 9999
cccC
CCCC     CCC le 17 mars 2006 sur l'appel de teamsf car mauvais triangles
CCCC     MODIFICATION DE LA TOPOLOGIE AUTOUR DES SOMMETS FRONTALIERS
CCCC     POUR AVOIR UN NOMBRE DE TRIANGLES EGAL A L'ANGLE/60 DEGRES
CCCC     ET MISE EN TRIANGULATION DELAUNAY LOCALE
CCCC     ===========================================================
CCC      CALL TEAMSF( NOFOTI, NUTYSU, RAP2P3,
CCC     %             NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
CCC     %             MOARTR, MXARTR, N1ARTR, NOARTR,
CCC     %             MXARCF, NOTRCF,
CCC     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
CCC     %             COMXMI, NBDPFR, NBSOMM, MXSOMM, PXYD, NSLIGN,
CCC     %             IERR )
CCC      IF( IERR .NE. 0 ) GOTO 9999
C
C     QUELQUES ITERATIONS DE BARYCENTRAGE DES POINTS INTERNES
C     MODIFICATION DE LA TOPOLOGIE POUR AVOIR 4 OU 5 OU 6 TRIANGLES
C     POUR CHAQUE SOMMET DE LA TRIANGULATION
C     ET MISE EN TRIANGULATION DELAUNAY
C     =============================================================
      CALL TEAMQS( NOFOTI, NUTYSU, RAP2P3,
     %             NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR,
     %             MXARCF, NOTRCF, NOSTBO,
     %             N1ARCF, NOARCF, LARMIN,
     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
     %             NBDPFR, NBDPII, NBSOMM, PXYD, NSLIGN,
     %             IERR )
ccc      D    = DINFO('DELTA CPU')
ccc      TCPU = TCPU + D
ccc      print *,'Sortie teamqs:',D,' secondes cpu'
ccc      print *,'Amelioration :',TCPU,' secondes cpu au total'
C
 9999 RETURN
      END
