      SUBROUTINE TESUSP( QUAMAL, NBDPFR, NBDPII, PXYD,   NOARST,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   MXARCF, N1ARCF, NOARCF, LARMIN, NOTRCF, LIARCF,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   SUPPRIMER DE LA TRIANGULATION LES SOMMETS DE TE TROP PROCHES
C -----   SOIT D'UN SOMMET FRONTALIER OU POINT INTERNE IMPOSE
C         SOIT D'UNE ARETE FRONTALIERE
C
C         ATTENTION: LE CHAINAGE LCHAIN DE NOSOAR DEVIENT CELUI DES CF
C
C ENTREES:
C --------
C QUAMAL : QUALITE DES TRIANGLES AU DESSOUS DE LAQUELLE DES SOMMETS
C          SONT A SUPPRIMER
C NBDPFR : NUMERO DU DERNIER POINT SUR LA FRONTIERE
C NBDPII : NUMERO DU DERNIER POINT INTERNE IMPOSE PAR L'UTILISATEUR
C PXYD   : TABLEAU DES COORDONNEES 2D DES POINTS
C          PAR POINT : X  Y  DISTANCE_SOUHAITEE
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE ET
C          INDICE DANS NOSOAR DE L'ARETE SUIVANTE DANS LE HACHAGE
C MXSOAR : NOMBRE MAXIMAL D'ARETES STOCKABLES DANS LE TABLEAU NOSOAR
C          ATTENTION: MXSOAR>3*MXSOMM OBLIGATOIRE!
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXARCF : NOMBRE DE VARIABLES DES TABLEAUX N1ARCF, NOARCF, LARMIN, NOTRCF
C
C MODIFIES:
C ---------
C NOARST : NOARST(I) NUMERO D'UNE ARETE DE SOMMET I
C N1SOAR : NO DE L'EVENTUELLE PREMIERE ARETE LIBRE DANS LE TABLEAU NOSOAR
C          CHAINAGE DES VIDES SUIVANT EN 3 ET PRECEDANT EN 2 DE NOSOAR
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = NOSOAR(1)+NOSOAR(2)*2
C          AVEC MXSOAR>=3*MXSOMM
C          UNE ARETE I DE NOSOAR EST VIDE <=> NOSOAR(1,I)=0 ET
C          NOSOAR(2,ARETE VIDE)=L'ARETE VIDE QUI PRECEDE
C          NOSOAR(3,ARETE VIDE)=L'ARETE VIDE QUI SUIT
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C
C
C AUXILIAIRES :
C -------------
C N1ARCF : TABLEAU (0:MXARCF) AUXILIAIRE D'ENTIERS
C NOARCF : TABLEAU (3,MXARCF) AUXILIAIRE D'ENTIERS
C LARMIN : TABLEAU ( MXARCF ) AUXILIAIRE D'ENTIERS
C NOTRCF : TABLEAU ( MXARCF ) AUXILIAIRE D'ENTIERS
C LIARCF : TABLEAU ( MXARCF ) AUXILIAIRE D'ENTIERS
C
C SORTIE :
C --------
C IERR   : =0 SI PAS D'ERREUR
C          >0 SI UNE ERREUR EST SURVENUE
C          11 ALGORITHME DEFAILLANT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1997
C....................................................................012
      PARAMETER        ( LCHAIN=6 )
      include"./incl/ampli.inc"
      include"./incl/trvari.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      DOUBLE PRECISION  PXYD(3,*), D, DMIN
      INTEGER           NOSOAR(MOSOAR,MXSOAR),
     %                  NOARTR(MOARTR,MXARTR),
     %                  NOARST(*),
     %                  N1ARCF(0:MXARCF),
     %                  NOARCF(3,MXARCF),
     %                  LARMIN(MXARCF),
     %                  NOTRCF(MXARCF),
     %                  LIARCF(MXARCF)
C
      INTEGER           NOSOTR(3)
      EQUIVALENCE      (NOSOTR(1),NS1), (NOSOTR(2),NS2),
     %                 (NOSOTR(3),NS3)
C
C     LE NOMBRE DE SOMMETS DE TE SUPPRIMES
      NBSTSU = 0
      IERR   = 0
C
C     INITIALISATION DU CHAINAGE DES ARETES DES CF => 0 ARETE DE CF
      DO 10 NARETE=1,MXSOAR
         NOSOAR( LCHAIN, NARETE ) = -1
 10   CONTINUE
C
C     BOUCLE SUR L'ENSEMBLE DES SOMMETS FRONTALIERS OU POINTS INTERNES
C     ================================================================
      DO 100 NS = 1, NBDPII
C
C        LE NOMBRE DE SOMMETS SUPPRIMES POUR CE SOMMET NS
         NBSUNS = 0
C
C        LA QUALITE MINIMALE AU DESSOUS DE LAQUELLE LE POINT PROCHE
C        INTERNE EST SUPPRIME
         QUAOPT = QUAMAL
C
C        UNE ARETE DE SOMMET NS
 15      NARETE = NOARST( NS )
         IF( NARETE .LE. 0 ) THEN
C           ERREUR: LE POINT APPARTIENT A AUCUNE ARETE
            WRITE(IMPRIM,*) 'SOMMET ',NS,' DANS AUCUNE ARETE'
            CALL XVPAUSE
            IERR = 11
            RETURN
         ENDIF
C
C        RECHERCHE DES TRIANGLES DE SOMMET NS
C        ILS DOIVENT FORMER UN CONTOUR FERME DE TYPE ETOILE
         CALL TRP1ST( NS,     NOARST, MOSOAR, NOSOAR,
     %                MOARTR, MXARTR, NOARTR,
     %                MXARCF, NBTRCF, NOTRCF )
         IF( NBTRCF .EQ. 0 ) GOTO 100
         IF( NBTRCF .LT. 0 ) THEN
C           ERREUR: IMPOSSIBLE DE TROUVER TOUS LES TRIANGLES DE SOMMET NS
C           SEULE UNE PARTIE EST A PRIORI RETROUVEE
            NBTRCF = -NBTRCF
         ENDIF
C
C        BOUCLE SUR LES TRIANGLES DE L'ETOILE DU SOMMET NS
         QUAMIN = 2.0
         DO 20 I=1,NBTRCF
C
C           LE NUMERO DES 3 SOMMETS DU TRIANGLE NT
            NT = NOTRCF(I)
            CALL NUSOTR( NT, MOSOAR, NOSOAR, MOARTR, NOARTR,
     %                   NOSOTR )
C           NOSOTR(1:3) EST EN EQUIVALENCE AVEC NS1, NS2, NS3
C
C           LA QUALITE DU TRIANGLE NS1 NS2 NS3
            CALL QUTR2D( PXYD(1,NS1), PXYD(1,NS2), PXYD(1,NS3), QUALIT )
            IF( QUALIT .LT. QUAMIN ) THEN
               QUAMIN = QUALIT
               NTQMIN = NT
            ENDIF
 20      CONTINUE
C
C        BILAN SUR LA QUALITE DES TRIANGLES DE SOMMET NS
         IF( QUAMIN .LT. QUAOPT ) THEN
C
C           RECHERCHE DU SOMMET DE NTQMIN LE PLUS PROCHE ET NON FRONTALIER
C           ==============================================================
C           LE NUMERO DES 3 SOMMETS DU TRIANGLE NT
            CALL NUSOTR( NTQMIN, MOSOAR, NOSOAR, MOARTR, NOARTR,
     %                   NOSOTR )
            NSTE = 0
            DMIN = 1D123
            DO 30 J=1,3
               IF( NOSOTR(J) .NE. NS .AND. NOSOTR(J) .GT. NBDPII ) THEN
                  D = (PXYD(1,NOSOTR(J))-PXYD(1,NS))**2
     %              + (PXYD(2,NOSOTR(J))-PXYD(2,NS))**2
                  IF( D .LT. DMIN ) THEN
                     DMIN = D
                     NSTE = J
                  ENDIF
               ENDIF
 30         CONTINUE
C
C           SI CE POINT EST A UNE DISTANCE SUPERIEURE A CELLE DEMANDEE
C           IL N'EST PAS SUPPRIME
C           ==========================================================
            IF( DMIN .GT. (AMPLI2*PXYD(3,NS))**2 ) GOTO 100
ccc 21 novembre 2006 IF( DMIN .LT. (AMPLI*PXYD(3,NS))**2 ) GOTO 100
C
C           SI CE POINT EST DANS UNE BOULE DE L'UN DES POINTS INTERNES
C           IMPOSES (RAYON=3 DIST SOUHAITEE) ALORS IL N'EST PAS DETRUIT
            CALL PTBPTI( NSTE, NBDPFR, NBDPII, PXYD, NONOUI )
            IF( NONOUI .NE. 0 ) GOTO 100
C
            IF( NSTE .GT. 0 ) THEN
C
C              NSTE EST LE SOMMET LE PLUS PROCHE DE NS DE CE
C              TRIANGLE DE MAUVAISE QUALITE ET SOMMET NON ENCORE TRAITE
               NSTE = NOSOTR( NSTE )
C              => LE SOMMET NSTE VA ETRE SUPPRIME
C              ========================================================
               CALL TE1STM( NSTE,   NBDPII, PXYD,   NOARST,
     %                      MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                      MOARTR, MXARTR, N1ARTR, NOARTR,
     %                      MXARCF, N1ARCF, NOARCF,
     %                      LARMIN, NOTRCF, LIARCF, IERR )
               IF( IERR .EQ. 0 ) THEN
C                 UN SOMMET DE TE SUPPRIME DE PLUS
                  NBSTSU = NBSTSU + 1
C                 BOUCLE JUSQU'A OBTENIR UNE QUALITE SUFFISANTE
C                 SI TRIANGULATION TRES IRREGULIERE =>
C                 DESTRUCTION DE BEAUCOUP DE POINTS INTERNES
C                 LES 2 VARIABLES SUIVANTES BRIDENT CES DESTRUCTIONS MASSIVES
                  NBSUNS = NBSUNS + 1
                  QUAOPT = QUAOPT * 0.8
                  IF( NBSUNS .LE. 5 ) GOTO 15
               ELSE IF( IERR .LT. 0 ) THEN
C                 LE SOMMET NSTE EST EXTERNE DONC NON SUPPRIME
C                 OU BIEN LE SOMMET NSTE EST LE CENTRE D'UN CF DONT TOUTES
C                 LES ARETES SIMPLES SONT FRONTALIERES
C                 DANS LES 2 CAS LE SOMMET N'EST PAS SUPPRIME
                  IERR = 0
                  GOTO 100
               ELSE
C                 ERREUR MOTIVANT UN ARRET DE LA TRIANGULATION
                  RETURN
               ENDIF
            ENDIF
         ENDIF
C
 100  CONTINUE
      WRITE(IMPRIM,*) 'TESUSP: RETRAIT DE',NBSTSU,
     %                ' SOMMETS DE TE TROP PROCHES DE LA FRONTIERE'
      RETURN
      END
