      SUBROUTINE TETRFAPE( NUVOLU, KNMVOL, NBVDWH, COANPL,
     %                     QUAMINEX, QTEAME, NOFOTI,
     %                     MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                     MNTAST, MNLIPO,
     %                     HEXAPAVE,NBIPAV,ECHPAV, N1SPAVE, NOPTSUIV,
     %                     NBSTSV, NOSTSV,
     %                     MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %                     MXTE1S, MNTE1S,
     %                     MXTRCF, MNTRCF, MXFETO, MNARCF, MNFETO,
     %                     INFACO, MXFACO, NBFACO, LEFACO, N1FASC,
     %                     IVOLTE, NVOLTE,
     %                     MXFAPE, NBFAPE, MNFAPE, MXPILE, LAPILE,
     %                     NOSOM1, NOSOM2, CPUT,   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    REGENERATION DES FACES PERDUES DE LA FRONTIERE ET DES
C -----    INTERFACES DE LA PARTITION DES VOLUMES A TETRAEDRISER
C          SI NON TOUTES RETROUVEES, CREATION DE POINTS A RE-TETRAEDRISER

C ENTREES:
C --------
C NUVOLU : NUMERO DU VOLUME PARTITION DANS LE LEXIQUE DES VOLUMES
C KNMVOL : NOM DU VOLUME A TETRAEDRISER
C NBVDWH : NUMERO DE L'ITERATION POUR RETROUVER LES FACES PERDUES
C COANPL : SEUIL DU COSINUS DE L'ANGLE FORME PAR LES NORMALES AUX
C          2 FACES ET AU DESSUS DUQUEL LES FACES
C          SONT CONSIDEREES COPLANAIRES
C          ( 0.9848   => 10   DEGRES )
C          ( 0.99     => 8.11 DEGRES )
C          ( 0.9962   => 5    DEGRES )
C          ( 0.99756  => 4    DEGRES )
C          ( 0.99863  => 3    DEGRES )
C          ( 0.999    => 2.56 DEGRES )
C          ( 0.9999   => 0.8  DEGRES )
C QUAMINEX: QUALITE MINIMALE EXIGEE POUR CREER UN TETRAEDRE
C QTEAME : QUALITE AU DESSOUS DE LAQUELLE UN TETRAEDRE N'EST PAS CREE ou
C          QUALITE DES TETRAEDRES AU DESSOUS DE LAQUELLE UNE
C          AMELIORATION DE LA QUALITE DES TETRAEDRES EST DEMANDEE
C NOFOTI : =1       EXISTENCE DE LA FONCTION UTILISATEUR 'TAILLE_IDEALE'
C          =0 PAS D'EXISTENCE DE LA FONCTION UTILISATEUR 'TAILLE_IDEALE'

C MXSOMM : NOMBRE MAXIMAL DE SOMMETS DECLARABLES DANS PTXYZD
C NBSOMM : NOMBRE DE SOMMETS UTILISES DANS PTXYZD
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C NPSOFR : =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C              LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE PT OU FACE
C          = -1 SI LE POINT EST SOMMET D'OT TROP PROCHE PT OU FACE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT DEPLACE SUR LA SURFACE
C            DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE
C MNTAST : ADRESSE MCN D'UN TMC DE   MXSOMM ENTIERS
C MNLIPO : ADRESSE MCN D'UN TMC DE 1+MXSOMM ENTIERS POUR LES TRIS

C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES

C NBSTSV : NOMBRE DE SOMMETS DE LA TETRAEDRISATION APRES TETRAEDRISATION
C          DES SOMMETS DE LA SURFACE DU VOLUME A MAILLER
C NOSTSV : TABLEAU DE MXSOMM ENTIERS POUR L'DENTIFICATION
C          DE SOMMETS DE CONTOURS FERMES DE FACES PERDUES

C MXTETR : NOMBRE DE TETRAEDRES DECLARABLES DANS NOTETR
C N1TEVI : NO DU PREMIER TETRAEDRE VIDE DANS NOTETR
C N1TETS : N1TETS(NS) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET NS
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C NUDTETR: PLUS GRAND NUMERO DANS NOTETR DE TETRAEDRE OCCUPE

C MXTE1S : NOMBRE MAXIMAL DE TETRAEDRES D'UN SOMMET
C MNTE1S : TMC(MXTE1S) D'ENTIERS

C MXTRCF : NOMBRE MAXIMAL DECLARABLE D'ARETES OU TRIANGLES
C          OU SOMMETS DANS L'ETOILE
C MNTRCF : ADRESSE MCN DU TMC NUMERO DANS LEFACO DES TRIANGLES PERDUS DU CF
C          PUIS, TABLEAU NOSTCF DU NUMERO DANS PTXYZD DES SOMMETS DU CF

C MXFETO : MAXIMUM D'ENTIERS DECLARABLES DANS N1ARCF, NOARCF, NFETOI
C MNARCF : ADRESSE MCN DU TMC NOTRCF(0:4*MXFETO)

C MXFETO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LE CHAINAGE NFETOI
C MNFETO : ADRESSE MCN DU TMC NFETOI(5,MXFETO)
C          AU DEBUT VERSION1  FACES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR AYANT CETTE FACE
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3: NON UTILISE ICI
C          4: NUMERO DE CETTE FACE DANS LEFACO, 0 SI PAS DANS LEFACO
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES
C          ENSUITE VERSION2
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST DIRIGE VERS L'INTERIEUR DE L'ETOILE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C INFACO : = 0 PAS DE TABLEAU LEFACO NI DE CONSERVATION DES
C              FACES FRONTIERE ( NO DE VOLUME CONNU PAR NVOLTE )
C          = 1 EXISTENCE DU TABLEAU LEFACO ET CONSERVATION DES
C              FACES DE LA FRONTIERE
C MXFACO : MAX DE FACES DECLARABLES DANS LEFACO
C NBFACO : NOMBRE DE FACES INITIALES DES SURFACES CONTOUR DES VOLUMES
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3

C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)

C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...

C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES d'OpenCascade
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS

C IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL
C          1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C NVOLTE : >0 NUMERO DU VOLUME DE 1 A NBVOPA DE CHAQUE TETRAEDRE
C          -1 SI TETRAEDRE INACTIF ou SUPPRIME

C MXTRCF : NOMBRE MAXIMAL DECLARABLE D'ARETES OU TRIANGLES
C          OU SOMMETS DANS L'ETOILE
C MNTRCF : ADRESSE MCN DU TABLEAU NOTRCF SUIVI DE NOSTCF
C          TABLEAU DU NUMERO DANS LEFACO DES TRIANGLES PERDUS DU CF

C MXFAPE : NOMBRE MAXIMAL DE FACES PERDUES DE LEFACO DU TABLEAU NOFAPE
C NBFAPE : NOMBRE DE FACES PERDUES DANS LEFACO
C MNFAPE : ADRESSE MCN DES NUMEROS DES NBFAPE FACES PERDUES DANS LEFACO

C MXPILE : MAXIMUM D'ELEMENTS DE LAPILE(2,MXPILE)
C LAPILE : PILE AUXILIAIRE

C SORTIES:
C --------
C NBFAPE : NOMBRE DE FACES PERDUES DANS LEFACO
C NOSOM1 : NUMERO PTXYZD DU 1-ER    SOMMET A RE-TETRAEDRISER
C          =0 SI NBFAPE=0
C NOSOM2 : NUMERO PTXYZD DU DERNIER SOMMET A RE-TETRAEDRISER
C          =0 SI NBFAPE=0
C CPUT   : TEMPS CPU TOTAL DEPUIS DEBUT DE LA TETRAEDRISATION
C IERR   : =0 SI PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY     Mars 2016
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY  Octobre 2017
C2345X7..............................................................012
      include"./incl/langue.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      CHARACTER*24      KNMVOL
      DOUBLE PRECISION  PTXYZD(4,MXSOMM)
      INTEGER           NOTETR(8,MXTETR), N1TETS(MXSOMM),
     %                  NPSOFR(MXSOMM), N1FASC(MXSOMM), NVOLTE(MXTETR),
     %                  LEFACO(11,0:MXFACO), LAPILE(2,MXPILE),
     %                  NOSTSV(MXSOMM)
      INTEGER           NBIPAV(3), N1SPAVE(0:*), NOPTSUIV(1:*)

      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3)
      DOUBLE PRECISION  CPU, CPUT, DINFO

C     ===================================================
C     TRAITEMENT DES NBFAPE FACES PERDUES DE LA FRONTIERE
C     ===================================================
      TRACTE0 = TRACTE
      NBPASS  = 0
      NBFAPE0 = NBFAPE

      IF( NBFAPE .LE. 0 ) GOTO 9900

C     UNE ITERATION DE PLUS D'EXECUTION DE TETRFAPE
C     ---------------------------------------------
 1    NBPASS = NBPASS + 1
      PRINT*,'tetrfape: NBVDWH=',NBVDWH,' NBPASS=',NBPASS
      IF( NBPASS .GT. 8 ) THEN
C        TROP D'ITERATIONS
         PRINT*,'tetrfape: TROP D''ITERATIONS NBPASS=',NBPASS
         IERR = 13
         GOTO 9999
      ENDIF

C     ESSAI DE TROUVER DES COUPLES DE FACES PERDUES COPLANAIRES
C     QUI PAR L'AUTRE DECOUPAGE POSSIBLE DONNENT 2 FACES RETROUVEES
C     LEFACO EST ALORS MODIFIE
C     -------------------------------------------------------------
      CALL VD2F2F( COANPL, PTXYZD, N1TETS, NOTETR,
     %             MXFACO, LEFACO, N1FASC,
     %             MXTE1S, MCN(MNTE1S),
     %             MXFAPE, MCN(MNFAPE), NBFAPE, NB2F2F )

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

C     BILAN EN TEMPS CPU
      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU

      WRITE(IMPRIM,*)
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'vd2f2f  :',CPU
         WRITE(IMPRIM,*)     'vd2f2f  :',NB2F2F,' ECHANGES 2F->2F'
         WRITE(IMPRIM,*)'vd2f2f  :',NBFAPE,' FACES FRONTIERE PERDUES'
      ELSE
         WRITE(IMPRIM,22001) 'vd2f2f  :',CPU
         WRITE(IMPRIM,*)     'vd2f2f  :',NB2F2F,' EXCHANGES 2F->2F'
         WRITE(IMPRIM,*)     'vd2f2f  :',NBFAPE,' LOST BOUNDARY FACES'
      ENDIF
12001 FORMAT(' ',A,T12,F11.2,'  SECONDES CPU')
22001 FORMAT(' ',A,T12,F11.2,'  CPU SECONDS')

      IF( NBFAPE .LE. 0 ) GOTO 9900


cccC     TRACE DES ARETES DES FACES PERDUES ET DES TETRAEDRES
cccC     DE LEURS SOMMETS, FACE PERDUE PAR FACE PERDUE
cccC     ----------------------------------------------------
ccc      TRACTE = .TRUE.
ccc      CALL TRARPETE( MXFACO, LEFACO, PTXYZD, N1TETS, NOTETR,
ccc     %               MXTE1S, MCN(MNTE1S), IERR )


C     PREMIER ESSAI DE RECUPERATION DES FACES PERDUES DE LA FRONTIERE
C     RECUPERATION DE FACES PERDUES DE LA FRONTIERE PAR
C     IDENTIFICATION DE SOMMETS PROCHES NON CF A DES SOMMETS CF
C     ---------------------------------------------------------------
      CALL FAPEIDST( MXSOMM, PTXYZD, NPSOFR, NBSTSV, NOSTSV,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), MXFACO, LEFACO,
     %               MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %               MXTE1S, MCN(MNTE1S),
     %               MXFETO, MCN(MNFETO), IERR )

      IF( IERR .NE. 0 ) GOTO 9999

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

C     RECHERCHE DE SOMMETS FRONTALIERS NON TETRAEDRISES
      NOSOM1 = NBSOMM
      DO NS = 1, NOSOM1
         IF( ABS(NPSOFR(NS)) .GT. 1000000 .AND. N1TETS(NS) .LE. 0 ) THEN
C           SOMMET POINT OU SUR UNE SURFACE ET NON TETRAEDRISE
            PRINT*,'tetrfape 1: Sommet,',NS,' NON TETRAEDRISE. NPSOFR=',
     %              NPSOFR(NS)
C           LE NUMERO DU SOMMET NS DANS LE TABLEAU LIPO
            NBSOMM = NBSOMM + 1
            MCN( MNLIPO + NBSOMM ) = NS
         ENDIF
      ENDDO

      IF( NBSOMM .GT. NOSOM1 ) THEN
C        REMONTEE A LA TETREDRISATION DES POINTS AJOUTES NOSOM1 a NOSOM2
         NOSOM1 = NOSOM1 + 1
         NOSOM2 = NBSOMM
         GOTO 9999
      ENDIF

      CPU  = DINFO( 'DELTA CPU' )
      CPUT = CPUT + CPU

      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'fapeidst:',CPU
         WRITE(IMPRIM,*)   'fapeidst:',NBFAPE,' FACES FRONTIERE PERDUES'
      ELSE
         WRITE(IMPRIM,22001) 'fapeidst:',CPU
         WRITE(IMPRIM,*)     'fapeidst:',NBFAPE,' LOST BOUNDARY FACES'
      ENDIF

      IF( NBFAPE .LE. 0 ) GOTO 9900


C     ESSAI DE RECUPERER LES ARETES PERDUES DES FACES PERDUES
C     CHGT 2 TETRAEDRES => 3 TETRAEDRES DE MEME ARETE COMMUNE
C     -------------------------------------------------------
C     IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL
C              1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C     NVOLTE : NUMERO DU VOLUME (1 A NBVOPA) DE CHAQUE TETRAEDRE
C             -1 SI VOLUME INCONNU
      IVOLTE = 0
      NBSOM0 = NBSOMM
      CALL RECUARPE( NBSOMM, MXSOMM, PTXYZD, NPSOFR,
     %               N1TETS, NOTETR, N1TEVI, NUDTETR,
     %               INFACO, MXFACO, LEFACO, N1FASC,
     %               IVOLTE, NVOLTE, MXTE1S, MCN(MNTE1S),
     %               NBFAPE, MCN(MNFAPE), NBARRE, IERR )

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

      CPU  = DINFO( 'DELTA CPU' )
      CPUT = CPUT + CPU

      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'recuarpe:',CPU
         WRITE(IMPRIM,*) 'recuarpe:',NBARRE,' ARETES RETROUVEES'
         WRITE(IMPRIM,*) 'recuarpe:',NBFAPE,' FACES FRONTIERE PERDUES'
      ELSE
         WRITE(IMPRIM,22001) 'recuarpe:',CPU
         WRITE(IMPRIM,*) 'recuarpe:',NBARRE,' RECOVERED EDGES'
         WRITE(IMPRIM,*) 'recuarpe:',NBFAPE,' LOST BOUNDARY FACES'
      ENDIF

      IF( IERR   .NE. 0 ) GOTO 9999
      IF( NBFAPE .LE. 0 ) GOTO 9900
      IF( NBSOM0 .LT. NBSOMM ) THEN
C        DES MILIEUX D'ARETES PERDUES A TETRAEDRISER
         NOSOM1 = NBSOM0
         GOTO 1000
      ENDIF


C     SECOND ESSAI DE TROUVER DES COUPLES DE FACES PERDUES COPLANAIRES
C     QUI PAR L'AUTRE DECOUPAGE POSSIBLE DONNENT 2 FACES RETROUVEES
C     LEFACO EST ALORS MODIFIE
C     ----------------------------------------------------------------
      CALL VD2F2F( COANPL, PTXYZD, N1TETS, NOTETR,
     %             MXFACO, LEFACO, N1FASC,
     %             MXTE1S, MCN(MNTE1S),
     %             MXFAPE, MCN(MNFAPE), NBFAPE, NB2F2F )

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

C     BILAN EN TEMPS CPU
      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU

      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'vd2f2f  :',CPU
         WRITE(IMPRIM,*)     'vd2f2f  :',NB2F2F,' ECHANGES 2F->2F'
         WRITE(IMPRIM,*)'vd2f2f  :',NBFAPE,' FACES FRONTIERE PERDUES'
      ELSE
         WRITE(IMPRIM,22001) 'vd2f2f  :',CPU
         WRITE(IMPRIM,*)     'vd2f2f  :',NB2F2F,' EXCHANGES 2F->2F'
         WRITE(IMPRIM,*)     'vd2f2f  :',NBFAPE,' LOST BOUNDARY FACES'
      ENDIF

      IF( NBFAPE .LE. 0 ) GOTO 9900

      IF( NBVDWH .EQ. 2 ) THEN

C        DERNIER POINT TETRAEDRISE
         NOSOM1 = NBSOMM

C        AJOUT DU MILIEU DE CERTAINES GRANDES ARETES PERDUES
C        AJOUT DU BARYCENTRE DES FACES PERDUES D'ARETES NON PERDUES
C        ----------------------------------------------------------
C        TRI SELON LES SURFACES DECROISSANTES DES FACES PERDUES
         CALL TRIFAP( NBFAPE, MCN(MNFAPE), LEFACO, PTXYZD )

         CALL AJOMIL( KNMVOL, COANPL, MXFACO, LEFACO, NBFACO, N1FASC,
     %                NBFAPE, MXFAPE, MCN(MNFAPE), N1TETS, NOTETR,
     %                NBSOMM, MXSOMM, PTXYZD, NPSOFR, MCN(MNTAST),
     %                MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
     %                MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
     %                MXFETO, MCN(MNFETO), MCN(MNFETO),
     %                IERR )

         NOSOM2 = NBSOMM
         N      = NOSOM2 - NOSOM1

         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU

         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12001) 'ajomil  :',CPU
            WRITE(IMPRIM,*)'ajomil  :',NBFAPE,' FACES FRONTIERE PERDUES'
            WRITE(IMPRIM,*)'ajomil  :',N,' MILIEU D''ARETES AJOUTES'
         ELSE
            WRITE(IMPRIM,22001) 'ajomil  :',CPU
            WRITE(IMPRIM,*) 'ajomil  :',NBFAPE,' LOST BOUNDARY FACES'
            WRITE(IMPRIM,*) 'ajomil  :',N,' ADDED EDGE MIDDLES'
         ENDIF

         IF( IERR .NE. 0 ) THEN
            GOTO 9999
         ELSE
            GOTO 1000
         ENDIF

      ENDIF


C     ESSAI DE RECUPERATION DES FACES PERDUES DE LA FRONTIERE
C     PAR TETRAEDRISATION DE L'ETOILE DES ARETES DU CF et
C     DES SOMMETS ISOLES DU CF AVEC OU SANS AJOUT DE POINTS INTERNES
C     --------------------------------------------------------------
      CALL FAPE22SE( NUVOLU, KNMVOL, NOFOTI, QUAMINEX, QTEAME,
     %               NBSOMM, MXSOMM, PTXYZD, NPSOFR,
     %               HEXAPAVE,NBIPAV,ECHPAV, N1SPAVE, NOPTSUIV,
     %               MXFAPE, NBFAPE, MCN(MNFAPE),
     %               INFACO, MXFACO, LEFACO, N1FASC, IVOLTE, NVOLTE,
     %               MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
     %               MXTRCF, MCN(MNTRCF),MCN(MNTRCF+MXTRCF),MCN(MNTAST),
     %               MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
     %               MXFETO, MCN(MNFETO), MXPILE, LAPILE, MCN(MNLIPO),
     %               NBABAN, IERR )
      IF( IERR .NE. 0 ) GOTO 9999

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )
      IF( NBFAPE .LE. 0 ) GOTO 9900

C     RECHERCHE DE SOMMETS FRONTALIERS NON TETRAEDRISES
      NOSOM1 = NBSOMM
      NOSOM2 = NBSOMM
      DO NS=1,NBSOMM
         IF( ABS(NPSOFR(NS)) .GT. 1000000 .AND. N1TETS(NS) .LE. 0 ) THEN
C           SOMMET POINT OU SUR UNE SURFACE ET NON TETRAEDRISE
            PRINT*,'tetrfape 2: Sommet,',NS,' NON TETRAEDRISE. NPSOFR=',
     %              NPSOFR(NS)
C           LE NUMERO DU SOMMET NS DANS LE TABLEAU LIPO
            NOSOM2 = NOSOM2 + 1
            MCN( MNLIPO + NOSOM2 ) = NS
         ENDIF
      ENDDO

      IF( NOSOM2 .GT. NOSOM1 ) THEN
C        REMONTEE A LA TETRAEDRISATION DES POINTS AJOUTES NOSOM1 a NOSOM2
         NOSOM1 = NOSOM1 + 1
         GOTO 9999
      ENDIF

      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'fape22se:',CPU
       WRITE(IMPRIM,*)     'fape22se:',NBFAPE,' FACES FRONTIERE PERDUES'
      ELSE
         WRITE(IMPRIM,22001) 'fape22se:',CPU
         WRITE(IMPRIM,*)     'fape22se:',NBFAPE,' LOST BOUNDARY FACES'
      ENDIF

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

      IF( NBFAPE .LE. 0 ) GOTO 9900

C     DERNIER POINT TETRAEDRISE
      NOSOM1 = NBSOMM

      IF( NBVDWH .EQ. 3 ) THEN

C        BARYCENTRAGE/2 DES SOMMETS D'UNE TETRAEDRISATION
C        EXCEPTES LES SOMMETS DE NPSOFR NON NUL
C        ------------------------------------------------
         NBITERBA = 4
         CALL BASTTETR( NBITERBA, NBSOMM, PTXYZD, NPSOFR,
     %                  MXTETR, NOTETR, N1TETS, MXFETO, MCN(MNARCF) )

C        AJOUT DU MILIEU DE CERTAINES GRANDES ARETES PERDUES
C        AJOUT DU BARYCENTRE DES FACES PERDUES D'ARETES NON PERDUES
C        ----------------------------------------------------------
C        TRI SELON LES SURFACES DECROISSANTES DES FACES PERDUES
         CALL TRIFAP( NBFAPE, MCN(MNFAPE), LEFACO, PTXYZD )

         CALL AJOMIL( KNMVOL, COANPL, MXFACO, LEFACO, NBFACO, N1FASC,
     %                NBFAPE, MXFAPE, MCN(MNFAPE), N1TETS, NOTETR,
     %                NBSOMM, MXSOMM, PTXYZD, NPSOFR, MCN(MNTAST),
     %                MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
     %                MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
     %                MXFETO, MCN(MNFETO), MCN(MNFETO),
     %                IERR )

         NOSOM2 = NBSOMM
         N      = NOSOM2 - NOSOM1

         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU

         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12001) 'ajomil  :',CPU
            WRITE(IMPRIM,*)'ajomil  :',NBFAPE,' FACES FRONTIERE PERDUES'
            WRITE(IMPRIM,*)'ajomil  :',N,' MILIEU D''ARETES AJOUTES'
         ELSE
            WRITE(IMPRIM,22001) 'ajomil  :',CPU
            WRITE(IMPRIM,*) 'ajomil  :',NBFAPE,' LOST BOUNDARY FACES'
            WRITE(IMPRIM,*) 'ajomil  :',N,' ADDED EDGE MIDDLES'
         ENDIF

         IF( IERR .NE. 0 ) GOTO 9999

      ENDIF


      IF( NBVDWH .EQ. 4 ) THEN

C        AJOUT DE 2 POINTS SUR LA NORMALE DES FACES PERDUES DES
C        CONTOURS FERMES
C        ------------------------------------------------------
         NBSOM0 = NBSOMM
         CALL AJNOR2CF( NBVDWH, MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                  HEXAPAVE, NBIPAV, ECHPAV, N1SPAVE, NOPTSUIV,
     %                  N1TETS, NOTETR,
     %                  MXFACO, LEFACO, N1FASC, NBFAPE, MCN(MNFAPE),
     %                  MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
     %                  MCN(MNTAST),
     %                  MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
     %                  IERR )

         IF( IERR .NE. 0 ) GOTO 9999

         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU

         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12001) 'ajnor2fp 1:',CPU
            WRITE(IMPRIM,*)'ajnor2fp:',NBSOMM-NBSOM0,
     %      ' POINTS AJOUTES SUR LA NORMALE AUX',NBFAPE,' FACES PERDUES'
         ELSE
            WRITE(IMPRIM,22001) 'ajnor2fp:',CPU
            WRITE(IMPRIM,*) 'ajnor2fp:',NBSOMM-NBSOM0,
     %      ' ADDED POINTS on NORMAL VECTOR to the',NBFAPE,
     %      ' LOST BOUNDARY FACES'
         ENDIF

      ENDIF


      IF( NBVDWH .EQ. 5 ) THEN

C        IDEM POUR LA NORMALE AU BARYCENTRE PONDERE PAR LE NO DES SOMMETS
C        DES FACES
C        ----------------------------------------------------------------
         NBSOM0 = NBSOMM
         CALL AJNOR2FP( NBVDWH, MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                  HEXAPAVE, NBIPAV, ECHPAV, N1SPAVE, NOPTSUIV,
     %                  N1TETS, NOTETR,
     %                  MXFACO, LEFACO, N1FASC, NBFAPE, MCN(MNFAPE),
     %                  MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
     %                  MCN(MNTAST),
     %                  MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
     %                  IERR )
         IF( IERR .NE. 0 ) GOTO 9999

         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU

         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12001) 'ajnor2fp:',CPU
            WRITE(IMPRIM,*)'ajnor2fp:',NBSOMM-NBSOM0,
     %      ' POINTS AJOUTES SUR LA NORMALE AUX',NBFAPE,' FACES PERDUES'
         ELSE
            WRITE(IMPRIM,22001) 'ajnor2fp:',CPU
            WRITE(IMPRIM,*) 'ajnor2fp:',NBSOMM-NBSOM0,
     %      ' ADDED POINTS on NORMAL VECTOR to the',NBFAPE,
     %      ' LOST BOUNDARY FACES'
         ENDIF

      ENDIF

      IF( NBVDWH .EQ. 6 ) THEN

C        AJOUT A LA LISTE DES POINTS A TETRAEDRISER DES 2 POINTS SITUES
C        SUR LA NORMALE MOYENNE AUX FACES DES CONTOURS FERMES
C        --------------------------------------------------------------
         NBSOM0 = NBSOMM
         CALL AJNOR2BCF( NBVDWH, MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                   HEXAPAVE, NBIPAV, ECHPAV, N1SPAVE, NOPTSUIV,
     %                   N1TETS, NOTETR,
     %                   MXFACO, LEFACO, N1FASC, NBFAPE, MCN(MNFAPE),
     %                   MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
     %                   MCN(MNTAST),
     %                   MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
     %                   IERR )
         IF( IERR .NE. 0 ) GOTO 9999

         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU

         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12001) 'ajnor2bcf 3:',CPU
            WRITE(IMPRIM,*)'ajnor2bcf:',NBSOMM-NBSOM0,
     %      ' POINTS AJOUTES SUR LA NORMALE AUX',NBFAPE,' FACES PERDUES'
         ELSE
            WRITE(IMPRIM,22001) 'ajnor2bcf:',CPU
            WRITE(IMPRIM,*) 'ajnor2bcf:',NBSOMM-NBSOM0,
     %      ' ADDED POINTS on NORMAL VECTOR to the',NBFAPE,
     %      ' LOST BOUNDARY FACES'
         ENDIF

      ENDIF


C     DES POINTS NOSOM1+1 A NBSOMM ONT ILS ETE AJOUTES POUR ETRE TETRAEDRISES?
C     ========================================================================
 1000 IF( NOSOM1 .LT. NBSOMM ) THEN

C        OUI: DE NOUVEAUX POINTS INTERNES AUX TETRAEDRES ONT ETE CREES
C             ILS FORMENT LE NOUVEAU JEU DES POINTS A TETRAEDRISER EN
C             UNE ITERATION NBVDWH DE PLUS DE TETRAEDRISATION
C        -------------------------------------------------------------
         NOSOM1 = NOSOM1 + 1
         NOSOM2 = NBSOMM

         DO N = NOSOM1, NOSOM2
C           LE NUMERO DU SOMMET N DANS LE TABLEAU LIPO
            MCN( MNLIPO + N ) = N
         ENDDO

C        RETOUR A LA TETREDRISATION DES POINTS AJOUTES NOSOM1 a NOSOM2
C        -------------------------------------------------------------
         GOTO 9999

      ENDIF


C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
     %               N1FASC, MXFACO, LEFACO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

      IF( NBFAPE .LE. 0 ) THEN
C        AUCUNE FACE PERDUE
         GOTO 9900
      ELSE IF( NBFAPE .NE. NBFAPE0 ) THEN
C        APRES EXECUTION DE TETRFAPE, LE NOMBRE DE FACES PERDUES A EVOLUER
         NBFAPE0 = NBFAPE
         GOTO 1
      ELSE
C        LE NOMBRE de FACES PERDUES N'A PAS EVOLUER DANS
C        L'EXECUTION DE TETRFAPE => ABANDON DU TRAITEMENT des FACES PERDUES
         PRINT*
         IERR = 14
         PRINT*,'tetrfape: NB PASSAGES=',NBPASS,
     %          ' NOMBRE STAGNANT de FACES PERDUES=',NBFAPE0,NBFAPE,
     %          ' IERR=',IERR
         PRINT*
         GOTO 9999
      ENDIF


cccC     ESSAI DE RECUPERATION DES FACES PERDUES DE LA FRONTIERE
cccC     PAR L'ETOILE DE TOUS LES SOMMETS DU CF ET SOMMETS ISOLES
cccC     ET TETRAEDRISATION DU TORE DES FACES DE L'ETOILE
cccC     -------------------------------------------------------
ccc      CALL FAPETORE( NBSOMM, MXSOMM, PTXYZD, NPSOFR,
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE),
ccc     %               MXFACO, LEFACO, N1FASC,
ccc     %               MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
ccc     %               MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
ccc     %               MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
ccc     %               MXFETO, MCN(MNFETO), MCN(MNTAST),
ccc     %               NBABAN, IERR )
ccc      IF( IERR   .NE. 0 ) GOTO 9999
ccc      IF( NBFAPE .LE. 0 ) GOTO 9900

cccC     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
ccc     %               N1FASC, MXFACO, LEFACO,
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

ccc      CPU  = DINFO('DELTA CPU')
ccc      CPUT = CPUT + CPU
ccc      IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,12001) 'fapetore:',CPU
ccc       WRITE(IMPRIM,*)     'fapetore:',NBFAPE,' FACES FRONTIERE PERDUES'
ccc      ELSE
ccc         WRITE(IMPRIM,22001) 'fapetore:',CPU
ccc         WRITE(IMPRIM,*)     'fapetore:',NBFAPE,' LOST BOUNDARY FACES'
ccc      ENDIF


cccC     AJOUT D'UN POINT SUR LA NORMALE DES FACES PERDUES
cccC     -------------------------------------------------
ccc      IF( NBVDWH .EQ. 2 .AND. NBABAN .GT. 0 ) THEN
ccc         NOSOM1 = NBSOMM
ccc         CALL AJPTNFL( NBVDWH, MXSOMM, NBSOMM, PTXYZD, NPSOFR,
ccc     %                 MXFACO, LEFACO, NBFAPE, MCN(MNFAPE),  IERR )
ccc         IF( IERR .NE. 0 ) GOTO 9999

ccc         CPU  = DINFO('DELTA CPU')
ccc         CPUT = CPUT + CPU

ccc         IF( LANGAG .EQ. 0 ) THEN
ccc            WRITE(IMPRIM,12001) 'ajptnfl :',CPU
ccc            WRITE(IMPRIM,*)'ajptnfl :',NBSOMM-NOSOM1,
ccc     %      ' POINTS AJOUTES SUR LA NORMALE AUX',NBFAPE,' FACES PERDUES'
ccc         ELSE
ccc            WRITE(IMPRIM,22001) 'ajptnfl :',CPU
ccc            WRITE(IMPRIM,*) 'ajptnfl :',NBSOMM-NOSOM1,
ccc     %      ' ADDED POINTS on NORMAL VECTOR to the',NBFAPE,
ccc     %      ' LOST BOUNDARY FACES'
ccc         ENDIF

ccc         IF( NOSOM1 .LT. NBSOMM ) THEN
cccC           DE NOUVEAUX POINTS INTERNES AUX TETRAEDRES ONT ETE CREES
cccC           ILS FORMENT LE NOUVEAU JEU DES POINTS A AJOUTER
cccC           UNE ITERATION DE PLUS DE TETRAEDRISATION
ccc            NOSOM2 = NBSOMM
ccc            GOTO 9000
ccc         ENDIF
ccc      ENDIF

ccc      IF( NBFAPE .LE. 0 ) GOTO 9900

cccC     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
ccc     %               N1FASC, MXFACO, LEFACO,
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )


cccC     ESSAI DE RECUPERATION DES FACES PERDUES DE LA FRONTIERE
cccC     PAR L'ETOILE DE TOUS LES SOMMETS DU CF ET SOMMETS ISOLES
cccC     --------------------------------------------------------
ccc      CALL FAPEETST( QUAMINEX, QTEAME,
ccc     %               NBSOMM, MXSOMM, PTXYZD, NPSOFR,
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE),
ccc     %               INFACO, MXFACO, LEFACO, N1FASC,
ccc     %               MXTETR, N1TEVI, N1TETS, NOTETR, NUDTETR,
ccc     %               MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
ccc     %               MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
ccc     %               MXFETO, MCN(MNFETO), MCN(MNTAST),
cccccc     %               MXFAAB, NBFAAB, MNFAAB,
ccc     %               IERR )
ccc      IF( IERR .NE. 0 ) GOTO 9999

cccC     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
ccc     %               N1FASC, MXFACO, LEFACO,
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

ccc      CPU  = DINFO( 'DELTA CPU' )
ccc      CPUT = CPUT + CPU
ccc      IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,12001) 'fapeetst:',CPU
ccc         WRITE(IMPRIM,*)   'fapeetst:',NBFAPE,' FACES FRONTIERE PERDUES'
ccc      ELSE
ccc         WRITE(IMPRIM,22001) 'fapeetst:',CPU
ccc         WRITE(IMPRIM,*)     'fapeetst:',NBFAPE,' LOST BOUNDARY FACES'
ccc      ENDIF

ccc      IF( NBFAPE .LE. 0 ) GOTO 9900


ccc      IF( NBVDWH .EQ. 33 ) THEN
cccC        ESSAI DE RECUPERER LES FACES PERDUES PERFOREES PAR UNE
cccC        ARETE COMMUNE A 3 TETRAEDRES: 3 TETRAEDRES => 2 TETRAEDRES
cccC        ----------------------------------------------------------
ccc         CALL FR3T2T( PTXYZD, NBFAPE, MCN(MNFAPE),
ccc     %                MXFACO, LEFACO, N1FASC,
ccc     %                N1TETS, N1TEVI, NOTETR, NUDTETR,
ccc     %                MXSOMM, MCN(MNTAST),
ccc     %                MXTE1S, MCN(MNTE1S),
ccc     %                NBARRE, IERR )
cccC        MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                    ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc         CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
ccc     %                  N1FASC, MXFACO, LEFACO,
ccc     %                  MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )
ccc         CPU  = DINFO( 'DELTA CPU' )
ccc         CPUT = CPUT + CPU
ccc         IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,12001)'fr3t2t  :',CPU
ccc         WRITE(IMPRIM,*)   'fr3t2t  :',NBFAPE,' FACES FRONTIERE PERDUES'
ccc         WRITE(IMPRIM,*)   'fr3t2t  :',NBARRE,' ARETES RETROUVEES'
ccc         ELSE
ccc         WRITE(IMPRIM,22001) 'fr3t2t  :',CPU
ccc         WRITE(IMPRIM,*)     'fr3t2t  :',NBFAPE,' LOST BOUNDARY FACES'
ccc         WRITE(IMPRIM,*)     'fr3t2t  :',NBARRE,' RECOVERED EDGES'
ccc         ENDIF
ccc      ENDIF


C     ARRIVEE ICI SI PLUS AUCUNE FACE PERDUE NBFAPE=0
C     -----------------------------------------------
 9900 CONTINUE 


C     SI NBFAPE>0 ICI ALORS RESTE A FAIRE LA TETRAEDRISATION DES SOMMETS
C                           NOSOM1 A NOSOM2 DANS LE SP DE RETOUR
 9999 TRACTE = TRACTE0
      RETURN


ccc      IF( NBFAPE .GT. 0 .AND. (NBVDWH .EQ. 2 .OR.  NBVDWH .EQ. 4) ) THEN

cccC        CREATION D'UNE LISTE DE POINTS PTXYZD SUR LA NORMALE AUX
cccC        FACES PERDUES DU CONTOUR DEFINI PAR LE TABLEAU LEFACO
cccC        --------------------------------------------------------
ccc         NOSOM2 = NBSOMM
ccc         CALL AJPTNOFA( MXSOMM, NBSOMM, PTXYZD, NPSOFR, NBVDWH,
ccc     %                  NBFAPE, MCN(MNFAPE), MXFACO, LEFACO,
ccc     %                  IERR )

ccc         N = NBSOMM - NOSOM2
ccc         CPU  = DINFO('DELTA CPU')
ccc         CPUT = CPUT + CPU
ccc         IF( LANGAG .EQ. 0 ) THEN
ccc            WRITE(IMPRIM,12013) 'AJPTNOFA',N,CPU
ccc         ELSE
ccc            WRITE(IMPRIM,22013) 'AJPTNOFA',N,CPU
ccc         ENDIF
ccc12013    FORMAT(' ',A,':',I7,' POINTS AJOUTES SUR NORMALE FACE CPU='
ccc     %,F11.2,' SECONDES')
ccc22013    FORMAT(' ',A,':',I7,' ADDED LOST FACE NORMALS CPU=',
ccc     %F11.2,' SECONDS')
ccc         IF( IERR .NE. 0 ) GOTO 9900

ccc         IF( NOSOM2 .LT. NBSOMM ) THEN
ccc            NOSOM1 = NOSOM2 + 1
ccc            NOSOM2 = NBSOMM
cccC           MISE A L'IDENTITE DANS LIPO
ccc            DO I=NOSOM1,NOSOM2
ccc               MCN(MNLIPO-1+I) = I
ccc               MCN(MNSOFR-1+I) = 0
ccc            ENDDO

cccC           REMONTEE A LA TETREDRISATION DES POINTS NOSOM1 a NOSOM2
cccC           -------------------------------------------------------
ccc            GOTO 1000
ccc         ENDIF

ccc      ENDIF

ccc      IF( NBFAPE .GT. 0 ) THEN

cccC        ESSAI DE TROUVER DES COUPLES DE FACES PERDUES COPLANAIRES
cccC        QUI PAR L'AUTRE DECOUPAGE POSSIBLE DONNENT 2 FACES RETROUVEES
cccC        LEFACO EST ALORS MODIFIE
cccC        -------------------------------------------------------------
ccc         CALL VD2F2F( COANPL, PTXYZD, N1TETS, NOTETR,
ccc     %                MXFACO, LEFACO, N1FASC,
ccc     %                MXTE1S, MCN(MNTE1S),
ccc     %                MXFAPE, MCN(MNFAPE), NBFAPE, NB2F2F )
ccc         CPU  = DINFO('DELTA CPU')
ccc         CPUT = CPUT + CPU
ccc         IF( LANGAG .EQ. 0 ) THEN
ccc            WRITE(IMPRIM,12001) 'vd2f2f  ',NBFAPE,CPU
ccc            WRITE(IMPRIM,*)     'vd2f2f  :',NB2F2F,' ECHANGES 2F->2F'
ccc         ELSE
ccc            WRITE(IMPRIM,22001) 'vd2f2f  ',NBFAPE,CPU
ccc            WRITE(IMPRIM,*)     'vd2f2f  :',NB2F2F,' EXCHANGES 2F->2F'
ccc         ENDIF
ccc      ENDIF


ccc      IF( NBFAPE .GT. 0 ) THEN
cccC
cccC        ESSAI DE REORDONNER LA TRIANGULATION DE SURFACE
cccC        POUR INTEGRER DES ARETES DE LA TETRAEDRISATION ACTUELLE
cccC        -------------------------------------------------------
ccc         IF( NBFAPE .GE. MXFAPE ) THEN
cccC           AJOUT DE PLACES POUR LES FACES PERDUES AJOUTEES
ccc            I = MAX( NBFAPE*2, MXFAPE+1024 )
ccc            CALL TNMCAU( 'ENTIER',MXFAPE,I,NBFAPE,MNFAPE )
ccc            MXFAPE = I
ccc         ENDIF
ccc         CALL LIERCF( COSMIN, COSMAX, COANPL,
ccc     %                MXFAPE, NBFAPE, MCN(MNFAPE),
ccc     %                MXTETR, NOTETR, N1TETS,
ccc     %                MXFACO, NBFACO, LEFACO, N1FASC,
ccc     %                MXSOMM, NBSOMM, PTXYZD, MCN(MNTAST), 
ccc     %                MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
ccc     %                MXFETO, MCN(MNARCF), MCN(MNARCF+1+MXFETO),
ccc     %                MXFETO, MCN(MNFETO), MXTE1S, MCN(MNTE1S),
ccc     %                IERR )
cccC        MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                    ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc         CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
ccc     %                  N1FASC, MXFACO, LEFACO,
ccc     %                  MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )
ccc         CPU  = DINFO('DELTA CPU')
ccc         CPUT = CPUT + CPU
ccc         IF( IERR .NE. 0 ) GOTO 9900
ccc         IF( LANGAG .EQ. 0 ) THEN
ccc            WRITE(IMPRIM,12001) 'liercf  ',NBFAPE,CPU
ccc         ELSE
ccc            WRITE(IMPRIM,22001) 'liercf  ',NBFAPE,CPU
ccc         ENDIF
ccc      ELSE
ccc         GOTO 9900
ccc      ENDIF

CCC      IF( NBFAPE .GT. 0 ) THEN
CCCC
CCCC        ESSAI DE TROUVER 3 TETRAEDRES A REORDONNER EN 2 TETRAEDRES
CCCC        REDONNANT UNE FACE PERDUE DE LEFACO
CCCC        ----------------------------------------------------------
CCC         CALL VD3T2T(PTXYZD, N1TETS, NOTETR,
CCC     %               N1TEVI, MXFACO, LEFACO,
CCC     %               MXFETO, MCN(MNTETO), MCN(MNARCF),
CCC     %               MXFETO, MCN(MNFETO),
CCC     %               NBFAPE, MCN(MNFAPE), IERR )
cccC        MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                    ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc         CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR, N1TETS,
ccc     %                  N1FASC, MXFACO, LEFACO,
ccc     %                  MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )
CCCC        LE BILAN EN NOMBRE DE FACES PERDUES ET TEMPS CPU
CCC         CPU  = DINFO('DELTA CPU')
CCC         CPUT = CPUT + CPU
CCC         WRITE(IMPRIM,12001) 'vd3t2t  ',NBFAPE,CPU
CCC         IF( IERR .NE. 0 ) GOTO 9900
CCC      ELSE
CCC         GOTO 9900
CCC      ENDIF
CCC=============================================================================

      END
