      SUBROUTINE TETRA1SF( NUCENTR, NBST1SF, NBSOEF, NBTR1SF, NOSTTR,
     %                     NOIDST,  PTXYZD,  MXTETR, N1TEVI,  NOTETR,
     %                     N1TETS, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CREATION DES NBTR1SF PREMIERS TETRAEDRES RECOUVRANT LE VOLUME
C -----    DE LA SURFACE FERMEE CONVEXE ENGLOBANTE ET 
C          INITIALISATION DES TETRAEDRES VIDES
C          LE CENTRE DU VOLUME EST LE POINT NUCENTR=1 DE PTXYZD
C
C ENTREES:
C --------
C NBST1SF: NOMBRE DE SOMMETS IDENTIFIES DANS PTXYZD DE LA SURFACE 1 CONVEXE
C NBSOEF : NOMBRE DE SOMMETS STOCKES PAR TRIANGLE DANS NOSTTR
C NBTR1SF: NOMBRE DE TRIANGLES DE LA PREMIERE SURFACE CONVEXE ENGLOBANTE
C NOSTTR : NUMERO DES NBSOEF SOMMETS DES TRIANGLES DE LA SURFACE 1
C NOIDST : NUMERO NS2 DANS PTXYZD DU SOMMET NS1 DE LA SURFACE ENGLOBANTE

C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE ALENTOUR
C MXTETR : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES
C
C SORTIES:
C --------
C N1TEVI : NUMERO DU PREMIER TETRAEDRE VIDE DANS LE CHAINAGE NOTETR(5,*)
C NOTETR : SOMMET1   < SOMMET2    SOMMET3     SOMMET4
C          ORDRE CLASSIQUE 1 2 3 DIRECT EN BAS ET 4 EN HAUT
C          LE SOMMET 1 EST LE PLUS PETIT
C          LE VOLUME EST POSITIF => UN ORDRE
C
C          TETRAEDRE1  TETREDRE2  TETRAEDRE3  TETREDRE4  VOISINS
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C N1TETS : N1TETS(I) NUMERO NOTETR D'UN TETRAEDRE DE SOMMET I PTXYZD
C IERR   :  0 SI CALCUL CORRECT SANS PROBLEME RENCONTRE
C          +1 SI UN TETRAEDRE EST DEGENERE
C          -1 SI UN TETRAEDRE EST MAL ORIENTE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC et St Pierre du Perray    Aout 2014
C2345X7..............................................................012
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      DOUBLE PRECISION  PTXYZD(1:4,1:*), CENTRE(4)
      INTEGER           NOSTTR(NBSOEF,NBTR1SF),
     %                  NOTETR(8,NBTR1SF), N1TETS(NBST1SF),
     %                  NOIDST(0:*)
      DOUBLE PRECISION  VOLUTE, VOLTET
      INTEGER           NOSOFATE(3,4)
      DATA              NOSOFATE/ 1,2,3, 2,4,3, 3,4,1, 4,2,1 /

      DO NT = 1, NBTR1SF

C        NO DANS PTXYZD DES 3 SOMMETS DU TRIANGLE NT
C        PERMUTATION 2<->3 POUR AVOIR UN VOLUME POSITIF
         NS1 = NOIDST( NOSTTR( 1, NT ) )
         NS2 = NOIDST( NOSTTR( 3, NT ) )
         NS3 = NOIDST( NOSTTR( 2, NT ) )

         VOLUTE = VOLTET( PTXYZD(1,NS1), PTXYZD(1,NS2),
     %                    PTXYZD(1,NS3), PTXYZD(1,NUCENTR) )
         IF( VOLUTE .LE. 0D0 )THEN
C           PERMUTATION  NS2 NS3 POUR AVOIR UN VOLUME >=0
            K   = NS3
            NS3 = NS2
            NS2 = K
         ENDIF

C        NO DES 4 SOMMETS DU TETRAEDRE DE VOLUME>0
         NOTETR( 1, NT ) = NS1
         NOTETR( 2, NT ) = NS2
         NOTETR( 3, NT ) = NS3
         NOTETR( 4, NT ) = NUCENTR

C        CALCUL DU CENTRE DE LA BOULE CIRCONSCRITE ET DU CARRE DU RAYON
         CALL CERABOCI( PTXYZD(1,NS1), PTXYZD(1,NS2),
     %                  PTXYZD(1,NS3), PTXYZD(1,NUCENTR),
     %                  CENTRE, VOLUTE, IERR )
C        IERR   :  0 SI CALCUL CORRECT SANS PROBLEME RENCONTRE
C                 +1 SI TETRAEDRE DEGENERE
C                 -1 SI TETRAEDRE MAL ORIENTE
         IF( IERR .NE. 0 ) THEN
            RETURN
         ENDIF

C        UN NUMERO DE PREMIER TETRAEDRE POUR CHACUN DES 3-ER SOMMETS DU TETRAEDRE
         N1TETS( NS1 ) = NT
         N1TETS( NS2 ) = NT
         N1TETS( NS3 ) = NT

      ENDDO

C     UN NUMERO DE PREMIER TETRAEDRE DU CENTRE DE LA SURFACE CONVEXE ENGLOBANTE
      N1TETS( NUCENTR ) = 1

C     MISE A JOUR DU NO DE TETRAEDRE OPPOSE PAR LES FACES DANS NOTETR
C     PAR DEFAUT 0 SIGNIFIE PAS DE TERAEDRE OPPOSE
      DO NT = 1, NBTR1SF
         DO K=5,8
            NOTETR(K,NT) = 0
         ENDDO
      ENDDO

C     LA FACE 1 DU TETRAEDRE N'A PAS DE TETRAEDRE OPPOSE PAR CONSTRUCTION
C     D'OU LE DEBUT DES BOUCLES SUR LES FACES DEBUTENT A 2
      DO NT = 1, NBTR1SF
         DO 10 K=2,4

C           LA FACE K DU TETREDRE NT A T ELLE UN TETRAEDRE OPPOSE IDENTIFIE?
            IF( NOTETR(4+K,NT) .GT. 0 ) GOTO 10

C           NON: LES 3 SOMMETS DE LA FACE K DU TETRAEDRE
            NS1 = NOTETR( NOSOFATE(1,K), NT )
            NS2 = NOTETR( NOSOFATE(2,K), NT )
            NS3 = NOTETR( NOSOFATE(3,K), NT )

C           CETTE FACE DE SOMMETS NS1-NS2-NS3 EST ELLE DANS UN AUTRE TETRAEDRE?
            DO NN = NT+1, NBTR1SF
               DO KK = 2, 4
C                 LES 3 SOMMETS DE LA FACE KK DU TETRAEDRE NN
                  NNS1 = NOTETR( NOSOFATE(1,KK), NN )
                  NNS2 = NOTETR( NOSOFATE(2,KK), NN )
                  NNS3 = NOTETR( NOSOFATE(3,KK), NN )

                  IF( NS1. EQ. NNS1 .OR.
     %                NS1. EQ. NNS2 .OR.
     %                NS1. EQ. NNS3 ) THEN
                     IF( NS2. EQ. NNS1 .OR.
     %                   NS2. EQ. NNS2 .OR.
     %                   NS2. EQ. NNS3 ) THEN
                        IF( NS3. EQ. NNS1 .OR.
     %                      NS3. EQ. NNS2 .OR.
     %                      NS3. EQ. NNS3 ) THEN
C                          LES 3 SOMMETS COINCIDENT
C                          MISE A JOUR DU NO DES TETRAEDRES OPPOSES
                           NOTETR( 4+K , NT ) = NN
                           NOTETR( 4+KK, NN ) = NT
                           GOTO 10
                        ENDIF
                     ENDIF
                  ENDIF

               ENDDO
            ENDDO

 10      CONTINUE
      ENDDO
C
ccc      VERIFICATION D'AUCUN ZERO EN POSITION 6 7 8 DE NOTETR
ccc      WRITE(IMPRIM,*)
ccc10010 FORMAT('NOTETR(',I8,')=',8I8)
ccc      DO NT=1,NBTR1SF
ccc         WRITE(IMPRIM,10010) NT, (NOTETR(K,NT),K=1,8)
ccc      ENDDO
C
C     DEBUT DES CHAINAGES DES TETRAEDRES OCCUPES ET VIDES
      N1TEVI = NBTR1SF + 1
C
C     CHAINAGE DES TETRAEDRES VIDES SUIVANTS
      DO NT = N1TEVI, MXTETR
C        LE NUMERO DU PREMIER SOMMET EST MARQUE TETRAEDRE VIDE
         NOTETR( 1, NT ) = 0
C        LE TETRAEDRE VIDE SUIVANT
         NOTETR( 5, NT ) = NT + 1
      ENDDO
C     LA FIN DU CHAINAGE DES TETRAEDRES SUIVANTS VIDES
      NOTETR(5,MXTETR) = 0
C
      RETURN
      END
