      SUBROUTINE TETRGROC( KNMVOLU, QTEAME, HEXA,  VOLMOY,
     %                     NBSOMM, MXSOMM, PTXYZD, NPSOFR,
     %                     HEXAPAVE,NBIPAV,ECHPAV, N1SPAVE, NOPTSUIV,
     %                     MXTETR, N1TEVI, NOTETR, NUDTETR, NBTETR,
     %                     N1TETS,
     %                     INFACO, MXFACO, LEFACO, N1FASC,
     %                     IVOLTE, NVOLTE,
     %                     MXETOI, NFETOI, NTETOI, LISPOI,
     %                     IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TETRAEDRISATION DE POINTS SUR UNE GRILLE D'OCTAEDRES REGULIERS
C -----    DE TAILLE D'ARETE ARETGR

C ENTREES:
C --------
C KNMVOLU: NOM DU VOLUME A TETRAEDRISER
C QTEAME : QUALITE DES TETRAEDRES AU DESSOUS DE LAQUELLE UNE
C          AMELIORATION DE LA QUALITE DES TETRAEDRES EST DEMANDEE
C HEXA   : MIN ET MAX DES 3 COORDONNEES D'UN HEXAEDRE ENGLOBANT
C          LES POINTS DE L'OBJET A MAILLER
C VOLMOY : VOLUME MOYEN DES TETRAEDRES DE LA TETRAEDRISATION

C MXSOMM : NOMBRE MAXIMAL DE SOMMETS DECLARABLES
C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES

C MXTETR : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES
C MXPILE : MAXIMUM D'ELEMENTS DE LAPILE(2,MXPILE)

C PARAMETRES de darete.inc
C ------------------------
C ARETGR : LONGUEUR DE L'ARETE SOUHAITEE POUR L'ENSEMBLE DES TETRAEDRES
C NOFOTI : NUMERO DE LA FONCTION 'TAILLE_IDEALE' DES ARETES SINON 0

C ENTREE ET SORTIE :
C ------------------
C NBSOMM : NOMBRE DES (FUTURS) SOMMETS (DE LA TETRAEDRISATION
C          EN ENTREE ET EN SORTIE APRES AJOUT DES POINTS SUR LES ARETES
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C NPSOFR : NUMERO DE POSITION PAR RAPPORT A LA FRONTIERE DE CHAQUE POINT
C          LE SIGNE DEVIENT NEGATIF SI LE SOMMET EST DEPLACE
C          =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C                    LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -1 SI LE POINT EST SOMMET D'OT ET RECONNU TROP PROCHE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT I DEPLACE SUR LA SURFACE
C             DANS LEUR SURFACE FERMEE INITIALE OU NO DE POINT INTERNE
C HEXAPAVE: MIN ET MAX DES COORDONNEES DU PAVAGE
C NBIPAV  : NOMBRE D'ARETES DANS LA DIRECTION I
C ECHPAV  : ECHELLE DANS LA DIRECTION I
C N1SPAVE : NO DU 1-ER SOMMET DANS PTXYZD DU PAVE
C NOPTSUIV: NO DU POINT SUIVANT DANS LE CHAINAGE DES POINTS DES PAVES

C N1TEVI : NUMERO DU PREMIER TETRAEDRE VIDE DANS LE CHAINAGE NOTETR(5,*)
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C NUDTETR: PLUS GRAND NUMERO DANS NOTETR DE TETRAEDRE OCCUPE
C N1TETS : NUMERO DANS NOTETR D'UN TETRAEDRE DE CHAQUE SOMMET

C INFACO : = 0 PAS DE TABLEAU LEFACO NI DE CONSERVATION DES
C              FACES FRONTIERE CAR LE NO DE VOLUME CONNU PAR NVOLTE
C          = 1 EXISTENCE DU TABLEAU LEFACO ET CONSERVATION DES
C              FACES DE LA FRONTIERE
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
cccC          12: = NO FACEOC DE 1 A NBFACES D'OC
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS
C IVOLTE : 0 PAS       DE TABLEAU NVOLTE A L'APPEL => ERREUR
C          1 EXISTENCE DU TABLEAU NVOLTE A L'APPEL
C NVOLTE : >0 NUMERO DU VOLUME DE 1 A NBVOPA DE CHAQUE TETRAEDRE
C          -1 SI TETRAEDRE INACTIF ou SUPPRIME
C LISPOI  : LISPOI(I)=I OU 0 EN ENTREE POUR PERMETTRE LA PERMUTATION
C           DES POINTS LORSQUE DES TETRAEDRES DEGENERES SONT RENCONTRES
C           PERMET DE TETRAEDRISER LES POINTS DANS UN ORDRE NON INITIAL


C TABLEAUX AUXILIAIRES :
C ----------------------
C MXETOI : NOMBRE MAXIMAL DE FACES OU TETRAEDRES DECLARABLES DANS UNE ETOILE
C NFETOI : ENTIER (1:5,1:MXETOI)
C NTETOI : ENTIER (1:MXETOI)

C SORTIES:
C --------
C NBTETR : NOMBRE DE TETRAEDRES ACTIFS DANS NOTETR
C IERR   : 0 SI PAS D'ERREUR
C          1 SATURATION DES SOMMETS    TABLEAU PTXYZD
C          3 SATURATION DES TETRAEDRES TABLEAU NOTETR
C          5 TABLEAU NVOLTE NON PRESENT A L'APPEL DE tetrgroc.f
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET St PIERRE du PERRAY & VEULETTES  Janvier 2019
C MODIFS : ALAIN PERRONNET Saint PIERRE DU PERRAY              Juin 2020
C23456...............................................................012
      PARAMETER        (MXTECH=2048, MXSMIN=1024, QUAMED=0.005)
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/darete.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      REAL              HEXA(6,2)
      DOUBLE PRECISION  PTXYZD(4,MXSOMM), DISTMIN(MXSMIN), DISMIN,
     %                  HXYZ(3), COBARY(4), PTINIT(3), VOLMOY, VOLUMT,
     %                  TAID
      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3), DX, DY, DZ, XYZ(3)

      INTEGER           NBIPAV(3), N1SPAVE(0:*), NOPTSUIV(1:*)
      INTEGER           NPSOFR(MXSOMM), LEFACO(1:11,0:MXFACO),
     %                  N1FASC(1:MXSOMM),
     %                  NOTETR(8,MXTETR), N1TETS(MXSOMM),
     %                  NFETOI(5,MXETOI), NTETOI(MXETOI),
     %                  LISPOI(0:MXSOMM), NVOLTE(MXTETR),
     %                  NOTECH(MXTECH),   NOSMIN(MXSMIN), NODSNO(MXSMIN)
      CHARACTER*160     KTITRE
      CHARACTER*24      KNMVOLU

      TRACTE0  = TRACTE

C     NOMBRE INITIAL DE SOMMETS
      NBSOMM0  = NBSOMM

C     NOMBRE DE POINT NON TETRAEDRISES
      NBPTNOTE = 0

C     TOUTES LES FACES DE L'ETOILE SONT CONSIDEREES VIDES
C     ---------------------------------------------------
      N1FEVI = 1
      N1FEOC = 0
      DO I=1,MXETOI
cccC        NUMERO DU TETRAEDRE DE L'AUTRE COTE DE LA FACE
cccC        NFETOI(1,I) = 0
cccC        NUMERO LOCAL AU TETRAEDRE DE LA FACE
cccC        NFETOI(2,I) = 0
C        NUMERO DE LA FACE DANS LEFACO
         NFETOI(4,I) = 0
C        NUMERO DANS NFETOI DE LA FACE SUIVANTE
         NFETOI(5,I) = I+1
      ENDDO
      NFETOI(5,MXETOI) = 0

      PRINT*

C     LONGUEUR DE L'ARETE DE LA GRILLE a PARTIR de darete.inc
C     -------------------------------------------------------
      ARETGR = REAL( DARETE )
      IF( LANGAG .EQ. 0 ) THEN

         IF( NOFOTI .EQ. 0 ) THEN
            PRINT*,'tetrgroc: AJOUT de SOMMETS (No au DELA de NBSOMM=',
     %           NBSOMM,') sur une GRILLE d''OCTAEDRES d''ARETE de LONGU
     %EUR',ARETGR
         ELSE
            PRINT*,'tetrgroc: AJOUT de SOMMETS (No au DELA de NBSOMM=',
     %           NBSOMM,') a PARTIR de lz FONCTION UTILISATEUR Taille_Id
     %eale(x,y,z)'
         ENDIF

      ELSE

         IF( NOFOTI .EQ. 0 ) THEN
            PRINT*,'tetrgroc: VERTICES are ADDED from NBSOMM=',NBSOMM,
     %          ' on an OCTAHEDRA GRID with EDGE SIZE=',ARETGR
         ELSE
            PRINT*,'tetrgroc: VERTICES are ADDED from the USER''s FUNCTI
     %ON EDGE_LENGTH(x,y,z)'
         ENDIF

      ENDIF


C     BOUCLE SUR LES SOMMETS DE LA GRILLE D'OCTAEDRES d'ARETE aretgr
C     --------------------------------------------------------------
      PTINIT(1) = HEXA(1,1)
      PTINIT(2) = HEXA(2,1)
      PTINIT(3) = HEXA(3,1)

C     CALCUL DE LA TAILLE IDEALE DE L'ARETE A L'ORIGINE DE LA GRILLE
      CALL TAILIDEA( NOFOTI, PTINIT, NCODEV, TAID )

cccC     momentanement ...
ccc      nofoti0 = nofoti
ccc      nofoti  = 0

      IF( NOFOTI .EQ. 0 ) THEN

C        GRILLE D'ARETES ARETGR
         HXYZ(1) = ARETGR * 0.97
         HXYZ(2) = ARETGR * 0.97
         HXYZ(3) = ARETGR * 0.97 / SQRT( 2D0 )

ccc         HXYZ(3) = ARETGR * 0.97 / SQRT(2D0)
ccc         HXYZ(3) = ARETGR * 0.97 / 2
ccc         HXYZ(3) = ARETGR * 0.97 / SQRT(2D0) * 0.85D0

         NBX = INT( ( HEXA(1,2) - HEXA(1,1) ) / HXYZ(1) )
         NBY = INT( ( HEXA(2,2) - HEXA(2,1) ) / HXYZ(2) )
         NBZ = INT( ( HEXA(3,2) - HEXA(3,1) ) / HXYZ(3) )

         PRINT*,'tetrgroc: GRILLE d''ARETE',ARETGR,' de',
     %        NBX,' x',NBY,' x',NBZ,' ARETES soit',
     %       (1+NBX)*(1+NBY)*NBZ,' SOMMETS POTENTIELS'

      ELSE

C        GRILLE D'ARETES TAID
         HXYZ(1) = TAID * 0.97
         HXYZ(2) = TAID * 0.97
         HXYZ(3) = TAID * 0.97 / SQRT( 2D0 )

      ENDIF

C     PREMIER TETRAEDRE A VOIR POUR RECHERCHER LES TETRAEDRES
C     CONTENANT LE POINT A TETRAEDRISER
      NOTEIN = N1TETS( NBSOMM )

      KPAIR = 0
      DX = PTINIT(1)
      DY = PTINIT(2)
      DZ = PTINIT(3)


C     CONSTRUCTION DES SOMMETS DE LA GRILLE ET TETRAEDRISATION
C     ========================================================
C     CALCUL DE LA TAILLE IDEALE DE L'ARETE AU DEBUT DES Z
 30   IF( NOFOTI .LE. 0 ) THEN
         TAID = HXYZ(3)
      ELSE
         XYZ(1) = PTINIT(1)
         XYZ(2) = PTINIT(2)
         XYZ(3) = DZ
         CALL TAILIDEA( NOFOTI, XYZ, NCODEV, TAID )
      ENDIF
      DZ = DZ + TAID
      IF( DZ .LT. HEXA(3,2)-TAID/2 ) THEN
         NOTE1Z = 0

C        CALCUL DE LA TAILLE IDEALE DE L'ARETE AU DEBUT DES Y
 20      IF( NOFOTI .LE. 0 ) THEN
            TAID = HXYZ(2)
         ELSE
C           CALCUL DE LA TAILLE IDEALE DE L'ARETE AU DEBUT DES Y
            XYZ(1) = PTINIT(1)
            XYZ(2) = DY
            XYZ(3) = DZ
            CALL TAILIDEA( NOFOTI, XYZ, NCODEV, TAID )
         ENDIF
         DY = DY + TAID
         IF( DY .LT. HEXA(2,2)-TAID/2 ) THEN
            NOTE1Y = 0

C           CALCUL DE LA TAILLE IDEALE DE L'ARETE AU DEBUT DES X
 10         IF( NOFOTI .LE. 0 ) THEN
               TAID = HXYZ(1)
            ELSE
C              CALCUL DE LA TAILLE IDEALE DE L'ARETE AU DEBUT DES X
               XYZ(1) = DX
               XYZ(2) = DY
               XYZ(3) = DZ
               CALL TAILIDEA( NOFOTI, XYZ, NCODEV, TAID )
            ENDIF
            DX = DX + TAID
            IF( DX .LT. HEXA(1,2)-TAID/2 ) THEN

C              LE SOMMET (DX,DY,DZ) DE LA GRILLE
C              ---------------------------------
               IF( NBSOMM .GE. MXSOMM ) THEN
                  GOTO 9910
               ENDIF
C              NUMERO PTXYZD DE L'EVENTUEL SOMMET
               NBSOMM = NBSOMM + 1
               PTXYZD(1,NBSOMM) = DX
               PTXYZD(2,NBSOMM) = DY
               PTXYZD(3,NBSOMM) = DZ

C              CALCUL DE LA TAILLE IDEALE DE L'ARETE AU SOMMET NBSOMM
               CALL TAILIDEA( NOFOTI, PTXYZD(1,NBSOMM), NCODEV, TAID )
               PTXYZD(4,NBSOMM) = TAID

C              RECHERCHE DE NOTET1 TETRAEDRE CONTENANT LE POINT NBSOMM
C              -------------------------------------------------------
               CALL R1TCO1P1( NBSOMM,  MXSOMM, PTXYZD, 0,
     %                        HEXAPAVE,NBIPAV, ECHPAV, N1SPAVE,NOPTSUIV,
     %                        NOTEIN,  MXTETR, NOTETR, NUDTETR, N1TETS,
     %                        MXETOI,  NTETOI, MXTECH, NOTECH,
     %                        NOTET1,  COBARY )

               IF( NOTET1 .LE. 0 ) THEN
C                 LE SOMMET EST EXTERIEUR et NON AJOUTE
                  NBPTNOTE = NBPTNOTE + 1
                  NBSOMM   = NBSOMM - 1
                  GOTO 10
               ENDIF

C              LE POINT NBSOMM EST IL TROP PROCHE D'UN DES SOMMETS
C              DEJA TETRAEDRISES (OBTENU PAR LES PAVES D'HEXAPAVE)?
C              ----------------------------------------------------
               CALL DMINSTPAV( HEXAPAVE,NBIPAV,ECHPAV,N1SPAVE,NOPTSUIV,
     %                         PTXYZD(1,NBSOMM), PTXYZD,
     %                         MXSMIN, NBSMIN, NOSMIN, NODSNO, DISTMIN )
               DO N = 1, NBSMIN
C                 LE SOMMET LE PLUS PROCHE DE NBSOMM NON LUI MEME
                  NSDMIN = NOSMIN( NODSNO(N) )
                  IF( NSDMIN .NE. NBSOMM ) THEN
                     DISMIN = SQRT( DISTMIN(N) )
                     IF( DISMIN .LT. PTXYZD(4,NBSOMM)*0.333D0 ) THEN
C                       LE SOMMET NBSOMM EST TROP PROCHE DE NSDMIN
C                       LE SOMMET NBSOMM N'EST PAS AJOUTE
                        NBPTNOTE = NBPTNOTE + 1
                        NBSOMM   = NBSOMM - 1
                        GOTO 10
                     ENDIF
                     GOTO 40
                  ENDIF
               ENDDO

C              NOTET1 CONTIENT LE POINT NBSOMM
 40            NOTEIN = NOTET1

C              PREMIER TETRAEDRE CONTENANT LE PREMIER POINT EN X POUR CET Y
               IF( NOTE1Y .EQ. 0 ) THEN
                  NBSOMY = NBSOMM
                  NOTE1Y = NOTEIN
                  IF( NOTE1Z .EQ. 0 ) THEN
C                    PREMIER TETRAEDRE CONTENANT LE PREMIER POINT EN X et Y POUR CE Z
                     NBSOMZ = NBSOMM
                     NOTE1Z = NOTEIN
                  ENDIF
               ENDIF

C              NO NOTETR D'UN TETRAEDRE DE SOMMET NBSOMM
               N1TETS( NBSOMM ) = 0

C              NBSOMM EST UN POINT INTERNE
               NPSOFR( NBSOMM ) = 0

               LISPOI( NBSOMM ) = NBSOMM

C              LE SOMMET NBSOMM EST INTERNE AU TETRAEDRE NOTET1
               NOTEIN = NOTET1

               CALL TETRA1ST( KNMVOLU, NBSOMM, NOTEIN,
     %                        MXSOMM, PTXYZD, NPSOFR,
     %                        HEXAPAVE,NBIPAV,ECHPAV, N1SPAVE,NOPTSUIV,
     %                        MXTETR, N1TEVI, NUDTETR,NOTETR, N1TETS,
     %                        INFACO, MXFACO, LEFACO, N1FASC,
     %                        IVOLTE, NVOLTE,
     %                        MXETOI, N1FEOC, N1FEVI, NFETOI,
     %                        NBTEET, NTETOI, VOLET0, VOLET1 )

               IF( NBTEET .LE. 0 ) THEN
C                 LE SOMMET N'A PAS ETE TETRAEDRISE
                  NBPTNOTE = NBPTNOTE + 1
                  NBSOMM   = NBSOMM - 1
               ENDIF

               GOTO 10
            ENDIF
C           FIN DE L'INCREMENTATION EN X


C           REPOSITIONNEMENT AU DEBUT DES X POUR UN NOUVEAU DY
            DX = PTINIT(1)
            IF( NOTE1Y .GT. 0 ) THEN
               NOTEIN = N1TETS( NBSOMY )
            ENDIF

            GOTO 20
         ENDIF
C        FIN DE L'INCREMENTATION EN Y et DES X

C        DECALAGE DES QUADRANGLES DU PLAN XY
         KPAIR = 1 - KPAIR
         IF( NOFOTI .LE. 0 ) THEN
            PTINIT(1) = HEXA(1,1) + KPAIR * HXYZ(1) / 2
            PTINIT(2) = HEXA(2,1) + KPAIR * HXYZ(2) / 2
         ELSE
C           CALCUL DE LA TAILLE IDEALE DE L'ARETE AU DEBUT DES X et Y
            XYZ(1) = HEXA(1,1)
            XYZ(2) = HEXA(1,2)
            XYZ(3) = DZ
            CALL TAILIDEA( NOFOTI, XYZ, NCODEV, TAID )
            PTINIT(1) = HEXA(1,1) + KPAIR * TAID / 2
            PTINIT(2) = HEXA(2,1) + KPAIR * TAID / 2
         ENDIF
ccc         PTINIT(3) = HEXA(3,1)

C        REPOSITIONNEMENT AU DEBUT DES X Y POUR UN NOUVEAU DZ
         DX = PTINIT(1)
         DY = PTINIT(2) 
         IF( NOTE1Z .GT. 0 ) THEN
            NOTEIN = N1TETS( NBSOMZ )
         ENDIF

         PRINT*,'tetrgroc: TETRAEDRISATION du SOMMET',NBSOMM

         GOTO 30
      ENDIF
C     FIN DE L'INCREMENTATION EN Z

ccc      nofoti = nofoti0

C     QUALITE DES TETRAEDRES APRES AJOUT DES SOMMETS ILLE d'OCTAEDRES
      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )
      VOLMOY = VOLUMT / NBTETR

      NBSAJ = NBSOMM-NBSOMM0
      PRINT*,'tetrgroc: AVANT BARYCENTRAGE',NBSAJ,' SOMMETS de',
     %        NBSOMM0,' a',NBSOMM,' ONT ETE TETRAEDRISES et',
     %        NBPTNOTE,' SOMMETS de la GRILLE NON TETRAEDRISES'
      PRINT*,'QUAMOY=',QUAMOY,' QUAMIN=',QUAMIN,' VOLUME=',VOLUMT,
     %       ' Nb TETRA=',NBTETR,' No Dernier TETRA=',NUDTETR
      PRINT*

C     TRACE DES TETRAEDRES FRONTIERE ET DES SOMMETS TETRAEDRISES DE LA GRILLE
ccc      tracte = .true.
      KTITRE='tetrgroc: AVANT BARYCENTRAGE          SOMMETS AJOUTES de l
     %a GRILLE d''OCTAEDRES QUAMIN=                 QUAMOY=            '
      WRITE( KTITRE(30:37),  '(I8)'    ) NBSAJ
      WRITE( KTITRE(88:102), '(G15.6)' ) QUAMIN
      WRITE( KTITRE(112:120),'(F9.6)'  ) QUAMOY
      CALL TRTEFR(KTITRE, NBSOMM0+1, NBSOMM, PTXYZD, NUDTETR, NOTETR, 0)


C     BARYCENTRAGE DES SOMMETS INTERNES DE LA TETRAEDRISATION
C     AVEC RECHERCHE D'UNE QUALITE MINIMALE DES TETRAEDRES
C     DE LEUR ETOILE
C     -------------------------------------------------------
C     QUALITE D'UN TETRAEDRE AU DESSOUS DUQUEL IL EST DECLARE MEDIOCRE
C     ET LEUR NOMBRE EST RECENSE DANS qualgrte.f
      CALL BARYSTTE( QUAMED, NBSOMM, PTXYZD, NPSOFR,
     %               NBTETR, NUDTETR, MXTETR, NOTETR, N1TETS,
     %               MXETOI, NTETOI )

C     QUALITE DES TETRAEDRES APRES AJOUT DES SOMMETS ILLE d'OCTAEDRES
      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )
      VOLMOY = VOLUMT / NBTETR

      NBSAJ = NBSOMM-NBSOMM0
      PRINT*,'tetrgroc: APRES BARYCENTRAGE',NBSAJ,' SOMMETS de',
     %        NBSOMM0,' a',NBSOMM,' ONT ETE TETRAEDRISES'
      PRINT*,'QUAMOY=',QUAMOY,' QUAMIN=',QUAMIN,' VOLUME=',VOLUMT,
     %       ' Nb TETRA=',NBTETR,' No Dernier TETRA=',NUDTETR
      PRINT*

C     TRACE DES TETRAEDRES FRONTIERE ET DES SOMMETS TETRAEDRISES
C     DE LA GRILLE
ccc      tracte = .true.
      KTITRE='tetrgroc: APRES BARYCENTRAGE          SOMMETS AJOUTES de l
     %a GRILLE d''OCTAEDRES QUAMIN=                 QUAMOY=            '
      WRITE( KTITRE(30:37),  '(I8)'    ) NBSAJ
      WRITE( KTITRE(88:102), '(G15.6)' ) QUAMIN
      WRITE( KTITRE(112:120),'(F9.6)'  ) QUAMOY
      CALL TRTEFR(KTITRE, NBSOMM0+1, NBSOMM, PTXYZD, NUDTETR, NOTETR, 0)

      IF( NBTETR .GT. 0 ) GOTO 9000



C     TENTATIVE D'AMELIORER LA QUALITE DE TOUS LES TETRAEDRES
C     DE QUALITE MEDIOCRE PAR DIFFERENTES TECHNIQUES SELON
C     LE TYPE DU TETRAEDRE PLAT ( TRIANGLE ou QUADRANGLE ) :
C     SUPPRESSION DES TETRAEDRES D'UNE ARETE TRES COURTE
C     CHANGEMENTS 3 TETRAEDRES -> 2 TETRAEDRES
C     DECOMPOSITION DE TETRAEDRES EN 2 TETRAEDRES
C     AMELIORER LA QUALITE DES TETRAEDRES AUTOUR 
C     DU TETRAEDRE NTE DE MEDIOCRE QUALITE ET DE LUI-MEME
C     -------------------------------------------------------
      CALL AMQALLTE( QTEAME,  MXTETR, N1TEVI, NOTETR, N1TETS,
     %               MXSOMM,  NBSOMM, PTXYZD, NPSOFR,
     %               INFACO,  MXFACO, LEFACO, IVOLTE, NVOLTE,
     %               MXETOI,  NTETOI, MXETOI, NFETOI, MXTECH, NOTECH,
     %               NUDTETR, VOLMOY, MODIFT, IER )

C     QUALITE DES TETRAEDRES APRES AJOUT DES SOMMETS
      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )
      VOLMOY = VOLUMT / NBTETR

      NBSAJ = NBSOMM-NBSOMM0
      PRINT*,'tetrgroc: APRES AMELIORATION',NBSAJ,' SOMMETS de',
     %        NBSOMM0,' a',NBSOMM,' ONT ETE TETRAEDRISES'
      PRINT*,'QUAMOY=',QUAMOY,' QUAMIN=',QUAMIN,' VOLUME=',VOLUMT,
     %' Nb TETRA=',NBTETR,' No Dernier TETRA=',NUDTETR
      PRINT*

C     TRACE DES TETRAEDRES FRONTIERE ET DES SOMMETS TETRAEDRISES
ccc      tracte = .true.
      KTITRE='tetrgroc: APRES AMELIORATION          SOMMETS AJOUTES de l
     %a GRILLE d''OCTAEDRES QUAMIN=                 QUAMOY=            '
      WRITE( KTITRE(30:37),  '(I8)'    ) NBSAJ
      WRITE( KTITRE(88:102), '(G15.6)' ) QUAMIN
      WRITE( KTITRE(112:120),'(F9.6)'  ) QUAMOY
      PRINT*,KTITRE
      CALL TRTEFR(KTITRE, NBSOMM0+1, NBSOMM, PTXYZD, NUDTETR, NOTETR, 0)

 9000 IERR = 0
      GOTO 9999

 9910 PRINT *,'tetrgroc: TABLEAU PTXYZD SATURE MXSOMM=',MXSOMM
      IERR = 1
      GOTO 9999

 9999 TRACTE = TRACTE0
      RETURN
      END
