      SUBROUTINE TETRPOMM( NUSFPI, NUVLPI, NTVLPI,
     %                     NBSTVL, NTXYZSV, MNXYZSV,
     %                     NBTETR, NTNSEFV, MNNSEFV, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  TETRAEDRISATION D'UNE TRIANGULATION D4UNE SURFACE TRIANGULEE
C -----  DE TYPE POMME EN JOIGNANT SON BARYCENTRE A CHACUN DES TRIANGLES

C ENTREE :
C --------
C NUSFPI : NUMERO TMS DE LA SURFACE TRIANGULEE
C NUVLPI : NUMERO TMS DU VOLUME A TETRAEDRISER
C NTVLPI : NUMERO LEXIQUE DU VOLUME A TETRAEDRISER

C SORTIES:
C --------
C NBSTVL : NOMBRE DE SOMMETS DE LA TETRAEDRISATION
C          (=CELUI DE LA TRIANGULATION + 1 le BARYCENTRE)
C NTXYZSV: NUMERO  du TMS 'XYZSOMMET' DE LA TETRAEDRISATION
C MNXYZSV: ADRESSE du TMS 'XYZSOMMET' DE LA TETRAEDRISATION

C NBTETR : NOMBRE DE TETRAEDRES
C          (=NOMBRE DE TRIANGLES DE LA TRIANGULATION)
C NTNSEFV: NUMERO  du TMS 'NSEF' DE LA TETRAEDRISATION
C MNNSEFV: ADRESSE du TMS 'NSEF' DE LA TETRAEDRISATION
C IERR   : =0 SI PAS D'ERREUR DETECTEE
C          >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN  Saint PIERRE du PERRAY             Juin 2019
C23456...............................................................012
      include"./incl/langue.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/a_surface__definition.inc"
      include"./incl/a_volume__definition.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (RMCN(1),MCN(1))

      REAL              XYZBAR(3)
      DOUBLE PRECISION  VOLTER, V
      CHARACTER*24      KNMS, KNMV

      IERR = 0
      CALL NMOBNU( 'SURFACE', NUSFPI, KNMS )
      CALL NMOBNU( 'VOLUME',  NUVLPI, KNMV )
      PRINT*,'tetrpomm: TETRAEDRISATION de la PIECE VOLUMIQUE de SURFACE
     % ',KNMS,' EN LE VOLUME ',KNMV

C     OUVERTURE DU LX DE LA SURFACE NUSFPI
      CALL LXNLOU( NTSURF, NUSFPI, NTSFPI, MNSFPI )
      IF( MNSFPI .LE. 0 ) THEN
         PRINT*,'tetrpomm: SURFACE INTROUVABLE: ',KNMS
         IERR = 1
         GOTO 9999
      ENDIF

C     OUVERTURE DU TMS XYZSOMMET de la SURFACE
      CALL LXTSOU( NTSFPI, 'XYZSOMMET', NTXYZSF, MNXYZSF )
      IF( MNXYZSF .LE. 0 ) THEN
        PRINT*,'tetrpomm: TMS XYZSOMMET INTROUVABLE de la SURFACE ',KNMS
         IERR = 2
         GOTO 9999
      ENDIF

C     OUVERTURE DU TMS NSEF de la SURFACE
      CALL LXTSOU( NTSFPI, 'NSEF', NTNSEFSF, MNNSEFSF )
      IF( MNNSEFSF .LE. 0 ) THEN
         PRINT*,'tetrpomm: TMS NSEF INTROUVABLE de la SURFACE ',KNMS
         IERR = 3
         GOTO 9999
      ENDIF

C     NOMBRE DE SOMMETS DE LA TRIANGULATION DE LA SURFACE
      NBSTSF = MCN( MNXYZSF + WNBSOM )
C     ADRESSE DU XYZ DU 1-ER SOMMET
      MNXYZSU = MNXYZSF + WYZSOM

C     NOMBRE DE TRIANGLES DE LA TRIANGULATION DE LA SURFACE
      NBTRIA = MCN( MNNSEFSF + WBEFOB )
C     ADRESSE DU NUMERO DU 1-ER SOMMET DU 1-ER TRIANGLE
      MNTRIA = MNNSEFSF + WUSOEF

C     CONSTRUCTION DU TMS XYZSOMMET DU VOLUME
      NBSTVL  = NBSTSF + 1
      CALL LXTNDC( NTVLPI, 'XYZSOMMET', 'ENTIER', WYZSOM + 3*NBSTVL )
      CALL LXTSOU( NTVLPI, 'XYZSOMMET',  NTXYZSV, MNXYZSV )
      IF( MNXYZSV .LE. 0 ) THEN
        PRINT*,'tetrpomm: PLUS ASSEZ DE PLACE DANS LE SUPER-TABLEAU MCN'
         IERR = 4
         GOTO 9999
      ENDIF
C     NOMBRE DESOMMETS
      MCN( MNXYZSV + WNBSOM ) = NBSTVL
C     NOMBRE DE TANGENTES
      MCN( MNXYZSV + WNBTGS ) = 0
C     NOMBRE DE COORDONNEES D'UN SOMMET
      MCN( MNXYZSV + WBCOOR ) = 3
C     ADRESSE MCN DU XYZ DU 1-ER SOMMET DE LA TETRAEDRISATION
      MNXYZVO = MNXYZSV + WYZSOM

C     DECLARATION DU TMS NSEF DU NO DES SOMMETS DES TETRAEDRES DU VOLUME
      NBTETR  = NBTRIA
      CALL LXTNDC( NTVLPI, 'NSEF', 'ENTIER', WUSOEF + 8*NBTETR )
      CALL LXTSOU( NTVLPI, 'NSEF',  NTNSEFV, MNNSEFV )
      IF( MNNSEFV .LE. 0 ) THEN
        PRINT*,'tetrpomm: PLUS ASSEZ DE PLACE DANS LE SUPER-TABLEAU MCN'
         IERR = 5
         GOTO 9999
      ENDIF
C     Type du PLSV: VOLUME
      MCN( MNNSEFV + WUTYOB ) = 4
C     Type INCONNU de FERMETURE
      MCN( MNNSEFV + WUTFMA ) = -1
C     NBSOEF Nombre de sommets par EF = 8
      MCN( MNNSEFV + WBSOEF ) = 8
C     NBTGEF Nombre de tangentes par EF
      MCN( MNNSEFV + WBTGEF ) = 0
C     NBEFOB Nombre des EF du PLSV
      MCN( MNNSEFV + WBEFOB ) = NBTETR
C     NBEFTG Nombre des EF avec TG
      MCN( MNNSEFV + WBEFTG ) = 0
C     NBEFAP Nombre des EF avec POINTEUR sur EF a TG
      MCN( MNNSEFV + WBEFAP ) = 0
C     NUTYMA Numero de type du maillage 0 : non structure
      MCN( MNNSEFV + WUTYMA ) = 0

C     ADRESSE MCN DU NO DU 1-ER SOMMET DU 1-ER TETRAEDRE DE LA TETRAEDRISATION
      MNTETR = MNNSEFV + WUSOEF

C     CALCUL DU BARYCENTRE DE LA TRIANGULATION QUI EST LE
C     SOMMET NBSTVL DE LA TETRAEDRISATION
      DO K=1,3
         XYZBAR( K ) = 0
      ENDDO
      MNTR = MNTRIA - 1
      DO N=1,NBTRIA
C        LE TRIANGLE N
         DO I=1,3
C           LE NO DE SOMMET I DU TRIANGLE N
            NS = MCN( MNTR + I )
            MNS = MNXYZSU + 3*NS - 4
            DO K=1,3
               XYZBAR( K ) = XYZBAR( K ) + RMCN( MNS + K )
            ENDDO
         ENDDO
         MNTR = MNTR + 4
      ENDDO
      DO K=1,3
         XYZBAR( K ) = XYZBAR( K ) / (3*NBTRIA)
      ENDDO

      CALL TRTATA( RMCN(MNXYZSU), RMCN(MNXYZVO), 3*NBSTSF )
C     AJOUT DU BARYCENTRE COMME SOMMET NBSTSF+1 DE LA TETRAEDRISATION
      MNS = MNXYZVO + 3*NBSTSF - 1
      DO K=1,3
         RMCN( MNS + K ) = XYZBAR( K )
      ENDDO

C     LA DATE DE CREATION DU TMS XYZSOMMET
      CALL ECDATE( MCN(MNXYZSV) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNXYZSV + MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )

C     GENERATION DES NBTETR=NBTRIA TETRAEDRES:
C     1 TETRAEDRE = 1 TRIANGLE + SOMMET NBSTVL = XYZBAR
      MNTR = MNTRIA - 1
      MNTE = MNTETR - 1
      MNXYZ = MNXYZVO - 3
      DO N=1,NBTRIA

C        LE TRIANGLE N ET TETRAEDRE N
         DO I=1,3
C           LE NO DE SOMMET I DU TRIANGLE N
            NS = MCN( MNTR + I )
C           LE NO DE SOMMET I DU TETRAEDRE N
            MCN( MNTE + I ) = NS
         ENDDO

C        LE NO DE SOMMET 4 DU TETRAEDRE N EST LE BARYCENTRE
         MCN( MNTE + 4 ) = NBSTVL

C        LES 4 AUTRES SOMMETS SONT NULS
         DO I=5,8
            MCN( MNTE + I ) = 0
         ENDDO

C        TOUS LES TETRAEDRES SONT SUPPOSES DE VOLUME>=0
         V = VOLTER( RMCN( MNXYZ + 3*MCN(MNTE+1) ),
     %               RMCN( MNXYZ + 3*MCN(MNTE+2) ),
     %               RMCN( MNXYZ + 3*MCN(MNTE+3) ),
     %               RMCN( MNXYZ + 3*MCN(MNTE+4) ) )

         IF( V .LT. 0D0 ) THEN
C           PERMUTATION DES SOMMETS 2 et 3 DU TETRAEDRE
            NS          = MCN(MNTE+2)
            MCN(MNTE+2) = MCN(MNTE+3)
            MCN(MNTE+3) = NS
         ENDIF


C        PASSAGE AU TRIANGLE ET TETRAEDRE SUIVANT
         MNTR = MNTR + 4
         MNTE = MNTE + 8

      ENDDO

C     LA DATE DE CREATION
      CALL ECDATE( MCN(MNNSEFV) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNNSEFV + MOTVAR(6) ) = NONMTD( '~>>>NSEF' )

 9999 RETURN
      END
