      SUBROUTINE TETR11F( NS1, NS2, NS3, N1TETS, NOTETR,
     %                    MXTE1S, NOTE1S, NTE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RETROUVER UN TETRAEDRE DE NOTETR CONTENANT LA FACE
C -----    DE SOMMETS NS1 NS2 NS3

C ENTREES:
C --------
C NS1,NS2,NS3: NUMERO DES 3 SOMMETS DE LA FACE A RECHERCHER DANS LA
C          TETRAEDRISATION ACTUELLE
C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C MXTE1S : MAXIMUM DE MOTS DU TABLEAU AUXILIAIRE NOTE1S
C NOTE1S : TABLEAU DES FACES CONTENANT UN SOMMET

C SORTIES:
C --------
C NTE    : >0 NUMERO D'UN TETRAEDRE DE NOTETR AYANT CETTE FACE
C          =0 SI AUCUN TETRAEDRE DE NOTETR NE CONTIENT CETTE FACE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 2005
C2345X7..............................................................012
      INTEGER  NOTETR(8,1:*), N1TETS(1:*), NOTE1S(MXTE1S)

      IF( N1TETS(NS1) .LE. 0 ) THEN
C        PAS DE TETRAEDRE DE SOMMET NS1
         GOTO 9000
      ENDIF

      IF( N1TETS(NS2) .LE. 0 ) THEN
C        PAS DE TETRAEDRE DE SOMMET NS2
         GOTO 9000
      ENDIF

      IF( N1TETS(NS3) .LE. 0 ) THEN
C        PAS DE TETRAEDRE DE SOMMET NS3
         GOTO 9000
      ENDIF

C     RECHERCHE DES NBF TETRAEDRES DE NOTETR CONTENANT LE SOMMET NS1
      CALL TETR1S( NS1, N1TETS, NOTETR, NBF, MXTE1S, NOTE1S, IERR )
C     SI NBF<=0 LA SORTIE AVEC NTE=0 EST CORRECTE SANS TEST SUPPLEMENTAIRE

C     BOUCLE SUR LES TETRAEDRES DE SOMMET NS1 ET CONTENANT LES SOMMETS NS2 NS3
      DO N=1,NBF
C        LE TETRAEDRE NTE DE SOMMET NS1
         NTE = NOTE1S( N )
         DO I=1,4
            IF( NOTETR(I,NTE) .EQ. NS2 ) THEN
C              LE TETRAEDRE A LE SOMMET NS2
               DO J=1,4
                  IF( NOTETR(J,NTE) .EQ. NS3 ) THEN
C                    NTE TETRAEDRE DE SOMMETS NS1NS2 NS3
                     GOTO 9999
                  ENDIF
               ENDDO
            ENDIF
         ENDDO
      ENDDO
C
C     ICI PAS DE TETRAEDRE DE SOMMETS NS1 NS2 NS3
 9000 NTE = 0
C
 9999 RETURN
      END
