      SUBROUTINE TETSOM( MXSOMM, NBSOTE, MXTETR, NBTETR, NSTETR,
     %                   N1TEVI, N1TESO, NO1TSO, MXTESO, NOTESO)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   ETABLIR LES TABLEAUX
C -----   NO1TSO POINTEUR SUR UN TETRAEDRE DE CHAQUE SOMMET
C         NOTESO NUMERO ET CHAINAGE CIRCULAIRE SUR LES TETRAEDRES
C                DE CHAQUE SOMMET
C
C ENTREES:
C --------
C NBSOTE : VALEUR MAXIMALE DE DECLARATION DU PREMIER INDICE DE NSTETR(>3)
C MXTETR : NOMBRE MAXIMAL DE TETRAEDRES DECLARABLES DANS NSTETR
C NBTETR : NOMBRE DE TETRAEDRES
C NSTETR : NUMERO DES 4 SOMMETS DES NBTETR TETRAEDRES
C          SI TETRA VIDE NSTETR(1,I)=0 ET NSTETR(2,I)=TETRA VIDE SUIVANT
C MXSOMM : NUMERO MAXIMAL DES SOMMETS DES TETRAEDRES
C MXTESO : NOMBRE MAXIMAL DE NUMERO DE TETRAEDRES DES SOMMETS
C
C SORTIES:
C --------
C N1TEVI : NUMERO DANS NSTETR DE LA PREMIERE PLACE VIDE
C          CHAINAGE SUIVANT DANS NSTETR(2,*) ET DERNIER A ZERO
C N1TESO : NUMERO DANS NOTESO DE LA PREMIERE PLACE VIDE
C          CHAINAGE SUIVANT DANS NOTESO(2,*) ET DERNIER A ZERO
C NO1TSO : NUMERO DU 1-ER TETRAEDRE DANS NOTESO DE CHAQUE SOMMET
C NOTESO : NOTESO(1,*) NUMERO DANS NSTETR DU TETRAEDRE
C          NOTESO(2,*) NUMERO DANS NOTESO DU TETRAEDRE SUIVANT
C                      0 SI C'EST LE DERNIER
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   DECEMBRE 1991
C....................................................................012
      INTEGER   NSTETR(NBSOTE,MXTETR),NOTESO(2,MXTESO),NO1TSO(MXSOMM)
C
C     MISE A ZERO DU POINTEUR
      DO I=1,MXSOMM
         NO1TSO(I) = 0
      ENDDO
C
C     BOUCLE SUR LES TETRAEDRES EXISTANTS
      N1TESO = 0
      DO NT=1,NBTETR
         DO I=1,4
C           LE SOMMET I DU TETRAEDRE NT
            NS = NSTETR(I,NT)
C           UNE PLACE VIDE DANS NOTESO  EN SEQUENCE POUR L'INSTANT
            N1TESO = N1TESO + 1
C           LE NUMERO DU TETRAEDRE DANS NSTETR
            NOTESO( 1, N1TESO ) = NT
C           CE NOUVEAU TETRAEDRE EST CHAINE SUR L'ANCIEN
            NOTESO( 2, N1TESO ) = NO1TSO( NS )
C           NT DEVIENT LE PREMIER TETRAEDRE DU SOMMET NS
            NO1TSO( NS ) = N1TESO
         ENDDO
      ENDDO
C
C     MISE EN OEUVRE DU CHAINAGE DES TETRAEDRES VIDES DE NOTESO
C     LE PREMIER NOTESO VIDE
      N1TESO = N1TESO + 1
      DO I=N1TESO,MXTESO
C        PAS DE TETRAEDRE
         NOTESO(1,I) = 0
C        LE TETRAEDRE SUIVANT
         NOTESO(2,I) = I+1
      ENDDO
C     FIN DU CHAINAGE NOTESO DES TETRAEDRES DES SOMMETS
      NOTESO(2,MXTESO) = 0
C
C     MISE EN OEUVRE DU CHAINAGE DES TETRAEDRES VIDES DE NSTETR
C     LE PREMIER NSTETR VIDE
      N1TEVI = NBTETR + 1
      DO I = N1TEVI, MXTETR
C        LE TETRAEDRE EST VIDE
         NSTETR(1,I) = 0
C        LE TETRAEDRE SUIVANT
         NSTETR(2,I) = I+1
      ENDDO
C     FIN DU CHAINAGE NSTETR DES TETRAEDRES VIDES
      NSTETR(2,MXTETR) = 0
C
      RETURN
      END
