      SUBROUTINE TORETI( NUSURF, RAPCTO, RAGCTO,
     %                   XYZCEN, XYZAXX, XYZAXY,
     %                   NTFASU, MNFASU, NTSOFA, MNSOFA, NOMSUR,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT:     GENERER LE MAILLAGE DE LA SURFACE FERMEE D'UN TORE
C -----    AVEC LA FONCTION TAILLE_IDEALE(x,y,z)
C                        OU    EDGE_LENTH(x,y,z)
C ENTREES:
C --------
C NUSURF : NUMERO DE LA SURFACE DANS LE LEXIQUE DES SURFACES
C RAPCTO : RAYON DU CERCLE INFERIEUR
C RAGCTO : RAYON DU CERCLE SUPERIEUR
C XYZCEN : XYZ DU CENTRE DU TORE
C XYZAXX : XYZ DU POINT SUR L'AXE PROPRE X DU TORE
C XYZAXY : XYZ DU POINT SUR L'AXE PROPRE Y DU TORE
C MXSOM  : NOMBRE MAXIMAL DE SOMMETS DECLARES DANS XYZSOM
C MXEF   : NOMBRE MAXIMAL DE EF DECLARES DANS NSEF
C
C SORTIES:
C --------
C NTFASU : NUMERO      DU TMS 'NSEF' DES NUMEROS DES ELEMENTS FINIS
C MNFASU : ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES ELEMENTS FINIS
C          CF '~td/d/a___nsef'
C NTSOFA : NUMERO      DU TMS 'XYZSOMMET' DE LA SURFACE
C MNSOFA : ADRESSE MCN DU TMS 'XYZSOMMET' DE LA SURFACE
C           CF '~td/d/a___xyzsommet'
C NOMSUR : NOM DE LA SURFACE DES PARAMETRES
C IERR   : =0 SI PAS D'ERREUR
C          >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2011
C2345X7..............................................................012
      include"./incl/ntmnlt.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/a_point__definition.inc"
      include"./incl/a_ligne__definition.inc"
      include"./incl/a_surface__definition.inc"
C     LE SUPER-TABLEAU OU TOUS LES TMC ET TMS OUVERTS SONT STOCKES
C     ICI LE TABLEAU DMCN REEL DOUBLE PRECISION N'EST PAS UTILE
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL             RMCN(1)
      DOUBLE PRECISION DMCN(1)
      EQUIVALENCE     ( MCN(1), RMCN(1), DMCN(1) )
C
      DOUBLE PRECISION  DMATRI, DMATM1
      COMMON /S09S01/   DMATRI(3,4), DMATM1(3,4), RAPCT, RAGCT
C
      REAL              XYZCEN(3), XYZAXX(3), XYZAXY(3)
C
      CHARACTER*1       KNBRE
      CHARACTER*24      NMSURF, NOMPOI(5), NOMLIG(3), NOMSUR
      INTEGER           NUSURF, NUMPOI(5), NUMLIG(3),
     %                  NBSLIG(3), MNLXYZ(3)
      REAL              XYZ3PI(3,3), XYZ3PF(3,3), XYZ(3), XYZPT(3,5)
      DOUBLE PRECISION  PI, PI2, DF(3,3)
      INTRINSIC         COS, SIN, SQRT, ATAN
C
C     LE NOM DE LA SURFACE
      CALL NMOBNU( 'SURFACE', NUSURF, NMSURF )
C
C     CHARGEMENT DU COMMON /S09S01/
      RAPCT = RAPCTO
      RAGCT = RAGCTO
      DO K=1,3
         NUMLIG(K) = 0
      ENDDO
C
C     CONSTRUIRE LA MATRICE DE TRANSFORMATION DES COORDONNEES POUR
C     PASSER D'UN REPERE DEFINI PAR 3 POINTS INITIAUX NON ALIGNES
C                               A   3 POINTS FINAUX   NON ALIGNES
C     ============================================================
C     LE REPERE INITIAL
      XYZ3PI(1,1) = 0.
      XYZ3PI(2,1) = 0.
      XYZ3PI(3,1) = 0.
C
      XYZ3PI(1,2) = RAGCTO
      XYZ3PI(2,2) = 0.
      XYZ3PI(3,2) = 0.
C
      XYZ3PI(1,3) = 0.
      XYZ3PI(2,3) = RAGCTO
      XYZ3PI(3,3) = 0.
C
C     LE REPERE FINAL AU CENTRE DU TORE
      XYZ3PF(1,1) = XYZCEN(1)
      XYZ3PF(2,1) = XYZCEN(2)
      XYZ3PF(3,1) = XYZCEN(3)
C
C     AXES X et Y PROPRE DU TORE
      XYZ3PF(1,2) = XYZAXX(1)
      XYZ3PF(2,2) = XYZAXX(2)
      XYZ3PF(3,2) = XYZAXX(3)
C
      XYZ3PF(1,3) = XYZAXY(1)
      XYZ3PF(2,3) = XYZAXY(2)
      XYZ3PF(3,3) = XYZAXY(3)
C
C     CONSTRUCTION DE LA MATRICE DE TRANSFORMATION QUI ENVOIE
C     LES 3 POINTS INITIAUX SUR LES 3 POINTS FINAUX
C     -------------------------------------------------------
      CALL TR3P3P( XYZ3PI, XYZ3PF, DMATRI, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     CALCUL DE LA MATRICE INVERSE DMATM1 DE L'ISOMETRIE
C     ------------------------------------------------
      DO J=1,3
         DO I=1,3
            DF(I,J) = DMATRI(I,J)
         ENDDO
      ENDDO
      CALL DFM1R3( DF, DMATM1, IERR )
C     LE VECTEUR
      DMATM1(1,4) = DMATRI(1,4)
      DMATM1(2,4) = DMATRI(2,4)
      DMATM1(3,4) = DMATRI(3,4)
C
C     LE DOMAINE DES PARAMETRES EST [RAGCTO * 2 PI] x [RAPCTO * 2 PI]
C     AINSI LA TRIANGULATION DANS CET ESPACE RESPECTE LA TAILLE DES ARETES
C     ====================================================================
      PI  = ATAN(1.D0) * 4.D0
      PI2 = PI * 2D0
C
C     CONSTRUCTION DU CERCLE DE L'EQUATEUR DU TORE
C     --------------------------------------------
C     CONSTRUCTION DES 3 POINTS SUR LE GRAND CERCLE
C
C     POINT 1 DU CERCLE EQUATEUR
      XYZ(1) = RAGCTO + RAPCTO
      XYZ(2) = 0.
      XYZ(3) = 0.
C     POINT APRES TRANSFORMATION
C     PASSAGE DU REPERE PROPRE DU TORE AU REPERE GENERAL
      CALL ISOMVA( DMATRI, XYZ, XYZPT(1,1) )
C
C     POINT 2 DU CERCLE EQUATEUR
      R = REAL( (RAGCTO + RAPCTO) / SQRT(2D0) )
      XYZ(1) = R
      XYZ(2) = R
      XYZ(3) = 0.
C     POINT APRES TRANSFORMATION
C     PASSAGE DU REPERE PROPRE DU TORE AU REPERE GENERAL
      CALL ISOMVA( DMATRI, XYZ, XYZPT(1,2) )
C
C     POINT 3 DU CERCLE EQUATEUR
      XYZ(1) = 0.
      XYZ(2) = RAGCTO + RAPCTO
      XYZ(3) = 0.
C     POINT APRES TRANSFORMATION
C     PASSAGE DU REPERE PROPRE DU TORE AU REPERE GENERAL
      CALL ISOMVA( DMATRI, XYZ, XYZPT(1,3) )
C
C     POINT 2 DU PETIT CERCLE DU PLAN XZ
      R = REAL( RAPCTO / SQRT(2D0) )
      XYZ(1) = RAGCTO + R
      XYZ(2) = 0.
      XYZ(3) = R
C     POINT APRES TRANSFORMATION
C     PASSAGE DU REPERE PROPRE DU TORE AU REPERE GENERAL
      CALL ISOMVA( DMATRI, XYZ, XYZPT(1,4) )
C
C     POINT 3 DU PETIT CERCLE DU PLAN XZ
      XYZ(1) = RAGCTO
      XYZ(2) = 0.
      XYZ(3) = RAPCTO
C     POINT APRES TRANSFORMATION
C     PASSAGE DU REPERE PROPRE DU TORE AU REPERE GENERAL
      CALL ISOMVA( DMATRI, XYZ, XYZPT(1,5) )
C
      DO K=1,5
C
C        CREATION DU POINT K DANS LE LEXIQUE DES POINTS
C        ----------------------------------------------
C        NOM DU POINT K SUR LE CERCLE
         NOMPOI(K) = NMSURF
         N = NUDCNB( NOMPOI(K) )
         N = MIN(N,21)
         WRITE(KNBRE,'(I1)') K
         NOMPOI(K) = NOMPOI(K)(1:N) // '_P' // KNBRE
C
C        SI CE POINT EXISTE, IL EST DETRUIT
         CALL LXLXOU( NTPOIN, NOMPOI(K), NT1PT, MN1PT )
         IF( MN1PT .GT. 0 ) CALL LXTSDS( NTPOIN, NOMPOI(K) )
C
C        CONSTRUCTION DU POINT K
         CALL LXLXDC( NTPOIN, NOMPOI(K), 24, 8 )
         CALL LXLXOU( NTPOIN, NOMPOI(K), NT1PT, MN1PT )
C        NUMERO DU POINT DANS LE LEXIQUE DES POINTS
         CALL NUOBNM( 'POINT', NOMPOI(K), NUMPOI(K) )
C
C        LE POINT A UN TMS DEFINITION DE POINT
         CALL LXTNDC( NT1PT, 'DEFINITION', 'MOTS', WOORPO+3 )
         CALL LXTSOU( NT1PT, 'DEFINITION', NT1PDE, MN1PDE )
C        TRANSFORMATION (I pour IDENTITE)
         MCN( MN1PDE + WTYTRP ) = 1
C        TYPE DU POINT
         MCN( MN1PDE + WUTYPO ) = 1
C        X Y Z
         RMCN( MN1PDE + WOORPO   ) = XYZPT(1,K)
         RMCN( MN1PDE + WOORPO+1 ) = XYZPT(2,K)
         RMCN( MN1PDE + WOORPO+2 ) = XYZPT(3,K)
C        AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
         MCN( MN1PDE + MOTVAR(6) ) = NONMTD('~>POINT>>DEFINITION')
C        AJOUT DE LA DATE
         CALL ECDATE( MCN(MN1PDE) )
C
C        LE TMS XYZSOMMET DU POINT K
         CALL LXTNDC( NT1PT, 'XYZSOMMET', 'MOTS', WYZSOM+3 )
         CALL LXTSOU( NT1PT, 'XYZSOMMET', NT1XYZ, MN1XYZ )
         MCN( MN1XYZ + WNBSOM ) = 1
         MCN( MN1XYZ + WNBTGS ) = 0
         MCN( MN1XYZ + WBCOOR ) = 3
         RMCN( MN1XYZ + WYZSOM   ) = XYZPT(1,K)
         RMCN( MN1XYZ + WYZSOM+1 ) = XYZPT(2,K)
         RMCN( MN1XYZ + WYZSOM+2 ) = XYZPT(3,K)
C        AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
         MCN( MN1XYZ + MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )
C        AJOUT DE LA DATE
         CALL ECDATE( MCN(MN1XYZ) )
C
      ENDDO
C
C     CONSTRUCTION DES 2 LIGNES CERCLES
C     ---------------------------------
      DO NULG = 1, 2
C
         WRITE(KNBRE,'(I1)') NULG
         NOMLIG(NULG) = NMSURF
         N = NUDCNB( NOMLIG(NULG) )
         N = MIN(N,21)
         NOMLIG(NULG) = NOMLIG(NULG)(1:N) // '_L' // KNBRE
C
C        SI CETTE LIGNE EXISTE, ELLE EST DETRUITE
         CALL LXLXOU( NTLIGN, NOMLIG(NULG), NT1LG, MN1LG )
         IF( MN1LG .GT. 0 ) CALL LXTSDS( NTLIGN, NOMLIG(NULG) )
C
         CALL LXLXDC( NTLIGN, NOMLIG(NULG), 24, 8 )
         CALL LXLXOU( NTLIGN, NOMLIG(NULG), NT1LG, MN1LG )
C        NUMERO DE LA LIGNE DANS LE LX DES LIGNES
         CALL NUOBNM( 'LIGNE', NOMLIG(NULG), NUMLIG(NULG) )
C
C        LA LIGNE A UN TMS DEFINITION DE LIGNE DE TYPE 8: CERCLE
         CALL LXTNDC( NT1LG, 'DEFINITION', 'MOTS', WUPT3C+1 )
         CALL LXTSOU( NT1LG, 'DEFINITION', NT1LDE, MN1LDE )
C        TRANSFORMATION (I pour IDENTITE)
         MCN( MN1LDE + WTYTRL ) = 1
C        TYPE DE LA LIGNE: CERCLE COMPLET DE R3
         MCN( MN1LDE + WUTYLI ) = 8
C        NOMBRE DE SOMMETS DE LA LIGNE: INACTIF
         MCN( MN1LDE + WBARLI ) = 16
C        TYPE DU CERCLE: 'cercle defini par 3 points sur le cercle'
         MCN( MN1LDE + WUTYCI ) = 1
C        NOM DES 3 POINTS SUR LE CERCLE NULG
C        variable NUPT1C nom 1-er  point sur le cercle
         MCN( MN1LDE + WUPT1C ) = NUMPOI(1)
         IF( NULG .EQ. 1 ) THEN
C           variable NUPT2C nom 2-eme point sur le cercle
            MCN( MN1LDE + WUPT2C ) = NUMPOI(2)
C           variable NUPT3C nom 3-eme point sur le cercle
            MCN( MN1LDE + WUPT3C ) = NUMPOI(3)
         ELSE
C           variable NUPT2C nom 2-eme point sur le cercle
            MCN( MN1LDE + WUPT2C ) = NUMPOI(4)
C           variable NUPT3C nom 3-eme point sur le cercle
            MCN( MN1LDE + WUPT3C ) = NUMPOI(5)
         ENDIF
C        AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
         MCN( MN1LDE + MOTVAR(6) ) = NONMTD( '~>LIGNE>>DEFINITION' )
C        AJOUT DE LA DATE
         CALL ECDATE( MCN(MN1LDE) )
C
C        CONSTRUCTION DE LA LIGNE NULG DE TYPE 8 CERCLE DE R3
         CALL LIEX08( NT1LG,  MCN(MN1LDE), RMCN(MN1LDE),
     %                NTARLI, MNARLI, NTSOLI, MNLXYZ(NULG), IERR )
         IF( IERR .NE. 0 ) GOTO 9999
         NBSLIG(NULG) = MCN( MNLXYZ(NULG) + WNBSOM )
C
      ENDDO
C
C     POUR LE GRAND CERCLE, RETOUR AUX PARAMETRES DU TORE
C     DANS [RAGCTO * 2 PI] x [RAPCTO * 2 PI]
C     ---------------------------------------------------
      MN1 = MNLXYZ(1) + WYZSOM
      DO K = 1, NBSLIG(1)
C        LE POINT DU GRAND CERCLE EQUATEUR RMCN(MN1+1:3)
C        DANS LE REPERE PROPRE DU TORE
         CALL XYZTOREM1( RMCN(MN1), R, S )
         RMCN(MN1  ) = R
         RMCN(MN1+1) = S
         RMCN(MN1+2) = 0
         MN1 = MN1 + 3
      ENDDO
C
C     POUR LE PETIT CERCLE, RETOUR AUX PARAMETRES DU TORE
C     DANS [RAGCTO * 2 PI] x [RAPCTO * 2 PI]
C     ---------------------------------------------------
      MN1 = MNLXYZ(2) + WYZSOM
      DO K = 1, NBSLIG(2)
C        LE POINT DU GRAND CERCLE EQUATEUR RMCN(MN1+1:3)
C        DANS LE REPERE PROPRE DU TORE
         CALL XYZTOREM1( RMCN(MN1), R, S )
         RMCN(MN1  ) = R
         RMCN(MN1+1) = S
         RMCN(MN1+2) = 0
         MN1 = MN1 + 3
      ENDDO
C
C     CONSTRUCTION DE LA LIGNE CONTOUR DU RECTANGLE DES PARAMETRES
C     A PARTIR DES 2 CERCLES MAILLES (CHACUN EST VU 2 FOIS)
C     ------------------------------------------------------------
C     NOMBRE DE SOMMETS SUR LE RECTANGLE DES PARAMETRES
      NBSLIG(3) = 2 * ( NBSLIG(1) + NBSLIG(2) ) + 1
      NOMLIG(3) = NMSURF
      N = NUDCNB( NOMLIG(3) )
      N = MIN(N,21)
      NOMLIG(3) = NOMLIG(3)(1:N) // '_L3'
C
C     SI CETTE LIGNE EXISTE, ELLE EST DETRUITE
      CALL LXLXOU( NTLIGN, NOMLIG(3), NT1LG, MN1LG )
      IF( MN1LG .GT. 0 ) CALL LXTSDS( NTLIGN, NOMLIG(3) )
C
      CALL LXLXDC( NTLIGN, NOMLIG(3), 24, 8 )
      CALL LXLXOU( NTLIGN, NOMLIG(3), NT1LG, MN1LG )
C     NUMERO DE LA LIGNE DANS LE LX DES LIGNES
      CALL NUOBNM( 'LIGNE', NOMLIG(3), NUMLIG(3) )
C
C     LA LIGNE A UN TMS DEFINITION DE LIGNE DE TYPE 7: LISTE XYZ
      CALL LXTNDC( NT1LG, 'DEFINITION', 'MOTS', WYZPLI+3*NBSLIG(3) )
      CALL LXTSOU( NT1LG, 'DEFINITION', NT1LDE, MN1LDE )
C     TRANSFORMATION (I pour IDENTITE)
      MCN( MN1LDE + WTYTRL ) = 1
C     TYPE DE LA LIGNE: 7: LISTE XYZ
      MCN( MN1LDE + WUTYLI ) = 7
C     NOMBRE DE SOMMETS
      MCN( MN1LDE + WBPOLI ) = NBSLIG(3)
C
C     XYZ DES NBPOLI SOMMETS DE LA LIGNE RECTANGLE
C
C     COTE 1 DU RECTANGLE
      MN1 = MNLXYZ(1) + WYZSOM
      MN2 = MN1LDE + WYZPLI
      DO K = 1, NBSLIG(1)
         RMCN(MN2  ) = RMCN(MN1)
         RMCN(MN2+1) = 0
         RMCN(MN2+2) = 0
         MN1 = MN1 + 3
         MN2 = MN2 + 3
      ENDDO
C
C     COTE 2 DU RECTANGLE
      MN1 = MNLXYZ(2) + WYZSOM
      DO K = 1, NBSLIG(2)
         RMCN(MN2  ) = REAL( RAGCTO * PI2 )
         RMCN(MN2+1) = RMCN(MN1+1)
         RMCN(MN2+2) = 0
         MN1 = MN1 + 3
         MN2 = MN2 + 3
      ENDDO
C
C     COTE 3 DU RECTANGLE
C     LE DERNIER DE LA LIGNE
      RMCN(MN2  ) = REAL( RAGCTO * PI2 )
      RMCN(MN2+1) = REAL( RAPCTO * PI2 )
      RMCN(MN2+2) = 0
      MN2 = MN2 + 3
      MN1 = MNLXYZ(1) + WYZSOM + 3*NBSLIG(1) - 3
      DO K = 2, NBSLIG(1)
         RMCN(MN2  ) = RMCN(MN1)
         RMCN(MN2+1) = REAL( RAPCTO * PI2 )
         RMCN(MN2+2) = 0
         MN1 = MN1 - 3
         MN2 = MN2 + 3
      ENDDO
C
C     COTE 4 DU RECTANGLE
C     LE DERNIER DE LA LIGNE
      RMCN(MN2  ) = 0
      RMCN(MN2+1) = REAL( RAPCTO * PI2 )
      RMCN(MN2+2) = 0
      MN2 = MN2 + 3
      MN1 = MNLXYZ(2) + WYZSOM + 3*NBSLIG(2) - 3
      DO K = 2, NBSLIG(2)
         RMCN(MN2  ) = 0
         RMCN(MN2+1) = RMCN(MN1+1)
         RMCN(MN2+2) = 0
         MN1 = MN1 - 3
         MN2 = MN2 + 3
      ENDDO
C
C     LE DERNIER POINT DE LA LIGNE EST LE PREMIER POUR LA FERMER
      MN1 = MN1LDE + WYZPLI
      RMCN(MN2  ) = RMCN(MN1  )
      RMCN(MN2+1) = RMCN(MN1+1)
      RMCN(MN2+2) = RMCN(MN1+2)
C
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MN1LDE + MOTVAR(6) ) = NONMTD( '~>LIGNE>>DEFINITION' )
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MN1LDE) )
C
C     CONSTRUCTION DE LA LIGNE DE TYPE 7 LISTE DE SOMMETS XYZ
      CALL LIEX07( NT1LG,  MCN(MN1LDE), RMCN(MN1LDE),
     %             NTARLI, MNARLI, NTSOLI, MNSOLI, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     TRIANGULATION DANS LE REPERE DES PARAMETRES DU TORE
C     ===================================================
C     CONSTRUCTION DES TMS DEFINITION, NSEF et XYZSOMMET
      NOMSUR = NMSURF
      N = NUDCNB( NOMSUR )
      N = MIN(N,21)
      NOMSUR = NOMSUR(1:N) // '_S1'
C
C     SI CETTE SURFACE EXISTE, ELLE EST DETRUITE
      CALL LXLXOU( NTSURF, NOMSUR, NT1SF, MN1SF )
      IF( MN1SF .GT. 0 ) CALL LXTSDS( NTSURF, NOMSUR )
C
C     CONSTRUCTION DE LA SURFACE TRIANGULATION DU RECTANGLE DES PARAMETRES
      CALL LXLXDC( NTSURF, NOMSUR, 24, 8 )
      CALL LXLXOU( NTSURF, NOMSUR, NT1SF, MN1SF )
C
C     LA SURFACE A UN TMS DEFINITION DE SURFACE 9:
C     TRIANGULATION ENTRE LIGNES FERMEES
      CALL LXTNDC( NT1SF, 'DEFINITION', 'MOTS', WULFTR+1 )
      CALL LXTSOU( NT1SF, 'DEFINITION', NT1SDE, MN1SDE )
C     TRANSFORMATION (I POUR IDENTITE)
      MCN( MN1SDE + WTYTRS ) = 1
C     TYPE DE LA SURFACE
      MCN( MN1SDE + WUTYSU ) = 9
C     ARETMX MAX LENGTH OF EDGES OF REGULAR TRIANGLES  INACTIVE
      RMCN( MN1SDE + WRETMX ) = 1.
C     NBLFTR  NUMBER OF CLOSED LINES CONTOUR OF THE SURFACE
      MCN( MN1SDE + WBLFTR ) = 1
C     NBPTIT NUMBER OF INTERNAL POINTS FUTURE VERTICES
      MCN( MN1SDE + WBPTIT ) = 0
C     TABLEAU  NULFTR(1..NBLFTR) NAME OF CLOSED LINES ^~>LIGNE
      MCN( MN1SDE + WULFTR ) = NUMLIG(3)
C     TABLEAU NUPTIT(1..NBPTIT) NAME OF INTERNAL POINTS FUTURE VERTICES
C     INEXISTANT CAR NBPTIT=0
C     AJOUT DU NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MN1SDE + MOTVAR(6) ) = NONMTD( '~>SURFACE>>DEFINITION' )
C     AJOUT DE LA DATE
      CALL ECDATE( MCN(MN1SDE) )
C
C     TRIANGULATION DU RECTANGLE DES PARAMETRES
      CALL SUEX09( 23, NT1SF, MCN(MN1SDE), RMCN(MN1SDE),
     %                 NTFASU, MNFASU, NTSOFA, MNSOFA, IERR )
      IF( IERR .GT. 0 ) GOTO 9999
C
C     PASSAGE AUX COORDONNEES DU REPERE PROPRE, PUIS FINAL
      MN = MNSOFA + WYZSOM
      DO K = 1, MCN( MNSOFA + WNBSOM )
C        LES ANGLES PARAMETRES DU TORE DONNENT LES COORDONNEES
C        XYZ DANS LE REPERE FINAL DU TORE
         CALL XYZTORE( RMCN(MN), RMCN(MN+1),  RMCN(MN) )
         MN = MN + 3
      ENDDO
C
C     DESTRUCTION DU LEXIQUE DES LIGNES INTERMEDIAIRES
      DO NULG=1,3
         IF( NUMLIG(NULG) .GT. 0 ) CALL LXTSDS( NTLIGN, NOMLIG(NULG) )
      ENDDO
C
 9999 RETURN
      END
