      SUBROUTINE TR1ACF( NBET,   NA01,   NA1,    NA2,    NF1,  NF3,
     %                   N1TRVI, NOTRIA, NOTRSO,
     %                   MXETRI, N1ARCF, NOARCF, NF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    MODIFICATION DE LA TRIANGULATION DU CONTOUR FERME NBET
C -----    PAR AJOUT D'UN TRIANGLE AYANT 1 ARETE SUR LE CONTOUR
C          MODIFICATION DU CONTOUR PAR AJOUT DE LA 3-EME ARETE
C          CREATION D'UN CONTOUR FERME A PARTIR DE LA SECONDE ARETE
C
C ENTREES:
C --------
C NBET    : NUMERO DANS N1ARCF DU CF TRAITE ICI
C NA01    : NUMERO NOARCF DE L'ARETE PRECEDENT L'ARETE NA1 DE NOARCF
C NA1     : NUMERO NOARCF DU 1-ER SOMMET DU TRIANGLE
C           IMPLICITEMENT L'ARETE NA1 N'EST PAS UNE ARETE DU TRIANGLE
C NA2     : NUMERO NOARCF DU 2-EME SOMMET DU TRIANGLE
C           CETTE ARETE EST L'ARETE 2 DU TRIANGLE A AJOUTER
C           SON ARETE SUIVANTE DANS NOARCF N'EST PAS SUR LE CONTOUR
C NF1,NF3 : NUMERO DU TRIANGLE NOTRIA EXTERIEUR A LA 1-ERE ET 3-EME ARETE
C N1TRVI  : NOMBRE MAXIMAL DE TRIANGLES PERMIS POUR LA TRIANGULATION
C
C ENTREES ET SORTIES :
C --------------------
C NOTRIA : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES
C NOTRSO : NOTRSO(I) NUMERO D'UN TRIANGLE DE NOTRIA DE SOMMET I
C N1ARCF : NUMERO D'UNE ARETE DE CHAQUE CONTOUR
C NOARCF : NUMERO DES ARETES DE LA LIGNE DU CONTOUR FERME
C          ATTENTION : CHAINAGE CIRCULAIRE DES ARETES
C
C SORTIE :
C --------
C NF     : NUMERO DU TRIANGLE AJOUTE DANS NOTRIA
C          0 SI SATURATION DU TABLEAU NOTRIA OU NOARCF OU N1ARCF
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    FEVRIER 1992
C2345X7..............................................................012
      include"./incl/gsmenu.inc"
      INTEGER           NOTRSO(*),
     %                  NOTRIA(6,*),
     %                  N1ARCF(0:*),
     %                  NOARCF(3,*)
C
C     L' ARETE SUIVANTE DU TRIANGLE NON SUR LE CF
      NA3 = NOARCF( 2, NA2 )
C
C     LE TRIANGLE A L'ARETE 2 COMME ARETE DU CONTOUR NA2
C     ==================================================
C     AJOUT DANS NOTRIA DE CE TRIANGLE NF
      CALL TRAJFA( NOARCF(1,NA1), NOARCF(1,NA2), NOARCF(1,NA3),
     %             NF1, NOARCF(3,NA2), NF3,
     %             N1TRVI, NOTRIA, NOTRSO, NF )
      IF( NF .LE. 0 ) RETURN
C
C     MODIFICATION DU CONTOUR EXISTANT
C     ================================
C     SUPPRESSION DE L'ARETE NA2 DU CF
C     MODIFICATION DU CF EN POINTANT NA2 SUR NA1
      NOARCF( 2, NA2 ) = NA1
      NOARCF( 3, NA2 ) = NF
C     DEBUT DU CF
      N1ARCF( NBET ) = NA2
C
C     CREATION D'UN NOUVEAU CONTOUR FERME NA3 - NA1
C     =============================================
      IF( NBET .GE. MXETRI ) THEN
         NBLGRC(NRERR) = 1
         KERR(1) ='SATURATION DU NOMBRE DE CONTOURS FERMES'
         NF = 0
         RETURN
      ENDIF
      NBET = NBET + 1
C
C     RECHERCHE D'UNE ARETE DE CF VIDE
      NAV = N1ARCF(0)
      IF( NAV .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         KERR(1) ='SATURATION DU NOMBRE D''ARETES DE CF'
         NF = 0
         RETURN
      ENDIF
C     LA 1-ERE ARETE VIDE EST MISE A JOUR
      N1ARCF(0) = NOARCF( 2, NAV )
C
C     AJOUT DE L'ARETE NAV POINTANT SUR NA3
C     LE NUMERO DU SOMMET
      NOARCF( 1, NAV ) = NOARCF( 1, NA1 )
C     L'ARETE SUIVANTE
      NOARCF( 2, NAV ) = NA3
C     LE TRIANGLE NOTRIA OPPOSE
      NOARCF( 3, NAV ) = NF
C
C     L'ARETE PRECEDENTE NA01 DE NA1 POINTE SUR LA NOUVELLE NAV
      NOARCF( 2, NA01 ) = NAV
C
C     DEBUT DU CF
      N1ARCF( NBET ) = NAV
      END
