      SUBROUTINE TRACECF( PTXYZD, MXFACO, LEFACO, NOTETR,
     %                    NBSTCF, NOSTCF,
     %                    NBTRCF, NOTRCF,
     %                    NBTECF, NOTECF )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACER DES SOMMETS TRIANGLES ET TETRAEDRES D'UN CF LEFACO
C -----
C ENTREES:
C --------
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          LEFACO(11,.) = NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE, 0 SINON
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C NBSTCF : NOMBRE DE SOMMETS DU CF
C NOSTCF : NUMERO DES NBSTCF SOMMETS DU CF
C NBTRCF : NOMBRE DE TRIANGLES DU CF
C NOTRCF : NUMERO DES NBTRCF TRIANGLES DU CF
C NBTECF : NOMBRE DE TETRAEDRES DU CF
C NOTECF : NUMERO DES NBSTCF TETRAEDRES DU CF
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC ET ST PIERRE DU PERRAY   AVRIL 2008
C2345X7..............................................................012
      include"./incl/trvari.inc"
      include"./incl/mecoit.inc"
C
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE
C     STOPTE = FAUX ==> PAS D'ARRET APRES LE TRACE DE CHAQUE TETRAEDRE
C              VRAI ==> DEMANDE D'UN CARACTERE POUR REDEMARRER
C     TRACTE = FAUX ==> PAS DE TRACE DES TETRAEDRES
C              VRAI ==> TRACE DES TETRAEDRES DE L'ETOILE
C
      DOUBLE PRECISION  PTXYZD(4,*)
      INTEGER           LEFACO(1:11,0:MXFACO)
      INTEGER           NOTETR(8,*)
      INTEGER           NOSTCF(NBSTCF), NOTRCF(NBTRCF), NOTECF(NBTECF)
      REAL              XYZ(3)
C
      IF( .NOT. TRACTE ) RETURN
C
C     TRACE EN MODE 3 BOUTONS POUR DEPLACEMENT ROTATIONS ZOOM
      PREDU0 = PREDUF
      PREDUF  = 20.0
      LORBITE = 1
      IF( LORBITE .EQ. 0 ) GOTO 20
C
C     INITIALISATION DE L'ORBITE
C     ==========================
      CALL ORBITE0( NOTYEV )
      GOTO 20
C
C     TRACE SELON L'ORBITE OU ZOOM OU TRANSLATION ACTIFS
C     ==================================================
 10   CALL ORBITE1( NOTYEV )
      IF( NOTYEV .EQ. 0 ) GOTO 9000
C
C     TRACE DES AXES 3D
      CALL TRAXE3
C
C     LE TRACE DES 3 ARETES DES FACES TRIANGULAIRES DU TABLEAU LEFACO
 20   DO 30 NF=1,MXFACO
         IF( LEFACO(11,NF) .GT. 0 ) THEN
            CALL TRARTR( NCNOIR, LEFACO(1,NF), PTXYZD )
         ENDIF
 30   CONTINUE
C
C     LE TRACE DES SOMMETS DU TABLEAU NOSTCF
      DO 50 N = 1, NBSTCF
         NS = NOSTCF(N)
         XYZ(1) = REAL( PTXYZD(1,NS) )
         XYZ(2) = REAL( PTXYZD(2,NS) )
         XYZ(3) = REAL( PTXYZD(3,NS) )
         CALL ENTIER3D( NCMAGE, XYZ, NS )
 50   CONTINUE
C
C     LE TRACE DES TRIANGLES DU CF DU TABLEAU LEFACO
      NCF = NCROUG
      NCA = NCBLEU
      DO 60 NF=1,NBTRCF
         CALL TRFATR( NCF, NCA, LEFACO(1,NOTRCF(NF)), PTXYZD )
 60   CONTINUE
C
C     LE TRACE DES 6 ARETES DES TETRAEDRES DU TABLEAU LEFACO
      DO 80 NF=1,NBTECF
         CALL TRTETRA( NCBLEU, NOTETR(1,NOTECF(NF)), PTXYZD )
 80   CONTINUE
C
C     TITRE ET TRACE EFFECTIF
      CALL TRFINS( 'SOMMETS TRIANGLES TETRAEDRES du CF' )
C
C     REPRISE DE L'ORBITE
C     ===================
      IF( LORBITE .NE. 0 ) GOTO 10
C
 9000 PREDUF = PREDU0
      RETURN
      END
