      SUBROUTINE TRASGI( NBS1, XYZS1,  NBTRS1, NUSTS1, PSGISF1, NT1,
     %                   NBS2, XYZS2,  NBTRS2, NUSTS2, PSGISF2, NT2,
     %                   MXSGI,NSTSGI, MXCHSGI,LCHSGI, MXPTA,   XYZPTA,
     %                   NBPT, PT )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACE DES SEGMENTS D'INTERSECTION ENTRE LE TRIANGLE NT1
C -----    DE LA SURFACE 1 ET LE TRIANGLE NT2 DE LA SURFACE 2
C
C ENTREES:
C --------
C NBS1   : NOMBRE  DE     SOMMETS DE LA SURFACE 1
C XYZS1  : 3 XYZ DES NBS1 SOMMETS DE LA SURFACE 1
C NBTRS1 : NOMBRE DE TRIANGLES    DE LA SURFACE 1
C NUSTS1 : (4,NBTRS1) NUMERO DANS XYZS1 DES 3 SOMMETS + 0 EN POSITION 4
C PSGISF1: (NBTRS1) POINTEUR SUR 1-ER SEGMENT INTERSECTION DE CHAQUE
C          TRIANGLE DE LA SURFACE 1
C NT1    : NUMERO DU TRIANGLE A TRACER AVEC SES SGI
C
C NBS2   : NOMBRE  DE     SOMMETS DE LA SURFACE 2
C XYZS2  : 3 XYZ DES NBS2 SOMMETS DE LA SURFACE 2
C NBTRS2 : NOMBRE DE TRIANGLES    DE LA SURFACE 2
C NUSTS2 : (4,NBTRS2) NUMERO DANS XYZS2 DES 3 SOMMETS + 0 EN POSITION 4
C PSGISF2: (NBTRS2) POINTEUR SUR 1-ER SEGMENT INTERSECTION DE CHAQUE
C          TRIANGLE DE LA SURFACE 2
C NT2    : NUMERO DU TRIANGLE A TRACER AVEC SES SGI
C
C MXSGI  : NOMBRE MAXIMAL DE SGI DECLARABLES DANS NSTSGI
C NSTSGI : NUMERO DANS XYZPTA DES 2 POINTS EXTREMITES DU SEGMENT INTERSECTION
C          NUMERO DU TRIANGLE DANS NUSTS1 ET DANS NUSTS2
C
C MXCHSGI: NOMBRE MAXIMAL DE SGI DECLARABLES DANS LCHSGI
C LCHSGI : NUMERO DU SGI et CHAINAGE SUR LE SUIVANT
C
C MXPTA  : NOMBRE MAXIMAL DE POINTS AJOUTES DECLARABLES DANS XYZPTA
C XYZPTA : 3 XYZ  DES POINTS AJOUTES, SOMMET DES ARETES D'INTERSECTION
C NBPT   : NOMBRE DE POINTS A TRACER
C PT     : PT(3,NBPT) XYZ DES NBPT POINTS
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET Alain LJLL UPMC& St Pierre du Perray SEPTEMBRE 2011
C2345X7..............................................................012
      include"./incl/trvari.inc"
      COMMON / UNITES /  LECTEU, IMPRIM, INTERA, NUNITE(29)
C
      DOUBLE PRECISION  XYZS1(3,NBS1), XYZS2(3,NBS2), XYZPTA(3,MXPTA),
     %                  PT(3,NBPT)
      INTEGER           NSTSGI(4,MXSGI),  LCHSGI(2,MXCHSGI),
     %                  PSGISF1(NBTRS1),  PSGISF2(NBTRS2),
     %                  NUSTS1(4,NBTRS1), NUSTS2(4,NBTRS2)
C
      REAL              R, COMIMX(3,2), XYZ1(3), XYZ2(3), XYZ3(3),
     %                  XYZB(3)
C
C     CADRE DE TRACE ENGLOBANT LES 2 TRIANGLES NT1 et NT2
      DO K=1,3
         R = REAL( XYZS1( K, NUSTS1(1,NT1) ) )
         COMIMX(K,1) = R
         COMIMX(K,2) = R
         DO N = 2, 3
            R = REAL( XYZS1( K, NUSTS1(N,NT1) ) )
            COMIMX(K,1) = MIN( COMIMX(K,1), R )
            COMIMX(K,2) = MAX( COMIMX(K,2), R )
         ENDDO
         DO N = 1, 3
            R = REAL( XYZS2( K, NUSTS2(N,NT2) ) )
            COMIMX(K,1) = MIN( COMIMX(K,1), R )
            COMIMX(K,2) = MAX( COMIMX(K,2), R )
         ENDDO
      ENDDO
C
C     POSITION DU POINT VISE AXOPTV ET DE L'OEIL AXOEIL
      DO K=1,3
         AXOPTV(K) = ( COMIMX(K,1) + COMIMX(K,2) ) / 2
         AXOEIL(K) = AXOPTV(K)
      ENDDO
      AXOEIL(1) = AXOPTV(1) + COMIMX(1,2) - COMIMX(1,1)
C
C     L'AXONOMETRIE
      NOTYVI = 11
      CALL MATAXO
C
ccc      IF( INTERA .EQ. 3 ) THEN
         LORBITE = 1
ccc      ELSE
ccc         LORBITE = 0
ccc      ENDIF
C
C     LES TRACES SONT DEMANDES
C     INITIALISATION DE L'ORBITE ZOOM DEPLACEMENT
      IF( LORBITE .NE. 0 ) THEN
         CALL ORBITE0( NOTYEV )
         IF( NOTYEV .EQ. 0 ) GOTO 9900
      ENDIF
C
C     LA MEMOIRE PIXEL EST EFFACEE
 10   CALL EFFACEMEMPX
C
C     TRACE DES AXES
      CALL TRAXE3
C
C     TRACE DES 3 ARETES DU TRIANGLE NT1
C     LES X,Y DES 3 SOMMETS POUR LE TRACE DU TRIANGLE NT1
      NS1     = NUSTS1(1,NT1)
      XYZ1(1) = REAL( XYZS1(1,NS1) )
      XYZ1(2) = REAL( XYZS1(2,NS1) )
      XYZ1(3) = REAL( XYZS1(3,NS1) )
C
      NS2     = NUSTS1(2,NT1)
      XYZ2(1) = REAL( XYZS1(1,NS2) )
      XYZ2(2) = REAL( XYZS1(2,NS2) )
      XYZ2(3) = REAL( XYZS1(3,NS2) )
C
      NS3     = NUSTS1(3,NT1)
      XYZ3(1) = REAL( XYZS1(1,NS3) )
      XYZ3(2) = REAL( XYZS1(2,NS3) )
      XYZ3(3) = REAL( XYZS1(3,NS3) )
C
C     LE TRACE DES 3 ARETES DE NT1
      CALL TRAIT3D( NCBLEU, XYZ1, XYZ2 )
      CALL TRAIT3D( NCBLEU, XYZ2, XYZ3 )
      CALL TRAIT3D( NCBLEU, XYZ3, XYZ1 )
C
C     TRACE DU NUMERO DES SOMMETS DU TRIANGLE NT1
      CALL ENTIER3D( NCNOIR, XYZ1, NS1 )
      CALL ENTIER3D( NCNOIR, XYZ2, NS2 )
      CALL ENTIER3D( NCNOIR, XYZ3, NS3 )
C
C     LE BARYCENTRE DE NT1
      XYZB(1) = (XYZ1(1) + XYZ2(1) + XYZ3(1) ) / 3
      XYZB(2) = (XYZ1(2) + XYZ2(2) + XYZ3(2) ) / 3
      XYZB(3) = (XYZ1(3) + XYZ2(3) + XYZ3(3) ) / 3
      CALL ENTIER3D( NCBLEU, XYZB, NT1 )
C
C     TRACE DES SGI DU TRIANGLE NT1
C     NUMERO DANS LCHSGI DU 1-ER SGI de NT1
      NCH = PSGISF1( NT1 )
 30   IF( NCH .GT. 0 ) THEN
C
C        NUMERO DANS NSTSGI DU SGI DANS NT1
         NSGI = LCHSGI( 1, NCH )
C
C        LES 2 POINTS DANS XYZPTA EXTREMITES DU SGI NSGI
         NP1 = NSTSGI(1,NSGI)
         NP2 = NSTSGI(2,NSGI)
C
C        TRACE DU SGI NSGI DANS NT1
         XYZ1(1) = REAL( XYZPTA(1,NP1) )
         XYZ1(2) = REAL( XYZPTA(2,NP1) )
         XYZ1(3) = REAL( XYZPTA(3,NP1) )
         XYZ2(1) = REAL( XYZPTA(1,NP2) )
         XYZ2(2) = REAL( XYZPTA(2,NP2) )
         XYZ2(3) = REAL( XYZPTA(3,NP2) )
         CALL TRAIT3D(  NCROUG, XYZ1, XYZ2 )
         CALL ENTIER3D( NCROSE, XYZ1, NP1 )
         CALL ENTIER3D( NCROSE, XYZ2, NP2 )
C
C        LE SGI SUIVANT DE NT1
         NCH = LCHSGI( 2, NCH )
         GOTO 30
C
      ENDIF
C
C     TRACE DES 3 ARETES DU TRIANGLE NT2
C     LES X,Y DES 3 SOMMETS POUR LE TRACE DU TRIANGLE NT2
      NS1     = NUSTS2(1,NT2)
      XYZ1(1) = REAL( XYZS2(1,NS1) )
      XYZ1(2) = REAL( XYZS2(2,NS1) )
      XYZ1(3) = REAL( XYZS2(3,NS1) )
C
      NS2     = NUSTS2(2,NT2)
      XYZ2(1) = REAL( XYZS2(1,NS2) )
      XYZ2(2) = REAL( XYZS2(2,NS2) )
      XYZ2(3) = REAL( XYZS2(3,NS2) )
C
      NS3     = NUSTS2(3,NT2)
      XYZ3(1) = REAL( XYZS2(1,NS3) )
      XYZ3(2) = REAL( XYZS2(2,NS3) )
      XYZ3(3) = REAL( XYZS2(3,NS3) )
C
C     LE TRACE DES 3 ARETES DE NT2
      CALL TRAIT3D( NCVERT, XYZ1, XYZ2 )
      CALL TRAIT3D( NCVERT, XYZ2, XYZ3 )
      CALL TRAIT3D( NCVERT, XYZ3, XYZ1 )
C
C     TRACE DU NUMERO DES SOMMETS DU TRIANGLE NT2
      CALL ENTIER3D( NCNOIR, XYZ1, NS1 )
      CALL ENTIER3D( NCNOIR, XYZ2, NS2 )
      CALL ENTIER3D( NCNOIR, XYZ3, NS3 )
C
C     LE BARYCENTRE DE NT2
      XYZB(1) = (XYZ1(1) + XYZ2(1) + XYZ3(1) ) / 3
      XYZB(2) = (XYZ1(2) + XYZ2(2) + XYZ3(2) ) / 3
      XYZB(3) = (XYZ1(3) + XYZ2(3) + XYZ3(3) ) / 3
      CALL ENTIER3D( NCVERT, XYZB, NT2 )
C
C     TRACE DES SGI DU TRIANGLE NT2
C     NUMERO DANS LCHSGI DU 1-ER SGI de NT2
      NCH = PSGISF2( NT2 )
 50   IF( NCH .GT. 0 ) THEN
C
C        NUMERO DANS NSTSGI DU SGI DANS NT2
         NSGI = LCHSGI( 1, NCH )
C
C        LES 2 POINTS DANS XYZPTA EXTREMITES DU SGI NSGI
         NP1 = NSTSGI(1,NSGI)
         NP2 = NSTSGI(2,NSGI)
C
C        TRACE DU SGI NSGI DANS NT2
         XYZ1(1) = REAL( XYZPTA(1,NP1) )
         XYZ1(2) = REAL( XYZPTA(2,NP1) )
         XYZ1(3) = REAL( XYZPTA(3,NP1) )
         XYZ2(1) = REAL( XYZPTA(1,NP2) )
         XYZ2(2) = REAL( XYZPTA(2,NP2) )
         XYZ2(3) = REAL( XYZPTA(3,NP2) )
         CALL TRAIT3D(  NCJAUN, XYZ1, XYZ2 )
         CALL ENTIER3D( NCBLAN, XYZ1, NP1 )
         CALL ENTIER3D( NCBLAN, XYZ2, NP2 )
C
C        LE SGI SUIVANT DE NT2
         NCH = LCHSGI( 2, NCH )
         GOTO 50
C
      ENDIF
C
C     TRACE DES EVENTUELS POINTS
      DO K=1,NBPT
         XYZ1(1) = REAL( PT(1,K) )
         XYZ1(2) = REAL( PT(2,K) )
         XYZ1(3) = REAL( PT(3,K) )
         CALL SYMBOLE3D( NCROUG, XYZ1, '.Pt' )
      ENDDO
C
C     COPIE DE MEMPX DANS FENETRE
      CALL MEMPXFENETRE
C
C     REPRISE DE L'ORBITE
      IF( LORBITE .GT. 0 ) THEN
         CALL ORBITE1( NOTYEV )
         IF( NOTYEV .NE. 0 ) GOTO 10
      ENDIF
C
 9900 RETURN
      END
