      SUBROUTINE TRBARF( MOARFR, MXARFR, L1ARFR, LAREFR,
     %                   NBCOOR, XYZPOI,
     %                   LEDECA, NOFAFR, DIFAFR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE BARYCENTRE DE CHAQUE ARETE FRONTALIERE
C -----    CALCULER LA COTE AXONOMETRIQUE DE CES BARYCENTRES
C          A PARTIR DE LA POSITION LEDECA+1 DES TABLEAUX
C
C ENTREES:
C --------
C MOARFR : NOMBRE DE MOTS PAR ARETE FRONTALIERE DU TABLEAU LAREFR
C MXARFR : NOMBRE DE FACES DU TABLEAU LAREFR
C L1ARFR : NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
C LAREFR : TABLEAU NUMERO DES 2 SOMMETS ET LIEN
C          LAREFR(1,I)= NO DU 1-ER  SOMMET DE L'ARETE FRONTALIERE
C          LAREFR(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LAREFR(3,I)= 0 OU NUMERO DE L'ARETE FRONTALIERE SUIVANTE
C NBCOOR : NOMBRE DE COORDONNEES D'UN POINT
C XYZPOI : XYZ DES POINTS DES EF DU MAILLAGE
C LEDECA : NOMBRE DE DECALAGES DE L'INDICE DANS LES TABLEAUX
C
C SORTIES:
C --------
C ATTENTION : LES VALEURS CALCULEES ICI DEBUTENT EN POSITION LEDECA+1
C NOFAFR : -NUMERO DE LA FACE FRONTALIERE DANS LAREFR
C DIFAFR : COTE AXONOMETRIQUE DU BARYCENTRE DES ARETES
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1994
C ...................................................................012
      include"./incl/trvari.inc"
      INTEGER        LAREFR(1:MOARFR,1:MXARFR)
      REAL           XYZPOI(1:NBCOOR,1:*)
      INTEGER        NOFAFR(1:*)
      REAL           DIFAFR(1:*)
      REAL           XYZ(3)
C
C     BOUCLE SUR LES ARETES FRONTALIERES
      I = LEDECA
      N = L1ARFR
 10   IF( N .GT. 0 ) THEN
C
C        L'ARETE N DE LAREFR EST FRONTALIERE
         I = I + 1
C        LE NUMERO DE L'ARETE FRONTALIERE I DANS LE TABLEAU LAREFR
         NOFAFR(I) = -N
C
C        LES COORDONNEES DU BARYCENTRE DE L'ARETE
         DO 30 K=1,3
C           LAREFR(J,N) NUMERO DU SOMMET J DE L'ARETE FRONTALIERE N
            XYZ(K)= (XYZPOI(K,LAREFR(1,N)) + XYZPOI(K,LAREFR(2,N)) )*0.5
 30      CONTINUE
C
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         DIFAFR(I) = XYZ(3)
C
C        PASSAGE A L'ARETE FRONTALIERE SUIVANTE
         N = LAREFR(3,N)
         GOTO 10
      ENDIF
C
      RETURN
      END
