      SUBROUTINE TRBFIS( TRIANG, NBFPLA, NBCOPS, NOAXE, XYZFIP,
     %                   NOFAFR, DIFAFR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ETABLIR LE TABLEAU DES NUMEROS DES FACES INTERSECTIONS PLANS
C -----    A LA SUITE DE CELUI DES FACES FRONTALIERES
C          CALCULER LA COTE AXONOMETRIQUE DES BARYCENTRES DE CES FACES
C ENTREES:
C --------
C TRIANG : REEL VALEUR TEMOIN DE TRIANGLE DANS XYZFIP(3,4,.)
C NBFPLA : NOMBRE DE FACES INTERSECTIONS AVEC LES PLANS
C NBCOPS : NOMBRE DE COORDONNEES DE CHAQUE SOMMET (3 SECTION ou 4 PROFILS)
C NOAXE  : NUMERO DE LA COORDONNEE DU PLAN DE COUPE (1 a 3) ou 4 PLAN QCQ
C XYZFIP : XYZ (CTE du PLAN si PROFILS) DES 4 SOMMETS DES FACES INTERSECTION
C
C SORTIES:
C --------
C NOFAFR : NUMERO DE CHAQUE FACE INTERSECTION
C DIFAFR : COTE AXONOMETRIQUE DU BARYCENTRE DES FACES INTERSECTIONS
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR :PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS      OCTOBRE 1994
C AUTEUR :PERRONNET ALAIN ANALYSE NUMERIQUE LJLL UPMC PARIS OCTOBRE 2003
C ...................................................................012
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      REAL              XYZFIP(1:NBCOPS,1:4,1:NBFPLA)
      INTEGER           NOFAFR(1:NBFPLA)
      REAL              DIFAFR(1:NBFPLA),
     %                  XYZ(3), AXYZ(3)
      LOGICAL           PLAN
C
C     TRACE DANS LES PLANS DE COUPE
      PLAN = NBCOPS .EQ. 4 .AND. 1 .LE. NOAXE .AND. NOAXE .LE. 3
C
C     BOUCLE SUR LES FACES DES SURFACES INTERSECTIONS
      DO 100 N=1,NBFPLA
C
C        LE NUMERO DE LA FACE DANS L'ENSEMBLE FACES FRONTALIERES + FIP
         NOFAFR( N ) = N
C
C        CALCUL DES BARYCENTRES
C        LE NOMBRE DE SOMMETS DE LA FACE INTERSECTION N
         IF( XYZFIP(3,4,N) .EQ. TRIANG ) THEN
            NBS = 3
         ELSE
            NBS = 4
         ENDIF
C
C        LES COORDONNEES DU BARYCENTRE DE CETTE FACE
         DO 30 K=1,3
            XYZ(K) = 0.0
            DO 20 J=1,NBS
               XYZ(K) = XYZ(K) + XYZFIP(K,J,N)
 20         CONTINUE
            XYZ(K) = XYZ(K) / NBS
 30      CONTINUE
C
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, AXYZ )
         DIFAFR( N ) = AXYZ(3)
C
         IF( PLAN ) THEN
C
C           LE NUMERO DE LA FACE DANS L'ENSEMBLE FACES FRONTALIERES + FIP
            NOFAFR( NBFPLA+N ) = NBFPLA+N
C
C           COORDONNEE DU PLAN
            XYZ( NOAXE ) = XYZFIP(NBCOPS,1,N)
C
C           COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
            CALL XYZAXO( XYZ, AXYZ )
            DIFAFR( NBFPLA+N ) = AXYZ(3)
C
         ENDIF
C
 100  CONTINUE
C
      RETURN
      END
