      SUBROUTINE TRC1ST( NS1, NT0, NOTRIA, MXPILE, LHPILE, LAPILE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   RECHERCHE DES TRIANGLES DE SOMMET NS1
C -----   LIMITE: UN CAMEMBERT DE CENTRE NS1 ENTAME 2 FOIS
C                 NE DONNE QUE L'UNE DES PARTIES
C
C ENTREES:
C --------
C NS1    : NUMERO DU SOMMET
C NT0    : NUMERO DANS NOTRIA D'UN TRIANGLE DE SOMMET NS1
C NOTRIA : LISTE DES TRIANGLES
C                 ------- ------- ------- -------- -------- --------
C  PAR TRIANGLE : SOMMET1 SOMMET2 SOMMET3 TR_VOIS1 TR_VOIS2 TR_VOIS3
C                 ------- ------- ------- -------- -------- --------
C                 SOMMET    EST LE NUMERO DU SOMMET
C                 TR_VOIS i EST LE NUMERO DANS NOTRIA DU TRIANGLE
C                          ADJACENT PAR L'ARETE i
C MXPILE : NOMBRE MAXIMAL DE TRIANGLES EMPILABLES
C
C SORTIES :
C --------
C LHPILE : NOMBRE DE TRIANGLES EMPILES
C          0       SI IMPOSSIBLE DE TOURNER AUTOUR DU POINT
C          -LHPILE SI APRES BUTEE SUR LA FRONTIERE IL Y A A NOUVEAU
C          BUTEE SUR LA FRONTIERE . A CE STADE ON NE PEUT DIRE SI TOUS
C          LES TRIANGLES AYANT CE SOMMET ONT ETE RECENSES
C          CE CAS ARRIVE SEULEMENT SI LE SOMMET EST SUR LA FRONTIERE
C LAPILE : NUMERO DANS NOTRIA DES TRIANGLES DE SOMMET NS1
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    JANVIER 1994
C....................................................................012
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      INTEGER           NOTRIA(6,*),LAPILE(1:MXPILE)
C
C     PARCOURS DES TRIANGLES PAR LES ARETES DE SOMMET NS1
C     REPERAGE DU SOMMET NS1 DANS NT0
      NT1 = NT0
      NTA = NT0
      DO 7 NAR0=1,3
         IF( NOTRIA(NAR0,NT0) .EQ. NS1 ) GOTO 8
 7    CONTINUE
      GOTO 9995
C
C     NS1 RETROUVE : LE TRIANGLE NT0 EST EMPILE
 8    NAR    = NAR0
      LHPILE = 1
      LAPILE(1) = NT0
C
C     RECHERCHE DANS LE SENS DES AIGUILLES D'UNE MONTRE
      NT1 = NOTRIA(3+NAR,NT1)
      IF( NT1 .GT. 0 ) THEN
C
C        LE TRIANGLE VOISIN DE NT1 EXISTE
C        REPERAGE DU SOMMET NS1 DANS NT1
 15      DO 20 NAR=1,3
            IF( NOTRIA(NAR,NT1) .EQ. NS1 ) GOTO 25
 20      CONTINUE
         NTA = NT1
         GOTO 9995
C
C        NT1 EST EMPILE
 25      IF( LHPILE .GE. MXPILE ) GOTO 9990
         LHPILE = LHPILE + 1
         LAPILE(LHPILE) = NT1
C
C        L'ARETE DANS LE SENS INDIRECT
         NTA = NT1
         NT1 = NOTRIA(3+NAR,NT1)
         IF( NT1 .EQ. 0   ) GOTO 30
         IF( NT1 .NE. NT0 ) GOTO 15
C
C        BOUCLE TERMINEE PAR ARRIVEE SUR NT0
         RETURN
      ENDIF
C
C     PAS DE TRIANGLE VOISIN A NT1
C     LE PARCOURS PASSE PAR 1 DES TRIANGLES EXTERIEURS
C     LE PARCOURS EST INVERSE PAR L'ARETE DE GAUCHE
C     LE TRIANGLE NTA EST EMPILE
 30   LHPILE = 1
      LAPILE(LHPILE) = NTA
      DO 32 NAR=1,3
         IF( NOTRIA(NAR,NTA) .EQ. NS1 ) GOTO 33
 32   CONTINUE
 33   IF( NAR .EQ. 1 ) THEN
         NAR = 3
      ELSE
         NAR = NAR - 1
      ENDIF
C     LE TRIANGLE VOISIN DE NTA DANS LE SENS DIRECT
      NT1 = NOTRIA(3+NAR,NTA)
      IF( NT1 .LE. 0 ) THEN
C        UN SEUL TRIANGLE CONTIENT NS1
         GOTO 70
      ENDIF
C
C     REPERAGE DU SOMMET NS1 DANS NT1
 35   DO 50 NAR=1,3
         IF( NOTRIA(NAR,NT1) .EQ. NS1 ) GOTO 60
 50   CONTINUE
      NTA = NT1
      GOTO 9995
C
C     NT1 EST EMPILE
 60   IF( LHPILE .GE. MXPILE ) GOTO 9990
      LHPILE = LHPILE + 1
      LAPILE(LHPILE) = NT1
C
C     L'ARETE DANS LE SENS DIRECT
      IF( NAR .EQ. 1 ) THEN
         NAR = 3
      ELSE
         NAR = NAR - 1
      ENDIF
      NTA = NT1
      NT1 = NOTRIA(3+NAR,NT1)
      IF( NT1 .GT. 0 ) GOTO 35
C
C     BUTEE SUR LE TROU => FIN DES TRIANGLES DE SOMMET NS1
 70   LHPILE = -LHPILE
C     IMPOSSIBLE ICI DE TROUVER LES AUTRES TRIANGLES DE SOMMET NS
      RETURN
C
C     SATURATION DE LA PILE DES TRIANGLES
 9990 WRITE(IMPRIM,*) 'TRC1ST:SATURATION PILE DES TRIANGLES AUTOUR ',
     %'SOMMET ',NS1
      GOTO 9999
C
C     ERREUR
 9995 WRITE(IMPRIM,*) 'TRC1ST: TRIANGLE ',NTA,' ST=',
     %                (NOTRIA(NAR,NTA),NAR=1,3),
     %                ' SANS LE SOMMET ' ,NS1
C
 9999 LHPILE = 0
      RETURN
      END
