      SUBROUTINE TRCF3A( NS1,    NS2,    NS3,
     %                   NOAR1,  NOAR2,  NOAR3,
     %                   MOSOAR, NOSOAR,
     %                   MOARTR, N1ARTR, NOARTR,
     %                   NT )
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUTER DANS LE TABLEAU NOARTR LE TRIANGLE
C -----    DE SOMMETS NS1   NS2   NS3
C          D'ARETES   NOAR1 NOAR2 NOAR3 DEJA EXISTANTES
C                     DANS LE TABLEAU NOSOAR DES ARETES
C
C ENTREES:
C --------
C NS1,  NS2,  NS3   : LE NUMERO DANS PXYD   DES 3 SOMMETS DU TRIANGLE
C NOAR1,NOAR2,NOAR3 : LE NUMERO DANS NOSOAR DES 3 ARETES  DU TRIANGLE
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE ET
C          INDICE DANS NOSOAR DE L'ARETE SUIVANTE DANS LE HACHAGE
C MXSOAR : NOMBRE MAXIMAL D'ARETES STOCKABLES DANS LE TABLEAU NOSOAR
C          ATTENTION: MXSOAR>3*MXSOMM OBLIGATOIRE!
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXARTR : NOMBRE MAXIMAL DE TRIANGLES STOCKABLES DANS LE TABLEAU NOARTR
C
C MODIFIES :
C ----------
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = NOSOAR(1)+NOSOAR(2)*2
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C
C SORTIES:
C --------
C NT     : NUMERO DANS NOARTR DU TRIANGLE AJOUTE
C          =0 SI LE TABLEAU NOARTR EST SATURE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1997
C....................................................................012
      COMMON / UNITES / LECTEU,IMPRIM,NUNITE(30)
      INTEGER           NOSOAR(MOSOAR,*),
     %                  NOARTR(MOARTR,*)
C
C     RECHERCHE D'UN TRIANGLE LIBRE DANS LE TABLEAU NOARTR
      IF( N1ARTR .LE. 0 ) THEN
         WRITE(IMPRIM,*) 'SATURATION DU TABLEAU NOARTR DES ARETES'
         NT = 0
         RETURN
      ENDIF
C
C     LE NUMERO DANS NOARTR DU NOUVEAU TRIANGLE
      NT = N1ARTR
C
C     LE NOUVEAU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
      N1ARTR = NOARTR(2,N1ARTR)
C
C     ARETE 1 DU TRIANGLE NT
C     ======================
C     ORIENTATION DES 3 ARETES DU TRIANGLE POUR QU'IL SOIT DIRECT
      IF( NS1 .EQ. NOSOAR(1,NOAR1) ) THEN
         N =  1
      ELSE
         N = -1
      ENDIF
C     LE NUMERO DE L'ARETE 1 DU TRIANGLE NT
      NOARTR(1,NT) = N * NOAR1
C
C     LE NUMERO DU TRIANGLE NT POUR L'ARETE
      IF( NOSOAR(4,NOAR1) .LE. 0 ) THEN
         N = 4
      ELSE
         N = 5
      ENDIF
      NOSOAR(N,NOAR1) = NT
C
C     ARETE 2 DU TRIANGLE NT
C     ======================
C     ORIENTATION DES 3 ARETES DU TRIANGLE POUR QU'IL SOIT DIRECT
      IF( NS2 .EQ. NOSOAR(1,NOAR2) ) THEN
         N =  1
      ELSE
         N = -1
      ENDIF
C     LE NUMERO DE L'ARETE 2 DU TRIANGLE NT
      NOARTR(2,NT) = N * NOAR2
C
C     LE NUMERO DU TRIANGLE NT POUR L'ARETE
      IF( NOSOAR(4,NOAR2) .LE. 0 ) THEN
         N = 4
      ELSE
         N = 5
      ENDIF
      NOSOAR(N,NOAR2) = NT
C
C     ARETE 3 DU TRIANGLE NT
C     ======================
C     ORIENTATION DES 3 ARETES DU TRIANGLE POUR QU'IL SOIT DIRECT
      IF( NS3 .EQ. NOSOAR(1,NOAR3) ) THEN
         N =  1
      ELSE
         N = -1
      ENDIF
C     LE NUMERO DE L'ARETE 3 DU TRIANGLE NT
      NOARTR(3,NT) = N * NOAR3
C
C     LE NUMERO DU TRIANGLE NT POUR L'ARETE
      IF( NOSOAR(4,NOAR3) .LE. 0 ) THEN
         N = 4
      ELSE
         N = 5
      ENDIF
      NOSOAR(N,NOAR3) = NT
      END
