      SUBROUTINE TRFASEOB( NOMOBJ, NOAXE, VNORMAL, IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACER LES FACES DES EF SECTIONNES PAR UN PLAN D'UN OBJET 3D
C -----    INTERPOLE
C ENTREES:
C --------
C NOMOBJ : NOM DE L'OBJET 3D AVEC INTERPOLATION
C NOAXE  : =1 AXE X
C          =2 AXE Y
C          =3 AXE Z
C          =4 AXE AVEC VNORMAL=NORMALE AU PLAN
C VNORMAL: VECTEUR NORMAL AU PLAN POUR NOAXE=4
C
C SORTIE :
C --------
C IERR   : =0 SI PAS D'ERREUR RENCONTREE, >0 SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Laboratoire JL LIONS UPMC Paris Decembre 2006
C23456...............................................................012
      IMPLICIT          INTEGER (W)
      PARAMETER        (MXTYEL=7)
      include"./incl/langue.inc"
      include"./incl/trvari.inc"
      include"./incl/mecoit.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/a_objet__definition.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___aretefr.inc"
      include"./incl/ponoel.inc"
      include"./incl/xyzext.inc"
C
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      COMMON / MSSFTA / MSSF(28),NTADAM
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (RMCN(1),MCN(1))
      CHARACTER*(*)     NOMOBJ
      CHARACTER*24      KNOMOB
C
      REAL              VNORMAL(3)
      REAL              PTPLAN(3), APTPLAN(3)
      REAL              XYZ0(3), XYZ(3)
      REAL              COPLAN, COPLANMIN, COPLANMAX
      REAL              XYZPLAN(3,4)
C
      IERR    = 0
      MNELEM  = 0
      MXPLS   = 0
      NBSO    = 0
      NBAR    = 0
      NBFA    = 0
      MNNODL  = 0
      MNPLS   = 0
      MXPLS   = 0
C
      MNNSFS = 0
      MNQUEF = 0
      MNXYBS = 0
      MNBARY = 0
      MNNUBA = 0
C
      NBFASE = 0
C
C     L'OBJET EXISTE-T-IL ?
C     =====================
      CALL LXLXOU( NTOBJE, NOMOBJ, NTLXOB, MNLXOB )
      IF( NTLXOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OBJET INCONNU ' // NOMOBJ
         ELSE
            KERR(1) = 'ERROR: UNKNOWN OBJECT ' // NOMOBJ
         ENDIF
         CALL LEREUR
         IERR   = 1
         KNOMOB = NOMOBJ
         GOTO 9999
      ENDIF
C     TRACE DU NOM DE L'OBJET
      CALL RECTEF( NRHIST )
      NBLGRC(NRHIST) = 1
      KHIST(1) = 'OBJET: ' //  NOMOBJ
      CALL LHISTO
C
C     L'OBJET EST IL AVEC OU SANS INTERPOLATION ?
C     ===========================================
C     LE TABLEAU TOPOLOGIE DE L'OBJET
      CALL LXTSOU( NTLXOB, 'TOPOLOGIE', NTTOPO, MNTOPO )
      IF( NTTOPO .LE. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OBJET SANS INTERPOLATION ' // NOMOBJ
         ELSE
            KERR(1) = 'ERROR: OBJECT WITHOUT INTERPOLATION ' // NOMOBJ
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     L'OPTION DE TRACE EST VALABLE EN 3D SEULEMENT
 1    IF( NDIMLI .EQ. 2 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OPTION 3D et OBJET 2D: ' // NOMOBJ
         ELSE
            KERR(1) = 'ERROR: 3D OPTION and 2D OBJECT: ' // NOMOBJ
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     ========================
C     OBJET AVEC INTERPOLATION
C     ========================
C     RECHERCHE DES TABLEAUX SOMMETS NOEUDS POINTS ASSOCIES A L'OBJET
C     ADRESSAGE DES ADRESSES DES TABLEAUX ELEMENTS DE CET OBJET
      MNELEM = 0
      CALL TNMCDC( 'ENTIER', 2*MXTYEL, MNELEM )
      MNTELE = MNELEM + MXTYEL
      CALL NDPGEL( NTLXOB, NTTOPO, MNTOPO,
     %             NTXYZP, MNXYZP, NTXYZN, MNXYZN,
     %             NBTYEL, MCN(MNTELE), MCN(MNELEM), IERR )
C     NTTOPO : NUMERO      DU TMS 'TOPOLOGIE' DE L'OBJET
C     MNTOPO : ADRESSE MCN DU TMS 'TOPOLOGIE' DE L'OBJET
C     NTXYZP : NUMERO      DU TMS 'XYZPOINT'    DE L'OBJET
C     MNXYZP : ADRESSE MCN DU TMS 'XYZPOINT'    DE L'OBJET
C     NTXYZN : NUMERO      DU TMS 'XYZNOEUD'    DE L'OBJET
C     MNXYZN : ADRESSE MCN DU TMS 'XYZNOEUD'    DE L'OBJET
C     NBTYEL : NOMBRE DE TYPES D'ELEMENTS FINIS DU MAILLAGE
C     MNTELE : NUMERO      DU TMS DES NBTYEL TYPES D'ELEMENTS
C     MNELEM : ADRESSE MCN DU TMS DES NBTYEL TYPES D'ELEMENTS
      IF( IERR .NE. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OBJET 3D AVEC INTERPOLATION INCORRECTE: '
     %              // NOMOBJ
         ELSE
            KERR(1) = 'ERROR: 3D OBJECT with INCORRECT INTERPOLATION: '
     %              // NOMOBJ
         ENDIF
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     NDPGST : CODE TRAITEMENT DES XYZ DES SOMMETS POINTS NOEUDS DU MAILLAGE
C              0 : NOEUDS=POINTS=SOMMETS
C              1 : NOEUDS=POINTS#SOMMETS
C              2 : NOEUDS#POINTS=SOMMETS
C              3 : NOEUDS#POINTS#SOMMETS
      NDPGST = MCN( MNTOPO + WDPGST )
C
C     NDIM DIMENSION EFFECTIVE DE L'ESPACE DES COORDONNEES
      NBCOOR = MCN( MNXYZP+WBCOOP )
C
C     LES COORDONNEES EXTREMES SONT CELLES DE CET OBJET
      NBPOMA = MCN(MNXYZP+WNBPOI)
      CALL MIMXPT( NBCOOR, NBPOMA, RMCN(MNXYZP+WYZPOI), COOEXT )
C     CADRE AVEC 20% EN PLUS
      DO 30 I=1,NBCOOR
         EC = ( COOEXT(I,2) - COOEXT(I,1) ) * 1.2 / 2
         CM = ( COOEXT(I,1) + COOEXT(I,2) ) / 2
         COOEXT(I,1) = CM - EC
         COOEXT(I,2) = CM + EC
 30   CONTINUE
C
      IF( NBCOOR .EQ. 6 ) THEN
C
C        TRACE DES 192 ARETES DES 6-CUBES DE L'OBJET 6D AVEC INTERPOLATION
C        =================================================================
C        LA DIRECTION DE VISEE EN 6D
         AXOLAR = 0
         DO 35 N=1,6
            AXOPTV(N) = ( COOEXT(N,1) + COOEXT(N,2) ) * 0.5
            S = COOEXT(N,2) - COOEXT(N,1)
            AXOLAR = MAX( AXOLAR, S )
            AXOEIL(N) = AXOPTV(N) + S
 35      CONTINUE
         AXOLAR = AXOLAR / 1.5
         AXOHAU = AXOLAR * 0.75
C
C        CONSTRUCTION DE LA MATRICE D'AXONOMETRIE 6D
         CALL MATAXO6
C
C        DEFINITION DE LA FENETRE EN LARGEUR ET HAUTEUR
         CALL ISOFENETRE( -AXOLAR, AXOLAR, -AXOHAU, AXOHAU )
C
C        TRACE FINAL DANS R3
         NDIM   = 3
         NDIMLI = NDIM
C
C        TRACE DES ARETES DES 6-CUBES EN PROJECTION XYZ (OUBLI DE UVW)
C        INITIALISATION DE L'ORBITE ZOOM DEPLACEMENT
         CALL ORBITE0( NOTYEV )
         GOTO 55
C
C        ORBITE OU ZOOM OU TRANSLATION ACTIFS
 53      CALL ORBITE1( NOTYEV )
         IF( NOTYEV .EQ. 0 ) GOTO 9000
C
C        TRACE DES 192 ARETES DES 6-CUBES
 55      CALL T3AR6C( NOMOBJ )
C        TRACE DES AXES DU CUBE ENGLOBANT
         CALL TRAXE3
C        TRACE DU TITRE ET FERMETURE
         CALL TRFINS( NOMOBJ )
C
C        REPRISE DE L'ORBITE
         IF( LORBITE .NE. 0 ) GOTO 53
C        SORTIE DU TRACE
         NOTYVI = 0
         GOTO 9000
C
      ENDIF
C
C     OBJET 3D AVEC POINTS A 3 COORDONNEES DANS XYZPOINT
      CALL DIMCOO( NBPOMA, MCN(MNXYZP+WYZPOI), NDIM )
      NDIMLI = NDIM
      IF( NDIM .LE. 2 ) GOTO 1
C
C     TRACE DE L'OBJET 3D AVEC INTERPOLATION
C     ======================================
C
C     LES ARETES FRONTALIERES DES VOLUMES DE L'OBJET INTERPOLE
C     --------------------------------------------------------
C     CREATION OU REDECOUVERTE DU TMS OBJET>>>FACE
      CALL HACHOB( NOMOBJ, 4, NTFAOB, MNFAOB, IERR )
      IF( IERR .GT. 0 .OR. NTFAOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 2
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR TRFASEOB: OBJET ' // NOMOBJ
            KERR(2) = 'CALCUL IMPOSSIBLE DE SES FACES'
         ELSE
            KERR(1) = 'ERROR TRFASEOB: OBJECT ' // NOMOBJ
            KERR(2) = 'FACES NOT COMPUTABLE'
         ENDIF
         CALL LEREUR
         GOTO 99999
      ENDIF
C
C     CREATION DU HACHAGE DES ARETES DES FACES FRONTALIERES DE L'OBJET
      CALL HACHAF( NOMOBJ, 0, NTFAOB, MNFAOB, NTAFOB, MNAFOB, I )
C
C     LE NOMBRE D'ENTIERS PAR ARETE FRONTALIERE
      MOARFR = MCN( MNAFOB + WOARFR )
C     LA MAJORATION DU NOMBRE DES ARETES FRONTALIERES
      MXARFR = MCN( MNAFOB + WXARFR )
C     LE NUMERO DANS LAREFR DE LA PREMIERE ARETE FRONTALIERE
      L1ARFR = MCN( MNAFOB + W1ARFR )
C     LE NOMBRE D'ARETES FRONTALIERES DANS LE CHAINAGE
      NBARFR = MCN( MNAFOB + WBARFR )
C
C     BOUCLE SUR LES DIFFERENTS TYPES D'ELEMENTS FINIS DU MAILLAGE
C     POUR CALCULER LE NOMBRE DE FACES, ARETES, SOMMETS APPARTENANT A
C     DES SURFACES, LIGNES ET POINTS NOMMES PAR L'UTILISATEUR
C     ===============================================================
      NBEF = 0
      NBFA = 0
      NBAR = 0
      NBSO = 0
C
      DO 110 I = 0, NBTYEL-1
C
C        L'ADRESSE MCN DU DEBUT DU TABLEAU NPEF DE CE TYPE D'EF
         MNELE = MCN( MNELEM + I )
C
C        NOMBRE D'EF DE CE TYPE
         NBEF = NBEF + MCN( MNELE + WBELEM )
C
C        LES SOMMETS IDENTIQUES A DES POINTS UTILISATEUR
         NBSO = NBSO + MCN( MNELE + WBPSEL )
C
C        LES ARETES APPARTENANT A UNE LIGNE
         NBAR = NBAR + MCN( MNELE + WBLAEL )
C
C        LES FACES APPARTENANT A UNE SURFACE
         NBFA = NBFA + MCN( MNELE + WBSFEL )
C
 110  CONTINUE
C
C     CREATION DU TABLEAU DES NUMEROS DANS XYZPOINT DES SOMMETS
C     DES FACES ARETES SOMMETS APPARTENANT A UNE SURFACE LIGNE POINT
C     --------------------------------------------------------------
      MNFASU = 0
      IF( NBFA .GT. 0 ) THEN
         CALL TNMCDC( 'ENTIER', 5*NBFA, MNFASU )
      ENDIF
      MNF = MNFASU - 1
C
      MNARLI = 0
      IF( NBAR .GT. 0 ) THEN
         CALL TNMCDC( 'ENTIER', 3*NBAR, MNARLI )
      ENDIF
      MNA = MNARLI - 1
C
      MNSOPO = 0
      IF( NBSO .GT. 0 ) THEN
         CALL TNMCDC( 'ENTIER', 2*NBSO, MNSOPO )
      ENDIF
      MNS = MNSOPO - 1
C
C     LE TABLEAU DU NUMERO DES DEGRES DE LIBERTE D'UN ELEMENT FINI
      NBDLMX = 64
      CALL TNMCDC( 'ENTIER', NBDLMX, MNNODL )
C
C     INITIALISATION DE CES 3 TABLEAUX
      DO 150 I = 0, NBTYEL-1
C
C        L'ADRESSE MCN DU DEBUT DU TABLEAU NPEF DE CE TYPE D'EF
         MNELE = MCN( MNELEM + I )
C
C        LE NUMERO DU TYPE DES ELEMENTS FINIS
         NUTYEL = MCN( MNELE + WUTYEL )
C
C        LE NOMBRE DE TELS ELEMENTS
         NBELEM = MCN( MNELE + WBELEM )
C
C        LES CARACTERISTIQUES DE L'ELEMENT FINI
         CALL ELTYCA( NUTYEL )
C
C        NBNSOM = Nombre de sommets d'un EF
C
C        L'ADRESSE MCN DU TABLEAU 'NPEF' POUR CE TYPE D'EF
C        Nombre de noeuds d'un EF
         NBNDEL = MCN( MNELE + WBNDEL )
C        Nombre de points d'un EF (0 si points=noeuds)
         NBPGEL = MCN( MNELE + WBPGEL )
C        L'ADRESSE DE NUNDEL
         MNNGEL = MNELE + WUNDEL
C        L'ADRESSE DE NUPGEL
         MNPGEL = MNNGEL
         IF( NDPGST .LT. 2 ) THEN
C           NOEUDS=POINTS
            NBPGEL = NBNDEL
         ELSE
C           NOEUDS#POINTS
            NBPGEL = MCN( MNELE + WBPGEL )
            MNPGEL = MNPGEL + NBELEM * NBNDEL
         ENDIF
C
C        ATTENTION : RECUL D'UN MOT POUR EVITER LA SOUSTRACTION
C        DANS LES BOUCLES
         MNPGEL = MNPGEL - 1
C
C        LES SOMMETS = POINTS UTILISATEUR
         NBPSEL = MCN( MNELE + WBPSEL )
         MOPSEL = MCN( MNELE + WOPSEL )
C        ADRESSE JUSTE AVANT LE TABLEAU NLPSEL
         MNPSEL = MNPGEL + NBELEM * NBPGEL + NBPSEL
         DO 120 J = 1,NBPSEL
C           LE NUMERO DU POINT
            MCN( MNS + 2 ) = MCN( MNPSEL - NBPSEL + J )
C           LE NUMERO LOCAL DU SOMMET DANS L'EF
            N   = MCN( MNPSEL + J )
C           LE NUMERO DE L'EF DE CE SOMMET
            NEF = MCN( MNPSEL + MOPSEL + J )
C           LE NUMERO XYZPOI DE CE SOMMET
            NS  = MCN( MNPGEL + NEF + NBELEM * ( N - 1 ) )
C           CE NUMERO EST STOCKE DANS LE TABLEAU DES SOMMETS=POINTS
            MCN( MNS + 1 ) = NS
            MNS = MNS + 2
 120     CONTINUE
C
C        LES ARETES APPARTENANT A UNE LIGNE
         NBLAEL = MCN( MNELE + WBLAEL )
         MOLAEL = MCN( MNELE + WOLAEL )
C        ADRESSE JUSTE AVANT LE TABLEAU NLLAEL
         MNLAEL = MNPSEL + MOPSEL + MOPSEL + NBLAEL
         DO 130 J = 1,NBLAEL
C           LE NUMERO DE LA LIGNE
            MCN( MNA + 3 ) = MCN( MNLAEL - NBLAEL + J )
C           LE NUMERO LOCAL DE L'ARETE DANS L'EF
            N   = MCN( MNLAEL + J )
C           LE NUMERO DE L'EF DE CETTE ARETE
            NEF = MCN( MNLAEL + MOLAEL + J )
C           LE NUMERO XYZPOI DE SES 2 SOMMETS
            DO 125 K=1,2
C              LE NUMERO LOCAL DU SOMMET DANS L'EF
               NS = NOSOAR( K, N )
               NS = MCN( MNPGEL + NEF + NBELEM * ( NS - 1 ) )
C              CE NUMERO EST STOCKE DANS LE TABLEAU DES SOMMETS=POINTS
               MCN( MNA + K ) = NS
 125        CONTINUE
            MNA = MNA + 3
 130     CONTINUE
C
C        LES FACES APPARTENANT A UNE SURFACE
         NBSFEL = MCN( MNELE + WBSFEL )
         MOSFEL = MCN( MNELE + WOSFEL )
C        ADRESSE JUSTE AVANT LE TABLEAU NLSFEL
         MNSFEL = MNLAEL + MOLAEL + MOLAEL + NBSFEL
         DO 140 J = 1,NBSFEL
C           LE NUMERO DE LA SURFACE
            MCN( MNF + 5 ) = MCN( MNSFEL - NBSFEL + J )
C           LE NUMERO LOCAL DE LA FACE DANS L'EF
            N   = MCN( MNSFEL + J )
C           LE NUMERO DE L'EF DE CETTE FACE
            NEF = MCN( MNSFEL + MOSFEL + J )
C           LE NOMBRE DE SOMMETS DE CETTE FACE
            NBSTFA = NBSOFA(N)
C           TEMOIN DE TRIANGLE, ECRASE SI CETTE FACE A 4 SOMMETS
            MCN( MNF + 4 ) = 0
C           LE NUMERO XYZPOI DE SES NBSTFA SOMMETS
            DO 135 K=1,NBSTFA
C              LE NUMERO LOCAL DU SOMMET DANS L'EF
               NSL = NOSOFA( K, N )
C              LE NUMERO XYZPOI DE CE SOMMET
               MMM = MNPGEL + NEF + NBELEM * ( NSL - 1 )
               NS = MCN( MMM )
C              CE NUMERO EST STOCKE DANS LE TABLEAU DES SOMMETS=POINTS
               MCN( MNF + K ) = NS
 135        CONTINUE
            MNF = MNF + 5
 140     CONTINUE
 150  CONTINUE
C
C     LES FACES DES EF SECTIONNES PAR LE PLAN
      MXFASE = NBEF * 4 + 1024
      CALL TNMCDC( 'ENTIER', 4*MXFASE, MNNSFS )
      CALL TNMCDC( 'REEL',     MXFASE, MNQUEF )
      CALL TNMCDC( 'REEL',   3*MXFASE, MNXYBS )
C
C     LE TABLEAU DES Z AXONOMETRIQUES DES BARYCENTRES DES
C     FACES ARETES ET SOMMETS
      NBBARY = NBFA + NBAR + NBSO + NBARFR
      MXBARY = NBBARY + MXFASE + 64
      CALL TNMCDC( 'REEL',   MXBARY, MNBARY )
      CALL TNMCDC( 'ENTIER', MXBARY, MNNUBA )
C
C     COULEUR ET EPAISSEUR DES ARETES DES FACES
      CALL XVCOULEUR( NCOUAF )
      CALL XVEPAISSEUR( NEPARF )
C
C     DEFINITION DE LA VISEE AXONOMETRIQUE POUR DEFINIR LE PLAN DE SECTION
C     --------------------------------------------------------------------
C     POINT VU LE CENTRE DE L'HEXAEDRE ENGLOBANT
      AXOPTV(1) = ( COOEXT(1,1) + COOEXT(1,2) ) * 0.5
      AXOPTV(2) = ( COOEXT(2,1) + COOEXT(2,2) ) * 0.5
      AXOPTV(3) = ( COOEXT(3,1) + COOEXT(3,2) ) * 0.5
C     POSITION DE L'OEIL
      AXOEIL(1) = AXOPTV(1) + 4.0 * ( COOEXT(1,2) - COOEXT(1,1) )
      AXOEIL(2) = AXOPTV(2) + 3.0 * ( COOEXT(2,2) - COOEXT(2,1) )
      AXOEIL(3) = AXOPTV(3) + 3.5 * ( COOEXT(3,2) - COOEXT(3,1) )
C     LARGEUR/2 et HAUTEUR/2 de la FENETRE
      AXOLAR = (COOEXT(1,2)-COOEXT(1,1) + COOEXT(2,2)-COOEXT(2,1))*0.45
      AXOHAU = ( COOEXT(3,2) - COOEXT(3,1) ) * 0.85
C     PAS DE PLAN ARRIERE ET AVANT
      AXOARR = 0
      AXOAVA = 0
      CALL AXONOMETRIE( AXOPTV, AXOEIL, AXOLAR, AXOHAU, AXOARR, AXOAVA )
C
C     INITIALISATION DE L'ORBITE ZOOM DEPLACEMENT
C     -------------------------------------------
C     LE BARYCENTRE DE L'HEXAEDRE ENGLOBANT SERT DE POINT DE DEPART
C     DU PLAN DE SECTION
      PTPLAN(1) = AXOPTV(1)
      PTPLAN(2) = AXOPTV(2)
      PTPLAN(3) = AXOPTV(3)
C
C     LES COORDONNEES AXONOMETRIQUES DU POINT DU PLAN
      CALL XYZAXO( PTPLAN, APTPLAN )
C
      IF ( NOAXE .LE. 3 ) THEN
C        COORDONNEE SELON L'AXE NOAXE
         COPLANMIN = COOEXT(NOAXE,1)
         COPLANMAX = COOEXT(NOAXE,2)
      ELSE
C        LA COORDONNEE SELON LA DIRECTION NORMALE
         COPLAN0   = PROSCR( PTPLAN,      VNORMAL, 3 )
         COPLANMIN = PROSCR( COOEXT(1,1), VNORMAL, 3 )
         COPLANMAX = PROSCR( COOEXT(1,2), VNORMAL, 3 )
      ENDIF
      IF( COPLANMIN .GT. COPLANMAX ) THEN
         C         = COPLANMIN
         COPLANMIN = COPLANMAX
         COPLANMAX = C
      ENDIF
C
C     ECART MAXIMAL MIN-MAX = DIAGONALE DE L'HEXAEDRE
      ECMX = SQRT( (COOEXT(1,2)-COOEXT(1,1))**2 +
     %             (COOEXT(2,2)-COOEXT(2,1))**2 +
     %             (COOEXT(3,2)-COOEXT(3,1))**2 )
      CALL ORBITE0( NOTYEV )
      IF( NOTYEV .EQ. 0 ) GOTO 9000
C
      NOPX0 = LAPXFE / 2
      NOPY0 = LHPXFE / 2
C     LE POINTEUR DE LA SOURIS EST CENTRE DANS LA FENETRE
      CALL DEPLSOURIS( NOPX0, NOPY0 )
C
C     MISE A JOUR DU TRACE 3D AVEC TRANSLATION ORBITE TRANSLATION
C     -----------------------------------------------------------
 200  CALL ORBITE2( NOTYEV )
      IF( NOTYEV .EQ.  0 ) GOTO 9000
      IF( NOTYEV .EQ. -3 ) THEN
C
C        DEPLACEMENT EN COORDONNEE AXONOMETRIQUE
C        PAR RAPPORT A CELUI EN PIXELS
         APTPLAN(1) = APTPLAN(1) + ECMX*2 * FLOAT( NOPX1 - NOPX0 )
     %                           / FLOAT(LAPXFE)
         APTPLAN(2) = APTPLAN(2) + ECMX*2 * FLOAT( NOPY0 - NOPY1 )
     %                           / FLOAT(LHPXFE)
C        PASSAGE AUX COORDONNEES CARTESIENNES
         CALL AXOXYZ( APTPLAN, PTPLAN )
C
C        SELON NOAXE CALCUL DE COPLAN SELON LA NORMALE AU PLAN
C        ET DES 4 SOMMETS DU CARRE DE VISUALISATION DU PLAN
         CALL SCTPLN( NOAXE,  VNORMAL,
     %                PTPLAN, COPLAN0, COPLANMIN, COPLANMAX,
     %                COPLAN, XYZPLAN )
C
C        MISE A JOUR DU PIXEL INITIAL
         NOPX0 = NOPX1
         NOPY0 = NOPY1
      ENDIF
C
C     FORMATION TABLEAUX Z-AXONOMETRIQUES ET NUMERO DES BARYCENTRES AVANT TRI
C     -----------------------------------------------------------------------
      CALL TBAFAS( NBCOOR, NBPOMA, RMCN(MNXYZP+WYZPOI),
     %             NBSO,   MCN(MNSOPO),
     %             NBAR,   MCN(MNARLI),
     %             NBFA,   MCN(MNFASU),
     %             MOARFR, MXARFR, L1ARFR, MCN(MNAFOB+WAREFR),
     %             NBBARY, MCN(MNNUBA), RMCN(MNBARY),
     %             NUMXPO, NUMXLI, NUMXSU )
C
C     LISTE DES NO DES SOMMETS DES FACES DES EF 3D SECTIONNES PAR
C     LE PLAN DE COORDONNEE COPLAN DANS LA DIRECTION DE LA NORMALE AU PLAN
C     --------------------------------------------------------------------
      CALL TRFASEOB1( NOAXE,  VNORMAL, COPLAN,
     %                NBPOMA, RMCN(MNXYZP+WYZPOI),
     %                NBTYEL, MNELEM, MCN(MNNODL),
     %                MXFASE, NBFASE, MCN(MNNSFS), MCN(MNQUEF),
     %                RMCN(MNXYBS) )
C
C     LES FACES DES EF SECTIONNES SONT AJOUTEES POUR LE TRI DU PEINTRE
      MNBA = MNXYBS
      DO 310 NF = 0, NBFASE-1
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( RMCN(MNBA), XYZ )
         RMCN(MNBARY+NBBARY+NF) = XYZ(3)
C        NO NEGATIF POUR SAVOIR QUE C'EST UNE FACE DE SECTION
         MCN(MNNUBA+NBBARY+NF) = -(1+NF)
         MNBA = MNBA + 3
 310  CONTINUE
C
C     LES 4 ARETES DU RECTANGLE DU PLAN DE SECTION
      NBFACT = NBBARY + NBFASE
      NF0 = 4
      DO 320 NF = 1, 4
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         XYZ0(1) = (XYZPLAN(1,NF0) + XYZPLAN(1,NF)) * 0.5
         XYZ0(2) = (XYZPLAN(2,NF0) + XYZPLAN(2,NF)) * 0.5
         XYZ0(3) = (XYZPLAN(3,NF0) + XYZPLAN(3,NF)) * 0.5
         CALL XYZAXO( XYZ0, XYZ )
         RMCN(MNBARY+NBFACT+NF-1) = XYZ(3)
C        NO>NBFACT POUR SAVOIR QUE C'EST UNE ARETE DU RECTANGLE DU PLAN
         MCN(MNNUBA+NBFACT+NF-1) = -(NBFASE + NF)
         NF0 = NF
 320  CONTINUE
C
C     NOMBRE TOTAL DE TRACES A TRIER
      NBFACT = NBFACT + 4
C
C     LE TRI PAR TAS DE CETTE COTE AXONOMETRIQUE
      CALL TRITRP( NBFACT, RMCN(MNBARY), MCN(MNNUBA) )
C
C     LA MEMOIRE PIXELS EST EFFACEE
      CALL EFFACEMEMPX
C
C     TRACE DES AXES
      CALL TRAXE3
C
C     TRACE EFFECTIF DES ARETES FRONTALIERES SURFACES LIGNES POINTS
C     ET FACES DES EF SECTIONNES PAR LE PLAN
C     -------------------------------------------------------------
      MXPLS = NUMXPO + NUMXLI + NUMXSU
      IF( MXPLS .GT. 0 ) THEN
         MNPLS = 0
         CALL TNMCDC( 'ENTIER', MXPLS, MNPLS )
         CALL AZEROI( MXPLS, MCN(MNPLS) )
      ELSE
C        ADRESSE BIDON NON UTILISEE ENSUITE
         MNPLS = MNNUBA
      ENDIF
      CALL TRFASEOB2( NBCOOR, NBPOMA, RMCN(MNXYZP+WYZPOI),
     %                NBSO,   MCN(MNSOPO),
     %                NBAR,   MCN(MNARLI),
     %                NBFA,   MCN(MNFASU),
     %                MOARFR, MXARFR, MCN(MNAFOB+WAREFR),
     %                MCN(MNNUBA), RMCN(MNBARY),
     %                NUMXPO, NUMXLI, NUMXSU, MCN(MNPLS),
     %                NBFASE, MCN(MNNSFS), MCN(MNQUEF),
     %                NBFACT, XYZPLAN )
C
C     TRACE DU TITRE ET FERMETURE
      CALL TRFINS( NOMOBJ )
C
C     REPRISE DE L'ORBITE
      GOTO 200
C
C     DESTRUCTION DES TABLEAUX DEVENUS INUTILES
 9000 IF( MXPLS  .GT. 0 ) CALL TNMCDS( 'ENTIER',   MXPLS,  MNPLS  )
      IF( NBSO   .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*NBSO,   MNSOPO )
      IF( NBAR   .GT. 0 ) CALL TNMCDS( 'ENTIER', 3*NBAR,   MNARLI )
      IF( NBFA   .GT. 0 ) CALL TNMCDS( 'ENTIER', 5*NBFA,   MNFASU )
      IF( MNELEM .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXTYEL, MNELEM )
      IF( MNNSFS .GT. 0 ) CALL TNMCDS( 'ENTIER', 4*MXFASE, MNNSFS )
      IF( MNQUEF .GT. 0 ) CALL TNMCDS( 'REEL',     MXFASE, MNQUEF )
      IF( MNXYBS .GT. 0 ) CALL TNMCDS( 'REEL',   3*MXFASE, MNXYBS )
      IF( MNBARY .GT. 0 ) CALL TNMCDS( 'REEL',     MXBARY, MNBARY )
      IF( MNNUBA .GT. 0 ) CALL TNMCDS( 'ENTIER',   MXBARY, MNNUBA )
      IF( MNNODL .GT. 0 ) CALL TNMCDS( 'ENTIER',   NBDLMX, MNNODL )
      GOTO 99999
C
C     OBJET INCONNU => ERREUR AVEC LISTE DES OBJETS ACTUELS
C     =====================================================
 9999 NBLGRC(NRERR) = 2
      IF( LANGAG .EQ. 0 ) THEN
         KERR(1) = 'OBJET INCONNU:' // KNOMOB
         KERR(2) = 'A choisir parmi :'
         WRITE(IMPRIM,19999) 'OBJET',KNOMOB
      ELSE
         KERR(1) = 'UNKNOWN OBJECT:' // KNOMOB
         KERR(2) = 'CHOOSE an OBJECT AMONG:'
         WRITE(IMPRIM,29999) 'OBJECT',KNOMOB
      ENDIF
      CALL LEREUR
19999 FORMAT(1X,A,1X,A,' NON RETROUVE PARMI')
29999 FORMAT(1X,A,1X,A,' NOT FOUND AMONG')
C     OUVERTURE DES OBJETS
      CALL LXLXOU( NTADAM, 'OBJET', NTOBJE, MNOBJE )
      CALL LXIM0( MNOBJE )
C
99999 RETURN
      END
