      SUBROUTINE TRFPTEST( KTITRE, PTXYZD, NOSOM1, NOSOM2,
     %                     NBFAPE, NOFAPE, MXFACO, LEFACO,
     %                     MXTE1S, NOTE1S, NOTETR, N1TETS  )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRACE DES ARETES DES FACES FRONTIERE et INTERFACE
C -----    DU TABLEAU LEFACO avec LES FACES PERDUES et
C          DES ARETES DES TETRAEDRES D'AU MOINS UN SOMMET
C          DES SOMMETS DES FACES PERDUES

C ENTREES:
C --------
C KTITRE : TITRE DU TRACE
C PTXYZD : PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE
C NOSOM1 : NUMERO PTXYZD DU PREMIER SOMMET A TRACER
C NOSOM2 : NUMERO PTXYZD DU DERNIER SOMMET A TRACER

C NBFAPE : NOMBRE DE FACES PERDUES DE LEFACO
C NOFAPE : NUMERO DES NBFAPE FACES PERDUES
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C          LEFACO(11,.) = NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE, 0 SINON

C MXTE1S : NOMBRE D'ENTIERS DU TABLEAU NOTE1S
C NOTE1S : NOTE1S(I) >0 NUMERO NOTETR DES TETRAEDRES DE SOMMET DES FACES PERDUES
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE DE NUMEROTATION
C          1: 123      2: 234      3: 341      4: 412
C N1TETS : N1TETS(I) NUMERO D'UN TETRAEDRE AYANT POUR SOMMET I
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Saint Pierre du Perray           Janvier 2020
C2345X7..............................................................012
      include"./incl/trvari.inc"
      include"./incl/mecoit.inc"
      include"./incl/xyzext.inc"

      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE
C     STOPTE = FAUX ==> PAS D'ARRET APRES LE TRACE DE CHAQUE TETRAEDRE
C              VRAI ==> DEMANDE D'UN CARACTERE POUR REDEMARRER
C     TRACTE = FAUX ==> PAS DE TRACE DES TETRAEDRES
C              VRAI ==> TRACE DES TETRAEDRES DE L'ETOILE
C
      DOUBLE PRECISION  PTXYZD(4,*)
      INTEGER           LEFACO(1:11,0:MXFACO), NOFAPE(NBFAPE),
     %                  NOTE1S( MXTE1S ), NOTETR(8,*), N1TETS(*)
      REAL              XYZ(3)
      CHARACTER*(*)     KTITRE

      IF( .NOT. TRACTE ) RETURN

C     MINIMUM ET MAXIMUM DES COORDONNEES DES FACES PERDUES
C     ====================================================
      R = RINFO( 'GRAND' )
      DO L=1,3
         COOEXT(L,1) =  R
         COOEXT(L,2) = -R
      ENDDO

      DO NS = NOSOM1, NOSOM2
         DO L=1,3
            R = REAL( PTXYZD(L,NS) )
            IF( R .LT. COOEXT(L,1) )  COOEXT(L,1)=R
            IF( R .GT. COOEXT(L,2) )  COOEXT(L,2)=R
         ENDDO
      ENDDO

C     LISTAGE DES TETRAEDRES AVEC UN SOMMET DES FACES PERDUES
      NBTE1ST = 0
      DO 3 N = 1, MIN( 32, NBFAPE )
         NFL = ABS( NOFAPE( N ) )
         IF( LEFACO(1,NFL) .EQ. 0 ) GOTO 3
         DO K=1,3
            NS = LEFACO(K,NFL)
            CALL TETR1S( NS,   N1TETS, NOTETR,
     %                 NBTE1S, MXTE1S-NBTE1ST, NOTE1S(NBTE1ST+1), IERR )
            IF( IERR .NE. 0 ) THEN
               GOTO 5
            ENDIF
            NBTE1ST = NBTE1ST + NBTE1S
         ENDDO
 3    ENDDO

C     COMPRESSION DES NUMEROS DE TETRAEDRES AVEC UN SOMMET de FACE PERDUE
 5    CALL UNITABL( NOTE1S, NBTE1ST )

C     HEXAEDRE ENGLOBANT CES NBTE1ST TETRAEDRES
      DO N = 1, NBTE1ST
         NTE = NOTE1S( N )
         DO K=1,4
            NS = NOTETR( K, NTE )
            DO L=1,3
               R = REAL( PTXYZD(L,NS) )
               IF( R .LT. COOEXT(L,1) )  COOEXT(L,1)=R
               IF( R .GT. COOEXT(L,2) )  COOEXT(L,2)=R
            ENDDO
         ENDDO
      ENDDO

      DO N = 1, MXFACO
         IF( LEFACO(1,N) .GT. 0 ) THEN
            DO K=1,3
               NS = LEFACO(K,N)
               DO L=1,3
                  R = REAL( PTXYZD(L,NS) )
                  IF( R .LT. COOEXT(L,1) )  COOEXT(L,1)=R
                  IF( R .GT. COOEXT(L,2) )  COOEXT(L,2)=R
               ENDDO
            ENDDO
         ENDIF
      ENDDO

      CALL VISEE0

      CALL EFFACEMEMPX

C     TRACE EN MODE 3 BOUTONS POUR DEPLACEMENT ROTATIONS ZOOM
      NORBITE = 0
      LORBITE = 1
C     TRACE EN MODE 3 BOUTONS POUR DEPLACEMENT ROTATIONS ZOOM
      PREDU0  = PREDUF
      PREDUF  = 0.0

      IF( LORBITE .EQ. 0 ) GOTO 20

C     INITIALISATION DE L'ORBITE
C     ==========================
      CALL ORBITE0( NOTYEV )
      GOTO 20

C     TRACE SELON L'ORBITE OU ZOOM OU TRANSLATION ACTIFS
C     ==================================================
 10   CALL ORBITE1( NOTYEV )
      IF( NOTYEV .EQ. 0 ) GOTO 9000
C
C     TRACE DES AXES 3D
 20   CALL TRAXE3

C     LE TRACE DES 6 ARETES DES TETRAEDRES AVEC UN SOMMET DE FACE PERDUE
      DO N = 1, NBTE1ST
         NTE = NOTE1S( N )
         CALL TRTETRA( NCORAN, NOTETR(1,NTE), PTXYZD )
      ENDDO

C     LE TRACE DES 3 ARETES DES FACES TRIANGULAIRES DU TABLEAU LEFACO
      DO NF=1,MXFACO
         IF( LEFACO(1,NF) .GT. 0 ) THEN
            CALL TRARTR( NCNOIR, LEFACO(1,NF), PTXYZD )
         ENDIF
      ENDDO

C     LE TRACE DES FACES TRIANGULAIRES PERDUES DU TABLEAU LEFACO
      DO N=1, NBFAPE

         NF = ABS( NOFAPE(N) )
         CALL TRFATR( NCROUG, NCBLEU, LEFACO(1,NF), PTXYZD )

C        TRACE DU NUMERO DES 3 SOMMETS DE LA FACE NF
         DO K=1,3
            NS = LEFACO(K,NF)
            XYZ(1) = REAL( PTXYZD(1,NS) )
            XYZ(2) = REAL( PTXYZD(2,NS) )
            XYZ(3) = REAL( PTXYZD(3,NS) )
            CALL ENTIER3D( NCGRIS, XYZ, NS )
         ENDDO

      ENDDO

C     LE TRACE DES SOMMETS NOSOM1 A NOSOM2 DE PTXYZD
      DO NS = NOSOM1, NOSOM2
         XYZ(1) = REAL( PTXYZD(1,NS) )
         XYZ(2) = REAL( PTXYZD(2,NS) )
         XYZ(3) = REAL( PTXYZD(3,NS) )
         CALL SYMBOLE3D( NCTURQ, XYZ, '*' )
         CALL ENTIER3D(  NCVERT, XYZ, NS )
      ENDDO

C     TRACE EFFECTIF
      CALL TRFINS( KTITRE )

C     REPRISE DE L'ORBITE
C     ===================
      IF( LORBITE .NE. 0 ) GOTO 10

C     REDUCTION DES FACES REMISE A SA VALEUR PRECEDENTE
 9000 PREDUF = PREDU0

      RETURN
      END
