      SUBROUTINE TRIEDR( XYZ1 , XYZ2 , XYZ3 , AXES , IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCUL DES COEFFICIENTS DIRECTEURS DES AXES DU TRIEDRE
C ----     DEFINIS PAR 3 POINTS DE R**3
C
C ENTREES :
C ---------
C XYZ1   : 3 COORDONNEES DU POINT ORIGINE DU TRIEDRE
C XYZ2   : 3 COORDONNEES DU POINT EXTREMITE DU 1-ER AXE
C XYZ3   : 3 COORDONNEES DU POINT DEFINISSANT LE PLAN AVEC LE 1-ER AXE
C
C SORTIES :
C ---------
C AXES   : LES 3 COMPOSANTES DES 3 AXES
C IERR   : 0 SI PAS D'ERREUR, >0 SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE PARIS UPMC    DECEMBRE 1989
C23456...............................................................012
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      REAL              XYZ1(3),XYZ2(3),XYZ3(3),COEPLA(4),XYZ(3,3)
      DOUBLE PRECISION  DCOOR(3,3),AXES(3,3)
C
C     LES 3 POINTS SONT ILS ALIGNES ?
      DO 10 I=1,3
         XYZ(I,1) = XYZ1(I)
         XYZ(I,2) = XYZ2(I)
         XYZ(I,3) = XYZ3(I)
 10   CONTINUE
      CALL EQPLAN( XYZ , COEPLA , IERR )
      IF( IERR .GT. 0 ) THEN
         NBLGRC(NRERR) = 1
         KERR(1) =  'TRIEDRE DEFINI AVEC 3 POINTS ALIGNES'
         CALL LEREUR
         WRITE(IMPRIM,10010) XYZ1
         WRITE(IMPRIM,10010) XYZ2
         WRITE(IMPRIM,10010) XYZ3
10010    FORMAT(3G16.7)
         RETURN
      ENDIF
C
C     FORMATION DU TRIEDRE D'ORIGINE XYZ1
C     DE PREMIER AXE XYZ1-XYZ2
C     DE PLAN XYZ1 XYZ2 XYZ3 ET 3-EME AXE  XXYZ2-YZ1 VECTORIEL XYZ3-XYZ1
C     DE 2-EME AXE  ; 3-EME AXE VECTORIEL XYZ2-XYZ1
      DO 30 I=1,3
         DO 20 J=1,3
            DCOOR(J,I) = XYZ(J,I)
 20      CONTINUE
 30   CONTINUE
      CALL P3AXE3( DCOOR, AXES, IERR )
      END
