      SUBROUTINE TRIFAFR( MOFACE , MXFACE , LFACES , XYZSOM ,
     %                    L1FAFR , NBFAFR , NOFAFR , DIFAFR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRIER LES FACES FRONTALIERES SELON LEUR DISTANCE A L'OEIL
C -----
C ENTREES:
C --------
C MOFACE : NOMBRE DE MOTS PAR FACE DU TABLEAU NFACE DES FACES
C MXFACE : NOMBRE DE FACES DU TABLEAU NFACE
C LFACES : TABLEAU NUMERO DES FACES, LIEN, NO DES CUBES
C          LFACES(1,I)= NO DU 1-ER  SOMMET DE LA FACE
C          LFACES(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LFACES(3,I)= NO DU 3-EME SOMMET DE LA FACE
C          LFACES(4,I)= NO DU 4-EME SOMMET DE LA FACE
C                      0 SI TRIANGLE
C          LFACES(5,I)= + ou - CHAINAGE HACHAGE SUR FACE SUIVANTE
C                      >0 FACE INTERNE
C                      <0 FACE FRONTALIERE
C          SI SOMMET 2 < DERNIER SOMMET  => FACE   DIRECTE
C                      <                 => FACE INDIRECTE
C          UNE FACE DIRECTE EST VUE DE L EXTERIEUR AU CUBE
C          SOUS LA FORME DIRECTE
C          LFACES(6,I)= NUMERO DU 1-ER  CUBE CONTENANT CETTE FACE
C                      >0 SI FACE   DIRECTE DANS CE CUBE
C                      <0 SI FACE INDIRECTE DANS CE CUBE
C          SI LA FACE APPARTIENT A 2 CUBES ALORS
C          LFACES(7,I)= NUMERO DU 2-EME CUBE CONTENANT CETTE FACE
C                      >0 SI FACE   DIRECTE DANS CE CUBE
C                      <0 SI FACE INDIRECTE DANS CE CUBE
C          SINON
C          LFACES(7,I)= NUMERO DE LA FACE FRONTALIERE SUIVANTE
C                      0 SI C'EST LA DERNIERE
C L1FAFR : NUMERO DE LA PREMIERE FACE FRONTALIERE
C NBFAFR : NOMBRE DE FACES FRONTALIERES
C
C SORTIES:
C --------
C NOFAFR : NUMERO   DE LA FACE LA PLUS PROCHE, PUIS LA SUIVANTE, ...
C DIFAFR : DISTANCE DE LA FACE LA PLUS PROCHE, PUIS LA SUIVANTE, ...
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PERRONNET ALAIN ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1994
C ...................................................................012
      include"./incl/trvari.inc"
      INTEGER           LFACES(1:MOFACE,1:MXFACE)
      REAL              XYZSOM(1:3,1:*)
      INTEGER           NOFAFR(1:NBFAFR)
      REAL              DIFAFR(1:NBFAFR)
C
C     CALCUL DES TABLEAUX NOFAFR ET DIFAFR
C     NOFAFR : NUMERO DE LA FACE FRONTALIERE DANS LFACES
C     DIFAFR : COTE AXONOMETRIQUE DU BARYCENTRE DES FACES
      CALL TRBFFR( MOFACE , MXFACE , LFACES , XYZSOM ,
     %             L1FAFR , 0,       NBFAFR , NOFAFR , DIFAFR )
C
C     LE TRI PAR TAS DE CETTE DISTANCE
C     LA FACE LA PLUS PROCHE EST LA PREMIERE
      CALL TRITRP( NBFAFR , DIFAFR , NOFAFR )

      RETURN
      END
