      SUBROUTINE TRLFPI( NOFOTI, NUTYSU, ARETMX, PERMT2, MXSOMM,
     %                   NBLFTR, NULFTR, NDARLF,
     %                   NBSOIN, NOSOIN, DISOIN, NBARFR,
     %                   MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %                   MOARTR, MXARTR, N1ARTR, NOARTR,
     %                   PXYD  , NOARST, NSLIGN,
     %                   NBSOMM, NBSOM,  NBTRIA, NDTRI0,
     %                   ORIGIN, D2D3, XMIN, YMIN, XYMXMI,
     %                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    TRIANGULATION D'UNE SURFACE PLANE DELIMITEE PAR DES ARETES
C -----    FORMANT LA FRONTIERE ET DES POINTS INTERNES IMPOSES,
C          CONSTRUCTION DE L'ETOILE DES POINTS FRONTALIERS ET INTERNES
C          REGENERATION DES ARETES FRONTALIERES NON ARETES DE LA TRIANGULATION
C          AMELIORATION DE LA QUALITE GEOMETRIQUE DES TRIANGLES
C          PRISE EN COMPTE SI ELLE EXISTE DE LA FONCTION
C          TAILLE_IDEALE(X,Y,Z) ENTRE LES 2 SOMMETS DE CHAQUE ARETE
C
C ENTREES:
C --------
C NOFOTI : NUMERO DE LA FONCTION UTILISATEUR TAILLE_IDEALE(x,y,z)
C          0 SI LA FONCTION N'A PAS ETE DONNEE PAR L'UTILISATEUR
C NUTYSU : NUMERO D'OPTION DE GENERATION DU MAILLAGE DE CETTE SURFACE
C         19 APPEL DIRECT A PARTIR DU SP SUEX19
C          1 APPEL PAR LE SP SUEX01-QUNSAL (QUADRANGLE ALGEBRIQUE)
C          3 APPEL PAR LE SP SUEX03        (B-SPLINE POLYNOMIALE )
C          6 APPEL PAR LE SP SUEX06-TRNSAL (TRIANGLE   ALGEBRIQUE)
C ARETMX : LONGUEUR MAXIMALE DES ARETES DES TRIANGLES
C PERMT2 : PERIMETRE DE LA LIGNE ENVELOPPE DANS LE PLAN
C          AVANT MISE A L'ECHELLE A 2**20
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TRIANGULATION
C NBLFTR : NOMBRE DE  LIGNES FERMEES LIMITANT LA SURFACE A TRIANGULER
C NULFTR : NUMERO DES LIGNES FERMEES LIMITANT LA SURFACE A TRIANGULER
C NDARLF : NUMERO DE LA PREMIERE ARETE DE CHAQUE LIGNE FERMEE DANS
C          LE TABLEAU NOSOAR
C NBARFR : NOMBRE D'ARETES  DE LA FRONTIERE OU CONTOUR DU DOMAINE =
C          NOMBRE DE POINTS DE LA FRONTIERE OU CONTOUR DU DOMAINE
C MOSOAR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE ET
C          INDICE DANS NOSOAR DE L'ARETE SUIVANTE DANS LE HACHAGE
C MOARTR : NOMBRE MAXIMAL D'ENTIERS PAR ARETE DU TABLEAU NOARTR
C MXSOAR : NOMBRE MAXIMAL D'ARETES FRONTALIERES DECLARABLES
C
C
C ENTREES ET SORTIES :
C --------------------
C NBSOIN : NOMBRE DE POINTS INTERNES A LA SURFACE FUTUR SOMMET DE LA
C          TRIANGULATION (REMIS A JOUR SI POINTS DOUBLES)
C NOSOIN : NOSOIN(I) NUMERO DANS LE LEXIQUE POINTS DU I-EME POINT
C          INTERNE
C DISOIN : DISOIN(I) DISTANCE SOUHAITEE AVEC LES VOISINS DU POINT
C N1SOAR : NUMERO DE LA PREMIERE ARETE VIDE DANS LE TABLEAU NOSOAR
C          UNE ARETE I DE NOSOAR EST VIDE  <=>  NOSOAR(1,I)=0
C NOSOAR : NUMERO DES 2 SOMMETS , NO LIGNE, 2 TRIANGLES DE L'ARETE,
C          CHAINAGE DES ARETES FRONTALIERES, CHAINAGE DU HACHAGE DES ARETES
C          HACHAGE DES ARETES = H(NS1,NS2)=MIN(NS1,NS2)
C
C    ATTENTION: UNE ARETE DOIT ETRE LA SUIVANTE DE LA PRECEDENTE
C    ---------- OU LA PREMIERE D'UNE COMPOSANTE CONNEXE DE LA
C               FRONTIERE  OU LA DERNIERE
C
C SORTIES:
C --------
C N1ARTR : NUMERO DU PREMIER TRIANGLE VIDE DANS LE TABLEAU NOARTR
C          LE CHAINAGE DES TRIANGLES VIDES SE FAIT SUR NOARTR(2,.)
C NOARTR : LES 3 ARETES DES TRIANGLES +-ARETE1, +-ARETE2, +-ARETE3
C          ARETE1 = 0 SI TRIANGLE VIDE => ARETE2 = TRIANGLE VIDE SUIVANT
C
C PXYD   : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  DISTANCE_SOUHAITEE
C          TABLEAU REEL2(3,MXSOMM)
C
C NOARST : NOARST(I) NUMERO NOSOAR D'UNE ARETE DU SOMMET I
C
C NSLIGN : TABLEAU DU NUMERO DE SOMMET DANS SA LIGNE POUR CHAQUE
C          SOMMET FRONTALIER
C          NUMERO DU POINT DANS LE LEXIQUE POINT SI INTERNE IMPOSE
C          0 SI LE POINT EST INTERNE NON IMPOSE PAR L'UTILISATEUR
C         -1 SI LE SOMMET EST EXTERNE AU DOMAINE
C
C NBSOMM : NOMBRE DE SOMMETS INTERNES + EXTERNES APRES TRIANGULATION
C NBTRIA : NOMBRE DE TRIANGLES DE LA TRIANGULATION
C NDTRI0 : NUMERO MAXIMAL DANS NOARTR D'UN TRIANGLE INTERNE
C ORIGIN : POINT ORIGINE DANS LE PLAN DE MAILLAGE
C D2D3   : MATRICE DE PASSAGE DES COORDONNEES 3D EN COORDONNEES 2D
C XMIN   : ABSCISSE MINIMALE APRES TRANSFORMATION 3D->2D
C YMIN   : ORDONNEE MINIMALE APRES TRANSFORMATION 3D->2D
C XYMXMI : ECART MAXIMAL ENTRE XMAX-XMIN ET YMAX-YMIN
C NBSOM  : NOMBRE DE SOMMETS DE LA TRIANGULATION FINALE
C IERR   :  0 SI PAS D'ERREUR
C          52 SATURATION DES SOMMETS DANS LE TABLEAU PXYD
C           2 SATURATION DES ARETES
C           3 SATURATION DES TRIANGLES
C           4 PILE SATUREE DES ARETES FRONTALIERES NON RETROUVEES
C           5 PILE SATUREE DES ARETES EXTERIEURES AU DOMAINE
C           7 TOUS LES POINTS SONT ALIGNES
C           8 AUCUN CERCLE CIRCONSCRIT AUX TRIANGLES ACTUELS NE CONTIENT
C             LE POINT COURANT
C           9 TABLEAU NOSOAR DE TAILLE INSUFFISANTE CAR TROP D'ARETES
C             PERDUES
C          10 LIGNE ENVELOPPE INCORRECTE
C          11 2 EXTREMITES CONFONDUES POUR UNE ARETE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & ST PIERRE DU PERRAY DECEMBRE 2007
C....................................................................012
      IMPLICIT INTEGER (W)
      include"./incl/a___xyzsommet.inc"
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/trvari.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
C     LA LONGUEUR DES ARETES DE LA LIGNE ENVELOPPE DANS R**3
      COMMON / PEL1R3 / PERMT3
      LOGICAL           TRATRI
      COMMON / DV2DCO / TRATRI
C     TRACE OU NON DES TRIANGLES GENERES DANS LA TRIANGULATION
C
C     LES PARAMETRES D'ENTREE ET SORTIE
      INTEGER           NOSOAR(MOSOAR,MXSOAR),
     %                  NSLIGN(MXSOMM),
     %                  NULFTR(1:NBLFTR),
     %                  NDARLF(1:NBLFTR),
     %                  NOARST(MXSOMM),
     %                  NOSOIN(NBSOIN)
      REAL              DISOIN(NBSOIN)
      DOUBLE PRECISION  DINFO, TCPU, D
      DOUBLE PRECISION  RAP2P3
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
C
C     LES PARAMETRES RESULTATS
      INTEGER           NOARTR(MOARTR,MXARTR)
      DOUBLE PRECISION  PXYD(3,MXSOMM)
      REAL              COMXMI(3,2),
     %                  ORIGIN(3)
      DOUBLE PRECISION  D2D3(3,3)
C
      INTEGER           NOSOTR(3)
      EQUIVALENCE      (NOSOTR(1),NS1), (NOSOTR(2),NS2),
     %                 (NOSOTR(3),NS3)
C
      INTEGER           NUARCO(5)
C
cccC     TRACE OU NON DES TRIANGLES GENERES
ccc      TRATRI = .TRUE.
ccc      TRATRI = .FALSE.
C
C     AU DEBUT PAS D'ERREUR
      IERR = 0
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10000)
      ELSE
         WRITE(IMPRIM,20000)
      ENDIF
10000 FORMAT(' TRIANGULATION de LIGNES FERMEES dans un PLAN de R3')
20000 FORMAT(' TRIANGULATION of CLOSED LINES in a PLANE of R3')
C
C     RAPPORT DES PERIMETRES DES ARETES DE LA LIGNE ENVELOPPE DE R2 SUR R3
      IF( NOFOTI .LE. 0 .OR. NUTYSU .EQ. 19 ) THEN
         RAP2P3 = 1D0
      ELSE
C        LE PERIMETRE DE LA LIGNE ENVELOPPE EST CALCULEE DANS SUEX01 03 06
         RAP2P3 = PERMT2 / PERMT3
      ENDIF
C
C     INITIALISATIONS DES POINTS INTERNES ET DES ARETES FRONTALIERES
C     VALEUR DE LA TAILLE SOUHAITEE AUTOUR DES FUTURS SOMMETS
C     RENUMEROTATION GLOBALE DES SOMMETS POUR LA TRIANGULATION
C     ==============================================================
      CALL TEQINI( NOFOTI, MXSOMM, NBLFTR, NDARLF,
     %             NBARFR, NSLIGN,
     %             NBSOIN, NOSOIN, DISOIN,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             PXYD  , NBARPI,
     %             ORIGIN, D2D3  , COMXMI, AREMIN, AREMAX,
     %             XMIN  , YMIN  , XYMXMI, ARETMX, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C     ICI LE TABLEAU PXYD N'A PAS DE SOMMETS IDENTIQUES
C
      IF( TRATRI ) THEN
C        LES TRACES SONT DEMANDES
         CALL EFFACE
C        LE CADRE OBJET GLOBAL APRES MISE A L'ECHELLE EN 2D ENTRE 0 ET 2**20
         XE = ( COMXMI(1,2) - COMXMI(1,1) ) / 15
         YE = ( COMXMI(2,2) - COMXMI(2,1) ) / 15
         CALL ISOFENETRE( COMXMI(1,1)-XE, COMXMI(1,2)+XE,
     %                    COMXMI(2,1)-YE, COMXMI(2,2)+YE )
      ENDIF
      D    = DINFO('DELTA CPU')
      TCPU = D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10002) TCPU
      ELSE
         WRITE(IMPRIM,20002) TCPU
      ENDIF
10002 FORMAT(' TEMPS COHERENCE des DONNEES',T60,':',F11.2,' SECONDES')
20002 FORMAT(' TIME for INPUT COHERENCE',T60,':',F11.2,' SECONDS')
C
C     INITIALISATION DU TABLEAU NOARTR
C     ================================
      DO 5 I=1,MXARTR
C        LE NUMERO DE L'ARETE EST INCONNU
         NOARTR(1,I) = 0
C        LE CHAINAGE SUR LE TRIANGLE VIDE SUIVANT
         NOARTR(2,I) = I+1
 5    CONTINUE
      NOARTR(2,MXARTR) = 0
C
C     CREATION DES 4 SOMMETS NBSOMM+1...4 DU RECTANGLE ENGLOBANT
C     ==========================================================
      NBSOMM = NBARPI
      XE = ( COMXMI(1,2) - COMXMI(1,1) ) / 18
      YE = ( COMXMI(2,2) - COMXMI(2,1) ) / 18
C
C     SOMMET BAS GAUCHE
      NBSOMM = NBSOMM + 1
      NSR1   = NBSOMM
      PXYD(1,NBSOMM) = COMXMI(1,1) - XE
      PXYD(2,NBSOMM) = COMXMI(2,1) - YE
      PXYD(3,NBSOMM) = 2**20
C
C     SOMMET BAS DROITE
      NBSOMM = NBSOMM + 1
      NSR2   = NBSOMM
      PXYD(1,NBSOMM) = COMXMI(1,2) + XE
      PXYD(2,NBSOMM) = COMXMI(2,1) - YE
      PXYD(3,NBSOMM) = 2**20
C
C     SOMMET HAUT DROITE
      NBSOMM = NBSOMM + 1
      NSR3   = NBSOMM
      PXYD(1,NBSOMM) = COMXMI(1,2) + XE
      PXYD(2,NBSOMM) = COMXMI(2,2) + YE
      PXYD(3,NBSOMM) = 2**20
C
C     SOMMET HAUT GAUCHE
      NBSOMM = NBSOMM + 1
      NSR4   = NBSOMM
      PXYD(1,NBSOMM) = COMXMI(1,1) - XE
      PXYD(2,NBSOMM) = COMXMI(2,2) + YE
      PXYD(3,NBSOMM) = 2**20
C
C     CREATION DES 5 ARETES DES 2 TRIANGLES DU RECTANGLE ENGLOBANT 1234
C     =================================================================
C     AJOUT DE L'ARETE I DE SOMMETS SI SI+1 DANS LE TABLEAU NOSOAR
      DO 8 I=1,4
         NS1 = NBARPI + I
         IF( I .LT. 4 ) THEN
            NS2 = NBARPI + I + 1
         ELSE
            NS2 = NBARPI + 1
         ENDIF
         CALL FASOAR( NS1, NS2, (I+1)/2, 0, 0,
     %                MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %                NUARCO(I), IERR )
         IF( IERR .NE. 0 ) RETURN
 8    CONTINUE
C     L'ARETE 5 COMMUNE DE SOMMETS S1-S3 AUX TRIANGLES 1-2
      CALL FASOAR( NBARPI+1, NBARPI+3, 1, 2, 0,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR, NOARST,
     %             NUARCO(5), IERR )
      IF( IERR .NE. 0 ) RETURN
C
C     CREATION DES 2 TRIANGLES INITIAUX ENGLOBANT LE RECTANGLE MAX
C     ============================================================
      NOARTR( 1, 1 ) =  NUARCO(1)
      NOARTR( 2, 1 ) =  NUARCO(2)
      NOARTR( 3, 1 ) = -NUARCO(5)
C
      NOARTR( 1, 2 ) =  NUARCO(3)
      NOARTR( 2, 2 ) = -NUARCO(4)
      NOARTR( 3, 2 ) =  NUARCO(5)
C
C     PREMIER TRIANGLE VIDE
      N1ARTR = 3
C
C     TRIANGULER LES SOMMETS DES LIGNES DE LA FRONTIERE ET DES POINTS INTERNES
C     ========================================================================
      CALL TRPRTR( NBARPI, MXSOMM, NBSOMM, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             IERR  )
C     IERR =0 SI PAS D'ERREUR
C          =1 SI LE TABLEAU NOSOAR EST SATURE
C          =2 SI LE TABLEAU NOARTR EST SATURE
C          =3 SI AUCUN DES TRIANGLES NE CONTIENT L'UN DES POINTS
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10007) D
      ELSE
         WRITE(IMPRIM,20007) D
      ENDIF
10007 FORMAT(' TEMPS TRIANGULATION DES LIGNES',T60,':',F11.2,
     %       ' SECONDES')
20007 FORMAT(' TIME of LINES TRIANGULATION',T60,':',F11.2,' SECONDS' )
cccC     TRACE DE LA TRIANGULATION ACTUELLE
ccc      CALL TETRMA( NCNOIR, NCBLAN,
ccc     %             COMXMI, PXYD,
ccc     %             MOSOAR, MXSOAR, NOSOAR,
ccc     %             MOARTR, MXARTR, NOARTR,
ccc     %             NBTRIA, QUAMOY, QUAMIN )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     DETECTION DES ARETES FRONTALIERES INITIALES PERDUES
C     TRIANGULATION FRONTALE POUR LES RESTAURER
C     ===================================================
      MXARCF = MXSOMM / 5
      MNARCF = 0
      CALL TNMCDC( 'ENTIER', MXARCF*6+1, MNARCF )
      CALL TEREFR( NBARPI, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             MXARCF, MCN(MNARCF+MXARCF*5), MCN(MNARCF+MXARCF*2),
     %             MCN(MNARCF), MCN(MNARCF+MXARCF),
     %             NBARPE, IERR )
      CALL TNMCDS( 'ENTIER', MXARCF*6+1, MNARCF)
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10040) NBARPE
      ELSE
         WRITE(IMPRIM,20040) NBARPE
      ENDIF
10040 FORMAT(' RESTAURATION de',I7,' ARETES PERDUES DE LA FRONTIERE' )
20040 FORMAT(' RECOVERING of',I7,' LOST EDGES of the BOUNDARY' )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10045) D
      ELSE
         WRITE(IMPRIM,20045) D
      ENDIF
10045 FORMAT(' TEMPS RECUPERATION DES ARETES PERDUES DE LA FRONTIERE',
     %         T60,':',F11.2,' SECONDES')
20045 FORMAT(' TIME RECUPERATION of LOST EDGES of the BOUNDARY',
     %         T60,':',F11.2,' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCBLEU, NCCYAN,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C     ICI TRIANGULATION AVEC RESPECT DES ARETES INITIALES FRONTALIERES
C
C     SUPPRESSION DES TRIANGLES EXTERNES AU DOMAINE
C     =============================================
C     RECHERCHE DU DERNIER TRIANGLE UTILISE
      DO 55 NDTRI0=MXARTR,1,-1
         IF( NOARTR(1,NDTRI0) .NE. 0 ) GOTO 58
 55   CONTINUE
 58   MNTRSU = 0
      CALL TNMCDC( 'ENTIER', NDTRI0,   MNTRSU )
      CALL TESUEX( NBLFTR, NULFTR,
     %             NDTRI0, NBSOMM, PXYD, NSLIGN,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             NBTRIA, MCN(MNTRSU), IERR )
      CALL TNMCDS( 'ENTIER', NDTRI0, MNTRSU )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10060) D
      ELSE
         WRITE(IMPRIM,20060) D
      ENDIF
10060 FORMAT(' TEMPS SUPPRESSION DES TRIANGLES EXTERNES',
     %         T60,':',F11.2,' SECONDES')
20060 FORMAT(' TIME SUPPRESSION of EXTERNAL TRIANGLES',
     %         T60,':',F11.2,' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCBLEU, NCMAGE,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     AJOUTER DES SOMMETS D'UNE GRILLE DE TRIANGLES EQUILATERAUX
C     DE COTE DE LONGUEUR ARETMX
C     SI FONCTION TAILLE_IDEALE(X,Y,Z) EXISTE => AJOUT DE POINTS MEDIANS
C     ==================================================================
      NBSXGR = INT( ( COMXMI(1,2) - COMXMI(1,1) ) / ARETMX )
      NBSYGR = INT( ( COMXMI(2,2) - COMXMI(2,1) )
     %            / ( ARETMX * SQRT(3D0) * 0.5D0 ) )
      MNSTGR = 0
      CALL TNMCDC( 'ENTIER', NBSXGR*NBSYGR, MNSTGR )
      CALL TRAJGR( COMXMI, ARETMX, NBSXGR, NBSYGR, MCN(MNSTGR),
     %             NOFOTI, NUTYSU, RAP2P3,
     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
     %             MXSOMM, NBSOMM, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             IERR  )
      CALL TNMCDS( 'ENTIER', NBSXGR*NBSYGR, MNSTGR )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10061) D
      ELSE
         WRITE(IMPRIM,20061) D
      ENDIF
10061 FORMAT(' TEMPS AJOUT DE LA GRILLE',T60,':',F11.2,' SECONDES'
     %)
20061 FORMAT(' TIME of GRID VERTICES ADDITION',T60,':',F11.2,
     %' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCORAN, NCBLEU,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     AJOUTER DES POINTS POUR RESPECTER LA TAILLE SOUHAITEE DES ARETES
C     ================================================================
      CALL TRAJPT( ARETMX, NOFOTI, NUTYSU, RAP2P3,
     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
     %             MXSOMM, NBSOMM, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             IERR  )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10062) D
      ELSE
         WRITE(IMPRIM,20062) D
      ENDIF
10062 FORMAT(' TEMPS AJOUT DES BARYCENTRES',T60,':',F11.2,' SECONDES'
     %)
20062 FORMAT(' TIME of BARYCENTER POINT ADDITION',T60,':',F11.2,
     %' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCVERT, NCJAUN,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     AJOUTER LE MILIEU POUR RESPECTER LA TAILLE SOUHAITEE DES ARETES
C     ===============================================================
      CALL TRAJMA( ARETMX, NOFOTI, NUTYSU, RAP2P3,
     %             ORIGIN, D2D3,   XMIN,   YMIN,   XYMXMI,
     %             MXSOMM, NBSOMM, PXYD,
     %             MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR, NOARST,
     %             IERR  )
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10064) D
      ELSE
         WRITE(IMPRIM,20064) D
      ENDIF
10064 FORMAT(' TEMPS AJOUT MILIEU DES ARETES',T60,':',F11.2,' SECONDES'
     %)
20064 FORMAT(' TIME of EDGE MIDDLE ADDITION',T60,':',F11.2,' SECONDS')
      IF( IERR .NE. 0 ) GOTO 9999
C     TRACE DE LA TRIANGULATION ACTUELLE
      CALL TETRMA( NCJAUN, NCNOIR,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     AMELIORATION DE LA QUALITE DE LA TRIANGULATION PAR
C     BARYCENTRAGE DES SOMMETS INTERNES A LA TRIANGULATION
C     SUPPRESSION DES ARETES TROP LONGUES OU TROP COURTES
C     MODIFICATION DE LA TOPOLOGIE DES GROUPES DE TRIANGLES
C     MISE EN DELAUNAY DE LA TRIANGULATION
C     =====================================================
      MXARCF = MXSOMM / 10
      MNARCF = 0
      CALL TNMCDC( 'ENTIER', 7*MXARCF+1, MNARCF )
      CALL TEAMQT( NOFOTI, NUTYSU, RAP2P3,
     %             NOARST, MOSOAR, MXSOAR, N1SOAR, NOSOAR,
     %             MOARTR, MXARTR, N1ARTR, NOARTR,
     %             MXARCF, MCN(MNARCF), MCN(MNARCF+MXARCF),
     %             MCN(MNARCF+6*MXARCF), MCN(MNARCF+3*MXARCF),
     %             MCN(MNARCF+2*MXARCF),
     %             ORIGIN, D2D3,   XMIN,   YMIN,  XYMXMI,
     %             NBARFR, NBARPI, NBSOMM, MXSOMM,
     %             PXYD, NSLIGN, IERR )
      CALL TNMCDS( 'ENTIER', 7*MXARCF+1, MNARCF )
C
      IF( IERR .EQ. -13 ) IERR=0
C     MODIF 6/10/2006 ARRET DE L'AMELIORATION APRES BOUCLE INFINIE DANS CAETOI
C
      IF( IERR .NE. 0 ) GOTO 9999
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10065) D
      ELSE
         WRITE(IMPRIM,20065) D
      ENDIF
10065 FORMAT(' TEMPS AMELIORATION DE LA QUALITE DE LA TRIANGULATION',
     %         T60,':',F11.2,' SECONDES')
20065 FORMAT(' TIME IMPROVEMENT of TRIANGULATION QUALITY',
     %         T60,':',F11.2,' SECONDS')
C
C     TRACE DE LA TRIANGULATION FINALE
      CALL TETRMA( NCCYAN, NCROUG,
     %             COMXMI, PXYD,
     %             MOSOAR, MXSOAR, NOSOAR,
     %             MOARTR, MXARTR, NOARTR,
     %             NBTRIA, QUAMOY, QUAMIN )
C
C     =======================
C     FIN DE LA TRIANGULATION
C     =======================
C
C     RENUMEROTATION DES SOMMETS INTERNES: NOARST(I)=NUMERO FINAL DU SOMMET
C     ===================================
      DO 70 I=1,NBSOMM
         NOARST(I) = 0
 70   CONTINUE
      DO 80 NT=1,MXARTR
         IF( NOARTR(1,NT) .NE. 0 ) THEN
C           LE NUMERO DES 3 SOMMETS DU TRIANGLE NT
            CALL NUSOTR( NT, MOSOAR, NOSOAR, MOARTR, NOARTR,
     %                   NOSOTR )
C           LES 3 SOMMETS DU TRIANGLE SONT ACTIFS
            NOARST( NOSOTR(1) ) = 1
            NOARST( NOSOTR(2) ) = 1
            NOARST( NOSOTR(3) ) = 1
            NDTRI0 = NT
         ENDIF
 80   CONTINUE
      NBSOM = 0
      DO 90 I=1,NBSOMM
         IF( NOARST(I) .GT. 0 ) THEN
            NBSOM = NBSOM + 1
            NOARST(I) = NBSOM
         ENDIF
 90   CONTINUE
C
C     IMPRESSION DU NOMBRE DE SOMMETS ET TRIANGLES
C     ============================================
      D    = DINFO('DELTA CPU')
      TCPU = TCPU + D
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10093) TCPU
      ELSE
         WRITE(IMPRIM,20093) TCPU
      ENDIF
10093 FORMAT(' TEMPS TOTAL DE LA TRIANGULATION',T60,':',F11.2,
     %       ' SECONDES')
20093 FORMAT(' TIME TOTAL of TRIANGULATION',T60,':',F11.2,
     %       ' SECONDS')
C
 9999 RETURN
      END
