      SUBROUTINE TRSGPT( NBSGPT, XYZSG,
     %                   NOFAFR, DIFAFR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    ETABLIR LE TABLEAU DES NUMEROS DES FACES ISOVALEURS
C -----    DERRIERE CELUI DES FACES FRONTALIERES
C          CALCULER LA COTE AXONOMETRIQUE DES BARYCENTRES DE CES FACES
C ENTREES:
C --------
C NBSGPT : NOMBRE TOTAL DE SEGMENTS XYZ INTERSECTION AVEC LES TETRAEDRES
C XYZSG  : XYZ DU MILIEU DES SEGMENTS   INTERSECTION AVEC LES TETRAEDRES
C
C SORTIES:
C --------
C NOFAFR : NUMERO DE CHAQUE FACE DE CHAQUE FACE ISOVALEUR
C DIFAFR : COTE AXONOMETRIQUE DU BARYCENTRE DES FACES ISOVALEURS
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR :PERRONNET ALAIN ANALYSE NUMERIQUE LJLL UPMC PARIS OCTOBRE 2003
C ...................................................................012
      REAL      XYZSG(3,2,NBSGPT)
      INTEGER   NOFAFR(1:NBSGPT)
      REAL      DIFAFR(1:NBSGPT),
     %          XYZ(3)
C
C     BOUCLE SUR LES SEGMENTS DEFINIS PAR UN COUPLE DE POINTS D'INTERSECTION
      DO 100 N=1,NBSGPT
C
C        LE NUMERO DU SEGMENT DANS L'ENSEMBLE FACES-ARETES
         NOFAFR( N ) = N
C
C        LES COORDONNEES DU BARYCENTRE DE CE SEGMENT
         XYZ(1) = ( XYZSG(1,1,N) + XYZSG(1,2,N) ) /2
         XYZ(2) = ( XYZSG(2,1,N) + XYZSG(2,2,N) ) /2
         XYZ(3) = ( XYZSG(3,1,N) + XYZSG(3,2,N) ) /2
C
C        COTE Z AXONOMETRIQUE DANS LA DIRECTION DE VISEE
         CALL XYZAXO( XYZ, XYZ )
         DIFAFR( N ) = XYZ(3)
C
 100  CONTINUE
C
      END
