      SUBROUTINE VD1F3F( NOSOMM, NOFACO, MXFACO, LEFACO, NBFACO,
     %                   N1FASC, NBFAPE, MXFAPE, NOFAPE,
     %                   NPSOFR, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    DECOUPER EN 3 FACES LA FACE TRIANGULAIRE NOFACO
C -----    PAR AJOUT DU POINT NOSOMM INTERNE
C
C ENTREES:
C --------
C NOSOMM : NO PTXYZD DU POINT INTERNE A LA FACE NOFACO DE LEFACO
C NOFACO : NO DANS LEFACO DE LA FACE A SUBDIVISER
C
C MODIFIES :
C ----------
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO
C LEFACO : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES
C NBFACO ; NOMBRE DE FACES ACTIVES DE LEFACO
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS
C NBFAPE : NOMBRE DE FACES PERDUES
C NOFAPE : NUMERO DES FACES PERDUES
C NPSOFR : NPSOFR(I)=1 SI POINT AJOUTE AU MILIEU D'UNE ARETE LEFACO
C                   =2 SI POINT AJOUTE BARYCENTRE DE SOMMETS LEFACO
C
C SORTIE :
C --------
C IERR   : 0 SI PAS D'ERREUR
C          1 SI SATURATION DES SOMMETS DE PTXYZD
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC   NOVEMBRE 2005
C2345X7..............................................................012
      INCLUDE"./incl/trvari.inc"
      INCLUDE"./incl/gsmenu.inc"
      INTEGER           LEFACO(11,0:MXFACO),
     %                  NPSOFR(*),
     %                  N1FASC(1:*),
     %                  NOFAPE(1:MXFAPE)
      INTEGER           NOSOFA(3), NOFAOP(3)
C
C     LES 2 VOLUMES DES 3 FACES (VDR1CF ASSURE MEMES VOLUMES)
      NV1 = LEFACO( 4, NOFACO )
      NV2 = LEFACO( 5, NOFACO )
C
C     PROTECTION DES SOMMETS ET FACES OPPOSEES
      DO I=1,3
         NOSOFA(I) = LEFACO(I,NOFACO)
         NOFAOP(I) = LEFACO(5+I,NOFACO)
      ENDDO
C
CCCC     LA FACE NOFACO EST MARQUEE RETROUVEE DANS NOFAPE
CCC      CALL VDNFRE( NOFACO, NBFAPE, NOFAPE, LEFACO )
C
C     DESTRUCTION DE LA FACE NOFACO DE LEFACO AVEC MISE A JOUR DES ADJACENCES
      CALL VDDSFA( NOFACO, MXFACO, LEFACO, NBFACO, N1FASC )
C
C     LE POINT EST MARQUE DE TYPE INTERNE A LA FACE LEFACO
      NPSOFR(NOSOMM) = 2
C
C     LES FACES OPPOSEES AU CF
      NF0 = 0
      NF3 = -1
      DO 10 I=1,3
C
C        LE NUMERO DES 2 SOMMETS DE L'ARETE ET DES 3 SOMMETS DE LA FACE
         NS1 = NOSOFA(I)
         NS2 = NOSOFA(MOD(I,3)+1)
C
C        LA FACE OPPOSEE AU CF
         NFOP = NOFAOP(I)
C
C        LA FACE NFOP EST SUPPOSEE RETROUVEE
CCC         CALL VDNFRE( NFOP, NBFAPE, NOFAPE, LEFACO )
C
C        AJOUT DU TRIANGLE I A PARTIR DE L'ARETE I ET DU BARYCENTRE
         CALL VDAJFA( NS1, NS2, NOSOMM, NV1, NV2, NFOP, -2, NF3,
     %                MXFACO, LEFACO, NBFACO, N1FASC, NF )
         IF( NF .LE. 0 ) GOTO 9000
         IF( NBFAPE .GE. MXFAPE ) THEN
C           SATURATION DES FACES PERDUES
            NBLGRC(NRERR) = 1
            KERR(1) = 'SATURATION DES FACES PERDUES'
            CALL LEREUR
            IERR = 3
            GOTO 9999
         ENDIF
         NBFAPE = NBFAPE + 1
         NOFAPE(NBFAPE) = NF
C
         IF( I .EQ. 1 ) THEN
C           SAUVEGARDE DU NUMERO DE LA PREMIERE FACE
            NF0 = NF
         ELSE
C           MISE A JOUR DE L'ADJACENCE DE NF3 ET DE NF
            DO 4 J=6,8
               IF( LEFACO(J,NF3) .EQ. -2 ) THEN
                  LEFACO(J,NF3) = NF
                  GOTO 6
               ENDIF
 4          CONTINUE
         ENDIF
C
C        MISE A JOUR DE LA FACE OPPOSEE CONNUE
 6       NF3 = NF
 10   CONTINUE
C
C     LA FACE NOFACO N'EST PLUS PERDUE
      DO I=1,NBFAPE
         IF( NOFAPE(I) .EQ. NOFACO ) THEN
             NOFAPE(I) = -NOFACO
             GOTO 15
          ENDIF
       ENDDO
C
C      MISE A JOUR DE L'ADJACENCE DE NF ET DE NF0
 15    DO 20 I=6,8
         IF( LEFACO(I,NF) .EQ. -2 ) THEN
            LEFACO(I,NF) = NF0
            GOTO 30
         ENDIF
 20   CONTINUE
C
C     MISE A JOUR DE L'ADJACENCE DE NF0 ET NF
 30   DO 40 I=6,8
         IF( LEFACO(I,NF0) .EQ. -1 ) THEN
            LEFACO(I,NF0) = NF
            GOTO 50
         ENDIF
 40   CONTINUE
 50   GOTO 9999
C
C     SATURATION LEFACO
 9000 IERR = 2
C
 9999 RETURN
      END
