      SUBROUTINE VD1F2F( NOQUEUE, NAA,   NFF,    MXFACO, LEFACO, NBFACO,
     %                   N1FASC, NBFAPE, NOFAPE,
     %                   NBSOMM, MXSOMM, PTXYZD, NPSOFR,
     %                   MXPIFA, MNPIFA, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  DECOUPER EN 2 FACES LEFACO TOUTES LES FACES DE LEFACO AYANT
C -----  L'ARETE NAA DE LA FACE NFF DE LEFACO COMMUNE ET LE POINT MILIEU

C ENTREES:
C --------
C NOQUEUE: =0 DECOUPAGE DE LA SEULE ARETE NAA DE LA FACE NFF
C          =1 DECOUPAGE D'AUTRES FACES PERDUES
C NAA    : NUMERO DE 1 A 3 DE L'ARETE DE LA FACE NFF
C NFF    : NUMERO DANS LEFACO DE LA FACE

C MODIFIES:
C ---------
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO
C LEFACO : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES I.E.
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1 < SOMMET 2 < SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...
C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON C-A-D AUCUN TETRAEDRE CONTIENT CETTE FACE
CCCC       LEFACO(12,*) NO DE FACE OC
C NBFACO ; NOMBRE DE FACES ACTIVES DE LEFACO
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS

C NBFAPE : NOMBRE DE  FACES PERDUES
C NOFAPE : NUMERO DES FACES PERDUES
C NBSOMM : NUMERO PTXYZD DU DERNIER SOMMET AJOUTE A LA TETRAEDRISATION
C          MIS A JOUR EN SORTIE = NUMERO PTXYZD DU MILIEU AJOUTE
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C NPSOFR : NPSOFR(I)=1 SI POINT AJOUTE AU MILIEU D'UNE ARETE LEFACO
C                   =2 SI POINT AJOUTE BARYCENTRE DE SOMMETS LEFACO
C MXPIFA : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LA QUEUE
C MNPIFA : ADRESSE MCN DE LA QUEUE DES FACES

C SORTIE :
C --------
C IERR   : 0 SI PAS D'ERREUR
C          1 SI SATURATION DES SOMMETS DE PTXYZD
C          2 SI SATURATION DES FACES TRIANGULAIRES DE LEFACO
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       MARS 1993
C2345X7..............................................................012
      PARAMETER      (COSMAX=0.99863, MXNEWF=128)
C     COSMAX : SEUIL DU COSINUS DE L'ANGLE FORME PAR LES NORMALES AUX
C              2 FACES ET AU DESSUS DUQUEL LES FACES
C              SONT CONSIDEREES COPLANAIRES
C              ( 0.99     => 8.11 DEGRES )
C              ( 0.9962   => 5    DEGRES )
C              ( 0.99756  => 4    DEGRES )
C              ( 0.99863  => 3    DEGRES )
C              ( 0.999    => 2.56 DEGRES )
C              ( 0.9999   => 0.8  DEGRES )
      include"./incl/trvari.inc"
      include"./incl/gsmenu.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      DOUBLE PRECISION  PTXYZD(1:4,1:*),COS3PD,C,C3,C4
      INTEGER           LEFACO(11,0:MXFACO),N1FASC(1:*),
     %                  NOFAPE(1:NBFAPE),NPSOFR(MXSOMM)
      INTEGER           NONEWF(MXNEWF), NS(4)

C     ANGLE AU DELA DUQUEL IL FAUT LE DECOUPER
C     SOIT  UN ANGLE ARCOS(-0.76)=139.46 DEGRES
C     SOIT  UN ANGLE ARCOS(-0.80)=143.13 DEGRES
C     SOIT  UN ANGLE ARCOS(-0.85)=148.21 DEGRES
ccc      COSMIN =-0.8   19/11/2019
C     DECOUPAGE SI ANGLE SUPERIEUR A 90 degres
      COSMIN = -0.01

      IERR    = 0
      NBNEWF  = 0
      TRACTE0 = TRACTE

C     INITIALISATION DE LA QUEUE
      L1FACE = 0
      L2FACE = 1
C     LA FACE ET NO D'ARETE EST MISE DANS LA QUEUE
      MCN( MNPIFA ) = NFF
      MCN( MNPIFA + 1 ) = NAA
      MCN( MNPIFA + 2 ) = 0
      MCN( MNPIFA + 3 ) = 0

C     TANT QU'UNE FACE EST A DECOUPER LE FAIRE
C     ========================================
 1    L1FACE = L1FACE + 1
      IF( L1FACE .GT. L2FACE ) GOTO 8000

C     LA FACE ET ARETE A DECOUPER
      MN   = MNPIFA + 4 * L1FACE - 4
      NF   = MCN( MN )
      NFFF = NF
      NAR  = MCN( MN + 1 )

C     PROTECTION DES DONNEES
      NONOUIS = 1
      NBT   = 0
      NBFD  = 1
      NFDER = 0
      NF10  = 0
      NF20  = 0
      NF30  = 0
      NF40  = 0

C     PROTECTION DES 4 SOMMETS DES 2 FACES PARTAGEANT L'ARETE NAR
      IF( NAR .EQ. 1 ) THEN
         N0 = 3
      ELSE
         N0 = NAR - 1
      ENDIF
      IF( NAR .EQ. 3 ) THEN
         N1 = 1
      ELSE
         N1 = NAR + 1
      ENDIF
      NS(1) = LEFACO( NAR, NF )
      NS(2) = LEFACO( N1 , NF )
      NS(3) = LEFACO( N0 , NF )
C     LA FACE OPPOSEE PAR L'ARETE NAR DE LA FACE NF
      NF2 = LEFACO( 5+NAR, NF )
C     LE NUMERO NS(4) DU SOMMET DE NF2 N'APPARTENANT PAS A NF
      DO I=1,3
         NS(4) = LEFACO(I,NF2)
         IF( NS(4) .NE. NS(1) .AND. NS(4) .NE. NS(2) .AND.
     %       NS(4) .NE. NS(3) ) GOTO 4
      ENDDO
      PRINT*, 'vd1f2f: ANOMALIE cf ETIQUETTE 4 NS=',NS

C     LE NUMERO DES 2 SOMMETS DE L'ARETE
 4    NS1  = NS(1)
      NS2  = NS(2)

C     CREATION DES COORDONNEES DU POINT MILIEU DE L'ARETE NAR DE NF
      IF( NBSOMM .GE. MXSOMM ) THEN
         PRINT*,'vd1f2f: SATURATION DU TABLEAU PTXYZD MXSOMM=',MXSOMM
         IERR = 1
         GOTO 9999
      ENDIF
      NBSOMM = NBSOMM + 1
      DO I=1,4
         PTXYZD(I,NBSOMM) = (PTXYZD(I,NS1)+PTXYZD(I,NS2)) * 0.5D0
      ENDDO
C     MILIEU D'UNE ARETE LEFACO
      NPSOFR(NBSOMM) = 1

C     DEBUT DE BOUCLE SUR LES FACES A DIVISER EN 2 DEMI-FACES
C     =======================================================
 10   NBT = NBT + 1
C     LE NUMERO DES 2 SOMMETS DE L'ARETE ET DES 3 SOMMETS DE LA FACE
      IF( NAR .EQ. 1 ) THEN
         N0 = 3
      ELSE
         N0 = NAR - 1
      ENDIF
      IF( NAR .EQ. 3 ) THEN
         N1 = 1
      ELSE
         N1 = NAR + 1
      ENDIF
      NS1 = LEFACO( NAR, NF )
      NS2 = LEFACO( N1 , NF )
      NS3 = LEFACO( N0 , NF )
C
C     LES 2 VOLUMES DE LA FACE
      NV1 = LEFACO( 4 , NF )
      NV2 = LEFACO( 5 , NF )

C     LA FACE INITIALE NF, SI ELLE EST PERDUE, EST ALORS MARQUEE RETROUVEE
      CALL VDNFRE( NF, NBFAPE, NOFAPE, LEFACO )

C     LES FACES ADJACENTES
      NF0 = LEFACO( 5+N0 , NF )
      NF1 = LEFACO( 5+N1 , NF )
      NF2 = LEFACO( 5+NAR, NF )
      IF( NF2 .EQ. NF ) THEN
C        LA FACE EST SA PROPRE VOISINE => C'EST LA DERNIERE A TRAITER
         NFDER = 1
      ELSE
C        NF N'EST PAS LA DERNIERE FACE A TRAITER
C        NF ET NF2 SONT ELLES COPLANAIRES ?
         CALL VD2TPL( COSMAX, NF, NF2, LEFACO, PTXYZD, NONOUI )
         IF( NONOUI .EQ. 0 ) THEN
            NONOUIS = 0
         ENDIF
         NBFD = NBFD + 1
      ENDIF

CCCC     TRACE DE LA FACE NF
CCC      CALL TRFATR( NCBLAN, NCVERT, LEFACO(1,NF), PTXYZD )

C     DESTRUCTION DE LA FACE NF DE LEFACO SANS MISE A JOUR DES ADJACENCES
      CALL VDDSFA( NF, MXFACO, LEFACO, NBFACO, N1FASC )

C     AJOUT DES DEMI-FACES DANS LEFACO
      CALL VDAJFA( NS3, NS1, NBSOMM, NV1, NV2, NF0, -1, -2,
     %             MXFACO, LEFACO, NBFACO, N1FASC, NF3 )
      IF( NF3 .LE. 0 ) GOTO 9000
C     RECENSEMENT DE LA NOUVELLE FACE LEFACO POUR TRACE.
C     SUPPRIMABLE ENSUITE
      IF( NBNEWF .GE. MXNEWF ) GOTO 22
      NBNEWF = NBNEWF + 1
      NONEWF( NBNEWF ) = NF3

 22   CALL VDAJFA( NS3, NBSOMM, NS2, NV1, NV2, NF3, -1, NF1,
     %             MXFACO, LEFACO, NBFACO, N1FASC, NF4 )
      IF( NF4 .LE. 0 ) GOTO 9000
      IF( NF4 .LE. 0 ) GOTO 9000
C     RECENSEMENT DE LA NOUVELLE FACE LEFACO POUR TRACE.
C     SUPPRIMABLE ENSUITE
      IF( NBNEWF .GE. MXNEWF ) GOTO 25
      NBNEWF = NBNEWF + 1
      NONEWF( NBNEWF ) = NF4

C     MISE A JOUR DE L'ADJACENCE DE NF4 DANS NF3
 25   DO I=6,8
         IF( LEFACO(I,NF3) .EQ. -2 ) THEN
            LEFACO(I,NF3) = NF4
            GOTO 30
         ENDIF
      ENDDO

C     MISE A JOUR DE N1FASC
 30   N1FASC( NS3 ) = NF3
      N1FASC( NS1 ) = NF3
      N1FASC( NS2 ) = NF4
      N1FASC( NBSOMM ) = NF4

      IF( NF .EQ. NFFF ) THEN

C        SAUVEGARDE DES 2 PREMIERES DEMI-FACES DE LA 1_ERE FACE
         NF10 = NF3
         NF20 = NF4

      ELSE

C        TRIANGLE DONT ON CONNAIT LES 2 PREDECESSEURS
C        MISE A JOUR DE LEUR ADJACENCE
         DO I=6,8
            IF( LEFACO(I,NF30) .EQ. -1 ) THEN
               LEFACO(I,NF30) = NF3
            ENDIF
            IF( LEFACO(I,NF40) .EQ. -1 ) THEN
               LEFACO(I,NF40) = NF4
            ENDIF
         ENDDO

      ENDIF

CCCC     TRACE DES 2 FACES FINALES DE LEFACO
CCC      CALL TRFATR( NCCYAN, NCBLEU, LEFACO(1,NF3), PTXYZD )
CCC      CALL TRFATR( NCCYAN, NCBLEU, LEFACO(1,NF4), PTXYZD )

      IF( NBT .GT. 1 .OR. L1FACE .EQ. 1 ) THEN
C        L'ANGLE AU SOMMET NBSOMM DANS LES 2 TRIANGLES CREES EST IL CORRECT?
         C3 = COS3PD( PTXYZD(1,NBSOMM), PTXYZD(1,NS1), PTXYZD(1,NS3) )
         C4 = COS3PD( PTXYZD(1,NBSOMM), PTXYZD(1,NS2), PTXYZD(1,NS3) )
         C  = MIN( C3, C4 )
         IF( C .LT. COSMIN ) THEN
C           ANGLE TROP GRAND: LE MILIEU DE L'ARETE OPPOSEE A CET ANGLE SERA AJOUTE
C           L'ANGLE MAX AUGMENTE POUR EVITER DE TROP AJOUTER DE NOUVEAUX MILIEUX
            COSMIN = COSMIN - 0.03
            IF( C .EQ. C3 ) THEN
C              LA FACE NF3 SERA DECOUPEE
               NFA  = NF3
               NFOP = NF4
            ELSE
C              LA FACE NF4 SERA DECOUPEE
               NFA  = NF4
               NFOP = NF3
            ENDIF
C           RECHERCHE DE L'ARETE OPPOSEE AU SOMMET NBSOMM DANS NFA
            DO I=1,3
               IF( NBSOMM .EQ. LEFACO(I,NFA) ) GOTO 60
            ENDDO
 60         IF( I .EQ. 3 ) THEN
               NARA = 1
            ELSE
               NARA = I+1
            ENDIF
C           CETTE FACE ET ARETE SONT MISES DANS LA QUEUE SI DEMANDE
            IF( NOQUEUE .NE. 0 ) THEN
               L2FACE = L2FACE + 1
               IF( 4*L2FACE .GT. MXPIFA ) THEN
                  CALL TNMCAU('ENTIER', MXPIFA, MXPIFA+2048, MXPIFA,
     %                         MNPIFA)
                  MXPIFA = MXPIFA + 2048
               ENDIF
               MN = MNPIFA + 4 * L2FACE - 4
               MCN( MN ) = NFA
               MCN( MN + 1 ) = NARA
C              LA FACE OPPOSEE PAR L'ARETE NBSOMM-NS3
               MCN( MN + 2 ) = NFOP
               CALL NO1A1F( NBSOMM, NS3, LEFACO(1,NFOP), MCN(MN+3) )
            ENDIF
         ENDIF
      ENDIF

C     PASSAGE A LA FACE ADJACENTE SUIVANTE
C     ====================================
      IF( NFDER .EQ. 0 ) THEN
C        IL EXISTE UNE FACE NF2 DIFFERENTE DE NF VOISINE
C        LE NUMERO D'ARETE NA2 DANS NF2 DE L'ARETE NAR DE NF
         CALL NO1A1F( NS1, NS2, LEFACO(1,NF2), NA2 )

C        IL EXISTE UNE FACE SUIVANTE NF2 NON IDENTIQUE A LA PREMIERE NF
C        RECHERCHE DU SENS DE PARCOURS DE L'ARETE NA2
         IF( NS1 .NE. LEFACO(NA2,NF2) ) THEN
C           PERMUTATION DES FACES NF3 NF4 POUR LA MISE A JOUR ULTERIEURE
            NF30 = NF4
            NF40 = NF3
         ELSE
            NF30 = NF3
            NF40 = NF4
         ENDIF
C        LA NOUVELLE FACE A DIVISER EN 2
         NF  = NF2
         NAR = NA2
         GOTO 10
      ENDIF

C     MISE A JOUR DES ADJACENCES DES 2 DEMI FACES DE LA PREMIERE FACE NFFF
C     RECHERCHE DE NS1 DANS LA FACE NF10
      DO I=1,3
         IF( LEFACO(I,NF10) .EQ. NS1 ) GOTO 90
      ENDDO

C     ICI LA FACE NF10 NE CONTIENT PAS NS1 DONC EST FACE A NF4
C     ET NF20 EST FACE A NF3  => PERMUTATION DE NF10 ET NF20
      I    = NF10
      NF10 = NF20
      NF20 = I

C     NF3 EST FACE A NF10 ET NF4 EST FACE A NF20
 90   CALL NO1A1F( NS1, NBSOMM, LEFACO(1,NF3), N1 )
      LEFACO( 5+N1, NF3 ) = NF10
      CALL NO1A1F( NS2, NBSOMM, LEFACO(1,NF4), N1 )
      LEFACO( 5+N1, NF4 ) = NF20

      IF( NONOUIS .NE. 0 .AND. (NBFD .EQ. 2) ) THEN
C        LES 2 FACES DECOUPEES SONT COPLANAIRES
C        LE QUADRANGLE DE DIAGONALE NS1-NS2 EST IL CONVEXE ?
         CALL QUADCXD( PTXYZD(1,NS(1)), PTXYZD(1,NS(3)),
     %                 PTXYZD(1,NS(2)), PTXYZD(1,NS(4)), NONOUI )
         IF( NONOUI .NE. 0 ) THEN

C           OUI: LE MILIEU DE L'ARETE DEVIENT LE BARYCENTRE DU QUADRANGLE
C           DE SOMMETS NS(1) NS(3) NS(2) NS(4)
            DO I=1,4
               PTXYZD(I,NBSOMM)=( PTXYZD(I,NS(1)) + PTXYZD(I,NS(2))
     %              +  PTXYZD(I,NS(3)) + PTXYZD(I,NS(4)) ) * 0.25D0
            ENDDO

CCCC           TRACE DU POINT BARYCENTRE DU QUADRANGLE
CCC            X = PTXYZD(1,NBSOMM)
CCC            Y = PTXYZD(2,NBSOMM)
CCC            Z = PTXYZD(3,NBSOMM)
CCC            CALL MOVE( X, Y, Z )
CCC            CALL ECRENT( NBSOMM )
         ENDIF
      ENDIF
      GOTO 1

C     EVENTUEL CHANGEMENT DE DIAGONALES POUR AMELIORER LA QUALITE MINIMALE
C     ====================================================================
 8000 MN = MNPIFA + 6
      DO I=2,L2FACE
C        LA FACE ET ARETE
         NFA = MCN( MN )
         NAR = MCN( MN + 1 )
C        LA FACE OPPOSEE
         NFOP = LEFACO( 5+NAR, NFA )
         IF( NFOP .GT. 0 ) THEN
C           QUALITE DES 2 TRIANGLES POUR UNE EVENTUELLE PERMUTATION
            CALL MQ2F2F( NAR, NFA, NFOP, LEFACO, PTXYZD, NONOUI )
            IF( NONOUI .NE. 0 ) THEN
C              ECHANGE EFFECTIF
               CALL CH2F2F( NAR, NFA, NFOP, PTXYZD,
     %                      MXFACO, LEFACO, N1FASC,
     %                      NF2, NF3 )
            ENDIF
         ENDIF
         MN = MN + 4
      ENDDO

ccc      PRINT*,'vd1f2f:',NBNEWF,' FACES LEFACO CREEES'

cccC     TRACE DES FACES LEFACO CREEES
ccc      IF( NBNEWF .GT. 4 ) THEN
ccc         TRACTE=.TRUE.
ccc         CALL TRQQLEFA( PTXYZD, NBNEWF, NONEWF, MXFACO, LEFACO )
ccc      ENDIF

      GOTO 9999
C
C     SATURATION LEFACO
 9000 IERR = 2
      PRINT*,'vd1f2f: SATURATION DU TABLEAU LEFACO MXFACO=',MXFACO

 9999 TRACTE = TRACTE0
      RETURN
      END
