      SUBROUTINE VDFALF( N, NOTENT, MXFACO, LEFACO, NOFACO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   RETROUVER LE NUMERO DANS LEFACO DE LA FACE N DU TETRAEDRE
C -----   DONT LES NUMEROS DES 4 SOMMETS SONT DANS NOTENT

C ENTREES:
C --------
C N      : NUMERO LOCAL DE 1 A 4 DE LA FACE A RETROUVER DANS LEFACO
C NOTENT : NO DU SOMMET1  SOMMET2  SOMMET3  SOMMET4
C          ORDRE CLASSIQUE 1 2 3 DIRECT EN BAS ET 4 EN HAUT
C          LE SOMMET 1 EST LE PLUS PETIT
C          LE VOLUME EST POSITIF => UN ORDRE
C          TETRAEDRE1  TETREDRE2  TETRAEDRE3  TETREDRE4  VOISINS PAR LA
C          FACE1       FACE2D      FACE3       FACE4
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3

C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)

C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...

C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
CCCC       LEFACO(12,*) NO DE FACE OC

C SORTIE :
C --------
C NOFACO : NUMERO DANS LEFACO DE CETTE FACE SI ELLE EST RETROUVEE
C          0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       JUIN 1991
C....................................................................012
      INTEGER   NOTENT(8), LEFACO(11,0:MXFACO), NOSOFA(3)

C     LE NUMERO DES 3 SOMMETS DE LA FACE N DU TETRAEDRE NOTENT
      NOSOFA(1) = NOTENT(N)

      IF( N .LT. 4 ) THEN
         N1 = N + 1
      ELSE
         N1 = 1
      ENDIF
      NOSOFA(2) = NOTENT(N1)

      IF( N1 .LT. 4 ) THEN
         N1 = N1 + 1
      ELSE
         N1 = 1
      ENDIF
      NOSOFA(3) = NOTENT(N1)

      CALL TRI3NO( NOSOFA, NOSOFA )

C     HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
      NOFACO = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3), MXFACO ) + 1
      NOFACO = LEFACO(10,NOFACO)

 10   IF( NOFACO .GT. 0 ) THEN

         IF( NOSOFA(1) .EQ. LEFACO(1,NOFACO) ) THEN
            IF( NOSOFA(2) .EQ. LEFACO(2,NOFACO) ) THEN
               IF( NOSOFA(3) .EQ. LEFACO(3,NOFACO) ) THEN
                  RETURN
               ENDIF
            ENDIF
         ENDIF

C        LA FACE N'EST PAS RETROUVEE.PASSAGE A LA SUIVANTE
         NOFACO  = LEFACO(9,NOFACO)
         GOTO 10

      ENDIF

C     FACE NON RETROUVEE
      NOFACO = 0

      RETURN
      END
