      SUBROUTINE VDFAPE( PTXYZD, N1TETS, NOTETR,
     %                   MXFACO, LEFACO, MXTAUX, MNTAUX,
     %                   NBFAPE, MXFAPE, MNFAPE )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    RECHERCHE DES FACES DE LA TRIANGULATION DE LA FRONTIERE
C -----    NON PRESENTES DANS LA TETRAEDRISATION ACTUELLE

C ENTREES:
C --------
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z  DISTANCE_SOUHAITEE ALENTOUR
C N1TETS : N1TETS(I) NUMERO NOTETR D'UN TETRAEDRE AYANT POUR SOMMET I
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          1:   =0 POUR UNE FACE VIDE
C          123: NO (DANS PTXYZD) DU SOMMET 1 < SOMMET 2 < SOMMET 3
C          45:  NO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          678: NO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3

C          9: ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C             => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C             LEFACO(9,*) -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)

C          10: HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C              LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C              NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C              SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C              NF = LEFACO( 9, NF )  ...

C          11: >0  NO NOTETR D'UN TETRAEDRE AYANT CETTE FACE,
C              =0  SINON
CCCC       LEFACO(12,*) NO DE FACE OC

C MXTAUX : MAXIMUM D'ENTIERS DU TABLEAU D'ADRESSE MNTAUX
C MNTAUX : ADRESSE MCN DU TABLEAU TAUX

C SORTIES:
C --------
C NBFAPE : NOMBRE DE FACES PERDUES DE LEFACO DU CONTOUR
C          NON PRESENTES DANS LA TETRAEDRISATION
C MXFAPE : NOMBRE MAXIMAL DE FACES PERDUES
C MNFAPE : ADRESSE MCN DU TABLEAU DES NUMEROS DES FACES PERDUES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC       JUIN 1991
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY  Fevrier 2017
C....................................................................012
      include"./incl/langue.inc"
      include"./incl/pp.inc"

      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE, TRACTE0

      COMMON            MCN(MOTMCN)
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      DOUBLE PRECISION  PTXYZD(1:4,1:*)
      INTEGER           NOTETR(8,*),
     %                  N1TETS(*),
     %                  LEFACO(11,0:MXFACO),
     %                  NOSOFATE(3,4)
      DATA              NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /
C     NO DES SOMMETS DES 4 FACES AVEC LA NORMALE DIRIGEE VERS L'EXTERIEUR

C     LE NOMBRE DE FACES PERDUES DES INTERFACES
      NBFAPE = 0
      NBFACO = 0
      NBF    = 0

      DO 100 NF = 1, MXFACO
C
         IF( LEFACO(1,NF) .LE. 0 ) GOTO 100

C        LA FACE NF DE LEFACO 
         NBFACO = NBFACO + 1
C
C        EXISTE T IL UN TETRAEDRE AYANT CETTE FACE ?
         NT = LEFACO( 11, NF )
         IF( NT .GT. 0 ) THEN

C           LE TETRAEDRE EXISTE T IL REELLEMENT?
            IF( NOTETR(1,NT) .LE. 0 ) THEN
C              NO DE TETRAEDRE ABANDONNE
               LEFACO( 11, NF ) = 0
               GOTO 30
            ENDIF

C           LA FACE EST ELLE BIEN DANS LE TETRAEDRE NT DE NOTETR?
            DO 20 I=1,3
               NS = LEFACO( I, NF )
               IF( NS.EQ.NOTETR(1,NT) .OR. NS.EQ.NOTETR(2,NT) .OR.
     %             NS.EQ.NOTETR(3,NT) .OR. NS.EQ.NOTETR(4,NT) ) GOTO 20
C              ICI: LE SOMMET NS DE LA FACE NF N'EST PAS DANS LE TETRAEDRE
               LEFACO( 11, NF ) = 0
               GOTO 30
 20         CONTINUE

C           ICI: LA FACE NF EST UNE FACE DU TETRAEDRE NT
C           ============================================
            GOTO 100

         ENDIF

C        A PRIORI LA FACE NF DE LEFACO N'EST PAS UNE FACE DES TETRAEDRES
C        RECHERCHE DES TETRAEDRES AYANT LES 3 SOMMETS DE CETTE FACE NF?
 30      CALL TETR1F( LEFACO(1,NF), N1TETS, NOTETR,
     %                NBTENSF, MXTAUX, MCN(MNTAUX), IERR )

         IF( NBTENSF .GT. 0 ) THEN
C           UNE DES FACES DU TETRAEDRE MCN(MNTAUX) EST LA FACE NF DE LEFACO
            LEFACO( 11, NF ) = MCN( MNTAUX )
            GOTO 100
         ENDIF

C        LA FACE NF EST PERDUE N'APPARTENANT A AUCUN TETRAEDRE
C        =====================================================
         IF( NBFAPE .GE. MXFAPE ) THEN
            CALL TNMCAU( 'ENTIER', MXFAPE, MXFAPE+1024, NBFAPE, MNFAPE )
            MXFAPE = MXFAPE + 1024
         ENDIF

C        LA FACE PERDUE DE LEFACO EST EMPILEE
         MCN( MNFAPE + NBFAPE ) = NF
         NBFAPE = NBFAPE + 1

 100  CONTINUE

      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) NBFAPE, NBFACO
      ELSE
         WRITE(IMPRIM,22001) NBFAPE, NBFACO
      ENDIF
ccc      print *,'nofape=',(mcn(mnfape+k),k=0,nbfape-1)
12001 FORMAT(' vdfape  :',I6,' FACES TRIANGULAIRES PERDUES parmi les',
     %         I8,' FACES TRIANGULAIRES LEFACO de la FRONTIERE')
22001 FORMAT(' vdfape  :',I6,' LOST TRIANGULAR FACES among',
     %         I8,' BOUNDARY TRIANGULAR FACES')

C     TRACE EVENTUEL DES NBFAPE FACES PERDUES DANS LEFACO
C     ---------------------------------------------------
      TRACTE0 = TRACTE
      TRACTE  = .TRUE.
      CALL TRFAPE( NBFAPE, MCN(MNFAPE), MXFACO, LEFACO, PTXYZD )
      TRACTE = TRACTE0

      RETURN
      END
