      SUBROUTINE VDMFNF( NBTRCF, NOTRCF, N1ARCF, NOARCF,
     %                   MXFACO, LEFACO, NBFACO,
     %                   N1FASC, NBFAPE, NOFAPE,
     %                   NBSOMM, MXSOMM, PTXYZD, NPSOFR, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    DECOUPER EN NBTRCF+2 FACES LE POLYGONE CONVEXE FORME DE
C -----    NBTRCF TRIANGLES A PARTIR DE SON BARYCENTRE

C ENTREES:
C --------
C NBTRCF : NOMBRE DE TRIANGLES DU CONTOUR FERME
C NOTRCF : TABLEAU DU NUMERO DANS LEFACO DES 3 TRIANGLES DU PENTAGONE
C N1ARCF : TABLEAU (0:MXTRCF) AUXILIAIRE
C NOARCF : NUMERO DES ARETES DE LA LIGNE DU CONTOUR FERME SELON UN SENS
C          (1,*) NUMERO DU SOMMET
C          (2,*) NUMERO DE L'ARETE SUIVANTE DU CF DANS LE TABLEAU NOARCF
C          (3,*) NUMERO DE L'ARETE DANS LE TABLEAU NOSOAR

C MODIFIES :
C ----------
C MXFACO : NOMBRE MAXIMAL DE FACES DECLARABLES DANS LEFACO
C LEFACO : LES 3 SOMMETS, 2 MATERIAUX, 3 FACES VOISINES ET CHAINAGE
C          DES FACES TRIANGULAIRES DU CONTOUR ET INTERFACES
C NBFACO ; NOMBRE DE FACES ACTIVES DE LEFACO
C N1FASC : N1FASC(NS)=NUMERO (DANS LEFACO) D'UNE FACE DE SOMMET NS
C NBFAPE : NOMBRE DE FACES PERDUES
C NOFAPE : NUMERO DES FACES PERDUES
C NBSOMM : NUMERO DU DERNIER SOMMET AJOUTE A LA TETRAEDRISATION
C          MIS A JOUR EN SORTIE
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C NPSOFR : NPSOFR(I)=1 SI POINT AJOUTE AU MILIEU D'UNE ARETE LEFACO
C                   =2 SI POINT AJOUTE BARYCENTRE DE SOMMETS LEFACO

C SORTIE :
C --------
C IERR   : 0 SI PAS D'ERREUR
C          1 SI SATURATION DES SOMMETS DE PTXYZD
C          2 SI SATURATION DE LEFACO
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS UPMC    OCTOBRE 1991
C2345X7..............................................................012
      include"./incl/trvari.inc"
      include"./incl/gsmenu.inc"
      DOUBLE PRECISION  PTXYZD(1:4,1:MXSOMM)
      INTEGER           NOTRCF(NBTRCF),
     %                  N1ARCF(0:*),
     %                  NOARCF(1:3,1:*),
     %                  LEFACO(11,0:MXFACO),
     %                  N1FASC(1:*),
     %                  NOFAPE(1:NBFAPE),
     %                  NPSOFR(MXSOMM)
      DOUBLE PRECISION  D

C     CREATION DES COORDONNEES DU POINT BARYCENTRE DU CONTOUR FERME
C     =============================================================
      IF( NBSOMM .GE. MXSOMM ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER)(1:10),'(I10)') MXSOMM
         KERR(1) = 'MAXIMUM DE SOMMETS ' // KERR(MXLGER)(1:10) //
     %             ' ATTEINT'
         CALL LEREUR
         IERR = 1
         GOTO 9999
      ENDIF
      NBSOMM = NBSOMM + 1
C     LE NOMBRE D'ARETES OU SOMMETS DE LA FRONTIERE DU POLYGONE
      NBARET = NBTRCF + 2
      DO I=1,4
C        LA PREMIERE ARETE
         N1 = N1ARCF(1)
         D  = 0D0
         DO J=1,NBARET
            D  = D + PTXYZD(I,NOARCF(1,N1))
            N1 = NOARCF(2,N1)
         ENDDO
         PTXYZD(I,NBSOMM) = D / NBARET
      ENDDO

C     BARYCENTRE DE NBARET SOMMETS LEFACO
      NPSOFR(NBSOMM) = 2

C     LES 2 VOLUMES DES FACES
      NV1 = LEFACO( 4 , NOTRCF(1) )
      NV2 = LEFACO( 5 , NOTRCF(1) )

C     TRACE ET DESTRUCTION DES NBTRCF FACES INITIALES
C     ===============================================
      DO I=1,NBTRCF
C        LA FACE I
         NF = NOTRCF(I)
CCCC        TRACE EVENTUEL DE LA FACE
CCC         CALL TRFATR( NCBLAN, NCNOIR, LEFACO(1,NF), PTXYZD )
C        LA FACE NF EST MARQUEE RETROUVEE DANS NOFAPE
         CALL VDNFRE( NF, NBFAPE, NOFAPE, LEFACO )
C        DESTRUCTION DE LA FACE NF DE LEFACO AVEC
C        MISE A JOUR DES ADJACENCES
         CALL VDDSFA( NF,  MXFACO, LEFACO, NBFACO, N1FASC )
      ENDDO

C     LES TRIANGLES OBTENUS PAR JONCTION DES ARETES AU BARYCENTRE
C     ===========================================================
      NF0 = 0
      NF3 = -1
      N1  = N1ARCF(1)
      DO I=1,NBARET

C        LE NUMERO DES 2 SOMMETS DE L'ARETE ET DES 3 SOMMETS DE LA FACE
         NS1 = NOARCF(1,N1)
         N2  = NOARCF(2,N1)
         NS2 = NOARCF(1,N2)

C        LA FACE OPPOSEE AU CF
         NF1 = NOARCF(3,N1)

C        LA FACE NF1 DE LEFACO EST RETIREE DE LA LISTE NOFAPE
C        AINSI QUE TOUTES LES FACES VOISINES PARTAGEANT L'UNE
C        DES 3 ARETES DE LA FACE NF1
         CALL VDNFRE( NF1, NBFAPE, NOFAPE, LEFACO )

C        AJOUT DU TRIANGLE I A PARTIR DE L'ARETE I ET DU BARYCENTRE
         CALL VDAJFA( NS1, NS2, NBSOMM, NV1, NV2, NF1, -1, NF3,
     %                MXFACO, LEFACO, NBFACO, N1FASC, NF )
         IF( NF .LE. 0 ) GOTO 9000

CCCC        TRACE DE LA NOUVELLE FACE
CCC         CALL TRFATR( NCCYAN, NCBLEU, LEFACO(1,NF), PTXYZD )

C        SAUVEGARDE DU NUMERO DE LA PREMIERE FACE
         IF( I .EQ. 1 ) NF0 = NF

C        MISE A JOUR DE N1FASC
         N1FASC( NS1 ) = NF

C        MISE A JOUR DE LA FACE OPPOSEE CONNUE
         NF3 = NF

C        ARETE SUIVANTE
         N1 = N2
      ENDDO

C     MISE A JOUR DE L'ADJACENCE DE NF ET DE NF0
      DO I=6,8
         IF( LEFACO(I,NF) .EQ. -1 ) THEN
            LEFACO(I,NF) = NF0
            GOTO 30
         ENDIF
      ENDDO

C     MISE A JOUR DE L'ADJACENCE DE NF0 ET NF
 30   DO I=6,8
         IF( LEFACO(I,NF0) .EQ. -1 ) THEN
            LEFACO(I,NF0) = NF
            GOTO 50
         ENDIF
      ENDDO
 50   GOTO 9999

C     SATURATION DU TABLEAU LEFACO
 9000 IERR = 2

 9999 RETURN
      END
