      SUBROUTINE VDPTNF( COULIM, MXSOMM, NBSOMM, PTXYZD, NPSOFR,
     %                   MXFACO, LEFACO,  IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    AJOUT A LA LISTE DES POINTS DE LA COUCHE LIMITE SITUES
C -----    SUR LA NORMALE MOYENNE AUX SOMMETS DES FACES ET
C          SUR LA NORMALE AUX FACES DU CONTOUR
C          DEFINI PAR LE TABLEAU LEFACO
C
C ENTREES:
C --------
C COULIM : EPAISSEUR DE LA COUCHE LIMITE
C MXSOMM : NOMBRE MAXIMAL DE SOMMETS PERMIS POUR LA TETRAEDRISATION
C PTXYZD : X Y Z DISTANCE SOUHAITEE DES POINTS
C MXFACO : NOMBRE MAXIMAL DECLARABLE DE FACES DU CONTOUR
C LEFACO : FACE DU CONTOUR OU INTERFACES ENTRE VOLUMES
C          IL CONTIENT DANS CET ORDRE
C          NUMERO (DANS PTXYZD) DU SOMMET 1, SOMMET 2, SOMMET 3
C          NUMERO (DANS NUVOPA 0 SINON) DU VOLUME1 , VOLUME2 DE LA FACE
C          NUMERO (DANS LEFACO) DE LA FACE ADJACENTE PAR L'ARETE 1 2 3
C
C          ATTENTION: UNE ARETE PEUT APPARTENIR A PLUS DE 2 FACES
C          => CHAINAGE CIRCULAIRE DE CES FACES DANS LEFACO
C          LEFACO(9,*)  -> FACE SUIVANTE (*=0:VIDE, *<>0:NON VIDE)
C          HACHAGE AVEC LA SOMME DES 3 SOMMETS MODULO MXFACO
C          LF = MOD( NOSOFA(1)+NOSOFA(2)+NOSOFA(3) , MXFACO ) + 1
C          NF = LEFACO( 10, LF ) LE NUMERO DE LA 1-ERE FACE DANS LEFACO
C          SI LA FACE NE CONVIENT PAS. PASSAGE A LA SUIVANTE
C          NF  = LEFACO( 9, NF )  ...
C
C ENTREES ET SORTIES :
C --------------------
C NBSOMM : NOMBRE DE SOMMETS DANS PTXYZD A L'APPEL ET EN SORTIE
C NPSOFR : NUMERO DES POINTS INITIAUX
C          LE SIGNE DEVIENT NEGATIF SI LE SOMMET EST DEPLACE
C          =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C          =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C          =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C          =  1 000 000  + NUMERO DU  POINT INTERNE UTILISATEUR
C          = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C                    LA NUMEROTATION DES SOMMETS DE LA SURFACE
C          = -1 SI LE POINT EST SOMMET D'OT ET RECONNU TROP PROCHE
C          = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE
C          = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C          = -NPSOFR(I) SI POINT I DEPLACE SUR LA SURFACE
C             DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE
C
C SORTIES:
C --------
C IERR   : 0 SI PAS D'ERREUR
C          1 SATURATION DES SOMMETS
C          2 PROBLEME LORS DU CALCUL DE LA FONCTION TAILLE_IDEALE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St Pierre du Perray     Aout 2012
C....................................................................012
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/trvari.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      INTEGER           LEFACO(1:11,0:MXFACO), NPSOFR(MXSOMM)
      DOUBLE PRECISION  COULIM, PTXYZD(1:4,1:MXSOMM)
      DOUBLE PRECISION  PROSCD, COORNO(3), V(3,2), D, BARY(4)
      INTRINSIC         SQRT
C
      IERR = 0
      IF( COULIM .LE. 0D0 ) RETURN
C
      MOREE2 = MOTVAR(6)
      NBSOM0 = NBSOMM
C
C     EXISTENCE OU NON DE LA FONCTION TAILLE_IDEALE(X,Y,Z)
      NOFOTI = NOFOTIEL()
C
C     DECLARATION DU TABLEAU COORNO(3,NBSOM0)
C     XYZ DU VECTEUR NORMAL EN CHAQUE SOMMET DES FACES LEFACO
      MNCOSF = 0
      CALL TNMCDC( 'REEL2', 3*NBSOM0, MNCOSF )
      CALL AZEROD( 3*NBSOM0, MCN(MNCOSF) )
      MNXYZ = (MNCOSF-1)/MOREE2 - 3
C
C     DECLARATION DU TABLEAU NBFASL(NBSOM0)
C     NOMBRE DE FACES LEFACO CONTENANT LE SOMMET
      MNNBFS = 0
      CALL TNMCDC( 'ENTIER', NBSOM0, MNNBFS )
      CALL AZEROI( NBSOM0, MCN(MNNBFS) )
C
C     PARCOURS DES FACES ACTUELLES DE LEFACO
      DO 10 NF=1,MXFACO
C
C        NUMERO DU SOMMET 1 DE LA FACE NF DE LEFACO
         NS = LEFACO(1,NF)
         IF( NS .LE. 0 ) GOTO 10
C
C        LA FACE EXISTE: CALCUL DU VECTEUR NORMAL UNITE A LA FACE NF
         DO J=1,2
            DO I=1,3
               V(I,J) = PTXYZD(I,LEFACO(J+1,NF)) - PTXYZD(I,NS)
            ENDDO
         ENDDO
C        LE VECTEUR NORMAL
         CALL PROVEC( V(1,1) , V(1,2) , COORNO )
         D = SQRT( PROSCD( COORNO, COORNO, 3 ) )
C        LE VECTEUR NORMAL DE NORME 1
         DO I=1,3
            COORNO(I) = COORNO(I)  / D
         ENDDO
C
C        AJOUT DE LA NORMALE AUX 3 SOMMETS DE LA FACE LEFACO
         DO J=1,3
C           LE NUMERO DU SOMMET J DE LA FACE NF
            NS = LEFACO(J,NF)
C           UNE FACE DE PLUS POUR LE SOMMET
            MCN(MNNBFS-1+NS) = MCN(MNNBFS-1+NS) + 1
C           LA DISTANCE SOUHAITEE AUTOUR DU SOMMET NS EST 2 COUCHE LIMITE
            PTXYZD(4,NS) = COULIM * 2D0
C           AJOUT DES 3 COORDONNEES AUX NORMALES DU SOMMET
            MNX = MNXYZ + 3 * NS
            DO I=1,3
               DMCN( MNX + I ) = DMCN( MNX + I ) + COORNO(I)
            ENDDO
         ENDDO
C
C        CREATION DE 2 POINTS UN DE CHAQUE COTE DE LA FACE
C        SUR LA NORMALE AU BARYCENTRE DE LA FACE
         DO I=1,4
            BARY(I) = 0D0
            DO J=1,3
               BARY(I) = BARY(I) + PTXYZD(I,LEFACO(J,NF))
            ENDDO
            BARY(I) = BARY(I) / 3D0
         ENDDO
C
         IF( NOFOTI .GT. 0 ) THEN
C           LES 3 PARAMETRES D'APPEL DE LA FONCTION 'TAILLE_IDEALE'
C           EN CE SOMMET XYZ DU REPERE R**3 "NATUREL"
            CALL FONVAL( NOFOTI, 3, BARY, NCODEV, BARY(4) )
            IF( NCODEV .LE. 0 ) THEN
               IERR = 2
               GOTO 9999
            ENDIF
         ENDIF
C
C        AJOUT POSSIBLE DE CES 2 POINTS?
         IF( NBSOMM+1 .GE. MXSOMM ) THEN
            NBLGRC(NRERR) = 1
            WRITE(KERR(MXLGER)(1:10),'(I10)') MXSOMM
            KERR(1) = 'MAXIMUM DE SOMMETS ' // KERR(MXLGER)(1:10) //
     %                ' ATTEINT'
            CALL LEREUR
            IERR = 1
            GOTO 9999
         ENDIF
C
         ISIGNE = 1
         DO K=1,2
C
C           AJOUT DU POINT
            NBSOMM = NBSOMM + 1
C           IL PEUT ETRE SUPPRIME CAR NON SUR LA FRONTIERE
            NPSOFR(NBSOMM) = 0
C
C           CALCUL DES XYZ DISTANCE SOUHAITEE DES 2 POINTS
C           SUR LA NORMALE A LA FACE (DESSUS et DESSOUS)
            DO I=1,3
               PTXYZD(I,NBSOMM) = BARY(I) + COORNO(I) * COULIM * ISIGNE
            ENDDO
C
C           REDUCTION DE LA TAILLE IDEALE POUR TENIR COMPTE DE COULIM
            PTXYZD(4,NBSOMM) = ( BARY(4) + COULIM ) * 0.5D0
C
            ISIGNE = -ISIGNE
C
         ENDDO
C
 10   CONTINUE
C
C     CREATION DE 2 POINTS UN DE CHAQUE COTE DES FACES LEFACO
C     SUR LA NORMALE MOYENNE AUX SOMMETS DES FACES LEFACO
      DO 50 NS=1,NBSOM0
C
C        NS EST IL UN SOMMET LEFACO?
         IF( MCN(MNNBFS-1+NS) .LE. 0 ) GOTO 50
C
C        AJOUT DE 2 POINTS DE CHAQUE COTE DE LA NORMALE MOYENNE
         IF( NBSOMM+1 .GE. MXSOMM ) THEN
            NBLGRC(NRERR) = 1
            WRITE(KERR(MXLGER)(1:10),'(I10)') MXSOMM
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'vdptnf: MAXIMUM DE SOMMETS '
     %                   // KERR(MXLGER)(1:10) // ' ATTEINT'
            ELSE
               KERR(1) = 'vdptnf: MAXIMUM of VERTICES '
     %                   // KERR(MXLGER)(1:10) // ' ATTAINED'
            ENDIF
            CALL LEREUR
            IERR = 1
            GOTO 9999
         ENDIF
C
C        LA NORMALE AU SOMMET NS EST MOYENNEE
         MNX = MNXYZ + 3 * NS
         DO I=1,3
            DMCN( MNX + I ) = DMCN( MNX + I ) / MCN(MNNBFS-1+NS)
         ENDDO
C
C        CALCUL DE LA COUCHE LIMITE SUR LA NORMALE A LA FACE
C        CREATION D'UN POINT DESSUS et UN DESSOUS
         ISIGNE = 1
         DO K=1,2
            NBSOMM = NBSOMM + 1
            NPSOFR(NBSOMM) = 0
            DO I=1,3
               PTXYZD(I,NBSOMM) = PTXYZD(I,NS)
     %                          + DMCN( MNX + I ) * COULIM * ISIGNE
            ENDDO
C
            IF( NOFOTI .GT. 0 ) THEN
C              LES 3 PARAMETRES D'APPEL DE LA FONCTION 'TAILLE_IDEALE'
C              EN CE SOMMET NBSOMM DU REPERE R**3 "NATUREL"
               CALL FONVAL( NOFOTI, 3, PTXYZD(1,NBSOMM), NCODEV,
     %                      PTXYZD(4,NBSOMM) )
               IF( NCODEV .LE. 0 ) THEN
                  IERR = 2
                  GOTO 9999
               ENDIF
            ENDIF
C
C           REDUCTION DE LA TAILLE IDEALE POUR TENIR COMPTE DE COULIM
            PTXYZD(4,NBSOMM) = ( PTXYZD(4,NBSOMM) + COULIM ) * 0.5D0
C
            ISIGNE = -ISIGNE
         ENDDO
C
 50   CONTINUE
      IERR = 0
C
 9999 CALL TNMCDS( 'REEL2',  NBSOM0*3, MNCOSF )
      CALL TNMCDS( 'ENTIER', NBSOM0,   MNNBFS )
C
      WRITE(IMPRIM,*)
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,*) 'vdptnf: Couche limite=',COULIM,
     % ' Ajout de ',NBSOMM-NBSOM0,
     % ' POINTS SUR LA NORMALE MOYENNE AUX SOMMETS DES FACES DU CONTOUR'
      ELSE
        WRITE(IMPRIM,*) 'vdptnf: Boundary Layer=',COULIM, NBSOMM-NBSOM0,
     %   ' POINTS ADDED on MEAN NORMAL VECTOR to BOUNDARY FACE VERTICES'
      ENDIF
      WRITE(IMPRIM,*)
C
      RETURN
      END
