      SUBROUTINE VE1AFET( NOTETR, NS1, NS2, N1FEOC, NFETOI,
     %                    NBFA1AI, NBFA1AM ) 
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LE NOMBRE DE FACES ADJACENTES PAR  L'ARETE NS1->NS2
C -----    PARCOURUES DANS LE SENS NS1->NS2 ET LE SENS INVERSE NS2->NS1
C          PARMI LES FACES SIMPLES NFETOI DES TETRAEDRES DE L'ETOILE

C ENTREES:
C --------
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412

C NS1 NS2: 2 SOMMETS DE L'ARETE
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)

C NFETOI : VERSION 1
C          1: NUMERO DU TETRAEDRE DANS NOTETR
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3  NON UTILISE ICI
C          4: NUMERO DE CETTE FACE DANS LEFACO, 0 SI PAS DANS LEFACO
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C          EN VERSION 2 (NFETOI(3,.)>0)
C          1: NUMERO NOTETR DU TETRAEDRE AU DELA DE LA FACE
C             =0 SI INCONNU
C          2: NUMERO PTXYZD DU 1-ER SOMMET DE LA FACE
C          3: NUMERO PTXYZD DU 2-ME SOMMET DE LA FACE
C          4: NUMERO PTXYZD DU 3-ME SOMMET DE LA FACE
C             S1S2xS1S3 EST LA NORMALE DIRIGEE VERS L'INTERIEUR DE
C             L'ETOILE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C SORTIES:
C --------
C NBFA1AI : NOMBRE DE FACES D'ARETE NS1-NS2 PARCOURUE DANS LE SENS NS2->NS1
C NBFA1AM : NOMBRE DE FACES D'ARETE NS1-NS2 PARCOURUE DANS LE SENS NS1->NS2
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC& St PIERRE DU PERRAY Septembre 2015
C2345X7..............................................................012
      PARAMETER (MXFA1A=128)
      COMMON / TRTETR / STOPTE, TRACTE
      LOGICAL           STOPTE, TRACTE

      INTEGER  NOTETR(8,*), NFETOI(5,*)
      INTEGER  NOFA1A(MXFA1A)
      INTEGER  NOSOFATE(3,4)
      DATA     NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /
C     => LA NORMALE A LA FACE EST ORIENTEE VERS L'EXTERIEUR DU TETRAEDRE

C     NOMBRE DE FACES AYANT CETTE ARETE NS1-NS2 DANS LE SENS NS2->NS1
      NBFA1AI = 0

C     NOMBRE DE FACES AYANT CETTE ARETE NS1-NS2 DANSLE SENS NS1->NS2
      NBFA1AM = 0

C     RECHERCHE DES FACES SIMPLES ADJACENTES PAR NS1-NS2 DANS L'ETOILE
      NTE = 0
      NFT = 0
      NF  = N1FEOC

C     BOUCLE SUR LES FACES CHAINEES DE L'ETOILE
 10   IF( NF .GT. 0 ) THEN

C        SOMMET 3 DE L'ARETE 3 DE LA FACE NF SIMPLE DES TETRAEDRES
         IF( NFETOI(3,NF) .EQ. 0 ) THEN
C           NFETOI VERSION 1
C           NUMERO NOTETR DU TETRAEDRE DE LA FACE SIMPLE
            NTE  = NFETOI( 1, NF )
C           NUMERO DE LA FACE SIMPLE DANS LE TETRAEDRE NTE SI VERSION 1
            NFT  = NFETOI( 2, NF )
            NSS1 = NOTETR( NOSOFATE(3,NFT), NTE )
         ELSE
C           NFETOI VERSION 2
            NSS1 = NFETOI( 4, NF )
         ENDIF

         DO K=1,3

C           SOMMET 2 DE L'ARETE K-1 DE LA FACE NF SIMPLE DES TETRAEDRES
            IF( NFETOI(3,NF) .EQ. 0 ) THEN
C              NFETOI VERSION 1
               NSS2 = NOTETR( NOSOFATE(K,NFT), NTE )
            ELSE
C              NFETOI VERSION 2
               NSS2 = ABS( NFETOI(1+K,NF) )
            ENDIF

C           ARETE K-1 DE LA FACE NF DE SOMMETS NSS1-NSS2
            IF( NSS2 .EQ. NS1 .AND. NSS1 .EQ. NS2 ) THEN

C              L'ARETE EST RETROUVEE UNE FOIS DE PLUS DANS LE SENS INVERSE
               NBFA1AI = NBFA1AI + 1
               GOTO 20

            ELSE IF( NSS1 .EQ. NS1 .AND. NSS2 .EQ. NS2 ) THEN

C              L'ARETE EST RETROUVEE UNE FOIS DE PLUS DANS LE MEME SENS
               NBFA1AM = NBFA1AM + 1
               GOTO 20

            ENDIF

            GOTO 30

 20         IF( NBFA1AI + NBFA1AM .LE. MXFA1A ) THEN
C              STOCKAGE DU NUMERO NF DE LA FACE SIMPLE D'ARETE NS1-NS2
               NOFA1A( NBFA1AI + NBFA1AM ) = NF
            ELSE
               PRINT *,'ve1afet: AUGMENTER MXFA1A=',MXFA1A
            ENDIF

C           PASSAGE A L'ARETE SUIVANTE DE LA FACE NF
 30         NSS1 = NSS2

         ENDDO

C        PASSAGE A LA FACE SUIVANTE DE NF
         NF = NFETOI( 5, NF )
         GOTO 10

      ENDIF

C     NBFA1AI et NBFA1AM SONT DEFINITIFS
      IF( NBFA1AI .NE. NBFA1AM ) THEN
C        ARETE A PROBLEME?
         TRACTE = .TRUE.
         PRINT*
         PRINT*,'ve1afet: ARETE',NS1,'->',NS2,' PARCOURUE dans',
     %           NBFA1AI,' FACES en SENS INVERSE et',
     %           NBFA1AM,' FACES dans le MEME SENS'
         DO K = 1, NBFA1AI+NBFA1AM
            NF = NOFA1A( K )
            PRINT*,'ve1afet: NFETOI( ',NF,')=',(NFETOI(KK,NF),KK=1,5)
         ENDDO
         PRINT*
ccc         CALL AFNFETOI( N1FEOC, NFETOI, NOTETR )
      ENDIF

      RETURN
      END
