      SUBROUTINE VETAFET( NOTETR, N1FEOC, NFETOI, NBFETO, NBARPB ) 
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    VERIFIER QUE TOUTE ARETE DE L'ETOILE APPARTIENT
C -----    SEULEMENT A 2n FACES DE L'ETOILE avec n=1,2

C ENTREES:
C --------
C NOTETR : LISTE DES TETRAEDRES
C          SOMMET1,    SOMMET2,    SOMMET3,    SOMMET4,
C          TETRAEDRE1, TETRAEDRE2, TETRAEDRE3, TETRAEDRE4
C          DE L'AUTRE COTE DE LA FACE
C          1: 123      2: 234      3: 341      4: 412

C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)

C NFETOI : VERSION 1
C          1: NUMERO DU TETRAEDRE DANS NOTETR
C          2: NUMERO LOCAL AU TETRAEDRE DE LA FACE DE L'ETOILE
C             UN SIGNE NEGATIF INDIQUE UN TRAITEMENT EFFECTUE
C          3  NON UTILISE ICI
C          4: NUMERO DE CETTE FACE DANS LEFACO, 0 SI PAS DANS LEFACO
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C          EN VERSION 2 (NFETOI(3,.)>0)
C          1: NUMERO NOTETR DU TETRAEDRE AU DELA DE LA FACE
C             =0 SI INCONNU
C          2: NUMERO PTXYZD DU 1-ER SOMMET DE LA FACE
C          3: NUMERO PTXYZD DU 2-ME SOMMET DE LA FACE
C          4: NUMERO PTXYZD DU 3-ME SOMMET DE LA FACE
C             S1S2xS1S3 EST LA NORMALE DIRIGEE VERS L'INTERIEUR DE
C             L'ETOILE
C          5: CHAINAGE SUIVANT DES FACES OCCUPEES ET VIDES

C SORTIES:
C --------
C NBFETO : NOMBRE DE FACES DE L'ETOILE
C NBARPB : NOMBRE D'ARETES DES FACES DE L'ETOILE N'APPARTENANT PAS A
C          2 ET SEULEMENT 2 FACES DE L'ETOILE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC Paris et Villard de Lans  Aout 2015
C2345X7..............................................................012
      INTEGER  NOTETR(8,*)
      INTEGER  NFETOI(5,*)
      INTEGER  NOSOFATE(3,4)
      DATA     NOSOFATE / 1,3,2,  2,3,4,  3,1,4,  4,1,2 /
C     => LA NORMALE A LA FACE EST ORIENTEE VERS L'EXTERIEUR DU TETRAEDRE

C     PREMIERE FACE DE L'ETOILE
      NBFETO = 0

C     NOMBRE D'ARETES A PROBLEME
      NBARPB = 0

C     PREMIERE FACE DE L'ETOILE
      NTE = 0
      NFT = 0
      NF1 = N1FEOC

 20   IF( NF1 .GT. 0 ) THEN

C        UNE FACE DE L'ETOILE DE PLUS
         NBFETO = NBFETO + 1

C        LE SENS DE PARCOURS DES ARETES DE LA FACE NF1
C        DOIT ETRE EN SENS INVERSE DE CELUI DE L'ARETE
C        DE LEUR FACE ADJACENTE POUR RESPECTER LE SENS DE LA NORMALE
C        ET GENERER DES TETRAEDRES DE VOLUME POSITIF

         IF( NFETOI(3,NF1) .EQ. 0 ) THEN
C           NFETOI VERSION 1
C           NUMERO NOTETR DU TETRAEDRE DE LA FACE SIMPLE
            NTE = NFETOI( 1, NF1 )
C           NUMERO DE LA FACE SIMPLE DANS LE TETRAEDRE NTE SI VERSION 1
            NFT = NFETOI( 2, NF1 )
            NS1 = NOTETR( NOSOFATE(3,NFT), NTE )
         ELSE
C           NFETOI VERSION 2
            NS1 = NFETOI( 4, NF1 )
         ENDIF

         DO L = 1, 3

C           ARETE L de la FACE NF1 de SOMMETS NS1-NS2 
            IF( NFETOI(3,NF1) .EQ. 0 ) THEN
C              NFETOI VERSION 1
               NS2 = NOTETR( NOSOFATE(L,NFT), NTE )
            ELSE
C              NFETOI VERSION 2
               NS2 = ABS( NFETOI(1+L,NF1) )
            ENDIF

C           RECHERCHE DE LA FACE ADJACENTE PAR NS1-NS2 DANS L'ETOILE
            CALL VE1AFET( NOTETR,  NS1, NS2, N1FEOC, NFETOI,
     %                    NBFA1AI, NBFA1AM ) 
C           NBFA1AI NB DE FACES AYANT CETTE ARETE NS1-NS2 DANS LE SENS INVERSE
C           NBFA1AM NB DE FACES AYANT CETTE ARETE NS1-NS2 DANS LE MEME SENS

            IF( NBFA1AM .NE. NBFA1AI ) THEN
C              ARETE A PROBLEME
               NBARPB = NBARPB + 1
               print*,'vetafet: ARETE',NS1,'->',NS2,' de NFETOI(',
     %                 NF1,')=',(NFETOI(KKK,NF1),KKK=1,4),' dans',
     %                 NBFA1AI,' FACES en SENS INVERSE et',
     %                 NBFA1AM,' FACES en le MEME SENS'
            ENDIF

C           ARETE NS1-NS2 DE NF1 NON RETROUVEE DANS LES FACES DE L'ETOILE
C           PASSAGE A L'ARETE SUIVANTE DE LA FACE NF1
            NS1 = NS2

         ENDDO

C        LA FACE SUIVANTE
         NF1 = NFETOI( 5, NF1 )
         GOTO 20

      ENDIF

C     BILAN FINAL
      IF( NBARPB .GT. 0 ) THEN
         PRINT *,'vetafet:',NBARPB,' ARETES A PROBLEME PARMI LES',
     %            NBFETO,' FACES DE L''ETOILE'
         CALL AFETOI( N1FEOC, NFETOI )
      ENDIF

      RETURN
      END
