      SUBROUTINE VIBFCBTE( NBEF, NBNOEF, NUNOTE, NTEBF, NTDLHB, NDDLNO,
     %                     VXYZPN, CBTE, Vit )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCUL DE LA VITESSE Vit( CBTE ) SUR UN TETRAEDRE BREZZI-FORTIN
C -----

C ENTREES:
C --------
C NBEF   : NOMBRE DE TETRAEDRES DU MAILLAGE
C NBNOEF : NOMBRE DE NOEUDS D'UN TETRAEDRE
C NUNOTE : NUMERO DES NBNOEF NOEUDS DES TETRAEDRES
C NTEBF  : NO NUNOTE DU TETRAEDRE BREZZI-FORTIN de VITESSE A CALCULER
C NTDLHB : NOMBRE TOTAL DE DEGRES DE LIBERTE DE L'OBJET HORS BARYCENTRES
C          (NDIM+1) NBNOHB (SOMMETS SANS les BARYCENTRES)
C NDDLNO : TABLEAU DES POINTEURS SUR LE DERNIER DL DE CHAQUE NOEUD FLUIDE
C          CE TABLEAU EST DIMENSIONNE 0:NBNOEU
C VXYZPN : VECTEUR GLOBAL des DL VITESSES-PRESSIONS (1:NTDLHB) AUX NOEUDS
C          SUIVI DES 3 VITESSES AU BARYCENTRE DES TETRAEDRES
C CBTE   : 4 COORDONNEES BARYCENTRIQUES SUR NTEBF DU POINT DE VITESSE A CALCULER

C SORTIE :
C --------
C Vit    : 3 COMPOSANTES DE LA VITESSE AU POINT CBTE de NTEBF
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Saint Pierre du Perray           Octobre 2020
C23456---------------------------------------------------------------012
      INTEGER            NBEF, NBNOEF, NUNOTE(NBEF,NBNOEF), NTEBF,
     %                   NTDLHB,  NDDLNO(0:*)
      DOUBLE PRECISION   VXYZPN(1:*), CBTE(4), Vit(3), BULLE, PRCBL(5)

C     INTERPOLATION de la VITESSE Vit( tn, XYZ1 ) dans le TETRAEDRE Brezzi-Fortin
C     CALCUL DES POLYNOMES LAGRANGE DE DEGRE 1 + BULLE P4 sur TETRAEDRE UNITE
      BULLE = 64D0 * CBTE(1) * CBTE(2) * CBTE(3) * CBTE(4)
      PRCBL(1) = CBTE(1) - BULLE
      PRCBL(2) = CBTE(2) - BULLE
      PRCBL(3) = CBTE(3) - BULLE
      PRCBL(4) = CBTE(4) - BULLE
      PRCBL(5) = 4D0 * BULLE

C     CALCUL DE LA VITESSE Vit( CBTE ) dans l'EF NTEBF
      Vit(1) = 0D0
      Vit(2) = 0D0
      Vit(3) = 0D0

      DO I=1,4
C        NO DU DL I DANS L'EF NTEBF DE LA VITESSE-PRESSION AUX NOEUDS
         NDL = NDDLNO( NUNOTE(NTEBF,I) - 1 )
         Vit(1) = Vit(1) + PRCBL(I) * VXYZPN( NDL+1 )
         Vit(2) = Vit(2) + PRCBL(I) * VXYZPN( NDL+2 )
         Vit(3) = Vit(3) + PRCBL(I) * VXYZPN( NDL+3 )
      ENDDO

C     LE NO DU DERNIER DL VITESSE DU BARYCENTRE DU TETRAEDRE NTEBF
      NDL = NTDLHB + 3 * NTEBF
      Vit(1) = Vit(1) + PRCBL(5) * VXYZPN( NDL-2 )
      Vit(2) = Vit(2) + PRCBL(5) * VXYZPN( NDL-1 )
      Vit(3) = Vit(3) + PRCBL(5) * VXYZPN( NDL   )

      RETURN
      END
