      SUBROUTINE VOEX09( NUVOLU, NTLXVL, LADEFI, RADEFI,
     %                   NTCUPA, MNCUPA, NTSOMM, MNSOMM, IERR )
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : GENERER LES TETRAEDRES DU VOLUME NUVOLU (CODE DEFINITION TYPE 9)
C ----- PARTITION DE VOLUMES DE TYPE 8 A TETRAEDRISER EN UNE FOIS

C ENTREES:
C --------
C NUVOLU : NUMERO DU VOLUME PARTITION DANS LE LEXIQUE DES VOLUMES
C NTLXVL : NUMERO DU TABLEAU TS DU LEXIQUE DU VOLUME PARTITION
C LADEFI : TABLEAU DE DEFINITION DU VOLUME PARTITIONNE
C          CF '~/td/d/a_volume__definition'
C RADEFI : MEME TABLEAU DECLARE REEL

C SORTIES:
C --------
C NTCUPA : NUMERO DU TS DES NUMEROS DES CUBES DU VOLUME PARTITION
C MNCUPA : ADRESSE MCN DU TABLEAU DES NUMEROS DES NO SOMMET DU VOLUME
C          CF '~/td/d/a___nsef'
C NTSOMM : NUMERO DU TABLEAU TS DES SOMMETS DE LA PARTITION
C MNSOMM : ADRESSE MCN   DU TABLEAU SOMMETS DE LA PARTITION
C          CF '~/td/d/a___xyzsommet'
C IERR   : 0  SI PAS D'ERREUR,  >0 SI ERREUR DETECTEE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1992
C MODIFS : ALAIN PERRONNET LJLL UPMC & VEULETTES SUR MER  SEPTEMBRE 2014
C MODIFS : ALAIN PERRONNET LJLL UPMC & St PIERRE DU PERRAY     MARS 2016
C MODIFS : ALAIN PERRONNET Saint PIERRE DU PERRAY           OCTOBRE 2018
C MODIFS : ALAIN PERRONNET Saint PIERRE DU PERRAY         SEPTEMBRE 2019
C2345X7..............................................................012
C     QTEAME: QUALITE DES TETRAEDRES AU DESSOUS DE LAQUELLE UNE
C             AMELIORATION DE LA QUALITE DES TETRAEDRES EST DEMANDEE
ccc      PARAMETER        (QTEAME=0.001)  9/9/17
ccc      PARAMETER        (QTEAME=0.01 ) 13/10/17
ccc      PARAMETER        (QTEAME=0.02 )  3/12/18
ccc      PARAMETER        (QTEAME=0.05)
      PARAMETER        (QTEAME=0.08)

C    QUAMINEX: QUALITE MINIMALE EXIGEE POUR CREER UN TETRAEDRE
C              C-A-D AU DESSOUS DE LAQUELLE UN TETRAEDRE N'EST PAS CREE
ccc      PARAMETER        (QUAMINEX=0.001)   2020/02/05
      PARAMETER        (QUAMINEX=0.005)

      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      COMMON / EPSSSS / EPZERO, EPSXYZ

      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/a_surface__definition.inc"
      include"./incl/a_volume__definition.inc"
      include"./incl/a___nsef.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___materiaux.inc"
      include"./incl/xyzext.inc"
      include"./incl/darete.inc"
      include"./incl/trvari.inc"

      COMMON / TRTETR / STOPTE,TRACTE
      LOGICAL           STOPTE,TRACTE,TRACTE0

      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))

cccC     DEFINITION DE LA COUCHE LIMITE
ccc      DOUBLE PRECISION  COULIM

C     FORMULES : TETRAEDRES + ARETES + NB_FRONTIERES = FACES + SOMMETS
C     ========== 4*TETRAEDRES = FACES_FRONTALIERES + 2*FACES_INTERNES
C                ASYMPTOTIQUEMENT  FACES = 2 * TETRAEDRES

      CHARACTER*80      KINFO
      CHARACTER*24      KNMVOL
      INTEGER           LADEFI(0:*)
      REAL              RADEFI(0:*)
      REAL              HEXAVOLU(6,2)
      REAL              QUAMIN, QUAMOY
      INTEGER           NUFACE(16), NOSOCU(1:8)
      EQUIVALENCE     ( NUFACE(1), NOSOCU(1) )
      INTEGER           NBIPAV(3)
      DOUBLE PRECISION  HEXAPAVE(3,2), ECHPAV(3)
      DOUBLE PRECISION  DINFO, VOLUMT, VOLMOY, CPU, CPUT, TAID

      DOUBLE PRECISION, allocatable, dimension(:,:) :: PTXYZD
      INTEGER, allocatable, dimension(:,:) ::  LARBRO, LARBRT, LARETE,
     %                                         NOTETR
      INTEGER, allocatable, dimension(:)   ::  CHATVO


C     STOPTE = FAUX ==> PAS D'ARRET APRES LE TRACE DE CHAQUE TETRAEDRE
C              VRAI ==> DEMANDE D'UN CARACTERE POUR REDEMARRER
ccc   STOPTE = .FALSE.

C     TRACTE = FAUX ==> PAS DE TRACE DES TETRAEDRES
C              VRAI ==> TRACE DES TETRAEDRES DE L'ETOILE
      TRACTE  = .FALSE.
      TRACTE0 = TRACTE

C     NOM DU VOLUME DE NUMERO NUVOLU DANS LE LEXIQUE DES VOLUMES
      CALL NMOBNU( 'VOLUME', NUVOLU, KNMVOL )
      PRINT*
      PRINT*,'voex09: Debut de la TETRAEDRISATION du VOLUME ',KNMVOL

C     INITIALISATION DU TEMPS CPU
C     ---------------------------
      CPU  = DINFO( 'DELTA CPU' )
      CPUT = 0D0

C     AU DEPART PAS DE TABLEAU NVOLTE
      IVOLTE = 0
      IERAOALLOC = 1
      IERATALLOC = 1
      IERZDALLOC = 1
      IERTEALLOC = 1
      IERCHALLOC = 1
      IERARELLOC = 1
C
C     EXISTENCE OU NON DE LA FONCTION 'TAILLE_IDEALE'
C     -----------------------------------------------
      NOFOTI = NOFOTIEL()
      IF( LANGAG .EQ. 0 ) THEN
         IF( NOFOTI .GT. 0 ) THEN
C           LA FONCTION TAILLE_IDEALE(X,Y,Z) EXISTE
            WRITE(IMPRIM,10000) 'AVEC'
         ELSE
C           LA FONCTION TAILLE_IDEALE(X,Y,Z) N'EXISTE PAS
            WRITE(IMPRIM,10000) 'SANS'
         ENDIF
      ELSE
         IF( NOFOTI .GT. 0 ) THEN
C           LA FONCTION EDGE_LENGTH(X,Y,Z) EXISTE
            WRITE(IMPRIM,20000) '  WITH '
         ELSE
C           LA FONCTION EDGE_LENGTH(X,Y,Z) N'EXISTE PAS
            WRITE(IMPRIM,20000) 'WITHOUT'
         ENDIF
      ENDIF
10000 FORMAT(' voex09: TETRAEDRISATION ',A4,
     %       ' FONCTION TAILLE_IDEALE(X,Y,Z) (ou EDGE_LENGTH(X,Y,Z))' )
20000 FORMAT(' voex09: TETRAHEDRISATION ',A7,
     %       ' FUNCTION EDGE_LENGTH(X,Y,Z) (or TAILLE_IDEALE(X,Y,Z))' )

C     ADRESSE DU LEXIQUE DES SURFACES
      CALL TAMSOU( NTSURF, MNSURF )

C     ADRESSE DU LEXIQUE DES VOLUMES
      CALL TAMSOU( NTVOLU, MNVOLU )

C     AU DEBUT PAS D'ERREUR
      IERR = 0

C     LA PARTITION EST FORMEE DE NBVOPA VOLUMES
      NBVOPA = LADEFI( WBVOPA )

C     LE MAXIMUM DE SOMMETS A GENERER
      MXSOMM = LADEFI( WXSOVO )

C     LONGUEUR DE L'ARETE DE LA GRILLE REGULIERE
C     ------------------------------------------
      ARETGR = ABS( RADEFI( WRETGR ) )
      DARETE = ARETGR

C     ANGLE DE COPLANEARITE ENTRE FACES DE TETRAEDRES
C     -----------------------------------------------
      ANEN2P = RADEFI( WNEN2P )
      ANEN2P = MAX( ANEN2P, 0.0 )
      ANEN2P = MIN( ANEN2P, 45. )
      COANPL = COS( ANEN2P / 45.0 * ATAN(1.0) )

C     COANPL: SEUIL DU COSINUS DE L'ANGLE FORME PAR LES NORMALES AUX
C             2 FACES ET AU DESSUS DUQUEL LES FACES SONT CONSIDEREES
C             COPLANAIRES
C              ( 0.95     => 18.2  DEGRES )
C              ( 0.96     => 16.3  DEGRES )
C              ( 0.97     => 14.1  DEGRES )
C              ( 0.98     => 11.5  DEGRES )
C              ( 0.99     =>  8.11 DEGRES )
C              ( 0.9962   =>  5    DEGRES )
C              ( 0.99756  =>  4    DEGRES )
C              ( 0.99863  =>  3    DEGRES )
C              ( 0.999    =>  2.56 DEGRES )
C              ( 0.9999   =>  0.8  DEGRES )

      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10001) ANEN2P, ARETGR
      ELSE
         WRITE(IMPRIM,20001) ANEN2P, ARETGR
      ENDIF
10001 FORMAT(' voex09: ANGLE en DEGRES de COPLANEARITE de 2 FACES =',
     %         F8.2/
     %       ' voex09: LONGUEUR de l''ARETE de la GRILLE REGULIERE =',
     %         G14.6)
20001 FORMAT(' voex09: 2 FACES COPLANEARITY ANGLE DEGREES =',F8.2 /
     %       ' voex09: REGULAR  GRID  EDGE  LENGTH        =',G14.6)

C     LE NOMBRE DE POINTS INTERNES AU VOLUME DEFINIS PAR L'UTILISATEUR
      NBPTIV = LADEFI( WBPTIV )
      NBTETR = 0
      NUDTETR= 0

C     LE NOMBRE DE FACES PERDUES DES INTERFACES ET DE LA FRONTIERE
      NBFAPE0= 0
      NBFAPE = 0
      MXFAPE = 0

C     NOMBRE DE SOMMETS ET POINTS INTERNES DES SURFACES DU VOLUME
C     PARTITIONE AVANT IDENTIFICATION
      NBSOCO = NBPTIV

C     PROTECTION POUR LES DESTRUCTIONS DE TABLEAUX APRES ERREUR
      MNTETS = 0
      MNSOFR = 0
      MNFACO = 0
      MNFASC = 0
      MNLIPO = 0
      MNTETO = 0
      MNARCF = 0
      MNFETO = 0
      MNF1VO = 0
      MNFRIN = 0
      MX3T2T = 0
      MN3T2T = 0
      MNPILL = 0
      MNOTPT = 0
      MNFAPE = 0
      MNTE1S = 0
      MNTRCF = 0
      MNSTIS = 0
      MNOPTSUIV=0
      MN1SPAVE=0

C     RECHERCHE DES COORDONNEES HEXAVOLU DE L'HEXAEDRE ENGLOBANT
C     LES TRIANGULATIONS DES SURFACES DES VOLUMES DE TYPE 8 DU
C     VOLUME DE TYPE 9 A TETRAEDRISER ICI
C     ==========================================================
      CALL OBVOMIMX( KNMVOL, LADEFI, HEXAVOLU, NBSOCO, NBFACO, IERR )
      CALL TRTATA( HEXAVOLU, COOEXT, 12 )

      IF( IERR .NE. 0 ) GOTO 9999

C     MAJORATION DU NOMBRE DE SOMMETS FACES TETRAEDRES
C     ================================================
C     LE NOMBRE MAXIMAL DE SOMMETS DECLARABLES
      MXSOMM = MAX( MXSOMM, NBSOCO*3, 100 000 )
C     MAJORATION DU NOMBRE DE TETRAEDRES SELON LE MAXIMUM DE SOMMETS
      MXTETR = 5 * MXSOMM
C     MAJORATION DU NOMBRE DE FACES DES SURFACES CONTOUR DU VOLUME
      IF( NBFACO .LT. 1000 ) THEN
         MXFACO = NBFACO * 4 + 256
      ELSE IF( NBFACO .LT. 5000 ) THEN
         MXFACO = NBFACO * 2
      ELSE
         MXFACO = ( NBFACO * 3 ) / 2
      ENDIF

C     MAJORATION DU NOMBRE DES OT OCTAEDRES
C     =====================================
CCC      MXARBO = MIN( 16 * MXFACO + MXSOMM/32 + 10 000, 250 000 )
CCC      MXARBO = 16 * MXFACO + MXSOMM/32 + 10 000   17/09/2014
CCC      MXARBO = 16 * MXFACO + MXSOMM    + 10 000   12/09/2019
      MXARBO = 32 * MXFACO + MXSOMM + 10 000
      MXARBO = MAX( MXARBO, 100 000 )

C     MAJORATION DU NOMBRE DES TETRAEDRES
C     =====================================
      MXARBT = 2 * MXARBO

C     IMPRESSIONS DE CES MAJORATIONS
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10010) MXSOMM,MXTETR,NBFACO,MXARBO,MXARBT
      ELSE
         WRITE(IMPRIM,20010) MXSOMM,MXTETR,NBFACO,MXARBO,MXARBT
      ENDIF
10010 FORMAT(/
     %' MAX SOMMETS        =',I9/
     %' MAX TETRAEDRES     =',I9/
     %' TRIANGLES INITIAUX =',I9/
     %' MAX OT OCTAEDRES   =',I9/
     %' MAX OT TETRAEDRES  =',I9)
20010 FORMAT(/
     %' VERTICES   MAXIMUM =',I9/
     %' TETRAHEDRA MAXIMUM =',I9/
     %' INITIAL TRIANGLES  =',I9/
     %' MAX OT OCTAHEDRA   =',I9/
     %' MAX OT TETRAHEDRA  =',I9)

C     ALLOCATION FORTRAN 90 du tableau PTXYZD(4,MXSOMM)
      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'DEMANDE ALLOCATION de',4*MXSOMM,
     %                ' DOUBLE PRECISION pour PtXYZd'
         ALLOCATE ( PTXYZD( 1:4, 1:MXSOMM ), STAT=IERZDALLOC )
         IF( IERZDALLOC .NE. 0 ) THEN
            PRINT*,'ERREUR ALLOCATION des',4*MXSOMM,
     %                ' DOUBLE PRECISION pour PtXYZd'
            IERR = IERZDALLOC
            GOTO 9900
         ENDIF
         PRINT*,'CORRECTE ALLOCATION de PtXYZD(1:4,1:',MXSOMM,
     %                ') DOUBLE PRECISION'
      ELSE
         PRINT*,'ALLOCATION DEMAND  of',4*MXSOMM,
     %                ' DOUBLE PRECISION of PtXYZd'
         ALLOCATE ( PTXYZD( 1:4, 1:MXSOMM ), STAT=IERZDALLOC )
         IF( IERZDALLOC .NE. 0 ) THEN
            PRINT*,'ALLOCATION ERROR   of',4*MXSOMM,
     %                ' DOUBLE PRECISION of PtXYZd'
            IERR = IERZDALLOC
            GOTO 9900
         ENDIF
         PRINT*,'ALLOCATION CORRECT of PtXYZD(1:4,1:',MXSOMM,
     %                ') DOUBLE PRECISION'
      ENDIF

C     GENERATION DES 6 SOMMETS DE L'OCTAEDRE RACINE
C     CONSTRUCTION DES XYZ DE L'HEXAEDRE ENGLOBANT LE VOLUME
C     ======================================================
      CALL OTRACINE( KNMVOL, ARETGR, MXSOMM, HEXAVOLU,
     %               NBSOMM, PTXYZD, ARETOCG, IERR )
C     EN SORTIE NBSOMM=6 les 6 SOMMETS de l'OCTAEDRE ENGLOBANT
      IF( IERR .GT. 0 ) GOTO 9900

C     RESERVATION DES TABLEAUX LES PETITS D'ABORD ET DANS UN ORDRE
C     FONCTION DES DESTRUCTIONS POUR EVITER L'EMIETTEMENT
C     ============================================================
C     RESERVATION DE LA PILE DES OT
      MXPILL = 4096
      MNPILL = -1
      CALL TNMCDC( 'ENTIER', MXPILL, MNPILL )
      IF( MNPILL .LE. 0 ) GOTO 9995

C     RESERVATION DU TABLEAU NPSOFR POUR RETOURNER AUX COORDONNEES INITIALES
C     NPSOFR(I) =  0 SI POINT AJOUTE NON SUR LA SURFACE DE L'OBJET
C               =  1 SI LE POINT EST AJOUTE SUR UNE ARETE DE LA SURFACE
C               =  2 SI LE POINT EST AJOUTE COMME BARYCENTRE SUR LA SURFACE
C               =  1 000 000  + NUMERO DU POINT INTERNE UTILISATEUR
C               = (1 000 000) * (NO SURFACE + 1) + NUMERO DU SOMMET DANS
C                              LA NUMEROTATION DES SOMMETS DE LA SURFACE
C               = -4 SI LE POINT EST SOMMET D'OT NON TROP PROCHE PT OU FACE
C               = -1 SI LE POINT EST SOMMET D'OT TROP PROCHE PT OU FACE
C               = -3 SI LE POINT EST SOMMET D'OT REFUSE DANS LA TETRAEDRISATION
C               = -NPSOFR(I) SI POINT DEPLACE SUR LA SURFACE
C     DANS LEUR SURFACE FERMEE INITIALE ou NO DE POINT INTERNE
      MNSOFR = -1
      CALL TNMCDC( 'ENTIER', MXSOMM, MNSOFR )
      IF( MNSOFR .LE. 0 ) GOTO 9995

C     MCN(MNLIPO) ( 1+MXSOMM ) NO DU POINT AVANT ET APRES TRI
      MNLIPO = -1
      CALL TNMCDC( 'ENTIER', 1+MXSOMM, MNLIPO )
      IF( MNLIPO .LE. 0 ) GOTO 9995

C     RESERVATION DU TABLEAU LEFACO :
C     3 SOMMETS, 2 VOLUMES D'APPARTENANCE ET FACES VOISINES PAR LES 3 ARETES
      MNFACO = -1
      CALL TNMCDC( 'ENTIER', 11*MXFACO+11, MNFACO )
      IF( MNFACO .LE. 0 ) GOTO 9995

C     RESERVATION DU TABLEAU :  NO 1 FACE DANS LEFACO D'UN SOMMET
      MNFASC = -1
      CALL TNMCDC( 'ENTIER', MXSOMM, MNFASC )
      IF( MNFASC .LE. 0 ) GOTO 9995
      CALL AZEROI( MXSOMM, MCN(MNFASC) )

C     RESERVATION DU TABLEAU :  LAPILE(2,MXPILE) PILE AUXILIAIRE
      MXPILE = 9192
      MNPILE = -1
      CALL TNMCDC( 'ENTIER', 2*MXPILE, MNPILE )
      IF( MNPILE .LE. 0 ) GOTO 9995

C     RESERVATION DU TABLEAU DU NUMERO D'UN OT CONTENANT CHAQUE SOMMET
C     SI SOMMET d'OT => UN SEUL PARMI PLUSIEURS OT
C     SI POINT       => UN SEUL PARMI CEUX LE CONTENANT
C                       (LE POINT PEUT ETRE SUR UNE ARETE OU FACE)
      MNOTPT = -1
      CALL TNMCDC( 'ENTIER', MXSOMM, MNOTPT )
      IF( MNOTPT .LE. 0 ) GOTO 9995

C     ALLOCATION FORTRAN 90 de l'ARBRE LARBRO des OCTAEDRES
C     -----------------------------------------------------
C     LARBRO : ARBRE-14 DES OCTAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRO(0,0) : NO DU 1-ER OCTAEDRE VIDE DANS LARBRO
C      LARBRO(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRO (ICI -1:20)
C      LARBRO(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRO
C                    (ICI = MXARBO)
C      LARBRO(-1:20,1) : RACINE DE L'ARBRE (OCTAEDRE SANS PERE)
C      LARBRO(-1,J) : NO DU PERE DE L'OCTAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRO(0,J)  : 1 A 14 NO DE FILS DE L'OCTAEDRE J POUR SON PERE
C                     + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C     SI LARBRO(0,J)>0 ALORS J EST UN OCTAEDRE OCCUPE
C      SI LARBRO(1,.)>0 ALORS
C         LARBRO(1:14,J): NO (>0) LARBRO DES 14 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRO(1:14,J):-NO PTXYZD DES 0 A 14 POINTS INTERNES DE L'OCTA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DE L'ARBRE )
C
C      LARBRO(15:20,J) : NO PTXYZD DES 6 SOMMETS DE L'OCTAEDRE J
C     SINON
C      LARBRO(0,J): -ADRESSE DANS LARBRO DE L'OCTAEDRE VIDE SUIVANT
      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'DEMANDE ALLOCATION de',22*(MXARBO+1),
     %                ' ENTIERS pour l arbre des OCTAEDRES'
         ALLOCATE ( LARBRO(-1:20, 0:MXARBO), STAT=IERAOALLOC )
         IF( IERAOALLOC .NE. 0 ) THEN
            PRINT*,'ERREUR ALLOCATION de',22*(MXARBO+1),
     %               ' ENTIERS pour l arbre des OCTAEDRES'
            IERR = IERAOALLOC
            GOTO 9900
         ENDIF
         PRINT*,'CORRECTE ALLOCATION de (-1:20, 0:',MXARBO,
     %                ') ENTIERS pour l arbre des OCTAEDRES'
        ELSE
         PRINT*,'ALLOCATION DEMAND  of',22*(MXARBO+1),
     %                ' INTEGER of the OCTAHEDRA TREE'
         ALLOCATE ( LARBRO(-1:20, 0:MXARBO), STAT=IERAOALLOC )
         IF( IERAOALLOC .NE. 0 ) THEN
            PRINT*,'ALLOCATION ERROR   of',22*(MXARBO+1),
     %                ' INTEGER of the OCTAHEDRA TREE'
            IERR = IERAOALLOC
            GOTO 9900
         ENDIF
         PRINT*,'ALLOCATION CORRECT of (-1:20, 0:',MXARBO,
     %                ') INTEGER of the OCTAHEDRA TREE'
      ENDIF

C     ALLOCATION FORTRAN 90 de l'ARBRE LARBRT des TETRAEDRES
C     ------------------------------------------------------
C     LARBRT : ARBRE-5 DES TETRAEDRES ( FOND DE LA TETRAEDRISATION )
C      LARBRT(0,0) : NO DU 1-ER TETRAEDRE VIDE DANS LARBRT
C      LARBRT(1,0) : MAXIMUM DU 1-ER INDICE DE LARBRT (ICI -1:9)
C      LARBRT(2,0) : MAXIMUM DECLARE DU 2-EME INDICE DE LARBRT
C                     (ICI = MXARBT)
C      LARBRT(-1,J) : NO DU PERE DU TETRAEDRE J DANS UN DES 2 ARBRES
C                     >0 => DANS LARBRO
C                     <0 => DANS LARBRT
C      LARBRT(0,J) : 0 A 4 NO DE FILS DU TETRAEDRE J POUR SON PERE
C                    + 100 * NO TYPE DE L'OT J
C                     NO TYPE DE L'OT : 0 SI OCTAEDRE
C                                       1 SI TETRAEDRE T RONDE (T1)
C                                       2 SI TETRAEDRE T       (T2)
C     SI LARBRT(0,J)>0 ALORS J EST UN TETRAEDRE OCCUPE
C      SI LARBRT(1,J)>0 ALORS
C         LARBRT(1:5,J): NO (>0) LARBRT DES 5 SOUS-OCTA-TETRAEDRES
C      SINON
C         LARBRT(1:5,J):-NO PTXYZD DES 0 A 5 POINTS INTERNES AU TETRA J
C                         0  SI PAS DE POINT
C                        ( J EST ALORS UNE FEUILLE DU ARBRE )
C
C      LARBRT(6:9,J) : NO PTXYZD DES 4 SOMMETS DU TETRAEDRE J
C     SINON
C      LARBRT(0,J): ADRESSE DANS LARBRT DU TETRAEDRE VIDE SUIVANT
      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'DEMANDE ALLOCATION de',11*(MXARBT+1),
     %                ' ENTIERS pour l arbre des TETRAEDRES'
         ALLOCATE ( LARBRT(-1:9, 0:MXARBT), STAT=IERATALLOC )
         IF( IERATALLOC .NE. 0 ) THEN
            PRINT*,'ERREUR ALLOCATION de',11*(MXARBT+1),
     %                ' ENTIERS pour l arbre des TETRAEDRES'
            IERR = IERATALLOC
            GOTO 9900
         ENDIF
         PRINT*,'CORRECTE ALLOCATION de(-1:9, 0:',MXARBT,
     %                ') ENTIERS pour l arbre des TETRAEDRES'
      ELSE
         PRINT*,'ALLOCATION DEMAND  of',11*(MXARBT+1),
     %                ' INTEGER of the TETRAHEDRA TREE'
         ALLOCATE ( LARBRT(-1:9, 0:MXARBT), STAT=IERATALLOC )
         IF( IERATALLOC .NE. 0 ) THEN
            PRINT*,'ALLOCATION ERROR   of',11*(MXARBT+1),
     %                ' INTEGER of the TETRAHEDRA TREE'
            IERR = IERATALLOC
            GOTO 9900
         ENDIF
         PRINT*,'ALLOCATION CORRECT of (-1:9, 0:',MXARBT,
     %                ') INTEGER of the TETRAHEDRA TREE'
      ENDIF

C     DECLARATION DES TABLEAUX DES TETRAEDRES
C     ALLOCATION FORTRAN 90 de NOTETR(8,MXTETR) no SOMMETS DES TETRAEDRES
C     et TETRAEDRES VOISINS
C     -------------------------------------------------------------------
      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'DEMANDE ALLOCATION de',8*MXTETR,
     %                ' ENTIERS No DES SOMMETS des TETRAEDRES'
         ALLOCATE ( NOTETR( 1:8, 1:MXTETR ), STAT=IERTEALLOC )
         IF( IERTEALLOC .NE. 0 ) THEN
            PRINT*,'ERREUR ALLOCATION de',8*MXTETR,
     %                ' ENTIERS No DES SOMMETS des TETRAEDRES'
            IERR = IERTEALLOC
            GOTO 9900
         ENDIF
         PRINT*,'CORRECTE ALLOCATION de NOTETR(1:8,1:',MXTETR,
     %                ') ENTIERS No DES SOMMETS des TETRAEDRES'
      ELSE
         PRINT*,'ALLOCATION DEMAND  of',8*MXTETR,
     %                ' INTEGER of TETRAHEDRA VERTICES NUMBER'
         ALLOCATE ( NOTETR( 1:8, 1:MXTETR ), STAT=IERTEALLOC )
         IF( IERTEALLOC .NE. 0 ) THEN
            PRINT*,'ALLOCATION ERROR   of',8*MXTETR,
     %                ' INTEGER of TETRAHEDRA VERTICES NUMBER'
            IERR = IERTEALLOC
            GOTO 9900
         ENDIF
         PRINT*,'ALLOCATION CORRECT of NOTETR(1:8,1:',MXTETR,
     %                ') INTEGER of TETRAHEDRA VERTICES NUMBER'
      ENDIF

C     ALLOCATION FORTRAN 90 du tableau CHATVO
C     LE CHAINAGE DES TETRAEDRES DE CHACUN DES VOLUMES
C     PUIS LE NUMERO DE VOLUME DE 1 A NBVOPA DES TETRAEDRES
C     DE CHACUN DES VOLUMES
C     -----------------------------------------------------
      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'DEMANDE ALLOCATION de',MXTETR,
     %                ' ENTIERS pour CHATVO'
         ALLOCATE ( CHATVO( 1:MXTETR ), STAT=IERCHALLOC )
         IF( IERCHALLOC .NE. 0 ) THEN
            PRINT*,'ERREUR ALLOCATION de',MXTETR,
     %                ' ENTIERS pour CHATVO'
            IERR = IERCHALLOC
            GOTO 9900
         ENDIF
         PRINT*,'CORRECTE ALLOCATION de CHATVO(1:',MXTETR,
     %                ') ENTIERS pour CHATVO'
      ELSE
         PRINT*,'ALLOCATION DEMAND  of',MXTETR,
     %                ' INTEGER of CHATVO'
         ALLOCATE ( CHATVO( 1:MXTETR ), STAT=IERCHALLOC )
         IF( IERCHALLOC .NE. 0 ) THEN
            PRINT*,'ALLOCATION ERROR   of',MXTETR,
     %                ' INTEGER of CHATVO'
            IERR = IERCHALLOC
            GOTO 9900
         ENDIF
         PRINT*,'ALLOCATION CORRECT of CHATVO(1:',MXTETR,
     %                ') INTEGER'
      ENDIF
C     -1 TEMOIN DE NON UTILISATION
C      0 POUR INDIQUER LA FIN DU CHAINAGE
      DO N = 1, MXTETR
         CHATVO( N ) = -1
      ENDDO

C     MCN(MNTETS) ( MXSOMM )  NO 1 TETRAEDRE DE CHAQUE SOMMET
      MNTETS = -1
      CALL TNMCDC( 'ENTIER', MXSOMM, MNTETS )
      IF( MNTETS .LE. 0 ) GOTO 9995
      CALL AZEROI( MXSOMM, MCN(MNTETS) )

C     INITIALISATION DES 2 ARBRES des OT
C     ==================================
      CALL OTARBINI( MXARBO, MXARBT,
     %               LARBRO, LARBRT, MXSOMM, MCN(MNOTPT) )

C     ALLOCATION FORTRAN 90 du tableau LARETE
C     RESERVATION DU TABLEAU DES ARETES DES OT
C     ----------------------------------------
C     UNE ARETE D'OT APPARTIENT A AU PLUS 4 OT
      MXARET = ( 12 * MXARBO + 6 * MXARBT ) / 4 + 18
      PRINT*
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'DEMANDE ALLOCATION de',4*MXARET,
     %          ' ENTIERS pour LARETE'
         ALLOCATE ( LARETE( 1:4, 1:MXARET ), STAT=IERARELLOC )
         IF( IERARELLOC .NE. 0 ) THEN
            PRINT*,'ERREUR ALLOCATION de',4*MXARET,
     %             ' ENTIERS pour LARETE'
            IERR = IERARELLOC
            GOTO 9900
         ENDIF
         PRINT*,'CORRECTE ALLOCATION de LARETE(1:4,1:',MXARET,
     %          ') ENTIERS pour LARETE'
      ELSE
         PRINT*,'ALLOCATION DEMAND  of',4*MXARET,
     %          ' INTEGER of LARETE'
         ALLOCATE ( LARETE( 1:4, 1:MXARET ), STAT=IERARELLOC )
         IF( IERARELLOC .NE. 0 ) THEN
            PRINT*,'ALLOCATION ERROR   of',4*MXARET,
     %             ' INTEGER of LARETE'
            IERR = IERARELLOC
            GOTO 9900
         ENDIF
         PRINT*,'ALLOCATION CORRECT of LARETE(1:4,1:',MXARET,') INTEGER'
      ENDIF

C     INITIALISATION DU HACHAGE DES ARETES DES OT
      CALL AZEROI( 4*MXARET, LARETE )
C     LA 1-ERE ARETE LIBRE DERRIERE CELLES ADRESSEES PAR LE MINIMUM
      LAVIDE = MXARET

C     AJOUT DANS LES OT DES POINTS INTERNES IMPOSES PAR L'UTILISATEUR
C     AVEC  LA DISTANCE SOUHAITEE AUTOUR
C     ===============================================================
C     PAR DEFAUT, LES SOMMETS D'OT NE SONT PAS SUR L'OBJET
      DO I=MNSOFR,MNSOFR+MXSOMM-1
C        POINT NON SUR LA SURFACE DE L'OBJET
         MCN( I ) = -4
      ENDDO
C     NUPRPTSF : NUMERO DU PREMIER POINT INTERNE OU FRONTALIER DANS PTXYZD
      NUPRPTSF = NBSOMM+1
      CALL OTAJPI( HEXAVOLU, NBPTIV, LADEFI(WUVOPA+NBVOPA),
     %             RADEFI(WUVOPA+NBVOPA+NBPTIV),
     %             NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
     %             MXARBO, LARBRO, MXARBT, LARBRT,
     %             MCN(MNOTPT),
     %             LAVIDE, MXARET, LARETE, IERR )
      IF( IERR .NE. 0 ) GOTO 9900


C     AJOUT DES SOMMETS DES FACES DE LA TRIANGULATION DES SURFACES FERMEES
C     ====================================================================
C     RESERVATION DU TABLEAU DES ARETES DE LEFACO
      MXAREF = (NBFACO * 3) / 2 + 128
      MNAREF = -1
      CALL TNMCDC('ENTIER', MXAREF*4, MNAREF )
      IF( MNAREF .LE. 0 ) GOTO 9995
      INFACO = 1
      CALL OTAJSF( NUVOLU, KNMVOL, HEXAVOLU, NBVOPA, LADEFI(WUVOPA),
     %             NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
     %             MXARBO, LARBRO, MXARBT, LARBRT, MCN(MNOTPT),
     %             LAVIDE, MXARET, LARETE,
     %             NBFACO, MXFACO, MCN(MNFACO), MCN(MNFASC),
     %             MXAREF, MCN(MNAREF),
     %             QTRMIN, QTRMOY, AREMIN, AREMAX, AREMOY,
     %             COSMIN, COSMAX, IERR  )
      CALL TNMCDS('ENTIER', MXAREF*4, MNAREF )

      IF( IERR .NE. 0 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            PRINT*,'voex09: Sortie otajsf avec IERR=',IERR,
     %             ' -> ABANDON du VOLUME ',KNMVOL
         ELSE
            PRINT*,'voex09: otajsf EXIT with ERROR=',IERR,
     %             ' -> the VOLUME ',KNMVOL,' is ABANDONED'
         ENDIF
         GOTO 9900
      ENDIF

C     AJUSTAGE DE ARETGR SI PAS DE TAILLE_IDEALE(X,Y,Z)
C     -------------------------------------------------
      IF( NOFOTI .LE. 0 ) THEN
         IF( ARETGR .GT. AREMAX*1.55 ) ARETGR = AREMAX
         IF( ARETGR .LT. AREMIN ) ARETGR = (AREMIN+AREMAX*2)/3.0
ccc         IF( ARETGR .GT. AREMOY ) ARETGR = AREMOY
      ENDIF
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10020)ARETGR, ARETGR/AREMIN, ARETGR/AREMAX, AREMOY
      ELSE
         WRITE(IMPRIM,20020)ARETGR, ARETGR/AREMIN, ARETGR/AREMAX, AREMOY
      ENDIF
      DARETE = ARETGR

10020 FORMAT(' LONGUEUR ARETE DE LA GRILLE =',G15.6/
     %       ' ARETE GRILLE/ARETE MINIMALE =',F11.2/
     %       ' ARETE GRILLE/ARETE MAXIMALE =',F11.2/
     %       ' ARETE MOYENNE DES SURFACES  =',G15.6/)

20020 FORMAT(' EDGE LENGTH of the GRID =',G15.6/
     %       ' GRID EDGE/MINIMUM EDGE  =',F11.2/
     %       ' GRID EDGE/MAXIMUM EDGE  =',F11.2/
     %       ' MEAN EDGE of SURFACES   =',G15.6/)

C     L'HEXAEDRE DU PAVAGE EST DIMENSIONNE
C     ====================================
      DO K=1,3
         H = ( HEXAVOLU(K,2) - HEXAVOLU(K,1) ) * 0.5 + 1.31 * ARETGR
         D = ( HEXAVOLU(K,1) + HEXAVOLU(K,2) ) * 0.5
         HEXAPAVE(K,1) = DBLE( D - H )
         HEXAPAVE(K,2) = DBLE( D + H )
      ENDDO


C     BILAN EN TEMPS CPU DE LA PREPARATION DES DONNEES
C     ------------------------------------------------
      CPU  = DINFO( 'DELTA CPU' )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11002) NBSOMM, NBFACO, CPU
      ELSE
         WRITE(IMPRIM,21002) NBSOMM, NBFACO, CPU
      ENDIF
11002 FORMAT(' TEMPS CPU de PREPARATION des',I7,' SOMMETS et',
     %       I8,', TRIANGLES =',F11.2,' SECONDES')
21002 FORMAT(' CPU TIME to PREPARE',I7,' VERTICES and',
     %       I8,' TRIANGLES =',F11.2,' SECONDS')
      CPUT = CPUT + CPU



cccC     AJOUT DES 2 POINTS SUR LA NORMALE AUX FACES DU CONTOUR
cccC     ======================================================
cccC     DEFINITION DE LA COUCHE LIMITE
ccc      COULIM = AREMIN / 5D0
ccc      CALL VDPTNF( COULIM, MXSOMM, NBSOMM, PTXYZD, MCN(MNSOFR),
ccc     %             MXFACO, MCN(MNFACO),  IERR )
cccC
ccc      CPU = DINFO( 'DELTA CPU' )
ccc      IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,11003) CPU
ccc      ELSE
ccc         WRITE(IMPRIM,21003) CPU
ccc      ENDIF
ccc11003 FORMAT(/' TEMPS CPU AJOUT FACES FRONTALIERES   =',F11.2,
ccc     %' SECONDES')
ccc21003 FORMAT(/' CPU TIME ADDITION of BOUNDARY TRIANGLES  =',F11.2,
ccc     %' SECONDS')
ccc      CPUT = CPUT + CPU
ccc      IF( IERR .NE. 0 ) GOTO 9900
C
cccC     QTEMIN = QUALITE MINIMALE POUR DIRE QU'UN TETRAEDRE EST SUPPOSE DEGENERE
cccC     C'EST LE DIZIEME DE CELUI DU PLUS MAUVAIS TRIANGLE
ccc      QTEMIN = MIN( QTRMIN * 0.1 , 0.005 )
ccc      PRINT*,'QUALITE DES TETRAEDRES SUPPOSES DEGENERES<',QTEMIN


c     Surveiller que le stockage des arbres N'EXPLOSE...
C     REDUCTION DES OT POUR QUE LA TAILLE DES ARETES DE L'OT SOIT
C     INFERIEURE AU MIN DES DISTANCES SOUHAITEES DE SES SOMMETS
C     ===========================================================
      NBSOMM0 = NBSOMM
      CALL OTARDI( NOFOTI, ARETGR, ARETOCG, HEXAVOLU,
     %             MXARBO, LARBRO, MXARBT, LARBRT, MCN(MNOTPT),
     %             NBSOMM, MXSOMM, PTXYZD,
ccc     %             MCN(MNSOFR),
     %             LAVIDE, MXARET, LARETE, MXPILL, MCN(MNPILL),
     %             IERR )
  
      PRINT*,'voex09: otardi ajoute',NBSOMM-NBSOMM0,' SOMMETS des OT'
C     BILAN EN TEMPS CPU
      CPU = DINFO( 'DELTA CPU' )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11004) CPU
      ELSE
         WRITE(IMPRIM,21004) CPU
      ENDIF
11004 FORMAT(' TEMPS CPU AJUSTAGE DISTANCE SOUHAITEE=',F11.2,
     %' SECONDES')
21004 FORMAT(' CPU TIME to ADJUST WISHED DISTANCES       =',F11.2,
     %' SECONDS')
      CPUT = CPUT + CPU
      IF( IERR .NE. 0 ) GOTO 9900


C     HOMOGENEISATION POUR AU PLUS UN SAUT A TRAVERS CHAQUE FACE DES OT
C     =================================================================
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11014)
      ELSE
         WRITE(IMPRIM,21014)
      ENDIF
11014 FORMAT(' HOMOGENEISATION au PLUS UN SAUT a TRAVERS CHAQUE FACEd''O
     %T')
21014 FORMAT(' HOMOGENEIZATION to NO MORE ONE JUMP THROUGH EVERY OT FACE
     %')
      NBSOMM0 = NBSOMM
      CALL OTHOMO( NOFOTI, ARETGR, ARETOCG, HEXAVOLU,
     %             MXARBO, LARBRO, MXARBT, LARBRT, MCN(MNOTPT),
     %             NBSOMM, MXSOMM, PTXYZD,
     %             MXPILL, MNPILL, LAVIDE, MXARET, LARETE, IERR )
      PRINT*,'voex09: l''HOMOGENEISATION des OT a CREE',NBSOMM-NBSOMM0,
     %       ' SOMMETS des OT'


ccc      IF( IERARELLOC .EQ. 0 ) then
ccc         IF( LANGAG .EQ. 0 ) THEN
ccc            PRINT*,'LARETE est DESALLOUE'
ccc         ELSE
ccc            PRINT*,'LARETE is DESALLOCATED'
ccc         ENDIF
ccc         DEALLOCATE( LARETE )
ccc         IERARELLOC = 1
ccc      ENDIF

C     BILAN EN TEMPS CPU
      CPU = DINFO( 'DELTA CPU' )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11005) CPU
      ELSE
         WRITE(IMPRIM,21005) CPU
      ENDIF
11005 FORMAT(' TEMPS CPU HOMOGENEISATION DES OT =',F11.2,
     %' SECONDES')
21005 FORMAT(' OT HOMOGENEIZATION CPU TIME=',F11.2,
     %' SECONDS')
      CPUT = CPUT + CPU
      IF( IERR .NE. 0 ) GOTO 9900

C     RETRAIT DES SOMMETS D'OT TROP PROCHES D'UN POINT OU FACE LEFACO
C     ===============================================================
      CALL OTPTPROC( NUPRPTSF, NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
     %               MXARBO, LARBRO, MXARBT, LARBRT, MCN(MNOTPT),
     %               MXFACO, MCN(MNFACO),
     %               MXPILL, MNPILL, NBSTSU )

C     BILAN EN TEMPS CPU
C     ------------------
      CPU = DINFO( 'DELTA CPU' )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11006) NBSTSU, CPU, NBSOMM
      ELSE
         WRITE(IMPRIM,21006) NBSTSU, CPU, NBSOMM
      ENDIF
11006 FORMAT(' TEMPS CPU SUPPRESSION',I6,' POINTS TROP PROCHES =',F11.2,
     %' SECONDES  NBSOMM=',I9)
21006 FORMAT(' CPU TIME SUPPRESSION of',I6,' TOO NEAREST POINTS=',F11.2,
     %' SECONDS  NBSOMM=',I9)
      CPUT = CPUT + CPU

C     LES POINTS DE 1 A NBSOMM SONT ICI 
C     LES 6 SOMMETS DE L'OCTAEDRE ENGLOBANT
C     LES POINTS INTERNES IMPOSES PAR L'UTILISATEUR
C     LES SOMMETS DES TRIANGLES DES SURFACES DES VOLUME DE TYPE 8 DU VOLUME
C     LES SOMMETS DES OT FILS CREER LORS DE L'HOMOGENEISATION DES OT

C     TRI DES POINTS POUR FAVORISER LEUR TETRAEDRISATION
C     LES SOMMETS D'OT SONT PLACES EN PREMIER SELON LEUR TAILLE
C     DES OT LES PLUS GRANDS AUX PLUS PETITS
C     =========================================================
      MNTEST = -1
      CALL TNMCDC( 'ENTIER', NBSOMM, MNTEST )
      IF( MNTEST .LE. 0 ) GOTO 9995
      CALL OTTRIPT( NUPRPTSF, NBSOMM, MCN(MNSOFR),
     %              LARBRO, LARBRT, MXPILL, MNPILL,
     %              NBPOIN, MCN(MNLIPO), MCN(MNTEST) )
C     DESTRUCTION DANS MCN DU TABLEAU MNTEST DEVENU INUTILE
      CALL TNMCDS( 'ENTIER', NBSOMM, MNTEST )

C     BILAN EN TEMPS CPU
C     ------------------
      CPU = DINFO( 'DELTA CPU' )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11007) CPU, NBSOMM, NBPOIN
      ELSE
         WRITE(IMPRIM,21007) CPU, NBSOMM, NBPOIN
      ENDIF
11007 FORMAT(' TEMPS CPU DE NUMEROTATION DES POINTS =',F11.2,
     %' SECONDES  NBSOMM=',I9,' NBPOIN=',I9)
21007 FORMAT(' POINTS RENUMBERING CPU TIME =',F11.2,
     %' SECONDS  NBSOMM=',I9,' NBPOIN=',I9)
      CPUT = CPUT + CPU


C     GENERATION DES 4 TETRAEDRES DE L'OCTAEDRE ENGLOBANT A PARTIR DE
C     SES 6 SOMMETS ET DES TETRAEDRES VIDES
C     ===============================================================
      CALL OT4TET( PTXYZD, MXTETR, N1TEVI, NOTETR ,
     %             MCN(MNTETS), NUDTETR, IERR )
      IF( IERR .NE. 0 ) GOTO 9900


C     QUELQUES TABLEAUX et INITIALISATIONS POUR LA TETRAEDRISATION
C     DECLARATION DES PILES SUR L'ETOILE NFETOI ET NTETOI
      MXARCF = MAX( 4096, NBFACO )
      MNARCF = -1
      CALL TNMCDC( 'ENTIER', 4*MXARCF+1, MNARCF )
      IF( MNARCF .LE. 0 ) GOTO 9995

      MXETOI = MAX( 4096, NBFACO )

      MNDSTM = -1
      CALL TNMCDC( 'REEL2',   MXETOI, MNDSTM )
      IF( MNDSTM .LE. 0 ) GOTO 9995

      MNFETO = -1
      CALL TNMCDC( 'ENTIER', 5*MXETOI, MNFETO )
      IF( MNFETO .LE. 0 ) GOTO 9995

      MNTETO = -1
      CALL TNMCDC( 'ENTIER',   MXETOI, MNTETO )
      IF( MNTETO .LE. 0 ) GOTO 9995

      MNAETO = -1
      CALL TNMCDC( 'ENTIER', 4*MXETOI, MNAETO )
      IF( MNAETO .LE. 0 ) GOTO 9995

      MN0FAR = -1
      CALL TNMCDC( 'ENTIER', 3*MXETOI, MN0FAR )
      IF( MN0FAR .LE. 0 ) GOTO 9995

      MXFAPE = MXFACO
      MNFAPE = -1
      CALL TNMCDC( 'ENTIER', MXFAPE, MNFAPE )
      IF( MNFAPE .LE. 0 ) GOTO 9995

      MXTE1S = MAX( 2*NBFACO, 8192 )
      CALL TNMCDC( 'ENTIER', MXTE1S, MNTE1S )
      IF( MNTE1S .LE. 0 ) GOTO 9995

      MXTRCF = MAX( NBFACO, 2048 )
      CALL TNMCDC( 'ENTIER', 2*MXTRCF, MNTRCF )
      IF( MNTRCF .LE. 0 ) GOTO 9995

C     NOMBRE D'IDENTIFICATION D'UN SOMMET DU VOLUME A TETRAEDRISER
      MXSTIS = MXSOMM
      CALL TNMCDC( 'ENTIER', MXSTIS, MNSTIS) 
      IF( MNSTIS .LE. 0 ) GOTO 9995

C     CREATION DE L'HEXAEDRE DU PAVAGE DE L'HEXAEDRE ENGLOBANT
C     TOUS LES SOMMETS DES SURFACES DU VOLUME
C     POUR ACCELERER LA RECHERCHE DU PLUS PROCHE SOMMET D'UN POINT
C     ============================================================
C     CREATION DU PAVAGE ENGLOBANT LE VOLUME
      CALL CREERPAVAGE( ARETGR, HEXAPAVE, NBIPAV, ECHPAV )

C     NOMBRE DE SOMMETS DES CUBES DE L'HEXAEDRE ENGLOBANT
      NBSTPV = (NBIPAV(1)+2) * (NBIPAV(2)+2) * (NBIPAV(3)+2)

C     NOMBRE DE PAVES DE L'HEXAEDRE
      NBPAVE = (NBIPAV(1)+1) * (NBIPAV(2)+1) * (NBIPAV(3)+1)

C     CREATION ET INITIALISATION DU TABLEAU DU PAVAGE
C     POINTEUR SUR UN SOMMET PTXYZD DE CHAQUE PAVE
      CALL TNMCDC( 'ENTIER', NBPAVE, MN1SPAVE )
      CALL AZEROI(  NBPAVE,  MCN(MN1SPAVE) )

      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10002) KNMVOL,((HEXAPAVE(I,J),I=1,3),J=1,2),
     %                       NBSTPV, NBPAVE, ARETGR
      ELSE
         WRITE(IMPRIM,20002) KNMVOL,((HEXAPAVE(I,J),I=1,3),J=1,2),
     %                       NBSTPV, NBPAVE, ARETGR
      ENDIF

10002 FORMAT(/' voex09: VOLUME ',A/
     % ' PAVAGE de l''HEXAEDRE: COORDONNEES MIN-MAX'/
     % ' XMIN=',G15.7,'  YMIN=',G15.7,'  ZMIN=',G15.7 /
     % ' XMAX=',G15.7,'  YMAX=',G15.7,'  ZMAX=',G15.7 /
     % I9,' SOMMETS des',I9,' PAVES de LONGUEUR d''ARETE',G15.7)

20002 FORMAT(/' voex09: VOLUME ',A/
     % ' HEXAHEDRON PAVEMENT: MIN-MAX COORDINATES'/
     % ' XMIN=',G15.7,'  YMIN=',G15.7,'  ZMIN=',G15.7 /
     % ' XMAX=',G15.7,'  YMAX=',G15.7,'  ZMAX=',G15.7 /
     % I9,' VERTICES of',I9,' CUBES of EDGE LENGTH',G15.7)

C     NO DU SOMMET SUIVANT DE CHAQUE SOMMET DANS SON PAVE
      CALL TNMCDC( 'ENTIER', MXSOMM, MNOPTSUIV )
      CALL AZEROI(  MXSOMM,  MCN(MNOPTSUIV) )

ccc      DO NS = 1, NBSOMM
cccC        AJOUT DANS LE PAVAGE DU POINT NS
ccc         IF( MCN(MNTETS-1+NS) .GT. 0 ) THEN
ccc            CALL NUPAVEST( NS, PTXYZD, HEXAPAVE, NBIPAV, ECHPAV,
ccc     %                     MCN(MN1SPAVE), MCN(MNOPTSUIV) )
ccc         ENDIF
ccc      ENDDO


C     BILAN EN TEMPS CPU DE LA PREPARATION DE LA TETRAEDRISATION
C     ----------------------------------------------------------
      CPUT = CPUT + DINFO( 'DELTA CPU' )
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,11008) CPUT
      ELSE
         WRITE(IMPRIM,21008) CPUT
      ENDIF
11008 FORMAT(/' CPU TEMPS TOTAL de PREPARATION TETRAEDRISATION ',F11.2,
     %' SECONDES')
21008 FORMAT(/' CPU TIME TOTAL of TETRAHEDRIZATION PREPARATION ',F11.2,
     %' SECONDS')


C     TETRAEDRISATION DES POINTS NOSOM1=7 A NOSOM2=NBPOIN
C     ---------------------------------------------------
C     LE JEU DES SOMMETS A TRAITER DU POINT 7 AU POINT NBPOIN
      NOSOM1 = 7
      NOSOM2 = NBPOIN
 
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12000) NOSOM1-1, NOSOM2-NOSOM1+1
      ELSE
         WRITE(IMPRIM,22000) NOSOM1-1, NOSOM2-NOSOM1+1
      ENDIF
12000 FORMAT(/' voex09  : TETRAEDRISATION: NOMBRE SOMMETS ACTUELS =',I9,
     %        ' NOMBRE SOMMETS A AJOUTER =',I9,'  ',50('+'))
22000 FORMAT(/' voex09  : TETRAHEDRIZATION : ACTUAL VERTEX NUMBER =',I9,
     %        ' VERTEX NUMBER TO ADD =',I9,'  ',50('+'))


C     VERIFICATION QUE LE CALCUL DE LA TAILLE IDEALE DES ARETES EST
C     INITIALISEE ET SINON RETOUR POUR EVITER DES CALCULS INUTILES
      N = ( NOSOM1 + NOSOM2 ) / 2
C     CALCUL DE TAILLE_IDEALE( N )
      CALL TAILIDEA( NOFOTI, PTXYZD(1,N), NCODEV, TAID )
      IF( NCODEV .EQ. 0 ) THEN
C        TAILLE_IDEALE(X,Y,Z) INCALCULABLE ou DARETE<=0
         IERR = 5
         GOTO 9900
      ENDIF

C     TRACE DES FACES LEFACO ET DES POINTS A TETRAEDRISER
ccc      tracte  = .true.
      LORBITE = 1
      CALL TRFAPEPT( NBFAPE, MCN(MNFAPE), MXFACO, MCN(MNFACO),
     %               1,      NOSOM2,      PTXYZD )
      tracte = tracte0

      NBPTSUP = 0
      NTE0    = 1
      CALL TETRAPTS( NUVOLU, KNMVOL, QUAMINEX, QTEAME, NOSOM1, NOSOM2,
     %               NTE0, MXSOMM, NBSOMM, PTXYZD, MCN(MNSOFR),
     %               HEXAPAVE, NBIPAV, ECHPAV,
     %               MCN(MN1SPAVE), MCN(MNOPTSUIV),
     %               INFACO, MXFACO, MCN(MNFACO), MCN(MNFASC),
     %               IVOLTE, CHATVO,
     %               MXTETR, N1TEVI, NOTETR, MCN(MNTETS),
     %               MXETOI, MCN(MNFETO), MCN(MNTETO), MCN(MNLIPO),
     %               NUDTETR,NBPTSUP, IERR )

C     MISE A JOUR DES TABLEAUX LEFACO, NOFAPE, NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR,MCN(MNTETS),
     %               MCN(MNFASC), MXFACO, MCN(MNFACO),
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )
      NBFAPE0 = NBFAPE

C     QUALITE DES TETRAEDRES ET VOLUME TOTAL
      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %               NBTETR, NUDTETR,   QUAMIN, QUAMOY, VOLUMT )

      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'tetrapts: TETRAEDRISATION des SOMMETS',
     %   NOSOM1,' a',NOSOM2,' en',CPU,' SECONDES CPU. IERR=',IERR
      ELSE
         PRINT*,'tetrapts: TETRAHEDRIZATION of VERTICES',
     %   NOSOM1,' to',NOSOM2,' for',CPU,'  CPU SECONDS. IERR=',IERR
      ENDIF
12001 FORMAT(' ',A,T12,F11.2,'  SECONDES CPU et IERR=',I4)
22001 FORMAT(' ',A,T12,F11.2,'  CPU SECONDS and IERR=',I4)

      IF( IERR .NE. 0 ) THEN
         PRINT*
         PRINT*,'voex09: IERR=',IERR,
     %          ' IMPOSSIBLE de TETRAEDRISER UN POINT -> ABANDON'
         PRINT*
         GOTO 9900
      ENDIF

cccC     ESSAI D'AMELIORER LA QUALITE DE TOUS LES TETRAEDRES
cccC     DE QUALITE MEDIOCRE PAR DIFFERENTES TECHNIQUES SELON
cccC     LE TYPE DU TETRAEDRE PLAT ( TRIANGLE ou QUADRANGLE ):
cccC     SUPPRESSION DES TETRAEDRES D'UNE ARETE TRES COURTE
cccC     CHANGEMENTS 3 TETRAEDRES -> 2 TETRAEDRES
cccC     DECOMPOSITION DE TETRAEDRES EN 2 TETRAEDRES
cccC     -----------------------------------------------------
ccc      IF( QUAMIN .GT. QTEAME ) GOTO 1030
ccc      CALL AMQALLTE( QTEAME, MXTETR, N1TEVI, NOTETR, MCN(MNTETS),
ccc     %               MXSOMM, NBSOMM, PTXYZD, MCN(MNSOFR),
ccc     %               INFACO, MXFACO, MCN(MNFACO), IVOLTE, CHATVO,
ccc     %               MXTE1S, MCN(MNTE1S), MXETOI, MCN(MNFETO),
ccc     %               MXTRCF, MCN(MNTRCF),
ccc     %               NUDTETR, VOLMOY, MODIFT, IERR )
cccC     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
cccC                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
ccc      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR,MCN(MNTETS),
ccc     %               MCN(MNFASC), MXFACO, MCN(MNFACO),
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )
cccC     QUALITE DES TETRAEDRES ET VOLUME TOTAL
ccc      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
ccc     %               NBTETR, NUDTETR,   QUAMIN, QUAMOY, VOLUMT )
ccc      CPU  = DINFO('DELTA CPU')
ccc      CPUT = CPUT + CPU
ccc      IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,12001) 'amqallte 1',CPU,IERR
ccc      ELSE
ccc         WRITE(IMPRIM,22001) 'amqallte 1',CPU,IERR
ccc      ENDIF
ccc 1030  IF( NBFAPE .LE. 0 ) GOTO 1500


C     RECUPERATION DES FACES PERDUES DE LA FRONTIERE ET DES
C     INTERFACES DE LA PARTITION DES VOLUMES A TETRAEDRISER
C     =====================================================
      IF( NBFAPE .LE. 0 ) GOTO 1500
      CALL RECUFAPE( NUVOLU, KNMVOL, COANPL, QUAMINEX, QTEAME,
     %               MXSOMM, NBSOMM, PTXYZD,
     %               MCN(MNSOFR), MCN(MNLIPO),
     %               HEXAPAVE, NBIPAV, ECHPAV,
     %               MCN(MN1SPAVE),  MCN(MNOPTSUIV),
     %               MXTETR, N1TEVI, MCN(MNTETS), NOTETR, NUDTETR,
     %               MXTE1S, MNTE1S, MCN(MNTE1S),
     %               MXTRCF, MCN(MNTRCF), MCN(MNTRCF+MXTRCF),
     %               MCN(MNSTIS),
     %               MXARCF, MCN(MNARCF), MCN(MNARCF+1+MXARCF),
     %               MXETOI, MCN(MNFETO), MCN(MNAETO), MCN(MNDSTM),
     %               INFACO, MXFACO, NBFACO, MCN(MNFACO), MCN(MN0FAR),
     %               MCN(MNFASC), IVOLTE, CHATVO,
     %               MXFAPE, NBFAPE, MCN(MNFAPE),
     %               MXPILE, MNPILE, MCN(MNPILE),
     %               NBABAN, IERR )

C     MISE A JOUR DU NO NOTETR DE TETRAEDRE CONTENANT UNE FACE LEFACO
C                 ET DES TABLEAUX NOTETR, N1TETS, N1FASC
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR,MCN(MNTETS),
     %               MCN(MNFASC), MXFACO, MCN(MNFACO),
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

C     CALCUL DE LA QUALITE DE LA TETRAEDRISATION et VOLUME TOTAL
      PRINT*,'voex09: CALCUL de la QUALITE de la TETRAEDRISATION apres R
     %ECUFAPE'
      CALL QUALTETR( PTXYZD, MXTETR,  NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )

      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'recufape:',CPU,IERR
      ELSE
         WRITE(IMPRIM,22001) 'recufape:',CPU,IERR
      ENDIF

      IF( NBFAPE .GT. 0 .OR. IERR .EQ. 11 ) THEN
         PRINT*,'voex09:',NBFAPE,' FACES PERDUES APRES la TENTATIVE de l
     %eur RECUPERATION'
         PRINT*,'voex09: Algorithme INSUFFISANT. A AMELIORER...'
         IERR = 1
C        ABANDON DE LA TETRAEDRISATION
         GOTO 9900
      ENDIF


C     MISE A JOUR DES TABLEAUX LEFACO, NOFAPE, NOTETR, N1TETS, N1FASC
 1500 CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR,MCN(MNTETS),
     %               MCN(MNFASC), MXFACO, MCN(MNFACO),
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )

C     BARYCENTRAGE DES SOMMETS INTERNES D'UNE TETRAEDRISATION
C     C-A-D DES SOMMETS DE NPSOFR >=-4 et <=0
C     -------------------------------------------------------
      NBITERBA = 5
      CALL BASTTETR( NBITERBA, NBSOMM, PTXYZD, MCN(MNSOFR),
     %               MXTETR, NOTETR, MCN(MNTETS), 4*MXARCF, MCN(MNARCF))

C     CALCUL DE LA QUALITE DE LA TETRAEDRISATION et VOLUME TOTAL
      PRINT*,'voex09: CALCUL de la QUALITE de la TETRAEDRISATION apres B
     %ARYCENTRAGE des SOMMETS INTERNES'
      CALL QUALTETR( PTXYZD, MXTETR,  NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )

      IF( IERR .NE. 0 ) GOTO 9900

      IF( NBFAPE .GT. 0 ) THEN
C        ALGORITHME de RECUPERATION des FACES PERDUES INSUFFISANT
         IERR = 13
         GOTO 9900
      ENDIF

C     FIN DE LA TETRAEDRISATION ETOILEE et
C     ICI TOUTES LES FACES FRONTALIERES ONT ETE RETROUVEES
C     ----------------------------------------------------
      IF( MNFAPE .GT. 0 ) CALL TNMCDS( 'ENTIER', MXFAPE, MNFAPE )


C     DESTRUCTION DES TETRAEDRES EXTERIEURS AU DOMAINE
C     GENERATION  DES TETRAEDRES DE CHAQUE VOLUME
C     RECHERCHE DU NOMBRE DE TETRAEDRES ACTUELS
C     DU TETRAEDRE LE 'PLUS ECRASE' ET IMPRESSIONS
C     ------------------------------------------------
      CALL VDTUER( KNMVOL, MXSOMM, PTXYZD, NBVOPA,
     %             MXTETR, N1TEVI, MCN(MNTETS), NOTETR,
     %             MXFACO, MCN(MNFACO),
     %             MNF1VO, CHATVO, NBTETR, NUDTETR, NUDSOMM, IERR )


C     LE TABLEAU CHATVO (CHAINAGE SUR LE TETRAEDRE SUIVANT DE CHAQUE VOLUME)
C     EST DEVENU LE TABLEAU NVOLTE (NO DE VOLUME DE CHAQUE TETRAEDRE)
      IVOLTE = 1
C     => LE TABLEAU LEFACO N'EST PLUS UTLE
      INFACO = 0

C     CALCUL DE LA QUALITE DE LA TETRAEDRISATION et VOLUME TOTAL
      CALL QUALTETR( PTXYZD, MXTETR,  NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )

      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'vdtuer  :',CPU,IERR
      ELSE
         WRITE(IMPRIM,22001) 'vdtuer  :',CPU,IERR
      ENDIF

      IF( IERR .GT. 0 ) GOTO 9900


C     TENTATIVE D'AMELIORER LA QUALITE DE TOUS LES TETRAEDRES
C     DE QUALITE MEDIOCRE PAR DIFFERENTES TECHNIQUES SELON
C     LE TYPE DU TETRAEDRE PLAT DEGENERE EN TRIANGLE ou QUADRANGLE
C     SUPPRESSION DES TETRAEDRES D'UNE ARETE TRES COURTE
C     CHANGEMENTS 3 TETRAEDRES -> 2 TETRAEDRES
C     DECOMPOSITION DE TETRAEDRES EN 2 TETRAEDRES
C     AMELIORER LA QUALITE DES TETRAEDRES AUTOUR 
C     DU TETRAEDRE NTE DE MEDIOCRE QUALITE ET DE LUI-MEME
C     ------------------------------------------------------------
ccc      CALL AMQALLTE( QTEAME, MXTETR, N1TEVI, NOTETR, MCN(MNTETS),
ccc     %               MXSOMM, NBSOMM, PTXYZD, MCN(MNSOFR),
ccc     %               INFACO, MXFACO, MCN(MNFACO), IVOLTE, CHATVO,
ccc     %               MXTE1S, MCN(MNTE1S), MXETOI, MCN(MNFETO),
ccc     %               MXTRCF, MCN(MNTRCF),
ccc     %               NUDTETR, VOLMOY, MODIFT, IERR )

C     CALCUL DE LA QUALITE DE LA TETRAEDRISATION et VOLUME TOTAL
      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %               NBTETR, NUDTETR,   QUAMIN, QUAMOY, VOLUMT )
      VOLMOY = VOLUMT / NBTETR

      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'amqallte 2',CPU,IERR
      ELSE
         WRITE(IMPRIM,22001) 'amqallte 2',CPU,IERR
      ENDIF


      IF( NBTETR .GT. 0 ) THEN
C        SAUT DE L'AJOUT DE NOUVEAUX POINTS INTERNES .................
         GOTO 2000
      ENDIF


cccC     AJOUT DE POINTS DANS LES TETRAEDRES POUR AJUSTER LES ARETES
cccC     A LA DISTANCE SOUHAITEE ENTRE LEURS SOMMETS
cccC     ===========================================================
cccC     TETRAEDRISATION DE POINTS SUR L'ARETE MAX DES TETRAEDRES
cccC     SI SA TAILLE EST SUPERIEURE A LA TAILLE SOUHAITEE EN AU
cccC     MOINS UN DES SOMMETS PUIS
cccC     AMELIORIATION DES TETRAEDRES AU DELA DES DECOUPES PAR
cccC     2T->3T ou mT->2m-4T
ccc      MXTE1A = 3*MXETOI
ccc      MXSSTE = 2*MXETOI
ccc      CALL AJPTARMX( ARETGR, NOFOTI, NBVOPA, VOLMOY,
ccc     %               NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
ccc     %               MXTETR, N1TEVI, NOTETR, NUDTETR,
ccc     %               MCN(MNTETS), MCN(MNF1VO),
ccc     %               MXFACO, MCN(MNFACO), IVOLTE, CHATVO,
ccc     %               MXPILE, MCN(MNPILE),
ccc     %               MXTE1A, MCN(MNFETO),
ccc     %               MXSSTE, MCN(MNFETO+MXTE1A),
ccc     %               IERR )
cccccc      DEJA EXECUTE DANS ajptarmx
cccccc      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
cccccc     %               NBTETR, NUDTETR,   QUAMIN, QUAMOY, VOLUMT )
ccc      CPU  = DINFO('DELTA CPU')
ccc      CPUT = CPUT + CPU
ccc      IF( LANGAG .EQ. 0 ) THEN
ccc         WRITE(IMPRIM,12001) 'ajptarmx:',CPU,IERR
ccc      ELSE
ccc         WRITE(IMPRIM,22001) 'ajptarmx:',CPU,IERR
ccc      ENDIF

cccC     MISE A JOUR DU NOMBRE DE SOMMETS ACTIFS ET
cccC                 DU TABLEAU N1TETS(NS)=1 TETRAEDRE DE SOMMET NS
cccC     ----------------------------------------------------------
ccc      CALL AZEROI( MXSOMM, MCN(MNTETS) )
ccc      NBSOMM = 0
ccc      MNT1   = MNTETS - 1
ccc      DO NTE = 1, NUDTETR
ccc         IF( NOTETR(1,NTE) .GT. 0 ) THEN
ccc            DO K=1,4
ccc               NS = NOTETR( K, NTE )
ccc               IF( NS .GT. NBSOMM ) THEN
ccc                  NBSOMM = NS
ccc               ENDIF
ccc               MCN( MNT1 + NS ) = NTE
ccc            ENDDO
ccc         ENDIF
ccc      ENDDO
ccc      PRINT*,'voex09: NOMBRE DE SOMMETS ACTIFS NBSOMM=',NBSOMM


cccC     RE-INITIALISATION DU CHAINAGE DES SOMMETS DANS L'HEXAPAVE
cccC     ---------------------------------------------------------
ccc      CALL AZEROI( NBPAVE, MCN(MN1SPAVE) )
ccc      CALL AZEROI( MXSOMM, MCN(MNOPTSUIV) )

ccc      DO NS = 7, NBSOMM
cccC        AJOUT DANS LE PAVAGE DU POINT NS
ccc         IF( MCN(MNT1+NS) .GT. 0 ) THEN
ccc            CALL NUPAVEST( NS, PTXYZD, HEXAPAVE, NBIPAV, ECHPAV,
ccc     %                     MCN(MN1SPAVE), MCN(MNOPTSUIV) )
ccc         ENDIF
ccc      ENDDO


C     MISE A JOUR DES TABLEAUX LEFACO, NOFAPE, NOTETR, N1TETS, N1FASC
C     ---------------------------------------------------------------
      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR,MCN(MNTETS),
     %               MCN(MNFASC), MXFACO, MCN(MNFACO),
     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )


C     MISE A JOUR DE LA TAILLE IDEALE DES ARETES AUTOUR DES SOMMETS
C     -------------------------------------------------------------
      NBS = 0
      ARETMOY = 0
      DO NSt = 7, NBSOMM
         IF(  MCN(MNTETS-1+NSt ) .GT. 0 ) THEN
C           CALCUL DE TAILLE_IDEALE( NSt )
            CALL TAILIDEA( NOFOTI, PTXYZD(1,NSt),
     %                     NCODEV, PTXYZD(4,NSt) )
            IF( NCODEV .EQ. 0 ) THEN
C              TAILLE_IDEALE(X,Y,Z) INCALCULABLE ou DARETE<=0
               IERR = 5
               GOTO 9900
            ENDIF
            NBS = NBS + 1
            ARETMOY = ARETMOY + REAL( PTXYZD(4,NSt) )
         ENDIF
      ENDDO
      ARETMOY = ARETMOY / NBS

C     TETRAEDRISATION DE POINTS SUR UNE GRILLE D'OCTAEDRES REGULIERS
C     DE TAILLE D'ARETE ARETGR
C     --------------------------------------------------------------
      IF( NOFOTI .EQ. 0 ) THEN
         CALL TETRGROC( KNMVOLU, QTEAME, HEXAVOLU, VOLMOY,
     %                  NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
     %                  HEXAPAVE, NBIPAV, ECHPAV,
     %                  MCN(MN1SPAVE), MCN(MNOPTSUIV),
     %                  MXTETR, N1TEVI, NOTETR, NUDTETR, NBTETR,
     %                  MCN(MNTETS),
     %                  INFACO, MXFACO, MCN(MNFACO), MCN(MNFASC),
     %                  IVOLTE, CHATVO,
     %                  MXETOI, MCN(MNFETO), MCN(MNTETO), MCN(MNLIPO),
     %                  IERR )
         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,12001) 'tetrgroc:',CPU,IERR
         ELSE
            WRITE(IMPRIM,22001) 'tetrgroc:',CPU,IERR
         ENDIF
         print*
         PRINT*,'voex09: VOLUME et QUALITE du MAILLAGE apres TETRGROC'
         CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %                  NBTETR, NUDTETR,   QUAMIN, QUAMOY, VOLUMT )
         VOLMOY = VOLUMT / NBTETR
      ENDIF


C     TETRAEDRISATION DE POINTS A L'INTERIEUR DES TETRAEDRES TROP
C     VOLUMINEUX DE LA BOULE DE CENTRE UN SOMMET ET DE RAYON
C     LA TAILLE SOUHAITEE DES ARETES AUTOUR DU SOMMET AINSI QUE
C     LES POINTS SUR LES ARETES TROP LONGUES ISSUES DU SOMMET
C     -----------------------------------------------------------
      CALL TETRARBO( NUVOLU, KNMVOL, QUAMINEX, QTEAME, VOLMOY,
     %               NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
     %               HEXAPAVE, NBIPAV, ECHPAV,
     %               MCN(MN1SPAVE), MCN(MNOPTSUIV),
     %               MXTETR, N1TEVI, NOTETR, NUDTETR, NBTETR,
     %               MCN(MNTETS),
     %               INFACO, MXFACO, MCN(MNFACO), MCN(MNFASC),
     %               IVOLTE, CHATVO,
     %               MXETOI, MCN(MNFETO), MCN(MNTETO), MCN(MNLIPO),
     %               IERR )
      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'tetrarbo:',CPU,IERR
      ELSE
         WRITE(IMPRIM,22001) 'tetrarbo:',CPU,IERR
      ENDIF

      PRINT*,'voex09: VOLUME et QUALITE du MAILLAGE apres TETRARBO'
      CALL QUALTETR( PTXYZD, NUDTETR+1, NOTETR,
     %               NBTETR, NUDTETR,   QUAMIN, QUAMOY, VOLUMT )
      VOLMOY = VOLUMT / NBTETR


cccC     MISE A JOUR DES TABLEAUX LEFACO, NOFAPE, NOTETR, N1TETS, N1FASC
ccc      CALL NTLEFACO( MXSOMM, NBSOMM, PTXYZD, MXTETR, NOTETR,MCN(MNTETS),
ccc     %               MCN(MNFASC), MXFACO, MCN(MNFACO),
ccc     %               MXFAPE, NBFAPE, MCN(MNFAPE), N1TEVI, NUDTETR )


C     ITERATIONS de TETRAEDRISATION DU BARYCENTRE DES TETRAEDRES
C     TROP VOLUMINEUX AU REGARD DE LA TAILLE SOUHAITEE D'ARETES
C     AUX 4 SOMMETS
C     ----------------------------------------------------------
      CALL TETROPVL( NUVOLU, KNMVOL, QUAMINEX, QTEAME,
ccc     %               VOLMOY,
     %               NBSOMM, MXSOMM, PTXYZD, MCN(MNSOFR),
     %               HEXAPAVE, NBIPAV, ECHPAV,
     %               MCN(MN1SPAVE), MCN(MNOPTSUIV),
     %               MXTETR, N1TEVI, NOTETR, NUDTETR, NBTETR,
     %               MCN(MNTETS),
     %               INFACO, MXFACO, MCN(MNFACO), MCN(MNFASC),
     %               IVOLTE, CHATVO,
     %               MXETOI, MCN(MNFETO), MCN(MNTETO), MCN(MNLIPO),
     %               IERR )

      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'tetropvl:',CPU
      ELSE
         WRITE(IMPRIM,22001) 'tetropvl:',CPU
      ENDIF


C     BARYCENTRAGE/2 DES SOMMETS INTERNES D'UNE TETRAEDRISATION
C     C-A-D DES SOMMETS DE NPSOFR NUL
C     ---------------------------------------------------------
      NBITERBA = 4
      CALL BASTTETR( NBITERBA, NBSOMM, PTXYZD, MCN(MNSOFR),
     %               MXTETR, NOTETR, MCN(MNTETS), 4*MXARCF, MCN(MNARCF))

C     CALCUL DE LA QUALITE DE LA TETRAEDRISATION et VOLUME TOTAL
      PRINT*,'voex09: CALCUL de la QUALITE de la TETRAEDRISATION apres B
     %ARYCENTRAGE des SOMMETS INTERNES avant CREATION xyzsommet et nsef'
      CALL QUALTETR( PTXYZD, MXTETR,  NOTETR,
     %               NBTETR, NUDTETR, QUAMIN, QUAMOY, VOLUMT )


C     REGENERATION DES VRAIES COORDONNEES DES POINTS DEPLACES
C     GENERATION DU TABLEAU 'MATERIAUX' DE LA PARTITION
C     GENERATION DES TMS 'NSEF' 'XYZSOMMET' DES VOLUMES ET DE LA PARTITION
C     CREATION DES SURFACES INTERFACES ET FRONTIERES DE LA PARTITION
C     --------------------------------------------------------------------
 2000 CALL TETRPAVO( NUVOLU, NTLXVL, LADEFI, NBVOPA,
     %               NBSOMM, PTXYZD, MNSOFR, MNLIPO,
     %               NUDTETR,NBTETR, NOTETR, MCN(MNF1VO), CHATVO,
     %               MXFACO, MNFACO,
     %               NBSP,   NBTETT, VOLUMT,
     %               NTCUPA, MNCUPA, NTSOMM, MNSOMM )

      IERR = 0
      CPU  = DINFO('DELTA CPU')
      CPUT = CPUT + CPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,12001) 'tetrpavo',CPU,IERR
      ELSE
         WRITE(IMPRIM,22001) 'tetrpavo',CPU,IERR
      ENDIF


C     DESTRUCTION DES TABLEAUX DEVENUS INUTILES
C     -----------------------------------------
 9900 PRINT*
      IF( LANGAG .EQ. 0 ) THEN

         IF( IERARELLOC .EQ. 0 ) then
            PRINT*,'LARETE est DESALLOUE'
            DEALLOCATE( LARETE )
         ENDIF
         IF( IERCHALLOC .EQ. 0 ) then
            PRINT*,'CHATVO est DESALLOUE'
            DEALLOCATE( CHATVO )
         ENDIF
         IF( IERTEALLOC .EQ. 0 ) then
            PRINT*,'NOTETR est DESALLOUE'
            DEALLOCATE( NOTETR )
         ENDIF
         IF( IERATALLOC .EQ. 0 ) then
            PRINT*,'Arbre TETRAEDRES est DESALLOUE'
            DEALLOCATE( LARBRT )
         ENDIF
         IF( IERAOALLOC .EQ. 0 ) then
            PRINT*,'Arbre  OCTAEDRES est DESALLOUE'
            DEALLOCATE( LARBRO )
         ENDIF
         IF( IERZDALLOC .EQ. 0 ) then
            PRINT*,'PtXYZd est DESALLOUE'
            DEALLOCATE( PTXYZD )
         ENDIF

      ELSE

         IF( IERARELLOC .EQ. 0 ) then
            PRINT*,'LARETE is DESALLOCATED'
            DEALLOCATE( LARETE )
         ENDIF
         IF( IERCHALLOC .EQ. 0 ) then
            PRINT*,'CHATVO is DESALLOCATED'
            DEALLOCATE( CHATVO )
         ENDIF
         IF( IERTEALLOC .EQ. 0 ) then
            PRINT*,'NOTETR is DESALLOCATED'
            DEALLOCATE( NOTETR )
         ENDIF
         IF( IERATALLOC .EQ. 0 ) then
            PRINT*,'Arbre TETRAEDRES is DESALLOCATED'
            DEALLOCATE( LARBRT )
         ENDIF
         IF( IERAOALLOC .EQ. 0 ) then
            PRINT*,'Arbre  OCTAEDRES is DESALLOCATED'
            DEALLOCATE( LARBRO )
         ENDIF
         IF( IERZDALLOC .EQ. 0 ) then
            PRINT*,'PtXYZd is DESALLOCATED'
            DEALLOCATE( PTXYZD )
         ENDIF

      ENDIF

C     DESTRUCTION DES TABLEAUX STOCKES EN MCN
      IF( MNOPTSUIV.GT.0) CALL TNMCDS( 'ENTIER', MXSOMM, MNOPTSUIV)
      IF( MN1SPAVE .GT.0) CALL TNMCDS( 'ENTIER', NBPAVE, MN1SPAVE )
      IF( MNSTIS .GT. 0 ) CALL TNMCDS( 'ENTIER', MXSTIS,   MNSTIS )
      IF( MNTE1S .GT. 0 ) CALL TNMCDS( 'ENTIER', MXTE1S,   MNTE1S )
      IF( MNTRCF .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXTRCF, MNTRCF )
      IF( MNF1VO .GT. 0 ) CALL TNMCDS( 'ENTIER', 3*NBVOPA, MNF1VO )
      IF( MNFAPE .GT. 0 ) CALL TNMCDS( 'ENTIER', MXFAPE,   MNFAPE )
      IF( MN0FAR .GT. 0 ) CALL TNMCDS( 'ENTIER', 3*MXETOI, MN0FAR )
      IF( MNAETO .GT. 0 ) CALL TNMCDS( 'ENTIER', 4*MXETOI, MNAETO )
      IF( MNTETO .GT. 0 ) CALL TNMCDS( 'ENTIER',   MXETOI, MNTETO )
      IF( MNFETO .GT. 0 ) CALL TNMCDS( 'ENTIER', 5*MXETOI, MNFETO )
      IF( MNDSTM .GT. 0 ) CALL TNMCDS( 'REEL2',    MXETOI, MNDSTM )
      IF( MNARCF .GT. 0 ) CALL TNMCDS( 'ENTIER', 4*MXARCF+1, MNARCF )
      IF( MNLIPO .GT. 0 ) CALL TNMCDS( 'ENTIER', MXSOMM+1, MNLIPO )
      IF( MNPILE .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXPILE, MNPILE )
      IF( MNFASC .GT. 0 ) CALL TNMCDS( 'ENTIER', MXSOMM ,  MNFASC )
      IF( MNFACO .GT. 0 ) CALL TNMCDS( 'ENTIER', 11*MXFACO+11, MNFACO )
      IF( MNSOFR .GT. 0 ) CALL TNMCDS( 'ENTIER', MXSOMM,   MNSOFR )
      IF( MNTETS .GT. 0 ) CALL TNMCDS( 'ENTIER', MXSOMM,   MNTETS )
      IF( MN3T2T .GT. 0 ) CALL TNMCDS( 'ENTIER', MX3T2T,   MN3T2T )
      IF( MNOTPT .GT. 0 ) CALL TNMCDS( 'ENTIER', MXSOMM,   MNOTPT )
      IF( MNPILL .GT. 0 ) CALL TNMCDS( 'ENTIER', MXPILL,   MNPILL )


C     AFFICHAGE DU TEMPS CPU TOTAL UTILISE PAR LA TETRAEDRISATION
C     -----------------------------------------------------------
      IF( IERR .NE. 0 ) THEN

C        ERREUR DETECTEE -> PAS DE CREATION de la TETRAEDRISATION
19880    FORMAT(200('/'))
         PRINT 19880
         NBLGRC(NRERR) = 2
         IF( LANGAG .EQ. 0 ) THEN
          KERR(1) = 'voex09: SUITE au PROBLEME IERR=           VU AVANT'
            WRITE(KERR(1)(32:37),'(I6)') IERR
            KERR(2) = 'la TETRAEDRISATION du VOLUME ' // KNMVOL //
     %                ' N''EST PAS REALISEE'
         ELSE
            KERR(1) = 'voex09: From the PROBLEM IERR=       SEEN BEFORE'
            WRITE(KERR(1)(31:36),'(I6)') IERR
            KERR(2) = 'the TETRAHEDRIZATION of VOLUME ' // KNMVOL //
     %                ' is NOT CREATED'
         ENDIF
         CALL LEREUR
         PRINT 19880
         GOTO 9997

      ELSE

C        BILAN DE LA TETRAEDRISATION
C        TEMPS CPU DE LA GENERATION FINALE DES TETRAEDRES
         CPU  = DINFO('DELTA CPU')
         CPUT = CPUT + CPU
         print*
         IF( LANGAG .EQ. 0 ) THEN
         PRINT*,'voex09: VOLUME ',KNMVOL,
     %           ' Nombre de FACES PERDUES INITIAL=',NBFAPE0,
     %           ' Nombre de FACES PERDUES FINAL L=',NBFAPE
       WRITE(IMPRIM,19900) CPU,CPUT,NBSP,NBTETT,VOLUMT,KINFO('MACHINE')
         ELSE
         PRINT*,'voex09: VOLUME ',KNMVOL,
     %           ' INITIAL LOST FACE Number=',NBFAPE0,
     %           ' FINAL LOST FACE Number=',NBFAPE
       WRITE(IMPRIM,29900) CPU,CPUT,NBSP,NBTETT,VOLUMT,KINFO('MACHINE')
         ENDIF

      ENDIF

19900 FORMAT(' voex09: TEMPS CPU CREATION FINALE des TETRAEDRES et STOCK
     %AGE du MAILLAGE',F11.2,' SECONDES'/
     %' voex09: TEMPS CPU TOTAL DE LA TETRAEDRISATION',F11.2,
     %' SECONDES pour',I9,' SOMMETS et',I9,' TETRAEDRES et un VOLUME TOT
     %AL de ',G20.12,' sur l''ordinateur ',A/166('-'))
29900 FORMAT(' voex09: CPU TIME of FINAL TETRAHEDRA CREATION and MESH ST
     %ORAGE ',F11.2,' SECONDS'/
     %' voex09: TETRAHEDRIZATION TOTAL CPU TIME',F11.2,
     %' SECONDS for',I9,' VERTICES and',I9,' TETRAHEDRA of TOTAL VOLUME'
     %,G20.12,' on COMPUTER ',A/ 166('-'))

      GOTO 9999


C     SATURATION DE LA PLACE MEMOIRE
C     ------------------------------
 9995 NBLGRC(NRERR) = 5
      KERR(1)='voex09: VOLUME ' // KNMVOL
      IF( LANGAG .EQ. 0 ) THEN
         KERR(2)='SATURATION de la MEMOIRE OCCUPEE par les TABLEAUX'
         KERR(3)='AUGMENTEZ la TAILLE du SUPER-TABLEAU MCN'
         KERR(4)='ou AUGMENTEZ le NOMBRE MAXIMAL de SOMMETS DE LA TETRAE
     %DRISATION'
         KERR(5) ='ou REDUISEZ LE NOMBRE DE TRIANGLES INITIAUX'
      ELSE
         KERR(2)='SUPER-ARRAY MCM MEMORY is FULL by the TMS'
         KERR(3)='AUGMENT the LENGTH of SUPER-ARRAY MCN'
       KERR(4)='or AUGMENT the TETRAHEDRIZATION VERTICES MAXIMUM NUMBER'
         KERR(5)='or REDUCE the INITIAL TRIANGLES NUMBER'
      ENDIF
      PRINT*
      CALL LEREUR
      GOTO 9900

C     ERREUR
 9997 IERR = 100

 9999 TRACTE = TRACTE0
      RETURN
      END
