      SUBROUTINE VOEX02( NTLXVO, NITCOR, FADIST,
     S                   NTVOOB, MNVOOB, NTSOVO, MNSOVO, TCPU,
     S                   IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    GENERER LE MAILLAGE D'UN HEXAEDRE DEFINI PAR LES
C -----    SURFACES STRUCTUREES DE CHACUNE DE SES 6 FACES
C          PAR LA METHODE DE WINSLOW
C
C ENTREES:
C --------
C NTLXVO : NUMERO DU TABLEAU TS DU LEXIQUE DU VOLUME
C
C SORTIES:
C --------
C NTVOOB : NUMERO      DU TMS 'NSEF' DES NUM. DES VOL.
C MNVOOB : ADRESSE MCN DU TMS 'NSEF' DES NUM. DES VOL.
C          CF '~/TD/D/A___NSEF'
C NTSOVO : NUMERO      DU TMS 'XYZSOMMET' DE L'OBJET
C MNSOVO : ADRESSE MCN DU TMS 'XYZSOMMET' DE L'OBJET
C          CF '~/TD/D/A___XYZSOMMET'
C IERR   : 0 SI PAS D'ERREUR
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : DOURSAT CHRISTOPHE  ANALYSE NUMERIQUE PARIS      OCTOBRE 1989
C2345X7..............................................................012
      IMPLICIT INTEGER (W)
      include"./incl/gsmenu.inc"
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
      include"./incl/ntmnlt.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/a_volume__definition.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE       (MCN(1),RMCN(1))
      REAL              FADIST(6)
      DOUBLE PRECISION TCPU(3,100)
C
      IERR = 0
C
C     VERIFICATION DU TYPE DE MAILLAGE DU VOLUME
C     OUVERTURE DU TABLEAU 'NSEF' DE CE VOLUME MAILLAGE INITIAL
      CALL LXTSOU( NTLXVO, 'NSEF', NTVOOB, MNVOOB )
C
C     LE VOLUME EST IL STRUCTURE ?
      NUTYOB = MCN( MNVOOB + WUTYOB )
      NUTYMA = MCN( MNVOOB + WUTYMA )
      IF((NUTYOB .NE. 4).OR.(NUTYMA .NE. 7)) THEN
         NBLGRC(NRERR) = 2
         WRITE(KERR(MXLGER)(1:10),'(I10)') NUTYOB
         KERR(1) = ' VOEX02: TYPE DE L OBJET =' // KERR(MXLGER)(1:10)
         WRITE(KERR(MXLGER)(1:10),'(I10)') NUTYMA
         KERR(2) = '         TYPE DU MAILLAGE=' // KERR(MXLGER)(1:10)
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     LE NOMBRE DE SOMMETS DANS CHAQUE DIRECTION
      NBS1 = MCN ( MNVOOB + WBARXH ) + 1
      NBS2 = MCN ( MNVOOB + WBARYH ) + 1
      NBS3 = MCN ( MNVOOB + WBARZH ) + 1
C
C     OUVERTURE DU TABLEAU 'XYZSOMMET' DE CE VOLUME
      CALL LXTSOU( NTLXVO, 'XYZSOMMET', NTSOVO, MNSOVO )
C     LE NOMBRE DE SOMMETS
      NBSO = MCN( MNSOVO + WNBSOM)
C     L'ADRESSE DU TABLEAU DES COORDONNEES DES SOMMETS DU VOLUME
      MNSOMM = MNSOVO + WYZSOM
C
C     TEST SUR LE NOMBRE DE SOMMETS
      NBS = NBS1*NBS2*NBS3
      IF( NBSO .NE. NBS ) THEN
         NBLGRC(NRERR) = 2
         WRITE(KERR(MXLGER)(1:6),'(I6)') NBSO
         KERR(1) = ' ERREUR VOEX02:' // KERR(MXLGER)(1:6)
     S             // 'XYZSOMMET'
         WRITE(KERR(MXLGER)(1:6),'(I6)') NBS
         KERR(2) = ' AU LIEU DE ' // KERR(MXLGER)(1:6)
         CALL LEREUR
         IERR = 4
         RETURN
      ENDIF
C
C     RESERVATION DE LA PLACE NECESSAIRE AUX TABLEAUX TEMPORAIRES :
C     DANS L'ORDRE LA  MATRICE  2 COLONNES DISTID
C                  LES VECTEURS FCI FCJ ET FCK
      LGMAX  = NBS1*NBS2*NBS3
      NADDIS = 0
      CALL TNMCDC( 'REEL', LGMAX, NADDIS )
      NADFCI = 0
      CALL TNMCDC( 'REEL', LGMAX, NADFCI )
      NADFCJ = 0
      CALL TNMCDC( 'REEL', LGMAX, NADFCJ )
      NADFCK = 0
      CALL TNMCDC( 'REEL', LGMAX, NADFCK )
C
C     EXECUTION DE LA SUBROUTINE DE MAILLAGE ELLIPTIQUE PAR WINSLOW
      CALL MAIWIN(NBS1,NBS2,NBS3,MCN(MNSOMM),RMCN(NADDIS),RMCN(NADFCI),
     S            RMCN(NADFCJ),RMCN(NADFCK),NITCOR,FADIST,LGMAX,
     S            TCPU,IERR)
C
C     DESTRUCTION DES TABLEAUX DE TRAVAIL
      CALL TNMCDS( 'REEL', LGMAX, NADDIS )
      CALL TNMCDS( 'REEL', LGMAX, NADFCI )
      CALL TNMCDS( 'REEL', LGMAX, NADFCJ )
      CALL TNMCDS( 'REEL', LGMAX, NADFCK )
      RETURN
      END
