      SUBROUTINE VOEX63( NTLXVO, LADEFI, RADEFI,
     %                   NTEF6C, MNEF6C, NTST6C, MNST6C, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    GENERER LE MAILLAGE NON STRUCTURE EN 6-CUBES D'UNE BOITE
C -----    DE 3 DIFFERENCES FINIES ET PAR HOMOTHETIE EN PROGRESSION
C          GEOMETRIQUE DE CES 6-CUBES
C
C ENTREES:
C --------
C NTLXVO : NUMERO DU TABLEAU TS DU LEXIQUE DU VOLUME
C LADEFI : TABLEAU DE DEFINITION DES VOLUMES
C          CF '~td/d/a_volume__definition'
C
C SORTIES:
C --------
C NTEF6C : NUMERO      DU TMS 'NSEF' DES NUMEROS DES 6-CUBES
C MNEF6C : ADRESSE MCN DU TMS 'NSEF' DES NUMEROS DES 6-CUBES
C          CF '~td/d/a___nsef'
C NTST6C : NUMERO      DU TMS 'XYZSOMMET' DU MAILLAGE DES 6-CUBES
C MNST6C : ADRESSE MCN DU TMS 'XYZSOMMET' DU MAILLAGE DES 6-CUBES
C          CF '~td/d/a___xyzsommet'
C IERR   : 0 SI PAS D'ERREUR
C        > 0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR: ALAIN PERRONNET  TEXAS A & M UNIVERSITY      24 SEPTEMBRE 2005
C MODIF : ALAIN PERRONNET LJLL UMPC & Saint Pierre du Perray   MARS 2009
C.......................................................................
      COMMON / UNITES / LECTEU , IMPRIM , INTERA , NUNITE(29)
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___nsef.inc"
      include"./incl/a_volume__definition.inc"
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1))
      INTEGER           LADEFI(0:*)
      REAL              RADEFI(0:*)
      REAL              COIN(6,2)
C
      IERR = 0
C
C     DIMENSION DE L'ESPACE DU 6-CUBE
C     ===============================
      NBCOOR = 6
C
C     MIN A L'ORIGINE OU CUBE6 CENTRE?
C     NC6CUM =0 : origine au minimum des coordonnees du cube6
C            =1 : origine centree au centre du cube6
C            =2 : origine centree au centre du sous cube6 milieu
C     ==========================================================
      NC6CUM = LADEFI(WUBE6M)
C
C     NOMBRE D'ARETES DU NOYAU
C     ========================
      NA6CUB = LADEFI(WUBE6N)
      WRITE(IMPRIM,*)'NOMBRE D''ARETES DU NOYAU=',NA6CUB
      IF( NA6CUB .LT. 2 ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER)(1:4),'(I4)') NA6CUB
         KERR(1)='NOMBRE INCORRECT (<2) D''ARETES DU NOYAU ='
     %            // KERR(MXLGER)(1:4)
         CALL LEREUR
         IERR = 1
         RETURN
      ENDIF
C
C     LARGEUR DU NOYAU DU 6-CUBE DANS UNE DIRECTION
C     =============================================
      CUB6LA = RADEFI(WUBE6L)
      WRITE(IMPRIM,*)'LARGEUR DU NOYAU=',CUB6LA
      IF( CUB6LA .LT. 0.0 ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER)(1:14),'(E14.6)') CUB6LA
         KERR(1) =  'LARGEUR INCORRECTE DU NOYAU DU 6-CUBE='
     %           //  KERR(MXLGER)(1:4)
         CALL LEREUR
         IERR = 2
         RETURN
      ENDIF
C     LONGUEUR D'UNE ARETE DU NOYAU
      AR6CUB = CUB6LA / NA6CUB
      WRITE(IMPRIM,*)'LONGUEUR D''UNE ARETE DU NOYAU DU 6-CUBE =',AR6CUB
C
C     LARGEUR TOTALE DU 6-CUBE DANS UNE DIRECTION
C     ===========================================
      CUB6DI = RADEFI(WUBE6D)
      WRITE(IMPRIM,*)'LARGEUR DU 6-CUBE=',CUB6DI
      IF( CUB6DI .LT. CUB6LA ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER)(1:14),'(E14.6)') CUB6DI
         KERR(1) = 'LARGEUR TOTALE INCORRECTE DU 6-CUBE='
     %          //  KERR(MXLGER)(1:4)
         CALL LEREUR
         IERR = 3
         RETURN
      ENDIF
C
C     NOMBRE DE COUCHES OU HOMOTHETIES
C     ================================
      NC6CUB = LADEFI(WUBE6C)
      WRITE(IMPRIM,*)'NOMBRE DE COUCHES HOMOTHETIQUES=',NC6CUB
      IF( NC6CUB .LT. 0 ) THEN
         NBLGRC(NRERR) = 1
         WRITE(KERR(MXLGER)(1:4),'(I4)') NC6CUB
         KERR(1)='NOMBRE INCORRECT (<0) DE COUCHES ='//KERR(MXLGER)(1:4)
         CALL LEREUR
         IERR = 4
         RETURN
      ENDIF
C
C     RAISON GEOMETRIQUE D''HOMOTHETIE DANS LES 6 DIMENSIONS
C     ======================================================
      HMIN = AR6CUB
      IF( NC6CUB .GT. 0 ) THEN
         CUB6RG = REAL( ( CUB6DI / CUB6LA ) ** (1d0/NC6CUB) )
C        LONGUEUR DE LA PLUS PETITE ARETE DES COUCHES
         HMC = NA6CUB*AR6CUB*(CUB6RG-1)/2
        WRITE(IMPRIM,*)'LONGUEUR MINIMALE D''UNE ARETE DES COUCHES=',HMC
      ELSE
         CUB6RG = 1D0
      ENDIF
      WRITE(IMPRIM,*)'RAISON GEOMETRIQUE DES ARETES DES COUCHES=',CUB6RG
      WRITE(IMPRIM,*)'LONGUEUR MINIMALE DES ARETES DES 6-CUBES =',
     %                MIN(HMIN,HMC)
      WRITE(IMPRIM,*)'LONGUEUR MAXIMALE DES ARETES DES 6-CUBES =',
     %                CUB6DI/NA6CUB
C
C     GENERATION DES SOMMETS DE CES 6-CUBES
C     =====================================
C     CONSTRUCTION DU TABLEAU 'XYZSOMMET' DE CE VOLUME
C     NOMBRE DE SOMMETS DANS UNE DIRECTION
      NS6CUB = NA6CUB + 1
C     NOMBRE DE SOMMETS DU NOYAU
      NBSOMN = NS6CUB ** NBCOOR
      WRITE(IMPRIM,*)'NOMBRE DE SOMMETS DU NOYAU    =',NBSOMN
C     NOMBRE DE SOMMETS DE LA DERNIERE PEAU DES DIFFERENCES FINIES
      NBSTCH = NBSOMN - (NA6CUB-1) ** NBCOOR
      WRITE(IMPRIM,*)'NOMBRE DE SOMMETS d''une COUCHE=',NBSTCH
C     NOMBRE TOTAL DE SOMMETS DU MAILLAGE DES 6-CUBES
      NBSOM  = NBSOMN + NBSTCH * NC6CUB
      WRITE(IMPRIM,*)'NOMBRE TOTAL DE SOMMETS       =',NBSOM
C     DECLARATION OUVERTURE DU TMS XYZSOMMET
      CALL LXTNDC( NTLXVO, 'XYZSOMMET', 'MOTS' , WYZSOM+NBCOOR*NBSOM )
      CALL LXTSOU( NTLXVO, 'XYZSOMMET',  NTST6C, MNST6C )
C
C     NO GLOBAL DES SOMMETS DE LA 1ERE COUCHE AU DELA DU NOYAU
      CALL TNMCDC( 'ENTIER', NBSOMN, MNSTDF )
      CALL AZEROI( NBSOMN, MCN(MNSTDF) )
C
C     CONSTRUCTION DU TABLEAU XYZUVW
      MNXCH = MNST6C + WYZSOM + NBCOOR * NBSOMN
      CALL XYZS6C( AR6CUB, NA6CUB, CUB6DI, CUB6RG, NC6CUB, NBSTCH,
     %             MCN(MNSTDF), RMCN(MNST6C+WYZSOM), RMCN(MNXCH) )
C
C     LA DIMENSION DE L'ESPACE = NOMBRE DES COORDONNEES D'UN SOMMET
      MCN( MNST6C + WBCOOR ) = NBCOOR
C     LE NOMBRE DE SOMMETS
      MCN( MNST6C + WNBSOM ) = NBSOM
C     LE NOMBRE DE TANGENTES
      MCN( MNST6C + WNBTGS ) = 0
C     LA DATE DE CREATION
      CALL ECDATE( MCN(MNST6C) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNST6C + MOTVAR(6) ) = NONMTD( '~>>>XYZSOMMET' )
C
C     NC6CUM :  0 : 'min des coordonnees a l'origine'
C               1 : 'origine centree au centre du cube6'
C               2 : 'origine centree au centre du sous cube6 milieu'
C                    si NA6CUB est pair il y a une arete de plus
C                    dans la zone negative que dans la zone positive
C
C     POUR L'ATOME D'HELIUM => NC6CUM=2
C     L'ORIGINE DU REPERE NE DOIT PAS ETRE SUR UNE FACE DU 6-CUBES CAR
C     LES POIDS ET COORDONNEES DE LA FORMULE D INTEGRATION EMPLOIENT
C     NPI=64  POINTS SUR LE 6CUBES XYZUVW OBTENUE PAR PRODUIT TENSORIEL DE
C     CELLE SUR L HEXAEDRE UNITE XYZ EXACTE POUR Q1 A 8 POINTS=SOMMETS ET
C     CELLE SUR L HEXAEDRE UNITE UVW EXACTE POUR Q3 A 8 POINTS DE GAUSS
C
      IF( NC6CUM .EQ. 2 .AND. MOD(NA6CUB, 2) .EQ. 0 ) THEN
C        ORIGINE CENTREE AU CENTRE DU SOUS CUBE6 MILIEU
C        DECALAGE DE LARGEUR/2 + 1 DEMI 6CUBE CENTRAL
         TRANSLA = - AR6CUB / 2
C        TRANSLATION EFFECTIVE
         MN = MNST6C + WYZSOM
         DO 20 J=1,NBSOM
            DO 10 I=1,6
               RMCN(MN) = RMCN(MN) + TRANSLA
               MN = MN + 1
 10         CONTINUE
 20      CONTINUE
      ELSE IF( NC6CUM .EQ. 0  ) THEN
C        ORIGINE DU 6CUBE AU MIN DES COORDONNEES ACTUELLES DU 6CUBE
C        MISE A JOUR MIN ET MAX DES COORDONNEES
         CALL CADEXT( MNST6C, COIN )
C        TRANSLATION EFFECTIVE
         MN = MNST6C + WYZSOM
         DO 40 J=1,NBSOM
            DO 30 I=1,6
               RMCN(MN) = RMCN(MN) - COIN(I,1)
               MN = MN + 1
 30         CONTINUE
 40      CONTINUE
      ENDIF
C
C     GENERATION DES NUMEROS DES SOMMETS DE CHAQUE EF
C     ===============================================
C     CONSTRUCTION DU TABLEAU 'NSEF' DE CES 6-CUBES NON STRUCTURES
      NBSOEF = 2 ** NBCOOR
      WRITE(IMPRIM,*)'NOMBRE DE 6CUBES DU NOYAU     =',NA6CUB**NBCOOR
C     UNE COUCHE = NBFACES DE LA PEAU DES DIFFERENCES FINIES
C     NBFACE = 2 * NOMBRE DE CHOIX DE 5 PARMI 6
C     NBFACE = 2 * 6 = 12 FACES DANS UN 6-CUBE
      NBEF1C = NA6CUB ** (NBCOOR-1) * 12
      WRITE(IMPRIM,*)'NOMBRE DE 6CUBES PAR COUCHE   =',NBEF1C
C     NOMBRE TOTAL D'EF DU MAILLAGE
      NBEFOB = NA6CUB ** NBCOOR + NBEF1C * NC6CUB
      WRITE(IMPRIM,*)'NOMBRE TOTAL DE 6CUBES        =',NBEFOB
      MOTS   = WUSOEF + NBSOEF * NBEFOB
      CALL LXTNDC( NTLXVO, 'NSEF', 'ENTIER', MOTS   )
      CALL LXTSOU( NTLXVO, 'NSEF',  NTEF6C,  MNEF6C )
C
C     TABLEAU  NUSOEF(1..NBSOEF,1..NBEFOB)
C     NUMERO DES NBSOEF=64 SOMMETS DES NBEFOB EF DE L'OBJET
C     CONSTRUCTION DU TABLEAU DU NO DES 64 SOMMETS DES EF
C     EN 3 MORCEAUX: LES DF, LA 1-ERE COUCHE, LES AUTRES COUCHES
      MNEFDF = MNEF6C + WUSOEF
      MNEFCH = MNEFDF + NBSOEF * (NA6CUB**NBCOOR)
      CALL NSEF6C( NA6CUB, NC6CUB, NBSTCH, MCN(MNSTDF), NBEF1C,
     %             MCN(MNEFDF), MCN(MNEFCH) )
      CALL TNMCDS( 'ENTIER', NBSOMN, MNSTDF )
C
C     MISE A JOUR DU TABLEAU 'NSEF' DE CE MAILLAGE
C     TYPE DE L'OBJET : 6-CUBE vu comme un VOLUME ici => 4
      MCN( MNEF6C + WUTYOB ) = 4
C     LE TYPE INCONNU DE FERMETURE DU MAILLAGE
      MCN( MNEF6C + WUTFMA ) = -1
C     VARIABLE NBSOEF 'NOMBRE DE SOMMETS PAR EF'
C     ( 4 : 'FACE' , 8 : 'CUBE', '64 : '6-CUBES' ) ;
      MCN( MNEF6C + WBSOEF ) = NBSOEF
C     VARIABLE NBTGEF 'NOMBRE DE TANGENTES PAR EF'
C     ( 0 : '0 TG PAR EF' , 1 : '1 TG PAR SOMMET' , 2 : '2 TG PAR ARETE' ,
C       8 : '8 TG PAR FACE' ,  24 : '24 TG PAR CUBE' )  ;
      MCN( MNEF6C + WBTGEF ) = 0
C     VARIABLE NBEFOB 'NOMBRE DES EF DU PLSV'
      MCN( MNEF6C + WBEFOB ) = NBEFOB
C     variable NBEFTG 'Nombre des EF avec TG'
      MCN( MNEF6C + WBEFTG ) = 0
C     variable NBEFAP 'Nombre des EF avec POINTEUR sur EF a TG'
      MCN( MNEF6C + WBEFAP ) = 0
C     VARIABLE NUTYMA 'NUMERO DE TYPE DU MAILLAGE'
C     ( 0 : 'NON STRUCTURE' , ... )
      MCN( MNEF6C + WUTYMA ) = 0
C     LA DATE DE CREATION
      CALL ECDATE( MCN(MNEF6C) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNEF6C + MOTVAR(6) ) = NONMTD( '~>>>NSEF' )
C
C     RENUMEROTATION DES SOMMETS POUR REDUIRE LE PROFIL DE LA MATRICE
ccc      CALL RE6CUB( NTLXVO, NTEF6C, MNEF6C, MNST6C )
C     AUGMENTE LEGEREMENT LE PROFIL DE LA MATRICE! => SUPPRESSION
C
C     MISE A JOUR MIN ET MAX DES COORDONNEES
      CALL CADEXT( MNST6C, COIN )
C
C     MIN ET MAX DES COORDONNEES DU 6CUBE
      CALL MAJEXT( MNST6C )
C
      RETURN
      END
