      SUBROUTINE VOTEET( PTXYZD, XYZ, N1FEOC, NFETOI, NBFETO, VOLETO )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :   CALCUL DU VOLUME DES TETRAEDRES FACES TRIANGULAIRES NFETOI+XYZ
C -----

C ENTREES:
C --------
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C XYZ    : POINT 4-EME SOMMET POUR LES TETRAEDRES FACE+XYZ
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C NFETOI : LES FACES TRIANGULAIRES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST DIRIGE VERS L'INTERIEUR DE L'ETOILE
C          5: CHAINAGE SUR LA FACE SUIVANTE OCCUPEE OU VIDE

C SORTIES:
C --------
C NBFETO : NOMBRE DE FACES NFETOI CHAINEES A PARTIR DE NFETOI
C VOLETO : VOLUME ABSOLU DES TETRAEDRES FACE+XYZ DE L'ETOILE NFETOI
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Decembre 2017
C2345X7..............................................................012
      DOUBLE PRECISION  PTXYZD(4,*), XYZ(3), VOLETO, VOLTET
      INTEGER           NFETOI(5,*)

      VOLETO = 0D0
      NBFETO = 0

      NF1    = N1FEOC

 10   IF( NF1 .GT. 0 ) THEN

C        UNE FACE DE PLUS
         NBFETO = NBFETO + 1

C        VOLUME DU TETRAEDRE FACE NF1+XYZ
         NS1 = ABS( NFETOI(2,NF1) )
         VOLETO = VOLETO + ABS( VOLTET( PTXYZD(1,NS1),
     %                                  PTXYZD(1,NFETOI(3,NF1)),
     %                                  PTXYZD(1,NFETOI(4,NF1)),
     %                                  XYZ ) )
C        LA FACE SUIVANTE
         NF1 = NFETOI(5,NF1)
         GOTO 10

      ENDIF

      RETURN
      END
