      SUBROUTINE XYZBF11( PTXYZD, NFETOI, NBVPSI, NFVPSI,  XYZ )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C  BUT :   CALCULER LES COORDONNEES XYZ DU BARYCENTRE DES NBVPSI FACES
C  -----   DE NUMERO NFETOI

C ENTREES:
C --------
C PTXYZD : TABLEAU DES COORDONNEES DES POINTS
C          PAR POINT : X  Y  Z DISTANCE_SOUHAITEE
C N1FEOC : POINTEUR SUR LA PREMIERE FACE DE L'ETOILE
C          CHAINAGE SUIVANT DANS NFETOI(5,*)
C NPFEOC : NUMERO NFETOI DE LA PREMIERE FACE DE L'ETOILE A NE PAS TRAITER
C NFETOI : LES FACES TRIANGULAIRES DE L'ETOILE
C          1: NUMERO DU TETRAEDRE DANS NOTETR OPPOSE A CETTE FACE
C          2: NUMERO PTXYZD DU SOMMET 1 DE LA FACE
C          3: NUMERO PTXYZD DU SOMMET 2 DE LA FACE
C          4: NUMERO PTXYZD DU SOMMET 3 DE LA FACE
C             S1S2xS1S3 EST DIRIGE VERS L'INTERIEUR DE L'ETOILE
C          5: CHAINAGE SUR LA FACE SUIVANTE OCCUPEE OU VIDE

C SORTIES:
C --------
C NBFETO : NOMBRE DE FACES DE L'ETOILE
C XYZ    : 3 COORDONNEES XYZ DU BARYCENTRE DES NBVPSI FACES
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & VEULETTES SUR MER       Mars 2015
C2345X7..............................................................012
      DOUBLE PRECISION  PTXYZD(4,*), XYZ(3)
      INTEGER           NFETOI(5,*), NFVPSI(NBVPSI)

C     COORDONNEES DU BARYCENTRE DES SOMMETS DES NBVPSI FACES DE L'ETOILE
      XYZ(1) = 0D0
      XYZ(2) = 0D0
      XYZ(3) = 0D0
      NBS = 0

      DO NF = 1, NBVPSI

C        BOUCLE SUR LES 3 SOMMETS DE LA FACE NF1
         NF1 = NFVPSI( NF )
 
         DO K=1,3

C           NUMERO DU SOMMET K DE LA FACE NF1
            NS = NFETOI(1+K,NF1)

            DO L=1,3
               XYZ(L) = XYZ(L) + PTXYZD(L,NS)
            ENDDO

         ENDDO

         NBS = NBS + 3

      ENDDO

C     3 COORDONNEES DU BARYCENTRE DES BARYCENTRES DES NBVPSI FACES
      DO L=1,3
         XYZ(L) = XYZ(L) / NBS
      ENDDO

      RETURN
      END
