      SUBROUTINE XYZTOREM1( XYZ, R, S )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    A PARTIR DES 3 COORDONNEES D'UN POINT DU TORE, CALCULER
C -----    LES PARAMETRES LONGITUDE, LATIUDE DU POINT DU TORE
C          ATTENTION des PARAMETRES SONT CACHES DANS LE COMMON /S09S01/!
C
C ENTREES:
C --------
C XYZ    : 3 COORDONNEES DU POINT SUR LE TORE
C
C SORTIES:
C --------
C R,S    : COORDONNEES DU POINT DU RECTANGLE DES PARAMETRES DU TORE
C          [RAGCTO * 2 PI] x [RAPCTO * 2 PI]
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY Novembre 2011
C2345X7..............................................................012
C ATTENTION: LE COMMON SUIVANT DOIT ETRE INITIALISE dans le SP toreti.f
      DOUBLE PRECISION  DMATRI, DMATM1
      COMMON /S09S01/   DMATRI(3,4), DMATM1(3,4), RAPCTO, RAGCTO
      REAL              XYZ0(3), XYZ(3)
      INTRINSIC         SQRT
C
C     XYZ DANS LE REPERE PROPRE DU TORE
      CALL ISOMVAM1( DMATM1, XYZ, XYZ0 )
C
C     LES ANGLES dans [0, 2PI] PARAMETRES DU TORE
C     LA LONGITUDE
      CALL LONGITUD( XYZ0(1), XYZ0(2), RAGCTO, ALFA )
C
C     LA LATITUDE
      R = SQRT( XYZ0(1)**2 +  XYZ0(2)**2 ) - RAGCTO
      CALL LONGITUD( R, XYZ0(3), RAPCTO, BETA )
C
C     LES COORDONNEES DANS L'ESPACE DES PARAMETRES
C     [RAGCTO * 2 PI] x [RAPCTO * 2 PI]
      R = RAGCTO * ALFA
      S = RAPCTO * BETA
C
      RETURN
      END
