      SUBROUTINE XYZTTF( R, S, XYZ )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : A PARTIR DES 3 APPLICATIONS :
C ----- P1: TRIANGLE RECTANGLE UNITE => TRIANGLE PLAN       P1(U,V)=(R,S)
C       T : TRIANGLE RECTANGLE UNITE => TRIANGLE ALGEBRIQUE T(U,V)=(X,Y,Z)
C       F : TRIANGLE PLAN  => TRIANGLE ALGEBRIQUE  F(R,S)=(X,Y,Z)=T(P1**(-1))
C       CALCULER F(R,S)=(X,Y,Z)
C       ICI LES ARETES DES 3 COTES DU TRIANGLE SONT SUPPOSEES DROITES (P1)
C       SEUL LE SP TRNSAL PEUT EXECUTER CE SP CAR DE NOMBREUX
C       PARAMETRES SONT CACHES DANS LE COMMON /S09S01/!
C
C ENTREES:
C --------
C R,S    : LES 2 COORDONNEES DU POINT DU TRIANGLE PLAN DEFINI PAR SES
C          3 SOMMETS SELON LES LONGUEURS DES 3 COTES DU TRIANGLE ALGEBRIQUE
C
C SORTIES:
C --------
C XYZ    : LES 3 COORDONNEES DU POINT IMAGE SUR LE TRIANGLE ALGEBRIQUE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET  ANALYSE NUMERIQUE PARIS         FEVRIER 1997
C234567..............................................................012
C     ATTENTION: LE COMMON SUIVANT DOIT ETRE INITIALISE!
C                CF LE SP TRNSAL
      COMMON /S09S01/  MNCOCU, NBSOCQ(4), NUCOTQ(4), MNSOCQ(4),
     %                 XYZ4ST(3,4), XYZL(3,4), XY(4), ST(2,4), UNMOT
      REAL             XYZ(3)
C
C     (U,V) = P1**(-1) (R,S)
C     PASSAGE DES COORDONNEES DU POINT DU TRIANGLE DE SOMMETS ST
C     AUX COORDONNEES DU POINT DU TRIANGLE RECTANGLE UNITE
C     APPLICATION INVERSE DE P1: TRIANGLE RECTANGLE UNITE => TRIANGLE PLAN
C     P1(U,V)=(R,S)  <=>  P1**(-1)(R,S)=(U,V)
      V = S / ST(2,3)
      U = ( R - V * ST(1,3) ) / ST(1,2)
C
C     ( X, Y, Z ) = T( U, V )
C     PASSAGE DES COORDONNEES DU POINT DU TRIANGLE RECTANGLE UNITE
C     AUX COORDONNEES DU POINT DU TRIANGLE ALGEBRIQUE DANS R**3
      CALL XYZTTT( U, V, XYZ )
C
      RETURN
      END
