      SUBROUTINE DLFXKG( NBRDLX, NUDLFX, TGV, NTDL, LPDIAG, KG )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    PRISE EN COMPTE SUR LA MATRICE GLOBALE DES DL FIXES
C -----    DANS LE CAS DE L'ONDE COMPLEXE NLSE
C
C ENTREES:
C --------
C NBRDLX : NOMBRE DE DL FIXES EN NUMEROTATION (2,NBOEUDS)
C NUDLFX : TABLEAU DES NUMEROS DES DL FIXES
C TGV    : VALEUR IMPOSEE AUX COEFFICIENTS DIAGONAUX DES DL FIXES
C NTDL   : NOMBRE DE LIGNES ET COLONNES DE LA MATRICE KG
C LPDIAG : POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE LA MATRICE KG
C
C MODIFIE:
C --------
C KG     : MATRICE GLOBALE EN ENTREE ET SORTIE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & Saint Pierre du Perray  Aout 2011
C23456---------------------------------------------------------------012
      INTEGER           NUDLFX(NBRDLX), LPDIAG(0:NTDL)
      DOUBLE PRECISION  TGV, KG(*)
C
      DO K=1,NBRDLX
C
C        NUMERO DU DL FIXE DE 1 A NTDL
         NDL = NUDLFX( K )
C
C        NUMERO DU NOEUD DU DL FIXE DANS LE CAS DE L'ONDE COMPLEXE
C        2 DL PAR NOEUD
         NOE = (NDL+1) / 2
C
C        VALEUR IMPOSEE A TGV DU COEFFICIENT DIAGONAL NOE DE KG
         KG( LPDIAG(NOE) ) = TGV
C
      ENDDO
C
      RETURN
      END
