      SUBROUTINE DLFXBG( NBRDLX, NUDLFX, ONDEFX, TGV, NBNOMA,  ONDTGV )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    PRISE EN COMPTE SUR LE VECTEUR GLOBAL DES COMPOSANTES
C -----    DES VITESSES FIXEES
C
C ENTREES:
C --------
C NBRDLX : NOMBRE DE DL DE L'ONDE FIXES
C          ERREUR SI NBRDLX=0 CAR PAS DE CONDITION AUX LIMITES!
C NUDLFX : TABLEAU MC DES NUMEROS DES DL FIXES
C ONDEFX : TABLEAU MC DES VALEURS DES DL FIXES
C TGV    : VALEUR MULTIPLICATIVE  DES DL FIXES
C NTDL   : NOMBRE DE COMPOSANTES OU DL DE L'ONDE
C
C MODIFIE:
C --------
C ONDTGV : VALEUR DES COEFFICIENTS DU VECTEUR GLOBAL(2,NTDL/2)
C          DES DL DE L'ONDE COMPLEXE
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & Saint Pierre du Perray  Aout 2011
C23456---------------------------------------------------------------012
      INTEGER           NUDLFX(NBRDLX)
      DOUBLE PRECISION  ONDEFX(NBRDLX), TGV, ONDTGV(NBNOMA,2)
C
      DO K=1,NBRDLX
C
C        NUMERO DU DL FIXE DE 1 A NBNOMA*2 DEFINI POUR VECTEUR(2,NBNOMA)
         NDL = NUDLFX( K )
C
C        NUMERO DU NOEUD DU DL
         NOE = (NDL+1) / 2
C
C        NUMERO DE LA PARTIE REELLE 1 ou IMAGINAIRE 2
         IF( 2*NOE .EQ. NDL ) THEN
C           PARTIE IMAGINAIRE
            NPART = 2
         ELSE
C           PARTIE REELLE
            NPART = 1
         ENDIF
C
C        VALEUR FIXEE DE LA VITESSE
         ONDTGV( NOE, NPART ) = ONDEFX(K) * TGV
C
      ENDDO
C
      RETURN
      END
