      SUBROUTINE ISOSUR( KNOMOB , IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  TRACER LES ISOSURFACES DEFINIES PAR UNE FONCTION F(X,Y,Z)=Ctes
C -----  D'UN OBJET 2D OU 3D DE NOM KNOMOB APRES CALCUL
C
C ENTREE :
C --------
C KNOMOB : NOM DE L'OBJET
C
C SORTIE :
C --------
C IERR   : 0 SI PAS D'ERREUR , NON NUL SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS        MARS 1997
C23456---------------------------------------------------------------012
      IMPLICIT          INTEGER (W)
      PARAMETER         (MXTYEL=7, LIGCON=0)
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/msvaau.inc"
      include"./incl/trvari.inc"
      include"./incl/xyzext.inc"
      include"./incl/a_objet__definition.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___vecteur.inc"
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAl             RMCN(1)
      DOUBLE PRECISION DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
      CHARACTER*(*)     KNOMOB
      CHARACTER*24      NMFONC
      DOUBLE PRECISION  XYZ(3)
      DOUBLE PRECISION  DTMIN, DTMAX
      type typ_dptab
         DOUBLE PRECISION, dimension(:), pointer :: dptab
      end type typ_dptab
      type( typ_dptab ),dimension(0:1) :: dptemp

C     INITIALISATIONS POUR LA REMANENCE DES VALEURS
      MNELEM = 0
      NCAS   = 1
      NDSM   = 1
      IERR   = 0
C     LE NOMBRE DE MOTS D'UNE VARIABLE REEL2
      MOREE2 = MOTVAR(6)
C
      CALL LXLXOU( NTOBJE , KNOMOB , NTLXOB , MNLXOB )
      IF( NTLXOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR : OBJET INCONNU ' // KNOMOB
         ELSE
            KERR(1) = 'ERROR : UNKNOWN OBJECT ' // KNOMOB
         ENDIF
         CALL LEREUR
         IERR = 1
         GOTO 9000
      ENDIF
C
C     RECHERCHE DU TABLEAU DEFINITION
      CALL LXTSOU( NTLXOB , 'DEFINITION' , NTDFOB , MNDFOB )
C
C     S'IL N'EXISTE PAS RETOUR A LA DEMANDE DU NOM DE L'OBJET
      IF( NTDFOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'OBJET SANS DEFINITION:' // KNOMOB
         ELSE
            KERR(1) = 'OBJECT WITHOUT DEFINITION:' // KNOMOB
         ENDIF
         CALL LEREUR
         GOTO 9000
      ENDIF
C
C     RECHERCHE DES TABLEAUX SOMMETS NOEUDS POINTS ASSOCIES A L'OBJET
C     ADRESSAGE DES ADRESSES DES TABLEAUX ELEMENTS DE CET OBJET
      CALL TNMCDC( 'ENTIER' , 2*MXTYEL , MNELEM )
      MNTELE = MNELEM + MXTYEL
      CALL NDPGEL( NTLXOB , NTTOPO , MNTOPO ,
     %             NTPOGE , MNPOGE , NTNOEU , MNNOEU ,
     %             NBTYEL , MCN(MNTELE) , MCN(MNELEM) , IERR )
C     NTTOPO : NUMERO      DU TMS 'TOPOLOGIE' DE L'OBJET
C     MNTOPO : ADRESSE MCN DU TMS 'TOPOLOGIE' DE L'OBJET
C     NTPOGE : NUMERO      DU TMS 'XYZPOINT'    DE L'OBJET
C     MNPOGE : ADRESSE MCN DU TMS 'XYZPOINT'    DE L'OBJET
C     NTNOEU : NUMERO      DU TMS 'XYZNOEUD'    DE L'OBJET
C     MNNOEU : ADRESSE MCN DU TMS 'XYZNOEUD'    DE L'OBJET
C     NBTYEL : NOMBRE DE TYPES D'ELEMENTS DU MAILLAGE
C     NTELEM : NUMERO      DU TMS DES NBTYEL TYPES D'ELEMENTS
C     MNELEM : ADRESSE MCN DU TMS DES NBTYEL TYPES D'ELEMENTS
      IF( IERR .NE. 0 ) GOTO 10
C
C     NDPGST : CODE TRAITEMENT DES XYZ DES SOMMETS POINTS NOEUDS DU MAILLAGE
C              0 : NOEUDS=POINTS=SOMMETS
C              1 : NOEUDS=POINTS#SOMMETS
C              2 : NOEUDS#POINTS=SOMMETS
C              3 : NOEUDS#POINTS#SOMMETS
      NDPGST = MCN( MNTOPO + WDPGST )
C
C     NDIM DIMENSION EFFECTIVE DE L'ESPACE DES COORDONNEES
      CALL DIMCOO( MCN(MNPOGE+WNBPOI), MCN(MNPOGE+WYZPOI), NDIM )
      NDIMLI = NDIM
C
C     CONSTRUCTION DU VECTEUR"TEMPERATURE A PARTIR DE LA FONCTION F(X,Y,Z)
 10   CALL INVITE( 39 )
      NCVALS = 0
      CALL LIRCAR( NCVALS, NMFONC )
      IF( NCVALS .LT. 0 ) GOTO 9000
C
C     OUVERTURE DE LA FONCTION
      CALL LXNMNO( NTFONC, NMFONC, NOFONC, I )
C     NOFONC>0 SI CETTE FONCTION EXISTE
      IF( NOFONC .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'FONCTION INCONNUE: ' // NMFONC
         ELSE
            KERR(1) = 'UNKNOWN FUNCTION: ' // NMFONC
         ENDIF
         CALL LEREUR
         GOTO 10
      ENDIF
C
C     CONSTRUCTION DU TABLEAU VECTEUR"TEMPERATURE
      CALL LXTSOU( NTLXOB, 'VECTEUR"TEMPERATURE', NTVECT, MNVECT )
      IF( NTVECT .GT. 0 ) THEN
C        LE VECTEUR EST DETRUIT POUR ETRE REDECLARE
         CALL LXTSDS( NTLXOB, 'VECTEUR"TEMPERATURE' )
      ENDIF
      NBNOE = MCN( MNNOEU + WNBNOE )
      L     = WECTEU + NBNOE * MOREE2
      CALL LXTNDC( NTLXOB, 'VECTEUR"TEMPERATURE', 'MOTS', L )
      CALL LXTSOU( NTLXOB, 'VECTEUR"TEMPERATURE', NTVECT, MNVECT )
      MNX = MNNOEU + WYZNOE
      MNV = MNVECT + WECTEU
C
      DO 20 I=1,NBNOE
C
C        LES 3 PARAMETRES D'APPEL DE LA FONCTION F(X,Y,Z)
         XYZ(1) = RMCN( MNX   )
         XYZ(2) = RMCN( MNX+1 )
         XYZ(3) = RMCN( MNX+2 )
         CALL FONVAL( NOFONC, 3, XYZ,  NCODEV, RMCN(MNV) )
         IF( NCODEV .LE. 0 ) THEN
            NBLGRC(NRERR) = 1
            IF( LANGAG .EQ. 0 ) THEN
               KERR(1) = 'PB DANS LE CALCUL DE LA FONCTION ' // NMFONC
            ELSE
               KERR(1) = 'PROBLEM with COMPUTATION of FUNCTION '//NMFONC
            ENDIF
            CALL LEREUR
            GOTO 9000
         ENDIF
C        F(X,Y,Z) EST INITIALISE
         MNV = MNV + MOREE2
         MNX = MNX + 3
C
 20   CONTINUE
C
C     LE NOMBRE DE COMPOSANTES DU VECTEUR
      MCN( MNVECT + WBCOVE ) = NBNOE
C     LE NOMBRE DE VECTEURS
      MCN( MNVECT + WBVECT ) = 1
C     PAS D'INFORMATION COMPLEMENTAIRE
      MCN( MNVECT + WBCPIN ) = 0
C     LA DATE
      CALL ECDATE( MCN(MNVECT) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVECT + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
C     CONSTRUCTION DU TABLEAU LESTEMPS A L'ADRESSE MCN MNTIMES
C     NBVECT NOMBRE DE VECTEUR"VITESSEPRESSION STOCKES
      CALL LESTEMPS( KNOMOB, MNVECT, NBVECT, MNTIMES, IERR )
      IF( IERR .NE. 0 ) GOTO 9000
C
C     LA FENETRE EST EFFACEE ET LE NOM DE L'OBJET EST TRACE
CCC      CALL EFFACE
      CALL RECTEF( NRHIST )
      CALL XVEPAISSEUR( 1 )
      CALL XVTYPETRAIT( LIGCON )
      NBLGRC(NRHIST) = 1
      IF( LANGAG .EQ. 0 ) THEN
         KHIST(1) = 'OBJET: ' // KNOMOB
      ELSE
         KHIST(1) = 'OBJECT: ' // KNOMOB
      ENDIF
      CALL LHISTO
C
C     CALCUL DES TEMPERATURES MIN ET MAX ET DE LEURS NOEUDS
      CALL MXVECT( NBNOE, NDSM,   MCN(MNVECT+WECTEU),
     %             DTMIN, NOEMIN, NCAMIN, DTMAX, NOEMAX, NCAMAX )
      TMIN = REAL( DTMIN )
      TMAX = REAL( DTMAX )
C
C     TRACE DES ISOTHERMES (LIGNES EN 2D ET SURFACES EN 3D)
C     =====================================================
      MODECO = 1
      CALL TRISOT( NDIM,   KNOMOB, MODECO,
     %             NBTYEL, MNELEM, MNPOGE, NDPGST,
     %             NCAS,   NCAS,   NBNOE,
     %             0,      MCN(MNVECT+WECTEU), dptemp,
     %             TMIN,   NOEMIN, BCAMIN, TMAX, NOEMAX, NCAMAX,
     %             RMCN(MNTIMES) )
      GOTO 10
C
C     FIN DE L'EXECUTION
C     ==================
C     RETOUR AUX PARAMETRES INITIAUX
 9000 CALL XVEPAISSEUR( 1 )
      CALL XVTYPETRAIT( LIGCON )
      IF( MNELEM .GT. 0 ) CALL TNMCDS( 'ENTIER', 2*MXTYEL, MNELEM  )
      IF( MNTIMES.GT. 0 ) CALL TNMCDS( 'REEL',   NBVECT,   MNTIMES )
      RETURN
      END
