      SUBROUTINE MXFLU1( NBPNFX, NBELFX, NBCAFX, COPNFX, FLUXNP,
     %                   COIN  , FLUXMX )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LA LONGUEUR MAXIMALE DU VECTEUR FLUX NORMAL ET
C -----    L'HEXAEDRE ENGLOBANT TOUS LES POINTS
C
C ENTREES :
C ---------
C NBELFX : NOMBRE D'ELEMENTS FINIS DE CE TYPE
C NBPNFX : NOMBRE DE POINTS DE CALCUL SUR CHAQUE ELEMENT FINI
C NDIMES : DIMENSION DE L'ESPACE OU NOMBRE DE COMPOSANTES DU FLUX
C COPNFX : COORDONNEES DES POINTS DES ELEMENTS FINIS
C FLUXNP : FLUX NORMAL  DE TEMPERATURE EN TOUS LES POINTS DE TOUS LES EF
C NCAS   : NUMERO DU CAS A TRAITER
C
C MODIFIES :
C ----------
C COIN   : MIN ET MAX DES COORDONNEES DES POINTS OU SONT CALCULEES
C          LES FLUX NORMAUX DE LA TEMPERATURE
C FLUXMX : LA LONGUEUR MAXIMALE DU VECTEUR FLUX NORMAL
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS    NOVEMBRE 1994
C23456---------------------------------------------------------------012
      REAL              COPNFX(1:3,1:NBPNFX,1:NBELFX,1:2), COIN(6,2)
      DOUBLE PRECISION  FLUXNP(1:NBPNFX,1:NBELFX,1:NBCAFX)
C
C     LE PARCOURS DES COORDONNEES DES POINTS ET DES FLUXIENTS
      DO 30 K=1,NBPNFX
         DO 20 J=1,NBELFX
C
            DO 10 I=1,3
C              LE MINIMUM DES COORDONNEES
               S = COPNFX( I, K, J, 1 )
               COIN(I,1) = MIN( COIN(I,1) , S )
C              LE MAXIMUM DES COORDONNEES
               COIN(I,2) = MAX( COIN(I,2) , S )
 10         CONTINUE
C
C           LE MAXIMUM DES COMPOSANTES DU FLUX
            DO 15 NCAS = 1, NBCAFX
               FLUXMX = REAL( MAX(DBLE(FLUXMX), ABS(FLUXNP(K,J,NCAS)) ))
 15         CONTINUE
C
 20      CONTINUE
 30   CONTINUE
      END
