      SUBROUTINE MXGRA1( NBELFI , NBPIEF , NDIMES , NBCAS ,
     %                   COPIEF , DTEMPE ,
     %                   COIN   , GRADMX )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LA LONGUEUR MAXIMALE DU VECTEUR GRADIENT ET
C -----    L'HEXAEDRE ENGLOBANT TOUS LES POINTS ET POUR TOUS LES CAS
C
C ENTREES :
C ---------
C NBELFI : NOMBRE D'ELEMENTS FINIS DE CE TYPE
C NBPIEF : NOMBRE DE POINTS DE CALCUL SUR CHAQUE ELEMENT FINI
C NDIMES : DIMENSION DE L'ESPACE OU NOMBRE DE COMPOSANTES DU GRADIENT
C COPIEF : COORDONNEES DES POINTS DES ELEMENTS FINIS
C DTEMPE : GRADIENT DE TEMPERATURE EN TOUS LES POINTS DE TOUS LES EF
C NCAS   : NUMERO DU CAS A TRAITER
C
C MODIFIES :
C ----------
C COIN   : MIN ET MAX DES COORDONNEES DES POINTS OU SONT CALCULEES
C          LES GRADIENTS DE TEMPERATURE
C GRADMX : LA LONGUEUR MAXIMALE DU VECTEUR GRADIENT
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1990
C23456---------------------------------------------------------------012
      REAL              COPIEF(1:NBELFI,1:NBPIEF,1:NDIMES),COIN(6,2)
      DOUBLE PRECISION  DTEMPE(1:NBELFI,1:NBPIEF,1:NDIMES,1:NBCAS)
C
C     LE PARCOURS DES COORDONNEES DES POINTS ET DES GRADIENTS
      DO 30 K=1,NBELFI
         DO 20 J=1,NBPIEF
            DO 10 I=1,NDIMES
C              LE MINIMUM DES COORDONNEES
               COIN(I,1) = MIN( COIN(I,1) , COPIEF(K,J,I) )
C              LE MAXIMUM DES COORDONNEES
               COIN(I,2) = MAX( COIN(I,2) , COPIEF(K,J,I) )
               DO 5 NCAS = 1, NBCAS
C                 LE MAXIMUM DES COMPOSANTES DU GRADIENT DE TEMPERATURE
                  GRADMX=REAL(MAX(DBLE(GRADMX),ABS(DTEMPE(K,J,I,NCAS))))
 5             CONTINUE
 10         CONTINUE
 20      CONTINUE
 30   CONTINUE
      RETURN
      END
