      SUBROUTINE NLSEQR( NBDLIB, NBVAPR, VECPR, MGVECPR,
     %                   NCODSM, MUMG, MG,
     %                   NCODSK, MUKG, KG,
     %                   MGV0, V1, MGV1, TVMGV, TVKGV, QUORAY, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : UNE ITERATION INVERSE avec KG=(KG -VaP MG)-1 A PARTIR DU VECTEUR V0
C ----- RECUPERER LE VECTEUR V ET W=MG V APRES ITERATION INVERSE
C       CALCUL du QUOTIENT DE RAYLEIGHT, MG-NORMALISATION DU VECTEUR V1
C
C ENTREES:
C --------
C NBDLIB : NOMBRE DE DEGRES DE LIBERTE LIBRES
C NBVAPR : NOMBRE DE VALEURS PROPRES DEJA CALCULEES
C VECPR  : NBVAPR VECTEURS PROPRES DEJA CALCULES
C MGVECPR: NBVAPR MG * VECPR VECTEURS PROPRES DEJA CALCULES
C NCODSM : CODE DE STOCKAGE DE LA MATRICE GLOBALE DE CAPACITE
C          0 SI MATRICE DIAGONALE
C          1 SI MATRICE SYMETRIQUE
C MNMUMG : ADRESSE DU POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE MG
C MG     : MATRICE PROFIL GLOBALE DE CAPACITE CALCULEE
C NCODSK : CODE DE STOCKAGE DE LA MATRICE GLOBALE DE CONDUCTIVITE
C          1 SI MATRICE SYMETRIQUE
C         -1 SI MATRICE NON SYMETRIQUE
C NBRDKG : NOMBRE DE REELS DOUBLE PRECISION DE LA MATRICE GLOBALE KG
C          = NBRDKG SI MATRICE NON DIAGONALE, =NTDL SI MATRICE DIAGONALE
C MNMUKG : ADRESSE DU POINTEUR SUR LES COEFFICIENTS DIAGONAUX DE KG
C KG     : MATRICE PROFIL GLOBALE  KG - VaP MG = tL D L  FACTORISEE
C MGV0   : VECTEUR MG V0 AVANT ITERATION INVERSE
C
C SORTIES:
C --------
C V1     : VECTEUR APRES ITERATION INVERSE
C          V1 = (KG - VaP MG)**-1 MG V0 = (L D tL)**-1 (MG V0)
C          ET MG NORMALISATION PAR SQRT( TVMGV )
C MGV1   : = MG V1  MG NORMALISATION PAR SQRT( TVMGV )
C TVKGV  : tV1 (KG - VaP MG) V1
C TVMGV  : tV1 MG V1
C QUORAY : QUOTIENT DE RAYLEIGHT = tV1 (KG - VaP MG) V1 / tV1 MG V1
C IERR   : 0 PAS D'ERREUR, >0 SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET TEXAS A & M UNIVERSITY at QATAR  FEVRIER 2011
C2345X7..............................................................012
      INTEGER           MUKG(0:NBDLIB), MUMG(0:NBDLIB)
      DOUBLE PRECISION  VECPR(NBDLIB,NBVAPR), MGVECPR(NBDLIB,NBVAPR)
      DOUBLE PRECISION  KG(*), MG(*),
     %                  MGV0(NBDLIB), V1(NBDLIB), MGV1(NBDLIB),
     %                  QUORAY, TVMGV, TVKGV, S
      INTRINSIC         SQRT, ABS
C
C     V1 = (KG - VaP MG)**-1 (MG V0) = (L D tL)**-1 (MG V0)
      CALL DRCRPR( NBDLIB, NCODSK, MUKG, KG, MGV0, 3,  V1, IERR )
C
C     MG-ORTHOGONALISATION AUX NBVAPR VECTEURS PROPRES DEJA CALCULES
      CALL BORTHO( NBDLIB, NBVAPR, VECPR, MGVECPR, V1 )
C
C     LE NUMERATEUR DU QUOTIENT DE RAYLEIGHT pour V1
C     TVKGV = t(MG V0) (KG - VaP MG)**-1 (MG V0) = t(MG V0) V1
      TVKGV = 0D0
      DO I=1,NBDLIB
         TVKGV = TVKGV + MGV0(I) * V1(I)
      ENDDO
C
C     MGV1 = MG V1
      CALL MAPRVE( 0, 1D0, NBDLIB, NCODSM, MUMG, MG, V1,  MGV1 )
C
C     LE DENOMINATEUR DU QUOTIENT DE RAYLEIGHT: TVMGV = tV1 MG V1
      TVMGV = 0D0
      DO I=1,NBDLIB
         TVMGV = TVMGV + V1(I) * MGV1(I)
      ENDDO
C
C     QUORAY QUOTIENT DE RAYLEIGH: t(MG V0) (KG - VaP MG)-1 (MG V0) / tV1 MG V1
      QUORAY = TVKGV / TVMGV
C
C     MG-NORMALISATION DU VECTEUR V1 et MGV1 AVEC TVMGV=( tV1 MG V1 )**1/2
C     Ajout de la MG normalisation de V1 le 15/2/2011
      S = SQRT( ABS(TVMGV) )
      DO I=1,NBDLIB
           V1(I) =   V1(I) / S
         MGV1(I) = MGV1(I) / S
      ENDDO
C
      RETURN
      END
