      SUBROUTINE NLSEVVP( KNOMOB, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    CALCULER LES VALEURS ET VECTEURS PROPRES DE L'OPERATEUR
C -----(1) - Alfa LAPLACIEN u(X) + N(u(X)**2) u(X) = Rho E u(X)   u reel
C          POUR DES ELEMENTS FINIS LAGRANGE DE DEGRE 1 OU 2 EN 2D OU 3D
C
C REMARQUE: A partir de l'Equation Non Lineaire de SCHRODINGER (NLSE)
C il suffit de chercher les solutions de type U(t,X) = u(X) exp(iEt) dans
C (NLSE) i Rho dU(t,X)/dt - Alfa LAPLACIEN U(t,X) + N(|U|**2) U(t,X) = 0
C pour trouver (1).
C ATTENTION: Pas de TERME de ROTATION (OmegaZ=0)
C            Aucune rotation n'est prise en compte
C
C ENTREE :
C --------
C KNOMOB : NOM DE L'OBJET DE VALEURS ET VECTEURS PROPRES A CALCULER
C
C SORTIE :
C --------
C IERR   : 0 SI PAS D'ERREUR D'EXECUTION, NON NUL SINON
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET TEXAS A & M UNIVERSITY at QATAR  FEVRIER 2011
C MODIFS : ALAIN PERRONNET LJLL UPMC Paris& St Pierre du Perray Mai 2014
C23456---------------------------------------------------------------012
      DOUBLE PRECISION   PENALI
      PARAMETER         (PENALI=0D0)
      PARAMETER         (MXTYEL=7)
      PARAMETER         (MXITER=32)
      PARAMETER         (MXCN0=10)
      include"./incl/langue.inc"
      include"./incl/gsmenu.inc"
      include"./incl/ntmnlt.inc"
      include"./incl/donthe.inc"
      include"./incl/donele.inc"
      include"./incl/a_objet__topologie.inc"
      include"./incl/a_objet__definition.inc"
      include"./incl/a___xyzsommet.inc"
      include"./incl/a___xyznoeud.inc"
      include"./incl/a___xyzpoint.inc"
      include"./incl/a___npef.inc"
      include"./incl/a___contact.inc"
      include"./incl/a___vecteur.inc"
      include"./incl/a___profil.inc"
      include"./incl/a___fluxpt.inc"
      include"./incl/a___tableau1r.inc"
      include"./incl/epsvvp.inc"
      include"./incl/msvaau.inc"
      include"./incl/ponoel.inc"
      include"./incl/ctemps.inc"
      include"./incl/cnonlin.inc"
      include"./incl/cthet.inc"
      include"./incl/xyzext.inc"
      include"./incl/trvari.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1),RMCN(1),DMCN(1))
      COMMON / UNITES / LECTEU, IMPRIM, INTERA, NUNITE(29)
C
      EXTERNAL          ETTAEL
      DOUBLE PRECISION  RELMIN, EIGMIN, EIGMAX, TVMGV
      DOUBLE PRECISION  DINFO,  DCPU, DERR, DPREP, DEIGV, DMAT, DTOTAL
      DOUBLE PRECISION  VECT(MXCN0)
      INTEGER           NUMIOB(4), NUMAOB(4), MNDOEL(4), MXDOEL(4)
      INTEGER           NUM(MXCN0)
C
      DOUBLE PRECISION, allocatable, dimension(:) :: MG
      DOUBLE PRECISION, allocatable, dimension(:) :: KG
      INTEGER           IERMGALLOC, IERKGALLOC
      INTRINSIC         ALLOCATED
C
      CHARACTER*(*)     KNOMOB
      CHARACTER*20      NOMVEC
      DATA              RELMIN/-1D28/
C
      DCPU = DINFO( 'CPU' )
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10000) KNOMOB
      ELSE
         WRITE(IMPRIM,20000) KNOMOB
      ENDIF
10000 FORMAT(/1X,100('=')/
     %' RESOLUTION des VALEURS et VECTEURS PROPRES de -Alfa LAPLACIEN u
     %+ Beta u^3 = E u de l''OBJET: ',A/ 1X,100('='))
20000 FORMAT(/1X,100('=')/
     %' SOLUTION of EIGENVALUES and EIGENVECTORS of -Alfa LAPLACIAN u +
     %Beta u^3 = E u of the OBJECT: ',A/ 1X,100('='))
C
C     QUELQUES INITIALISATIONS
C     PB NON LINEAIRE DE VP:  -Alfa LAPLACIEN u + N(u**2) u = E u
      TESTNL = 5
      TEMPEL = 0D0
      ONDEPI = 0D0
      TEMPS  = 0
C
C     SEUILS POUR LES METHODES DE CALCUL DES VALEURS ET VECTEURS PROPRES
C     ------------------------------------------------------------------
C     SCALE BASE POUR L EVALUATION DU DETERMINANT POUR LES HOMOTHETIES
      SCALE = 1.D70
C
C     PRECIS: SEUIL AU DESSOUS DUQUEL LA NORME D UN VECTEUR EST SUPPOSE
C             NULLE LORS D'UNE M-ORTHONORMALISATION AUX VP PRECEDENTS
      PRECIS = 1D-10
C
C     FAST: FACTEUR PAR LEQUEL ON TRANSLATE LEGEREMENT MU POUR PRESERVER
C           LA FACTORISATION PAR LA METHODE DE CROUT
      FAST = 5.E-5
C
C     EPS: SEUIL DES FACTORISATIONS CORRECTES L D tL DES MATRICES PROFIL
      EPS = 1.E-12
C
C     TEMPS ACTUEL PAR DEFAUT
      TEMPS  = 0.0
      IERR   = 0
C
C     LE NOMBRE DE MOTS D'UNE VARIABLE REEL2
      MOREE2 = MOTVAR(6)
C
C     LE NOMBRE DE JEUX DE DONNEES
      NBJEUX = 1
C
C     TEMPS CPU INTERMEDIAIRES
      DPREP  = 0D0
      DMODR  = 0D0
C
C     PROTECTION DES ADRESSES POUR EVITER DES PROBLEMES LORS
C     DE LA DESTRUCTION DES TABLEAUX
      MNNPEF = 0
      MNTPOB = 0
      MNTAUX = 0
      MNTAEL = 0
      MNNODL = 0
      MNTHER = 0
      MNX    = 0
      MNMUMG = 0
      MNMUKG = 0
      IERMGALLOC = 1
      IERKGALLOC = 1
      DO I=1,4
         MNDOEL(I) = 0
         MXDOEL(I) = 0
      ENDDO
      NBTYEL = 0
      MOAUX  = 0
      MOTAEL = 0
      NBDLMX = 0
      NBNOMA = 0
      MOFLTO = 0
      MOFLPT = 0
      MONDLX = 0
      MNNDLX = 0
      MNVDLX = 0
      NDSM   = 1
      MNTHDL = 0
      MNDLIB = 0
      MNV    = 0
      MNEIGV = 0
      MNNINV = 0
      INIDONN= 1
      NBCOOR = 0
      MNTHET = 0
      MNRAVANT=0
      MNPIL3 = 0
      MNSOLE = 0
      MNVALS = 0
      MNVPMA = 0
      MNVENL = 0
C
C     VALEUR PROPRE MINIMALE INITIALE DES ITERATIONS DE POINT FIXE
      VAMIN0 = 0
      NBVAPR = 0
C
C     AFFICHAGE ET VERIFICATION DU NOM_DE_L'OBJET
C     ===========================================
C     RECHERCHE DU NOM DE L'OBJET DANS LE LEXIQUE DES OBJETS
      CALL LXLXOU( NTOBJE, KNOMOB, NTLXOB, MNLXOB )
C     S'IL N'EXISTE PAS RETOUR A LA DEMANDE DU NOM DE L'OBJET
      IF( NTLXOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) = 'ERREUR: OBJET INCONNU ' // KNOMOB
         ELSE
            KERR(1) = 'ERROR: UNKNOWN OBJECT ' // KNOMOB
         ENDIF
         CALL LEREUR
         CALL LXIM( NTOBJE )
         IERR = 1
         RETURN
      ENDIF
C
C     RECHERCHE DU TABLEAU DEFINITION
      CALL LXTSOU( NTLXOB,'DEFINITION', NTDFOB, MNDFOB )
C     S'IL N'EXISTE PAS RETOUR A LA DEMANDE DU NOM DE L'OBJET
      IF( NTDFOB .LE. 0 ) THEN
         NBLGRC(NRERR) = 1
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) ='ERREUR: DEFINITION INCONNUE de l''OBJET ' //KNOMOB
         ELSE
            KERR(1) ='ERROR: UNKNOWN DEFINITION for the OBJECT '//KNOMOB
         ENDIF
         CALL LEREUR
         IERR = 2
         RETURN
      ENDIF
C
C     CHOIX DE LA METHODE DE CALCUL DES VALEURS ET VECTEURS PROPRES
C     =============================================================
ccc      CALL LIMTCL( 'methvvpr' , METVVP )
ccc      IF( METVVP .LE. 0 ) GOTO 9999
C
C     LA METHODE DES ITERATIONS INVERSES AVEC TRANSLATION EST FORCEE
      METVVP = 2
C
      IF( METVVP .EQ. 1 ) THEN
C
C        CHOIX NLSEVVP: ENTREE DES BORNES DES VALEURS PROPRES A CALCULER
C        --------------------------------------------------------------
         CALL INVITE( 6 )
         NCVALS = 0
         CALL LIRRDP( NCVALS, EIGMIN )
         IF( NCVALS .LT. 0 ) THEN
C           ABANDON DE LA LECTURE DES DONNEES
            IERR = 3
            RETURN
         ENDIF
         CALL INVITE( 7 )
         NCVALS = 0
         CALL LIRRDP( NCVALS, EIGMAX )
         IF( NCVALS .LT. 0 ) THEN
C           ABANDON DE LA LECTURE DES DONNEES
            IERR = 3
            RETURN
         ENDIF
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,10001) EIGMIN, EIGMAX
         ELSE
            WRITE(IMPRIM,20001) EIGMIN, EIGMAX
         ENDIF
C
10001 FORMAT('NLSEVVP: CALCUL DES VALEURS PROPRES COMPRISES ENTRE',G14.6
     %,' ET ',G14.6)
20001 FORMAT('NLSEVVP: COMPUTATION of EIGENVALUES from ',G14.6,
     %' to ',G14.6)
C
      ELSE
C
C        CHOIX ITEINV: LECTURE DU NOMBRE DE VALEURS PROPRES A CALCULER
C        -------------------------------------------------------------
C        NBROOT > 0 CALCUL DES NBROOT PLUS PETITES VALEURS ET VECTEURS PROPRES
C               = 0 CALCUL DES VALEURS PROPRES POSITIVES INFERIEURES A EIGMAX
         EIGMAX = 0D0
C        EIGMAX: BORNE DES VALEURS PROPRES A DONNER LORSQUE NBROOT = 0
         CALL INVITE( 68 )
         NCVALS = 0
         CALL LIRENT( NCVALS, NBROOT )
         IF( NCVALS .LT. 0 ) THEN
C           ABANDON DE LA LECTURE DES DONNEES
            IERR = 3
            RETURN
         ENDIF
C
         IF( NBROOT .GT. 0 ) THEN
C
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,12002) NBROOT
            ELSE
               WRITE(IMPRIM,22002) NBROOT
            ENDIF
C
12002 FORMAT(/'NLSEVVP: NOMBRE VALEURS PROPRES A CALCULER=',I6)
22002 FORMAT(/'NLSEVVP: NUMBER of EIGENSOLUTIONS to COMPUTE=',I6)
C
         ELSE
C
C           ENTREE DE LA BORNE SUPERIEURE EIGMAX DES VALEURS PROPRES A CALCULER
C           -------------------------------------------------------------------
            CALL INVITE( 7 )
            NCVALS = 0
            CALL LIRRDP( NCVALS, EIGMAX )
            IF( NCVALS .LT. 0 ) THEN
C              ABANDON DE LA LECTURE DES DONNEES
               IERR = 3
               RETURN
            ENDIF
            NBROOT = 0
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,12003) EIGMAX
            ELSE
               WRITE(IMPRIM,22003) EIGMAX
            ENDIF
C
         ENDIF
12003 FORMAT(/'BORNE SUPERIEURE DES VALEURS PROPRES A CALCULER =',G14.6)
22003 FORMAT(/'SUPERIOR BOUNDARY of EIGENVALUES =',G14.6)
C
      ENDIF
C
C     RECHERCHE DES TABLEAUX XYZSOMMET XYZNOEUD XYZPOINT NPEF"...
C     -----------------------------------------------------------
C     ASSOCIES A L'OBJET
      CALL MIMAOB( 1,      NTLXOB, MXDOTH, NTTOPO, MNTOPO,
     %             NTXYZP, MNXYZP, NTXYZN, MNXYZN,
     %             MXTYEL, NBTYEL, MTNPEF, MNNPEF,
     %             NUMIOB, NUMAOB,
     %             NDPGST, NBOBIN, MNOBIN, NBOBCL, MNOBCL,
     %             MXDOEL, MNDOEL, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C     ICI NUMIOB CONTIENT LES 4 NUMEROS MINIMA DES OBJETS
C         NUMAOB          LES 4 NUMEROS MAXIMA DES OBJETS
C     MNDOEL LES 4 ADRESSES MCN DES TABLEAUX DES ADRESSES DES
C     TABLEAUX DECRIVANT LA THERMIQUE DE L'OBJET COMPLET
C
C     OUVERTURE DES TABLEAUX DES DONNEES NLSE DES PLSV DE L'OBJET
C     -----------------------------------------------------------
      CALL THEDON( NUMIOB, NBOBIN, MNOBIN, NBOBCL, MNOBCL,
     %             NBJEUX, MNDOEL,
     %             IEMAST, IECHMA, IECOND, IEDILA, IEVIFL, IECOET,
     %             IESOIN, IECONT, IEECHA, IESOCL, IESOPO,
     %             IETEIN, IEVIIN, IEVIANT,IECOBO,
     %             IERR )
C
      IF( IERR .GT. 0 ) THEN
         IERR = 4
         GOTO 9999
      ENDIF
C
C     INITIALISATIONS DE VARIABLES ET AFFICHAGES
C     NBCOOR : NOMBRE DE COORDONNEES DES NOEUDS=POINTS (3 ou 6)
      NBCOOR = MCN( MNXYZP + WBCOOP )
C
C     LE NOMBRE DE POINTS DU MAILLAGE DE L'OBJET
      NBPOI = MCN( MNXYZP + WNBPOI )
C
C     NDIM LA DIMENSION 2 OU 3 OU 6 DE L'ESPACE DES COORDONNEES
      CALL DIMCOO( NBPOI, MCN(MNXYZP+WYZPOI), NDIM )
C     PARTICULARITE DES 6-CUBES (3Q1C NON A TRAITER EN THERMIQUE)
      IF( NBCOOR .EQ. 6 ) THEN
         NBTYEL = 1
         NDIM   = NBCOOR
      ENDIF
C
C     NOMBRE DE NOEUDS DU MAILLAGE DE L'OBJET = NOMBRE TOTAL DE DL
      NBNOMA = MCN( MNXYZN + WNBNOE )
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10210) NDIM, NBNOMA
      ELSE
         WRITE(IMPRIM,20210) NDIM, NBNOMA
      ENDIF
10210 FORMAT(/' DIMENSION 2 OU 3 OU 6 DE L''ESPACE',T42,'=',I6/
     %' NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR',   T42,'=',I6)
20210 FORMAT(/' SPACE DIMENSION (2 or 3 or 6)',T40,'=',I6/
     %' NUMBER of COMPONENTS of each VECTOR',  T40,'=',I6)
C
C     RECUPERATION DES TABLEAUX POBA NECESSAIRES A LA
C     CONSTRUCTION DES TABLEAUX ELEMENTAIRES
      CALL TAPOBA( NBTYEL, MNNPEF, ETTAEL,
     %             MNTPOB, NBDLMX, MOAUX, NBTTEF, NOAXIS, NCODSM, IERR )
      IF( IERR .NE. 0 ) GOTO 9999
C
C     ADRESSAGE DES TABLEAUX AUXILIAIRES ET ELEMENTAIRES
      CALL TNMCDC( 'REEL2', MOAUX, MNTAUX )
C
C     LES 2 MATRICES ELEMENTAIRES ET LES NDSM VECTEURS ELEMENTAIRES
      MOTAEL = NBDLMX * (NBDLMX+1) + NBDLMX * NDSM
      CALL TNMCDC( 'REEL2', MOTAEL, MNTAEL )
C
C     LE NUMERO DES DEGRES DE LIBERTE GLOBAUX DES DL D'UN EF
      CALL TNMCDC( 'ENTIER', NBDLMX, MNNODL )
C
C     LE TENSEUR DE CONDUCTIVITE ou COEFFICIENT TEMPERATURE(Pts INTEGRATION)
      CALL TNMCDC( 'REEL2', 128, MNTHER )
C
C     LE TABLEAU DES NBCOOR COORDONNEES DES NBDLMX NOEUDS D'UN ELEMENT FINI
      CALL TNMCDC( 'REEL', NBDLMX*NBCOOR, MNX )
C
C     VECTEUR SERVANT A DEFINIR DANS THEMKB LA NON LINEARITE DU PROBLEME
      CALL TNMCDC( 'REEL2', NBNOMA, MNVENL )
      CALL AZEROD( NBNOMA, MCN(MNVENL) )
C
C     LE TABLEAU DE LA TEMPERATURE DES DL DE L'EF ACTUEL
C     ADRESSE MNTHDL CONTENUE DANS ./incl/cthet.inc POUR UN PB NON LINEAIRE
      CALL NLDATADC( NBDLMX )
C
C     CALCUL DU PROFIL DES MATRICES DE MASSE [MG] ET CONDUCTIVITE [KG(u**2)]
C     ----------------------------------------------------------------------
C     PREPARATION DE LA RESOLUTION STOCKAGE PROFIL DE KG ET MG
C     CALCUL DU PROFIL DES MATRICES ICI SYMETRIQUES NON DIAGONALES
      NCODSK = 1
      CALL TNMCDC( 'ENTIER', 1+NBNOMA, MNMUKG )
      CALL PRPRMC( MNTOPO, MCN(MNNPEF), MNXYZN, 1, NCODSK,
     %             MCN(MNMUKG), IERR )
      IF( IERR .GT. 0 ) GOTO 9999
C
C     COPIE DU TABLEAU POINTEUR (ENSUITE PEUT ETRE MODIFIE PAR LES CL)
      CALL TNMCDC( 'ENTIER', 1+NBNOMA, MNMUMG )
C
C     DECLARATION DES 2 MATRICES PROFIL SYMETRIQUE  [MG] & [KG]
C    (+1 MATRICE DE PROTECTION DANS CALVVP APRES CL => PLUS PETITE)
      NBRDKG = MCN( MNMUKG + NBNOMA )
      NBRDMG = NBRDKG
      DMAT   = NBRDKG + NBRDMG
      IF( NBRDKG .LE. 0 ) THEN
C        PLACE MEMOIRE INSUFFISANTE
         NBLGRC(NRERR) = 3
         WRITE(KERR(MXLGER-1)(1:25),'(G25.0)') DMAT
         IF( LANGAG .EQ. 0 ) THEN
            KERR(1) ='ERREUR: PLACE MEMOIRE INSUFFISANTE'
            KERR(2) = KERR(MXLGER-1)(1:25) //
     %              ' MOTS NECESSAIRES pour MG + KG'
            KERR(3) ='REDUIRE le MAILLAGE'
         ELSE
            KERR(1) ='ERROR: NOT ENOUGH MEMORY'
            KERR(2) = KERR(MXLGER-1)(1:25) //
     %               ' NECESSARY WORDS to store MG + KG'
            KERR(3) ='REDUCE the MESH'
         ENDIF
         CALL LEREUR
         IF( INTERA .LE. 1 ) CALL ARRET( 100 )
         GOTO 9999
      ENDIF
C
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,10290) NBRDKG, NBRDKG/NBNOMA
      ELSE
         WRITE(IMPRIM,20290) NBRDKG, NBRDKG/NBNOMA
      ENDIF
10290 FORMAT(' 2 MATRICES PROFIL CHACUNE DE',I15,
     %' REELS DOUBLE PRECISION'/
     %' 1/2 LARGEUR DE BANDE MOYENNE =',I9)
20290 FORMAT(' 2 SKYLINE MATRICES EACH of',I15,' DOUBLE REALS'/
     %' HALF WIDTH AVERAGE=',I9)
C
C     ALLOCATION DYNAMIQUE EN FORTRAN 90 DES MATRICES PROFIL MG et KG
C     ---------------------------------------------------------------
      WRITE(IMPRIM,*)
      WRITE(IMPRIM,*) 'ALLOCATION DEMAND  of',NBRDKG,
     %      ' DOUBLE PRECISION of the [MG] and [KG] MATRICES'
      ALLOCATE ( MG(1:NBRDKG), STAT=IERMGALLOC )
      IF( IERMGALLOC .NE. 0 ) THEN
         WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBRDKG,
     %                  ' DOUBLE PRECISION of the [MG] MATRIX'
         IERR = IERMGALLOC
         GOTO 9999
      ENDIF
      ALLOCATE ( KG(1:NBRDKG), STAT=IERKGALLOC )
      IF( IERKGALLOC .NE. 0 ) THEN
         WRITE(IMPRIM,*)'ALLOCATION ERROR   of',NBRDKG,
     %                  ' DOUBLE PRECISION of the [KG] MATRIX'
         IERR = IERKGALLOC
         GOTO 9999
      ENDIF
      WRITE(IMPRIM,*) 'ALLOCATION CORRECT of',NBRDKG,
     %                ' DOUBLE PRECISION of the [MG] and [KG] MATRICES'
      WRITE(IMPRIM,*)
C
C     SUPPRESSION DU TMS 'VECTEUR"VALEURPROPRE'
C     POUR NE PAS LES RETROUVER ET LES ACCEPTER TELLES QUE
      CALL LXTSOU( NTLXOB, 'VECTEUR"VALEURPROPRE', NTVVPR, MNVVPR )
      IF( NTVVPR .GT. 0 ) THEN
         CALL LXTSDS( NTLXOB, 'VECTEUR"VALEURPROPRE' )
      ENDIF
C
C     MXROOT: MAJORANT DU NOMBRE DE VALEURS PROPRES >NBROOT A CAUSE DES
C             VALEURS MULTIPLES OU DES VALEURS SUPERIEURES A CELLES
C             CHERCHEES
      MXROOT = MIN( 2*NBROOT, NBROOT+8 )
C
C     LES VALEURS PROPRES ET BORNES D'ERREUR
      CALL TNMCDC( 'REEL2', MXROOT+2, MNEIGV )
C
C     LES VALEURS MINIMALES ET MAXIMALES AYANT N VALEURS PROPRES AVANT ELLES
      CALL TNMCDC( 'REEL2', (1+MXROOT*2)*2, MNRAVANT )
C
C     LE NOMBRE D'ITERATIONS INVERSES  POUR CHAQUE VALEUR PROPRE
      CALL TNMCDC( 'ENTIER', MXROOT, MNNINV )
C
C     CALCUL DE LA MATRICE GLOBALE [MG(Rho)] REDUITE APRES PRISE EN COMPTE
C     DES CONDITIONS AUX LIMITES DE DIRICHLET HOMOGENES DES DL 1 A NBNOMA
C     --------------------------------------------------------------------
      IEMG = 1
      IEKG = 0
      MNTHET = 0
      CALL NLSEMK( NDIM,   NBNOMA, MNTOPO,
     %             NBTYEL, MNNPEF, NDPGST, MNTPOB, MNTAUX,
     %             MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %             MNTHER, MNTAEL, MNX,    MNVENL,
     %             IEMG,   NCODSM, NBRDMG, MNMUMG, MG,
     %             IEKG,   NCODSK, NBRDKG, MNMUKG, KG,
     %             NBRDLX, MONDLX, MNNDLX, MNVDLX,
     %             NBDLIB, MNDLIB, IERR  )
C
C     CREATION DES TABLEAUX DE TRAVAIL, DES VECTEURS PROPRES ET AUXILIAIRES
      MOTSV = NBDLIB * ( 4 + MXROOT*2 )
      CALL TNMCDC( 'REEL2', MOTSV, MNV )
      MNW    = MNV    + MOREE2 * NBDLIB
      MNDIA0 = MNW    + MOREE2 * NBDLIB
      MNDIA1 = MNDIA0 + MOREE2 * NBDLIB
      MNVV   = MNDIA1 + MOREE2 * NBDLIB
      MNWW   = MNVV   + MOREE2 * NBDLIB * MXROOT

      IF( INTERA .GE. 1 ) THEN

C        CONSTRUCTION DES DONNEES POUR LE TRACE DU VECTEUR PROPRE ACTUEL
C        ===============================================================
C        TRACE DU MODULE D'UNE ONDE COMPLEXE AUX NOEUDS DU MAILLAGE
         MODECO = 8
C        LA PALETTE ARC EN CIEL
         CALL PALCDE( 14 )

C        CADRE MAXIMAL DE L'OBJET
         CALL MIMXPT( NBCOOR, NBPOI, MCN(MNXYZP+WYZPOI), COOEXT )

C        PARAMETRES DE LA VISEE
         NOTYVI  = 0
         LORBITE = 0
         NETAXE  = 0

         IF( NDIM .EQ. 2 ) THEN
C           DECLARATION DU TABLEAU D'UN VECTEUR PROPRE AUX NOEUDS DU MAILLAGE
            CALL TNMCDC( 'REEL2', NBPOI, MNVPMA )
C           LA VISEE EN 2D
            CALL VISEE0
C           PARAMETRES DES TABLEAUX POUR LE TRACE DES ZONES DE COULEURS
C           MXSOUI : MAXIMUM D INTERVALLES DU SEGMENT UNITE
C           MXSOUI ** 2 SOUS-TRIANGLES CREES AU PLUS DANS UN TRIANGLE
            MXSOUI = 4
C           MXPIL3 : MAXIMUM DE SOUS-TRIANGLES GENERES DANS L ELEMENT REFERENCE
            MXPIL3 = 2 * MXSOUI * MXSOUI + 16
C           MAXDLE : MAXIMUM DE D.L. D UNE INTERPOLATION (CF SP INTERP)
            MAXDLE = 30
C
C           NPIL3 (3,MXPIL3) PILE DES 3 SOMMETS DE CHAQUE SOUS-TRIANGLE
            MOPIL3 = 3 * MXPIL3
            CALL TNMCDC( 'ENTIER', MOPIL3, MNPIL3 )
C
C           SOLEL (MXNOEL) SOLUTION AUX NOEUDS DE L ELEMENT DU MAILLAGE
C           FBASE (MAXDLE) VALEUR DES FONCTIONS DE BASE EN UN POINT
C           COPOE (MXPOEL,3) COORDONNEES DES POINTS DE L ELEMENT
            MOSOLE = MXNOEL+MAXDLE+MXPOEL*3
            CALL TNMCDC( 'REEL2', MOSOLE, MNSOLE )
            MNFBAS = MNSOLE + MOREE2 * MXNOEL
            MNCOPO = MNFBAS + MOREE2 * MAXDLE
C
C           MXSOMM : MAXIMUM DE SOMMETS DES SOUS-TRIANGLES DE L EF REFERENCE
            MXSOMM = ( MXSOUI + 1 ) ** 2 + 16
C           VALST (3,MXSOMM) COORDONNEES ET VALEUR DE LA SOLUTION
C           XYZSOM(3,MXSOMM) COORDONNEES DES SOMMETS DES SOUS-TRIANGLES
C           AUX SOMMETS DES SOUS-TRIANGLES (DANS R2 OU R3)
            IF( MNVALS .GT. 0 ) CALL TNMCDS( 'REEL', MOVALS, MNVALS )
            MOVALS = 6 * MXSOMM
            CALL TNMCDC( 'REEL', MOVALS, MNVALS )
            MNXYZS = MNVALS + 3 * MXSOMM

         ENDIF
      ENDIF

C     DECLARATION ET INITIALISATION D'UNE APPROXIMATION A 1D0 DU
C     VECTEUR PROPRE INITIAL POUR ( KG(Un**2) + EIGV MG ) Un+1 = 0
C     PAR LA METHODE DES ITERATIONS INVERSES AVEC TRANSLATION
C     ------------------------------------------------------------
C     ADRESSE DU VECTEUR PROPRE ACTUEL V POUR LE CALCUL DU TERME
C     NON LINEAIRE DANS LA MATRICE [KG]
      MNTHET = MNV
      MN0    = ( MNV - 1 ) / MOREE2
      DO I = 1, NBDLIB
         DMCN(MN0+I) = 1D0
      ENDDO
C
C     W0 = MG V0
      CALL MAPRVE( 0, 1D0, NBDLIB, NCODSM, MCN(MNMUMG), MG, MCN(MNV),
     %             MCN(MNW) )
C
C     CALCUL DE TVMGV = tV0 MG V0 = tV0 W0
      MN1 = ( MNW - 1 ) / MOREE2
      TVMGV = 0D0
      DO I = 1, NBDLIB
         TVMGV = TVMGV + DMCN(MN0+I) * DMCN(MN1+I)
      ENDDO
C
C     MG ORTHONORMALISATION DE V0 ET W0 = MG V0
      TVMGV = SQRT( TVMGV )
      DO I = 1, NBDLIB
         DMCN(MN0+I) = DMCN(MN0+I) / TVMGV
         DMCN(MN1+I) = DMCN(MN1+I) / TVMGV
      ENDDO
C
C     TEMPS CALCUL DE LA PREPARATION
      DPREP = DINFO( 'CPU' )
C
C     CALCUL DE LA MATRICE [KG]=[KG(tGrad Alfa Grad) + Beta MG(V0**2)]
C     REDUITE APRES PRISE EN COMPTE DES CONDITIONS AUX LIMITES HOMOGENES
C     DE DIRICHLET SUR DL 1 A NBNOMA
C     -------------------------------------------------------------------
      WRITE(IMPRIM,*)
      IF( MNDLIB .LE. 0 ) THEN
         MNDLB = 1
      ELSE
         MNDLB = MNDLIB
      ENDIF
      CALL CPSIVV( 1, NBNOMA, NBDLIB, MCN(MNDLB), NBRDLX, MCN(MNVDLX),
     %             MCN(MNV), MCN(MNVENL) )
      IEMG = 0
      IEKG = 1
      CALL NLSEMK( NDIM,   NBNOMA, MNTOPO,
     %             NBTYEL, MNNPEF, NDPGST, MNTPOB, MNTAUX,
     %             MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %             MNTHER, MNTAEL, MNX,    MNVENL,
     %             IEMG,   NCODSM, NBRDMG, MNMUMG, MG,
     %             IEKG,   NCODSK, NBRDKG, MNMUKG, KG,
     %             NBRDLX, MONDLX, MNNDLX, MNVDLX,
     %             NBDLIB, MNDLIB, IERR  )
C
C     MISE A ZERO DES COEFFICIENTS INFERIEURS A 1D-20
      DO I = 1, NBRDKG
         IF( ABS(KG(I)) .LT. 1D-20 ) KG(I) = 0D0
      ENDDO
C
C     METHODE DES ITERATIONS INVERSES AVEC TRANSLATIONS
C     =================================================
      CALL NLSEVV1( NDIM,   NBNOMA, MNTOPO, NBTYEL, MNNPEF, NDPGST,
     %              MNTPOB, MNTAUX, MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %              MNTHER, MNTAEL, MNX,    MNVENL,
     %              NCODSM, NBRDMG, MNMUMG, MG,
     %              NCODSK, NBRDKG, MNMUKG, KG,
     %              NBRDLX, MONDLX, MNNDLX, MNVDLX, NBDLIB, MNDLIB,
     %              NBROOT, MXROOT, MCN(MNRAVANT),
     %              MCN(MNDIA0), MCN(MNDIA1), MCN(MNV),    MCN(MNW),
     %              NBVAPR,MCN(MNVV),MCN(MNWW),MCN(MNEIGV),MCN(MNNINV),
     %              IERR  )

      IF( INTERA .GE. 1 ) THEN
C        TRACE DES VECTEURS PROPRES
         DO I=1,NBVAPR
            MNVELB = MNVV   + MOREE2 * NBDLIB * (I-1)
            MNVAPR = MNEIGV + MOREE2 * (I-1)
            CALL TR2DVVP( KNOMOB, NDIM, MCN(MNVAPR), NBRDLX,MCN(MNVDLX),
     %                    MNDLIB, NBDLIB, MCN(MNVELB),
     %                   NBNOMA,MCN(MNVPMA),NBTYEL,MNNPEF,NDPGST,MNXYZN,
     %                    MXSOMM, MNSOLE, MNCOPO, MXPIL3, MNPIL3,
     %                    MNVALS, MNFBAS, MNXYZS )
         ENDDO
      ENDIF
C
C     GESTION DE L'ERREUR EVENTUELLE
      IF( IERR .NE. 0 .AND. NBVAPR .LE. 0 ) GOTO 9999
C
C     ADRESSAGE DU NOUVEAU TMS VECTEUR"VALEURPROPRE
C     REMPLISSAGE A PARTIR DU TABLEAU MNVV
C     ---------------------------------------------
      NOMVEC = 'VECTEUR"VALEURPROPRE'
      CALL LXTSOU( NTLXOB, NOMVEC, NTVVPR, MNVVPR )
      IF( NTVVPR .GT. 0 ) THEN
C        LE VECTEUR EST DETRUIT POUR ETRE REDECLARE
C        AVEC LES DIMENSIONS ACTUELLES
         CALL LXTSDS( NTLXOB, NOMVEC )
      ENDIF
C
      L =  WECTEU + NBVAPR * NBNOMA * MOREE2 + NBVAPR
      CALL LXTNDC( NTLXOB, NOMVEC, 'MOTS', L )
      CALL LXTSOU( NTLXOB, NOMVEC, NTVVPR, MNVVPR )
C
C     NOMBRE DE COMPOSANTES DE CHAQUE VECTEUR PROPRE
      MCN( MNVVPR + WBCOVE ) = NBNOMA
C     NOMBRE DE VECTEURS
      MCN( MNVVPR + WBVECT ) = NBVAPR
C     NOMBRE DE VALEURS PROPRES REELLE SIMPLE PRECISION
      MCN( MNVVPR + WBCPIN ) = NBVAPR
C
C     AJOUT DES DEGRES DE LIBERTE FIXES A ZERO DE LA CONDITION
C     HOMOGENE DE DIRICHLET DANS LES VECTEURS PROPRES S'IL EN EXISTE
C     --------------------------------------------------------------
      CALL CPSIVV( NBVAPR, NBNOMA, NBDLIB, MCN(MNDLB),
     %             NBRDLX, MCN(MNVDLX),
     %             MCN(MNVV), MCN(MNVVPR+WECTEU) )
C
C     COPIE DES NBVAPR VALEURS PROPRES EN SIMPLE PRECISION
C     DANS LE TMS 'VECTEUR"VALEURPROPRE'
      MNR = MNVVPR + WECTEU + MOREE2*NBNOMA*NBVAPR
      MND = (MNEIGV+1) / MOREE2
      DO I=1,NBVAPR
         RMCN(MNR) = REAL( DMCN(MND) )
         MNR = MNR + 1
         MND = MND + 1
      ENDDO
C
C     LA DATE
      CALL ECDATE( MCN(MNVVPR) )
C     LE NUMERO DU TABLEAU DESCRIPTEUR
      MCN( MNVVPR + MOREE2 ) = NONMTD( '~>>>VECTEUR' )
C
C     AFFICHAGE DES VALEURS PROPRES ET COMPOSANTES DES VECTEURS PROPRES
C     -----------------------------------------------------------------
C     LE NOMBRE DE VALEURS PROPRES EFFECTIVEMENT CALCULEES
      NBVAPR = MCN(MNVVPR+WBVECT)
C     LE NOMBRE DE COMPOSANTES D'UN VECTEUR PROPRE
      NBNOMA   = MCN(MNVVPR+WBCOVE)
      IF( IERR .NE. 3 ) THEN
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,13000) NBVAPR
         ELSE
            WRITE(IMPRIM,23000) NBVAPR
         ENDIF
13000 FORMAT(/' Les ',I6,' VALEURS PROPRES:',/1X,80(1H=))
23000 FORMAT(/' The ',I6,' EIGENVALUES:'/1X,80(1H=))
C
         MNR = MNVVPR + WECTEU + MOREE2*NBNOMA*NBVAPR - 1
         IF( LANGAG .EQ. 0 ) THEN
            WRITE(IMPRIM,13001) (I,RMCN(MNR+I),I=1,NBVAPR)
         ELSE
            WRITE(IMPRIM,23001) (I,RMCN(MNR+I),I=1,NBVAPR)
         ENDIF
13001 FORMAT(5(' VALEUR PROPRE',I3,' =',G14.6))
23001 FORMAT(5(' EIGENVALUE',I3,' =',G14.6))
C
C        AFFICHAGE PARTIEL DES VECTEURS PROPRES
         MND = ( MNVVPR + WECTEU - 1 ) / MOREE2
         MXCVEC = MIN(MXCN0,NBNOMA)
         DO 3010 I=1,NBVAPR
            IF( LANGAG .EQ. 0 ) THEN
               WRITE(IMPRIM,13009) MXCVEC, NBNOMA, I
            ELSE
               WRITE(IMPRIM,23009) MXCVEC, NBNOMA, I
            ENDIF
            M = 0
            DO 3005 K=1,NBNOMA
C              REMPLISSAGE DANS VECT DES MXCVEC PREMIERES COMPOSANTES
C              NON NULLES DU VECTEUR PROPRE I
               IF( M .LT. MXCVEC .AND. DMCN(MND+K) .NE. 0D0 ) THEN
                  M       = M + 1
                  NUM(M)  = K
                  VECT(M) = DMCN(MND+K)
               ENDIF
 3005       CONTINUE
C           AFFICHAGE EFFECTIF DES MXCVEC PREMIERES COMPOSANTES
            WRITE(IMPRIM,13010) (NUM(K),VECT(K),K=1,MXCVEC)
            MND = MND + NBNOMA
 3010    CONTINUE
      ENDIF
C
13009 FORMAT(/I6,' PREMIERES COMPOSANTES NON NULLES DES',I8,
     %' COMPOSANTES DU VECTEUR PROPRE',I4)
23009 FORMAT(/I6,' FIRST NO NULL COMPONENTS of',I8,
     %' COMPONENTS of the EIGENVECTOR',I4)
13010 FORMAT(5(I6,':',G14.6))
C
C     COUT CALCUL DES VALEURS ET VECTEURS PROPRES
      DEIGV = DINFO( 'CPU' )
C
C     VERIFICATION QUE KG(VP**2) VP = VaP MG VP
C     =========================================
      CALL VERIFVP( NTLXOB, NDIM,   NBNOMA, MNTOPO,
     %              NBTYEL, MNNPEF, NDPGST,
     %              MNTPOB, MXPOBA, MNTAUX,
     %              MNXYZP, NUMIOB, NUMAOB, MNDOEL,
     %              MNTHER, MNTAEL, MNX,
     %              NORESO, MNMUKG, NCODSM, MG, NCODSK, KG,
     %              IERR )
C
C     COUT CALCUL DE L'ERREUR SUR LE CALCUL DES VALEURS ET VECTEURS PROPRES
      DERR = DINFO( 'CPU' )
C
C     DESTRUCTION DES MATRICES POUR REDONNER LEUR PLACE EN MC
C     =======================================================
 9999 IF(MNMUMG .GT. 0) CALL TNMCDS( 'ENTIER', NBNOMA+1, MNMUMG )
      IF(MNMUKG .GT. 0) CALL TNMCDS( 'ENTIER', NBNOMA+1, MNMUKG )
C     FREE MEMORY USED BY ARRAY VG
      IF( IERKGALLOC .EQ. 0 ) THEN
         DEALLOCATE( KG )
         IERKGALLOC = 1
      ENDIF
      IF( IERMGALLOC .EQ. 0 ) THEN
         DEALLOCATE( MG )
         IERMGALLOC = 1
      ENDIF

C     DESTRUCTION DES TABLEAUX MC INUTILES
C     ------------------------------------
      IF( MNVPMA  .GT. 0 ) CALL TNMCDS( 'REEL2',  NBPOI,    MNVPMA )
      IF( MNPIL3  .GT. 0 ) CALL TNMCDS( 'ENTIER', MOPIL3,   MNPIL3 )
      IF( MNSOLE  .GT. 0 ) CALL TNMCDS( 'REEL2',  MOSOLE,   MNSOLE )
      IF( MNVALS  .GT. 0 ) CALL TNMCDS( 'REEL',   MOVALS,   MNVALS )
      IF( MNV     .GT. 0 ) CALL TNMCDS( 'REEL2',  MOTSV,    MNV )
      IF( MNEIGV  .GT. 0 ) CALL TNMCDS( 'REEL2',  MXROOT+2, MNEIGV )
      IF( MNRAVANT.GT. 0 ) CALL TNMCDS( 'REEL2',(1+MXROOT*2)*2,MNRAVANT)
      IF( MNNINV  .GT. 0 ) CALL TNMCDS( 'ENTIER', MXROOT,   MNNINV )
      IF( MNDLIB  .GT. 0 ) CALL TNMCDS( 'ENTIER', NBNOMA,   MNDLIB )
      IF( MNTHDL  .GT. 0 ) CALL NLDATADS
      IF( MNNPEF  .GT. 0 ) CALL TNMCDS( 'ENTIER',2*MXTYEL, MNNPEF )
      DO I=1,4
         IF( MNDOEL(I) .GT. 0 .AND. MXDOEL(I) .GT. 0 ) THEN
            CALL TNMCDS( 'ENTIER', MXDOEL(I), MNDOEL(I) )
         ENDIF
      ENDDO
      IF( MNTPOB .GT. 0 ) CALL TNMCDS( 'ENTIER', NBTYEL*MXPOBA,MNTPOB )
      IF( MNTAUX .GT. 0 ) CALL TNMCDS( 'REEL2' , MOAUX , MNTAUX )
      IF( MNTAEL .GT. 0 ) CALL TNMCDS( 'REEL2' , MOTAEL, MNTAEL )
      IF( MNNODL .GT. 0 ) CALL TNMCDS( 'ENTIER', NBDLMX, MNNODL )
      IF( MNTHER .GT. 0 ) CALL TNMCDS( 'REEL2' , 128   , MNTHER )
      IF( MNVENL .GT. 0 ) CALL TNMCDS( 'REEL2' , NBNOMA, MNVENL )
      IF( MNX    .GT. 0 ) CALL TNMCDS( 'REEL'  , NBDLMX*NBCOOR, MNX )
      IF( MNNDLX .GT. 0 ) CALL TNMCDS( 'ENTIER', MONDLX, MNNDLX )
      IF( MNVDLX .GT. 0 ) CALL TNMCDS( 'REEL2' , MONDLX, MNVDLX )
C
C     GESTION DES ERREURS
C     ===================
      IF( IERR .EQ. 7 ) THEN
C        RETOUR SI MATRICE NON INVERSIBLE
         IERR = 0
         RETURN
      ENDIF
      IF( IERR .NE. 0 ) RETURN
C
C     COUT en TEMPS de CALCUL
C     -----------------------
      DPREP = DPREP - DCPU
      DEIGV = DEIGV - DCPU - DPREP
      DERR  = DERR  - DCPU - DEIGV
      DTOTAL= DINFO( 'CPU' ) - DCPU
      IF( LANGAG .EQ. 0 ) THEN
         WRITE(IMPRIM,19001) DPREP, DEIGV, DERR, DTOTAL
      ELSE
         WRITE(IMPRIM,29001) DPREP, DEIGV, DERR, DTOTAL
      ENDIF
C
19001 FORMAT(/
     %' TEMPS CALCUL DE  LA PREPARATION  =',F12.2,' SECONDES CPU'/
     %' TEMPS CALCUL DES VALEURS PROPRES =',F12.2,' SECONDES CPU'/
     %' TEMPS CALCUL DES ERREURS         =',F12.2,' SECONDES CPU'/
     %' TEMPS CALCUL TOTAL               =',F12.2,' SECONDES CPU')
29001 FORMAT(/
     %' PREPARATION TIME =',F12.2,' CPU SECONDS'/
     %' EIGENVALUES TIME =',F12.2,' CPU SECONDS'/
     %' ERRORS      TIME =',F12.2,' CPU SECONDS'/
     %' TOTAL       TIME =',F12.2,' CPU SECONDS')
C
      RETURN
      END
