      SUBROUTINE SDTHE2( NTLXOB , IAU0 , IAB , IERR )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT : CALCULER LES TEMPERATURES DANS UN SOUS-DOMAINE
C ----- PAR RESOLUTION D'UN PROBLEME DE DIRICHLET
C
C ENTREES :
C ---------
C NTLXOB : NUMERO  DU LEXIQUE DE L'OBJET SOUS-DOMAINE
C IAU0   : ADRESSE DU VECTEUR TEMPERATURE
C IAB    : ADRESSE DU SECOND MEMBRE
C
C SORTIES :
C ---------
C IERR   : 0 SI PAS D'ERREUR , NON NUL SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : PASCAL JOLY     ANALYSE NUMERIQUE UPMC PARIS  FEVRIER 1990
C23456---------------------------------------------------------------012
      IMPLICIT          INTEGER (W)
      include"./incl/gsmenu.inc"
      include"./incl/a___profil.inc"
      include"./incl/a___morse.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      COMMON / UNITES / LECTEU,IMPRIM,INTERA,NUNITE(29)
      COMMON / SOUSDO / NORESO,NTDL,NDSM,NDIM,NPIMAX
CPU      DOUBLE PRECISION  DINFO,DCPU
C
C     INITIALISATIONS
C     ===============
CPU   DCPU = DINFO( 'DELTA CPU' )
      IERR = 0
      MOREE2 = MOTVAR(6)
C
C     RESOLUTION
C     ==========
C
      IF ( NORESO .EQ. 1 ) THEN
C
C       METHODE DE CHOLESKY :
C       -------------------
C       RECHERCHE DE LA MATRICE PROFIL SYMETRIQUE
        CALL LXTSOU( NTLXOB , 'PROFIL"CONDUCTIVITE_D' ,
     %               NTPROF , MNPROF )
        NCODSA = 1
        IAMUDL = MNPROF + WPDIAG
        NTDL   = MCN( MNPROF + WBLIPR )
        LPPROF = MCN( MNPROF + WPPROF )
        MNAG   = MNPROF + LPPROF
C       LOAG   = MCN( IAMUDL + NTDL )
C       IF (NOIMPR.NE.0) WRITE(IMPRIM,10290) LOAG
C 10290   FORMAT(/,' MATRICE PROFIL DE',I10,' REELS DOUBLE PRECISION')
         CALL DRCH1D( NTDL,NCODSA,MCN(IAMUDL),MCN(MNAG),NDSM,MCN(IAB),2,
     %                MCN(IAU0) )
C
      ELSE IF(NORESO.EQ.2) THEN
C
C       METHODE DU GRADIENT CONJUGUE
C       ----------------------------
        CALL LXTSOU( NTLXOB , 'MORSE"CONDUCTIVITE_D' ,
     %               NTMORS , MNMORS )
        NTDL   = MCN(MNMORS + WBLIMO)
        LPMORS = MCN(MNMORS + WPMORS)
        MNAG   = MNMORS + LPMORS
        MNLPLI = MNMORS + WPLIGN
        MNLPCO = MNLPLI + NTDL + 1
C       LOAG = MCN(MNLPLI+NTDL)
C       IF (NOIMPR.NE.0) WRITE(IMPRIM,10291) LOAG
C 10291   FORMAT(/,' MATRICE MORSE DE',I10,' REELS DOUBLE PRECISION')
        CALL LXTSOU( NTLXOB , 'MORSE"CONDUCTIVITE_DC' ,
     %               NTMORC , MNMORC )
        LPMORC = MCN(MNMORC + WPMORS)
        MNAGC  = MNMORC + LPMORC
        MNLPLC = MNMORC + WPLIGN
        MNLPCC = MNLPLC + NTDL + 1
C       LES TABLEAUX AUXILIAIRES DE GCPRCH
        LOAUX = NTDL * 4
        MNAUX = 0
        CALL TNMCDC( 'REEL2' , LOAUX , MNAUX )
C       MNAUX1 EST L'ADRESSE MCN DU VECTEUR INITIAL X0
        MNAUX1 = MNAUX
        MNAUX2 = MNAUX1 + NTDL * MOREE2
        MNAUX3 = MNAUX2 + NTDL * MOREE2
        MNAUX4 = MNAUX3 + NTDL * MOREE2
C       MISE A ZERO DU TABLEAU AUXILIAIRE
        CALL AZEROD( LOAUX , MCN(MNAUX) )
        NBDIR = 1
        LODIR = (NTDL+1) * NBDIR * 2
        MNBDIR = 0
        CALL TNMCDC( 'REEL2' , LODIR , MNBDIR )
C       MISE A ZERO
        CALL AZEROD( LODIR , MCN(MNBDIR) )
        MNDIR  = MNBDIR
        MNADIR = MNBDIR + NTDL * NBDIR * MOREE2
        MNDAD  = MNADIR + NTDL * NBDIR * MOREE2
        MNBET  = MNDAD  + NBDIR * MOREE2
        CALL GCPRCH( NTDL , NDSM , NBDIR ,
     &               MCN(MNLPLI),MCN(MNLPCO),MCN(MNAG),MCN(IAB),
     &               MCN(MNLPLC),MCN(MNLPCC),MCN(MNAGC),
     &               MCN(MNAUX1),MCN(MNAUX2),MCN(MNAUX3),
     &               MCN(MNAUX4),MCN(MNDIR),MCN(MNADIR),
     &               MCN(MNDAD),MCN(MNBET),MCN(IAU0),IERR)
        CALL TNMCDS( 'REEL2' , LOAUX , MNAUX )
        CALL TNMCDS( 'REEL2' , LODIR , MNBDIR )
C       VERIFICATION DE LA CONVERGENCE
        IERR = 0
        IF( IERR .NE. 0 ) THEN
C          LA METHODE NE CONVERGE PAS : ABANDON DES CALCULS
           NBLGRC(NRERR) = 2
           KERR(1) = ' NON CONVERGENCE :'
           KERR(2) = ' ABANDON DE LA METHODE DU GRADIENT CONJUGUE'
C          DESTRUCTION DE LA STRUCTURE MORSE
           CALL LXTSOU( NTLXOB,'MORSE"CONDUCTIVITE_D',NTMORS,MNMORS)
           CALL LXTSDS( NTLXOB , 'MORSE"CONDUCTIVITE_D' )
C          DESTRUCTION DE LA STRUCTURE MORSE DE CONDITIONNEMENT
           CALL LXTSOU( NTLXOB,'MORSE"CONDUCTIVITE_DC',NTMORC,MNMORC)
           CALL LXTSDS( NTLXOB , 'MORSE"CONDUCTIVITE_DC' )
           IERR = 9
           GOTO 9999
        END IF
      ENDIF
C
CPU   I = NINT( DINFO( 'DELTA CPU' ) )
CPU   WRITE(IMPRIM,12000) I
CPU 12000 FORMAT(/'FIN NORMALE SDTHE2 : COUT=',I12,' SECONDES CPU'/)
      RETURN
C
C     GESTION DES ERREURS
C     ===================
 9999 IF( IERR .EQ. 2 ) THEN
C     RETOUR SI NON CONVERGENCE DU G.C.
         IERR = 0
      ENDIF
      RETURN
      END
