      SUBROUTINE TE2P1D( X,      NDSM,
     %                   NBELEM, NUELEM,
     %                   NTDL,   NUNDEL, NBPIFN,
     %                   NOOBLA, NUMILI, NUMALI, LTDELI,
     %                   NOOBSF, NUMISU, NUMASU, LTDESU,
     %                   FOMEGA, COND,   DCOND,
     %                   TEMP,   FGAMMA,
     %                   COPNFN, FLUXNP, FLUXTO,
     %                   NUEF,   NBTTEF, NBPTAR,
     %                   MOARET, MXARET, LARETE,
     %                   CPNFAF, SFLUAF, ERTHEF, H1TEEF,
     %                   REELVI, ERTHAF )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :  EF TRIANGLE LAGRANGE DE DEGRE 1
C -----  CALCUL DU FLUX NORMAL SUR CHAQUE ARETE FRONTIERE
C        CALCUL DU SAUT DU FLUX NORMAL SUR CHAQUE ARETE INTERNE
C        CALCUL DE L'ESTIMATEUR D'ERREUR (BERNARDI, METIVET, VERFURTH)
C        CALCUL DE LA NORME H1 DE LA TEMPERATURE SUR CHAQUE EF
C
C ENTREES :
C ---------
C X      : COORDONNEES X Y DES 3 SOMMETS DU TRIANGLE
C NDSM   : NOMBRE DE SECONDS MEMBRES
C NBELEM : NOMBRE D'ELEMENTS FINIS DE CE TYPE
C NUELEM : NUMERO DE L'ELEMENT FINI PARMI CEUX DE CE TYPE
C NTDL   : NOMBRE TOTAL DE DL DE TEMPERATURE POUR TOUT LE MAILLAGE
C NUNDEL : NUMERO DES NOEUDS DES ELEMENTS FINIS
C NBPIFN : NOMBRE TOTAL DE POINTS SUR LES ARETES DE L'EF OU SONT CALCULES
C          LES FLUX NORMAUX DE CHALEUR (1MILIEU DE 3 ARETES => 1*3)
C
C NOOBLA : NUMERO DES LIGNES DES ARETES DE L'EF
C NUMILI : NUMERO MINIMAL DES OBJETS LIGNES
C NUMALI : NUMERO MAXIMAL DES OBJETS LIGNES
C LTDELI : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DE THERMIQUE
C          DES OBJETS LIGNES
C
C NOOBSF : NUMERO DE L'OBJET SURFACE DE CET EF
C NUMISU : NUMERO MINIMAL DES OBJETS SURFACES
C NUMASU : NUMERO MAXIMAL DES OBJETS SURFACES
C LTDESU : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DE THERMIQUE
C          DES OBJETS SURFACES
C
C TEMP   : TEMPERATURE EN TOUS LES NOEUDS DU MAILLAGE
C FGAMMA : NDSM FLUX NORMAUX EN DONNEE (LUS DANS CE SP)
C
C NUEF   : NUMERO DE L'EF ACTUEL PARMI LA TOTALITE DES EF DE L'OBJET
C NBTTEF : NOMBRE TOTAL D'EF DE L'OBJET
C NBPTAR : NOMBRE MAXIMAL DE POINTS D'INTEGRATION PAR ARETE (MAX=3)
C
C MOARET : NOMBRE D'ENTIERS PAR ARETE DU TABLEAU LARETES
C MXARET : NOMBRE D'ARETES DECLAREES POUR LE HACHAGE ET LE TABLEAU ARETES
C LARETE : TABLEAU DE HACHAGE DES ARETES DU MAILLAGE DE L'OBJET
C          LARETE(1,I)= NO DU 1-ER  SOMMET DE L'ARETE
C          LARETE(2,I)= NO DU 2-EME SOMMET > 1-ER  SOMMET
C          LARETE(3,I)= CHAINAGE HACHAGE SUR ARETE SUIVANTE
C          LARETE(4,I)= NUMERO DU 1-ER  TOUQ CONTENANT CETTE ARETE
C                       >0 SI ARETE   DIRECTE DANS CE TOUQ
C                       <0 SI ARETE INDIRECTE DANS CE TOUQ
C          SI L'ARETE APPARTIENT A 2 TOUQ ALORS
C          LARETE(5,I)= NUMERO DU 2-EME TOUQ CONTENANT CETTE ARETE
C                       >0 SI ARETE   DIRECTE DANS CE TOUQ
C                       <0 SI ARETE INDIRECTE DANS CE TOUQ
C                       =0 SI ARETE APPARTENANT A UN SEUL TOUQ
C          LARETE(6,I)= NUMERO DANS LARETE DE L'ARETE SUIVANTE
C                       SOIT DANS LE CHAINAGE D'UNE LIGNE J ENTRE NUMILF ET NUMX
C                       SOIT DANS LE CHAINAGE DES ARETES FRONTALIERES
C                       0 SI C'EST LA DERNIERE
C
C          L1ARFR = NUMERO DE LA PREMIERE ARETE CHAINEE FRONTALIERE DANS LARETE
C          L1ARIN = NUMERO DE LA PREMIERE ARETE CHAINEE INTERFACE   DANS LARETE
C          L1LGFR(J)  = NUMERO DE LA PREMIERE ARETE CHAINEE DE LA LIGNE J
C                       POUR J COMPRIS ENTRE NUMILF ET NUMXLF
C REELVI : IDENTIFICATEUR POUR INDIQUER LA NON INITIALISATION D'UN REEL
C
C SORTIES:
C --------
C COPNFN : 2 COORDONNEES DES NBPIFN POINTS ET DE LA NORMALE SUR LES
C          ARETES DES EF OU SONT CALCULES LES FLUX NORMAUX DE TEMPERATURE
C FLUXNP : FLUX NORMAL EN LES NBPIFN POINTS DES ARETES DES EF DE CE TYPE
C FLUXTO : FLUX NORMAL SOMME SUR CHAQUE LIGNE DE L'OBJET
C CPNFAF : 3 COORDONNEES DES POINTS D'INTEGRATION ET NORMALES SUR LES ARETES
C SFLUAF : 2 FLUX NORMAUX EN LES POINTS D'INTEGRATION SUR LES ARETES
C ERTHEF : ERREUR L2 A POSTERIORI SUR CHAQUE EF
C H1TEEF : NORME H1 DE LA TEMPERATURE SUR CHAQUE EF ET POUR CHAQUE CAS
C REELVI : TEMOIN DE NON UTILISATION D'UNE VARIABLE DE ERTHAF
C ERTHAF : ERREUR L2 A POSTERIORI SUR CHAQUE ARETE DES EF
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1995
C23456---------------------------------------------------------------012
      include"./incl/donthe.inc"
      include"./incl/cthet.inc"
      include"./incl/cnonlin.inc"
C
      COMMON / UNITES / LECTEU, IMPRIM, NUNITE(30)
      DOUBLE PRECISION  REELVI
      DOUBLE PRECISION  TEMP(NTDL,NDSM),
     %                  FOMEGA(NDSM),
     %                  COND(6),
     %                  DCOND(3,6),
     %                  DREM(3),
     %                  TPPTDP(3,3),
     %                  FGAMMA(NDSM,1),
     %                  ECHANG(1),
     %                  FLUXTO(NUMILI:NUMALI,1:NDSM),
     %                  FLUXNP(NBPIFN,NBELEM,NDSM),
     %                  SFLUAF(1:2,1:NBPTAR,1:MXARET,1:NDSM),
     %                  ERTHAF(1:MXARET,1:NDSM),
     %                  ERTHEF(1:NBTTEF,1:NDSM),
     %                  H1TEEF(1:NBTTEF,1:NDSM)
      DOUBLE PRECISION  GL(3), DN(2), FLUXPT(3), XYZ(3)
      DOUBLE PRECISION  X21, Y21, X31, Y31, X32, Y32, DELTA, DELTA2,
     %                  H, HAR, EC, EF, S, C1, C2, C3,
     %                  TEMPRE(3), VITEFL(2)
C
      REAL              X(3,2),
     %                  COPNFN(3,NBPIFN,NBELEM,2),
     %                  CPNFAF(1:3,1:NBPTAR,1:MXARET,1:2)
C
      INTEGER           LARETE(1:MOARET,1:MXARET)
      INTEGER           NOOBLA(3)
      INTEGER           LTDESU(1:MXDOTH,NUMISU:NUMASU)
      INTEGER           LTDELI(1:MXDOTH,NUMILI:NUMALI)
      INTEGER           NUNDEL(NBELEM,3)
      INTEGER           NOSA(2)
C
C     LA MATRICE JACOBIENNE DF DE L'APPLICATION EF REFERENCE SUR EF COURANT
      X21 = X(2,1) - X(1,1)
      X31 = X(3,1) - X(1,1)
      X32 = X(3,1) - X(2,1)
C
      Y21 = X(2,2) - X(1,2)
      Y31 = X(3,2) - X(1,2)
      Y32 = X(3,2) - X(2,2)
C
      DELTA = X21 * Y31 - X31 * Y21
C
C     CONTRIBUTION DES ARETES DE CET EF NUEF A L'ESTIMATEUR D'ERREUR
C     ==============================================================
      H      = 0D0
      LIBREF = MXARET
      NUPTF0 = 0
      DO 100 K=1,3
C
C        L'ARETE EST ELLE SUR UNE LIGNE UTILISATEUR?
         NL     = NOOBLA( K )
C        A PRIORI PAS DE F GAMMA OU FLUX NORMAUX EN DONNEE
         LIFGAM = 0
C        A PRIORI PAS DE COEFFICIENT D'ECHANGE EN DONNEE
         LIECHA = 0
CCCC
CCCC        A PRIORI PAS DE CONTACT (TEMPERATURE IMPOSEE) SUR CETTE ARETE
CCC         LICONT = 0
CCCC
CCCC        L'ARETE A T ELLE SA TEMPERATURE IMPOSEE?
CCC         IF( NL .GT. 0 ) THEN
CCC            IF( LTDELI(LPCONT,NOOBLA(K)) .GT. 0 ) THEN
CCCC              UN TABLEAU CONTACT EXISTE POUR CETTE LIGNE
CCCC              LE FLUX SUR CETTE ARETE NE DOIT PAS ETRE CALCULE
CCCC              POUR L'ESTIMATEUR D'ERREUR
CCC               LICONT = 1
CCC            ENDIF
CCC         ENDIF
C
C        LE NUMERO DES POINTS DU COTE DE L'ARETE K DU TRIANGLE
         IF( K .NE. 3 ) THEN
            K1 = K + 1
         ELSE
            K1 = 1
         ENDIF
C
C        CALCUL DES COORDONNEES DU POINT MILIEU DE L'ARETE
         GL(1) = ( X(K,1) + X(K1,1) ) * 0.5
         GL(2) = ( X(K,2) + X(K1,2) ) * 0.5
C
C        LE VECTEUR NORMAL UNITAIRE A L'ARETE
         DN(1) = X(K1,2) - X(K ,2)
         DN(2) = X(K ,1) - X(K1,1)
C        LA LONGUEUR DE L'ARETE K DE CET EF
         HAR   = SQRT( DN(1)**2 + DN(2)**2 )
         DN(1) = DN(1) / HAR
         DN(2) = DN(2) / HAR
C
C        LA LONGUEUR DE L'ARETE MAXIMALE
         H = MAX( H, HAR )
C
C        RECHERCHE DU NUMERO DE CETTE ARETE DANS LE TABLEAU LARETE
         NOSA(1) = NUNDEL( NUELEM, K  )
         NOSA(2) = NUNDEL( NUELEM, K1 )
         IF( NOSA(1) .GT. NOSA(2) ) THEN
            L       = NOSA(1)
            NOSA(1) = NOSA(2)
            NOSA(2) = L
         ENDIF
         CALL HACHAG( 2, NOSA, MOARET, MXARET, LARETE, 3,
     &                LIBREF, NOARE )
         IF( NOARE .LE. 0 ) THEN
C           ARETE NON RETROUVEE
            WRITE(IMPRIM,*) 'ERREUR TE2P1D: ARETE ',NOSA,
     %                      ' NON RETROUVEE DANS LARETE'
            IERR = 1
            RETURN
         ENDIF
C
C        NOMBRE D'EF CONTENANT CETTE ARETE
         IF( LARETE(5,NOARE) .NE. 0 ) THEN
            NBEFAR = 2
         ELSE IF( LARETE(4,NOARE) .NE. 0 ) THEN
            NBEFAR = 1
         ELSE
C           ARETE NON RETROUVEE
            WRITE(IMPRIM,*)'ERREUR TE2P1D: ARETE ',NOSA,' DANS AUCUN EF'
            IERR = 1
            RETURN
         ENDIF
C
C        CETTE ARETE A T ELLE ETE VUE ?
         IF( ERTHAF(NOARE,1) .EQ. REELVI ) THEN
C           NON: ARETE VUE POUR LA PREMIERE FOIS
            NBVUAR = 0
         ELSE
            NBVUAR = 1
         ENDIF
C
C        RECHERCHE DU TENSEUR SYMETRIQUE DE CONDUCTIVITE AU SOMMET L
C        LES 2 COORDONNEES DU SOMMET EN DOUBLE PRECISION
         GL(3) = 0D0
         CALL RECOND( 3, NOOBSF, 3, GL,
     %                LTDESU(LPCOND,NOOBSF), COND )
C        DIVISION PAR DELTA POUR CALCULER LE FLUX AU MILIEU DE L'ARETE
         C1 = COND(1) / DELTA
         C2 = COND(2) / DELTA
         C3 = COND(3) / DELTA
C
C        LES COORDONNEES DU POINT OU EST CALCULE LE FLUX NORMAL
         NUPTFN = NUPTF0 + 1
         COPNFN( 1, NUPTFN, NUELEM, 1 ) = REAL( GL(1) )
         COPNFN( 2, NUPTFN, NUELEM, 1 ) = REAL( GL(2) )
         COPNFN( 3, NUPTFN, NUELEM, 1 ) = 0
C
C        LES COMPOSANTES DU VECTEUR NORMAL OU EST CALCULE LE FLUX NORMAL
         COPNFN( 1, NUPTFN, NUELEM, 2 ) = REAL( DN(1) )
         COPNFN( 2, NUPTFN, NUELEM, 2 ) = REAL( DN(2) )
         COPNFN( 3, NUPTFN, NUELEM, 2 ) = 0
C
         IF( NBVUAR .EQ. 0 ) THEN
C           ARETE VUE POUR LA PREMIERE FOIS
C           INITIALISATION DES COORDONNEES DU POINT DE CALCUL
            CPNFAF( 1, 1, NOARE, 1 ) = REAL( GL(1) )
            CPNFAF( 2, 1, NOARE, 1 ) = REAL( GL(2) )
            CPNFAF( 3, 1, NOARE, 1 ) = 0
C
C           LES COMPOSANTES DU VECTEUR NORMAL OU EST CALCULE LE FLUX NORMAL
            CPNFAF( 1, 1, NOARE, 2 ) = REAL( DN(1) )
            CPNFAF( 2, 1, NOARE, 2 ) = REAL( DN(2) )
C           PROTECTION DE HAR LA LONGUEUR DE L'ARETE
            CPNFAF( 3, 1, NOARE, 2 ) = REAL( HAR )
C
C           CONTRIBUTION DE F GAMA SUR L'ARETE
            IF( NL .GT. 0 ) THEN
               XYZ(1) = REAL( GL(1) )
               XYZ(2) = REAL( GL(2) )
               XYZ(3) = 0
               IF( LTDELI(LPSOUR,NOOBLA(K)) .GT. 0 ) THEN
C                 UN TABLEAU SOURCE (FLUX NORMAL) EXISTE POUR CETTE LIGNE
                  LIFGAM = 1
C                 RECHERCHE DU FLUX NORMAL AU POINT D'INTEGRATION NUMERIQUE
                  CALL RESOUR( 2, NOOBLA(K), 3, XYZ,
     %                         LTDELI(LPSOUR,NOOBLA(K)), FGAMMA(1,1))
               ENDIF
C
               IF( LTDELI(LPECHA,NOOBLA(K)) .GT. 0 ) THEN
C                 UN TABLEAU ECHANGE EXISTE POUR CETTE LIGNE
                  LIECHA = 1
C                 CALCUL DU COEFFICIENT D'ECHANGE SUR CETTE ARETE
                  CALL REECHA( 2,NOOBLA(K), 3, XYZ,
     %                         LTDELI(LPECHA,NOOBLA(K)), ECHANG(1) )
               ENDIF
            ENDIF
         ENDIF
C
C        LES 3 COEFFICIENTS DU FLUX AU MILIEU DE L'ARETE
         FLUXPT(1) = DN(1) * (-C1*Y32+C2*X32) + DN(2) * (-C2*Y32+C3*X32)
         FLUXPT(2) = DN(1) * ( C1*Y31-C2*X31) + DN(2) * ( C2*Y31-C3*X31)
         FLUXPT(3) = DN(1) * (-C1*Y21+C2*X21) + DN(2) * (-C2*Y21+C3*X21)
C
         DO 90 N=1,NDSM
C
C           LE FLUX NORMAL AU POINT MILIEU DE CETTE ARETE (FLUX CONSTANT)
            S = 0D0
            DO 30 I=1,3
               S = S - FLUXPT(I) * TEMP( NUNDEL(NUELEM,I), N )
 30         CONTINUE
            FLUXNP( NUPTFN, NUELEM, N ) = S
C
C           LA CONTRIBUTION AUX FLUX NORMAUX DE L'ARETE K DE L'EF
            IF( NL .GT. 0 ) THEN
               FLUXTO( NL, N ) = FLUXTO( NL, N ) - S * HAR
            ENDIF
C
C           TEMOIN DE PASSAGE SUR CETTE ARETE (REELVI EST REMPLACE)
            ERTHAF(NOARE,N) = 0D0
C
C           FLUX NORMAL AU MILIEU DE L'ARETE NOARE POUR LE CAS N
            SFLUAF( 1+NBVUAR, 1, NOARE, N ) = S
C
            IF( NBEFAR .EQ. 2 .AND. NBVUAR .EQ. 1 ) THEN
C              ARETE COMMUNE A 2 EF VUE POUR LA SECONDE FOIS
C              LE SAUT EST AVEC + CAR NORMALES DANS DES SENS OPPOSES
C              ET LA CONTRIBUTION A L'ERREUR L2 DE L'ARETE
               ERTHAF(NOARE,N) = HAR * ABS(  SFLUAF(2,1,NOARE,N)
     %                                     + SFLUAF(1,1,NOARE,N) )
            ENDIF
C
            IF( NBEFAR .EQ. 1 ) THEN
C              ARETE FRONTALIERE
               EC = 0D0
               IF( LIECHA .NE. 0 ) THEN
C                 CALCUL DE ECHANGE(BL) * [PA(BL)] * TEMPERATURE(ARETE)
                  EC = (TEMP( NUNDEL(NUELEM,K ), N ) +
     %                  TEMP( NUNDEL(NUELEM,K1), N )) * ECHANG(1)*0.5D0
               ENDIF
C
               EF = 0D0
               IF( LIFGAM .NE. 0 ) THEN
C                 F GAMMA AU POINT D'INTEGRATION MILIEU ARETE ET POUR LE CAS N
                  EF = FGAMMA(N,1)
               ENDIF
C
C              || F GAMMA - G TEMP - D COND D TEMP || L2(ARETE)
C              LE POIDS * NORME DU VECTEUR NORMAL A DGL
               ERTHAF(NOARE,N) = ERTHAF(NOARE,N) + HAR *
     %                ABS( EF - EC + SFLUAF( 1+NBVUAR, 1, NOARE, N ) )
            ENDIF
C
 90      CONTINUE
C
C        MISE A JOUR DU NUMERO DU DERNIER POINT OU EST CALCULE LE FLUX NORMAL
         NUPTF0 = NUPTF0 + 1
 100  CONTINUE
C
C     CONTRIBUTION DE LA SURFACE DE CET EF NUEF A L'ESTIMATEUR D'ERREUR
C     =================================================================
C     INITIALISATION DE L'ESTIMATEUR D'ERREUR SUR CET EF POUR LES NDSM CAS
      DO 105 N=1,NDSM
         ERTHEF(NUEF,N) = 0D0
 105  CONTINUE
C
C     LE CALCUL DU TABLEAU  INTEGRALE( TP P + TDP DP ) POUR LA NORME H1
C     DE LA TEMPERATURE
      DELTA2 = DELTA * 2
      C1 = DELTA / 12D0
      C2 = DELTA / 24D0
      TPPTDP(1,1) = C1 + (X32*X32 + Y32*Y32) / DELTA2
      TPPTDP(1,2) = C2 - (X32*X31 + Y32*Y31) / DELTA2
      TPPTDP(1,3) = C2 + (X32*X21 + Y32*Y21) / DELTA2
      TPPTDP(2,2) = C1 + (X31*X31 + Y31*Y31) / DELTA2
      TPPTDP(2,3) = C2 - (X31*X21 + Y31*Y21) / DELTA2
      TPPTDP(3,3) = C1 + (X21*X21 + Y21*Y21) / DELTA2
C     LE RESTE PAR SYMETRIE
      TPPTDP(2,1) = TPPTDP(1,2)
      TPPTDP(3,1) = TPPTDP(1,3)
      TPPTDP(3,2) = TPPTDP(2,3)
C
C     A PRIORI PAS DE SOURCE DE CHALEUR EN DONNEE
      LIFOME = 0
C
      DO 180 L=1,3
C
C        LES 2 COORDONNEES DOUBLE PRECISION DU SOMMET L
         C1 = X(L,1)
         C2 = X(L,2)
C
         IF( LTDESU(LPSOUR,NOOBSF) .GT. 0 ) THEN
C           IL EXISTE UN TABLEAU SOURCE POUR CETTE SURFACE
            LIFOME = 1
C           LA VALEUR DES NDSM SOURCES SURFACIQUES EN CE POINT
            XYZ(1) = C1
            XYZ(2) = C2
            XYZ(3) = 0D0
            CALL RESOUR( 3, NOOBSF, 3, XYZ,
     %                   LTDESU(LPSOUR,NOOBSF), FOMEGA )
         ENDIF
C
C        CALCUL DU "LAPLACIEN" DE LA TEMPERATURE AU POINT BL
C        ICI PAS DE CONTRIBUTION DUE A DDP = 0
C
C        RECHERCHE DU GRADIENT DU TENSEUR SYMETRIQUE DE CONDUCTIVITE
C        AU POINT D'INTEGRATION L
         IF( LTDESU(LPDCON,NOOBSF) .GT. 0 ) THEN
            XYZ(1) = C1
            XYZ(2) = C2
            XYZ(3) = 0D0
            CALL REDCON( 3, NOOBSF, 3, XYZ,
     %                   LTDESU(LPDCON,NOOBSF),DCOND )
C           DCOND(i,j) = D/DXi CONDUCTIVITE j  1:11, 2:21, 3:22, ...
            C1 = DCOND(1,1) + DCOND(2,2)
            C2 = DCOND(1,2) + DCOND(2,3)
            DREM(1) = (C2*X32 - C1*Y32) / DELTA
            DREM(2) = (C1*Y31 - C2*X31) / DELTA
            DREM(3) = (C2*X21 - C1*Y21) / DELTA
         ELSE
            DREM(1) = 0D0
            DREM(2) = 0D0
            DREM(3) = 0D0
         ENDIF
C
         DO 140 N=1,NDSM
            S = 0D0
C
C           LE LAPLACIEN DE LA TEMPERATURE AU SOMMET L = POINT D'INTEGRATION L
            DO 130 I=1,3
               TEMPRE( I ) = TEMP( NUNDEL(NUELEM,I), N )
               S = S + DREM(I) * TEMPRE( I )
 130        CONTINUE
C
C           LA CONTRIBUTION DE FOMEGA (SOURCE SURFACIQUE) ET DU LAPLACIEN
C           A L'ESTIMATEUR D'ERREUR EN CE POINT D'INTEGRATION
            IF( LIFOME .NE. 0 ) S = S + FOMEGA(N)
C
C           LA CONTRIBUTION EVENTUELLE DE - VITESSE * GRADIENT TEMPERATURE
C           ACTUELLEMENT CE TERME EST SOUSTRAIT DU SECOND MEMBRE + POINT FIXE
            IF( LTDESU(LPVIFL,NOOBSF) .GT. 0 ) THEN
               TEMPEL = TEMPRE(L)
               XYZ(1) = C1
               XYZ(2) = C2
               XYZ(3) = 0D0
               CALL REVIFL( 3, NOOBSF, 2, 3, XYZ,
     %                      LTDESU(LPVIFL,NOOBSF), VITEFL )
               S = S - ( VITEFL(1) * ( Y31 * ( TEMPRE(2) - TEMPRE(1) )
     %                               - Y21 * ( TEMPRE(3) - TEMPRE(1) ) )
     %                 + VITEFL(2) * ( X21 * ( TEMPRE(3) - TEMPRE(1) )
     %                               - X31 * ( TEMPRE(2) - TEMPRE(1) ) )
     %                 ) / DELTA
            ENDIF
C
C           L'INTEGRALE DU CARRE SUR LE TRIANGLE
            ERTHEF(NUEF,N)= ERTHEF(NUEF,N) + S * S * DELTA / 6D0
 140     CONTINUE
C
 180  CONTINUE
C
C     LE PRODUIT PAR H LE DIAMETRE DE L'EF ET LA RACINE CARREE
      DO 190 N=1,NDSM
         ERTHEF(NUEF,N) = SQRT( ERTHEF(NUEF,N) ) * H
 190  CONTINUE
C
C     LA NORME H1 DE LA TEMPERATURE SUR TOUT LE MAILLAGE
      DO 240 N=1,NDSM
         S = 0D0
         DO 230 I=1,3
            DO 220 J=1,3
               S = S + TPPTDP(I,J) * TEMP( NUNDEL(NUELEM,I), N ) *
     %                               TEMP( NUNDEL(NUELEM,J), N )
 220        CONTINUE
 230     CONTINUE
C        LA CONTRIBUTION DE CET EF A LA NORME H1 DE LA TEMPERATURE
         H1TEEF(NUEF,N) = SQRT( S )
 240  CONTINUE
      END
