      SUBROUTINE TF1LAG( X,      NDSM,   NBELEM, NUELEM,
     %                   NTDL,   NBPOLY, NUNDEL, NBPIFN,
     %                   NOOBPS, NUMIPO, NUMAPO,
     %                   NOOBLA, NUMILI, NUMALI, LTDELI,
     %                   IDPSMT, DPSOMT, TEMP,   FLUXPT,
     %                   COPNFN, FLUXNP, FLUXTO )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     CALCUL DU FLUX NORMAL AUX 2 SOMMETS DE L'EF 1D LAGRANGE
C -----
C
C ENTREES:
C --------
C X      : COORDONNEE X DES NBPOLY POINTS DE L'ELEMENT FINI
C NDSM   : NOMBRE DE SECONDS MEMBRES
C NBELEM : NOMBRE D'ELEMENTS FINIS DE CE TYPE
C NUELEM : NUMERO DE L'ELEMENT FINI PARMI CEUX DE CE TYPE
C NTDL   : NOMBRE TOTAL DE DL DE TEMPERATURE POUR TOUT LE MAILLAGE
C NBPOLY : NOMBRE DE POLYNOMES = NOMBRE DE NOEUDS DE L'EF
C NUNDEL : NUMERO DES NOEUDS DES ELEMENTS FINIS
C
C NBPIFN : =2 NOMBRE DE SOMMETS DE L'EF OU SONT CALCULES LES FLUX DE CHALEUR
C
C NOOBPS : NUMERO DES POINTS DES 2 SOMMETS DE L'EF
C NUMIPO : NUMERO MINIMAL DES OBJETS POINTS
C NUMAPO : NUMERO MAXIMAL DES OBJETS POINTS
C
C NOOBLA : NUMERO DE L'OBJET LIGNE DE CET EF
C NUMILI : NUMERO MINIMAL DES OBJETS LIGNES
C NUMALI : NUMERO MAXIMAL DES OBJETS LIGNES
C LTDELI : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DE THERMIQUE
C          DES OBJETS LIGNES
C
C IDPSMT : IDPSMT(K) ADRESSE DANS DPSOMT DE LA 1-ERE VARIABLE DU
C          SOMMET K DANS DPSOMT
C DPSOMT : DPSOMT(J,K)=DPSOMT(J,IDPSMT(K))
C          DERIVEE DE LA J-EME FONCTION DE BASE AU K-EME SOMMET
C          DE L EF DE REFERENCE LIGNE
C
C TEMP   : TEMPERATURE EN TOUS LES NOEUDS DU MAILLAGE
C FLUXPT : TABLEAU AUXILIAIRE DE NBPOLY REELS DOUBLE PRECISION
C
C SORTIES:
C --------
C COPNFN : COORDONNEE DES NBPIFN POINTS ET DE LA NORMALE SUR LES
C          SOMMETS DES EF OU SONT CALCULES LES FLUX NORMAUX DE TEMPERATURE
C FLUXNP : FLUX NORMAL EN LES NBPIFN POINTS DES SOMMETS DES EF DE CE TYPE
C FLUXTO : FLUX NORMAL SOMME SUR CHAQUE POINT DE L'OBJET
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET LJLL UPMC & St PIERRE du PERRAY     JUIN 2009
C23456---------------------------------------------------------------012
      include"./incl/donthe.inc"
      include"./incl/ctemps.inc"
      include"./incl/cthet.inc"
      include"./incl/cnonlin.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1), RMCN(1), DMCN(1))
C
      DOUBLE PRECISION  FLUXPT(NBPOLY),
     %                  TEMP(NTDL,NDSM),
     %                  COND(6)
      DOUBLE PRECISION  D, S, DF, DF1, DN, DPSOMT(*), GL(3)
      DOUBLE PRECISION  FLUXTO(NUMIPO:NUMAPO,1:NDSM),
     %                  FLUXNP(NBPIFN,NBELEM,NDSM)
      REAL              X(NBPOLY),
     %                  COPNFN(3,NBPIFN,NBELEM,2)
      INTEGER           NOOBPS(2)
      INTEGER           LTDELI(1:MXDOTH,NUMILI:NUMALI)
      INTEGER           NUNDEL(NBELEM,NBPOLY)
      INTEGER           IDPSMT(2)
C
      DO 100 K=1,2
C
C        LE SOMMET K EST IL UN POINT?
         NP = NOOBPS( K )
C
         DO 90 N=1,NDSM
C
            IF( MNTIME .GT. 0 ) THEN
C              LE TEMPS DU VECTEUR TEMPERATURE N EST MIS DANS LE COMMON CTEMPS
               TEMPS = RMCN(MNTIME+N)
            ENDIF
C
C           LE DEBUT DU TABLEAU DE LA DERIVEE DES POLYNOMES AU SOMMET K
            MNDPA = IDPSMT( K ) + NBPOLY
C
C           RECUPERATION DE LA TEMPERATURE AU SOMMET K
            TEMPEL = TEMP( NUNDEL(NUELEM,K), N )
C
C           RECHERCHE DU TENSEUR SYMETRIQUE DE CONDUCTIVITE AU SOMMET K
            GL(1) = X(K)
            GL(2) = 0D0
            GL(3) = 0D0
            CALL RECOND( 2, NOOBLA, 3, GL,
     %                   LTDELI(LPCOND,NOOBLA), COND )
C
C           LES COORDONNEES DU POINT OU EST CALCULE LE FLUX NORMAL
            COPNFN( 1, K, NUELEM, 1 ) = REAL( GL(1) )
            COPNFN( 2, K, NUELEM, 1 ) = REAL( GL(2) )
            COPNFN( 3, K, NUELEM, 1 ) = REAL( GL(3) )
C
C           LES COMPOSANTES DU VECTEUR NORMAL OU EST CALCULE LE FLUX NORMAL
C           CALCUL DE LA NORMALE: PRODUIT VECTORIEL(DG/DX1,DG/DX2)*-POIDS
            IF( K .EQ. 1 ) THEN
               DN = -1D0
            ELSE
               DN =  1D0
            ENDIF
            COPNFN( 1, K, NUELEM, 2 ) = REAL( DN )
            COPNFN( 2, K, NUELEM, 2 ) = 0
            COPNFN( 3, K, NUELEM, 2 ) = 0
C
C           CALCUL DE DF(BL) AU SOMMET K
            DF = ABS( X(2) - X(1) )
C
C           CALCUL DE DF(BL) ** -1
            DF1 = 1D0 / DF
C
C           D = TRANSPOSE(DN) * COND * ((DF) ** -1)
            D = DN * COND(1) * DF1
C
C           FLUXPT = D * DP SOMMET AU POINT
            DO 10 I=1,NBPOLY
               FLUXPT(I) = D * DPSOMT(MNDPA-1+I)
 10         CONTINUE
C
C           LE FLUX NORMAL AU SOMMET K DE L'EF
            S = 0D0
            DO 20 I=1,NBPOLY
               S = S - FLUXPT(I) * TEMP( NUNDEL(NUELEM,I), N )
 20         CONTINUE
            FLUXNP( K, NUELEM, N ) = S
C
C           LA CONTRIBUTION AU FLUX NORMAL AU POINT NP
            IF( NP .GT. 0 ) THEN
C              SOMMATION DES FLUX AU POINT NP DE LA FRONTIERE
               FLUXTO( NP, N ) = FLUXTO( NP, N ) + S
            ENDIF
C
 90      CONTINUE
C
 100  CONTINUE
C
      RETURN
      END
