      SUBROUTINE TF2LAG( D2PI,   NOAXIS, X,      NDSM,
     %                   NBELEM, NUELEM,
     %                   NTDL,   NBPOLY, NUNDEL, NBPIFN,
     %                   NBPOLA, NPIA,   POIDSA, POLYA, DPOLYA,
     %                   NBCOTE, NOOBLA, NUMILI, NUMALI,
     %                   NOOBSF, NUMISU, NUMASU, LTDESU,
     %                   IDPARE, DPARET, TEMP,   FLUXPT,
     %                   COPNFN, FLUXNP, FLUXTO )
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :     CALCUL DU FLUX NORMAL A CHAQUE ARETE DE L'EF 2D
C -----     LAGRANGE ISOPARAMETRIQUE
C
C ENTREES :
C ---------
C D2PI   : 2 FOIS PI
C NOAXIS : 1 SI PROBLEME AXISYMETRIQUE, 0 SINON
C X      : COORDONNEES RAYON ET COTE DES NBPOLY POINTS DE L ELEMENT
C          OU X Y DES NBPOLY POINTS DE L'ELEMENT
C NDSM   : NOMBRE DE SECONDS MEMBRES
C NBELEM : NOMBRE D'ELEMENTS FINIS DE CE TYPE
C NUELEM : NUMERO DE L'ELEMENT FINI PARMI CEUX DE CE TYPE
C NTDL   : NOMBRE TOTAL DE DL DE TEMPERATURE POUR TOUT LE MAILLAGE
C NBPOLY : NOMBRE DE POLYNOMES = NOMBRE DE NOEUDS DE L'EF
C NUNDEL : NUMERO DES NOEUDS DES ELEMENTS FINIS
C
C NBPIFN : NOMBRE TOTAL DE POINTS SUR LES ARETES DE L'EF OU SONT CALCULES
C          LES FLUX NORMAUX DE CHALEUR   (=NPIA*NBCOTE)
C NBPOLA : NOMBRE DE POLYNOMES DE BASE SUR UNE ARETE DE L'EF
C NPIA   : NOMBRE DE POINTS D INTEGRATION SUR UNE ARETE DE L'EF
C POIDSA : POIDS DES POINTS D INTEGRATION SUR UNE ARETE DE L'EF
C POLYA  : VALEUR DES POLYNOMES DE BASE AUX POINTS D INTEGRATION D'UNE ARETE
C DPOLYA : VALEUR DU GRADIENT DE CES MEMES POLYNOMES AUX POINTS ...
C
C NBCOTE : NOMBRE DES ARETES DE L'EF
C NOOBLA : NUMERO DES LIGNES DES ARETES DE L'EF
C NUMILI : NUMERO MINIMAL DES OBJETS LIGNES
C NUMALI : NUMERO MAXIMAL DES OBJETS LIGNES
C
C NOOBSF : NUMERO DE L'OBJET SURFACE DE CET EF
C NUMISU : NUMERO MINIMAL DES OBJETS SURFACES
C NUMASU : NUMERO MAXIMAL DES OBJETS SURFACES
C LTDESU : TABLEAU DES ADRESSES DU TABLEAU DES DONNEES DE THERMIQUE
C          DES OBJETS SURFACES
C
C IDPARE : IDPARE(K) ADRESSE DANS DPARET DE LA 1-ERE VARIABLE DE
C          L'ARETE K DANS DPARET
C DPARET : DPARET(I,J,L,K)=DPARET(I,J,IDPARE(K)+L)
C          DERIVEE / XI DE LA J-EME FONCTION DE BASE AU L-EME POINT
C          DE LA K-EME ARETE DE L EF DE REFERENCE SURFACE
C
C TEMP   : TEMPERATURE EN TOUS LES NOEUDS DU MAILLAGE
C FLUXPT : TABLEAU AUXILIAIRE DE NBPOLY * NPIA REELS DOUBLE PRECISION
C
C SORTIES:
C --------
C COPNFN : 2 COORDONNEES DES NBPIFN POINTS ET DE LA NORMALE SUR LES
C          ARETES DES EF OU SONT CALCULES LES FLUX NORMAUX DE TEMPERATURE
C FLUXNP : FLUX NORMAL EN LES NBPIFN POINTS DES ARETES DES EF DE CE TYPE
C FLUXTO : FLUX NORMAL SOMME SUR CHAQUE LIGNE DE L'OBJET
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET ANALYSE NUMERIQUE UPMC PARIS     OCTOBRE 1994
C23456---------------------------------------------------------------012
      include"./incl/donthe.inc"
      include"./incl/ctemps.inc"
      include"./incl/cthet.inc"
      include"./incl/cnonlin.inc"
C
      include"./incl/pp.inc"
      COMMON            MCN(MOTMCN)
      REAL              RMCN(1)
      DOUBLE PRECISION  DMCN(1)
      EQUIVALENCE      (MCN(1), RMCN(1), DMCN(1))
C
      DOUBLE PRECISION  D2PI,
     %                  POIDSA(NPIA),
     %                  POLYA(NBPOLA,NPIA),
     %                  DPOLYA(NBPOLA,NPIA),
     %                  FLUXPT(NBPOLY,NPIA),
     %                  TEMP(NTDL,NDSM),
     %                  COND(6),
     %                  DREM(9)
      DOUBLE PRECISION  DF(2,2), DF1(2,2), DN(2), DPARET(*)
      DOUBLE PRECISION  GL(3), DGL(2), DELTA, PROSCD
      DOUBLE PRECISION  D(2), DD(2), S, DGLN
      DOUBLE PRECISION  FLUXTO(NUMILI:NUMALI,1:NDSM),
     %                  FLUXNP(NBPIFN,NBELEM,NDSM)
      REAL              X(NBPOLY,2),
     %                  COPNFN(3,NBPIFN,NBELEM,2)
      INTEGER           NOOBLA(NBCOTE)
      INTEGER           LTDESU(1:MXDOTH,NUMISU:NUMASU)
      INTEGER           NOPOAR(3), NUNDEL(NBELEM,NBPOLY)
      INTEGER           IDPARE(NBCOTE)
C
      NUPTF0 = 0
      DO 100 K=1,NBCOTE
C
C        L'ARETE EST ELLE SUR UNE LIGNE UTILISATEUR?
         NL = NOOBLA( K )
C
C        LE NUMERO DES POINTS DU COTE
         NOPOAR(1) = K
         IF( K .NE. NBCOTE ) THEN
            NOPOAR(2) = K+1
         ELSE
            NOPOAR(2) = 1
         ENDIF
C        LE NUMERO DU POINT MILIEU
         NOPOAR(3) = K + NBCOTE
C
         DO 90 N=1,NDSM
C
C           MISE A ZERO DU TABLEAU DREM
            CALL AZEROD( NBPOLY, DREM )
C
            IF( MNTIME .GT. 0 ) THEN
C              LE TEMPS DU VECTEUR TEMPERATURE N EST MIS DANS LE COMMON CTEMPS
               TEMPS = RMCN(MNTIME+N)
            ENDIF
C
C           LE DEBUT DU TABLEAU DES DERIVEES DES POLYNOMES AUX POINTS
C           D'INTEGRATION NUMERIQUE DE L'ARETE K
            MNDPA = IDPARE( K ) + NBPOLY * NPIA
C
            IF( TESTNL .GE. 1 ) THEN
C              RECUPERATION DE LA TEMPERATURE AUX DL DE L'ARETE K
               MNT = (MNTHDL-1) / 2
               DO 5 I=1,NBPOLA
                  DMCN(MNT+I)= TEMP( NUNDEL(NUELEM,NOPOAR(I)), N )
 5             CONTINUE
            ENDIF
C
            DO 20 L=1,NPIA
C
C              CALCUL DES COORDONNEES DU POINT D INTEGRATION L ET DU JACOBIEN
               CALL E22LAG ( NBPOLY, NBPOLA, NOPOAR ,
     %                      POLYA(1,L), DPOLYA(1,L),
     %                      X, GL, DGL, DELTA )
C              EN SORTIE GL=LES 2 COORDONNEES DU POINT D'INTEGRATION SUR E
C
               IF( TESTNL .GE. 1 ) THEN
C                 CALCUL DE LA TEMPERATURE AU POINT D'INTEGRATION L
                  TEMPEL=PROSCD( POLYA(1,L), MCN(MNTHDL), NBPOLA )
               ENDIF
C
C              RECHERCHE DU TENSEUR SYMETRIQUE DE CONDUCTIVITE AU POINT
C              D'INTEGRATION L DE L'ARETE
               GL(3) = 0D0
               CALL RECOND( 3, NOOBSF, 3, GL,
     %                      LTDESU(LPCOND,NOOBSF), COND )
C
C              LES COORDONNEES DU POINT OU EST CALCULE LE FLUX NORMAL
               NUPTFN = NUPTF0 + L
               COPNFN( 1, NUPTFN, NUELEM, 1 ) = REAL( GL(1) )
               COPNFN( 2, NUPTFN, NUELEM, 1 ) = REAL( GL(2) )
               COPNFN( 3, NUPTFN, NUELEM, 1 ) = 0
C
C              LES COMPOSANTES DU VECTEUR NORMAL OU EST CALCULE LE FLUX NORMAL
C              CALCUL DE LA NORMALE: PRODUIT VECTORIEL(DG/DX1,DG/DX2)*-POIDS
               DGLN  = SQRT( DGL(1) ** 2 + DGL(2) ** 2 )
               DN(1) =  DGL(2) / DGLN
               DN(2) = -DGL(1) / DGLN
               COPNFN( 1, NUPTFN, NUELEM, 2 ) = REAL( DN(1) )
               COPNFN( 2, NUPTFN, NUELEM, 2 ) = REAL( DN(2) )
               COPNFN( 3, NUPTFN, NUELEM, 2 ) = 0
C
C              CALCUL DE DF(BL) AU POINT D INTEGRATION DE L ARETE REFERENCE
               CALL MATJAC( 2, NBPOLY, X, DPARET(MNDPA), DF )
C
C              CALCUL DE DF(BL) ** -1
               CALL DFM1R2( DF, DELTA, DF1 )
C
C              D = TRANSPOSE(DN) * COND
               CALL TABSZD( 1, 2, DN, COND, D )
C
C              DD = D * ((DF) ** -1)
               CALL AB0D( 1, 2, 2, D, DF1, DD )
C
C              FLUXPT = DD * DP ARETE AU POINT
               CALL AB0D( 1, 2, NBPOLY, DD, DPARET(MNDPA), FLUXPT(1,L) )
C
               IF( NL .GT. 0 ) THEN
C                 CONTRIBUTION A L'INTEGRALE NUMERIQUE DU FLUX NORMAL SUR L'ARET
C                 LE POIDS * NORME DU VECTEUR NORMAL A DGL
                  S = POIDSA(L) * DGLN
C                 SI ELEMENT AXISYMETRIQUE PRODUIT PAR 2 * PI * R
                  IF( NOAXIS .NE. 0 ) THEN
                     S = S * D2PI  * GL( 1 )
                  ENDIF
                  DO 10 I=1,NBPOLY
                     DREM(I) = DREM(I) + S * FLUXPT(I,L)
 10               CONTINUE
               ENDIF
C
C              PASSAGE AU POINT D'INTEGRATION NUMERIQUE SUIVANT
               MNDPA = MNDPA + 2 * NBPOLY
 20         CONTINUE
C
C           LE FLUX NORMAL AUX POINTS D'INTEGRATION NUMERIQUE DE CETTE ARETE
            DO 40 L=1,NPIA
               S = 0
               DO 30 I=1,NBPOLY
                  S = S - FLUXPT(I,L) * TEMP( NUNDEL(NUELEM,I), N )
 30            CONTINUE
               NUPTFN = NUPTF0 + L
               FLUXNP( NUPTFN, NUELEM, N ) = S
 40         CONTINUE
C
C           LA CONTRIBUTION AUX FLUX NORMAUX DE L'ARETE K DE L'EF
            IF( NL .GT. 0 ) THEN
               S = 0
               DO 80 I=1,NBPOLY
                  S = S + DREM(I) * TEMP( NUNDEL(NUELEM,I), N )
 80            CONTINUE
C              SOMMATION DES FLUX POUR LA LIGNE FRONTIERE NL
               FLUXTO( NL, N ) = FLUXTO( NL, N ) + S
            ENDIF
 90      CONTINUE
C
C        MISE A JOUR DU NUMERO DU DERNIER POINT OU EST CALCULE LE FLUX NORMAL
         NUPTF0 = NUPTF0 + NPIA
 100  CONTINUE
      END
