      SUBROUTINE VEFLUX( NCAS,   CMFLUX,
     %                   NBPNFX, NEF,    NBELFI, COPNFX, FLUXNP,
     %                   NBFLEC, MXFLEC, XYZDFL, CMMXFL,
     %                   NBAREF, MXAREF, NOAREF, NOPTEF, IERR )
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C BUT :    LISTER LES VECTEURS FLUX NORMAUX DE L'EF 3D NEF
C -----
C
C ENTREES :
C ---------
C NCAS   : NUMERO DU CAS A TRAITER
C NBCAS  : NOMBRE DE CAS TRAITES
C CMFLUX : NOMBRE DE CM POUR L'UNITE DE FLUX NORMAL
C NBPNFX : NOMBRE DE POINTS DE CALCUL DES FLUX NORMAUX POUR 1 EF DE CE TYPE
C NEF    : NUMERO DE L'EF 3D
C NUTYEF : NUMERO DU TYPE DE L'EF de 1 A NBELFI
C COPNFX : (*,*,*,1) 3 COORDONNEES DES POINTS DE CALCUL DES FLUX NORMAUX
C          (*,*,*,2) 3 COMPOSANTES DU VECTEUR NORMAL UNITAIRE AUX POINTS
C FLUXNP : LES FLUX NORMAUX AUX POINTS D'INTEGRATION DES FACES DES EF
C
C SORTIES :
C ---------
C NBFLEC : NOMBRE DE FLECHES FLUX NORMAUX
C MXFLEC : NOMBRE MAXIMAL DE FLECHES FLUX NORMAUX DECLARABLES DANS XYZDFL
C XYZDFL : 1:3 XYZ DU POINT DE DEPART DE LA FLECHE
C          4:6 XYZ DE LA DIRECTION DE LA FLECHE
C          7   DIMENSION EN CM DU TRACE
C              SON SIGNE DETERMINE LE SENS DU TRIANGLE DE LA FLECHE
C CMMXFL : CM DE LA FLECHE MAXIMALE
C NBAREF : NOMBRE D'ARETES DES EF SECTIONNES
C MXAREF : MAXIMUM D4ARETES DES EF SECTIONNES A DECLARER DANS NOAREF
C NOAREF : NO DES 2 SOMMETS DES ARETES DES EF SECTIONNES
C NOPTEF : NO DES POINTS DE L'EF
C IERR   : 1 SI TABLEAU XYZDFL SATURE, 0 SINON
C ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C AUTEUR : ALAIN PERRONNET Laboratoire JL LIONS UPMC Paris Decembre 2006
C....................................................................012
      include"./incl/ponoel.inc"
      REAL              XYZDFL( 7, MXFLEC )
      REAL              COPNFX( 3, NBPNFX, NBELFI, 2 )
      DOUBLE PRECISION  FLUXNP(    NBPNFX, NBELFI, * )
      INTEGER           NOAREF(2,MXAREF), NOPTEF(64)
C
      IERR   = 0
      CMMXFL = 0
C
C     LISTAGE DES VECTEURS FLUX NORMAUX
      DO 10 L=1,NBPNFX
C
C        CONSTRUCTION DU VECTEUR DE FLUX NORMAL
         IF( NBFLEC .GE. MXFLEC ) THEN
            IERR = 1
            RETURN
         ENDIF
         NBFLEC = NBFLEC + 1
C
C        XYZ DU DEBUT DE LA FLECHE
         XYZDFL(1,NBFLEC) = COPNFX(1,L,NEF,1)
         XYZDFL(2,NBFLEC) = COPNFX(2,L,NEF,1)
         XYZDFL(3,NBFLEC) = COPNFX(3,L,NEF,1)
C
C        L'INTENSITE DU FLUX NORMAL EN CE POINT RAMENE EN CM
         FL = REAL( FLUXNP( L, NEF, NCAS ) * CMFLUX )
C
C        LONGUEUR CM DE LA FLECHE DANS LA DIRECTION NORMALE
         CONXCM = COPNFX( 1, L, NEF, 2 ) * FL
         CONYCM = COPNFX( 2, L, NEF, 2 ) * FL
         CONZCM = COPNFX( 3, L, NEF, 2 ) * FL
         XYZDFL(7,NBFLEC) = SQRT( CONXCM**2 + CONYCM**2 + CONZCM**2 )
         CMMXFL = MAX( CMMXFL, XYZDFL(7,NBFLEC) )
C
C        DIRECTION DE LA FLECHE
         XYZDFL(4,NBFLEC) = CONXCM
         XYZDFL(5,NBFLEC) = CONYCM
         XYZDFL(6,NBFLEC) = CONZCM
 10   CONTINUE
C
C     AJOUT DES ARETES DE L'EF SECTIONNE
      IF( NBAREF+NARET .GT. MXAREF ) THEN
         IERR = 2
         RETURN
      ENDIF
      DO 20 K=1,NARET
         NBAREF = NBAREF + 1
C        LE NO DES 2 SOMMETS DE L'ARETE K DE L'EF
         NOAREF(1,NBAREF) = NOPTEF( NOSOAR(1,K) )
         NOAREF(2,NBAREF) = NOPTEF( NOSOAR(2,K) )
 20   CONTINUE
C
      RETURN
      END
